### ISSUE TITLE
Investigate how to continue the streams API work

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10023]
The project from https://github.com/mozilla/pdf.js/projects/4 is completed, but it's likely that we can get additional speed-ups by using the streams API in more places. The following notes were left on the project and may be used for further improvements:

- Wrapper for xhr: We can create a Streams API wrapper for xhr to incrementally read and write data.
- Streams API with MessageHandler: MessageHandler is used for sending OperatorList data from worker thread to main thread. As sending of data only happens when the whole data is parsed, this may cause time and memory inefficiency.

**Comment by apoorv-mishra** [comment]
Anyone working on this currently @timvandermeij ? If not, I would like to pick it up.

**Comment by Snuffleupagus** [comment]
> - Wrapper for xhr: We can create a Streams API wrapper for xhr to incrementally read and write data.

Given that `Fetch` is usually used/preferred to XHR in PDF.js now, the question is if doing that is actually worthwhile at this point in time!?

> - [...] As sending of data only happens when the whole data is parsed, this may cause time and memory inefficiency.

Looking at `RenderPageRequest`/`RenderPageChunk` in the API/Worker, and also how the `OperatorList` is implemented in e.g. https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/src/core/operator_list.js#L575-L583 this part is actually *already* supported, since the API/viewer have supported incremental rendering ever since PR #3461 (back in 2013). Obviously it's certainly possible, and even likely, that this can be made even more efficient, in various ways, by also utilizing the `Stream`s API here as well.
Although I'm not really convinced that this would be a good beginner bug though...

**Comment by timvandermeij** [comment]
Closing since, as indicated above, most of this is already done and the remainder is not really actionable. If the have a clear indication of a spot where the streams API would be beneficial, a separate issue should be opened.
