### ISSUE TITLE
Support regex search

### ISSUE THREAD

**Issue by tk3369** [mozilla/pdf.js#10036]
Hi, great project!  
Currently, pdf.js seems to support exact matches only.  Can it be enhanced with regular expression search function?

**Comment by yurydelendik** [comment]
IMHO is it too complex for end user and hardly adds any value to the demo viewer

**Comment by timvandermeij** [comment]
You could update the find controller (https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js) in a custom build to support this, which is most likely not too difficult because you have the query handling and match calculation logic there, but we don't plan on adding such functionality in the default viewer since most users won't use this.

**Comment by lixaotec** [comment]
That would be a great feature, not for end user, but as api, developers need. I also look foward this behavior.
