### ISSUE TITLE
Investigate why the text layer optimization causes Mochitest failures

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10043]
Refer to #10041. It turns out that this patch caused failures upstream, but it's unclear why.

**Comment by rvandermeulen** [comment]
Some notes from when I was looking into this:
* The failures were appearing as window and docShell leaks.
* This was only happening on Win10 for some reason. It was failing ~80% of the time there, but fine elsewhere.
* Looking at test runtimes, it does appear that in general, the tests were running more slowly on affected builds vs. ones without that change (5-10% longer runtime). I didn't do any sort of scientific analysis on that, though.

Ultimately, I suspect this is some sort of timing issue with the test harness. It's possible there's a real perf regression caused by this change, which in turn had a negative on shutdown timings, causing the leak detector to see those windows as leaked. Or something :-)

I was also thinking this could be something to throw at roc's Pernosco tool to see if it can be reproduced in rr in chaos mode (it's had success reproducing test failures in the past which were previously limited to one specific platform).

**Comment by timvandermeij** [comment]
Looking at this again, I'm really not sure how to proceed with this. Since it happened a while ago and seems to me like an upstream test harness issue, perhaps we should just try landing it again, since I do think the original patch is helpful?

**Comment by Snuffleupagus** [comment]
> [...] perhaps we should just try landing it again, since I do think the original patch is helpful?

Honestly, I was never really that happy about the patch since it felt too much like a hack (and it only fixed a *single* known issue). There was also at least *one* bug in the original implementation, see https://github.com/mozilla/pdf.js/pull/10041#pullrequestreview-152741467, and the way that it changes when flushing occurs does strike me as potentially risky (given the amount of async-ness in this part of the code-base).

All in all, it may be better to come up with a different patch in order to address that issue.

**Comment by timvandermeij** [comment]
Alright. Let's close this issue then because it's not actionable anymore. If we need additional text layer fixes, they can be done in a new issue/PR. Thanks!
