### ISSUE TITLE
Potentially improve performance of web reader using Intersection Observer API

### ISSUE THREAD

**Issue by dmisdm** [mozilla/pdf.js#10059]
Would it be possible that the new Intersection Observer API could improve performance of the web reader?
https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API#Browser_compatibility

My logic is that this would remove the need to listen to scroll events, which would reduce or completely remove any scroll lags/jumps due to less blocking of the main thread/loop, but is only a hypothesis.

Although it's not widely supported yet (https://caniuse.com/#feat=intersectionobserver) it could still be beneficial i think.

**Comment by timvandermeij** [comment]
Interesting find. If we can feature-detect this, we might be able to fall back to the current scroll event handling for older browsers such as IE.

**Comment by JohannesNaegele** [comment]
Could this maybe help solving this [issue](https://stackoverflow.com/questions/59761142/pdf-js-viewer-extension-is-laggy) (just my private extension)?

**Comment by ewheelerinc** [comment]
This could fix an issue in 2.4.246: When we load a large PDF and then scroll to the bottom by dragging the scroll-bar slider it takes forever to load the last page.  However, if I just press "END" on my keyboard, it goes to the last page and loads quickly.   

I'm guessing that it is trying to load pages in order that they are viewed.  If so, then this could be fixed by the Observer API or waiting a "dwell time" before rendering on mouse move.  The dwell time could probably be 10ms since I didn't dwell on any but the last page when I scrolled quickly by dragging the scroll bar to the bottom with my mouse.

**Comment by dmisdm** [comment]
> This could fix an issue in 2.4.246: When we load a large PDF and then scroll to the bottom by dragging the scroll-bar slider it takes forever to load the last page. However, if I just press "END" on my keyboard, it goes to the last page and loads quickly.
> 
> I'm guessing that it is trying to load pages in order that they are viewed. If so, then this could be fixed by the Observer API or waiting a "dwell time" before rendering on mouse move. The dwell time could probably be 10ms since I didn't dwell on any but the last page when I scrolled quickly by dragging the scroll bar to the bottom with my mouse.

@ewheelerinc I think you're on the money! That sounds like an issue that could be fixed using something like a debouncer (dwell time) on the function that adds pages to the render queue, and i actually think theres a high chance that even if you use the intersection observer you'll still have this problem, given that the events look something like this as you scroll along:
- queue page 1
- queue page 2
- queue page 3
- queue page 4
...
- queue page 241
- queue last page

...Then, asynchronously (not necessarily after queing the last page has finished):
- start render page 1, is it visible? nope, cancel
- start render page 2, is it visible? nope, cancel
- start render page 3, is it visible? nope, cancel
- start render page 4, is it visible? nope, cancel
...
- start render page 241, is it visible? nope, cancel
- start render last page, is it visible? yes!, continue rendering loop.

If intersection observer was to be used, you'd still have the same queing process, only it won't be done through scroll events + position calculations.

So, as you say, dwell time (or debouncing) on the adding of pages to the queue might be the best way i think :)...however there may be a very valid reason for it not being there in the first place.
https://lodash.com/docs/#debounce

Dealing with timing of events can be tricky, especially in a codebase like this where it's highly dependent on tests to pick up faults.

Also if my assumptions about the rendering algorithm are wrong maybe this isn't the way to go!

**Comment by Snuffleupagus** [comment]
Considering that the [Intersection Observer API](https://developer.mozilla.org/en-US/docs/Web/API/Intersection_Observer_API) is, as far as I can tell, only *asynchronous* it's difficult to see how it would help the PDF.js viewer in general since there's *numerous* cases where we (for various reasons) need to be able to get e.g. the currently visible pages *synchronously*.
Note also that e.g. the [`watchScroll` helper function](https://github.com/mozilla/pdf.js/blob/3d80c21a8e5583c0594b2d5e039f3eab65e09975/web/ui_utils.js#L171-L211) is already debouncing scroll events.

Given that https://github.com/mozilla/pdf.js/issues/10059#issue-358851432 doesn't provide any measurements of *potential* performance improvements, and that the `getVisibleElements` functionality simply *cannot* be removed (as mentioned above); this issue unfortunately doesn't seem all that actionable as-is and I'd suggesting closing it as WONTFIX. /cc @timvandermeij 

---

The problem described in https://github.com/mozilla/pdf.js/issues/10059#issuecomment-628325083 seem pretty much orthogonal to this issue as filed, and *this* issue doesn't seem like the correct place for that discussion, however those problems should generally have been fixed by PR #11106.
Possible another explanation could be that the viewer was *relatively* positioned, which is not currently supported (and already tracked elsewhere), since that could lead to the sort of issues described (which is why the viewer now fails to load in those circumstances).
