### ISSUE TITLE
How to extract text and keep their semantics? 

### ISSUE THREAD

**Issue by Jun711** [mozilla/pdf.js#10073]
I found an example on how to extract text on a [StackOverflow thread](https://stackoverflow.com/questions/17424639/extract-text-from-pdf-file-using-javascript)

This is the [example code](http://git.macropus.org/2011/11/pdftotext/example/) linked on the thread

But, it just grabs all the text without keeping the semantics. I wonder if there is a API method that is provided by pdf.js to extract text semantically?  

Thanks

**Comment by timvandermeij** [comment]
The `getTextContent` API (refer to https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js#L45 for a usage example) can only give you the text content of a single page, but there are no more semantics. This is mainly because in the PDF format text is just a series of glyphs and positions and in general no more information is included. Exceptions are tagged PDFs, which we don't support yet but we do track the support in #6269.
