### ISSUE TITLE
Can I get html file of rendered pdf?

### ISSUE THREAD

**Issue by taizan** [mozilla/pdf.js#10077]
Thanks for great project.
Maybe that is not main task of pdf.js, I want to host the rendered pdf as html and enable annotation on it in internal network.
Can I get html or DoM file of rendered pdf ?

**Comment by timvandermeij** [comment]
The pages are rendered onto canvases, so they are images instead of HTML. You can convert the canvases to PNG format (see https://github.com/mozilla/pdf.js/tree/master/examples/node/pdf2png) so you can host the rendered versions elsewhere. However, that won't give you the text/annotation layer, which PDF.js renders separately in HTML. Perhaps you could get those by saving the HTML content of the rendered PDF in the browser, but this is really out of scope for the project.
