### ISSUE TITLE
examples not work

### ISSUE THREAD

**Issue by gwl002** [mozilla/pdf.js#10081]
https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js
I follow the example in up link.But why I cannot find the pdfjsViewer constructor.
`var pdfPageView = new pdfjsViewer.PDFPageView({
      container: container,
      id: PAGE_TO_VIEW,
      scale: SCALE,
      defaultViewport: pdfPage.getViewport(SCALE),
      // We can enable text/annotations layers, if needed
      textLayerFactory: new pdfjsViewer.DefaultTextLayerFactory(),
      annotationLayerFactory: new pdfjsViewer.DefaultAnnotationLayerFactory(),
    });`
Is that mean the examples is not in line with the new version?
Another issue,
`pdfjsLib.GlobalWorkerOptions.workerSrc =
  '../../node_modules/pdfjs-dist/build/pdf.worker.js';`
GlobalWorkerOptions is not defined

**Comment by Snuffleupagus** [comment]
That example works for me, and with the (currently) lack of any details it's basically impossible to tell know why you weren't able to get it to work. You'll need to provide *detailed* information about *exactly* what steps you took, since otherwise no one will be able to help and the issue will be closed as incomplete.

**Comment by Snuffleupagus** [comment]
That example works for me, and with the (current) lack of any details it's basically impossible to tell why you weren't able to get it to work. You'll need to provide *detailed* information about *exactly* what steps you took, since otherwise no one will be able to help and the issue will be closed as incomplete.

**Comment by timvandermeij** [comment]
Most likely you did not run `gulp dist-install` before opening the example. As indicated above, you'll need to provide more information about the exact steps taken for us to be able to help.
