### ISSUE TITLE
GhostScript security issue

### ISSUE THREAD

**Issue by jlballonv** [mozilla/pdf.js#10097]
Based on reported [GhostScript vulnerability](https://www.kb.cert.org/vuls/id/332928).

Is it planned to upgrade GhostScript from 8.63 to [9.24](https://ghostscript.com/doc/9.24/History9.htm#Version9.24) version that already solves the security issue?

**Comment by brendandahl** [comment]
Is this filed in the right project, we don't use GhostScript in pdf.js?

**Comment by timvandermeij** [comment]
I don't think this is filed for the right project because we don't use GhostScript at all. Note that we have our own PostScript parser for (a subset of) PostScript; see https://github.com/mozilla/pdf.js/blob/master/src/core/ps_parser.js. Closing since this should not be an issue for us, but if you think there is anything we need to do on our side please provide more information and we can reopen this.

**Comment by jlballonv** [comment]
Thanks for the clarification.
