### ISSUE TITLE
Can't resolve '/util' with webpack react app

### ISSUE THREAD

**Issue by vldrsk** [mozilla/pdf.js#10118]
My app show this error and don't want to render component
![default](https://user-images.githubusercontent.com/25148010/46278995-9022aa00-c570-11e8-8299-adc2f0bcadb7.png)

As i found working example, your lib imports in such way 
![default](https://user-images.githubusercontent.com/25148010/46279048-b7797700-c570-11e8-906c-2c17ede1b162.png)

And after import i just console.log this variable, but caught this error. I added lib as yarn add pdfjs-dist

**Comment by timvandermeij** [comment]
Could you share a runnable example on e.g., JSBin or another server so we can take a look? It's not possible to find the issue from screenshots and snippets alone.

**Comment by vldrsk** [comment]
Sorry, but project is huge, cant move it to jsbin.
There i try to use it 
![default](https://user-images.githubusercontent.com/25148010/46330694-f95ff700-c61c-11e8-9230-08ccee3c72d9.png)

And there node module
![default](https://user-images.githubusercontent.com/25148010/46330711-13013e80-c61d-11e8-85ae-a33594d3966f.png)

I had same issue with other modules and there i just missed with module import. Which is correct way to import variables from library?

**Comment by timvandermeij** [comment]
The usage you're looking for is most likely https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js#L6 if you're using Webpack or https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js if you're using the components. I can only suggest to look at the examples in the https://github.com/mozilla/pdf.js/tree/master/examples folder for how to use it since from just the screenshots we cannot provide more information.
