### ISSUE TITLE
Print original PDF without header and footer

### ISSUE THREAD

**Issue by pankajmehra009** [mozilla/pdf.js#10125]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version:
- PDF.js version: 1.9.426
- Is a browser extension:No

Steps to reproduce the problem:
1. Using blob PDF
2. Testing the viewer.html in browser embedding the blob pdf in test html page
3. Print the pdf using print option from viewer html menu.
4. The header includes unwanted Date and Title (PDF name) and footer has the file path.

What is the expected behavior? 
PDF should be print as original PDF viewed in the viewer.

What went wrong? 
Extra details in header and footer [ Date and Title (PDF name), file path] 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * Web browser and its version: Chrome
>
> Extra details in header and footer [ Date and Title (PDF name), file path]

That's a browser limitation, since it's not generally possible[1] to control such printing features using JavaScript/CSS; hence this issue is probably wontfix/invalid.

---
[1] With the exception of Firefox, which has the `mozPrintCallback` API that allows (slightly) greater control over the printing output.
