### ISSUE TITLE
Odd permissions in release zip files

### ISSUE THREAD

**Issue by The-Compiler** [mozilla/pdf.js#10132]
Looking at `pdfjs-1.10.100-dist.zip` and `pdfjs-2.0.550-dist.zip` from the releases page, the files therein have quite weird permissions set.

Some files have 644 (`-rw-r--r--`) permission which is reasonable, but e.g. most files in `web/images/` have 650 permission (`-rw-r-x---`). In other words, when e.g. creating a distribution package for PDF.js, those files will be unreadable for anyone except root. Usually, that kind of thing is only done for files with sensitive information such as passwords. Due to that, @Foxboron had to [patch](https://git.archlinux.org/svntogit/community.git/commit/trunk?h=packages/pdfjs&id=e689c2b9841f3602ff6fcbb387ef58c0fc2774f8) the Archlinux package.

When I run `gulp publish` myself, the files seem to get the expected 644 permissions - so I'm not sure what's going on. Maybe whoever is building the releases has a restrictive umask set?

**Comment by timvandermeij** [comment]
Could you verify if this is still the case for the latest release at https://github.com/mozilla/pdf.js/releases? This time I made the release and I just ran `gulp publish`, so it should be fine now.

**Comment by The-Compiler** [comment]
Indeed, v2.0.943 looks good to me! However, if @brendandahl still does releases in the future, it might be good to figure out what's different there, I guess?

**Comment by timvandermeij** [comment]
I think this may have been fixed by recent package upgrades. For version 2.0, we upgraded (among others) the `gulp-zip` dependency, which is used during the `publish` build target. This may have changed how the permissions are set. Otherwise, perhaps something had to be fixed manually before which altered the permissions, but from now on the procedure is that the `publish` target is used for a release, so this should be fixed now.
