### ISSUE TITLE
Proposal: concatenate blocks close to each other

### ISSUE THREAD

**Issue by hugocaillard** [mozilla/pdf.js#10154]
I recently used PDF.js to extract data from PDFs. In some cases I found that some texts items were split (when they were "close" or on the some line). I therefore tried to figure out a way to merge these blocks.

For exemple, let's say we have the sample data 
Note: `x` and `y` are extracted from the transform matrix for simplification

```js
[
  {
    "str": "3",
    "width": "20",
    "height": "30",
    "x": "10",
    "y": "10",
  },
  {
    "str": "14159",
    "width": "50",
    "height": "30",
    "x": "31",
    "y": "10",
  }
]
```

And the expected output

```js
[
  {
    str: "3,14159", // data[0].str + data[1].str
    width: "70",    // data[0].width + data[1].str
    height: "30",   // data[0].height
    x: "10",        // data[0].x
    y: "10",        // data[0].y
  }
]
```

Here was my first simple solution
```js
/**
 @param {TextContent} data
 @param {number} delta
*/
function concatblocks(data, delta) {
  // group by block on the same line
  // could be 'x' if dir is ttb
  const grouped = groupBy('y', data) 

  return Object.entries(grouped)
    .map(([y, blocks]) => {
      return sortBy('x', blocks).reduce((acc, current) => {
        const previous = last(acc)
        
        // first iteration returns the first item
        if (!previous) return [current]

        const left = previous.x + previous.width
        const right = current.x

        // if they are close enough
        // replace the previous block
        if (right - left < delta) {
          return acc.slice(0, acc.length - 1).concat({
            txt: `${previous.txt}${current.txt}`,
            width: current.width + previous.width,
            height: current.height,
            x: left + current.width,
            y: current.y,
          })
        }

        // do nothing, just add the block to the array
        return acc.concat(current)
      }, [])
    })
    // flatten everything back together
    .reduce((acc, blocks) => [].concat(acc, blocks), [])
}
```

I then add the option to pass a predicate function that could offer more flexibility, here's part of the code
```js
/**
 @param {TextContent} data
 @param {number} delta
 @param {function} predicate 
*/
function concatblocks(data, delta, predicate) {
  return Object.entries(groupBy('y', data)).map(([y, blocks]) =>
    sortBy('x', blocks).reduce((acc, current) => {
      // ...
      // *** RELEVANT PART
      const isValid = predicate ? predicate(left, right) : true

      if (isValid && right - left < delta) {
        return acc.slice(0, acc.length - 1).concat({
          txt: `${previous.txt}${current.txt}`,
          // ...
        })
      }
    }, [])
  )
}

// usage, for instance merging only they are both number
concatBlocks(
  textContent,
  50,
  (left, right) => !isNaN(left.txt) && !isNaN(right.txt)
)
```

The `delta` could also be handle by a default predicate.

Would it be nice if it a was part of PDF.js, as an option of `getTextContent()`? I'd be happy to open a PR if so. Just wanted to discuss it first.

**Comment by Snuffleupagus** [comment]
Trying to combine text runs is a somewhat difficult problem in general, as can be seen from the various open issues tagged with `4-text-selection`.
One of the reasons for the difficulty is the various writing modes that exist in PDF files, i.e. left-to-right, right-to-left, and top-to-bottom. Another problem is that text in PDF files is *very often* absolutely positioned, which creates the need to try and insert spaces between words. Hence there's a risk that what you're suggesting could have a somewhat though time dealing with various edge-cases, and thus this probably isn't something that could/should be used by default.

There's also the question of who will use this kind of feature, since historically there's been some reluctance to add code/functionality that unused in the default API/viewer. The reason is that while it's often (fairly) easy to add code, however it then has to be both maintained and tested which is something that takes time and resources. (Once a feature is added, there's often little choice except to keep supporting it.)
*In closing:* While the suggested changes may be useful in *certain* situations, it's not really clear if the general library benefits from it in my opinion.

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX, for the reasons outlined in https://github.com/mozilla/pdf.js/issues/10154#issuecomment-429613480.
