### ISSUE TITLE
PrintService in pre-build version

### ISSUE THREAD

**Issue by benjhoo** [mozilla/pdf.js#10164]
Hi,
I'm using the pre-build version of pdf.js (installed via npm) in my project to display pdf in my webpages. This works well.

Now I would like to print only the pdf with an external button, but it seems this pre-build version doesn't implement the PrintService. Am I wrong ?

If not, is it possible to easily add the print component to this version or should I edit and compile again the entire pdf.js project ?

Thanks

**Comment by timvandermeij** [comment]
You're correct that this is not in the pre-built version from NPM since it only contains the parts necessary to render PDF files, i.e., it does not provide all functionality that the generic viewer has because most custom applications don't need that at all or only need a small subset. You can, however, use the functionality from the generic viewer in your own viewer. You can find the printing code here, but it may require some adaptations in order to fit in your project: https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js

**Comment by AlexandrosG** [comment]
@benjhoo Were you able to figure this out? I'd like to do the same but using Angular via a custom pdf viewer component that I built but had no luck so far hooking up the print service.

**Comment by benjhoo** [comment]
@AlexandrosG Unfortunately, I didn't succeed in developing a custom pdf viewer which implements the PrintService component.

What I did : I used the npm pre-build version and made a css hack with javascript to print only the pdf canvas when the user decides to print the entire page.
It's not the best solution but it works.

Example : https://codepen.io/DenisDov/pen/yMEXGV
