### ISSUE TITLE
Investigate upgrading Gulp, Webpack and Node.js dependencies

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#10177]
From #10176:

```
Webpack is pinned because versions higher than this cause the viewer not
to work (see https://github.com/mozilla/pdf.js/pull/10170#issuecomment-431697032).

Node.js is pinned for Travis CI because version 11 requires that we
update to Gulp 4.
```

**Comment by Snuffleupagus** [comment]
> Webpack is pinned because versions higher than this cause the viewer not to work (see https://github.com/mozilla/pdf.js/pull/10170#issuecomment-431697032).

The problem is that Webpack, starting from version `4.22.0`, is now *parsing* the entire
```javascript
typeof __non_webpack_require__ !== 'undefined'
```
expression during the build process, causing the above line to be reduced to `true`.
The expected, and previous output, is that `__non_webpack_require__` is replaced with `require` as
```javascript
typeof require !== 'undefined'
```

According to the documentation, this *should* still work; see https://webpack.js.org/api/module-variables/#__non_webpack_require__-webpack-specific-

If someone has time (since a reduced test-case might be needed), this should be reported to https://github.com/webpack/webpack/issues

**Comment by Snuffleupagus** [comment]
Was the Webpack regression described in https://github.com/mozilla/pdf.js/issues/10177#issuecomment-441279491 ever reported upstream, or has it perhaps already been fixed in a later release?

(You could probably hack around this on the PDF.js side, by using e.g. `PDFJSDev.eval` or similar, but that would IMHO be a last resort if the Webpack regression isn't fixed.)

**Comment by timvandermeij** [comment]
I tried the latest release and it isn't fixed yet, nor do I really know how to report this in a way that it's actionable for upstream because I don't know that much about this part of the codebase to reduce it to a minimal example.

**Comment by timvandermeij** [comment]
I have filed an upstream issue for this bug at https://github.com/webpack/webpack/issues/8829. If that is fixed, we can remove the workaround. Tracking this upstream now.
