### ISSUE TITLE
Not able to access page.objs.objs.img_p1_1.data even when promise is already resolved

### ISSUE THREAD

**Issue by Rhuansantos** [mozilla/pdf.js#10174]
Configuration:
- Web browser and its version: Chrome Version 68.0.3440.106 (Official Build) (64-bit)
- Operating system and its version: macOS High Sierra V 10.13.6
- PDF.js version: 2.0.550
- Is a browser extension: No

Steps to reproduce the problem:
```
   await import('pdfjs-dist')
     .then((pdfJs) => {
       pdfJs.GlobalWorkerOptions.workerSrc = './pdf.worker.min.js'; 
       this.setState({ PdfJsLib: pdfJs });
     })
   const pdf = await this.state.PdfJsLib.getDocument(this.props.file);
   const page = await pdf.getPage(this.props.page);
   const pageWidth = page.view[2];
   const pageHeight = page.view[3];
   const normalizeCoordinates = Math.min(
      page.objs.objs[`img_p${pageNum - 1}_1`].data.width / pageWidth,
      page.objs.objs[`img_p${pageNum - 1}_1`].data.height / pageHeight,
    );

```

What is the expected behavior? (add screenshot)
Get original document properties through pdf.objs.objs.img_p1_1.data

What went wrong? (add screenshot)
Object undefined

**Comment by timvandermeij** [comment]
Did you try logging the available objects in `page.objs.objs`? Otherwise, please provide a link to a runnable version (on JSFiddle, JSBin or your own server) as asked for in the issue template since it's hard to help with just a code snippet.

**Comment by Rhuansantos** [comment]
@timvandermeij , sorry I could not provide the link since it is a huge project and it's running on React Js. I was able to read the property after page.render(). looks like objs.objs.img_p1_1.data it's defined after we call page.render().
Would be nice if the property it's available before we pass the render context to the page.render() function because what about if I need to use the original page properties on my canvas context?

Thank you!

**Comment by timvandermeij** [comment]
The image data is only available after rendering because then the actual parsing of the data happens. This is not done beforehand because it's also possible to load page data without rendering the page itself, for example to find out the dimensions of the page since this comes from metadata in the PDF file. The rendering operation actually gets the data for things like images on the page. Closing as answered since we cannot fix this without loading the page content, which should only happen when rendering.
