### ISSUE TITLE
error:Invalid or damaged PDF file

### ISSUE THREAD

**Issue by 1120892638** [mozilla/pdf.js#10199]
Hello, iOS loads the PDF address with pdf. js. There are two electronic signatures in it, but they can only be displayed for the first time, and they can't be loaded later (hint: Invalid PDF structure). If only an electronic signature PDF can be loaded every time, how can I solve this problem?

**Comment by timvandermeij** [comment]
It looks like the PDF is corrupted or it's not served correctly (try opening it with https://mozilla.github.io/pdf.js/web/viewer.html), but it's impossible to tell without the actual PDF file as requested in the issue template. Please take care of filling out the entire issue template when you make an issue, otherwise it's not actionable for us.

**Comment by 1120892638** [comment]
thanks for reply, like this pdf  'http://testfile.douziit.com/carchain/sign/1541040722327.pdf'  only load once and then load faild

**Comment by timvandermeij** [comment]
It loads just fine for me in the default viewer, so either a viewer modification is causing this or the server is intermittently not serving the file correctly. You can verify by checking the status of the PDF request in the network tab of the console.
