### ISSUE TITLE
pdf.js coding quote

### ISSUE THREAD

**Issue by daverad525** [mozilla/pdf.js#10210]
Hello all.
I have a client that is looking to get a quote for a custom pdf.js plugin for Wordpress.  I was recommended to come to this site by someone in this community.  Is this the appropriate space to ask?  If not, please direct me to the appropriate url to ask this question to pdf.js coders.

Thanks

**Comment by timvandermeij** [comment]
This issue tracker is only meant for development of the PDF.js library itself, not for third-party plugin development. I think you should ask this in the Wordpress developer community since I don't think anyone here has experience with this. You could also try asking on IRC (irc.mozilla.org, #pdfjs channel).
