### ISSUE TITLE
Pdf.js is not rendering the large size pdf files

### ISSUE THREAD

**Issue by Menalish** [mozilla/pdf.js#10236]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 63
- Operating system and its version: windows 7 and 10
- PDF.js version: Latest
- Is a browser extension:

Steps to reproduce the problem:
1. Attach 250 MB file
2. It’s keep loading and it’s not rendering..

What is the expected behavior? (add screenshot) It should be rendered for large file sizes too 

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Menalish** [comment]
What is maximum file pdf js render engines supports?

**Comment by timvandermeij** [comment]
It completely depends on a few factors:

- Is the PDF file linearized (optimized for web)? If so, then the first few pages can already be rendered without fetching the entire file.
- Is the PDF file served with range requests enabled on the server? If not, then the entire file must be downloaded before rendering can start.
- Does the file contain huge images? This can slow down PDF.js considerably since canvas tiling is not yet implemented.

Refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize for more information about optimizing PDF files. In general I would say that 250 MB files are challenging to say the least, but with the optimizations above it should be doable I think.
