### ISSUE TITLE
Low quality of document in PDFViewer.

### ISSUE THREAD

**Issue by eugeniipol** [mozilla/pdf.js#10251]
The PDF document loading in low quality and there is no reload after zoom, so text and pictures stays in a low quality. Only in Chrome (70.0.3538.77) and Opera (56.0.3051.36).

**Comment by timvandermeij** [comment]
Please provide all information from the issue template (https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) in order for this to be actionable. In particular, is this using the Chrome add-on or does it also happen with https://mozilla.github.io/pdf.js/web/viewer.html?

**Comment by timvandermeij** [comment]
Closing until the information is provided.

**Comment by timvandermeij** [comment]
I checked the screenshots and it looks like it's a custom version of PDF.js that just doesn't implement the zooming correctly. Instead of re-rendering the page, it seems to perform CSS zooming, which makes the text illegible. Is the `useOnlyCssZoom` option perhaps enabled? Otherwise, you must implement zooming according to how the default viewer does, i.e., by calculating the new zoom factor and re-rendering the canvas with the new zoom factor accordingly. Since this is a third-party implementation, there is not much more we can do here.
