### ISSUE TITLE
Memory comsumption when rendering number of pdfs one after another

### ISSUE THREAD

**Issue by quarryman** [mozilla/pdf.js#10260]
Attach (recommended) or Link to PDF file here:
is not related to particular pdf
Configuration:
- Browser: Chrome: 70.0.3538.77 (Official Build) (64-bit)
- Operating system and its version: MacOS Mojave
- PDF.js version: 3.0.5
- Is a browser extension: no

Steps to reproduce the problem:
1.Render 50-100 pdfs one after another
2.Record memory usage profile
3.Sort by memory usage

What is the expected behavior? 

What went wrong? 
![screen shot 2018-11-15 at 14 19 55](https://user-images.githubusercontent.com/1093040/48553492-646f3f80-e8e4-11e8-9139-0201e2a6922f.png)

79% of memory consumed by application is due to MessageHandler._onComObjPOnMessage method, which sends data from pdf worker to app (as far as I understand)

after 100 documents rendered (not more then 10 pages each) one after another, memory consumption grows up to 500Mb from 60 at app start before rendering.

Can this be considered memory leak?

**Comment by Snuffleupagus** [comment]
> Can this be considered memory leak?

No, not unless you're actually destroying the loadingTask before opening each new PDF file, which the STR above doesn't mention, refer to: https://github.com/mozilla/pdf.js/blob/960213cb6963f9bf46d6224805de2dc73fef0af4/src/display/api.js#L481-L498

**Comment by quarryman** [comment]
Thanx you, @Snuffleupagus 
I am using react-pdf wrapper, so must clarify how it utilizes destroy API.

Is it right that we MUST call destroy() to avoid memory consumption and if we dont it may lead to situation above?

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.0.5

Please note that no such version exists, the latest stable one as of this writing is `2.0.943`; please see https://github.com/mozilla/pdf.js/releases

> I am using react-pdf wrapper,

It's (obviously) not possible for the PDF.js project to provide direct support for third-party libraries that are using/embedding the PDF.js library in various ways.

> Is it right that we MUST call destroy() to avoid memory consumption and if we don't it may lead to situation above?

Yes. Basically, there's two conditions that need to be met in order for this issue to be considered valid from the point of the PDF.js project:
 - The loadingTask *must* be `destroy()`-ed in order to clean-up various resources, both on the main- and worker-threads.
 - The issue must be possible to replicate using just the standard PDF.js library *directly*, to rule out the possibility that a third-party library somehow keeps some data alive unexpectedly.

**Comment by quarryman** [comment]
Thanx for clarification, @Snuffleupagus
Asked for details to be able to create react-pdf issue as I was not sure I can deliver right info to their team.
