### ISSUE TITLE
how  to set the initial page number when open file PDF. 

### ISSUE THREAD

**Issue by nhuemne2012** [mozilla/pdf.js#10265]
I have a list page number. How to view page number any when open file PDF online. Thanks

**Comment by timvandermeij** [comment]
If you're using the viewer components, you can use the `getPage` API; refer to https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L35. Otherwise, if you're using the default viewer, you can use https://github.com/mozilla/pdf.js/blob/3770073955066c7100b8e455fb6f3e01c199dbe8/web/base_viewer.js#L207.
