### ISSUE TITLE
Range Requests are not sent

### ISSUE THREAD

**Issue by alienhsu** [mozilla/pdf.js#10286]
1. we have 2 servers , one is app server , the other is file server; the two server are diff origins;
2. when we get the file from the app server , we find  that range request are sent ;
3. but if we try to load the file from the file server(diff origins), just full file request is sent.
4. the file server support cors and range request ;
5. when i debug the code that i find it can not get the response header ,for example content-length ,even if  the actual response return all headers which pdf js need for range request;

so may i know what can i do that let pdf.js support range request with the file server ?

**Comment by alienhsu** [comment]
i use the demo https://mozilla.github.io/pdf.js/web/viewer.html to try , but get the same result.

**Comment by timvandermeij** [comment]
It's not possible to tell from this description alone without having access to said servers, but if the server handles range requests correctly it should work for both. Therefore it looks like there is some difference in the range requests configuration for the file server. Since you mentioned a different origin, perhaps https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr is relevant. Closing since there is not much more we can do with this limited information.
