### ISSUE TITLE
pdfjsLib undefined

### ISSUE THREAD

**Issue by eucliwoodv** [mozilla/pdf.js#10283]
Configuration:
- Firefox Quantum 62.0 64 bits
- Windows 7 Enterprise
- PDF.js version: 2.0.943 

I´m using JavaScript and I set pdfjsLib correctly:
![imagen](https://user-images.githubusercontent.com/44077167/48847364-f6ed6400-ed66-11e8-98bc-393074f5df33.png)

When I try to view pdf, It isn't show and catch this error, but I don't know what happend, a few days works good  

![imagen](https://user-images.githubusercontent.com/44077167/48846819-9dd10080-ed65-11e8-8d91-6eea45407c64.png)

**Comment by timvandermeij** [comment]
I don't think you can use the `window` object that way. Moreover, it's not recommended to set the worker source to our demo build since it can be unstable and doesn't match the version of `pdfjs-dist` you're using. You most likely want something like https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js#L6 or https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js#L26.
