### ISSUE TITLE
How to use pdfviewer with react?

### ISSUE THREAD

**Issue by AOQNRMGYXLMV** [mozilla/pdf.js#10303]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 70.0.3538.102
- Operating system and its version: Windows 10
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. import pdf.js:
```
import * as PDFJS from 'pdfjs-dist/webpack';
import { PDFViewer as pdfViewer } from 'pdfjs-dist/web/pdf_viewer';
```
2. create a react class component name PDFViewer:
```
export class PDFViewer extends React.Component {
    constructor(props) {
        super(props);

        this.containerRef = React.createRef();
    }

    componentDidMount() {
        this.pdfViewer = new pdfViewer({
            container: this.containerRef.current
        });
    }

    render() {
        return (
            <div ref={this.containerRef}></div>
        )
    }
}
```

What is the expected behavior? (add screenshot)
Then it's expected to be a blank component.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/11152675/49020687-0982f580-f1cc-11e8-86d7-92235c181762.png)
I can't understand what error it is.

**Comment by timvandermeij** [comment]
Take a look at the stack trace. It complains about the `_resetView` method in the `BaseViewer` class. This clears the text content in the viewer at https://github.com/mozilla/pdf.js/blob/3770073955066c7100b8e455fb6f3e01c199dbe8/web/base_viewer.js#L535. `this.viewer` is indeed `null` since you did not provide it in `componentDidMount`; refer to https://github.com/mozilla/pdf.js/blob/3770073955066c7100b8e455fb6f3e01c199dbe8/web/base_viewer.js#L141-L142 for the options you have to pass in.

**Comment by awesomesunil** [comment]
how to pass a url to view the pdf ?
