### ISSUE TITLE
publish es6 modules to npm

### ISSUE THREAD

**Issue by robrez** [mozilla/pdf.js#10317]
I was looking to use pdf.js today via something like `import {pdfjs} from pdfjs-dist/pdf.js` and learned that all that is available is a require module.

Would it be possible to add es6 modules somewhere on npm?

**Comment by bennypowers** [comment]
In an ideal world, `src` should be refactored as standard modules. If CJS is still needed, it could be automatically built (say, in a `cjs` directory) using rollup or other similar tools, or better yet - left up to the user to generate (node users could easily use the [`esm`](https://github.com/standard-things/esm) module to enable es module syntax in node apps). That would allow library users to choose if, when, and how to bundle or transpile.

If there's interest, I'd be happy to provide a PR.

**Comment by amundo** [comment]
Is this  the bundled-es-modules/pdfjs-dist repo still relevant or has module functionality been rolled into this main distribution? There seem to be “components” in this repo.

**Comment by daKmoR** [comment]
the published `pdfjs-dist` still seems to not have es modules?
- https://unpkg.com/browse/pdfjs-dist@2.1.266/build/pdf.js => UMD
- https://unpkg.com/browse/pdfjs-dist@2.1.266/lib/pdf.js => commonjs

or is there another distribution somewhere?

**Comment by xiaoxiangmoe** [comment]
@timvandermeij any update on this


```
node_modules/ng2-pdf-viewer/__ivy_ngcc__/fesm2015/ng2-pdf-viewer.js depends on 'pdfjs-dist/build/pdf'. CommonJS or AMD dependencies can cause optimization bailouts.
```

**Comment by rondonjon** [comment]
@bennypowers:

> If there's interest, I'd be happy to provide a PR.

That would be very helpful.

**Comment by janetlee** [comment]
Hi! Commenting to give this a bump. I would love this to be tree-shakeable since I do not actually need `pdfjs-dist`. I have a broken TS config (Which I am trying to fix) but tree-shaking would eliminate this error being thrown in the first place.
https://github.com/wojtekmaj/react-pdf/issues/280#issuecomment-786166774

**Comment by nischi** [comment]
Please publish ES6 modules for this library.

**Comment by zenflow** [comment]
This is a big issue as the JS package ecosystem migrates from CommonJS to ESM. The migration has progressed a lot since this issue was opened in 2018, and ESM is now very much standard, and nowhere near bleeding-edge (especially on frontend, as opposed to on nodejs which is another story).

Webpack can still handle this, but next-gen bundlers like Vite cannot.

@Snuffleupagus Any plan to publish ES Modules to catch up with the ecosystem?

**Comment by zenflow** [comment]
https://github.com/mozilla/pdf.js/issues/10317#issuecomment-523430529: 
> the published pdfjs-dist still seems to not have es modules?
> 
> https://unpkg.com/browse/pdfjs-dist@2.1.266/build/pdf.js => UMD
> https://unpkg.com/browse/pdfjs-dist@2.1.266/lib/pdf.js => commonjs
> or is there another distribution somewhere?

https://github.com/mozilla/pdf.js/blob/master/src/pdf.js => ES modules

This project is developed with ES modules, but the `src/` dir just isn't published in the package on NPM. 

Seems like this would be an easy fix, no?

**Comment by Snuffleupagus** [comment]
> Any plan to publish ES Modules to catch up with the ecosystem?

Please keep in mind that the *primary* focus of development for this library is the Firefox PDF Viewer.

For the general PDF.js library, we've been doing various work (over the years) to clean-up and simplify things in order to *reduce* the number of builds that we have to maintain/support. Hence why we provide both browser and Node.js support *in the same* builds in e.g. `pdfjs-dist`, and thus it's *not currently* planned to add any "new" builds.

> This project is developed with ES modules, but the `src/` dir just isn't published in the package on NPM.

And neither should it be, since the only thing that we *officially support* is the functionality accessed via https://github.com/mozilla/pdf.js/blob/master/src/pdf.js respectively https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js (once those files are built and and published in `pdfjs-dist`).

Please keep in mind that using the "raw" `src/`-files directly has never be officially recommended nor supported. (Hence the only thing that may, some day in the future, become supported are ESM-versions of the files in e.g. the https://github.com/mozilla/pdfjs-dist/tree/master/build and https://github.com/mozilla/pdfjs-dist/tree/master/web folders.)

> Seems like this would be an easy fix, no?

Not really, since as mentioned above we don't want to add even more builds and we also want to support both browsers *and* Node.js environments with the same builds.

**Comment by justinfagnani** [comment]
Node package exports would allow you to publish plain, unbundled modules but only allow importing specific entry points.

Node has also supported modules for the last 7 major and 4 LTS versions, so you could still keep one build for both (modulo using environment specific API like DOM and process.env).

**Comment by arcs-** [comment]
This would be a great addition to have in 2023

**Comment by quantuminformation** [comment]
I get

Error: Cannot find module 'pdfjs-dist/es5/build/pdf.js'

<img width="1167" alt="image" src="https://user-images.githubusercontent.com/216566/235322394-734c79af-2f15-473a-b357-dff43e1ecefa.png">

**Comment by quantuminformation** [comment]
I get this running in node

```js
const pdfjsLib = require('pdfjs-dist/build/pdf.js');
const fs = require('fs');

const pdfPath = 'pdf3.pdf';

(async function() {
    const pdf = await pdfjsLib.getDocument(pdfPath).promise;
    const numPages = pdf.numPages;

    for (let i = 1; i <= numPages; i++) {
        const page = await pdf.getPage(i);

        // Check if page is a PDFPageProxy object before calling getTextContent()
        if (page instanceof pdfjsLib.PDFPageProxy) {
            const content = await page.getTextContent();

etc
```

```
[UnhandledPromiseRejection: This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). The promise rejected with the reason "UnknownErrorException: The browser/environment lacks native support for critical functionality used by the PDF.js library (e.g. `Path2D` and/or `ReadableStream`); please use a `legacy`-build instead.".] {```

**Comment by ODAncona** [comment]
I agree :D 🔥 🚀
