### ISSUE TITLE
"Sidebar state on load" incorrect for web-hosted pdfs

### ISSUE THREAD

**Issue by zsiegel92** [mozilla/pdf.js#10335]
Attach (recommended) or Link to PDF file here:

Configuration:
Mac OS 10.13.1, Chrome Version 70.0.3538.110 (Official Build) (64-bit), PDF.js 2.0.673 in Chrome extension

Steps to reproduce the problem:
1. Open a web-hosted pdf file
2. Sidebar opens despite settings

What is the expected behavior? (add screenshot)
Sidebar does not open on load.

What went wrong? (add screenshot)
Sidebar opens on load ONLY for web-based files. This does NOT happen for local files.

NOTE: I attempted to submit another issue (that apparently didn't go through - I can't find it now) regarding web-hosted pdfs not caching correctly. On my computer, when web-hosted (not local files) pdfs are loaded but have changed at their address, the old version (cached) is loaded, even with a "force reload". This is circumvented only by opening the Chrome developer panel and reloading again with "disable cache" checked. These two issues are evidence that this plugin works as intended in some cases only for local files.

**Comment by Snuffleupagus** [comment]
> Sidebar opens despite settings

It's not, at all, clear *exactly* which "settings" are referred to here, since modifying only the `sidebarViewOnLoad` preference might not be enough. You probably need to set the `disablePageMode` preference as well, more on that below.

> Sidebar opens on load ONLY for web-based files. This does NOT happen for local files.

Whether or not the sidebar is opened on load can also be controlled by the PDF file *itself* through the `PageMode` parameter, please refer to the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=82), so it's quite possible the files in question simply have different defaults here.

Given that no example PDF files were provided, and without knowing which "settings" were adjusted, I'm not sure if there's anything actionable to go on here!? @timvandermeij Closing as incomplete for now?

**Comment by zsiegel92** [comment]
Thank you for your responses @Snuffleupagus @timvandermeij 

I've attach a .pdf file (pb_scheduling.pdf) that always loads with the sidebar OPEN despite my "Sidebar state on load: Do not show sidebar" preference. I've also attached a screenshot of my pdf.js preferences.

Please do let me know what preferences I can set to successfully prevent the sidebar from showing on load.

I do not know what tool to use to check `PageMode` for a given file, nor do I know how to specify that parameter for LaTeX output. **I believe the expected behavior for most users would be for the pdf.js "Sidebar state on load" setting to override a pdf's "PageMode" parameter.**


[pb_scheduling.pdf](https://github.com/mozilla/pdf.js/files/2799361/pb_scheduling.pdf)

![pdf_viewer_prefs](https://user-images.githubusercontent.com/26341564/51791309-d9b58700-2155-11e9-9490-aaa132184421.png)

**Comment by Snuffleupagus** [comment]
> Please do let me know what preferences I can set to successfully prevent the sidebar from showing on load.

`disablePageMode`, which was already mentioned in https://github.com/mozilla/pdf.js/issues/10335#issuecomment-457820815.
