### ISSUE TITLE
ligature and ToUnicode 

### ISSUE THREAD

**Issue by Jun711** [mozilla/pdf.js#10372]
Thank you.

Attach (recommended) or Link to PDF file here:
[CS231n Convolutional Neural Networks for Visual Recognition.pdf](https://github.com/mozilla/pdf.js/files/2703924/CS231n.Convolutional.Neural.Networks.for.Visual.Recognition.pdf)
[CS231-qpdf.txt](https://github.com/mozilla/pdf.js/files/2704047/CS231-qpdf.txt)
This one seems to have both ToUnicode and Encoding

[the-environments-of-the-organization-9.3.pdf](https://github.com/mozilla/pdf.js/files/2703927/the-environments-of-the-organization-9.3.pdf)
[the-environments-of-the-organization-9.3-qpdf.txt](https://github.com/mozilla/pdf.js/files/2704055/the-environments-of-the-organization-9.3-qpdf.txt)
This one only has Encoding

Configuration:
- Web browser and its version: Chrome 71.0
- Operating system and its version: macOS High Sierra 10.13.6
- PDF.js version: 1.8.188 build ad1023ff
- Is a browser extension: no

Steps to reproduce the problem:
1. https://mozilla.github.io/pdf.js/web/viewer.html
2. upload the pdf file
3. inspect the html
4. see that the ligature text is missing
5. use [qpdf](https://github.com/qpdf/qpdf) to extract the text using this command:
`qpdf --stream-data=uncompress input.pdf output.txt`

What is the expected behavior? (add screenshot)
expect to be able to copy text converted from ligature

What went wrong? (add screenshot)
![cs231n-ligature](https://user-images.githubusercontent.com/6880939/50359799-d9045200-0512-11e9-8742-818050ca1187.png)
This is what it looks like when I copy that phrase on Acrobar Reader:
input image one label from a 􀂡xed set of categories

![the-environments-ligature](https://user-images.githubusercontent.com/6880939/50359813-e3265080-0512-11e9-9dc0-db39591b5a8e.png)
This is what it looks like when I copy that phrase on Acrobar Reader:
The rst link connects to

Questions
1. Do both of these pdf have Encoding and ToUnicode? 
2. How do I check if it is caused by Encoding and ToUnicode issue?

**Comment by Snuffleupagus** [comment]
Based on the above, you're apparently aware of the fact that your PDF files are the culprits here since by your own account even Adobe Reader (i.e. the reference implementation) cannot select/copy the text perfectly; hence it's not really clear why this issue was opened against the PDF.js library.

Please keep in mind that this is, first and foremost, a *bug tracker* for the PDF.js project, and not a support forum for arbitrary questions about the PDF format itself.
As such, this issue in INVALID and really belongs elsewhere. *Ninja-edit:* It appears that you've already asked this question in https://stackoverflow.com/questions/53890212/how-to-check-if-encoding-and-tounicode-are-properly-done-for-a-pdf and have received reasonable responses there.

**Comment by Jun711** [comment]
@Snuffleupagus 
Thank you for replying and sorry for creating an INVALID issue. 

The main reason was I wasn't sure how to check if my PDF files are ok so I didn't know what was causing the text issue(which was my second question). I also commented on this [issue](https://github.com/mozilla/pdf.js/issues/10225) to get more information. 
From now on, I will use PDF.js and other PDF viewers to compare and check if my PDF files are ok.
