### ISSUE TITLE
Change URL of pdf file in js way ?

### ISSUE THREAD

**Issue by cbastienbaron** [mozilla/pdf.js#10382]
Hi folks,

From issue #9846 

This seems this work sometimes. example : 

```javascript
    <script>
        window.addEventListener('load', function() {
            console.log('there');
            PDFViewerApplicationOptions.set('defaultUrl', '/assets/test.pdf');
        });
    </script>
```
doesn't work each times, sometimes PDFViewer try to load default file `compressed.tracemonkey-pldi-09.pdf` .
My 2cts, viewer part is rely on dom load event. 
There is a simple way to set `defaultUrl` when all stuff is loaded ? and prevent try load `compressed.tracemonkey-pldi-09.pdf` ?

**Comment by timvandermeij** [comment]
You can now listen for the `webviewerloaded` event, which we introduced in #10318 after having seen some reports about `PDFViewerApplication`/`PDFViewerApplicationOptions` being more difficult to set in version 2.0. From that pull request:

> With the removal of the global PDFJS object, in PDF.js version 2.0, the viewer options are no longer as easily accessible as they previously were (and issues have been filed about this).
In particular, since the viewer files aren't necessarily loaded immediately, this means that PDFViewerApplication/PDFViewerApplicationOptions aren't necessarily available directly. By dispatching an event once all viewer files are loaded but before the viewer initialization has run, setting AppOptions during load (in custom implementations of the default viewer) should hopefully become a little bit easier[1].

**Comment by jasonslogan** [comment]
I tried the event listener but it never did load the pdf. It kept trying that monkey one. It seems changing the defaultUrl after the page loads does not work. I'm guessing but it seems the viewer has already initialized by then.

It was weird but this is how I did it using PHP.

I needed a way to pass in a GET variable into the already present file= that is reported to javascript querystring in viewer.js. This is how the viewer.html?file=blah.pdf  works.

I tried viewer.html?file=/path/myphp.php?id=1234

That did not work.

Since the defaultUrl is buried in the viewer.js file, that wasn't going to work either.

So I changed viewer.html to viewer.php and did the following encoding:

viewer.php?file=/path/myphp.php%3Fid%3D1234

As you can see the ? and the = sign are now encoded to %3F and %3D hex in the GET string.

This worked!

As I change the url to different numbers, other than 1234, it pulled up each PDF as it should but now using the PDFJS viewer instead of the default PDF viewer that the browser uses.

**Comment by jasonslogan** [comment]
I can report now that the viewer.html?file=/path/myphp.php%3Fid%3D1234

works too!

You do not need to change viewer.html to viewer.php. The php, for me, came in later.

**Comment by timvandermeij** [comment]
It's related to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file:

*[...] or you can append the ?file= query string to the viewer URL, e.g. http://mozilla.github.com/pdf.js/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf. **In the latter case, the PDF path/URL must be encoded using encodeURIComponent().***
