### ISSUE TITLE
Download button on iOS download only first page and saves as image

### ISSUE THREAD

**Issue by Prabudotb** [mozilla/pdf.js#10433]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 12.1.2
- Operating system and its version: iOS 12.1.2
- PDF.js version: 2.0.943-dist
- Is a browser extension: No

Steps to reproduce the problem:
1. Click on the download button on the pdf created using pdfjs and embedded in web app
2. Save in the downloaded pdf in the iOS books

What is the expected behavior? (add screenshot)
All pages of the pdf should be downloaded to the books and should be saved as pdf. 

What went wrong? (add screenshot)
1. The displayed pdf has 2 pages while the downloaded pdf shows only the first page.
2. The pdf saved to iOS books should be saved as pdf and not as image

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Prabudotb** [comment]
Update: The issue happens only when the pdf binary data is passed to the viewer dynamically using the below code

    var pdfjsframe = document.getElementById('pdfViewer');

    base64Data = [[${eletterPDFVO.fileData}]];
    var pdfData = base64ToUint8Array(base64Data);
    var binaryData = [];
    binaryData.push(pdfData);
    var url = window.URL.createObjectURL(new Blob(binaryData, {type: "application/pdf"}));

    pdfjsframe.src = "../../web/viewer.html?file=" + encodeURIComponent(url);
    // pdfjsframe.src = "../../web/viewer.html?file=document.pdf";
    function base64ToUint8Array(base64) {
        var raw = atob(base64);
        var uint8Array = new Uint8Array(raw.length);
        for (var i = 0; i < raw.length; i++) {
            uint8Array[i] = raw.charCodeAt(i);
        }
        return uint8Array;
    }

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
> 
>     1. Click on the download button on the pdf created using pdfjs and embedded in web app
> 
>     2. Save in the downloaded pdf in the iOS books

What download button are you actually referring to here, since the download functionality of the PDF.js default viewer will simply download the PDF file as-is and will definitely *not* convert the file to an image!?

Based on the (somewhat limited) information provided, this really sounds more like a platform/browser issue rather than a PDF.js one (in which case, there's probably not much that can be done here).

**Comment by timvandermeij** [comment]
I also don't think it's PDF.js that's doing this. Looking at the download code, see https://github.com/mozilla/pdf.js/blob/master/web/app.js#L714-L717, all we do it create a blob of the raw data and set the `application/pdf` type, so we definitely don't convert anything to an image. It could be that your platform misinterprets the type somehow, but that is not something we can fix. Closing since it's not actionable for us.
