### ISSUE TITLE
How to implement on scroll chunk loading in pdfjs

### ISSUE THREAD

**Issue by bikramnayak** [mozilla/pdf.js#10431]
I am creating a pdf viewer using pdf.js with support of chunk loading but chunks are getting loaded automatically which occurred memory issue so Is there any way to load the chunks while required.

I want the chunks to be loaded on scroll only not by default 
I have made some changes in my component but its not working, can someone guide me to resolve this?

sample code: 
var loadingTask = PDFJS.getDocument({
            url: this.pdfSrc,
            rangeChunkSize: this.chunkSize,
            disableAutoFetch: true,
            disableStream:true
        });

Thanks in Advance

**Comment by Snuffleupagus** [comment]
It works just fine in the default viewer, with `disableAutoFetch` and `disableStream` set.

If you completely ignore the *entire* [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, no one will be able to help you! In particular, for custom implementations, you *need* to provide access to a complete and runnable example since code-snippets are essentially useless.

**Comment by timvandermeij** [comment]
Closing as answered until more information is provided.
