### ISSUE TITLE
how to provide custom filename in viewer.html where the file is a blob url

### ISSUE THREAD

**Issue by Prabudotb** [mozilla/pdf.js#10435]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 12.1.2
- Operating system and its version: iOS 12.1.2
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
When user tries to download the pdf using the download button in the viewer, the file should be downloaded with the name provided during rendering the pdf in the viewer.

What went wrong? (add screenshot)
All files are using the "undefined.pdf" when downloading the pdf.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Prabudotb** [comment]
I was able to provide a custom file name as below but after few hours of google and trial & error.
  pdfjsframe.src = "../../web/viewer.html?file=" + encodeURIComponent(url + "#" + eltrName);

Hope the documentation can be updated.

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file for general information about opening files with the default viewer.

In particular note that the *correct* way, if you need to open a `blob://` URL and want to specify a custom filename, will be to first load the viewer without a file (as outlined in the FAQ) and then call:
```javascript
PDFViewerApplication.open({
  url: /* blob:// URL goes here */,
  originalUrl: /* custom filename goes here */,
```

(To know when the viewer has loaded, such that the above code can be run, you can listen for the `webviewerloaded` event on the window.)

**Comment by Prabudotb** [comment]
Thanks for the sharing the FAQ link and the tip. Cheers

**Comment by Prabudotb** [comment]
Hi Snuffleupagus,

Sorry, i am relatively new ot JS. 

I am adding the pdf.js and viewer.js files in my html using the script tag. When I try to invoke PDFViewerApplication, I get the following error in the console

"message_handler.js:433 Uncaught (in promise) DOMException: Failed to execute 'postMessage' on 'Worker': TypeError: Cannot read property 'parentNode' of null could not be cloned."

My code snippet
------------------
    var base64Data = [[${eletterPDFVO.fileData}]];
    var eltrName = [[${eletterPDFVO.filename}]];
    var pdfData = base64ToUint8Array(base64Data);
    var binaryData = [];
    binaryData.push(pdfData);
    var bloburl = window.URL.createObjectURL(new Blob(binaryData,{type: "application/pdf"})) ;
	
	var DEFAULT_URL = "";
	
	pdfjsLib.GlobalWorkerOptions.workerSrc = '../../build/pdf.worker.js';
	pdfjsLib.disableCreateObjectURL = true;
	pdfjsLib.disableRange=true;
	pdfjsLib.disableStream=true;

	var loadingTask = pdfjsLib.getDocument(pdfData);
	loadingTask.promise.then(function(pdf) {
		console.log('PDF loaded');
		var container = document.getElementById('viewerContainer');
		console.log(window.PDFViewerApplication);
        pdfjsViewer = window.PDFViewerApplication;
        PDFViewerApplication.open({
            url: bloburl,
            originalUrl: eltrName
        });

	});

**Comment by Prabudotb** [comment]
Update my code Snippet. Any help is appreciated. Thanks

**Comment by Prabudotb** [comment]
I was able to call the pdfviewerapplication as below

                <iframe class="h100" id="pdfViewer" src="../../web/viewer.html?file=" allowfullscreen="" webkitallowfullscreen="" onload="loadPDF()">
                </iframe>

loadPDF(){

// Other code to build the bloburl & eltrName

	document.getElementById('pdfViewer').contentWindow.PDFViewerApplication.open({url: bloburl, originalUrl: eltrName});
}

When I try to save the file in iOS, it shows as unknow.pdf. Appreciate if someone could share a similar experience.

Thanks

**Comment by brunomptavares** [comment]
Despite being old this issue helped me to get to where I wanted closer than any other resource. I spent so much time to make this work that I really want to share so that it may help someone in the future.

Im using Vue to create a PWA to manage documents so I need to display pdf files and I use pdfjs to display them. I store the blobs in indexedDB. When the user clicks a button it opens a new window pointing to the `viewer.html` file with the corresponding query. I included pdfjs-dist in my `public `folder where the static assets live.

```
let fileUrl = URL.createObjectURL(fileBlob); 
let win = window.open(process.env.BASE_URL+"pdfjs/web/viewer.html?file=&fileUrl="+encodeURIComponent(fileUrl)+"&displayName="+file.displayName+"."+file.type)`
```

Notice that in the query I leave `file` parameter emtpy in order for the file name change occur, according to the FAQ link referred above. The second parameter `fileUrl` is the actual blob url that points to the file and the last one `displayName` is the actual file name that we want to show.

Now comes the tricky part that actually made me proud because I really had to try a lot of stuff to get to this. 

We need to use the `PDFViewerApplication.open()` function somewhere to override the name and set the file URL. I figured that this must be part of pdfjs core so I edited the `viewer.html` to include a custom script after the main `pdf.js` but before `viewer.js` file.

```
window.addEventListener('webviewerloaded', () => {
  let urlParams = new URLSearchParams(window.location.search);
  let displayName = urlParams.get('displayName');
  let fileUrl = urlParams.get('fileUrl');
  PDFViewerApplication.open({
    url: fileUrl,
    originalUrl: displayName,
  });
  PDFViewerApplication.setTitleUsingUrl(displayName)
})
```

Here we can access the query parameters and also `PDFViewerApplication.open()` function and we can set the `url` and `originalUrl`.

BONUS: pdfjs tries to guess the name of the file from the URL, and because it's a blob URL it's not possible to get that information so the name by default is `document.pdf`. With the last line of code you can programatically set that name!

I hope this helps someone struggling like I was! Thanks @Prabudotb and @Snuffleupagus without your help I would still be banging my head against the wall.

**Comment by zonglinlee** [comment]
const req = await viewEnrollCertificate({ studentId: row.id })
        const blob = new Blob([req])
        const URL = window.URL || window.webkitURL
        const displayNameHash = encodeURIComponent(`#displayName=${row.name}_${row.examNo}_通知书.pdf`)
        const objectUrl = URL.createObjectURL(blob) + displayNameHash
        const windowUrl = window.location.origin + window.location.pathname
        window.open(`${windowUrl}pdf/web/viewer.html?file=${objectUrl}`)

**Comment by bkane11** [comment]
Thanks @Prabudotb and @brunomptavares, a synthesis of your answers is what I was looking for.

Open with blank `file` parameter initially to prevent opening the default file hard-coded in PDF.js `viewer.js` when no file is specified.
Then open the open the file with `originalUrl` specified from which the viewer will obtain file name.
```javascript
const src = 'data:application/pdf;base64,...the base64 encoded PDF contents...';
const response = await fetch(src);
const blob = await response.blob();
const objectURL = URL.createObjectURL(blob);
const iframe = document.getElementById('the-target-iframe');
iframe.onload = () => {
    iframe.contentWindow.PDFViewerApplication.open({
        url: objectURL,
        originalUrl: 'my-better-filename.pdf'',
    });
}
iframe.src = `${pdfViewerURL}?file=`;
```

**Comment by qq715152910** [comment]
> ```
>     const req = await viewEnrollCertificate({ studentId: row.id })
>     const blob = new Blob([req])
>     const URL = window.URL || window.webkitURL
>     const displayNameHash = encodeURIComponent(`#displayName=${row.name}_${row.examNo}_通知书.pdf`)
>     const objectUrl = URL.createObjectURL(blob) + displayNameHash
>     const windowUrl = window.location.origin + window.location.pathname
>     window.open(`${windowUrl}pdf/web/viewer.html?file=${objectUrl}`)
> ```

This code is awesome, thanks!

**Comment by jaggaer-aradice** [comment]
`document.getElementById('pdfViewer').contentWindow.PDFViewerApplication._contentDispositionFilename = 'yourPDF.pdf'`
