### ISSUE TITLE
While downloading on iOS, the pdf is saved as unknown.pdf.

### ISSUE THREAD

**Issue by Prabudotb** [mozilla/pdf.js#10442]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 12.1.2
- Operating system and its version: iOS 12.1.2
- PDF.js version: 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Embed pdfjs in "responsive web app" (thyme/spring) by adding an iframe with src as viewer.html?file=
2. Load pdf using PDFViwereApplication.open ({bloburl, custfilename})
3. Once the pdf is loaded click on download

What is the expected behavior? (add screenshot)
When saving the pdf using the download button in the viewer, the custfilename used while loading the pdf should be used.

What went wrong? (add screenshot)
When saving the file on iOS, the file is saved as unknow.pdf instead of the custfilename provided while loading it in the viewer.

Note: The file saves with the custname when saved on android & windows devices

I am unable to provide the code or link to the web app to it as I have could not get it cleared for sharing.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> When saving the file on iOS, the file is saved as unknow.pdf instead of the custfilename provided while loading it in the viewer.

Simply put, there's no code in the viewer that will ever attempt to set the filename to `unknown.pdf`. As can be seen in https://github.com/mozilla/pdf.js/blob/e4d2a1604efdb4a49f29b4a593baea23e4470c36/web/ui_utils.js#L550 the default name is `document.pdf` and this thus seem like a browser issue rather than a PDF.js one.

(The only other explanation would be if your server sends a `Content-Disposition` header which is setting the filename to `unknown.pdf`.)
