### ISSUE TITLE
Un english chars split any world in text layer

### ISSUE THREAD

**Issue by kfir91** [mozilla/pdf.js#10446]
Hello,
this is text layer of english pdf:

![image](https://user-images.githubusercontent.com/11144887/51084194-79265300-172e-11e9-9f66-6c9ddd121995.png)
like you see, every line in the pdf in new span.

but if my pdf is hebrew pdf
its split every word to new span.
like this:

![image](https://user-images.githubusercontent.com/11144887/51084208-bf7bb200-172e-11e9-8bcf-d16e9e4b6990.png)

for this text:

![image](https://user-images.githubusercontent.com/11144887/51084215-ce626480-172e-11e9-9d85-442be7dbe734.png)

what can i do?
tnx

**Comment by timvandermeij** [comment]
You can try tweaking this constant: https://github.com/mozilla/pdf.js/blob/ed4ac1bc67d109938bcf6e55981cabed315e2981/src/core/evaluator.js#L1307

However, this is a more general problem for which we already have other open issues, such as the similar issue #7224. Since this one also does not contain the information from the issue template, I'm closing this as a duplicate.

**Comment by kfir91** [comment]
> You can try tweaking this constant:
> 
> [pdf.js/src/core/evaluator.js](https://github.com/mozilla/pdf.js/blob/ed4ac1bc67d109938bcf6e55981cabed315e2981/src/core/evaluator.js#L1307)
> 
> Line 1307 in [ed4ac1b](/mozilla/pdf.js/commit/ed4ac1bc67d109938bcf6e55981cabed315e2981)
> 
>  var SPACE_FACTOR = 0.3; 
> However, this is a more general problem for which we already have other open issues, such as the similar issue #7224. Since this one also does not contain the information from the issue template, I'm closing this as a duplicate.

@timvandermeij its not duplicate.
