### ISSUE TITLE
Repeats the first page at the end

### ISSUE THREAD

**Issue by shreyasb07** [mozilla/pdf.js#10450]
Hi Team,

There is a very weird behavior of the PDF viewer that I am experiencing!
I see the first page repeat itself at the end of the document.

For example, if the original document consists of 4 pages, I see the pages 1-4 in order, but I see the 1st page again after the 4th page!

'data-page-number' repeats!

Any help is really appreciated!

**Comment by timvandermeij** [comment]
Closing since, as stated in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, it's impossible for us to help out if there is no working example provided, together with the rest of the issue template. Since this doesn't happen in the default viewer, or at least we haven't had any reports of this yet, it looks like this is a bug in a custom solution.
