### ISSUE TITLE
Over 100 times lower performance in Chrome compared to Firefox

### ISSUE THREAD

**Issue by uxmaster** [mozilla/pdf.js#10506]
Attach (recommended) or Link to PDF file here:
[8.pdf](https://github.com/mozilla/pdf.js/files/2803741/8.pdf)

Configuration:
- Web browser and its version: Chrome 71.0.3578.98 (Official Build) (64-bit)
- Operating system and its version: Ubuntu 16.04.5
- PDF.js version: 2.1.228 & 2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached one-page PDF
2. Wait...

What is the expected behavior? (add screenshot)
After a second or so the page is ready in Firefox.

What went wrong? (add screenshot)
Using PDF.js 2.1.228 it takes over 100 seconds in Chrome, while I have not managed to get any result using version 2.0.943, the tab became unresponsible and I had to close the browser.

I used the demo viewer (PDF.js 2.1.228): https://mozilla.github.io/pdf.js/web/viewer.html
and my own embedded solution using the latest stable version 2.0.943.

**Comment by Snuffleupagus** [comment]
> What is the expected behavior? (add screenshot)
> After a second or so the page is ready in Firefox.
> 
> What went wrong? (add screenshot)
> Using PDF.js 2.1.228 it takes over 100 seconds in Chrome,

Given that this sounds entirely like a bug in Chrome rather than in the PDF.js library, since it works fine in Firefox, is it meaningful to keep this issue open?
Please keep in mind that the primary reason for this library to exist is for the Firefox built-in PDF Viewer, it unfortunately seems very unlikely that we'd make any changes and thus risk reducing performance in Firefox, for a Chrome-specific issue.
