### ISSUE TITLE
How to update/install pdf.js without updating firefox?

### ISSUE THREAD

**Issue by shiftyshady** [mozilla/pdf.js#10500]
I have been able to update pdf.js by modifying omni.ja. 
60.4.0esr's pdf.js version works great on an older firefox with a clean profile, but it stops working as soon as any other addon is installed. So I don't know if the problem is with how omni.ja is updated or due to pdf.js being incompatible.

A few xpi files released during 2018 here on github.com/mozilla/pdf.js/issues install and work without problems. I have tried to create xpi files using the "content" dir from updated pdf.js versions, but I am not an addon dev and the xpi files I created do not work (can be installed, but pdf files do not open then).

Is there an easier way to update pdf.js?

**Comment by timvandermeij** [comment]
First of all, please don't open duplicate issues as this is already asked in #10496. There I clearly stated that this is not easily possible because we don't build extensions anymore given the fact that PDF.js is now embedded in Firefox. Moreover, we don't have experience with `omni.ja`, so you should really ask the question to them.
