### ISSUE TITLE
Stop using mozPrintCallback in generic builds

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#10528]
Over in https://bugzilla.mozilla.org/show_bug.cgi?id=1524640 the fix is only allowed for the built in pdf.js viewer, so if fonts are cleaned before the callback, printing will break. There's also been a little discussion on moving mozPrintCallback to only be allowed by the internal PDF.js viewer since no other browser implement it nor do they plan to.

**Comment by Snuffleupagus** [comment]
The generic printing code, which is found in [web/pdf_print_service.js](https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js), hasn't been using `mozPrintCallback` ever since PR #7697 :-)

The only usage of `mozPrintCallback` is found in https://github.com/mozilla/pdf.js/blob/master/web/firefox_print_service.js, a file which is only bundled into `MOZCENTRAL` builds: https://github.com/mozilla/pdf.js/blob/7d24fc34f9fb4045d49025512e5bb6989709eb13/web/viewer.js#L44-L47

**Comment by brendandahl** [comment]
Hah, missed that one.
