### ISSUE TITLE
Failed to fetch canvas for later pages from a front page 

### ISSUE THREAD

**Issue by lumingc** [mozilla/pdf.js#10553]
I am trying to modify the viewer of PDF.js to allow highlight of multiple places. I already have the coordinates for the bounding boxes that I want to highlight. The highlight function I used requires getting canvas for multiple pages. However, the canvas for later pages oftentimes fail to load so I ended up with a null error. Is there a way to load all canvas at once inside viewer.js? Or is there a better way to highlight multiple places?

One example pdf I used was https://arxiv.org/pdf/1804.00933.pdf. And when I am on page one and want to highlight something on page 14, I got null from fetching the canvas from PDFViewerApplication.pdfViewer._pages[pageNum - 1]. canvas;

**Comment by Snuffleupagus** [comment]
> However, the canvas for later pages oftentimes fail to load so I ended up with a null error.

The general PDF.js library, and the default viewer, is asynchronous hence this is expected behaviour. In the default viewer pages won't be rendered until actually visible, in order to save resources.

> Is there a way to load all canvas at once inside viewer.js?

As explained in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, that's not a good idea and it won't be officially supported.

> PDFViewerApplication.pdfViewer._pages[pageNum - 1]. canvas;

Please note that while JavaScript doesn't (yet) have a concept of private properties/methods, a leading underscore is usually used to denote something that should be considered *private*. The code above could stop working at *any time*, you should be using `getPageView` instead; see https://github.com/mozilla/pdf.js/blob/81f5835cd7024827e0671ccd66525df98fb15703/web/base_viewer.js#L176-L178

---

In the default viewer a `pagerendered` event is emitted whenever a page has been loaded *and* rendered, hence you can use that to know when the page in question is available; see https://github.com/mozilla/pdf.js/blob/81f5835cd7024827e0671ccd66525df98fb15703/web/pdf_page_view.js#L220-L224
