### ISSUE TITLE
Correct word is not highlighted after searching any word in PDF

### ISSUE THREAD

**Issue by nikhilwork** [mozilla/pdf.js#10602]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Android Webview, Targe 28
- Operating system and its version: Android 28
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. set the pdf viewer zoom percent to 50 or lower and then search any word.
2. Search result words not highlighting on the correct position.

What is the expected behavior? (add screenshot)
Word selection and highlight should appear on correct position

What went wrong? (add screenshot) the highlight is happening with other words.
![pdf_viewer_issue](https://user-images.githubusercontent.com/25149156/53632079-0ae41400-3c3a-11e9-89bf-32cf52674910.jpg)

**Comment by Snuffleupagus** [comment]
This issue is unfortunately lacking too much of the required information in order to be actionable!

> Attach (recommended) or Link to PDF file here:

The PDF file must be provided.

> PDF.js version:

This information must be provided.

> set the pdf viewer zoom percent to 50 or lower and then search any word.

The screen-shot uses `page-fit`, hence it's not obvious that it's a clear representation of the problem!?

---

Finally, there's something off about the viewer UI in the screen-shot, since the `findBar` is clearly offset from the `Find` button itself (which obviously shouldn't happen). One possible explanation for these issues could be that that viewer UI itself, rather than just the PDF file, has been zoomed in the browser which may explain the problems.

**Comment by timvandermeij** [comment]
Closing until more information is provided.
