### ISSUE TITLE
Where do thumbnails get generated on first load?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10609]
i figured the pagerendered event will generate the thumbnails but it does not look like it because only pages that are visible on screen are generated

but the page thumbnails in the sidebar are all generated.

would like to request guidance on where these happen. thank you

**Comment by Snuffleupagus** [comment]
Rather than expecting someone else to spend *a lot* of time and effort painstakingly walking you through the rendering code of the default viewer, please take the time to carefully read through *and* play with the code in question (using e.g. breakpoints in a debugger and/or print statements inserted in the code).

If, after doing so, you have questions about *specific* parts of the code-base, there's a much greater chance that good answers can be (easily) provided.
Please keep in mind that this is, first and foremost, a *bug tracker* and not a general support forum.

**Comment by timvandermeij** [comment]
You can start taking a look at https://github.com/mozilla/pdf.js/blob/master/web/pdf_thumbnail_viewer.js, which contains most thumbnail-related code.

**Comment by chitgoks** [comment]
i got it to work. but, just like print preview, there is no way to accomplish it without adding code in viewer.js

thanks for the tips.
