### ISSUE TITLE
All text missing from node.js rasterization

### ISSUE THREAD

**Issue by cemerick** [mozilla/pdf.js#10623]
Attach (recommended) or Link to PDF file here: 
[1120.pdf](https://github.com/mozilla/pdf.js/files/2936435/1120.pdf)

Configuration:
- Operating system and its version: ubuntu 18, node v10.13.0
- PDF.js version: HEAD, e9661edda74963dbbba411529fe48f8e8cd01c5c
- Is a browser extension: no

Steps to reproduce the problem:
1. Clean build, `mv build/dist node_modules/pdfjs-dist`
2. Move the sample `1120.pdf` to `compressed.tracemonkey-pldi-09.pdf`
3. `cd examples/node/pdf2png/; node pdf2png.js`

What is the expected behavior?
An accurate rasterization of the first page of the source document, i.e. ![screenshot from 2019-03-06 08-45-12](https://user-images.githubusercontent.com/47489/53885663-4e4cd280-3fec-11e9-88d3-9aa4306b17a0.png)

What went wrong?
None of the text in the document is rendered:

![output](https://user-images.githubusercontent.com/47489/53885640-40974d00-3fec-11e9-9e1d-87b1fc640445.png)

`stderr` contains a bunch of warnings like:

```
Warning: getPathGenerator - ignoring character: "Error: Requesting object that isn't resolved yet Helvetica_path_$.".
```

Note that the document contains a single embedded font, and it's not Helvetica, so the message doesn't really make sense to me.

Are there things that need to be done in a node context to ensure reliably correct rasterization that aren't included in the example code?

**Comment by cemerick** [comment]
If I add `disableFontFace:false` to the `.getDocument` call, the rasterization output is as expected.

It seems that `disableFontFace:true` is [the default on node](https://github.com/mozilla/pdf.js/blob/e9661edda74963dbbba411529fe48f8e8cd01c5c/src/display/api_compatibility.js#L36), perhaps given the workaround advice provided in e.g. #7929 and elsewhere?

It seems like that "compatibility" setting is counterproductive in this case? It seems at least one other person determined this, https://github.com/mozilla/pdf.js/issues/4244#issuecomment-463865708

**Comment by Snuffleupagus** [comment]
Duplicate of #4244.

**Comment by Snuffleupagus** [comment]
> Is there a way to e.g. point to where system fonts can be loaded?

No, since this isn't entirely easy to implement. (You cannot simply register the font one the main-thread.)

> [...] would you be interested in a PR that provided such a configuration facility, and whatever font plumbing was necessary to load them?

*__First a disclaimer:__ Please keep in mind that I'm not now, nor have I ever been, paid to work on the PDF.js library. (It was always just a simple way to contribute to Firefox for me.)*

Personally I couldn't care less since it seems somewhat unlikely that this would ever be included in the PDF.js version that's shipping in Firefox, considering first of all the space required for the fonts and secondly the potential issues with font copyrights/licenses.

Also, implementing this is probably not entirely simple without prior experience with the PDF.js font code.

---

*Ninja-edit:* Looking through my local branches, I've actually got a set of WIP-patches that implemented a basic (and somewhat hacky) way of loading standard fonts :-)
However, given the reasons above I never finished it, but I seem to recall it working "OK" for something that I hacked together in an afternoon/evening; see the following screen-shot for an example:

![4244](https://user-images.githubusercontent.com/2692120/53892727-216cdf80-402d-11e9-9b7d-3a3ee976ae24.png)

**Comment by cemerick** [comment]
> Please keep in mind that I'm not now,
> nor have I ever been, paid to work on the 
> PDF.js library. (It was always just a simple 
> way to contribute to Firefox for me.)

Sure, I guess I was using the royal "you" there. 😊

We already maintain our own fork for various reasons, so a solution that isn't necessarily eligible for inclusion upstream is just fine. If you feel like pushing up your WIP, maybe I can polish it up as necessary.

**Comment by Snuffleupagus** [comment]
> [...] it seems somewhat unlikely that this would ever be included in the PDF.js version that's shipping in Firefox, considering first of all the space required for the fonts and secondly the potential issues with font copyrights/licenses.

*In addition:* Generally speaking it's *never* a good idea to add code which is both unused *and* untested, since that just causes huge headaches for anyone needing to maintain this (or related) code in the future.
Hence why I stopped working in the feature, since I don't think this can be considered for inclusion in the PDF.js library when the points above haven't been resolved.

> We already maintain our own fork for various reasons, so a solution that isn't necessarily eligible for inclusion upstream is just fine. If you feel like pushing up your WIP, maybe I can polish it up as necessary.

Sorry, but I don't intent to providing a patch for something that I cannot see directly benefiting the PDF Viewer that's shipping in Firefox.

---

Anyway, this should just be closed as a duplicate of #4244.

**Comment by cemerick** [comment]
Sure, I understand completely. Thanks very much for the clarifications, etc. :+1: Closing.

**Comment by Snuffleupagus** [comment]
Adding to https://github.com/mozilla/pdf.js/issues/10623#issuecomment-470199768, I could possibly provide a *basic* patch which allows loading of external font files[1] such that they are available to the font code on the worker-thread.

However, please note I'd only consider doing so in return for reasonable (monetary) compensation.

For anyone using PDF.js in e.g. a commercial setting, and thus willing to pay for a patch, please feel free to contact me directly to discuss this further (email address is in my GitHub profile).

---
[1] Obviously I wouldn't be able, for e.g. copyright reasons, to provide the actual font files themselves; however I've used [these ones](https://pdfium.googlesource.com/pdfium/+/master/core/fxge/fontdata/chromefontdata) when taking the screen-shot in https://github.com/mozilla/pdf.js/issues/10623#issuecomment-470154820.
