### ISSUE TITLE
PDF version support question

### ISSUE THREAD

**Issue by AleksandrovM** [mozilla/pdf.js#10637]
What version of PDF does pdf.js support (1.7 / 2.0) ? Is there any documentation and plans regarding version support ?

**Comment by timvandermeij** [comment]
As far as I know we provide support until and including PDF 1.7; see https://github.com/mozilla/pdf.js/wiki/Enumeration-Assignments-for-the-Telemetry-Histograms. However, since PDF 2.0 is backwards compatible, most if not all functionality should just work, perhaps only the newly added functionality is not yet available.
