### ISSUE TITLE
Cannot import any node_modules dependency

### ISSUE THREAD

**Issue by chayka** [mozilla/pdf.js#10648]
Hello everyone. I've forked pdfjs and trying to build my browser extension by extending the one you have in this repo. In fact I'm extending the web app.

Problem I'm stuck with is: how do I import some 3rd party node_module?

I've installed npm module 'spelling' by running:
```
npm i --save-dev spelling
```
and when in let's say /web/base_viewer.js I'm trying to:
```
import Spelling from 'spelling';
```
I get:
```
GET http://localhost:8888/web/spelling.js 404 (Not Found)
```

Any other node_module import does all the same, produces http fetch that is never found.

Configuration:
- Web browser and its version: Chrome 72.0.3626.121
- Operating system and its version: MacOS Mojave 10.14.3
- PDF.js version: 2.0.0
- Is a browser extension: doesn't matter

Steps to reproduce the problem:
1. npm install --save-dev DEPENDENCY
2. import * as DEP from DEPENDENCY; // anywhere inside /web
3. gulp server

What is the expected behavior? (add screenshot)
Dependency is imported.

What went wrong? (add screenshot)
Instead of importing DEPENDENCY webpack or system.js or whatever is trying to fetch it from http://localhost:8888/web/DEPENDENCY.js url.

Example:
![image](https://user-images.githubusercontent.com/1560684/54479863-b2646780-4832-11e9-8150-7e6dc5fa64c4.png)

Console output:
![image](https://user-images.githubusercontent.com/1560684/54479852-9365d580-4832-11e9-9462-8c1957370746.png)

Any help is appreciated :)

**Comment by Snuffleupagus** [comment]
> I've forked pdfjs and trying to build my browser extension by extending the one you have in this repo.

If all you want to do is build an extensions compatible with Chromium-based browser, no particular changes *should* be required after installing the Node dependencies and just running `gulp chromium` ought to work.

>  In fact I'm extending the web app.

However, since it seems that you're attempting to use `gulp server` for development (before actually generating the extension), you'll thus need to list the Node dependencies in https://github.com/mozilla/pdf.js/blob/b4c3b9459216c57aeb50f237d4f5857d92a08dcb/systemjs.config.js#L66-L72
