### ISSUE TITLE
PDf.js in Ionic 4 / Angular 7

### ISSUE THREAD

**Issue by Solangetatiana** [mozilla/pdf.js#10667]
Hi there,

I'm trying to develop PDF Viewer in Ionic 4 / Angular 7 using PDF.js 

I've run `npm i pdfjs-dist` and put `import * as pdfjsdist from 'pdfjs-dist';` in home.page.ts

But I'm not finding any example to make it works.

Anyone has any suggestions??

Regards,
Solange

**Comment by timvandermeij** [comment]
We don't have examples for Ionic/Angular. The examples in the `examples/` folder are general and should apply no matter which framework you use. I think there are some Angular examples on e.g., GitHub and StackOverflow, but we cannot provide them since we don't have experience with those frameworks.

**Comment by Rattone** [comment]
@Solangetatiana did you find how to do it? have you succeeded?
