### ISSUE TITLE
Can we DISABLE links within the PDF document?

### ISSUE THREAD

**Issue by aamakerlsa** [mozilla/pdf.js#10664]
is it possible to DISABLE links in the PDF displayed in PDF.js embedded iframe?

**Comment by timvandermeij** [comment]
Yes. For component-based viewers, you can remove the `annotationLayerFactory` (https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L56). Otherwise, you can edit https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_layer.js#L270 to not display link annotations.
