### ISSUE TITLE
Does not load Pdf in IE11 using pre built version

### ISSUE THREAD

**Issue by AdamOlevall** [mozilla/pdf.js#10676]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: Windows 10 Enterprise
- PDF.js version: 2.0.943
- Is a browser extension: no

Steps to reproduce the problem:
1. Download pre built version.
2. PDF.js is initialized in the following way:
![initializer](https://user-images.githubusercontent.com/11074668/54885905-136aeb80-4e82-11e9-943e-4e2c7b18b580.PNG)

What is the expected behavior? (add screenshot)
The Pdf should be rendered

What went wrong? (add screenshot)
The Pdf works great using chrome, edge and firefox. But using IE 11 does not generate any pdf. The toolbar is rendered but there is no pdf to be seen. The console throws the following errors:
![console_errors](https://user-images.githubusercontent.com/11074668/54885978-d6ebbf80-4e82-11e9-9a97-fd5f44bdcf69.PNG)
 where the const message refers to the following code: `for (const key in value)` which can be found on row 86 in viewer.js. This seems lika a babel problem but we are already using babel in our project so that could not be the case... I also read that compatibility.js, which should help out on IE 11 problems, is included in the pdf.js and pdf.worker.js... 
Am I missing some obvious things here?

**Comment by Snuffleupagus** [comment]
> Download pre built version.

From where *exactly* are you downloading the files, since the releases available at https://github.com/mozilla/pdf.js/releases are translated used Babel and they should thus work in IE11?

Keep in mind that, as mentioned in e.g. https://github.com/mozilla/pdf.js#getting-the-code, the *source code* itself cannot run in older browsers without building it first (or using a release as referenced above).

> PDF.js is initialized in the following way:

A screen-shot of code isn't that useful unfortunately, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by AdamOlevall** [comment]
I thought I had downloaded the newest release, but I followed your link and tried the newest and now it works. My bad! Thanks for helping out!
