### ISSUE TITLE
Set custom width of sidebar

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10687]
Is there a way to change the width dynamically? the current sidebar width is thin for my requirements.

**Comment by Snuffleupagus** [comment]
See PR #9026; note also this excerpt from e.g. https://mozilla.github.io/pdf.js/getting_started/:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

However, this issue doesn't contain nearly enough details to be actionable! When opening as issue you *need* to actually fill out [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) such that all relevant information is available (otherwise there's a lot of contributor time wasted just trying to get necessary information).

Finally, please keep in mind that this is first and foremost a *bug tracker* and not a support forum!
However, people may attempt to help out when possible, provided that issues questions actually contain all the necessary details/context.

**Comment by chitgoks** [comment]
Thanks. I saw the _updateWidth() in pdfSideBarResizer.
