### ISSUE TITLE
Not able to prevent downloading PDF files from Safari 12 browser

### ISSUE THREAD

**Issue by VigneshAnbumani** [mozilla/pdf.js#10686]
PDF files is rendered in PDF JS Safari browser, but I don't want the user to download the files. I am able to download using File ->Save As -> Web Archive. Is there any way to prevent files from being downloaded.

Configuration:
- Web browser and its version: Safari 12
- Operating system and its version: IOS
- PDF.js version: V2.0.943
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF file in Safari browser

What is the expected behavior? (add screenshot)
Disable or prevent download option in Safari

What went wrong? (add screenshot)
Able to download the file

**Comment by Snuffleupagus** [comment]
> I am able to download using File ->Save As -> Web Archive. Is there any way to prevent files from being downloaded.

This sounds like you're referring to a menu entry in the browser *itself*, which a web-page/web-app obviously cannot control.

> Disable or prevent download option in Safari

It's not all all clear what "download option" you're actually referring to here. If it's the functionality found in the default viewer, then you can obviously modify the viewer to e.g. hide the download buttons; please keep https://mozilla.github.io/pdf.js/getting_started/ in mind:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

As-is this issue will be closed as incomplete, since it's unfortunately impossible to understand what you're actually trying to report/ask here.

**Comment by timvandermeij** [comment]
> Is there any way to prevent files from being downloaded.

In general, no. The contents of the PDF need to be present for PDF.js to render it and thus it's interceptable.
