### ISSUE TITLE
External links are not active although they are in Chrome pdf viewer and Accrobat Reader

### ISSUE THREAD

**Issue by daumain** [mozilla/pdf.js#10695]
Attach (recommended) or Link to PDF file here:
[link_problems.pdf](https://github.com/mozilla/pdf.js/files/3021529/link_problems.pdf)

![image](https://user-images.githubusercontent.com/31903382/55216541-51a73880-51fd-11e9-9cb8-f136b901d4b2.png)

When opened in Chrome, the external link on the last page (see picture) is clickable although in pdf.js it is not (neither directly in Firefox). Anythink I should enable in pdf.js.

Note, the link is of type myapp://link2document and not an http:// on.

Thank you for your help.

**Comment by Snuffleupagus** [comment]
Those annotations contain URIs with a non-standard `amos://` protocol (which none of the browsers I've tried are able to open directly anyway), and PDF.js will purposely for security reasons only display link annotations with white-listed standard protocols; please refer to https://github.com/mozilla/pdf.js/blob/b4c3b9459216c57aeb50f237d4f5857d92a08dcb/src/shared/util.js#L335-L370

Hence I believe that this issue is thus INVALID, or WONTFIX, since the default PDF.js library won't be adding non-standard protocols to the white-list.

---

In a custom implementation of PDF.js you can use the `unsafeUrl` property, to access the original URI, on the annotation objects that's returned by the `getAnnotations` method; see https://github.com/mozilla/pdf.js/blob/b4c3b9459216c57aeb50f237d4f5857d92a08dcb/src/display/api.js#L948-L953

**Comment by daumain** [comment]
Thanks for the super fast and very helpfull answer :) 👍
