### ISSUE TITLE
The file does not display correctly on Wndows XP

### ISSUE THREAD

**Issue by letsevi** [mozilla/pdf.js#10701]
Attach (recommended) or Link to PDF file here: 
[problemFileXP.pdf](https://github.com/mozilla/pdf.js/files/3028836/problemFileXP.pdf)

Configuration:
- **Google Chrome 49.0.2623.112 m**
- Operating system and its version: **Windows XP Home Edition v.2002 SP3**
- PDF.js version: 2.0.943 **(1.8.188 work correctly)**
- Is a browser extension: No

![System](https://user-images.githubusercontent.com/8323814/55320931-1026bf80-5481-11e9-8362-a85161557d4c.png)
![Browser)](https://user-images.githubusercontent.com/8323814/55320996-34829c00-5481-11e9-83bf-136bcb885bbe.png)

Steps to reproduce the problem:
1. Try to open the file

What is the expected behavior? (add screenshot)
![Expected-1-8-188](https://user-images.githubusercontent.com/8323814/55321064-63007700-5481-11e9-83ba-2f4da6e9642c.png)
What went wrong? (add screenshot)
![Wrong-2.0.943](https://user-images.githubusercontent.com/8323814/55321151-9fcc6e00-5481-11e9-8651-cd59b239f5cb.png)

**Comment by Snuffleupagus** [comment]
> Operating system and its version: **Windows XP Home Edition v.2002 SP3**

According to e.g. https://en.wikipedia.org/wiki/Windows_XP#End_of_support, that OS version has been officially unsupported for a couple of years now. Hence it's not unfortunately not realistic to expect the PDF.js project to support running the library on a platform that's old enough for even the manufacturer to cease support; this issue is thus INVALID.
