### ISSUE TITLE
When using nameddest in url, the initial zoom will be 100%

### ISSUE THREAD

**Issue by yelluo** [mozilla/pdf.js#10748]
Without nameddest=2 in url, the initial zoom can be set in the viewer.html (option of scaleSelect), or via adding zoom=page-width in url. However, when using nameddest=2 in url, both methods failed to set the initial zoom, which will be 100%.

viewer.html?file=2019.pdf#zoom=page-width&nameddest=2

**Comment by Snuffleupagus** [comment]
> However, when using nameddest=2 in url, both methods failed to set the initial zoom, which will be 100%.

Given that the default zoom level is `auto`, this would actually suggest that the named destination is setting the zoom level exactly as intended (by the PDF specification).

However, there's unfortunately no actionable information provided here and the issue is thus INVALID; please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

**Comment by yelluo** [comment]
I have confirmed that the named destination contains the zoom level when it was created in the PDF file. Pdf.js will use this zoom level and ignore the default zoom level in viewer.html and the zoom parameter in the url. 

I suggest that the zoom parameter in the url can overwrite the zoom level of the named destination because in some case we can not modify the PDF file.
