### ISSUE TITLE
Unexpected server response (612) on loading pdf by using query url file parameter

### ISSUE THREAD

**Issue by leo19930826** [mozilla/pdf.js#10740]
we used the new PDFJS version(1.10.100) to load file at the mobile side, but we found many pdf files are not properly loaded.and I google it but I can't find the PDFJS error code named 612.so I am confussed.the pdf file can download properly,but can't view it online at the mobile side.

result in an error message:
PDF.js v1.10.100 (build: ea29ec83)
Message: Unexpected server response (612) while retrieving PDF.

**Comment by Snuffleupagus** [comment]
> we used the new PDFJS version(1.10.100)

As can be seen in https://github.com/mozilla/pdf.js/releases, the latest *stable* release as of this writing is `2.0.943`, and the version you're using is no longer supported. Hence you'll need to update to the latest release, before asking for further assistance here.

> and I google it but I can't find the PDFJS error code named 612

Note that it's the *server* which responds with that error (when the file is requested), hence this suggests a configuration problem on the server itself which the PDF.js library obviously cannot fix/support.

---

Finally, this issue is missing too many of the required details to be actionable in its current form. When opening an issue you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, and in this case you'll also need to follow https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
