### ISSUE TITLE
The canvas will cover the scrollbar, and the scrollbar cannot be seen

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#10744]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version: Chrome or Safari
- Operating system and its version: Mac OS
- PDF.js version: the latest
- Is a browser extension: no

Steps to reproduce the problem:
1. set the scrollbar shown when scrolling, not always.
![image](https://user-images.githubusercontent.com/18492951/56258111-0ba90a80-6101-11e9-81ba-c7a3c0cc811e.png)

2.keep zoomin in.

3.the scrollbar will be covered

What is the expected behavior? (add screenshot)
the scrollbar can be seen. 
![image](https://user-images.githubusercontent.com/18492951/56258401-09937b80-6102-11e9-9dff-39c32a13a4e5.png)

What went wrong? (add screenshot)
the scrollbar disappeared. 
![image](https://user-images.githubusercontent.com/18492951/56258379-f2ed2480-6101-11e9-9884-c95f4ec2f9de.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Chrome or Safari

The scrollbar is part of the browser UI and a web-page, which is essentially what the PDF.js viewer is, shouldn't be able to affect that. Hence this issue is INVALID, since it cannot be fixed here, and needs to be reported directly to the browser vendors instead.

---

> PDF.js version: the latest

For future reference: this *needs* to state the actual version number, since "the latest" is of very limited use.
