### ISSUE TITLE
Pdfjs In safari, if there is a watermark, it can't be loaded,

### ISSUE THREAD

**Issue by caihuoche** [mozilla/pdf.js#10749]
Configuration:

Web browser and its version:
   safari Any version
Operating system and its version:
   centos 7
PDF.js version:
   v2.0.943
Steps to reproduce the problem: 1. 2.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/24805030/56420965-dd7b2480-62d2-11e9-801f-491c0db1b9f1.png)
This is the normal display of Google Chrome.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/24805030/56421027-321e9f80-62d3-11e9-8962-95d8e8c8634d.png)
This is in safari, by comparing Google Chrome, you can see too many loaded components, as shown in the red circle, if I delete these two components on the server, then the file can be displayed normally, but there is no Watermark

Pdfjs In safari, if there is a watermark, it can't be loaded, and the loading is very slow. It can be seen from the network that it is the reason of two components (UniGB-UTF16-H.bcmap, Adobe-GB1-UCS2.bcmap), how can I solve it?

**Comment by Snuffleupagus** [comment]
Please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, as-is there's no actionable information provided and the issue is thus INVALID.

> It can be seen from the network that it is the reason of two components (UniGB-UTF16-H.bcmap, Adobe-GB1-UCS2.bcmap), how can I solve it?

The best guess, given the missing information, would be that https://github.com/mozilla/pdf.js/issues/10660#issuecomment-475185456 is relevant here as well.
