### ISSUE TITLE
pdf.js renders entire document when jumping to the last page

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#10763]
I'm the author of Polar (https://getpolarized.io/)

and we're using pdf.js pretty heavily.

I noticed a really weird but which only manifests itself on our desktop version.

if I have a large PDF (160MB) and I jump to the last page, it seems to render ALL the pages before showing the last page and is insanely slow.

Our web app does CORS properly and only loads the right pages and loads super fast even when jumping around.

The desktop apps runs under Electron but doesn't do anything weird. Just serves up the file via express / HTTP and uses does range requests properly.  IT's just insanely slow.

Here's what a CPU profile looks like:

![image](https://user-images.githubusercontent.com/45447/56666556-ff710000-6660-11e9-95fe-9310947a0a0c.png)

this gets much worse under large documents.  We have one user trying to work with a 900 page PDF and it just brought his machine to a crawl and had to uninstall.

**Comment by burtonator** [comment]
BTW.. the gap at the beginning was when I just paused for a moment as my mouse got stuck.  CPU goes to 100% CPU and the last page takes a the entire time to load with just a spinning progress wheel.

**Comment by Snuffleupagus** [comment]
> if I have a large PDF (160MB) and I jump to the last page, it seems to render ALL the pages before showing the last page and is insanely slow.

That shouldn't be happening in the default viewer, available at https://mozilla.github.io/pdf.js/web/viewer.html, hence it's unfortunately not clear that this is actually a valid issue for the PDF.js project. 

> The desktop apps runs under Electron but doesn't do anything weird.

Unfortunately, it's quite unlikely that that's a configuration the PDF.js project contributors can realistically provide any support/help with.

---

In case it's helpful, please note that the default viewer doesn't actually scroll "normally" when e.g. the <kbd>Home</kbd>/<kbd>End</kbd> keyboard buttons are used but rather go directly to the first/last page instead: see https://github.com/mozilla/pdf.js/blob/762c58e0fcfdc8f3fd23ce22a15ee044d8d372ec/web/app.js#L2353-L2367

**Comment by burtonator** [comment]
> That shouldn't be happening in the default viewer, available at https://mozilla.github.io/pdf.js/web/viewer.html, hence it's unfortunately not clear that this is actually a valid issue for the PDF.js project.

I would generally agree but pdf.js shouldn't revert to this mode so we're definitely triggering a bug.  

I think I figured out what's happening based on your feedback.

If I scroll the document very slowly, all the way to the end, it attempts to render EVERY page.

Even pages that are no longer needed because they will just be discarded. 

Jumping from page 1 to 100 is pretty fast.

Scrolling through slowly is insanely slow.

**Comment by Snuffleupagus** [comment]
> I would generally agree but pdf.js shouldn't revert to this mode so we're definitely triggering a bug.

What does "revert to this mode" actually mean here, since you can't very well not render the document when normal scrolling happens? Also, to clarify: Is this problem actually happening in the default viewer, or only in your desktop application (given the difficulty in supporting the latter)? 

> If I scroll the document very slowly, all the way to the end, it attempts to render EVERY page.

Sure, but that shouldn't be a problem in the default viewer since pages that are no longer visible will be removed *and* their rendering stopped; see e.g. https://github.com/mozilla/pdf.js/blob/762c58e0fcfdc8f3fd23ce22a15ee044d8d372ec/web/base_viewer.js#L515 and https://github.com/mozilla/pdf.js/blob/762c58e0fcfdc8f3fd23ce22a15ee044d8d372ec/web/base_viewer.js#L69-L103

**Comment by burtonator** [comment]
ok.. turns out THIS was the issue:

https://github.com/mozilla/pdf.js/issues/10741

which is fixed just not in my release.

having is isNodeJS return false fixed the problem so far.  

Please keep this bug open for a bit longer.  I'll fully document this and verify but 99% certain this fixes it.  The bug might help other people in the future. 

Glad this is fixed though!  This one was stressing me out!!!

**Comment by Snuffleupagus** [comment]
> Please keep this bug open for a bit longer.

In this bug tracker it's customary to always close fixed issues directly, since having a bunch of solved issues open makes tracking actual bugs more difficult.

Furthermore, since there's still no indication that the issue reported here affects the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) directly, that provides even less justification for keeping this open.

@timvandermeij Since it's been over a week, should we just close this out now?

**Comment by timvandermeij** [comment]
Yes, let's do that. If there are indications that there is in fact a problem in PDF.js, we can always reopen.
