### ISSUE TITLE
PDF attachments not opened on iOS

### ISSUE THREAD

**Issue by gpbaratto** [mozilla/pdf.js#10764]
Attach (recommended) or Link to PDF file here:
any pdf that has pdf attachments

Configuration:
- Web browser and its version: Safari latest version
- Operating system and its version: iOS 12.2
- PDF.js version: v2.0.9.4.3.
- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdf with attachments
2. Open a pdf attachment

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/40430098/56667551-57822380-66ae-11e9-92fd-be41cf4006e4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

The pdf viewer does not open pdf attachments on ios, any browser you use. On android it opens them without problems.

**Comment by Snuffleupagus** [comment]
> The pdf viewer does not open pdf attachments on ios, any browser you use. On android it opens them without problems.

That would suggest a platform issue, rather than a problem with the PDF.js default viewer; hence this issue may be INVALID from the PDF.js point of view.
Furthermore, note that the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) was developed mainly for desktop usage and may not be a good fit for mobile devices.
