### ISSUE TITLE
Clarity issue or blur fonts when not zoomed 

### ISSUE THREAD

**Issue by afsinak** [mozilla/pdf.js#10777]
Attach (recomme
![Screenshot 2019-04-30 at 10 14 20 AM](https://user-images.githubusercontent.com/46594945/56941218-be7d5d80-6b30-11e9-8e0d-c4351d52523b.png)
nded) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome (latest version)
- Operating system and its version: mac 
- PDF.js version: 1.0.1040
- Is a browser extension:

Steps to reproduce the problem:
1. render any pdf.
2.check the font clarity without zoom in.

What is the expected behavior? 
![Screenshot 2019-04-30 at 10 18 41 AM](https://user-images.githubusercontent.com/46594945/56941315-5d09be80-6b31-11e9-9c23-8da91fb2db1d.png)
need better clarity for fonts.

What went wrong? clarity goes away when zoomed out.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Without access to the PDF file in question, this issue is invalid. (In #10769 you were specifically instructed to provide *all* information from [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.)

> PDF.js version: 1.0.1040

Finally, that version is no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases
