### ISSUE TITLE
how to remove comment note（yellow block） from pdf file?

### ISSUE THREAD

**Issue by yuweiming2016** [mozilla/pdf.js#10776]
Attach (recommended) or Link to PDF file here:
![image](https://user-images.githubusercontent.com/22490427/56937782-3186d400-6b31-11e9-83ff-0fcd032dda0a.png)
[note.docx](https://github.com/mozilla/pdf.js/files/3129738/note.docx)

Configuration:
- Web browser and its version: chrome
- Operating system and its version: linux centos 7.2
- PDF.js version:1.10.88
- Is a browser extension:no

Steps to reproduce the problem:
1. open attach pdf file by pdfjs

What is the expected behavior? (add screenshot)
remove comment note
What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [note.docx](https://github.com/mozilla/pdf.js/files/3129738/note.docx)

That's not a PDF file, but a Microsoft Word file; hence this issue is invalid.
Furthermore, as mentioned in the FAQ PDF.js doesn't contain any functionality for editing PDF files; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations

> PDF.js version: 1.10.88

Finally, that version is no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases
