### ISSUE TITLE
pspdfkit performs much better

### ISSUE THREAD

**Issue by songtzu** [mozilla/pdf.js#10775]
I compared the same pdf file post by issue 10719 below.
[#10719](https://github.com/mozilla/pdf.js/issues/10719)
 pspdfkit performs much better than pdf.js in which pdf.js shows obviously waiting progress.  

using
[pspdfkit](https://web-examples.pspdfkit.com/custom)

[pdf.js](https://mozilla.github.io/pdf.js/web/viewer.html)

according to the official doc, pspdfkit take web assembly as their solution.  it's not just render pdf to image, also it has text layer.

**Comment by Snuffleupagus** [comment]
The performance of the particular file is already tracked in issue #10719, which you are apparently aware of, hence this will be closed as a duplicate.

*For future reference:* Please refrain from knowingly open duplicate issues, since that's of no use. Furthermore, this issue is missing too much of the required information to be valid; see https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
