### ISSUE TITLE
ReadableStream fails in Cordova Windows 10 app

### ISSUE THREAD

**Issue by johnsonsw100** [mozilla/pdf.js#10797]
My code uses pdfjs-1.9.426-dist and works great in Chrome, Firefox, Edge, and Safari.  I use the same JavaScript in Cordova apps and it works great in iOS and Android but NOT in Windows 10.

When loading the Windows 10 app I get this error:

.../www/pdfjs-1.9.426-dist/build/pdf.worker.js   0x800a138a - JavaScript runtime error: Function expected   This error occurs in lines that contain "new ReadableStream({..."

All calls to pdfjs subsequently fail (e.g., PDFJS.getDocument ).

Is there any way around this?

**Comment by Snuffleupagus** [comment]
> My code uses pdfjs-1.9.426-dist

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases

> JavaScript runtime error: Function expected This error occurs in lines that contain "new ReadableStream({..."

Please note that native support for `ReadableStream` is tested before use, see https://github.com/mozilla/pdf.js/blob/83f6de3cf8bcb39e05847321f45b44446bd9a858/src/shared/streams_polyfill.js#L24-L37 and that it's polyfilled otherwise, see https://github.com/mozilla/pdf.js/blob/83f6de3cf8bcb39e05847321f45b44446bd9a858/src/shared/streams_polyfill.js#L52-L53

> [...] it works great in iOS and Android but NOT in Windows 10.

This would indicate a `ReadableStream` bug in Windows 10, rather than in the PDF.js library, given the code referenced above.

---

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by johnsonsw100** [comment]
Thank you for your quick response.  Before submitting this question, I tried upgrading to the latest pdf.js release but experienced the same issue. I suspect you're right that Windows 10 Corodova apps don't support ReadableStream (see https://developer.mozilla.org/en-US/docs/Web/API/ReadableStream), assuming Windows 10 Corodova apps use Edge Mobile.

My question is: is there anyway around this?  Can pdf.js work without using ReadableStream?  Or do you know of an reasonable alternative to pdf.js that offers function like .getDocument and .getPage?

I'd greatly appreciate any help.

**Comment by Snuffleupagus** [comment]
> I suspect you're right that Windows 10 Corodova apps don't support ReadableStream

But in that case PDF.js should be falling back its built-in `ReadableStream` polyfill, as mentioned in https://github.com/mozilla/pdf.js/issues/10797#issuecomment-490522364.

> Can pdf.js work without using ReadableStream?

No, unfortunately not.

---

Could you please link to the *exact* line, in the source code, where the failure occurs?

**Comment by Snuffleupagus** [comment]
> Could you please link to the _exact_ line, in the source code, where the failure occurs?

Without an answer to this question, and given that every other platform/browser works, this should probably be closed as INCOMPLETE.
