### ISSUE TITLE
Multiple syntax, invalid, & missing related error during compilation

### ISSUE THREAD

**Issue by marknovem** [mozilla/pdf.js#10792]
I am using JSP on my system. One of my objective is to provide reports generated by the system. So i decided to use PDF.js, the prebuild stable one (Stable v2.0.943) to render the PDF file. During the rendering process a multiple error appears coming from ha pdf.js script. So i decided to download the latest yuicompressor from [https://github.com/yui/yuicompressor/releases] version 2.4.8. From the terminal i run: 
java -jar yuicompressor-2.4.8.jar pdf.js -o pdf.min.js    
and it resulted to a multiple lines of error messages related to syntax.. Sample output:
[ERROR] in pdf.js
  22943:9:invalid return
[ERROR] in pdf.js
  22944:1:syntax error
[ERROR] in pdf.js
  22946:7:syntax error
[ERROR] in pdf.js
  22967:86:invalid property id
[ERROR] in pdf.js
  23007:40:missing name after . operator
[ERROR] in pdf.js
  23385:25:missing name after . operator
[ERROR] in pdf.js
  23387:34:missing name after . operator
[ERROR] in pdf.js
  23388:19:missing ; before statement
[ERROR] in pdf.js
  23389:50:missing ; before statement

Is there any link for a solution or related problem with solution to this?

**Comment by Snuffleupagus** [comment]
> [...] the latest yuicompressor from [https://github.com/yui/yuicompressor/releases] version 2.4.8.

This points to a bug in a particular minifier, since it probably doesn't support modern JavaScript features, which is a bug in the minifier *itself* and not in the PDF.js library. Hence this issue is INVALID here, and needs to be reported to the developers of the minifier instead.

The only minifier that the PDF.js project currently supports is https://github.com/terser-js/terser, as can be seen in build scripts: https://github.com/mozilla/pdf.js/blob/83f6de3cf8bcb39e05847321f45b44446bd9a858/gulpfile.js#L798-L800 a pre-built minified version of the PDF.js library can be found in https://github.com/mozilla/pdfjs-dist/tree/master/build (files with `.min` in their names).
