### ISSUE TITLE
How to disable web workers on v2.1.266?

### ISSUE THREAD

**Issue by dschissler** [mozilla/pdf.js#10808]
I'm currently trying to disable the web workers to use "fake web worker" using Chromium for see if it fixes #9048 on `2.1.266` but I can't figure out the API for it.  When I set `GlobalWorkerOptions.workerSrc` to false then the page refreshes over and over again on every browser.  Is there a bug or am I missing something in a changed API?

**Comment by dschissler** [comment]
Also if I don't set `workerSrc` then the browser reloads/refreshes with the message `Error: Setting up fake worker failed: "window.pdfjsWorker is undefined".`

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that disabling of workers have never been an officially supported configuration, but rather only exists for compatibility with older browsers and/or Node.js.

In PDF.js version `2.0` changes were made to make it more difficult to disable workers, please refer to PR #9385 and the related discussion. (The code should give some idea of how the API/viewer implements disabling of workers for *debugging* purposes.)

> When I set `GlobalWorkerOptions.workerSrc` to false

That's never been a supported configuration, as far as I know...

---

Finally, this issue is missing most the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and there's also no working example provided; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by MillerSvt** [comment]
What if I need to use the library in Service Worker? You can't create a Worker from it.
