### ISSUE TITLE
PDF viewer doesn't render in production builds

### ISSUE THREAD

**Issue by kwayebopp** [mozilla/pdf.js#10803]
Configuration:
- Web browser and its version: **Firefox 66.0.4**
- Operating system and its version: **Pop!_OS 18.10 (similar to Ubuntu 18.10)**
- PDF.js version: **2.0.943** using prebuilt pdfjs-dist
- Is a browser extension: **No**

Steps to reproduce the problem:
1. Follow the instructions in [this tutorial ](https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/)(should take less than 20 minutes)
2. Run the application on dev server
3. Build and run the production build of the application 

What is the expected behavior? (add screenshot)
The PDF viewer renders as expected when running on the dev server. Ignore the purple dot, that's from a custom annotation layer.

![image](https://user-images.githubusercontent.com/12959564/57473266-6dbae280-725d-11e9-8064-d77c92b8c308.png)

What went wrong? (add screenshot)
The PDF viewer doesn't render at all for the production build. I'd add a screen shot, but it's an empty iframe.

**Comment by Snuffleupagus** [comment]
> Follow the instructions in [this tutorial ](https://www.pdftron.com/blog/react/how-to-build-a-react-pdf-viewer/)(should take less than 20 minutes)

That example is not an official one, but rather provided by a third-party, and as such it's unfortunately not possible for the PDF.js project to provide support for it. 

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by kwayebopp** [comment]
@Snuffleupagus 

If I recreate a codesandbox or jsfiddle with the tutorial code, would I still not be able to receive guidance?

**Comment by Snuffleupagus** [comment]
> If I recreate a codesandbox or jsfiddle with the tutorial code,

Considering that the PDF.js project only uses "regular" JavaScript, and that the example you're attempting to use seems to be based on React, the likelihood that a PDF.js contributor will be able to offer assistance cannot be guaranteed. (The people you're interacting with here are volunteers, and not paid support staff.)

Also, please keep in mind that the "PDFTron" project seems to be mostly interested in selling you there own PDF/document viewing solutions. Hence it *may* not be in their interest to provide a good PDF.js example, and it's also unclear which version of PDF.js the example was based on.

> [...] would I still not be able to receive guidance?

As long as the example is *small and self-contained* a contributor *may* be able to offer help, but it cannot be guaranteed since it's quite probable that the issue lies in the React code.

**Comment by kwayebopp** [comment]
> The people you're interacting with here are volunteers, and not paid support staff.

I am aware and I thank you for taking the time to help me!

> As long as the example is _small and self-contained_ a contributor _may_ be able to offer help, but it cannot be guaranteed since it's quite probable that the issue lies in the React code.

Here is a minimal implementation  of the PDFTron tutorial. In order to build a production version, you may need to download the contents and run `npm react-scripts build"` from the project root:

https://codesandbox.io/s/oo4j6xl1lq?fontsize=14

I understand the folks at PDF.js won't necessarily be able to help me, but I appreciate any and all assistance with this.

**Comment by Snuffleupagus** [comment]
> In order to build a production version, you may need to download the contents and run `npm react-scripts build` from the project root:

If it works in one React configuration, but not another one, that would point rather clearly to a problem with React rather than in the PDF.js library (since otherwise it *should* be consistently broken). In cases such as these, I'd assume that you'd probably get more useful insight from people actually familiar with React.

(Also, an example that requires both downloading of code *and* setting up React locally is probably not a great reduced test-case, but maybe that's just me :-)

**Comment by kwayebopp** [comment]
Ah, ok. I'll keep hunting for a solution. Closing this for now!

**Comment by i-fuyun** [comment]
@kwayebopp Excuse me, How to solve this problem?
