### ISSUE TITLE
Messy code in the text layer (canvas layer looks fine)

### ISSUE THREAD

**Issue by coolKIH** [mozilla/pdf.js#10812]
**Attach (recommended) or Link to PDF file here:** http://www.hkexnews.hk/listedco/listconews/GEM/2003/0313/GLN20030313002_C.pdf

**Configuration:**
- Web browser and its version: Chrome/74.0.3729.131
- Operating system and its version: macOS Version 10.14.4
- PDF.js version: Stable (v2.0.943)
- Is a browser extension: No

**Steps to reproduce the problem:**
1. Open the problem PDF on the PDF.JS web viewer
2. Select and copy a piece of text on the top of the first page of the PDF, then I've got some messy code in my clipboard rather than the characters displaying on the viewer.
3. When I "inspect" the elements in the text layer using Chrome Developer Tools, I can see that most of the characters in the text layers are not correct.

**What is the expected behavior? (add screenshot)**
The text in text layers should be exactly what can be read in the PDF.
The first page of the PDF looks like this:
![Screen Shot 2019-05-13 at 12 25 46 PM](https://user-images.githubusercontent.com/20931311/57595905-5f7d0700-757a-11e9-8bfd-ad12dc1acc01.png)

**What went wrong? (add screenshot)**
The text in text layers are messy code, which are not what can be read in the PDF. If I copy and paste them to my clipboard from the viewer, I'll got something like **!"#$%&'()*+,-.+/#012345&65*1**. 
If I use some JS code to get the inner text of the first page of the PDF, I'll get:
![Screen Shot 2019-05-13 at 12 26 13 PM](https://user-images.githubusercontent.com/20931311/57595941-889d9780-757a-11e9-82c9-193ed1bcc333.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Unfortunately there isn't any meaningful/complete `ToUnicode` data to be found in *any* of the fonts in this PDF file, and it's thus impossible for text-selection/extraction to work correctly in this case.

Please note that this is a limitation of a *specific* PDF file, and not of the PDF.js library (or any other PDF viewer), and without the PDF file itself containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.

**Comment by coolKIH** [comment]
> Unfortunately there isn't any meaningful/complete `ToUnicode` data to be found in _any_ of the fonts in this PDF file, and it's thus impossible for text-selection/extraction to work correctly in this case.
> 
> Please note that this is a limitation of a _specific_ PDF file, and not of the PDF.js library (or any other PDF viewer), and without the PDF file itself containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.

Thanks for the explanation! It's really helpful.

I wonder if there is a way to detect such unreadable unicode characters from the converted text? I noticed that the unicode **!"#$%&'()*** appear many times in the PDF that I attached. Why are **!"#$%&'()***? Are they a special pattern that I can use to recognize messy code in the PDF?

**Comment by Snuffleupagus** [comment]
> I wonder if there is a way to detect such unreadable unicode characters from the converted text?

The best/easiest way, in general, is unfortunately to have a human doing the actual comparison. Otherwise the only possible solution would probably be to use OCR (which obviously won't produce perfect results).

> I noticed that the unicode **!"#$%&'()*** appear many times in the PDF that I attached.

Unfortunately, with fonts like these, it's arbitrary what textLayer characters you'll end up with and no generally discernible pattern will exist for different PDF files (or even different fonts in the same file really).

How PDF viewers should handle this kind of situation is not even properly specified, please refer to the following excerpt from the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=301):
> If  these  methods  fail  to  produce  a  Unicode  value,  there  is  no  way  to  determine  what  the  character  code  represents in which case a conforming reader may choose a character code of their choosing.

**Comment by coolKIH** [comment]
> > I wonder if there is a way to detect such unreadable unicode characters from the converted text?
> 
> The best/easiest way, in general, is unfortunately to have a human doing the actual comparison. Otherwise the only possible solution would probably be to use OCR (which obviously won't produce perfect results).
> 
> > I noticed that the unicode **!"#$%&'()*** appear many times in the PDF that I attached.
> 
> Unfortunately, with fonts like these, it's arbitrary what textLayer characters you'll end up with and no generally discernible pattern will exist for different PDF files (or even different fonts in the same file really).
> 
> How PDF viewers should handle this kind of situation is not even properly specified, please refer to the following excerpt from the [PDF specification](https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=301):
> 
> > If  these  methods  fail  to  produce  a  Unicode  value,  there  is  no  way  to  determine  what  the  character  code  represents in which case a conforming reader may choose a character code of their choosing.

Thanks! PDF is really a wonderful and mysterious land!
