### ISSUE TITLE
Clarification on 2.1 going non-beta?

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#10819]
I just need a clarification for when 2.1 is going non-beta. I also noticed that the demo version is running 2.2.x.   I assume 2.2.x is alpha?

**Comment by Snuffleupagus** [comment]
There's generally *very* little difference, as far as stability is concerned, between the stable/pre-release version (since no code lands without e.g. all tests passing).
Firefox Nightly, for example, is always using what's essentially the latest `master` version of the PDF.js library. Hence the decision to use "stable" or "pre-release" versions is really up each implementer (and note that unless something is *really* broken, patches are generally not back-ported).

**Comment by timvandermeij** [comment]
I do agree that we should make a new release again. @brendandahl If we follow the release process, does the existing pre-release automatically become stable (on GitHub and NPM) or do we need to do that ourselves somehow?

**Comment by Snuffleupagus** [comment]
> I do agree that we should make a new release again.

In that case, how about making sure that #10794 is landed first?

**Comment by brendandahl** [comment]
> I do agree that we should make a new release again. @brendandahl If we follow the release process, does the existing pre-release automatically become stable (on GitHub and NPM) or do we need to do that ourselves somehow?

If everything is working correctly it should.

**Comment by Snuffleupagus** [comment]
I'd suggest trying to get PRs #10850 and #10851 (maybe #10879 as well) landed as soon as possible, and then just create a new release immediately afterwards (before considering landing any larger items).

**Comment by timvandermeij** [comment]
Yes, I agree. Those three are mostly done, other PRs can wait. @brendandahl Could you fix up your two PRs?

**Comment by Camo30** [comment]
I'm waiting for that too, but it seems it got stuck. Would be great to get a new release soon

**Comment by timvandermeij** [comment]
I'm planning to make a new release next Wednesday.

**Comment by timvandermeij** [comment]
Version 2.1 is now stable; refer to https://github.com/mozilla/pdf.js/releases.
