### ISSUE TITLE
PDFViewerApplication.ScrollMode method to switch on call

### ISSUE THREAD

**Issue by mkubdev** [mozilla/pdf.js#10815]
Configuration:
- Operating system and its version: Windows10
- PDF.js version: latest

## Hi, i'm trying to extract some pdfjs commands. There is a way to call a method to switch scrollMode with PDFViewerApplication ?
I'm trying to call it via : 
`PDFViewerApplication.pdfViewer.scrollMode = scrollMode.HORIZONTAL;` 
But it doesn't work.

* In **viewer.js** line 3420, we can see that ScrollMode var as 4 option :

`var ScrollMode = {
  UNKNOWN: -1,
  VERTICAL: 0,
  HORIZONTAL: 1,
  WRAPPED: 2
};`

How can i set the ScrollMode view ? Please advise

*For example: to rotate Left your PDF, you can call **`PDFViewerApplication.rotatePages(-90);`***
Similar to : #9178

**Comment by timvandermeij** [comment]
You should use the `PDFViewerApplication.pdfViewer.scrollMode` setter. This is internally also used in https://github.com/mozilla/pdf.js/blob/fef86cc3e327f0554136482fee901b52909fa37a/web/app.js#L1990, which is the handler for pressing the button in the interface. You can find the underlying setter at https://github.com/mozilla/pdf.js/blob/master/web/base_viewer.js#L1072. If that doesn't work, then you'll need to provide a running example, otherwise we can't help out.

**Comment by mkubdev** [comment]
Thank you! I just need to return PDFViewerApplication.pdfViewer.scrollMode = {-1,0,1,2} to get the desired mod.
