### ISSUE TITLE
How to stop PDF turns into 180 Degree when using page navigation

### ISSUE THREAD

**Issue by viral-w3nuts** [mozilla/pdf.js#10822]
Attach (recommended) or Link to PDF file here:
http://testchat32.tk/PDF/ 

Configuration:
- Web browser and its version: Latest Chrome and Firefox
- Operating system and its version: Windows 10
- PDF.js version: 1.5.188
- Is a browser extension: No

Steps to reproduce the problem:
1. Open this link and select PDF with multi page. Now go back to previous page from navigation: http://testchat32.tk/PDF/ 

What is the expected behavior? 
Currently it rotates whole page 180 Degree 

What went wrong? 
For example see this video : https://youtu.be/4w0276IFv58

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://testchat32.tk/PDF/ 

Question Ref. : https://stackoverflow.com/questions/56132141/pdf-js-how-to-stop-pdf-turns-into-180-degree-when-using-page-navigation
 
Any help or suggestion are appreciated. Many thanks

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.5.188

That version is a couple of *years* old, and is consequently no longer officially supported.
Hence you'll need to update to the *latest* version of the PDF.js library, please find the latest stable/pre-releases at https://github.com/mozilla/pdf.js/releases, before asking for help (otherwise this issue in invalid).
