### ISSUE TITLE
Can't view PDFs on iOS Safari in Fullscreen

### ISSUE THREAD

**Issue by ghost** [mozilla/pdf.js#10831]
When viewing the current PDF.js demo in Safari 12 on iOS I can't enter the fullscreen mode.
(https://mozilla.github.io/pdf.js/web/viewer.html)

Configuration:
- Web browser and its version: iOS Safari 12
- Operating system and its version: iOS 12.2
- PDF.js version: I guess the newest, because the current demo is affected

Steps to reproduce the problem:
1. Open pdf with pdf.js on iPhone
2. Try to go into fullscreen

What is the expected behavior?
PDF.js shows the fullscreen button and it allows to view the pdf in fullscreen.

What went wrong?
No fullscreen button is shown and even if I bypass the compatibility check for fullscreen and am able to display it then nothing happens when clicking on it.

Related: #4779

**Comment by n1kio** [comment]
Anything new on this issue, or pointers on how to fix it?

**Comment by jcalado** [comment]
Any news on this? Full screen button still missing on safari.

**Comment by TwisterMc** [comment]
Any news?

**Comment by kellertobias** [comment]
any updates here?

**Comment by Snuffleupagus** [comment]
> Web browser and its version: iOS Safari 12
> Operating system and its version: iOS 12.2

Given that this appears to be specific to a *particular* platform/browser combination, rather than a general PDF.js bug, since otherwise you'd expect it to consistently broken everywhere; the question is if this is really an actionable/fixable issue *here*!?

Please keep in mind that we *really* want to avoid adding any sort of hacks to the main code-base, for reasons of code readability and maintainability, for these types of platform/browser-specific issues.
