### ISSUE TITLE
Update core-js dependencies

### ISSUE THREAD

**Issue by RuelleAnthony** [mozilla/pdf.js#10842]
Hi, 

pdf.js is not working with core-js version > 2.

In compatibility.js file, pdf.js uses polyfill from core-js 2:
- require('core-js/fn/weak-map');
- require('core-js/fn/number/is-integer');
- require('core-js/fn/number/is-nan');
etc...

Can you update your project to use core-js version 3 ?

This problem blocks me to update webpack, babel to the latest version of my project...

Thank you in advance

**Comment by Snuffleupagus** [comment]
> Can you update your project to use core-js version 3?

Because of the changes between `core-js` versions 2 and 3, it's quite unlikely that this will be a simple drop-in-replacement on the PDF.js side (based on briefly looking into issue #10490). 
It may even be necessary to update/replace the `SystemJS` dependency *first*, possibly making this a somewhat large effort (given the current dev/build system used).

**Comment by timvandermeij** [comment]
Closing since the migration to `core-js` version 3 is tracked in the issue above already.
