### ISSUE TITLE
pdf.js prevents Ctrl-K prefix inside vscode

### ISSUE THREAD

**Issue by memeplex** [mozilla/pdf.js#10861]
Ctrl-K is an important prefix key in vscode. It starts keyboard sequences for many common commands. The LaTeX Workshop extension uses pdf.js as a previewer. When a pdf.js tab inside vscode has focus many vscode shortcuts stop working, particularly Ctrl-K. For example, typing Ctrl-K Ctrl-T usually opens a theme selector, but inside pdf.js it's as if the initial Ctrl-K was lost and the entire sequence performs the operation bound to Ctrl-T instead.

AFAICS pdf.js doesn't use Ctrl-K (it uses K without modifiers though): https://github.com/mozilla/pdf.js/blob/fef86cc3e327f0554136482fee901b52909fa37a/web/app.js#L2152

There is also report https://github.com/mozilla/pdf.js/issues/979, a bug apparently fixed. So I don't know what to do with this. Do you have any idea why this might be happening?

Steps to reproduce the problem:

1. Install VSCode 1.34
2. Install LaTeX Workshop 7.0.0
3. Create a simple LaTeX document
4. Compile it and open the previewer (Ctrl-Alt-V)
5. In the previewer (pdf.js) type Ctrl-K Ctrl-T.

I'm on Arch Linux but I'll ask the LaTeX Workshop developers to fill the rest of this:

Configuration:
- Web browser and its version:
- PDF.js version:
- Is a browser extension:

**Comment by Snuffleupagus** [comment]
> AFAICS pdf.js doesn't use Ctrl-K (it uses K without modifiers though):

Correct, <kbd>Ctrl</kbd>+<kbd>K</kbd> isn't used in the PDF.js default viewer and it's thus difficult to understand how this is a valid PDF.js bug. It might be that "LaTeX Workshop" (which we know nothing about here) needs to adapt the default viewer to their use-cases, as outlined at https://mozilla.github.io/pdf.js/getting_started/:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

---

> Steps to reproduce the problem:
> [...]

Unfortunately these STR are way too broad, please don't assume that everyone is familiar with e.g. "VSCode" and "LaTeX Workshop", and thus *very* difficult to follow as-is. Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Configuration:
> 
>     * Web browser and its version:
> 
>     * PDF.js version:
> 
>     * Is a browser extension:

Please don't leave https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md completely blank when opening an issue, since the requested details are usually quite important.

**Comment by timvandermeij** [comment]
I also don't see how PDF.js itself is related to this issue. I think you should contact the "LaTeX Workshop" developers for this instead.
