### ISSUE TITLE
PDF rendering half page

### ISSUE THREAD

**Issue by GovetaXV** [mozilla/pdf.js#10860]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version: 1.5.0
- Is a browser extension: No

Steps to reproduce the problem:
1.  Open https://examsnap.io/papers/index.php/s/mEBfMpoqrLxwXJx?path=%2FMathematics%20(0580)%2F2019%2FFeburary-March#pdfviewer
and then open 0580_m19_qp_22
2. Page 4 is not rendering other than the first line.  When you try to select the text, you can. but it is invisible.
3. The same file opens on chrome's default pdf viewer just fine. (try downloading the file then opening it)
4. Also works fine on PDF.JS in edge.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/26822488/58371967-543fb900-7f34-11e9-8a0b-247f31e4b663.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/26822488/58371969-5ace3080-7f34-11e9-8b1e-ca6207f2498e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM. when opening https://examsnap.io/papers/index.php/s/mEBfMpoqrLxwXJx/download?path=%2FMathematics%20(0580)%2F2019%2FFeburary-March&files=0580_m19_qp_22.pdf#page=4 directly with PDF.js version `2.2.177` in Firefox Nightly.

---

> PDF.js version: 1.5.0

First of all, that doesn't correspond to an official release (and I'd question if that exact version number has ever existed), and it's also a *few years* out-of-date and thus no longer supported.
Please make sure to always update to the *lastest* release, as found at https://github.com/mozilla/pdf.js/releases, before opening an issue.

Furthermore, confusingly enough, it appears that the page you linked to uses a *custom* version of the PDF.js default viewer (version `1.9.426`, thus not in agreement with the information above and still too old to be supported). Looking briefly at the toolbar, the viewer has been modified with at least a new button (and who knows what else).

Given the findings above, it really seems like you need to contact https://examsnap.io for support *first*, since their viewer is too old and given that it's impossible for anyone here to support their implementation knowing nothing about it. See also https://mozilla.github.io/pdf.js/getting_started/
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

**Comment by timvandermeij** [comment]
Works for me as well with the current viewer in Firefox 67. Closing because of the reasons above.
