### ISSUE TITLE
Error: Warning: name token is longer than allowed by the spec: 141

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#10871]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome
- Operating system and its version:windows
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Uploading Pdf gives follwing error in console and few pages appear blank
2.

What is the expected behavior? (add screenshot) pdf should be rendered

What went wrong? (add screenshot)error in console and pdf not rendered properly
Error: Warning: name token is longer than allowed by the spec: 134

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Without this information the issue will be closed as INVALID, since there's unfortunately no actionable information provided here.

> PDF.js version: latest

You need to provide the *actual* version number when reporting an issue, since "latest" can mean any number of things (e.g. current `master` version, current beta/release version) and is also of no use in e.g. a weeks time.

**Comment by SwatiMaheshwari** [comment]
I have the above code in my parser.js. I am getting error from pdf.worker.js.
Also some pages of pdf are getting blank on load.

**Comment by Snuffleupagus** [comment]
> I have the above code in my parser.js. I am getting error from pdf.worker.js.

Did you actually read *all* of https://github.com/mozilla/pdf.js/issues/10871#issuecomment-497337708, since it mentions that you're using a *several years* out-of-date version of the PDF.js library?

You'll need to update to the latest release, as found at https://github.com/mozilla/pdf.js/releases, and this issue will be resolved. Keep in mind that only the latest version is officially supported.

**Comment by timvandermeij** [comment]
Closing because of the reasons above and the fact that without a PDF file it will not be possible to look into this.
