### ISSUE TITLE
bookmak do not work when encomes cjk character

### ISSUE THREAD

**Issue by netmou** [mozilla/pdf.js#10884]
Attach (recommended) or Link to PDF file here:
[腾讯企业邮箱OpenApi协议v1.4.pdf](https://github.com/mozilla/pdf.js/files/3255075/OpenApi.v1.4.pdf)

Configuration:
- browser:chrome 73
- Operating system and its version:win10
- PDF.js version:2.1.266
- Is a browser extension: no

Steps to reproduce the problem:
1. open a Chinese file
2. click the bookmark link at left side

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/7068058/58923340-da989e00-8771-11e9-811d-327a3654a15d.png)

What went wrong? (add screenshot)
no reaction with click
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
A lot of the outline items in that PDF file points to (almost) identical positions, hence why it may *appear* that nothing happens when clicking on many of them. If you however zoom the document such that a horizontal scrollbar is displayed, then you'll see that at least the *horizontal* position actually changes for some of the outline items (which otherwise appeared identical).

Also, note that this has *nothing* to do with the language used for `Title` attribute of the outline items, which is completely separate from the outline destination. 

This is a case of the PDF *itself* specifying outline items in this broken way and not a bug in the PDF.js library, and you can reproduce the same behaviour in e.g. Adobe Reader as well, hence this issue in INVALID.

**Comment by netmou** [comment]
thanks
