### ISSUE TITLE
Attached PDF not able View (7th page)

### ISSUE THREAD

**Issue by satishreddy81** [mozilla/pdf.js#10880]
Configuration:
- Web browser and its version:   Chrome latest version
- Operating system and its version:   Windows 10
- PDF.js version:     tried in all versions
- Is a browser extension:  No

Steps to reproduce the problem:
1.  Please try to open in Browser and 7th page 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by THausherr** [comment]
The boilerplate text had "Attach (recommended) or Link to PDF file here". So where is your PDF?

**Comment by satishreddy81** [comment]
Sorry, I have uploaded file now
[
[B3-T-G5-50.pdf](https://github.com/mozilla/pdf.js/files/3247065/B3-T-G5-50.pdf)
](url)

**Comment by THausherr** [comment]
I thought it is #6741 but the messages in the console are different. The two images in p7 and 8 are big, but not THAT big.

**Comment by satishreddy81** [comment]
Is there any solution for this yet?

**Comment by THausherr** [comment]
I'm not part of this project, I just hang around and look at problem PDFs. #6741 does not have a solution yet, obviously. And as I wrote, it isn't sure that this is the cause.

**Comment by Snuffleupagus** [comment]
Pages 7 and 8 contains *corrupt* JPEG images, which have a SOF (Start of Frame) markers with *completely* incorrect scanLines parameters, see excerpt below:
```
ffc0 0011 08ff 0028 0803 0122 0002 1101 0311 01..
```
As outlined in the JPEG specification, see https://www.w3.org/Graphics/JPEG/itu-t81.pdf#page=40, the scanLines value here is `0xff 0x00 => 65280` whereas the *correct* value would be `3712`.

Trying to fix this will, most likely, require adding a fair bit of heuristics but is probably doable (although it probably won't be fast, since we'll have to parse the image twice in order to recover).
