### ISSUE TITLE
DOM structure constancy

### ISSUE THREAD

**Issue by AleksandrovM** [mozilla/pdf.js#10895]
It's more like a question. For my projects it's important to have constant DOM structure generated for each of the file(I use css selectors of nodes to programmatically navigate through them, mainly element>element selector). I spotted that the same PDF file was rendered in not the same way with versions 1.7 and 2.* - the DOM trees are not equal. 
What is the policy regarding the constancy of DOM structure generated by pdf.js ? I think I am not in right to think it won't change from version to version, right?
Currently we use 1.7.354 and planning to use 2.*

**Comment by Snuffleupagus** [comment]
> What is the policy regarding the constancy of DOM structure generated by PDF.js?

What do you actually mean with "DOM structure" here, the `textLayer` which is used to enable text-selection/copying in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) or something else?

If the former then that's *not* guaranteed to remain unchanged over time/versions, since it's not part of the core library API. The official PDF.js API can be found at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js, and is the only thing that won't be changed in backwards incompatible ways (unless absolutely necessary, in which case it's gradually `deprecated`).
I.e. the [`streamTextContent` and `getTextContent` methods](https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/src/display/api.js#L1147-L1195) in the API should remain compatible between versions, but how the viewer then uses the returned information through https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js and https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js is subject to changes (at any time).

**Comment by AleksandrovM** [comment]
I mean `textLayer`. Thank you for clarification

> > What is the policy regarding the constancy of DOM structure generated by PDF.js?
> 
> What do you actually mean with "DOM structure" here, the `textLayer` which is used to enable text-selection/copying in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) or something else?
> 
> If the former then that's _not_ guaranteed to remain unchanged over time/versions, since it's not part of the core library API. The official PDF.js API can be found at https://github.com/mozilla/pdf.js/blob/master/src/display/api.js, and is the only thing that won't be changed in backwards incompatible ways (unless absolutely necessary, in which case it's gradually `deprecated`).
> I.e. the [`streamTextContent` and `getTextContent` methods](https://github.com/mozilla/pdf.js/blob/06b253d6092e14a118f9d5b23fa0652498c68a96/src/display/api.js#L1147-L1195) in the API should remain compatible between versions, but how the viewer then uses the returned information through https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js and https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js is subject to changes (at any time).
