### ISSUE TITLE
"fi" ligature is not displayed properly

### ISSUE THREAD

**Issue by Gavroche-Jocatop** [mozilla/pdf.js#10918]
"fi" ligature is displayed wrong (shifted) with Roboto font in a PDF.

Attach (recommended) or Link to PDF file here:
Copyright prevents me to do so.

**Configuration:**
- Web browser and its version: Chrome 75.0.3770.100
- Operating system and its version: Windows 10 x64
- PDF.js version: 1.6.264
- Is a browser extension: No

**What is the expected behavior?**
![image](https://user-images.githubusercontent.com/52038743/59851415-dfae3d80-936c-11e9-83d7-470706ca0aba.png)

**What went wrong?**
![image](https://user-images.githubusercontent.com/52038743/59851379-cf965e00-936c-11e9-91f9-705c30d6d18b.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> Copyright prevents me to do so.

That unfortunately means that the issue will be closed as INCOMPLETE, since it's simply impossible to debug font problems with only a screen-shot.

> PDF.js version: 1.6.264

That version was first of all not an official release, and furthermore it's a couple of years old. Please note that only the latest stable/beta releases, as found at https://github.com/mozilla/pdf.js/releases, are officially supported.

Finally, please note that it's quite possible that this issue has already been fixed in later versions of PDF.js, which you can easily test yourself by opening your file with the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html). If it works there, you'll need to update to the latest version of PDF.js to fix the issue (which you should probably do anyway, given that your version is outdated).
