### ISSUE TITLE
changing embedded link domains (instead of relative links)

### ISSUE THREAD

**Issue by ashleyjb** [mozilla/pdf.js#10919]
Hoping someone can provide some guidance to someone with little coding experience.

Using a plugin using pdf.js (pdf embedder) and the challenge I have is multiple sites using the same pdf - but requiring localised links).    All PDFs to be stored in a single folder, but referenced from all sites and embedded links to point locally (all pages are replicated - but with difference content).

I looked at issue #8771 and the piece of code in issue  #10427 but struggling.

I use the 'pdf embedder' shortcode to bring up the PDF - in a template file using various variables in the URL to retrieve the pdf.

Anyone have any ideas that can help - which code and where it needs to go?

Thanks in advance

**Comment by Snuffleupagus** [comment]
This was already answered in https://github.com/mozilla/pdf.js/issues/10427#issuecomment-452224375, and without any explanation of what's unclear with it, it's unfortunately quite difficult to provide additional help here. (Also keeping in mind that this is, first and foremost, a *bug tracker* and not a general support forum.)

Furthermore, this issue is missing all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md as well (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
