### ISSUE TITLE
one dropdown value in pdf not getting saved. some form values get saved on second click of save.

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#10913]
Attach (recommended) or Link to PDF file here: cant attach privacy issue

Configuration:
- Web browser and its version: chrome latest
- Operating system and its version: windows 7
- PDF.js version:1.0.1
- Is a browser extension: no

Steps to reproduce the problem:
1.  open pdf in version 1 of pdf.js 
2.click on save

What is the expected behavior? form values should get saved on first click

Please suggest what could be the possible reason for this failure

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: cant attach privacy issue

Without access to a test-case, there's unfortunately nothing anyone can do here.

> PDF.js version: 1.0.1

I don't think that *exact* version has ever be officially released, but in any case that would indicate that you're using a version that's over *five* years old. Only the *latest* stable/beta releases, as found at https://github.com/mozilla/pdf.js/releases, are officially supported.

> What is the expected behavior? form values should get saved on first click

The PDF.js library does *not* support modifying/editing of PDF files, since it's only a viewer, hence the default viewer won't save anything except the *original* file. Hence the implication that whatever you're attempting to do actually works, when repeatedly saving, unfortunately doesn't make any sense...
