### ISSUE TITLE
how to modify css so that buttons in toolbar (toggle moves to the left) doesn't get rearranged

### ISSUE THREAD

**Issue by mmhashimoto** [mozilla/pdf.js#10911]
This happens in any browser.  When the viewer stretches, secondarytoolbartoggle button moves to the left of zoom in and overlaps zoom in button.  Originally when it's not stretched, toggle button is right of scaleselect.  I tried to add "position: absolute;" in toolbar buttons in viewer.css, but it's not working.   How do I stop rearrangement of toolbar buttons?

Thank you.

**Comment by Snuffleupagus** [comment]
With *every* single piece of the information requested in the [ISSUE TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) missing, there's unfortunately no actionable information provided here and the issue will thus be closed as INCOMPLETE.

> This happens in any browser. When the viewer stretches, secondarytoolbartoggle button moves to the left of zoom in and overlaps zoom in button.

Resizing the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) works for me, and given that the relevant code hasn't changed in a quite some time this is honestly quite unlikely to be broken in the way described (without anyone noticing before).

**Comment by mmhashimoto** [comment]
Here is the screenshot of stretched :
![image](https://user-images.githubusercontent.com/6692445/59695202-b475f380-919e-11e9-8c4e-141590036353.png)

Here is the one shrunk to look good:
![image](https://user-images.githubusercontent.com/6692445/59695415-10407c80-919f-11e9-9faf-76b9bf311018.png)

There must be something in css that controls this.

**Comment by Snuffleupagus** [comment]
You've still not provided *any* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, with the exception of a screen-shot, meaning that this issue is still INVALID.

However, from the screen-shots it's clear that you've made a number of modifications to the default viewer (since the toolbar contains buttons/elements not present in https://mozilla.github.io/pdf.js/web/viewer.html).
It's simply impossible for anyone to tell, looking only at a couple of screen-shots, what the problem might be and I'd like to direct you to https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

*For future reference:* When opening an issue, you *need* to provide all of the required information upfront. This includes filling out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with *all* of the requested information and in cases such as this providing access to a runnable example.

**Comment by mmhashimoto** [comment]
Configuration:
Web browser and its version: Chrome Version 74.0.3729.169 
Operating system and its version: Windows 7
PDF.js version: pdfjs-2.0.943
Is a browser extension: ?
Steps to reproduce the problem: 1. 2.
Make browser viewer small
What is the expected behavior? (add screenshot)
When browser full & extended I want to see the same way as shrunk browser view
What went wrong? (add screenshot)
I attached screenshots.
I believe css is doing something.  I would like to know how to update css to correct this.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
From the screenshots this looks like a modified viewer and without a link to it we cannot help with this. You can check if the media queries in the CSS need to be modified.
