### ISSUE TITLE
Corrupted PDF still displayed

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#10934]
Hi, I looked into this 2.6 kB PDF and it seems corrupted to me:

[JM.pdf](https://github.com/mozilla/pdf.js/files/3338766/JM.pdf)

The "startxref" points to offset 2425. However, the keyword "xref" starts at byte 2418, which is against the PDF spec. Is the PDF file corrupted? PDF.js still renders it somehow.

**Comment by Snuffleupagus** [comment]
Given that PDF.js is able to render the file the same way as Adobe Reader, I really cannot understand why this issue was opened!?

Please keep in mind that this is a *bug tracker* for the PDF.js project, and not a general support forum for all things related to the PDF format itself, hence this issue is by definition INVALID.

**Comment by timvandermeij** [comment]
@photopea If you open the file with PDF.js, you'll see `Warning: Indexing all PDF objects` in the console. This means that PDF.js couldn't find the XRef section and therefore scans the PDF file contents for finding the objects instead. This is fallback logic for corrupted PDF files, so I would say: yes, the file is corrupted, but PDF.js recovers from the corruption by scanning for objects itself.

**Comment by photopea** [comment]
@timvandermeij I see, thank you very much. 

Also, I noticed, that the last object in "xref" does not point to "7 0 obj\n", but to "\n<<...." (also 7 bytes more than should).

Are you sure it is a good strategy to display such corrupted PDFs? If the creator tried to open them in PDF.js and saw an error, he or she would investigate it, and fix their process of PDF generation.

**Comment by Snuffleupagus** [comment]
> Are you sure it is a good strategy to display such corrupted PDFs?

If you implement a PDF viewer, you really have no choice in the matter since Adobe Reader (i.e. the PDF reference implementation) unfortunately have choosen to open all kinds of broken/corrupt files.
If you actually look through issues tagged with `4-corrupted-pdf` you'll see lots of examples of bad PDF files, where users are basically saying something along the lines of "but it works in {insert other PDF viewer here}".

>  If the creator tried to open them in PDF.js and saw an error, he or she would investigate it, and fix their process of PDF generation.

In a perfect world that might work, but in *reality* people will just compare with other PDF viewers regardless of the brokenness of the actual PDF file itself.
Not to mention the fact that the PDF format has been around for a couple of decades, and there's thus huge amounts of older PDF files in existence and no one will reasonably fix them all.
