### ISSUE TITLE
Is it necessary to override window.print() in embedded mode?

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#10944]
The generic viewer ("`gulp generic`") override the standard JavaScript function `window.print()`. One of the users of `ngx-extended-pdf-viewer` reports they need both features: printing PDF files and printing other stuff.

I've renamed the function without seeing any detrimental side effects yet. However, you, @Snuffleupagus, @timvandermeij , and the rest of the pdf.js team, are the experts. What are the side effects of renaming the print() function? Especially considering the embedded mode?

Related links: https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/101 and https://stackoverflow.com/questions/56711126/window-print-throws-me-an-program-stopping-error/56719053

**Comment by timvandermeij** [comment]
I think we override `window.print` for the use case where the user presses Ctrl + P or the print button in the browser. If you rename the overwritten `window.print` and use that for printing PDF files, I think it should still work if you ensure that e.g., Ctrl + P calls your renamed function. We only override `window.print` because printing PDF files requires some additional rendering and presentation logic before it can actually be sent to the printer, and `window.print` is for us a way to ensure it always gets triggered correctly.

**Comment by stephanrauh** [comment]
Thanks a lot!
