### ISSUE TITLE
Garbled character

### ISSUE THREAD

**Issue by 382580322** [mozilla/pdf.js#10956]
http://mozilla.github.io/pdf.js/web/viewer.html
open
http://www.zh17.com/demo.pdf
Garbled character
20190710

**Comment by Snuffleupagus** [comment]
*For future reference:* You need to actually fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, since a lot of details are missing.

Given that the PDF file uses non-standard fonts, but doesn't embed a single one of them, this unfortunately cannot be fixed; as such this issue is INVALID. This is bug in the PDF file *itself*, not in the PDF.js library, and is a good example of why PDF files should *always* include all of their fonts.

**Comment by 382580322** [comment]
> _For future reference:_ You need to actually fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue, since a lot of details are missing.
> 
> Given that the PDF file uses non-standard fonts, but doesn't embed a single one of them, this unfortunately cannot be fixed; as such this issue is INVALID. This is a bug in the PDF file _itself_, not in the PDF.js library, and is a good example of why PDF files should _always_ include all of their fonts.

Thank you very much.
