### ISSUE TITLE
Include breaking changes in changelog

### ISSUE THREAD

**Issue by bryanph** [mozilla/pdf.js#10951]
When upgrading PDF.js (using the pdfjs-dist repo) it can be quite difficult to figure out what breaking changes were made in the last release. It would therefore be useful to include a little section in the release that indicates which of the changes were breaking and how we can migrate our code to work with the newer version.

Also just overall a more descriptive changelog instead of a list of PRs that were merged would be really nice.

**Comment by Snuffleupagus** [comment]
Each new `pdfjs-dist` release, as found at https://github.com/mozilla/pdfjs-dist/releases, will link to the relevant release page in the main repository (i.e. directly to a release as found at https://github.com/mozilla/pdf.js/releases).

To find important and/or breaking changes in a release, please look for the strings `[api-minor]` and `[api-major]`. Generally speaking, the relevant PRs should/will have a description of the changes that were made, and how to have adapt your code. Additionally, for API changes, there will also be a `deprecated` message printed in the web-console with (some) migration information, when you're using older functionality.

> Also just overall a more descriptive changelog instead of a list of PRs that were merged would be really nice.

Most of the somewhat recent releases[1] haven't had a particular focus, meaning that it's probably not easy/meaningful to summarize them any other way than as a list of the actual changes that were made; see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#version
Furthermore, given that most contributions to PDF.js are made by unpaid volunteers, while compiling better change-logs (where it makes sense, given the above) would obviously be nice it could however be that finding the time for someone to actually do so is difficult (since these sort of things tend to take a fair bit of time).

---
[1] With the exception of the *first* release on the `2.0` branch, which removed the global `PDFJS` object.
