### ISSUE TITLE
Links to open a file are not generated

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#10971]
Please see attached PDF.
[160202-2.pdf](https://github.com/mozilla/pdf.js/files/3389518/160202-2.pdf)
 
in the bookmarks, the "go to another file" bookmark works in acrobat reader . but in pdf.js bookmark list (in sidebar),  there is no link generated in the anchor tag. when viewed in dev console. it is just

&lt;a href=""&gt;Go to another file&lt;/a&gt;

**Comment by Snuffleupagus** [comment]
When opening an issue you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, otherwise the issue will be closed as INCOMPLETE/INVALID. (You've already been asked, on multiple previous occasions, to actually follow these instructions; so please just provide all information upfront to save everyone's time.)

Among the required information is clear and concise details under the "Steps to reproduce the problem:" heading, since there's no "go to another file" string anywhere to be found in the PDF file.

**Comment by chitgoks** [comment]
hi @snuffle its not the string in the pdf but the label of the bookmark in the bookmarks list.

it seems the html code got formatted into a real link instead.

**Comment by Snuffleupagus** [comment]
I don't think it's fair to expect anyone to provide assistance if you cannot be bothered to actually read *and* follow explicit instructions, as outlined above.

**Comment by chitgoks** [comment]
ill recreate thanks
