### ISSUE TITLE
Warning: Error during font loading: Font ArialMT is not available

### ISSUE THREAD

**Issue by SwatiMaheshwari** [mozilla/pdf.js#10991]
Configuration:
- Web browser and its version: chrome
- Operating system and its version: window 7
- PDF.js version: https://viewerjs.org/
Using viewer.js which internally uses pdf.js
- Is a browser extension: NO

We are using iText api to prepopulate pdf and read data from it. While for viewing pdf we are using viewer.js api. However some values are not getting saved and I am getting following error in console
Warning: fontRes not available
Warning: Error during font loading: Font **ArialMT** is not available

Can the above fonts be supported in pdf.js?

**Comment by Snuffleupagus** [comment]
>     * PDF.js version: https://viewerjs.org/
>       Using viewer.js which internally uses pdf.js

We obviously cannot provide support for *another* project, just because it happens to use PDF.js internally, and you'll need to contact that project directly for support in such cases.

Furthermore, there's also too much of the required information missing (such as no PDF file provided and not clear enough steps to reproduce) in order for this to be a valid PDF.js issue.

**Comment by SwatiMaheshwari** [comment]
Does pdf.js support Font ArialMT?
https://forums.adobe.com/thread/1849401
If we use esign api to fill pdf and open it via pdf.js then we are not able to read Font ArialMT

**Comment by timvandermeij** [comment]
It could be that the font is not embedded in the PDF file, which should always be done to make sure that the same file is rendered equally on all platforms. However, given that no PDF file is provided and no other details are given, it's impossible for us to tell.
