### ISSUE TITLE
The API version "2.3.45" does not match the Worker version "2.1.266

### ISSUE THREAD

**Issue by asalria** [mozilla/pdf.js#10997]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 72.0.3626.121
- Operating system and its version: Windows 10
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Followed the steps on readme
2. Installed pdfjs-dist as it was not included in node-modules

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6043258/61591644-1aa8c880-abda-11e9-90e1-29d3449aa175.png)

When calling loadingTask.promise

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
`pdfjs-dist` is version 2.1.266, but the master branch clone is 2.3.45. Those two are incompatible. You should either only use `pdfjs-dist` or the master branch clone, but not a mix of both.

**Comment by wwwhatley** [comment]
I have this issue as well, and I don't believe it has anything to do with what you're saying @timvandermeij  .... 

`"pdfjs-dist": "^2.4.456",`
` pdfjs.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';`

Please help. Working with PDFJS has been a nightmare.

**Comment by timvandermeij** [comment]
Given the lack of enough details here, I'm going by what you wrote and it seems to have everything to do with what I wrote earlier because you're also mixing versions here! The error is pretty clear: you're installing `pdfjs-dist` version 2.4.456, but the worker you're linking to is version 2.6.140 as of writing. You should _never_ directly link to `mozilla.github.io/pdf.js` since it changes on every push to master. It's not meant to be a CDN. The worker file is simply bundled in `pdfjs-dist` so there is not even a need to link to another source...

**Comment by wwwhatley** [comment]
I appreciate the response--so what should I be referencing with `pdfjs.GlobalWorkerOptions.workerSrc =` ? Without it, it says 
"Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined"." @timvandermeij

**Comment by wwwhatley** [comment]
And when I add ` pdfjs.GlobalWorkerOptions.workerSrc =  '../../../node_modules/pdfjs-dist/build/pdf.worker.js';` I get the same error...

**Comment by timvandermeij** [comment]
Looking at the various examples, for example https://github.com/mozilla/pdf.js/blob/50bc4a18e8c564753365d927d5ec6a6d2cce3072/examples/components/pageviewer.js, that should be enough. Without a running example there is not much we can do to help since it may very well be caused by something else in your code. I'd suggest to try running the examples first, see if that works and go from there.

**Comment by AxelSally2** [comment]
I know this issue is closed but I want to share my solution for those who have this problem.
Just clear your browser's cache [and cookies]

**Comment by chocoford** [comment]
For me, I use CDN and found that `pdfjsLib.GlobalWorkerOptions.workerSrc` should be set to same version as `pdf.min.js` rather than `//mozilla.github.io/pdf.js/build/pdf.worker.js` in [Examples](https://mozilla.github.io/pdf.js/examples/)

```html
<script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.min.js"></script>
<script>
...

// Loaded via <script> tag, create shortcut to access PDF.js exports.
var pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '//cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.worker.js';

...
</script>
```

**Comment by hao-wang** [comment]
Use the same source for both API and worker. 

E.g., if your API (pdf.js) is from rawgit: 
<script
      type="text/javascript"
      src="https://rawgit.com/mozilla/pdf.js/gh-pages/build/pdf.js"></script>

then set your worker to be from rawgit too:
window.pdfjsLib.GlobalWorkerOptions.workerSrc = '//rawgit.com/mozilla/pdf.js/gh-pages/build/pdf.worker.js';

This ensures the same version.

**Comment by Snuffleupagus** [comment]
@hao-wang Please remove your suggestion, since it's really not a good idea nor supported in any way! 

 - No one should be linking directly to the `gh-pages` branch, since it's not intended to be a CDN.
 - That branch changes with *every* merge, which means that all sorts of breakage may occur.
 - Users should be using *official releases*, as e.g. found at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by lamnouar** [comment]
You have the issue because you already have an instance for the pdfWorker created, I hade the same issue and I fixed it by adding this  `globalThis.pdfjsWorker = null;`  just before setting the workerSrc
Like this you will be able to create a new instance with your local file

**Comment by hassamulhaq** [comment]
### Fix for any release. Now use pdfjs without CDN and **no Worker version error** anymore.

Goto: `https://github.com/mozilla/pdf.js/releases`

there are four files

```
pdfjs-2.16.105-dist.zip    5.5 MB
pdfjs-2.16.105-legacy-dist.zip    5.71 MB
Source code (zip)
Source code (tar.gz)
```

Download **`pdfjs-2.16.105-dist.zip`** file. Or download `pdfjs-x.xx.xxx-dist.zip` of the latest release.

Extract `zip` in any folder like `/public/plugins/pdfjs-2.16.105-dist`

```
Inside
pdfjs-2.16.105-dist.zip there are two folders (build, web)

├── pdfjs-2.16.105-dist
├── build
│   ├── pdf.js
│   └── pdf.sandbox.js
│   └── pdf.worker.js
├── web
│   ├── cmaps
│   └── images
│   └── locale
│   └── standared_fonts


We need to use js inside the build folder.
```

Now add `pdf.worker.js` path where you declared `const pdfjsLib = window['pdfjs-dist/build/pdf'];`

```
const pdfjsLib = window['pdfjs-dist/build/pdf'];

// The workerSrc property shall be specified.
pdfjsLib.GlobalWorkerOptions.workerSrc = '../../public/plugins/pdfjs-2.16.105-dist/build/pdf.worker.js';
```

So, now you will never face any conflict of versions. because `pdf.js` and `pdf.worker.js` are both available in `pdfjs-dist` directory. Or if you want to add pdfjs using CDN then check comment by `chocoford`.

**Comment by hainguyenvan6799** [comment]
> ### Fix for any release. Now use pdfjs without CDN and **no Worker version error** anymore.
> Goto: `https://github.com/mozilla/pdf.js/releases`
> 
> there are four files
> 
> ```
> pdfjs-2.16.105-dist.zip    5.5 MB
> pdfjs-2.16.105-legacy-dist.zip    5.71 MB
> Source code (zip)
> Source code (tar.gz)
> ```
> 
> Download **`pdfjs-2.16.105-dist.zip`** file. Or download `pdfjs-x.xx.xxx-dist.zip` of the latest release.
> 
> Extract `zip` in any folder like `/public/plugins/pdfjs-2.16.105-dist`
> 
> ```
> Inside
> pdfjs-2.16.105-dist.zip there are two folders (build, web)
> 
> ├── pdfjs-2.16.105-dist
> ├── build
> │   ├── pdf.js
> │   └── pdf.sandbox.js
> │   └── pdf.worker.js
> ├── web
> │   ├── cmaps
> │   └── images
> │   └── locale
> │   └── standared_fonts
> 
> 
> We need to use js inside the build folder.
> ```
> 
> Now add `pdf.worker.js` path where you declared `const pdfjsLib = window['pdfjs-dist/build/pdf'];`
> 
> ```
> const pdfjsLib = window['pdfjs-dist/build/pdf'];
> 
> // The workerSrc property shall be specified.
> pdfjsLib.GlobalWorkerOptions.workerSrc = '../../public/plugins/pdfjs-2.16.105-dist/build/pdf.worker.js';
> ```
> 
> So, now you will never face any conflict of versions. because `pdf.js` and `pdf.worker.js` are both available in `pdfjs-dist` directory. Or if you want to add pdfjs using CDN then check comment by `chocoford`.

Hi, I updated the source code following your instruction, but it can not solve my problem. Can you give me your example source code?

**Comment by hassamulhaq** [comment]
@hainguyenvan6799 Hi.
Here is my working Pdf.js project repo:  `https://github.com/hassamulhaq/project-media`

**Comment by gokul-afk** [comment]
I had this issue in React, Check the worker url specified  in the worker component. 

`<Worker workerUrl="https://unpkg.com/pdfjs-dist@2.16.105/build/pdf.worker.js">`

"pdfjs-dist": "^2.16.105",

mke sure its the same version as of package.json.  solved it for me .

**Comment by Paelsis** [comment]
I have tried to find a worker for 2 days.
Contradicting issues all the time.
react-pdf is a nightmare.

**Comment by jothbc** [comment]
> I have tried to find a worker for 2 days. Contradicting issues all the time. react-pdf is a nightmare.

see this answer, hope this helps you

https://github.com/mozilla/pdf.js/issues/17245#issuecomment-2090340040

**Comment by arifkk0313** [comment]
pdfjs.GlobalWorkerOptions.workerSrc = 'https://unpkg.com/pdfjs-dist@2.16.105/build/pdf.worker.js';
"pdfjs-dist": "^2.16.105",

works for me
