### ISSUE TITLE
Fail to load font Japan

### ISSUE THREAD

**Issue by dungvvfabbi** [mozilla/pdf.js#10999]
Attach (recommended) or Link to PDF file here:
[book88_2.pdf](https://github.com/mozilla/pdf.js/files/3416448/book88_2.pdf)

Configuration:
- Web browser and its version: all browser
- Operating system and its version: ubuntu 18.04
- PDF.js version:2.2
- Is a browser extension:

Steps to reproduce the problem:
1. Warning: Error during font loading: Unable to load binary CMap at: ../web/cmaps/Adobe-Japan1-UCS2.bcmap

What is the expected behavior? (add screenshot)
![Screenshot from 2019-07-22 15-55-14](https://user-images.githubusercontent.com/50563692/61619487-28715300-ac99-11e9-863d-dd44a0f63a84.png)

What went wrong? (add screenshot)
![Screenshot from 2019-07-22 15-54-28](https://user-images.githubusercontent.com/50563692/61619437-0a0b5780-ac99-11e9-8242-1b5303d88cd9.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): all browser

**Comment by timvandermeij** [comment]
These links are relevant here: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request and https://stackoverflow.com/questions/41965066/access-to-image-from-origin-null-has-been-blocked-by-cors-policy

Basically you need to serve the files since you cannot access local files directly.
