### ISSUE TITLE
Garbled German special character

### ISSUE THREAD

**Issue by tfenster** [mozilla/pdf.js#11008]
Attach (recommended) or Link to PDF file here: [document.pdf](https://github.com/mozilla/pdf.js/files/3427108/document.pdf)

Configuration:
- Web browser and its version: Version 75.0.3770.142 (Official Build) (64-Bit)
- Operating system and its version: Microsoft Windows 10, 1903, Build 18362.207
- PDF.js version: Latest on http://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the PDF
2. See garbled characters

What is the expected behavior? (add screenshot)
Downloading the PDF and opening it e.g. in Adobe Reader shows correctly rendered German special characters 
![image](https://user-images.githubusercontent.com/15346084/61800105-b16cc380-ae2c-11e9-9ae6-60e909a146aa.png)

What went wrong? (add screenshot)
In pdf.js the whole string is garbled
![image](https://user-images.githubusercontent.com/15346084/61800091-a9148880-ae2c-11e9-915e-082eb6cb6a6e.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): - 

The font is not embedded to keep the file size down. But the font (Segoe UI) is already installed with Windows, so it is available on Client and Server

**Comment by Snuffleupagus** [comment]
> The font is not embedded to keep the file size down.

Please note that all fonts should *always* be embedded in PDF files, to prevent exactly the kind of font substitution errors shown here (which is also inline with the "*Portable* document format" name). 

> But the font (Segoe UI) is already installed with Windows, so it is available on Client and Server

For security reasons a web application (such as PDF.js) cannot access locally installed fonts, which unfortunately means that the only way to fix this issue is to re-create the file with all fonts properly embedded.
