### ISSUE TITLE
whether have simple method to apply word match like pdf.js 1.x version?

### ISSUE THREAD

**Issue by sunweiconfidence** [mozilla/pdf.js#11002]
Configuration:
pdf.js 2.0.943.

Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
Type "CTRL+F" to open the find dialog
Type "like eat apple". The search result will only contains "like eat apple" can be searched .
but in the pdf.js 1.7.225, The search result will list all contains "like" or "eat" or "apple" or "like eat apple"
do i have simple method like js plugin or other method to implement this like pdf.js 1.7.225's effect? thanks

**Comment by Snuffleupagus** [comment]
> Configuration:
> pdf.js 2.0.943.

That version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases. Furthermore, please actually fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md properly when reporting issues.

> but in the pdf.js 1.7.225, The search result will list all contains "like" or "eat" or "apple" or "like eat apple"

Sorry, but this really doesn't make any sense! The default has *always* been to use phrase-searching in the find functionality of the default viewer, hence any difference in an older PDF.js version must have been the result of customizations.
 
In order to use word-searching instead, you'll need to call [`PDFFindController.executeCommand`](https://github.com/mozilla/pdf.js/blob/9b7208988639c4f1841e1b8abeaf6072b17f2f43/web/pdf_find_controller.js#L115) with `phraseSearch: false` set in the `state` object; for example see how the default viewer findbar triggers searching in https://github.com/mozilla/pdf.js/blob/9b7208988639c4f1841e1b8abeaf6072b17f2f43/web/pdf_find_bar.js#L93-L104

**Comment by sunweiconfidence** [comment]
whether i need to change pdf.js and pdf.worker.js code to support word-searching? thanks
