### ISSUE TITLE
after print logging

### ISSUE THREAD

**Issue by jasulan** [mozilla/pdf.js#11007]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE >9
- Operating system and its version: Windows 10
- PDF.js version: last
- Is a browser extension: 

Steps to reproduce the problem:
1. How to disable in printDialog page range?
2. How to get printDialog\printPreviewDialog settings after print (i need how many copies are printed)?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: IE >9

As explained in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for Internet Explorer is very limited.

> PDF.js version: last

*For future reference:* You need to provide an actual version number, since "last" isn't in no way clear enough.

>     1. How to disable in printDialog page range?

It's quite difficult to understand what's actually being asked here.

>     2. How to get printDialog\printPreviewDialog settings after print (i need how many copies are printed)?

It's generally not possible to control and/or access browser specific print setting from JavaScript, hence this cannot be supported and this issue is thus INVALID.

**Comment by jasulan** [comment]
> > Web browser and its version: IE >9
> 
> As explained in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for Internet Explorer is very limited.
> 
> > PDF.js version: last
> 
> _For future reference:_ You need to provide an actual version number, since "last" is in no way clear enough.
> 
> > ```
> > 1. How to disable in printDialog page range?
> > ```
> 
> It's quite difficult to understand what's actually being asked here.
> 
> > ```
> > 2. How to get printDialog\printPreviewDialog settings after print (i need how many copies are printed)?
> > ```
> 
> It's generally not possible to control and/or access browser specific print setting from JavaScript, hence this cannot be supported and this issue is thus INVALID.


how to attach QRcode
I want to log how many times have the document been printed? How many copies are printed in one print? and save this information in qrcode. As much as possible
