### ISSUE TITLE
whether can fully support chinese word search in chinese article?

### ISSUE THREAD

**Issue by sunweiconfidence** [mozilla/pdf.js#11021]
Configuration:

Chrome 75.0.3770.142
Windows 10:
PDF.js 1.7.225:
Steps to reproduce the problem:

Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2 Type "CTRL+F" to open the find dialog
3 Type "你好".
What is the expected behavior? (add screenshot)
The search result will list all contains "你好" 

What went wrong?
now only some words with "你好" can be searched out in the article, but some “你好” can't be searched out, my pdf is an chinese article, whether can fully support chinese word search in pdf.js or for chinese word search, it can't be fully supported? thanks

**Comment by Snuffleupagus** [comment]
There's unfortunately no actionable information provided here, since you didn't fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) completely; hence the issue will be closed as INCOMPLETE.

> PDF.js 1.7.225

As was explained previously, that version is very old and thus no longer supported. Hence you'll need to update to the latest release, see https://github.com/mozilla/pdf.js/releases

> Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
> 2 Type "CTRL+F" to open the find dialog
> 3 Type "你好".
> What is the expected behavior? (add screenshot)
> The search result will list all contains "你好"

There's no Chinese text in that PDF file, so it's no surprise that that search term won't produce any results. You'll need to actually attach the relevant PDF file in to the issue, in order for this to be valid.
