### ISSUE TITLE
The PDF file is printed and printed on paper, which is very blurry.

### ISSUE THREAD

**Issue by beijingalex** [mozilla/pdf.js#11026]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  chrome
- Operating system and its version: ;win10
- PDF.js version: 2.1.266
- Is a browser extension:no

Steps to reproduce the problem:
1.The PDF file is printed and printed on paper, which is very blurry.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This issue is missing *crucial* parts of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, such as e.g. the PDF file in question and screen-shots/images of the print result, and without *all* of the information provided this will be closed as INCOMPLETE.

> PDF.js version: 2.0

That *exact* version number has never existed...

**Comment by lixuguang** [comment]
I had the same problem, and the blurring was particularly bad with Internet explorer.
(translated by Google)
