### ISSUE TITLE
Load PDF.JS dynamically with an issue 

### ISSUE THREAD

**Issue by Motard** [mozilla/pdf.js#11039]
I am having an issue when I trie to load the library dynamically. 

So when I load the library in my index.html, I have no issue, but if I trie to load with 
`      var script = document.createElement('script');
        script.src = 'vendor/js/pdfjs/pdf.min.js';
        document.getElementsByTagName('head')[0].appendChild(script);` I have an error

<img width="792" alt="Screenshot 2019-08-03 at 09 35 33" src="https://user-images.githubusercontent.com/5487982/62409613-0ef1d480-b5d2-11e9-9eb1-b64589103117.png">

<img width="479" alt="Screenshot 2019-08-03 at 09 35 01" src="https://user-images.githubusercontent.com/5487982/62409607-03061280-b5d2-11e9-9454-9180cddc5cb1.png">

Do you have any idea why this is happening?

I have added a debug point to this line (in the above shot), and when the library is loaded in index.html, the browser only stops at that line when I click to open a pdf, but when I load the library dynamically, the browser stops on that line right after load.

**Comment by Snuffleupagus** [comment]
This looks (somewhat) similar to issue #9712, please note https://github.com/mozilla/pdf.js/issues/9712#issuecomment-459368526.

This issue is currently missing all of the necessary information in order to be actionable, and will probably be closed as INCOMPLETE with additional information.
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
