### ISSUE TITLE
Do you return parameters when the pdf file is loaded using pdf.js?

### ISSUE THREAD

**Issue by beijingalex** [mozilla/pdf.js#11031]
Configuration:

Web browser and its version:chrome
Operating system and its version: win10
PDF.js version: 2.0.943 and 2.1beta
Is a browser extension:no
Steps to reproduce the problem:

Do you return parameters when the pdf file is loaded using pdf.js? 

What is the expected behavior? (add screenshot)
I want to get the parameters returned after loading and do subsequent functional processing.

What went wrong? (add screenshot)
i don't know what went wrong .

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I want to get the parameters returned after loading and do subsequent functional processing.

Unfortunately it's not at all clear what this actually means, since it's impossible to tell what "parameters" you're referring to and if "after loading" means once the whole file is available or something else. For the latter case, you could call https://github.com/mozilla/pdf.js/blob/d909b86b28958045e59869d6d1d0a95f43547ed3/src/display/api.js#L758-L763 on the `PDFDocumentProxy` instance that's returned by the `getDocument` call.
