### ISSUE TITLE
Documents are not rendering well in Firefox Browser.

### ISSUE THREAD

**Issue by amitK007** [mozilla/pdf.js#11043]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 63
- Operating system and its version: win 7
- PDF.js version:2.2
- Is a browser extension:

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/34776401/62441823-48157a80-b773-11e9-9296-d154b8dcf6ef.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/34776401/62441802-2d430600-b773-11e9-836e-811e243d2f3b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This issue is missing too much of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md in order to be actionable, and in its current for it will be closed as INCOMPLETE.

> Attach (recommended) or Link to PDF file here:

Without this information, there's really no point opening an issue.

> Web browser and its version: 63

If this means Firefox 63, then that version is no longer supported and you need to update to the latest release (which as of this writing is Firefox 68).

> PDF.js version: 2.2

That version number doesn't exist...
