### ISSUE TITLE
Warning: Unable to decode image: JpegError: JPEG error: marker was not found

### ISSUE THREAD

**Issue by cyfour** [mozilla/pdf.js#11052]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome 75.0.3770.80 （64）
- Operating system and its version:window 10
- PDF.js version:2.0.943
- Is a browser extension:

Steps to reproduce the problem:
1. open the test.pdf
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[test.pdf](https://github.com/mozilla/pdf.js/files/3479488/test.pdf)

**Comment by Snuffleupagus** [comment]
*A PR has been submitted, however for future reference when reporting an issue:*

> Attach (recommended) or Link to PDF file here:

Please make sure to place the PDF file *directly* after this line, to save people time by not having to read through the entire issue just to find the PDF file.

> PDF.js version: 2.0.943

Always remember to test with the latest release, see https://github.com/mozilla/pdf.js/releases, since the quoted version is no longer supported.

> What is the expected behavior? (add screenshot)
> 
> What went wrong? (add screenshot)

Please note the "add screenshot" part, since that helps to quickly identify the problem.

**Comment by cyfour** [comment]
Thank you. I used pdfjs-2.2.228-dist to test the same effect.
![QQ图片20190808165911](https://user-images.githubusercontent.com/24726616/62689771-0815f800-b9fe-11e9-85ba-76919c42c278.png)
![QQ图片20190808170052](https://user-images.githubusercontent.com/24726616/62689824-1ebc4f00-b9fe-11e9-8b50-978a33881063.png)

**Comment by jkester79** [comment]
PDF is blank in firefox 69.0 (64-bit) #11140
In regards to my post, I am not finding the PDF to be corrupt, it opens fine in all other browsers and pdf viewers. Am I to understand that the problem is with the attached PDF, and not the viewer?
