### ISSUE TITLE
Canvas preview PDF, how to clear canvas and re-render new files instead of adding new rendering content after the original canvas

### ISSUE THREAD

**Issue by wsyxzxs** [mozilla/pdf.js#11058]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 75.0.3770.100（正式版本）（64 位）
- Operating system and its version:  windows 10
- PDF.js version: 1.9.426
- Is a browser extension:

Steps to reproduce the problem:
1. When you first enter the preview PDF page, canvas can render PDF correctly
2.When you exit the page and re-preview other PDF files, canvas renders a new PDF file behind the original canvas

What is the expected behavior? (add screenshot)
I want to preview PDF again, just look at the current file, not all the information previewed.

What went wrong? (add screenshot)
Page Rendering Document Information Error.I hope you can provide an API to solve this problem. Thank you and look forward to your reply.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
It's essentially impossible to understand what you're actually trying to report/ask here!

Please provide much more detailed and clear information under the "Steps to reproduce the problem" heading, since otherwise it's not possible for anyone to assist. Furthermore, note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> PDF.js version: 1.9.426

That version is more than two years old, and is thus no longer supported; please find the latest releases at https://github.com/mozilla/pdf.js/releases
