### ISSUE TITLE
copy/paste, additional characters appear

### ISSUE THREAD

**Issue by CrossMountain** [mozilla/pdf.js#11066]
# Attach (recommended) or Link to PDF file here:
[copy-paste-problem.pdf](https://github.com/mozilla/pdf.js/files/3489985/copy-paste-problem.pdf)

# Configuration:
- Web browser and its version:
Chrome 75
- Operating system and its version:
Mac OS 10.14
- PDF.js version:
2.0.0
- Is a browser extension:
No

# Steps to reproduce the problem:
1. Copy the first line "电子科技大学", then paste it to somewhere
2. It will become "电⼦子科技⼤大学".

# What is the expected behavior? (add screenshot)
It should be "电子科技大学"。

# What went wrong? (add screenshot)
It is because of the font's ToUnicode map's problem. You can check the pdf file's structure, you will see the ToUnicode in the font, it maps <09fc> to <2f26 5b50> which are "⼦子⼦子". Also, it maps <095f> to <2f24 5927> which are "⼤大⼤大".
![ToUnicode](https://user-images.githubusercontent.com/32870413/62834287-97304380-bc7c-11e9-9264-16fe9b430b6b.png)

# How to generate this pdf file?
The pdf is generated in Mac OS.
First, write "电子科技大学" in an txt file. 
Second, click the "File".
Third, click the "Export As PDF"
Then, it becomes what you see.

# Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I don't know how to upload it to a site.

# The issue will be solved in my pull request.
https://github.com/mozilla/pdf.js/pull/11067

**Comment by timvandermeij** [comment]
The pull request above contains a discussion about a possible solution that was tried but wasn't a full solution. We should check if/how other PDF viewers handle this and come up with a fix that doesn't negatively impact existing (valid) PDF files.

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, rather than in the PDF.js library, and please note that you get *identical* copy-and-paste behaviour as Adobe Reader as well (i.e. the PDF reference implementation).
Furthermore, as shown by the previously attempted PR, fixing this edge-case without regressing *correct* PDF documents in the process appear to be quite difficult. This problem should also not be a common one, since this issue is only such report we've received in either GitHub or Bugzilla (to the best of my knowledge).

All-in-all, closing as WONTFIX for now given the points above.
