### ISSUE TITLE
PDF with data on top of it - all data is lost when opening via pdf.js

### ISSUE THREAD

**Issue by danielstachowiak** [mozilla/pdf.js#11162]
Here is the example file that fails to open correctly in pdf.js on your demo page (and in our instance):
[dummkj19.pdf](https://github.com/mozilla/pdf.js/files/3631530/dummkj19.pdf)
It is a layered document (a pdf with data on top of it). Only the pdf opens, the data is lost.

Configuration:
- Web browser and its version: any browser
- Operating system and its version: any operating system
- PDF.js version: Your own DEMO version
- Is a browser extension: no

Steps to reproduce the problem:
1. Upload the above file via the Demo button on pdf.js website

2. Expected result: a pdf with data
![2](https://user-images.githubusercontent.com/454432/65250302-46b6cc00-daed-11e9-9f46-f77b690d6bcc.jpg)

3. Actual result: empty pdf (all data is lost)
![1](https://user-images.githubusercontent.com/454432/65250226-27b83a00-daed-11e9-9990-ee6c10467779.jpg)

We are happy to pay a modest fee for a quick fix.
Please contact support@mydocsafehq.com if you would like to discuss this further.

**Comment by devstore49** [comment]
I`m sure to resolve this issue.
Thank you.

**Comment by LuckyStar121** [comment]
I need to check your code right now.

**Comment by Snuffleupagus** [comment]
There's something wrong with one of the `ExtGState` entries for the first page, either in the PDF file itself and/or in the way that PDF.js handles GState.
However, even if that would be fixed the PDF file is still corrupt since it doesn't embed *all* of its fonts (i.e. the same problem as outlined in https://github.com/mozilla/pdf.js/issues/11068#issuecomment-521589843).

*Finally, given the two comments just above:* Unless you have something add to an issue, please refrain from posting essentially meaningless/empty comments since that just clutters the discussion.

**Comment by THausherr** [comment]
Amazingly, the font that is missing in the resources has the same name! (Ffcs1)

**Comment by Snuffleupagus** [comment]
Should this be closed as fixed now, given the PR referenced above?
