### ISSUE TITLE
How to use pdf.js with requirejs

### ISSUE THREAD

**Issue by rafaelstz** [mozilla/pdf.js#11189]
I believe it's a good topic to be in the [Wiki](https://github.com/mozilla/pdf.js/wiki).
To implement it with RequireJS you must use the names to instantiate like this image below.

![Screen Shot 2019-10-01 at 3 53 01 PM](https://user-images.githubusercontent.com/610598/65991418-b0c35f80-e463-11e9-842f-30c0422e858f.png)

![Screen Shot 2019-10-01 at 3 50 51 PM](https://user-images.githubusercontent.com/610598/65991267-748fff00-e463-11e9-997d-81a9c6e26bd9.png)

Reference: https://github.com/mozilla/pdf.js/issues/7287#issuecomment-348143963

**Comment by timvandermeij** [comment]
You shouldn't be using the version from `mozilla.github.io` since it's always the latest `master` version, which may contains bugs from time to time. You should always use an official release from https://github.com/mozilla/pdf.js/releases instead, or use https://github.com/mozilla/pdfjs-dist (the NPM package).

Moreover, it's probably better to provide a good and self-contained example for RequireJS in https://github.com/mozilla/pdf.js/tree/master/examples since that is more likely to be found/used than the wiki for usage with external libraries; pull requests for this are welcome. (Also, we don't really provide support for using the PDF.js library with third-party libraries other than giving example usages.)

**Comment by pnevesdh** [comment]
It is not working for me. Do you know if it still works?
