### ISSUE TITLE
Undefined variable: regeneratorRuntime

### ISSUE THREAD

**Issue by TemitaTom** [mozilla/pdf.js#11204]
Hi

When try to minify the js files, bundleminifier show this error:

Strict-mode does not allow assignment to undefined variables: regeneratorRuntime

Thanks

**Comment by Snuffleupagus** [comment]
> [...] bundleminifier show this error:

The only (currently) supported minifier is https://github.com/terser/terser, since that's the one used with the `gulp minified` build target:
https://github.com/mozilla/pdf.js/blob/4a1fc62d6c700f9f45901ca6e88fa0b56ac94218/gulpfile.js#L760-L837

*For future reference:* You need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue, since otherwise it's not considered valid.
