### ISSUE TITLE
Can I use this module in react native?

### ISSUE THREAD

**Issue by zRelux** [mozilla/pdf.js#11217]
I tried to use this module with react native but I get this weird error about `GlobalWorkerOptions`
you can see it here [Expo snack](https://snack.expo.io/H110r-tuS)
is there anyway I can use this module in react native?
Thank you for any answer

**Comment by timvandermeij** [comment]
You should be able to use PDF.js with React Native, but we don't explicitly provide support for third-party library integrations. However, the error you're facing seems to be because you're missing https://github.com/mozilla/pdf.js/blob/2e05827b87646e621593fb26f4327f335d0a0d7a/examples/learning/helloworld.html#L22-L26.

**Comment by luistak** [comment]
Added this simple example with create-react-app
