### ISSUE TITLE
In safari Ipad browser on the tap of hyperlink in PDF is navigating to different URL end point and in remaining browsers it is working as expected by navigating to the right URL end point. 

### ISSUE THREAD

**Issue by varunreddy1800** [mozilla/pdf.js#11255]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Safari IPAD 12.1.3
- Operating system and its version:IOS 12.1.3
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.open the safari browser in the IPAD
2.open my pdf file in browser with the hyperlinks in it.
3.when i tap on hyperlink it is navigating to the wrong url end point only in safari IPAD browser and remaining browsers are working as expected and navigating to the correct url end point. 

What is the expected behavior? (add screenshot)
1)when i tap on hyperlink in PDF file in  safari browser it should be navigating to the right url endpoint
What went wrong? (add screenshot)
2)The URL path is appending with the different string at the end only for the safari browser.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
> open my pdf file

No PDF file is actually provided here.

> only in safari IPAD browser

This most likely means that the issue should be reported to Safari instead.

> different string at the end

What is the exact difference then?

In short, this issue doesn't contain nearly enough information be actionable. Please either give a more clear description or file the issue with Safari, since their browser apparently behaves differently from the rest and we don't want to introduce browser-specific workarounds if not strictly necessary.
