### ISSUE TITLE
Question: release schedule

### ISSUE THREAD

**Issue by mwakerman** [mozilla/pdf.js#11265]
tl;dr is there a release schedule or somewhere that the expected next release date is available?

We are looking to upgrade the version of pdf.js we use in our web application but thought it would be wise to wait if the next stable release is imminent. The wiki doesn't mention mention a release schedule but it looks like you have released at the end of October in 2017 and 2018. Is there a release schedule (aspirational or otherwise)?

**Comment by Snuffleupagus** [comment]
> [...] but it looks like you have released at the end of October in 2017 and 2018.

At the time of writing, there's been no less than *three* release in 2019 already (with the latest one being less than a month old); please see https://github.com/mozilla/pdf.js/releases

Also, please note that there's generally *very* little difference, as far as stability is concerned, between stable and pre-release versions (since no code lands without e.g. all tests passing).
Firefox Nightly, for example, is always using what's more-or-less the latest `master` version of the PDF.js library. Hence the decision to use "stable" or "pre-release" versions is really up each implementer (and note that unless something is *really* broken, patches are generally not back-ported).

> Is there a release schedule (aspirational or otherwise)?

No regularly occurring one, as far as I'm aware. Since a lot of this project is driven by volunteers, releases usually happen when someone has time to create one (after e.g. a couple of `[api-minor]` patches and/or other significant changes has happened since the last release).

**Comment by timvandermeij** [comment]
Closing since the comment above is accurate.
