### ISSUE TITLE
Don't log messages to the console that the user or developer can do nothing about

### ISSUE THREAD

**Issue by KeithHenry** [mozilla/pdf.js#11292]
We're developing an app that uses pdf.js - we use the browser console extensively during development but don't log anything to it (unless absolutely necessary) in production. We deal with millions of PDFs from different sources, often converted poorly or corrupted before we get them.

pdf.js is excellent, but logs warnings and errors to the console that the developer or end user can do nothing about. 

For instance #3768 - a bad font recovery message. That's useful information, but not to the end user viewing the PDF or the application developer.

Other warnings are useful but with an unhelpful and persistent message, for instance #10377 if you `await page.render(...` you get told that `then` syntax is deprecated. The fix (to `await page.render(...).promise`) and related documentation to it should be indicated, and if the deprecated method is still called in production then end users don't need to know about it.

## What is the expected behaviour?
In the production build:
- Issues handled internally should not be logged to the console.
- Information about using the API can be logged to the console but 
  - should be written for an external developer with links to documentation.
  - can be turned off in production environments or alternate development contexts.
- Issues that some end users in some contexts _could_ act on (for instant a bad font message telling a PDF author to change the PDF) need to be some kind of event, observer, subscription or callback, as there's no way to promote the console log messages to actual UI.

**Comment by Snuffleupagus** [comment]
> [...] but logs warnings and errors to the console that the developer or end user can do nothing about.

I suppose that it depends on what sort of "developer" we're talking about here, since I can assure you that from the PDF.js-contributor perspective many of the console messages are most helpful.
As for the end-user part, console messages are definitely not useless there either since they often allow users to provide additional and useful information when reporting bugs.

> [...] and if the deprecated method is still called in production then end users don't need to know about it.

It's, generally speaking, the responsibility of the person actually utilizing the PDF.js library to ensure that their code is using correct *and* current APIs, and otherwise update their own code such that deprecated messages aren't seen by end-users.
In particular, you probably don't want to deploy a new PDF.js [release](https://github.com/mozilla/pdf.js/releases) without testing it yourself *first*.

> Issues handled internally should not be logged to the console.

The amount of logging printed in the console can be easily controlled by the API user when calling `getDocument`, please see
https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/src/display/api.js#L152-L153 and the currently available values in https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/src/shared/util.js#L182-L186
For example, calling `getDocument` in the following way will *only* print actual error messages:
```javascript
const loadingTask = getDocument({
  url,
  verbosity: 0,
});
```

> Information about using the API can be logged to the console but
>
>   should be written for an external developer with links to documentation.

This is an *open source* project, with most people contributing in their spare time. Please understand that writing good documentation can be both time-consuming and non-trivial, so if the documentation is lacking please consider contributing to it :-)

>   can be turned off in production environments or alternate development contexts.

It's not clear what you mean by "production environments" here, but if you're e.g. referring to the pre-built `pdf.js`/`pdf.worker.js` files that's distributed [here](https://github.com/mozilla/pdf.js/releases) and [here](https://github.com/mozilla/pdfjs-dist) then those *need* to have API warnings printed by default since otherwise the *implementer* wouldn't get notified about e.g. deprecated APIs.

> [...] need to be some kind of event, observer, subscription or callback, as there's no way to promote the console log messages to actual UI.

There already is such a thing[1], for unsupported features, please see https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/src/display/api.js#L463-L467
For an example of how this can be used, please see the default viewer code [here](https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/web/app.js#L666-L680) and [here](https://github.com/mozilla/pdf.js/blob/72bd8e8bdb96791bd66a961c428c9edfffd11a71/web/app.js#L744-L763).

---
[1] This is e.g. being used to display a notification bar, for feature which aren't supported, in the built-in Firefox PDF Viewer.

**Comment by timvandermeij** [comment]
Closing as answered; I also agree with everything said above.
