### ISSUE TITLE
Text Layer pushed to bottom and side

### ISSUE THREAD

**Issue by mmacdonald1** [mozilla/pdf.js#11309]
Attach (recommended) or Link to PDF file here:
[testFile.pdf](https://github.com/mozilla/pdf.js/files/3820820/testFile.pdf)

Configuration:
- Web browser and its version:
Chrome 78.0.3904.70 
- Operating system and its version:
MacOS Mojave 10.14.16
- PDF.js version:
1.4.162
- Is a browser extension:
no
Steps to reproduce the problem:
1. click document filename to show in viewer (runs get document)
2. Document renders with text on the side at the bottom

What is the expected behavior? (add screenshot)
TextLayer aligned
What went wrong? (add screenshot)
![Screen Shot 2019-11-07 at 11 55 59 AM](https://user-images.githubusercontent.com/27786743/68411110-df65e180-0157-11ea-8c32-5b354f6f80d4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.4.162

That version is a few years old, and also doesn't correspond to any official release.
Please update the *latest* version, as found at https://github.com/mozilla/pdf.js/releases, since any version not marked either `Pre-release` or `Latest release` is no longer supported.

> What went wrong? (add screenshot)

Considering that the text-layer should not be visible, the screen-shot looks somewhat "weird". Is this perhaps a custom implementation, since this doesn't happen in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html)?

**Comment by timvandermeij** [comment]
I also verified that this PDF file works in the latest version, i.e., the development viewer, so upgrading to the latest release should fix this.
