### ISSUE TITLE
Determining when to use disableFontFace

### ISSUE THREAD

**Issue by tristansokol** [mozilla/pdf.js#11311]
I'm running into issues similar to #4244 but am interested in knowing if there is a way to programmatically determine if I should use `disableFontFace`. 

I'm attempting to OCR invoices, and some of them render correctly with `disableFontFace:false` and others with `disableFontFace:true`, if you supply a pdf the wrong `disableFontFace` you end up with a pdf that is void of text, or has boxes as is documented in other issues. 

My question is, Is there a way to determine (via the `pdfDocument` metadata or any other means) if I should use the `disableFontFace` option when calling `.getDocument()`?

I have tried getting text content and looking at fonts, but I'm not sure if I can just say "oh this text content seems to be all in Helvetica, so I know that I need to use `disableFontFace:true`" That information and a list of system fonts seems like the only path forward based on the other issues I've read. 

Thank you.

**Comment by sayo96** [comment]
@tristansokol I faced this issue today . Can you provide a working example of your code?

**Comment by sayo96** [comment]
@timvandermeij  is there any update on this?

**Comment by tristansokol** [comment]
@sayo96 as far as I am aware there is not a way to determine which setting you need, and depending on your pdfs you may need the effects of both setting to correctly render.

**Comment by sayo96** [comment]
@tristansokol Thanks a lot for the fast response 🙏 .  I tried to implement your solution and i just realised this.
So, as things stand i think the only way to get a proper pdf ( in which everything appears properly) is by embedding the fonts after we set `disabledFontFace: true`.

I'm having a few more doubts. Please correct me if i'm wrong:

1. I'm using pdf js in node based environment. So i tried used `registerFont` method of node canvas library to register the font and then use it in canvas context like  below:

```
  Canvas.registerFont(path.resolve('assets', 'fonts', 'Anton-Regular.ttf'), { family: 'Anton' });

    var canvas = Canvas.createCanvas(width, height);
    var context = canvas.getContext("2d");

    context.font = '200px "Anton"'
    context.fillText('Everyone hates this font :(', 250, 10)
```
But to my surprise, the text within the pdf image were unaffected and the text **Everyone hates this font** was displayed in anton font. I feel i'm missing something simple here but i'm not able to find it... 

2. I have searched the docs but i could not find how to embed multiple fonts.  I feel like since i have the pdf-dist js library running in node env, i just need to embed a list of fonts that will be used by my pdfs to get a good pdf in which text of different font-families will be rendered

**Comment by SantiagoM92** [comment]
I had a similar problem. In my case the problem occurs when, PDF files have an embedded font. When PDF files do not have an embedded font they render fine. For Example

With embedded font
![image](https://user-images.githubusercontent.com/4475572/122496602-ab000b80-cfb1-11eb-8881-562a8782d1cd.png)

For this I made a workaround, manipulating the disableFaceFont property. Because when the FaceFont is active, it tries to look for the embedded font and if it doesn't find it, it renders wrong.

Whereas, if the FaceFont is inactive and the file has no embedded font, it doesn't render.

To do this when I call open the PDF, I set the "disableFaceFont" property to true 

`PDFViewerApplication.open(uint8Array,{disableFontFace: true});`

And in the "CanvasGraphics.paintChar" method of "pdf.js" I make the following control: 

If the PDF has embedded font, then disable FaceFont "disableFaceFont:true" and if it does not have embedded font, then enables FaceFont "disableFaceFont:false".

`font.disableFontFace = !font.missingFile || font.mimetype;`

![image](https://user-images.githubusercontent.com/4475572/122498554-f23bcb80-cfb4-11eb-9bdf-f9cd5c42f25a.png)


This way it works fine for both.

Same PDF with workaround

![image](https://user-images.githubusercontent.com/4475572/122498535-eb14bd80-cfb4-11eb-9407-a69a96240812.png)

**Comment by Snuffleupagus** [comment]
After PR #12726, rendering of *standard fonts* should work even with `disableFontFace = true` set; assuming obviously that the `standardFontDataUrl` parameter is correctly set when calling `getDocument`:
https://github.com/mozilla/pdf.js/blob/891f21fba6db64cd602c1a9a51826d7b9cd06af0/src/display/api.js#L168-L169

Furthermore, it should *also* be possible to successfully use `disableFontFace = false` now (i.e. the default value); possibly you may need to manually set `useSystemFonts = false` in that case (if you're using PDF.js in a browser).
