### ISSUE TITLE
[PDF viewer][enhancement] File-Open dialog should ignore non-PDF files

### ISSUE THREAD

**Issue by stephanrauh** [mozilla/pdf.js#11319]
This affects any browser, on any OS, with the current PDF viewer. You can test it with the current online demo https://mozilla.github.io/pdf.js/web/viewer.html.

When you click "open file", a dialog opens which allows you to open every file, no matter whether it's a PDF file or not:

<img width="794" alt="image" src="https://user-images.githubusercontent.com/3045767/68626353-8097c380-04db-11ea-86d3-24ba886b1155.png">

As you can see, every file is printed with black color. Adding the attribute `accept=".pdf,application/pdf"` highlights the PDF files and paints the other files gray:

![image](https://user-images.githubusercontent.com/3045767/68626493-c5235f00-04db-11ea-930b-976f678513ba.png)

The nice thing is that the user can still override this setting, so that's no breaking change.

**Comment by stephanrauh** [comment]
Also see https://github.com/stephanrauh/ngx-extended-pdf-viewer/issues/167. And thanks to @umar-shafiq who proposed this enhancement.

**Comment by stephanrauh** [comment]
If you want to implement this suggestion, it's basically adding a single line at https://github.com/mozilla/pdf.js/blob/21895aa75afb9d5a35d987923af241f349a50ea6/web/app.js#L1572:

```javascript
  fileInput.className = 'fileInput';
  fileInput.setAttribute('accept', '.pdf,application/pdf'); // issue 11319
  fileInput.setAttribute('type', 'file');
```

**Comment by Snuffleupagus** [comment]
Given that the API/Worker *purposely* doesn't impose e.g. any file extension limitations, since those may not necessarily be correct[1], I really don't see why the viewer should be doing that either.

The most likely result of such a change, is that there will be bug reports/support requests from users of the default viewer who are *not able to find their files*. All in all, I'd probably suggest WONTFIX here. 

---
[1] I recall seeing examples of on-the-fly PDF generation on the web, where the file extension isn't necessary the correct one.

**Comment by stephanrauh** [comment]
Makes sense. On the other hand, you could make it an option that's disabled by default.

BTW, my approach checks both the extension and the MIME type. Maybe that helps with the on-the-fly PDFs (provided the generator sets the correct file header).

**Comment by Snuffleupagus** [comment]
> Makes sense. On the other hand, you could make it an option that's disabled by default.

It's not possible to add options for *everything* a particular implementer might want, since the number of combinations that would then have to be tested/supported would make it unmanageable. (Personally, I do believe that we already have too many default viewer options as-is.)

This particular case seems like a *very* minor issue, and in general these kind of feature requests ought to be covered by the statement in http://mozilla.github.io/pdf.js/getting_started/#introduction:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

**Comment by timvandermeij** [comment]
Yes, I also don't really see much added value for having this in the default viewer, and I also recall having seen cases where file extension/content type checking doesn't work reliably, so I don't think this is something we can/will implement.
