### ISSUE TITLE
ETA for official 2.3.x release?

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11323]
Is there an ETA for an official 2.3.x release?  I'm want to merge it into Polar to get the latest code as there are some bug fixes that impact our product.

I know the pre-release was about a month ago so hopefully, there's an official/stable 2.3.x release soon.

**Comment by Snuffleupagus** [comment]
> Is there an ETA for an official 2.3.x release? 

Not that I'm aware of, since that would require a new release first (and it's *only* been a little over a month since the `v2.3.200` version was released).

Furthermore, it seems that https://github.com/mozilla/pdf.js/issues/10819#issuecomment-491945927 is probably relevant here as well.

**Comment by timvandermeij** [comment]
Indeed, there is no ETA yet, but the comment above is correct that there is usually no difference between the pre-release and the release because, unless a serious regression is found, the pre-release automatically becomes the release in the next cycle. We don't have a fixed release schedule, we usually wait until we gathered enough feedback from the community on the previous release and then make a new release.
