### ISSUE TITLE
Find function not working with arabic word 

### ISSUE THREAD

**Issue by gadriaahmed** [mozilla/pdf.js#11321]
Attach (recommended) or Link to PDF file here:
https://drive.google.com/file/d/1ZsfWYWts2AeKPokOAPMbnAi4-9MTIa01/view?usp=sharing

Configuration:
- Web browser and its version: all browser
- Operating system and its version: all operating system 
- PDF.js version: latest version 
- Is a browser extension:

Steps to reproduce the problem:
1. write a word on the find field in arabic 
2. 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![Screenshot from 2019-11-12 10-36-27](https://user-images.githubusercontent.com/33733887/68659878-5d4f3180-0538-11ea-98b3-0e04b77188c2.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> https://drive.google.com/file/d/1ZsfWYWts2AeKPokOAPMbnAi4-9MTIa01/view?usp=sharing

None of the PDF viewer I've tried, which includes Adobe Reader (i.e. the reference implementation), is able to successfully copy and/or search text in that PDF document.

The problem is that none of the fonts in the PDF document contain any meaningful `ToUnicode` data, hence this is a limitation of the PDF document *itself* rather than the PDF.js library and it's thus unfortunately not possible to fix that here.

**Comment by gadriaahmed** [comment]
Thanks for your responce 
I used another pdf file writen in arabic so when i type the word in arabic with the keyboard the pdf reader can't find the word but when i copy it from the pdf  the pdf reader find the word so i thing it's a problem of encoding 
![Screenshot from 2019-11-12 10-58-07](https://user-images.githubusercontent.com/33733887/68662870-fa609900-053d-11ea-84a6-2c8ff1cbf4ea.png)

![1214](https://user-images.githubusercontent.com/33733887/68662873-fcc2f300-053d-11ea-8ce2-5f998448dbd0.png)

**Comment by Snuffleupagus** [comment]
The problem reported in https://github.com/mozilla/pdf.js/issues/11321#issue-521402686 isn't actionable, for the reasons explained in https://github.com/mozilla/pdf.js/issues/11321#issuecomment-552815512, and this issue is thus invalid.

---

What's described in https://github.com/mozilla/pdf.js/issues/11321#issuecomment-552828520 might be a totally different problem, however please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> The issues are used to track both bugs filed by users and specific work items for developers. **Try to file one issue per problem observed.** Please specify a valid title (e.g. "Glyph spacing is incorrect" instead of "PDF.js does not work") and provide more details about the issue: link to the PDF, location in the PDF, screenshot, browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.
