### ISSUE TITLE
WebWorker may not close in IE11

### ISSUE THREAD

**Issue by tqtiwvfdn** [mozilla/pdf.js#11329]
While open pdfjs in IE11 with iframe，multi times。Web Worker may not close 。

like this：
![image](https://user-images.githubusercontent.com/8609832/68578034-30edd380-04ac-11ea-809f-b6ceb8d39fbd.png)

Fix it in pdf.js

```javascript
            var worker = new Worker(workerSrc);
            // IE11 下关闭iframe没有停止WebWorker
            // lijiancheng@agree.com.cn
            window.addEventListener('unload',function(){
              worker.terminate();
            });

            var messageHandler = new _message_handler.MessageHandler('main', 'worker', worker);
```

**Comment by Snuffleupagus** [comment]
This issue is first of all missing most of the relevant information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (e.g. there's no steps to reproduce the problem).
Secondly, as clearly stated in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, support for IE11 is now limited:
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. Going forward, only bugs which *completely* prevent the library and/or the default viewer from running will be accepted.
