### ISSUE TITLE
Problem with createLoadingTask o getDocument

### ISSUE THREAD

**Issue by jonathan010180** [mozilla/pdf.js#11333]
I have problem with getDocument
     send multiple get to server, how i can limit get.
Chrome:
data.pdf | 200 | fetch | Folio.e272658….js:24015 | (disk cache) | 2 ms
data.pdf | 206 | fetch | Folio.e272658….js:24171 | (disk cache) | 1 ms
Mozilla more from 4. 

DPFJs Version v2.3.200 and last vue-dpf version. 

![image](https://user-images.githubusercontent.com/57727704/68891940-a8b43c00-0700-11ea-923f-3bef39859895.png)

**Comment by timvandermeij** [comment]
The 206 response code is chunked loading, which is actually better because it allows your PDF files to render faster because the whole file doesn't need to be downloaded at once. You can disable this with the `disableRange` option, see https://github.com/mozilla/pdf.js/blob/21895aa75afb9d5a35d987923af241f349a50ea6/src/display/api.js#L187, but it is not recommended.

**Comment by jonathan010180** [comment]
pdf.disableRange=true   not working :(
