### ISSUE TITLE
Feature Request: Center thumbnails even when resizing sidebar

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#11336]
This is a feature request. It looks better if the thumbnails are always at the center when you resize the sidebar.

Tried to do some css work but no luck

**Comment by Snuffleupagus** [comment]
This sounds like something with a *clearly* disproportionate implementation effort in relation to it's usefulness. Especially considering that it'd likely required a bit of JavaScript, as opposed to just CSS, since if the thumbnails were centred they wouldn't just *automatically* wrap when the sidebar width changes.

All in all, I'd suggest WONTFIX as an appropriate resolution here and also point to http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---

Finally, you need to fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue!
