### ISSUE TITLE
Disable 'r' to rotate page.  Users get too confused and don't know what happened.

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#11341]
A non-trivial percentage of our users are accidentally hitting 'r' and then getting stuck/confused when the document is rotated.

The biggest challenge is that it persists between restarts and they can't figure out how it happened.

A lot of our users are complaining about this so I thought I would let you guys know.

It might also be nice (via API) to be able to selectively disable key bindings.

**Comment by Snuffleupagus** [comment]
> A non-trivial percentage of our users [...]

It's not really clear what "our users" are referring to here, so I'd guess that you're likely embedding/using the default viewer in some kind of custom setting.

> The biggest challenge is that it persists between restarts and they can't figure out how it happened.

If this is a common enough problem you may perhaps want to consider setting the `viewOnLoad` preference/option to INITIAL (rather than the default PREVIOUS) in your implementation, such that all documents *always* loads at the first page (and with default zoom/rotation/page layout/etc.). Please see https://github.com/mozilla/pdf.js/blob/be02e679728d86709b31aebc7e89c863512af91a/web/app_options.js#L146-L150 and https://github.com/mozilla/pdf.js/blob/be02e679728d86709b31aebc7e89c863512af91a/web/app.js#L55-L59

> A lot of our users are complaining about this so I thought I would let you guys know.

OK; unfortunately I'm not sure how actionable this issue is though...

> It might also be nice (via API) to be able to selectively disable key bindings.

That seems like something which could very easily have a disproportionate implementation/maintenance overhead for the default viewer, given the specialized nature of this (and it feels a tiny bit similar to something like e.g. #8077).
In general, please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by timvandermeij** [comment]
I agree with the above. The default viewer is specialized for the Firefox use-case, so other use-cases may require changing its code. I do think that https://github.com/mozilla/pdf.js/issues/8077#issuecomment-475868012 also applies here, so this is not something we aim to support in the default viewer given its use-case.
