### ISSUE TITLE
Problem with createLoadingTask o getDocument

### ISSUE THREAD

**Issue by jonathan010180** [mozilla/pdf.js#11342]
I have problem with getDocument
send multiple get to server, how i can limit get.
Chrome:
data.pdf | 200 | fetch | Folio.e272658….js:24015 | (disk cache) | 2 ms
data.pdf | 206 | fetch | Folio.e272658….js:24171 | (disk cache) | 1 ms
Mozilla more from 4.

DPFJs Version v2.3.200 and last vue-dpf version.

![image](https://user-images.githubusercontent.com/57727704/69083608-30f85100-0a21-11ea-99e7-238533b2d279.png)

pdf.disableRange = true
pdf.getDocument
and not working.

**Comment by timvandermeij** [comment]
You might also need to set `disableStream`; see the documentation at https://github.com/mozilla/pdf.js/blob/21895aa75afb9d5a35d987923af241f349a50ea6/src/display/api.js#L187-L193. Please read that first and if it does not work, provide a runnable example since otherwise we cannot help, i.e., provide all details from the issue template.
