### ISSUE TITLE
Is it possible to prehighlight in memory?

### ISSUE THREAD

**Issue by huzjakd** [mozilla/pdf.js#11357]
I am building a custom application.
I use the find controller like this:
```
findController.executeCommand('find', {
  query: 'query',
  highlightAll: true
})
```
and then I attach the findController to the text layer builder:
```
let textLayerBuilder = new TextLayerBuilder({
  textLayerDiv: textLayerDiv,
  pageIndex: page.pageIndex,
  viewport: scaledViewport,
  enhanceTextSelection: false,
  findController: findController
})
textLayerBuilder.setTextContent(textContent)
textLayerBuilder.render()
```

What this does is it renders the text layer first.
And then the findController kicks in and it goes through the rendered text and updates the DOM live with a `<span class="highlight">query</span>`.

My question is is it possible to update the DOM in memory so when the text layer gets rendered the first time it will already come with "highlight" spans?

**Comment by Snuffleupagus** [comment]
> My question is is it possible to update the DOM in memory so when the text layer gets rendered the first time it will already come with "highlight" spans?

No, since the `textLayer` is created in https://github.com/mozilla/pdf.js/blob/master/src/display/text_layer.js and highlighting of search results is done in https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js.

Note that the default viewer uses `streamTextContent` for performance reasons, rather than fetching all the textContent at once, and highlighting of search results won't generally work correctly *until* the entire `textLayer` is rendered. Hence trying to support what this issue asks for isn't really possible, or at the very least it would add an unwanted level of complexity to the `textLayer` building code.

**Comment by huzjakd** [comment]
To build upon this question:
With this setup highlighting seems really slow. A 2-3 seconds pass between the time the text layer gets rendered and the highlights visible on the screen.
If I try it in the demo viewer or even if I use a custom HTML replacer function instead of the find controller, it's almost instantaneous. So I'm not sure if I'm doing anything wrong.
Here is some more code if it helps:
```
let pdfLinkService = new PDFLinkService()

pdfLinkService.setDocument(pdf)
pdfLinkService.setViewer(viewer)
let findController = new PDFFindController({
	linkService: pdfLinkService
})
findController.setDocument(pdf)
findController.executeCommand('find', {
	query: self.localSearchTerm,
	highlightAll: true
})
```

**Comment by huzjakd** [comment]
What I think is happening is: I have a search page and I render a page or two from 20 pdfs on that page and I would like for highlighting to happen only on those pages, but what probably happens is that the FindController highlights on the entire pdf. So it highlights 20 full pdfs even though I only show a page or two from each, and that takes those 2-3 seconds. Possible? Can I specify pages for highlighting?
