### ISSUE TITLE
SEO - Google search issue

### ISSUE THREAD

**Issue by andreadd** [mozilla/pdf.js#11366]
Hello, my website consists in a library of PDFs files for students. PDFs are displayed online using pdf.js

I noticed that if a search keywords or sentences contained in PDF file using google search, it doesn't doesn't appear in the results. If I link the PDF directly (without the viewer), it is well indexed. So I think that the problem is related to the PDF viewer (pdf.js)

There are other websites using more advanced PDF viewers like Studocu. Here we have an example: https://www.studocu.com/it/document/politecnico-di-milano/costruzione-di-macchine/appunti/appunti-costruzione-di-macchine-aa20172018/968837/view

I would like that all PDF are displayed on the website with a PDF viewer like pdf.js. At the same time they must be well indexed on google search!

What is your opinion? Can I achieve this result?

Thank you for your suggestions.

Andrea

**Comment by timvandermeij** [comment]
The problem is that Google can only index direct links. However, the viewers loads the file dynamically and renders the text content dynamically, so beforehand there is no way to know what the text contents are. I don't think this can actually be achieved without some form of text layer extraction for each PDF file and finding a way to present that to Google's crawler...

**Comment by andreadd** [comment]
Hello Tim, thank you for your reply.
On my website links are in this format, i.e.:
https://www.domainname.it/appunti/viewer.html?file=appunti/Teoria/T_Parte_1.pdf

Can I consider it as direct link? Moreover all my links, like the one above, are in my sitemap.

I started thinking about this because there are other PDF viewers like Studocu's one that succeed in presenting to Google the PDF documents. i.e.:
https://www.studocu.com/it/document/politecnico-di-milano/costruzione-di-macchine/appunti/appunti-costruzione-di-macchine-aa20172018/968837/view

How is it possible?
I would like to improve the viewer for SEO.

Thank you

**Comment by sanzgrapher** [comment]
what method does these site like studocu use to show the pdf 
https://www.studocu.com/it/document/politecnico-di-milano/costruzione-di-macchine/appunti/appunti-costruzione-di-macchine-aa20172018/968837/view  

i am working on pdf js and using read only mode of the pdf.js .
Currently when i need to open an pdf file i need to give this type of url 
`https://example.com/generic/web/viewer_readonly.html?file={path to the file}`
or
`https://example.com/generic/web/viewer_readonly.html?file=./docs/PoU-CMP-225-DSA%20Tutorial-1666968672 `
in which if we alter the link like  
removed `viewer_readonly.html?file=./`
`https://example.com/generic/web/docs/PoU-CMP-225-DSA%20Tutorial-1666968672 `
we will be shown a pdf which is rendered from browser where we can download it
[![enter image description here](https://i.stack.imgur.com/yfBqg.png)](https://i.stack.imgur.com/yfBqg.png)


The thing i want to achieve is that i want to show document to user but dont want to allow user to download it or access it directly from file path 
if i alter the url from 
https://example.com/generic/web/viewer_readonly.html?file={path to the file}
or

**to**
https://example.com/generic/web/viewer_readonly/file/{path to the file}


Or is there any method so that we can use post method to provide url to path so that we dont need to provide full url using get method.

**Comment by vporton** [comment]
Google does support JavaScript links inside a web application, just need to use them correctly:
https://developers.google.com/search/docs/crawling-indexing/javascript/javascript-seo-basics#use-history-api
