### ISSUE TITLE
Can we have some examples with system.js?

### ISSUE THREAD

**Issue by Bluejanis** [mozilla/pdf.js#11381]
I am not able to use the PDFFindController with pdfjs and systemjs.

Displaying a pdf document works fine with this library, but the PDFFindController cannot be resolved. 
`import pdfjsLib from "pdfjs-dist";`

So maybe I need another library file, `pdfjs-dist/web/pdf_viewer.js`?

I tried importing that one as well, but that causes an error in the console:
`ReferenceError: require is not defined`

I couldnt find anything about these issues in the docs.
How does the PDFFindController work?

**Comment by Snuffleupagus** [comment]
SystemJS is only used in PDF.js development, but is *not* used in any of the builds that's officially distributed through https://github.com/mozilla/pdf.js/releases and https://github.com/mozilla/pdfjs-dist/
We're purposely not trying to provide *detailed* examples for lots of different frameworks/loaders, since it's difficult for people involved in the PDF.js project to provide support for them.

---

In this case, please refer to the `viewer components` examples, see https://github.com/mozilla/pdf.js/tree/master/examples/components, where e.g. the "simpleviewer" (see the `simpleviewer.js`/`simpleviewer.html` files) one shows exactly how to use `PDFFindController`.

> Displaying a pdf document works fine with this library, but the PDFFindController cannot be resolved.
> `import pdfjsLib from "pdfjs-dist";`

That's hardly surprising, if you look at how the `PDFFindController` is actually initialized in https://github.com/mozilla/pdf.js/blob/514b500a6ce8f983385ea3b50b982ad43b1ff111/examples/components/simpleviewer.js#L41-L44 and then how it's used in https://github.com/mozilla/pdf.js/blob/514b500a6ce8f983385ea3b50b982ad43b1ff111/examples/components/simpleviewer.js#L41-L44

---

Finally, when opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
