### ISSUE TITLE
Upside-Down Issue

### ISSUE THREAD

**Issue by aumweb** [mozilla/pdf.js#11392]
Hello,

We are trying to use the latest pdf.js build to show pdf in our PDF Embedder WordPress plugin
We are able to use the latest library but there is some problem with displaying pdf. For more clarification please see the screenshot attached.
![upside-down](https://user-images.githubusercontent.com/55882136/70414149-39bbd000-1a7f-11ea-98e4-ff71b9c18592.PNG)

Please let me know what I can do for this to correct the upside-down issue.

Thanks & Regards,
Bhavesh Akhade

**Comment by Snuffleupagus** [comment]
When opening an issue, you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by aumweb** [comment]
Hello,

Thank you for your quick response.

Sorry for the inconvenience caused to you.

Attach (recommended) or Link to PDF file here:
https://github.com/aumweb/pdf-embeder.git

Configuration:

Web browser and its version: **Google Chrome Version 78.0.3904.108**
Operating system and its version: **Windows 10**
PDF.js version: **2.4.142**
Is a browser extension: No its a WordPress Extention

Steps to reproduce the problem: 1. 2.
We use the PDF.js library to show the embedded pdf on WordPress Front-end

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/55882136/70423682-fd469f00-1a93-11ea-85b5-d5505e735866.png)


What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/55882136/70423653-edc75600-1a93-11ea-93d3-f544c7421b2a.png)


Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://inuscg.com/wordpress-inuscg/?page_id=859

Please let me know if you require more details

Thanks & Regards,
Bhavesh Akhade

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
https://github.com/aumweb/pdf-embeder.git

That's not an actual PDF document (i.e. one with a `.pdf` file extension).

> Is a browser extension: No its a WordPress Extention

That question refers to https://github.com/mozilla/pdf.js#browser-extensions.
Note that "WordPress" is not, in any way, affiliated with the PDF.js project and as such we cannot provide support for that here.

Finally, none of the links provided above seem to point to examples which are "short well-documented example", making it *extremely* difficult for anyone to tell what's happening.
Please keep in mind that this is, first and foremost, an open source *bug-tracker* rather than a support forum, as such all issues must be clear and concise in order to be valid.
