### ISSUE TITLE
Corrupted PDF viewer shows the original document not the last correct document

### ISSUE THREAD

**Issue by markotaht** [mozilla/pdf.js#11402]
There is a PDF with a number of incremental additions made. Now if any of there additions is corrupted(some bytes added or removed so that xref table is not correct) then the PDFviewer will show only the original file without the incremental updates. I dug around in the sourcecode a bit and found that xrefParsing in recovery mode will default to the original trailer before any incremental additions.
Expected behaviour would be that it will default to last correct trailer/xref before the corrupted addition.

**Comment by Snuffleupagus** [comment]
Please keep in mind that, generally speaking, recovering usable data from *corrupt* PDF files is a fairly difficult topic.

> I dug around in the sourcecode a bit and found that xrefParsing in recovery mode will default to the original trailer before any incremental additions.

That's not entirely accurate, since `XRef.indexObjects` will simply use the *first* trailer that is not obviously corrupt regardless of the document being edited or not.

---

Furthermore, when opening an issue you need to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, as-is there's unfortunately no actionable information provided here and this issue will thus be closed as INCOMPLETE.

**Comment by markotaht** [comment]
> That's not entirely accurate, since XRef.indexObjects will simply use the first trailer that is not obviously corrupt (regardless of the document being edited or not).

Then why in all my tests with different PDF files it always fell back to the original document without the incremental additions? When the PDF is correct it works fine, but once i corrupt it (for testing) all incremental updates are not shown.

**Comment by Snuffleupagus** [comment]
Please actually follow the *last* paragraph in https://github.com/mozilla/pdf.js/issues/11402#issuecomment-564561119. since having a *theoretical* discussion on this topic is unlikely to be able to provide any useful/meaningful answer.

**Comment by timvandermeij** [comment]
Yes, without examples this is not actionable.
