### ISSUE TITLE
getTextContent returns incorrect characters

### ISSUE THREAD

**Issue by kinztechcom** [mozilla/pdf.js#11401]
Attach (recommended) or Link to PDF file here: [Lidl Fairfax Finishes Plan.pdf](https://github.com/mozilla/pdf.js/files/3947368/Lidl.Fairfax.Finishes.Plan.pdf)

Configuration:
- Web browser and its version: Microsoft Edge Dev Version 80.0.345.0 (Official build) dev (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 2.2.228 Build: d7afb74a
- Is a browser extension: No

Steps to reproduce the problem:
1. Retrieve the text content of the provided pdf.

What is the expected behavior? (add screenshot)
Expected behavior would be that the text service in pdfjs returns the text reflected when opening the pdf.

What went wrong? (add screenshot)
The text service (getTextContent) is returning random characters. It appears that the number of characters is correct, but it is the wrong characters.
Note that the text does render correctly when the pdf is rendered.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Unfortunately there isn't any meaningful `ToUnicode` data to be found in *any* of the fonts in this PDF file, and it's thus impossible for text-selection/extraction to work correctly in this case.

Please note that this is a limitation of a *specific* PDF file, and not of the PDF.js library (or any other PDF viewer[1]), and without the PDF file itself containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.

---
[1] Similarly broken text-selection behaviour can be observed in e.g. Adobe Reader and PDFium (in Google Chrome) as well.
