### ISSUE TITLE
Investigate long page render times

### ISSUE THREAD

**Issue by zakangelle** [mozilla/pdf.js#11419]
Attach (recommended) or Link to PDF file here: _(cannot provide for privacy reasons)_

**Configuration**:
- Web browser and its version: Chrome 79.0.3945.79
- Operating system and its version: macOS Mojave 10.14.6
- PDF.js version: 2.0.489-2.3.200
- Is a browser extension: No

**What is the expected behavior?**

All pages in the PDF document can be scrolled to and rendered within a reasonable time frame.

**What went wrong?** 

I am running into an issue with a specific document where a page can take anywhere from 12-30 seconds to render. I unfortunately cannot provide this document, as it contains sensitive material, but can provide some detailed findings I recorded while debugging.

+ PDF document is 115 KB, 3 pages (612 × 792 resolution)
+ First and second page load very quickly, but third page (when scrolled to) remains in a loading state for 12-30 seconds
+ Opening the PDF viewer directly to third page initially renders it immediately
+ First page PDF text layer is empty, even though it contains text and _should_ have a text layer
+ PageCanvas `renderTask.promise` takes a while to resolve, and seems to point to where the bottleneck is
+ Flattening/resaving the PDF fixes the issue, but in this case is an insufficient workaround
+ Happens in Chrome, does _not_ happen in Firefox

Also did some performance profiling and found that the majority of the delay appears to happen specifically in PDF.js worker's `createImageData`:

![Screen Shot 2019-12-19 at 12 01 24 PM](https://user-images.githubusercontent.com/1393139/71197531-6ded7880-2257-11ea-9eeb-2c26966a1371.png)

![Screen Shot 2019-12-19 at 12 01 54 PM](https://user-images.githubusercontent.com/1393139/71197547-7a71d100-2257-11ea-9cbc-1dd15b7bb736.png)

I realize that without the offending document, this is difficult to debug or provide a fix for -- I am currently looking into the PDF.js source code and would appreciate any guidance on relevant areas to investigate.

**Comment by Snuffleupagus** [comment]
> Happens in Chrome, does _not_ happen in Firefox

That *could* mean that it's not entirely, or even at all, the PDF.js library that's at fault here. 

> I realize that without the offending document, this is difficult to debug or provide a fix for

Unfortunately it's not just difficult to help, but actually *impossible* without any way of reproducing the problem.

> I am currently looking into the PDF.js source code and would appreciate any guidance on relevant areas to investigate.

Please keep in mind that even if you managed to fix the problem yourself, a PR would generally need to include a test-case to be considered (since experience has shown that making changes to `core` code without tests isn't a good idea).

**Comment by timvandermeij** [comment]
I agree with https://github.com/mozilla/pdf.js/issues/11419#issuecomment-567613317. Given that the PDF file contains sensitive data, one way of obtaining a test case for this issue to become actionable would be to reduce it, i.e., use PDF editing tools to remove all sensitive data. I think that's the only way for this to be reopened, because in general it's impossible to help out with this.

> Flattening/resaving the PDF fixes the issue

This may also indicate some form of corruption and PDF.js needs to recover from, which might take more parsing time. Given the rest of your information, it could also mean that the image data in the original PDF is too large, and a resave compresses it. However, without being able to see the actual PDF file, it's only guessing at this point.
