### ISSUE TITLE
Test-drive Prettier

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11444]
This is a tracking issue since `mozilla-central` uses Prettier upstream, so to align with them it's probably best if we adopt it as well if it works for us. This should help with code formatting.

Being worked on by @Snuffleupagus.

**Comment by Snuffleupagus** [comment]
Enabling and running Prettier turns out to be entirely straightforward, since the only thing you need to do is: Add the Prettier configuration file, extend the ESLint configuration file to use the Prettier plugin, and finally remove redundant ESLint rules.
The only slight annoyance, which will take a little bit of time to fix, is to add `// prettier-ignore` to things that you don't want to autoformat, for example data structures such as https://github.com/mozilla/pdf.js/blob/c3a1c679500e1e4cfa13291f2bcd58ebbba2eb14/src/core/jpg.js#L47-L64

Stay tuned for, what will unfortunately be, an absolutely *huge* patch soon :-)
