### ISSUE TITLE
How to embed a font before rendering pages into canvas

### ISSUE THREAD

**Issue by arelaxend** [mozilla/pdf.js#11448]
Dear pdfjs contributors,

How to embed a font before rendering a pdf in a canvas ? Is there a proper way to do this ?

The context behind this question is the following. 

One has a backend that splits a big pdf into several pdfs of smaller size (chunks) using a Java SDK for example. By default embedded fonts are incorporated in each and every chunks. So, the sum of sizes of all chunks is way higher than the original big pdf file. Whenever one sends those chunks through the network therefore increases the overall throughput consumption.

One way to avoid this to happen is to remove all embedded fonts in chunks. And to insert those embedded fonts using pdfjs at rendering time. How to do this ?

This is an important topic to reduce carbon imprint in real scenario including for readers that do pages streaming.

Best,
A.

**Comment by Snuffleupagus** [comment]
> One has a backend that splits a big pdf into several pdfs of smaller size (chunks) using a Java SDK for example.

Generally, a better solution would probably be to *not* split the PDF files and instead ensure that your server supports range requests and make use of the PDF.js `disableAutoFetch` option to only load the data that's actually necessary; please see https://github.com/mozilla/pdf.js/blob/c3a1c679500e1e4cfa13291f2bcd58ebbba2eb14/src/display/api.js#L128-L136

> One way to avoid this to happen is to remove all embedded fonts in chunks.

The whole point of PDF (Portable Document Format) is that files should be well *portable*, and by not embedding fonts that's no longer the case. Because of the problems commonly associated with non-embedded fonts, you should *always* ensure that any non-standard font is embedded in the PDF file.

**Comment by arelaxend** [comment]
@Snuffleupagus you are absolutely right for the 95% worldwide use cases. But if you look in the market for pdf readers, you will find many readers does page splitting server side (few examples are https://www.cafeyn.co, https://www.pressreader.com and so on) and they all rely on pdfjs.

Here is an example of what a page streaming reader that uses pdfjs is: [here](https://app.fays.io/013ab276-1631-4fcc-8b1d-1bc04365f2d5).

**Comment by arelaxend** [comment]
@Snuffleupagus you are absolutely right for the 95% worldwide use cases. In the meantime, looking at the pdf readers market, one find that many readers does page splitting server side (few examples are https://www.cafeyn.co, https://www.pressreader.com and so on) and they all rely on pdfjs.

Here is an example of what a page streaming reader that uses pdfjs is: [here](https://app.fays.io/013ab276-1631-4fcc-8b1d-1bc04365f2d5). 

> The whole point of PDF (Portable Document Format) is that files should be well portable, and by not embedding fonts that's no longer the case. Because of the problems commonly associated with non-embedded fonts, you should always ensure that any non-standard font is embedded in the PDF file.

This is a good option for many use cases, still, some readers add page streaming option to be able to load specific pages, say page 22.

What I understand is that a font in a pdf is just "attached" at some place and referenced elsewhere. Whevener server side one remove the "attached" part, one would like to reattached the exact same lines using pdfjs before rendering the canvas.

**Comment by Snuffleupagus** [comment]
> One finds that few pdf readers does page splitting server side ([here](https://www.cafeyn.co), [here](https://www.pressreader.com)) and rely on pdfjs.

Well, we cannot really influence how people are choosing to implement the PDF.js library :-)

> Network consumption is too high because of redundant objects in chunks after splitting.

That shouldn't be a problem with `disableAutoFetch` set, since data will be loaded as necessary in response to the [`PDFDocument.getPage`](https://github.com/mozilla/pdf.js/blob/c3a1c679500e1e4cfa13291f2bcd58ebbba2eb14/src/display/api.js#L546-L553) calls being made in your code.

> To my knowledge, it is not possible to do this if one use range requests only.

And I'm telling you that it *does* work as described with range requests ;-)

**Comment by arelaxend** [comment]
I don't know how the fetch works in pdfjs.
1) Sometime you can not download the file using the pdfjs sinces files are stored in a cloud (not an URL) and one must use their loader.
2) One wants to display page 22 only, but fonts are store after page 45 (pdf is not linearized), what will the pdfjs fetcher download ?

**Comment by arelaxend** [comment]
Thank you. I have just done some sucessful tests and it seems that you are absolutely right from A to Z. I have tested with https://s3.amazonaws.com/visually-alexey-test/oversize_pdf_test_0.pdf

Still, do you think that this process works for all PDF including non linearize documents ?

**Comment by Snuffleupagus** [comment]
> Still, does one know whether this process works for all PDF including non linearized documents.

It works for all PDF documents, it's just more efficient for linearized ones.

**Comment by timvandermeij** [comment]
Closing as answered.

**Comment by arelaxend** [comment]
Is there a way to cancel fetching on `getPage()` ? The same way one `destroy() getDocument()`
