### ISSUE TITLE
Will the embedded script in PDF be executed?

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#11458]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: 2.1.183
- Is a browser extension: No

Steps to reproduce the problem:
1. Open a PDF containing a malicious script.
2. Will the script be executed?

What is the expected behavior? 
Any script inside the PDF will be disabled.

**Comment by timvandermeij** [comment]
If you're talking about embedded JavaScript, then the answer is "no" because we don't execute embedded JavaScript. The only thing we do with embedded JavaScript is parse it to check if there is a print instruction, and open the print dialog if that is the case. This is only string parsing though, no JavaScript is actually executed.
