### ISSUE TITLE
Linux/Windows bots are stuck

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#11478]
In #11459 we noticed that both the Linux and the Windows bots are having troubles; see https://github.com/mozilla/pdf.js/pull/11459#issuecomment-571196047. We also noticed this in https://github.com/mozilla/pdf.js/pull/11465#issuecomment-571108988.

@brendandahl @yurydelendik Could one of you restart both bots?

**Comment by Snuffleupagus** [comment]
Also, looking at the logs it seems that Google Chrome hasn't been updated in quite some time (note the excerpts below), which probably explains some of recently seen failures as well.
While it seems that Firefox updates automatically as expected (to track the Beta release channel), that doesn't seem to happen with Google Chrome (since the current Beta release is `80`).

Linux bot:
```
User agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/64.0.3282.71 Safari/537.36
```
Windows bot:
```
User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
```
