### ISSUE TITLE
Text characters rendered as black squares on OSX/Chrome

### ISSUE THREAD

**Issue by acwr** [mozilla/pdf.js#11479]
Example PDF: [acwr-issue.pdf](https://github.com/mozilla/pdf.js/files/4028182/acwr-issue.pdf)

Configuration:
- Web browser: Chrome 79.0.3945.88 (Official Build)(64-bit)
- Operating system: MAC OSX 10.15.2
- PDF.js version: 2.2.228
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF on OSX/Chrome using PDFJS (e.g. using the [PDFJS Demo](https://mozilla.github.io/pdf.js/web/viewer.html))
2. Observe incorrect text rendering (works correctly on OSX/Safari and Windows/Chrome etc).

What is the expected behavior?

![correct](https://user-images.githubusercontent.com/59585096/71856584-25c3c680-3130-11ea-9b2b-ae6fd748150d.png)

What went wrong?

![incorrect](https://user-images.githubusercontent.com/59585096/71856594-2e1c0180-3130-11ea-982f-179a812daa96.png)

Thanks!

**Comment by Snuffleupagus** [comment]
> Web browser: Chrome 79.0.3945.88 (Official Build)(64-bit)
> Operating system: MAC OSX 10.15.2
>
> Observe incorrect text rendering (works correctly on OSX/Safari and Windows/Chrome etc).

Given that this appears to be specific to a particular platform *and* browser, there's a fairly good chance that it's not actually a bug in the PDF.js library itself since in that case you'd probably expect it to (more) consistently broken.
If I were to guess: This might be a (more general) bug in the Font Loading API, when used with Canvas, specific to some configurations. Unfortunately, the best advice here may be to report the problem to the browser developers instead.
