### ISSUE TITLE
pdfjs-dist doesn't have core-js in dependencies

### ISSUE THREAD

**Issue by AndreyChernykh** [mozilla/pdf.js#11539]
Attach (recommended) or Link to PDF file here: N/A

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Mac OS
- PDF.js version: Any
- Is a browser extension: No

Steps to reproduce the problem:
1. N/A

**What is the expected behavior? (add screenshot)**

pdfjs-dist should have **all required 3rd-party packages** (including core-js) explicitly specified in the package.json _dependencies_.

**What went wrong? (add screenshot)**

If in the app a version of `core-js` mismatch the implicit expectation of the pdfjs-dist code in `pdfjs-dist/lib/shared/compatibility.js`, then it leads to unexpected behaviour or build errors, such as 
```
Module not found: Error: Can't resolve 'core-js/es/string/starts-with'
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

See similar issue https://github.com/parcel-bundler/parcel/issues/2819#issuecomment-475008861

**Comment by AndreyChernykh** [comment]
@Snuffleupagus Hi

How is the linked PR related to the bug?

**Comment by timvandermeij** [comment]
The pull request is making it more clear that the `/lib` folder shouldn't be used for anything other than unit tests. For using PDF.js you should use the pre-built versions because `core-js` is a dev dependency and its references will be resolved on build time. Hence there should be no need to put `core-js` in the dependencies of `pdfjs-dist`.

**Comment by AndreyChernykh** [comment]
@timvandermeij Got it! Thanks.
