### ISSUE TITLE
Release v2.3.200?

### ISSUE THREAD

**Issue by djmarland** [mozilla/pdf.js#11550]
2.3.200 has been in pre-release quite a while now. It has some good fixes in it that we are waiting for. Any estimates on when it might become a full release?
Thanks

**Comment by Snuffleupagus** [comment]
Duplicate of #11495.

**Comment by Snuffleupagus** [comment]
Duplicate of #11495, no time-line currently exists. 

Also, please note that there's generally *very* little difference, as far as stability is concerned, between stable and pre-release versions (since no code lands without e.g. all tests passing).
Firefox Nightly, for example, is always using what's more-or-less the latest `master` version of the PDF.js library. Hence the decision to use "stable" or "pre-release" versions is really up each implementer (and note that unless something is *really* broken, patches are generally not back-ported).

**Comment by djmarland** [comment]
Closing in favour of https://github.com/mozilla/pdf.js/issues/11495 (I did search but somehow missed it).
We were basically waiting for it to come through the standard package.json setup as the latest version, rather than targeting versions specifically. But we'll look again.

**Comment by Snuffleupagus** [comment]
> We were basically waiting for it to come through the standard package.json setup as the latest version, rather than targeting versions specifically.

If you're using `pdfjs-dist` via NPM, then it should be available with the `next` tag; see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions
