### ISSUE TITLE
Unclear timing behavior

### ISSUE THREAD

**Issue by clecap** [mozilla/pdf.js#11560]
I wrote a small next/previous - type of web-page application and use it on Chrome 79 @ MacOS Catalina with pdf.js 2.3.188. I use it as pdf viewer for locally, SSD stored PDFs on a MacPro.

I get very nice and fast rendering behavior which lets me step through pages in long (400+ page) PDFs. Rendering time for every page is 30-100 ms.

Every once a while the rendering time shoots up to 9000+ ms or even higher for one or two pages. Then things are normal again.

I am trying to understand that behavior. I suspect this is due to some housekeeping in the background, as this happens in particular when I render a larger number of pages immediately in a row. However, the long time of 9 sec makes me wonder what might be going on here.

**Comment by timvandermeij** [comment]
In general it's not possible for us to tell without access to the application itself. Most likely you're rendering too many canvases at one time. The default viewer tries to render only the pages that are actually in view, but the previous/next example does not, so it will unconditionally render all canvases which takes time. Closing as answered unless that's not the problem and access to the application is provided.

**Comment by clecap** [comment]
I did a few more tests. Actually, I only render into two canvases between which I alternate for smoother double buffering. However, I assume that the problem is connected with garbage collection as I give the system not enough time for settling down between two renderings. Reducing the load makes the phenomenon less frequent (but not disappear).

Actually I was hoping for some hints or pointers to documentation for debugging the connection to the worker backend. Sorry for intruding with my question on a project operating under a different schedule.

**Comment by Snuffleupagus** [comment]
If I were to *guess*, since there's no runnable example provided, a possible explanation could be that you're not using any of the API methods for cleaning up resources allocated by the PDF.js parsing/rendering.

When leaving a page, you probably want to call the `cleanup` method on the `PDFPageProxy` instance; see https://github.com/mozilla/pdf.js/blob/d6754d1e22fb7b3eb98ace8ce671eac094a4859d/src/display/api.js#L1268-L1273

Additionally, you may also want to occasionally (e.g. after a period of inactivity in your viewer) call the `cleanup` method on the `PDFDocumentProxy` instance since that will release resources on both the main- and worker-threads; see https://github.com/mozilla/pdf.js/blob/d6754d1e22fb7b3eb98ace8ce671eac094a4859d/src/display/api.js#L760-L763

**Comment by clecap** [comment]
**very helpful, thank you**.

I still experience hangs once in a while but the occasional calls to cleanup methods make it much more stable and reliable.
