### ISSUE TITLE
Add Github donate button

### ISSUE THREAD

**Issue by docduo** [mozilla/pdf.js#11600]
Dear PDF.JS contributors,

If one adds the "donate" button on Github for the repo, people might donate directly on Github.
https://help.github.com/en/github/administering-a-repository/displaying-a-sponsor-button-in-your-repository

Best, A.

**Comment by Snuffleupagus** [comment]
> If one adds the "donate" button on Github for the project, people might donate.

Perhaps, but how would those donations then be *fairly* distributed amongst current (and possibly prior) PDF.js contributors?
Furthermore, since the project is run by Mozilla I'm not even sure if something like this would even be allowed.

All-in-all, this issue probably ought to be closed; see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by docduo** [comment]
> Perhaps, but how would those donations then be fairly distributed amongst current (and possibly prior) PDF.js contributors?
Furthermore, since the project is run by Mozilla I'm not even sure if something like this would even be allowed.

Honestly, I did not even think about this!

**Comment by timvandermeij** [comment]
I'm positive about adding a donation button where the donations go to Mozilla itself.

@yurydelendik @brendandahl Could one of you comment on Mozilla's policy regarding this?

**Comment by Rob--W** [comment]
We are currently not interested in a Donate button, because the potential benefits of having it does not outweigh the complications of setting it up and supporting it.

This project is run by Mozilla, and has grown to where it is right now thanks to the help of our valuable volunteers. There is no system in place to directly donate to them, but you can support Mozilla at https://donate.mozilla.org/ or by contributing (see https://www.mozilla.org/contribute/).
