### ISSUE TITLE
Getting Partially Decode base64 Pdf

### ISSUE THREAD

**Issue by shipra-vishnoi** [mozilla/pdf.js#11617]
Attach (recommended) or Link to PDF file here:

Configuration:
- Chrome Version 80.0.3987.87
- Linux
- PDF.js version: '4.1.10'
- Is a browser extension: No

What went wrong? 
![Screen Shot 2020-02-19 at 2 42 21 PM](https://user-images.githubusercontent.com/28987538/74819238-14bcc680-5326-11ea-951b-64234b2584f2.png)

**Comment by shipra-vishnoi** [comment]
I have a base64 encoded pdf string. I can share if needed.
Please respond ASAP

**Comment by Snuffleupagus** [comment]
> PDF.js version: '4.1.10'

That version does *not* exist!

> I have a base64 encoded pdf string.

As is clearly mentioned in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, we specifically advise *against* using Base64-encoding since it's very inefficient memory-wise and because some browsers may even [truncate long Base64-strings](https://developer.mozilla.org/en-US/docs/Web/HTTP/Basics_of_HTTP/Data_URIs#Common_problems).

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine) since there's currently not enough information provided in order for the issue to be valid:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by shipra-vishnoi** [comment]
Thanks @Snuffleupagus for sharing your views. 
As I have checked there is no such library that can help me create custom pdfViewer except pdf.js.
Do you have any idea how can I overcome this issue or something else I can use?
