### ISSUE TITLE
Fix or switch test harness

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#11628]
On the linux bot I see lots of test-runs that have never finished with a lot of chrome processes open still. Chrome also seems to stay open on windows sometimes as well.

I'm starting to think we should consider switching our test runner to puppeteer or something similar that handles starting up and shutting down the browser.

**Comment by timvandermeij** [comment]
I agree. I have also been thinking about another approach, which would be to run all tests on Travis CI. We can run Chrome/Firefox headless nowadays and we can store the reference images in e.g., an S3 bucket. That means that ideally we could replace our bot with Travis CI integration. Of course it's also possible to use other test runners.

**Comment by brendandahl** [comment]
I'd like to do that step too. I think it's two separate pieces though 1) update the test runner and 2) change where we run stuff.

**Comment by timvandermeij** [comment]
@brendandahl Until we move forward with this, the Windows bot is hanging again. Could you reset it?

**Comment by brendandahl** [comment]
Gave it a kick.

**Comment by timvandermeij** [comment]
I now have the unit tests working with Puppeteer in Firefox and Chrome instead of our own browser implementation, but I'll need to fine tune it and extend it to the font/reference tests. I first tried the popular Karma framework, but it turns out that our requirements for running tests are too custom to be a good fit with Karma since it works best for standardized approaches. However, Puppeteer (while unknown to me before) provides a simple interface to start/stop the browser for our existing testing infrastructure. The objective is to replace `webbrowser.js` with a small amount of logic to call Puppeteer.

I wanted to look into this for a while now, but given that the Windows bot is still not happy after multiple kicks and I had some time, I moved this forward a bit :-)
