### ISSUE TITLE
Using Range Requests - Do the first call as a a HEAD call

### ISSUE THREAD

**Issue by AlexUrbanAc** [mozilla/pdf.js#11669]
I would like to ask whether it's possible to tweak the pdf.js library calls for a range request environment. pdf.js currently seems to always do its first call as a GET call. The backend we use, however, can quickly return the file size, which is kept in a database, but takes its jolly time to start receiving the actual document from file storage. If it's a big document, say, 100 MB with 10k pages, the difference will be a few seconds. For HTTP standard compatibility, GET requests have to return the full document if they are not aborted, and with the framework/pipeline used it is not possible to first send the headers, then wait whether the request will be aborted, and if it is not, start requesting the document from storage and send it.

In https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests it is described that a HEAD http request for the resource does return the Content-length and the Accept-Range header for evaluation. I would expect a Mozilla library supporting range requests to at least allow me to configure it to work according to Mozilla's own range request documentation.

**Comment by Snuffleupagus** [comment]
> In https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests it is described that a HEAD http request for the resource does return the Content-length and the Accept-Range header for evaluation.

As can be seen [in the relevant code](https://github.com/mozilla/pdf.js/blob/7b07b88e714f55b14b933e6fafc44b247aec41ab/src/display/network_utils.js#L23-L62), it's necessary to validate the `Content-Encoding` as well.

Furthermore, note that in all modern browsers the Fetch API will be used to load the PDF document (see [src/display/fetch_stream.js](https://github.com/mozilla/pdf.js/blob/master/src/display/fetch_stream.js)) since that by default allows the data to be fetched using the initial (200) request rather than aborting and using range requests.
Using streaming, rather than range requests, is not only more efficient *and* faster in general, but it also prevents errors with servers that don't allow resources to be fetched more than once.

If you have "special" requirements, with regards to how the PDF.js library is fetching data, then it's recommended to utilize the [`PDFDataRangeTransport`](https://github.com/mozilla/pdf.js/blob/7b07b88e714f55b14b933e6fafc44b247aec41ab/src/display/api.js#L499-L573) functionality since it allows *completely* custom data delivery; please find some additional information/pointers in https://github.com/mozilla/pdf.js/issues/11453#issuecomment-569347187.

All-in-all, I don't really think that any changes to the PDF.js library are necessary/desirable here.

**Comment by catmanjan** [comment]
@Snuffleupagus I think this issue is actually causing a lot of people headaches with streaming in PDF.js - I had a look around Stackoverflow and there are a lot of examples of people who could never get it working over the years, I suspect due to the assumption of their server technologies that a HEAD would have been issued to find the Content-Length header.

Any chance you can rethink this one?

**Comment by edoardocavazza** [comment]
Thanks @Snuffleupagus for pointing this out, I don't know why but I couldn't find it in my search.

I'd like to share a couple of observations regarding your previous explanation.

> As can be seen in the relevant code, it's necessary to validate the Content-Encoding as well.

I may be wrong, but as far as I know, Range requests don't accept content encoding, so it wouldn't make sense to validate the `Content-Encoding` header if the file can be served with a Range request. If you make a `HEAD` call to see if the server supports Range requests before making the `GET` call that validates a possible `Content-Encoding` header, you can avoid the second request.

> Using streaming, rather than range requests, is not only more efficient and faster in general, but it also prevents errors with servers that don't allow resources to be fetched more than once.

I understand that PDF rendering is the main focus of this project, but the great work that has been done on PDF.js has made the library much much more. In particular, if you use the library in a NodeJS web server to generate page renders on demand, it still seems more efficient to use Range requests to get only the necessary bytes instead of streaming the whole file.

---

I will still take a look at `PDFDataRangeTransport` to see if it solves my case, but I agree with @catmanjan about the possibility of revisiting this solution.
