### ISSUE TITLE
getJavaScript fails to return embedded script

### ISSUE THREAD

**Issue by ebickle** [mozilla/pdf.js#11685]
Attach (recommended) or Link to PDF file here: 
[breakout.pdf](https://github.com/mozilla/pdf.js/files/4313001/breakout.pdf)
[Horrifying PDF Experiments: Breakout](https://github.com/osnr/horrifying-pdf-experiments)

Configuration 1:
- Web browser and its version: Node.js  v12.14.1
- Operating system and its version: Windows 10 Version 1909 x64.
- PDF.js version: 2.2.228
- Is a browser extension: No

Configuration 2:
- Web browser and its version: Firefox 67.0.1 32-bit
- Operating system and its version: Windows 10 Version 1909 x64.
- PDF.js version: Latest (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
```javascript
const pdf = await pdfjs.getDocument({data: fs.readFileSync(path)});
console.log(await pdf.getJavaScript());
```

What is the expected behavior? (add screenshot)
* getJavaScript() should return the scripts embedded in the PDF.

What went wrong? (add screenshot)
* getJavaScript() returned null.

**Comment by Shakil-is-here** [comment]
you are missing a parantheses  at the end here ->
console.log(await pdf.getJavaScript());

**Comment by ebickle** [comment]
> btw , also you are missing a parantheses at the end here ->
> console.log(await pdf.getJavaScript());

Thanks, corrected it 👍 Unfortunately that was only a typo in the issue description here, not the code I wrote that uncovered the potential problem.

**Comment by Shakil-is-here** [comment]
that  was easy one for me to catch 😀

**Comment by mitchell-frost** [comment]
I am new to open source and pdf.js. I would like to work on this

**Comment by Snuffleupagus** [comment]
> getJavaScript() should return the scripts embedded in the PDF.

That's not actually the intended behaviour here, since your PDF document contains no embedded JavaScript in the /Catalog.
However, individual *pages* and/or *annotations* contain JavaScript which in this case can be accessed via either:
 - The `PDFPageProxy.getJSActions` method, see https://github.com/mozilla/pdf.js/blob/59f938d073333cd6ed0d9ee77cf2037e3dade53f/src/display/api.js#L1138-L1146
 - The `.actions` property on the Annotation-instances returned by the `PDFPageProxy.getAnnotations` method, see https://github.com/mozilla/pdf.js/blob/59f938d073333cd6ed0d9ee77cf2037e3dade53f/src/display/api.js#L1122-L1136

The reason that we're *not* simply providing one method in the API that extracts all embedded JavaScript, regardless of where in the PDF document it's placed, is that doing so would essentially force the entire document to load all at once (essentially breaking the entire purpose of streamed/ranged loading that PDF.js implements).
Hence, given that all of embedded JavaScript can now be returned (at least in PDF.js version `2.7.570` an up), this issue is fixed :-)
