### ISSUE TITLE
create-react-app example uses a fake worker

### ISSUE THREAD

**Issue by artdent** [mozilla/pdf.js#11729]
Configuration:
- PDF.js version: 2.4.456

Steps to reproduce the problem:
1. `cd examples/create-react-app`
2. `npm install && npm start`
3. Open the js console
4. Observe `Warning: Setting up fake worker.`

What is the expected behavior?
Example loads pdfjs.worker as an actual web worker

What went wrong?
A fake worker was used

Currently, `examples/create-react-app/package.json` depends on pdfjs-dist version 2.2.228, but I upgraded it to 2.4.456 and observed the same behavior.

A workaround is to serve the js worker statically in the `public/`, but it would be nice if the example included in the pdf.js repository were working out of the box.

**Comment by Snuffleupagus** [comment]
> Observe `Warning: Setting up fake worker.`

Looking at https://github.com/mozilla/pdf.js/blob/b86df97725cef5ec29feea3d61b8a7112c21ebcb/examples/create-react-app/src/pdf.tsx#L5-L7 and then https://github.com/mozilla/pdfjs-dist/blob/a3a0d672c2f3464e4bff95ad0a3b41341eb65a26/build/pdf.worker.entry.js, the example looks trivially wrong since that's obviously *not* how `workerSrc` can/should be used (given that it should be assigned a string).

> Currently, `examples/create-react-app/package.json` depends on pdfjs-dist version 2.2.228,

Having the version number hard-coded *really* isn't good :-(

---

The general problem with the [create-react-app](https://github.com/mozilla/pdf.js/tree/master/examples/create-react-app) example is that none of the few regular PDF.js contributors know much (or even anything) about React.
Consequently it's very difficult for us to maintain that example, not to mention provide support for it, and I do wonder if having it ends up does more harm than good!? @timvandermeij Should we perhaps consider removing that example?
