### ISSUE TITLE
Bad End Offset on first page visit

### ISSUE THREAD

**Issue by thebiff999** [mozilla/pdf.js#11731]
Configuration:
- Web browser and its version: Firefox (74.0), Chrome (80.0.3987.149), Edge (44.18362.449.0)
- Operating system and its version: Windows 10.0.18362
- PDF.js version: 3.8.2 (at least that is the version of the pdf.worker.min.js file of the Real3D Flipbook Plugin)
- Is a browser extension: no

Steps to reproduce the problem:
1. visit mitteilungsblatt-online.de/mb-epaper
2. open one of the posts and click the thumbnail

What is the expected behavior? 
When clicking on one of the articles a fullscreen overlay opens up in which the pdf is loaded and presented like a flipbook if everything works fine.
![issue](https://user-images.githubusercontent.com/62479917/77303072-996a7e00-6cf2-11ea-895a-36bb171c8f3c.png)

What went wrong?
The fullscreen overlay opens up but the pdf doesn't load. The javascript error seems to be in the line:
this.stream.onReceiveData(i, t);

However, if you reload the page the pdf loads just fine. This probably just has something to do with the cache and the real problem persists I suppose?
Unfortunately I'm not that skilled at coding with javascript and can't give much more inside than that.

![image](https://user-images.githubusercontent.com/62479917/77233244-94001d00-6ba6-11ea-8ff1-b576f12bee98.png)

Finally, I observed something strange with this issue. We sometimes use a simple pdf embedder plugin that also uses pdf.js. Those pages also throw the 'Bad End Offset' Error but the pdf loads anyway. You can check that out at this URL:
https://mitteilungsblatt-online.de/werfen-sie-einen-blick-ins-mitteilungsblatt/

I'd be so thankful for any help since the Real3D Flipbook plugin developer tells me that the problem is in pdf.js and not in the plugin itself. I'm sorry if there's any information missing or insufficient but hope to help out with more information if you point me into the right directions.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.8.2 (at least that is the version of the pdf.worker.min.js file of the Real3D Flipbook Plugin)

Unfortunately that version number simply does *not* exist. Note that the *latest* PDF.js release, as of this writing, is `2.4.456`; see https://github.com/mozilla/pdf.js/releases

Furthermore, we know nothing about "Real3D Flipbook Plugin" since that's not a project which is in any way affiliated with the PDF.js project. Hence it's unfortunately impossible for anyone here to provide help/support for it.

---

Finally, for issues with custom deployments of the PDF.js library; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by thebiff999** [comment]
Hi Snuffleupagus,

how can I find out the correct version?
I'm aware that the Plugin has nothing to do with PDF.js. I only mentioned it because I have the version number form the minified javascript file. Since the error also appears on when using other plugins, the issue is not linked to the plugin but PDF.js itself. That's why I'd hoped to get help here.

**Comment by timvandermeij** [comment]
You might be able to find the PDF.js version number in the browser console since it's printed there (assuming the plug-in author didn't remove it). Given that you mention `this.stream.onReceiveData`, this might be a problem of the web server not serving the content correctly, also given that you mention the intermittent nature of the problem.

**Comment by timvandermeij** [comment]
Closing since no additional information has been provided and there is nothing we can do to fix this.
