### ISSUE TITLE
Compare two PDF.js - side by side 

### ISSUE THREAD

**Issue by santoshprakash** [mozilla/pdf.js#11775]
Dear Team, 

is there any way to use compare two pdf.js side by side. I don't want to use iFrame. Plz help.

**Comment by timvandermeij** [comment]
You can render PDFs onto different canvases on the same page by providing another canvas when rendering; see https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html#L51-L55

Multiple viewers are best to embed in iFrames, otherwise you might run into #11626 which is an open issue.

**Comment by amitK007** [comment]
if we go with way, can we archive all those features of PDFJS like Search and print and download?
