### ISSUE TITLE
Error to load pdf in vue-pdf | sample: require('@/assets/sample.pdf')

### ISSUE THREAD

**Issue by patrykKlimczak** [mozilla/pdf.js#11791]
SPA apllication with vue.config.js

My configuration webpack:
```
  chainWebpack: config => {
    config.optimization.splitChunks({
      cacheGroups: {
        vendors: {
          name: 'chunk-vendors',
          test: /[\\\/]node_modules[\\\\/]/,
          priority: -10,
          chunks: 'initial'
        },
        common: {
          name: 'chunk-common',
          minChunks: 2,
          priority: -20,
          chunks: 'initial',
          reuseExistingChunk: false
        }
      }
    })
  },

  configureWebpack: {
    output: {
      globalObject: 'this',
      filename: 'js/[name].js',
      chunkFilename: 'js/[name].js',
    },
    plugins: [
      new WriteFilePlugin(),
      (process.env.NODE_ENV === "production" ?
        new BundleTracker({
          filename: 'webpack-stats-prod.json',
          publicPath: '/'
        }) :
        new BundleTracker({
          filename: 'webpack-stats.json',
          publicPath: 'http://localhost:8099/'
        })
      )
    ],
  }

```

**Comment by Snuffleupagus** [comment]
Was this issue perhaps opened against the wrong repository by mistake, since "vue-pdf" sounds like a different project?

As-is there's unfortunately no information provided that makes this an actionable/valid issue for the PDF.js library, and I also don't think that any of the PDF.js core contributors know much about the "Vue.js" framework; please note:
 - When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

 - Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
   > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
The `vue-pdf` bug tracker is here: https://github.com/FranckFreiburger/vue-pdf
