### ISSUE TITLE
How to test whether to use range-requests in pdf.js ?

### ISSUE THREAD

**Issue by wideweide** [mozilla/pdf.js#11820]
Steps to reproduce the problem:
1. I created a servlet for download files from a java file server： head to reponse accept-ranges,support range in header...
2. user pdf.js to show pdf: viewer.html?file=...download/fileid

What is the expected behavior? (add screenshot)
use range-requests

What went wrong? (add screenshot)
but just load the full file then display

So How to test whether to use range-requests in pdf.js ?

**Comment by Snuffleupagus** [comment]
> So How to test whether to use range-requests in pdf.js ?

See https://github.com/mozilla/pdf.js/blob/c218e94f664c97d3c95994d57b11d11488dae54b/src/display/network_utils.js#L23-L62

If that's not enough to answer your question, then please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue doesn't really seem actionable; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
