### ISSUE TITLE
Only trigger fallback bar for forms when user interacts with page

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#11838]
We're investigating ways to show the fallback bar less. One option is only show the bar when someone clicks within a document.

**Comment by timvandermeij** [comment]
I wondered how many times the fallback bar is still shown (since I barely see it anymore myself) and what the reasons for that are, and fortunately the new telemetry helps a lot here. The results [over here](https://telemetry.mozilla.org/new-pipeline/dist.html#!cumulative=0&end_date=2020-05-30&include_spill=0&keys=__none__!__none__!__none__&max_channel_version=nightly%252F78&measure=PDF_VIEWER_FALLBACK_REASON&min_channel_version=null&processType=*&product=Firefox&sanitize=1&sort_by_value=0&sort_keys=submissions&start_date=2020-05-20&table=0&trim=1&use_submission_date=0) are quite interesting and show that it's probably beneficial to make this change. It also gives some insights into other changes that might help here for other bars in the chart.

**Comment by bwinton** [comment]
Two questions:
1) How hard would it be to only show the fallback bar if the user tries to interact with the form (instead of clicking anywhere in the PDF)?
2) Will this also show the fallback bar for people who use accessibility technologies, and try to tab to the form fields?

**Comment by timvandermeij** [comment]
Fixed in the pull request above.
