### ISSUE TITLE
Printing Extra blank page in  - Paper size 'Letter & A5'

### ISSUE THREAD

**Issue by santoshprakash** [mozilla/pdf.js#11854]
Hi There, 

I have used  pdfjs - 2.0.719 and viewser js 2.0. I'm facing issues while printing documents. One extra page getting printed after each page in **Letter paper size**. It's working for A3, A4, legal. Issue only with A5 and letter paper size. 

Plz help

**Comment by Snuffleupagus** [comment]
> I have used pdfjs - 2.0.719

That version is *not* an official release, see https://github.com/mozilla/pdf.js/releases
Please make sure to *always* use the latest release, since everything else is unsupported.

> and viewser js 2.0

You cannot use different versions of the PDF.js core library and its default viewer, hence this doesn't really make much sense.

---

Finally, when opening an issue you need to provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) in order for the issue to be valid.

**Comment by santoshprakash** [comment]
thanks for reply @Snuffleupagus .. but any idea how to fix this issue. I may change the version in the coming days but as of now, I can't change it.

**Comment by timvandermeij** [comment]
Using the correct versions is a requirement for PDF.js. Moreover, note that we have limited influence on printing behavior due to browser restrictions, and in order for this issue to be actionable we need an example PDF file and clear steps to reproduce the problem.
