### ISSUE TITLE
pdfjslib is null in IE 11 and Edge

### ISSUE THREAD

**Issue by shingoonk** [mozilla/pdf.js#11870]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11.0.9600
- Operating system and its version: Window 7
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
I have included 
<script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>

and using 
var pdfjsLib = window['pdfjs-dist/build/pdf'];
pdfjsLib.GlobalWorkerOptions.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';

on my script code. But I am getting error null reference of 'GlobalWorkerOptions'. I did some google research and find out the pdfjslib is null somehow in IE 11. Everything works fine in Chrome and Safari. Please give me some advice on this. I've been spending 2 days on this issue.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
First of all, you should never link to "mozilla.github.io" directly since the file changes on every merge; it's an unstable version that might break. Use the official releases from https://github.com/mozilla/pdf.js/releases or https://github.com/mozilla/pdfjs-dist instead.

Second of all, support for IE11 and non-Chromium-based Edge is limited. Given that you say it works in other browsers, there is not much we can do here, especially without a running example.

**Comment by Ck14** [comment]
Friend, you solved it?
