### ISSUE TITLE
Undefined Is Not an Object (Evaluating 'n.renderTasks.length')

### ISSUE THREAD

**Issue by EkaterinaAksenchik** [mozilla/pdf.js#11893]
In our project we are using `react-pdf` (v4.1.0), which depends on `pdf.js`. On our production we got following error: 

``
EVENT ACTION: 02/05/2020 20:01:45 - TypeError: Undefined Is Not an Object (Evaluating 'n.renderTasks.length')
``

It looks like the error was in `pdfjs-dist`, because I found few lines with this code in this file https://github.com/mozilla/pdfjs-dist/blob/master/lib/display/api.js

**Comment by Snuffleupagus** [comment]
> In our project we are using `react-pdf` (v4.1.0),

That's a completely different project, and consequently we cannot provide support for that *here*.

Can you reproduce this when using the PDF.js library *directly*, without another project on top of it?
If not, then please report the problem to the `react-pdf` project instead (read on otherwise).

---

In its current form, this issue unfortunately contains *no* actionable information.
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
