### ISSUE TITLE
The image and the emoji disappear in PDF.js.

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#11895]
Attach (recommended) or Link to PDF file here:
[Image disappear (1).pdf](https://github.com/mozilla/pdf.js/files/4613123/Image.disappear.1.pdf)

Configuration:
- Web browser and its version: Chrome 81.0.4044.138
- Operating system and its version: macOS 10.15.4 
- PDF.js version: 2.1.183
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attachment With PDF.js 2.1.183.
2. Zoom out the file.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/18492951/81634155-efc98280-9440-11ea-9c49-8197565f82c6.png)

What went wrong? (add screenshot)
![ezgif-6-e620fb70467e](https://user-images.githubusercontent.com/18492951/81634393-7f6f3100-9441-11ea-9608-a7c5251d5129.gif)

I found that this problem was fixed in the version 2.4.456 (but the emoji still doesn't appear

), could you tell me how it was fixed, I need to make a patch.

Thanks!

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [Image disappear (1).pdf](https://github.com/mozilla/pdf.js/files/4613123/Image.disappear.1.pdf)

That PDF file contains nothing but an image of (part of) the default viewer, it's consequently *very* difficult to understand how it's relevant for this issue (especially the "emoji" part of the title).

> PDF.js version: 2.1.183

That's not an official release, please see https://github.com/mozilla/pdf.js/releases
Furthermore, only the latest releases are supported.

> What went wrong? (add screenshot)

The attached `gif` doesn't show the default viewer, hence it's again difficult to understand this part.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

All-in-all, this issue is currently missing clear and concise information describing the problem and in its current form it's not really actionable/valid.
