### ISSUE TITLE
PDFjs keeps accumulating workers everytime a pdf is viewed

### ISSUE THREAD

**Issue by Kaspanoombro** [mozilla/pdf.js#11897]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chromium Versão 81.0.4044.122 (Versão oficial) Built on Ubuntu , running on Ubuntu 19.10 64 bits
- Operating system and its version: Ubuntu 19.10 64 bits
- PDF.js version: 2.4.456
- Is a browser extension: no

Steps to reproduce the problem:
1. Run the example helloworld64 (edit to add a button to load another PDF)
2. After running, i go to the DevTools of Chromium and i can see that everytime i load a PDF, it creates a new webworker. 

What is the expected behavior? (add screenshot)
That adfter laoding the PDf, the webworker gets destroyed or that uses the same webworker instead of accumulating webworkers.

**Comment by Snuffleupagus** [comment]
You need to call the `destroy` method on the `PDFDocumentLoadingTask` instance, as returned by `getDocument`, in order to clean-up after each PDF document; see https://github.com/mozilla/pdf.js/blob/8b9492a5c41d0776488a27021981b60fbf23a3bf/src/display/api.js#L478-L496

---

If you want to re-use a worker, you can either:
 - Use the `GlobalWorkerOptions.workerPort` option, rather than `workerSrc`, to load the worker file; see https://github.com/mozilla/pdf.js/blob/8b9492a5c41d0776488a27021981b60fbf23a3bf/src/display/worker_options.js#L18-L22 and e.g. this example: https://github.com/mozilla/pdfjs-dist/blob/master/webpack.js
 - Manually initialize a `PDFWorker` instance and provide it in the `worker` parameter of the `getDocument` call; see https://github.com/mozilla/pdf.js/blob/8b9492a5c41d0776488a27021981b60fbf23a3bf/src/display/api.js#L111-L112
