### ISSUE TITLE
How not  to fetch data when  scrolling?

### ISSUE THREAD

**Issue by wideweide** [mozilla/pdf.js#11920]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
chrome 75
- Operating system and its version:
win 10
- PDF.js version:
2.0
- Is a browser extension:

Steps to reproduce the problem:
1. set disableAutoFetch": true, "disableStream": true
2. use view.html?file=***/test.pdf，has many pages such as 600
3. move scroll bar  from page 1 to 400

What is the expected behavior? (add screenshot)
just fetch  page 400's data from server
What went wrong? (add screenshot)
so many requests to fetch  data  between 1-400‘s data

So Is there a method not to fetch data when scrolling)?

**Comment by Snuffleupagus** [comment]
> So Is there a method not to fetch data when scrolling)?

No, since that could *very* easily break rendering if you don't fetch/render pages for *some* scrolling operations. Generally speaking, if the user scrolls the assumption must be that the intention is to actually fetch/render the now visible pages.

However if you go *directly* to another part of the document, using e.g. the pageNumber input, any pages between the current and the new one won't need to be fetched.

---

You could *possibly* change the source code to maybe delay fetching of pages when scrolling occurs, but this isn't something that the PDF.js library can/will support.

**Comment by wideweide** [comment]
> 
> 
> > So Is there a method not to fetch data when scrolling)?
> 
> No, since that could _very_ easily break rendering if you don't fetch/render pages for _some_ scrolling operations. Generally speaking, if the user scrolls the assumption must be that the intention is to actually fetch/render the now visible pages.
> 
> However if you go _directly_ to another part of the document, using e.g. the pageNumber input, any pages between the current and the new one won't need to be fetched.
> 
> You could _possibly_ change the source code to maybe delay fetching of pages when scrolling occurs, but this isn't something that the PDF.js library can/will support.

I try to read the source code, delay fetching maybe is not a good method:can not reduce the requests，and so complex
Disable or hide the scrollbar maybe is the better metod now?

I have another idea,to imply new style scrollbar when a file has pages more than 20 or 100,when scrolling,just display a big number of page,when stop,go directly to the target page

scrolling when a file has too many pages，you can hardly see the page content..
