### ISSUE TITLE
Along with disableAutoFetch option as true，how to control when trigger fetch data

### ISSUE THREAD

**Issue by wideweide** [mozilla/pdf.js#11933]
Configuration:
- Web browser and its version:
chrome 75
- Operating system and its version:
win 10
- PDF.js version:
2.0
- Is a browser extension:

Steps to reproduce the problem:
1. set disableAutoFetch": true, "disableStream": true，var DEFAULT_RANGE_CHUNK_SIZE = 1666666;
2. use view.html?file=***/test.pdf，has many pages such as 600
3. scroll pages ，when at page 10（may other page），pdf.js show loading and will wait a while form fetch data;then at page 20 , it will wait fetch data too

What is the expected behavior? (add screenshot)
pre fetch data at page 5,then when scroll to page 10, pdf.js can show a page without wait fetching

How can I do this?

**Comment by Snuffleupagus** [comment]
> DEFAULT_RANGE_CHUNK_SIZE = 1666666;

Using such a large value might not be generally advisable, since in many cases that could actually end up slowing down loading since that much data may take some time to transfer from the server.

>  scroll pages ，when at page 10（may other page），pdf.js show loading and will wait a while form fetch data;then at page 20 , it will wait fetch data too

Well, that's essentially how `disableAutoFetch` is intended to work. The whole purpose of using it is to *only* fetch/render pages as they become visible in the viewer, thus saving bandwidth upfront.

Basically you'll have to choose here: Either load data as-needed with `disableAutoFetch` set and accept *some* waiting for pages to load on demand, or use default settings to load the entire file directly such that all data is available upfront.

> pre fetch data at page 5,then when scroll to page 10, pdf.js can show a page without wait fetching

You'd have to modify [getHighestPriority](https://github.com/mozilla/pdf.js/blob/9d38dd4e8b53eada0c506e26a2b3827d8d45e3d0/web/pdf_rendering_queue.js#L91-L137) to pre-render more pages than it currently does.
However, please note that doing so will affect general performance negatively [as already explained in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages) and that pre-rendering a larger number of pages also risk making `disableAutoFetch` more or less pointless by forcing a lot of data to load upfront.

---

All-in-all, this seems very similar to issue #11933, and again you'd have to modify the source code to achieve what you ask (although that's not really recommended as described above).

**Comment by wideweide** [comment]
>All-in-all, this seems very similar to issue #11933, and again you'd have to modify the source code to achieve what you ask (although that's not really recommended as described above).

This  is just #11933 :)

The best way seems to:
1. keep DEFAULT_RANGE_CHUNK_SIZE = 64k
2. modify getHighestPriority,when view page no. 1,just pre fetch page no. 6' data just like down?

```
if (scrolledDown) {
                  var nextPageIndex = visible.last.id + 5;// next 5 page no
    
                  if (views[nextPageIndex] && !this.isViewFinished(views[nextPageIndex])) {
                    return views[nextPageIndex];
                  }
                } else {
                  var previousPageIndex = visible.first.id - 2;
    
                  if (views[previousPageIndex] && !this.isViewFinished(views[previousPageIndex])) {
                    return views[previousPageIndex];
                  }
                }
```

**Comment by Snuffleupagus** [comment]
> This is just #11933 :)

That's a simple typo, but the point is that this is *very* similar your old issue #11920.

> modify getHighestPriority,when view page no. 1,just pre fetch page no. 6' data just like down?

Please note that as explained in https://github.com/mozilla/pdf.js/issues/11933#issuecomment-634314487, we really don't recommend doing that; see this part in particular:

> However, please note that doing so will affect general performance negatively [as already explained in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages) and that pre-rendering a larger number of pages also risk making `disableAutoFetch` more or less pointless by forcing a lot of data to load upfront.

**Comment by wideweide** [comment]
in #11920 
>I have another idea,to imply new style scrollbar when a file has pages more than 20 or 100,when scrolling,just display a big number of page,when stop,go directly to the target page
I have writen some code to do this.

>Edit: Also the changes you're suggesting above are wrong, since they would break "normal" pre-rendering in ways you probably don't expect. We won't support this use-case, for the reasons explained above.
it seems worked well... so what is the correct method to pre fetch data ? may be 
1. must set chunksize to a big number,this will render page more than 5 page
2. modify getHighestPriority: var nextPageIndex = visible.last.id + 5; // this is wrong?
I can accept more or less downloading some data

**Comment by timvandermeij** [comment]
Closing since this is answered and not something we can further support in the library.
