### ISSUE TITLE
Two-page scrolling

### ISSUE THREAD

**Issue by SieC65** [mozilla/pdf.js#11946]
This problem applies to all the documents that I have ever opened.

Configuration:
- Web browser and its version: Google Chrome 83.0.4103.61 , also Firefox 76.0.1
- Operating system and its version: Win 7 x64
- PDF.js version: 2.3.164 version of extension
- Is a browser extension: yes

Steps to reproduce the problem:
1. Select any "Spreads" mode of view. Or "No spreads", but wrapped scrolling mode - doesn't matter. 
2. Select "Page Fit" zoom mode. We should get several pages per screen
3. Try to scroll document by any of keys: Page Down, n, j, Space Bar

I expect to see the next group of pages (for example, if there are 5 pages on the screen, I expect to see the next 5 pages)

What went wrong? Scrolling goes one page at a time, so if I have 5 pages on the screen, nothing happens when I pressed Page Down 5 times . For the 6th time I finally see the next group of pages.

Just for example: Adobe Reader scrolls properly in two-page mode, 2 pages at once. 

P.S. Sorry for my English, I hope I correctly stated the essence of the problem

**Comment by SieC65** [comment]
Please let me know if this is a known mistake, or if it is not considered a mistake at all.
Should I hope that it will be fixed in the future?

Just to be sure that I clearly explain the problem, I attach 2 screenshots. I expect to see pages 4-7 after the first press of a key "Page Down". But I have to press it 4 times, of which the first three times nothing happens.

![pdfjs-1](https://user-images.githubusercontent.com/20519714/85285360-77bb9700-b499-11ea-9e9d-f1e629f4dc6c.png)
![pdfjs-2](https://user-images.githubusercontent.com/20519714/85285365-7be7b480-b499-11ea-9da0-8255f6479781.png)

**Comment by Tsudico** [comment]
I have also noticed this behavior. When showing multiple pages, you must remember which "page" you are on when using previous/next page keys because they operate on a page level and not on the view level.

This seems to be an issue due to the following lines in web/app.js:
`
function webViewerNextPage() {
  PDFViewerApplication.page++;
}
function webViewerPreviousPage() {
  PDFViewerApplication.page--;
}
`

I think it could possibly be fixed by adjusting to the following code:
`
function webViewerNextPage() {
  PDFViewerApplication.page += PDFViewerApplication.pdfViewer._getVisiblePages().views.length;
}
function webViewerPreviousPage() {
  PDFViewerApplication.page -= PDFViewerApplication.pdfViewer._getVisiblePages().views.length;
}
`

But there probably is a better way.

**Comment by ikartikgautam** [comment]
Hii, I will be creating a pull request soon, to fix this issue. Currently I am thoroughly testing it.

**Comment by Snuffleupagus** [comment]
Please note that the changes suggested in https://github.com/mozilla/pdf.js/issues/11946#issuecomment-663090342, for a variety of reasons, are unfortunately *not* a good idea in general.

**Comment by Snuffleupagus** [comment]
Please note that the changes suggested in https://github.com/mozilla/pdf.js/issues/11946#issuecomment-663090342, for a variety of reasons, are unfortunately *not* a good idea in general and that a proper solution would be more involved than it may look at first (which is why this issue is still open).

**Comment by Snuffleupagus** [comment]
Please note that the changes suggested in https://github.com/mozilla/pdf.js/issues/11946#issuecomment-663090342, for a variety of reasons, are unfortunately *not* a good idea in general and that a proper solution will be more involved than it may look at first (which is why this issue is still open).

**Comment by ikartikgautam** [comment]
okay thanks, i was about to create a pull request.
