### ISSUE TITLE
can't display the whole pdf

### ISSUE THREAD

**Issue by 1160300208** [mozilla/pdf.js#11942]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/web/viewer.html

Configuration:
- Web browser and its version:
**Google Chrome 83.0.4103.61 (正式版本) （64 位）**
- Operating system and its version:
**Ubuntu 18.04.4 LTS**
- PDF.js version:
**2.3.164**
- Is a browser extension:
**Yes**

Steps to reproduce the problem:
1. **open a pdf file with pdf.js extension**

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/34236718/83267876-69aa8b80-a1f7-11ea-877c-28107178b828.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/34236718/83267984-8d6dd180-a1f7-11ea-84dd-4c3449c2cc08.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by 1160300208** [comment]
The extension works well on Win10(Google Chrome) and Ubuntu18.04(Firefox) except Ubuntu18.04(Google Chrome).

**Comment by timvandermeij** [comment]
It looks like this is a platform issue since it works on other platforms. Usually this can happen because of outdated/incorrect graphics drivers, so please update them if not done yet. Otherwise, please file an upstream issue in the Chrome bug tracker for this, since it's not something we can address unfortunately.
