### ISSUE TITLE
getDocument(...).then is not a function

### ISSUE THREAD

**Issue by josephernest** [mozilla/pdf.js#11960]
The following code loads the PDF file successfully from a filepicker into a byte array, but fails PDF.js with

> Uncaught TypeError: pdfjsLib.getDocument(...).then is not a function

Code:
```
<html>
<head>
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
</head>
<body>
<input type="file" id="file">
</body>
<script>
pdfjsLib.GlobalWorkerOptions.workerSrc = 'https://mozilla.github.io/pdf.js/build/pdf.worker.js';
document.getElementById('file').onchange = function(event) {
    var file = event.target.files[0];
    var fileReader = new FileReader();  
    fileReader.onload = function() {
        var typedarray = new Uint8Array(this.result);
        console.log(typedarray);
        pdfjsLib.getDocument(typedarray).then(function(pdf) {
            console.log(pdf);
        });
    };
    fileReader.readAsArrayBuffer(file);
}
</script>
</html>
```

Mostly coming from the main answer of https://stackoverflow.com/questions/22048395/how-to-open-a-local-pdf-in-pdfjs-using-file-input.

**How to make it work?**

PS: I have seen a few similar questions like https://github.com/mozilla/pdf.js/issues/9075 closed because they lacked a minimal reproducible example.

**Comment by Snuffleupagus** [comment]
As shown in the JSDocs, `getDocument` returns a `PDFDocumentLoadingTask` instance: https://github.com/mozilla/pdf.js/blob/8fc1126b5a2b6d2fa0cfa98a061882ef21c1abc9/src/display/api.js#L169-L180

which has a `promise` property which contains the information you want here:
https://github.com/mozilla/pdf.js/blob/8fc1126b5a2b6d2fa0cfa98a061882ef21c1abc9/src/display/api.js#L453-L459

According to the code/docs quoted above, the following thus works:
```javascript
  const loadingTask = pdfjsLib.getDocument(/* data here */);
  loadingTask.promise.then(pdfDocument => {
    // The document is loaded here...
  });
```

---

Generally speaking, note that linking to code at https://mozilla.github.io/pdf.js/build/ is never a good idea (since those files change with every merge).
Please always use official releases instead, see https://github.com/mozilla/pdf.js/releases

Finally, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by josephernest** [comment]
Thanks @Snuffleupagus for your answer. Finally just the `.promise.` was missing, I'll remember this.

More generally, is it mandatory to use asynchronous code? For example:

    pdfjsLib.getDocument(typedarray).promise.then(function(pdf) {
            for (var i = 1; i <= pdf.numPages; i++) {
                pdf.getPage(i).then(function(page) {
                    var viewport = page.getViewport({scale: 1});
                    var context = canvas.getContext('2d');
                    ...

does not work because it would require multiple canvas:

> Error: Cannot use the same canvas during multiple render() operations.

Is there a way to use synchronous code instead? 

    page = pdf.getPage(i);

in replacement of `pdf.getPage(i).then(function(page) {` is not working.

**Comment by Snuffleupagus** [comment]
> More generally, is it mandatory to use asynchronous code?

Yes; note also that generally speaking *a lot* of modern JavaScript code is asynchronous.

> does not work because it would require multiple canvas:
> 
> > Error: Cannot use the same canvas during multiple render() operations.

The solution is simple though, either: create a new canvas for each page, or wait for one page to finish rendering before starting the next one.

> Is there a way to use synchronous code instead?

No, for all intents and purposes *all* PDF.js API-methods are asynchronous at this point in time.

**Comment by josephernest** [comment]
Thanks @Snuffleupagus for your reply. Just to conclude, how would you transform:

    for (var i = 1; i <= pdf.numPages; i++) {
            pdf.getPage(i).then(function(page) {
               ... 
            });
    }

to make it "wait for one page to finish rendering before starting the next one"?
