### ISSUE TITLE
Zoom resets to 'page fit' when clicking TOC

### ISSUE THREAD

**Issue by jeenuv** [mozilla/pdf.js#11970]
Attach (recommended) or Link to PDF file here: https://download.clojure.org/papers/clojure-hopl-iv-final.pdf

Configuration:
- Web browser and its version: Firefox 77.0.1
- Operating system and its version: Linux Mint
- PDF.js version: Bult-in (I think)
- Is a browser extension: No

Steps to reproduce the problem:
1. Load any PDF. Adjust zoom to a custom level, say 160%.
2. Click any link on the table of contents.
3. Zoom resets to 'page fit'.

What is the expected behavior? (add screenshot)
Different zoom level to what's loaded by default is required on some pages. Zoom level set by user should be respected and preserved when jumping from a TOC link. Otherwise, it'd be a pain to repeatedly adjust the zoom level when jumping around the document.

**Comment by Snuffleupagus** [comment]
This behaviour is specified by the PDF document *itself*, since the destinations explicitly states that the "page-fit" zoom level should be used.

Duplicate of issues such as #5064 and #11606; note that PR #11608 added an option to disable this behaviour (in Firefox, search for "pdfjs.ignoreDestinationZoom" in about:config).

**Comment by jeenuv** [comment]
I see. I tried a couple of other PDFs, which had the same behaviour. That made me think it's the viewer that's doing this.

The option works for me. Thanks.
