### ISSUE TITLE
Unable to Add text layer on the said pdf.

### ISSUE THREAD

**Issue by crookedcircle** [mozilla/pdf.js#11975]
Attach (recommended) or Link to PDF file here: 
https://theprismac.com/demo.pdf
https://theprismac.com/doc.pdf
https://theprismac.com/doc1.pdf

Configuration:
- Web browser and its version: Chrome / Firefox both
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
1. upload different pdf files from the provided links on top.
2. For the first one, I am able to select text. For the other two pdf files, I am unable to select the text.

What is the expected behavior? (add screenshot) I want to be able to select the text. That selected text should be visible in the text box n the right side. I am not sure as to how should will it differentiate if the pdf has images or it is a text based pdf. 

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  https://theprismac.com/pdfjs/

Please help!

**Comment by Snuffleupagus** [comment]
The only way that text-selection/extraction works in the PDF.js library, is if the PDF document actually contains text-rendering operators (since this isn't an OCR library).

Only your *first* document contains actual text, the other two only contains images, and consequently text-selection simply cannot work; as such this issue isn't really actionable/valid.

In order to determine if there's text on a particular page, you can use the `getTextContent` method on the `PDFPageProxy` instance; see https://github.com/mozilla/pdf.js/blob/c97200ff5921518048c5f741f1c1b2b03ea18630/src/display/api.js#L1186-L1191
If there's no text-content available, the resolved `items` Array will thus be empty; note https://github.com/mozilla/pdf.js/blob/c97200ff5921518048c5f741f1c1b2b03ea18630/src/display/api.js#L808-L814
