### ISSUE TITLE
PDF not render in mobile (ios 13). Work in desktop (Chrome)

### ISSUE THREAD

**Issue by andersb79** [mozilla/pdf.js#11982]
Attach (recommended) or Link to PDF file here:
https://www.dropbox.com/s/qrh4ggn7axefq98/notRendering.pdf?dl=0

Configuration:
- Web browser and its version: Safari on iOS or Chrome on iOS
- Operating system and its version: iOS 13.5
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html
- Is a browser extension:

Steps to reproduce the problem:
1. Go to https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the pdf (link above)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Blank page, pdf not rendering. If you do this on desktop it will render.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by CareerFairPlus** [comment]
Experiencing the same issue.  Same OS versions and Browser versions.  All of these tests pass in both browsers on iOS: https://mozilla.github.com/pdf.js/features

**Comment by hqh0713** [comment]
Experiencing the same issue

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari on iOS or Chrome on iOS
> Operating system and its version: iOS 13.5

Given that this only appears to be broken on a *specific* platform, it unfortunately seems somewhat unlikely to be an issue that can be fixed in the PDF.js library (it *could* e.g. be that the platform blocks large `<canvas>` elements).
Generally speaking, if it were a PDF.js bug you'd kind of expect it to be consistently broken everywhere. /cc @timvandermeij
