### ISSUE TITLE
pdfjsLib.GlobalWorkerOptions.workerSrc and PDF occasionally failing to render

### ISSUE THREAD

**Issue by NicolayD** [mozilla/pdf.js#11989]
Configuration:
- Web browser and its version: Firefox Developer 78.0b2 (64-bit)
- Operating system and its version: macOS Catalina 10.15.2
- PDF.js version: 2.3.200
- Is a browser extension: No

Steps to reproduce the problem:
I use pdf.js in 2 React components - a parent one with a few children components for each page.

In the parrent I have:
```
componentDidMount() {
    this.renderPdf(this.props.pdf_url);
}
```

In `renderPdf` I have:
```
renderPdf(doc) {
    var pdfjsLib = window.pdfjsLib;
    pdfjsLib.getDocument(doc).promise.then(this.renderPages);
  }
```

And in `renderPages` which receives an argument for example `renderPages(doc)` based on the number of pages I call:
```
for (var num = 1; num <= doc.numPages; num++) {
      doc.getPage(num).then(this.renderPage);
}
```

Now, `renderPage` adds a child `Page` component for each PDF page and receives as props (passed as props again to the parent originally) a CDN url for `pdfjsWorkerSrc`. Before rendering each page in it I call:
```
var pdfjsLib = window.pdfjsLib;
pdfjsLib.GlobalWorkerOptions.workerSrc = this.props.pdfjsWorkerSrc;
```

I use `window.pdfjsLib` and not `window['pdfjs-dist/build/pdf']` - I guess it might be helpful information.

Then I have some canvas settings and ultimately:
```
var renderContext = {
      canvasContext: context,
      viewport: viewport
};

var renderTask = page.render(renderContext);
renderTask.promise.then(function() {
      console.log('Page rendered');
 });
```

Which I believe is similar to an official example that I have seen at https://mozilla.github.io/pdf.js/examples/ but I cannot seem to find currently.

What is the expected behavior?
The expected behaviour is for the PDF to always render.

What went wrong?
The PDF sometimes does not render, but then after refreshing it renders. Usually it does not render on the first load and after refreshing it is ok.

I believe I have been having this issue in the last few months and it was not present before.
I wonder if it might be due to the loading of the worker script from the CDN url or perhaps due to the downloading of the PDF.

However, the strangest thing is that if I remove 
```
pdfjsLib.GlobalWorkerOptions.workerSrc = this.props.pdfjsWorkerSrc;
```

And basically ignore the worker, it seems to solve the issue and the PDFs seem to render properly every time. It may not be as strange as it seems to me currently though, so I thought of asking in an issue here so that I could understand it properly and see if I am not doing something I should actually not do.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.3.200

Please note that that version is no longer supported, please find the latest releases at https://github.com/mozilla/pdf.js/releases 

> I use pdf.js in 2 React components

Unfortunately I don't believe that any of the (few) regular PDF.js contributors know anything about React, as such it's thus very difficult for anyone here to help.

Furthermore, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Which I believe is similar to an official example that I have seen at https://mozilla.github.io/pdf.js/examples/ but I cannot seem to find currently.

While there *were* previously a React example in this library (as contributed by a React user), unfortunately a couple of things were wrong with it (w.r.t. how it used the PDF.js library) and it was thus removed.
Since, as mentioned, the regular PDF.js contributors don't know React trying to fix/maintain and not to mention providing support for it would be really difficult, the decision in the end was thus that having no "official" React example rather than a broken/unmaintained one was overall better.

Finally, note that there's third-party React-projects which use PDF.js under the hood; one such example is https://github.com/wojtekmaj/react-pdf

**Comment by NicolayD** [comment]
Thank you for your response! I'll close the issue for now.
