### ISSUE TITLE
Setting up fake worker failed: "Cannot read property 'WorkerMessageHandler' of undefined"

### ISSUE THREAD

**Issue by dharmatv** [mozilla/pdf.js#11990]
Configuration:
Chrome version: 81.0.4044.129
OS: Ubuntu
PDF.js version: Using pdf-dist npm module(https://www.npmjs.com/package/pdfjs-dist)
Is a browser extension: No

Pdf file is:  http://www.africau.edu/images/default/sample.pdf

Problem: 
I am using a pdf-dist library, It was working correctly, but suddenly got an issue like the following picture
https://snipboard.io/A67H4J.jpg

Could you guys please provide any solution.

**Comment by Snuffleupagus** [comment]
> PDF.js version: Using pdf-dist npm module(https://www.npmjs.com/package/pdfjs-dist)

Please provide the *actual* version number when opening an issue.

> [...] but suddenly got an issue like the following picture

(Generally speaking, it's always easier/quicker for people if you actually *attach* screen-shots directly to the issue rather than linking to it.)

The screen-shot *clearly* shows that you haven't setup the PDF.js library correctly, based on the warning messages, since you should *always* ensure that the `workerSrc` property is set correctly such that the `pdf.worker.js` file can be found/loaded; basically you need to add a line looking something like the below (obviously with the path adjusted as necessary for your deployment) *before* calling `pdfjsLib.getDocument(...)` or doing anything else: 
```javascript
pdfjsLib.GlobalWorkerOptions.workerSrc = "../some/path/to/pdf.worker.js";
```

---

Finally, please note that this is a *bug tracker* rather than a support forum and that this issue is missing too many details to be actionable/valid; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dharmatv** [comment]
Using below version for
pdfjs-dist:  2.2.228

**Comment by gold3bear** [comment]
```
const pdfjs = require("pdfjs-dist");
pdfjs.GlobalWorkerOptions.workerSrc = require("pdfjs-dist/build/pdf.worker.entry.js");
```

**Comment by Nataliasem** [comment]
I use Pdfjs v2.8.335 with legacy supporting in this way:

import * as pdfjsLib from 'pdfjs-dist/legacy/build/pdf'
import PDFJSWorker from 'pdfjs-dist/legacy/build/pdf.worker.entry'

pdfjsLib.GlobalWorkerOptions.workerSrc = PDFJSWorker

**Comment by Lgowen** [comment]
> ```
> const pdfjs = require("pdfjs-dist");
> pdfjs.GlobalWorkerOptions.workerSrc = require("pdfjs-dist/build/pdf.worker.entry.js");
> ```

In order not to increase the size of the mobile product dependent package, is there any other way we can solve it?

**Comment by LePhenix47** [comment]
> ```
> const pdfjs = require("pdfjs-dist");
> pdfjs.GlobalWorkerOptions.workerSrc = require("pdfjs-dist/build/pdf.worker.entry.js");
> ```

Thank you
