### ISSUE TITLE
viewport.convertToPdfPoint return incorrect  coordinates especially with landscape pages

### ISSUE THREAD

**Issue by charuvasudev** [mozilla/pdf.js#12003]
Hi,

I am using PDF JS to display pdf files and add annotations/tags.  End user drags a canvas(tempcanvas) and places it on the pdf. I get the location of the canvas(tempcanvas) and convert it to pdf coordinates using the following function-
var x = PDFViewerApplication.pdfViewer.getPageView(PDFViewerApplication.page - 1).viewport.convertToPdfPoint(tempcanvas.style.left.replace("px", ""), tempcanvas.style.top.replace("px", ""));

My problem is that the location returned by the above is not always correct. This is more common in case of landscape pages and pages of non-standard sizes. Though it does not happen always. it seems that in some cases the corner (0,0) is on the bottom left of the page and in some it is on top left of the page. I have some sample files which show this behaviour. I am attaching a file (refer page no-3) here for your reference. Let me know if this can be fixed? or if there is a work around.
[Brochure.zip](https://github.com/mozilla/pdf.js/files/4780081/Brochure.zip)
Rgds
Charu

**Comment by jrkoenig** [comment]
It looks like the pages in question have a rotation set. So the PDF coordinates are rotated relative to what they appear to be on the screen.

In the PDF you linked, `PDFViewerApplication.pdfViewer.getPageView(0).viewport.convertToPdfPoint(0,0)` returns `[-0, 792]`. This makes sense: (0,0) is upper left corner in CSS coordinates, and [0,792] is also the upper left (792pt = 11in) because PDF coordinates start in the lower left.

The landscape pages have PDF rotation applied. (`getPageView(2).viewport.rotation == 90`) So now the PDF origin is in the upper left, with the x-axis down and the y-axis to the right. `getPageView(2).viewport.convertToPdfPoint(0,0)` gives us [0,0]. Note that the CSS coordinates haven't changed: (0,0) in CSS is still the upper left.

**Comment by Snuffleupagus** [comment]
Comment https://github.com/mozilla/pdf.js/issues/12003#issuecomment-659752714 seems spot on, since some of the pages have a non-zero /Rotate-entry (in the PDF document itself).
Hence checking the rotation of the `PageViewport`-instance, and for those where it's non-zero calling e.g. `viewport.clone({ rotation: 0, });` ought give you a new `PageViewport`-instance with a zero-rotation; see https://github.com/mozilla/pdf.js/blob/891f21fba6db64cd602c1a9a51826d7b9cd06af0/src/display/display_utils.js#L249-L269
That should thus provide one way of getting consistent coordinates for all pages, as far as I can tell.

Closing as answered; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
