### ISSUE TITLE
Corner rendered incorrectly in figure

### ISSUE THREAD

**Issue by 7Z0t99** [mozilla/pdf.js#12010]
Link to PDF file: http://mirrors.ctan.org/graphics/pgf/contrib/circuitikz/doc/circuitikzmanual.pdf (version 1.1.2)

Configuration:
- Web browser and its version: Firefox 77.0.1
- Operating system and its version: Windows 10 1909
- PDF.js version: 2.5.95 (included in Firefox)

Consider the bottom left corner in the figure at the bottom of page 148.

What is the expected behavior?
![correct](https://user-images.githubusercontent.com/16905338/84997925-731c7900-b14f-11ea-877c-7d7abd5e5c21.png)

What went wrong?
![wrong](https://user-images.githubusercontent.com/16905338/84998187-cd1d3e80-b14f-11ea-85d5-822d4fdfa44e.png)

**Comment by THausherr** [comment]
reduced file:
[PDFJS-12010-p153-reduced.pdf](https://github.com/mozilla/pdf.js/files/4845750/PDFJS-12010-p153-reduced.pdf)

This is somehow related to a rectangle having a zero width.

**Comment by calixteman** [comment]
It's because of:
https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L1189
The pdf docs:
https://www.adobe.com/content/dam/acom/en/devnet/pdf/PDF32000_2008.pdf#page=141
don't mention that neither width nor height for a rectangle has a minimal value.
The rendering in evince is correct and the code in poopler doesn't use a minimal width:
https://gitlab.freedesktop.org/poppler/poppler/-/blob/master/poppler/Gfx.cc#L1724
Unfortunately, I'm not able to get the pdf in https://github.com/mozilla/pdf.js/issues/4260#issue-27168204 so I can't check what's wrong exactly with it.
Anyway I think that removing these "default" values will fix the issue.
@timvandermeij, @brendandahl wdyt ?

**Comment by brendandahl** [comment]
@Snuffleupagus might also still have that PDF?
