### ISSUE TITLE
Scaling the PDF with the pdf.js node pdf2png example will cause the font width to be squished

### ISSUE THREAD

**Issue by bobsingor** [mozilla/pdf.js#12035]
Hi Pdf.js

I am running a node pdf to png converter. I'm running into the issue below. hope someone can help me out with this one.

Attach (recommended) or Link to PDF file here:
[example_028.pdf](https://github.com/mozilla/pdf.js/files/4842438/example_028.pdf)

Configuration:
- Web browser and its version: node.js
- Operating system and its version: Mac OSX 10.15.4
- PDF.js version: 2.4.456

https://jsfiddle.net/2vtLa94h/

What went wrong? (add screenshot)

Scale 1 (Font is right width)
![scale 1](https://user-images.githubusercontent.com/7645917/85950722-d5028d00-b95e-11ea-9215-c44eb3da11e2.png)

Scale 2 (font width squished)
![scale 2](https://user-images.githubusercontent.com/7645917/85950727-d92eaa80-b95e-11ea-9805-265e7de22088.png)

Scale 3 (font width get squished even more)
![scale 3](https://user-images.githubusercontent.com/7645917/85950730-db910480-b95e-11ea-80e4-f014c8c766f9.png)

**Comment by Snuffleupagus** [comment]
This unfortunately looks like an issue with the [`node-canvas` package](https://github.com/Automattic/node-canvas) that's used in the "pdf2png" example, rather than the PDF.js library itself, since otherwise you'd expect it to be broken in e.g. the default viewer as well.

You might want to try updating the `node-canvas` package to its latest version, and see if that helps. However it probably doesn't make sense to keep this issue open, since it unfortunately doesn't look like something we can fix *here*.
