### ISSUE TITLE
Checked checkboxes in acroform are printed in white

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12046]
Attach (recommended) or Link to PDF file here:
https://www.irs.gov/pub/irs-pdf/f1040.pdf

Configuration:
- Web browser and its version: firefox
- Operating system and its version: debian testing
- PDF.js version: master
- Is a browser extension: no

Steps to reproduce the problem:
1. Run acroforms example (https://github.com/mozilla/pdf.js/tree/master/examples/acroforms)
2. Check some checkboxes
3. Print the result in a file (sorry I've no printer)

What is the expected behavior? (add screenshot)
Having some checked boxes in the printed pdf

What went wrong? (add screenshot)
The crosses are printed in white so they're invisible

**Comment by Snuffleupagus** [comment]
> Run acroforms example (https://github.com/mozilla/pdf.js/tree/master/examples/acroforms)

First of all, I don't that example ever really "supported" printing, given all the hoops we have to jump through for printing to work in the default viewer; via `web/firefox_print_service.js` receptively `web/pdf_print_service.js`.
The only way to get printing to work, in that example, would thus have been to *essentially* re-implement printing similar to those files.

Secondly, that example has now been removed (see PR #13053), and effectively "replaced" by the regular [viewer-component](https://github.com/mozilla/pdf.js/tree/master/examples/components) examples, since it was old and didn't illustrate best practices.

All-in-all, it seems that we should just close this issue now.
