### ISSUE TITLE
Highlight same text with different colors in the pdf.

### ISSUE THREAD

**Issue by romy421kumari** [mozilla/pdf.js#12058]
Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  search 'ent' or 'try' in the pdf.,
2. choose the highlight option.

What is the expected behavior? (add screenshot)
Expected output : text should be highlighted with same color.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/44578093/86518229-a0567000-be4d-11ea-9d16-7ecaa8a7dd22.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Configuration:
>  * Web browser and its version:
>  * Operating system and its version:
>  * PDF.js version:
>  * Is a browser extension:

This part of the ISSUE_TEMPLATE is *required* when opening an issue.

> 2\. choose the highlight option.

There's no findbar option called "highlight", did you perhaps mean "highlight all" here?

> Expected output: text should be highlighted with same color.

If all matches used the same colour, when "highlight all" is enabled, it would be *impossible* to tell the currently active match from the rest of the matches. (Also, this behaviour is basically identical to searching in a regular web-page in e.g. Firefox).
Hence this is working as intended, and the issue is thus INVALID.
