### ISSUE TITLE
[PDF to SVG, Embed font] How to extract the embed font?

### ISSUE THREAD

**Issue by Hideman85** [mozilla/pdf.js#12054]
Hi community, I need to extract the embed font before writing the svg file and also to have the reel font name and not a generated one (`font-family="g_d0_f1"`).

I need for my usage to extract and convert the font via fontforge and it would be great to have the reel font family name (because most of the time I have already this font in the global document that use the generated svg and so don't need to process it a second time).

I'm using your [example code](https://github.com/mozilla/pdf.js/blob/master/examples/node/pdf2svg.js). In this sample the font is extracted and also embed into the svg thanks to these lines:
https://github.com/mozilla/pdf.js/blob/fe3df495cc0c2b1232ae367d30fba0f135889110/examples/node/pdf2svg.js#L107-L108

At the end the font ins embed in the svg in a `<svg:style type="text/css">` tag can I capture the font instead of generating this tag? so I will be able to convert it and integrate it in my global document.

**Comment by Snuffleupagus** [comment]
> also to have the reel font name and not a generated one (`font-family="g_d0_f1"`).

There *needs* to be a custom font identifier to prevent issues in general case, so that won't change and/or become optional.

However, the original font name should already be present on the *exported* font objects (using the `.name` property) and those can be accessed via the `commonObjs` property on the `SVGGraphics` instance; see https://github.com/mozilla/pdf.js/blob/fe3df495cc0c2b1232ae367d30fba0f135889110/src/display/svg.js#L442-L450 where `commonObjs` is an instance of https://github.com/mozilla/pdf.js/blob/fe3df495cc0c2b1232ae367d30fba0f135889110/src/display/api.js#L2489-L2495

---

Finally, please keep in mind that the SVG-backend isn't fully supported as explained in the Wiki: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends
