### ISSUE TITLE
Loading Pdf Document so slow

### ISSUE THREAD

**Issue by vituthanh** [mozilla/pdf.js#12061]
I have a pdf document with 6310 pages. My project build in Electron.NET, i used pdfjs for render pdf document. When i load pdf document, it's take me near by 120 seconds to finish. I saw loading bar stopping when it loaded 25%, after 60 seconds, it continue load remain. I tried to load this document by open file in viewer.html, it's me 10 seconds to finish. Thanks for reading.

**Comment by Snuffleupagus** [comment]
When opening an issue, you must provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md for the issue to be actionable/valid.

> I tried to load this document by open file in viewer.html, it's me 10 seconds to finish.

This would suggest that the problem is somewhere in your implementation, hence see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
