### ISSUE TITLE
"documentloaded" not working

### ISSUE THREAD

**Issue by gebteus** [mozilla/pdf.js#12077]
```
document.addEventListener("documentloaded", function() {
    alert("TEST");
})
```
This code not working. The event not working.
I'm not a JS developer. But, I researched this problem. 

In file "viewer.js"
```
this.eventBus.dispatch("documentloaded", {
    source: this
});
```
I replaced on
```
const event = document.createEvent("CustomEvent");
event.initCustomEvent("documentloaded", true, true, {});
document.dispatchEvent(event);
```
and BINGO! This works!

My UA
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36

**Comment by Snuffleupagus** [comment]
> This code not working. The event not working.

It's not supposed to work either, please see PR #11655 for the *correct* way to access events in the default viewer and see also https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage

Given that this works as intended, since we don't want to dispatch events globally, this issue is thus INVALID.

**Comment by gebteus** [comment]
Thanks!
