### ISSUE TITLE
[SUGGESTION] fix open URL to new tab from PDF 

### ISSUE THREAD

**Issue by DCVolo** [mozilla/pdf.js#12071]
https://mozilla.github.io/pdf.js/getting_started/#download => pdf.js

While it has been an hassle for years from Adobe's part, why not fixing this here ?
It may be partialy stupid for some but for those who already have existing huge PDF files, it saves a lot of time.

case LinkTarget.TOP:
      targetStr = "_blank";// instead of_top
      break;

**Comment by Snuffleupagus** [comment]
It's really not at all clear *exactly* what you're actually asking/suggesting here, since `_blank` is already supported as seen in https://github.com/mozilla/pdf.js/blob/cf8daaf78bf9a2cd0487f5a17116835419db4ec5/src/display/display_utils.js#L434-L436 and furthermore having a `linkTarget` do something else than its name suggests is definitely more confusing than helpful.
