### ISSUE TITLE
Fastest way of PDF Rendering

### ISSUE THREAD

**Issue by punith7676** [mozilla/pdf.js#12080]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 83.0.4103.116 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Enterprise 
- PDF.js version: 1.8.188
- Is a browser extension: no

What is the expected behavior? (add screenshot)
When we load pdf file is having more than 500mb size(having more annotation, link etc..) taking more time to load and even some time its says "Unexpected server response (500) while retrieving PDF".
Is it any other way to load large document quickly and responsive. Please let us know as early as possible. definitely we appreciate your quick response. Thanks
![PDF load Error](https://user-images.githubusercontent.com/68045767/87003969-430a4800-c1da-11ea-9024-9330096394d9.PNG)

What went wrong? (add screenshot)
PDF.JS is too much time to load more than 500mb document.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is required.

> PDF.js version: 1.8.188

That version is over *three* years old, and is thus no longer supported. You'll need to update to the *latest* release, see https://github.com/mozilla/pdf.js/releases

> When we load pdf file is having more than 500mb size(having more annotation, link etc..)

This is *impossible* to reproduce without the actual PDF document...

> taking more time to load and even some time its says "Unexpected server response (500) while retrieving PDF".

... and this suggests a *server* and/or connection issue which is likewise impossible to replicate without access to the server.

> Is it any other way to load large document quickly and responsive.

Unfortunately this issue contains nowhere near enough information to be actionable, see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Please keep in mind that this is an *open-source* project, which you're able to use for free, with most people contributing in their spare time.
Furthermore, this is first and foremost a *bug tracker* rather than a support forum, and issues are thus required to contain *all* of the necessary information to be easily actionable/reproducible in order for anyone to help you.

**Comment by wojtekmaj** [comment]
> This is impossible to reproduce without the actual PDF document...

...and without the actual server, because PDF.js AFAIK is capable of requesting parts of documents from the server if the server supports it, right?

**Comment by timvandermeij** [comment]
Indeed, that's range requests. "Unexpected server response (500) while retrieving PDF" is the server not serving the PDF file properly. Without access to the file and the server, it's impossible to provide any assistance unfortunately.
