### ISSUE TITLE
Ability to change base_viewer.js DEFAULT_CACHE_SIZE

### ISSUE THREAD

**Issue by burtonator** [mozilla/pdf.js#12104]
The base_viewer.js file has a DEFAULT_CACHE_SIZE of ten... 

This is sort of limiting and I'd like to change it but it's hard coded. 

Modern desktop machines with more memory could keep more pages cached but keeping this limited prevents that.

**Comment by Snuffleupagus** [comment]
> The base_viewer.js file has a DEFAULT_CACHE_SIZE of ten...

There's a (generally) good reason for keeping it limited, please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages

**Comment by burtonator** [comment]
@Snuffleupagus agreed on keeping it limited but 10 seems to low if your machine has like 16GB of RAM... :)

**Comment by Snuffleupagus** [comment]
> but 10 seems to low if your machine has like 16GB of RAM

This isn't *only* about memory usage though, since that *completely* ignores another and equally important detail: The effects on general CPU-usage, and thus the parsing/rendering times of the PDF document.

The `PDFPageViewBuffer` doesn't just control how many pages are kept alive in the viewer, it also *indirectly* controls how many pages can be parsed concurrently at the worker-thread. (Since pages evicted from the cache will also have their worker-thread parsing aborted, in addition to just having their rendering stopped.)

Consider the case where you scroll (quickly) through a long document, e.g. with over a thousand pages, were worker-thread parsing *and* main-thread rendering is thus triggered for every page:
While only *one* page at a time will be rendering (on the main-thread), note however that the worker-thread will run parsing for *all* active pages. Currently this concurrent worker-thread parsing is thus *indirectly* limited to only `10` pages, and it's hopefully easy to see what happens to general PDF.js parsing/rendering performance if that value is significantly increased. (If you double it, to `20`, you could thus easily double the time it takes to render the pages.)

The above is a slight simplification, but tries to illustrate why the number of cached pages (in the viewer) is *far from* a memory issue alone. Given that users, based on experience with e.g. the now removed `disableWorker` option, often set options without understanding the ramifications of doing so, it's hopefully obvious why making `DEFAULT_CACHE_SIZE` easily configurable is probably not a good idea!

**Comment by timvandermeij** [comment]
I agree with the above. If you need this to be configurable it can be done in a custom deployment, but we won't recommend it for the reasons outlined above.
