### ISSUE TITLE
Missing dots in extracted text

### ISSUE THREAD

**Issue by TimotheAlbouy** [mozilla/pdf.js#12100]
Link to PDF file: https://www.welivesecurity.com/wp-content/uploads/2019/07/ESET_Okrum_and_Ketrican.pdf

Configuration:
- Web browser and its version: Chrome 83.0.4103.116
- Operating system and its version: macOS Catalina 10.15.5
- PDF.js version: 2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. Load a PDF using the `PDFViewer` component
2. Extract the text of the PDF using `viewer.getPageView(i).textLayer.textContentItemsStr` for each page

What is the expected behavior?
![](https://i.imgur.com/pXFYFTK.png)

What went wrong?
![](https://i.imgur.com/Vs7F13x.png)

Link to a viewer: N/A

![](https://i.imgur.com/4YbtDq3.png)

As we can see the dots are properly displayed in the `<canvas>` but they are not present in the text layer, which prevents extracting them using the method I described. It is very important for me to retrieve those dots because I'm doing natural-language processing on the PDF text to detect the sentences, but if there are no dots to close the sentences they are considered to be one big sentence instead of several ones.

Here is a question on Stack Overflow that features a code snippet for you to see it firsthand: https://stackoverflow.com/questions/62950684/pdf-js-missing-dots-in-extracted-text

**Comment by Snuffleupagus** [comment]
> Extract the text of the PDF using `viewer.getPageView(i).textLayer.textContentItemsStr` for each page

Please don't use that, since that's *internal* functionality which is *not guaranteed* to work (it could theoretically stop working tomorrow) and it's also not guaranteed to even be defined in general. E.g. not all pages even have a `textLayer`, the `textLayer` property is only defined *after* a page has finished rendering, and finally note that the actual `textLayer`-contents is built *asynchronously* as well.
The correct approach here would be use this API method:
https://github.com/mozilla/pdf.js/blob/a604973cc74fbe66e2d23fd3d4ccd7d0d7b596ad/src/display/api.js#L1199-L1204
as is e.g. done when searching in the default viewer:
https://github.com/mozilla/pdf.js/blob/a604973cc74fbe66e2d23fd3d4ccd7d0d7b596ad/web/pdf_find_controller.js#L464-L472

---

As for the text-selection/text-extraction issue at hand: This is a bug in the /ToUnicode data of the font that's used for this text, since it explicitly maps `.` to the `space`-character.

**Comment by Snuffleupagus** [comment]
Simply ignoring the entire /ToUnicode data is (most likely) bound to lead to much worse text-selection behaviour *in general*, even if you manage to limit it to "bad" data (which you'd need to detect without false positives), hence I don't think that it's a good idea. Also, it's not always possible to tell *with code* if a particular /ToUnicode data is "bad", without a human doing the actual checking.

**Comment by TimotheAlbouy** [comment]
Do you know how the detection of bad /ToUnicode data was made for pdf2htmlEX then?

**Comment by Snuffleupagus** [comment]
> Do you know how the detection of bad /ToUnicode data was made for pdf2htmlEX then?

No, since that's a completely different project which we don't know anything about here :-)

*Generally speaking:* We're currently attempting to parse as much as possible of the /ToUnicode data, which is most likely improving text-selection some documents. Hence it's unfortunately quite unlikely that we'd accept a patch which limits this, since that'd risk *regressing* text-selection in other documents (and we may not have sufficient test-coverage to catch that).

**Comment by TimotheAlbouy** [comment]
Ok thank you for your help, I guess I cannot use PDF.js then because extracting the dots is critical for my project.

But I don't really understand why you wouldn't accept outright a patch that fixes this issue for PDF.js the same way that pdf2htmlEX handles it. You admitted that you don't know how it works, so maybe it deals with bad /ToUnicode problems in a really clever way. I get that maybe this solution improves text-selection only for the PDF I gave but for other PDFs it performs worse, but having used both technologies I must say that pdf2htmlEX has always done a proper job for me.

But if you want to be sure of this, you could create a dataset of several PDFs associated with their true text content. You can test this dataset using the 2 methods: the current PDF.js method and the pdf2htmlEX method. The method that gives the extracted text the closest to the true text content is the best one. This test method could be useful to check every time there is a modification to the text parsing algorithm of PDF.js, to see if it improved or not the performance.

**Comment by Snuffleupagus** [comment]
> But I don't really understand why you wouldn't accept outright a patch that fixes this issue for PDF.js the same way that pdf2htmlEX handles it.

We don't (generally) accept any patches which regress existing test-cases. If you're able to fix *this* issue, without regressing *anything* else, there's nothing stopping you from submitting a PR (although it's impossible to guarantee beforehand that it'll be accepted); please see https://github.com/mozilla/pdf.js/wiki/Contributing#4-run-lint-and-testing

> you could create a dataset of several PDFs associated with their true text content.

We already have reference-tests of the `text` kind, which will thus catch text-selection regressions; my point was simply that our test-coverage may be *limited* and that dealing with corrupt PDF documents is tricky in general.

**Comment by TimotheAlbouy** [comment]
Sorry to drag this out, but I checked the same PDF with PDFium, the PDF renderer of Chrome, and all the characters (including the dots) were parsed perfectly. The problem is, unlike PDF.js, PDFium does not expose an API for developers. What I'm trying to say is that there is a solution to the problem of bad /ToUnicode maps, and it is not OCR. I'm just a bit disappointed that Firefox is a bit behind Chrome for this particular issue.

**Comment by THausherr** [comment]
The reason that it works with other software is that it uses "/ActualText" to repair the mess done by a (probably) incomplete /ToUnicode stream.
```
/Span << /Lang (en-US) /MCID 106 >> BDC
  BT
    0.259 0.302 0.337 rg
    /T1_0 1 Tf
    9 0 0 9 152.5669 726.2613 Tm
    (, also known as APT15, is a threat group believed to be operating out of China) Tj
    /Span << /ActualText (\376\377\000.) >> BDC
      (.) Tj
    EMC
    [ ( Its) 20 ( ) ] TJ
  ET
EMC
```

**Comment by TimotheAlbouy** [comment]
@THausherr Yes thank you, I had a similar answer when I asked how Acrobat Reader does to correctly detect correctly all the characters. And will this feature be implemented in PDF.js in a foreseeable future?

**Comment by timvandermeij** [comment]
Closing in favor of #12237 which has more details.
