### ISSUE TITLE
Access CCS_UNITS

### ISSUE THREAD

**Issue by clempe** [mozilla/pdf.js#12129]
I'm updating the our PDF Viewer form Version 1.8.188 to the newest version.
In the old version it was possible to access the `CSS_UNITS` value in the viewer.js (pdf-viewer.js) with the following code:
`pdfjsWebLibs.pdfjsWebUIUtils.CSS_UNITS`
 
How can I access the value in the new version?

**Comment by Snuffleupagus** [comment]
> How can I access the value in the new version?

You can't, and please note that it was *never intentionally* exported previously.

The fact that it apparently worked previously was probably a result of the older packaging, which has been changed since then, and please note that you generally don't want to expose *everything* to an outside consumer since that makes future code changes much more difficult.

---

If you want us to *consider* exporting the `CSS_UNITS` constant [here](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js), please explain in some detail what your use-case actually is (links to code may also be helpful here).
Please note that there's no guarantee that `CSS_UNITS` will be exported, but without any context it's impossible to decide either way.

**Comment by clempe** [comment]
Our viewer can place custom annotations. The `CSS_UNITS` is used to calculate the values of the CSS `transform: matrix()` for the drag function of the annotations. 

Old:
```javascript
var val = pdfjsWebLibs.pdfjsWebUIUtils.CSS_UNITS * PDFViewerApplication.pdfViewer._currentScale;
var transform = [val,0,0,val,0,0];
```

New:
```javascript
var val = Math.abs(PDFViewerApplication.pdfViewer._pages[markData.pageIndex].viewport.transform[0]);
var transform = [val,0,0,val,0,0];
```
