### ISSUE TITLE
landscape 2.1.266 resolve in 2.4.456

### ISSUE THREAD

**Issue by Nicolaslup** [mozilla/pdf.js#12146]
Hi,
I use in a personnal project the version 2.1.266 to pdf.js. I have a problem to display sometimes with pdf. When i use the version 2.2.456 this problem is resolved.
My problem, i can't upgrade pdf.js in my project because i cloned repo and amended some files for adapted library to my project.

Do you know what files i must changes in my version 2.1.266 for have the result of version 2.2.456?
 I search for 4 day the difference between the 2 version but i don't arrive to find.

I can't send you the pdf document cause confidentiality but i took an image of my deskop. To the left the pdf loaded in pdf.js 2.1.266 and to the right the same pdf loaded in pdf.js 2.2.456

![v_2_1_266_andv_2_2_456](https://user-images.githubusercontent.com/26337037/89036079-56718480-d33c-11ea-91d9-ba7718695db9.png)

Thanks is very important.

**Comment by Snuffleupagus** [comment]
> I use in a personnal project the version 2.1.266 to pdf.js. I have a problem to display sometimes with pdf. When i use the version 2.2.456 this problem is resolved.

That rather clearly suggests that you'll need to update to the latest version, and the one you're using is unsupported anyway, there really is no other solution here!

> My problem, i can't upgrade pdf.js in my project because i cloned repo and amended some files for adapted library to my project.

That problem will only get *worse* over time, as new PDF.js releases become available, hence the only recommendation would be to re-factor how you customize the PDF.js library such that future updates are easier. 

> Do you know what files i must changes in my version 2.1.266 for have the result of version 2.2.456?

Again, you should just update. However, using `git bisect` can help you with tracking down the exact commit where your issue was fixed.

> I can't send you the pdf document cause confidentiality but i took an image of my deskop.

It's simply *impossible* to do any meaningful debugging with nothing more than a screen-shot!

---

All-in-all, this issue unfortunately contains no actionable information.
