### ISSUE TITLE
Detect Browser support (ES5/Normal) 

### ISSUE THREAD

**Issue by clempe** [mozilla/pdf.js#12140]
I want to automatically detect if the browser can handle the "standard" `viewer.js`, `pdf.js` and `pdf.worker.js` files or have to use the ES5 compatible ones. 

Is there a list of features/functions I can check to either load the ES5 or normal JS files? 

---
Update:
This is my current solution looks like this:
```javascript
function es5Check() {
    "use strict";
    try { eval("var foo = (x)=>x+1"); }
    catch (e) {return true; }

    try { eval("(a = 0) => a"); }
    catch (e) {return true; }
    
    if (window.Promise == null || window.Promise.allSettled == null) {  return true; }
    
    if (window.ReadableStream == null) { return true;}

    try{eval("new ReadableStream({start: controller => {},pull: controller => {}, cancel: reason => {}})");}
    catch (e) {return true; }

    return false;
}

var isES5 = es5Check();

['build/pdf.js', 'viewer.js'].forEach(function (js) {
    var script = isES5 ? js.replace('.js', '.es5.js') : js;
    var scriptTag = document.createElement('script');
    scriptTag.src = script;
    scriptTag.type = 'text/javascript';
    document.getElementsByTagName('head')[0].appendChild(scriptTag);
});

document.addEventListener('webviewerloaded', function () {
        var workerPath = 'build/pdf.worker.js';
        if(isES5) {
            workerPath = workerPath.replace('.js', '.es5.js')
        }
        PDFViewerApplicationOptions.set('workerSrc', workerPath);
    }
);
```

**Comment by Yegorich555** [comment]
I guess this is out of the scope of this repo. Why? Because browser-support is a task for bundlers like webpack or babel. Today checking "isES5" is bad practice. **Webpack** with **babel-loader** and **browserlist** automatically prepare your scripts according to requirements (pointed browser) and it's the best because ES6 or ES2015 is outdated and today ESNext (ES2020) exists and browsers implement these features step-by-step with each new version. So better if your scripts will be prepared according to browsers that your support.

**Comment by timvandermeij** [comment]
Moreover, the library could raise errors if the non-ES5 version is used in an ES5-only environment; see for example this:

https://github.com/mozilla/pdf.js/blob/bcbbd03f7beb60c0ac8750e9f3b851d5fd8b2158/src/core/worker.js#L145-L150

The non-ES5 version can be used if only modern browsers are targeted (latest Firefox, Chrome and Edge), otherwise you most likely need the ES5 version.
