### ISSUE TITLE
download error

### ISSUE THREAD

**Issue by jzyzxx** [mozilla/pdf.js#12150]
there are some problems when people click the download button in  some deivices width lower syetem version,such as android 5/6/7/8,why do'nt use tag a?Tag a performs better

**Comment by timvandermeij** [comment]
Google only supports Android 8 and higher, but even Android 8 is already three years old. Modern browsers support our code and those are the only browser we can support unfortunately. The download button is made in such a way specifically to work on modern platforms since `a` tags also don't work everywhere.
