### ISSUE TITLE
Unable to use modules from build generic

### ISSUE THREAD

**Issue by bredmann** [mozilla/pdf.js#12194]
Hello, I recently was trying to use some of the modules that are compiled in the build folder from the cmd `gulp generic`, but was unable to successfully use them. The particular situation I ran into was with the following implementation: 

```
const pdfjs = require('../build/generic/build/pdf');

var loadingTask = pdfjs.getDocument('AlphaForm.pdf');
loadingTask.promise.then(function(pdf) {
  console.log('success');
});
```

I end up with the following error from this. 

```
(node:21472) UnhandledPromiseRejectionWarning: Error
    at BaseExceptionClosure (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:1302:29)
    at Object.<anonymous> (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:1305:2)
    at __w_pdfjs_require__ (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:52:30)
    at Object.<anonymous> (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:388:13)
    at __w_pdfjs_require__ (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:52:30)
    at Object.<anonymous> (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:322:22)
    at __w_pdfjs_require__ (C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:52:30)
    at C:\Users\\\Documents\pdf.js\build\generic\build\pdf.js:116:18
    at C:\Users\\Documents\pdf.js\build\generic\build\pdf.js:119:10
```

Is there a reason that I am unable to use the modules from the generic build directory?

**Comment by Snuffleupagus** [comment]
When using PDF.js in Node.js environments you'll need to build it with `gulp generic-es5` instead, since otherwise not all necessary compatibility code and polyfills will be present.

Unfortunately that's the only possible suggestion here, since this issue is currently missing too many necessary details for anyone else to be able to reproduce the problem you're seeing:
 - When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
 - Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
   > If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by bredmann** [comment]
@Snuffleupagus, thanks so much! That solved my problem.
