### ISSUE TITLE
How to listen popstate event or hitory.back?

### ISSUE THREAD

**Issue by wideweide** [mozilla/pdf.js#12208]
Attach (recommended) or Link to PDF file here:
https://mozilla.github.io/pdf.js/es5/web/viewer.html

Steps to reproduce the problem:
1.  open any pdf
2.  scroll to the bottom
3. f12 open develop tool
4. press toggle device toolbar 
5 press alt+<-  or mobile's back botton

What is the expected behavior? (add screenshot)
history back to pre url

What went wrong? (add screenshot)
history back to  the pre position of pdf 

disableHistory may be usable,but I want keep history,and history back to the pre url when press alt+<- or mobile's back button

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/es5/web/viewer.html

**Comment by Snuffleupagus** [comment]
> history back to the pre position of pdf

That's the intended behaviour of the default viewer, and it won't be changed.

> disableHistory may be usable,

That's the only simple solution to your problem.

> but I want keep history,and history back to the pre url when press alt+<- or mobile's back button

That's definitely not something that the default viewer will support, since it would be *really* confusing if the back button just "jumped" several positions in the history rather than (as intended) moved to the previous entry.

---

You'll have to implement this yourself, by modifying `web/pdf_history.js`, in your *custom* PDF.js viewer: please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by wideweide** [comment]
> > disableHistory may be usable,
> 
> That's the only simple solution to your problem.
> 
@Snuffleupagus 
I found a strange thing: disaleHistory is usable in a page ,but when set it in a iframe it seems wrong -- the develop tool'  network will show the url like this:
http://localhost:8213/statics/pdfjs/web/viewer.html?disableHistory=true&file=80.pdf#page=13&id=0
http://localhost:8213/statics/pdfjs/web/viewer.html?disableHistory=true&file=80.pdf#page=12&id=0

**Comment by wideweide** [comment]
@Snuffleupagus 
It seems I need to clearHistorySate, some code like this?
self.pdfHistory.clearHistoryState();
