### ISSUE TITLE
Win10 - update styling for dropdown menu in PDF forms

### ISSUE THREAD

**Issue by cfogelSV** [mozilla/pdf.js#12216]
**Affected versions**
* 81.0a1 (2020-08-16)

**Affected platforms**
* Windows 10

**Steps to reproduce**
 pdfjs.renderInteractiveForms - enabled

1. Launch Firefox;
2. Access a PDF [form](http://foersom.com/net/HowTo/data/OoPdfFormExample.pdf) with dropdown menus;

**Expected result**
* consistent icons across OSs;

**Actual result**
* dropdown buttons look ugly;

**Additional notes**
* S4 as suggested severity;
* attached screenshot with the issue;
<img width="447" alt="Screenshot 2020-08-17 at 10 12 16" src="https://user-images.githubusercontent.com/49230899/90368054-28957b00-e072-11ea-93f6-74f4a314d480.png">

**Comment by timvandermeij** [comment]
I originally tried to style all interactive form elements according to how Adobe Reader/Acrobat rendered them since users are likely to be more familiar with that, but I'm now thinking that it might be better to just let the browser do all rendering (according to OS styles) since that is more consistent with other browser form elements and avoids us having to do quite a bit of styling that can even differ when overridden in the PDF file itself. If we print/save, the appearance stream of the PDF will be used anyway, so for editing purposes users might indeed expect rendering like any other normal form.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.1.20 [7e5008f0f] in Firefox Nightly 108 on Windows 7; probably fixed by the browser no longer using the native OS form-appearance:

![arrow](https://user-images.githubusercontent.com/2692120/200850689-58daa2fb-a2b1-4ce7-a797-2337ea6ea119.png)
