### ISSUE TITLE
Checkmarks can be edited while in Presentation mode

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12232]
**Affected versions**
* 81.0a1 (2020-08-17)

**Affected platforms**
* Windows 10
* macOS 10.15
* Ubuntu 18.04 64bit

**Steps to reproduce**
pdfjs.renderInteractiveForms - true

1. Launch Firefox
2. Access a PDF form with fillable content (eg: https://www.irs.gov/pub/irs-pdf/f1040.pdf)
3. Enter presentation mode
4. Scroll to page 2 and try and fill the form

**Expected result**
* Form can't be edited since we are in presentation mode.

**Actual result**
* Checkmarks can still be edited while in presentation mode.

**Additional notes**
* S3 as suggested severity, not sure how many people use presentation mode
* Not sure if this is intended behavior or not though

**Comment by timvandermeij** [comment]
This most likely applies to _all_ form fields, not only checkboxes.

**Comment by Snuffleupagus** [comment]
This is probably more complicated than it first looks, since a CSS-only solution won't prevent *all* editing in PresentationMode.
For example: While you can use `pointer-events: none;` to prevent clicks, that won't help if the user uses <kbd>Tab</kbd> to navigate.

Basically, I *think* that what we'll need to do is *disable* `renderInteractiveForms` while PresentationMode is active. While making this change would be easy, it'd cause any data that the user has already entered on the page to not be displayed while PresentationMode is active, this might be unexpected and/or outright bad UX!?
Obviously we *could* fix that as well, by adopting a similar approach as used when e.g. printing, however it might become a bit messy given how the code is currently structured.
