### ISSUE TITLE
Text Layer rendered incorrect Chinese Characters 

### ISSUE THREAD

**Issue by harmansingha** [mozilla/pdf.js#12245]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 84.0.4147.125
- Operating system and its version: Windows 10
- PDF.js version: **Latest (Reproducing in all versions)**
- Is a browser extension: NO

Steps to reproduce the problem:
1. Uploading Chinese Document
2. Check Text Layer in the DOM

What is the expected behavior?
**Should show Chinese characters in the text layer. I have attached a document referring to in the screenshot for your reference. Wanted to know what is the probable fix in the library to have Chinese characters rendered correctly**

What went wrong?
![image](https://user-images.githubusercontent.com/50094184/90642153-aa8ecb00-e24f-11ea-98a2-4022606d9da8.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[chinese.pdf](https://github.com/mozilla/pdf.js/files/5096821/chinese.pdf)

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, rather than in the PDF.js library, since the fonts in question don't include any `/ToUnicode` data and text-selection/copying thus cannot work. Please note that this is broken in other PDF viewer too, e.g. Adobe Reader and PDFium/Google Chrome.

Basically, without the PDF document *itself* containing the necessary data there's nothing that can be done here; hence this issue is unfortunately INVALID.
