### ISSUE TITLE
Expose renderer (=canvas|svg) in Chrome extension's options UI

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#12279]
A user requested the ability to enable the svg backend in the Chrome extension, despite being aware of [its limitations](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends).

We should add a description to https://github.com/mozilla/pdf.js/blob/34cec29288212a6ca5bb9d703d6c5102c47e635d/extensions/chromium/preferences_schema.json#L142-L149
and change the `renderEnumPref` logic to support string-based enums at https://github.com/mozilla/pdf.js/blob/34cec29288212a6ca5bb9d703d6c5102c47e635d/extensions/chromium/options/options.js#L166-L181

**Comment by Snuffleupagus** [comment]
> A user requested the ability to enable the svg backend in the Chrome extension, despite being aware of [its limitations](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends).

That *particular* user may have read the FAQ; but in general users unfortunately don't seem to actually bother reading the FAQ.[1]

Given just how much that the SVG-backend doesn't support, and also how much slower and more memory intensive it is[2]; I thus think that it would be a mistake to expose this option in the UI.
Most likely the effects of doing so would be worse UX for those who enable it, and more bug reports about the Chrome extension having "broken" rendering.

Finally, note that the SVG-backend is *only* bundled in the `GENERIC` since it's not officially supported:
https://github.com/mozilla/pdf.js/blob/34cec29288212a6ca5bb9d703d6c5102c47e635d/src/display/svg.js#L37

---
[1] This observation is based on the frequency with which people open issues asking about things already covered in the FAQ.

[2] The sheer number of DOM-elements, in some documents, can be enough to slow the browser to a crawl.

**Comment by Rob--W** [comment]
Thanks for pointing out that it's not bundled by default. That does mean that the option in `preferences_schema.json` isn't really useful.

Nevertheless, since the SVG feature is barely working at the moment, and offering the ability to toggle it would increase the size of the extension package, I'm deciding to not add the option for now.
