### ISSUE TITLE
Change reftests to render forms by default

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#12288]
Now that forms are enabled by default, we should switch reftests to match the default behavior.

**Comment by Snuffleupagus** [comment]
> Now that forms are enabled by default, we should switch reftests to match the default behavior.

Note that this is only the default value for *the viewer*, however the API itself doesn't does render forms by default since that requires a separate annotationLayer (thus functionality not found in the `src/display/api.js` file).

Hence it's not really clear, at least to me, that we want to change this for all reference tests since most of them only need/want to check the actual page rendering and not annotations/forms specifically.
