### ISSUE TITLE
A question about web worker

### ISSUE THREAD

**Issue by cuijing1031** [mozilla/pdf.js#12317]
I am learning the PDF.js, I am curious why fetch is in the main thread, and then synchronize the request result to worker? 
What are the benefits of doing this？

**Comment by brendandahl** [comment]
I thought there was  comment in the the PR that it was done to support a browser where fetch wasn't supported in the worker. Though I don't know what browsers/versions didn't support it. @Snuffleupagus do you remember?

**Comment by Snuffleupagus** [comment]
There's a couple of reasons for loading data on the main-thread, and then transferring it to the worker-thread, as far as I know:
 - The fact that some browsers had/have issues with using the Fetch API and/or `XMLHttpRequest` in Workers. Unfortunately I don't remember which browsers/versions were affected, since it's been too many years.
 - Given that *some* custom PDF.js deployments are loading the `pdf.worker.js` file from a CDN, to avoid having to serve the file locally, that could potentially lead to additional CORS issues that loading the PDF document on the main-thread may help to (somewhat) alleviate and/or simplify.
 - Finally, and quite important for the overall consistency of the code-base, is that this way *all* data loading in the PDF.js library happens *only* on the main-thread. Note that `getDocument` accepts a fair number of ways of loading PDF data:
   - As a `TypedArray`.[1] 
   - Getting the PDF data from a URL, by using the Fetch API (in browsers which support it).
   - Getting the PDF data from a URL, by using `XMLHttpRequest` (as a fallback in browsers when the Fetch API can't be used).
   - Getting the PDF data from a path, by using the File system API in Node.js environments.
   - Getting the PDF data via a *custom* fetching/delivery mechanism, by using the `PDFDataRangeTransport`/`PDFDataTransportStream` functionality (which is what the Firefox built-in PDF Viewer uses).

Hence keeping *all* data-loading on the main-thread makes overall sense, as far as I'm concerned, and hopefully this should answer the question and allow this issue to be closed!

---
[1] And also as a Base64-encoded string, although no one ought to this format since it's very memory-inefficient and some browsers may truncate long Base64 strings (which obviously cause errors).
