### ISSUE TITLE
no embedded font is not displayed

### ISSUE THREAD

**Issue by AlexTorg** [mozilla/pdf.js#12318]
The T-FlexTypeA font is not displayed correctly, is it possible to embed it into the document using this library?
Attach (recommended) or Link to PDF file here:
[my_fileA.PDF](https://github.com/mozilla/pdf.js/files/5162440/my_fileA.PDF)

Configuration:
- Web browser and its version: firefox 80.0.1 
- Operating system and its version: Windows 10 
- PDF.js version: 2.5.207
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![rax](https://user-images.githubusercontent.com/70644390/91986867-ef2d6280-ed35-11ea-9e11-eafbd5e0813c.jpg)

What went wrong? (add screenshot)
![dva](https://user-images.githubusercontent.com/70644390/91987060-37e51b80-ed36-11ea-811a-6083ac0e060a.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> is it possible to embed it into the document using this library?

No, the PDF.js library is a PDF *viewer* and not a generator; as such this issue is unfortunately not actionable/valid.

Also, I cannot render the attached PDF document in *any* of the PDF viewers I've tried (which includes Adobe Reader, PDFium in Google Chrome, and of course the PDF.js library) since I don't have the required fonts available on my computer.
Unfortunately your PDF document violates the specification, since all (non-standard) fonts *must* be embedded in the document for it to work correctly on all platforms and in all PDF viewers.

**Comment by AlexTorg** [comment]
Thanks to Snuffleupagus for the detailed advice, I will look at other options for the output of my_pdf on the page
