### ISSUE TITLE
Saving specific PDF that contains input data will not be displayed in Adobe Reader in other 3rd party apps

### ISSUE THREAD

**Issue by bogdanmaris** [mozilla/pdf.js#12319]
**Affected versions**
* Firefox 81.0b5
* Latest Nightly 82.0a1

**Affected platforms**
* Ubuntu 18.04 64bit
* Windows 10 64
* macOS 10.15

**Steps to reproduce**
1. Open the following pdf https://www.irs.gov/pub/irs-pdf/f1040.pdf
2. Fill some data
3. Click the download button to save the file locally
4. Open the saved PDF in: 
Windows: Adobe Reader/Foxit
macOS: Adobe Reader
Ubuntu: Adobe Reader

**Expected result**
* Data saved in Firefox is displayed in Adobe Reader after saving locally.

**Actual result**
* Data saved in step 2 is not displayed once the PDF is opened in Adobe Reader.

**Regression range**
* Not a regression since this is reproducible since this feature was first enabled in Nightly.

**Additional Notes**
* This is not reproducible if the PDF is opened in another browser (Chrome, Safari, IE, Firefox, SumatraPDF).
* Same thing if saving the PDF inside chrome and opening in Adobe.

**Suggested severity**
* I my opinion this should have the S2 severity since data loss is involved.

**Comment by calixteman** [comment]
This file contains XFA and Acroform and Acrobat (probably Foxit too) uses data from XFA so since we don't update them then nothing is displayed.
After investigations, getting "datasets" stream from XFA array, updating it (using the T value from Acroform to get field id) with the value and appending the new stream at end fixes the issue.
I'll do a patch in the next days.

**Comment by timvandermeij** [comment]
Fixed by the PR above.
