### ISSUE TITLE
Highlight disappears when page is re-rendered after being out of view

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#12337]
Steps to reproduce:

1. Go to https://mozilla.github.io/pdf.js/web/viewer.html.
2. Download https://drive.google.com/uc?export=download&id=0B6YhVF9p-y2AU0RlYjRKakFQRjQ and open it with the viewer.
3. Notice that the highlight (without appearance stream) is rendered correctly on the first page.
4. Scroll to the last page.
5. Scroll to the first page.
6. Notice that the highlight is gone.

I don't directly have an idea how this can happen. As far as I know, the complete page is re-rendered after being out of view, so we _should_ also re-render the annotations, but apparently we don't. This is not intermittent and reproduces 100% of the time.

/cc @calixteman Perhaps you have any ideas why the second time the appearance stream is not generated/rendered?

**Comment by timvandermeij** [comment]
It looks like we parse the annotations only once and store them in `this._parsedAnnotations`, but even then the `this.appearance` on the annotation should be set. We loop over the parsed annotations and include their operator lists here:

https://github.com/mozilla/pdf.js/blob/60ffac04808da1e427b395f783c028d84d5b8ecb/src/core/document.js#L334-L353

**Comment by calixteman** [comment]
Adding a `appearance.dict.get("Resources").get("XObject").get("Fm0").reset();` at https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L558 fixes the issue... 
I had this idea because of the `reset` just before.
I can add a bool and a check to add this `reset` but I've the impress we can do better. Any ideas ?

**Comment by timvandermeij** [comment]
I wonder why that fixes the problem though. I can only image the current `reset` usage is to reduce memory usage because the operator list is rendered, so we can discard the appearance stream. However, when re-rendering I would expect it to just be recalculated. Why is that not the case now and is the case when you reset that particular element?

**Comment by timvandermeij** [comment]
Ah, `reset` on a `StringStream` doesn't do what I thought it did. It doesn't clear the stream, but it puts the reading position back to the beginning of the stream. In that case it makes sense that we need to reset this new string stream too because once we read it, we're at the end and a new invocation will simply do nothing because we already read everything...

I think your solution will indeed work, but I also can't avoid feeling that there should be a better solution...

**Comment by Snuffleupagus** [comment]
> It doesn't clear the stream,

Note that it's *not* suppose to either...

> but it puts the reading position back to the beginning of the stream.

... and this is the one and only purpose of the `reset` method, which exist on all of the various Stream-implementations.

> I think your solution will indeed work, but indeed there should be a better solution.

The problem with the idea in https://github.com/mozilla/pdf.js/issues/12337#issuecomment-687900775 is that it feels very hacky, and in general it's also not a workable solution.

---

The first thing you want to (and should) do here is understand *exactly* why things break, and in particular what's special about newly added code. As you might remember, we don't cache Streams on the `XRef`-instance partly because of size considerations *and* partly because of the problems associated resetting their start-position.

In this case though, the issue with the Streams in the `_setDefaultAppearance` method is that they're not referred to by `Ref`s (since you cannot just create `Ref`s, if they're not already in the PDF document) but instead created/referenced explicitly. Given that the result of `_setDefaultAppearance` is cached in `this.appearance`, you end you keeping some Streams alive in an (for other parts of the code-base) completely unexpected fashion.

My somewhat naive idea, given that `_setDefaultAppearance` is only relevant to a subset of documents without complete data, would be if it's possible to e.g. cache the `buffer` and some related state and instead lazily create `this.appearance` using a non-caching getter in this case!?
