### ISSUE TITLE
TypeError:  Function expected at message_handler.js:232

### ISSUE THREAD

**Issue by gvillo** [mozilla/pdf.js#12347]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge 18.18362
- Operating system and its version: Windows 10
- PDF.js version: v2.4.456
- Is a browser extension: No

Steps to reproduce the problem:
1. We were just trying to render a PDF using that particular version of Edge Browser
2. It works ok for other browsers such as new Edge, Chrome, Firefox.
2. Nothing else. 

What is the expected behavior? (add screenshot)
Avoid having that error in the console and show the PDF.

What went wrong? (add screenshot)
I've got the stack trace from our production logging:
![image](https://user-images.githubusercontent.com/11096470/92526430-e0debb00-f1fb-11ea-838e-21f5d8bbf577.png)
![image](https://user-images.githubusercontent.com/11096470/92526444-e63c0580-f1fb-11ea-81c4-baa41478ecb3.png)

Console log errors:
![image](https://user-images.githubusercontent.com/11096470/92526392-cc022780-f1fb-11ea-84d8-30a25b7ca3e4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
I can't provide this

Sorry I can't provide a link or the PDF because of confidentiality.

**Comment by timvandermeij** [comment]
> It works ok for other browsers such as new Edge, Chrome, Firefox.

Note that this seems to be a platform issue then instead of a PDF.js issue. Note also that PDF.js will stop supporting the non-Chromium-based Edge versions from the next stable version.

It _seems_ to error at `ReadableStream`, so I can only guess that the browser does not support readable streams yet. Make sure you're using the correct version of PDF.js: there is an ES5 version for older browsers and a non-ES5 version for modern browsers; see https://github.com/mozilla/pdf.js/blob/50958c46f76f927b83bacee705803b33a1018c0a/external/dist/README.md#L11 and in particular:

`For usage with older browsers/environments, without support for modern features such as e.g. async/await, and ReadableStream, please see the es5 folder.`
