### ISSUE TITLE
Add the possibility to parse and create xref streams and objects in object streams

### ISSUE THREAD

**Issue by nradosevic** [mozilla/pdf.js#12358]
Since a lot of newer PDFs (for example the pdf created using google docs) use xref streams instead of xref tables, It would be nice to have the possibility to parse and create xref streams and the objects included in those streams. 

Here's the issue I currently face for example: I'm using pdf.js to create a javascript library for signing pdfs. Since, in some pdfs the pages object is inside the xref stream, I need to somehow manipulate this object in order to add the signature annotation. And also, since during preparation for signin I add a lot of object inside the pdf, I need to rewrite the xref stream in the end. So, the possibility to re-create those streams from the parsed values would also be very helpful

**Comment by Snuffleupagus** [comment]
Please keep in mind that the purpose of the PDF.js project is allow to parsing and rendering of existing PDF documents, rather than arbitrary editing of documents.

While the need to support AcroForms has meant that there's now some *limited* support for saving of data, this is mostly restricted to incremental updating of existing annotation data. Hence it's really quite unlikely that more general editing support will be added, unless absolutely necessary for some aspect of AcroForm support since PDF editing isn't the main focus of the PDF.js library.

> I need to somehow manipulate this object in order to add the signature annotation. And also, since during preparation for signin I add a lot of object inside the pdf,

Also, this kind of feature does seem *somewhat orthogonal* to the kind of editing (of AcroForm data) that's currently supported in the PDF.js library.

Finally, as-is this issue unfortunately isn't really actionable; please note the *third* paragraph in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our Matrix room at https://chat.mozilla.org/#/room/#pdfjs:mozilla.org.

**Comment by nradosevic** [comment]
Hello, 
Thanks for your ultra quick answer. Ok, I realise that editing PDF documents isn't in the scope of this library. But, how about parsing the values of the objects that are embedded in xref stream, as well as other stream objects?

**Comment by timvandermeij** [comment]
Unless it's necessary for rendering the PDF, it's unlikely that will be added unfortunately.
