### ISSUE TITLE
Failed to load resource: net::ERR_FILE_NOT_FOUND

### ISSUE THREAD

**Issue by mygamingfr7** [mozilla/pdf.js#12353]
Attach (recommended) or Link to PDF file here:
![Screenshot (2)](https://user-images.githubusercontent.com/70934541/92596067-d5a29280-f2c2-11ea-9139-ccded36df3a2.png)

Configuration:
- Web browser and its version: Microsoft Edge Version 85.0.564.44 
- Operating system and its version: Windows 10
- PDF.js version: latest 
- Is a browser extension:

Steps to reproduce the problem:
1. just opened the viewer.html
2. the view was opened but no buttons are working.
3. in console, i got this error(attached in screenshot).
4. i just clicked on file, but it is not working.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Looking at the screen-shot, it appears that you didn't read https://github.com/mozilla/pdf.js#getting-the-code since it contains the following information:
> Finally, you need to start a local web server as some browsers do not allow opening PDF files using a `file://` URL. 

---

> PDF.js version: latest

You should always provide *actual* version numbers, since "latest" can mean any number of things and is consequently of no use.

---

All-in-all, this issue is missing too much information in order to be actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
