### ISSUE TITLE
Readme should have `npm install pdf.js` on how to use... And a better tutorial. (I've added a suggestion on how could be improved)

### ISSUE THREAD

**Issue by stevemarksd** [mozilla/pdf.js#12379]
I think is a big oversight forgetting to add this, I had to open package.json to figure out if was even on npm... I haven't seen a readme without `npm install ...` for long time. and this seem like a big project.

**Comment by stevemarksd** [comment]
And this installs `"pdf.js": "^0.1.0",` wtf... OMG is actually installing another package `https://github.com/stanfeldman/pdf.js`, what a mess. How to use this with the regular `npm install`?

**Comment by stevemarksd** [comment]
Ok, I saw now burried in a block of text.. is `npm install pdfjs-dist`... I think should be way way more obvious.

**Comment by stevemarksd** [comment]
Tutorial could be so much better

## How to actually use it with npm

### Installation

Install: `yarn add pdfjs-dist @types/pdfjs-dist` (replace `yarn add` for `npm install` if you use npm. Also remove `@types/pdfjs-dist` if you don't use typescript.

### Setup

```
// We need to get the url of the worker (we use min for prod)
import workerSrc from '!!file-loader!pdfjs-dist/build/pdf.worker.min.js'
// Use require because import doesn't work for some obscure reason. Also use `webpackChunkName` so it will not bundle this huge lib in your main code
const pdfjsLib = require(/* webpackChunkName: "pdfjs-dist" */ `pdfjs-dist`)
// Now you assign the worker file path to the `pdfjsLib` (yes, it's that cumbersome)
pdfjsLib.GlobalWorkerOptions.workerSrc = workerSrc
```

### Usage

Add a `<canvas id="pdf-canvas"/>` to your HTML.

Then in a js file put:

```
    // Loads the actual pdf
    const pdf = await pdfjsLib.getDocument(props.url).promise
    // Opens page 1?
    const page = await pdf.getPage(1)
    // Creates or gets a viewport?
    const viewport = page.getViewport({scale: 1})

    const canvas = document.getElementById('pdf-canvas')
    const context = canvas.getContext('2d')
    canvas.width = 600
    canvas.height = 300

    const renderContext = {
      canvasContext: context,
      viewport: viewport,
    }
    page.render(renderContext)
```

This is what I'd expect from a tutorial TBH. Yes, I complain about it, but I also give you a way to improve.

## Minor details in guides

All these small details gives me the impression of a poorly written library. (even if it might not be)

```
canvas.height = viewport.height;
canvas.width = viewport.width;
```

Why in the world would you switch width, height order to height, width? Just wasted time to fix bug where I expected width and height ordering.

### Promises async await

Mentions await in many places, but tutorial is `loadingTask.promise.then`... let's write some nice code with `async` `await`

### Still on es5?

`var`s, no arrow functions...

### Naming

`const loadingTask = pdfjsLib.getDocument(props.url)`, loadingTask is weird

`the-canvas`... come on..

**Comment by Snuffleupagus** [comment]
> I'm talking about https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples

*Generally speaking:* Most of the examples provided are purposely generic, and not framework/bundler specific, since it's very difficult to maintain and support a wide range of different of frameworks/bundlers for the regular PDF.js contributors.

Note that https://mozilla.github.io/pdf.js/examples/index.html#hello-world-walkthrough contain links to additional examples.

> Webpack specific code [...]

For the reasons outlined above, we don't want to advertise e.g. Webpack specifically in *basic* examples; however [the examples folder](https://github.com/mozilla/pdf.js/tree/master/examples/) contains the following: https://github.com/mozilla/pdf.js/tree/master/examples/webpack 

> [...] so I think this example makes more sense than using the cdn

It may be more appropriate for *your* use-case, but everyone probably isn't using Webpack,

> Also remove `@types/pdfjs-dist` if you don't use typescript.

No one should be using those, since they're *not* official and most likely neither up-to-date or correct.

However, *official* TypeScript definitions are being distributed here: https://github.com/mozilla/pdfjs-dist/tree/master/types

> canvas.width = 600
> canvas.height = 300

Note that simply hard-coding of values, without any regard for the `viewport`, may have generally unintended side-effects for many PDF documents.

> Why in the world would you switch width, height order to height, width?

It's hopefully obvious that mistakes can/will happen, since everyone is human. (Also, this really seem like a minor issue for rather than a huge "bug"..)

> Mentions await in many places, but tutorial is `loadingTask.promise.then`... let's write some nice code with `async` `await`
>
> `var`s, no arrow functions...

The general PDF.js library is still usable in environments/browsers without native support for those features, hence we *purposely* don't use things like `async`/`await` in general examples; note e.g. the two different kind of builds mentioned in https://mozilla.github.io/pdf.js/getting_started/#download

> `const loadingTask = pdfjsLib.getDocument(props.url)`, loadingTask is weird

What's weird about it?
The `getDocument` call returns a `PDFDocumentLoadingTask`-instance, see
https://github.com/mozilla/pdf.js/blob/b0c7a74a0c7403aba86087f8180d75c16ec58602/src/display/api.js#L196-L208
and
https://github.com/mozilla/pdf.js/blob/b0c7a74a0c7403aba86087f8180d75c16ec58602/src/display/api.js#L438-L468

> `the-canvas`... come on..

Huh?

**Comment by stevemarksd** [comment]
I see what you mean, but still, is hard to get started... I didn't even find the webpack example. I'd say there is a discoverability issue on the readme. I'd suggest you to look at other libraries and take a look on how they architect their readme. I don't usually take my time to write so much, unless I think there is a big room for improvement.

I don't have time to read everything on the readme to find examples and then webpack. See what happened:

 - I searched for `npm` on readme: found a few results, somehow I missed the text `usage with NPM and Bower under the pdfjs-dist name. `. My patter recognition didn't notice a `npm install blabla` so I missed. 
 - I searched for `typescript`: no results. then my default is to use `@types/blabla`. Again, apparently I got the wrong library
 - I searched for `webpack`: no results. I guess I should have found `More examples can be found in the examples folder. `, press that link, then webpack... but didn't happen.

All these details makes it hard to get started. For example as a user of this library I don't even want to look at the source code, especially when I'm in rush. (I know is superficial, but sometimes you can't read source code of every lib you use, especially if I'm only trying out to do a proof of concept)



Also https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js

```
pdfjsLib.GlobalWorkerOptions.workerSrc =
  "../../build/webpack/pdf.worker.bundle.js";
```

I'm not sure that's something to suggest, would be nice to give an example that can be used by a noobie. Also still not async/await and vars. (but not a big deal)

**Comment by timvandermeij** [comment]
> I didn't even find the webpack example. I'd say there is a discoverability issue on the readme.

We don't want to advertise all individual examples separately in the README since it would make it much bigger than necessary and big README files may be even less inviting to actually read. In my experience it's pretty common to just Ctrl + F for "example" and find them.

> I don't have time to read everything on the readme to find examples and then webpack.

To be fair, we can change the README all we want, but if people can't be bothered to actually read the README then you can't be surprised that you're missing information...

>  I searched for npm on readme: [..] somehow I missed the text usage with NPM and Bower under the pdfjs-dist name. My patter recognition didn't notice a npm install blabla so I missed.

I think NPM is listed pretty clear with a link to a page with more details, including the `pdfjs-dist` name. The README should be concise, so we can't put all details in there. The "somehow I missed " and "pattern recognition didn't notice" to me just seem to indicate that the search was incomplete.

>  I searched for typescript: no results.

According to https://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html#including-declarations-in-your-npm-package the `types` property in the `pdjs-dist` package is the standard way of publishing those types, and we do this in https://github.com/mozilla/pdfjs-dist/blob/master/package.json#L5. We only ship TypeScript definitions in the final NPM package, so I don't know what there would be to mention about TypeScript here...

> sometimes you can't read source code of every lib you use, especially if I'm only trying out to do a proof of concept

I agree that you shouldn't need to read the source code, but even for a POC you'll need to do _some_ reading of e.g., READMEs and example code.

All in all, this issue contains _a lot_ of different points about not only the README but also the examples and the source code syntax, so it's kind of all over the place. In order for this issue to be actionable, let's focus on the README and leave the rest as-is since, as indicated, there are good reasons for the code to be like this.

Let's discuss how the README could be improved to make getting started easier. Do you have examples of README files from other projects that you'd recommend we follow if they have a more clear structure? It could help to serve as inspiration to change our README file.

**Comment by VicJer** [comment]
How do I type RenderTask? The PDFPageProxy.render type is RenderTask but I can't seem to be able to import the RenderTask def.

**Comment by timvandermeij** [comment]
Please don't post unrelated questions here. This has _nothing_ to do with the README.

**Comment by Snuffleupagus** [comment]
Given that https://github.com/mozilla/pdf.js/issues/12379#issuecomment-692955362 asked for more *detailed* information about what to improve in the README, but none has been provided, should we close this for now until more actionable information is available?

**Comment by Z-a-r-a-k-i** [comment]
Please add a section in readme with simple npm install instruction, this is standard in 2021 and I can't believe that I had to dig this issue. Seriously this is a 33k stars repository, it's supposed to be golden standard about being easy to understand and integrate in any solution.

Most insane part is that the issue was closed and nothing was done to address the problem.

**Comment by Z-a-r-a-k-i** [comment]
Okay my bad it's here in the readme: https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website
Could have been way easier to find

**Comment by codydbentley** [comment]
I know this is closed, but I have to also agree with @stevemarksd. Despite being very popular, there is a *lot* of room for improvement in this library's docs. Googling this library and how to use it almost always lands on the mozilla.github.io page, which *does not have anything anywhere about using yarn or npm*. Steve's answer gave me enough information about how to solve it for my own use. Only after coming here did I find out it was buried in the FAQ under a question completely unrelated to using a package manager. And even then, it only tells me something I already knew, which was to install the `pdfjs-dist` library, but nothing about how to get it to actually work after installing.

> We don't want to advertise all individual examples separately in the README since it would make it much bigger than necessary and big README files may be even less inviting to actually read. In my experience it's pretty common to just Ctrl + F for "example" and find them.

You don't have to include an example for every webpack config possible, you just need *any* example of importing the lib and using it manually without knowing the inner workings of the core, and most people can figure it out from there. 

Ideally, like most modern frameworks, it's desirable to be as simple as this:
```
npm install pdfjs-dist
or
yarn add pdfjs-dist

import pdfjsLib from 'pdfjs-dist'
or
pdfjsLib = require('pdfjs-dist')

let loadingTask = pdfjsLib.getDocument('..')
... // follow the existing examples from here
```

That is good enough and covers most use cases without going into specifics of webpack configs etc. However, I'm assuming due to the inner workings of the core, it requires setting up stuff with the worker manually. But as long as you can show one example of importing/requiring the pieces and putting them together to make a working pdfjsLib, people can figure out the specifics for their dev environment and then follow the examples from there.

**Comment by irskep** [comment]
I'm jumping into this library today and had the exact same experience as @codydbentley. I totally agree with his suggestions. I don't use webpack but any example using a `require` or `import` would have saved me a lot of time.

**Comment by robertmazzo** [comment]
> bad

indeed. After copying the build to my local assets folder, I used: `import * as pdfjsLib from 'pdfjs-dist/webpack';
`

**Comment by robertmazzo** [comment]
> Okay my bad it's here from a link in the readme: https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website Could have been way easier to find

indeed. After copying the build to my local assets folder, I used in my ts file: import * as pdfjsLib from 'pdfjs-dist/webpack';

**Comment by BryanCrotaz** [comment]
I followed the instructions and just got a load of worker errors. I completely agree with @stevemarksd that the readme needs a lot of work. I only found this thread via two other closed issues. 

I want to render a pdf in a webpage in my Emberjs app. Ember has fabulous tooling that for ANY other npm package JustWorks(TM). 

You want a really good example of a readme?

https://github.com/mainmatter/ember-simple-auth

**Comment by dremnik** [comment]
I'm shocked that after this many years the docs for this library still haven't been improved... the obstacles that one has to overcome just to get a working example are absurd.

**Comment by v-radev** [comment]
You can load it with npm like this:
```
import { GlobalWorkerOptions } from 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.7.76/build/pdf.min.mjs'

GlobalWorkerOptions.workerSrc = 'https://cdn.jsdelivr.net/npm/pdfjs-dist@4.7.76/build/pdf.worker.min.mjs'
```

The use `pdfjsLib` like the examples.
