### ISSUE TITLE
pdfjs-2.5.207-es5-dis can not display INK in pdf file。

### ISSUE THREAD

**Issue by starryfunj** [mozilla/pdf.js#12392]
Attach (recommended) or 
[product1.pdf](https://github.com/mozilla/pdf.js/files/5249872/product1.pdf)
Link to PDF file here:

Configuration:
-  chrome 80.0.3987.149
- windows 10 professional edition:
- PDF.js version:pdfjs-2.5.207-es5-dist,pdfjs-1.8.188-dist
- Is a browser extension: no

Steps to reproduce the problem:
1. use pdfjs-1.8.188-dist ,chrome can display Ink in the first page  in product1.pdf.
2. use pdfjs-2.5.207-es5-dist ,chrome can not display Ink in the first page  in product1.pdf.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/71555076/93668018-7b70b100-fabc-11ea-873f-1850b4c4a641.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/71555076/93668001-5a0fc500-fabc-11ea-8d0b-40efc8728811.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
The pull request above will fix this, but do note that the PDF generator you're using (iText 7.0.3) is generating _invalid_ PDF files since the `InkList` property for ink annotations is required and must be an array according to the PDF specification; see https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#page=413&zoom=auto,-215,569 section 12.5.6.13. Consider filing a bug report for iText too.
