### ISSUE TITLE
FormatError: Page count in top-level pages dictionary is not an integer.

### ISSUE THREAD

**Issue by Will233** [mozilla/pdf.js#12402]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Chrome
- Operating system and its version:Mac OS
- PDF.js version: 2.4.456
- Is a browser extension:no

Steps to reproduce the problem:
1. open this pdf:
https://askbob-stg.pingan.com.cn/terms/TA001801.pdf

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
Can't open the pdf, **FormatError: Page count in top-level pages dictionary is not an integer.**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> https://askbob-stg.pingan.com.cn/terms/TA001801.pdf

It appears that this PDF document has changed on the server, since the issue was originally opened, and given that the new one is in a sense *more* broken[1] I'm thus attaching the original one here:

[issue12402.pdf](https://github.com/mozilla/pdf.js/files/5597129/issue12402.pdf)

---
[1] All of the "new" breakage is however not related to the XRef-issues as such, which is good.
