### ISSUE TITLE
pdfjs-dist should include the types in npm release

### ISSUE THREAD

**Issue by gaspard** [mozilla/pdf.js#12403]
"pdfjs-dist" release: 2.5.207

Steps to reproduce the problem:
1. npm install psdfjs-lib
2. look at installed node_modules/pdfjs-lib

![image](https://user-images.githubusercontent.com/21707/93865587-cfe77c80-fcc6-11ea-9f8f-ec6306e899c8.png)

The types present [here](https://github.com/mozilla/pdfjs-dist/tree/master/types) are not included.

What is the expected behavior?

Keep the "types" entry in `package.json` and include the `types` folder with the build.

What went wrong?

There is no easy way I know of for people to have up-to-date types for this library...

I think `@types/pdfjs-dist` is not maintained (I have errors using it).

With the confusion around `pdf.js` and the (not related) npm package `pdfjs`, this is not helping.

If anyone can explain the npm release process for this library, I could create a PR...

Oh and why is this thread #12384 referring to release 2.6.347 ? There is no such npm release.

**Comment by Snuffleupagus** [comment]
> "pdfjs-dist" release: 2.5.207
> [...]
> The types present [here](https://github.com/mozilla/pdfjs-dist/tree/master/types) are not included.

The TypeScript definitions are available starting with PDF.js version `2.6.347`, which is the current pre-release version.

The version you mention is the current *stable* release, and please note that unless there's a *very significant* regression found it won't be updated/changed at this point in time. Hence you'll either have to update to the pre-release version, or wait for the next stable release, in order to use the official PDF.js TypeScript definitions.

> There is no easy way I know of for people to have up-to-date types for this library...

As already mentioned, 

> Oh and why is this thread #12384 referring to release 2.6.347 ? There is no such npm release.

Yes there is; it's available under the `next` tag, see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

**Comment by Snuffleupagus** [comment]
> "pdfjs-dist" release: 2.5.207
> [...]
> The types present [here](https://github.com/mozilla/pdfjs-dist/tree/master/types) are not included.

The TypeScript definitions are available starting with PDF.js version `2.6.347`, which is the current pre-release version.

The version you mention is the current *stable* release, and please note that unless there's a *very significant* regression found it won't be updated/changed at this point in time. Hence you'll either have to update to the pre-release version, or wait for the next stable release, in order to use the official PDF.js TypeScript definitions.

> There is no easy way I know of for people to have up-to-date types for this library...

As mentioned above, TypeScript definitions are available from PDF.js version `2.6.347` (and above).

> If anyone can explain the npm release process for this library, I could create a PR...

Again, as mentioned above, we're unfortunately not going to update previous releases.

> Oh and why is this thread #12384 referring to release 2.6.347 ? There is no such npm release.

Yes there is; it's available under the `next` tag, see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions

**Comment by gaspard** [comment]
@Snuffleupagus Thanks for the neat and clear reply 😊 

I did not understand this thing about pre-release and stable versions.

I'll do a `patch-package` hack until this new stable release 😌

**Comment by simhyr** [comment]
Thanks for the typescript-definitions! 

Could you also provide a basic typescript example? I tried different ways to import the pdfjs-dist library, but the import is typed as 'any' or fails. I tried to import it like this:

`
import * as pdfjsLib from 'pdfjs-dist'; // Error: 'Could not find a declaration file for module pdfjs-dist'
let pdfjsLib = require('pdfjs-dist'); // is typed as 'any'

// this does not work at all - i think that's maybe a pretty old example
import { PDFJSStatic } from 'pdfjs-dist';
const PDFJS: PDFJSStatic = require('pdfjs-dist');
`

**Comment by kcterala** [comment]
@trieu-hphuc96 Hi, are you able to solve the issue?

**Comment by Alwaz** [comment]
> Hi, I see the same issue when try to import pdfjs-dist/build/pdf.min.mjs
> 
> ![image](https://private-user-images.githubusercontent.com/22952175/286861910-14b970ef-9a2b-4ce5-9af9-a54175002e1a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2MzY1MDMsIm5iZiI6MTcxMzYzNjIwMywicGF0aCI6Ii8yMjk1MjE3NS8yODY4NjE5MTAtMTRiOTcwZWYtOWEyYi00Y2U1LTlhZjktYTU0MTc1MDAyZTFhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE4MDMyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWIzYzQxYmNkN2Q5MDkyOGU4MTUyZDQ0OTE3YTlhYmEzZmM4NDFjODRkYWU5ODk0Yjc1MzQ1ZmI3MjI5ZmZhMWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4Yz0opEi7ZeMNDf1BtVRleobo3fDsH5YMDoqAyThM48)

Same issue, is anyone able to solve it?

**Comment by leniel** [comment]
I just asked a question at StackOverflow regarding this same issue with the latest version of pdf.js @ the moment which is v4.9.155:

https://stackoverflow.com/q/79303943/114029
