### ISSUE TITLE
Page-next/Page-prev navigation via left/right arrow key broken in Firefox 81

### ISSUE THREAD

**Issue by occasionallydavid** [mozilla/pdf.js#12416]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 81
- Operating system and its version: Ubuntu 20.04
- PDF.js version: included
- Is a browser extension: no

Steps to reproduce the problem:

1.  Open any PDF in any mode except 'page fit'
2. Observe left/right arrow no longer jump to top of prev/next page, but scroll viewport horizontally
3. Observe viewport scrolling even in zoom modes (like page width) where there is no horizontal bleed, and for which prior versions implemented prev/next page

What is the expected behavior? (add screenshot)

Previous behaviour was ideal

What went wrong? (add screenshot)

Firefox 81 upgrade broke prev/next page keyboard nav

**Comment by Snuffleupagus** [comment]
WFM, with http://mirrors.ctan.org/info/lshort/english/lshort.pdf in Firefox 83.

> Observe left/right arrow no longer jump to top of prev/next page, but scroll viewport horizontally

Just to make it *absolutely* clear, can you please confirm that there's not a horizontal scrollbar visible?

(Since if there is, then the correct behaviour is indeed to just scroll rather than changing pages.)

> Firefox 81 upgrade broke prev/next page keyboard nav

There's been no recent changes, as far as I know, to the relevant PDF.js code which could explain this. 

Without a lot more information, it's unfortunately going to be next to impossible to fix this; hence
 - See if you can reproduce this in Safe Mode, more information here: https://support.mozilla.org/en-US/kb/troubleshoot-firefox-issues-using-safe-mode
 - See if you can reproduce this when a "clean" Profile, more information here: https://support.mozilla.org/en-US/kb/profile-manager-create-remove-switch-firefox-profiles
 - If all of the above fails to provide any clues, please use https://mozilla.github.io/mozregression/ to try and narrow down *exactly* when this broke.

**Comment by occasionallydavid** [comment]
Can confirm, closing sidebar for this one particular PDF causes horizontal scrollbar to disappear. Apologies, inner autistic screeching  at changed toolbar icons was convinced the sky was falling. ;) Closing
