### ISSUE TITLE
The context of the document is not rendered properly in the document,Garbled text in two text boxes

### ISSUE THREAD

**Issue by menver** [mozilla/pdf.js#12418]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
All browsers.
- Operating system and its version:
Windows 10
- PDF.js version:
Tested 2.0/2.1.266/2.3.200/2.4.456/2.5.207/2.6.347
- Is a browser extension:
Yes and viewer and embeded in our product, same issue

Steps to reproduce the problem:
1. open document

What is the expected behaviour?
Compare to Acrobat or Chrome PDF viewer

What went wrong? (add screenshot)
Garbled text in two text boxes

Document to be supplied by client rep.

**Comment by alex-tuca** [comment]
[AnonymizedDocument-PRSTECM-760.pdf](https://github.com/mozilla/pdf.js/files/5291451/AnonymizedDocument-PRSTECM-760.pdf)

**Comment by Snuffleupagus** [comment]
I have a patch for this locally; however when opening future issues it would be helpful if you observe the following points:

---

> Attach (recommended) or Link to PDF file here:

To save everyone's time, please make sure to always attach the PDF document *directly* after this line; note that the initial comment should contain *all* of the necessary information.

> Web browser and its version:
>       All browsers.

Please actually list the browsers you tested with, since "all browsers" isn't terribly helpful in *general*.

> What went wrong? (add screenshot)
> Garbled text in two text boxes

Also, attaching screen-shots is often helpful to quickly illustrate to problem (which is why the ISSUE_TEMPLATE asks for those).
Especially since the use of words such as "text boxes" makes it sound like this was a form-related issue (which isn't the case here).

**Comment by menver** [comment]
Hello, 
thank you for your comments.
FYI We cannot provide the document due to GDPR limitations within our company.
But the "client" cannot provide the technical detail you need.
This is why we always have to take this route, Synchronise client with us to create the ticket and them to upload.
I understand this may be irritating but please be assured its more so for us.
For the browser comment, yes sorry should have listed, IE11 FF and Chrome.
Due to GDPR we also cannot upload screenshots.
Would you prefer the client to do this as they upload the document?

**Comment by Snuffleupagus** [comment]
Please refrain from *knowingly* open incomplete issues, and either:
 - Wait until you've collected *all* the necessary details before opening the issue. (If necessary, obtain permission from your users to supply the needed information.)
 - Have the user with access to all of the required details open the issue instead.

> This is why we always have to take this route,
> [...]
> I understand this may be irritating but please be assured its more so for us.

It seems completely reasonable that you adjust *your internal process* to make life easier for the PDF.js contributors, rather than expecting the opposite here; please also see below.

---

Finally, please keep in mind that this is an open source project that you're able to use *for free*, with a lot of the development done by unpaid volunteers. As such it's imperative that all opened issues are fully complete and actionable, since you unfortunately end up wasting peoples spare time otherwise!

**Comment by menver** [comment]
Hello,

Neither is possible.
GDPR means we cannot supply client information such as the document.
We cannot have the client open the issue as firstly we need to be the owner, and secondly they do not have the product knowledge to open a ticket.
I did explain this in my last post.
lol extremely reasonable, yep ok perhaps you have not worked for a large cooperation with a large legal team.
When you do you try getting them to change their mind on a stated internal process.
I do understand this is a free resource, and we do appreciate it.
I am really struggling on how one person creating the ticket, and then moments (less then 30 seconds) another person uploading the document is really a big deal.
We have raised Several tickets and this concern has never been raised.

Many thanks,

**Comment by timvandermeij** [comment]
Fixed by the PR above.
