### ISSUE TITLE
Which version do I need to make getDocument work with Microsoft Edge browser?

### ISSUE THREAD

**Issue by gremo** [mozilla/pdf.js#12425]
Using version `2.5.207` and importing:

- `pdfjs-dist/build/pdf`
- `pdfjs-dist/build/pdf.worker.entry`

Will lead to an error as soon as you use `getDocument`:

```
const loadingTask = pdfjsLib.getDocument(pdfUrl);
await loadingTask.promise;
```

> Unhandled promise rejection TypeError: Function expected
> TypeError: Function expected at MessageHandler.prototype.sendWithStream (http://localhost:8000/build/vendors~app~catalog.js:61445:5) at PDFWorkerStreamReader

From the FAQ:

> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being [...]

So I'm wondering, which version can work with Microsoft Edge?

**Comment by Snuffleupagus** [comment]
If using `pdfjs-dist`, please see https://github.com/mozilla/pdfjs-dist/tree/master/es5

**Comment by gremo** [comment]
Hi @Snuffleupagus thanks for helping. So it's not my bad, Edge is quite a good browser but still I need to import ES5 version (which is slow as hell)?

**Comment by timvandermeij** [comment]
Modern Edge is Chromium-based, so that version is supported. The non-Chromium-based Edge is not supported anymore and contained a number of bugs in the platform, so if you need that version you need to ES5 version. There should be many noticeable differences between the ES5 and the non-ES5 version, but that also depends on the platform.
