### ISSUE TITLE
JAPAN text is not displaying in PDF with PDF.js

### ISSUE THREAD

**Issue by DILEEPKUMAREBIX** [mozilla/pdf.js#12457]
Japanese characters are not loading in IE 11 browser with latest **pdfjs-2.6.347-es5-dist**.

Where as same PDF displaying good in all other browser including EDGE.

Getting below warning message in console.

PDF 9a16c1e2adbc4e44af1ed7dedb359d9d [1.4 Adobe PDF Library 10.0 / Acrobat PDFMaker 10.1 for Word] (PDF.js: 2.6.347)
Warning: Load test font never loaded.
Warning: Load test font never loaded.

Chrome:
![image](https://user-images.githubusercontent.com/16190934/95458268-8b7b0280-098f-11eb-9f79-6c6c74128b35.png)

IE:
![image](https://user-images.githubusercontent.com/16190934/95458394-b8c7b080-098f-11eb-9e81-a1e7c2a81f93.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide ***all*** of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's actionable information provided.

Furthermore, please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support (emphasis mine):
> While the library and the default viewer should still work in IE 11/Edge (non-Chromium-based) for the time being, some functionality/features may not be available and the performance will be worse compared to modern browsers. ***However, this support will be dropped after stable version `2.6.347`.***
