### ISSUE TITLE
Is this lib deprecated for angularJS ?

### ISSUE THREAD

**Issue by JordaoViktor** [mozilla/pdf.js#12455]
Guys i'm trying to use that lib but my angularJS do not reconize this lib! someone with same problem ?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by timvandermeij** [comment]
Moreover, AngularJS is not developed anymore, only Angular is. That may be another reason why PDF.js doesn't work anymore in combination with that framework version.
