### ISSUE TITLE
Full width on mobile view

### ISSUE THREAD

**Issue by dickyj** [mozilla/pdf.js#12456]
When viewing the pdf in Android or iOS Safari,

I use the following code:
```
eventBus.on("pagesinit", function() {
            // We can use pdfViewer now, e.g. let's change default scale.
            // adjust to 66% based on bootstrap theme
            const currentPage = pdfViewer._pages[pdfViewer._currentPageNumber - 1];
            if (jQuery.browser.mobile) {
                // pdfViewer.currentScaleValue = DEFAULT_SCALE_VALUE;
                pdfViewer.currentScaleValue =  (pdfViewer.container.clientWidth - 10) / currentPage.width * currentPage.scale;
            } else {               
                const pageWidthScale =
                    ((pdfViewer.container.clientWidth * 0.64) / currentPage.width) *
                    currentPage.scale;
                //pdfViewer.currentScaleValue = DEFAULT_SCALE_VALUE;
                pdfViewer.currentScaleValue = pageWidthScale;
            }

        });
```

But I notice that somehow it always default to some padding that is 15 pixels on left and right side, even though I only allocate 10 pixels total (5 left and 5 right). Have anyone experienced the same issue? I am unable to scale it so that it takes up as much space as possible in a mobile device.

**Comment by Snuffleupagus** [comment]
Given the overall lack of information it's somewhat difficult to tell, but perhaps you want to use this option when initializing the `PDFViewer`-instance: https://github.com/mozilla/pdf.js/blob/99a2302d88aa0df8254e225cedc9c68e8ba9aacb/web/base_viewer.js#L59-L60

> `const currentPage = pdfViewer._pages[pdfViewer._currentPageNumber - 1];`

That code could stop working *at any time*, since an underscore in JavaScript should be interpreted as something being a "private" property. The correct thing would be to use [this method instead](https://github.com/mozilla/pdf.js/blob/99a2302d88aa0df8254e225cedc9c68e8ba9aacb/web/base_viewer.js#L214-L216), i.e.
```javascript
const currentPage = pdfViewer.getPageIndex(pdfViewer.currentPageNumber - 1);
```

---
 
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue isn't really actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dickyj** [comment]
Jonas,
Thanks for the tips, its very helpful indeed. 
But the pageBorders does not seem to help much, here is what happened after I set removePageBorders to true.
![Inkedcropped_LI](https://user-images.githubusercontent.com/6478334/95476333-58496b00-09b1-11eb-9f06-d9e64008a4d9.jpg)

**Comment by timvandermeij** [comment]
Without a runnable example, as indicated in the issue template. there is nothing we can do to debug this unfortunately.
