### ISSUE TITLE
extension not working with other extensions/looking to find a way to change scroll speed

### ISSUE THREAD

**Issue by joegonzalez722** [mozilla/pdf.js#12466]
I'm using the firefox pdf viewer on google chrome through this extension https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

I'm also using another chrome extension that allows me to change the scroll speed of a webpage
https://chrome.google.com/webstore/detail/chromium-wheel-smooth-scr/khpcanbeojalbkpgpmjpdkjnkfcgfkhb

Due to a code in the pdf viewer, the scrolling chrome extension won't work on the pdf viewer chrome extension, so I can't change the scrolling speed in the pdf.

Is there code I can change in the pdf viewer that would allow me to either
a) change the scroll speed or b) allow the pdf viewer to work with other chrome extensions?

                                            please let me know, I'm eager to hear

**Comment by Snuffleupagus** [comment]
Similar to issues such as e.g. #6444 and #11278, it's somewhat "expected" that different Chrome extensions cannot directly interact with each other; please refer to https://github.com/mozilla/pdf.js/issues/11278#issuecomment-547117742 for more information.

As such it's unfortunately not clear to me that we need to keep this issue open, since the underlying issue is already tracked elsewhere.
