### ISSUE TITLE
how to use svg or make cavanas clearer

### ISSUE THREAD

**Issue by zhoulin845522** [mozilla/pdf.js#12461]
i just use this project in Tomcat without using vue

**Comment by Snuffleupagus** [comment]
As mentioned in the Wiki, the SVG-backend is not officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue simply isn't actionable/valid.
