### ISSUE TITLE
Why did you set maxCanvasPixels as a fixed value(5242880)

### ISSUE THREAD

**Issue by QM36** [mozilla/pdf.js#12495]
Configuration:
- Web browser and its version: chrome 86.0.4240.80
- Operating system and its version: macOS Mojave 10.14.6
- PDF.js version: 2.6.347
I just want to ask a question: Why is maxCanvasPixels set to a fixed value, how is this fixed value calculated, whether it is related to the resolution of the mobile phone, whether it is compatible with multiple models, and whether there will be a black screen on a low-configuration mobile phone Or crash, whether there will be a fuzzy picture in a high-profile mobile phone

Can I customize this value and calculate it dynamically according to the configuration of the phone
https://github.com/mozilla/pdf.js/blob/8b9492a5c41d0776488a27021981b60fbf23a3bf/web/viewer_compatibility.js#L34

Thanks for your answer!

**Comment by QM36** [comment]
Is the following formula correct？ but the value I calculated on iphonex is smaller than 5242880
`compatibilityParams.maxCanvasPixels = window.screen.availHeight * window.screen.availWidth * window.devicePixelRatio * window.devicePixelRatio`

**Comment by timvandermeij** [comment]
> how is this fixed value calculated

The calculation is explained in https://github.com/mozilla/pdf.js/blob/8608f0e6115bf22b4520ed0ef73f3c7bdb451df9/web/pdf_page_view.js#L62-L64.

You can customize it in a custom deployment. It's mainly set to the current value since we found that to work on most devices. It can be seen as an upper limit for what PDF.js can handle on all devices.

**Comment by anudhuri23** [comment]
Do we need to import viewer_compatibility.js to access maxCanvasPixels in viewer.js?
