### ISSUE TITLE
Broken words in span | Question

### ISSUE THREAD

**Issue by 12seetharaman** [mozilla/pdf.js#12509]
I'm seeing words in pdf are broken into multiple spans or sometimes a single word split with extra spaces inside the span.
Is it due to the font? 
Texts are shown correctly in pdf view. I'm trying to extract text from the HTML page (pdf converted).  
Eager to understand the reason for this issue and Is there any way to fix it?
![image](https://user-images.githubusercontent.com/53142037/96791516-41c1fb80-1416-11eb-9e7e-2aa9b07bff8b.png)

**Comment by timvandermeij** [comment]
Text extraction in PDF files is a complex topic because there is no fixed way to do this. For example, there is not really a concept of spaces in text extraction in PDF files: text is not saved as strings, but rather as absolutely positioned glyphs/characters. PDF viewers need to use heuristics in order to get the text extraction that the end user expects. Ours usually gets the job done, but there are also quite some cases where it's suboptimal. Those are tracked in the https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-text-selection category, and what you're describing here is already tracked in there. We'll have to improve the heuristics for these kinds of PDF files.

**Comment by 12seetharaman** [comment]
Thanks for the details @timvandermeij
