### ISSUE TITLE
links not included in annotations

### ISSUE THREAD

**Issue by bbsteventill** [mozilla/pdf.js#12517]
Attach (recommended) or Link to PDF file here:
[document(1).pdf](https://github.com/mozilla/pdf.js/files/5423737/document.1.pdf)

Configuration:
- Web browser and its version: firefox 81.0.2 
- Operating system and its version: macos catalina 10.15.6
- PDF.js version: using the version in ff
- Is a browser extension: no

Steps to reproduce the problem:
1. open the pdf

What is the expected behavior? the links on pages 4 & 5 work

What went wrong? the links in the pdf do not work/not clickable

**Comment by Snuffleupagus** [comment]
That PDF file doesn't actually contain any annotations, but just standard text formatted to *look* like links.

Such "links" can work in e.g. Adobe Reader, but only if you have enabled automatic creation of hyperlinks (this setting seems to default to on).

The issue is tracked in #3172, of which this is a duplicate.
