### ISSUE TITLE
range-download works only with pdfBugEnabled=true

### ISSUE THREAD

**Issue by sharkvik** [mozilla/pdf.js#12513]
![image](https://user-images.githubusercontent.com/13486577/96836858-3db1d000-144e-11eb-892d-33fcad5682de.png)
and
![image](https://user-images.githubusercontent.com/13486577/96836991-65a13380-144e-11eb-8e57-a80d3467ac45.png)

Attach (recommended) or Link to PDF file here:
tested on different files 
the samle is https://cloud.mail.ru/public/2WXG/5diVR5g8K

Configuration:
- Web browser and its version: Chrome dev 88.0.4292.2
- Operating system and its version: Win10
- PDF.js version: 2.5.207

why if i turn off pdfBugEnabled, pdfjs loads everything in the first request, then first and last chunks. If I turn on the flag it works correctly.
url like: http://host/pdf.js/web/viewer.html?file=http%3A%2F%2Fhost%2Fapi%2F%2Fcontent (it's local).
headers is 
![image](https://user-images.githubusercontent.com/13486577/96838064-06442300-1450-11eb-990d-dcbe58cf48ed.png)
what i have done wrong?

**Comment by Snuffleupagus** [comment]
> the samle is https://cloud.mail.ru/public/2WXG/5diVR5g8K
> 
> PDF.js version: 2.5.207

That page is *extremely* difficult to navigate if you don't speak the language in question.
Also, it seems that the page above loads the built-in PDF viewer of the browser used, rather than the PDF.js version you listed.

Please provide a smaller/simpler example, as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Web browser and its version: Chrome dev 88.0.4292.2

Are other browsers similarly affected, or is it specific to Google Chrome?

> why if i turn off pdfBugEnabled, pdfjs loads everything in the first request, then first and last chunks. If I turn on the flag it works correctly.

It's not clear *exactly* how you're setting `pdfBugEnabled`, however please note that there's nothing related to `pdfBug`/`pdfBugEnabled` that should affect file loading. As such this does seem like a red herring, and the possible explanation may e.g. be related to the caching of requests by the browsers.

Furthermore, note that the order and type of requests that are sent depends not just on what the server supports, but also on e.g. the timing of requests (which may vary depending on the PDF data being loaded). 

---

As-is this issue unfortunately doesn't really contain enough information to be easily actionable/valid, and it's also somewhat difficult to follow.
