### ISSUE TITLE
CFF font glyph width processing issue

### ISSUE THREAD

**Issue by acchou** [mozilla/pdf.js#12541]
Six years ago in commit a2c2f81167206560236610b8615541ce5ad84e22, cff glyph widths were added to the hmtx table. At the time, CFF was parsed in `fonts.js`; today that code lives in `cff_parser.js`. Part of that change was extracting each glyph's width from the charstrings parser state machine:

https://github.com/mozilla/pdf.js/blob/8098102714f722988b28b2e00da4d7c1ba2ae8a1/src/core/cff_parser.js#L644-L646

I think there may be a problem with the test `stack[stackSize - 1] >= 0`. The value on the stack is a decoded width value according to the Type 2 Charstring Format section 3.1:

```
1) Width: If the charstring has a width other than that of defaultWidthX (see Technical Note #5176, “The Compact
Font Format Specification”), it must be specified as the first number in the charstring, and encoded as the difference
from nominalWidthX.
```

Note that the encoded width in the font file is the difference from `nominalWidthX`, therefore a negative value is possible.

There is code in the parser to address this:

https://github.com/mozilla/pdf.js/blob/8098102714f722988b28b2e00da4d7c1ba2ae8a1/src/core/cff_parser.js#L721-L727

However, this code never gets a chance to work because `state.width`is never assigned if the value on the stack is negative. I believe the test `stack[stackSize - 1] >= 0` could be removed, but am unsure of the intent. Was this intended to help sanitize values that might be a negative width *after* adjustment by nominalWidth?

The net effect of this issue is that CFF fonts with glyphs that have widths that are less than `nominalWidthX` will have the `defaultWidthX` instead of the correct glyph width. I confirmed that some fonts have incorrect glyph widths by dumping the font data and reviewing with a font/glyph inspector tool.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; without a PDF file that can be used to reproduce/test this we simply cannot consider making any changes to this code since it's just too easy to introduce regressions that way.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; without a PDF file that can be used to reproduce/test this it's very unlikely that we'll make any changes to this code since it's just too easy to introduce regressions that way.

**Comment by acchou** [comment]
Unfortunately a PDF will not be forthcoming because PDF.js does not appear to rely on the width of glyphs in the font data when positioning them for rendering. I'm using the fonts in a different application where the widths in the font data matter. I acknowledge that this isn't a use case that pdf.js would prioritize, so it is in a category of defects that you might be unwilling to spend resources to look at. Given that, I'll close this and simply fix it on my own branch.
