### ISSUE TITLE
Android webview killing itself when loading pdf in webview

### ISSUE THREAD

**Issue by shibilyt** [mozilla/pdf.js#12571]
Attach (recommended) or Link to PDF file here: https://prawnpdf.org/manual.pdf

I am trying to create an android webview to load PDF files. It works fine. But in Andriod Nougat, it will load, and in a couple of seconds, it will close the webview. The issue is only seen for files larger than 1 MB. Smaller files are loading without issue.

Configuration:
- Web browser and its version: android.chrome version 86.0.4240.110
- Operating system and its version: Android Nougat MiUI
- PDF.js version: 2.6.347

Steps to reproduce the problem:
1. In the android Nougat, opening the webview and loading the pdf file.
2. webview is closed after loading initially

What is the expected behavior? (add screenshot)
The pdf should load and not close the webview automatically.

What went wrong? (add screenshot)
The pdf is getting closed automatically

**Comment by Snuffleupagus** [comment]
> I am trying to create an android webview to load PDF files. It works fine. But in Andriod Nougat, it will load, and in a couple of seconds, it will close the webview.

That sounds like a bug in the platform itself, rather than in the PDF.js library, in that case. Hence that's not really something that we can fix here, since the PDF.js simply uses standard web-functionality (e.g. `<canvas>` for rendering).
Furthermore, according to https://en.wikipedia.org/wiki/Android_version_history#Android_7.0_Nougat_(API_24) the last release from that branch was more that three years ago (in April, 2017)

**Comment by belphegor-s** [comment]
This issue is basically due to the platform itself. Also could you please confirm you are using ``MIUI`` (Xiaomi's  UI). If yes, please tell me the current UI version you are using as the PDF.js library is working fine __Tested It BY Myself.__Please do provide the answers as I am pretty much sure that it is a platform based issue not the PDF.js library.

Do, update to any latest version of your UI if available.

**Comment by timvandermeij** [comment]
Closing because of the above. You're most likely hitting a resource limit, causing the webview to be closed. That's a platform issue.

**Comment by ivanferrer** [comment]
The solution should not always be a soap type answer.
