### ISSUE TITLE
Displaying blacked out pages in android webview

### ISSUE THREAD

**Issue by shibilyt** [mozilla/pdf.js#12580]
Attach (recommended) or Link to PDF file here: https://raw.githubusercontent.com/mozilla/pdf.js/ba2edeae/web/compressed.tracemonkey-pldi-09.pdf

I've been working on pdfjs in android webview. Now, when I load the pdf, it's working fine for the first few pages, then in the middle, I'm getting a blacked-out page. 
![screenshot](https://user-images.githubusercontent.com/3939547/98206605-31eeff00-1f60-11eb-9877-7ca80a47a5d5.jpeg)

Now I will go to the bottom of the page and when I scroll up again, all the pages above the blacked out page is now blacked out as well.
![screenshot of all pages blacked out](https://user-images.githubusercontent.com/3939547/98206732-6c589c00-1f60-11eb-9e32-0d1951646e9d.jpeg)

The device is Vivo 1603
The android version is 6.0.1 Marshmello

Configuration:
- PDF.js version: 2.6.347

Steps to reproduce the problem:
1. load the pdf and scroll down
2. A blacked out page will appear.
3. If we scroll down and scroll back to the top, all pages above the blacked-out page is now blacked-out as well

What is the expected behavior? (add screenshot)
The pages should all render without blacking out.

What went wrong? (add screenshot)
Some pages are blacked out

**Comment by Snuffleupagus** [comment]
This (once again) sounds like a bug in the platform/browser *itself*, rather than in the PDF.js library. Hence that's not really something that we can fix here, since the PDF.js simply uses standard web-functionality (e.g. `<canvas>` for rendering).

Furthermore, according to https://en.wikipedia.org/wiki/Android_version_history#Android_6.0_Marshmallow_(API_23) the last release from that branch was almost five years ago (in December 2015).
