### ISSUE TITLE
Sidebar opens after loading PDF

### ISSUE THREAD

**Issue by clempe** [mozilla/pdf.js#12590]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:   Chrome  86.0.4240.183 
- Operating system and its version: Windows 10
- PDF.js version: 2.4.456
- Is a browser extension: no

I hide the _toggle sidebar button_ in the viewer, so the sidebar cannot be opened. However, some pdf files automatically open the sidebar after loading. 
Is there option to disable the sidebar, so it cannot be opened (by user or pdf-file) ?

**Comment by timvandermeij** [comment]
From the description here it looks like that happens because of existing preferences, which is handled here: https://github.com/mozilla/pdf.js/blob/4e13559cb0af2bb5465b69d02b5e0853d101fbd7/web/app.js#L1252-L1255

**Comment by clempe** [comment]
Thanks for your answer.
Ist there an option to permanently disable the sidebar without changing the viewer.js file, like the PDFViewerApplicationOptions ?

**Comment by timvandermeij** [comment]
The only thing you can do it set the `sidebarViewOnLoad` app option to `0`, meaning that the sidebar is not shown. For the meaning of all integer values, see:
https://github.com/mozilla/pdf.js/blob/1eaf9c961b72f9f8803ecd55a90545abc651c8f2/extensions/chromium/preferences_schema.json#L29

**Comment by clempe** [comment]
I tried to set the _sidebarViewOnLoad_ like this:
`document.addEventListener("webviewerloaded", function (){
    PDFViewerApplicationOptions.set('sidebarViewOnLoad', 0);
`
However, the navigation still opens
Testfile: [test.pdf](https://github.com/mozilla/pdf.js/files/5615484/test.pdf)

**Comment by Snuffleupagus** [comment]
> I tried to set the _sidebarViewOnLoad_ like this:
> `document.addEventListener("webviewerloaded", function (){ PDFViewerApplicationOptions.set('sidebarViewOnLoad', 0);}); `
> However, the navigation still opens

This is likely caused by the Preferences over-riding the value you set, which is *generally* desirable given that the primary usage of the default viewer is as the Firefox built-in PDF viewer.

For a *custom* implementation of the default viewer this may not be what you want though, and in that case you *also* need to set the `disablePreferences` options, by adding a `PDFViewerApplicationOptions.set("disablePreferences", true);`-line to your event listener. This will ignore *any* Preference-values, and thus ensure that whatever options you set in your "webviewerloaded"-handler will always be respected.

**Comment by clempe** [comment]
@Snuffleupagus 
Unfortunately, I found another PDF that forces the Sidebar to open.
Any other suggestions to stop this behavior?

[test_2.pdf](https://github.com/mozilla/pdf.js/files/6229435/test_2.pdf)

**Comment by Snuffleupagus** [comment]
> Unfortunately, I found another PDF that forces the Sidebar to open.

Huh; but the two files are basically identical in this respect, since both contain `/PageMode /UseOutlines` in the /Root-dictionary.

> Any other suggestions to stop this behavior?

Please actually follow the already provided answers, particularly https://github.com/mozilla/pdf.js/issues/12590#issuecomment-736433783, since it's been explained which you need to set.

If that's not sufficient, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
