### ISSUE TITLE
font size less than 12px

### ISSUE THREAD

**Issue by liuyuze** [mozilla/pdf.js#12626]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome 76.0.3809.100
- Operating system and its version:win10
- PDF.js version:2.5.207
- Is a browser extension:no

Steps to reproduce the problem:
1. ZoomIn to the fontSize less than 12 px
2.Select a line of text

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/10252397/99212448-05f83700-2806-11eb-8c3f-0cf96746d8ec.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/10252397/99212372-d9441f80-2805-11eb-97dd-a945aecab644.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):none

I fix this bug 
![image](https://user-images.githubusercontent.com/10252397/99212555-48217880-2806-11eb-8e7b-d0f5ceb2657f.png)
![image](https://user-images.githubusercontent.com/10252397/99212606-7010dc00-2806-11eb-8a34-79b01c92a26d.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Once more, please don't open issues without providing this information; as-is this issue will be closed as INCOMPLETE.

> Steps to reproduce the problem:
> 1. ZoomIn to the fontSize less than 12 px
> 2. Select a line of text

That's nowhere near sufficient information to be actionable, especially the *first* point would need be expanded *a lot* since it's almost impossible to understand what "ZoomIn to the fontSize less than 12 px" actually means.

Finally, the code-changes in the screen-shot unfortunately looks more like a hack rather than a proper solution.
