### ISSUE TITLE
Broken ES5 compatibility: typed arrays

### ISSUE THREAD

**Issue by kmcclellan** [mozilla/pdf.js#12633]
Configuration:
- Web browser and its version:  [therubyracer@v0.12.3](https://github.com/rubyjs/therubyracer/tree/v0.12.3) (wrapper for V8 3.16)
- Operating system and its version: Ubuntu 20.04.1
- PDF.js version: 2.5.207

Steps to reproduce the problem:

1. Install Ruby and `therubyracer`.

       $ sudo apt install ruby2.7
       $ sudo gem install therubyracer -v 0.12.3

2. Download "generic" `pdfjs-dist` (including ES5 build).

       $ wget https://registry.npmjs.org/pdfjs-dist/-/pdfjs-dist-2.5.207.tgz
       $ tar -x -f pdfjs-dist-2.5.207.tgz

3. Attempt to load `pdf.js`.

       $ ruby -r v8 -e "V8::Context.new.load('package/es5/build/pdf.js')"

What is the expected behavior?
Script loads successfully using the ES5 engine.

What went wrong?
Engine fails when trying to interpret typed arrays (introduced in ES6).

```
Traceback (most recent call last):
	13: from -e:1:in `<main>'
	12: from at package/es5/build/pdf.js:32:3
	11: from at webpackUniversalModuleDefinition (package/es5/build/pdf.js:31:50)
	10: from at package/es5/build/pdf.js:119:10
	 9: from at Object.defineProperty.value (package/es5/build/pdf.js:116:18)
	 8: from at __w_pdfjs_require__ (package/es5/build/pdf.js:52:30)
	 7: from at Object.defineProperty.value (package/es5/build/pdf.js:322:22)
	 6: from at __w_pdfjs_require__ (package/es5/build/pdf.js:52:30)
	 5: from at package/es5/build/pdf.js:389:13
	 4: from at __w_pdfjs_require__ (package/es5/build/pdf.js:52:30)
	 3: from at package/es5/build/pdf.js:1738:1
	 2: from at __w_pdfjs_require__ (package/es5/build/pdf.js:52:30)
	 1: from at Object.defineProperty.value (package/es5/build/pdf.js:2856:5)
at checkTypedArraySlice (package/es5/build/pdf.js:2851:9): Uint8Array is not defined (V8::Error)
```

**Comment by Snuffleupagus** [comment]
> Web browser and its version:  [therubyracer@v0.12.3](https://github.com/rubyjs/therubyracer/tree/v0.12.3) (wrapper for V8 3.16)

According to the GitHub-page of that project, the last change seems to have been in 2017. From a security perspective, using a browser which is that old might not be generally advisable.

---

> Engine fails when trying to interpret typed arrays (introduced in ES6).

Unfortunately a browser without native support for `TypedArray`s is simply way too old to be used with the PDF.js library; based on e.g. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray#Browser_compatibility every remotely modern browser should support `TypedArray`s.

This is probably a case of a slightly misleading naming convention, on the PDF.js side, since the ES5-releases simply means "for usage with older browsers" and nothing else at this point.
/cc @timvandermeij Should we try to rename those to something else, or would better information in e.g. the README and/or Wiki be enough in your opinion?

**Comment by kmcclellan** [comment]
> the ES5-releases simply means "for usage with older browsers" 

Yeah this was admittedly confusing. Some documentation about compatibility would definitely help!

> a browser without native support for `TypedArray`s is simply way too old to be used with the PDF.js library

Thanks, I suspected that was the answer. Feel free to close this 👍

**Comment by timvandermeij** [comment]
I think better information in the README might indeed help. I don't immediately see a rename making things more clear here.

Let's close this issue then; a proposal for rewording the README can be considered in a PR. Thanks!
