### ISSUE TITLE
TypeError: Cannot read property 'GlobalWorkerOptions' of undefine

### ISSUE THREAD

**Issue by CarlosNano** [mozilla/pdf.js#12643]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  87.0.4280.47
- Operating system and its version: OSX 10.15.7
- PDF.js version: 2.5.207
- Is a browser extension: No

Steps to reproduce the problem:

I'm trying to use the library using the examples (from https://mozilla.github.io/pdf.js/examples/ ) with stenciljs.

My problem is with this line: 

pdf.GlobalWorkerOptions.workerSrc =
  '//mozilla.github.io/pdf.js/build/pdf.worker.js';

TypeError: Cannot read property 'GlobalWorkerOptions' of undefine

I'm importing pdf as follow:

const pdf = window['pdfjs-dist/build/pdf'];

And in the index html adding the script:

    <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
 What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/72921935/99823413-a62ac480-2b54-11eb-8c32-ed3ca2d92e9c.png)

Any idea if I'm missing something? Thanks

**Comment by timvandermeij** [comment]
> stenciljs

This is not something we know of or maintain, so we cannot provide support for that. Given that the examples work, you're most likely running into an integration issue, but especially without any source code it's impossible to tell. I'd recommend running the examples standalone and if those work backtrack from there.

> //mozilla.github.io/pdf.js/build/

_Never_ link to this URL since it changes on every commit to master and may therefore be unstable. Fetch the resources from a CDN, see https://github.com/mozilla/pdf.js/blob/master/README.md#including-via-a-cdn, or host the files yourself.

**Comment by CarlosNano** [comment]
Thanks. 

It seems to work fine with the hello world pdf using the following:

```
pdf.GlobalWorkerOptions.workerSrc =
  'https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.worker.min.js';
```

In the html:
```
  <script src="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/2.5.207/pdf.min.js"></script>
```
