### ISSUE TITLE
After migrating from 1.6.210 to 2.5.207, existing method not working

### ISSUE THREAD

**Issue by jitangupta** [mozilla/pdf.js#12649]
Configuration:
- Web browser and its version: Chrome 85
- Operating system and its version: Windows 10
- PDF.js version: 2.5.207
- Is a browser extension: no

## Migrating from 1.6.210 to 2.5.207

Previous code
```
 var loadingTask = PDFJS.getDocument(pageSrcNormal);
loadingTask.promise.then(function (pdf) {
       getPagePdf(omniview, pdf, 1);
}, function (reason) {
     // PDF loading error
      console.error(reason);
      leaflet.spin(false);
});
```

Current Code:
```
 var loadingTask = pdfjsLib.getDocument(pageSrcNormal);
loadingTask.promise.then(function (pdf) {
       getPagePdf(omniview, pdf, 1);
}, function (reason) {
     // PDF loading error
      console.error(reason);
      leaflet.spin(false);
});
```
pageSrcNormal is URL of dotnet api, which will return the pdf file dynamically

What is the expected behavior?
Document's preview should render on screen after getting data from API

What went wrong?
The API is not getting hit 
![image](https://user-images.githubusercontent.com/11292363/99958351-3fedae00-2daf-11eb-8674-739696a86b4b.png)
Note: with previous version the method is working as expected

**Comment by Snuffleupagus** [comment]
The error message in your screen-shot clearly points out bugs in *your environment*, and not in the PDF.js library, and as mentioned in the error message you've added[1] two methods (`min` and `max`) to the `Array.prototype` in such a way that they become *enumerable*.
Having methods on built-in primitives, such as e.g. `Array`, be enumerable will lead to (strange font-related) breakage elsewhere in the PDF.js code-base, which is why the library will now refuse to load in those circumstances.

---
[1] It's also possible that you're using a JavaScript framework which is responsible for this error, however we cannot really help with that (even more so, since no *runnable* test-case was provided).
