### ISSUE TITLE
[firefox]- Printing 500 pages pdf costs 200 seconds to "prepare document for printing "

### ISSUE THREAD

**Issue by nintymiles** [mozilla/pdf.js#12667]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 83
- Operating system and its version: Mac OS 10.15.7
- PDF.js version: latest version
- Is a browser extension: no

Steps to reproduce the problem:
1. open 500pages.pdf
2. click on print button

What is the expected behavior? (add screenshot) 
The preparing document process should be less than 60 seconds (close to a local pdf editor printing function)

What went wrong? (add screenshot) It costs 200 seconds from "prepare document for printing" dialog to print console, so can I have any optimization methods?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Without this information, the issue is simply not actionable/valid and unless the PDF document is provided this issue is unfortunately INCOMPLETE.

> The preparing document process should be less than 60 seconds (close to a local pdf editor printing function)

Given that the PDF.js library is written in JavaScript, it's unfortunately not entirely reasonable to expect that its performance will be *identical* to that of a native PDF viewer.

> so can I have any optimization methods?

Most likely the main problem is the number of pages, since parsing all of them for printing simply takes time and there's no way around that. However, if you're in control of the PDF generation you may be able to improve overall performance with the ideas from https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize
