### ISSUE TITLE
SinglePageViewer API unnecessarily complex, lacks basic functionality

### ISSUE THREAD

**Issue by d01010101** [mozilla/pdf.js#12686]
I like pdfjs and find it solid, but I suppose that being focused on the standard viewer, you have neglected the development of a simple, robust API for `SinglePageViewer`.

Like a number of users, I want to have a simple bare, no-widgets component displaying a single-page PDF, with either links enabled or not. I would think that there is a method like `load(component, pdfUrl, linksEnabled, maxResolution)`. In reality, your example at https://github.com/mozilla/pdf.js/blob/master/examples/components/singlepageviewer.js has >60 lines of code which does not even tackle the maximum resolution (I believe that there is only some hard-coded max memory value instead which, if you plan canvas tiling, may make sense).

I would guess that for most casual users of your library like me, the API in question is either not completely understood or they need to learn a number of complexities of your library, which is against the principles of the separation of concerns. I guess that you do not need an explanation of problems which an unnecessarily complex API used by lot of users may give maintenance-wise. Let me just say about my own question at https://github.com/mozilla/pdf.js/issues/12683 where I said "close it", feeling like a newbie but why should I be not a pdfjs newbie if I just want the simplest bare component with a page of some PDF file?

**Comment by d01010101** [comment]
Alternatively, few more comments. It won't prevent obsoleted API (which happened already after I copied this example) but may make its usage more reliable. For a user which has no idea about your library and does not want to search around for pieces of information.

 - where to find pdfjsLib and pdfjsViewer? they do not exist after loading pdf.js and pdf_viewer.js
```
    const pdfjsLib = window['pdfjs-dist/build/pdf'];
    const pdfjsViewer = window['pdfjs-dist/web/pdf_viewer'];
```
- if I have several viewers, can some helper objects/services be shared?
- are the maps obligatory? no, you can skip everything related to them if it works for your PDF
- can the maps be found anywhere in pdfjs?
- few words about technology, everything is rasterized at the beginning to a single canvas, link service adds a text overlay.

**Comment by d01010101** [comment]
Might be, because of library size considerations, you do not want to enlarge the basic library with unnecessary API for fringe applications, and thus you just maintain external examples instead.

**Comment by Snuffleupagus** [comment]
> I would think that there is a method like `load(component, pdfUrl, linksEnabled, maxResolution)`.

While that might be useful for a *particular* case, it's hopefully obvious why something like that is completely inappropriate in the *general* case. Please note e.g. the number of options currently supported by e.g. `PDFViewer`: https://github.com/mozilla/pdf.js/blob/31b78921caf0266589c8cc26cb8be02c7ecf483f/web/base_viewer.js#L48-L84 and `PDFPageView`: https://github.com/mozilla/pdf.js/blob/31b78921caf0266589c8cc26cb8be02c7ecf483f/web/pdf_page_view.js#L34-L66

Trying to support the kind of format asked for above would simply not scale well at all, and would make it essentially impossible to add and/or change parameters.

> where to find pdfjsLib and pdfjsViewer? they do not exist after loading pdf.js and pdf_viewer.js

Following the existing examples in https://github.com/mozilla/pdf.js/tree/master/examples/components should work, but without more information/context it's impossible to help.

> if I have several viewers, can some helper objects/services be shared?

Generally speaking, no. If you do that, you'll quickly end up with confusing and inconsistent state.

> are the maps obligatory? no, you can skip everything related to them if it works for your PDF
> can the maps be found anywhere in pdfjs?

What "maps" are you actually referring to here? Source maps, CMaps, or something else entirely.

---

Given that the `load`-function asked for in https://github.com/mozilla/pdf.js/issues/12686#issue-755646677 is not a good idea (see above), and that the questions above are difficult to address without more information/context; hence I'd suggest closing this issue since there's not really an actionable bug here (as far as I can tell).

**Comment by d01010101** [comment]
The format which I suggested may be wrong, given that I had only an occasional contact with pdf.js. So, if it is really a badly informed bug, it may well deserve to be closed.

Still, I am not quite sure if using pdf.js just as a simple page element without frills is a particular case. For PNG, SVG etc. it is not a particular case, but one of the most basic cases. PDF is different, of course. But using it like that is **not particular, but absolutely normal in a number of documents formats or editors**. Some of them do or will migrate to the web eventually.

Also, given that we talk about a **convenience method for creating a simple, plain component**, I am not sure **if talking at the same time about a multitude of options and scalability is relevant**. Possibly, it was by mistake to talk about options in the same issue, instead of keeping it simple.

I would close this issue if you do not like it. Also, its clarity is not good. But let someone better informed about pdf.js decide.
