### ISSUE TITLE
Is it possible to get span details on selection of text or paragraph?

### ISSUE THREAD

**Issue by trikdas** [mozilla/pdf.js#12690]
Attach (recommended) or Link to PDF file here:
[ttt.pdf](https://github.com/mozilla/pdf.js/files/5640442/ttt.pdf)
Configuration:
Web browser and its version: Google Chrome
Version 86.0.4240.111 (Official Build) (64-bit)
Operating system and its version: Windows 10
PDF.js version: pdf.js 2.6.401

Steps to reproduce the problem:
1. Need to get span details of text/paragraph which is selected on pdf viewer
![selection](https://user-images.githubusercontent.com/73604779/101119018-68c43d80-3610-11eb-872b-e603e3505168.png)

What is the expected behavior? (add screenshot)
on-selection of text/paragraph span details of the selected text to be captured.
as shown in the screenshot 'Aaa' and 'bbb' are selected ,need to get span details of this selection.

What went wrong? (add screenshot)
unable to find a way to capture this

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: pdf.js 2.6.401

Perhaps unrelated here, but please keep in mind that it's generally recommended to use only *official* releases as found at https://github.com/mozilla/pdf.js/releases

> on-selection of text/paragraph span details of the selected text to be captured.
> as shown in the screenshot 'Aaa' and 'bbb' are selected ,need to get span details of this selection.

You might perhaps be able to use something like `window.getSelection()`. However, please note that there's no functionality in the PDF.js library (or default viewer) for this, since it's not something that's needed for the viewer.
