### ISSUE TITLE
Question about JS parsing

### ISSUE THREAD

**Issue by jabra98** [mozilla/pdf.js#12709]
Does pdf.js parse embedded JS nowadays (on PCs and mobile devices)? If so is there an option to disable it to avoid exploitation?

**Comment by Snuffleupagus** [comment]
It's not entirely clear (at least to me) if your question refers to the basic API or the default viewer here, since that matters here:
 - For the API itself, the answer is NO. There's no embedded JavaScript being executed anywhere, nor is that planned as far as I'm aware of.
 - For the default viewer, it depends on the value of the `enableScripting` option/preference.
It's currently *disabled* by default, however that may change in the future. (Please keep in mind though, that any embedded JavaScript will then be executed in a sandbox.)

**Comment by jabra98** [comment]
Sorry for the ambiguity, yes I was talking about the default viewer (I suppose this is the one implemented in the latest Firefox on PCs and mobile devices). Okay so due to the sandboxed nature of it, exploitation by malicious PDF documents are not possibe, correct?

**Comment by Snuffleupagus** [comment]
> I suppose this is the one implemented in the latest Firefox on PCs and mobile devices

Yes, with the caveat that it's currently only being used in *desktop* versions of Firefox. (I don't *think* that mobile Firefox version have built-in PDF viewing support yet, but I could be wrong of course.)

> Okay so due to the sandboxed nature of it, exploitation by malicious PDF documents are not possible, correct?

Yes, in a perfect world this should thus make things safe. (If you're really worried about security, you'll be able to disable all embedded JavaScript execution simply be setting `pdfjs.enableScripting = false` in about:config)

**Comment by jabra98** [comment]
I see, thanks. Do you know a safe alternative for mobile devices by any chance?

**Comment by timvandermeij** [comment]
Yes, for the default viewer it's behind a preference and it's currently turned off by default. Even if it's enabled, it will only run in a sandbox. Firefox mobile does not use PDF.js at the moment, but maybe it will at a later stage. For mobile, at the moment perhaps the Adobe Reader app would work, although we cannot tell what security measures it takes; you'd have to try it out to see if JS can be disabled there.
