### ISSUE TITLE
can you provie the web/viewer.js before it has been packaged?

### ISSUE THREAD

**Issue by jdljf** [mozilla/pdf.js#12713]

**Comment by Snuffleupagus** [comment]
With only a cryptic title, and no further information, this issue is INVALID since it's impossible to understand what your asking.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and make sure to read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md *before* opening an issue.
