### ISSUE TITLE
Add support for ResetForm action

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#12721]
The spec for this action:
https://www.adobe.com/content/dam/acom/en/devnet/pdf/pdfs/PDF32000_2008.pdf#G11.2111850
An example of a form using this action:
https://www2.illinois.gov/rev/forms/reg/Documents/reg-1-mr.pdf

**Comment by calixteman** [comment]
Another test case (`Cancella Dati` button):
[15ddb282-dd10-47b7-ad91-7d9b99a4b982_filled.pdf](https://github.com/mozilla/pdf.js/files/6206539/15ddb282-dd10-47b7-ad91-7d9b99a4b982_filled.pdf)

**Comment by marco-c** [comment]
The "Reset" button in the first form of this issue is actually clickable and it works when the PDF is loaded from https. It doesn't work when the PDF is saved and then opened from the disk.

The "Cancella Dati" button in the second form of his issue actually isn't clickable at all.

Maybe they are actually two different issues?
