### ISSUE TITLE
zoom in and zoom out event is not working 

### ISSUE THREAD

**Issue by sharmarajat687** [mozilla/pdf.js#12749]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by sharmarajat687** [comment]
the zoom in and zoom out event is not working 
when ever i click on the event the show the error in console 
the error is "offsetParent is not set -- cannot scroll"

**Comment by Ridho-Ilahi** [comment]
Hy

Pada tanggal Jum, 18 Des 2020 16:39, Rajat Sharma <notifications@github.com>
menulis:

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable information and will be closed as INVALID.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
