### ISSUE TITLE
Improve the viewer layer documentation

### ISSUE THREAD

**Issue by Navds** [mozilla/pdf.js#12764]
It would be straightforward to get started from the upper layer that is the viewer. Unfortunately, every tutorials and examples show basic display functionalities such as how to render a page in a canvas, how to add previous and next button, etc.
https://github.com/mozilla/pdf.js/wiki/Viewer-options is the only available resource on the viewer. There is no indication on how to customize it, like:

- How to reskin while being compatible with an upstream update ?
- How to pass request headers to the server serving the requested file ? 
- How to disable/enable such and such options ?
- How to switch from continuous scrolling to single page per view ?

**Comment by Snuffleupagus** [comment]
*Generally speaking:* Please note that the lack of proper documentation for the default viewer is *somewhat* on purpose, given http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by Navds** [comment]
Yeah, It clearly advises to **re-skin it or build upon it** but don't give enough materials on how.

**Comment by znap026** [comment]
So are you saying that viewer.js should not be used?

**Comment by GAGANsinghmsitece** [comment]
It's difficult to re-skin it as there are no docs available on how to customise its skin

**Comment by mstralka** [comment]
I agree that more documentation and examples for customizing the viewer would be extremely helpful.

For example, we want to hide the Save and Print buttons in certain situations:
![image](https://user-images.githubusercontent.com/439680/109725545-4e521f80-7b7f-11eb-8322-826917f1e2c5.png)

**Comment by anggafsahid** [comment]
I am trying to re-skin it to hide some button in toolbar with editing viewer.html file and viewer.css file. 
although I can hide some button in toolbar, but without documentation it was difficult, especially when you try to resize, change color and reposition the button.

**Comment by Snuffleupagus** [comment]
> How to reskin while being compatible with an upstream update ?

Considering that the default viewer is written *specifically* to be used as the built-in PDF Viewer in Firefox, general re-use has never been a priority and we thus need to be able to make backwards incompatible changes where that makes sense for the Firefox use-case. (The viewer components, see https://github.com/mozilla/pdf.js/tree/master/examples/components, on the other hand should not break in backwards incompatible ways when updating.)

Hence we cannot guarantee that updating the default viewer will always work, however making e.g. CSS-only changes should *reduce* the risk of breakage when updating. Another good idea is to update *frequently*, and not wait e.g. a year before doing so, since that should also limit the number of changes that you need to deal with.

Please keep in mind that the versioning in this library is based on the API (see https://github.com/mozilla/pdf.js/blob/master/src/display/api.js) and also on the viewer components (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.component.js), however the default viewer is *not* included in the versioning.

> How to pass request headers to the server serving the requested file ?

Please note the following `getDocument` option https://github.com/mozilla/pdf.js/blob/41dab8e7b6c1e2684d4afabb8f02e40a874d8e85/src/display/api.js#L134, or if you're using the default viewer please see https://github.com/mozilla/pdf.js/blob/41dab8e7b6c1e2684d4afabb8f02e40a874d8e85/web/app.js#L876-L885

> How to disable/enable such and such options ?

It's unclear exactly what "options" that's referred to here, and if it's the API or the default viewer that's relevant.
For the API itself, see e.g. https://github.com/mozilla/pdf.js/blob/41dab8e7b6c1e2684d4afabb8f02e40a874d8e85/src/display/api.js#L126-L218
For the default viewer, options can be set using either the Preferences and/or the AppOptions, please see https://github.com/mozilla/pdf.js/blob/master/web/preferences.js and https://github.com/mozilla/pdf.js/blob/master/web/app_options.js

Possibly https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage is also helpful here.

> How to switch from continuous scrolling to single page per view ?

Please see PR #14112, which is available in the latest release; see https://mozilla.github.io/pdf.js/getting_started/#download.
