### ISSUE TITLE
Show PDF from folder in Firefox

### ISSUE THREAD

**Issue by KarelSvo** [mozilla/pdf.js#12775]
Hi there
I work with a htm software, that can call various PDF files from folders (a wiring diagram program).
The wiring program works excellently on Ubuntu 18.04, Firefox 84.0, PDF.js 1.7.0.
Unfortunately not on Android 4.4, Firefox 68.6, PDF.js 1.7.0 :(
Embed PDF in browser from https works, PDF from a folder does not.
What is the cause, is there a solution?

Happy Holidays and stay healthy!

**Comment by Snuffleupagus** [comment]
> PDF.js 1.7.0.

First of all, that PDF.js version number doesn't exists. Secondly, any version from the `1.7.x` format is *many years* out-of-date and thus no longer supported; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Unfortunately not on Android 4.4, Firefox 68.6

Both of those are too old to be supported as well, *especially* Android 4.4 (which [according to Wikipedia](https://en.wikipedia.org/wiki/Android_version_history#Android_4.4_KitKat_(API_19)) was last updated in 2014).

> What is the cause, is there a solution?

Most likely the "ancient" versions, of both the platforms/browsers and the PDF.js library itself, being used. You need to update to the latest releases, since otherwise we cannot help!

---

Furthermore, as-is there's unfortunately no particularly actionable information provided here; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, for future reference, please actually fill out the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue since that simplifies things for us.

**Comment by KarelSvo** [comment]
I searched for Android PDF.js and found this page with an .xpi file version 1.7.0  https://addons.mozilla.org/en-US/firefox/addon/android-pdf-js/

**Comment by Snuffleupagus** [comment]
> I searched for Android PDF.js and found this page with an .xpi file version 1.7.0 https://addons.mozilla.org/en-US/firefox/addon/android-pdf-js/

Unfortunately that's not *in any way* associated with the PDF.js project, since it's maintained by a third-party, and consequently we cannot provide support for it; please contact its maintainer for support instead!

**Comment by KarelSvo** [comment]
What do I have to do to turn your download folder 2.5.207 into an xpi file that can be easily installed?

**Comment by Snuffleupagus** [comment]
> What do I have to do to turn your download folder 2.5.207 into an xpi file that can be easily installed?

We no longer have any build-scripts for, and thus cannot support, doing that kind of packaging in the PDF.js project.

*Once more:* Since your issue seem to actually be with the https://github.com/M-Reimer/android-pdf-js project, please direct further support questions there instead.
