### ISSUE TITLE
Can't resolve 'worker-loader'

### ISSUE THREAD

**Issue by jarvistesting** [mozilla/pdf.js#12782]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome Version 87.0.4280.88 (Official Build) (64-bit)
- Operating system and its version: Linux ubuntu 18.04
- PDF.js version: Latest version
- Is a browser extension: nope

Steps to reproduce the problem:
1. I have used create-react-app and trying to run my local but getting issue "Can't resolve 'worker-loader'".
2. I am using react-pdf-to-image "1.0.2" internaly it's using pdfjs-dist.

What is the expected behavior? (add screenshot) My local should run properly.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/39655989/103171299-1b369b80-4871-11eb-99e5-44bf3fd79744.png)
![image](https://user-images.githubusercontent.com/39655989/103171660-0dcee080-4874-11eb-941a-9e58a9bf3a0d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest version

You need to provide an *actual* version number, since "latest version" can mean any number of things and is consequently not useful.

> I have used create-react-app and trying to run my local but getting issue "Can't resolve 'worker-loader'".

Note that we no longer have a `create-react-app` example in the latest releases, hence the "latest version" claim above seems questionable here.
Furthermore, the error suggests that you haven't installed the `worker-loader` dependency, which you need to do *manually*.

> I am using react-pdf-to-image "1.0.2" internaly it's using pdfjs-dist.

We know nothing about `react-pdf-to-image` here, since it's not affiliated with the PDF.js project, and consequently this unfortunately isn't the right place to get support for it.

---

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by lk77** [comment]
Same issue here
