### ISSUE TITLE
Images are displayed as blank

### ISSUE THREAD

**Issue by prasanna734** [mozilla/pdf.js#12794]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome-latest
- Operating system and its version:
- PDF.js version:
- Is a browser extension: No

Steps to reproduce the problem:
1. once the page is loaded with pdf.js, the images are not displayed
2. shows  Warning: Image exceeded maximum allowed size and was removed
3. Is there any code to solve this problem instead of reducing resolution of image?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/76766862/103334075-2d455380-4a96-11eb-947d-b28aade5b779.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version: chrome-latest

*In general:* Note that "latest" can mean any number of things, and is thus not helpful; you must provide actual version numbers. 

Furthermore, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; as-is this issue contains no actionable information and will be closed as INVALID.

> shows  Warning: Image exceeded maximum allowed size and was removed

That *clearly* indicates some kind of custom implementation, since you've *explicitly* opted into skipping of large images by setting a `maxImageSize` when calling `getDocument; see https://github.com/mozilla/pdf.js/blob/9a779c2e9037524e6bb8557021eaea83d2eb5682/src/display/api.js#L150-L152

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
