### ISSUE TITLE
Cache changed between v2.5.207 and v2.6.347?

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#12790]
In my app I have one visible canvas. To speed up the rendering and improve the user experience I render the next page in a hidden canvas. When I render the page to the visible canvas it is displayed very fast because pdf.js caches resources and doesn't need to do everything again.

In v2.5.207 it works well. Transition between pages is fast and smooth.
In v2.6.347 rendering to the hidden canvas doesn't help. When I render the next page to the visible canvas it takes more time and the visible canvas flashes between pages.

Tested with tracemonkey.pdf, Firefox 84 and Chrome 87.

Is there a change between v2.5.207 and v2.6.347 that could cause this?

I'm installing pdfjs with npm install pdfjs-dist and npm install pdfjs-dist@next.
Is there a way to do a bisect to find the commit that changed the cache behavior? pdfjs-dist only has the tags.

**Comment by timvandermeij** [comment]
I'm not aware of such a change in the codebase. To do a bisect between versions, you can find the commit hashes for both versions at https://github.com/mozilla/pdf.js/releases, in this case between 0974d60 and 3be9c65. This can be reopened if there is in fact an issue in PDF.js, and it's not related to e.g. the custom implementation.

**Comment by Snuffleupagus** [comment]
> To speed up the rendering and improve the user experience I render the next page in a hidden canvas. When I render the page to the visible canvas it is displayed very fast because pdf.js caches resources and doesn't need to do everything again.

I might be misunderstanding this, but it sounds a bit like you pre-render the next page and then throw away its canvas once done, and then when actually changing pages you render the page yet *again*?
If that's correct, then I'd humbly suggest *not* doing that, since rendering the same page twice (rather than only once) is obviously less efficient regardless of the caching issues you seem to be having. Basically, simply switching to the pre-rendered canvas is bound to be a lot more efficient in general (also since not all resources are guaranteed to be cache-able).

Anyway, as to the issue you're seeing, I've looked at the changelog in https://github.com/mozilla/pdf.js/releases/tag/v2.6.347 and cannot immediately recall and/or see a PR that would regress main-thread caching. Generally speaking, in the last couple of releases, we should actually have *improved* (primarily worker-thread) caching of various graphics-resource a fair bit.
