### ISSUE TITLE
Some text disappeared in this PDF.

### ISSUE THREAD

**Issue by cmh1996** [mozilla/pdf.js#12823]
Attach (recommended) or Link to PDF file here:
[1.pdf.lin (1).pdf](https://github.com/mozilla/pdf.js/files/5780764/1.pdf.lin.1.pdf)

Configuration:
- Web browser and its version: FireFox 84.0 
- Operating system and its version: macOS 10.15.7
- PDF.js version: 2.7.262
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF with pdf.js.
2. Found the text of this PDF disappeared.

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/18492951/103877578-3d9da400-5110-11eb-8d84-4edd9aa1298b.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/18492951/103877735-6d4cac00-5110-11eb-9e76-7f3d9330086b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Your PDF document is *corrupt*, since one of the fonts is missing necessary data, as indicated by the errors in your screen-shot.
While we perhaps should handle the actual error better, please note that Adobe Reader (i.e. the PDF reference implementation) renders that document that same way as the PDF.js library.
