### ISSUE TITLE
Typescript types definition missing for es5 build

### ISSUE THREAD

**Issue by lanwin** [mozilla/pdf.js#12827]
The current type definition did only work if pdfjs is directly imported, but not if the es5 build is used (when used with node).

I had to add a d.ts file to make it work. But I think this should be directly included in the release.

```typescript
declare module "pdfjs-dist/es5/build/pdf.js" {
  export * from "pdfjs-dist";
}
```

**Comment by tamuratak** [comment]
I think it is an easy solution to tell users write the following:
```ts
const pdfjsLib: typeof import('pdfjs-dist') = require('pdfjs-dist/es5/build/pdf.js');
```
See [doc](https://devblogs.microsoft.com/typescript/announcing-typescript-2-9-2/#import-types) for `typeof import`.

If we want an out-of-the-box solution, it is not easy. TypeScript finds a type file `types/pdf.d.ts` for `build/pdf.js` based on the properties `main` and `types` of `pdfjs-dist/package.json`.

```json
  "license": "Apache-2.0",
  "main": "build/pdf.js",
  "name": "pdfjs-dist",
  "repository": {
    "type": "git",
    "url": "git+https://github.com/mozilla/pdfjs-dist.git"
  },
  "types": "types/pdf.d.ts",
  "version": "2.6.347"
```

Therefore, TypeScript cannot find the type file `types/pdf.d.ts` for `pdfjs-dist/es5/build/pdf.js` now. Because we cannot put multiple files to the `main` property, microsoft/TypeScript/issues/21423, we have no way to tell TypeScript the location of the type file for `pdfjs-dist/es5/build/pdf.js`.

The only solution we can have is putting a `pdf.d.ts` file in the same directory as `pdfjs-dist/es5/build/pdf.js`. The content of the `pdf.d.ts` file should be:

```ts
export * from 'pdfjs-dist'
```

**Comment by lanwin** [comment]
I think the first approach can not work when ES Modules are used cause require is not allowed there. 

My guess is that the second approach would be far better. 

Tanks for looking into this!

**Comment by Snuffleupagus** [comment]
Given that *this* particular issue seem to be mostly related to building/packaging the PDF.js library, rather than TypeScript as such, I've submitted a small patch following the suggestion in https://github.com/mozilla/pdf.js/issues/12827#issuecomment-756471707. @tamuratak Thanks for your help!

---

@lanwin Please keep in mind that the PDF.js library is still a *JavaScript* project; hence it's generally speaking going up to the TypeScript users *themselves* to help maintain/improve the definitions where necessary :-)
