### ISSUE TITLE
Underscore too thin when the document is zoomed in

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#12868]
This is a regression from #12864. The underscore is now too thin when the document is zoomed in.

URL: https://github.com/mozilla/pdf.js/files/2321540/issue6127.pdf
PDF.js 2.7.526: https://i.imgur.com/T4mIpct.png
PDF.js 2.7.510: https://i.imgur.com/nbwEpGT.png
Adobe Acrobat Reader DC 2020.013.20074: https://i.imgur.com/wDFBf3R.png

The screenshots were taken at 400% zoom.

**Comment by calixteman** [comment]
The problem is the following: at 400% the transformation matrix (in the canvas: current pdf transform + zoom) is `[ 0.6728517413139343, 0, 0, -5.3331708908081055]` and the linewidth is `1.158` so when matrix is apply to linewidth we get a rectangle pixel `0.78x6.17` this is why it's replaced by a 1px linewidth.
According to the screenshot with Acrobat, I've the impress that zoom scale is not taken into account when fixing the linewidth, I mean only the transformation in the pdf is taken into account, linewidth is then fixed and finally the zoom is applied.
@Snuffleupagus, @timvandermeij is there a way to get the zoom factor when drawing in the canvas ?

**Comment by calixteman** [comment]
This info is available in `viewport.transform` in `canvas.js`.
