### ISSUE TITLE
gulp generic - Web worker Build Issue

### ISSUE THREAD

**Issue by Faizranas** [mozilla/pdf.js#12860]
[Configuration:
- Chrome 84
- Windows 7
- pdf.js-2.6.347

I am using 2.6.3 PDF JS source code to make a custom build. 
**gulp server** command is working fine without any issue
**gulp generic** command is also creating a build without any error but It is throwing "_Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at_"  when we run it in Chrome. I don't see any **pdf.worker.js** in a build folder. There is only pdf.js and its map file are there.

Why **pdf.worker.js** is missing and not created when I run **gulp generic**. Please let's know what is missing here. This command should automatically create everything as per our understanding. Let's know If we have to do anything manually to create a worker file.

![pdf](https://user-images.githubusercontent.com/6050477/104570952-886f6c80-5678-11eb-9281-a87af6e9b4d3.PNG)

**Comment by Snuffleupagus** [comment]
Your screen-shot clearly shows that you haven't actually setup things correctly, since the error would suggest that Git isn't installed locally; note how the version number isn't correct and that the build number is completely missing.

If I were to guess, since this issue is a bit light on the details, you downloaded the release from https://github.com/mozilla/pdf.js/releases and *then* tried to create a custom build. If that's the case, this explains the problem your facing since you *must* follow https://github.com/mozilla/pdf.js#getting-the-code since otherwise the build scripts simply won't work!

**Comment by Faizranas** [comment]
Hello Snuffleupagus,
Thanks for your response. I cloned the code from https://github.com/mozilla/pdf.js#getting-the-code as suggested by you. Now, the code is throwing error and not working in dev & prod both environments. As I informed you earlier that we are using 
Node 11.0.0, Chrome 84 and Windows7 for our development. Please help us to resolve this problem so we can move further and look into customization.

We are getting following errors when we run gulp server command:
Navigated to http://localhost:8888/web/viewer.html
app.js:1765 Uncaught (in promise) SyntaxError: Unexpected token '??=' in app.js
we found below syntax in app.js 
this._contentLength ??= contentLength; // See `getDownloadInfo`-call above.
when I removed ?? then we got below error in ui_utils js.
Uncaught (in promise) SyntaxError: Unexpected token '||=' in ui_utils.js:866
(externalListeners ||= []).push(listener);

We don't know understand why this invalid syntax is there in your code-lab. Please help us to resolve it.
please see the screenshot below
![dev](https://user-images.githubusercontent.com/6050477/104807332-365b5200-5804-11eb-91da-06d80507a5a2.PNG)

We are getting following errors when we run gulp generic command:
same pdf worker error is coming
Uncaught (in promise) Error: Setting up fake worker failed: "Cannot load script at: http://localhost:8000/build/pdf.worker.js".
    at api.js:2047

We don't see pdf.worker.js file in build folder.
build folder conatins only pdf.js and pdf.sandbox
please see the screen shot below.
![prod](https://user-images.githubusercontent.com/6050477/104807361-876b4600-5804-11eb-8298-a74f28ad8b60.PNG)

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum, and generally speaking the people that you interact with here are *unpaid* volunteers!
Furthermore, you need to ensure that whenever you open an issue it's both complete with all of the necessary information and also that it's *easy* to follow.

> We are getting following errors when we run gulp server command:
> Navigated to http://localhost:8888/web/viewer.html
> app.js:1765 Uncaught (in promise) SyntaxError: Unexpected token '??=' in app.js

This suggests that the browser you're using is too old for *development* purposes, since only the latest ones are supported. The error clearly points to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment#browser_compatibility being the issue so you need to update your browser.

> We don't know understand why this invalid syntax is there in your code-lab.

As mentioned, the syntax is most certainly valid however your browser is too old. Furthermore, according to https://en.wikipedia.org/wiki/Google_Chrome_version_history, Chrome 84 is not even supported any longer.
There's also potentially an issue with your Node.js version, since https://nodejs.org/en/ lists the current LTS release as `14.15.4` whereas your version is quite a bit older; please keep in mind that the PDF.js project cannot support older Node.js versions. 

> We are getting following errors when we run gulp generic command:

For older browsers, you'll need to use `gulp generic-es5` instead to get a working build.

> We don't see pdf.worker.js file in build folder.
> build folder conatins only pdf.js and pdf.sandbox
> please see the screen shot below.

This honestly doesn't make sense, since if the build scripts were *generally* broken that'd would have been noticed/fixed. More likely, as already mentioned previously, you've still not setup everything necessary for building PDF.js locally, however it's *complete impossible* for anyone to debug things like this with nothing more than only a screen-shot.

**Comment by Faizranas** [comment]
Thanks a lot Snuffleupagus for your quick response and suggestions. Appreciate for your time.
It may be some setup issues at our end on Windows 7. I am still struggling to resolve it. 
Thanks
