### ISSUE TITLE
Css error

### ISSUE THREAD

**Issue by abbassss** [mozilla/pdf.js#12877]
I use Dansoftowner "pdfviewerfx" to work and manipulate pdf in my javafx desktop software. But I got alot of error in Css file probably because of verison, I fix most of them but @-webkit-keyframes in css has "missing EOF at" error and doesn't fix. And probably this error cause my other problem  which is exception in run time when I scroll fast or resize window. Do you have Any idea how can I handle that?

**Comment by Snuffleupagus** [comment]
> I use Dansoftowner "pdfviewerfx"

We have no idea what that is, since that's not at all related to the PDF.js project; hence it's *really* not at all clear why this issue was opened *here*.
Furthermore, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable/valid information and will be closed as INVALID.

**Comment by abbassss** [comment]
Ok, thanks
