### ISSUE TITLE
Integration with angular 8

### ISSUE THREAD

**Issue by glalwani2** [mozilla/pdf.js#12889]
Can someone point me to a working example with angular 8? I am having a hard time integrating it with the available documentation.

**Comment by Snuffleupagus** [comment]
Unfortunately the (core) PDF.js contributors don't know Angular, and as such we unfortunately cannot help.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable provided here.
