### ISSUE TITLE
Installed font is not being used to display the text

### ISSUE THREAD

**Issue by lostincomputer** [mozilla/pdf.js#12882]
[PDF file](https://github.com/mozilla/pdf.js/files/5846352/font-not-embedded.pdf) 

### Configuration:
- Web browser and its version: Firefox 84.0.2
- Operating system and its version: Windows 10.0.19041

### Steps to reproduce the problem:
1. Install [Indie Flower](https://fonts.google.com/specimen/Indie+Flower) for all users (Right-click the font then select "Install for all users")
2. Open the [PDF](https://github.com/mozilla/pdf.js/files/5846352/font-not-embedded.pdf) in Firefox. The text in this PDF is using the Indie Flower font.

### What is the expected behavior?
Viewer should use Indie Flower to display the text. This is the behavior of Adobe Acrobat Reader, Chrome, and Edge.

Expected
![expected](https://user-images.githubusercontent.com/5906698/105270408-95510a80-5bfa-11eb-9e13-fc5eb1424e35.jpg)

Actual
![actual](https://user-images.githubusercontent.com/5906698/105270418-9a15be80-5bfa-11eb-97d3-c8c35f8cc207.jpg)

What went wrong?
Viewer doesn't use the installed font

**Comment by Snuffleupagus** [comment]
First of all, your document violates the PDF specification, since all non-standard fonts must be embedded and otherwise you are simply *not* guaranteed that text rendering works correctly across different platforms and PDF readers (note how PDF is short for *Portable* Document Format).
Secondly, for security reasons, a web-application (which is what PDF.js is) can't just load locally available font data in a way that would be necessary for something like this to work.

All-in-all, please actually *embed* all fonts in your PDF documents; there's unfortunately nothing that we can do about this here.

**Comment by lostincomputer** [comment]
Thanks for your reply.

1. We are aware that it's not guaranteed that text rendering will work correctly (even though I think that it's a bad idea 99% of the time).
2. Chrome's PDF viewer, Edge's PDF viewer, and Google Drive's PDF viewer somehow is fine with loading local fonts but PDF.js doesn't want to. Why do they allow it? Are they less secure that PDF.js?

**Comment by dhufnagel** [comment]
I think as @Snuffleupagus pointed out, PDF.js is a web-application which cannot access the locally installed fonts. It is simply not possible. The mentioned Viewers (mainly pdfium) are embedded into the browser, so they can access local storage and locally installed fonts. I am no PDF.js expert, but this seems to be the obvious difference.

**Comment by timvandermeij** [comment]
Yes, it's exactly what is described above. Embedding fonts is simply necessary all the time, otherwise the file is violating the specification and rendering correctness cannot be guaranteed since web applications cannot access local fonts.
