### ISSUE TITLE
Can't see "≼" 

### ISSUE THREAD

**Issue by aaafgcfg** [mozilla/pdf.js#12880]
Attach (recommended) or Link to PDF file here:

[Diskretnaya_matematika.pdf](https://github.com/mozilla/pdf.js/files/5843587/Diskretnaya_matematika.pdf)

Configuration:
- Web browser and its version: mozilla firefox 82.0.2 (64-битный)
- Operating system and its version: Windows 10 Home 1909 
- PDF.js version don't know
- Is a browser extension: yes

Steps to reproduce the problem:
1. open file
2. open 46-47 page

What is the expected behavior? (add screenshot) I see square instead of ≼, but can copy and past and see it

What went wrong? (add screenshot)
![изображение](https://user-images.githubusercontent.com/40723997/105199687-1606fc80-5b50-11eb-8d46-aac4e6b0fb64.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
It looks the same in both Adobe Reader (i.e. the PDF reference implementation) and in PDFium in Google Chrome, hence this suggests a bug in the PDF file *itself* rather than the PDF.js library.

---

![reader](https://user-images.githubusercontent.com/2692120/105203472-6d52a000-5b43-11eb-9253-df11a8307193.png)

---

![chrome](https://user-images.githubusercontent.com/2692120/105203810-d1756400-5b43-11eb-8c4b-99e4005aaa17.png)
