### ISSUE TITLE
Further modularize the pdf.js npm package

### ISSUE THREAD

**Issue by rondonjon** [mozilla/pdf.js#12900]
Given that pdf.js was once built as a PDF rendering library for Firefox and bundled with the application, I understand that bundle size was never a top priority. On the other hand, pdf.js is still (and maybe more than ever) the first choice for developers who work on web applications that need to process or render PDF documents in some way. There is a [myriad](https://stackoverflow.com/questions/44840859/pdf-js-worker-bundled-with-a-hashed-name-with-webpack) of [questions](https://stackoverflow.com/questions/65815717/webpack-chunks-are-not-splitting-properly/65862503#65862503) on [StackOverflow](https://stackoverflow.com/questions/43136934/how-to-render-pdf-file-with-pdfjs-gulp-and-webpack) around [how](https://stackoverflow.com/questions/58099138/getting-failed-to-construct-worker-with-js-worker-file-located-on-other-domain) to [bundle](https://stackoverflow.com/questions/48323206/webpack-how-to-combine-0-bundle-with-main-bundle-pdfjs) the [huge](https://stackoverflow.com/questions/62278039/externalize-pdf-js-in-an-npm-module-with-webpack) pdfjs [CommonJS](https://stackoverflow.com/questions/53723039/unable-to-specify-custom-path-for-pdf-worker-js-in-pdfjs)  modules with applications.

@robrez suggested to deploy at least tree-shakeable ES modules along with the CJS modules in 2017 (#10317), but the ticket has received little attention despite 33 thumb-ups. There is a module called [@bundled-es-modules/pdfjs-dist](https://www.npmjs.com/package/@bundled-es-modules/pdfjs-dist) on npm that claims to "bundle and expose" pdfjs as an ES module, but I think they're really only *wrapping* the [pre-built pdf.js library](https://github.com/bundled-es-modules/pdfjs-dist/blob/master/build/pdf.js) (which is still only default-exporting and relying on that built-in `require()`), i.e. no tree-shaking advantage over the original library.

I spent many hours browsing the source code of pdf.js, and my greatest concerns with regard to reducing the bundle size are:

 - the highly generic API which even abstracts the different types of input sources from the caller
 - the hardcoded worker module resolution
 - the runtime evaluation of the `PDFJSDev.*` configuration variables

As an application developer, I probably don't need or want a PDF library to handle input abstraction (including different buffer formats, downloading from [network streams](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/display/network.js#L216), [node.js integration](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/display/node_stream.js#L57), etc.) for me. I would probably prefer direct access to the underlying processor and provide my PDF data directly in its single, preferred buffer format. That, together with working tree-shaking, would probably already remove a big part from the resulting bundle.

The worker module resolution is a similar case. The published version of the library relies on a hardcoded (yet [dynamic](https://github.com/mozilla/pdfjs-dist/blob/master/es5/build/pdf.js#L13618)) `require()` which bundlers cannot replace with their own module resolution due to the sheer [number of evaluated options](https://github.com/mozilla/pdfjs-dist/blob/master/es5/build/pdf.js#L13563). Again, I think this should better be handled outside the library, by the caller, who knows better about the (single, actual) environment.

And lastly, the whole `PDFJSDev` variable system could contribute to smaller bundle sizes if only it would qualify for build-time evaluation and dead code removal. Maybe I am missing something, but I have a feeling that the configuration (which is currently an `object` and runtime-processed with helpers like [`.test()`](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/pdf.js#L80) and [`.eval()`](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/pdf.js#L61) on top) could just as well be replaced with something [more common](https://webpack.js.org/plugins/define-plugin/#usage) like `process.env` variables, which bundlers like webpack or rollup would then evaluate earlier, at build time, so that unused code could be identified and removed from the bundle.

I think this whole topic deserves more attention than it is currently receiving. I would be willing to contribute a fair share, but it would need more volunteers, and contact to somebody who is more familiar with the code would surely speed things up.

**Comment by timvandermeij** [comment]
I think the problem so far has been that most contributors work on the library itself and are not too familiar with the myriad of bundling tools. In the beginning we supported multiple bundling tools that contributors helped to implement, but this became complex quite soon, so we simplified this in order for it to be maintainable for us. I think we're all open to suggestions for improved bundling, but we rely on the community here to provide us with feedback and patches since this isn't something we work with often. We're happy to review any patches to improve the current situation, but we do want to focus on maintainability as well.

**Comment by Snuffleupagus** [comment]
> Given that pdf.js was once built as a PDF rendering library for Firefox and bundled with the application,

Well, please note that this is *still* the main reason for this library to exist :-)

As mentioned in https://github.com/mozilla/pdf.js/issues/12900#issuecomment-766397559, over the last few years we've purposely removed a lot of overall complexity related to bundling since that's allowed quite a bit of clean-up/simplification of old code.

>  the highly generic API which even abstracts the different types of input sources from the caller

Note that having *one* unified API-surface *significantly* simplifies both maintenance *and* support, not to mention that by *not* providing direct access to "lower"-level code we can much more easily make changes and implement new features.
Basically, we *really* want to avoid a situation where a significant portion of the underlying code is part of the *official* API-surface.

> the hardcoded worker module resolution
> [...]
> The worker module resolution is a similar case. The published version of the library relies on a hardcoded (yet [dynamic](https://github.com/mozilla/pdfjs-dist/blob/master/es5/build/pdf.js#L13618)) `require()`

Note that this part in *only* relevant for Node.js environments, where Web Workers aren't available...

> which bundlers cannot replace with their own module resolution due to the sheer [number of evaluated options](https://github.com/mozilla/pdfjs-dist/blob/master/es5/build/pdf.js#L13563).

... for every other use-case, i.e. in browsers, note that you're not supposed to load the `pdf.worker.js` file manually since that will lead to *very poor* performance (since all parsing should run in a worker-thread).
Hence you should either use the `workerSrc` option to point its location, or use the `workerPort` option (see e.g. the [Webpack use case](https://github.com/mozilla/pdfjs-dist/blob/master/webpack.js) in pdfjs-dist), or even provide your own `PDFWorker`-instance when calling `getDocument` (note [the JSDocs here](https://github.com/mozilla/pdf.js/blob/6249ef517d3aaacc9aa6c9e1f5377acfaa4bc2a7/src/display/api.js#L131-L132)).

> the runtime evaluation of the `PDFJSDev.*` configuration variables
> [...]
>  Maybe I am missing something, but I have a feeling that the configuration (which is currently an `object` and runtime-processed with helpers like [`.test()`](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/pdf.js#L80) and [`.eval()`](https://github.com/mozilla/pdf.js/blob/699d65eb1c34271e6fc9bd7d64fee433c57b01bb/src/pdf.js#L61) on top) could just as well be replaced with something

Huh, but those are evaluated when the library is *built* rather than at runtime!?

---

While you can obviously always create your own build of the PDF.js library, where you remove e.g. the network-code that you don't need, I'm a bit worried that trying to *officially* support such a thing in our builds could quickly lead to a very high maintainable/support-burden for the few regular PDF.js contributors.

**Comment by timvandermeij** [comment]
I'm going to close this issue since there are currently no actionable points in here. Hopefully it does shed some light on the current situation and in which areas we will review contributions. Thanks.

**Comment by yang1978u** [comment]
this is a good idea
