### ISSUE TITLE
es5/build/pdf.worker.js has arrow syntax in 2.7.x

### ISSUE THREAD

**Issue by kevinbeal** [mozilla/pdf.js#12906]
Configuration:
- PDF.js version: 2.7.x

Steps to reproduce the problem:
1. Got here: https://raw.githubusercontent.com/mozilla/pdfjs-dist/master/es5/build/pdf.worker.js
2. See that arrow function syntax is used throughout.

What is the expected behavior? (add screenshot)
ES5 syntax to be used instead

What went wrong? (add screenshot)
Arrow functions present.
![image](https://user-images.githubusercontent.com/855252/105740891-7e5a3300-5eee-11eb-9085-f89b80f406c4.png)

**Comment by Snuffleupagus** [comment]
> See that arrow function syntax is used throughout.

Browsers and/or environments without array function support is now too old to be supported in PDF.js, regardless of build type; please note the compatibility information at https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Arrow_functions#browser_compatibility

> ES5 syntax to be used instead

This is probably a case of a somewhat misleading naming convention, on the PDF.js side, since the `es5`-releases simply means "for usage with older browsers/environments" and nothing else at this point in time; note in particular that e.g. IE 11 is now *explicitly unsupported*.

Unfortunately naming things is a surprisingly difficult problem in general, and I don't know if we can change the `es5`-part of the build-names to something else (and if so what to use instead?).

**Comment by kevinbeal** [comment]
> This is probably a case of a somewhat misleading naming convention, on the PDF.js side, since the `es5`-releases simply means "for usage with older browsers/environments" and nothing else at this point in time; note in particular that e.g. IE 11 is now _explicitly unsupported_.

Understood. I'll just have to use an older version then. Thank you for explaining.

> Unfortunately naming things is a surprisingly difficult problem in general, and I don't know if we can change the `es5`-part of the build-names to something else (and if so what to use instead?).

I agree that naming things is difficult.
