### ISSUE TITLE
Gain access full control of functionalities/services of the library when using built-in web viewer

### ISSUE THREAD

**Issue by ishanuda** [mozilla/pdf.js#12913]
Hi,

I would like to know the possibility/ limitations or any existing example of accessing the underlying pdfjsLib functionalities/ related services to work with (e.g. set the `docBaseUrl`) or to read the PDF document metadata (e.g. `getJavaScript()` etc.) when using the built-in [web viewer](https://mozilla.github.io/pdf.js/web/viewer.html)?

Thank you very much

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum, and that issues must contain all of the necessary information to be easily actionable in order to be valid.

The following section from the FAQ, https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, seem relevant here:
> The viewer can be started without any PDF loaded by setting the defaultUrl app option to an empty string or by using the ?file= query string without any location specified. Use PDFViewerApplication.open(file) to load the PDF file later.

Hence you can provide custom arguments when opening your document, see the JSDocs in https://github.com/mozilla/pdf.js/blob/465697eb10558d5c440ed058b292f588bcb2f8e8/web/app.js#L875-L884

> read the PDF document metadata (e.g. `getJavaScript()` etc.)

Huh; the metadata is fetched using the following method, and generally speaking it'd probably be a good idea to familiarize yourself with the code in https://github.com/mozilla/pdf.js/blob/master/web/app.js if you want to implement something custom.
https://github.com/mozilla/pdf.js/blob/465697eb10558d5c440ed058b292f588bcb2f8e8/src/display/api.js#L808-L817
