### ISSUE TITLE
PDF file is not rendering using WKWebview

### ISSUE THREAD

**Issue by SravanPeddi** [mozilla/pdf.js#12923]
Attach (recommended) or Link to PDF file here:
With WKWebview it is showing empty viewer not pdf file. Can you please help.
![Simulator Screen Shot - iPhone 11 Pro Max - 2021-01-27 at 22 34 04](https://user-images.githubusercontent.com/13622491/106026425-d01ddb80-60ef-11eb-92d9-eabca35c6ec5.png)

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, and not a support forum, and that this issue is missing *every* single piece of information necessary to be actionable!

Furthermore, the attached screen-shot clearly shows an old and no longer supported version of the default viewer.

When opening an issue, you must provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
