### ISSUE TITLE
getTextContent strings returning more than single characters

### ISSUE THREAD

**Issue by mckiernantim** [mozilla/pdf.js#12934]
Attach (recommended) or Link to PDF file here:
[G59.pdf](https://github.com/mozilla/pdf.js/files/5898443/G59.pdf)

Configuration:
- Web browser and its version:
- CHROME
- Version 88.0.4324.96 (Official Build) (x86_64)
- Operating system and its version:
- OS Catalina 10.15.7
- PDF.js version:2.6.3 es5 version
- Is a browser extension:

Steps to reproduce the problem:
1. Scanned over 200 pages of similar documents with same result
2.

What is the expected behavior? (add screenshot)

Majority of my getTextContent returns single character string - I'm trying to understand why some calls are returning _multiple characters str values_
output of getTextContent 99% of the time
<img width="861" alt="Screen Shot 2021-01-30 at 1 40 53 PM" src="https://user-images.githubusercontent.com/38140787/106365597-a1c51980-6304-11eb-81b1-6462fdd62035.png">

What went wrong? (add screenshot)
see index 497 - 
<img width="870" alt="Screen Shot 2021-01-30 at 1 51 09 PM" src="https://user-images.githubusercontent.com/38140787/106365617-be615180-6304-11eb-85df-d9de2e49cd86.png">
also happening with page-numbers.
<img width="754" alt="Screen Shot 2021-01-30 at 1 53 11 PM" src="https://user-images.githubusercontent.com/38140787/106365676-07190a80-6305-11eb-9070-11d0f6a9c0e4.png">
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
example of page - green underlines do not register as single characters.
[G59.pdf](https://github.com/mozilla/pdf.js/files/5898560/G59.pdf)

**Comment by Snuffleupagus** [comment]
In order to improve text-selection, which is the main reason for `getTextContent` to exist, we'll *attempt* to concatenate individual glyphs into (ideally) full lines of text. However, this depends on a number of heuristics (since it's unfortunately a somewhat difficult topic) which for some PDF documents doesn't always do a great job (as is the case for your document).

If you want to disable *all* concatenation of text, as returned by `getTextContent`, the you can use the `disableCombineTextItems` as described in the JSDocs: https://github.com/mozilla/pdf.js/blob/59f938d073333cd6ed0d9ee77cf2037e3dade53f/src/display/api.js#L950-L958

**Comment by mckiernantim** [comment]
Amaze. For my sake its probably better that the text is not concatenated but this solves my issue greatly thanks.  Any thoughts on as to why these glyphs don't register as concatenated text?  May help me down the road to keep an eye out.
