### ISSUE TITLE
Viewer: Password secured PDF focussing issue

### ISSUE THREAD

**Issue by SoftCreatR** [mozilla/pdf.js#12951]
Tested in latest Chrome and FF:

If you have multiple PDF files embedded as Iframe (via viewer.html) and at least one of them is password protected, the browser automatically jumps to the (first) iframe that shows the password prompt.

Imho, the iframe shouldn't modify the behavior of it's parent in any way.

See https://support.softcreatr.com/thread/4360-pdf-test/ for a demo.

**Comment by Snuffleupagus** [comment]
> the browser automatically jumps to the (first) iframe that shows the password prompt.

But wouldn't that suggest a *browser* issue, rather than a PDF.js one, in that case?

Furthermore, the PDF.js default viewer uses a *custom* password prompt and not [`window.prompt()`](https://developer.mozilla.org/en-US/docs/Web/API/Window/prompt) or similar.

> See https://support.softcreatr.com/thread/4360-pdf-test/ for a demo.

Huh, but none of those PDF documents ask for a password when opened!?

---

Finally, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by SoftCreatR** [comment]
> But wouldn't that suggest a browser issue, rather than a PDF.js one, in that case?

Since this happens in all (tested) Browsers... Dunno.

> Furthermore, the PDF.js default viewer uses a custom password prompt and not window.prompt() or similar.

I'm aware of that. That's why I think, that this is an issue with this lib.

> Huh, but none of those PDF documents ask for a password when opened!?

Restored it 😄 

> Finally, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):

That's planned. I'Ve just started working with it.

**Comment by Snuffleupagus** [comment]
Apparently an `iframe` will be automatically scrolled into view, by the browser, if an element within it is focused.

Looking at the code in question, see https://github.com/mozilla/pdf.js/blob/86a4ba55c56f735e51e29a7aa368bcdcce9d8a23/web/password_prompt.js#L70, this is thus expected behaviour since forcing users to *manually* focus the password-input doesn't seem like a great UX in general; please keep in mind that the default viewer exists *primarily* for the Firefox use-case.

I'm not sure if we want to change this, in PDF.js, for the embedded use-case specifically; however you can always change it in your own implementation.

---

*Also, for future reference:* Please save everyone's time by actually filling out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.

**Comment by SoftCreatR** [comment]
Thank you for the hint. For our case, I've commented out the focus line and it works as expected now.

**Comment by timvandermeij** [comment]
The pull request above fixed the issue that was reported here by not focusing the password input field on load if we're embedded in an iFrame.

**Comment by SoftCreatR** [comment]
Thank you :)
