### ISSUE TITLE
Converting pdf to html in pure javascript

### ISSUE THREAD

**Issue by kertom** [mozilla/pdf.js#12958]
I was wondering if there is a way to convert a pdf document to html in pure javascript?

**Comment by Snuffleupagus** [comment]
This is first an foremost a *bug tracker* rather than a support forum, hence please make sure that any issue you open is actionable; you should always provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

Furthermore, as explained in the [README](https://github.com/mozilla/pdf.js#pdfjs-):
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.

> I was wondering if there is a way to convert a pdf document to html in pure javascript?

The `pdf2svg` example is perhaps useful here, see https://github.com/mozilla/pdf.js/tree/master/examples/node, however it's impossible to know given the overall lack of information here.

**Comment by kertom** [comment]
I apologize for not following the rules of the forum.I completely understand,that what i am asking is not a bug. However ,could you tell me where i could ask it,please? 
Thank you very much for your information about turning pdf into an image. Unfortunately ,in my case , what i need is and editable version of the document,because i would like to put it into an editor where the user will be able to edit the text.Also i would like to extract the tables and display them to the editor in such a way  ,that the user can edit the text that exists on them.
Once again i apologize.I would really appreciate ,if you could give me further information,please?
I am looking forward to hearing from you.
Thank you in advance.

**Comment by Snuffleupagus** [comment]
> Thank you very much for your information about turning pdf into an image.

Huh; I specifically mentioned the `pdf2svg` example does *not* produce an image, but rather an SVG file.

> Unfortunately ,in my case , what i need is and editable version of the document,

As explained in the README, which I also quoted above, this library simply isn't intended for that kind of use-case.

**Comment by kertom** [comment]
Thank you very much for your information.I see now in the pdf2svg approach,that it runs only in the node environment and not on the client/vanilla javascript. Is it like that,please? The thing is that i am working on the client. Is there another approach for my case ,please? 
Thank you in advance.
