### ISSUE TITLE
Slow rendering in Chrome

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#12968]
Attach (recommended) or Link to PDF file here:
[slow.pdf](https://github.com/mozilla/pdf.js/files/5939389/slow.pdf)

Configuration:
- Web browser and its version: Chrome 88.0.4324.150 - slow. Firefox 85.0 - fast.
- Operating system and its version: Ubuntu 20.04
- PDF.js version: hosted default viewer
- Is a browser extension: No

The PDF has only one object (I think). It takes several long seconds to load on Chrome, CPU reach almost 100% and the browser is unresponsive. Firefox is much faster and CPU is under 30%.

**Comment by Snuffleupagus** [comment]
> The PDF has only one object (I think).

Not quite, that PDF document contains *no* `/XObject`s at all. In fact, the document actually consists of nothing but normal path rendering operators.

> Web browser and its version: Chrome 88.0.4324.150 - slow. Firefox 85.0 - fast.

Given that it works well in Firefox, which is the primary reason for this library existing in the first place, it seems really quite unlikely that we'd try and optimize for Google Chrome here (since that could risk regressing performance in Firefox).

**Comment by benbro** [comment]
Rendering is fast in Chrome 89.0.4389.72.

For reference, the PDF was created from a [canva template](https://www.canva.com/templates/EAD40XECjoY-blue-farm-animals-education-zoom-background/).
