### ISSUE TITLE
PageViewport no longer accessible

### ISSUE THREAD

**Issue by ElModdy** [mozilla/pdf.js#12980]
**Link to PDF file here:**
https://github.com/ElModdy/public-resources/blob/main/algebra.pdf

**Configuration:**
- Web browser and its version: Google Chrome 84.0.4147.89
- Operating system and its version: Arch Linux
- PDF.js version: latest
- Is a browser extension: no

**What I would like to do**
I would like to render only a portion of the pdf and from [this tutorial](https://www.integratingstuff.com/2014/09/14/displaying-a-part-of-a-pdf-page-and-reading-acroforms-with-pdf-js/) seems like it was possible in older version.

**What went wrong**
My problem is that `PageViewport` is no longer accessible from `pdfjsLib`

**Comment by Snuffleupagus** [comment]
> PDF.js version: latest

*For future reference:* Please remember to provide an actual version *number*, since "latest" isn't entirely clear. (E.g. do you mean the latest *stable* release, the latest *beta* release, the `master`-branch, or something else.)

> I would like to render only a portion of the pdf and from [this tutorial](https://www.integratingstuff.com/2014/09/14/displaying-a-part-of-a-pdf-page-and-reading-acroforms-with-pdf-js/) seems like it was possible in older version.

First of all, please keep in mind that that example is *not* an official one, which means that there's no guarantee that it ever illustrated best practices. Secondly, that example is really old (from 2014 apparently) and the PDF.js code-base has changed quite a bit since then.

> My problem is that `PageViewport` is no longer accessible from `pdfjsLib`

Please note that `PageViewport` was never purposely exposed in the official API, but it was rather an artifact of the old build system.

The correct way to obtain a `PageViewport`-instance is by calling the `PDFPageProxy.getViewport` method, which takes a number of parameters that allows you to customize the effective viewport; please see:
https://github.com/mozilla/pdf.js/blob/3787bd41ef861c8c00ebd987241e6cc89708aa5f/src/display/api.js#L1100-L1120
and 
https://github.com/mozilla/pdf.js/blob/3787bd41ef861c8c00ebd987241e6cc89708aa5f/src/display/api.js#L935-L948

**Comment by ElModdy** [comment]
Thank you !

**Comment by ElModdy** [comment]
I still haven't figured out how to solve the problem.
I am a beginner so I apologize for any errors.
That's what I've tried:

**SOLUTION 1**

**index.html**
```html
<!DOCTYPE html>
<html>
<body>
  <canvas id="the-canvas"></canvas>
  <script src="//mozilla.github.io/pdf.js/build/pdf.js"></script>
  <script>
    console.log(pdfjsLib.PDFPageProxy)  //undefined
    console.log(PDFPageProxy)  //undefined
  </script>
</body>
</html>
```
**Problem:** Returns `undefined`

**SOLUTION 2 ( Typescript + webpack )**
```javascript
import { PDFPageProxy } from 'pdfjs-dist';

PDFPageProxy.getViewport()
```
**Problem:** Returns this error: `'PDFPageProxy' only refers to a type, but is being used as a value here.`.
It seems like `PDFPageProxy` is an interface but how can I call a function on an interface?

**Comment by Snuffleupagus** [comment]
Please refer to the *official examples*, see e.g. https://mozilla.github.io/pdf.js/examples/ and https://github.com/mozilla/pdf.js/tree/master/examples/

Furthermore, since this is first and foremost a *bug tracker*, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
