### ISSUE TITLE
Unable to access PDF fonts

### ISSUE THREAD

**Issue by Leone25** [mozilla/pdf.js#13002]
Configuration:
- Web browser and its version: edge
- Operating system and its version: windows 10
- PDF.js version: 2.6.347 (display)

Hello,
i'm trying to manually access the fonts embedded in the PDF to then use to make a custom text overlay.
So far i have been able to render to canvas and get all the text pieces, but i'm unable to access the fonts.

What I've tried is having the `page` object => `commonObjs` => `get(the key of one of this fonts)` => trying to run the `createFontFaceRule()` function on the result but i seem always receive `null` because the `data` key of the font face is always empty. Why is that? how do i fix it?

thank you in advance

Rico

**Comment by Snuffleupagus** [comment]
> I'm trying to manually access the fonts embedded in the PDF to then use to make a custom text overlay.

Please note that this isn't generally recommended, since the PDF specification uses two different formats for rendering vs text-selection (which PDF.js follows), and that doing this is *not* guaranteed to provide correct and/or even useful results in general[1].

> [...] but I seem always receive `null` because the `data` key of the font face is always empty.

That's done in order to save memory, since we don't need the font data (on the main-thread) after it's been attached to the document; please see PR #11844.
While you *can* disable that with the `fontExtraProperties` parameter, see below, as already explained this *really* isn't recommended: https://github.com/mozilla/pdf.js/blob/3d80c21a8e5583c0594b2d5e039f3eab65e09975/src/display/api.js#L160-L164

---
[1] For example, with something as simple as ligatures there's no guarantee that a font actually contains the *individual* glyphs.

**Comment by Leone25** [comment]
ty it seems like it was what i was looking for, will do a bit of exploration
