### ISSUE TITLE
Duplicated shadow text when highlighting

### ISSUE THREAD

**Issue by Akaban** [mozilla/pdf.js#13016]
**Description**

When I highlight any text on the rendered PDF the text is duplicated all over the highlighting, making it unreadable. Since this does not happen on online demos that I can find on the net I expected the problem to be related to versions. But I used many differents versions ofpdf.js and nothing seems to fix the problem.

I tried to change versions differents versions of PdfWorker as well and nothing seemed to fix the problem.

Same problem happens in Google Chrome and Mozilla Firefox.

**Steps to reproduce**

1. Load a PDF using pdfjs
2. Highlight some text
3. Text is duplicated all over the highlighting

**Expected behavior**

I didn't expect text to be duplicated

**Additional information**

![Capture de 2021-02-11 12:03:31](https://user-images.githubusercontent.com/10995524/107634834-0f0c6f00-6c62-11eb-9f7d-e493d8acb860.png)

**Environment**

 - Browser (if applicable): google-chrome 88.0.4324.150-1 and firefox 85.0.2-1
 - React version : 17.0.1
 - PDFjs version: 2.6.347

**Comment by Snuffleupagus** [comment]
> I tried to change versions differents versions of PdfWorker as well and nothing seemed to fix the problem.

The textLayer is handled on the main-thread, hence the *exactl version of the `pdf.worker.js` file isn't really expected to matter here.

> React version : 17.0.1

Unfortunately we know nothing about "React" here, and furthermore your screen-shot does *not* look like it's from [the demo viewer](https://github.com/mozilla/pdf.js#online-demo).

If I were to guess, since it's not really clear from the provided information, is this is either *some* kind of custom implementation of the PDF.js library or even another project altogether.
As-is, it's unfortunately quite difficult to find anything that's actionable *here*; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Akaban** [comment]
Hey,

In fact you are right, I am working on a fork of a project which is based on PDF.js. I'm trying to understand everything but I am pretty new to JavaScript, I tought that maybe that shadow highlighting problem could be a known issue even though I could not find anything on the net.

I will investigate that problem until I'm sure this comes from upstream.

Thanks again for your time and the precious information :)

**Comment by Snuffleupagus** [comment]
> In fact you are right, I am working on a fork of a project which is based on PDF.js.

*For future reference;* Please remember to state that *clearly* upfront, to save from people having to "read between the lines" to figure that out.

> I will investigate that problem until I'm sure this comes from upstream.

It's guaranteed to *not* be a bug in the PDF.js library, since we don't provide any sort of highlighting functionality here.
