### ISSUE TITLE
How to change meta title

### ISSUE THREAD

**Issue by cepcemuh** [mozilla/pdf.js#13034]
How could change the meta title of the .html... whatever I put in the title tag, it comes with file.pdf title...

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable information and will be closed as INVALID.

Furthermore, as [explained in the README](
https://github.com/mozilla/pdf.js#pdfjs-) (from which I'm quoting below), PDF.js is *not* a PDF editing library:
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.
