### ISSUE TITLE
Invalid PDF structure - please provide more information in error message

### ISSUE THREAD

**Issue by ralfhauser** [mozilla/pdf.js#13035]
![image](https://user-images.githubusercontent.com/1681677/109517204-4a53ce00-7aa9-11eb-8304-1c1262ba4902.png)

It would be very helpful to know
a) whether the file was "null" ?
b) if not, what size it had
c) possibly even a filename / URL

this happened for example once I removed the compressed.tracemonkey-pldi-09.pdf file

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this doesn't contain nearly enough information to be *easily* actionable.

**Comment by Snuffleupagus** [comment]
> whether the file was "null" ?

What do you actually mean with `null`, since there's already a specific error message for *empty* files.

> if not, what size it had

Please provide a use-case/example, since it's extremely difficult to evaluate this issue as-is.

> possibly even a filename / URL

Generally speaking, neither is guaranteed to exist since the API is able to a TypedArray and/or binary data (and the worker-thread has no context of any filename/URL).

> this happened for example once I removed the compressed.tracemonkey-pldi-09.pdf file

Please actually follow the issue reporting guidelines, as asked for above, since it's first of all not clear *exactly* how to reproduce this.

---

In general, for any feature request, please provide enough context/information to make it possible to actually evaluate what you're asking for; as-is there's no use-case provided here.

**Comment by ralfhauser** [comment]
> Please provide a use-case/example, since it's extremely difficult to evaluate this issue as-is.
Steps:
1) removed "compressed.tracemonkey-pldi-09.pdf" from the web directory since this 1MB big
2) Added a 20K "SampleDocument.pdf" to the web
3) PDFViewerApplication.open('SampleDocument.pdf');

Then, it happens

> Generally speaking, neither is guaranteed to exist since the API is able to open a TypedArray and/or binary data (and the worker-thread has no context of any filename/URL).
Suggestion:
4) provide the context in the relevant functions to be able to provide more useful error messages

**Comment by ralfhauser** [comment]
Re 3) when I changed viewer.js to

   defaultUrl: {
      value: "SampleDocument.pdf",
      
it seems to work now

**Comment by Snuffleupagus** [comment]
> provide the context in the relevant functions to be able to provide more useful error messages

I'm not sure what additional "context" we could realistically provide here, since this particular error occurs when *all* data parsing (including the various fallback code-paths) have failed; see https://github.com/mozilla/pdf.js/blob/63c5d449f243637385db5bacba046742784e386b/src/core/obj.js#L1938-L1939 

Unfortunately, at that point we:
 - Cannot be sure, in the general case, if the document is either a corrupt PDF document or some *other* file format.
 - Don't have access to a file name, assuming one even existed in the first place (which it doesn't it the data was loaded as e.g. a TypedArray).
 - Might not have a "file size" that makes sense.

All-in-all, it unfortunately going to be difficult to provide any of the information you're asking about (and it does seem like an edge-case anyway).

**Comment by ralfhauser** [comment]
> Might not have a "file size" that makes sense.
5) even if you don't have the proper "file size", it would be interesting what the size of the data structure at hand is (e.g. also TypedArray) that is causing the errors

6) Also , even though not physically existing, the tab got the title "compressed.tracemonkey-pldi-09.pdf" (in the html.header)
