### ISSUE TITLE
Is there any way to use 2 pdf.js versions in one website.

### ISSUE THREAD

**Issue by 1notchdev** [mozilla/pdf.js#13048]
I am building one website in WordPress, and using one plugin that uses an older version of pdf.js(2.1.266).
And I want to use new pdf.js version(2.6.347), but I can't update the pdf.js version of the plugin, because it is caused many errors.
Is there any resolution?

**Comment by Snuffleupagus** [comment]
As long as you isolate the different PDF.js version is e.g. separate `<iframe>`s it *should* work.

However, please keep in mind that we know nothing about WordPress here and that this issue is missing *all* of the information required to be actionable/valid; please note https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
