### ISSUE TITLE
Extract Individual Words

### ISSUE THREAD

**Issue by irtzasuhail** [mozilla/pdf.js#13047]
Hi,

Apologies for not following the recommended template in advance.

I have a basic nodejs script that takes a pdf, extracts the text and the coordinates and returns them to me. However, it returns whole lines of text with the corresponding coordinates for the entire line. Is it possible for getTextContent() to return individual words and their coordinates? I have already tried with setting normalizeWhitespace and disableCombineTextItems to every possible combination of true/false, but there is no change in how the text gets extracted.

**Comment by Snuffleupagus** [comment]
Setting `disableCombineTextItems: true` when calling `getTextContent` is the only advice that we can give you unfortunately, but that's *not* guaranteed to break text-runs into individual words (as you've noticed).
The explanation is that in the PDF specification text isn't specified as words, or even letters, but rather as individually positioned glyphs and consequently this cannot work like you want in general. (Since most PDF documents simply have no concept of either word- or line-breaks.)

All-in-all, this unfortunately cannot work like you want since the PDF file format wasn't really created for such a use-case.

**Comment by danielo515** [comment]
I am facing a similar problem, where I have data in a table, and almost all the table cells (which contain individual words) are extracted as a single word.
Reading this issue I assume there is no workaround for this, right?
