### ISSUE TITLE
now the build on window's chorme's 49 has display bug

### ISSUE THREAD

**Issue by zhuochengs** [mozilla/pdf.js#13059]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chorme's 49 
- Operating system and its version:  windows  xp
- PDF.js version: newest
- Is a browser extension: yes

now the windows  xp chorme's 49  behavior
![微信截图_20210307150933](https://user-images.githubusercontent.com/17957646/110232225-7e226e00-7f57-11eb-86db-1c402c3555fc.png)
![微信截图_20210307151231](https://user-images.githubusercontent.com/17957646/110232257-af9b3980-7f57-11eb-977e-1089f94d8db5.png)

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
![微信截图_20210307151146](https://user-images.githubusercontent.com/17957646/110232221-7a8ee700-7f57-11eb-840b-426b3c069a64.png)
![微信截图_20210307151310](https://user-images.githubusercontent.com/17957646/110232260-b32ec080-7f57-11eb-898e-b3dc4d6410d6.png)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by zhuochengs** [comment]
And I think this should have a screenshot Features

**Comment by Snuffleupagus** [comment]
> Web browser and its version: chorme's 49

Assuming that you mean *Google Chrome 49*, then according to https://en.wikipedia.org/wiki/Google_Chrome_version_history that browser is *four* years old and using such an old browser is never recommended for security reasons.

> PDF.js version: newest

Please make to sure to always provide an actual version *number*, since "newest" can mean any number of things and consequently isn't really useful.

---

In the updated viewer UI, the toolbar icons are displayed using `mask-image`/`mask-size` (or `-webkit-mask-image`/`-webkit-mask-size` in Chrome), which according to this compatibility information should be available in all browsers that we support:
 - https://developer.mozilla.org/en-US/docs/Web/CSS/mask-image#browser_compatibility
 - https://developer.mozilla.org/en-US/docs/Web/CSS/mask-size#browser_compatibility

If the toolbar icons aren't working, then the browser is simply *too old* to be supported in the PDF.js at this point in time; hence this issue won't be fixed unfortunately.

**Comment by timvandermeij** [comment]
Indeed. Chrome 49 is _way_ too old to be supported, let alone Windows XP which you _absolutely_ should not be using anymore.

**Comment by zhuochengs** [comment]
thanks! AND what about the  screenshot Features?
