### ISSUE TITLE
Cannot extract jpg from pdf using pdf.js 

### ISSUE THREAD

**Issue by kertom** [mozilla/pdf.js#13068]
Attach (recommended) or Link to PDF file here:
https://dl.dropboxusercontent.com/s/9r24qq5s61o7mbi/jpgImagePdf.pdf?dl=0
Configuration:
- Web browser and its version:Chrome 88
- Operating system and its version:macOS BigSur
- PDF.js version:2.6.347
- Is a browser extension:No

Steps to reproduce the problem:
1. I am trying to extract a jpg image from a pdf file. Please take a look at a reproducible example:
https://codepen.io/thomas-kertsalis/pen/YzpYwYo?editors=1111

What is the expected behavior? (add screenshot)
The extracted image should be displayed in html.
What went wrong? (add screenshot)
The image is not displayed.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Sorry, but this doesn't *really* look like a PDF.js bug as such and more like a general question about handling of image data in HTML (since in the example you're apparently able to extract the raw JPEG data from the PDF); please keep in mind that this is first and foremost a *bug tracker* for the PDF.js project.

**Comment by kertom** [comment]
Dear Mr Jonas Jenwald,

I was wondering ,if you could take a second look at my question, please?  The raw data are extracted from the image ,but apparently in the wrong way. That’ s why they are not displayed in html. This is most likely be a bug of pdf.js. 
I sure keep in mind ,that this is a bug tracker.That’s why i examined this problem thoroughly before posting this issue as I did not want in anyway waste your time. 
I would like to ask you one more time to take a second look before judging me. 

Kind regards,
Thomas Kertsalis

**Comment by Snuffleupagus** [comment]
> The raw data are extracted from the image ,but apparently in the wrong way. That’ s why they are not displayed in html. This is most likely be a bug of pdf.js.

Once more, there really is no bug in the PDF.js library!

Your problem seem to be that you've made the, unfortunately incorrect, *assumption* that the PDF.js library provide image data as JPEGs. That's *not* actually correct and all images, regardless of their types (since the PDF specification supports multiple image formats), will be returned as *raw pixel data*, since that's what's needed for the display-layer (see https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js).

Hence, you'll need to convert the pixel data of the image into a format that works on a web page. While the rest of the example isn't exactly relevant here, this *particular part* shows one way of converting the image data returned by PDF.js into something that can be rendered to a `canvas` element (from which you can easily get an `image`-element): https://github.com/mozilla/pdf.js/blob/57e7557235c4f47ec150a28fc62d9daaf4c2b9b5/examples/image_decoders/jpeg_viewer.js#L70-L82

**Comment by kertom** [comment]
Thank you very much for your response and help! I really appreciate it!
