### ISSUE TITLE
pdfjs fails to read a Buffer.from or buffer from fs.readFileSync

### ISSUE THREAD

**Issue by yrambler2001** [mozilla/pdf.js#13075]
Attach (recommended) or Link to PDF file here:
[issue13075.pdf](https://github.com/mozilla/pdf.js/files/6117265/issue13075.pdf)

Configuration:
- Web browser and its version: Node.js 14.15.5
- Operating system and its version: Mac OS 11.2.1
- PDF.js version: master/2.7.570/2.6.347/1.10.100
- Is a browser extension: false

Steps to reproduce the problem:
1. const fileBuffer = fs.readFileSync('./pdf')
2. PDFJS.getDocument(fileBuffer)
3. fileBuffer.buffer has junk data at the start and at the end. Randomly, pdfjs can not read a buffer, whose buffer.buffer contains random memory junk data in fileBuffer.buffer

What is the expected behavior? pdfjs ignores a buffer.buffer and reads only buffer

What went wrong? (add screenshot)
I've catched that random error and wrote fileBuffer.buffer of the error buffer to a file named issue13075.pdf
I've recreated a buffer that has the wrong buffer.buffer (see line 6). Pdfjs fails to read that buffer (console.log('Fail')).
The Uint8Array of that buffer, pdfjs correctly reads (console.log('OK')).
![image](https://user-images.githubusercontent.com/8398353/110660366-59f1a780-8178-11eb-94c2-29be826c2118.png)

codesandbox:
https://codesandbox.io/s/pdfjs-loading-from-buffer-issue-9h4fd?file=/src/index.js

**Comment by Snuffleupagus** [comment]
> const fileBuffer = fs.readFileSync('./pdf')
> PDFJS.getDocument(fileBuffer)

As can be seen in the docs, `getDocument` does *not* accept any Node.js-specific data types: https://github.com/mozilla/pdf.js/blob/5e3af62d582133d1f3e2550768e87680c8c2076c/src/display/api.js#L195-L207

Hence you need to convert your `fileBuffer` into a *standard* `TypedArray`, otherwise it simply cannot work!

> codesandbox:
> https://codesandbox.io/s/pdfjs-loading-from-buffer-issue-9h4fd?file=/src/index.js

That gives a "502: Bad Gateway" error when I load it (in both Firefox and Chrome browser).

**Comment by yrambler2001** [comment]
> That gives a "502: Bad Gateway" error when I load it (in both Firefox and Chrome browsers).
Unfortunately for me too, I have to click on the plus button and write yarn start in the new console 
> does not accept any Node.js-specific data types
Oh that's bad. I as a developer see that pdfjs almost always opens a pdf Buffer well, so I can assume pdfjs supports a Buffer.
It will be better if
a) throw an exception if the input parameter is not in the list of supported types
b) merge my pull request that fixes this issue

**Comment by yrambler2001** [comment]
However, other developers that use pdf.js on the node, simply pass a Buffer from readFileSync and assume it will work.
Example package that internally uses pdf.js:
https://www.npmjs.com/package/pdf-parse https://gitlab.com/autokent/pdf-parse/-/blob/master/lib/pdf-parse.js#L71

**Comment by Snuffleupagus** [comment]
> However, other developers that use pdf.js on the node, simply pass a Buffer from readFileSync and assume it will work.

Unfortunately we cannot really help if others have implemented things this way, without consulting the docs.

> Example package that internally uses pdf.js:
> https://www.npmjs.com/package/pdf-parse

We don't really know anything about that here (since it's not affiliated with the PDF.js project).

> https://gitlab.com/autokent/pdf-parse/-/blob/master/lib/pdf-parse.js#L71

It *seems* like that's based on a severely outdated version of the PDF.js library, since that code wouldn't even work with an up-to-date PDF.js version.

---

*Back to the issue at hand:* Looking through this again, unless I've completely misunderstood things, it appears that this is only a problem when calling `getDocument` with a `TypedArray` with a `byteOffset !== 0`!?
If that's indeed the case, the problem is *mostly* limited to Node.js environments[1] and we could probably work-around it with a *targeted* fix that wouldn't risk affecting anything else.

---
[1] Since workers aren't (and can't be) used in Node.js, and normally sending data between threads should've prevented this bug.

**Comment by yrambler2001** [comment]
> when calling getDocument with a TypedArray with a byteOffset !== 0!?

Yes. I've updated a pull request

**Comment by Snuffleupagus** [comment]
> Yes. I've updated a pull request

Unfortunately that's *still not* correct, since there's first of all no `offset` property on `TypedArray`s and secondly it's also not a complete solution (since it misses a lot of cases). If we're going to fix this, it needs to be generally applicable and done in the *one* central spot where all `TypedArray`s pass when workers are disabled.

**Comment by yrambler2001** [comment]
Looks like the PDFDocument constructor is the proper place for this fix. All PDF files will go through that constructor.
