### ISSUE TITLE
The PDF bar elements are not visible with High Contrast

### ISSUE THREAD

**Issue by brendandahl** [mozilla/pdf.js#13109]
This is a copy of from [bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1685700).
![image](https://user-images.githubusercontent.com/942640/111253707-df3de780-85d0-11eb-98c7-67cbdc92dd30.png)

@utopianknight maybe you have some ideas on how to support high contrast mode?

**Comment by utopianknight** [comment]
I'm going to focus on the icons only for now. And I think I've found the culprit. In my [original commit](https://github.com/mozilla/pdf.js/commit/c0b671d91b037065c9bf16e6b6920d32334dea61), each icon had a dark and light version with a 'fill' attribute set to white in the dark version. Now there is only one icon for each button, with no fill color explicitly set. [Apparently](https://sarahmhigley.com/writing/whcm-quick-tips/#2.-svgs-and-currentcolor), the SVG fill colors are not overiden in high contrast mode. So I think we need to revert back to having two icons for each button.

**Comment by utopianknight** [comment]
I was able to get this to work in Edge, but not in Firefox even with `layout.css.forced-colors.enabled` set to true:

```CSS
@media screen and (forced-colors: active) {
    :root {
      --button-hover-color: Highlight;
    }
}
```
So I think this needs to be fixed first.

**Comment by MReschenberg** [comment]
Hello! 

We currently support `forced-colors` and `prefers-contrast` [behind preferences](https://searchfox.org/mozilla-central/rev/ee9dab6aa95f167a34cb178960f7375210a0bba4/servo/components/style/media_queries/media_feature_expression.rs#220) in the content process. The `prefers-contrast` query is also enabled by default (without the preference) for everything in the chrome process. I assume pdf-js lives in the content process, right? If not, you should be able to use `prefers-contrast: high` here. Let me follow up and see why we haven't released `forced-colors` fully -- if I remember correctly the CSSWG has resolved most of the outstanding spec issues. It'd be great to use that here.

Also: is this something that could be fixed with color keywords? Most of our HCM issues are resolved by relying on a user's default background/forground color that are overridden automatically when a user activates HCM. We mostly do this through the currentColor keyword (this is how, for example, custom components in about:preferences react to HCM changes). When I view something in the PDF viewer currently, the toolbar background adapts to my HCM background color. I think it'd make sense for the icons to match the foreground/text color, which currentColor might help with. I'm not familiar with pdf-js though so please ignore if this is wildly off base 😀 

In any case, let me know if I can answer any questions -- I'm the accessibility engineer on high contrast/low vision stuff.
