### ISSUE TITLE
Wrong rendering in print dialog

### ISSUE THREAD

**Issue by Merlignux** [mozilla/pdf.js#13129]
Configuration:
- Web browser and its version: Firefox 86 (64-bit) - (but in any other versions i've tried it the same happens) and Edge 89 (anything Chromium based will do, actually)
- Operating system and its version: Windows 10 20H2 (But Any OS will have the same problem - Linux inclusive)
- PDF.js version: the one on Firefox 86

Steps to reproduce the problem:
1. Open PDF file
2. Bring up the print dialog

Description:
I have a company PDF transport document generated by SalesForce software (which i cannot publicly share).
It looks like this (I had to remove the text inside the rectangles):
![org](https://user-images.githubusercontent.com/8130393/112022188-f24d3c00-8b29-11eb-8739-90dbc8623282.png)

Now, if i open it under MS Edge (or anything chromium based, or in any other pdf viewer like Adobe Reader or Okular) and bring up the print dialog it looks like this (which is how it should look like):

![edge](https://user-images.githubusercontent.com/8130393/112022383-2aed1580-8b2a-11eb-9935-8ea4f6b9d4e2.png)

In Firefox, however, it shows up reduced and centered to the left:
![ff](https://user-images.githubusercontent.com/8130393/112022476-40fad600-8b2a-11eb-9149-5d5c77b2fee0.png)

(And it does print like the preview, in case you're wondering)
The page size and all the other configurations are the same.

**Comment by Snuffleupagus** [comment]
> I have a company PDF transport document generated by SalesForce software (which i cannot publicly share).

As a general rule, please note that all issues must include a test-case in order to be actionable/valid (since it's generally impossible to debug something using only a screen-shot).

> In Firefox, however, it shows up reduced and centered to the left:

After PR #13102, the content will always be printed in the *centre* of the pages; hence this should be partially fixed already.

> The page size and all the other configurations are the same.

Most likely, given the lack of a test-case, the rest of the issue is caused by Firefox not yet supporting the `@page`-rule which means that we cannot provide accurate page size information when printing.

---

All-in-all, let's just close this as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1697778 for now.

**Comment by Merlignux** [comment]
> All-in-all, let's just close this as a duplicate of https://bugzilla.mozilla.org/show_bug.cgi?id=1697778 for now.

Hi, Thank you for your fast reply! :)

I cannot provide the original file, unfortunately... company policy!

But it seems to be the case of the bug you mentioned, so i agree that the bug can be closed.

Is PR #13102 available in nightly already?

Thanks

**Comment by Snuffleupagus** [comment]
> I cannot provide the original file, unfortunately... company policy!

It's usually possible to create a PDF document with "dummy"-data, to work-around that limitation.

(Please keep in mind that this is an open-source *bug tracker*, rather than a support forum, and many of the people you interact with here are volunteers and not paid support staff.)

> Is PR #13102 available in nightly already? (what's the FF version that's estimated to have this fix?)

See https://bugzilla.mozilla.org/show_bug.cgi?id=1699313

**Comment by Merlignux** [comment]
> It's usually possible to create a PDF document with "dummy"-data, to work-around that limitation.

Yes, "usually"... but since we do not control the data used to generate the file, it does not apply to this case.

It's also kind of confusing having two places to report problems in pdf.js... here and in BugZilla...

Anyway, thank you so much for you time and support. :)
