### ISSUE TITLE
Fully load pdf

### ISSUE THREAD

**Issue by MonkeyTiger** [mozilla/pdf.js#13139]
Hello.
I need to call a custom function after pdf file contents fully inserted like HTML dom in the browser.  How can I know that? Please help me. Thanks!

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is it's quite difficult to understand *exactly* what you're asking here.

Furthermore, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

For example: Are you using the API directly, the viewer-components, the demo viewer, or something else?
More context is going to be necessary, since otherwise people are going to have to *guess* at what you actually mean.

Finally, note that as explained in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, hence (in the demo viewer) there's no point where all pages are guaranteed to be rendered (except for one page documents).
