### ISSUE TITLE
Can view a PDF file but ONLY page option OR zoom option work, not both of them

### ISSUE THREAD

**Issue by zorbathegreek** [mozilla/pdf.js#13136]
EDIT: 
I just realized that I made a mistake: I was trying to pass the options from the command line, but I should have written in the URL bar. Just like Tim vd Meij proposed (below). 
Whatever this may be worth, I leave this issue here but close it myself. 

Hello, 

I am trying to view a PDF file from the CL at a certain page and at a certain zoom level, like so: firefox file:/foo.pdf#page5&zoom=200 but only the first of the two options works. Meaning, when I swap "page" and "zoom", then the zoom option works but not the "page" option. I tried several PDF files from different sources that were created with different tools/methods, and I always have the same problem. 

Configuration:
- Firefox 82.0.2 (64-bit) 
- Fedora 31
- PDF.js version:  2.7.69; build 26ae7ba2a (according to resource://pdf.js/build/pdf.js)
- This is not a browser extension

Steps to reproduce the problem:
1. firefox file:/bla.pdf#page5&zoom=200   result: page 5 is displayed at "Automatic Zoom"
2. firefox file:/bla.pdf#zoom=200&page5   result: page 1 is displayed at zoom=200

Expected behavior: both options should work at the same time

As explained by: 
Tim van der Meij on Mar 7, 2019 · 3 revisions

"Below are the options for the PDF.js viewer that can be given at URL level. Multiple values of either type can be combined by separating with an ampersand (&) after the hash (for example: #page=2&zoom=200)." (snip)

Thanks a lot for looking into this!

**Comment by Snuffleupagus** [comment]
> #page5&zoom=200

That's not the correct format, since you're missing an equal sign, and it *should* read `#page=5&zoom=200`.
Opening e.g. https://ctan.uib.no/info/lshort/english/lshort.pdf#page=5&zoom=200 works for me, when using Firefox Nightly 89.

> Firefox 82.0.2 (64-bit)

The current Firefox version is `87`, so you really ought to update your browser. (Note that older browsers *may* have known security vulnerabilities.)

---

Given that this works, with a *correct* hash, there's nothing that can/will be fixed here.

**Comment by zorbathegreek** [comment]
Thanks Snufflejupagus, 
just realized what was wrong, edited my post, and closed the issue!
