### ISSUE TITLE
Uncatchable error thrown when embedded font is broken

### ISSUE THREAD

**Issue by keroxp** [mozilla/pdf.js#13147]
Attach (recommended) or Link to PDF file here:

[broken_font.pdf](https://github.com/mozilla/pdf.js/files/6210602/broken_font.pdf)

Configuration:
- Web browser and its version: Firefox@87, Chrome@89, Safari@14
- Operating system and its version: Mac OS@11.2.3
- PDF.js version: 2.7.570
- Is a browser extension: No

Steps to reproduce the problem:
1.  To render page by PDFPageProxy.render()
2. Uncatchable error thrown.

What is the expected behavior? (add screenshot)

- The error should be able to be caught.
- Or correctly rendered.

What went wrong? (add screenshot)

This is console log when opening that pdf by Firefox@87. 

![image](https://user-images.githubusercontent.com/927286/112610038-99e6a900-8e5f-11eb-8aca-05ddba50d3a8.png)

I met identical errors when opening it via pdfjs's API. Well, that file seems to contain the font that is wrongly encoded, but other pdf viewer can show the content.  The message `Warning: Failed to load font 'g_d2_f1': 'SyntaxError: Invalid font data in ArrayBuffer.'.` was logged from [here](https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js#L93).

**Comment by Snuffleupagus** [comment]
[issue13147_reduced.pdf](https://github.com/mozilla/pdf.js/files/6211549/issue13147_reduced.pdf)

The CFF in question font has weird/broken header data, since we get bogus data already in https://github.com/mozilla/pdf.js/blob/63471bcbbeee3fc1c6b1df988174640a124f097a/src/core/cff_parser.js#L234-L240

**Comment by calixteman** [comment]
The error comes from:
https://searchfox.org/mozilla-central/source/gfx/ots/src/cff.cc#1194
A dirty (??) workaround is to set `this.bytes[2] = 4;` in the CFFParser and then the display is fine.
Maybe we could set it to 4 (which is the correct value for the header size for this version of CFF) when it isn't 4 and when `major==1 && minor==0` and then print a warning in console.
@Snuffleupagus, any thoughts on that ?

**Comment by Snuffleupagus** [comment]
> Maybe we could set it to 4 (which is the correct value for the header size for this version of CFF) when it isn't 4

According to this specification, there's no such limitation placed upon the `hdrSize` field (that I can find at least): https://adobe-type-tools.github.io/font-tech-notes/pdfs/5176.CFF.pdf#G3.32094

Furthermore, this is also too far from a complete solution to be desirable in my opinion, since there's *still* `Warning: TypeError: can't access property "length", dict is undefined` thrown elsewhere in the font-code even with your hack.

@janpe2 Any ideas here?

**Comment by calixteman** [comment]
So I cheated again: I changed bytes[2] to 4 to make firefox (and chrome) happy but keep the real `hdrSize` (12) for endPos and no more warning with the reduced test case but still few errors with the original test case:
```
TypeError: can't access property "data", tables[tableTag] is null
``` 
Anyway I'd say that there is a bug in firefox and chrome about the hdrSize, I'll file a bug and we'll see if there is a rationale for this check.

**Comment by calixteman** [comment]
The code in Firefox comes from:
https://github.com/khaledhosny/ots
and the check for header size is here since 12 years (first commit in this repo).

**Comment by calixteman** [comment]
As far as I understand we parse the CFF and then compile it but the header we write:
https://github.com/mozilla/pdf.js/blob/master/src/core/cff_parser.js#L1381
has 4 bytes and not `hdrSize` so I think the fix is to set to 4 the header size in `compileHeader` to be consistent with the header we're writing and let `endPos` being `hdrSize` in `parseHeader` to skip correct number of bytes.
Just need to figure out why `tables[tableTag]` is null.

**Comment by calixteman** [comment]
`tables[tableTag]` is a pebcak...

**Comment by calixteman** [comment]
Thank you for reporting.

**Comment by keroxp** [comment]
@calixteman @Snuffleupagus Thank you!
