### ISSUE TITLE
getData function doesn't send the updated content after add the text in Canvas

### ISSUE THREAD

**Issue by 1notchdev** [mozilla/pdf.js#13159]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 89.0.4389.90
- Operating system and its version: Windows 10
- PDF.js version: 2.1.266
- Is a browser extension: Not sure

Steps to reproduce the problem:
1. Load PDF file and added one image to the canvas.
`
ctx = document.getElementById('page1').getContext('2d');
...
ctx.drawImage(img, 0, 0);
`
2. Get data using pdfDocument.getData(), but it doesn't returned the added image.

What is the expected behavior? (add screenshot)
I want to get the pdf data with the updated content.

**Comment by Snuffleupagus** [comment]
Unfortunately this issue is missing *too much* information to actionable/valid.

> Attach (recommended) or Link to PDF file here:

This piece of information is *required*.

> PDF.js version: 2.1.266

That version is too old to be supported, please find the latest release at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>  1. Load PDF file and added one image to the canvas.
>        `ctx = document.getElementById('page1').getContext('2d'); ... ctx.drawImage(img, 0, 0);`
> 
>  2. Get data using pdfDocument.getData(), but it doesn't returned the added image.

Please keep in mind that the PDF.js library isn't written with the intention of supporting the addition of arbitrary content to the rendered `canvas`es, since the purpose is simply to render the document as-is; hence this use-case is unfortunately not something that we can support.

Furthermore, as explained in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine), code snippets are unfortunately of no use:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by 1notchdev** [comment]
I can get it worked by using `saveDocument` function in v2.6.347.
Thank you.
