### ISSUE TITLE
When printing A4 and A5, there will always be a blank page in the horizontal plate, and the version used is 2.0

### ISSUE THREAD

**Issue by hahazhang521** [mozilla/pdf.js#13162]
When printing A4 and A5, there will always be a blank page in the horizontal plate, and the version used is 2.0

![1617098488(1)](https://user-images.githubusercontent.com/44281537/113082378-ee49aa00-920c-11eb-831b-a67234b8ce03.jpg)

**Comment by Snuffleupagus** [comment]
> and the version used is 2.0

First of all, that version number doesn't exist (all PDF.js version numbers follow a `x.y.z` pattern); please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Secondly, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable/valid information and will be closed as INVALID.
