### ISSUE TITLE
Default state of Optional Content Configuration (layers) is not respected

### ISSUE THREAD

**Issue by soadzoor** [mozilla/pdf.js#13192]
Attach (recommended) or Link to PDF file here:
[Lavatory.pdf](https://github.com/mozilla/pdf.js/files/6270805/Lavatory.pdf)
[Galley.pdf](https://github.com/mozilla/pdf.js/files/6270806/Galley.pdf)

Hello,
I've created a client-side PDF-merger tool. For generating thumbnails, I'm using pdf.js. It's [open source](https://github.com/soadzoor/PDF-merger), and there's also a [deployed version here](https://soadzoor.github.io/PDF-merger/)

The problem:
All the layers are visible on the thumbnails, although one of them should be invisible (note the blue parts):
Wrong:
![wrong](https://user-images.githubusercontent.com/10392261/113852289-b3132200-979c-11eb-9023-5f5968f556a9.png)

When open with chrome, or firefox, it displays correctly:
![correct](https://user-images.githubusercontent.com/10392261/113852324-befee400-979c-11eb-9124-070a035d8a0c.PNG)

Here's the part of the code that's responsible for the thumbnail generation:
https://github.com/soadzoor/PDF-merger/blob/6c64edfcc1ec9c796dd0d838aa5f53bf28d05eca/src/ts/utils/PDFRenderer.ts#L136

I've also tried reading out the default "optionalContentConfig", and passing it to the render function, but it didn't make any difference. What am I missing?

Thanks

Configuration:
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: 2.7.570
- Is a browser extension: No

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> [Lavatory.pdf](https://github.com/mozilla/pdf.js/files/6270805/Lavatory.pdf)
> [Galley.pdf](https://github.com/mozilla/pdf.js/files/6270806/Galley.pdf)

WFM, when opening those files with the https://github.com/mozilla/pdf.js#online-demo

> Here's the part of the code that's responsible for the thumbnail generation:
> https://github.com/soadzoor/PDF-merger/blob/6c64edfcc1ec9c796dd0d838aa5f53bf28d05eca/src/ts/utils/PDFRenderer.ts#L136

If you don't pass in an `optionalContentConfigPromise`-parameter to the `render` method, a default one will be created for you so this should just work; please see https://github.com/mozilla/pdf.js/blob/6ddc297170a48475b2fdb882efd895d0236474c3/src/display/api.js#L1216-L1247

However, please note that we cannot really debug your entire project since we know nothing about it here, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by soadzoor** [comment]
@Snuffleupagus Thank you for the quick answer.
I've checked the links you sent me, and I still believe that I do everything correctly.

I put the official demo, and my demo next to each other, and opened the same PDF in both of them. Then I debugged the code line by line in both of them, and found the following:
 `this._catDict.get("OCProperties")` returns with `null` in my demo (in `pdf.worker.js`), but it returns with a valid object in the official demo (`obj.js`).
 
Is it possible that that there's a bug inside the worker, and because of that, the `catDict` doesn't get populated correctly? I've tried to dig even deeper than this, but it's getting very hard for me to understand what's going on, because I'm already looking at some pretty low-level-looking stuff inside `parser.js`.
 
 
![ocp](https://user-images.githubusercontent.com/10392261/113865991-0e4d1080-97ad-11eb-82c1-3b85452be28a.PNG)

**Comment by Snuffleupagus** [comment]
> [...] and there's also a [deployed version here](https://soadzoor.github.io/PDF-merger/)
> PDF.js version: 2.7.570

It's *very* difficult to check the source-code of your demo, since it looks like some kind of minified bundle is being used. However, what I did observe is that it *appears* that it actually uses PDF.js version `2.6.347` which is at odds with the version number you mentioned above. While this might be unrelated, since layers-support is included in that version, it's nonetheless inconsistent.

Ideally we'd need a *reduced* test-case, but failing that you'd at the very least need to provide a build *without* minified code (i.e. using the regular `pdf.js`/`pdf.worker.js` files), since otherwise it's really not possible for anyone to assist here (since this is first and foremost a *bug tracker*, rather than a support forum).

**Comment by soadzoor** [comment]
@Snuffleupagus Oh, you're right, I forgot to update the version on github pages, but I've already tried with version 2.7.570 locally, and I had the same problem.
Now I've updated the [deployed version](https://soadzoor.github.io/PDF-merger/) with unminified code, and sourcemaps, so it should be much easier to debug the code.
Again: the relevant parts are all inside `PDFRenderer.ts`, and more specifically this part:
![Capture](https://user-images.githubusercontent.com/10392261/113869558-2757c080-97b1-11eb-8f25-ed6606322efb.PNG)

**Comment by Snuffleupagus** [comment]
> I don't do specifically anything with layers (optional contents), that's why I'm 99% sure it's a bug in pdf.js. Unless I'm missing a parameter, or something.

I don't think so, since it appears that *your* code somehow manages to corrupt the PDF data that you're passing to the PDF.js library.
To reproduce, using https://github.com/mozilla/pdf.js/files/6270805/Lavatory.pdf, do the following steps:
 1. Open https://mozilla.github.io/pdf.js/web/viewer.html, and drag-and-drop the referenced PDF file there.
 2. Open the web-console (usually <kbd>F12</kbd> works), and execute `PDFViewerApplication.pdfDocument.getData().then(data => { console.log(data); });`
 3. Note the *length* of the returned Uint8Array data.
 4. Open https://soadzoor.github.io/PDF-merger/, and with the DevTools put a break-point [at this line](https://github.com/soadzoor/PDF-merger/blob/6c64edfcc1ec9c796dd0d838aa5f53bf28d05eca/src/ts/utils/PDFRenderer.ts#L74).
 5. In the console, execute `PDFRenderer._pdf.getData().then(data => { console.log(data) });` and resume the paused script.
 6. Now note the *length* of the returned Uint8Array data.

Here step 3 and 6 should give *identical* data, however the lengths differ quite substantially (your data being shorter) and the inevitable conclusion is thus that some *other* part of your project corrupts the PDF data that you're passing to the PDF.js library thus causing this bug.
Unfortunately the PDF document you create isn't corrupt enough to trigger outright parsing errors, which would've made finding this easier (although setting `VerbosityLevel.ERRORS` in your code certainly didn't help).

**Comment by soadzoor** [comment]
@Snuffleupagus Oh, gosh, you're right.. I'm creating new PDF files from the PDF pages with [pdf-lib](https://github.com/Hopding/pdf-lib) (so I can merge them later), and that lib [doesn't respect layers at all, it seems](https://github.com/Hopding/pdf-lib/issues/597).

Sorry for the troubles I made, and thank you for your time, and patience!
