### ISSUE TITLE
Previous/Next example, passing in url via input field

### ISSUE THREAD

**Issue by EccentricDyslexic** [mozilla/pdf.js#13208]
Hi, appologies for my newbie ness, but i am more ofay with c# than js... 

Using the sample code mentioned in the title, how do i pass in the pdf file via ```<input type="file" id="myPdf"></input>``` ?

**Comment by timvandermeij** [comment]
You can use the `getDocument` API to pass not only a URL but also a typed array with data for example. Refer to https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L115-L117. In your case you'll need to get the data from the PDF file selected by the input element and pass that to `getDocument`. We cannot assist with custom implementations, so that's something you'll have to build yourself.
