### ISSUE TITLE
print rendering issue and on multiple click on print operation displays pop-up 

### ISSUE THREAD

**Issue by eparirishit** [mozilla/pdf.js#13206]
Attach (recommended) or Link to PDF file here:
[Dummy.pdf](https://github.com/mozilla/pdf.js/files/6283685/Dummy.pdf)

Configuration:

- Web browser and its version: Firefox / 87.0
- Operating system and its version: Windows 10
- PDF.js version: 2.6.347 and Latest (2.9.11 in the demo)
- Is a browser extension: No

We are trying to skin on top of the default viewer and for the single-page/multiple-page print operation, we see the page is not rendered in the print window, in case of the version 2.6.347 if I scroll down and then scroll up I see the content getting rendered but in the latest version it's not even rendering after scrolling and if we try to cancel the operation and click on it for the second time we get a confirmation pop-up dialog. 
How can I restrict the pop-up message and also fix the rendering issue?

Steps to reproduce the problem:
1. Navigate to the online demo link - https://mozilla.github.io/pdf.js/web/viewer.html
2. Click on Open File option on the toolbar
3. Download the pdf from the link above and select the file to be opened in the viewer
4. Click on Print
5. Cancel the operation and click on Print again

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/9528214/114140553-09fc3100-992e-11eb-8550-b92a7a15828e.png)

What went wrong? (add screenshot)
Issue - 1
![image](https://user-images.githubusercontent.com/9528214/114140714-47f95500-992e-11eb-931d-5791243ed010.png)

Issue - 2
Cancel the operation and click on print again
![image](https://user-images.githubusercontent.com/9528214/114140830-68291400-992e-11eb-9c0e-5be0b2e2e0ea.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N.A

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

That version is now explicitly unsupported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> How can I restrict the pop-up message

The dialog is controller by the browser *itself*, not the PDF.js library, hence this isn't something that we can "fix" here.

> and also fix the rendering issue?

WFM, in Firefox Nightly 89.

I remember seeing that behaviour *intermittently* in the past, with earlier Firefox versions, but it seems to have been fixed since. In any case that would likely be a *browser* bug, rather than a PDF.js one, and I'd suggest that you re-test using Nightly to see if it's indeed fixed; you can also use https://mozilla.github.io/mozregression/ to find out when it's fixed.

**Comment by eparirishit** [comment]
Thanks, @Snuffleupagus. I have tested both the scenarios in Firefox Nightly 89, it seems to be working fine. Hopefully, the update will be soon available to the general browser.
