### ISSUE TITLE
Not working in Safari 

### ISSUE THREAD

**Issue by utkarshbhati07** [mozilla/pdf.js#13202]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari 14.0.3
- PDF.js version: pdfjs-2.6.347-es5-dist

Viewer not rendering properly.
Please check attached image

![image](https://user-images.githubusercontent.com/74948236/114011187-90f3cf80-9882-11eb-8c3d-4eb89d44b4a2.png)

And getting this error in console :
![image](https://user-images.githubusercontent.com/74948236/114011231-a0731880-9882-11eb-894f-2cf0ca118b3e.png)

**Comment by Snuffleupagus** [comment]
> Please check attached image

The image very clearly shows a *custom* viewer, which we know nothing about here, and it's simply impossible to debug anything from a screen-shot alone!

> And getting this error in console

This suggests that you've somehow modified our demo viewer, by removing a DOM element without removing all of the code which accesses it.

---

Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum, and that *all* issues must be easily actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by utkarshbhati07** [comment]
I am just using the code which is in viewer.html without any modifications

**Comment by timvandermeij** [comment]
Given that the screenshot shows other icons and no working link is provided, there is nothing else we can do here.

**Comment by JammingBen** [comment]
Having the same issue. Safari seems to handle relative URLs differently than other browsers when working with CSS variables. While other browsers build the URL based on the location of the CSS file, Safari takes the base of the request URL. Also see for example:

* https://stackoverflow.com/questions/65199329/css-variable-url-fallback-relative-path-different-in-safari-to-other-browsers
* https://stackoverflow.com/questions/66860296/url-not-resolved-correctly-when-using-css-variable-in-safari

There's also an official bug ticket for webkit: https://bugs.webkit.org/show_bug.cgi?id=198512. Apparently this is fixed since February, however, I don't know on which webkit version Safari currently runs on.
