### ISSUE TITLE
Suggestion: Implement last view memory

### ISSUE THREAD

**Issue by cepedus** [mozilla/pdf.js#13218]
I'd like to know if it's possible to implement a "view settings memory" in the built-in reader. This is especially useful when going through long documents such as books and closing the reader tab doesn't keep any trace of advance within the PDF body. 

I have literally zero knowledge in js but I think it's rather straightforward to implement:

- Keep locally a list of locally stored opened pdfs "file:/ ... .pdf" 
- When tab closes, trigger "Current view", overwrite/add in previous list the path with current view "file;/ ... .pdf#page=XXX&zoom=YYY"
- When opening a pdf file, check if "file:/ ... .pdf" in the list, if it's the case open saved view

In order to keep it computationally bounded, limit list size to 100 (or set by the user in the settings) and treat it as a queue (FIFO)

**Comment by Snuffleupagus** [comment]
While this issue is a little "light" on the details, please remember to *always* fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) with all the requested information when opening an issue, note that the [demo viewer](https://github.com/mozilla/pdf.js#online-demo) already implements this courtesy of https://github.com/mozilla/pdf.js/blob/master/web/view_history.js

Hence this is already implemented, and this issue can be closed :-)

**Comment by JanilsWoerst** [comment]
Hi @Snuffleupagus,
The feature works in the demo viewer for me. And as far as I understood pdf.js is integrated in the newest Firefox.
Do you have a suggestion why the view_history feature doesn't work when I use Firefox on local pdf files(like with file://...) .
Is there anything I got wrong or should I open an Issue for that? Do I need to change a parameter in the about:config to make it work?

Thank you very much for your answer in advance :)

**Comment by iG8R** [comment]
I have the same issue. Where could I get answers to the same questions as @JanilsWoerst?
