### ISSUE TITLE
2.7.570 breaks builds for React apps built with Create-React-App (CRA)

### ISSUE THREAD

**Issue by aspnetde** [mozilla/pdf.js#13239]
I am using [React PDF Viewer](https://react-pdf-viewer.dev/), which is based on pdf.js at its [core](https://react-pdf-viewer.dev/docs/getting-started), within a React app created with [CRA](https://create-react-app.dev/). Which basically means, that there is Webpack working under the hood, abstracted away through CRA.

Now everything works fine up to `2.6.347`, but starting with `2.7.570` and also with `2.8.335` I am running into this error:

```
./node_modules/pdfjs-dist/build/pdf.js 3657:145
Module parse failed: Unexpected token (3657:145)
File was processed with these loaders:
 * ./node_modules/react-scripts/node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|               numPages: this._numPages,
|               annotationStorage: (annotationStorage === null || annotationStorage === void 0 ? void 0 : annotationStorage.getAll()) || null,
>               filename: ((_this$_fullReader = this._fullReader) === null || _this$_fullReader === void 0 ? void 0 : _this$_fullReader.filename) ?? null
|             }).finally(() => {
|               if (annotationStorage) {
```

I don't expect anyone here to provide support for either the react package nor CRA. However, as I could clearly identify `2.7.570` as the "deal breaker", I suspect there has been some change that makes a re-configuration of Webpack necessary?

Glad to receive any feedback that could help to shed some light on the root cause :-)

Thank you

**Comment by Snuffleupagus** [comment]
> I am using [React PDF Viewer](https://react-pdf-viewer.dev/),

We know nothing about that project here, since it's not affiliated with the PDF.js library in any way; hence please direct any support questions regard the "React PDF Viewer"-project *directly* to them instead.

> However, as I could clearly identify `2.7.570` as the "deal breaker",

Most likely, https://github.com/mozilla/pdf.js/issues/13190#issuecomment-814701619 is relevant here as well.

---

*Slightly off-topic, but:* In my opinion, it's reasonable to expect that the "React PDF Viewer"-project should handle *their own* user support, considering that they're charging users money for their software.

The PDF.js library, in contrast, is completely free and thus it seems somewhat unfair to expect the PDF.js contributors to provide support (for free) to a *commercial* project.

**Comment by aspnetde** [comment]
> We know nothing about that project here, since it's not affiliated with the PDF.js library in any way; hence please direct any support questions regarding the "React PDF Viewer"-project directly to them instead.

->

> **I don't expect** anyone here to provide support for either the react package nor CRA.

**Comment by timvandermeij** [comment]
"Unexpected token" probably refers to the use of the nullish coalescing operator (see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) used in that line that your environment does not support. Either add a plugin for that or use the legacy version of PDF.js if you need to be able to run in a browser that doesn't support that.

**Comment by dominik-bln** [comment]
Just to add another observation,  we are seeing a similar error when updating to `2.7.570` using plain `pdf.js` in a Vue project while building with Webpack:

<img width="1350" alt="Screenshot 2021-04-15 at 14 31 32" src="https://user-images.githubusercontent.com/855119/114869474-4e3c7500-9df7-11eb-812b-1d2057f803a6.png">

It looks like in this case it is related to [Optional Chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining). I tried to get it working again by adding pdfjs to transpiled dependencies (i. e. in `vue.config.js` via `transpileDependencies`), but no luck so far.

I'm still trying to understand why this is happening, since we are building in Node v14 that should support optional chaining and our browserslist should only have browsers that support it as well 🤷 .

**Comment by aspnetde** [comment]
@dominik-bln See https://github.com/react-pdf-viewer/react-pdf-viewer/issues/499#issuecomment-819568264

**Comment by dominik-bln** [comment]
@aspnetde Ah, thank you, that clears it up. Another thing to add to the list that will only work with Webpack 5.
