### ISSUE TITLE
publish a "only nodejs" module to npm

### ISSUE THREAD

**Issue by lublak** [mozilla/pdf.js#13241]
Currently it is very complicated to use pdfjs on the server side.
For this reason, only pdf.js is required in this build (no pdf.worker.js).
Also, the functions that access the dom (including the typescript definitions) or the worker would have to be removed.
A pdfjs-node package in npm would make the work much easier.
Currently, many developers copy the js file manually and set disableWorker to true: `PDFJS.disableWorker = true;`

**Comment by Snuffleupagus** [comment]
When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md to ensure that the issue is actionable/valid.

> For this reason, only pdf.js is required in this build (no pdf.worker.js).

Huh, given that *all* parsing happens in the `pdf.worker.js` file it's simply *impossible* to use the PDF.js project *anywhere* without that file being present...
(In e.g. Node.js environments it's loaded in the same context as the `pdf.js` file, but it's most definitely still used.)

> Also, the functions that access the dom (including the typescript definitions) or the worker would have to be removed.

Things such as e.g. DOM-accesses are done in such a way that the *general* PDF.js library should "just work" in Node.js environments; please refer to these examples (which use a "regular" PDF.js build): https://github.com/mozilla/pdf.js/tree/master/examples/node

> A pdfjs-node package in npm would make the work much easier.

The PDF.js library is primarily intended for *browsers*, and besides the general library shoulld already be usable in Node.js as-is (see above).
For reasons of both maintainability and user support, since most of this work is done by contributors, we thus need/want to limit the number of builds that we provide!

> Currently, many developers copy the js file manually and set disableWorker to true: `PDFJS.disableWorker = true;`

The `PDFJS` global itself, and the `disableWorker` option, have been removed *years* ago; which suggests that the PDF.js version you're using is very out-of-date.

**Comment by lublak** [comment]
At the moment I think I have made a big mistake.
I have brought `disableWorker` directly together with pdf.worker.js.
`disableWorker` itself I had found in slightly older libraries and adopted it without thinking, sorry for my incompetence.
I also had the definition files of https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pdfjs-dist/index.d.ts#L540, which still contains disableWorker.
Let's skip that as if I had addressed it.


> The PDF.js library is primarily intended for browsers, and besides the general library should already be usable in Node.js as-is (see above).
For reasons of both maintainability and user support, since most of this work is done by contributors, we thus need/want to limit the number of builds that we provide!

That's understandable, then I'll take "lib": ["dom"] into the tsconfig, even if it is relatively strange. Then I would close this issue and I would like to thank you very much for your answer and apologise again.
