### ISSUE TITLE
Responding programmatically to warnings

### ISSUE THREAD

**Issue by Lukellmann** [mozilla/pdf.js#13259]
I'm using the Display Layer of PDF.js and was wondering if there is a way to programmatically respond to warnings that appear in the console like  `Warning: Indexing all PDF objects` or `Warning: Unimplemented widget field type "Sig", falling back to base field type.`, so I can inform the user that something might have gone wrong.      
I tried to set `stopAtErrors` for `getDocument()` to `true` but it did not help there...

**Comment by Snuffleupagus** [comment]
> [...] was wondering if there is a way to programmatically respond to warnings that appear in the console

No, since messages printed with `warn` (or `info`) appear *only* in the console.[1] The reason is that these are *not* used for breaking errors, but rather only for information/debugging purposes.

For things that lead to *actual* errors, on the other hand, the following options exist:
 - Set an `onUnsupportedFeature` function to be notified of errors[2], but allow parsing/rendering to continue; see https://github.com/mozilla/pdf.js/blob/fd82adccfa409f9b2cc72ad2cb8555bd2aa68b36/src/display/api.js#L542-L547
 - Pass `stopAtErrors` when calling `getDocument`, in which case all errors will be breaking ones and parsing/rendering stops.

---
[1] Note that you can pass a `verbosity`-level, when calling `getDocument`, to disable printing of warning messages; please see https://github.com/mozilla/pdf.js/blob/fd82adccfa409f9b2cc72ad2cb8555bd2aa68b36/src/display/api.js#L134-L135

[2] The following is an example, purposely simplified, of how to use `onUnsupportedFeature`
```javascript
const loadingTask = getDocument(...);

loadingTask.onUnsupportedFeature = function(featureId) {
  // Here you can add custom error notifications.
};

const pdfDocument = loadingTask.promise;
...
```
