### ISSUE TITLE
some fonts are invisible

### ISSUE THREAD

**Issue by karikera** [mozilla/pdf.js#13255]
Attach (recommended) or Link to PDF file here:
[testtext.pdf](https://github.com/mozilla/pdf.js/files/6329159/testtext.pdf)

Configuration:
- Web browser and its version: any browser
- Operating system and its version:
- PDF.js version: pdfjs-dist@2.7.570 + webpack
- Is a browser extension: no

Steps to reproduce the problem:
print the pdf
I use [jsPDF](https://github.com/MrRio/jsPDF) to generate the pdf + a custom font called ["휴먼둥근헤드라인"](https://t1.daumcdn.net/cfile/blog/2725593F5260F78F02?download)

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/6016498/115112491-bb4f3680-9fc0-11eb-8976-51b98ca3f8b3.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/6016498/115112683-97402500-9fc1-11eb-9793-bcf0493fd53b.png)

 Output
```
Warning: getHexString - ignoring invalid character: 198
util.js:367 Warning: getHexString - ignoring invalid character: 27
util.js:367 Warning: getHexString - ignoring invalid character: 204
util.js:367 Warning: getHexString - ignoring invalid character: 180
util.js:367 Warning: getHexString - ignoring invalid character: 47
util.js:367 Warning: getHexString - ignoring additional invalid characters.
util.js:367 Warning: loadFont - preEvaluateFont failed: "FormatError: Descendant fonts are not specified".
util.js:367 Warning: Error during font loading: Font "F15" is not available
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)

**Comment by Snuffleupagus** [comment]
Please note that your document is *sufficiently corrupt* that even Adobe Reader, i.e. the PDF reference implementation, refuses to open it. (If you want PDF viewers to open/render your document correctly, please make sure that it's actually valid.)

**Comment by Snuffleupagus** [comment]
The bug, in the PDF document itself, can be seen highlighted in the screen-shot below:

![bad-name](https://user-images.githubusercontent.com/2692120/115115444-d1df9880-9f94-11eb-84c2-bd17c11b21d7.png)

That's obviously *not* a valid `Name`, and we simply break at the `<` character which results in the next invocation of `Lexer.getObj` trying to read a hexadecimal-string (thus leading to part of the font Dictionary being skipped).

Naively, this would be simple to fix and I've even got a patch locally (with the caveat that I've not run any tests).
However, we need to be *very* careful about making changes to this part of the code just to fix a *corrupt* document, since we obviously don't want to break valid ones in the process; hence I'll need some time, to think this through properly, before submitting a patch.

**Comment by karikera** [comment]
Thanks for explaining.
The browser could open it, so I thought it was in the normal range.
