### ISSUE TITLE
"export 'PDFLinkService' was not found in 'pdfjs-dist/es5/web/pdf_viewer'

### ISSUE THREAD

**Issue by LYL98** [mozilla/pdf.js#13252]
Attach (recommended) or Link to PDF file here:
npm run buid   vue-pdf  warning
Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by LYL98** [comment]
![image](https://user-images.githubusercontent.com/47982531/115012060-f0388c00-9ee1-11eb-9065-262f0dfee8be.png)

**Comment by LYL98** [comment]
![image](https://user-images.githubusercontent.com/47982531/115012113-01819880-9ee2-11eb-93aa-68b91c7ffac2.png)

**Comment by LYL98** [comment]
![image](https://user-images.githubusercontent.com/47982531/115012213-237b1b00-9ee2-11eb-9dd4-5be307d2c5ed.png)
![image](https://user-images.githubusercontent.com/47982531/115012227-2a099280-9ee2-11eb-81a3-d121a121c804.png)
![image](https://user-images.githubusercontent.com/47982531/115012238-2d9d1980-9ee2-11eb-845f-9980a174f13c.png)

**Comment by Snuffleupagus** [comment]
> npm run buid vue-pdf warning

We don't know anything about "vue-pdf" here, or other projects/frameworks, and consequently we cannot provide support for that.

---

Furthermore, this issue is missing *every single* piece of information required to be actionable/valid!
You need to actually fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) with *all* of the requested information, since screen-shots alone aren't useful.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
