### ISSUE TITLE
Question: button icon color changed in code?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#13262]
Configuration:

Web browser and its version:
Operating system and its version: Chrome Version 89.0.4389.128 (Official Build) (64-bit)
PDF.js version: "2.6.347"
Is a browser extension: no

Question:
the new viewer follows the o.s theme whether light or dark

i noticed there are only one set of icon files for both dark and light. 

i wish to confirm if 
the colors are changed programmatically? since the colors of the icons in buttons change based on the os theme. please see attached.
![ss2](https://user-images.githubusercontent.com/3955470/115229675-e9aa4e80-a145-11eb-891e-0a7c8f0b681a.png)
![ss1](https://user-images.githubusercontent.com/3955470/115229679-ea42e500-a145-11eb-8f35-56603323d95a.png)

**Comment by Snuffleupagus** [comment]
The best guess is that PR #12625 is what you're looking for here, but as (almost always) your issue lacks too many details that it's difficult know for certain. If that's not it, then this issue is most likely already covered by http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

As mentioned, I don't know how many times before, you must provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue; otherwise you're just wasting peoples time.

**Comment by chitgoks** [comment]
hello @Snuffleupagus , updated the post to include the configuration. i will check what you commented. thank you.

**Comment by Snuffleupagus** [comment]
> PDF.js version: "2.6.347"

That version is no longer supported, please find the current releases at https://mozilla.github.io/pdf.js/getting_started/#download
In this case, that's especially relevant since PR #12625 is only included in PDF.js versions `2.7.570` and above.

> [...] updated the post to include the configuration.

It'd be nice if the STR section was clearer as well, since it's difficult to tell if you simply want to switch between existing themes (already explained) or if you want to set *custom* colours (in which case you'll have to modify `web/viewer.css` manually).

**Comment by chitgoks** [comment]
this is indeed a mistake on my part that i did not put more detail on what i want to do. 

i wish to add a custom button and icon to the viewer. so i asked if the icon svg color were set programmatically based on os theme because i omly see  1 svg file of every icon in the viewer's buttons.

**Comment by Snuffleupagus** [comment]
> i wish to add a custom button and icon to the viewer. so i asked if the icon svg color were set programmatically based on os theme because i omly see 1 svg file of every icon in the viewer's buttons.

That wasn't at all clear above; however in that case the suggestion would be to look at how the existing buttons/icons are handled in https://github.com/mozilla/pdf.js/blob/master/web/viewer.css and also at how the `.svg` files are structured, and simply follow the same pattern here.

Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum, and that we cannot provide detailed support for custom implementations/functionality.

**Comment by chitgoks** [comment]
thanks. yes you are right. im aware this is not a support forum for custom.implementation.

my question is about how those icons in the buttons change to appropriate color bas3d on os theme.

thank you for the suggestion.  🙏
