### ISSUE TITLE
Type declaration are missing in prebuilt files for the viewer API

### ISSUE THREAD

**Issue by stof** [mozilla/pdf.js#13267]
The prebuilt files include `web/pdf_viewer.js` with some viewer APIs. Those are missing from type declarations.

**Comment by Snuffleupagus** [comment]
*This issue is a little light on the details, please remember to *always* fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.*

---

Please note that the *official API* is only what's documented in https://github.com/mozilla/pdf.js/blob/master/src/display/api.js, for which TypeScript declarations are available in `pdfjs-dist`; see https://github.com/mozilla/pdfjs-dist/tree/master/types

> The prebuilt files include `web/pdf_viewer.js` with some viewer APIs.

Assuming that you're referring to https://github.com/mozilla/pdfjs-dist/tree/master/web, then those interfaces are *probably not* at the same stability level as the official API.

Furthermore, please note that it'll be *solely* up to TypeScript users themselves to help maintain/improve the definitions (all work so far has been done by TypeScript users), since the PDF.js library is still a *JavaScript* project and the core contributors cannot be assumed to be familiar with TypeScript.

**Comment by stof** [comment]
Well, AFAICT, the types are autogenerated from the JSDoc, not maintained manually. The issue is that this generation runs only for the `src/` folder, not for exported files from `web/` (see the `types` task in the gulpfile).

> Assuming that you're referring to https://github.com/mozilla/pdfjs-dist/tree/master/web, then those interfaces are _probably not_ at the same stability level as the official API.

Even if they are not at the same stability level, shipping type definition for them would make them a lot easier to use, as IDEs would then be able to provide autocompletion for them based on the type definitions (and typescript would allow analyzing the code statically). The fact that this API is more experimental is something that can be documented in places talking about the import of that file (this file requires a separate import anyway before being able to use it).

**Comment by Snuffleupagus** [comment]
> Well, AFAICT, the types are autogenerated from the JSDoc, not maintained manually. The issue is that this generation runs only for the `src/` folder, not for exported files from `web/` (see the `types` task in the gulpfile).

That does *not* at all, in any way, change the fact that as already mentioned TypeScript users *themselves* will have to do the necessary work to make any of this happen!
