### ISSUE TITLE
Document edits performed by embedded JavaScript fail

### ISSUE THREAD

**Issue by leezu** [mozilla/pdf.js#13269]
Firefox 88 release notes specify "support JavaScript embedded in PDF files". Attached document uses JavaScript to automate certain tax calculations on common US tax forms. Unfortunately, pdf.js fails to input the calculated results into the fields.

PDF file: [f1040v2.pdf](https://github.com/mozilla/pdf.js/files/6339403/f1040v2.pdf) from https://www.pdftax.com/

Configuration:
- Web browser and its version: Firefox 88

Steps to reproduce the problem:
1. On page 1, click " I have read and agree to the terms of the Pdftax Software License Agreement" checkbox
2. On page 1, enter any number or letter in "Enter code in box to the right to get the printable and fileable version"

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/946903/115310416-51b85f00-a15d-11eb-99a3-5a6587c36e95.png)
via https://code-industry.net/masterpdfeditor/ on Linux (though Adobe Reader on Windows would produce the same result)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/946903/115310508-7280b480-a15d-11eb-944d-0050be5c350f.png)

The box in the lower left corner was not filled the number entered in step 2.
The same is true for any tax calculations performed in the form on the following pages.

**Comment by calixteman** [comment]
The issue is mostly a dup of #13132, so the pdf can be open in Firefox 89 (beta) or https://mozilla.github.io/pdf.js/web/viewer.html.
There few others bugs in it:
  - `app.alert({cMsg...}` doesn't work correctly;
  - some text fields are not updated because they have the same name as an other field;
  - `valueAsString` is not set before running `calculate` actions.
