### ISSUE TITLE
Application Hangs In Chrome Version - 90.0.4430.85  - Print feature

### ISSUE THREAD

**Issue by imoitra007** [mozilla/pdf.js#13281]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  Google Chrome **Version 90.0.4430.85 (Official Build) (64-bit)**
- Operating system and its version: Windows 10
- PDF.js version: "pdfjs-dist": "^2.7.570",
- Is a browser extension:

Steps to reproduce the problem:
1.  From our application, we open a new window which is showing the PDF.
2.  Click on "Print" Icon. Print Dialog box will Open
3.  Close the new Window.
4.  On closing the new window, our application hanged.

This above issue is not happening in 
- Google Chrome Version 89.0.4389.128 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: "pdfjs-dist": "^2.7.570",

What is the expected behavior? (add screenshot) : Our application should not hanged.

What went wrong? (add screenshot)
What I observed is pdf.js using Google print Cloud. This feature has been depreciated in 2021 which might cause the issue

![image](https://user-images.githubusercontent.com/42399766/115674509-594d5300-a36b-11eb-99d5-80baf3dd4736.png)

**Comment by Snuffleupagus** [comment]
> What I observed is pdf.js using Google print Cloud. This feature has been depreciated in 2021 which might cause the issue

Unfortunately "Google print Cloud", whatever that may be, isn't something that the PDF.js library can provide support for. (Even more so, when by your own account, it's apparently not even supported by Google any more.)
Hence this issue unfortunately doesn't seem actionable/valid *here*, since we cannot support third-party services.

Furthermore, since we cannot even reproduce this without access to "Google print Cloud", please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
