### ISSUE TITLE
How to hide the page number counter automatically generated in the upper right corner

### ISSUE THREAD

**Issue by jamesjianpeng** [mozilla/pdf.js#13302]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  90.0.4430.85
- Operating system and its version: window 10
- PDF.js version: 2.7.570
- Is a browser extension:

Steps to reproduce the problem:
![企业微信截图_16195078215191](https://user-images.githubusercontent.com/22436891/116210717-b5eaac80-a775-11eb-9cd6-2a9f90136d12.png)

This element has no class name and ID name

**Comment by Snuffleupagus** [comment]
As already explained in the README, this is a PDF *viewer* and not a PDF editor: 
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.

What you're asking about here is (arbitrary) editing of PDF documents, so you may have opened this issue in the wrong repository!?

> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *required*, since as-is this issue isn't really actionable/valid.

> PDF.js version: 2.7.0

That *exact* version number has never existed.

**Comment by jamesjianpeng** [comment]
The package of the production environment I use：
```   
 <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/es5/build/pdf.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/pdfjs-dist@2.7.570/es5/web/pdf_viewer.js"></script>
```

**Comment by jamesjianpeng** [comment]
I want to know what the numbers in the upper right corner mean

**Comment by timvandermeij** [comment]
PDF.js doesn't generate anything automatically, it just displays whatever is in the PDF file.
