### ISSUE TITLE
Presentation mode closes after few seconds

### ISSUE THREAD

**Issue by Af0x** [mozilla/pdf.js#13311]
Configuration:
- Firefox 88.0
- Fedora 33
- PDF.js version: 2.6.347

Steps to reproduce the problem:
1. Klick on presentation icon and wait few seconds

What is the expected behavior?
Presentation mode should be preserved.

What went wrong?
Without any further action the presentation mode closes.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Firefox 88.0
> Fedora 33

WFM, when using Firefox Nightly 90 (with its *built-in* PDF Viewer) on Windows.

Most likely this is an OS and/or browser bug, rather than a bug in the PDF.js viewer, since otherwise it should be consistently broken everywhere. Hence this unfortunately doesn't look like an actionable/valid issue *here*.

**Comment by Af0x** [comment]
Thanks for the answer. I opened an issue at the OS bugtracker: https://bugzilla.redhat.com/show_bug.cgi?id=1954703
