### ISSUE TITLE
Files for legacy browsers with not es5 code in 2.7.570

### ISSUE THREAD

**Issue by diegonjin** [mozilla/pdf.js#13334]
Attach (recommended) or Link to PDF file here:
https://github.com/mozilla/pdfjs-dist/blob/master/legacy/build/pdf.js

Configuration:
- Web browser and its version: **Legacy browsers like IE11**
- PDF.js version: 2.7.570

Steps to reproduce the problem:
1. Dist files for legacy browsers has code that is not es5 (like arrow functions). This legacy files are correct in version 2.6.347

What is the expected behavior? Working correctly in legacy browsers

What went wrong? 
![image](https://user-images.githubusercontent.com/10774862/117026036-b4802d80-acfb-11eb-8fda-cdc6ed867bc9.png)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: **Legacy browsers like IE11**

As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE 11 is now *explicitly* unsupported regardless of build.

> Dist files for legacy browsers has code that is not es5 (like arrow functions). This legacy files are correct in version 2.6.347

`legacy` simply means older browsers, rather than ES5-compatible, and any browser/environment without array function support is now too old to be supported; please see e.g. issue #12976.

**Comment by diegonjin** [comment]
In pdfjs-dist package we found this code inside es5 folder. It is for this reason that I think that it should be compatible with IE11.

If it's really not ES5- compatible, maybe the folder name should be changed

**Comment by Snuffleupagus** [comment]
> It is for this reason that I think that it should be compatible with IE11.

As already mentioned, you need to refer to the FAQ for the *official* support information (rather than assuming support for particular browsers).

> If it's really not ES5- compatible, maybe the folder name should be changed

It's has already been renamed in later versions, which is what the previously linked issue is about (again, see issue #12976 which is fixed in PDF.js version `2.8.335` and above); please note that we won't be making changes to older releases.
