### ISSUE TITLE
Incorrect rendering of shading pattern +  stencil

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#13372]
Attach (recommended) or Link to PDF file here:
[PATTYP2.pdf](https://github.com/mozilla/pdf.js/files/6471935/PATTYP2.pdf)

Configuration:
- Web browser and its version: FF 88.0.1
- Operating system and its version: W10.0.19042.985
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. open file to display

What is the expected behavior? (add screenshot)
![grafik](https://user-images.githubusercontent.com/6665575/118114800-5e407800-b3e8-11eb-860f-019f48a8eabf.png)

What went wrong? (add screenshot)
![grafik](https://user-images.githubusercontent.com/6665575/118114841-6c8e9400-b3e8-11eb-8252-1517e5d76475.png)

(memo for me: when fixed, check the files in https://issues.apache.org/jira/browse/PDFBOX-1958 )

**Comment by brendandahl** [comment]
When we paint the image mask object we create the fill gradient with the size and transform of the image instead of the entire page. I'm seeing a similar issue in #11050, but that one is related to a grouped smask. To fix we'll either need to create the gradient with the original size/transform or transform the gradient so it translates and scales to the correct offset. It will probably be better to translate/scale, since then we draw the gradient on the smaller clipped canvas.
