### ISSUE TITLE
Allowing rendering of all PDF pages and holding them in memory

### ISSUE THREAD

**Issue by lhl2617** [mozilla/pdf.js#13398]
I've read the FAQ, specifically [this question](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#i-want-to-render-all-100-pages-in-a-document-at-a-high-resolution-is-it-a-good-idea).

I think the fact that it is an FAQ does mean that this gets requested often? A quick search on Google of the query "pdfjs render all pages" does bring some hacky solutions up.

I understand that this isn't really a good idea--but I do have a use case. I am building a VSCode extension for LilyPond, which is basically LaTeX for music. LilyPond embeds links into the PDF that refers to the source code, which allows the implementation of point-and-click from the PDF to the code. The reverse however, is the challenge. I need the whole PDF in memory to efficiently search via the PDF->code references, which isn't possible because PDFjs only renders visible pages and hence I only have the PDF->code references for visible pages. I understand in LaTeX SyncTeX is used with a nicer solution, which [LaTeX Workshop](https://github.com/James-Yu/LaTeX-Workshop) uses (as an aside, they used a heavily-hacked version of PDFjs because the API is too limiting).

I'd love to see options to render and whole the entire PDF in memory. Is this possible? If no one is up for it, I'd love to be pointed to where the code is so I can make my own changes.

**Comment by lhl2617** [comment]
Seen: https://github.com/mozilla/pdf.js/issues/11179#issuecomment-535473979

**Comment by Snuffleupagus** [comment]
> I need the whole PDF in memory to efficiently search via the PDF->code references, which isn't possible because PDFjs only renders visible pages and hence I only have the PDF->code references for visible pages.

Given the overall lack of details in this issue it's unfortunately quite difficult to really understand the problem fully, since there *may* be other ways of accessing data in a PDF document without having to render the *entire* document first.[1]

Note how e.g. the search function is implemented [in the demo viewer](https://github.com/mozilla/pdf.js#online-demo), since it doesn't require the entire document to be rendered. Another example is PDF documents with internal links, try e.g. http://mirrors.ctan.org/info/lshort/english/lshort.pdf, which also work without the destination page having been rendered first.

> I've read the FAQ, specifically [this question](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#i-want-to-render-all-100-pages-in-a-document-at-a-high-resolution-is-it-a-good-idea).
> [...]
> I'd love to see options to render and whole the entire PDF in memory.

Sorry, but that simply won't happen for the reasons outlined in the FAQ, since we definitely don't want to provide users with options that are performance footguns.[2]

> Is this possible? If no one is up for it, I'd love to be pointed to where the code is so I can make my own changes.

Of course it's *technically possible*, however we purposely don't want to spell out how since then many users will simply implement it without understanding/thinking about the implications.

---
[1] Please remember to *always* fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue. Furthermore, in this case the following might also be relevant https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

[2] Experience has shown, with other "bad" and since removed options, that users are unfortunately quite likely to use certain options without fully understanding/realizing the consequences of doing so (e.g. by just copying from some third-party example).

**Comment by Creling** [comment]
> Not really. You can count yourself: a letter page size is 816⨉1056px at 96DPI (and if you have a HiDPI display, multiply each dimension by window.devicePixelRatio, e.g., 2), so you will need a canvas that takes up 816⨉1056⨉4 = 3,446,784 bytes (don't forget to multiply that by e.g., 2⨉2 = 4 if it's a HiDPI display). This requires you to allocate 3.5Mb (or 14Mb) per page. You need a decent amount of memory to hold the 100 canvases, and it does not count the time that is spent on rendering them.

It is 2021 now, 350Mb is not a big number anymore, in contrast, the latency caused by rendering pages matters and reduce user experiences most. It will be great if we could render all pages when init. At least it should be a option for users who prefer a good experience to saving some memory. 

I try to force render all pages at the beginning, however, pdf_view.js will still render pages when page number changing.

**Comment by Creling** [comment]
> I'd love to see options to render and whole the entire PDF in memory. Is this possible? If no one is up for it, I'd love to be pointed to where the code is so I can make my own changes.

The code snippet below will force render all pages. though pdf_view.js will render them again when page number changing.
```Js
this.pdfViewer._pages.forEach((pageView: any) => {
    this.pdfViewer.renderingQueue.renderView(pageView)
});
```

**Comment by evanjmg** [comment]
please reopen this. This is important in order todo custom annotations and measurements across many pages.

**Comment by ainp1** [comment]
I agree that this needs to be reopened, it's very frustrating to be arbitrarily limited in the ability to do a certain function because not everyone would understand it may cause slowdowns or issues if used all of the time.

**Comment by paalg** [comment]
I would love this issue to be opened again! I work on a system in a company that actively uses forms in PDF.js, and it is a huge problem for us that not all pages are in memory. The biggest problem is parts of forms filled out are removed when user scrolls down, and we loose information.

**Comment by calixteman** [comment]
> I would love this issue to be opened again! I work on a system in a company that actively uses forms in PDF.js, and it is a huge problem for us that not all pages are in memory. The biggest problem is parts of forms filled out are removed when user scrolls down, and we loose information.

Normally, the data shouldn't be lost when scrolling, if it is then you should really file a bug with a test case.

**Comment by MikiVanousek** [comment]
Is there a way I can use this code snippet to precompile a PDF in Firefox? It would considerably increase my productivity.

> > I'd love to see options to render and whole the entire PDF in memory. Is this possible? If no one is up for it, I'd love to be pointed to where the code is so I can make my own changes.
> 
> The code snippet below will force render all pages. though pdf_view.js will render them again when page number changing.
> 
> ```js
> this.pdfViewer._pages.forEach((pageView: any) => {
>     this.pdfViewer.renderingQueue.renderView(pageView)
> });
> ```
