### ISSUE TITLE
[Feature Request] Use inline workers

### ISSUE THREAD

**Issue by 101arrowz** [mozilla/pdf.js#13413]
Currently, PDF.js can use worker threads to accelerate PDF processing; however, this causes issues for people using bundlers because bundlers don't pick up files passed to `new Worker()` in most cases. Therefore, I suggest using inline workers, which dynamically generate worker URLs with `URL.createObjectURL(new Blob([javascriptCode]))`.

There are two ways to implement inline worker functionality.
1. Create a worker string as part of a build step, embed it in the JavaScript, and generate the worker URL at runtime.
2. I have personally implemented a technique for creating workers from a function without any build steps. Named [`isoworker`](https://github.com/101arrowz/isoworker), it can serialize functions with external dependencies and execute them asynchronously. I've implemented a similar technique in [`fflate`](https://github.com/101arrowz/fflate), which uses them to parallelize ZIP compression, and it's proven to be stable, effective, and performant from my tests. (Side note: I'm pretty sure `fflate` is faster than FlateStream, and it's already being used in `jsPDF`, but I can create a new issue for that if you'd like.)

The benefit of dynamically generating the worker string at runtime, as done in `isoworker`, is that there is no duplication of code if you use the same function/variable/object/etc. in the main thread as you do in the worker thread. However, generating a worker string in a build step does not incur the slight (sub-millisecond) runtime cost of using `isoworker`.

Whichever method is chosen, it will remove some of the logic used to create a fake worker and make it impossible to accidentally use fake workers in production. If there is interest, I can try to draft a PR with inline workerization, but I'd like to know your opinions first.

**Comment by Snuffleupagus** [comment]
> this causes issues for people using bundlers because bundlers don't pick up files passed to `new Worker()` in most cases.

We don't/can't really support various bundlers here; however it should be possible to inform bundlers about the path to the `pdf.worker.js` file, right?

Please note that it's also possible to load the Worker is a couple of different ways, not reliant directly on a `new Worker()`-call in the PDF.js API code itself, by providing either the:
 - `GlobalWorkerOptions.workerPort` option, see https://github.com/mozilla/pdf.js/blob/faf6b109392e6f69a9063d050d8682c3a8aa12fd/src/display/worker_options.js#L17-L19
 - `worker` option, when calling `getDocument`, see https://github.com/mozilla/pdf.js/blob/faf6b109392e6f69a9063d050d8682c3a8aa12fd/src/display/api.js#L131-L132

> Therefore, I suggest using inline workers, which dynamically generate worker URLs with `URL.createObjectURL(new Blob([javascriptCode]))`.

Sorry, but this really does *not* seem like a good idea for e.g. the Firefox PDF Viewer (which is the *primary* reason for this library existing in the first place).
The `pdf.worker.js` file is currently around 1.5 MB in size, and inlining all of that code as a string in the `pdf.js` file seems like it'd have a very non-desirable impact on memory usage (since the "worker"-code would be loaded from the `pdf.js` file rather than its *separate* `pdf.worker.js` file). It also seems like there may be some more run-time overhead, associated with the worker-initialization (e.g. the need to create a very large `Blob), which again we *really* don't want in e.g. Firefox.

> The benefit of dynamically generating the worker string at runtime, as done in `isoworker`, is that there is no duplication of code if you use the same function/variable/object/etc.

Note that the PDF.js code-base is already structured to minimize the amount of code which appears in both the `pdf.js` and `pdf.worker.js` files. 

---

The FlateStream discussion seems mostly unrelated *here*, but please note that we'd need a *very* convincing argument for replacing working code. (Also, we know nothing about "jsPDF" here, since despite the similar names there's no relation to this project.)

There's always a regression risk involved with any larger code change, and /FlateDecode isn't exactly uncommonly used in PDF documents :-)
If we change to a third-party dependency, rather than code that we maintain directly, in the event that there's ever a bug somewhere in that code we'd be reliant upon a third-party to get it fixed (rather than being able to handle that ourselves).
We'd also need to know that it doesn't regress *any* existing PDF.js test-case, see https://github.com/mozilla/pdf.js/wiki/Contributing. Furthermore, we'd need benchmarking results (using relevant PDF documents) done within the PDF.js project *itself*, see https://github.com/mozilla/pdf.js/wiki/Benchmarking-your-changes, to show a *clear* and statistically significant performance improvements.

---

All-in-all, given that the Firefox PDF Viewer is the main development target, I don't think that want to make larger and/or more invasive changes to the Worker-loading code here.
