### ISSUE TITLE
getAnnotations() not returning certain annotations

### ISSUE THREAD

**Issue by hedgybeats** [mozilla/pdf.js#13426]
I added some 'tick' and 'cross' annotations / icons to my PDF via Adobe Acrobat Pro:
[tickcross.pdf](https://github.com/mozilla/pdf.js/files/6530577/tickcross.pdf)

When calling getAnnotations() on this page, nothing is returned... I am not sure if this is expected behavior or not.
Is there another way to get the annotation info about these annotations? Any help would be greatly appreciated...

**Comment by Snuffleupagus** [comment]
> I added some 'tick' and 'cross' annotations / icons to my PDF via Adobe Acrobat Pro:

Those are not actually Annotations, as found in the `/Annots` array of the page, but rather included as a normal `/XObject`-stream in the page resources (rendered within an Optional Content Group in this case).
Hence this cannot work like you expect here, and this issue is unfortunately INVALID.

*For future reference:* When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since in general those details matter.

**Comment by hedgybeats** [comment]
@Snuffleupagus Thank you very much for the feedback and clarification!
