### ISSUE TITLE
When pdf pages is too large, how can I load 10 pages not all pages at first time?

### ISSUE THREAD

**Issue by lxinran** [mozilla/pdf.js#13439]
### The pdf pages is 10000, how can I load 10 pages every time: load 10 pages at first time and load next  10 pages  when  scroll to the bottom?

1. I tried PDFViewer, but it cannot implemente for it will load all pages at first when call the function:
`PDFLib.getDocument(src).promise.then((pdfDoc) => {
PDFViewer .setDocument(pdfDoc)
}`
2. I also tried PDFSinglePageViewer：it will show a page every time, but PDFSinglePageViewer is extend BaseViewer, BaseViewer is load all pages at first time? And when call the findcontroller's find function it will find text in all pages, not the visible page.
![image](https://user-images.githubusercontent.com/20336944/119598975-a1521080-be16-11eb-9f9a-a7fa30417fba.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is missing too much information to really be actionable/valid.

---

> how can I load 10 pages every time: load 10 pages at first time and load next 10 pages when scroll to the bottom?

There is not, nor will there be, a feature that does exactly this. With `disableAutoFetch` set (see below), the pages will be loaded/rendered *one at a time* as they become visible in the viewer (which I'm assuming this issue is about).

> BaseViewer is load all pages at first time?

Yes, all pages are *loaded* by default, however they're not actually rendered until they become visible in the viewer.

In order to only load pages as they become visible in the viewer, you need to set the `disableAutoFetch` (and `disableStream`) option when calling `getDocument`; please refer to https://github.com/mozilla/pdf.js/blob/3da9f077be33d8689129d5ddb7915d7bf1f2a5fa/src/display/api.js#L173-L182

However, note that for very large PDF documents we're already not loading more than the visible pages; see https://github.com/mozilla/pdf.js/blob/3da9f077be33d8689129d5ddb7915d7bf1f2a5fa/web/base_viewer.js#L579-L581

> And when call the findcontroller's find function it will find text in all pages, not the visible page.

Of course it works for all pages, however it might be a little bit slow for very large documents, since searching only working for the current page would render it useless in general (if you know there's a match on page there's not really much point in searching).
