### ISSUE TITLE
Backgroundimage is not rendered

### ISSUE THREAD

**Issue by gertot** [mozilla/pdf.js#13441]
Attach (recommended) or Link to PDF file here:
[backgroundimage_not_visible_anonymisiert.pdf](https://github.com/mozilla/pdf.js/files/6544725/backgroundimage_not_visible_anonymisiert.pdf)

Configuration:
- Web browser and its version: Chrome Version 90.0.4430.212 (Offizieller Build) (x86_64)
- Operating system and its version: Windows 10, MacOs BigSur
- PDF.js version: 2.5.207
- Is a browser extension: no

Steps to reproduce the problem:
1. open the document in demo viewer.js
2.

What is the expected behavior? (add screenshot)
The backgroundimage gets rendered like in Acrobat Reader
<img width="1348" alt="Bildschirmfoto 2021-05-26 um 09 44 21" src="https://user-images.githubusercontent.com/1286150/119621970-00a82480-be07-11eb-8fed-f74ac04b840b.png">

What went wrong? (add screenshot)
Backgroundimage is not rendered only some  text
<img width="987" alt="Bildschirmfoto 2021-05-26 um 09 43 57" src="https://user-images.githubusercontent.com/1286150/119621938-fab24380-be06-11eb-92ac-4ecb2c9334b1.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This looks like a pattern-related bug, rather than image-conversion related, and in up-to-date PDF.js versions (tested with PDF.js `2.9.273` in Firefox Nightly 90) at least *something* renders here:
![image_pattern](https://user-images.githubusercontent.com/2692120/119632784-6a2d3080-be11-11eb-83c1-972987a68192.png)

> PDF.js version: 2.5.207

Note that that that version is no longer supported, please find the current releases at https://mozilla.github.io/pdf.js/getting_started/#download
