### ISSUE TITLE
How to Get the number of pages in a PDF document

### ISSUE THREAD

**Issue by DJQTDJ** [mozilla/pdf.js#13440]
Attach (recommended) or Link to PDF file here:

 [02_QuiX端末認証・WhitePaper.pdf](https://www.ntt-west.co.jp/kiki/support/pdf/ud_detail.pdf)
------------------------------------------------------

Configuration:
- Web browser and its version: Google Chrome 92.0.4515.9（Official Build）canary （64 ビット） & IE11
- Operating system and its version: Windows 10 Pro 20H2
- PDF.js version:v2.7.570
- Is a browser extension: without extension

------------------------------------------------------

What is the expected behavior? (add screenshot)
 ＞　when I upload the pdf document, I want to show all pages on the website
 ＞　Is there any method to count the total number of pages in pdf file 
PS: I want to use forEach `like for {pdf.getPage(i)}`

------------------------------------------------------

```
                loadingTask.promise.then(function(pdf) {
                    // console.log('PDF loaded');

                    var pageNumber = 1;
                    pdf.getPage(pageNumber).then(function(page) {
                        // console.log('Page loaded');

```

**Comment by Snuffleupagus** [comment]
> when I upload the pdf document, I want to show all pages on the website

E.g. the `simpleviewer` example might be helpful, see https://github.com/mozilla/pdf.js/tree/master/examples/components

> Is there any method to count the total number of pages in pdf file

Use the `numPages` getter on the `PDFDocumentProxy`-instance returned by `getDocument`, see https://github.com/mozilla/pdf.js/blob/3da9f077be33d8689129d5ddb7915d7bf1f2a5fa/src/display/api.js#L680-L685

(Generally speaking, you should read the JSDocs in the API since those allow you to answer such questions yourself.)

**Comment by DJQTDJ** [comment]
@Snuffleupagus 

THANK YOU
