### ISSUE TITLE
Why the '?.' is in the file of build? such as 'annotationStorage?.getAll()'

### ISSUE THREAD

**Issue by wang12124468** [mozilla/pdf.js#13453]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: *
- Operating system and its version: *
- PDF.js version: 2.7.570
- Is a browser extension: no

Why the '?.' is in the file of build?

![image](https://user-images.githubusercontent.com/17714343/119944468-e1f08c00-bfc6-11eb-80b8-f916d843b7ea.png)

**Comment by Snuffleupagus** [comment]
> Why the '?.' is in the file of build?

Because that's valid JavaScript, see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

We *are* already providing builds for older browsers/environments, without those operators, note the two different headings at https://mozilla.github.io/pdf.js/getting_started/#download
