### ISSUE TITLE
Pdf arrow line annotations information seems different when retrieve via getAnnotations handler

### ISSUE THREAD

**Issue by roneytham-ideagen** [mozilla/pdf.js#13454]
Attach (recommended) or Link to PDF file here:
[Trace Monkey with arrows.pdf](https://github.com/mozilla/pdf.js/files/6559241/Trace.Monkey.with.arrows.pdf)

Configuration:

Web browser and its version: all browsers, tested with Chrome and Firefox latest versions.
Operating system and its version: tested in Windows 10
PDF.js version: current (online version)
Steps to reproduce the problem:
1. Visit https://mozilla.github.io/pdf.js/web/viewer.html
2. Upload the file above
3. Arrow annotations are showing correctly.
4. However, if we tried to retrieve the annotations information via **getAnnotations** , notice that the line coordinates information seems different from raw data (extract via iText library):
![image](https://user-images.githubusercontent.com/45581023/119950986-0bf97c80-bfce-11eb-9438-599413a7d727.png)

Any intention or reason that the values are different from what we got from raw Pdf?

**Comment by Snuffleupagus** [comment]
> Any intention or reason that the values are different from what we got from raw Pdf?

Yes, because we generally *normalize* (almost) all rectangles and bounding boxes since that simplifies both overall parsing and rendering; in this particular case note: https://github.com/mozilla/pdf.js/blob/2cc3b9635197f165599b6c1235eedd7ffc30a582/src/core/annotation.js#L2395-L2396

Simply normalizing a rectangle doesn't change what's rendered, just the order in which it renders, hence this is works as expected and we will *not* be making any changes to this code; closing as answered (or possibly even INVALID).

**Comment by roneytham-ideagen** [comment]
In this case how do we differentiate arrow annotation and line annotation after retrieving them via getAnnotations method? Since they are sharing the same annotationType.
