### ISSUE TITLE
Flickering when displaying PDF pages with render()

### ISSUE THREAD

**Issue by 1a7r0ch3** [mozilla/pdf.js#13493]
In my use case, PDF pages are displayed one after the others, using a mechanism along the lines of

```
pdfDoc.getPage(num).then(function(page) {
    // render PDF page into canvas context
   var renderTask = page.render(renderContext);
   ...
}
```
When changing from one page to another by calling the above with another `num` and same `renderContext`, there is an annoying flickering in the transition.

I tracked this down to the instruction `this.ctx.fillRect(0, 0, width, height);` within the `beginDrawing()` method of the `CanvasGraphics` object (file [canvas.js](https://github.com/mozilla/pdf.js/blob/3b502f7e07ce07d082128f61cb15b99cf03843df/src/display/canvas.js#L899)), which is called within `render()` (file [api.js](https://github.com/mozilla/pdf.js/blob/3b502f7e07ce07d082128f61cb15b99cf03843df/src/display/api.js#L3079)).

Is it possible to introduce an option within the API to prevent this? I suppose that such option could also be used to save some computations when the rendering context does not change.

Configuration:
- Web browser and its version: observed in both qutebrowser v2.2.0 and Mozilla Firefox 87.
- Operating system and its version: Arch Linux 5.11.15-arch1-2.
- PDF.js version: 2.8.335 (taken from https://www.jsdelivr.com/package/npm/pdfjs-dist?path=build&version=2.8.335).

Steps to reproduce the problem:
1. Display a page of a PDF on a canvas with above mechanism
2. Display another page : there is a flickering in the transition

Removing the instruction `this.ctx.fillRect(0, 0, width, height);` removes the flickering.

**Comment by Snuffleupagus** [comment]
> In my use case, PDF pages are displayed one after the others, using a mechanism along the lines of
> 
> ```
> pdfDoc.getPage(num).then(function(page) {
>     // render PDF page into canvas context
>    var renderTask = page.render(renderContext);
>    ...
> }
> ```

For future reference, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> When changing from one page to another by calling the above with another `num` and same `renderContext`, there is an annoying flickering in the transition.

Please note that it's *generally not* advisable to re-use the same `canvas` for multiple rendering operations, and note that e.g. the [demo viewer](https://github.com/mozilla/pdf.js#online-demo) creates a new `canvas` for each page.
Furthermore, since all pages of a PDF document cannot be assumed to have the exact same size, it might not be generally correct to render all pages with the *same* `viewport` (which re-using one renderContext would amount to).

> I tracked this down to the instruction `this.ctx.fillRect(0, 0, width, height);` within the `beginDrawing()` method of the `CanvasGraphics` object (file [canvas.js](https://github.com/mozilla/pdf.js/blob/3b502f7e07ce07d082128f61cb15b99cf03843df/src/display/canvas.js#L899)), which is called within `render()` (file [api.js](https://github.com/mozilla/pdf.js/blob/3b502f7e07ce07d082128f61cb15b99cf03843df/src/display/api.js#L3079)).
> 
> Is it possible to introduce an option within the API to prevent this?

Sorry, but adding such an option really does *not* seem like a good idea, since re-using the same `canvas` for multiple rendering operations without *fully* clearing it in between could possibly lead to rendering errors (e.g. part of the "old" page being visible).

Closing as WONTFIX, for the reasons mentioned above.

**Comment by 1a7r0ch3** [comment]
Thanks for the feedback.
