### ISSUE TITLE
The build path pdf_viewer fold is different by using yarn and npm

### ISSUE THREAD

**Issue by lxinran** [mozilla/pdf.js#13511]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version: Vue 3.0
- PDF.js version: "pdfjs-dist": "^2.7.570",
- Is a browser extension:NO

Steps to reproduce the problem:
1. using 'yarn install', the import path is 
` import {  PDFSinglePageViewer } from 'pdfjs-dist/es5/web/pdf_viewer'`
2.using 'npm install', the import path is 
` import {  PDFSinglePageViewer } from 'pdfjs-dist/web/pdf_viewer'`

What went wrong? (add screenshot)
the pdf_viewer path is different by using 'yarn install' and 'npm install', yarn command has es5, so how to make it same whenever using yarn or npm?

**Comment by Snuffleupagus** [comment]
> PDF.js version: "pdfjs-dist": "^2.7.570",
> [...]
> import {  PDFSinglePageViewer } from 'pdfjs-dist/es5/web/pdf_viewer'
>
> import {  PDFSinglePageViewer } from 'pdfjs-dist/web/pdf_viewer'

Those are *different* files, where the one from the `es5` folder is translated with Babel (and with polyfills included); it's really not clear how `yarn` vs `npm` is even relevant here since you can obviously simply choose which version to include!?

Furthermore, we only use `npm` in this library and thus cannot provide support for `yarn`. Finally, as-is this issue unfortunately isn't really actionable/valid; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
