### ISSUE TITLE
Program files created world writable

### ISSUE THREAD

**Issue by dittyroma** [mozilla/pdf.js#13512]
Steps to reproduce the problem:

Some program files and directories are created world writable. On a multiuser system this may allow an attacker to control behavior by modifying the files (eg a config file) or creating files in the directory (eg in a config directory). On Linux the umask should usually prevent this but it's not guaranteed. [Secure coding standards](https://wiki.sei.cmu.edu/confluence/display/c/FIO06-C.+Create+files+with+appropriate+access+permissions) recommend always specifying a restricted mode so files are secure in any environment. MITRE calls this [CWE-732](https://cwe.mitre.org/data/definitions/732.html), one of the [top 25 most dangerous](https://cwe.mitre.org/top25/archive/2020/2020_cwe_top25.html) vulnerabilities.

Findings are listed here:
https://lgtm.com/query/308122751628928618/
https://lgtm.com/query/8429440007276116881/

[This line](https://lgtm.com/projects/g/mozilla/pdf.js/snapshot/3525d09d63ce145bf6745daa2bc4346859b4017b/files/external/builder/builder.js?sort=name&dir=ASC&mode=heatmap#L197) in the preprocessor seems to output code world writable, possibly allowing an attacker to inject their own code. If any results in the gulpfile are creating config resources, they could allow an attacker to control behavior after install.

This came out of research with CodeQL.

What is the expected behavior?

Program files are created with secure permissions.

**Comment by Snuffleupagus** [comment]
> [This line](https://lgtm.com/projects/g/mozilla/pdf.js/snapshot/3525d09d63ce145bf6745daa2bc4346859b4017b/files/external/builder/builder.js?sort=name&dir=ASC&mode=heatmap#L197) in the preprocessor seems to output code world writable,

Generally speaking, linking directly to code within *this* repository usually simpler (since you get an inline preview that way):
https://github.com/mozilla/pdf.js/blob/e8fe0711eee655486aaa1689f50a7868ce75c5eb/external/builder/builder.js#L196-L198

Furthermore, please note that that's actually a standard method on the built-in "File system" module in Node.js; see https://nodejs.org/api/fs.html#fs_fs_writefilesync_file_data_options
If that method applies the "wrong" permissions, wouldn't that rather be a Node.js bug since we're simply calling the method with its default values!?

All-in-all, it's *slightly* difficult to understand if this issue was opened as a result of seeing an actual bug (given the use of the word "seems" above), since if this was just reported by some kind of tooling there's always a risk of false positives (we've seen that in other cases).

**Comment by dittyroma** [comment]
The Node.js defaults are functionally correct but not secure. That's a common situation. Secure by default is not the norm. It's your call whether you want to tighten it or not.

**Comment by Snuffleupagus** [comment]
Given that the PDF.js library is *primarily* intended for use in browsers, the actual file permissions should probably not really be all that relevant (as far as I can tell).
Furthermore, if you look at https://github.com/mozilla/pdf.js/blob/master/gulpfile.js there's *a lot* of similar Node.js methods used all over the place so I'm not sure if/how the particular case under discussion here is somehow "special*!?

All-in-all, unless there's an actual bug here, I'm not sure if we want to touch basically all of the build scripts here.
/cc @timvandermeij What's your opinion?

**Comment by dittyroma** [comment]
Just published an [`fs-secure`](https://www.npmjs.com/package/@dittyroma/fs-secure) module, drop in replacement for `fs` with secure modes by default. You could use it to get secure modes everywhere unobtrusively.

**Comment by Snuffleupagus** [comment]
> Just published a [`secure-fs`](https://www.npmjs.com/package/secure-fs) module, drop in replacement for `fs` with secure modes by default. You could use it to get secure modes everywhere unobtrusively.

Sorry; but replacing a *built-in* Node.js module with a third-party one, which also seem essentially unused by the larger community, unfortunately doesn't seem like a great idea (at least to me).
For one thing, there's no guarantees about future updates (we don't want to get stuck with old/abandoned packages) and generally speaking we always try to avoid adding dependences unless *absolutely* necessary.

Furthermore, as already mentioned, it's quite difficult to even see how this issue even matters in the context of browsers (which is where PDF.js is used).

**Comment by timvandermeij** [comment]
If we do this, we'll only consider patches that use the built-in Node.js modules since we want to limit the number of external packages we pull in if it can just be done with built-in logic. Moreover, we should then adjust _all_ call sites and not just one, most likely by making a simple wrapper function like we already have in the test utilities file.

Aside from that, I also don't really see a big risk here since Node.js is primarily used locally for building PDF.js, so only the final built assets should reach any production systems and the person that uploads the assets should then take care of setting the appropriate permissions. However, I agree that in general it's a good practice to reduce permissions as much as possible (i.e., set secure defaults), so if there is an _easy_ way to do this here we can consider a patch for this as far as I'm concerned.

**Comment by dittyroma** [comment]
Thanks for reviewing guys. I'm going to look into a patch and see if I can come up with something to propose.
