### ISSUE TITLE
Build error in my project

### ISSUE THREAD

**Issue by lintothomas77** [mozilla/pdf.js#13522]
I am facing an issue with my project build. What is the solution for this. 

![image](https://user-images.githubusercontent.com/50858823/121320484-d8eaad80-c92a-11eb-9caa-a03549a17afc.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable information provided.

While only a screen-shot is definitely not enough to create a *valid* issue, please also note that `vue` (whatever that is) isn't something that we can/will support here.

Finally, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
