### ISSUE TITLE
Looking for a PDF file with operation 88 paintImageXObjectRepeat to test.

### ISSUE THREAD

**Issue by bobsingor** [mozilla/pdf.js#13550]
This is not really an issue, but hope somebody can help me.

I'm looking for an example .pdf file that has operation 88: paintImageXObjectRepeat.

Can somebody help me with this?

**Comment by Snuffleupagus** [comment]
Simply using `git blame`, either locally or directly at GitHub, will eventually lead you to PR #4323 where that (custom) operator was introduced; the issues linked there should (hopefully) be of help.
Another quite simple way of finding examples would be to [replace this line](https://github.com/mozilla/pdf.js/blob/a4546e83c3d1b9b9ae3566466f018f8bada6c2e3/src/core/operator_list.js#L391) with the throwing of an `Error` and then run the reference tests with `gulp browsertest`; see also https://github.com/mozilla/pdf.js/wiki/Contributing

Closing as answered, since this isn't really a bug :-)

**Comment by bobsingor** [comment]
@Snuffleupagus Thanks! Appreciate it a lot
