### ISSUE TITLE
how to disable right click on pdf in iframes.  by using disable contextmenu im able to disable the right click outside the pdf but not on it. heres my code-- <html> <head>  </head> <body  onload="disableContextMenu();" oncontextmenu="return false">  <iframe id="fraDisabled"  src="https://wtf.tw/ref/duckett.pdf#toolbar=0&navpanes=0"  f#toolbar=0&navpanes=0" width="100%" height="600px"/> </iframe> </body> </html>

### ISSUE THREAD

**Issue by keerti1508** [mozilla/pdf.js#13620]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please provide a *proper* title when opening an issue, since using it to list your entire problem is not helpful here!

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable/valid.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
