### ISSUE TITLE
RegExp.prototype.unicode not allowed on some Android device

### ISSUE THREAD

**Issue by 296500148** [mozilla/pdf.js#13682]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:Android
- PDF.js version:2.9.359
- Is a browser extension:false

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
<img width="958" alt="屏幕截图 2021-07-06 203056" src="https://user-images.githubusercontent.com/43374341/124600444-4c83ca00-de99-11eb-8b31-abbd7ce790f8.png">

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't actionable/valid.

> Web browser and its version:
> Operating system and its version:Android

Most likely the browser version you're using is simply too old (however it's impossible to tell given the lack of information); please [refer to this FAQ entry](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), since https://caniuse.com/mdn-javascript_builtins_regexp_property_escapes suggests that this regular expression feature is indeed supported.
