### ISSUE TITLE
The svg text won't  show up in iPhone,but android phone works

### ISSUE THREAD

**Issue by samchild** [mozilla/pdf.js#13686]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: safari
- Operating system and its version: iphone x 14.6 or iphone8   13.6
- PDF.js version: pdfjs-2.9.359-legacy-dist
- Is a browser extension:

Steps to reproduce the problem:
1. download the input.pdf file
2.  using pdf2svg.js to generate svgs
3.the third page of the pdf file 

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/12930061/124710389-49d3b400-df2f-11eb-8a22-a40ace913095.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/12930061/124710476-6b34a000-df2f-11eb-86f7-395c09671909.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

attachments:
input pdf: 
[input.pdf](https://github.com/mozilla/pdf.js/files/6774879/input.pdf)

the result svg file:(please unzip)
[3.zip](https://github.com/mozilla/pdf.js/files/6774882/3.zip)

**Comment by Snuffleupagus** [comment]
> The svg text won't show up in iPhone,but android phone works

If it works in *one* platform/browser but not another, that'd generally suggest a bug in said platform/browser (rather than in the PDF.js library) since otherwise you'd really expect it to be *consistently* broken everywhere.

> using pdf2svg.js to generate svgs

Furthermore, as (clearly) mentioned in the FAQ the SVG back-end is *not* officially supported; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends
