### ISSUE TITLE
Localization does not work for sv (Swedish) in Edge (but does in Chrome that reports sv-SE).

### ISSUE THREAD

**Issue by sictransit** [mozilla/pdf.js#13689]
_Configuration:_
- Web browser and its version: 
   - **Edge**: 91.0.864.64 
   - **Chrome**: 91.0.4472.124
- PDF.js version:
   - Latest demo version: https://mozilla.github.io/pdf.js/web/viewer.html

_Steps to reproduce the problem:_
1. Open the demo viewer in Chrome
2. Open the demo viewer in Edge

_What is the expected behavior?_ 

The viewer should be localized, i.e. translated to Swedish.

_What went wrong? (add screenshot)_

The viewer is translated to Swedish in Chrome, but not in Edge.

_Request headers:_
  - Chrome: `Accept-Language: sv-SE,sv;q=0.9,en-US;q=0.8,en;q=0.7`
  - Edge: `Accept-Language: sv,en;q=0.9,en-GB;q=0.8,en-US;q=0.7`

The problem seems to be that the `l10n` folder does not contain an `sv` folder, but only an `sv-SE`.

**Comment by Snuffleupagus** [comment]
This does seem like more a Microsoft Edge issue, rather than a PDF.js one.
(In my testing, both Firefox Nightly 91.0a1 and Chrome Beta 92.0.4515.81 work just fine as-is.)

> The problem seems to be that the `l10n` folder does not contain an `sv` folder, but only an `sv-SE`.

That's how things have been since the very beginning of this project, hence I'm not sure that we necessarily want to make any changes here (since that *may* cause regressions elsewhere). There's basically three possible ways to address this:
 - Copying the `sv-SE` folder to a `sv` folder. This is undesirable for two reasons, first of all it'd unnecessarily increase the size of the viewer and secondly it'd add an undesirable maintenance overhead w.r.t. the `l10n`-folder.
 - Renaming the `sv-SE` folder to `sv` instead. This has, as already mentioned, the potential to basically fix things for one set of users while breaking things for another set of users; hence this feels problematic as well.
 - Configuring your *browser* to also accept an "sv-SE" locale (which at least in e.g. Firefox can be very easily done). This would definitely seem like the preferred solution to the issue.

**Comment by sictransit** [comment]
I agree that this is primarliy an Edge issue. However, on a few random machines with different Edge versions I've tried, `Accept-Language` is only `sv` (and does not include `sv-SE`). 

The main question might be whether to support the default Edge behaviour in pdf.js or not, as average users will not configure their browser to emit another language/region. Those who are able to, probably prefer English to Swedish anyway. 

For me, this is not an issue at all. I just wanted to let you know. If I bother fixing it, I'll probably just copy the folder to solve the minor problem.

**Comment by Snuffleupagus** [comment]
I suppose that another *possible* option could be to try and fixup these "incomplete" language codes, however I don't know if this is a desirable change (for the PDF.js project) and more importantly if this is actually a specification compliant way of handling language codes; e.g. something like https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-13689

**Comment by sictransit** [comment]
That would of course solve the problem, but as you say, is it the proper way of handling the issue and is it is a desirable change in PDF.js? I can't really tell. 

It is weird that Edge behaves differently than other browsers. There is also very little information/discussion on this topic. I spent an hour on google-fu and didn't find anything useful.

**Comment by nachoalcazar** [comment]
Same problem with Spanish:

this works OK

![image](https://user-images.githubusercontent.com/94051561/147833178-38a56b04-7004-4641-9f56-b7a79389c828.png)

(this NO WORKS)

![image](https://user-images.githubusercontent.com/94051561/147833183-5e600f90-0b10-453e-a2e7-d11d5031a69c.png)

Wouldn't it be a good solution to include a generic folder 'es', 'sv' ... with the generality of the language and thus avoid these problems?

![image](https://user-images.githubusercontent.com/94051561/147833244-1a0868ce-6f3d-46c0-bfe5-218c3e395a3e.png)

**Comment by timvandermeij** [comment]
The PR above _should_ have fixed this if I look at https://github.com/mozilla/pdf.js/pull/13696/files#diff-51a0dde82a8d1b56568a0375e28fccde02bc154a89b3cb92f34f090b5219b62aR100. Are you sure you're using the latest PDF.js version?

**Comment by nachoalcazar** [comment]
> The PR above _should_ have fixed this if I look at https://github.com/mozilla/pdf.js/pull/13696/files#diff-51a0dde82a8d1b56568a0375e28fccde02bc154a89b3cb92f34f090b5219b62aR100. Are you sure you're using the latest PDF.js version?

Yes, was fixed.
