### ISSUE TITLE
Filename on tab appears twice even if the Content Disposition name is same as the pdf title

### ISSUE THREAD

**Issue by symtalha14** [mozilla/pdf.js#13701]
Attach (recommended) or Link to PDF file here:
Unfortunately I cannot add the file here due to privacy reasons. But yes, I had downloaded this file from [Lucid](https://lucid.app)
Configuration:
- Web browser and its version:  Firefox 89.0.2
- Operating system and its version: Windows 10 Pro 64 bit
- PDF.js version: latest
- Is a browser extension: No

Steps to reproduce the problem:
1.
2.

What is the expected behavior? (add screenshot)
In case if the Content Disposition name and the PDF title are the same, it should show only one of them not both. Like it is done in Chrome's In-built Viewer.
![Screenshot (20)](https://user-images.githubusercontent.com/26308379/125011208-9c26e900-e085-11eb-8a25-1125719fb661.png)

What went wrong? (add screenshot)
![Screenshot (19)](https://user-images.githubusercontent.com/26308379/125011316-dbedd080-e085-11eb-8e2a-0aded4bed2ec.png)

 There are some files which have a Content Disposition header and name attached to them when they are downloaded from the web. For such files, PDF.js is showing the name twice in the document title (tab) even if the title and Content-disposition name are the same. 

I have tried adding a condition in the "if-block" in the _initializeMetadata function, and it is working as expected. Let me know if I should make a PR for the same.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Unfortunately I cannot add the file here due to privacy reasons.

Sorry, but that means that this issue isn't really actionable, since we'd need a test-case to e.g. consider accepting a patch.[1]

> PDF.js version: latest

*For future reference:* You should always provide a version *number*, since "latest" is ambiguous and thus not all that helpful.

> In case if the Content Disposition name and the PDF title are the same, it should show only one of them not both.

Looking at your screen-shots it shows the strings "toplinks_er" respectively "toplinks_er.pdf", which are definitely not identical (e.g. their lengths even differ).
Furthermore, it's not even clear (given the lack of a test-case) that this data comes from the Content-Disposition header and not e.g. from the /Info or /Metadata entries.

> I have tried adding a condition in the "if-block" in the _initializeMetadata function, and it is working as expected.

Given that various cases involved in that code and without a test-case to evaluate any changes, modifying that method *unfortunately* doesn't seem like a good idea here

Closing as WONTFIX for now; please feel free to re-open this issue when a test-case can be provided.

---
[1] Since it's not possible to review something, if you cannot actually test the "broken" PDF document. Experience have shown that unverified changes can lead to other issues, hence the need for us to be able to actually test things during review.

**Comment by symtalha14** [comment]
Alright, I'll try creating a sample test file on Lucid and attach it for your reference. 

> Looking at your screen-shots it shows the strings "toplinks_er" respectively "toplinks_er.pdf", which are definitely not identical (e.g. their lengths even differ).
> Furthermore, it's not even clear (given the lack of a test-case) that this data comes from the Content-Disposition header and not e.g. from the /Info or /Metadata entries.

I had verified this through the conditions that were written and my file's title was coming under Content disposition type. Anyways, I'll attach a file and you may have a look at it. Thanks.

**Comment by symtalha14** [comment]
This is a test PDF:
[Blank ERD.pdf](https://github.com/mozilla/pdf.js/files/6790853/Blank.ERD.pdf)

PDF.js Stable Version: 2.8.335

Please have a look. I tested  it again with my patch also and it works as expected.

**Comment by Snuffleupagus** [comment]
> This is a test PDF:
> [Blank ERD.pdf](https://github.com/mozilla/pdf.js/files/6790853/Blank.ERD.pdf)

Executing `PDFViewerApplication.metadata.get("dc:title")` in the console returns `"Blank ERD"`, whereas `PDFViewerApplication._docFilename` returns `"Blank.ERD.pdf"`; given that those strings are clearly *not* identical it's unfortunately not clear (at least to me) that the test-case actually demonstrates the issue as filed.

All-in-all, I'm sorry to say there doesn't really seems to be anything to fix here.

**Comment by symtalha14** [comment]
I would like to make a correction here. The actual problem is not the contentDisposition filename. Actually for some files we can get the "PDFTitle" from their meta information directly and for some there are only document titles available. Therefore, whenever the PDFTitle is available ( not null ), the set of conditions which control the file name are behaving a bit weirdly as they tend to combine the PDFTitle and the "document title" together.  Now, in every case, document title will be available and would mostly be the same as PDFTitle( if it is present). This leads to a duplication of filename.

` if (pdfTitle) {
      this.setTitle(
        `${pdfTitle} - ${contentDispositionFilename || document.title}`
      );
    } else if (contentDispositionFilename) {
      this.setTitle(contentDispositionFilename);
    }`

In the above code snippet as you can see, if pdfTitle is not null/undefined, the title becomes "PDFTitle-Document Title". ( assuming no content disposition filename). That is the cause of duplication in file name. Hope I make sense.

**Comment by symtalha14** [comment]
I know its seems a bit confusing but there is a fix for it and as Chrome and other Viewers are handling it well, I thought PDF.js could also have a patch for it.

**Comment by Snuffleupagus** [comment]
> Now, in every case, document title will be available and would mostly be the same as PDFTitle( if it is present).

Unfortunately the "would mostly be the same"-part cannot actually be assumed to hold *in the general case*, since there's nothing that says that the /Info or /Metadata titles need to have anything in common with the exact URL where a PDF file happens to be located; hence this issue is essentially INVALID.

> That is the cause of duplication in file name. Hope I make sense.

As mentioned in https://github.com/mozilla/pdf.js/issues/13701#issuecomment-877120367, there's not actually any *identical* strings here (only somewhat similar ones, in a particular case).

---

In the PDF.js default viewer, the idea is to *always* display the file name in the title and then (when it's available) supplement that with the document title from the /Info or /Metadata entries.
