### ISSUE TITLE
Setting up fake worker failed

### ISSUE THREAD

**Issue by padma88** [mozilla/pdf.js#13736]
Setting up fake worker failed: "Cannot load script at https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.worker.js"

How to handle this exeption

**Comment by Snuffleupagus** [comment]
> Setting up fake worker failed: "Cannot load script at https://cdn.jsdelivr.net/npm/pdfjs-dist@2.6.347/build/pdf.worker.js"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue contains no actionable information.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
