### ISSUE TITLE
"Requesting object that isn't resolved" error due to duplicate image during page.objs.get(name)

### ISSUE THREAD

**Issue by Soviut** [mozilla/pdf.js#13742]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: No browser, **Node 12.14.1**
- Operating system and its version: Ubuntu 20.04
- PDF.js version: latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a new Adobe Illustrator file.
2. Drag an image from your desktop onto the artboard.
3. Duplicate the artboard by selecting the artboard tool, select the artboard, copy and paste.
4. File > Save a Copy, choose PDF from the format dropdown
5. Use Acrobat Pro's "Content Panel" to ensure the images have the same id number.

Here is an example PDF  [2page-test.pdf](https://github.com/mozilla/pdf.js/files/6828465/2page-test.pdf)

Here is what it looks like in Acrobat's Content Panel
![image](https://user-images.githubusercontent.com/226882/125903988-8a74ffb3-79b1-410a-9303-e549d0829f31.png)

What is the expected behavior? (add screenshot)

I should be able to extract the image from either page using `page.objs.get(name)` without an error.

I find all the image object names using the following code.

```javascript
  const ops = await page.getOperatorList()
  const imageNames = ops.fnArray.reduce((acc, curr, i) => {
    if (
      [pdfjs.OPS.paintImageXObject, pdfjs.OPS.paintJpegXObject].includes(curr)
    ) {
      // console.log(ops.argsArray[i])
      acc.push(ops.argsArray[i][0])
    }
    return acc
  }, [])
```

I then use those names to get the image objects from the page.

```javascript
  const rawImages = imageNames.map((name) => {
      return [name, page.objs.get(name)]
  })
```

What went wrong? (add screenshot)

I get the error

> Error: Requesting object that isn't resolved yet g_d0_img_p1_1

I logged out the `page.objs` for each page and noticed this...

```
img_p0_1 PDFObjects {
  _objs: [Object: null prototype] {
    img_p0_1: {
      capability: [Object: null prototype],
      data: [Object],
      resolved: true
    }
  }
}
g_d0_img_p1_1 PDFObjects {
  _objs: [Object: null prototype] {}
}
```

The second page doesn't have a `g_d0_img_p1_1` key in its `page.objs`.

**Comment by Snuffleupagus** [comment]
> PDF.js version: latest

Please provide an actual version *number*, since "latest" is ambiguous and consequently not really helpful.

> I should be able to extract the image from either page using `page.objs.get(name)` without an error.

Note that *repeated* images will be cached on the document, rather than the page, level to improve both overall performance and memory usage; see PR #11912. Hence it seems that your problem is that you're trying to lookup some of the images in the wrong cache, and to fix this you need to:
 1. For image names starting with `"g_"`, fetch their data from `page.commonObjs`.
 2. For all other images, fetch their data from `page.objs`.

Note how the main PDF.js rendering code does that e.g. in https://github.com/mozilla/pdf.js/blob/4b2e0d0d01437ba5ba4ee3d901d8f8dd0ee03837/src/display/canvas.js#L2541-L2543

Closing as answered, since the above should be enough information for you to fix your code.

---

*For future reference:* Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Soviut** [comment]
Thanks! I've updated the version in the original post (it was `pdfjs-dist@2.8.335` for posterity)

I definitely did my due diligence with this before posting. I've gone through a lot of the example materials but didn't see anything regarding `page.commonObjs`. Now that I know, searching for it now yields results but they all relate to fonts.

I spent quite a bit of time going through the source code but was specifically avoiding frontend/canvas/rendering parts since I wasn't using them. I realize now that searching the source for `objs.get` might have got me on the right path.

Without knowing about `page.commonObjs` the expectation was that `page.objs` would contain a reference to the shared object on both pages. I'll adjust my code accordingly.
