### ISSUE TITLE
How to view byte[] array pdf 

### ISSUE THREAD

**Issue by im-nazmul** [mozilla/pdf.js#13758]
Hi,
 
I tired to view byte array data using pdf.js but it now working.  
I tried this way - this on my view. I just passed  base64sting to my custom.js
``
const url = '@Convert.ToBase64String(docBytes)';
``
And on custom js is tried this - 
``pdfjsLib.getDocument(url)......``

I've followed this [example ](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html) is not work for me , Now at this case what should I do?

Thank you
Nazmul Hossain

**Comment by Snuffleupagus** [comment]
> I tried this way - this on my view. I just passed base64sting to my custom.js
> `const url = '@Convert.ToBase64String(docBytes)';`
> And on custom js is tried this -
> `pdfjsLib.getDocument(url)......`
> 
> I've followed this [example ](https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html) is not work for me

That'd suggest that you didn't actually follow the example completely, since it contains this: https://github.com/mozilla/pdf.js/blob/07955fa1d31df62fd668a15f58cd40b29a82bd63/examples/learning/helloworld64.html#L40-L43

---

*Generally speaking:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't really actionable.

Please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by im-nazmul** [comment]
I did this too it just return `Uncaught ReferenceError: url is not defined`.
