### ISSUE TITLE
rewrite unsafeUrls to safeUrls before rendering

### ISSUE THREAD

**Issue by lublak** [mozilla/pdf.js#13767]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Firefox 90.0b12
- Operating system and its version: Windows 10
- PDF.js version: 2.8.335
- Is a browser extension: false

Steps to reproduce the problem:
1. Load a pdf file with links to another pdf file but with local paths (Example: file:///C:\Internal\blalbla.pdf) in the default viewer
2. URLs needs to be rewritten to http://intranet/Internal/blalbla.pdf

What is the expected behavior?

An option to rewrite urls before rendering with the pdf viewer.
Possibly with the SimpleLinkService?
https://github.com/mozilla/pdf.js/blob/227d0b0dac347c6a2b722588b12e13c74575897f/web/pdf_link_service.js#L517
A method `getSafeUrl(unsafeUrl)`

What went wrong? (add screenshot)

Currently impossible I think. Unless I rewrite parts of pdfjs.

**Comment by Snuffleupagus** [comment]
Please note that in cases where we're unable to obtain valid *absolute* URLs[1], we purposely don't try to re-write them and the `unsafeUrl` property is consequently not being used anywhere in the PDF.js library/viewer.
The `unsafeUrl` property is provided only to allow third-party implementations to access the *raw* URL-data, however the decision to make use of it will have to be made by the implementer (after considering the potential risks involved).

> Load a pdf file with links to another pdf file but with local paths (Example: file:///C:\Internal\blalbla.pdf) in the default viewer
> URLs needs to be rewritten to http://intranet/Internal/blalbla.pdf

Sorry, but this sort of *arbitrary* URL-rewriting isn't something that the PDF.js API (or viewer) can/will realistically support, since the "correct" format seem highly situation/implementation dependent and the use-case also seem somewhat "special" as far as I can tell.

> Possibly with the SimpleLinkService?
> A method `getSafeUrl(unsafeUrl)`

You can obviously write a custom [`IPDFLinkService`-implementation](https://github.com/mozilla/pdf.js/blob/6c9b6bc59999cfe7253ecc1323f38210b8739cd0/web/interfaces.js#L20) that does that, however as mentioned this doesn't seem feasible to support directly in the PDF.js library/viewer.

Closing as answered, or perhaps WONTFIX.

---
[1] Those can be e.g. relative URLs, where the `docBaseUrl` parameter hasn't been set, or URLs with unsupported protocols.

**Comment by lublak** [comment]
@Snuffleupagus thank your answer :)
Yes its special and I also understand that it's a won't fix.

**Comment by lublak** [comment]
Here ne small information if someone needs the same and does not know how to reach it.
Basically only the viewer.js has to be adapted.
In it is the class AnnotationLayerBuilder with the method render.
In this method there is a promise with getAnnotations and in the callback function this customization can be done.
annotations is an array which can be traversed. This can then be customized. It contains the unsafeUrl and also the "safe" url.
If you set the url in the element you can also realize complex rewritings of the links.

Sample code (do not use in production), please check the unsafeUrl before you use it:

```js
annotations.forEach(element => {
    if(!element.url && element.unsafeUrl) {
        element.url = 'http://intranet/' + element.unsafeUrl;
    }
});
```

**Comment by lublak** [comment]
Some extra informations:

Since you can't override the target (_top, _blan, _self) for each annotation, you need to do a customization directly in pdf.js.
In the LinkAnnotationElement class in the render method there is the following line:
```js
target: data.newWindow ? _display_utils.LinkTarget.BLANK : linkService.externalLinkTarget,
```
Replace it with:

```js
target: data.target ? data.target : (data.newWindow ? _display_utils.LinkTarget.BLANK : linkService.externalLinkTarget),
```
so the target die can also be overwritten.
