### ISSUE TITLE
PDF fails to load in Firefox.

### ISSUE THREAD

**Issue by xuyuehang** [mozilla/pdf.js#13760]
This PDF isn't loading with the builtin pdf.js in Firefox (Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0): http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=8F5424CF7B842FD327A1D5E7B19C89F6

Error message: An error occurred while loading the PDF.
PDF.js v2.7.570 (build: f2c7338b0)
message：NetworkError when attempting to fetch resource.

However, it can be opened in Chrome,

**Comment by Snuffleupagus** [comment]
> This PDF isn't loading with the builtin pdf.js in Firefox (Build identifier: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0): http://c.gb688.cn/bzgk/gb/showGb?type=online&hcno=8F5424CF7B842FD327A1D5E7B19C89F6

This is confusing, since the provided link points to a *custom* version of the PDF.js demo viewer and doesn't actually use the browser built-in PDF Viewer.
Furthermore, opening that link in *either* Mozilla Firefox or Google Chrome throws an empty-file Error (i.e. `The PDF file is empty, i.e. its size is zero bytes.`) which suggests that you're trying to load an empty/incorrect PDF document or that the server doesn't return the correct data, neither of which we unfortunately cannot help fix.

Furthermore, it appears that the viewer has been customized in various ways. E.g. some methods seem to be missing on `PDFViewerApplication`, and somewhere in your code a global `PDFJS` object is defined (we removed that with the *first* release from the `2`-branch). All-in-all, this makes it very difficult for anyone to tell what might be going wrong.

> PDF.js v2.7.570

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Finally, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable.
Also, it next to impossible to debug a *customized* viewer like this; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
