### ISSUE TITLE
PDF failed to render correctly; Page seemed to be overlapped with a filled rectangle

### ISSUE THREAD

**Issue by devjobbes** [mozilla/pdf.js#13800]
[Print_Sample_A4_VDP_KDCN_Template_Marathon_Ver1.00.pdf](https://github.com/mozilla/pdf.js/files/6882238/Print_Sample_A4_VDP_KDCN_Template_Marathon_Ver1.00.pdf)

Configuration:
- Google Chrome Version 91.0.4472.164 (Official Build) (64-bit)
- Windows Enterprise 10.0.19042 Build 19042
- PDF.js version: v2.9.539
- Is a browser extension: No

Steps to reproduce the problem:
1. Open modern browser viewer using the following link: [https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)
2. Open the attached file Print_Sample_A4_VDP_KDCN_Template_Marathon_Ver1.00.pdf

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/33852072/127085474-98513641-5572-4c25-9d1e-396e6d45a3b2.png)

What went wrong? 
![image](https://user-images.githubusercontent.com/33852072/127085570-ca43e29d-d2f0-4c46-94c0-899f4da8ae55.png)

**Comment by SamyCookie** [comment]
It's  a Chrome specific issue, rendering is fine with Firefox 90

**Comment by jhacksworth** [comment]
Also renders correctly in Safari.

**Comment by devjobbes** [comment]
Confirmed that rendering ok on Safari and Firefox 90.0.2 (64-bit).

**Comment by angelaperez1019** [comment]
This issue is also started happening in our project on both Chrome/Edge with specific text not appearing. However, it is appearing if you download the file and view in another pdf viewer.

Chrome Version 92.0.4515.107 (Official Build) (64-bit)
Edge Version Version 92.0.902.55 (Official build) (64-bit)

Firefox looks even worse for our form with text overlapping but our user based does not use Firefox, did not notice up until I read this post and decided to check Firefox.

**Comment by ankit1534** [comment]
Hi All,
Did anyone figure out what was the issue?

**Comment by Snuffleupagus** [comment]
Given comments https://github.com/mozilla/pdf.js/issues/13800#issuecomment-887244580, https://github.com/mozilla/pdf.js/issues/13800#issuecomment-887641741, and https://github.com/mozilla/pdf.js/issues/13800#issuecomment-887853445; this looks like a bug (e.g. `canvas`-related) in the Google Chrome browser itself, rather than in the PDF.js library since then you'd expect it to be consistently broken everywhere.

Closing for now, since this unfortunately doesn't look like an actionable issue *here*.
