### ISSUE TITLE
PDFViewer does not re-render canceled pages (not reproducible in the official demo viewer)

### ISSUE THREAD

**Issue by StemateF** [mozilla/pdf.js#13811]
Hey there,

I am working on a simple pdf viewer, but I noticed a weird issue that happens when the user scrolls up and down fast. The `PDFRenderingQueue` will throw a `RenderingCancelledException` and then never attempt to rerender that page again.

Inspecting the result of the `PDFViewer._getVisiblePages()`  [link](https://github.com/mozilla/pdf.js/blob/336a74a0e5c0848d6fa522dc0b22dbed4fb1d38b/web/base_viewer.js#L1117) returns the page as visible and the `PDFPageView.renderingState` is set as finished.

To me, it's obvious that I missed something because this issue doesn't happen on the demo viewer.

My original code was only using the `PDFViewer` but the demo has most of its code copy and pasted from the https://github.com/mozilla/pdf.js/blob/master/web/app.js#L197
in the hopes that the issue is fixed there but unfortunately it keeps happening.

I hope you guys can offer me some guidance on how to fix this issue.

Thanks. 

ISSUE TEMPLATE: 
Attach (recommended) or Link to PDF file here: [compressed.tracemonkey-pldi-09.pdf](https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Firefox 90.0 
- Operating system and its version: Pop!_OS 21.04
- PDF.js version: 2.9.359
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached codesandbox
2. Scroll real fast up and down
I also have a screen recording with the issue happening: [screen recording](https://www.awesomescreenshot.com/video/4640620?key=3b3922b13d3e79b35ea24ef595c1dfc8)

What is the expected behavior? (add screenshot)
I think after the RenderingCancelledException is thrown the viewer should render the page that got canceled if the page becomes visible again later.
![image](https://user-images.githubusercontent.com/20905432/127315867-fbdee382-00c1-4dca-9d5d-aed8f6ad182b.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/20905432/127315741-2f87d01f-0535-40c1-86a0-8e0dc044d072.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://codesandbox.io](https://codesandbox.io/s/starringjane-workshop-artevelde-forked-cvh9e?file=/src/pdf.js)

**Comment by Snuffleupagus** [comment]
> I am working on a simple pdf viewer,

Generally speaking, if you're writing a custom viewer, it's probably better to start with the "viewer component" examples rather than the full viewer; see https://github.com/mozilla/pdf.js/tree/master/examples/components

> My original code was only using the `PDFViewer` but the demo has most of its code copy and pasted from the https://github.com/mozilla/pdf.js/blob/master/web/app.js#L197
> [...]
> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> [https://codesandbox.io](https://codesandbox.io/s/starringjane-workshop-artevelde-forked-cvh9e?file=/src/pdf.js)

Sorry, but that's a bit too much code to try and look through to try and spot a potential problem!

What I did notice though, is that it appears that you're referencing files in https://github.com/mozilla/pdfjs-dist/tree/master/lib, which contains a warning about not using those files directly (hence that's not officially supported); please note https://github.com/mozilla/pdfjs-dist/tree/master/lib#readme

A custom viewer, following e.g. the "viewer component" examples, should thus be based on https://github.com/mozilla/pdfjs-dist/tree/master/web instead.

> `PDFRenderingQueue` will throw a `RenderingCancelledException` and then never attempt to rerender that page again.

That shouldn't actually happen though, since that Exception is *explicitly* ignored in https://github.com/mozilla/pdf.js/blob/336a74a0e5c0848d6fa522dc0b22dbed4fb1d38b/web/pdf_rendering_queue.js#L174-L177

---

Most likely your troubles come from trying to use the *pre-built* library together with files in the `pdfjs-dist/lib` folder, something that's not really intended/supported.

**Comment by StemateF** [comment]
Hey there @Snuffleupagus  thank you for the super quick response.

I am sorry I didn't notice the readme at /lib if it's not supported or encouraged I will think of an alternative.

I went ahead and removed all the lib/* references and reverted back to my initial code and created another demo that still reproduces the error.
https://codesandbox.io/s/starringjane-workshop-artevelde-forked-4ie1g?file=/src/PdfApp.js.

> Generally speaking, if you're writing a custom viewer, it's probably better to start with the "viewer component" examples rather than the full viewer; see https://github.com/mozilla/pdf.js/tree/master/examples/components

Regarding that, my idea was to let this class handle the rendering of the pdf (including queueing and prioritizing different pages) and just building the UI over it. 

Regarding the exception, I also noticed that the error shouldn't be thrown, I will do some more digging on the reason why it happens.

Thank you for your help.

**Comment by Snuffleupagus** [comment]
I'd suggest reducing your code even further to basically *only* the `simpleviewer` example, i.e. both the HTML and JavaScript files, see https://github.com/mozilla/pdf.js/tree/master/examples/components

My suspicion is that things may perhaps "just work" if you actually load the `pdf.js` file as a script, rather than importing it?

---

Please note that the Firefox built-in PDF Viewer is the *primary* development target for this library, hence there's *unfortunately* not been too much work put into allowing e.g. `import`-ing or `require`-ing the library code when using it together with the viewer.

Most of the focus has been (and is) concerned with simplicity and bundle-size for the Firefox PDF Viewer in particular, and it's thus (again very unfortunately) quite possible that this issue is "caused" by the way that you're referencing e.g. the `pdf.js` file

**Comment by StemateF** [comment]
@Snuffleupagus You were right!   Somehow, importing the library in my code broke it. Following the simpleviewer example I was able to update my demo and the issue is fixed. [LINK](https://codesandbox.io/s/starringjane-workshop-artevelde-forked-4ie1g?file=/src/index.js)

It's truly a shame that such a great library has such a limitation. 

OK thank you again for your support, I will look for a workaround to keep using the npm package.

As far as I am concerned this Issue can be closed.
