### ISSUE TITLE
Should use peerDependenciesMeta for worker-loader

### ISSUE THREAD

**Issue by tamuratak** [mozilla/pdf.js#13825]
Related to  #11474 and #12815.

The following should be added to `package.json` of `pdfjs-dist` for `worker-loader`.
```
  "peerDependenciesMeta": {
    "worker-loader": {
      "optional": true
    }
  }
```

npm v7 installs `peerDependencies` by default. We can see that calling `npm install pdfjs-dist` in an empty directory will install `webpack` and others in `node_modules`.

> In npm versions 3 through 6, peerDependencies were not automatically installed, and would raise a warning if an invalid version of the peer dependency was found in the tree. As of npm v7, peerDependencies are installed by default.

- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependencies
- https://github.blog/2020-10-13-presenting-v7-0-0-of-the-npm-cli/

We can make `worker-loader` optional with `peerDependenciesMeta`.

- https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta
- https://github.com/npm/rfcs/issues/221

**Comment by Snuffleupagus** [comment]
> The following should be added to `package.json` of `pdfjs-dist` for `worker-loader`.
> 
> ```
>   "peerDependenciesMeta": {
>     "worker-loader": {
>       "optional": true
>     }
>   }
> ```

@tamuratak That looks completely reasonable as far as I can tell; do you want to submit a patch?
The new code should be added just *after* the following block (since the `package.json` file is generated): https://github.com/mozilla/pdf.js/blob/3ec1bac9012b28fbb0773ed7328cb67a76e0d728/gulpfile.js#L2020-L2022

Also, if we're editing this code anyway I'd suggest bumping the `worker-loader` package to use version `^3.0.8` as well.
