### ISSUE TITLE
Error Localizer

### ISSUE THREAD

**Issue by MohsenEs** [mozilla/pdf.js#13843]
I think this problem occurs on some phones because the geographical area is not identified correctly
https://menu.jarcafe.ir/Menu/ViewMenuItems?menuId=3&collectionCode=JarCafe

![WhatsApp Image 2021-08-02 at 5 31 20 AM](https://user-images.githubusercontent.com/46873097/127791698-b5f056df-8116-470c-be97-4526c80eb65d.jpeg)

**Comment by MohsenEs** [comment]
https://menu.jarcafe.ir/Menu/ViewMenuItems?menuId=3&collectionCode=JarCafe

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately not actionable/valid.

> I think this problem occurs on some phones because the geographical area is not identified correctly

Furthermore, it's more-or-less impossible to even understand what problem you're attempting to report here, given that a sentence such as the above unfortunately isn't very clear.

> https://menu.jarcafe.ir/Menu/ViewMenuItems?menuId=3&collectionCode=JarCafe

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
