### ISSUE TITLE
Some letters in textLayer aren't properly aligned with the rendered text

### ISSUE THREAD

**Issue by mrtcode** [mozilla/pdf.js#13845]
Attach (recommended) or Link to PDF file here:
[example.pdf](https://github.com/mozilla/pdf.js/files/6916129/example.pdf)

Configuration:
- Web browser and its version: Chrome, Firefox
- Operating system and its version: all
- PDF.js version: various versions, including 2.11.54
- Is a browser extension: no

Screenshot with visible textLayer:
![Screenshot from 2021-08-02 13-05-03](https://user-images.githubusercontent.com/6362989/127844878-f85e291f-2060-4028-be09-7835f32ccfaa.png)

Which means some letters at the beginning/end of text selection are missing when copying text.

**Comment by tassioauad** [comment]
![image7](https://user-images.githubusercontent.com/771016/129558594-60190296-555f-45e8-8a82-deaa3d829bb8.png)

I am having the same problem here with PDFs that have gone through OCR processing. Any news about this?

Configuration:

Web browser and its version: Chrome, Firefox
Operating system and its version: all
PDF.js version: various versions, including 2.9.359
Is a browser extension: no

**Comment by 314warhurst** [comment]
I'm experiencing the same issue in
[this pdf](https://github.com/mozilla/pdf.js/files/7202615/Jack.de.Belin.trial_.NSW.Police.gave.legally.privileged.material.on.NRL.star.s.phone.to.prosecutors.pdf)

![Screen Shot 2021-09-21 at 1 16 36 PM](https://user-images.githubusercontent.com/5925000/134161391-5ebd6762-c8c5-4542-a34d-77b5ec5df818.png)

Did you make any progress here @mrtcode?

**Comment by henrywarhurst** [comment]
So in my PDF above, I noticed that the heading font that is used here `AbrilTitlingSb`, is actually a serif font, but is recorded as sans-serif in the PDF object:
```
35 0 obj
<</Type /FontDescriptor
/FontName /AbrilTitlingSb
/Flags 4
/Ascent 839
/Descent 279
/StemV 141
/CapHeight 700
/ItalicAngle 0
/FontBBox [-168 -229 980 927]
/FontFile2 34 0 R>>
endobj
```

If I set fallbackFont to always be `serif` (as a test) in `fonts.js`, then the alignment looks a lot better. Obviously we can't just switch the fallbackFont to default to serif, so, I'm wondering what other options might be explored here. @Snuffleupagus how can we be smarter about selecting the fallbackFont here in the case that the PDF itself seems to use the incorrect font?

![Screen Shot 2021-09-22 at 2 01 09 PM](https://user-images.githubusercontent.com/9415645/134340177-eb6a2fd8-0f4a-424d-88a5-efdcf349b71a.png)

**Comment by Snuffleupagus** [comment]
Based on a cursory look, the source of the problem in the PDF file in https://github.com/mozilla/pdf.js/issues/13845#issue-957987834 is that the fonts contain an *incorrect* /Flags entry (i.e. it's bug in the PDF file *itself*). If the font flags were correctly set to "serif", this should just work; however for that *particular case* a work-around might be possible (using the font name).

---

The PDF file in https://github.com/mozilla/pdf.js/issues/13845#issuecomment-923882716 is slightly different, since here there's not even any font flags at all (again clearly a bug in the PDF file *itself*). That case is slightly worse though, since it doesn't look like the same work-around (as above) would be possible.

All-in-all, the second case is *not really* the same identical issue and it's also going to be much more difficult to "hack around" the brokenness in PDF file *itself* (you always need to limit any hacks, especially in the font code, to prevent lots of other things breaking).

**Comment by henrywarhurst** [comment]
@Snuffleupagus got it! That's interesting re getting `serif` from the font name. I saw `isSerifFont` does name checking for serif-ness, but is only run if there is no font descriptor in the file. https://github.com/mozilla/pdf.js/blob/638115885584b82ee9ea6fed83aa7ae15348ba27/src/core/evaluator.js#L3620

If you don't have time to fix this one let me know and I can attempt a fix

**Comment by Snuffleupagus** [comment]
Re https://github.com/mozilla/pdf.js/issues/13845#issuecomment-924989328: Sorry, but I don't think we'll want to add a work-around for your particular case.
The reason is that the font names in question look very "non-standard", and it'd be difficult to know if it's generally safe to treat them as "serif" fonts. (And we *really* want to avoid dealing with a bunch of regressions later, just for one particular case of bad font data.)

**Comment by henrywarhurst** [comment]
Hey @Snuffleupagus - apologies for not being clearer - I understand that only @mrtcode 's PDF (and not mine) is going to benefit from the approach I was talking about in https://github.com/mozilla/pdf.js/issues/13845#issuecomment-924989328.

It's just that we use PDF.js extensively at Palantir and I'd like to help where I can to make text selection better in all/any ways.

**Comment by 1014670860** [comment]
Is there a solution, please?

**Comment by maxiloEmmmm** [comment]
same question in version latest

## i.e.
### serif
![image](https://user-images.githubusercontent.com/16779121/227761660-4c602aa9-8b07-4d1e-bd6c-b5cbb10499ac.png)

### sans-serif
![image](https://user-images.githubusercontent.com/16779121/227761684-ae568fdb-2233-4118-9b37-3df212bb8898.png)

debug:
![image](https://user-images.githubusercontent.com/16779121/227761639-f3f47ece-3ee7-465b-802d-02cf17285e42.png)
