### ISSUE TITLE
performance improvement when streaming PDFs

### ISSUE THREAD

**Issue by gregorymaertens** [mozilla/pdf.js#13897]
Hello,

I have noticed when the server does support ranges after reading the HTTP headers the stream is canceled (with disableStream=true), then range requests are made. In particular the first range request is made from byte 0.
I was wondering why not keep on reading the first chunk worth of data right after reading the headers? 
It would save a connection setup + CORS preflight.
That could shave off a few 100ms extra.
Is there any reason for that?

Note: I'm using disableStream=true as on Chrome, running with disableStream=false (default) it will make the range requests wait for the full PDF to be downloaded.

Thank you!

**Comment by Snuffleupagus** [comment]
> I have noticed when the server does support ranges after reading the HTTP headers the stream is canceled (with disableStream=true), then range requests are made.

Yes, that's the *intended* behaviour with `disableStream = true` set.

> I was wondering why not keep on reading the first chunk worth of data right after reading the headers?

Because that would *significantly* complicate the overall implementation, and could also (possibly) lead to issues with the initial request not actually being aborted as intended (or in time) in all cases depending on e.g. the PDF file-size and the chunk-size returned via streaming. It's actually quite easy to imagine how something like that may end up "breaking" the `disableAutoFetch` option in various ways, or at least make its behaviour inconsistent.

> Note: I'm using disableStream=true as on Chrome, running with disableStream=false (default) it will make the range requests wait for the full PDF to be downloaded.

Please note that the general recommendation is to *always* let streaming be enabled, since that will generally lead to the best overall performance.
Note also that in that default case, with `disableStream = false` set, there shouldn't normally even be any range requests used.

---

Finally, please note that as-is this issue is a little "light" on the details to be easily actionable.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
