### ISSUE TITLE
window['pdfjs-dist/build/pdf.hjs'] undefined in Electron

### ISSUE THREAD

**Issue by Laulesage** [mozilla/pdf.js#13903]
17/08/2021, no issues.

18/08/2021 : 
![image](https://user-images.githubusercontent.com/89136955/129888980-34dc27ae-6cb8-40af-bb92-bcfdcb6c4393.png)

The above is the Electron App version.
However, in our browser version : 
![image](https://user-images.githubusercontent.com/89136955/129889221-3d48a443-dfe1-4038-9b1b-429e1a0c2fac.png)

The error is coming from here after investigation:

![image](https://user-images.githubusercontent.com/89136955/129889291-eece7e17-f101-42a9-ab29-7b360194923a.png)

![image](https://user-images.githubusercontent.com/89136955/129890107-d3a78232-e007-4816-9575-370a0cd9db9d.png)

What happened and what is the solution ?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable.

Furthermore, please note that since the PDF.js library is primarily intended for usage in *browsers* we unfortunately cannot help with various frameworks such as e.g. "Electron" (since we know nothing about it).

Finally, please note that screen-shots are not really helpful in this case; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
