### ISSUE TITLE
Embedded PDF is displayed with wrong characters (Czech characters)

### ISSUE THREAD

**Issue by ladislavnachodsky** [mozilla/pdf.js#13916]
Attach (recommended) or Link to PDF file here: https://github.com/mozilla/pdf.js/files/7021521/sample.pdf

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Microsoft
- PDF.js: 2.2.228

What is the expected behavior? 
Embedded PDF Viewer should display right font with all characters

What went wrong? 
![image](https://user-images.githubusercontent.com/89254263/130225854-43467f78-e856-4a42-8e64-94bdfe479053.png)

Is it possible to add some other font? Is it possible to manage what encodings will be used?

Thank you in advantage

Regards Ladislav

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately actionable/valid.

> Attach (recommended) or Link to PDF file here:

This information is always required.

> PDF.js: 2.2.228

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by ladislavnachodsky** [comment]
[sample.pdf](https://github.com/mozilla/pdf.js/files/7021521/sample.pdf)
uploaded PDF thank you for investigation
