### ISSUE TITLE
Not working in Safari Version 12.1.2

### ISSUE THREAD

**Issue by HigherPhilosophy** [mozilla/pdf.js#13924]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari Version 12.1.2 
- Operating system and its version: OSX 10.12.6
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. Open
https://pdfjs.express/blog/how-embed-pdf-in-html-website
in Safari and the demo of PDF.js (not express) about half way down displays as a black box.
The same occurs with my own pdfs using  PDF.js version: 2.9.359

What is the expected behavior? (add screenshot)
![ChromeAsExpected](https://user-images.githubusercontent.com/87994282/130363980-8ad4b1e0-1404-4e35-bb57-0306279dae42.png)

What went wrong? (add screenshot)
![SafariBlackBox](https://user-images.githubusercontent.com/87994282/130363991-747e1d01-ccc6-490f-a908-57c0f3ac7492.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> https://pdfjs.express/blog/how-embed-pdf-in-html-website

Sorry, but that's not an official resource and as such we cannot provide help/support for it.

> PDF.js version: 2.9.359
> [...]
> What is the expected behavior? (add screenshot)

Unfortunately the quoted version number doesn't actually agree with the screen-shots that you included, since they show a *much older* version of the demo viewer.

---

All-in-all, this issue unfortunately isn't actionable in its current state; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
