### ISSUE TITLE
PDF rendering fails with: bad XRef entry

### ISSUE THREAD

**Issue by igoso** [mozilla/pdf.js#13946]
Configuration:
- Web browser and its version: chrome  92.0.4515.159
- Operating system and its version: windows 10
- PDF.js version:  v1.1.159 build 82536f8
- Is a browser extension: no

Steps to reproduce the problem:
1.  I use pdf.js as web pdf viewer in out website , when i enable range request , this "bad XRef entry" happens "randomly" . the backend api is in SpringMVC , and it supports HTTP range requests . I test it work well in local, but when deployed online , the "bad XRef entry" happens randomly.  

2. i use nginx to forward requests.
What is the expected behavior? (add screenshot)

work well when request pdf in  chunks.

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/8018236/131310189-4db193fd-2e39-49c3-a8b8-7d32573b769d.png)

the stack in js:
![image](https://user-images.githubusercontent.com/8018236/131311397-14d5a70c-0691-41df-a15c-4f850e865177.png)

**Comment by Snuffleupagus** [comment]
Note that the "Attach (recommended) or Link to PDF file here:"-part of the ISSUE_TEMPLATE is always required in order for any issue to be valid.

> PDF.js version:  v1.1.159 build [82536f8](https://github.com/mozilla/pdf.js/commit/82536f8fa65480234c5c3c58463e308d57b176a5)

That version is first of all not an official release, and secondly it's *over six years old*; please understand that no support will be provided for such "ancient" versions of the PDF.js library!
Please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> I test it work well in local, but when deployed online , the "bad XRef entry" happens randomly.

This clearly points to an issue in your environment, rather than the PDF.js library, which we cannot help with.

For future reference, please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by igoso** [comment]
thanks for your reply , we finally find the reason caused that problem is nginx upstream , because our pdf  located in different hosts. That's why it runs well in local and test environment but failed in product environment . Hope this can help others who meet same errors.  :)

**Comment by HeggyChan** [comment]
@igoso  i test the error pdf in local environment , but the problem still .....
by the way, my pdfJS version is  v2.9.359, which is the latest on in offical website
