### ISSUE TITLE
Judgment of serif font

### ISSUE THREAD

**Issue by 1034829217** [mozilla/pdf.js#13954]
We found that when determining whether a font is serif, because the recognized font can not match the name of the font in the font library well, many serif fonts are recognized as non serif fonts. How can we solve this problem？

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since otherwise the issue isn't actionable/valid.

> We found that when determining whether a font is serif, because the recognized font can not match the name of the font in the font library well, many serif fonts are recognized as non serif fonts. How can we solve this problem？

Also, please try and describe the problem in a clear and concise way since the above isn't very easy to understand (which is further exacerbated by the lack of information).
