### ISSUE TITLE
Enable XFA in the web viewer

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#13968]
- Open https://mozilla.github.io/pdf.js/web/viewer.html
  - Open a pdf with some XFA (for example the on in https://github.com/mozilla/pdf.js/issues/13679#issue-937616350)

The pdf is not correctly displayed because `enableXfa` is false.

@Snuffleupagus, the pref is set to true in Firefox nightly, is there anything blocking setting it to true in the web viewer ?

**Comment by marco-c** [comment]
#13745 enabled it in the development viewer.

**Comment by Snuffleupagus** [comment]
> the pref is set to true in Firefox nightly, is there anything blocking setting it to true in the web viewer ?

I thought, perhaps incorrectly, that we wanted to wait until it XFA-support was going to rid the trains to release in Firefox (and not just be Nightly-only)?

Note also that if we changed https://github.com/mozilla/pdf.js/blob/804abb3786e4f09ad084d705ff9b4d770067583d/web/app_options.js#L227-L233 to `true` unconditionally, then that'd also mean enabling it for all Firefox-channels and you'd need to essentially "flip" https://searchfox.org/mozilla-central/rev/55e8eba74b60b92d04b781f7928f54ef76b13fa9/modules/libpref/init/all.js#353-356 in order to keep XFA *disabled* in the release version of Firefox.

---

Finally, please note that if we decide to flip the preference everywhere also a couple of examples that should be updated accordingly as well (so the patch would touch more than just `web/app_options.js`)
