### ISSUE TITLE
Two icons for DropDownButtons

### ISSUE THREAD

**Issue by nedy13** [mozilla/pdf.js#13979]
I think this issue is related to this change: [Implement Photon design for the viewer #11077](https://github.com/mozilla/pdf.js/pull/11077)

Configuration:
- Web browser and its version: Firefox 91.0.2
- Operating system and its version: Win10
- PDF.js version: included in Firefox 91.0.2
- Is a browser extension: no

Steps to reproduce the problem:
1. Open Browser's developer console
2. change width of .dropdownToolbarButton to e.g. 250px in developer console

I think only one icon is the expected one.

![image](https://user-images.githubusercontent.com/4283170/132197641-524dc9f4-3257-4e60-9bba-d5276a79ec0e.png)

**Comment by Snuffleupagus** [comment]
> Open Browser's developer console 
> change width of .dropdownToolbarButton to e.g. 250px in developer console

Can you reproduce this issue in any other way than by *manually* changing the with using the devtools?
Please keep in mind that what you're above describing is neither an intended nor supported use-case.

**Comment by nedy13** [comment]
No, there is no other way to reproduce.

I only observed this, because I upgraded the PDFjs version in our own 3rd party integration and we created some different theme. I only wondered that there is a second icon. I know this is a minor / low issue, but I only want to log this as bug, because this is not expected / wanted.

**Comment by Snuffleupagus** [comment]
> No, there is no other way to reproduce.

In that case, this issue is basically INVALID.

> I only observed this, because I upgraded the PDFjs version in our own 3rd party integration and we created some different theme.

Ah, so your question is *actually* about customizing the default viewer. (Please note that that's the kind of information that's always helpful to state clearly upfront :-)

If you want to customize the width of the zoom-dropdown, you'll need to edit the following values:
 - https://github.com/mozilla/pdf.js/blob/d95f680d66dd46e2995a7784109a1b3af2b84bdd/web/viewer.css#L890
 - https://github.com/mozilla/pdf.js/blob/d95f680d66dd46e2995a7784109a1b3af2b84bdd/web/viewer.css#L911
 - https://github.com/mozilla/pdf.js/blob/d95f680d66dd46e2995a7784109a1b3af2b84bdd/web/toolbar.js#L27-L28

>  I only wondered that there is a second icon.

Because we want to re-use the *native* `select` element for overall simplicity, but provide the same icon regardless of browser and OS, hence we set the widths such that the browser icon becomes hidden (which your manual changes thus broke).
