### ISSUE TITLE
What's the problem？

### ISSUE THREAD

**Issue by hzj19980803** [mozilla/pdf.js#14019]
Module parse failed: Unexpected token (2164:21)
You may need an appropriate loader to handle this file type.
|     var _intentState;
|
>     if (arguments[0]?.annotationStorage !== undefined) {
|       (0, _display_utils.deprecated)("render no longer accepts an `annotationStorage` option, " + "please use the `includeAnnotationStorage`-boolean instead.");
|       includeAnnotationStorage || (includeAnnotationStorage = !!arguments[0].annotationStorage);

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this isn't actionable.

Furthermore, if you're using an environment where the optional chaining operator isn't supported you should be using a `legacy`-build of the PDF.js library.
