### ISSUE TITLE
Invalid PDF structure - Invalid or corrupted PDF file

### ISSUE THREAD

**Issue by Nataraj67** [mozilla/pdf.js#14022]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 93.0.4577.63
- Operating system and its version: Windows 10
- PDF.js version: v2.8.335
- Is a browser extension: No

Steps to reproduce the problem:
1.  Enter the URL in chrome browser
2. http://tools-stage.rightprospectus.com/Viewer/Viewer.aspx?file=%2fViewer%2fHosted%2fGetDocument.ashx%3ffile%3dhttp%3a%2f%2ffundcompli.rightprospectus.com%2fdocuments%2fVanguard%2fSUM_VIF_InternationalPortfolio.pdf
3.  It will throw the error like in valid pdf structure

What is the expected behavior? (add screenshot)

What went wrong? (ad
![image](https://user-images.githubusercontent.com/56388429/133245078-fb9aeeab-fc4f-4bfa-88ad-d029f699374b.png)
d screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

*For future reference:* Please always directly attach the document here, since that saves time.

> PDF.js version: v2.8.335

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> http://tools-stage.rightprospectus.com/Viewer/Viewer.aspx?file=%2fViewer%2fHosted%2fGetDocument.ashx%3ffile%3dhttp%3a%2f%2ffundcompli.rightprospectus.com%2fdocuments%2fVanguard%2fSUM_VIF_InternationalPortfolio.pdf
> It will throw the error like in valid pdf structure

First of all, please note that that looks like a *customized* version of the default viewer.
Secondly, and more importantly, that PDF document appear to be corrupt enough that none of the PDF viewers that I've tried can open it, those include Adobe Reader (i.e. the PDF reference implementation) and PDFium (embedded in Google Chrome).

Closing as INVALID, since it's the PDF document which is at fault here and not the PDF.js library.

**Comment by Nataraj67** [comment]
[SUM_VIF_InternationalPortfolio.pdf](https://github.com/mozilla/pdf.js/files/7161895/SUM_VIF_InternationalPortfolio.pdf)

This is the pdf I trying to load. Can you confirm is this corrupted pdf?

Note : I am able to open through adobe reader also Chrome.  through pdf.js only i am facing issue

**Comment by calixteman** [comment]
WFM in Firefox nightly on debian with the built-in viewer and https://mozilla.github.io/pdf.js/web/viewer.html.

**Comment by Snuffleupagus** [comment]
> [SUM_VIF_InternationalPortfolio.pdf](https://github.com/mozilla/pdf.js/files/7161895/SUM_VIF_InternationalPortfolio.pdf)
> 
> This is the pdf I trying to load. Can you confirm is this corrupted pdf?

That document WFM too, using Firefox Nightly 94.0 (with its built-in PDF Viewer) on Windows.
Furthermore, it also works when opening it with https://github.com/mozilla/pdf.js#online-demo

Hence that PDF file is not corrupt, whereas the one linked in https://github.com/mozilla/pdf.js/issues/14022#issue-995875901 however is corrupt.
