### ISSUE TITLE
Impossible to rotate due to error Invalid rotation, must be a multiple of 90 degrees

### ISSUE THREAD

**Issue by Tatsianacs** [mozilla/pdf.js#14037]
When pdf page is a result of scan, it may not be with rotation of 'multiple of 90 degrees'. 
For now, it is impossible to use e.g. 94 angle.
Other libs e.g. pdfium allows to rotate to any angle.

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.7.570
- Is a browser extension: no

Steps to reproduce the problem:
1. Pdf is created as a result of scan  (and text recognition is done where angle is detected)
2. Try to use getViewport({ rotation: 94});
=> Invalid rotation, must be a multiple of 90 degrees

What is the expected behavior? (add screenshot)
Expect that we can use angle e.g. 94 so that the page is rendered properly

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/42011535/133824053-e6665bd0-e333-4da3-902f-4f2e44cb6a55.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Please note that that part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable.

> PDF.js version: 2.7.570

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Pdf is created as a result of scan (and text recognition is done where angle is detected)
> [...]
> Expect that we can use angle e.g. 94 so that the page is rendered properly

In that case this is actually a bug in the scanning and/or the PDF-creation software, rather than the PDF.js library.

In order to simplify the overall rotation handling in both the viewer *and* the API, please note that we *purposely* only support rotation in multiple of 90 degrees (and this issue does seem like an edge-case).

Closing as answered (or possibly even WONTFIX).

**Comment by Tatsianacs** [comment]
@Snuffleupagus is it possible to leave it as an enhancement or this is no change it will be fixed?
