### ISSUE TITLE
Document Preview is white 

### ISSUE THREAD

**Issue by imdanielaalves** [mozilla/pdf.js#14032]
I'm using the PDF.JS with latest version.
I have an issue when I want preview a document.
This is my current file with data:
![image](https://user-images.githubusercontent.com/89107468/133576971-815c8168-700f-4cf9-bdb5-7c5fb532bff1.png)

This is what I see in the preview:
![image](https://user-images.githubusercontent.com/89107468/133577608-d99d3e8d-a42d-4732-a5a3-6a68b9d03410.png)

For some reason, I don't see all the information in the preview.
If I click in the download button, the document is correct.

Could you give me some help with this issue?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately not actionable!

> I'm using the PDF.JS with latest version.

Unfortunately your screen-shot clearly disagrees with that statement, since it shows an *old version* of the default viewer; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Closing for now; we can re-open this issue when *all* of the required information has been provided.
