### ISSUE TITLE
When a form is resetted using a JS action, Firefox ask for "Stay... or Leave..."

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14039]
Attach (recommended) or Link to PDF file here:
[0 NIF MODELO 30.pdf](https://github.com/mozilla/pdf.js/files/7187486/0.NIF.MODELO.30.2.pdf)

Configuration:
- Web browser and its version: firefox nightly
- Operating system and its version: linux debian

Steps to reproduce the problem:
1. Open the PDF
2. Click on the button  `Rellenar Formulario` (top right of the first page)
3. There is the pop-up "Stay... or Leave...`.

It's a bit annoying from the user pov and it doesn't make sense (nobody wants to leave the form but just reset it)

It works fine when replacing  `""` by `"#"` here:
https://github.com/mozilla/pdf.js/blob/7082ff9bf876b98fbda118cdbd6267d3c0df6948/src/display/annotation_layer.js#L483

@Snuffleupagus, you changed this few month ago:
https://github.com/mozilla/pdf.js/commit/e2b6d79dee9ffd2aba715d6b3cb8fa143d86153c

do you have some ideas ?

**Comment by marco-c** [comment]
Let's file this on Bugzilla so we can track the regression.

**Comment by Snuffleupagus** [comment]
> @Snuffleupagus, you changed this few month ago:
> [e2b6d79](https://github.com/mozilla/pdf.js/commit/e2b6d79dee9ffd2aba715d6b3cb8fa143d86153c)
> 
> do you have some ideas ?

I thought it looked strange to have a trailing `#` in the URL, and I didn't think it was actually necessary (which was clearly not correct); sorry about the regression!

Rather than re-introducing that, would it work if we followed the same pattern as in `_bindNamedAction` just above by adding the following code after [after line 483](https://github.com/mozilla/pdf.js/blob/7082ff9bf876b98fbda118cdbd6267d3c0df6948/src/display/annotation_layer.js#L483)?
```javascript
link.onclick = () => {
  return false;
};
```
