### ISSUE TITLE
Simple, declarative example in just a couple of lines of code?

### ISSUE THREAD

**Issue by brylie** [mozilla/pdf.js#14061]
Is there a high-level, declarative way to render a PDF with PDF.js? Something along the lines of

1. include `pdf_viewer.min.js` (e.g. from CDN)
2. `const pdfUrl = pdf.url`
3. `pdfViewer.render("dom-element-id", pdfUrl)`

The example code is very verbose and imperative, leaving a lot of work downstream to add and style page turning elements.

The ideal outcome would be a fully-rendered PDF js web viewer instance with around three lines of code.

## Alternative(s) considered

On a previous site, we have used PDF.js via the iFrame approach. However, this would require keeping the PDF.js distribution under revision control or introducing a build process in the project. 

A CDN include would be desirable to avoid additional maintenance.

## Caveats

I have read the statement on how to [setup PDF.js in a website](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#pre-built-pdfjs)

> we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.

That acknowledged, we really just need a simple, user-friendly way to render inline PDF on our open-source website. I.e. I am hoping to not have to worry about skinning or customizing the PDF viewer, when the default PDF.js rendition is really nice.

## Examples

We have [used PDF.js in our existing Drupal-based website](https://westernfriend.org/media/quaker-basics-key-books-and-pamphlets) by including the full contents of the dist project. However, I am [re-writing the project in Django](https://github.com/WesternFriend/WF-website) and would prefer to not use any JavaScript build tool (as they aren't a good fit for the project) or to have the [PDF.js dist](https://github.com/mozilla/pdfjs-dist) project under revision control.

**Comment by brylie** [comment]
Upon further research, I think the [PDFObject project](https://pdfobject.com/) exemplifies the API I'm describing:

![image](https://user-images.githubusercontent.com/17307/134348261-696b09ef-449b-482c-b004-45cf8e33c62f.png)

**Comment by Snuffleupagus** [comment]
> Is there a high-level, declarative way to render a PDF with PDF.js?

No, since the PDF format (and consequently a PDF Viewer) is complex enough that something like that is unlikely to be helpful in the general case. Furthermore, with a lot of components/options available, things such as e.g. configuration would become hard to maintain/support in that case (and the primary development target is the Firefox *built-in* PDF Viewer).

For building a *custom* PDF Viewer, please see the "viewer component" examples in https://github.com/mozilla/pdf.js/tree/master/examples/components (which could be used with files from the `pdfjs-dist` library) or perhaps also https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer

> A CDN include would be desirable to avoid additional maintenance.

Please note that we purposely don't include the default viewer in e.g. the `pdfjs-dist` library, since it's not intended to be used as-is in custom implementations (as you've noticed).

> I have read the statement on how to [setup PDF.js in a website](https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website#pre-built-pdfjs)
> 
> > we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.
> 
> That acknowledged, we really just need a simple, user-friendly way to render inline PDF on our open-source website. I.e. I am hoping to not have to worry about skinning or customizing the PDF viewer, when the default PDF.js rendition is really nice.

Please note that we're *specifically* asking for this since we want to prevent users confusing the Firefox *built-in* PDF Viewer with a custom viewer (since those may not be update all that frequently).
