### ISSUE TITLE
Worker file is fetched and a new thread created everytime getDocument is called

### ISSUE THREAD

**Issue by 698969** [mozilla/pdf.js#14079]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 93.0.4577.82 (Official Build) (64-bit)
- Operating system and its version: Microsoft Windown 10 Pro 10.0.19042 Build 19042
- PDF.js version: 2.9.359
- Is a browser extension: False

Steps to reproduce the problem:
I'm using PDF.js with SvelteKit/Vite, I don't think that's the cause of the problem, because the library is only imported once and the same for setting workerSrc, but I might be wrong. 

1. Import pdf.js into a component, (import only happens once)
2. Set the worker src through `GlobalWorkerOptions.workerSrc` (only happens once so not part of the problem either)
3. Call getDocument to load and render a PDF
4. Load another pdf using getDocument

What went wrong? (add screenshot)
On each getDocument call:
Worker file is **requested again** when loading the second document, the server responds with a 304 but there's still some latency, this is on a local dev server so the latency will be amplified on a remote server
![image](https://user-images.githubusercontent.com/50981692/134794828-64393917-3e27-4a7f-874b-fdf4afe022cb.png)

A **new worker thread is spawned**, each new thread is taking up more than **2.5MB** of memory, and this is on a page where getDocument will be called numerous times, so eventually, it'll add up to a lot
![image](https://user-images.githubusercontent.com/50981692/134794880-4ecb3dc4-e772-4d94-b589-cddd2721e760.png)

What is the expected behavior? (add screenshot)
If there is already a worker instantiated, use that worker and it's thread for rendering, instead of refetching the worker file, instantiating a worker and spawning a new thread

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Locally hosted but I might be able to create a minimal reproduction if needed

**Comment by Snuffleupagus** [comment]
> I'm using PDF.js with SvelteKit/Vite,

Please note that we unfortunately cannot really provide support for various frameworks (since we know nothing about them). Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Set the worker src through `GlobalWorkerOptions.workerSrc` (only happens once so not part of the problem either)

You could also use `GlobalWorkerOptions.workerPort` to contain the worker file-data, which may help if the browser isn't handling caching of loaded files correctly.

> If there is already a worker instantiated, use that worker and it's thread for rendering, instead of refetching the worker file, instantiating a worker and spawning a new thread

It sounds like you may want to manually create a `PDFWorker` instance instead, and then use that one via the following option when calling `getDocument`: https://github.com/mozilla/pdf.js/blob/3b3c487bed43900c5f55c3535c6f7697fed64e93/src/display/api.js#L148-L149

See also issue #7057, which while slightly older still looks relevant here.
