### ISSUE TITLE
pdf-dist 2.10.377 setup in React.js

### ISSUE THREAD

**Issue by Liocat-sp** [mozilla/pdf.js#14080]
Hey hi,
 
I am trying to create a React project on pdfjs v2.10.377 pre-release. But I am not able to figure what will be the setup I will require to run it. It always throws webpack or sometimes babel error. I was able to run the old pdfjs-dist version in react, but the new build is throwing Exceptions.

Configuration:
- Web browser and its version: chrome : v94.0.4606.61
- PDF.js version: 2.10.377

Steps to reproduce the problem:
1.  just do create-react app.
2. and npm install pdf-dist the latest build.

## What is the expected behavior? (add screenshot)
I just want to run pdfjs-dist with react.

## What went wrong? (add screenshot)
it is throwing some loader error and token error, you can check the screenshot below. I don't know what loader it requires running.

![image](https://user-images.githubusercontent.com/60030073/134797376-7ff99d4b-55a9-484b-b782-a7e16d428507.png)

## my current package json looks like this :
![img](https://user-images.githubusercontent.com/60030073/134797142-1b0639d8-dbff-45a3-be19-a99cf2680f25.jpg)

I just want to get started with the pdfjs in react, this is a blocker for me. Please let me know the fix for this issue, it will be really helpful. Let me know if you need more details. 

Thanks in advance 👍 ...

**Comment by Snuffleupagus** [comment]
> I am trying to create a React project on pdfjs v2.10.377 pre-release.

First of all, please note that we cannot provide support for various frameworks (e.g. "React" in this case).
Secondly, note that screen-shots of errors and/or code isn't really helpful in general; please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

I'm guessing that your environment doesn't support optional chaining, and in that case you need to use a `legacy`-build of the PDF.js library instead. Closing as answered, since this is the only information we can provide given the available information.
