### ISSUE TITLE
Reload the pdf document from the top

### ISSUE THREAD

**Issue by oAln** [mozilla/pdf.js#14084]
I'm rendering the pdf document through Mozilla pdf.js which is working fine and after that, I do the scrolling with the help of vanilla javascript.
but when I re-render the different or same pdf in the same session it loaded the pdf document from the last scrolled position.
I wanted to reload/re-render the pdf document from the top.

**Comment by Snuffleupagus** [comment]
Most likely setting the `viewOnLoad` option and/or preference to `1` will do what you want; see also https://github.com/mozilla/pdf.js/blob/93ed4bfa119fe82c1fe1fe9cd7d08b1ae719b49e/web/app.js#L87-L91

The above is a best guess, since this issue is missing basically all of the necessary information in order to be actionable!

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md (rather than deleting/ignoring it).
Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
