### ISSUE TITLE
Sample pdf xfa form doesn't work

### ISSUE THREAD

**Issue by jointri** [mozilla/pdf.js#14088]
[Example](https://experienceleague.adobe.com/docs/experience-manager-learn/assets/pdf-file-types.zip?lang=en)
Tiff image doesn't show up and the form drop downs doesn't work. It works mostly in chrome, but not firefox. Tested in firefox 92 stable, beta 93, and nightly 94. Same results. The drop downs are blank.

**Comment by Snuffleupagus** [comment]
> Tiff image doesn't show up

Tiff support in XFA documents are already tracked in issue #13707, of which this is thus a duplicate.

> the form drop downs doesn't work.

That appears to be a *separate* issue, hence please file a new issue about that specifically!
Note that as mentioned in both https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#issue and the first paragraph of https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, there should only be *one* problem reported *per* issue (to simplify tracking).

When opening an issue, please remember to provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable. Also, please attach the PDF document *directly* to the issue, rather than using a zip-file.
