### ISSUE TITLE
PDF not loading - this.dims is undefined

### ISSUE THREAD

**Issue by henryatzeal** [mozilla/pdf.js#14150]
Attach (recommended) or Link to PDF file here:
https://dol.georgia.gov/document/unemployment-tax/employers-quarterly-tax-and-wage-report-dol-4n/download

Configuration:
- Web browser and its version: Firefox 93
- Operating system and its version: Ubuntu 21.10
- PDF.js version: v2.11.243 (build: 7fb653b19)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF from https://dol.georgia.gov/document/unemployment-tax/employers-quarterly-tax-and-wage-report-dol-4n/download
2. Blue loading bar is stuck at 100, console log error

What is the expected behavior? (add screenshot)
PDF renders

What went wrong? (add screenshot)
PDF Fails to load, console error
https://imgur.com/a/8sHss0G

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by stbensonimoh** [comment]
@calixteman @marco-c Good afternoon from here. My name is Benson Imoh and I am an outreach intern. I would like to take on this issue as my first contribution (it is my first Open Source contribution). I will go ahead and set up the project right away. 
I would appreciate your support on this journey 😄 .
Thank you for the amazing work you do at Mozilla!

**Comment by stbensonimoh** [comment]
Kindly assign me to the issue.

**Comment by stbensonimoh** [comment]
@calixteman @brendandahl ﻿calixte: 
Hi Calixte and Brendan,
I have been able to replicate the issue on Ubuntu 21.10 Firefox. I tried to load the file on Chrome and was able to ascertain that the issue is indeed peculiar to the configuration as stated in the Issue.
I also found out in `src/core/xfa/factory.js` that the `this.dims` returns undefined because `this.pages` is null/undefined as well. However, I do not know how to proceed or what to do next.

Please help. I would really like to fix this issue. Thanks in anticipation.

**Comment by calixteman** [comment]
I'm attaching the pdf to have a link for the test.
[dol4n.pdf](https://github.com/mozilla/pdf.js/files/7528643/dol4n.pdf)
