### ISSUE TITLE
Image not shown

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#14200]
Attach (recommended) or Link to PDF file here:
[PDFBOX-5307-reduced.pdf](https://github.com/mozilla/pdf.js/files/7425315/PDFBOX-5307-reduced.pdf)

This is reduced from [here](https://issues.apache.org/jira/browse/PDFBOX-5307). The problem is somehow related to softmask / transparency group.

Configuration:
- Web browser and its version: FF 93.0
- Operating system and its version: W10.0.19042.1288
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. open the file
2.

What is the expected behavior? (tried with Adobe Reader and Ghostscript)
![grafik](https://user-images.githubusercontent.com/6665575/139049125-cd4fdfbe-edc6-44a2-b704-909a3f44f892.png)

What went wrong?
all white

**Comment by Snuffleupagus** [comment]
The reduced test-case in https://github.com/mozilla/pdf.js/issues/14200#issue-1037263879 looks small/simple enough that, compared to many other SMask issues, it'll *hopefully* be reasonable to debug this in detail. /cc @brendandahl

**Comment by brendandahl** [comment]
I'm still not really sure on this one, but it may be from transparency group isolation. The smask transparency group doesn't specify an "I" value so it defaults to be a "non-isolated" group. This means we should fill the transparency group canvas with what was already drawn in the parent group to start. That fixes the above issue, since the smask is then filled with white first. However, there are sections in the spec that say for a luminosity soft mask the initial backdrop color should be black. 🤷
