### ISSUE TITLE
Introduce a release schedule, and shorten the time between releases

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#14226]
Currently we don't have a set release schedule, which sometimes result in quite long times between releases (and also leads to issues along the lines of "When is the next stable release?").

To address this, I'm thus proposing that we first of all introduce a release schedule and secondly that we also shorten the time between releases.
In particular, I'd suggest that we basically try to follow the Firefox release schedule (perhaps with a small offset, e.g. creating a new release the weekend that follows each Firefox release); see https://wiki.mozilla.org/Release_Management/Calendar

The advantages of these changes include:
 - A much more predictable release schedule, reducing user confusion about when future releases will happen.
 - Shorter release cycles, meaning that e.g. bug fixes, performance improvements, and new features will reach users much sooner (since most users seem unwilling to utilize the pre-releases, despite those being generally very stable).
 - A shorter release cycle would also mean that any regression fixes would reach stable releases much faster.
 - Shorter release cycles would mean that there's *a lot fewer* changes in each release, especially e.g. `api-minor` ones, which should hopefully make updating easier for users.
 - Shorter release cycles would also reduce the total amount of time that we need to keep `deprecated`-functionality around, improving readability/maintainability of e.g. the API-code.

The disadvantages of these changes include:
 - The PDF.js release process includes a couple of manual steps, and more frequent releases would thus be taking more time overall for the contributor creating the release (which for the last few years has been handled *excellently* by Tim).
 - Shorter release cycles could possibly make it more difficult for users to keep up with updates.

/cc @timvandermeij Any ideas/opinions about these suggestions?

**Comment by Snuffleupagus** [comment]
> at the very least #12324 needs to be fixed so that we take one manual action out of the equation.

Oh right, that issue is a quite annoying one!

**Comment by Snuffleupagus** [comment]
I suppose that there's a *potential* work-around for #12324, at least I think so, which would be to only publish a stable release.

Some of the reasons for only having a *stable release* (and removing the pre-release) would be:
 - There's essentially no stability difference between the current stable/pre-release versions, since all patches must be both tested and reviewed before they can land.
 - Many users seem completely unwilling to use anything except releases officially marked as *stable*, even after informing users (who are asking for the next stable release date) about the point above.
   Without any usage statistics we cannot know how common this situation is, however based on GitHub issues, IRC conversations (back when that was used), and https://www.npmjs.com/package/pdfjs-dist?activeTab=versions it would seem that the pre-releases are mostly "unused".
 - The whole point of even having a pre-release in the first place, would be to actually update/re-create it when regressions are found. In practice, throughout the history of this project, that *almost never* happens and any regression fixes are simply included in an upcoming release instead. (Probably at least somewhat related to the manual work involved in creating a release.)
 - Closely related to the previous two point is that a pre-release is only useful, w.r.t. finding regressions, if a sufficient number of users are actually willing to try it out. In practice most regressions aren't reported until a release has already become the *stable* version, at which point it's mostly "too late" to fix a regression in that release anyway.
 - We're already providing preview-builds, via https://github.com/mozilla/pdf.js#online-demo and https://github.com/mozilla/pdf.js/tree/gh-pages, for users wanting to test the absolutely latest development version.
 - By only having *one* official release at a time, providing user support becomes simpler.
 - Having only a stable release would effectively shorten the release cycle even more, see the points in https://github.com/mozilla/pdf.js/issues/14226#issue-1043420197, meaning that improvements reach users faster.

**Comment by brendandahl** [comment]
In the meantime, I'm happy to give either/both of you npm access to publish releases. I'd like to fix #12324, but it is a bit painful to debug and setup everything. If anyone wants to look into #12324 themselves, I can spin up another ec2 instance where we can create a dummy repo for debugging.

**Comment by timvandermeij** [comment]
@Snuffleupagus Sorry for the delay here, I was on vacation for a few days. I think https://github.com/mozilla/pdf.js/issues/14226#issuecomment-960955499 would also work just fine for me and I like the idea of simplifying the releases (in order to also put them out faster). That would indeed mean that #12324 doesn't have to be fixed anymore since publishing releases works just fine; it's only editing an existing release that causes issues there.

@brendandahl Do you have ideas w.r.t. https://github.com/mozilla/pdf.js/issues/14226#issuecomment-960955499? If you also like the idea of only one release and putting that out more often, I'd say we can get that sorted, but only if you don't have concerns.

**Comment by Snuffleupagus** [comment]
> Sorry for the delay here, I was on vacation for a few days.

No worries; I hope you had a nice time!

**Comment by Snuffleupagus** [comment]
@brendandahl Ping, any objection only having stable releases; please see https://github.com/mozilla/pdf.js/issues/14226#issuecomment-960955499?

**Comment by brendandahl** [comment]
No objections here. Let's go for it.

**Comment by timvandermeij** [comment]
In order to proceed with this, I think we first need to make the current pre-release version stable and do a manual NPM push for the last time. Once that version is stable for some time, we can then make new stable-only releases.

Alternatively, we just make a new stable version and essentially "skip" the current pre-release version, but I'm not sure if that is confusing perhaps?

In any case, we'll need to make some adjustments to the website and the botio scripts to not deal with beta versions anymore, in particular the NPM push to the `next` tag needs to go; it should only push to to the `latest` tag.

**Comment by Snuffleupagus** [comment]
> Alternatively, we just make a new stable version and essentially "skip" the current pre-release version, but I'm not sure if that is confusing perhaps?

That's my idea, for overall simplicity, since any confusion would be a one-time thing.

> In any case, we'll need to make some adjustments to the website and the botio scripts to not deal with beta versions anymore,

I *believe* that both the gulpfile and website already handles this, given e.g. the following code:
https://github.com/mozilla/pdf.js/blob/3a8318aa1c338898961fab19d939f0d20c1606ef/gulpfile.js#L1973-L1985

However, it might not hurt to clean-up/remove all the beta-version handling there (and elsewhere) if we're indeed not going to be using it any more.

> in particular the NPM push to the `next` tag needs to go; it should only push to to the `latest` tag.

Looking at https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js it seems that we currently push a stable release without a tag. According to https://docs.npmjs.com/adding-dist-tags-to-packages#publishing-a-package-with-a-dist-tag, it *appears* that doing so would default to using the `latest` tag (unless I'm misunderstanding things completely).

**Comment by Snuffleupagus** [comment]
Is there any additional blockers here, or could any remaining (clean-up) work be done in follow-ups?

**Comment by timvandermeij** [comment]
I don't think so, and since the last release was quite some time ago I'll just carry on with the release now. If we find anything along the way that we need to fix, I'll comment that here. Let's see how it goes :-)

**Comment by timvandermeij** [comment]
The stable release (version 2.12.313) is done, the release process is updated and publishing to NPM worked too. Only updating `pdfjs-dist` didn't work because we forgot https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js#L20-L27 existed. 

For this release the following still needs to happen:

- [ ] Manually push the `pdfjs-dist` commit for this time (@brendandahl Could you do this? Basically https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js#L26 on the bot.)

For the beta to be gone the following still needs to happen:

- [ ] Remove the `next` tag on NPM since it will now never be updated anymore and we don't want to keep advertising an old version (@brendandahl Could you do this?)
- [ ] Remove the beta logic from https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js#L20-L27 and update the bots for the next time.
- [ ] Remove the beta logic from the Gulpfile/website/`pdfjs.config` file.

**Comment by brendandahl** [comment]
Should be good to go. Let me know if there's anything else.

**Comment by timvandermeij** [comment]
Great, thank for you doing this! Overall the release process is now easier and more automated, so that's really good.
