### ISSUE TITLE
Does pdfs.js use hint table in linearized pdfs? Very slow random page access.

### ISSUE THREAD

**Issue by pkgitlab** [mozilla/pdf.js#14224]
Attach (recommended) or Link to PDF file here: https://assets.studyring.org/assets/books/baws/TN/Tamil_Volume10_opt.pdf

Configuration:
Web browser and its version: Chrome 95.0.4638.54 (Build officiel) (64 bits)
Operating system and its version: Mac OS 11.6
PDF.js version: latest from github
Is a browser extension: No

Steps to reproduce the problem:
1. A pdf downloaded from archive.org, used qpdf to linearize it.
2. I am using a private copy with viewer.html where autofetch and streaming is disabled
2. I am relying on byte-range reads to only read relevant portion of data to display a page
3. Random access page in pdf with over 500 pages

What is the expected behavior? 
I expect pdfs.js to load pdf quickly, at least the first page, then I expect the pdf.js to be able to quickly jump to page 44, 99, 210 etc.  Each page may not be more than 200KB and my backend is AWS and it supports byte range reads

What went wrong? 
When I see in developer tools I see pdf.js reading over 8 MB to display a page (things eventually get cached, but 8MB per random page read is not desirable)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
temporary page : https://assets.studyring.org/pdfjs/generic/web/viewer.html?file=https://assets.studyring.org/assets/books/baws/TN/Tamil_Volume10_opt.pdf

We need this badly as we wont be able to afford our AWS cost if users read 8MB for random access to a page (our scenario expects people to share links of different pages)

**Comment by Snuffleupagus** [comment]
> Does pdfs.js use hint table in linearized pdfs? 

No, the Linearization-data is only used when fetching the *first* page and to determine the number of pages in the document.
More "advanced" features are not implemented, since the basic ones still improve performance a great deal for the "regular" PDF.js use-case (as the built-in PDF Viewer in Firefox). Please note that the Linearization-support that exists in the PDF.js library was simply implemented to allow PDF documents to *start rendering immediately*, since by default (e.g. in Firefox) the entire document is always fetched and subsequent page access thus won't be negatively affected in the general case.

> [...] then I expect the pdf.js to be able to quickly jump to page 44, 99, 210 etc.

Part of the performance issue, in your particular document, isn't limited to just fetching the data of the page in question. It appears that your document uses JPEG2000-images everywhere and those are slower to decode than e.g. standard JPEG-images, hence part of the issue here might be that the *rendering performance* isn't that great (once the data has been fetched).

---

Looking briefly at the relevant part of the PDF specification (regarding the "Hint Tables"-functionality) and considering the main PDF.js use-case (i.e. Firefox), I'm not entirely convinced that the added code/complexity required to support "Hint Tables" is worth it unfortunately; all-in-all closing as WONTFIX.

**Comment by pkgitlab** [comment]
Thank you, this explanation helped a lot.  I finally figured out that hinttable were not the main problem, the getPageDict function was running  in recursion too because the pdf had objects spread all over the places.  After coalescing the pdf the per page access works very nicely and also response is good too.
