### ISSUE TITLE
Parts of PDF with non-ASCII characters not rendering properly

### ISSUE THREAD

**Issue by Ankit404butfound** [mozilla/pdf.js#14237]
I am using pdfjs with pyqt5 to render and display some pdf files to the client, but non-ASCII characters are not visible or they are very faint.

Attach (recommended) or Link to PDF file here: https://github.com/Ankit404butfound/SmartClassLibrary/blob/main/enc_3790_StnnZIhQm9%20-%20Copy-2.pdf

Configuration:
- Web browser and its version: Chrome 95.0.4638.69 (Official Build) (64-bit)
- Operating system and its version: Windows 10 Home (20H2)
- PDF.js version: v2.10.377
- Is a browser extension: No

Steps to reproduce the problem:
1. Clone this repo https://github.com/Ankit404butfound/SmartClassLibrary
2. Run the .py file

What is the expected behavior? (add screenshot)
![image](https://user-images.githubusercontent.com/54436840/140505168-f7fb37a8-d128-41e8-b993-f498c0f9111d.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/54436840/140505215-b7d2f6c3-eaef-4da8-89cd-f9a6d11a7441.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): None

**Comment by Snuffleupagus** [comment]
> I am using pdfjs with pyqt5 to render and display some pdf files to the client,

Unfortunately that's not a configuration that we can support, and it's quite likely that the issue is related to the Qt-framework.
The only suggestion, since your environment might not handle font-loading correctly, is to set `disableFontFace = true` when calling `getDocument`; please see https://github.com/mozilla/pdf.js/blob/e136afbabcc24e3b914852246d49a513667e62be/src/display/api.js#L188-L192 

> Attach (recommended) or Link to PDF file here: https://github.com/Ankit404butfound/SmartClassLibrary/blob/main/enc_3790_StnnZIhQm9%20-%20Copy-2.pdf

That document renders well when opened directly with https://github.com/mozilla/pdf.js#online-demo

**Comment by Ankit404butfound** [comment]
Thanks for the quick response, I will look into it.
