### ISSUE TITLE
UCS-2 encoding—OBSOLETE (use UniGB-UTF16-H)

### ISSUE THREAD

**Issue by lizhengjian1220** [mozilla/pdf.js#14254]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:chrome 93.0.4577.82
- Operating system and its version:windows  10 
- PDF.js version:2.10
- Is a browser extension:no

Steps to reproduce the problem:
1. I found a sentence, on a Github project, that goes something like this:
UniGB-UCS2-H     ISO/IEC 10646 (Unicode), UCS-2 encoding—OBSOLETE (use UniGB-UTF16-H)
<img width="846" alt=" UCS-2 encoding—OBSOLETE (use UniGB-UTF16-H)" src="https://user-images.githubusercontent.com/53615742/140883889-39e2b06e-9faa-4198-93da-84761f06e3c8.png">
 
2.So I want to know. Whether pdf.js supports UnIGB-UCS2-H, 
The code of PDF files would show correctly，Yes  or  No？
I'm a little curious

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

Again, this part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable and valid.

> PDF.js version: 2.10

That's not a complete PDF.js version number!

---

As-is this issue unfortunately isn't actionable since it's missing *too much* of the required information, and furthermore it's also not entirely clear what *exact* problem you're actually trying to reporting here.
