### ISSUE TITLE
2 times '' style=" '' in documentation example

### ISSUE THREAD

**Issue by ubaldiniTerre** [mozilla/pdf.js#14279]
![image](https://user-images.githubusercontent.com/80910468/141997565-2597378d-4579-4f1f-ad9e-eb13dda59829.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable information provided here.

Furthermore, based on the screen-shot it really looks like this issue was opened against the wrong project, since this doesn't look like code found anywhere within this repository!?
