### ISSUE TITLE
pdfs "no results found'

### ISSUE THREAD

**Issue by gthills** [mozilla/pdf.js#14285]
Attach (recommended) or Link to PDF file here: https://gracebaptistottawa.com/parable-of-the-banquet-tract/

Configuration:
- Web browser and its version: chrome Version 95.0.4638.69 (Official Build) (x86_64)
- Operating system and its version: MacOs Version 11.6
- PDF.js version: Version 2.1.4
- Is a browser extension: I don't think so

Steps to reproduce the problem:
1. re-loaded pdfs
2. still 'no results found'

What is the expected behavior? to see the pdf in the viewer. It worked since I first installed it months ago.

What went wrong? (see screenshot)

<img width="1440" alt="Screen Shot 2021-11-17 at 9 55 12 PM" src="https://user-images.githubusercontent.com/94413895/142343842-e8c5f727-be65-4ff1-aa74-47dfeeb9dbfa.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: https://gracebaptistottawa.com/parable-of-the-banquet-tract/

That link seems to point to a HTML file, rather than a PDF file, hence it's somewhat difficult to understand what problem you're trying to report here.

> PDF.js version: Version 2.1.4

That version is no longer supported (and it was not an official release), please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
>     1. re-loaded pdfs
>     2. still 'no results found'
> 
> What is the expected behavior? to see the pdf in the viewer. It worked since I first installed it months ago.

In addition to the previous points, please note that it's unfortunately not possible to provide much (or any) assistance as-is; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
