### ISSUE TITLE
[Feature Request] One click Fit to Page button.

### ISSUE THREAD

**Issue by iDCoded** [mozilla/pdf.js#14286]
I use [PDF.js](https://github.com/mozilla/pdf.js) a lot and I usually require the document to fit to page, but to do so, I first have to click on the **Dropdown** and then select **Page Fit**, which seems a little inconvenient. 

It'd be really helpful if there was a button to quickly **Fit to Page** just like **Edge** has. 

This is what I mean. ⏬ 
![Fit To Page Button](https://user-images.githubusercontent.com/65074550/142357671-467a6358-3df5-4563-af46-c93f77d309eb.png)

**Comment by Snuffleupagus** [comment]
If we were to add a separate button for "page-fit", then we're going to have a difficult time saying "no" when other users start requesting separate buttons for e.g. "auto", "page-actual", and "page-width" which would very quickly end up making the toolbar looking really cluttered.

Furthermore, please note that you can set the `defaultZoomValue` preference to "page-fit" in order to *by default* load all documents with that zoom-level (for the Firefox *built-in* PDF Viewer, search for that preference in about:config).

All-in-all, closing as WONTFIX.

---

Also, if you're using the default viewer in a custom implementation, please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
