### ISSUE TITLE
Open file button not working in pdf.js demo in firefox VR browser

### ISSUE THREAD

**Issue by pavul** [mozilla/pdf.js#14284]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: firefox VR last version
- Operating system and its version: oculues quest 2 OS
- PDF.js version:
- Is a browser extension:
no, is a pdf.js demo

Steps to reproduce the problem:
1. open firefox VR browser in oculus quest 2 clip open file at top right in the screen, and clicking on that button does not open the file to load a new PDf
2. i have to say that opening a new pdf works in oculues quest 2 browser

What is the expected behavior? (add screenshot)
you will be able to select a new pdf file from oculus quest 2 storage and load a new PDF

What went wrong? (add screenshot)
clicking open file button does not work, does not open the interface to load the file

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

NOTE: is important to me because i use the demo to read PDF in firefox VR browser

**Comment by Snuffleupagus** [comment]
Sorry, but this sounds like a bug in the *browser itself*, rather than the PDF.js library, and note that we always try to limit browser-specific compatibility-hacks in the code-base.
Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for a list of the currently supported browsers.
