### ISSUE TITLE
Viewer: Improving the printing process

### ISSUE THREAD

**Issue by andraaspar** [mozilla/pdf.js#14282]
Steps to reproduce the problem:
1. Print any PDF from the viewer in Chrome / Edge / Firefox on the desktop.

What is the expected behavior? (add screenshot)
A smooth experience. No loss in quality.

What went wrong? (add screenshot)
It crashes on large PDFs on low-end systems. It is slow. It is low quality (text is pixelated).

There is a better way to print a PDF: [print.js](https://github.com/crabbly/print.js) ([website](https://printjs.crabbly.com/)). I just had to replace the built-in printing solution with print.js in a project. It solved all the aforementioned issues, although it was not easy or straightforward to replace the default. Maybe this solution could be the default in pdf.js? Or maybe it could be an option?

**Comment by Snuffleupagus** [comment]
Please keep in mind that the Firefox *built-in* PDF Viewer is the main development target of this library, and there we have slightly better support for printing (using the `mozPrintCallback` functionality).

For the GENERIC viewer I don't believe that we want to provide support for third-party printing frameworks, since we generally try to avoid using third-party resources in the main code-base, to lessen the maintenance burden of having to keep up with a moving target.
Closing as answered, or possibly wontfix, since (as far as I know) no changes are planned for the GENERIC printing code.

**Comment by Snuffleupagus** [comment]
Also, looking *very briefly* at the `Print.js` code it seems that it's not really "printing" PDF documents but rather just hands the file off to the browser to handle it natively (and hoping that works). If so, then the comparison becomes somewhat strange since the PDF.js viewer will *actually generate* the data for printing (as an image, to improve browser compatibility).

**Comment by andraaspar** [comment]
@Snuffleupagus You are right, print.js simply hands the PDF to the browser and triggers printing. I was suggesting that:
1. either the technique could be ported into the GENERIC pdf.js viewer,
2. or the GENERIC pdf.js viewer could make it easier to replace the default printing implementation. As it is, it seems to implement the printing function twice. Once in handling the print button and another in handling Ctrl-P. It could be easier.

**Comment by Snuffleupagus** [comment]
> either the technique could be ported into the GENERIC pdf.js viewer,

That'd mean that the printed result would no longer be *guaranteed* to agree with what's displayed in the PDF.js viewer, since printing would instead use the *browser* implementation rather than the PDF.js one. That just seems like a good way of getting loads of bug reports, that we then can't do anything about, regarding inconsistent printing in different browsers when using the GENERIC viewer.

> or the GENERIC pdf.js viewer could make it easier to replace the default printing implementation.

That should already be somewhat possible, please refer to the following code for the expected interface of print functionality: https://github.com/mozilla/pdf.js/blob/3209c013c411ace4414246a153eac26eea640aba/web/app.js#L3105-L3113

Please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Furthermore, please note that given the *fairly limited* printing support in the web-platform itself, we're forced to jump through some hoops in order to provide even the current level of printing support in the GENERIC viewer.

> As it is, it seems to implement the printing function twice. Once in handling the print button and another in handling Ctrl-P.

What's implemented *twice*!? Regardless of how printing is being triggered in the GENERIC viewer, the same exact code will be invoked to handle the actual printing as far as I can tell.

All-in-all, we'll not be implementing either of these things in the GENERIC viewer unfortunately.

**Comment by andraaspar** [comment]
OK, no worries. Thank you for taking the time to review my request.
