### ISSUE TITLE
Backgrounds render incorrectly on Safari in SVG mode

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#14300]
Attach (recommended) or Link to PDF file here:

[test.pdf](https://github.com/mozilla/pdf.js/files/7594170/test.pdf)

Configuration:
- Web browser and its version: Safari 15.1
- Operating system and its version: macOS Monterey
- PDF.js version: latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Render file in SVG mode on Firefox or Chrome
2. Render file in SVG mode on Safari, compare.

What is the expected behavior? (add screenshot)

![projects wojtekmaj pl_react-pdf_test_ (1)](https://user-images.githubusercontent.com/5426427/143206817-1c8151c0-7726-4517-b170-9a9216df37f1.png)

What went wrong? (add screenshot)

![Zrzut ekranu 2021-11-24 o 10 01 20](https://user-images.githubusercontent.com/5426427/143206915-3760a6cd-e487-4fa3-bbcd-7e714a92f66a.png)

_Originally raised by @pakindessama in https://github.com/wojtekmaj/react-pdf/issues/896_

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. Render file in SVG mode on Firefox or Chrome
>     2. Render file in SVG mode on Safari, compare.

First of all, please note that as mentioned in the FAQ the SVG-backend is *not officially supported* and it's consequently not supposed to be used in production; note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends
Secondly, if the bug is specific to a *particular browser* it unfortunately suggests a bug in the browser itself, rather than in the PDF.js library since otherwise you'd really expect it to be consistently broken everywhere.
