### ISSUE TITLE
SVG: XML not well-formed

### ISSUE THREAD

**Issue by doublex** [mozilla/pdf.js#14323]
This PDF:  [x-589.pdf](https://github.com/mozilla/pdf.js/files/7618178/x-589.pdf)

Steps to reproduce:

````
git clone https://github.com/mozilla/pdf.js.git
cd pdf.js
npm install
node_modules/.bin/gulp dist-install
node examples/node/pdf2svg.js ~/x-589.pdf

file: svgdump/x-589-1.svg
````

Issue:
````
<svg:tspan font-family="Courier" font-size="19.44px" y="0" x="0 11.664 23.328 34.992 46.656 58.32" fill="none">
*•]]>'
</svg:tspan>
````

**Comment by Snuffleupagus** [comment]
> *•]]>'

But, that's the *actual* text-content used in the document. Hence I really don't think we can fix that without actually breaking something (and the viewer still seem be able to open that document in SVG-mode).
Given the above, and https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends, closing as WONTFIX or possibly even INVALID, since I cannot imagine how this would be fixed.

**Comment by doublex** [comment]
text-content should be xml-encoded (`>` -> `&gt;`)
I don't think is issue is invalid.

**Comment by Snuffleupagus** [comment]
> text-content should be xml-encoded (`>` -> `&gt;`)

That would *break rendering*, since that char is actually referencing the relevant font-char in the non-embedded font used in the PDF document; hence why this cannot be fixed.
However, a *possible* work-around could be to ensure that the API option `useSystemFonts = false` is used; please see https://github.com/mozilla/pdf.js/blob/700eaecddd25d0a612fdb52dbb713deb983df84c/src/display/api.js#L163-L167

**Comment by doublex** [comment]
@Snuffleupagus 
Sorry for the inconvenience - and thanks for explaining!
