### ISSUE TITLE
Unable to render font family

### ISSUE THREAD

**Issue by rynangeles** [mozilla/pdf.js#14330]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10
- PDF.js version: 2.10.377
- Is a browser extension: No

Steps to reproduce the problem:
1. Updating project dependency pdfjs-dist@2.0.274 to 2.10.377
2. Custom rendering of texts
3. Make sure FontFaces are added to document
![Screenshot 2021-12-01 032105](https://user-images.githubusercontent.com/3428202/144113644-d16a9d5f-fdd6-445a-87fa-f7721bc436a6.png)

What is the expected behavior? (add screenshot)
2.0.274 renders texts based on font-family styles 
![Screenshot 2021-11-25 062236](https://user-images.githubusercontent.com/3428202/144113270-a52427f4-479e-4a8d-8d73-53d4f22b7b7b.png)

What went wrong? (add screenshot)
2.10.377 always use fallback font family
![unnamed](https://user-images.githubusercontent.com/3428202/144113771-6e08cde3-2c82-497d-8e18-e62ba2e8c50b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable.

> Steps to reproduce the problem:
>     1. Updating project dependency pdfjs-dist@2.0.274 to 2.10.377
>     2. Custom rendering of texts
>     3. Make sure FontFaces are added to document

While it's somewhat difficult to tell from the description, it sounds like this is maybe related to a *custom* implementation; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
> Updating project dependency pdfjs-dist@2.0.274 to 2.10.377

Please note that it's also quite difficult to assist with an upgrade from a PDF.js version that's almost *four years old*, and that `2.0.274` was also never an [official release](https://github.com/mozilla/pdf.js/releases).

Given the lack of details it's difficult to tell, but if I were to *guess* you might have been utilizing the fonts (as parsed by the PDF.js library) in a non-intended and thus unsupported way. Please keep in mind that rendering and text-extraction uses different code-paths in PDF documents, and we've never supported using the font-files themselves for e.g. text-selection purposes.
It's possible that e.g. the changes in PR #9340 could be relevant for the issue you're having, but please note that as mentioned above it's unfortunately quite possible that you were doing something that neither is (nor was) officially supported.

All-in-all, closing as INCOMPLETE for now since we cannot help given the currently provided information.

**Comment by rynangeles** [comment]
@Snuffleupagus sorry for the incomplete details of my issue. Basically, I was planning to update my project dependencies.
Application: https://typescript-35ttx9.stackblitz.io/ 
Code: https://stackblitz.com/edit/typescript-35ttx9?file=index.html  
this is the actual code I use to render the PDF and the custom text layers. 

In 2.0.274 I was able to display fontFaces of each text layer by just adding the **textItem.fontName** to its font-family rule in styles (as shown in my initial screenshots). e.g. **font-family: g_d0_f1, sans-serif;**. But in 2.10.377 its not rendering the fontFace.
