### ISSUE TITLE
[Question] Is the `legacy` build ever going to be removed?

### ISSUE THREAD

**Issue by MichaelDeBoey** [mozilla/pdf.js#14343]
Hi team!

When updating my version of `pdfjs-dist` I noticed that the `es5` build was renamed to `legacy`.
This suggests that it's going to be removed at some point in the future.

I'm however using it in a Node app, just like you are also doing in the [Node `getinfo` example].(https://github.com/mozilla/pdf.js/blob/dc455c836e80799fccd8f1741eb8f62e9ec01c37/examples/node/getinfo.js)
https://github.com/mozilla/pdf.js/blob/dc455c836e80799fccd8f1741eb8f62e9ec01c37/examples/node/getinfo.js#L11

So I was wondering if the `legacy` build is going to be removed at some point or not?
If not, I think a rename to `node` would be a good idea to make this more clear.

Thanks for taking the time to answer my question and keep up the good work!

**Comment by Snuffleupagus** [comment]
> [...] I noticed that the `es5` build was renamed to `legacy`.

That was done since the `es5` name wasn't accurate any more, and were causing user confusion, given that it now includes some JS features not present in ES5 (e.g. arrow functions).

> This suggests that it's going to be removed at some point in the future.

Nope; it's simply intended for environments that lack support for the *latest* ECMAScript version[1], and as such there aren't any plans to remove it. Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for information about the *currently* supported browsers.

---
[1] This includes both *slightly* older browsers, as well as Node.js of course.

**Comment by MichaelDeBoey** [comment]
Thanks for the explanation @Snuffleupagus! 👊
