### ISSUE TITLE
Multiple PDF render on same page.

### ISSUE THREAD

**Issue by yadavendra15** [mozilla/pdf.js#14352]
Hey there! First of all thank for creating this amazing lib. It's really awesome.. and i was using the prev/next example by pdf js.

I was trying it render inside the dynamic tabs.. where inside tabs.. we can open pdfs.. but I think PDFWorker is not able to render the multiple pdf at a time.
If it is possible. then , What will be the change probably  to do it.

**Attach (recommended) or Link to PDF file here:** Fiddle of pdf.js example : https://jsfiddle.net/pdfjs/wagvs9Lf/

**Configuration:**
- **Web browser and its version:** Google Chrome - Version 96.0.4664.45
- **Operating system and its version:** Windows 8.1 - 64 bit
- **PDF.js version:** 2.5.207
- **Is a browser extension:** no

**Steps to reproduce the problem:**
1.  Try to make same pdf viewer in same html page.. and try to prev/next.. it will render both the documents

**What is the expected behavior? (add screenshot)**
I want that pdf render will work for every document respectively.

**What went wrong? (add screenshot)**
it will render both the documents simultaneously.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.5.207

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Fiddle of pdf.js example : https://jsfiddle.net/pdfjs/wagvs9Lf/
> [...]
> Steps to reproduce the problem:
> 1. Try to make same pdf viewer in same html page.. and try to prev/next.. it will render both the documents

It's really quite difficult to connect that example with your questions, since there's only *one* document present there!?
Without a *proper reduced* test-case, and a clearer description of the problem, it's unfortunately not really possible to help; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
