### ISSUE TITLE
ERROR in node_modules/pdfjs-dist/legacy/web/pdf_viewer.d.ts  - error TS2691: An import path cannot end with a '.d.ts' extension. 

### ISSUE THREAD

**Issue by vnktdinesh** [mozilla/pdf.js#14357]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:All Browsers
- Operating system and its version: Windows 8, 10,11, windows server 2012, 2016
- PDF.js version: 2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1. Myne is an Angular web application and CLI version is 10.1.0 
2. I have Updated the pdfjs version from 2.5.207 to 2.9.359 
3. installed the dependencies "@types/pdfjs-dist": "^2.10.378"" 
2. we use PDFViewer, EventBus and in earlier version we import from "**pdfjs-dist/es5/web/pdf_viewer**";
3. After upgrade importing from "**pdfjs-dist/legacy/web/pdf_viewer**" but getting issue as ---> ERROR in node_modules/pdfjs-dist/legacy/web/pdf_viewer.d.ts:1:15 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing 'pdfjs-dist/types/web/pdf_viewer.component' instead.

What is the expected behavior? (add screenshot)
I should able to use PDFViewer, EventBus with no build errors, so that I can use to display the signed information in web application.  How to get .d.ts files excluded or how to get them ignored from build so that application will be working 

What went wrong? (add screenshot)
ERROR in node_modules/pdfjs-dist/legacy/web/pdf_viewer.d.ts:1:15 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing 'pdfjs-dist/types/web/pdf_viewer.component' instead.

if we remove '.d.ts' file in nodemodules folder the build is working fine but we can't do that in build pipeline steps. 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.9.359
> [..]
> I have Updated the pdfjs version from 2.5.207 to 2.9.359

Neither of those versions are supported any longer, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> installed the dependencies "@types/pdfjs-dist": "^2.10.378""

The `pdfjs-dist` library ships it own types now, please see https://github.com/mozilla/pdfjs-dist/tree/master/types and note also that we've never supported the *unofficial* ones provided by https://github.com/DefinitelyTyped/DefinitelyTyped

> After upgrade importing from "**pdfjs-dist/legacy/web/pdf_viewer**" but getting issue as ---> ERROR in node_modules/pdfjs-dist/legacy/web/pdf_viewer.d.ts:1:15 - error TS2691: An import path cannot end with a '.d.ts' extension. Consider importing 'pdfjs-dist/types/web/pdf_viewer.component' instead.

Looking at https://github.com/mozilla/pdfjs-dist/blob/master/legacy/web/pdf_viewer.d.ts, the import seems fine to me (with the caveat that I don't really know TypeScript). Most likely the old, and unsupported, PDF.js version used is related to the problem you're seeing.

Please update to the *latest* PDF.js version and try again, since the versions mentioned are no longer supported.
If that's not enough to address this issue, then please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
