### ISSUE TITLE
number word in pdf

### ISSUE THREAD

**Issue by nacimgoura** [mozilla/pdf.js#14353]
Hello,
It would be useful to add a function to get the number of words in the pdf.

**Comment by Snuffleupagus** [comment]
Given how text is handled in PDF documents, there's really no concept of "words" in the *general* case since text rendering is done using individually positioned glyphs. Furthermore, the PDF.js library will not parse all of a document upon load (in order to save resources), hence anything that'd required iterating through the *entire* document isn't a feature we'd consider adding either.

All-in-all, closing as WONTFIX.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md). Furthermore, even as a feature request this issue is a little "light" on the details.
