### ISSUE TITLE
Issues with downloading / Printing content PDF document

### ISSUE THREAD

**Issue by suminda1** [mozilla/pdf.js#14375]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Safari latest
- Operating system and its version: iOS 13/15
- PDF.js version:2.2.171
- Is a browser extension:

Steps to reproduce the problem:

when you clicked download button, nothing happens, document is not downloaded.
![image](https://user-images.githubusercontent.com/7395061/146119318-9f138248-5653-43cd-a389-26252724fa9f.png)

if you click "Print" and "Save as PDF", it will save an empty PDF.
![image](https://user-images.githubusercontent.com/7395061/146119464-17048cff-51fb-4797-82e1-1b69b0a7e368.png)

[real iPhone7/ios13] when you click "download" and then select "done" > screen is auto-locked.

![Untitled](https://user-images.githubusercontent.com/7395061/146119852-532774e5-e894-4012-8f23-f2166d173c89.png)

 see below, after you tap "download" button

![image](https://user-images.githubusercontent.com/7395061/146119564-4260cdc4-47c9-471c-afe7-2af0c78c670b.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.2.171

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Furthermore, this issue is little "light" on the details, but it really looks like a *browser and/or platform* specific problem rather than a PDF.js library/viewer one (since otherwise you'd expect it to be consistently broken everywhere); hence it unfortunately doesn't look like something that we can fix here.
