### ISSUE TITLE
Chrome 79 fails to parse pdf.js from v2.10.377

### ISSUE THREAD

**Issue by jwoodwardtfx** [mozilla/pdf.js#14384]
Using Chrome 79, in the Chrome Debugger console I get: **Uncaught SyntaxError: Unexpected token '.' pdf.js:2267** 

It seems this traces to:

  **async getXfa() {
    return this._transport._htmlForXfa?.children[this._pageIndex] || null;
  }**

I'd guess the **_?_** before the **_._** isn't supported on older Chrome versions?

(for reference, I get pdf.js from https://www.jsdelivr.com/package/npm/pdfjs-dist?path=build)

Thanks

**Comment by Snuffleupagus** [comment]
Please note e.g. https://github.com/mozilla/pdfjs-dist/blob/master/README.md (emphasis mine):
> PDF.js is a Portable Document Format (PDF) library that is built with HTML5. Our goal is to create a general-purpose, web standards-based platform for parsing and rendering PDFs.
>
> This is a pre-built version of the PDF.js source code. It is automatically generated by the build scripts.
>
> **For usage with older browsers or environments, without support for modern features such as e.g. `async`/`await`, `ReadableStream`, optional chaining, and nullish coalescing; please see the `legacy` folder.**
>
> See https://github.com/mozilla/pdf.js for learning and contributing.

**Comment by quiram** [comment]
Hi. I am having a related issue, in my case is with failing to parse the logical OR assignment used in later versions of pdf.js; the odd thing is that we're using node v16.9.1, which in theory supports this language feature. I know that the problem is most probably on my side but I'm struggling to find the root cause so posting here in case anybody has stumbled upon it before.

**Comment by markb-trustifi** [comment]
Those who has problem running it on Node.js please require lib from this folder:
`pdfjsLib = require('pdfjs-dist/legacy/build/pdf.js')`
