### ISSUE TITLE
Backporting a fix to v1.x

### ISSUE THREAD

**Issue by mateuszwitkowski** [mozilla/pdf.js#14381]
Hi!
We're experiencing an issue with rendering PDF in Chrome > 92 and FF > 90. The underlying issue was fixed in PDF.js v2.x with this commit: https://github.com/mozilla/pdf.js/commit/52fb5abb0b69025cf5888af2491c06141fb9cdc8

Unfortunately we're still using v1.x and it's not possible for us to upgrade. Is it possible to backport this fix (it is backwards-compatible) and release one more v1.x version?

Best regards
Mateusz

**Comment by Snuffleupagus** [comment]
> Unfortunately we're still using v1.x and it's not possible for us to upgrade.

Sorry, but the `1.x` branch is *completely unsupported* now (and has been for years) and really shouldn't be used at all.
There's been thousands of bug fixes since then, not to mention a lot of new features added and also performance improvements.

Hence you *really* should try to update to a supported release (see https://mozilla.github.io/pdf.js/getting_started/#download) since those are the only ones we support, but otherwise you'll have to *manually patch* the old release yourself.
