### ISSUE TITLE
Display multiple files successively using pdf.js

### ISSUE THREAD

**Issue by dadouch** [mozilla/pdf.js#14407]
Dear All,

I'm using PDF.Js into my Blazor application in order to diplay PDF document and insert digital signature. The goal is to display and sign multiple files successively. However, the current version of PDF.Js is keeps displaying the first loaded PDF although the new URL data is correctly received. I need to reload the whole component with the new data to get the correct behaviour.
Is there any way to reset the canvas and load new PDF data ?

Best regards.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't really actionable (nor easy to understand).

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
