### ISSUE TITLE
Typescript error accessing the library function getDocument

### ISSUE THREAD

**Issue by chetanrang** [mozilla/pdf.js#14403]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: 2.1
- Is a browser extension: no

Steps to reproduce the problem:
1. Generate type definition - Type definitions for PDF.js v2.1, with npm install command
2. Types generated in folder - <my proj folder>\node_modules\@types\pdfjs-dist
3. Indes.d.ts has function as below
declare function getDocument(.....
4. I create my own .ts file to access this library type and call funtion
import * as React from "react";
import * as PDFJS from "pdfjs-dist";

var resultDoc = await PDFJS.default.getDocument(this.state.documentUrl).promise;

What is the expected behavior? (add screenshot)
It works fine in runtime but TS gives compile error for above line acessing getDocument() below
----
Property default does not exist on 'type of import"(<my proj folder>\node_modules\@types\pdfjs-dist)"'.
Symbol 'default' cannot be properly resolved, probably it is located in inaccessible module.
--
Note: If we do not use default.getDocument then at runtime in JS the call fails. If we use .default.getDocument then at runtime JS works fine in browser.

What went wrong? (add screenshot)
TS compile error
Let us know how we can access the getDocument type function as per above steps in our custom .TS typescript file without getting error as mentioned

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> * PDF.js version: 2.1

Sorry, but that's not a complete/valid PDF.js version number; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Generate type definition - Type definitions for PDF.js v2.1, with npm install command
> Types generated in folder - \node_modules@types\pdfjs-dist

I'm guessing that you're referring to https://github.com/DefinitelyTyped/DefinitelyTyped, which we never supported here and furthermore please note that we're shipping *official* type definitions in https://github.com/mozilla/pdfjs-dist/tree/master/types

> import * as React from "react";

Unfortunately we cannot provide help/support for React here, since none of the PDF.js contributors really know that framework.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
