### ISSUE TITLE
pdf not showing without error

### ISSUE THREAD

**Issue by SungKyuMM** [mozilla/pdf.js#14406]
hi!

the pdf file to canvers was successful without any problem.

I initially succeeded in loading to canvas without any problems using `npm pdfjs-dist`.
but, for a nice screen, I tried to use the view file. 
so, I downloaded the project from git and use it.

The problem right now is,
the pdf viewer is not showing the pdf content without error.

In the presentation mode, the content is shown.

I am currently using Nodejs's express.
Is it a problem to rename the file html to ejs?

Can you tell me what I should do?

![1](https://user-images.githubusercontent.com/73621323/147561506-6f0445c4-443e-4afd-85d2-e08a40b2e168.PNG)
![2](https://user-images.githubusercontent.com/73621323/147561521-f3e459ee-f9a4-49d4-a74d-6f18179713b7.PNG)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is unfortunately missing every single piece of information required in order to be actionable.

> I am currently using Nodejs's express.

We have no idea what that is, and thus we cannot provide support for it.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
