### ISSUE TITLE
pdf. JS to view PDF. If you find that the contents of the drop-down box cannot be displayed, you can download it

### ISSUE THREAD

**Issue by lipeiyu2106** [mozilla/pdf.js#14410]
![1640742372(1)](https://user-images.githubusercontent.com/67227495/147718821-60250731-1e3d-498e-af17-94c333734cbc.jpg)
我发现在pdf预览的时候就有这种问题，下载就有数据了

**Comment by lipeiyu2106** [comment]
![1640742372(1)](https://user-images.githubusercontent.com/67227495/147718920-318868b2-df83-42b9-ba89-cfd3cd85576d.jpg)
I found this problem during PDF preview. After downloading the display, there will be data

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.
Furthermore, please make sure to always communicate in English and ensure that you provide clear and consists steps to reproduce the problem.
