### ISSUE TITLE
Large pdf breaks on scroll

### ISSUE THREAD

**Issue by itsHel** [mozilla/pdf.js#14420]
Attach (recommended) or Link to PDF file here: https://easyupload.io/qhkmjj

Configuration:
- Web browser and its version: chrome 96.0.4664.110, opera 82.0.4227.43
- Operating system and its version: windows 10
- PDF.js version: 2.13.24
- is extension: no

Steps to reproduce the problem:
1. open pdf in https://mozilla.github.io/pdf.js/web/viewer.html
2. scroll to bottom

What is the expected behavior? (add screenshot)
page loads

What went wrong? (add screenshot)
in chrome pages try to load and then break:
![image](https://user-images.githubusercontent.com/51739304/148226330-a29b33c1-ff94-4684-bb49-9405f40e0a9a.png)

in opera pages eventually load but it takes over 1 minute and 5gb of memory - pdf in question has barely 300mb

**Comment by Snuffleupagus** [comment]
Actually, looking closer at the PDF document I'd even say that the problem is in the document *itself*.
It appears that each page contains the *same identical* JPEG image data, but rather than each page simply referencing the same data it's needlessly duplicated *thirty times*.
Fixing the PDF creation to avoid that would improve performance *significantly*, since that'd then benefit from the existing PDF.js image caching.

**Comment by itsHel** [comment]
Thanks for answer, this is just testing document because original is private - its ever larger with 650mb and 48 pages, unfortunately not the biggest one we have to deal with

Anyway it seems that viewer keeps loading pages even after you scrolled long past them - is that ideal behavior?

I assume this isnt easy to fix/not fixable at all - do you think there is some workaround?

**Comment by Snuffleupagus** [comment]
> Anyway it seems that viewer keeps loading pages even after you scrolled long past them

Pages that are evicted from the `PDFPageViewBuffer` in the viewer will actually have their worker-thread parsing aborted, the problem here is that the (various) image-decoders used in the PDF.js library are *synchronous* and their parsing thus cannot be immediately aborted.

> I assume this isnt easy to fix/not fixable at all - do you think there is some workaround?

Unfortunately it's not easily fixable, and this *particular* issue is also not a common one (other cases benefit greatly from existing caching, which is done by /Reference).
As mentioned in https://github.com/mozilla/pdf.js/issues/14420#issuecomment-1005749257, making sure that the PDF documents will actually re-use identical resources rather than duplicating them should help a great deal.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: https://easyupload.io/qhkmjj

Unfortunately that document is no longer available, and as outlined in https://github.com/mozilla/pdf.js/issues/14420#issuecomment-1005767078 there's not really any simple way to improve performance of these *huge* images.
