### ISSUE TITLE
How to customize the font family for rendering PDF

### ISSUE THREAD

**Issue by yewanji** [mozilla/pdf.js#14433]
I find that the canvas rendered by PDFJS is blurry and the font is small, can I customize the font size and family

**Comment by YuHuaOu** [comment]
I've met the question！

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is unfortunately missing too much information to be actionable.

> can I customize the font size and family

No, since the PDF.js library renders the document using the font data as found in the PDF document itself; as mentioned in the README this project implements a PDF *viewer* and not a PDF editor.
