### ISSUE TITLE
Catch Load Errors

### ISSUE THREAD

**Issue by davehibshman** [mozilla/pdf.js#14451]
When using viewer.js code in an iframe (`web/viewer.html?file=my.pdf"`) and getting a load error like `Error: file origin does not match viewer's` how do I catch this error?  The console reports `app.js:2140 Uncaught (in promise) Error: file origin does not match viewer's`.  I have setup the load listener and am using the `PDFViewerApplication.initializedPromise`.  I was hoping the `PDFViewerApplication.initializedPromise` would reject, but it does not.  I could not find an eventbus event to listen to specifically for load errors either.

I would like to programmatically detect such load errors and dynamically remove the iframe hosting the pdf viewer and instead replace it with my own error messaging.  I can't figure out how to do that.

Configuration:
- Any, but testing on Chrome 97.0.4692.71 64-bit
- Ubuntu 20.04
- PDF.js version:  v2.12.313
- Is a browser extension: No

Steps to reproduce the problem:
1.  Purposely try to load a PDF in a way that would cause the `app.js:2140 Uncaught (in promise) Error: file origin does not match viewer's` error.

**Comment by Snuffleupagus** [comment]
> I was hoping the `PDFViewerApplication.initializedPromise` would reject, but it does not.

That's actually somewhat expected, since the `initializedPromise` is connected to the *viewer* initialization rather than a particular PDF document; please note that the promise is resolved already in https://github.com/mozilla/pdf.js/blob/e0032811cd0d3480fe953d3bf4ade84eccb8541d/web/app.js#L262-L295

> Purposely try to load a PDF in a way that would cause the `app.js:2140 Uncaught (in promise) Error: file origin does not match viewer's` error.

Are you already modifying the viewer source-code by e.g. extending the `HOSTED_VIEWER_ORIGINS` list?
If so, you could also dispatch your own (custom) event e.g. somewhere around https://github.com/mozilla/pdf.js/blob/e0032811cd0d3480fe953d3bf4ade84eccb8541d/web/app.js#L2136-L2139 and then listen for that one.

---

Given that the viewer was/is written *primarily* for Firefox, it's unfortunately not immediately clear that we need to make a lot of changes to support the (somewhat special) use-case in this issue out-of-the-box; please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by Snuffleupagus** [comment]
> I was hoping the `PDFViewerApplication.initializedPromise` would reject, but it does not.

That's actually somewhat expected, since the `initializedPromise` is connected to the *viewer* initialization rather than a particular PDF document; please note that the promise is resolved already in https://github.com/mozilla/pdf.js/blob/e0032811cd0d3480fe953d3bf4ade84eccb8541d/web/app.js#L262-L295

> I could not find an eventbus event to listen to specifically for load errors either.

No such thing exists, or has ever existed, since the use-case does seem somewhat specialized.

(Perhaps we could add a new "documenterror" event, but please note that neither of this really applies to the Firefox PDF viewer.)

> Purposely try to load a PDF in a way that would cause the `app.js:2140 Uncaught (in promise) Error: file origin does not match viewer's` error.

Are you already modifying the viewer source-code by e.g. extending the `HOSTED_VIEWER_ORIGINS` list?
If so, you could also (quite easily) dispatch your own (custom) event e.g. somewhere around https://github.com/mozilla/pdf.js/blob/e0032811cd0d3480fe953d3bf4ade84eccb8541d/web/app.js#L2136-L2139 and then listen for that one.

**Comment by davehibshman** [comment]
I can fire the custom event suggested.  Thanks.
