### ISSUE TITLE
Investigate if using a Service/Shared Worker instead of a Web Worker is better

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14467]
The docs:
 - https://developer.mozilla.org/en-US/docs/Web/API/Service_Worker_API
 - https://developer.mozilla.org/fr/docs/Web/API/SharedWorker
 - https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API
 
In case of service/shared worker we won't have to create a new one each time the user opens a new pdf. But a service worker will likely use more memory because it stays alive when a shared worker is destroyed when no more used but it has to be created within the same origin.
With a web worker, pdfs are parsed in isolation when they won't be with a service/shared worker.
If you've any ideas, feelings, opinions, feel free to share (even to say "it's a stupid idea").

**Comment by Snuffleupagus** [comment]
> In case of service/shared worker we won't have to create a new one each time the user opens a new pdf.

Yes, but in e.g. Firefox wouldn't that mean that *separate* windows/tabs (with PDF documents) would then use the *same exact* worker-thread?
If so, that seems like it could be *really bad* for overall performance though, since any long running parsing (e.g. image decoding) in a single PDF document would then prevent other documents (in other tabs/windows) from parsing and rendering.
Furthermore, if there's ever any errors thrown (in the worker-thread) that could potentially also break parsing/rendering in other windows/tabs.

Hence my gut feeling it that the problems, and possible performance issues, outweigh any potential gains from using Service/Shared Workers unfortunately.

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX, for the reasons outlined in https://github.com/mozilla/pdf.js/issues/14467#issuecomment-1015586419.
