### ISSUE TITLE
Facing issues in Rendering of PDF document with errors in pdf.js in browser console

### ISSUE THREAD

**Issue by SAJalal** [mozilla/pdf.js#14478]
Hey,

We have used the pdf.js library for rendering our documents in our instance - but we have been facing issues while doing so - While viewing one of our documents - we have seen that some of the characters are missing - Attached are the screenshots

Also, we are getting errors in the console related to the pdf.js
<img width="622" alt="Screenshot 2022-01-21 at 13 47 08" src="https://user-images.githubusercontent.com/98151269/150493191-66551c96-6de7-4822-9c54-50bdf1e7783a.png">
<img width="660" alt="Screenshot 2022-01-21 at 13 47 22" src="https://user-images.githubusercontent.com/98151269/150493196-42dd3d15-c1e3-4895-a6ba-f93665d0e6f1.png">
![error](https://user-images.githubusercontent.com/98151269/150493257-7d495163-3f9d-43dd-a5cc-fd449c74325d.png)

Can someone please look into it?

Many thanks

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information.

> Can someone please look into it?

Unfortunately, no meaningful debugging can be done with nothing but screen-shots; please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Also, we are getting errors in the console related to the pdf.js

That's not the part that I find interesting, but rather the line containing `(PDF.js: 1.5.188)`. 
That version is (obviously) no longer supported, given that it's close to six years old, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
