### ISSUE TITLE
Creating a pdf through MacOS by using a collection of images can lead into the images being rendered as black boxes in pdf.js

### ISSUE THREAD

**Issue by richardba** [mozilla/pdf.js#14494]
Attach (recommended) or Link to PDF file here:

[test conglomerate 6 2.pdf](https://github.com/mozilla/pdf.js/files/7934925/test.conglomerate.6.2.pdf)

Configuration:
- Web browser and its version: Safari 15.2
- Operating system and its version: MacOS
- PDF.js version: 2.12.213
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a pdf in MacOS by using several pictures through find and generating the pdf through the Image Viewer ([as shown in this link](https://www.macrumors.com/how-to/convert-images-to-pdf-macos-preview/))
2. Open the generated pdf in pdf.js and progressively browse through the file while zooming in and out
3. Sometimes images from the pdf will render as entire black boxes

What is the expected behavior? (add screenshot)

The images should be rendered with no issue or whatsoever

![image](https://user-images.githubusercontent.com/3475068/151008670-d745c696-d4fb-42ba-a503-a254f8eecce2.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/3475068/151009049-4d249e4c-f36a-4a3f-9703-7ec493097666.png)

I hope you could assist me on this issue

Thank you in advance!

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.13.77` in both Firefox Nightly 98 and Google Chrome Beta 98.
Hence this unfortunately looks like a *browser*, or possible OS/driver, bug rather than a PDF.js library one.

> Web browser and its version: Safari 5.17

According to https://en.wikipedia.org/wiki/Safari_version_history#Safari_5 that version number doesn't seem to exist, and in any case it'd be a *very old* and outdated browser Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 2.12

Sorry, but that's not a *complete* version number; which PDF.js version are you actually using?

**Comment by richardba** [comment]
Hey I have edited with the pertinent info required

**Comment by Snuffleupagus** [comment]
Unfortunately, given that it's specific to just *one* browser it doesn't seem like a bug in the PDF.js library but rather e.g. a `canvas`-related bug the browser *itself*. Please note that Firefox is the primary development target for this library.
