### ISSUE TITLE
Chrome extension doesn't work when setup as "on click" website access

### ISSUE THREAD

**Issue by fcastilloec** [mozilla/pdf.js#14498]
**Attach (recommended) or Link to PDF file here:**
Any pdf file online (i.e. https://www.americanexpress.com/content/dam/amex/us/staticassets/pdf/GCO/Test_PDF.pdf)

**Configuration**:
- Web browser and its version: Chrome 97.0.4692.99
- Operating system and its version: Ubuntu 20.04
- PDF.js version: 2.3.164
- Is a browser extension: yes

**Steps to reproduce the problem:**
1. Set the extension to work "on click" under "Allow this extension to read and change all your data on websites you visit"
2. Load any pdf on your browser, it'll load using the default pdf
3. Click on the pdf.js extension, I'll ask to reload, click on that too.
4. pdf.js loads but shows an error that it's unable to fetch the pdf.

**What is the expected behavior? (add screenshot)**
The pdf should be able to load
![Microsoft Word - Document1 - Test_PDF pdf - Google Chrome_001](https://user-images.githubusercontent.com/1280530/151081893-e414bd18-eacb-4fd9-8535-aa07cbc3621f.png)

**What went wrong? (add screenshot)**
The pdf couldn't be fetched.
![Test_PDF pdf - Google Chrome_002](https://user-images.githubusercontent.com/1280530/151081945-b60feca3-7e35-46ce-a628-67ff769d96bd.png)

**Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):**
I'm not sure what this means, but since I'm using the ["official" Chrome extension](https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=en), I'm guessing this is not needed. Do let me know if I'm missing something and I'd gladly help out.

**Comment by Poopooracoocoo** [comment]
Might want to use the more updated https://github.com/Emano-Waldeck/pdf-reader btw

**Comment by Rob--W** [comment]
This is not a bug in the PDF viewer.

The "on click" website access only grants temporary access to a resource. You shouldn't change it from all websites to on click.

What happens is this:
1. When the page is reload after clicking the button, Chrome grants access to the extension.
2. The extension redirects the page to the viewer.
3. Chrome revokes the granted permission since the page has unloaded.
4. PDF.js tries to fetch the PDF data, but fails due to step 3.

It is not really possible to work around this, because PDF.js may need more than one request to fetch the data, (a work-around such as loading the PDF before redirecting would therefore not work)
