### ISSUE TITLE
Failed to fetch

### ISSUE THREAD

**Issue by wmo123** [mozilla/pdf.js#14492]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 97.0.4692.99（正式版本）
- Operating system and its version: macOs 10.14.6
- PDF.js version:2.13.14
- Is a browser extension:no

Steps to reproduce the problem:
1. git clone pdf.js,edit the DEFAULT_URL = 'https://obs-dc-core1-pubread.obs.cn-north-4.myhuaweicloud.com:443/smartReportDocumentUpdate_2604078409535744.pdf';
2. open 'http://localhost:8888/web/viewer.html' in browser, then， it note that 'Failed to fetch'

What is the expected behavior? (add screenshot)
preview pdf normally
What went wrong? (add s
![image](https://user-images.githubusercontent.com/47963460/150893901-87207ce4-256e-49a5-8865-9391a0cf1066.png)
creenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.13.14

That's neither an official release, see https://mozilla.github.io/pdf.js/getting_started/#download, or the latest `master` version.

> [...] it note that 'Failed to fetch'

That's a *browser* error, rather than one originating in the PDF.js library; see also https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr which may be relevant here.

Unfortunately this doesn't look like something that can be fixed here; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
