### ISSUE TITLE
Get some unnecessary chunks with range request and make first page slow

### ISSUE THREAD

**Issue by ethan-zhs** [mozilla/pdf.js#14503]
Configuration:
- Web browser and its version:  Chrome 97.0.4692.99
- Operating system and its version:   MacOS 10.15.5
- PDF.js version:   2.12.313
- Is a browser extension:  no

1. I use the range request to render pdf
2. I get more chunks with this line of code `await this.pdfManager.requestRange(ex.begin, ex.end);`;
3. These chunks are unnecessary when rendering first page, the version 2.3.200 is normal;
4. The program also seems to run fine when I comment this line of code, and I can get less chunks to make the first page faster;
5. So what does this part of the code do? 
6. Is it possible not to execute it or not to use await?

```
// src/core/xref.js

async fetchAsync(ref, suppressEncryption) {
    try {
      return this.fetch(ref, suppressEncryption);
    } catch (ex) {
      if (!(ex instanceof MissingDataException)) {
        throw ex;
      }
      await this.pdfManager.requestRange(ex.begin, ex.end);
      return this.fetchAsync(ref, suppressEncryption);
    }
  }
```

I can get less chunks when I comment this line of code and the program also seems to run fine

![image](https://user-images.githubusercontent.com/20236999/151293851-0f08be28-3545-4630-8591-dc2423e4376d.png)

If I do nothing，the range request in network like this

![image](https://user-images.githubusercontent.com/20236999/151294255-c5112fa1-3b41-47cf-9206-89058a2fd3cd.png)

**Comment by daddybh** [comment]
wired

**Comment by Snuffleupagus** [comment]
*Given the lack of a runnable example, the following information will be **general** in nature.*

> I get more chunks with this line of code `await this.pdfManager.requestRange(ex.begin, ex.end);`

That line is necessary in order to *guarantee* that a particular part of the document is fully available, since otherwise parsing simply cannot work correctly in the general case.
However, we do have various fast-paths and caches (on both threads) to avoid dispatching duplicate/unnecessary range requests. Although it's probably good to remember that we primarily try to optimize the streaming-case, i.e. `disableStream = false`, since that's being used in the *built-in* Firefox PDF Viewer,

> These chunks are unnecessary when rendering first page, the version 2.3.200 is normal
> The program also seems to run fine when I comment this line of code, and I can get less chunks to make the first page faster

Given that there's no example provided, and generally not enough information about your *exact* configuration, it's very difficult to tell exactly what combination of the following `getDocument` options you're actually using here:
https://github.com/mozilla/pdf.js/blob/a69adf03825a42b69a9dcf67abe0ae3d59b21d39/src/display/api.js#L203-L215

Also, please note that version `2.3.200` is a few years old and a lot of changes/improvements have been made since then.
However, note that *in general* we should not be dispatching "unnecessary" range requests and it should hopefully be obvious why it'd (again) *not* be generally appropriate to just ignore that line. Just because it might *seem* to work in one particular case, doesn't mean it wouldn't break arbitrary documents really badly.

> So what does this part of the code do?
> Is it possible not to execute it or not to use await?

It ensures that the necessary part of document is available for parsing, and it (obviously) cannot be removed since that'd break so many things and would also introduce lots of *intermittent* failures.

---

Unfortunately this issue isn't particularly easy to follow as-is, and please keep in that changes to this part of the code-base could *very easily* break things quite badly. Finally, as-is this isn't really actionable; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
