### ISSUE TITLE
Maximum size of PDF that can be opened in pdf.js viewer

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#14501]
Attach (recommended) or Link to PDF file here:

When trying to open large PDF(309 MB) , pdf.js just shows a spinner and finally get a Aw snap error. I already created a ticket for this and got it closed that pdf.js does not support such large PDF. On that note, Can you please tell if there is any maximum size which PDF.js supports so that we can conclude beyond that sizing,  we do not support/create. 
Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I already created a ticket for this and got it closed that pdf.js does not support such large PDF.

Your issue(s) were closed since they unfortunately were missing *crucial* information required in order to be actionable.

> Can you please tell if there is any maximum size which PDF.js supports so that we can conclude beyond that sizing, we do not support/create.

Unfortunately it's simply impossible to answer such a question in general, since it (obviously) depends on a number of factors; among those are:
 - Overall computer performance, w.r.t. both CPU performance and the available RAM.
 - The file-size of the PDF document.
 - The number of pages in the PDF document.
 - The (internal) structure of the PDF document itself, since e.g. some streams are "expensive" to decompress.

**Comment by mirnalinikarthik** [comment]
@Snuffleupagus Thank you so much for your answer. This is what we wanted to know.
