### ISSUE TITLE
Make response headers case insensitive

### ISSUE THREAD

**Issue by angel-langdon** [mozilla/pdf.js#14514]
Configuration:
- PDF.js version: v2.12.313 (latest)

Steps to reproduce the problem:
1. Try doing `Range-Requests` with lower-case headers won't work

What is the expected behaviour? (add screenshot)
- To work properly with lower-case headers

What went wrong? (add screenshot)
- Using case-insensitive headers such as `accept-ranges` does not work as expected.

I am currently using `Starlette` (Python library)  to send the PDF using Range requests but PDF.js does not correctly detect when the headers are lower-cased. If the headers are case-sensitive using PascalCase everything works as expected  (https://github.com/encode/starlette/issues/1454)

### Headers should be case insensitive
According to **RFC 7230** (HTTP/1.1):

> Each header field consists of a case-insensitive field name
> followed by a colon (":"), optional leading whitespace, the field
> value, and optional trailing whitespace.

https://www.rfc-editor.org/rfc/rfc7230#section-3.2

Also, **RFC 7540** (HTTP/2):

> Just as in HTTP/1.x, header field names are strings of ASCII   
> characters that are compared in a case-insensitive fashion.

https://www.rfc-editor.org/rfc/rfc7540#section-8.1.2

**Comment by Snuffleupagus** [comment]
> Using case-insensitive headers such as `accept-ranges` does not work as expected.

That should *already* work, given that we're using the https://developer.mozilla.org/en-US/docs/Web/API/Headers/get and https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/getResponseHeader methods which are both documented as being case-insensitive.
In my quick testing, using both Mozilla Firefox and Google Chrome, those methods are indeed case-insensitive; however you've not said anything what browser(s) you're using.

> I am currently using `Starlette` (Python library) to send the PDF using Range requests but PDF.js does not correctly detect when the headers are lower-cased.

Unfortunately we don't know anything about that library here, and generally we also cannot really provide help with Python code either (since this is a JavaScript library).

---

As-is this unfortunately doesn't really seem actionable; please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by angel-langdon** [comment]
@Snuffleupagus Thank you for your fast response.

After what you said I tried to find what was causing this to fail and it was because of the development default CORS configuration. It was overriding my `Access-Control-Expose-Headers` and this was causing to fail everything. Thank you very much!
