### ISSUE TITLE
PDF.js displays all text in bold when using safari browser

### ISSUE THREAD

**Issue by MantautasG** [mozilla/pdf.js#14511]
Attach (recommended) or Link to PDF file here: 
[test.pdf](https://github.com/mozilla/pdf.js/files/7957652/test.pdf)

Configuration:
- Web browser and its version: Safari 15.2
- Operating system and its version: MacOS Catalina 10.15.7
- PDF.js version: v2.12.313
- Is a browser extension: No

Steps to reproduce the problem:
1.  Hello, I simply added base64 document string to current pdf.js implementation on my project. And as it is showed in screenshots below you can see that google chrome shows the document correctly(expected behavior), when safari browser "like" bolds all the text in the pdf document(wrong behavior). 

What is the expected behavior? 
![image](https://user-images.githubusercontent.com/28557416/151527383-865e5522-f649-4545-8c86-f1152e14dfbd.png)

What went wrong? 
![image](https://user-images.githubusercontent.com/28557416/151526509-9ebeaaca-5f92-40ec-879c-00ff3e2ac8c4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `2.13.93` in both Firefox Nightly 98 and Google Chrome Beta 98.

This unfortunately looks like a bug in the browser *itself* (e.g. `canvas` or Font Loading API related), or possibly even a OS/driver bug, rather than a problem in PDF.js library since then you'd really expect it to be consistently broken everywhere.
Hence closing this issue, since it doesn't seem like something that we can fix here unfortunately.
