### ISSUE TITLE
[Toggle Sidebar]: On resizing the screen to 300%, Content is overlapping with 'Sidebar'.

### ISSUE THREAD

**Issue by seahawksq** [mozilla/pdf.js#14523]
When setting browser's zoom to 300%, the content is overlapping with sidebar (also no scroll bar available to adjust content)
![image](https://user-images.githubusercontent.com/25859586/152259489-a000f1c3-5119-4b89-bcc7-cec4958af596.png)

Configuration:
- Web browser and its version: Chrome Version 97.0.4692.71 (Official Build) (64-bit) /Edge Version 97.0.1072.69 (Official build) (64-bit)
- Operating system and its version: 21H2(OS build 22000.376)
- PDF.js version: 2.13.107
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. Toggle Sidebar on
3. Set browser's zoom settings to 300%

What is the expected behavior? (add screenshot)
The content should not overlap with sidebar.

**Comment by Snuffleupagus** [comment]
> When setting browser's zoom to 300%,

That's not really something that the viewer intends to support; note how the Firefox *built-in* PDF Viewer (i.e. the main reason for this library existing) even disables zooming of the viewer UI itself.
Hence, when the viewer becomes narrow the sidebar will simply overlay the document itself as implemented in https://github.com/mozilla/pdf.js/blob/48c8831a79b764c73eca1a1b8d4596d367f3e4ca/web/viewer.css#L1885-L1905

All-in-all, closing as INVALID since this works as expected.
