### ISSUE TITLE
[Keyboard Navigation - Zoom Combo box]: The value gets selected/applied while discarding the value by Esc key

### ISSUE THREAD

**Issue by seahawksq** [mozilla/pdf.js#14524]
While moving within the combo box items using arrow keys, the value which is highlighted gets selected when pressing "Esc". User did not perform any action to select the item, but still the item gets selected as the value of the combo box.

Configuration:
- Web browser and its version: Chrome Version 97.0.4692.71 (Official Build) (64-bit) /Edge Version 97.0.1072.69 (Official build) (64-bit)
- Operating system and its version: 21H2(OS build 22000.376)
- PDF.js version: 2.13.107
- Is a browser extension: No

Steps to reproduce the problem:
1. Navigate to https://mozilla.github.io/pdf.js/web/viewer.html
2. Open Zoom Combo box and use arrow key to navigate to an option
3. Use Esc key to close the Combo box.

What is the expected behavior? (add screenshot)
The selection/value is discarded and not applied.

**Comment by Snuffleupagus** [comment]
> Operating system and its version: 21H2(OS build 22000.376)

The actual *name* of the OS appears to be missing here, since you've only included what looks like a version number.

> Open Zoom Combo box and use arrow key to navigate to an option
> Use Esc key to close the Combo box.

The `change` event on a `<select>` element fires when the element loses focus, hence this is somewhat expected unfortunately.
Furthermore, in the case when you've opened a `<select>` element with the mouse but then use the arrow-keys to navigate through the `<option>`s there doesn't appear to be any `keydown`/`keyup` events dispatched. Hence it unfortunately doesn't seem *generally* possible to detect this particular case (in any simple way), which as far as I can tell is basically a shortcoming of the web-platform itself rather than the PDF.js default viewer.

All-in-all, given that this is an edge-case and that the web-platform doesn't seem to provide the necessary events to handle this particular situation, closing as WONTFIX (or even can't fix really).

**Comment by calixteman** [comment]
@Snuffleupagus, I didn't try anything maybe we could try something with `:focus-visible`, wdyt ?

**Comment by Snuffleupagus** [comment]
> I didn't try anything maybe we could try something with `:focus-visible`, wdyt ?

Sorry, but I really understand how that'd help since the problem ought to be how the *JavaScript* is able to detect this case!?

**Comment by calixteman** [comment]
I thought it'd be possible to change for example the visibility of a transparent div on `:focus-visible :not(:focus)` and then add a js `focus` listener and check the visibility of the div to the in which case we are.
But as said I didn't try anything, it's just an idea.

**Comment by Snuffleupagus** [comment]
> thought it'd be possible to change for example the visibility of a transparent div on `:focus-visible :not(:focus)` and then add a js `focus` listener and check the visibility of the div to the in which case we are.

While I cannot (still) really imagine what sort of work-around you have in mind here, what you describe nonetheless sounds like something that'd potentially complicate this code quite a bit, thus hurting both readability and maintainability, in order to try and work-around what to me seems like a web-platform limitation[1] affecting an *edge-case* in the PDF.js viewer.

---
[1] The issue being that the `change` event always fires when the `<select>` element loses focus.
