### ISSUE TITLE
getGlobalEventBus is deprecated, use a manually created EventBus instance instead.

### ISSUE THREAD

**Issue by yewanji** [mozilla/pdf.js#14541]
i use pdfjs to render my pdf document 
  PDFJS.getDocument({
          url: pdfUrl,
          cMapUrl: '../../../static/pdfjs-dist/cmaps/',
          cMapPacked: true,
        })

 warning  getGlobalEventBus is deprecated, use a manually created EventBus instance instead.
what should i do?

**Comment by Snuffleupagus** [comment]
> warning getGlobalEventBus is deprecated, use a manually created EventBus instance instead.

That suggests that you're using a *very old*, and thus completely unsupported, version of the PDF.js library.
Furthermore there's no mention of using the default viewer in your code-snippet, since that warning originate in the viewer rather than the PDF.js library API; unfortunately though you've (again) not included anywhere near enough information in order for this issue to be actionable/valid.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
