### ISSUE TITLE
I need a Noto Sans S Chinese Bold.bcmap

### ISSUE THREAD

**Issue by fanjizhou** [mozilla/pdf.js#14546]
Attach (recommended) or Link to PDF file here:
Configuration:
Web browser and its version: chrome Version 92.0.4515.131
Operating system and its version: Windows 10
PDF.js version: 2.9.359
Is a browser extension: no

Steps to reproduce the problem:
1. 2.
![image](https://user-images.githubusercontent.com/99230042/152912366-e8db157a-e7d1-46a9-ab49-df4301330e01.png)

**Comment by Snuffleupagus** [comment]
> I need a Noto Sans S Chinese Bold.bcmap

No such thing exists, since CMaps are *not* font-specific; please also note https://github.com/adobe-type-tools/cmap-resources

> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> PDF.js version: 2.9.359

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

Closing as INCOMPLETE, since there's unfortunately too much information missing in order for this to be actionable/valid.
