### ISSUE TITLE
`10px` font size on `html` element in `viewer.css` makes for challenging styling

### ISSUE THREAD

**Issue by lyzadanger** [mozilla/pdf.js#14555]
Configuration:
- Web browser and its version: N/A (Affects any browser)
- Operating system and its version: N/A
- PDF.js version: 2.11.213
- Is a browser extension: No

Steps to reproduce the problem:
1. Add DOM content to a PDF.js viewer HTML document inside of a shadow DOM
2. Attempt to use CSS styling in the shadow-DOM'ed component that works in `rem` units

What is the expected behavior? (add screenshot)

Base `html` font size is `100%` (per web conventions)

What went wrong? (add screenshot)

Base REM sizing, set via `html` element rules, is `10px`, which is un-representative of actual document text sizing and makes styling in a shadow DOM challenging.

There is a CSS rule on the `html` element in `viewer.css` added in this [commit from 2013](https://github.com/mozilla/pdf.js/commit/c79acf5861b87295cd44ef149310a13bcb250ced) that sets the base font size to `10px`. However, the `body` element immediately sets font size to `16px`. The associated comment is that this `10px` size is necessary to "make the activity bar the correct size." Firstly, is this still needed? Forgive me: I cannot seem to find any reference to what the activity bar _is_: I tried a bit of googling and grepping to no avail.

The problem this poses is that root REM sizing can only be set on `:root` or, equivalently, the `html` element. I'm working on styling inside of a shadow DOM: shadow DOMs have access to a `:host` pseudo-element but do not have an `html` or `:root` selector available to them, so I cannot "reset" REM sizing (in any way that I am aware of, anyhow) inside the shadow DOM.

I recognize that some of the problem here is the way that shadow DOMs work, and I have an inelegant simple workaround—we maintain an override stylesheet in which I can simply override the `html` element's `font-size`. However, I thought I'd bring this to your attention in case that `10px` size is not actually needed: this could help a future dev.

It would also be valid to say, nope, we really do mean `10px`.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.11.213

Please note that that's *not* an official release, and consequently we cannot really provide support for it; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> However, the `body` element immediately sets font size to `16px`.

Where does that happen, since it's not being set in the following code (and the only `16px` occurrences in `viewer.css` seem completely unrelated to the `font-size`)?
https://github.com/mozilla/pdf.js/blob/f8b2a99ddc2eeb1aefda0fff2c8d5aadf31dfe8a/web/viewer.css#L185-L198

> The associated comment is that this `10px` size is necessary to "make the activity bar the correct size."

PR #3794 was related to the B2G, i.e. Boot to Gecko or Firefox OS (a project since abandoned), version of the PDF Viewer and there's also https://github.com/mozilla/pdf.js/pull/3794#discussion_r6983639 which suggests this was intended to be temporary.

> Firstly, is this still needed?

Probably not, but considering that this CSS rule has existed for over *eight years* there's consequently a small risk that something else in the viewer has implicitly started relying on that rule. Hence this will require careful *manual* testing, such that we don't needlessly break the Firefox PDF Viewer by removing this line.

**Comment by lyzadanger** [comment]
@Snuffleupagus Hiya!

> Where does that happen, since it's not being set in the following code (and the only 16px occurrences in viewer.css seem completely unrelated to the font-size)?

OK, my statement about 16px was inadvertently misleading (or more bluntly, inaccurate). This line:

https://github.com/mozilla/pdf.js/blob/f8b2a99ddc2eeb1aefda0fff2c8d5aadf31dfe8a/web/viewer.css#L195

applies the `message-box` system font — MDN briefly mentions it in its [`font` documentation](https://developer.mozilla.org/en-US/docs/Web/CSS/font) — which has different sizing results in my different local browsers. 

In Chrome (Version 97.0.4692.99 (Official Build) (arm64)), this results in a `16px` font size on the `body` element:

![image](https://user-images.githubusercontent.com/439947/153643716-c9d47b57-a023-4686-9254-3f2714f6aa9e.png)

In Safari (Version 15.2 (17612.3.6.1.6)), we get `13px`:

![image](https://user-images.githubusercontent.com/439947/153643823-a40b42ec-70fd-4a43-b71a-85ba67034155.png)

Presumably this reflects browser defaults related to the `message-box` system font, which I have zero previous experience with.

All of this ends up being moot because the various elements and components on the page set their own local `font-size`s.

The salient point is that nothing that I can see (immediately, at least) actually makes any use of that `10px` base font size. Disregard my specific `16px` citation as it is misleading!
