### ISSUE TITLE
[BUG] Font render is incorrect

### ISSUE THREAD

**Issue by thanhchuongbmd** [mozilla/pdf.js#14571]
Attach (recommended) or Link to PDF file here: https://214portal.bmdapp.store:4214/book/e40047ed2c20f7b52db8447936cbbfdc.pdf

Configuration:
- Web browser and its version: web view on android
- Operating system and its version: Android 8.1.0
- PDF.js version: 2.4.7
- Is a browser extension: No

What is the expected behavior? (add screenshot)
- Font using in pdf file: UTF-8 (Vietnamese)
- When I show on chrome browser then it's work ok, but show in web view android (react native) then font render not correct

What went wrong? (add screenshot)
![image_2022-02-16_16-26-02](https://user-images.githubusercontent.com/67777599/154234820-001ff36d-060e-4fce-82d7-9e66be8901ea.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): https://214pdf.bmdapp.store/?bookId=1&bookChapterId=2&token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwidHlwZSI6IkFETUlOIiwiaWEiOjE2NDUwMDM4NDcsImlhdCI6MTY0NTAwMzg0NywiZXhwIjoxNjc2MTA3ODQ3fQ.66IP4TcZz4vexijX0ekF705L8_J2zfa_8eyPYTh_j2s

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: https://214portal.bmdapp.store:4214/book/e40047ed2c20f7b52db8447936cbbfdc.pdf

WFM (with the caveat that I don't speak Vietnamese), using PDF.js version `2.13.133` in Firefox Nightly 99 (on Windows).

> * Web browser and its version: web view on android
> * Operating system and its version: Android 8.1.0

Unfortunately WebView isn't the primary development target, and furthermore that Android version is way too old to be supported since [according to Wikipedia](https://en.wikipedia.org/wiki/Android_version_history#Android_8.1_Oreo) it was released in 2017.

> PDF.js version: 2.4.7

Please note that that's not an official PDF.js release, as found on https://github.com/mozilla/pdf.js/releases, and furthermore such a version is too old to be supported now; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> When I show on chrome browser then it's work ok, but show in web view android (react native) then font render not correct

This unfortunately suggests a platform and/or browser bug, rather than a PDF.js one, and as such this unfortunately isn't valid or fixable here.

**Comment by thanhchuongbmd** [comment]
> > Attach (recommended) or Link to PDF file here: https://214portal.bmdapp.store:4214/book/e40047ed2c20f7b52db8447936cbbfdc.pdf
> 
> WFM (with the caveat that I don't speak Vietnamese), using PDF.js version `2.13.133` in Firefox Nightly 99 (on Windows).
> 
> > * Web browser and its version: web view on android
> > * Operating system and its version: Android 8.1.0
> 
> Unfortunately WebView isn't the primary development target, and furthermore that Android version is way too old to be supported since [according to Wikipedia](https://en.wikipedia.org/wiki/Android_version_history#Android_8.1_Oreo) it was released in 2017.
> 
> > PDF.js version: 2.4.7
> 
> Please note that that's not an official PDF.js release, as found on https://github.com/mozilla/pdf.js/releases, and furthermore such a version is too old to be supported now; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
> 
> > When I show on chrome browser then it's work ok, but show in web view android (react native) then font render not correct
> 
> This unfortunately suggests a platform and/or browser bug, rather than a PDF.js one, and as such this unfortunately isn't valid or fixable here.

Sorry, i missing version pdf, i updated version pdf to 2.12.313! But it still render missing unicode character!

**Comment by darrynten** [comment]
The &#272; (Đ) character does not render for me no matter what I try
