### ISSUE TITLE
[Help] How to compute the coordinate of a specific letter in one the pdf textContent?

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#14582]
I dont't use the textLayerBuilder to create the textlayer. Instead, i use a canvas. And I know the coordinate in the viewport  and i compute the textContent where the cooridinate is inside the textContent's offset. And i also know the cooridinate.left and the textContent.left. But how can i get the correct first letter index based on the cooridinate.left? I need it to draw rect on the canvas to select text.

**Comment by Snuffleupagus** [comment]
Sorry, but this is missing too much information/context in order to be actionable (please also keep in mind that this is first and foremost a *bug tracker*).

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and for these sort of questions please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
