### ISSUE TITLE
Is there any way to judge whether the file has permission password(or owner password)?

### ISSUE THREAD

**Issue by zhoujiachang** [mozilla/pdf.js#14590]
Is there any way to judge whether the file has permission password(or owner password)?

**Comment by Snuffleupagus** [comment]
PDF documents with passwords will throw a `PasswordException` opened, unless a password was provided when calling `getDocument`.
If your question is how to tell different kinds of passwords apart, i.e. owner/user passwords, then we don't have a way to do so since this isn't a use-case that matters for e.g. the default viewer. If that's not it then you'll have to provide a more detailed and clearer question (with more context), since as-is it's unfortunately quite difficult to understand *exactly* what you're actually asking about!

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes actionable/valid.

**Comment by zhoujiachang** [comment]
`it("should correctly check an owner key", function () {
      var password, ownerValidation, ownerPassword, alg, result, uBytes;
      alg = new PDF20();
      password = new Uint8Array([111, 119, 110, 101, 114]);
      ownerValidation = new Uint8Array([142, 232, 169, 208, 202, 214, 5, 185]);
      // prettier-ignore
      ownerPassword = new Uint8Array([88, 232, 62, 54, 245, 26, 245, 209, 137,
                                      123, 221, 72, 199, 49, 37, 217, 31, 74,
                                      115, 167, 127, 158, 176, 77, 45, 163, 87,
                                      47, 39, 90, 217, 141]);
      // prettier-ignore
      uBytes = new Uint8Array([94, 230, 205, 75, 166, 99, 250, 76, 219, 128,
                               17, 85, 57, 17, 33, 164, 150, 46, 103, 176, 160,
                               156, 187, 233, 166, 223, 163, 253, 147, 235, 95,
                               184, 83, 245, 146, 101, 198, 247, 34, 198, 191,
                               11, 16, 94, 237, 216, 20, 175]);
      result = alg.checkOwnerPassword(
        password,
        ownerValidation,
        uBytes,
        ownerPassword
      );
      expect(result).toEqual(true);
    });`
yes, i just want to if the file has a owner password. I found a function in pdf.js/test/unit/crypto_spec.js, what does the function of **checkOwnerPassword** mean? Can use it to check whether the file has a owner password?
