### ISSUE TITLE
Search results on Android Webview not displayed correctly

### ISSUE THREAD

**Issue by maximiliannocker** [mozilla/pdf.js#14604]
When the pdf is loaded inside an Android Webview then the search results are not highlighted above the text instead they are shifted to the right. On a normal Android Chrome browser it works correctly.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.

> On a normal Android Chrome browser it works correctly.

Given that it apparently works in *some* browsers/environments, this unfortunately suggests a bug in "Android Webview" rather than in the PDF.js library itself.

Please also that "Android Webview" is not an officially supported configuration, refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
It's also not really clear, given the limited information above, but I'm assuming that you're using the default viewer (since the library itself doesn't implement searching); hence please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Finally, given that "Android Webview" isn't an officially supported configuration it's also quite difficult to know how to even go about reproduce this; hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
