### ISSUE TITLE
Garbled characters appear when PDFjs is rendered in SVG

### ISSUE THREAD

**Issue by yewanji** [mozilla/pdf.js#14619]
pdfjs version pdfjs-dist@2.4.456
 problem    Garbled when I tried to take charge of the content
screenshot 
![image](https://user-images.githubusercontent.com/42515433/156133331-ffa35686-2ab2-4884-b03f-88508fca1e54.png)

demo code
  PDFJS.getDocument({
          url: pdfUrl,
          cMapUrl: './static/pdfjs-dist/cmaps/',
          cMapPacked: true,
        }).promise.then(pdfDocument=>{
          pdfDocument.getPage(1).then((page) => {
            let viewport = this.getHopeViewport(page)
            let pageDiv = document.querySelector(`#page-${this.pdfPageNum}`)
            page.getOperatorList()
              .then(function (opList) {
                var svgGfx = new PDFJS.SVGGraphics(page.commonObjs, page.objs);
                return svgGfx.getSVG(opList, viewport);
              })
              .then(function (svg) {
                pageDiv.appendChild(svg);
              });
          })
        }).catch(e=>{
          this.$message.error('加载PDF异常')
        })

attachment
[jsr303自定义注解总结.pdf](https://github.com/mozilla/pdf.js/files/8160033/jsr303.pdf)

**Comment by Snuffleupagus** [comment]
> Garbled characters appear when PDFjs is rendered in SVG

Note that as mentioned in the FAQ, the SVG back-end is not officially supported; see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#backends

> pdfjs version pdfjs-dist@2.4.456

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Garbled when I tried to take charge of the content

As far as I can tell, the rendering looks fine when comparing against the default `canvas` back-end.

It's slightly difficult to tell, given the (somewhat limited) information provided, but please keep in mind that all fonts are being mapped to a PUA (Private Use Area) in order to get around various limitations in browsers. Hence it's not expected that the SVG-rendering will contain the glyphs in their original locations, and in order to support e.g. text-selection you'll thus need to use a separate textLayer in the same way as in the default viewer (also, rendering and text-extraction uses separate algorithms in the PDF specification).

> demo code
> [...]

Also, please keep in mind https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by yewanji** [comment]
> 
I tried canvas rendering, but it would be blurry at a small resolution, and zooming in on the viewport would result in incomplete content
