### ISSUE TITLE
How to read HTTP response headers?

### ISSUE THREAD

**Issue by make-github-pseudonymous-again** [mozilla/pdf.js#14630]
What's the proper way to combine reading a PDF with HTTP URL source via `getDocument` and reading `last-modified` headers for instance without firing an additional request?

**Comment by Snuffleupagus** [comment]
Sorry, but it's unfortunately quite difficult to understand *exactly* what you're asking about here.
Please note that the PDF.js library has no functionality to read arbitrary HTTP headers, since that's not really relevant to its intended use-case (which is parsing and rendering PDF documents).

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by make-github-pseudonymous-again** [comment]
Here is a concrete example: use pdf.js to render page thumbnails, cache the page thumbnails on the client, until the PDF changes. Do I need to do a separate HTTP HEAD request to check that the PDF has changed (for instance with 'last-modified' response header) or is there a way to retrieve this information from the return value of `getDocument`?

**Comment by Snuffleupagus** [comment]
As alluded to above, the PDF.js API does *not* expose any way to access HTTP headers.

**Comment by make-github-pseudonymous-again** [comment]
OK! That answers my question. I will have to work around it somehow.

**Comment by Snuffleupagus** [comment]
One thing that might help is the PDF document ID, since that *should* be unique to each PDF document.[1]
That data can be accessed on the `PDFDocumentProxy`-instance that's available from the `getDocument`-call; please see https://github.com/mozilla/pdf.js/blob/234aa9a50e33599c28877ac3b5fff3542c55cd61/src/display/api.js#L731-L739

---
[1] Correctly implemented PDF creation software should be be generating a unique ID.
