### ISSUE TITLE
A question about scale

### ISSUE THREAD

**Issue by sershine** [mozilla/pdf.js#14632]
En
when I use viewer.js+viewer.html and operate zoomIn or zoomOut ,  It's very fast  ( PDF file size:15M, a pic inside ,only one pic)
when I build project with VUE and pdfjs-dist,  code zoomIn and zoomOut by self.  It's very slow.(PDF file is same )
I want to know why and how to fix it .What did viewer.js do to make it so fast

Cn
当我用viewer.js和viewer.html操作PDF放大或缩小时，速度非常快，测试的PDF大小是15M，里面只有一张图
当我用VUE+pdfjs-dist创建项目，自己实现放大缩小，速度非常慢，测试的PDF同上

Code/代码
async renderPage() {
      this.pagePosition.length = 0
      for (let i = 1; i <= this.totalPage; i++) {
        if (this.pages.length < this.totalPage) {
          let page = await this.pdfDoc.getPage(i)
          this.pages.push(page)
        }

        const viewport = this.pages[i - 1].getViewport({
          scale: this.lockScale * this.customScale
        })

        const canvas = document.getElementById('the-canvas' + i)
        const context = canvas.getContext('2d')

        canvas.height = viewport.height
        canvas.width = viewport.width
        const renderTask = this.pages[i - 1].render({
          canvasContext: context,
          viewport: viewport
        })
        await renderTask.promise
        this.pagePosition.push(canvas.offsetTop - 40)
      }
    },

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is unfortunately not actionable/valid.

> when I build project with VUE and pdfjs-dist, code zoomIn and zoomOut by self. It's very slow.(PDF file is same )

Sorry, but we really can't provide support for various frameworks (e.g. Vue in this case), since we know nothing about them here.

> Cn
> 当我用viewer.js和viewer.html操作PDF放大或缩小时，速度非常快，测试的PDF大小是15M，里面只有一张图
> 当我用VUE+pdfjs-dist创建项目，自己实现放大缩小，速度非常慢，测试的PDF同上

Please note that you need to communicate *only in English* when using this bug tracker.

> Code/代码
> [...]

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
