### ISSUE TITLE
v2.13.216 does not works with chrome 49 on windows xp

### ISSUE THREAD

**Issue by lygstate** [mozilla/pdf.js#14644]
Configuration:
- Web browser and its version:
Chrome 49
- Operating system and its version:
Windows XP SP3
- PDF.js version:
v2.13.216
- Is a browser extension:

Steps to reproduce the problem:
1. Open [web.xml](http://192.168.199.21:8080/web/viewer.html)

**Comment by Snuffleupagus** [comment]
> Web browser and its version:
> Chrome 49

As outlined in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, that browser version is too old to be supported by the PDF.js project.
Furthermore, note that it's *never* a good idea to use a browser that's over five years old since it may contain any number of known security bugs.

**Comment by timvandermeij** [comment]
In addition to the above you should _urgently_ move away from Windows XP and upgrade to the most recent Windows version since support for Windows XP ended in 2014 already and it's known to contain lots of unpatched security vulnerabilities.
