### ISSUE TITLE
Viewer is not waiting for pdfjs to load

### ISSUE THREAD

**Issue by GAGANsinghmsitece** [mozilla/pdf.js#14666]
Attach (recommended) or Link to PDF file here:
http://www.pdfill.com/example/pdf_commenting_new.pdf
Configuration:
- Web browser and its version:  Firefox 96.0
- Operating system and its version: Ubuntu 20.04
- PDF.js version:2.12.313
- Is a browser extension:  No

Steps to reproduce the problem:
1.  Use the viewer.js file shown in the issue
2. Reload viewer.html several times. Most likely you will encounter the error in the console

What is the expected behavior? (add screenshot)
PDF must get loaded without error.
![image](https://user-images.githubusercontent.com/37043052/158048486-8fb0f9c7-8a8a-4054-8a39-dd7049a4bef5.png)

What went wrong? (add screenshot)
Sometimes the pdf is not loaded with the error shown in the screenshot.  The viewer is not waiting for the `_pdfjsLib` to load which is why the error occurs but i am not sure why it is not waiting.
![image](https://user-images.githubusercontent.com/37043052/158048515-b3fbcfe4-4e3d-4bc6-a397-010032bcb391.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://cocky-dijkstra-3b97ff.netlify.app/

Here's the code of viewer file. I commented some components which i do not need.
https://gist.github.com/GAGANsinghmsitece/e04218e9caa9d56ff43b9665549c726f

**Comment by Snuffleupagus** [comment]
> Sometimes the pdf is not loaded with the error shown in the screenshot.

Please keep in mind that intermittent issues can be very difficult to debug in general...

> Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
> https://cocky-dijkstra-3b97ff.netlify.app/

An entire *customized* viewer isn't really possible/reasonable for us to debug, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> Here's the code of viewer file. I commented some components which i do not need.
> https://gist.github.com/GAGANsinghmsitece/e04218e9caa9d56ff43b9665549c726f

Unfortunately that's not really helpful, as mentioned above, since it's just too much code to look through. However, considering that https://mozilla.github.io/pdf.js/web/viewer.html works, it's unfortunately likely that one (or more) of your changes are the source of the problem.
Does the viewer work if you remove all of your changes/customizations? If so, I'd suggest changing only *one thing* at a time until you're able to pinpoint exactly where things break.

**Comment by GAGANsinghmsitece** [comment]
@Snuffleupagus  I found the root cause of the issue. In my case,  the problem is in these lines:-

```

let pdfjsLib;

if (typeof window !== "undefined" && window["pdfjs-dist/build/pdf"]) {
  pdfjsLib = window["pdfjs-dist/build/pdf"];
} else {
  pdfjsLib = "/static/pdfjs/build/pdf.js";
}
pdfjsLib = window["pdfjs-dist/build/pdf"];
module.exports = pdfjsLib;
```
In the normal viewer.js file, it is using require to load the library. 
```
let pdfjsLib;

if (typeof window !== "undefined" && window["pdfjs-dist/build/pdf"]) {
  pdfjsLib = window["pdfjs-dist/build/pdf"];
} else {
  pdfjsLib = require("../build/pdf.js");
}

module.exports = pdfjsLib;
```
In my case,i cannot use require as i am using ESM modules and i believe i cannot use import as well as require in same project. What should be done in this case?

**Comment by Snuffleupagus** [comment]
> I found the root cause of the issue. In my case, the problem is in these lines:-

That would suggest that *your own* build scripts are (somehow) interfering with the pre-built PDF.js files, which could lead to all sorts of bugs in general.

Besides the issues mentioned above, the most likely cause of your problem is actually in how you're attempting to load the library, since the only thing that's supported is using a `script` tag to load the `pdf.js` file.

**Comment by GAGANsinghmsitece** [comment]
I'm loading the library using script tag inside body of HTML page. I tried using the script tag inside head of the page and it seems to eliminate the issue.
