### ISSUE TITLE
How to enable annotations in this pdf.js code

### ISSUE THREAD

**Issue by SUHASV117** [mozilla/pdf.js#14660]
Even though I have cloned the repository and running it on my local,  when I open the browser, I am not able to select the text and do annotation. How to enable this feature?

**Comment by Snuffleupagus** [comment]
Please refer to the `viewer components` examples for a (simpler) way to build a viewer, see https://github.com/mozilla/pdf.js/tree/master/examples/components

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable/valid.
Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
