### ISSUE TITLE
Export PageViewport class?

### ISSUE THREAD

**Issue by vedantroy** [mozilla/pdf.js#14664]
I've noticed that the `PageViewport` class is only exported as a type.
I was wondering if it would be possible to export the class as a value, so consumers of the library can use it

Why? I have a `PageManager` class that handles which pages should be rendered, etc.

It stores a viewport for the current page width/height.
In my tests, I'd like to pass in a fake viewport, but currently I cannot do this because    I cannot use `PageViewport` as a value.

**Comment by Snuffleupagus** [comment]
> I was wondering if it would be possible to export the class as a value, so consumers of the library can use it

While it'd be technically possible, it's unfortunately not a desirable change from the PDF.js library perspective.

Note that while `PageViewport`-instances are returned by the `PDFPageProxy.getViewport`-method in the API, that class is *not* intended to be initialized manually by users. We purposely don't want to expose everything in the public API, since that makes both maintenance and any future changes of the affected code so much more difficult.

> In my tests, I'd like to pass in a fake viewport, but currently I cannot do this because I cannot use `PageViewport` as a value.

It's possible that there's ways to work-around that, but given that you've not provided any details about *exactly* what you're trying to do we cannot really help here.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes *easily* actionable.
Furthermore, since it seems very relevant here, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
