### ISSUE TITLE
Out of memory issue while loading the large pdf with around 25k pages and size of 130MB

### ISSUE THREAD

**Issue by ThalapaneniSushma** [mozilla/pdf.js#14673]
Hi,

Actually in our web application we are using mozilla pdf.js plugin to view the pdf files and very recently we are facing an issue i.e.  when we are trying to load a pdf which contains more than 25k pages with a size of 130MB (**Note: We are streaming the pdf files**), the browser is throwing out of memory issue in the Chrome browser, but in Firefox its working fine i.e. able to load the 25k pages pdf file

Please find the below screenshots for reference 
![pdf-failed](https://user-images.githubusercontent.com/91343957/158114131-53ecd58a-1112-4985-a478-5556d80b12b0.PNG)
![pdf-failed-1](https://user-images.githubusercontent.com/91343957/158114139-6751b8f1-7697-4a9a-8eff-65c7b7413743.PNG)

Please any suggestions/help would be appreciated as its the heart of our application.

Thank you

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't actionable/valid.

> Actually in our web application we are using mozilla pdf.js plugin to view the pdf files

Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> the browser is throwing out of memory issue in the Chrome browser, but in Firefox its working fine

That suggest a *browser* issue, rather than a PDF.js one, since otherwise you'd expect it to be consistently broken *everywhere*.
However, given that Firefox is the primary development target for this library and that you've not provided *any* of the details necessary to even reproduce this there's nothing that can be done here unfortunately.
