### ISSUE TITLE
Text markings are not alligned correctly

### ISSUE THREAD

**Issue by harrichtobias** [mozilla/pdf.js#14674]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome Version 99.0.4844.51
- Operating system and its version: Windows 10 Enterprise 21H2 Build 19044.1586
- PDF.js version: v2.13.216 (Issue can be reproduced in the pdf.js online Demo, I aussume its running on the latest build)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the online Demo (https://mozilla.github.io/pdf.js/web/viewer.html)
2. Mark the Letters "Ju" from the title of the demo Document ("Trace-based Just-in-Time Type Specialization for Dynamic
Languages")
3. Misaligned markings can be observed (Check given Screenshots for more detail)

What is the expected behavior? (add screenshot)
It is expected that the markings cover the marked characters completely

What went wrong? (add screenshot)
The Letters "Ju" are marked, however the markings cover only the half of the letter "J"
![image](https://user-images.githubusercontent.com/28890447/158149995-b5a50bdd-64f7-43b0-b0ce-46ffb9393924.png)

**Comment by Snuffleupagus** [comment]
Given how the text-layer is currently implemented, since rendering/text-extraction are separate in PDF documents, it's unfortunately somewhat expected that it won't always agree *perfectly* with the rendered glyphs.
One possible way to improve this is tracked in issue #13083, of which this is for all intents and purposes a duplicate.
