### ISSUE TITLE
Getting 'renderView: "RenderingCancelledException: Rendering cancelled, page 1"' error after upgrading version from 2.3 to 2.4

### ISSUE THREAD

**Issue by rekhakhatri1212** [mozilla/pdf.js#14677]
Attach (recommended) or Link to PDF file here: Any document

Configuration:
- Web browser and its version: Latest Chrome
- Operating system and its version: Windows 10
- PDF.js version: 2.4.456

Steps to reproduce the problem:
After setDocument, I'm setting zoom value, i.e. _this.pdfViewer.currentScaleValue = this.currentScaleValue;__

What is the expected behavior?
PDF should render fine and there should not be any errors in console.

What went wrong?
PDF is rendering fine but it displays this error in console: 
![image](https://user-images.githubusercontent.com/100104839/158321013-3e337737-0330-4361-8c03-366d2dcc80e4.png)

I tried upgrading the pdfjs version to 2.9 and it still gives the same error.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.4.456
> [...]
> I tried upgrading the pdfjs version to 2.9 and it still gives the same error.

Neither of those versions are supported any more, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:
> After setDocument, I'm setting zoom value, i.e. _this.pdfViewer.currentScaleValue = this.currentScaleValue;__

Unfortunately that's not nearly enough information for anyone else to reproduce what you're seeing, hence please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> PDF is rendering fine but it displays this error in console:

*Generally speaking, please include error messages as __text__ rather than images.*
However, please note that `zone.js` is *not* something that's provided by the PDF.js library and as such we unfortunately can't provide any support for that. Given the overall lack of information, closing as INCOMPLETE.
