### ISSUE TITLE
Date fields with custom formats are filled with a value but the input display something else

### ISSUE THREAD

**Issue by namblard-sword** [mozilla/pdf.js#14672]
Hi pdfjs team,

Please find attach a really simple pdf file to reproduce the issue.
[Date.pdf](https://github.com/mozilla/pdf.js/files/8242310/Date.pdf)
This pdf contains 4 date fields, One with a default format (dd/mm/yyyy) and the 3 others with custom formats:

    -  dd
    -  mm
    -  yyyy

The expected behavior is that whenever I fill dd field with 16 for instance, then when i focus out that field the value displayed is 16 but I get 01.

This happens for dd field and mm but it's working fine for dd/mm/yyyy and yyyy fields.

The initial values of the pdf are properly displayed, this happens only if I focus one of those fields.

Thank you for your time

Best regards.

**Comment by Snuffleupagus** [comment]
*For future reference;* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that all necessary details are provided.

**Comment by calixteman** [comment]
It's mainly due to:
https://github.com/mozilla/pdf.js/blob/90c5e9882bfaafbc7532fdd04c172d65b6757399/src/scripting_api/aform.js#L56
when the argument is for example "05".
In Firefox, the result is `NaN` when in QuickJS it's interpreted as 0005/01/01 (it's why with QuickJS we can see a "01"), and in Chrome it corresponds to "2001/05/01".
So to fix the issue, we must try to use `scand` and then if something is wrong try to use `Date.parse`.

**Comment by timvandermeij** [comment]
Fixed by the PR above. Thank you for reporting this!

**Comment by namblard-sword** [comment]
Hello,

Thank you for your support and your reactivity !
