### ISSUE TITLE
How to upload a PDF file to a web page, get the PDF fields values and render them into the same web page fields using JavaScript

### ISSUE THREAD

**Issue by samehkm** [mozilla/pdf.js#14686]
I am trying to develop a web page where I want to upload a PDF file to a web page, get the values of the PDF fields then render them into the web page fields using JavaScript. May I ask for a sample code on how to do this

I tried the following code but did not work

<html>
<head>
<script src="jquery-2.1.4.js"></script>
<script src="jspdf.min.js"></script>
</head>
<body>
		<input type="file" id="file-id" name="file_name" onchange="ExtractText();">
		
		<div id="output"></div>
<script>
 	function ExtractText() {
		var input = document.getElementById("file-id");
       	         // Insert get doc field code here
                var doc = new jsPDF(input.files[0]);          
        }
</script>
</body>
</html>

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum, and that this issue unfortunately contains no actionable information (and we cannot write your code for you).

> I tried the following code but did not work
> <script src="jquery-2.1.4.js"></script> <script src="jspdf.min.js"></script>
> <script> function ExtractText() { var input = document.getElementById("file-id"); // Insert get doc field code here var doc = new jsPDF(input.files[0]); } </script>

It really looks like you opened an issue with the *wrong project*, since this is *not* the jsPDF project!

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes actionable/valid.
Furthermore, please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
