### ISSUE TITLE
Is it possible to detect if the pdfjs.disabled Firefox parameter is true without causing a download?

### ISSUE THREAD

**Issue by SuperPat45** [mozilla/pdf.js#14697]
Configuration:
- Web browser and its version: Firefox 98
- Operating system and its version: Windows 10
- PDF.js version: latest
- Is a browser extension: no

There are some organizations that have disabled the Firefox PDF with the property pdfjs.disabled=true
In this case I would like to be able to detect it and embed PDF in an iframe through the viewer (I plan to use the [PDFObject](https://pdfobject.com/) librrary).

Is it possible to detect if the pdfjs.disabled Firefox parameter is true without causing a download?

**Comment by Snuffleupagus** [comment]
In up-to-date browsers, you might be able to use `navigator.plugins` since Firefox normally[1] returns an empty `PluginArray` when `pdfjs.disabled=true` is set. Closing as answered, since there's nothing that we can really do about this *here* (and `PDFObject` is an unrelated project).

---
[1] However, it's possible that the value isn't accurate if the `privacy.resistFingerprinting=true` is set.

**Comment by SuperPat45** [comment]
Since Firefox 99 and Chrome 94, it can now be detected with the parameter :
navigator.pdfViewerEnabled

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/pdfViewerEnabled
