### ISSUE TITLE
Use <dialog> element for the document properties modal

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14698]
It has been recently released in Firefox:
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog
and it's available in Safari too:
https://webkit.org/blog/12445/new-webkit-features-in-safari-15-4/

**Comment by Snuffleupagus** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog#browser_compatibility, we probably need to wait a little while longer since we try and keep the GENERIC PDF.js library/viewer compatible with at least the current Firefox ESR version; please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Also, we really should be updating *all* of the overlays then (e.g. the `PasswordPrompt` as well) and not just the `PDFDocumentProperties` one.

**Comment by Snuffleupagus** [comment]
Based on some quick tests, replacing our custom-overlays with `<dialog>` elements seems to *mostly* work just fine (although it will require some refactoring).
The only thing that didn't "just work" is the horizontal/vertical centering of the `<dialog>`s, since they end up at the top-left corner of the window, and I don't really understand why!?

**Comment by calixteman** [comment]
@Snuffleupagus, would you mind to push what you did in order to try to figure out what's wrong with the positioning ?

**Comment by Snuffleupagus** [comment]
I was, perhaps naively, assuming that by default the `<dialog>` elements would be centered automatically, since that's how all of the examples I found online seemed worked (although most of those were quite small/simple).
I also tried to replicate our old centering CSS, but that didn't seem to help in either when testing in both Firefox and Chrome.

> would you mind to push what you did in order to try to figure out what's wrong with the positioning ?

Sure, please see https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:overlays-dialog for a very basic patch (ignore the ugly hacks in the JS code).

**Comment by calixteman** [comment]
It works in commenting: https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/web/viewer.css#L175
In chrome devtools:
![image](https://user-images.githubusercontent.com/5641725/159487208-fa13bfc9-57bc-4406-a5ef-1db7f744799b.png)
I noticed that the dialog has margin set to auto when we've a 0 for all the elements.
So I just tried in unchecking and it worked.

**Comment by Snuffleupagus** [comment]
> I noticed that the dialog has margin set to auto when we've a 0 for all the elements.
> So I just tried in unchecking and it worked.

Thank you; it seems that simply setting `margin: auto;` for the `<dialog>` CSS works fine :-)

---

There's still, as far as I'm concerned, the question if should perhaps wait a little while longer with making this change (given that the feature is fairly new)?
Besides that, the "only" thing left to do for the patch would be to fix-up the `OverlayManager` functionality to properly handle things now that `<dialog>` elements are used.

**Comment by Snuffleupagus** [comment]
Actually, I think the patch(es) are mostly done now since everything *seems* to work as intended :-)
https://github.com/Snuffleupagus/pdf.js/compare/OverlayManager-private...Snuffleupagus:overlays-dialog?w=1
