### ISSUE TITLE
Set Textfield-Value with Javascript not working as expected

### ISSUE THREAD

**Issue by tma-src** [mozilla/pdf.js#14705]
**Demo PDF:**

[js_set_textfield_value.pdf](https://github.com/mozilla/pdf.js/files/8323371/js_set_textfield_value.pdf)

**Configuration:**
- Web browser and its version: Chrome Version 99.0.4844.74 (Offizieller Build) (64-Bit)
- Operating system and its version: Windows 10
- PDF.js version: Online Demo Viewer( https://mozilla.github.io/pdf.js/web/viewer.html )

**Steps to reproduce the problem:**
1. Load example pdf into demo viewer( https://mozilla.github.io/pdf.js/web/viewer.html )
2. Enter Something into the Textfield
3. Toggle Checkbox to change the value of the Textfield
=> Not Working

The Problem only occurs after something was put in the Textfield manually, if you load the pdf into the viewer and just toggle the checkbox the textfield value is changed as expected

**Link to a viewer** (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by calixteman** [comment]
It's because of this check:
https://github.com/mozilla/pdf.js/blob/feea2b78fab64d1b1c000ab5a0a6bb875d2a7dfe/src/display/annotation_layer.js#L972
There is a `userValue` and a `formattedValue` here because the string entered by the user can differ from the one displayed on blur, for example `1234` can be displayed as `1,234` but when the field is focused we must reset to `1234`.
