### ISSUE TITLE
Suggestion: use viewer width / height to calculate page scales when zoom factor is 'fit-page-width' or 'fit-page-height'

### ISSUE THREAD

**Issue by itechbear** [mozilla/pdf.js#14713]
When users choose percent zoom factors from menu, viewer's height/width is used to calculate page scales. However, the fit-page-width/fit-page-height modes use container's height/width to calculate scales, which is inconsistent. Although viewer's width & height are very close to container's width & height. 

Related lines:
https://github.com/mozilla/pdf.js/blob/db4f3adc5e521d767e0aba6327f7633b926f1523/web/base_viewer.js#L1097
https://github.com/mozilla/pdf.js/blob/db4f3adc5e521d767e0aba6327f7633b926f1523/web/base_viewer.js#L1101

**Comment by Snuffleupagus** [comment]
> However, the fit-page-width/fit-page-height modes use container's height/width to calculate scales

And there's a very good reason for doing that, namely documents with differently sized pages. In those cases it's really not helpful to use e.g. the entire viewer-width when zooming, since that could easily lead to a page becoming large enough that most of it is out-of-view (which is not going to be what users generally want).

> Although viewer's width & height are very close to container's width & height.

That only applies to documents where all pages are the *exact same size*, which in general isn't guaranteed.
