### ISSUE TITLE
Weird results from getTextContent with text in some large unicode ranges

### ISSUE THREAD

**Issue by karlak** [mozilla/pdf.js#14714]
Attach (recommended) or Link to PDF file here: [test3.pdf](https://github.com/mozilla/pdf.js/files/8341147/test3.pdf)

Configuration:
- Web browser and its version: Chrome Version 98.0.4758.102 (64 bits)
- Operating system and its version: Windows 10 (64bits)
- PDF.js version: v2.13.216
- Is a browser extension: No

Steps to reproduce the problem:
1. load the attached pdf and get the text with the `getTextContent` function
2. compare with adobe reader copied text

What is the expected behavior?
First character copied to clipboard with Adobe Reader is `U+100001`

What went wrong? 
I get the character `3` with pdf.js

I temporarily modified pdf.worker.js to try and see where this is coming from and I got some interesting data.
when printing the `chars` passed to `buildTextContentItem({chars, extraSpacing})` I get `\u00003\u0000R\u0000L\u0000Q\u0000W\u0000V\u0000\u000f`. I assume this is the first word so the first (2 ?) characters here are supposed to be the character `U+100001` I got from adobe reader. In any case it is strange to have `NUL` bytes here.

**Comment by Snuffleupagus** [comment]
> First character copied to clipboard with Adobe Reader is `U+100001`

When testing in Adobe Reader, I'm getting `U+100033` for the first character (i.e. the one rendering as an upper-case "P").
In any case, none of the PDF viewers I've tested (including Adobe Reader) produces any *meaningful* textContent here since what's copied is just gibberish that doesn't agree with the rendered text.

> I get the character `3` with pdf.js

I get more-or-less identical textContent in both PDF.js and in PDFium (the PDF viewer used in Google Chrome).
Furthermore, please note that your PDF document contains no `/ToUnicode` data and that text-selection and copying thus *unfortunately* cannot work correctly here. This is a bug in the PDF document itself, rather than in various PDF viewers.
