### ISSUE TITLE
CORS ERROR - Is there a limit in no. of users can access the uploaded file?

### ISSUE THREAD

**Issue by deepudinesh** [mozilla/pdf.js#14727]
Hi,
I am facing CORS error when users trying to access the pdf.

my application is a video conferencing  web application in nuxt,
inside a meeting multiple users say about 20 users, will access the pdf file which uploaded in s3 bucket.
some users facing CORS issue when opening the pdf.
So  MY DOUBT IS, IS THERE ANY LIMIT SPECIFIED ON VIEWERS SIZE INSIDE THE PDF JS'S LIBRARY, LIKE NO. USERS WHO CAN ACCESS THE SAME PDF.
(The pdf url is s3 bucket url and cors configurations are added there, everything is fine on server side. but some users face CORS issue.)

Any help is appreciated.
Thank you

**Comment by Snuffleupagus** [comment]
See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr, which is the only assistance that can realistically be provided here.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable details provided here.

**Comment by deepudinesh** [comment]
Ok Thank you for the quick  response, will do that.
