### ISSUE TITLE
pdf file convert canvas to blob  failed when print pdf in safari

### ISSUE THREAD

**Issue by justalways** [mozilla/pdf.js#14732]
Attach (recommended) or Link to PDF file here:
[67040_EH_Show_Booth_Banner_3_VFIN.pdf](https://github.com/mozilla/pdf.js/files/8379425/67040_EH_Show_Booth_Banner_3_VFIN.pdf)

Configuration:
- Web browser and its version: safari  15.3
- Operating system and its version:  MAC 15
- PDF.js version: PDF.js: 2.13.0
- Is a browser extension: no

Steps to reproduce the problem:
1. print this pdf will be stuck at here
2. 
![image](https://user-images.githubusercontent.com/9329575/160807929-c0862f2e-b567-448e-be78-b3dd0d72262a.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/9329575/160805861-53ba0912-6fe7-4d52-8372-9a6ce4c96462.png)
at red area , the argument blob is null , so it get error like this
![image](https://user-images.githubusercontent.com/9329575/160808684-765f30f5-dfc6-46fd-9a22-b55588d886ac.png)
 
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, when using PDF.js `2.14.117` (i.e. the latest development version) in both Firefox Nightly 100 and Google Chrome Beta 100.

Hence this unfortunately looks like a *browser* bug in Safari, rather than a PDF.js library/viewer one. Please note that Safari is *not* listed as fully supported, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: PDF.js: 2.13.0

That's not actually an existing version number...

**Comment by justalways** [comment]
@Snuffleupagus 
![image](https://user-images.githubusercontent.com/9329575/160824762-8bcf3432-22b9-4fc2-9dce-503a3d009663.png)
