### ISSUE TITLE
TextContent Font Information

### ISSUE THREAD

**Issue by maybe2105** [mozilla/pdf.js#14730]
Attach (recommended) or Link to PDF file here: https://shub-storage.sgp1.cdn.digitaloceanspaces.com/tests/2322868/file_url/1646841064228_2022._De_5.pdf

Configuration:
- Web browser and its version: Chrome   99.0.4844.84
- Operating system and its version:  Windows 10 21H2 19044.1586
- PDF.js version: 2.6.347

Is there anyway that i can get the font infomartion like fontSize 12px , open sanserif, etc.. from getTextContent or from getDocument ? After scrolling through some issues i know there is a FontFaceObj with fields like fallBackName : "serif" or loadedname "g_d2_f1" ,.... but i couldn't find the fontSize

I use the getPage function then render the pdf into canvas, does its fontsize affected by my html fontsize?

i need to calculate the width of textContent from getTextContent() to split the textContent into parts, because getTextContnet often break word into multiple text objects or keep the whole line as only 1 text object, but i can't find a way that i can get fontsize to do it

Thank you very much

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Is there anyway that i can get the font infomartion like fontSize 12px , open sanserif, etc.. from getTextContent or from getDocument ?

That'd require iterating through the operatorList[1], and checking for the `OPS.setFont` operator which contains both the *internal* font-name and also the font-size. However, please note that since rendering and text-extraction are separate in PDF documents (from a specification perspective) you'll not be able to directly connect the rendered glyphs with actual textLayer content. Unfortunately it sounds like your use-case might be one that we don't really support, however given the somewhat limited information it's a bit difficult to tell *exactly* what you're actually trying to do here.

---
[1] See https://github.com/mozilla/pdf.js/blob/4d4c67dd6e5c826287cd7cdd216435cd651a9301/src/display/api.js#L1545-L1554
