### ISSUE TITLE
Hi is there any way through which we can prevent download of my PDF through the applications like, (IDM) by using JavaScript project 

### ISSUE THREAD

**Issue by pawansoft** [mozilla/pdf.js#14762]
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <meta http-equiv="X-UA-Compatible" content="ie=edge" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css"
    integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous" />
  <link rel="stylesheet" href="css/style.css" />
  <title>PDF Viewer</title>
  <style type="text/css" media="print">
    body {
      visibility: hidden;
      display: none
    }
  </style>
</head>

<body oncontextmenu="return false">
  <div class="top-bar">
    <button class="btn" id="prev-page">
      <i class="fas fa-arrow-circle-left"></i> Prev Page
    </button>
    <button class="btn" id="next-page">
      Next Page <i class="fas fa-arrow-circle-right"></i>
    </button>
    <span class="page-info">
      Page <span id="page-num"></span> of <span id="page-count"></span>
    </span>
  </div>

  <iframe id = 'iframe' style="width:600px; height:500px;" frameborder="0"></iframe>

  <script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
  <script src="js/main.js"></script>
  
</body>

</html>

**Comment by Snuffleupagus** [comment]
Sorry, but this isn't really an actionable/valid issue! When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Generally speaking, if a document can be viewed is can also be downloaded (by e.g. tech-savvy users). Furthermore, we don't support any Internet Download Managers here (which I'm *guessing* is what the abbreviation means).

Finally, please *do not* use this GitHub repository as a CDN since that's really not intended; see https://mozilla.github.io/pdf.js/getting_started/#including-via-a-cdn
