### ISSUE TITLE
A PDF causes macOS Chrome's browser tab to crash

### ISSUE THREAD

**Issue by hubgit** [mozilla/pdf.js#14763]
Attach (recommended) or Link to PDF file here: 
[pdfjs-crash.pdf](https://github.com/mozilla/pdf.js/files/8451728/pdfjs-crash.pdf)

Configuration:
- Web browser and its version: Chrome 100
- Operating system and its version: macOS 12.3
- PDF.js version: 2.13, latest
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the attached PDF in https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? The PDF is rendered without crashing.

What went wrong? The Chrome tab crashes and displays the "Aw, Snap!" message.

---

The PDF is displayed without crashing in pdf.js v2.10, but causes the tab to crash in v2.13 and above.

The problem is not observed in macOS Safari or Firefox.

The metadata says that the PDF was created in PowerPoint 2016, but I didn't create it and haven't got access to the original source to be able to create a more minimal example.

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.13, latest

*For future reference:* Please keep in mind that all PDF.js versions consist of *three* numbers, hence the mentioned version number isn't entirely complete.

> The PDF is displayed without crashing in pdf.js v2.10, but causes the tab to crash in v2.13 and above.

You might be able to use `git bisect` to find out more exactly when this "broke" (but please read on below).

> What went wrong? The Chrome tab crashes and displays the "Aw, Snap!" message.
>
>The problem is not observed in macOS Safari or Firefox.

Given that this bug is apparently specific to *one browser* (i.e. Google Chrome), that unfortunately suggests a browser-specific (or even platform-specific) problem rather than a general PDF.js library one. Otherwise you'd really expect it to be consistently broken *everywhere*, rather than in just one browser and/or platform.

In my testing, using https://mozilla.github.io/pdf.js/web/viewer.html and Google Chrome Beta 101 on Windows, your document opens just fine without any crashes.
The first thing that'd be needed here is to try and pin-point *exactly* when this broke, however please keep in mind that we generally don't accept browser-specific compatibility hacks in the main PDF.js code-base. Hence this, most unfortunately, looks like a browser-bug rather than something that we can fix *here*.

**Comment by hubgit** [comment]
> In my testing, using https://mozilla.github.io/pdf.js/web/viewer.html and Google Chrome Beta 101 on Windows

The crash only occurs in Chrome on macOS.

> Please keep in mind that all PDF.js versions consist of three numbers, hence the mentioned version number isn't entirely complete.

There has only been one release per minor version, as per [the releases list](https://github.com/mozilla/pdf.js/releases). To be precise, this is [v2.10.377](https://github.com/mozilla/pdf.js/releases/tag/v2.10.377) vs [v2.13.216 ](https://github.com/mozilla/pdf.js/releases/tag/v2.13.216).

**Comment by calixteman** [comment]
I can reproduce with local dev environment with Chrome on mac OS 12.2.1.
I had a quick look and for now I don't really understand what's wrong here.

**Comment by hubgit** [comment]
`git bisect` suggests that commit 61d1063276137e87f4dd2d2e8a3e071a280357a0 is responsible.

**Comment by Snuffleupagus** [comment]
> `git bisect` suggests that commit [61d1063](https://github.com/mozilla/pdf.js/commit/61d1063276137e87f4dd2d2e8a3e071a280357a0) is the first bad commit.

The only thing that I could imagine possibly being a problem, based on the code, is the regular expression with [Unicode property escapes](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Unicode_Property_Escapes). Note that that regular expression has been extended, and moved, since then and now looks like: https://github.com/mozilla/pdf.js/blob/2b673a694114268bad7cc7dd687bf004513e1815/src/core/unicode.js#L1643

Does running the following code, in Google Chrome on MacOS, fail in the same (or a similiar) way?
```javascript
const SpecialCharRegExp = new RegExp("^(\\s)|(\\p{Mn})|(\\p{Cf})$", "u");
for (char of ["ܴ", "ܷ", "݀"]) {
  const groups = char.match(SpecialCharRegExp);
  console.log(groups);
}
```
If so, that's definitely a bug in Google Chrome and one which needs to be reported to the Chromium bug tracker.

**Comment by calixteman** [comment]
I just tried in the console and nothing wrong.
I commented the code in unicode.js and I got the same crash.

**Comment by calixteman** [comment]
In reading the potential guilty patch, I cannot see something which could trigger a chrome & mac specific bug... it's really strange.

**Comment by Band-Aid** [comment]
I'm able to replicate this with Edge as well.

**Comment by Snuffleupagus** [comment]
> I'm able to replicate this with Edge as well.

That's probably not too surprising, given that Microsoft Edge is *essentially* just a re-branded version of Chromium these days.

---

As mentioned above, given that this issue isn't just browser- or OS-specific but actually requires a very particular combination of one browser *and* one OS it unfortunately doesn't really seem actionable/valid here.
Furthermore, as also mentioned above, there's nothing in the *potentially offending* patch that looks out-of-place and which could easily explain the problems either.

All-in-all, this most unfortunately doesn't look actionable *here* and it's probably necessary to file a bug against the Chromium project in order to get to the bottom of this.

**Comment by elias-highspot** [comment]
@hubgit @Snuffleupagus 
Chromium bug report submitted: https://bugs.chromium.org/p/chromium/issues/detail?id=1320475
