### ISSUE TITLE
v2.13.216 fails to run at all on Safari 13 due to use of OR assignment operator ( ||= )

### ISSUE THREAD

**Issue by danatemple** [mozilla/pdf.js#14775]
The documentation says that in the standard build, Safari 12+ is supported, with "most features". This sounds fine, but....

What I've discovered is that Safari 13 completely fails due to a syntax error at line 1707 in pdf.js where it uses the ||= operator.
This matches what is expected to be supported from caniuse:

https://caniuse.com/?search=%7C%7C%3D

Obviously I can work around this by using the legacy distribution, but it seemed from the docs that this was not the intention to fully break such a recent version of a major browser, so I am raising this for your attention.

**Comment by Snuffleupagus** [comment]
> The documentation says that in the standard build, Safari 12+ is supported, with "most features".

(I'm guessing that you're referring to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support here.)
The intention with that data is to outline the *absolute minimum* browser versions that we'll try to support, however for anything except the very latest versions (of each browser) you'll need to use a `legacy`-build of the PDF.js library.

Please note that it's unfortunately way too much work for us to maintain *two* compatibility tables, i.e. one for the modern build and one for the `legacy` build, since the features used in the modern build will change as e.g. the JavaScript/HTML specifications evolve and improve.

> Obviously I can work around this by using the legacy distribution,

That's not a work-around, but actually the *intended* solution for anything except the very latest browsers. (However, that even the latest development version of Safari is lacking some standard features.)

**Comment by danatemple** [comment]
>(I'm guessing that you're referring to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support here.)
>The intention with that data is to outline the absolute minimum browser versions that we'll try to support,

What it actually says is:

**Safari 12+   "Mostly"  " Some missing features/defects have been reported, but no problems in general."**

I entirely agree that you don't need more work (excellent work on PDFJS, it's great and I appreciate that!). 

But it might help the next person to update that page following this report, that Safari 13 (at least) fails to work at all.

**Comment by Snuffleupagus** [comment]
> But it might help the next person to update that page following this report, that Safari 13 (at least) fails to work at all.

Again, you need to use a `legacy`-build for older versions of e.g. the Safari browsers; hence it *should* work as-is.
