### ISSUE TITLE
Does not work on huawei P30

### ISSUE THREAD

**Issue by ZhuoJunErGe** [mozilla/pdf.js#14778]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ZhuoJunErGe** [comment]
Same question on vivo X27

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for the only support information that we can realistically provide. Note that it's not feasible to provide device-specific information, and that we thus only provide support information for *browsers*.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue is missing every necessary piece of information required to be valid.
