### ISSUE TITLE
Uncaught SyntaxError: private fields are not currently supported

### ISSUE THREAD

**Issue by parasBisht** [mozilla/pdf.js#14782]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 71.0
- Operating system and its version: Linux mint
- PDF.js version: https://mozilla.github.io/pdf.js/build/pdf.js
- Is a browser extension: No

Not getting the issue in the latest version of mozilla browser.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: 71.0

That's just a version number, hence it's not entirely clear which browser it actually refers to!
However, assuming that it's Mozilla Firefox, note that that browser version is over two years old and consequently shouldn't be used any more (since it may contain known security vulnerabilities).

Please refer to the FAQ for the official PDF.js support information: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: https://mozilla.github.io/pdf.js/build/pdf.js

Note that you're *really not* supposed to use that as a CDN, please see https://mozilla.github.io/pdf.js/getting_started/#including-via-a-cdn for that.
Furthermore, you should use *official releases* for anything except development purposes; please see https://mozilla.github.io/pdf.js/getting_started/#download

> Not getting the issue in the latest version of mozilla browser.

Again, you shouldn't use old and outdated browsers. However, you'll need to use a `legacy`-build of the PDF.js library for anything except the very latest browsers; note the two different builds at https://mozilla.github.io/pdf.js/getting_started/#download
