### ISSUE TITLE
How to send data to inputs? 

### ISSUE THREAD

**Issue by silicahd** [mozilla/pdf.js#14806]
This might be easier than i am making it but cant seem to find any info on it. 

I have a PDF that has some form fields. I am trying to send data to them when the PDF loads. 
When I am done I just want to save the PDF as a flat file back to the server in a diffrent folder. 

Is this posible? Maybe it is not posible and I am just waisting my time.

**Comment by Snuffleupagus** [comment]
You might be able to use the `AnnotationStorage` to pre-populate the form, but given the overall lack of information it's somewhat difficult to tell *exactly* what you're trying to do, please see https://github.com/mozilla/pdf.js/blob/9a8fa3201fbe440ab4b546976f641b04518cca3c/src/display/api.js#L725-L730 and https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_storage.js

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
