### ISSUE TITLE
Vue js example

### ISSUE THREAD

**Issue by Lukenickerson** [mozilla/pdf.js#14819]
It may be good to include an example of utilitizing the PDF.js library in a [vue js app](https://vuejs.org/). I'm creating this Issue for any discussion necessary before creating a fork and PR for adding the example. (It's not clear in the [Contributing document](https://github.com/mozilla/pdf.js/wiki/Contributing) whether or not code contributions need as corresponding Issue or not.)

I'm developing a prototype that does the following:

* Makes use of the [pdfjs-dist](https://github.com/mozilla/pdfjs-dist) repo
* Allows opening and viewing of a PDF using the PDF.js library in modular vue (3.2.33) components
* Provides an example of how to include a vue app into a plain webpage
* Uses webpack to bundle the code

Is this something that would be useful to add?

**Comment by Snuffleupagus** [comment]
Unfortunately I don't believe that any of the PDF.js developers/contributors know much (if anything) about the `Vue.js` framework. Hence it's going to be very difficult for us to first of all provide (any) support for such an example, and secondly we're also not going to be able to keep the example up-to-date with any changes in the `Vue.js` framework.

Please note that once we add an example, that basically means that we'll have to *somehow* try to support/maintain it and experience has shown that that can unfortunately be quite difficult.[1]

Hence, while we certainly do appreciate the offer to add a new example, it unfortunately doesn't seem like a good idea to add examples for frameworks that the PDF.js library isn't directly using.

---
[1] Previously we've added examples that we were then eventually forced to remove, since none of the PDF.js contributors could maintain them and the original example-author wasn't around any more.

**Comment by Lukenickerson** [comment]
If you'd like to link to a Vue example, I've created this: https://github.com/Lukenickerson/pdf-js-vue
