### ISSUE TITLE
SecurityError: Permission denied to access property "document" warning message in console:

### ISSUE THREAD

**Issue by edsonfeimberg** [mozilla/pdf.js#14811]
Acutally, the PDF is displayed and everything is working perfectly. But i get this message in console:

`webviewerloaded: SecurityError: Permission denied to access property "document" on cross-origin object [viewer.js:238:16](webpack://pdf.js/web/viewer.js)`

Since it doens't seem to affect any functionality, is this something i should be worried about?

**Comment by Snuffleupagus** [comment]
Given the lack of details, the only guess is that it's possibly related to https://github.com/mozilla/pdf.js/blob/9a8fa3201fbe440ab4b546976f641b04518cca3c/web/viewer.js#L236-L239

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't particularly easy to follow.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
