### ISSUE TITLE
Broken PDFs

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#14821]
When I am trying to load the PDF using PDF JS, the PDF is not rendering properly, the same is opening fine in Chrome. Please help/suggest/fix the same.

The "PDF.Issue.details.docx" attachment also shows the console errors while loading the PDF.

Steps:
1. Copy the files to a folder
2. Host to folder in IIS
3. Open index.html
4. The issue is replicated

Note: The PDF file name can be updated in the index.html file to check the issues in console.

Thanks
Manish

[Issue2.pdf](https://github.com/mozilla/pdf.js/files/8537074/Issue2.pdf)
[Issue1.pdf](https://github.com/mozilla/pdf.js/files/8537076/Issue1.pdf)
[Issue3.pdf](https://github.com/mozilla/pdf.js/files/8537077/Issue3.pdf)
[PDF Issue details.docx](https://github.com/mozilla/pdf.js/files/8537078/PDF.Issue.details.docx)
[index_html.txt](https://github.com/mozilla/pdf.js/files/8537102/index_html.txt)

**Comment by Snuffleupagus** [comment]
> The "PDF.Issue.details.docx" attachment also shows the console errors while loading the PDF.

Please note that such information should be included as *raw text* directly in the issue, rather than having to open a Word-document to access the data.

> Issue1.pdf

That document is corrupt enough that even Adobe Reader, i.e. the PDF reference implementation, cannot open it successfully.
However, using PDF.js version `2.14.171` (as shipping in Firefox Nightly 101) the document opens and renders "fine" despite it being corrupt. Hence you're most likely using an out-of-date PDF.js version, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Issue2.pdf
> Issue3.pdf

Both of these documents contain corrupt/incomplete font-data, which indicate bugs in the PDF document themselves and not in the PDF.js library, as evident from the logs (taken from the first one):
```
PDF bc646a2597a23cb35b799158c2292eed [1.4 PDFlib+PDI 8.0.0 (AIX) / -] (PDF.js: 2.14.171) [viewer.js:1483:13](resource://pdf.js/web/viewer.js)
Warning: loadFont - translateFont failed: "FormatError: Encoding is not a Name nor a Dict". [pdf.worker.js:1091:13](resource://pdf.js/build/pdf.worker.js)
Warning: Error during font loading: Encoding is not a Name nor a Dict
```

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable.

Furthermore, as mentioned in *the first paragraph* in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, please only report *one* problem per issue since otherwise tracking things becomes very difficult.

**Comment by ms3534** [comment]
Thanks, as you mentioned "_Both of these documents contain corrupt/incomplete font-data_", so if Chrome, Adobe, PDFTron, PSPDkit and many other tools can open/render the PDf.

 Can Pdf.js library be fixed to show/render the same.

**Comment by ms3534** [comment]
Thanks, when will those changes be released, means any anticipated/scheduled date as i wasn't able to find it anywhere in the page.....
