### ISSUE TITLE
Viewer is overlapping PDF pages.

### ISSUE THREAD

**Issue by munish31** [mozilla/pdf.js#14839]
Attach (recommended) or Link to PDF file here: 

Configuration:
- Web browser and its version: Google chrome Version 100.0.4896.127 
- Operating system and its version: Mac OS big Sur
- PDF.js version: 2.7 and older
- Is a browser extension: NA

Steps to reproduce the problem:
1. Notice that there is no gap between pages. Every page is on top of its previous page. 
2. Created PDF viewer using PDF.js library. 

What is the expected behavior? (add screenshot) Pdf pages should not overlap to each other.

What went wrong? (add screenshot)Pdf pages are overlapping.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
<img width="1792" alt="Screenshot 2022-04-26 at 1 00 08 PM" src="https://user-images.githubusercontent.com/5114600/165246603-24252aef-4b70-4c13-985e-1c3d5cdc364b.png">
<img width="1792" alt="Screenshot 2022-04-26 at 1 00 15 PM" src="https://user-images.githubusercontent.com/5114600/165246620-1591a3ee-c8c9-46ca-a8f9-7cf269ea0d94.png">

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.7 and older

That's first of all not a *complete* version, since every version number has the `x.y.z` format.
Secondly that version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Notice that there is no gap between pages. Every page is on top of its previous page.
> Created PDF viewer using PDF.js library.

Your screen-shots clearly indicate a *custom viewer*, which we know nothing about here. Furthermore, given that https://mozilla.github.io/pdf.js/web/viewer.html works fine this unfortunately suggests some kind of bug in your viewer (and we cannot really fix that for you).

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
