### ISSUE TITLE
PDF Broken Issue

### ISSUE THREAD

**Issue by ms3534** [mozilla/pdf.js#14842]
[document5.pdf](https://github.com/mozilla/pdf.js/files/8561837/document5.pdf)

The attached PDF is rendeing in Chrome, but **not** in Firefox & also not rendering with  PDF js plugin  in FF & Chrome.
https://mozilla.github.io/pdf.js/web/viewer.html

Console error in FF & Chrome with PDF JS Plugin:
Warning: getOperatorList - ignoring errors during "GetOperatorList: page 0" task: "ParserEOFException: End of file inside array.". [pdf.worker.js:1111:13](https://mozilla.github.io/pdf.js/build/pdf.worker.js)
Warning: getTextContent - ignoring errors during "GetTextContent: page 0" task: "ParserEOFException: End of file inside array.". pdf.worker.js:1111:13

**Comment by Snuffleupagus** [comment]
Your document is *clearly corrupt*, since it contains text-rendering operators like e.g. `[[(!"#$%&'\(%\)*)]TJ` and non-escaped "["-chars aren't allowed inside of text like that. When parsing that structure, we end up treating it like a nested Array which thus cause things to break.

Unfortunately fixing that would require adding a bunch of special-cases to the *general* Parser-implementation, which would thus (slightly) affect performance negatively for every single PDF document in existence just to fix *one* corrupt document.
Given that this is the very first case that we've seen of this sort of breakage, and that the hacks we'd have to resort to handle this would affect general performance, I'd suggest that we WONTFIX this for now (unless this issue turns out to be more common).
