### ISSUE TITLE
Investigate if we can safely remove the use of Uint8clampedArray when it's useless

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#14849]
For example here:
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/decode_stream.js#L101
we use the ctor with a typedArray argument:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray/Uint8ClampedArray#typedarray
and ergo data are copied.
And as far as I understand, `Uint8ClampedArray` is especially useful when some data are written in the array but in general (afaik) there are no difference with an `Uint8Array`.

Those `Uint8ClampedArray` have been added in https://github.com/mozilla/pdf.js/pull/9802.

and it clearly makes sense for color stuff, for [image.js::undoPreblend](https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L630) and maybe few other cases I overlooked but in general my feeling is that they're useless and their use induces a performance penalty.

@Snuffleupagus, any opinion about that ?

**Comment by Snuffleupagus** [comment]
> Those `Uint8ClampedArray` have been added in #9802.
> 
> and it clearly makes sense for color stuff, for [image.js::undoPreblend](https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L630) and maybe few other cases I overlooked but in general my feeling is that they're useless and their use induces a performance penalty.

I suppose that it's possible that we currently use the `forceClamp`-parameter unnecessarily is *some* cases, however that should be limited to data where e.g. the ColorSpace-code will subsequently be used, but it's not really clear to me more exactly which those actually are.
Do you perhaps have a list of potential ones that you think could/should be removed? Given that all code-paths that need to use `Uint8clampedArray` should have `assert`s, have you tried running all tests locally with your proposed changes?

**Comment by calixteman** [comment]
For example it seems to be useless here:
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L358
and even here (which is almost the previous version of the code above):
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L303
or here:
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L714-L738
or:
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L742-L757

Maybe we could remove the `forceClamped` parameter and return a wrapper around a typedArray.
And add a method to get a clamped version of the underlying buffer or a clone if we mustn't change the underlying data, something similar to what we have here:
https://github.com/mozilla/pdf.js/blob/694cb311c045a3499b5ed5865a2fe28469b42691/src/core/image.js#L715-L726
Just a sort of `Copy-on-Write` wrapper... something like that.
And the clamped version is only useful when some data are potentially out of the 0-255 range, but in case we do stuff like `buffer[i] ^= 0xFF` it isn't required.

The problem I see with the `forceClamped = true` parameter is that we use it because maybe at some point we'll do some color stuff. With the CoW approach, we're more lazy and just do the clone only when we absolutely need it.

**Comment by Snuffleupagus** [comment]
I'd suggest that we simply remove the `forceClamped`-parameter where it's actually deemed unnecessary, based on code-inspection and testing, and refrain from bigger changes here.

> Maybe we could remove the `forceClamped` parameter and return a wrapper around a typedArray.

What you're suggesting is, assuming I'm understanding you correctly, is changing the return type of `BaseStream.getBytes` and related methods. Doing that would affect basically the entire worker-thread code, in one way or another, since in most cases we're actually fine with whatever kind of TypedArray.
Having those methods return a wrapper, rather than an actual TypedArray, would thus mean re-writing so much code and I'd also wonder if the wrapper itself wouldn't also incur additional memory/run-time overhead?

**Comment by Snuffleupagus** [comment]
> I was thinking changing the return value of [getImageBytes](https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L870) and for stuff like:

Oh, that's the missing piece of context required to understand what you meant here :-)

Basically you want to limit the previous `forceClamped` handling to only the `PDFImage`-code, which means that it can removed from the various Stream-implementations; in that case that should probably be fine!
(Hopefully our existing `assert`s, combined with the ref-tests, should ensure that we don't accidentally regression something.)

**Comment by calixteman** [comment]
@Snuffleupagus, if you agree that it'd make things better, would mind to fix this bug ?

**Comment by Snuffleupagus** [comment]
> if you agree that it'd make things better, would mind to fix this bug ?

Maybe, but I'm not sure *exactly* what you have in mind for the `getImageBytes`-method. Do you want it to look something e.g. something like the following?
```diff
diff --git a/src/core/image.js b/src/core/image.js
index af0bf6f4a..6985024c1 100644
--- a/src/core/image.js
+++ b/src/core/image.js
@@ -872,7 +872,16 @@ class PDFImage {
     this.image.drawWidth = drawWidth || this.width;
     this.image.drawHeight = drawHeight || this.height;
     this.image.forceRGB = !!forceRGB;
-    return this.image.getBytes(length, /* forceClamped = */ true);
+
+    const imageBytes = this.image.getBytes(length);
+    return {
+      raw: imageBytes,
+      clamped: () => {
+        return imageBytes instanceof Uint8ClampedArray
+          ? imageBytes
+          : new Uint8ClampedArray(imageBytes);
+      },
+    };
   }
 }
```

**Comment by calixteman** [comment]
Yep and if possible the return object could handle the `if (this.image instanceof DecodeStream) ...` thing.
And if it safe to write into the original buffer then use `new Uint8ClampedArray(imageBytes.buffer)` instead to avoid an extra copy.
The idea is really to try to have something smart enough to avoid useless copies and to make the code more simple.
I can do it for sure, but you're certainly the best to avoid to miss something important somewhere and handle some corner cases you've in mind if any.

**Comment by Snuffleupagus** [comment]
After taking a *brief* look, and running all tests with a quickly thrown together patch, I'm not actually sure that we need any of the `forceClamped` handling in the `PDFImage`-code at all.
I might be overlooking something, or maybe our test-coverage is lacking, because it's really starting to look like this is basically useless code...

In the following cases we're returning the data without any `ColorSpace`-parsing, and the exact TypedArray used shouldn't matter:
 - https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L714
 - https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L751

In the following cases the image-data is only used *internally*, and again the exact TypedArray used shouldn't matter:
 - https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L762 however the actual image-data is being defined below in https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L772-L779
 - https://github.com/mozilla/pdf.js/blob/b72a4483276d65bef32cff269eb40923c1363f2d/src/core/image.js#L837
