### ISSUE TITLE
Provide option to revert to classic UI

### ISSUE THREAD

**Issue by LifeIsStrange** [mozilla/pdf.js#14876]
The previous UX which was dark theme like, is the habit of many people and for many is considered better since the dark color provide contrast with the document, which helps drawind boundaries, reduce cognitive overhead, and IMHO is much prettier.
I assume there is currently no way to revert to the classic UI on a recent PDF.js release?
In theory this is just a CSS + HTML file so reverting to previous behaviour should be relatively straightforward.

**Comment by Snuffleupagus** [comment]
> I assume there is currently no way to revert to the classic UI on a recent PDF.js release?

No, and reverting to *the old* viewer UI is not something that we'd even consider supporting either; as such this issue is unfortunately INVALID.

---

Note that the current UI theme will follow your browser/OS theme *automatically*, however you can force either light or dark colours with a preference; refer to PR #12625 for additional information.

Also, if you're using the default viewer in a custom setting (since it's not really clear from the issue), please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Finally, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable/valid.
