### ISSUE TITLE
self hosted pdfjs Ignored call to 'print()'.

### ISSUE THREAD

**Issue by lublak** [mozilla/pdf.js#14878]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web: Chrome 101.0.4951.41
- Operating system and its version: Windows 10
- PDF.js version: 2.13.216
- Is a browser extension: no

Steps to reproduce the problem:
1. currently i host it in a express.js server express.static and nginx reverse proxy
2. try to print

What is the expected behavior?
Add the allow-modals to the print function?

What went wrong?
![grafik](https://user-images.githubusercontent.com/44057030/166926269-ce28df80-7063-4463-941a-1ab22ad7b710.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Its internal hosted

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. currently i host it in a express.js server express.static and nginx reverse proxy
>     2. try to print

Unfortunately this isn't really actionable as-is, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> What is the expected behavior?
> Add the allow-modals to the print function?

According to https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox, `allow-modals` is an `<iframe>`-attribute. Hence, reading between the lines, it appears that you've placed the viewer inside of an `<iframe>`-element and you'll thus have to add the appropriate attribute to your `<iframe>`.

I'm sorry to say that this doesn't really look like an actionable PDF.js issue, since it seems to be relevant to your particular *custom* implementation; please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

**Comment by lublak** [comment]
@Snuffleupagus Sorry for my incorrect request.
Nevertheless, thank you very much for the answer.
Even if it is not the solution (since it was not in the iframe).
The problem has been fixed by manually updating to version 101.0.4951.54.
