### ISSUE TITLE
How to get arrow annotations instead of lines?

### ISSUE THREAD

**Issue by wongself** [mozilla/pdf.js#14896]
Attach (recommended) or Link to PDF file here: [2205.00976.pdf](https://github.com/mozilla/pdf.js/files/8662515/2205.00976.-.annot.pdf)

The function `getAnnotations` will return all annotations in PDF document, including squares, lines, circle, etc. However, the `Line` annotation also contains the `Arrow` type, which prevents me from knowing the direction of the arrow and the style of the arrow head.

Configuration:
- Web browser and its version: Microsoft Edge 101.0
- Operating system and its version: Windows 10 21H2
- PDF.js version: 2.13.216

Here are two `Line` annotations:
1. True `Line`

![Line](https://i.imgur.com/jnldXg4.png)

3. Should be `Arrow`

![Arrow](https://i.imgur.com/4Tghe2A.png)

What you can see is that both types of annotations above (I think it should be both) have the same properties, if you ignore some numerical differences.

I wish the function `getAnnotations` would treat the arrows as special lines and provide them with specific properties to identify the direction and arrow head.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately is not actionable/valid.

In particular the `Attach (recommended) or Link to PDF file here:`-part is *always* required.

> However, the `Line` annotation also contains the `Arrow` type,

The PDF specification does not contain a special "Arrow"-annotation type, it's all just "Line"-annotations. Most likely, given the lack of information, you're actually asking about extracting the `/LE`-data from "Line"-annotations which is something that we don't support (since it's very rarely used).

**Comment by wongself** [comment]
> The PDF specification does not contain a special "Arrow"-annotation type, it's all just "Line"-annotations. Most likely, given the lack of information, you're actually asking about extracting the `/LE`-data from "Line"-annotations which is something that we don't support (since it's rarely used).

I just looked through the [book](https://books.google.co.jp/books/about/Developing_with_PDF.html?id=IaRYAQAAQBAJ) to learn about the line annotation, and did find the special key `LE` (Line Ending) you mentioned, which is really what I was looking for.

I have tried adding the code `this.lineEnding = dict.getArray("LE")` [here](https://github.com/mozilla/pdf.js/blob/38c82357b247199b11fb573d0a3d4201347a47fc/src/core/annotation.js#L367-L375), and it does give me the endpoint style information I want.

![](https://i.ibb.co/1dbCfDD/Snipaste-2022-05-10-19-50-19.png)

Thanks for your help and hopefully `LE` will be updated soon.

**Comment by Snuffleupagus** [comment]
> I have tried adding the code `this.lineEnding = dict.getArray("LE")` [here](https://github.com/mozilla/pdf.js/blob/38c82357b247199b11fb573d0a3d4201347a47fc/src/core/annotation.js#L367-L375), and it does give me the endpoint style information I want.

That's not actually safe in general, since in a corrupt PDF document the `/LE`-entry could contain *any* data (e.g. something that's unclonable). Hence the data would *obviously* need to be properly validated, the exact format (from an API perspective) agreed upon, and finally the changes would also need to be unit-tested.

> Thanks for your help and hopefully `LE` will be updated soon.

Given that you've still not added an example PDF document, since "all PDFs" isn't helpful, the issue is still INCOMPLETE.
