### ISSUE TITLE
PDF.js not rendering image with text box overlay on mobile browser

### ISSUE THREAD

**Issue by toddcollinson** [mozilla/pdf.js#14897]
Attach (recommended) or Link to PDF file here: 
[Microsoft Lync Server 2010_test document.pdf](https://github.com/mozilla/pdf.js/files/8661072/Microsoft.Lync.Server.2010_test.document.pdf)
[Procurement category plan_Edinburgh University.pdf](https://github.com/mozilla/pdf.js/files/8661073/Procurement.category.plan_Edinburgh.University.pdf)
[Test document for PDF.js_root cause.pdf](https://github.com/mozilla/pdf.js/files/8661074/Test.document.for.PDF.js_root.cause.pdf)

When you attempt to view a PDF file that has images behind text boxes, these files render perfectly when using PDF.js via Chrome desktop browser.  If you attempt to view these files using Android mobile version of Chrome, the files will render but various image components will fail to render.  If you adjust the zoom level on the file, then some images will appear and previously rendering images will disappear.

The issue can be recreated from a document by creating an image and then adding a text box over the top of the image and then saving as a PDF.  These files all render correctly on desktop and also render correctly on other mobile chromium based browsers e.g. vivaldi or opera browsers.  The files also all render correctly when you view them through pdf.js using the Chrome browser on an Apple phone.

Configuration:
- Web browser and its version:
Android Chrome version 101.0.4951.41
Chrome for Apple version 101.0.4951.44
Firefox 100.1.1 (Build #2015877459)
Vivaldi Browser 5.2.2620.52
Opera browser 68.3.3557.64528

- Operating system and its version:
Samsung Android version 12 / baseband version G998BXXU4BVB1
Apple iPhone 

- PDF.js version:
Version 2.13.216
Online version of PDf.js modern browser viewed through Chrome

- Is a browser extension:
No

Steps to reproduce the problem:
1. Open the example documents on PDF.js modern browser version via an Android based mobile using Chrome browser
2. Compare the rendering of images that appear on mobile based chrome viewer versus desktop based viewer

What is the expected behavior? (add screenshot)

Files should render the same image and text as the desktop version of pdf.js when using the Chrome browser on mobile.  When you view the files using pdf.js and firefox browser, the image renders correctly.  Using alternative Chromium based browsers e.g. Vivaldi also renders the image correctly

![Screenshot_20220510-123329_Vivaldi Browser](https://user-images.githubusercontent.com/48798517/167629699-aea62ae7-8bd7-4f9b-b612-140942051057.jpg)

![Screenshot_20220510-143937_Opera](https://user-images.githubusercontent.com/48798517/167642407-63fa8d51-37a9-4c6c-a5bb-a6aeb76fc4dc.jpg)

![Screenshot_20220510-123454_Firefox](https://user-images.githubusercontent.com/48798517/167620788-4a50fc6c-d399-4ea9-a327-a153f81f9916.jpg)

What went wrong? (add screenshot)

When the files are displayed, various image or text components are not rendered.  If you zoom in and out on the display, various aspects of the image will appear while some images or text will no longer render.

![Screenshot_20220510-132606_Chrome](https://user-images.githubusercontent.com/48798517/167630180-cec589ac-a59b-4d5a-b5b4-d0e74120fb55.jpg)

With the procurement plan document, you can see the first page of the PDF is not displayed at all and second page does not display

![Screenshot_20220510-144208_Chrome](https://user-images.githubusercontent.com/48798517/167644303-8af34a09-6ac9-4e3c-bda5-d4de7e4ffcff.jpg)

![Screenshot_20220510-132855_Chrome](https://user-images.githubusercontent.com/48798517/167630177-6d59c5fa-e32e-4687-aef3-5f28e52f083d.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by toddcollinson** [comment]
Hi @Snuffleupagus, thanks for your response.  

In order to try and eliminate the root cause as a browser / specific issue versus PDF.js related issue, I used a number of different Chromium based browsers.  If it was a browser based issue then you would expect all Chromium based browsers to fail.

Testing on Android mobile using Brave 1.38.109 / Chromium 101.0.4951.41 displays all three test files perfectly
Testing on Android mobile using Vivaldi 5.2.2620.52: all three test files pass
Testing on Android mobile using Opera 68.3.3557.64528: all three test files pass
Testing on iOS mobile using Chrome 101.0.4951.44 all three test files display correctly 

Testing on Android mobile using Chrome 101.0.4951.41 all three test files fail

Also the type of document where the mobile rendering failure occurs is very specific - text box overlays with an image background.  

So if you run PDF.js on Android with multiple Chromium based browsers it displays all three files correctly.  If you use PDF.js on iOS mobile using chrome it works fine, but use PDF.js on Android using the same Chromium version, the files do not render correctly.  

I don't think this is a general PDF.js bug, as you rightly point out, it should not display correctly on other Chromium based browsers.  But I also don't think we can exclude a PDF.js issue as a potential cause of the rendering issue.

Is there any diagnostic that can be run to compare rendering output from Android chrome PDF.js versus one of the other Chromium based browsers?

Any suggestions regarding potential ways to identify the root cause of this issue Jonas would be much appreciated.

Thanks and regards

Todd

**Comment by Snuffleupagus** [comment]
Given that all rendering in PDF.js is done on `<canvas>` elements, these problems could *maybe* be connected to hardware acceleration of canvases. Hence you may want to check if that's being used, and if so try to switch it off (assuming doing so is possible in mobile Chromium).[1]

> If you adjust the zoom level on the file, then some images will appear and previously rendering images will disappear.

This also suggests that an *intermittent* problem, which makes debugging more difficult and (at least to me) further suggests a platform/browser issue.

---
[1] At least in a *desktop* Chromium browser, entering `chrome://flags/` and searching for canvas brings up such options.

**Comment by toddcollinson** [comment]
Thanks @Snuffleupagus

On mobile, when I disable the Accelerated 2D canvas, all the test files render correctly.  On desktop, this function is enabled and displays the test files correctly, but switching it off does not appear to impact rendering 

Is there a way that we can programmatically configure PDF.js to not use accelerated GPU processing of the canvas?

**Comment by Snuffleupagus** [comment]
> On mobile, when I disable the Accelerated 2D canvas, all the test files render correctly.

Interesting; that confirms my suspicion about this being a browser-specific bug.

> Is there a way that we can programmatically configure PDF.js to not use accelerated GPU processing of the canvas?

Not that I know of, since it's a *browser* setting that a web-page thus cannot directly control.

Hence, as far as I'm concerned, the only way forward here is to report this to the Chromium bug-tracker as a problem related to hardware accelerated `<canvas>` in Android.

**Comment by tstibbs** [comment]
Can this be added to the FAQ or similar, at least to prevent duplicate reports (e.g. #14709)?

Is there any way of PDF.js _detecting_ if hardware acceleration is enabled, even if it can't directly control it? Or even simply detecting that the PDF is being rendered incorrectly? Seems like any webapp which uses this library is basically going to be useless on platforms with this issue, so anything that could be done to detect the problem would help because then users could be given advice as appropriate.

**Comment by blacksmiths-aali** [comment]
Hi @tstibbs,

Kindly note I have been testing this issue this afternoon. I believe the problem gets worse in pdf.js release version 2.5.207. In this version, I get malformed (as you say, useless) PDF viewing results almost all of the time.

In pdf.js release 2.4.456, the problem is much, much more intermittent - my testing shows a failure rate of about 1 in 15. We're considering downgrading until this is fixed.

I intend to raise an issue report with Chromium.

**Comment by reyjexter** [comment]
We are still using older PDF.js version 2.1.266 which the issue also occurred beginning Android 13 on Chrome 106.x.

Testing Android 10 Chrome 106.x and Samsung Browser 18.0.4.x, it still works correctly.

**Comment by tstibbs** [comment]
For anyone coming to this thread looking for a workaround (for their own device at least), visit `chrome://flags/` and disable `Accelerated 2D canvas` (at least that works for me in Chrome on a Galaxy S21). The problem is that if you're embedding PDF.js in your website, all your users will have to disable acceleration.

Note that PDF.js is not the only library affected by this - leaflet.js has the same problem. So, while I agree the PDF.js maintainers do seem remarkably/surprisingly relaxed about this issue, it isn't really a PDF.js issue.

**Comment by florian-jobrad** [comment]
If anybody is interested in another workaround that I found that can be done via code:
If the "willReadFrequently" flag of the 2d canvas context is set to "true", then this will force the use of a software (instead of hardware accelerated) 2d canvas. Using this the rendering issues on an android chrome browser were gone for me.
