### ISSUE TITLE
[Feature Request] PDF edit & highlighting text and built-in dictionary feature

### ISSUE THREAD

**Issue by rayshabh** [mozilla/pdf.js#14924]
I use Firefox as my default browser, but sometimes I need to switch to Microsoft Edge for editing and highlight PDF documents.
I know there are Free PDF applications that can serve the purpose, but I really don't want to install any external applications to perform such basic task.

Hence, I would very much appreciate if the developers introduce PDF editing and highlighting text feature in the **pdf.js** too.

Also, would love to see a **built-in dictionary** option.

**Comment by Snuffleupagus** [comment]
> Hence, I would very much appreciate if the developers introduce PDF editing and highlighting text feature in the **pdf.js** too.

Please note e.g. https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, which is the *current* state of things here.

> Also, would love to see a **built-in dictionary** option.

It's not really clear what this even means. (However, note that e.g. including a translation dictionary with the PDF.js library isn't going to happen since it's too much of an edge-case *and* would take up too much space.)
