### ISSUE TITLE
Some IPhont  cant show the PDF file

### ISSUE THREAD

**Issue by WuXudong0001** [mozilla/pdf.js#14934]
I find a strange problem when I test pdf.js in my program.
When I use IPhoneXR( IOS13.6 ) and 6PLS  (IOS14.8.1）,my PDF file is not showed.
The page is showing a lot of div .It seems like a original configuration page.
![pic](https://user-images.githubusercontent.com/105836072/169201036-4804b116-3d04-4cd2-bbed-beca42671ac1.png)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.

Also, for older browsers/platforms you'll need to use a `legacy`-build of the PDF.js library; note the two different builds provided at https://mozilla.github.io/pdf.js/getting_started/#download
