### ISSUE TITLE
How to import image and signature in pdf viewer

### ISSUE THREAD

**Issue by Tsroma** [mozilla/pdf.js#14949]
1. Importing images in pdf viewer.
2. Making signature function into pdf viewer.

**Comment by Snuffleupagus** [comment]
Note e.g. https://github.com/mozilla/pdf.js#pdfjs- and https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations, meaning that what you ask about isn't intended/supported.

Furthermore, when opening an issue please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this isn't really actionable/valid.
