### ISSUE TITLE
Cmaps error

### ISSUE THREAD

**Issue by vzaragoza** [mozilla/pdf.js#14996]
Attach (recommended) or Link to PDF file here:
Can not attach PDF due to client privacy.

Configuration:
- Web browser and its version: Chrome 102.0.5005.63
- Operating system and its version: Windows 10 
- PDF.js version: 2.10.377 to 2.14.305
- Is a browser extension: No

Steps to reproduce the problem:
1. Load a PDF that uses cmaps
2. Scroll or change the PDF page to the one with cmaps
3. Page does not load the text

What is the expected behavior? 
We expect to see the text of all the pages.

What went wrong? (add screenshot)
I checked the console to see if something was wrong and this is what I get:
![image](https://user-images.githubusercontent.com/69236726/172136435-3daed23b-a488-4030-b30c-b17251a1083b.png)
With this warning the pages using cmaps do not load the text.

I'm using pdfjs-dist for a React project with webpack.
Somehow, cmaps were working fine with the 2.9.359 version (and prior versions).

This is the code I'm using:
```typescript
import * as pdfjs from 'pdfjs-dist';

pdfjs.GlobalWorkerOptions.workerSrc = `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/build/pdf.worker.js`;

...

const loadingTask = pdfjs.getDocument({
          data: await getAsByteArray(src),
          cMapPacked: true,
          cMapUrl: `//cdn.jsdelivr.net/npm/pdfjs-dist@${pdfjs.version}/cmaps/`
        });
const doc = await loadingTask.promise;

...
``` 

This same code was working fine with 2.9.359 and prior versions.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> Can not attach PDF due to client privacy.

That's a problem (in general), since it means that it's *impossible* for anyone else to actually reproduce this.

> What went wrong? (add screenshot)
> I checked the console to see if something was wrong and this is what I get:

*For future reference:* Please always include error messages as *text*, rather than images, since that's much easier to work with.

Note that the `cMapUrl` that you've provided doesn't look like a *valid* absolute URL, which likely is part of the problem here.
However, assuming that part of the problem is that we're now (by default) using the Fetch API in a worker-thread you can actually disable that manually.

Please try adding `useWorkerFetch: false,` to your `getDocument`-call, see also https://github.com/mozilla/pdf.js/blob/135b9fbcfb2e2554754082d482341b4cbe9e1b43/src/display/api.js#L171-L174

> This is the code I'm using:
> [...]

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
