### ISSUE TITLE
No need to redraw the canvas on rotation

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15037]
As far as I can tell it seems useless and we could just rotate the canvas element itself and the text layer too.

**Comment by Snuffleupagus** [comment]
Initially I figured that we could simply use the `cssTransform` in these cases, however having looked into this a little bit my conclusion is that we can/should close this as WONTFIX for the following reasons:

 - For the "named" zoom-values, i.e. "auto"/"page-fit"/"page-width", we generally need to re-render anyway since rotation will (almost) always result in updating the *effective* zoom-value. Please keep in mind that there's *no additional* rendering occurring in this case, since we: first rotate the document, secondly update the scale, and then finally trigger rendering *just once*.
 
 - For the "numerical" zoom-values, we could potentially avoid re-rendering. However, it turns out that if we *only use CSS* to rotate the `canvas` it will look *slightly blurry* for some zoom-values. This doesn't always happen, since it seems that different PDF documents have trouble with different "numerical" zoom-values. Hence it seems, as far as I can tell, that also in these cases we need to re-render the document on rotation to ensure good quality.
