### ISSUE TITLE
How to specify a different number of pages to load dynamically? Or disable the feature temporarily for dev reasons?

### ISSUE THREAD

**Issue by Whoeza** [mozilla/pdf.js#15045]
Attach (recommended) or Link to PDF file here: private PDF with tabular data on it

Configuration:
- Web browser and its version: Firefox latest version
- Operating system and its version: Windows 10
- PDF.js version: built-in PDF viewer of Firefox latest version
- Is a browser extension: nope

Steps to reproduce the problem:
1. load a big PDF document
2. when you scroll the pages, old pages get unloaded dynamically

What is the expected behavior? Pages unload dynamically indeed.

What went wrong?
I was "playing" around with a PDF on my PC, and I found it annoying that Firefox's PDF viewer loads and unloads pages if you scroll many pages away. I was grabbing the tabular data on the pages, spanning 11-12 pages, and I could not get all the data and lost all day, until I noticed the "data-loaded=true" in the source, being set and removed when scrolling up and down the PDF. I'm new to JavaScript, I'm just learning. I even tried disabling the JS lines with the Debugger in the developer tools (F12), but the source is read-only. Anyone has any idea, tips or suggestions?

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages which explains why this is done, since overall performance would suffer considerably if we didn't unload old pages.

The easiest way to work-around that limitation temporarily could be to e.g. zoom out the document and/or change to a Scroll/Spread-mode where multiple pages are visible at the same time (since visible pages will always be kept alive in the cache).

Other than that, you'd have to [modify the source-code](https://github.com/mozilla/pdf.js/blob/89cebcb6f9b757583bc855bf0ddbde857ed6308b/web/base_viewer.js#L79) to increase the minimum cache-size; however we really don't recommend doing that in general as outlined in the FAQ.
