### ISSUE TITLE
Feature to save annotations in JSON format following the Web Annotation Data Model

### ISSUE THREAD

**Issue by jaime-rivas** [mozilla/pdf.js#15055]
Hi everyone,

@marco-c @calixteman @Snuffleupagus it's absolutely fantastic that you are adding editing capabilities to pdf.js to bring full annotation support, big thank you!

Giving this current effort, I wanted to suggest a related capability that might be very useful and hopefully achievable at the same time. In addition to supporting saving annotations in the native PDF annotation format inside the PDF, it would be great to have the option to save annotations outside the PDF in JSON format following the [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/). 

This will allow annotation libraries like [Apache Annotator](https://annotator.apache.org/) to externally load those annotations, enable collaborative annotations scenarios, etc. using the W3C’s standard Web Annotation data model. Related issue here: [Fragment selector for PDFs + PDF.js integration](https://github.com/apache/incubator-annotator/issues/125)

Thank you again!

**Comment by Snuffleupagus** [comment]
> [...] that you are adding editing capabilities to pdf.js to bring full annotation support

I don't believe it's going to be "full" editing support, given the sheer number of Annotation-types that the PDF specification support, but most likely rather a few commonly used types.

> [...] it would be great to have the option to save annotations outside the PDF in JSON format following the [Web Annotation Data Model](https://www.w3.org/TR/annotation-model/).

It sounds like that could very well require a fair amount of code, for a use-case that's potentially not entirely relevant for the Firefox *built-in* PDF Viewer. (Without having really looked at the linked specification...)

However, note that you're already able to access *modified* Annotation-data through the PDF.js API (but please keep in mind that *editing* is still unfinished/unreleased); refer to:
 - The `AnnotationStorage`-implementation in https://github.com/mozilla/pdf.js/blob/master/src/display/annotation_storage.js
 - Accessing the `AnnotationStorage`-instance, for the current PDF document, in https://github.com/mozilla/pdf.js/blob/b9f5a70dede81bd75a6381b0fcba50b5f4e7cf9d/src/display/api.js#L724-L729

Hence it'd likely be possible to implement the JSON-exporting you mention *outside* of the PDF.js library as well, since as outlined above it's possible to access the "raw" data for *modified* Annotations.

**Comment by jaime-rivas** [comment]
Thank you @Snuffleupagus!

We will work on an external library to access `AnnotationStorage` and exporting the annotations. We will keep this issue updated when we make progress.

**Comment by LibertyNLP** [comment]
Hi , I wish my work can help you.
I have figured out a solution of pdf.js annotation, use only pdf.js dist, and it is very easy to import into your project.

Demo and source code: https://demos.libertynlp.com/#/pdfjs-annotation
Demo video:https://www.youtube.com/watch?v=IYD7WKzx-yc&t=3s

functions:
① highlight : highlight selected text;
② underline : underline selected text;
③ edit: edit annotation ( copy/delete/add comment/navigate );
④ output annotations : output annotations for importing;
⑤ import annotations : import annotations for current file;
⑥ download annotations : download annotations and comments text;
⑦ undo annotations : undo annotations in current page;
⑧ help : open help file;

**Comment by Snuffleupagus** [comment]
Let's close this as WONTFIX for now, for the reasons outlined in https://github.com/mozilla/pdf.js/issues/15055#issuecomment-1158936493.
