### ISSUE TITLE
New ui/ux in pdf.js

### ISSUE THREAD

**Issue by raphael-louis-andress** [mozilla/pdf.js#15067]
Attach (recommended) or Link to PDF file here:
None.

Configuration:
- Web browser and its version: Mozilla Firefox 101.0.1 (64-bits).
- Operating system and its version: Windows 10 64 bits.
- PDF.js version: I don't have this information.
- Is a browser extension: I don't have this information.

Steps to reproduce the problem:
1. The toolbar is centered in the middle
2. Users access the centralized toolbar when reading the pdf text

What is the expected behavior? (add screenshot)

#### img 1: concept
![image](https://user-images.githubusercontent.com/95204402/174536875-2f51fe87-23e4-4449-8fc1-5f1858b85113.png)

#### img 2: ui/ux
![image](https://user-images.githubusercontent.com/95204402/174537189-cc6b90b7-a2b7-4c13-bd41-c5d23859c7f3.png)

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/95204402/174537896-b9e6c979-803d-4cf9-b73f-e9203f587395.png)

Notes:
1. Maybe this will improve the Mozilla Firefox PDF reader interface and help in better reading experience for the user too

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
- https://codepen.io/milanraring/pen/qBEPzKB
- https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX, since I don't believe that we want to make this sort of change. For example:
 - This kind of toolbar would *obscure* part of the document, which seems unfortunate (even worse when e.g. the findbar/secondary-toolbar is used).
 - It takes up much more *vertical* space than the current toolbar.
 - The width of the toolbar would change, based on both available features and the locale of the UI.
