### ISSUE TITLE
I meet an error in the newest version when I install pdfjs-dist in my angular project

### ISSUE THREAD

**Issue by zhuangYuFeiHelloGit** [mozilla/pdf.js#15078]
I meet an error in the newest version when I install pdfjs-dist in my angular project.

![package](https://user-images.githubusercontent.com/17961466/174967796-ecd9df4c-d2d4-4fbe-8cd9-0ad9594b6e72.png)

![error](https://user-images.githubusercontent.com/17961466/174967817-5c2c4a33-3ab2-48c2-9be3-f9debe44ddb5.png)

I don't know what I can do to resolve it.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this isn't really actionable.

Also, please include configuration information and error message *as text* (rather than images).

---

I'd suggest carefully reading https://github.com/mozilla/pdfjs-dist/blob/master/README.md, since the following paragraph might explain your issue:
> For usage with older browsers or environments, without support for modern features such as `async`/`await`, optional chaining, nullish coalescing, and private `class` fields/methods; please see the `legacy/` folder.
