### ISSUE TITLE
Feature request: Detect if page has loaded via the api

### ISSUE THREAD

**Issue by dancingshell** [mozilla/pdf.js#15077]
It would be great to detect if a page has loaded in (if loaded a document using range requests). Using `getPage` makes the network request. Use case: we have another panel where we are loading in the text layer and I only want to load the text layer for a page if that page has already been loaded so we don't interrupt the normal load/request order.

Request:

```js
if (document.pageIsReady(5)) { // no network request, just check if chunk is already loaded in
  const page = document.getPage(5); // this now shouldn't kick off a network request because the page is loaded
  // get text layer
}

**Comment by dancingshell** [comment]
@reckart thanks for the response. Do you know if there is any way to listen for that or similar events if we are not using the pdfjs viewer? I would guess not since we render our own pages. What I really am looking for is page loaded, not page rendered. We only render the pages that are in view to the user. In a 300 page document, page 299 might get dowloaded but not rendered since we only show the user a few pages at a time.

**Comment by dancingshell** [comment]
As we aren't really interested in the rendering part of that it might not be so helpful.

I'm looking for the api to expose either an event letting us know the page has downloaded, or a method to check if a page has downloaded.

option 1:
```js
const loadingTask = pdfjs.getDocument({
  url: 'example.pdf',
});
loadingTask.onPageLoadComplete = (progress) => {
  console.log('progress') // { pageNumber: 7 }
};
```

option 2
```js
if (document.pageIsReady(5)) { // no network request, just check if chunk is already loaded in
  const page = document.getPage(5); // this now shouldn't kick off a network request because the page is loaded
  // get text layer
}
```

**Comment by Snuffleupagus** [comment]
> It would be great to detect if a page has loaded in (if loaded a document using range requests). Using `getPage` makes the network request.

It's not completely clear, at least to me, *exactly* what you mean by "if a page has loaded in" here.

Because if you want to know whether, or not, you've previously loaded a specific page (by calling `PDFDocumentProxy.getPage` in the API), you could probably (quite easily) keep track of that directly in your own code.
However, if what you actually mean is whether or not the byte-range(s) corresponding to a particular page has been loaded, then that'd be *much more* involved to try and support. Hence that's unfortunately not really something that I think makes sense for the general PDF.js library, given that the use-case seems somewhat specialized.

**Comment by Snuffleupagus** [comment]
Closing for now, please see https://github.com/mozilla/pdf.js/issues/15077#issuecomment-1162272811.

**Comment by chitgoks** [comment]
reckart: `window.PDFViewerApplication.eventBus.on('pagerendered', ...);`

i actually do it like this as well when listening for this particular event. in the latest versions (im not sure when it started, maybe v3), when the viewer is zoomed in and out, i cant figure out why the pagerendered is called twice per page?

so if i am in page 1, when i click the zoom button, pagerendered is called twice for pages 1 and 2.

rotating is ok since the pages are just rotated so the pagerendered event is called only once.
