### ISSUE TITLE
Unable to preview on Android phone

### ISSUE THREAD

**Issue by szzhou** [mozilla/pdf.js#15070]
![Screenshot_20220620_161302_com tencent wework](https://user-images.githubusercontent.com/30004009/174556313-05d2cddc-8818-4e11-bf4d-20ebbf817405.jpg)

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately contains no actionable information.

---

The only possible suggestion would be to use a `legacy/`-build, see https://github.com/mozilla/pdf.js#online-demo

**Comment by szzhou** [comment]
https://mozilla.github.io/pdf.js/web/viewer.html 
URL above  Unable to preview on Android phone
