### ISSUE TITLE
Android WebView and pdf.js Versions

### ISSUE THREAD

**Issue by scientificware** [mozilla/pdf.js#15087]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: WebView 102.0.5005.125 ( Released on 13 june 2022 )
- Operating system and its version: Android 10
- PDF.js version: 2.9.359 to 2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.
pdf.js Version|Legacy|PDF displayed|Error Message|Work around
--|--|--|--|--
2.9.359 Prebuilt||:heavy_check_mark:|:warning:|
2.10.377 Prebuilt||:heavy_check_mark:|:warning:|
2.11.338 Prebuilt||:x:|Uncaught SyntaxError|
2.12.313 Prebuilt||:x:|Uncaught SyntaxError|
2.13.216 Prebuilt||:x:|Uncaught SyntaxError|
2.14.305 Prebuilt||:x:|Uncaught SyntaxError| switch to 2.14.305 Prebuilt Legacy 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

2.14.305 :
```
I/chromium: [INFO:CONSOLE(1753)] "Uncaught SyntaxError: Unexpected token '='", source: file:///android_asset/js/moz_pdfjs/build/pdf.js (1753)
I/chromium: [INFO:CONSOLE(1561)] "Uncaught SyntaxError: Unexpected token '='", source: file:///android_asset/js/moz_pdfjs/web/viewer.js (1561)
```
```
2.14.305 Legacy :
I/chromium: [INFO:CONSOLE(665)] "_readPreferences: "Cannot read property 'getItem' of null".", source: file:///android_asset/js/moz_pdfjs/web/viewer.js (665)
I/chromium: [INFO:CONSOLE(2101)] "PDF 36e9d6a8dec85dbda59b93a5ad1dcb1d [1.3 ESP Ghostscript 815.03 / -] (PDF.js: 2.14.305)", source: file:///android_asset/js/moz_pdfjs/web/viewer.js (2101)
```

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.9.359 to 2.14.305

Please note that anything *except* version `2.14.305` is explicitly unsupported now.

Furthermore, please note that we don't specifically support "Android WebView" and that the official support information can be at https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> switch to 2.14.305 Prebuilt Legacy

As mentioned in the Wiki-entry referenced above, for anything except the *very latest* browsers you'll thus need to use a `legacy/`-build of the PDF.js library in order for things to work.

> ```
> 2.14.305 Legacy :
> I/chromium: [INFO:CONSOLE(665)] "_readPreferences: "Cannot read property 'getItem' of null".", source: file:///android_asset/js/moz_pdfjs/web/viewer.js (665)
> I/chromium: [INFO:CONSOLE(2101)] "PDF 36e9d6a8dec85dbda59b93a5ad1dcb1d [1.3 ESP Ghostscript 815.03 / -] (PDF.js: 2.14.305)", source: file:///android_asset/js/moz_pdfjs/web/viewer.js (2101)
> ```

Those messages seem to suggest that the viewer actually loads correctly, with only a warning message logged because `localStorage` apparently isn't available.
