### ISSUE TITLE
pdf.js and web/viewer.js pass/open url outside webroot

### ISSUE THREAD

**Issue by alexla** [mozilla/pdf.js#15090]
I am experimenting with the pdf.js examples, and in particular the viewer.html/viewer.js. I am trying to access a URL outside of the webroot. My PHP installation has access to a specific folder outside where I store pdf files. In PHP I stream these files to the browser for download, which works fine. However, I would like to also stream the file to the viewer directly. Is that possible?

So, for example, my URL would be /web/viewer.html?file=/12345.pdf for a file that is accessible to the web browser.
However, if I want to stream this from outside the root, the URL may look like this: /web/viewer.html?file=fetch.php?id=12345

Any idea how I should go about this, as the viewer seems to fetch the filename directly. I also want to make sure that the URL remains obscured, so probably encoding the pdf (multiple pages) would presumably also not work.

Thanks

**Comment by Snuffleupagus** [comment]
> My PHP installation has access to a specific folder outside where I store pdf files.

Unfortunately we cannot really provide PHP-specific help/support here, since this is a JavaScript project after all.

> However, if I want to stream this from outside the root, the URL may look like this: /web/viewer.html?file=fetch.php?id=12345

That'd most likely require modification of the viewer source-code, since nothing like that is (or will be) supported here; please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---

Also, when opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that the issue becomes easily actionable.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
