### ISSUE TITLE
Scrolling view add two pages in one screen

### ISSUE THREAD

**Issue by lifechat** [mozilla/pdf.js#15091]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. Scrolling view, can I add two pages in one screen? Slide to turn pages

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is missing too much information to be easily actionable/understandable (e.g. the `Configuration:`-section is completely blank).

> Steps to reproduce the problem:
>     1. Scrolling view, can I add two pages in one screen? Slide to turn pages

It's impossible to tell, given the lack of details here, if your question is regarding the API itself or the viewer.
However, the default viewer does support a number of different Scroll/Spread-modes; see https://github.com/mozilla/pdf.js#online-demo

**Comment by lifechat** [comment]
when choose the Wrapped scrolling,spreads mode can't choose and show me two pages in Screen.

At 2022-06-24 18:20:12, "Jonas Jenwald" ***@***.***> wrote:

When opening an issue, please provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is missing too much information to be easily actionable/understandable (e.g. the Configuration:-section is completely blank).

Steps to reproduce the problem:
1. Scrolling view, can I add two pages in one screen? Slide to turn pages

It's impossible to tell, given the lack of details here, if your question is regarding the API itself or the viewer.
However, the default viewer does support a number of different Scroll/Spread-modes; see https://github.com/mozilla/pdf.js#online-demo
