### ISSUE TITLE
Don't recompute the text layer when zooming

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15131]
When zooming, the text layer is uselessly recreated and `evaluator.js::getTextContent` can be called.
If I'm correct we should be able to have a "constant" text layer as we have for the annotation layer thanks to percent unit, `var(--scale-factor)` and a rotation matrix.
It should simplify the code, maybe improve performance when zooming (even if it isn't really a bottleneck) and clearly slightly decrease the resource use.
@Snuffleupagus, do you see any drawbacks or "details" I could have overlooked which would avoid us to do such a simplification ?

**Comment by Snuffleupagus** [comment]
We already have code to do that, however it's currently only being used with CSS-zooming.[1] Hence that means that the code isn't really well-tested, since it's mostly unused, and there could potentially be cases it doesn't handle very well.[2]

Unfortunately there's not really a good way to test this, except *manually* in the viewer (with lots of different documents), and my worry is that we could easily break some edge-cases given how old all of this code is.

---
[1] Assuming it actually works, that code could perhaps be extracted/extended and then re-used generally for the textLayer.

[2] For example, what about text at non-multiple of 90 degrees.

**Comment by calixteman** [comment]
I noticed that the `aria-owns` I added are disappearing on zooming, hence it means that everything must be rebuild every time the zoom level is changing.
If a span or a set of spans have a rotation (whatever the angle is): it's fine, we can have a local transform as the one we've for annotations.
But the global rotation (page rotation) should be applied on the text layer itself (like for annotation).
I'll update my a11y patch to take into account this situation but I think we should do something to improve this.

I think we've a way to set the zoom level in tests, so maybe before starting anything we could just add some tests with different zoom levels and in displaying the text layer in order to avoid any future regression. Wdyt ?

**Comment by Snuffleupagus** [comment]
> I think we've a way to set the zoom level in tests, so maybe before starting anything we could just add some tests with different zoom levels and in displaying the text layer in order to avoid any future regression. Wdyt ?

I don't think that'd actually test the thing you'd want here, which is what happens *on zooming* in the viewer.[1]
Note how the `browsertest`s simply render at an initial scale, but doesn't actually change the scale in any way similar to what happens in the viewer.[2]
And in any case, I don't think it'd be possible to add anywhere nearly enough test-coverage upfront; you'd basically have to accept dealing with potential regressions...

---
[1] Also, the `browsertest`s only support "HiDPI simulation" but not really proper zoom levels (as far as I recall).

[2] Trying to shoehorn that sort of functionality into the `browsertest`s might not be pretty...
