### ISSUE TITLE
Calling getData() on XFA PDF does not persist changes made to allXfaHtml

### ISSUE THREAD

**Issue by ozziexsh** [mozilla/pdf.js#15148]
Attach (recommended) or Link to PDF file here:

https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5707e.pdf

Hello! First off, this library is incredible and has saved our team so much time already, thanks a ton!

We have the above XFA PDF that contains form inputs. We are trying to fill in data into the form inputs and then re-save the PDF but we are not sure how. We have managed to load the PDF and extract the XFA data using the following

```javascript
const pdf = await pdfjsLib.getDocument({
  url: 'https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5707e.pdf',
  enableXfa: true,
}).promise;

// json tree of XFA data
const xfa = pdf.allXfaHtml;
```

We were then able to find the node that holds one of the form inputs by searching the tree and updating the nested form inputs `textContent` property:

```javascript
// not the real path but something like it
xfa.children[0].children[1].children[0].attributes.textContent = 'Ozzie';
```

Eventually after filling out the data we figured we'd just be able to do the following to re-save the PDF using something like:

```javascript
new Blob([await pdf.getData()], { type: 'application/pdf' })
```

While this does save the PDF, it only produces the original PDF we loaded, not one with the modified form values. We also tried `pdf.saveDocument()` but this appears to be for acro forms only.

We've spent a few hours diving through the source code of this library and Firefox but we can't seem to figure it out. It looked like maybe this `allXfaHtml` property was just an initial read and not meant to be written to. Is there a different API to modify the XFA data? This must be possible to do as Firefox can edit these pdfs

Thanks in advance!

**Comment by Snuffleupagus** [comment]
The `PDFDocumentProxy.getData`-method will only ever return the *original* PDF document, and nothing else. In order to save a modified form, be it a "normal" AcroForm or a XFA-form, you need to use the `PDFDocumentProxy.saveDocument`-method.

> We were then able to find the node that holds one of the form inputs by searching the tree and updating the nested form inputs `textContent` property:

That's neither intended or supported unfortunately, since that'd basically mean having to implement *arbitrary* PDF-creation in the PDF.js library which isn't what it's intended to do.
What we do support, is saving or printing of filled in form-data. However, you cannot manually (or programmatically) modify the DOM and expect those changes to be saved.

In order to change the contents of a form, in such a way that `PDFDocumentProxy.saveDocument` will take it into account, please see
 - https://github.com/mozilla/pdf.js/blob/2b6a67c5d05cc4ec2f686eb0ac486ae0dd9285f0/src/display/api.js#L727-L732
 - https://github.com/mozilla/pdf.js/blob/2b6a67c5d05cc4ec2f686eb0ac486ae0dd9285f0/src/display/annotation_storage.js#L78-L103

If the above isn't sufficient for you to fix your issue, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by ozziexsh** [comment]
Thanks for the info!

I realized our mistake was that when we tried using the annotation storage earlier like this:

```js
pdf.annotationStorage.setValue(key, '1234');
```

where we should have been using it like this

```js
pdf.annotationStorage.setValue(key, { value: '1234' });
```

**Comment by Lakhtar-kays** [comment]
Hi @ozziexsh @Snuffleupagus 

Greeting of the day!! I am facing a typical challenge with XFA forms, nearly close to what you shared. 

IRCC XFA Ref: **https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257b_1.pdf**  

In this XFA form, the **fieldid and dataid** values are duplicates for multiple controls. E.g. <familyname>  

For example:  

{ 
        "name": "textarea", 
        "attributes": { 
            "dataId": "**field284442**", 
            "fieldId": "**field284442**", 
            "class": [ 
                "xfaTextfield" 
           ], 
            "aria-label": "Question 1 Family name as shown on your passport or travel document", 
            "aria-required": true, 
            "required": true, 
            "tabindex": 5002, 
            "maxLength": 100 
        } 
    } 
] 

  

https://prnt.sc/Mxel9q-YRrUE 

https://prnt.sc/KQse9WsR_3Y8 


Issue: If I want to update the <**field284442**> with value {john}, the code does not work due to duplicate id. 

pdf.annotationStorage.setValue('field284342', { value: 'John' }); 

Could you help me with: 
1. If there is we can avoid the duplicates; and update the text control to set value?  
2. is there any way so that we can traverse to that particular child node and set value? 

Any sample code, link to a solution or inputs are highly appreciated.  

Thanks in advance.

**Comment by gregorysouzasilva** [comment]
@ozziexsh Hey. Did you make it work? do you have a complete example? tks

**Comment by gregorysouzasilva** [comment]
@Lakhtar-kays Hi. Did you have any success on making the filling and saving of the pdf?

**Comment by jakekreider** [comment]
@gregorysouzasilva I'm late to the party here, but what I was stuck on is that `pdf.saveDocument()` is what returns the bytes (Promise) from the modified form, after you've used `pdf.annotationStorage.setValue(fieldId, { value: 'blah' });` as noted above. So the blob above would be `new Blob([await pdf.saveDocument()], { type: 'application/pdf' })`
