### ISSUE TITLE
Issues using PDFjs v2.14.305 with Bluebird

### ISSUE THREAD

**Issue by karelee7** [mozilla/pdf.js#15167]
When using PDFjs v2.14.305 with Bluebird, I run into the following error message:

<img width="1552" alt="Screen Shot 2022-07-14 at 1 35 52 PM" src="https://user-images.githubusercontent.com/95440409/179078538-c41f8a56-6d81-4095-af82-aae9976a5e84.png">

Here's the stack trace with the non minified files:
<img width="1559" alt="Screen Shot 2022-07-14 at 8 39 24 PM" src="https://user-images.githubusercontent.com/95440409/179145592-eba89879-fe45-4e5e-9732-769ebf9053eb.png">

Configuration:
- Web browser and its version: Chrome Version 103.0.5060.114 (also happening on Firefox and Safari)
- Operating system and its version: macOSMonterey v12.4
- PDF.js version: 2.14.305

Has anyone seen this happen before? And are there any suggestions on a possible solution that could make Bluebird work with this version of PDFjs? It seems like there are no problems with Bluebird in v2.2.228 of pdfjs which is interesting..

**Comment by Snuffleupagus** [comment]
The PDF.js library is written using *native* Promises, which all reasonably modern browsers/environments should have been supporting for years now; see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise#browser_compatibility and note that [all browsers that we support](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support) thus have *native* Promise-implementations.

Hence we unfortunately don't/can't provide support for using *custom* Promise-libraries together with the PDF.js library, and generally we'd suggest simply using *native* Promises instead to avoid any problems.

*For future reference:* Please note that this issue unfortunately isn't really actionable, since screen-shots of error aren't all that helpful when debugging things; hence see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by Snuffleupagus** [comment]
Also, according to https://www.npmjs.com/package/bluebird that library has apparently not been updated for almost *three* years.

Furthermore, there's also the following information which advises against using the Bluebird library (unless absolutely necessary): https://github.com/petkaantonov/bluebird#%EF%B8%8Fnote%EF%B8%8F
