### ISSUE TITLE
Select text with hand

### ISSUE THREAD

**Issue by tbertels** [mozilla/pdf.js#15177]
In Acrobat Reader and Foxit Reader, there's an option to allow the hand to select text.

It works this way: when the hand mouse pointer stays still over text, it turns to a text select mouse pointer. It then turns back to a hand if we move the mouse pointer over anything else.

This avoids having to switch back and forth between the hand and the text select tool.

This could be a third pointer choice, called "Combined tool" with an icon combining a hand and a text selection tool.

**Comment by Snuffleupagus** [comment]
> In Acrobat Reader and Foxit Reader, there's an option to allow the hand to select text.

That might depend on the exact version of Adobe Reader, or some setting in the program itself, since in the one I have installed locally it doesn't seem to work like that...

---

To me, this feature sounds like too much of an edge-case to warrant the additional complexity that would be required in order for this to work well; hence closing as WONTFIX.

**Comment by tbertels** [comment]
> > In Acrobat Reader and Foxit Reader, there's an option to allow the hand to select text.
> 
> That might depend on the exact version of Adobe Reader, or some setting in the program itself, since in the one I have installed locally it doesn't seem to work like that...

Yes, it seems broken in the current version of Adobe Reader, but it works fine in Foxit Reader.
