### ISSUE TITLE
Some fields in documents are being shown vertically

### ISSUE THREAD

**Issue by joanrotbard** [mozilla/pdf.js#15172]
Attach (recommended) or Link to PDF file here:

https://pdfhost.io/v/ZU3dTe8tK_Narcotics_Ventilator_Treatment_Cleaning

Configuration:
- Web browser and its version: Any
- Operating system and its version: Any
- PDF.js version: 1.1.1
- Is a browser extension:

Steps to reproduce the problem:
1. When uploading and processing the attached pdf (https://pdfhost.io/v/ZU3dTe8tK_Narcotics_Ventilator_Treatment_Cleaning) signature fields are not being transformed as expected ( see image below)
 
2. Added the code found in another issue https://github.com/mozilla/pdf.js/issues/9596 to solve it but it still not working for the signature fields

What is the expected behavior? (add screenshot)
https://postimg.cc/pmcsqTLM

What went wrong? (add screenshot)
https://postimg.cc/xNQkQf8s

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: 1.1.1

That version is no longer supported, since it's *over seven years old*; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Attach (recommended) or Link to PDF file here:
> https://pdfhost.io/v/ZU3dTe8tK_Narcotics_Ventilator_Treatment_Cleaning
> [...]
> What is the expected behavior? (add screenshot)
> https://postimg.cc/pmcsqTLM

*For future reference:* Please always *directly attach* the PDF document here.

Furthermore, your linked document does *not* actually agree with this screen-shot when opened e.g. with Adobe Reader or PDFium (in Google Chrome).
