### ISSUE TITLE
When dragging, the pdf display area is constantly flashing

### ISSUE THREAD

**Issue by Sylvenas** [mozilla/pdf.js#15198]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome@101.0.4951.64
- Operating system and its version: MacOS@12.3.1
- PDF.js version: 2.14.305
- Is a browser extension: no

Steps to reproduce the problem:

1.clone https://github.com/Sylvenas/pdf-viewer
2.npm install
3.npm start
4.click zoomIn button
5.drag the pdf viewer

What is the expected behavior? (add screenshot)
Can display pdf area smoothly and uninterruptedly

What went wrong? (add screenshot)
When dragging, the pdf display area is constantly flashing

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://github.com/Sylvenas/pdf-viewer

**After I debugged many times, I know why it flickers, because every time it redraws, pdfjs will delete the original canvas, and then recreate a new canvas, and there will be blanks in the middle of this.**

the Relation code:
https://github.com/Sylvenas/pdf-viewer/blob/master/src/pdf-viewer/helper/pdf-render.ts#L106
https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js#L315

So is there anything I can do to avoid the flicker problem?

**Comment by Snuffleupagus** [comment]
> After I debugged many times, I know why it flickers, because every time it redraws, pdfjs will delete the original canvas, and then recreate a new canvas, and there will be blanks in the middle of this.
>
> https://github.com/Sylvenas/pdf-viewer/blob/master/src/pdf-viewer/helper/pdf-render.ts#L106

In your code you're *explicitly* clearing out everything when redrawing. Hence it's not surprising that things don't work as you want. Also, your call of `PDFPageView.reset` is not correct, since it expects an Object rather than simple boolean arguments; see:
https://github.com/mozilla/pdf.js/blob/408c10b5bbd90381d152d0399588ad2fc62379d0/web/pdf_page_view.js#L282-L287

(So you'd need to call it as `reset({ keepZoomLayer: true });` instead, but see below.)

Hence, rather than manually calling `reset` and `draw`, it's recommended to instead use (which is what our viewer does):
https://github.com/mozilla/pdf.js/blob/408c10b5bbd90381d152d0399588ad2fc62379d0/web/pdf_page_view.js#L368

Furthermore, the way that you manually modify a `PageViewport`-instance is also not intended/supported unfortunately.

---

If you're trying to build a custom PDF viewer, please also see https://github.com/mozilla/pdf.js/tree/master/examples/components

**Comment by Sylvenas** [comment]
Thank you very much for your help!

I have solved the blinking problem by adding `zoomLayer` directly, but I think this belongs to the hack technique, is there any way to initialize `zoomLayer` automatically?
The result:     
https://github.com/Sylvenas/pdf-viewer/blob/master/src/pdf-viewer/helper/pdf-render.ts#L111


I noticed that `PDFJSViewer.PDFPageView` class can be added to initialize the `zoomLayer` parameters, but in the later code is not used, so there are other methods?
 https://github.com/mozilla/pdf.js/blob/408c10b5bbd90381d152d0399588ad2fc62379d0/web/pdf_page_view.js#L157

**Comment by Snuffleupagus** [comment]
Generally speaking you'll be much better off using the `BaseViewer`, rather than using `PDFPageView` directly, since that one contains lots of functionality that'll simplify things. Otherwise, you'll basically end up having re-implement a lot of viewer functionality (which as you've seen isn't always easy or straightforward).

Please refer to https://github.com/mozilla/pdf.js/tree/master/examples/components and specifically:
 - The `simpleviewer` example, which shows how to build a simple viewer.
 - The `singlepageviewer` example, similar to the above, but only displays *one* page at a time. That one could thus, potentially, replace your manual usage of `PDFPageView`.
