### ISSUE TITLE
More examples to use PDFindController outside the default viewer

### ISSUE THREAD

**Issue by valh1996** [mozilla/pdf.js#15201]
Hi,

I used to use the `PDFFindController` to make text highlight and it worked until now because the component I was using (vuejs) was using a default viewer.

But now I use a new open source component called [vue-pdf-embed](https://github.com/hrynko/vue-pdf-embed)  and [it uses renderTextLayer](https://github.com/hrynko/vue-pdf-embed/blob/master/src/vue-pdf-embed.vue#L377-L386) and I don't understand how to use a `PDFFindController` to search for a specific term using especially version `2.14.305` to do advanced search (diacritics, etc). 

Could you please give a concrete example on how to do this? I will be happy to submit a PR to this component to support open-source.

**Comment by Snuffleupagus** [comment]
> But now I use a new open source component called [vue-pdf-embed](https://github.com/hrynko/vue-pdf-embed) and [it uses renderTextLayer](https://github.com/hrynko/vue-pdf-embed/blob/master/src/vue-pdf-embed.vue#L377-L386)

Sorry, but we don't really know anything about that project here.
Generally speaking, if you're *manually* creating the textLayer you'll also need to manually handle initialization of e.g. the `PDFFindController` and `TextHighlighter` instances (and any other necessary components).

In order to simplify building a *custom* viewer, we thus provide a number of [viewer components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components). Note especially the `simpleviewer` one, which uses the `BaseViewer`-class which takes care of most things for you (among those is initializing everything needed for searching to work). Note especially, which shows a basic search:
https://github.com/mozilla/pdf.js/blob/5e7eab4dd8724e8287ab24ad372f187c3c3bc725/examples/components/simpleviewer.js#L78-L81

**Comment by valh1996** [comment]
@Snuffleupagus Thank you for these clarifications which confirm what I had seen. However, this does not seem very clear.

I see that the `TextLayerBuilder` class takes a highlighter as a parameter as you mention in your previous post. Could this be enough to initialize it?

I know this is not runnable code, but here is my code: 
```js
...

const pageIndex = page.pageIndex

this.eventBus = new EventBus()
this.findController = new PDFFindController({
  eventBus: this.eventBus,
  linkService: this.linkService,
})

const highlighter = new TextHighlighter({
  findController: this.findController,
  eventBus: this.eventBus,
  pageIndex: pageIndex
})

emptyElement(container)
const textLayer = new TextLayerBuilder({
  textLayerDiv: container,
  viewport: page.getViewport({
    scale: width / page.view[2],
    rotation: this.rotation,
  }),
  pageIndex: pageIndex,
  eventBus: this.eventBus,
  highlighter: highlighter
})

const textContent = await page.getTextContent()
textLayer.setTextContent(textContent)

textLayer.render();

this.eventBus.dispatch('find', { query: '1993' })
```

The text layer is well rendered, but nothing is highlighted, do you know please? Do I have to initialize an another component?

**Comment by Snuffleupagus** [comment]
> I see that the `TextLayerBuilder` class takes a highlighter as a parameter as you mention in your previous post. Could this be enough to initialize it?

There's potentially a bunch of other things that are missing, some things that come to mind:
 - None of this will work without the accompanying CSS rules, so are you using https://github.com/mozilla/pdfjs-dist/blob/master/web/pdf_viewer.css in your viewer? (This is assuming that you're using the `pdfjs-dist` library, which seems like a reasonable guess here.)
 - It's impossible to tell what `this.linkService` actually contains in your case, and it's thus not clear if you've provided a *working* `PDFLinkService`-instance rather than just a `SimpleLinkService`-instance? While you can obviously implement your own *custom* `PDFLinkService`-class, which may be required when your viewer is fully custom, it however needs to implement all of the "linkService"-functionality that the `PDFFindController`-class uses (otherwise things won't work).

> I know this is not runnable code, but here is my code:

Unfortunately that *severely* limits its usefulness, since as mentioned above it's impossible to e.g. tell what `this.linkService` actually is.

---

I realize that all of this isn't particularly easy to deal with, however that's the very reason for providing the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components since they handle all of this (and much more) for you.

**Comment by valh1996** [comment]
> I realize that all of this isn't particularly easy to deal with, however that's the very reason for providing the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components since they handle all of this (and much more) for you.

I see I understand, in this case I may just create my own component using your simpleviewer rather than trying to modify a third party wrapper component.

**Comment by valh1996** [comment]
Hi @Snuffleupagus, here are some update...

I can't seem to find a solution to my problem. I have tried different solutions but each time I encounter a different problem that makes me go back.

The solution that seemed to be the most flexible to me is your `PDFPageView` component. I managed to make the PDF and make it responsive, however impossible to make the term search work on it.

I'm using pdfjs-dist 2.14.305 with the legacy viewer.

Is it possible to do advanced search (diacritics, case insensitive, etc.) with the `PDFPageView` ?

**Comment by Snuffleupagus** [comment]
> Is it possible to do advanced search (diacritics, case insensitive, etc.) with the `PDFPageView` ?

Maybe, but as already mentioned you'd have to *manually initially all* of the necessary components in that case.
As mentioned in https://github.com/mozilla/pdf.js/issues/15201#issuecomment-1193087298, you'd definitely need a *custom* `PDFLinkService`-implementation since the find-functionality assumes that some kind of viewer is available (since searching in a single page isn't going to be generally useful).

However, it basically seems to me that in the end you're likely to more-or-less "re-implement" a fair amount of the `BaseViewer`-functionality; so why not just use that one and save yourself a lot of time/effort?
If you still want to using `PDFPageView` directly, then my only advise[1] would be to very carefully go through the `BaseViewer` and `PDFPageView` code to see how the viewer initializes/implements searching.

---
[1] Given that I'm an *unpaid* contributor, in this open-source project, it's unfortunately not at all feasible for me personally to provide detailed support for something *custom* like this.
