### ISSUE TITLE
pdfjs viewer is not working (missing pdf file) by running server

### ISSUE THREAD

**Issue by frankmehlhop** [mozilla/pdf.js#15202]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome current version
- Operating system and its version: Win 11
- PDF.js version: 2.14.305
- Is a browser extension:

Steps to reproduce the problem:
1. install and start python server (https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server)
2. start viewer.html

What is the expected behavior? (add screenshot)
I would like to see the pdf.

What went wrong? (add screenshot)
pdf is not shown.
I get Message: "Missing pdf file", the path und the file are ok.
cmd:
<img width="376" alt="Screenshot 2022-07-21 130945" src="https://user-images.githubusercontent.com/24494948/180200220-4e249bab-d457-4ad6-a5ab-d143483752c0.png">
Browser:
<img width="632" alt="Screenshot 2022-07-21 131054" src="https://user-images.githubusercontent.com/24494948/180200609-8922b222-32a9-4ed8-9f58-2c1043afa63e.png">

**Comment by Snuffleupagus** [comment]
Your browser screen-shot shows that you're, same as in issue #15178, loading the viewer using a `file://` URL. Hence the address you use to access the viewer needs to start with something like `http://localhost:8000/...` in order for this to work.

> install and start python server (https://developer.mozilla.org/en-US/docs/Learn/Common_questions/set_up_a_local_testing_server)

Unfortunately we cannot really support that, since it's not used within this project; for development purposes we use `gulp server` as outlined in https://github.com/mozilla/pdf.js#getting-the-code

**Comment by frankmehlhop** [comment]
Thank you very much Snuffleupagus! :-)
