### ISSUE TITLE
Invalid root reference when parsing pdf

### ISSUE THREAD

**Issue by YangZhenFu** [mozilla/pdf.js#15257]
**Configuration:**
- Web browser and its version:Google Chrome   97.0.4692.99
- Operating system and its version:win10 professional edition
- PDF.js version:2.16.6
- Is a browser extension: No

**What is the expected behavior?**
As rendered in Google Chrome PDF viewer:
![20220801193635](https://user-images.githubusercontent.com/27759767/182139845-d2386f2f-37d3-4fc5-a4d5-d46bdd08914a.png)

**What went wrong?**
1.Open attached PDF in public demo of PDF.js. The pdf worker is throwing
UnknownErrorException {
name: "UnknownErrorException",
message: "Invalid root reference",
details: "FormatError: Invalid root reference"
}
![20220801194507](https://user-images.githubusercontent.com/27759767/182141094-8e47ee1e-7ded-493e-a0c2-0f47539be351.png)
The error can be easily reproduced  using the attached pdf
[7C-C6-E2-4A-94-03-37-5E-CA-72-5D-4D-85-DD-44-7D.pdf](https://github.com/mozilla/pdf.js/files/9232166/7C-C6-E2-4A-94-03-37-5E-CA-72-5D-4D-85-DD-44-7D.pdf)
It can be opened normally in Google Chrome,So I want to know what is the reason.

**Comment by Snuffleupagus** [comment]
That PDF document is *corrupt* enough that even Adobe Reader (i.e. the reference implementation) refuses to open the document, hence it's not clear to me that it makes sense to attempt to fix this unfortunately.

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by YangZhenFu** [comment]
I updated the problem description, please check.
It can be opened normally in Google Chrome,So I want to know what is the reason.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "mozilla/pdf.js"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月1日(星期一) 下午4:20
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [mozilla/pdf.js] Invalid root reference when parsing pdf (Issue #15257)





 
That PDF document is corrupt enough that even Adobe Reader (i.e. the reference implementation) refuses to open the document, hence it's not clear to me that it makes sense to attempt to fix this unfortunately.
 
For future reference: When opening an issue, please provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by THausherr** [comment]
The PDF ends like this:
```
startxref
707619
%%EOF

```
This means that at offset 707619 there should be an xref table or an XRef stream object. Your PDF has just byte salat at that offset.

This file is two PDFs glued together. Because a new PDF starts at offset 676060. Maybe somebody thought that editing them together would create a multipage PDF - no, that's not the way PDFs work.

**Comment by YangZhenFu** [comment]
> The PDF ends like this:
> 
> ```
> startxref
> 707619
> %%EOF
> ```
> 
> This means that at offset 707619 there should be an xref table or an XRef stream object. Your PDF has just byte salat at that offset.
> 
> This file is two PDFs glued together. Because a new PDF starts at offset 676060. Maybe somebody thought that editing them together would create a multipage PDF - no, that's not the way PDFs work.

This PDF is corrupted because I used C# iTextSharp to add a watermark to the PDF, it can be opened normally by pdfjs without the watermark.Here is a screenshot of my code:
![2022-08-08_102459](https://user-images.githubusercontent.com/27759767/184070609-a530fb07-ca86-457e-893f-1b254bfd530b.png)

**Comment by Snuffleupagus** [comment]
Closing this issue as INVALID, for the following reasons:
 - The PDF document is clearly corrupt, as outlined nicely in https://github.com/mozilla/pdf.js/issues/15257#issuecomment-1210546100.
 - Even Adobe Reader, i.e. the PDF reference implementation, cannot open it.
 - The PDF document was apparently not produced by a proper PDF library, given https://github.com/mozilla/pdf.js/issues/15257#issuecomment-1211570863, but the file was rather "manually" edited. Doing that is *never* a good idea, since as seen above it's just too easy to end up *corrupt* PDF document that way. **Please update your PDF creation to actually generate _valid_ documents.**
 - Given the level of corruption in this PDF document, and importantly how it was created, it thus unfortunately doesn't seen reasonable/feasible to re-factor our fallback XRef-parsing to handle this one case.
