### ISSUE TITLE
Avoid hierarchal (tree) structure in the textlayer of pdfjs

### ISSUE THREAD

**Issue by BalajiArun004** [mozilla/pdf.js#15272]
I have been using Pdfjs for quite a long but with the recent update started to face issues with the textlayer structure. Previously the textlayer was flattened but with the latest release textlayer started to have hierarchy (tree) structure.
<br>
**Previous version Example:(2.8)**
<br>
```
<div id="textlayer">
<span>Hello World !!!</span>
<span>I'm confused </span>
</div>
```
**Latest version Example:(2.14)**
<br>
```
<div id="textlayer">
<span>
<br>
<span>Hello World !!!</span>
</span>
<span>
<br>
<br>
<span>I'm confused</span>
</span>
</div>
```
any way to get a flat structure on the textlayer?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this issue unfortunately isn't really possible to *easily* understand/reproduce.
Of particular importance is that you provide the PDF document in question.

---

It's possible that you'll need to use the `includeMarkedContent` parameter, however it is *off by default*, see https://github.com/mozilla/pdf.js/blob/8bad06f1580f8235c0ab4038d9211587dd39a9b5/src/display/api.js#L1084-L1085 and https://github.com/mozilla/pdf.js/blob/8bad06f1580f8235c0ab4038d9211587dd39a9b5/src/display/api.js#L1643-L1651

**Comment by BalajiArun004** [comment]
sample pdf: [https://github.com/BalajiArun004/publicFolder/blob/main/table.pdf](url)
I'm using the pdf-dist CDN URL in a html file to render the pdf file 
**Expecting a text layer to be flat like this** 
```
<div id="textlayer">
<span>Hello World !!!</span>
<span>I'm confused </span>
</div>
```
Actual behavior is having a nested span which I want to avoid
```
<div id="textlayer">
<span>
<br>
<span>Hello World !!!</span>
</span>
<span>
<br>
<br>
<span>I'm confused</span>
[table.pdf](https://github.com/mozilla/pdf.js/files/9268270/table.pdf)

</span>
</div>
```
to achieve this for now I'm downloading the pdfViewer.js file and changing the includemarkedcontent to be false
link (https://cdn.jsdelivr.net/npm/pdfjs-dist@2.14.305/web/pdf_viewer.js)
is there any way to achieve this without changing in the pdf viewer file

**Comment by calixteman** [comment]
Please attach a pdf (the link above is wrong).

**Comment by BalajiArun004** [comment]
> Please attach a pdf (the link above is wrong).

https://github.com/mozilla/pdf.js/files/9268270/table.pdf

**Comment by Snuffleupagus** [comment]
> https://cdn.jsdelivr.net/npm/pdfjs-dist@2.14.305/web/pdf_viewer.js

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> is there any way to achieve this without changing in the pdf viewer file

Unfortunately not, since various other parts of the default viewer uses that to improve accessibility.
