### ISSUE TITLE
Add runtime API to disable the findbar

### ISSUE THREAD

**Issue by nt1m** [mozilla/pdf.js#15285]
I'm running a setup where raw PDF.js is in an iframe and we inject a content script into it in order to do some tweaks.

I'm aware there is a way to disable the PDF.js findbar with a build time option, but that requires me to patch the code, which is not ideal, since I want to keep PDF.js unpatched, to make updates easier.

**Comment by Snuffleupagus** [comment]
> I'm running a setup where raw PDF.js is in an iframe and we inject a content script into it in order to do some tweaks.

In that case, can't you simply overwrite the `PDFViewerApplication.supportsIntegratedFind` getter in your code (setting it to `true`)?
Or, perhaps even provide your own *custom* `DefaultExternalServices`-implementation?
 - https://github.com/mozilla/pdf.js/blob/2a84a3078bd679aac42c9140df4314e7e4a94b9d/web/app.js#L720-L722
 - https://github.com/mozilla/pdf.js/blob/2a84a3078bd679aac42c9140df4314e7e4a94b9d/web/app.js#L142-L193
 - https://github.com/mozilla/pdf.js/blob/2a84a3078bd679aac42c9140df4314e7e4a94b9d/web/app.js#L254

As long as your content-script overwrites the necessary properties *before* the viewer initializes, I believe that should work; please see https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage

---

For reference, please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

Hence it's not entirely clear, at least to me, that it's overall desirable to add a new option for this since everything has a maintenance-cost and the use-case does seem *somewhat* specialized.

**Comment by nt1m** [comment]
> As long as your content-script overwrites the necessary properties before the viewer initializes

This is the tricky part unfortunately. We can inject stuff before the web viewer is navigated to (too early), or when the web viewer is fully loaded (too late).

I was hoping this would be a simple addition somewhere to check for `PDFViewerApplication.supportsIntegratedFind` at runtime that causes `event.preventDefault()` and related behaviour. 

The most problematic part is that the PDF.js findbar overrides the Cmd/Ctrl+F shortcut, and having a way to disable that behavior would be sufficient for me. I can the remainder of the tweaks using CSS.

**Comment by nt1m** [comment]
Ah I realized JS had a way to delete getters, so you can do:

```
delete PDFViewerApplication.supportsIntegratedFind;
PDFViewerApplication.supportsIntegratedFind = true;
```

**Comment by Snuffleupagus** [comment]
> This is the tricky part unfortunately. We can inject stuff before the web viewer is navigated to (too early), or when the web viewer is fully loaded (too late).

Why can't you listen for the "webviewerloaded" event, as mentioned in the Wiki-page linked above, since that one is intended to facilitate exactly these sort of things?

**Comment by nt1m** [comment]
> > This is the tricky part unfortunately. We can inject stuff before the web viewer is navigated to (too early), or when the web viewer is fully loaded (too late).
> 
> Why can't you listen for the "webviewerloaded" event, as mentioned in the Wiki-page linked above, since that one is intended to facilitate exactly these sort of things?

My current setup currently doesn't make this super practical, but my workaround in https://github.com/mozilla/pdf.js/issues/15285#issuecomment-1207371971 works for now. I might try again to fiddle with my setup if I have more time, but closing this for now. Thanks!
