### ISSUE TITLE
White spots on rendered PDF

### ISSUE THREAD

**Issue by frokohl** [mozilla/pdf.js#15304]
**Attach (recommended) or Link to PDF file here:**
[03_Zeugnis (1).pdf](https://github.com/mozilla/pdf.js/files/9314794/03_Zeugnis.1.pdf)

**Configuration**:
Chrome Version: 103.0.5060.134 (Offizieller Build) (64-Bit)
PDF.js Version: 2.0.489
Operating system:
Edition	Windows 11 Pro
Version	21H2
Betriebssystembuild	22000.795
Leistung	Windows Feature Experience Pack 1000.22000.795.0

**Is a browser extension:** 
no
We render the PDF within a custom solution.

**Steps to reproduce the problem:**
1. Render PDF in Browser

**What is the expected behavior? (add screenshot)**
Display fully readable PDF

**What went wrong? (add screenshot)**
White spots on the PDF preview 
![160809442-c3ee0cf9-8c1e-4f96-a90c-e3ae9e3ffa89](https://user-images.githubusercontent.com/22612550/184313951-8065c108-b7dd-4636-858d-1524ad5d9e9a.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `2.16.33` in Firefox Nightly 105 on Windows.

Also WFM, when opening your PDF document with https://github.com/mozilla/pdf.js#online-demo in Google Chrome Beta 105.0.5195.28 on Windows.

> PDF.js Version: 2.0.489

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

Please also note that the quoted version number was *not an official release*, as found at https://github.com/mozilla/pdf.js/releases, and it's over four years old.

---

Hence this is problem is either limited to old, and unsupported, versions of the PDF.js library or it's a `canvas`-related bug in the Google Chrome browser itself (which we unfortunately cannot do anything about here).

**Comment by dansoper** [comment]
Hello,
Apologies that this message is probably out of place, but I'm putting it here because this is where I wanted to find more information about this specific problem!

A very small number of users were experiencing exactly this issue. I upgraded to the latest (older browser version) PDF.js (3.1.81), but the issue still occured.

After a lot of experimentation, I found that the fix in my case was to change:
`var context = canvas.getContext('2d');` 
to
`var context = canvas.getContext('2d', { alpha: false });`

Whilst this only affected a small number of users, might it be worth adding that to the normal examples on this page: https://mozilla.github.io/pdf.js/examples.

Many thanks,

Dan
