### ISSUE TITLE
export annotation pdf is not working 

### ISSUE THREAD

**Issue by priyankarkhairnar** [mozilla/pdf.js#15305]
trying to send annoted pdf tp backend servert using export annotation method
getting this error v
code - const xfdfString =  this.wvInstance.CoreControls.annotationManager.exportAnnotations();
error -
Uncaught Error: AnnotationManager requires DocumentViewer to initialize
    at Function.ca [as AnnotationManager]

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable information here.

Furthermore, are you sure that you opened this issue in the *correct* repository since https://github.com/mozilla/pdf.js/issues/15305#issue-1336966255 mentions functions not found in this library?
