### ISSUE TITLE
No fieldValue on fieldType "Sig"

### ISSUE THREAD

**Issue by disjaPf** [mozilla/pdf.js#15301]
I have made an update from version 2.4.456 to version 2.15.349. Everything seemed to work! After some further tests I had to find out that something has changed. 

In version 2.4.456 it was possible (with some effort) to distinguish between signed and unsigned signature fields. So after calling the method getAnnotations() the fieldValue was filled with "Sig" for fieldType="Sig". So that was for me the distinction that a signature field was already signed. In case of unsigned signature fields the fieldValue remained null.

In version 2.15.349 the fieldValue in the resolved promise is always null. Also in case of already signed fields. See following:

![image](https://user-images.githubusercontent.com/111076033/184183322-c4e5d32b-0c21-40b4-984e-1ad724998f7e.png)

A verfication of a digital signature is not important for me. I only want the fieldValue to be filled when an annotation of a type "Sig" is filled. 

Is it possible to implement this???? 
Or is there already a way distinguish between signed and unsigned signature types????

**Comment by Snuffleupagus** [comment]
> A verfication of a digital signature is not important for me. I only want the fieldValue to be filled when an annotation of a type "Sig" is filled.

The first part would be *required* in order to support the second part properly, since otherwise there'll be breaking errors in the general case:
https://github.com/mozilla/pdf.js/blob/ab1297f0538c51e8e7ece037768e38a9991dcc37/src/core/annotation.js#L3163-L3166

> Is it possible to implement this????

Unfortunately not, without implementing #13351 first (of which this is thus basically a duplicate).

> Or is there already a way distinguish between signed and unsigned signature types????

No, since we currently don't parse SignatureAnnotations at all.
