### ISSUE TITLE
Text Extraction from pdf with pdfjs is inaccurate in Vue3

### ISSUE THREAD

**Issue by Clastine** [mozilla/pdf.js#15328]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google chrome 104.0.5112.81
- Operating system and its version: Windows 11 pro 22H2
- PDF.js version: pdfjs-dist: 2.14.305 and vuejs 3
- Is a browser extension: no

Steps to reproduce the problem:
1. Render all pages of pdf with Text layer

What is the expected behavior? (add screenshot)
to extract highlighted text accurately with windows.getSelection

What went wrong? (add screenshot)
![highlighted text](https://user-images.githubusercontent.com/104621944/185314339-3bc6b9d2-f9fc-4d72-a52c-cd46b6c0edc8.png)
![extracted text](https://user-images.githubusercontent.com/104621944/185314419-b2e6c7f0-9b34-4ee7-a780-5bdcfac57445.png)
when I extract the highlighted text from pdf with pdfjs using window.getselection the start position and end position is few characters after and before and also selecting the white space.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the issue template is *required* when opening an issue, since as-is it's unfortunately not actionable.

> PDF.js version: pdfjs-dist: 2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> and vuejs 3

Sorry, but we don't know anything about "vuejs 3" (since we don't use it here) and thus cannot provide any help/support for it.

> Steps to reproduce the problem:
>     1. Render all pages of pdf with Text layer

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
