### ISSUE TITLE
How to get the position of image in the pdf 

### ISSUE THREAD

**Issue by xiaoxiaoxiaodouzi** [mozilla/pdf.js#15323]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
support some api to get the position of the image

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this is essentially missing every single piece of information required to be actionable/valid.

> support some api to get the position of the image

The following is both unsupported/untested, since it's never been used in the PDF.js library, however it may help:
https://github.com/mozilla/pdf.js/blob/518115fddc6db2c28752b8e9369c79377f521592/src/display/api.js#L1175-L1176

**Comment by xiaoxiaoxiaodouzi** [comment]
thanks .it mean's that when i  `let page = await pdf.getPage(pageNumber)` i want to get the position of image in page ,so i can quickly to jump to the right position of the pdf
