### ISSUE TITLE
Cannot access fontLoader > nativeFontFaces

### ISSUE THREAD

**Issue by wizeobara** [mozilla/pdf.js#15321]
Configuration:
- Web browser and its version: All
- Operating system and its version: MacOS
- PDF.js version: `"pdfjs-dist": "2.2.228"`
- Is a browser extension: No

Steps to reproduce the problem:
```
    const loadingTask = getDocument({
      cMapPacked: true,
      cMapUrl: `${window['srcUrl']}assets/cmaps/`,
      url,
    });

    loadingTask.promise.then(pdfDocument => {

      pdfDocument.getData().then((data) => {
        this.pdfBlob = new Blob([data], { type: 'application/pdf' });
        this.pdfBlobUrl = window.URL.createObjectURL(this.pdfBlob);
        this.emit('file-blob-created', this.pdfBlob, this.pdfBlobUrl);
      });

      this.pdfDocument = pdfDocument;
      this.pdfViewer.setDocument(pdfDocument);

      console.log("CONSOLE1: ", this.pdfDocument._transport.fontLoader);
      console.log("CONSOLE2: ", this.pdfDocument._transport.fontLoader.nativeFontFaces);
      console.log("CONSOLE3: ", this.pdfDocument._transport.fontLoader.nativeFontFaces[0]);
      console.log("CONSOLE4: ", this.pdfDocument._transport.fontLoader.nativeFontFaces.some(i => i.status === "error"));
```

1. CONSOLE1 returns the following
<img width="974" alt="Screen Shot 2022-08-16 at 16 29 56" src="https://user-images.githubusercontent.com/79693828/184822873-5f1fec7b-65bf-433f-9f2e-4626d70ab848.png">

2. CONSOLE2 returns `[]`. Expected 3 [FontFace](https://developer.mozilla.org/en-US/docs/Web/API/FontFace) Objects in Array as seen in CONSOLE 1

3. CONSOLE3 returns `undefined`. Expected FontFace Object

4. CONSOLE4 returns `false` expected `true` since contains status: "error" as seen in CONSOLE 1

Disclaimer: I do not know if this is a bug or expected behavior.

I want to be able to access `this.pdfDocument._transport.fontLoader.nativeFontFaces[0].status` as I would like to display warning message when font may be altered/invisible (status: "error").

Is this a bug or not possible in this library.

**Comment by Snuffleupagus** [comment]
> PDF.js version: `"pdfjs-dist": "2.2.228"`

That version is no longer supported, since that version is over three years old; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem:

In general, please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> I want to be able to access `this.pdfDocument._transport.fontLoader.nativeFontFaces[0].status` as I would like to display warning message when font may be altered/invisible (status: "error").

Please keep in mind that a name beginning with an underscore, by tradition in JavaScript, means that the property/method in question should be regarded as "private" and thus isn't intended to be accessed.

Furthermore, it's not really clear really *exactly* what you're attempting to achieve here, also note that we already print warnings *and* attempt to fallback when a font fails to load. All-in-all, that you're attempting to do is unfortunately not supported here.
