### ISSUE TITLE
Firefox - Text highlight not working as expected

### ISSUE THREAD

**Issue by karelee7** [mozilla/pdf.js#15331]
File Types: 
PDF, pptx

Configuration:
- Web browser and its version: Firefox, v103.0.2
- Operating system and its version: mac OS Monterey v12.5
- PDF.js version: v2.14.305

The expected behavior is to have multiple lines of text highlighted correctly:
<img width="543" alt="Screen Shot 2022-08-18 at 5 28 56 PM" src="https://user-images.githubusercontent.com/95440409/185517269-10e86b20-6a7d-4bd8-aa56-253bd3a2e2db.png">

The issue is that with the newer version of PDFjs, only the last line is highlighted when multiple lines are selected:
<img width="535" alt="Screen Shot 2022-08-18 at 5 25 10 PM" src="https://user-images.githubusercontent.com/95440409/185517074-53fcdf4b-cede-4956-9a8c-0679e948cc92.png">

**Relevant code:**
```
let range = selection.getRangeAt(selection.rangeCount - 1);

const containerEl = findClosestElWithClass(range.endContainer as Element, 'textLayer');
const startPage = getPageNumber(range.startContainer as Element);
const endPage = getPageNumber(range.endContainer as Element);

console.log('START CONTAINER');
console.log(range.startContainer);
```
From the logs, it seems that in the previous versions of PDFjs, the `startContainer` is `#text "You can print out PPT files as handouts "`. But in v2.14.305 of PDFjs, the `startContainer` is `<span style="left: 77.0043px; top: 20…form: scaleX(0.937038);" role="presentation" dir="ltr">`. This seems to be where the issue is, as the latter case is selecting the span containing "PRINT WHAT..." as the starting point (i.e. the last line of the text selection). 

Any ideas as to how to resolve this for v2.14.305 of PDFjs?

**Comment by Snuffleupagus** [comment]
> File Types:
> PDF, pptx

First of all, the PDF.js library cannot open PowerPoint files, hence that part doesn't really make sense here unfortunately.

Furthermore, the `Attach (recommended) or Link to PDF file here:`-part of the ISSUE_TEMPLATE is *always required* when opening an issue since as-is there's unfortunately no actionable information provided here.

> PDF.js version: v2.14.305

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Relevant code:
> [...]

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> From the logs, it seems that in the previous versions of PDFjs, the `startContainer` is `#text "You can print out PPT files as handouts "`. But in v2.14.305 of PDFjs, the `startContainer` is `<span style="left: 77.0043px; top: 20…form: scaleX(0.937038);" role="presentation" dir="ltr">`.

Given that it's not clear which the "previous versions of PDFjs" are above, this information unfortunately isn't really helpful as-is.
However, note that textLayer improvements have been made is some of the latter releases (to improve overall text-selection in the *built-in* Firefox PDF Viewer) and it's thus *possible* for the exact textLayer-format to change slightly between releases.

In combination with the overall lack of information, it's simply *impossible* for us to provide any help here unfortunately.

**Comment by karelee7** [comment]
@Snuffleupagus Hm, I did some more investigating and it appears that this is happening because `window.getSelection()` is returning the wrong `anchorNode` in the selection object, for PDFjs v2.14.305 on Firefox (for special reasons, I need to use this specific version of PDFjs unfortunately). 

In the first image above (PDFjs v2.2.228), the anchorNode is the correct text node of "You can print out...".
In the second image above (PDFjs v2.14.305), the anchorNode is the incorrect span "PRINT WHAT...". 

Are there any known issues with PDFjs v2.14.305 and using `window.getSelection()` in Firefox??

**Comment by karelee7** [comment]
@Snuffleupagus Just checking in to see if you had any insights for this! I can't seem to figure out why the selection itself is incorrect for Firefox. I took a look at the layout of the elements on Firefox as well and it looks identical to Chrome, so I'm not sure why the selection is behaving differently...

**Comment by karelee7** [comment]
@Snuffleupagus It seems that the selection is also missing indentation, I think this may be part of the reason that only a single line is getting highlighted:

on Chrome:
```
You can print out PPT files as handouts
using the
PRINT >
PRINT WHAT > HANDOUTS option
```

on Firefox: 
```
You can print out PPT files as handoutsusing thePRINT >PRINT WHAT > HANDOUTS option
```

By any chance, do you know if this is expected behavior? Or if there's a workaround for this??
