### ISSUE TITLE
[Legacy viewer] Password protected document can't be opened on browsers that don't support <dialog>

### ISSUE THREAD

**Issue by imbaky** [mozilla/pdf.js#15330]
**Attach (recommended) or Link to PDF file here:**
[document-protected.pdf](https://github.com/mozilla/pdf.js/files/9377476/document-protected.pdf) (pwd: helloWorld)

**Configuration**:
- Web browser and Operating system : 
Safari (15.3) on macOS Monterey (12.2.1) and
Firefox (91.9.1esr) on Windows 11
- PDF.js version: latest
- Is a browser extension: N/A

**Steps to reproduce the problem:**
1. In Legacy viewer open password protected file.
2. Type password 

**What is the expected behavior? (add screenshot)**
You should be able to view the file.

**What went wrong? (add screenshot)**

Dialog close() is not supported which throws an error and interrupts the password verification 

Error: No given password

<img width="1342" alt="Screen Shot 2022-08-18 at 5 15 14 PM" src="https://user-images.githubusercontent.com/6955509/185496508-25fabb44-55fa-492b-8e96-3697951c230e.png">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/legacy/web/viewer.html

**Comment by calixteman** [comment]
WFM in Safari 15.6 on Monterey 12.

**Comment by imbaky** [comment]
@calixteman that's because dialog is supported only after 15.4:

<img width="901" alt="Screen Shot 2022-08-18 at 5 17 41 PM" src="https://user-images.githubusercontent.com/6955509/185496829-a694fc34-af36-410d-95a2-4f221ec07be5.png">



https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dialog

**Comment by Snuffleupagus** [comment]
In the `legacy`-viewer a polyfill is being used, to make sure that the dialogs work in older browsers, see
https://github.com/mozilla/pdf.js/blob/8f74fe6e1baf89a648e3a2b02d21f864238c2df0/web/overlay_manager.js#L40-L56

Hence it would seem that older Safari browsers may perhaps not actually enter that block as intended (given that I'm not a Mac-user I cannot even begin to debug this)!?

**Comment by imbaky** [comment]
@Snuffleupagus I'm aware of this change and it fixes the UI but this issue is caused by the logic which retrieves the password.... not sure if this is helpful but these are the errors logged in the console:

<img width="1430" alt="Screen Shot 2022-08-18 at 7 13 28 PM" src="https://user-images.githubusercontent.com/6955509/185511148-26138076-7fff-4d6f-8863-44eca3a77363.png">

Let me know if you need any additional info about this issue.

**Comment by Snuffleupagus** [comment]
There's two things that make https://github.com/mozilla/pdf.js/issues/15330#issuecomment-1220068586 less helpful unfortunately:
 - The fact that `async`/`await` was transpiled with Babel, which makes it much more difficult to trace this back to the original code. With a recent patch this no longer happens, so hopefully it's possible to get better error messages/stacks now.
 - The fact that the error messages/stacks are provided as an image, since that's (in general for most software development) very rarely what you want.

My suspicion is that there's *something* wrong with the dialog-polyfill, but it's very difficult to tell.
So, in order to *maybe* make progress here, please re-test this using the latest viewer at https://mozilla.github.io/pdf.js/legacy/web/viewer.html and please provide the full error messages/stacks *as text* instead.

**Comment by imbaky** [comment]
@Snuffleupagus Well that's the thing, since it is related to dialog support....you don't need a mac or safari to repro it.

 I was able to repro this on an older version of Firefox:
https://ftp.mozilla.org/pub/firefox/releases/91.9.1esr/win64/en-US/

**Comment by Snuffleupagus** [comment]
Given that this doesn't affect the *built-in* Firefox PDF Viewer, I cannot really justify spending my spare time trying to fix this (since I'm not getting paid to hack on the PDF.js library).
However if you'd be willing to compensate me for my time, I don't believe that it'd be too difficult for me to provide a patch for this.
