### ISSUE TITLE
Image in PDF is aliased / blurry in newer version of PDF.JS

### ISSUE THREAD

**Issue by Hans-ABC** [mozilla/pdf.js#15345]
Attach (recommended) or Link to PDF file here:
[sample-aliased-image.pdf](https://github.com/mozilla/pdf.js/files/9422811/sample-aliased-image.pdf)

Configuration:
- Web browser and its version: Chrome - Version 104.0.5112.101 (Official Build) (x86_64)
- Operating system and its version: MacOS Monterey (Version 12.3.1) - though the same issue is noticed in Windows
- PDF.js version: 2.12.313, 2.15.349
- Is a browser extension: no

Steps to reproduce the problem:
1. Load the sample file using the provided viewer.
2. See the image (for the attached images, please see the image in a new tab / full resolution to see the non-aliased in PDF.JS 2.5.207)

### What is the expected behavior? (add screenshot)
Image will be displayed fine - no aliasing. (this is from PDF.JS 2.5.207) 
![image](https://user-images.githubusercontent.com/65745103/186611943-eb121932-0c43-4896-95c6-ac9b3792b90b.png)

### What went wrong? (add screenshot)
Image is aliased

(PDF.JS 2.12.313)
![image](https://user-images.githubusercontent.com/65745103/186612168-fc740447-8cb6-4a33-b27b-d20f9d6bf7a3.png)

(PDF.JS 2.15.349)
![image](https://user-images.githubusercontent.com/65745103/186612117-ba5dbd6a-72c2-4fb7-ba71-93ed5c80d653.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `2.16.71` in Firefox Nightly 106; see

![firefox](https://user-images.githubusercontent.com/2692120/186616501-b731d649-e104-4f0a-bfea-e82e7dca151b.png)

---

> Web browser and its version: Chrome - Version 104.0.5112.101 (Official Build) (x86_64)

This unfortunately looks like a `canvas`-related bug in the Google Chrome browser *itself* rather than a general PDF.js bug, since otherwise you'd expect it to be consistently broken everywhere, hence it's really not clear what (if anything) we can do about it here. (And please keep in mind that Firefox is the *primary* development target for this library.)

**Comment by timvandermeij** [comment]
Closing since this really looks like an upstream Chrome bug, so please report the issue there instead.
