### ISSUE TITLE
[Bug] The textlayer has some unexpected chars.

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#15352]
Attach (recommended) or Link to PDF file here:

https://pdf.cdn.readpaper.com/aiKnowledge/pdf/2022-05-06/d55ec560f4c142c3973abc66397d1822-/userUpload/d0edf452a85821acf41cbfa0a6f2f2ac.pdf

Configuration:
- Web browser and its version: Google Chrome v104.0.5112.101 arm64
- Operating system and its version:  macOS Monterey v12.5.1
- PDF.js version: "pdfjs-dist": "^2.15.349"
- Is a browser extension: no

Steps to reproduce the problem:
1.  The selected chars are not correct.  Like this as blow:  There are some unexpected chars .
```
a fu ̄dame ̄tal requireme ̄t for reio ̄izi ̄g the u ̄iverse is that a sufficie ̄t fractio ̄ of the io ̄izi ̄g photo ̄s emitted by galaxies
```

<img width="1453" alt="image" src="https://user-images.githubusercontent.com/9332442/186853911-cc98ef61-96df-4737-a54d-22cc806a5f0e.png">

2. Open the pdf with the chrome itselt. Then ctrl+c & ctrl +v. The selected chars are correct.
<img width="1720" alt="image" src="https://user-images.githubusercontent.com/9332442/186854814-a48d36ee-955f-4275-869f-c0ed94d6128c.png">

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by calixteman** [comment]
It isn't directly related to text selection but something is wrong with the font encoding.
For example, the word `Preprint` on the first line is using the font `F82`which is a type1 font and its encoding dictionary contains the entry: `dup 110 /macron put` and 110 corresponds to a `n`, hence the `n` is mapped into a `macron`.
I opened this pdf in different viewers and `Preprint` is correctly recognized.

@Snuffleupagus, any insights ?

**Comment by calixteman** [comment]
I wonder if we should really use the encoding dictionary from the font stream when we already have one defined in the font dictionary.

**Comment by Snuffleupagus** [comment]
> I wonder if we should really use the encoding dictionary from the font stream when we already have one defined in the font dictionary.

There are cases where that really is necessary, and we should have reference-tests for it, in order for text-extraction/selection to work properly. Note that this code was added in response to loads of issues seen over the years, so we cannot just remove that unfortunately (unless we want a bunch of other text-selection regressions).

In this case the font in question have very little /ToUnicode-data, since a more "complete" map *should have* prevented issues here. Most likely we can adjust the existing heuristics to improve things, and I can see a *potential way* to do, that however I've not run any tests...
