### ISSUE TITLE
the pdfjs-dist legacy build version has the modern syntax

### ISSUE THREAD

**Issue by zhoufenfens** [mozilla/pdf.js#15363]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:  chrome 69
- Operating system and its version:  macos 10.15.7
- PDF.js version:   2.16.105
- Is a browser extension:  no

Steps to reproduce the problem:
1. import the legacy build version to some old browser
2.  some error  'Promise.allSettled is not a function' shows

What is the expected behavior? (add screenshot)
no error happens

What went wrong? (add screenshot)
the compatible code was removed from the lastest two verison in legacy build folder
https://github.com/mozilla/pdfjs-dist/blob/v2.14.305/legacy/build/pdf.js  (version 2.14.305 worked right)
<img width="502" alt="image" src="https://user-images.githubusercontent.com/3303836/187378734-02e2326e-54a5-4033-9fd6-c39f46bc1e1e.png">

I also found that some modern syntax like async, await, const was keeped in the latest verison 2.16.105. https://github.com/mozilla/pdfjs-dist/blob/v2.16.105/legacy/build/pdf.js
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Web browser and its version:  chrome 69

That browser is no longer supported in the PDF.js project, since quite some time.
Also, according to https://en.wikipedia.org/wiki/Google_Chrome_version_history that browser was released in 2018 and it's *generally never* a good idea to use such an old/outdated browser.

---

The *currently supported* browsers are always listed in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
