### ISSUE TITLE
Publicly Expose pdf viewer

### ISSUE THREAD

**Issue by joeldhenry** [mozilla/pdf.js#15362]
Attach (recommended) or Link to PDF file here:
Would is be possible to expose pdf viewer as a public API?

Right now I must import as:
```
import { EventBus, NullL10n, PDFLinkService, PDFViewer } from 'pdfjs-dist/web/pdf_viewer';
```

is there any reason this is not currently exposed?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately lacks enough detail to understand *exactly* what you're actually asking for!

> Would is be possible to expose pdf viewer as a public API?
>
> Right now I must import as:
> [...]

It's not entirely clear what this actually means, since it's being exposed as-is (otherwise you'd not be able to import it as shown)?

> is there any reason this is not currently exposed?

What's not being exposed, since you've not explained what's "wrong" with the current situation or what you'd like to see instead?
