### ISSUE TITLE
The display of Chinese characters in the lower version of Android is incomplete.

### ISSUE THREAD

**Issue by aiyadingya** [mozilla/pdf.js#15376]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Chrome/62.0.3202.84 
- Operating system and its version:
- Android webview
- PDF.js version:
- 2.8.335
- Is a browser extension:
- no

Steps to reproduce the problem:

Using the example/learning/helloworld.html page (using my pdf file), the Chinese display is incomplete on the above Android webview

![The display effect of the page](https://cdn.xiaoxiangyoupin.com/dev/img/Snipaste_2022-09-01_17-55-52.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* when opening an issue, since as-is there's unfortunately no actionable information provided here.

> Web browser and its version: Chrome/62.0.3202.84

That browser is no longer supported, please refer to the FAQ: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: 2.8.335

That version is no longer supported, since it's over a year old; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
