### ISSUE TITLE
On Degger.js of latest version: Uncaught SyntaxError: Cannot use 'import.meta' outside a module

### ISSUE THREAD

**Issue by ronganEnerknol** [mozilla/pdf.js#15404]
Configuration:
- Web browser and its version: Chrome Version 104.0.5112.101
- Operating system and its version: Ubuntu 18.04
- PDF.js version:  2.16.105
- Is a browser extension: No

I used the viewer.js in my Flask application. In the viewer.html, I have
   ```
 <link rel="resource" type="application/l10n" href="<path_to_locale.propertie>"/>
  <script type="text/javascript" src="<path_to_pdf.js>"></script>
  <script type="text/javascript" src="<path_to_viewer.js>"></script>
  <script type="text/javascript" src="<path_to_debugger.js"></script>

```

I don't have to include    ` <script type="text/javascript" src="<path_to_debugger.js"></script>` in viewer.html to work. But I wanted to include it so that I don't miss any features. Then I got this error on my console:
`VM496:1 Uncaught SyntaxError: Cannot use 'import.meta' outside a module`

I think this is a bug in debugger.js. Am I wrong? What am I supposed to with that?

**Comment by Snuffleupagus** [comment]
[web/debugger.js](https://github.com/mozilla/pdf.js/blob/master/web/debugger.js) and its accompanying CSS-file is only intended for debugging/development purposes, as indicated by the filename, hence it's not normally something that you need/want in a production environment.

> `<script type="text/javascript" src="<path_to_debugger.js"></script>`

Please note that that file has never been intended to be loaded unconditionally in that way[1], since the default viewer has *always* been loading it lazily; see https://github.com/mozilla/pdf.js/blob/95e3f5d49510bfa3425d7bfb9ce8be48deac30c0/web/app.js#L2212-L2220

Hence what you're trying to do here is neither intended, or supported, unfortunately.

---
[1] Although I suppose that setting `type="module"` instead probably "works", but again it doesn't really make sense to load it with a `script`-tag.
