### ISSUE TITLE
About import pdfjs-dist is undefined

### ISSUE THREAD

**Issue by Asaki-M** [mozilla/pdf.js#15434]
In my project, i install 'pdfjs-dist' version '^2.16.105'. When i use `import pdfjs from 'pdfjs-dist'`, but the `pdfjs` is undefined. 

How can I fix this error?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't actionable.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
