### ISSUE TITLE
Vertical lines render incorrectly with Safari 16

### ISSUE THREAD

**Issue by greengreengreengit** [mozilla/pdf.js#15456]
Using pdf.js in webpage on iOS 16 or macOS Ventura Safari 16. Also pdf.js in webpage in Safari Developer Preview on macOS Monterey

Vertical lines are wider and taller than expected. It may be a bug in the Safari 16, but any suggestions welcome before reporting to Apple. 

Here is example PDF…
[BAR FAIL.pdf](https://github.com/mozilla/pdf.js/files/9593728/BAR.FAIL.pdf)

Here is failed render…
![Failed Render](https://user-images.githubusercontent.com/11004468/190896977-a02c07bb-1032-47a2-8cca-25a4b06fe450.png)

Here is correct render…
![Correct render](https://user-images.githubusercontent.com/11004468/190896799-e8009292-b936-4a45-9175-99694ed7b688.png)

**Comment by Snuffleupagus** [comment]
> Using pdf.js in webpage on iOS 16 or macOS Ventura Safari 16. Also pdf.js in webpage in Safari Developer Preview on macOS Monterey

This doesn't say *anything* about what PDF.js version(s) you're using. Please make sure to fill out the ISSUE_TEMPLATE *completely*, including the "Configuration"-section, when opening an issue.

WFM, using PDF.js version `3.0.70` in both Mozilla Firefox Nightly 106 and Google Chrome Beta 106 on Windows.

Hence this unfortunately looks like a *Safari-specific bug*, related to regular `canvas`-rendering since the file only contains simple rendering operations, rather than a bug in the PDF.js library since you'd expect it to be consistently broken *everywhere* in that case.

Given that Firefox is the *primary* development target, where it does seem to work fine, you probably need to report this bug to the Safari developers instead.
