### ISSUE TITLE
[Bug] The chars of highlight annotations can not be seen.

### ISSUE THREAD

**Issue by Sara2009** [mozilla/pdf.js#15480]
Attach (recommended) or Link to PDF file here:
https://pdf.cdn.readpaper.com/aiKnowledge/pdf/2022-09-19/4541b29da5c5415cb8184f7f781b0780//userUpload/5d66ed2aa1037de37e185d596fc44a6f.pdf
Configuration:
- Web browser and its version:  Google Chrome v105.0.5195.125 arm64
- Operating system and its version: macOS Monterey v12.5.1   Apple M1 Pro
- PDF.js version: "pdfjs-dist": "^2.15.349"
- Is a browser extension:

Steps to reproduce the problem:
1. hightlight annotation is not right. The chars can not be seen.
<img width="1335" alt="image" src="https://user-images.githubusercontent.com/9332442/191412448-22c72a95-1213-4138-9e63-41c77e3e2bae.png">

What is the expected behavior? (add screenshot)

Use chrome to open the pdf.
<img width="1674" alt="image" src="https://user-images.githubusercontent.com/9332442/191412598-da333c77-17de-48ea-b1dd-acb84e00b0ed.png">

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `3.0.60` as built-in to Firefox Nightly 107 on Windows.

It also works when opening your document with https://mozilla.github.io/pdf.js/web/viewer.html in Google Chrome Beta 106, hence this looks like a browser/platform bug rather than a PDF.js one.

> * PDF.js version: "pdfjs-dist": "^2.15.349"

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
