### ISSUE TITLE
[BUG] Blank app / potential out-of-memory crash

### ISSUE THREAD

**Issue by idrisonehub** [mozilla/pdf.js#15481]
Attach (recommended) or Link to PDF file here:
https://github.com/mozilla/pdf.js/files/9614138/large_objects.pdf

Configuration:
- Web browser and its version: `Version 105.0.5195.127 (Official Build) (64-bit)`
- Operating system and its version: `Windows 10`
- PDF.js version: `pdfjs-dist@2.10.377`

Steps to reproduce the problem:
1. Download the pdf file [large_objects.pdf](https://github.com/mozilla/pdf.js/files/9614138/large_objects.pdf)
2. Run code below

```
let canvas = document.getElementById('page-canvas-1')
let context = canvas.getContext('2d')
let viewport = pages[0].getViewport({ scale: 1 })
let renderOp = pages[0].render({ canvasContext: context, viewport })

renderOp.promise.then(() => {console.log('page rendered')})
```

My app has potential out-of-memory when load the pdf (page 1).
You can try to open the pdf file using https://mozilla.github.io/pdf.js/web/viewer.html

![image](https://user-images.githubusercontent.com/55071226/191446553-dc17db24-0747-4f55-889d-36b7312c8d69.png)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: `Version 105.0.5195.127 (Official Build) (64-bit)`

This is only a version *number*, but doesn't say anything about what browser you actually used.

> PDF.js version: `pdfjs-dist@2.10.377`

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> My app has potential out-of-memory when load the pdf (page 1).

It doesn't crash in Mozilla Firefox, although memory usage continues to climb.

---

This is a bug in the PDF document *itself*, since even Adobe Reader (i.e. the reference implementation) cannot handle that document either; this issue looks quite similar to e.g. #14804.
