### ISSUE TITLE
PDF.js v2.16.105 no longer supports ES5?

### ISSUE THREAD

**Issue by ctruxaw** [mozilla/pdf.js#15497]
The [legacy release of v2.16.105](https://github.com/mozilla/pdf.js/releases/download/v2.16.105/pdfjs-2.16.105-legacy-dist.zip) appears to use ES6+ now (e.g. uses "let" keyword instead of "var") yet I see no mention of this change in the release notes.

My apologies if I missed an announcement. But will there be an ES5 compatible release of v2.16.105?

(The legacy release of v2.15.349 is ES5 compatible, so perhaps this is a build error?)

Thanks

**Comment by Snuffleupagus** [comment]
We've actually not supported ES5-browsers for well over a year, since already by the time of PR #12978 *full* ES5-compatibility had already started to "break".

> But will there be an ES5 compatible release of v2.16.105?

Unfortunately not, since trying to supporting older browsers is just too much work for the few regular PDF.js contributors, and the *minimum* supported browsers (in the `legacy`-version) are always listed in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
