### ISSUE TITLE
Text added via incremental save does not render correctly

### ISSUE THREAD

**Issue by Luxusio** [mozilla/pdf.js#15496]
Attach (recommended) or Link to PDF file here:
[result.pdf](https://github.com/mozilla/pdf.js/files/9630355/result.pdf)

Configuration:
- Web browser and its version: Chrome 105.0.5195.125 (arm64)
- Operating system and its version: macOS Monterey 12.4
- PDF.js version: 2.16.105
- Is a browser extension: No

Steps to reproduce the problem:
 - open file with chrome browser
 - or open file with PDF.js

What is the expected behavior? (add screenshot)

in Adobe Acrobat
![스크린샷 2022-09-23 오전 11 01 36](https://user-images.githubusercontent.com/44326048/191879792-0cfd529b-b2bc-4c83-aabb-f2464926b972.png)

What went wrong? (add screenshot)

in Chrome
![image](https://user-images.githubusercontent.com/44326048/191879910-d07e526d-ab6a-4efd-9a9a-6a5f14606e71.png)

in pdf.js 2.16.105
![image](https://user-images.githubusercontent.com/44326048/191880049-8e8158c7-3a85-45d3-8798-6e260fd0a844.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

I'm sorry that I can't attach it because it's a company project.

**Comment by Snuffleupagus** [comment]
Your document contains two non-standard *and* non-embedded fonts, called "NanumGothic" respectively "NanumGothicBold", hence this simply cannot work correctly in the general case.
Note that your document even renders incorrectly in Adobe Reader if you don't have those fonts installed locally, and this is how it renders for me:
![fonts](https://user-images.githubusercontent.com/2692120/191910201-9266d094-36a1-4ccb-922c-704c2e128855.png)

If you want this to work correctly across different PDF viewers and different computers, then you *must embed* all non-standard fonts in your PDF document since otherwise it simply cannot work; closing as INVALID since we can't fix this since the bug is in the PDF document *itself*.
