### ISSUE TITLE
Save modified document

### ISSUE THREAD

**Issue by rmi111** [mozilla/pdf.js#15502]
Greetings,
I have a requirement where I have to preview PDF and add signature image inside it. I am using PDFJS for previewing, and as far as I know PDFJS is simply is for viewing purpose only. I have came across an example in codepen where it uses PDFJS to drag and drop some element over a page. 
[Demo](https://codepen.io/ValerioEmanuele/pen/pGRZqe)
My question is based on above demo is there any way to save the modified pdf after drag and drop? Or It need to be combined with help of other library such as PDF-LIB or TFPDF etc.
Thanks

**Comment by Snuffleupagus** [comment]
We support saving modified/added annotations, but nothing else since PDF.js is primarily a PDF *viewer* and not a general editor.

Given that this is first and foremost a *bug tracker*, we cannot recommend other software projects here.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't an actionable/valid issue.
