### ISSUE TITLE
Rotate + Zoom on Image Decoder

### ISSUE THREAD

**Issue by chdonncha** [mozilla/pdf.js#15518]
I've an uploaded file selection that stores JPEG's and PDF's. Upon clicking any of them it'll detect the file type and use the appropriate render function for PDF's or JEPGs to display on a canvas in a modal on the same page. The JPEG render function is similar to the example image_decoders.

The issue I've run into is providing a Zoom and Rotation functionality to the image. Providing it to the PDF is straight forward using the Viewport, but have not found a solution to doing something similar with the image if there is one available? 

I'm trying to avoid using CSS transforms as an alternative.

my current JPEG render function:

```js
function renderJPEG(data) {
    pdfViewOptions.setAttribute('hidden', '');
    hideLoader();

    // Convert base64 encoded jpeg to a Unit8Array
    const typedArrayImage = Uint8Array.from(atob(data), c => c.charCodeAt(0))
    const jpegImage = new pdfjsImageDecoders.JpegImage();

    jpegImage.parse(typedArrayImage);

    const width = jpegImage.width,
        height = jpegImage.height;
    const jpegData = jpegImage.getData({
        width,
        height,
        forceRGB: true,
    });

    // Render the JPEG image on a <canvas>.
    const imageData = context.createImageData(width, height);
    const imageBytes = imageData.data;
    for (let j = 0, k = 0, jj = width * height * 4; j < jj;) {
        imageBytes[j++] = jpegData[k++];
        imageBytes[j++] = jpegData[k++];
        imageBytes[j++] = jpegData[k++];
        imageBytes[j++] = 255;
    }
    viewerCanvas.width = width;
    viewerCanvas.height = height;
    context.putImageData(imageData, 0, 0);
}
```

**Comment by Snuffleupagus** [comment]
> but have not found a solution to doing something similar with the image if there is one available?

That's because no such functionality exists for images.

Please note that the purpose of the PDF.js library is to, as its name suggests, parse/render *PDF documents*.
As part of doing that you also need to ability to decode various image formats, and as a convenience (since users asked for it) we thus provide some image decoders *standalone* (e.g. `JpegImage`). However, these image decoders are purposely very bare-bones and they only allow you to *decode* the image data (e.g. for rendering onto a `canvas`) but no other functionality.
