### ISSUE TITLE
Error: Loading aborted in node.js

### ISSUE THREAD

**Issue by DoneDeal0** [mozilla/pdf.js#15520]
Configuration:
- node: 16.13.0
- Operating system and its version: OSX 10.13.4
- PDF.js version: 2.16.105
- Is a browser extension: no

Steps to reproduce the problem:
1. I have downloaded all the files from pdf.js and put them in a folder in my repository.
2. I call pdf.js from a node script to read and parse a pdf
3. the script throws the error: "loading aborted" (line 1501 in the pdf.js script)
4. Everything goes well with the lib pdf-parse, which uses version 1.10.100 (repo [here](https://gitlab.com/autokent/pdf-parse/-/blob/master/lib/pdf-parse.js)). But i'd prefer to upgrade to your latest version.

Here is my code:

```js
import fs from "fs";
import { getDocument } from "./pdf"; // this calls pdf.js
const pdffile = fs.readFileSync("myFile.pdf");

function renderPage(pageData) {
    return pageData
      .getTextContent({
        normalizeWhitespace: false,
        disableCombineTextItems: false,
      })
      .then((textContent) => {
        let lastY = 0;
        let text = "";
        for (let item of textContent.items) {
          if (lastY == item.transform[5] || !lastY) {
            text += item.str;
          } else {
            text += "\n" + item.str;
          }
          lastY = item.transform[5];
        }
        return text;
      });
  }

async function pdfParser(dataBuffer) {
    try {
      let text = ""
      let doc = await getDocument(dataBuffer);
      //let metaData = await doc.getMetadata(); the function getMetadata doesn't work either. 
  
      for (let i = 1; i <= doc.numPages; i++) {
        let pageText = await doc
          .getPage(i)
          .then((pageData) => renderPage(pageData))
          .catch((_: Error) => null);
  
        text += `\n\n${pageText}`;
      }
  
      doc.destroy();
      return text
    } catch (err) {
      console.error("error", err);
    }
  }

pdfParser(pdffile)
  .then((data) => console.info(data))
  .catch((err: Error) => err);
```

What is the expected behavior?
I should get the text for each page.

What went wrong? (add screenshot)
the process is a bit long, and I get a loading aborted error.

EDIT: I've also tried to remove the line `doc.destroy`, but then I have the error `structuredClone is not defined (line 2555)`.

**Comment by Snuffleupagus** [comment]
Note that code-snippets are not particularly useful, since it's impossible to reproduce your *exact* setup that way; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---
> Everything goes well with the lib pdf-parse, which uses version 1.10.100 (repo [here](https://gitlab.com/autokent/pdf-parse/-/blob/master/lib/pdf-parse.js)).

Sorry, but that's a completely different project that we don't know anything about here and thus can't really help with.

> EDIT: I've also tried to remove the line `doc.destroy`, but then I have the error `structuredClone` is not defined (line 2555).

If `structuredClone` isn't available this would suggest that you don't use a `legacy`-build, which is required in Node.js environments; note e.g. https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and also https://github.com/mozilla/pdfjs-dist/blob/master/README.md (assuming you're using `pdfjs-dist` which isn't at all clear above).

Furthermore, it also looks like you're maybe not correctly awaiting *all promises* involved in the parsing/text-extraction and that you thus end up destroying the document while parsing is still ongoing. In particular, your issue might be related to the mixing of `await` and `then`/`catch` within the loop.
