### ISSUE TITLE
Feature request: Always open PDF in new tab

### ISSUE THREAD

**Issue by verbatim** [mozilla/pdf.js#1554]
There is another PDF viewer/converter (which used to be a very popular Firefox PDF viewer plugin, but seems to have stopped working), which has a preference to "always open PDFs in a new tab".

Possible to add that feature?

**Comment by Rob--W** [comment]
I've received this feature request very often in the Chrome Web Store and elsewhere (I didn't really count, but it's certainly more than I can count on my hands).

Unconditionally opening the PDF in a new tab seems a bit odd though (e.g. imagine a page that embeds 10 PDFs in child frames, that would then open 10 tabs...). How would this "Always open PDFs in a new tab" feature work, ideally?

**Comment by Snuffleupagus** [comment]
Considering that the *built-in* Firefox PDF Viewer doesn't "run" on every web-page, but is rather invoked when a response is deemed to contain a PDF document, I don't believe that we could actually implement something like this in the general case without lots of false positives or possibly other edge-case problems.[1]

Given the above, together with the fact that this hasn't been a commonly requested feature, and finally the age of this issue; let's just close this as WONTFIX now.

---
[1] Just because a link contains a `.pdf` extension, that doesn't guarantee that a PDF document is actually returned by the server. That also applies vice-versa, since a PDF document may be returned by the server despite the link not having a `.pdf` extension.
