### ISSUE TITLE
Error accessing "autoAllocateChunkSize" in PDFJS

### ISSUE THREAD

**Issue by Pierandrei** [mozilla/pdf.js#15556]
i have a new problem after firefox 99 update. I have an extension that reads pdfs using PDFJS (version pdfjs-2.13.216). It always worked and after the last update it started to give: Error: Permission denied to access property "autoAllocateChunkSize" The same extension,  works in chrome normally. Below is the code:

[Code](https://stackoverflow.com/questions/71970222/error-accessing-autoallocatechunksize-in-pdfjs)

The idea of ​​the method is simple, go through the pdf file and return all the text. However now as mentioned the error is generated. Detail that did not generate the error in version 32bit firefox, I believe it started in the last update of firefox 99.

**Comment by Snuffleupagus** [comment]
> i have a new problem after firefox 99 update.

That Firefox version is no longer supported, as far as I know; please update the the latest release.

> version pdfjs-2.13.216

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Error: Permission denied to access property "autoAllocateChunkSize"

Note that there's no property called `autoAllocateChunkSize` anywhere in the PDF.js code-base, see https://github.com/mozilla/pdf.js/search?q=autoAllocateChunkSize&type=code

> Below is the code:

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately isn't really actionable.
