### ISSUE TITLE
Few Form fields are not performing the calculation

### ISSUE THREAD

**Issue by MallRoy** [mozilla/pdf.js#15568]
Link to the PDF file here:
[miscalculation.pdf](https://github.com/mozilla/pdf.js/files/9770820/miscalculation.pdf)

Configuration:
- Web browser and its version: Chrome (106.0.5249.103)
- Operating system and its version: Windows 10
- PDF.js version: 3.0.206
- Is a browser extension: no

Steps to reproduce the problem:
1.  Enter the values as mentioned in the below images. The calculations are not performed on these fields.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/54269166/195503742-164bc22f-0074-4019-a489-ebdfce956a2a.png)

What went wrong?
![image](https://user-images.githubusercontent.com/54269166/195503514-1986be6e-a4e5-49fb-b976-cad3f3b16cb9.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): [Viewer](https://mozilla.github.io/pdf.js/legacy/web/viewer.html)

**Comment by calixteman** [comment]
I think the js code is not correct.
The total expenses is computed thanks to:
```
AFSimple_Calculate("SUM", new Array ("13.0.0.0.0.0.0", "13.0.0.0.0.0.1", "13.0.0.0.0.0.2", "13.0.0.0.0.0.3", "13.0.0.0.0.1.0", \"13.0.0.0.0.1.1", "13.0.0.0.0.1.2", "13.0.0.0.0.2.0", "13.0.0.0.0.2.1", "13.0.0.0.0.2.2"));
```

But the the field 1 on the left has a name equals to "13.0.0.0.0.0.0.0" (there is 7 zeros when the id for the above computations has only 6). This field has a ref equals to 135 and its structure is:
![image](https://user-images.githubusercontent.com/5641725/195557817-f9d5b8be-cfdf-487d-b733-6c234304ed6c.png)
You can see that its name is correctly computed.

In pdfium, they're likely getting the value of the field because they're doing some magic (there is only one field where its name starts with "13.0.0.0.0.0.0"), but in Acrobat the computations are broken (the sum computation is likely aborted just because the first entry is incorrect).

**Comment by Snuffleupagus** [comment]
Given that this is, according to https://github.com/mozilla/pdf.js/issues/15568#issuecomment-1277306812, clearly a case of a broken/corrupt PDF document since even Adobe Reader can't handle it, does it make sense to try and work-around this?

 - Can we easily limit any work-arounds to only broken documents, since we obviously don't want to accidentally break any *properly implemented* JS-code found in other documents?
 - Can a work-around be implemented without "hurting" readability/maintainability/performance of the associated code?
 - Do we expect that this sort of broken JS-code is going to be *somewhat* commonly found in real-world PDF documents?

Unless we can answer all of the above with "yes", should we perhaps WONTFIX this?

**Comment by calixteman** [comment]
I found this version of `AFSimple_Calculate` which contains a `getArray` to get all the terminal children with a value under a given parent:
https://github.com/snwmelt/XPDF/blob/f01fe1f15323a7e18f9f56154be00f66aeaba227/XPDF/Adobe/Acrobat%205.0/Acrobat/Javascripts/aform.js#L861-L862
It's likely why it's working in Chrome.
But in Acrobat, in the JS debugger I can see a lot of `f is null` which could mean that the got field is null !
But according the specs:
https://christianhaider.de/dokuwiki/lib/exe/fetch.php?media=pdf:pdf32000_2008.pdf#page=440&zoom=auto,-411,505
a field doesn't have to have a value it can just contain some kids.
About `getField`, in the specs we have: `Maps a Field object in the PDF document to a JavaScript variable` there is nothing saying that the field must have a value.
Since we don't have any specification for  `AFSimple_Calculate` is hard to say if it expects to have some fields with value or not.

**Comment by calixteman** [comment]
The current implementation of `getArray` is buggy because it only get the kids of a field but not the terminal ones under a parent.
So this bug must be fixed.
And then I guess it doesn't hurt that much to add a `getArray` call in the sum computation, so I'd say we can fix it without having to write crappy workarounds.
