### ISSUE TITLE
Linearized pdf not loading chunk by chunk.

### ISSUE THREAD

**Issue by scauzhangzhimu** [mozilla/pdf.js#15566]
We have a pdf from microsoft office,and then use qpdf --linearize convert to，Display without loading the entire pdf, i.e. load on demand，This is exactly the result I want.

but when we have a doc/docx file from microsoft office,and then use libreoffice7.3 convert to pdf file, and then use qpdf --linearize convert to, At this time, the entire pdf needs to be loaded to display
Can someone give some pointers?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is there's unfortunately no actionable information provided.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
