### ISSUE TITLE
Annotation does not scale on zooming after resize

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#15571]
Attach (recommended) or Link to PDF file here: Any

Configuration:
- Web browser and its version: Firefox 105.0.3
- Operating system and its version: macOS 11.6
- PDF.js version: 3.0.206 (latest demo)
- Is a browser extension: no

Steps to reproduce the problem:
1. Draw some annotation
2. Resize it using the handle
3. Zoom the viewer in/out

What is the expected behavior? (add screenshot)
The annotation should scale with the page.

What went wrong? (add screenshot)
Did not scale.

![zoom-annot](https://user-images.githubusercontent.com/18247990/195622628-2e98b7ff-ee29-4967-918c-ccb1fc3f915e.gif)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

**Comment by calixteman** [comment]
Interesting bug...
I can reproduce it Firefox nightly on mac but not on Windows.

**Comment by shivaprsd** [comment]
I can reproduce it also while zooming when the last annotation is uncommitted. One has to use Cmd/Ctrl +/- to see it, as clicking on the toolbar button commits the annotation before the zoom happens.

**Comment by calixteman** [comment]
The dimensions of an added ink annotation are in `%` and when it's resized (in using the resizer) the dimensions are  of course modified but in `px`.
The `ResizeObserver` is calling `setDimensions`, but the dimensions of the `div` aren't only changed in regard of some conditions:
https://github.com/mozilla/pdf.js/blob/06599f487fc2e939fec4a6fd9e4b543883c7eba7/src/display/editor/ink.js#L697
Consequently, from time to time, the `div` has some dimensions in `px` instead of `%` and finally it isn't correctly rescaled on zoom change.

**Comment by calixteman** [comment]
I filed a bug in Firefox:
https://bugzilla.mozilla.org/show_bug.cgi?id=1795536

**Comment by shivaprsd** [comment]
@calixteman The patch does fix the bug of the first kind, but it still does not fix the second one. Are they both due to [bug 1795536](https://bugzilla.mozilla.org/show_bug.cgi?id=1795536)? But it seems to be an edge case to add too many workarounds.. anyway, my 2c.

**Comment by shivaprsd** [comment]
@calixteman I thought both were due to the same bug, so did not want to open a duplicate issue. Good that you found the causes.
