### ISSUE TITLE
Lines way too thick at small scale (is line thickness a parameter?)

### ISSUE THREAD

**Issue by Triazic** [mozilla/pdf.js#15585]
Attach (recommended) or Link to PDF file here:
I can't - confidential information. 

Configuration:
- Chrome
- Windows 10
- PDF.js version: latest stable
- Is a browser extension: no

What is the expected behavior?
When rendering large pdfs at small scale (ie. to get a thumbnail view), line thickness should be scaled down appropriately. 

What went wrong? (add screenshot)
Instead, we get a big black lump of ink:
![image](https://user-images.githubusercontent.com/38064196/196321289-7d1bf5d2-75fd-4258-99ce-e3cbff1c21d2.png)

Question:
Is there a way I can set line thickness/width to be smaller for my thumbnail views?
Original size is ~3000 x 2000 and I want to render them ~80x80

**Comment by Triazic** [comment]
When converting the full sized canvas renders to rasterised images, much better:
![image](https://user-images.githubusercontent.com/38064196/196325547-88acd305-c53a-42be-95ee-de61d10fe630.png)

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> I can't - confidential information.

That unfortunately means that we cannot help you, since it's completely impossible to debug this (or any other issue really) with nothing more than a screen-shot and without access to the PDF document in question.
Please try and create a *reduced* test-case, without any sensitive information, that you can share here.

> Chrome

*For future reference:* Please include the *version number* as well, since just the browser name isn't really sufficient in general.

> PDF.js version: latest stable

Similarly, please always include the actual *version number* since what "latest" is naturally changes over time.

**Comment by Triazic** [comment]
Fair enough, however I don't have time atm. Using jpgs instead for thumbnails. 
You can achieve this by rendering using pdf.js at a scale of 1, then the following:
`export const getThumbnailFromPDFPage = (canvas: HTMLCanvasElement) => {
	const asDataURL = canvas.toDataURL("image/png").replace("image/png", "image/octet-stream");
	const image = new Image();
	image.src = asDataURL;
	return image;
};`
