### ISSUE TITLE
A page is rendered two times when its thumbnail is visible

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15601]
For visible pages, we should use a downscaled version of the canvas we've for a page in order to render the thumbnail.

**Comment by Snuffleupagus** [comment]
But we already do this, please see:
 - https://github.com/mozilla/pdf.js/blob/36967fcedb150786cdb0f7285800be9b42e98d8e/web/pdf_sidebar.js#L294-L307
 - https://github.com/mozilla/pdf.js/blob/36967fcedb150786cdb0f7285800be9b42e98d8e/web/pdf_thumbnail_view.js#L351-L368

**Comment by calixteman** [comment]
My bad, I saw two calls to `beginDrawing`, probably because of a page resize... and I wrongly attributed the second call to the thumbnail rendering.
So to reproduce, just load this one page pdf:
[tracemonkey_page1.pdf](https://github.com/mozilla/pdf.js/files/9828599/tracemonkey_page1.pdf)
then open the thumbnail view and reload to open the page and the thumbnail at the same time.

If you put a `console.log` in `beginDrawing` you can see it is called two times.

**Comment by calixteman** [comment]
And it's likely because devtools is in the same window, which reduces the viewport size.

**Comment by Snuffleupagus** [comment]
> My bad, I saw two calls to `beginDrawing`, probably because of a page resize...

Yes, that sounds like the correct explanation here.

> If you put a `console.log` in `beginDrawing` you can see it is called two times.

To reproduce this I also need to to set `page-width` as the scale, since otherwise I'm not triggering the two calls (this issue thus depends on things like document dimensions, browser window dimensions, and screen dimensions).

---

Please note that there's actually a few cases where we don't use the page `canvas` for the thumbnail:
 - Pages that are smaller than the thumbnail, to prevent blurriness; see PR #15251.
 - Pages with non-default optional content, which is behaviour similar to e.g. Adobe Reader; see PR #15215.
 - Pages with form fields, to prevent the thumbnail from being partially/completely blank; see PR #15246.
