### ISSUE TITLE
not found adress

### ISSUE THREAD

**Issue by shecong** [mozilla/pdf.js#15600]
![373469eaa89bc3c908dcfc8e1b94f74](https://user-images.githubusercontent.com/49265875/196904945-da6f189d-76a0-40fd-8ee6-e0daf0183274.png)
![4f9f176eaa67cca9dfb1726d7252cea](https://user-images.githubusercontent.com/49265875/196904976-78705466-edbd-4195-ad31-58ef3d32d5af.png)

!!!!you can see it ,item is my e: ,and file is my c:,so when i get files ,it not found a files,please help me!

**Comment by Snuffleupagus** [comment]
You (obviously) cannot load arbitrary *local* files using a web-server, since that'd be a huge security problem; hence it's not really clear what you perceive to be the problem here!?

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since only a couple of screen-shots is nowhere near enough details to make an issue actionable.
