### ISSUE TITLE
Annotation editor cursors have poor visibility over black text/images

### ISSUE THREAD

**Issue by shivaprsd** [mozilla/pdf.js#15611]
Configuration:
- PDF.js version: Latest live demo
- Is a browser extension: No

Steps to reproduce the problem:
1. Enable Ink or Free text editor
2. Hover over dark stuff

What is the expected behavior? (add screenshot)
Cursor should be discernible.

What went wrong? (add screenshot)
![editor-cursor](https://user-images.githubusercontent.com/18247990/197323230-1afaad3f-b844-4835-b6b5-0151bcd49e40.gif)

This is bad for accessibility. Mouse cursors typically have white outline/fill to make them visible on both light and dark backgrounds. The hand cursor used by PDF.js hand tool is a good example.

The pen cursor could be given a white fill. Or, if it clashes with Firefox design philosophy, at least a white outline. Similarly for the I-beam cursor, where white outline is standard.

**Comment by Snuffleupagus** [comment]
Currently we're using the same SVGs for both the toolbar buttons and the cursors, which means that if this issue is deemed necessary to fix we'd need new (and separate) SVGs to use specifically for the cursors.

**Comment by shivaprsd** [comment]
> Currently we're using the same SVGs for both the toolbar buttons and the cursors

I think they are now different for the Ink editor.

> we'd need new (and separate) SVGs to use specifically for the cursors

I guess this was the case with the hand tool. I can see a `grab.cur` and `grabbing.cur` files in the stable builds, but they are no longer referenced anywhere in code. Another question is whether to .cur is a more appropriate format.

**Comment by Snuffleupagus** [comment]
> I think they are now different for the Ink editor.

Apparently it varies, so we'd need an *updated* ink-cursor and a *new* freetext-cursor in order to address this: https://github.com/mozilla/pdf.js/blob/f5711fc385bc643a2f27343f160c04f11a3497be/web/annotation_editor_layer_builder.css#L25-L26

> I guess this was the case with the hand tool. I can see a `grab.cur` and `grabbing.cur` files in the stable builds,

That was only done as a *fallback* (since removed), for older browsers without native support for the relevant cursors; hence this isn't entirely relevant to this issue (since we're using completely custom icons with the editor).

> Another question is whether to .cur is a more appropriate format.

Given that the files are actually SVGs, and the `.cur`-format is something different, I don't think that'd correct here.

**Comment by calixteman** [comment]
I pinged UX about this issue.
