### ISSUE TITLE
Scroll Position change to top of Canvas upon page change

### ISSUE THREAD

**Issue by chdonncha** [mozilla/pdf.js#15628]
Rather than the default of the scroll positioning remaining the same on a re-render upon a page change, is it possible to change the scroll position of the PDF back to the top of the canvas?

So what I would like to expect is that upon any page change the new default scroll position will be always from the top of that page.

**Comment by Snuffleupagus** [comment]
> Rather than the default of the scroll positioning remaining the same on a re-render upon a page change, is it possible to change the scroll position of the PDF back to the top of the canvas?

Well, most things are possible with source-code modifications :-)

To do so, either commenting-out or removing the following lines should probably do the trick:
https://github.com/mozilla/pdf.js/blob/9a33a0fba9e08bcf1fcd95d315de83fe7a6443d1/web/pdf_viewer.js#L1090-L1102

Please note that the current behaviour was *purposely* implemented, since in many/most use-cases resetting the scroll-position on zooming isn't helpful.
