### ISSUE TITLE
[Feature] Center pages vertically in Page Scrolling Mode

### ISSUE THREAD

**Issue by jaime-rivas** [mozilla/pdf.js#15622]
Hello,

Adobe Reader centers the pages in Page Scrolling Mode (Fit One Full Page in their UI) and I think it is good for user experience and usability, so I'm writing to suggest adding this option to PDF.js as well. Maybe some of the work done here #14298 can be used here too. Thank you!

![image](https://user-images.githubusercontent.com/19812916/197731106-83b2b57d-50b3-470a-8f87-f4d7effc887b.png)

**Comment by Snuffleupagus** [comment]
> Adobe Reader centers the pages in Page Scrolling Mode (Fit One Full Page in their UI) and I think it is good for user experience and usability,

I've always found that the page physically moving when zooming out felt a little "jarring", so personally I'm not finding that behaviour better.
Hence I'm not convinced that this is a desirable change, and there's also bound to be edge-cases to consider that'd might make this a lot less straightforward than you probably think (e.g. will general scrolling and spreadModes still work correctly).

> Maybe some of the work done here #14298 can be used here too.

That case is (slightly) simpler since PresentationMode doesn't allow *any* scrolling, which reduces the overall complexity.
