### ISSUE TITLE
Error when dragging and dropping a non-pdf file into the viewer

### ISSUE THREAD

**Issue by Oasan01** [mozilla/pdf.js#15639]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome 106.0.5249.119
- Operating system and its version: Windows 10 Pro
- PDF.js version: v2.9.359
- Is a browser extension: No

Steps to reproduce the problem:
1.  open the application
2. load pdf file by default
3. Drag a different file to pdf for example word
4. An error is generated in the viewer

What is the expected behavior? (add screenshot)
It is expected to display an alert saying that the format is not supported and do not remove the preloaded file
![image](https://user-images.githubusercontent.com/54637072/198737494-2b3eaed1-97c2-40eb-a858-3e3be8f82b0f.png)

What went wrong? (add screenshot)
When trying to drag a file that is not a pdf, I generate an error in the viewer
![image](https://user-images.githubusercontent.com/54637072/198737718-df7da262-3af3-4279-bdb7-47241d56f3b5.png)

ERROR
![image](https://user-images.githubusercontent.com/54637072/198737835-11b878be-2fe6-485d-9778-2be78f74bb97.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: v2.9.359

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> It is expected to display an alert saying that the format is not supported and do not remove the preloaded file

Given that a PDF document may use an incorrect file extension, but still be a valid PDF document, we need to actually try and open it in order to correctly determine if (or if not) it's in fact valid. In order to (significantly) simplify the overall viewer implementation, and keeping in mind that only the GENERIC viewer supports opening more than one document, we thus close an existing document *before* trying to open the new one. Hence this is working as expected/intended here.

You may change any of the above in your deployment of the viewer, however it's not really something that we'll consider doing here unfortunately; please also see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
