### ISSUE TITLE
mozilla.github.io is not available

### ISSUE THREAD

**Issue by KeremArdicli** [mozilla/pdf.js#15645]
mozilla.github.io/pdf.js is not available for me in Turkey now. Is this a general issue or specific to me?

**Comment by Snuffleupagus** [comment]
WFM too, when connecting from Sweden. Looking at https://www.githubstatus.com/ nothing appears generally broken either.

Please keep in mind that http://mozilla.github.io/pdf.js/ is hosted by GitHub, so any further questions on this matter would need to be directed to GitHub support since we cannot help with that here.
