### ISSUE TITLE
How to extract / save images (jpeg, png etc.) from PDF without using node-canvas

### ISSUE THREAD

**Issue by GitMurf** [mozilla/pdf.js#15684]
Configuration:
- Web browser and its version: N/S
- Operating system and its version: Windows 11
- PDF.js version: 3.0.279
- Is a browser extension: No

Steps to reproduce the problem:

I am not able to use node-canvas for a variety of reasons but the simple reason is Electron does not play nicely with node-canvas since it is a native node module (among other reasons). One of my main use cases for pdf.js is to extract images from within PDFs and save them to file as PNG or JPEG (doesn't really matter). But the problem is that the `image.data` that comes from pdf.js `page.objs.get()` appears to be some sort of binary data that I cannot decode/"convert" to save as an image file. All the examples I see use Canvas / context to create a 2D canvas from the `image.data` binary which then can be converted and saved as a PNG. Is there a way to do this without using Canvas?

Essentially is there another way (without using Canvas) for pdf.js to allow for `image.data` from image objects within a PDF to be saved to PNG/JPEG files?

**Comment by Snuffleupagus** [comment]
The following function could perhaps help, although please keep in mind that the SVG back-end (and thus also this code) is no longer being maintained:
https://github.com/mozilla/pdf.js/blob/2d1b1e79685bc9c432395c612b6562dc76898486/src/display/svg.js#L81-L322

**Comment by GitMurf** [comment]
@Snuffleupagus thank you so much for pointing me here! I think this is promising. Is there a reason the SVG back-end (and this code above) is no longer being maintained? Has its functionality being replaced by Canvas or something?

**Comment by GitMurf** [comment]
@Snuffleupagus one further follow-up question. Similarly to my request above to save images as PNG without using node-canvas, is there a way I can convert/save each PDF page to PNG (or jpeg) without using node-canvas? Thanks so much!

**Comment by Snuffleupagus** [comment]
> is there a way I can convert/save each PDF page to PNG (or jpeg) without using node-canvas?

Not that I know of, since the PDF.js library is primarily intended for usage in browsers (with the Firefox PDF Viewer being the *primary* development target). For Node.js usage we assume that `node-canvas` is being used, since even the existing Node.js support takes a fair amount of time/effort to keep working (which is nowadays only done by *unpaid* contributors such as myself).

(Although this question seem *somewhat* orthogonal to the issue as filed...)

**Comment by GitMurf** [comment]
@Snuffleupagus i appreciate all your continued support especially as I know you are just a volunteer not being compensated. Would you be interested in me paying you to help come up with a solution to either of the following (preferably #2):

1) get PDF pages to be saved to PNG without requiring node-canvas (as it will not work with Electron currently)

OR

2) identifying why Electron and pdf.js is not full working when node-canvas is being used and coming up with a solution to get it to work with Electron

Feel free to DM me if that is more appropriate. Also if any other contributors or community members are interesting let me know.

thanks!

**Comment by Snuffleupagus** [comment]
> 1. get PDF pages to be saved to PNG without requiring node-canvas (as it will not work with Electron currently)

I'd consider this a non-starter, since assuming that you even could (somehow) get that to work it's way too much of an edge-case that's not at all relevant to the main PDF.js library and the amount of work required would be *very significant*.
Please keep in mind that every feature needs to be implemented, reviewed, and (automatically) tested. Then you'd have to maintain it, and provide support for it, potentially for many years which is the hard part (all for code we don't actually use).

> 2. identifying why Electron and pdf.js is not full working when node-canvas is being used and coming up with a solution to get it to work with Electron

That'd be the only reasonable way forward, as far as I'm concerned. However please keep in mind that we don't support Electron, or any framework really, here so we can't help with that unfortunately. (Personally, I've never used Electron myself.)

**Comment by GitMurf** [comment]
FYI this has been solved with node-canvas moving to node-addon-api recently!🎉 See PR here: https://github.com/Automattic/node-canvas/pull/2235 

So can go back to using things "out of the box" :)
