### ISSUE TITLE
How to set up underline for link in PDF.js?

### ISSUE THREAD

**Issue by can2000ca** [mozilla/pdf.js#15696]
It looks like if I changed the link style (color or underline etc) in annotationLayer, there is no affect.  
If changed in textLayer, it affected. 
Any help could be appreciated. Thanks

**Comment by Snuffleupagus** [comment]
Please keep in mind that this is first and foremost a *bug tracker*, rather than a support forum.

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
