### ISSUE TITLE
pdfjs page view data not correct

### ISSUE THREAD

**Issue by suyue0731** [mozilla/pdf.js#15704]
Attach (recommended) or Link to PDF file here:
here is my pdf, was generated by puppeteer with A4 format
[a4.pdf](https://github.com/mozilla/pdf.js/files/10028817/a4.pdf)

Configuration:
- Web browser and its version: chrome  107.0.5304.110
- Operating system and its version: macOS Big Sur 11.3.1
- PDF.js version: pdfjs-dist@2.12.313
- Is a browser extension: no

Steps to reproduce the problem:

1. use pdfjs to load this pdf, then execute pdf.getPage(pageIndex).then((page) => console.log(page.view))

What is the expected behavior? (add screenshot)

expected page.view is [0, 0, 794, 1123] // A4 paper pixel size

What went wrong? (add screenshot)

got 
![image](https://user-images.githubusercontent.com/18397351/202351891-06847b09-6f30-4cb9-a87f-00bd8df2977b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
no

**Comment by suyue0731** [comment]
> 

so, the unit of page.view is pt?
I was misleading by another issue, https://github.com/mozilla/pdf.js/issues/9408#issuecomment-520932114, where he said the unit is pixel

**Comment by Snuffleupagus** [comment]
> PDF.js version: pdfjs-dist@2.12.313

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> expected page.view is [0, 0, 794, 1123] // A4 paper pixel size

Then your expectation is unfortunately incorrect, since this getter returns the value of the `/MediaBox`-entry as found in the PDF document itself (and nothing else). To convert those values to inches, see e.g. https://github.com/mozilla/pdf.js/blob/c7d6ab2f7123c5a65155c55aa19d9d9abd8c2ff2/web/ui_utils.js#L328-L345 which expects a `PDFPageView`-instance as its argument (those results may be converted to millimetres by multiplying with `25.4` as usual).

Closing as answered, since there's no bug here.
