### ISSUE TITLE
Remove useless (?) check in ui_utils::scrollIntoView

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15714]
Checking for `hidden:
https://github.com/mozilla/pdf.js/blob/ae7c97aef81aa2934fbbbdc4a5511e0b274e086a/web/ui_utils.js#L131
has been added in:
https://github.com/mozilla/pdf.js/pull/5356
The original bug should have been fixed thanks to:
https://github.com/mozilla/pdf.js/pull/14564
Consequently, we could maybe revert this change and its follow-up (https://github.com/mozilla/pdf.js/pull/6524).

**Comment by Snuffleupagus** [comment]
Have you checked that reverting this doesn't regress issue #5355, and scrolling of search results in general?

Note also that while this particular check may no longer be necessary, I do believe that we still need to keep the `scrollMatches` parameter such that we can handle documents with markedContent correctly; please see [bug 1714183](https://bugzilla.mozilla.org/show_bug.cgi?id=1714183).

**Comment by Snuffleupagus** [comment]
Please note that this was reverted in PR #15740, since it apparently broke Chromium-based browsers.

We could *potentially* attempt a slightly different fix later (after the upcoming release), to at least get rid of the `getComputedStyle` call, see https://github.com/mozilla/pdf.js/pull/15740#discussion_r1031416127.
