### ISSUE TITLE
pagechanging event fired multiple times in Presentation Mode

### ISSUE THREAD

**Issue by tstibbs** [mozilla/pdf.js#15745]
### Configuration:
- Web browser and its version: Chrome 107.0.5304.107 64-bit
- Operating system and its version: Windows 10
- PDF.js version: 3.0.279 probably? Whichever version was deployed on https://mozilla.github.io/pdf.js/web/viewer.html on 25/11/2022 at 0800 UTC (console log outputs `PDF 110dd61fd57444010b1ab5ff38782f0f [1.4 pdfeTeX-1.21a / TeX] (PDF.js: 3.1.75 [8fda3f04f])`)
- Is a browser extension: no

### Steps to reproduce the problem:
1. Open https://mozilla.github.io/pdf.js/web/viewer.html in Chrome
1. Open dev tools (F12)
1. Execute the following in the console:
    ```
    PDFViewerApplication.eventBus.on('pagechanging', evt => {
	    console.log(`pagechanging: ${evt.previous} -> ${evt.pageNumber}`)
    })
    ```
1. Open presentation mode
1. Change page (by cliking or using the arrow keys)

### What is the expected behavior?

In both presentation mode and 'normal' mode, you would expect a single event to be fired for each page change (resulting in a single console log for each page from our test code), e.g.:
```
pagechanging: 1 -> 2
```

### What went wrong?

In presentation mode, three events are fired each time the user changes a page. E.g. for a change from page 1 to 2, the console output from our test code looks like this:
```
pagechanging: 1 -> 2
pagechanging: 2 -> 1
pagechanging: 1 -> 2
```

Note that this is not consistent with non-presentation mode, where behaviour is as expected.

### Notes

I'm unclear what, if any, impact this has on the core pdf.js library, however for anyone who's building on top of this library/viewer and relying on this event to trigger other behaviours, it causes a problem. My use-case is that I use these events to detect page changed, then push an event to a websocket which in turn causes other clients to change their page in response. Because any network connections are inherently async, rapidly changing events such as these can end up out of order, leading to incorrect behaviour even though the last event fired appears to be correct. Of course I could implement a workaround (e.g. debounce the events or enforce some kind of message ordering) but I'm flagging as a bug anyway as I doubt this is intended behaviour.

**Comment by Snuffleupagus** [comment]
> In presentation mode, three events are fired each time the user changes a page.

The explanation here would be that PresentationMode is "special" in various ways, in particular that it will always fit (and center) the page to the available screen-size. Hence there's an additional scale-change during page switching in PresentationMode, which doesn't happen normally in the viewer.

Given that this, as far as I'm concerned, is a mere inconsistency (for non-primary UI) rather than an actual bug, in combination with the relevant code being both old and quite complex[1] it doesn't seem worth the overall regression risk to attempt to address this minor issue here unfortunately. Hence closing this as WONTFIX.

Finally, please also note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---
[1] Given the many different cases it has to content with, such as e.g. varying Scroll/Spread modes.
