### ISSUE TITLE
Wrong color rendering on macOS Safari

### ISSUE THREAD

**Issue by bensmrs** [mozilla/pdf.js#15756]
[Faulty PDF here](https://github.com/overleaf/overleaf/files/10104304/latex_bug.pdf)

Configuration:
- Web browser and its version: Safari 16.1
- Operating system and its version: macOS 13.0.1
- PDF.js version: online demo (`pdfjsLib.version` says 3.2.9)
- Is a browser extension: no

Steps to reproduce the problem:
1. Open the given PDF using PDF.js on Safari

What is the expected behavior?
The viewer should show two black stripes around a blue one
![Two black stripes around a blue one](https://user-images.githubusercontent.com/25688414/200596828-9ff74935-9e3a-45e1-a904-d26ef175140e.png)

What went wrong?
The viewer displays the third stripe in blue instead of black
![The last stripe has the wrong color](https://user-images.githubusercontent.com/25688414/200596902-7aa2e94f-eaa4-4a4f-914a-0af0cb4cd130.png)

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js `3.1.73` [823723121] in Firefox Nightly 109 on Windows.
Also WFM, using PDF.js `3.2.9` [8bac57172] (i.e. https://mozilla.github.io/pdf.js/web/viewer.html) in Google Chrome Beta 108 on Windows.

If this is specific to Safari that unfortunately suggests a *browser bug*, e.g. `canvas`-related, since otherwise you'd expect it to be consistently broken everywhere. (Please keep in mind that the Firefox PDF Viewer is the primary development target here).
Most likely, you'll need to report this to the Safari developers instead.
