### ISSUE TITLE
Field isn't updated, if you reenter value, that was there when you opened PDF

### ISSUE THREAD

**Issue by Azarchaniel** [mozilla/pdf.js#15753]
Hey,
we have encountered an error with PDF.js. We were able to duplicate it and prepared little demonstration. In the attached PDF, there are two fields: "field1" labeled "Origin field" and "field2" labeled "Calculated field". "field2" takes value from "field1". Now to problem:

HOW TO REPLICATE:
Open PDF in PDF.js. In the field “field1” enter value, let’s say “24”. The fields are calculated. Save the PDF and close. Open it again. In the field “field1“ change the value to “48”. The fields are calculated. Now change it back to “24”. The fields won’t calculate.
Tested in Safari, Firefox, Chrome & Win10, MacOS.

EXPECTED BEHAVIOR:
Calculate every field no matter what was initial value.

[error.pdf](https://github.com/mozilla/pdf.js/files/10101473/error.pdf)

**Comment by Azarchaniel** [comment]
**Config:**
Browser: Firefox Developer 108.0b5 / Google Chrome 107.0.5304.108
OS: Windows 10 Pro 21H2 (also tested on Mac and Safari, but can't get versions now)
PDF.js version: "pdfjs-dist": "2.16.105",
Is a browser extension: No

**Comment by Snuffleupagus** [comment]
> PDF.js version: "pdfjs-dist": "2.16.105",

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by donarus** [comment]
I have REPRODUCED it using 2.16.05 but also using the latest master branch


```
git clone https://github.com/mozilla/pdf.js.git # clone official pdf.js master source code
npm install -g gulp-cli
npm install
gulp server
```

```
cd test/pdfs
wget https://github.com/mozilla/pdf.js/files/10101473/error.pdf
mv error.pdf issue15753.pdf
```

in firefox open http://localhost:8888/web/viewer.html?file=/test/pdfs/issue15753.pdf

![image](https://user-images.githubusercontent.com/1846145/204293377-d2ad3fd5-faf1-48ee-a213-e64752e0d00d.png)

in the "origin field" enter for example XXX and hit enter
![image](https://user-images.githubusercontent.com/1846145/204293426-dd990037-1863-4a0f-9da9-39ca8d7f8bb2.png)

then modify the string to something not-empty again (eg XXXYYY)
![image](https://user-images.githubusercontent.com/1846145/204294090-e96fb6d1-1e6d-40f6-ba00-91b30ee40bcb.png)

then delete all the content of the "origin field" (so put empty string in it) and hit enter ... nothing happens to the second (Calculated field) ... also try to focus (click) the second (calculated field) .. still nothing happens .. field is not recalculated
![image](https://user-images.githubusercontent.com/1846145/204294509-e556dd7a-a6fd-438c-8301-a963c24a68c0.png)


what is even weirder is that when I just change the focus instead of hitting the "ENTER" key, it seems it works.

sharing a video

when hitting  enter


https://user-images.githubusercontent.com/1846145/204296601-c2551d8d-ddbc-4870-af24-bc34263fef5b.mov


when using focus



https://user-images.githubusercontent.com/1846145/204296654-235c2359-2c6b-4a0c-8f9a-2ff6eb467dbc.mov
