### ISSUE TITLE
Error: DOMMatrix is not constructor.

### ISSUE THREAD

**Issue by YuriiShyshkin** [mozilla/pdf.js#15783]
Attach (recommended) or Link to PDF file here: for compliance reasons we cannot provide pdf file.

Configuration:
- Web browser and its version: Google Chrome, Version 108.0.5359.95 (Official Build) (64-bit);
- Operating system and its version: Windows 10 Enterprise Version: 21H1;
- PDF.js version: v3.1.81;
- Is a browser extension: no.

Steps to reproduce the problem:
1.  Render pdf file;
2.  Receive following error in DevTools:  
![DOMMatrixIsNotConstructor](https://user-images.githubusercontent.com/115140037/205624898-30c45c40-e4c1-447e-9d82-f5e7ff3d9554.png)

_What is the expected behavior?_ 
There should not be error.

_What went wrong?_
The error occurs in following line:
 ![image](https://user-images.githubusercontent.com/115140037/205625223-1854c952-2d8f-47fd-b8b8-d32b081b2717.png)

Workaround: 
If call WebKitCSSMatrix() constructor ([link](https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix#:~:text=the%20DOMMatrixReadOnly%20interface.-,WebKitCSSMatrix,-is%20an%20alias)) instead of DOMMatrix everything works fine.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: for compliance reasons we cannot provide pdf file.

That unfortunately means that the issue isn't actionable, since a test-case is *always* required.

> Web browser and its version: Google Chrome, Version 108.0.5359.95 (Official Build) (64-bit)

According to https://developer.mozilla.org/en-US/docs/Web/API/DOMMatrix/DOMMatrix#browser_compatibility this should be supported in that browser.

---

Testing `issue6006.pdf` from the test-suite locally, using http://localhost:8888/web/viewer.html?file=/test/pdfs/issue6006.pdf, works for me in both Mozilla Firefox Nightly 109 and Google Chrome Beta 109.

**Comment by YuriiShyshkin** [comment]
@Snuffleupagus Thanks for the quick reply.

Unfortunately, we cannot provide you with PDF file.

The possible workaround is to call WebKitCSSMatrix() constructor instead of DOMMatrix() constructor.
Old version:
![image](https://user-images.githubusercontent.com/115140037/205640616-71b1e5b4-6e4d-4599-b7bc-01c8c2781077.png)
New version: 
![image](https://user-images.githubusercontent.com/115140037/205640721-64a4c935-cdd8-4321-b6c9-e92b3869dd82.png)

Does calling WebKitCSSMatrix() constructor instead of DOMMatrix() constructor have negative affect on your logic?

**Comment by Snuffleupagus** [comment]
> Does calling WebKitCSSMatrix() constructor instead of DOMMatrix() constructor have negative affect on your logic?

First of all, that could break every non-Webkit browser so it's *obviously not* an acceptable change here.
Secondly, we generally don't accept browser-specific compatibility hacks in the main code-base (with compatibility code placed in a separate file).

However, as already mentioned in https://github.com/mozilla/pdf.js/issues/15783#issuecomment-1337261825 this isn't actionable as-is *and* when I tested a PDF document that exercises this code-path everything worked in Google Chrome as well.

**Comment by YuriiShyshkin** [comment]
We've tested with `issue6006.pdf` file and it doesn't work for us as well.

![image](https://user-images.githubusercontent.com/115140037/205643731-11d73814-41f8-4be3-990a-97b38ad2fe8e.png)

Could you advise something?

**Comment by Snuffleupagus** [comment]
Have you tried opening either PDF document with our demo viewer, using e.g. drag-and-drop, at https://mozilla.github.io/pdf.js/web/viewer.html?

Assuming that there's perhaps something wrong with your particular implementation, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> Could you advise something?

Not unless you provide a lot more information here, unfortunately. Please keep in mind that this is first-and-foremost an open-source *bug tracker*, frequented by unpaid volunteers (such as myself), rather than paid support.
