### ISSUE TITLE
pdfjs.GlobalWorkerOptions undefined in webpack.js file using 'pdfjs-dist/webpack' import

### ISSUE THREAD

**Issue by 21Kaen** [mozilla/pdf.js#15799]
Got this problem. Using import * as pdfjsLib from 'pdfjs-dist/webpack' and webpack 5:
   
Uncaught TypeError: Cannot set property 'workerPort' of undefined at Module../node_modules/pdfjs-dist/webpack.js

In webpack.js :
var pdfjs = __webpack_require__(/*! ./build/pdf.js */ "./node_modules/pdfjs-dist/build/pdf.js");

if (typeof window !== "undefined" && "Worker" in window) {
  pdfjs.GlobalWorkerOptions.workerPort = new Worker(new URL(/* worker import */ __webpack_require__.p + __webpack_require__.u("vendors-node_modules_pdfjs-dist_build_pdf_worker_js"), __webpack_require__.b));
}

How can i solve it?

**Comment by Snuffleupagus** [comment]
Please note that we cannot provide (detailed) support for any JavaScript frameworks here.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this unfortunately isn't really actionable.

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by 21Kaen** [comment]
description edited
