### ISSUE TITLE
How can I re-render annotation?

### ISSUE THREAD

**Issue by OnlY0226** [mozilla/pdf.js#15793]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/legacy/web/viewer.html

Steps to reproduce the problem:
1.  add annotation on page
2.  re-open page

What is the expected behavior? (add screenshot)
re-open page with annotations

**Comment by Snuffleupagus** [comment]
You (obviously) need to save the changes, since it's not really possible to just modify a file directly from a web-app. Hence clicking on the "Save"-button on the right-hand side of the toolbar will prompt you to download the modified PDF document.

This can also be triggered programmatically, see also https://github.com/mozilla/pdf.js/blob/c63906305055d27380ba2f94099a9fe9bb4c1017/web/app.js#L980-L1012 which invokes the following API-method https://github.com/mozilla/pdf.js/blob/c63906305055d27380ba2f94099a9fe9bb4c1017/src/display/api.js#L985-L991
