### ISSUE TITLE
Investigate if you should get rid of streaming the text content

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#15808]
Now we get the text content only on page creation, I'm not sure that it sill makes sense to keep this stuff.
Likely it'll reduce the code complexity and I wonder (I've no idea/opinion for the moment) if it could improve performance.

**Comment by Snuffleupagus** [comment]
But why, since it will in all likelihood *reduce* overall performance and responsiveness!

Please keep in mind that streaming allows the textLayer to be parsed (on the worker-thread) and laid-out/rendered (on the main-thread) *in chunks*, rather than all at once[1]. That means that we're still able to parse/render other things, e.g. the next page, in "parallel" with any textLayer parsing/rendering.

---
[1] This was exactly *why* streaming was introduced in the first place.

**Comment by Snuffleupagus** [comment]
To summarize what this proposal would do:
 - It would layout/render the entire textLayer *all at once*, which could easily end up causing jank and/or noticeable delays if there's a very large number of textLayer-elements on the page.
 - It would lose the ability to abort the worker-thread parsing, which `ReadableStream`s gives us essentially "for free" here.

Sorry if I'm sounding a bit grumpy here, but I really cannot see any way that I'd approve a patch that removes streaming of textContent.

**Comment by calixteman** [comment]
I've no patch and I've no plan to write one, I'm just wondering.
And a good argument (like the one about aborting a page rendering)  could lead me to "Don't think about that it's stupid".
It's because I don't want to waste my time on trying something stupid/useless, I'm opening this issue: just to collect some pros/cons.
