### ISSUE TITLE
Wrong rendering: white page

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#15853]
Attach (recommended) or Link to PDF file here: [test2.pdf](https://github.com/mozilla/pdf.js/files/10256841/test2.pdf)

Configuration:
- Web browser and its version: Safari 15.6.1
- Operating system and its version: macOS 12.6.1
- PDF.js version: 3.1.81
- Is a browser extension: no

Steps to reproduce the problem:
1.  open the attached PDF using pdfJsLib;
2.  render its first page.

What is the expected behavior? (add screenshot)
![chrome](https://user-images.githubusercontent.com/18655020/208371367-c31e6164-8495-4b77-a4f7-62ee2000cffd.png)

What went wrong? (add screenshot)
![safari](https://user-images.githubusercontent.com/18655020/208371336-a6da59a8-e7aa-464e-93c6-03dabe2c9f7e.png)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Safari 15.6.1

WFM, when opening it with https://mozilla.github.io/pdf.js/web/viewer.html in either Firefox Nightly 110 or Chrome Beta 109.

If this is specific to Safari that unfortunately suggests a *browser-specific* bug, rather than a general PDF.js one, since otherwise you'd expect it to be consistently broken everywhere.
Please report this as a `canvas`-related bug to the Safari developers instead, since this unfortunately doesn't look fixable here.
