### ISSUE TITLE
URL sheme "file" is not supported when fetching cmaps files

### ISSUE THREAD

**Issue by tamlok** [mozilla/pdf.js#15877]
Hi,

I am the author of VNote which will embed a local pdf.js lib to view the PDF file. As we do not hold any http server, we use the lib via "file:///xxxx/pdf.js" URL. Everything goes well except for the cmaps files. Is there any hard limit to not supporting "file" shceme here?

```
pdf.worker.js:12011 Fetch API cannot load file:///C:/Users/tanle/AppData/Roaming/VNote/VNote/web/pdf.js/web/cmaps/GBK-EUC-H.bcmap. URL scheme "file" is not supported.
fetchBuiltInCMap @ pdf.worker.js:12011
```

Thanks!

**Comment by Snuffleupagus** [comment]
> I am the author of VNote which will embed a local pdf.js lib to view the PDF file.

We have no idea what that is, and in general please remember to fill out the ISSUE_TEMPLATE when opening an issue.

> As we do not hold any http server, we use the lib via "file:///xxxx/pdf.js" URL.

As mentioned in https://github.com/mozilla/pdf.js#getting-the-code you need to use a web-server in order for things to work, in general, since the `file://`-protocol may cause problems.

> Is there any hard limit to not supporting "file" shceme here?

That's a limitation of the Fetch API itself, and it has nothing to do with the PDF.js library. You might want to try to *disable* `useWorkerFetch` when calling `getDocument`, see https://github.com/mozilla/pdf.js/blob/3fd2a35482a03e4f07fe0be7ce9e49900dd7c980/src/display/api.js#L178-L181, however as already mentioned there's no guarantee that it'll work.

**Comment by tamlok** [comment]
Thanks! It works now!

**Comment by malgee012** [comment]
> Thanks! It works now!

How to solve it
