### ISSUE TITLE
Building pdfjs-dist version 2.16.105 failed

### ISSUE THREAD

**Issue by roeycollignon** [mozilla/pdf.js#15889]
# Details
Failed to build `pdfjs-dist@2.16.105` because the bundle contains modern ES features such as private class fields (`#` syntax).
Only a minor version was bumped but got a breaking change in our build process.

Error:
```
ERROR in ./node_modules/pdfjs-dist/build/pdf.js 1413:9
Module parse failed: Unexpected character '#' (1413:9)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
| class PDFDocumentLoadingTask {
>   static #docId = 0;
|
|   constructor() {
```

Configuration:
- PDF.js version: 2.16.105
- Webpack: v4.46.0
- babel: v7.6.0

Steps to reproduce the problem:
1. Create a simple webpack 4 + babel 7 configuration (without private class fields support)
2. install `pdfjs-dist@2.16.105`
3. import the package and run build
4. the error should surface

What is the expected behavior? (add screenshot)
Build should work without transpiling the library through babel and without private fields support.

What went wrong? (add screenshot)
Build error from babel with a unexpected character

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.16.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

---

It sounds like you should use a `legacy`-build instead, since that one is already transpiled with Babel; note that we mentioned the `legacy`-build in both https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and https://github.com/mozilla/pdfjs-dist/blob/master/README.md

**Comment by Fuphoenixes** [comment]
import * as PDFJS from 'pdfjs-dist/legacy/build/pdf'
