### ISSUE TITLE
Password protected PDF file seems blank

### ISSUE THREAD

**Issue by sabriunal** [mozilla/pdf.js#15893]
Configuration:
- Mozilla Firefox 108.1 from PPA
- Ubuntu 22.04.1
- PDF.js version: I don't know
- Is a browser extension: No

Steps to reproduce the problem:
1. Download (removed) file.
2. Try to open with Firefox

What is the expected behavior?  Show the password protected file.
What went wrong? Showed two blank pages without any indication about the password protection.

I have tested with some application:
- Chrome: Requested pasword and viewed the file mean OK.
- KOReader: OK.
- Ongoogled Chromium: OK.
- Sioyek: OK.
- Master PDF Editor: OK.
- Firefox: Failed.
- Okular: Failed.
- LibreOffice: Failed.

**Comment by Snuffleupagus** [comment]
That's a really corrupt PDF document, since it's basically two different PDFs placed in the same file.

Furthermore, the actual password doesn't seem to be included anywhere (that I can find) in https://github.com/mozilla/pdf.js/issues/15893#issue-1519539310, so it's somewhat difficult to know how other viewers render the document.

**Comment by sabriunal** [comment]
I mailed the password to your email.

**Comment by sabriunal** [comment]
The password is Three Seven Six Five Three Eight Two Four. Convert to number ;)

**Comment by Snuffleupagus** [comment]
I would like to point out, since this PDF document contains sensitive data, that it's actually possible to access its contents *without* a password if you e.g. edit the file manually (by removing the "second" PDF document within the file) or by modifying how a PDF viewer (such as PDF.js) accesses the objects within the document.

Hence it would appear that, for anyone knowledgeable about the inner workings of PDF documents, you've unfortunately made this sensitive data available to the world by posting your document here.

**Comment by sabriunal** [comment]
If you downloaded it, I can delete it.

Jonas Jenwald ***@***.***>, 5 Oca 2023 Per, 00:53 tarihinde
şunu yazdı:

**Comment by Snuffleupagus** [comment]
> If you downloaded it, I can delete it.

Please note that we unfortunately *need* to be able to add test-cases when fixing this sort of bug, given what part of the code-base it touches, and the sort of PDF corruption that we're dealing with here is very difficult to re-create manually.

Hence, if we can't use this document for the test-suite it's not entirely clear (at least to me) that we can fix this unfortunately :-(
@calixteman What should we do in this case, since I really don't like the idea of submitting a patch that adds a bunch of additional complexity to `XRef.indexObjects` without it being covered by any tests.

**Comment by calixteman** [comment]
@Snuffleupagus I fully agree with you.
Would it be possible to replace the text data by "aaaa...." ?

**Comment by Snuffleupagus** [comment]
> Would it be possible to replace the text data by "aaaa...." ?

Perhaps in theory, but it seems that all sensitive data is found in `streams` and stubbing those out manually with dummy-data (of the correct length and filter-type) seems like a very slow and tedious process unfortunately.

**Comment by calixteman** [comment]
@sabriunal would you be able to provide a similar pdf but without any sensitive data ?

**Comment by sabriunal** [comment]
I can provide my file but it contains my National Id number and my credit score. Is there any way to remove them from the PDF without damaging data?
