### ISSUE TITLE
Safari 14 on iOS 16+ blocks execution for complexes PDFs

### ISSUE THREAD

**Issue by seb-montana** [mozilla/pdf.js#15919]
Attach (recommended) or Link to PDF file here:
This is an PDF example : [https://static.app-elly.fr/test-bug-pdf-viewer.pdf](https://static.app-elly.fr/test-bug-pdf-viewer.pdf)

### Environment
- Web browser and its version: Safari 14
- Operating system and its version: iOS 16+
- PDF.js version: 2.16.105
- Is a browser extension: no, used with react-pdf

### Description

When we use complexes PDFs, with lot of vectors, only on Safari on iOS 16+, processus seems to be stopped  (no error in console).
I think Safari prevents performance degradation for save iPhone battery.

Any idea ?

Thanks,

### Steps to reproduce

https://mozilla.github.io/pdf.js/web/viewer.html?file=https://static.app-elly.fr/test-bug-pdf-viewer.pdf
Maybe reload one or two times.
Bug appends on iPhone iOS 16+
Bug appends on xCode Simulator iPhone iOS 16+

### Expected behavior

Process not blocked, maybe optimized.

### Actual behavior

Process blocked by Safari (no error in console)

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.16.105

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> * Is a browser extension: no, used with react-pdf

Please note that that's a *different* project which is not maintained here.

> Bug appends on iPhone iOS 16+
> Bug appends on xCode Simulator iPhone iOS 16+

This sounds like a bug, and possibly even a regression, in the browser *itself* rather a bug in the PDF.js library. Most likely this needs to be reported to the Safari developers, since it unfortunately doesn't really look fixable here.
