### ISSUE TITLE
Use canvas.getContext('2d', {desynchronized: true}) ?

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#15912]
The desynchronized option is supported on Chrome and might improve latency. Will it be useful to add?

MDN [docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext) says:
> desynchronized
A boolean value that hints the user agent to reduce the latency by desynchronizing the canvas paint cycle from the event loop

More details on the [Chrome blog](https://developer.chrome.com/blog/desynchronized/).

Bugzilla [issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1536809).

Relevant code:
https://github.com/mozilla/pdf.js/blob/c791e01bfc280fb6abc476dece21c6a88d2340df/web/pdf_page_view.js#L1008
https://github.com/mozilla/pdf.js/blob/c791e01bfc280fb6abc476dece21c6a88d2340df/web/pdf_thumbnail_view.js#L56

- PDF.js version: v3.2.146

**Comment by Snuffleupagus** [comment]
First of all, according to https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/getContext#browser_compatibility this isn't supported in Firefox (which is the primary development target for PDF.js) and even in Google Chrome the support appear to be *partial*.
Secondly, if/once this becomes generally available, without any benchmarking (within the context of the PDF.js library) it's not really clear if this would even help performance here.

Let's close this as WONTFIX for now, since it's not something that we can/will implement now.

**Comment by calixteman** [comment]
And I read the docs, and I'm not sure that there is any benefit for us but as Jonas said, please provide benchmarks.
