### ISSUE TITLE
Render XFA form issue

### ISSUE THREAD

**Issue by sergei-harbour** [mozilla/pdf.js#15936]
PDF file here:
https://github.com/mozilla/pdf.js/blob/master/test/pdfs/xfa_filled_imm1344e.pdf

If I use the Hello World example from [here](https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) should I be able to see the rendered PDF file?
I'm asking because the viewer mode works fine with this file.

But with the code from the example I see this 
![image](https://user-images.githubusercontent.com/86401513/212971326-1c1629e3-929c-45f8-bc9c-5bfe24ef9f32.png)

Configuration:
- Web browser and its version: Chrome 108
- Operating system and its version: Mac/Windows
- PDF.js version: 3.2.146
- Is a browser extension: No

**Comment by Snuffleupagus** [comment]
> If I use the Hello World example from [here](https://mozilla.github.io/pdf.js/examples/index.html#interactive-examples) should I be able to see the rendered PDF file?

That's the most basic example, and thus it doesn't support rendering XFA-documents since those also require functionality not found in the API itself.
Hence you'll either need to use the [demo-viewer](https://github.com/mozilla/pdf.js#online-demo), or alternatively the [viewer-components](https://github.com/mozilla/pdf.js/tree/master/examples/components) (together with the `pdfjs-dist` library) which are intended to simplify building a custom viewer.
