### ISSUE TITLE
Can´t figure out printing.. Help please

### ISSUE THREAD

**Issue by kjartanvalur** [mozilla/pdf.js#15955]
Configuration:
- Web browser and its version:  Chrome Version 109.0.5414.75 (Official Build) (64-bit)
- Operating system and its version: Windows 11
- PDF.js version: 2.6.347
- Is a browser extension: No

Steps to reproduce the problem:
1. Open https://stackblitz.com/edit/bootstrap-5-w1zr5w?file=src/index.js
2. Open in new Tab (Button in StackBlitz in the top-right corner)
3. Right click on the screen and select print

What is the expected behavior? (add screenshot)
Expect to print the document as it is.

What went wrong? (add screenshot)
![printing](https://user-images.githubusercontent.com/3437106/214269015-f510a979-306d-4ea8-8189-37623532f37d.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://stackblitz.com/edit/bootstrap-5-w1zr5w?file=src/index.js

**Comment by Snuffleupagus** [comment]
> PDF.js version: 2.6.347

That version is no longer supported, since it's over two years old, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Expect to print the document as it is.

Sorry, but you can't print directly from a PDF viewer like that. Furthermore browsers unfortunately have limited support for controlling the printing output, which is why the default-viewer converts the entire document into images to allow printing; please refer to e.g. https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js to see how that's done.
