### ISSUE TITLE
`pdfjs-dist` commit for new release didn't get pushed

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#15975]
I followed the [release process](https://github.com/mozilla/pdf.js/wiki/Release-Process) like we do every month, but strangely the bot didn't push the `pdfjs-dist` commit this time since there should have been a push for version 3.3.122 at https://github.com/mozilla/pdfjs-dist/commits/master.

@calixteman Could you check the (I believe) Windows bot to see if there are any logs as to why that didn't happen this time, and push the commit manually if need be (see https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js for the commands the bot executes normally)? Thank you!

**Comment by Snuffleupagus** [comment]
It seems that the npm package has now been updated correctly, looking at https://www.npmjs.com/package/pdfjs-dist/v/3.3.122

Unfortunately though, the latest `dist`-build was *not* pushed to https://github.com/mozilla/pdfjs-dist and only an incorrect tag was created[1].
@calixteman Have you had a change to look at the bot logs to figure out what went wrong here?

It might have been something temporary, and I suppose that we could always *locally* generate the correct `dist`-build and manually push it to the `pdfjs-dist` repository this one time. (Probably either Tim or myself could do that later.)

However, if there's something that have "broken" on the bot that would be very good to look into/fix now such that we don't run into it again with the next release.

---
[1] I manually removed that tag, since as the issue above shows it was causing problems.

**Comment by calixteman** [comment]
The only wrong things I see for last sunday are:
```
Sun Jan 29 2023 12:24:01 GMT+0000 (Coordinated Universal Time): Ignoring release draft
Sun Jan 29 2023 12:34:41 GMT+0000 (Coordinated Universal Time): Command not implemented (push_to_v3.3.122)
```

But there were exactly the same for 3.2.146 so I'd say that there are nothing wrong in the logs.
So likely something went wrong on the gh side.

**Comment by r3g-5z** [comment]
Are there any plans to get this tag published at least in the mean time? We'd like to update our Android app that uses pdf.js to the latest version, but we cannot as we use the pdfjs-dist repo as a submodule and we use the minified version which the zip file in https://github.com/mozilla/pdf.js/releases/tag/v3.3.122 does not provide.

**Comment by timvandermeij** [comment]
@calixteman This didn't work for the new 3.4.120 release as well, so sadly it doesn't look like a one-time fluke. Could you perhaps try pushing the pending commits using Git on the Windows bot manually to see if for example Git there complains about anything that is not being written to the logs?

**Comment by Snuffleupagus** [comment]
*Possibly unrelated, but considering that the npm package was updated successfully:*
Has there perhaps been some kind of branch-protection rules added/changed recently (in GitHub) for the `pdfjs-dist` repository, since I suppose that that might be preventing the bot from pushing the updated files?

**Comment by calixteman** [comment]
There are no branch-protection rules for pdfjs-dist.
Finally I managed  to find something useful in one of the output.txt files and I can reproduce this error locally:
```
### Committing changes
Error: command "git" with parameters "add,"*"" exited with code 128
[16:14:51] The following tasks did not complete: dist, createDist
[16:14:51] Did you forget to signal async completion?
```
when running `gulp dist`.
The git command is ran from:
https://github.com/mozilla/pdf.js/blob/2da2ac492ef3fdba4bc9f6fb992bda2fb57dbb82/gulpfile.js#L2379

**Comment by calixteman** [comment]
I wonder if it could be because of:
https://github.com/mozilla/pdf.js/commit/32357e3d172a552e0408b3e1ed743e87fe7d5a21#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R2255

I'm not a node expert at all but maybe all the dir DIST_DIR is now removed when before all the contents of the dir were removed.
@Snuffleupagus, wdyt ?

**Comment by Snuffleupagus** [comment]
> I wonder if it could be because of: [32357e3#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R2255](https://github.com/mozilla/pdf.js/commit/32357e3d172a552e0408b3e1ed743e87fe7d5a21#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7R2255)
> 
> I'm not a node expert at all but maybe all the dir DIST_DIR is now removed when before all the contents of the dir were removed.

Also not a Node.js expert unfortunately. Does it work if you manually re-create the directory by adding `mkdirp.sync(DIST_DIR);` immediately after that line?

**Comment by calixteman** [comment]
If we just recreate the dir we lose the git repo created previously:
https://github.com/mozilla/pdf.js/blob/2da2ac492ef3fdba4bc9f6fb992bda2fb57dbb82/gulpfile.js#L2248

and it's why when we `git add *` later, we've an error because we're somewhere in the build directory which is in gitignore.

So if I understand correctly we must revert this line to `rimraf.sync(path.join(DIST_DIR, "*"));` to just remove all the files (but not the git ones), and then the dist stuff will add some new files here and then the `git add *` will happen in the clone of the pdfjs-dist git repo.

I tested with `gulp dist-pre` and it seems to work correctly (locally).

**Comment by Snuffleupagus** [comment]
> So if I understand correctly we must revert this line to `rimraf.sync(path.join(DIST_DIR, "*"));` to just remove all the files (but not the git ones),

Does that actually work *exactly* as before, since one of the breaking changes in `rimraf` 4 was the removal of glob support?

It seems to me that we'd either need to revert the `rimraf` update (which is likely annoying at this point), or perhaps introduce our own helper function that clears out all files and sub-directories (but leaves the directory itself intact).

---

Also, https://github.com/mozilla/pdf.js/commit/32357e3d172a552e0408b3e1ed743e87fe7d5a21#diff-25789e3ba4c2adf4a68996260eb693a441b4a834c38b76167a120f0b51b969f7L2449 is probably similarly affected here.

**Comment by calixteman** [comment]
You're right: the contents of the directory aren't removed.
Maybe we could just run `git rm -r *`.

**Comment by Snuffleupagus** [comment]
> Maybe we could just run `git rm -r *`.

Given how our other `git` invocations look that might be less ideal, but could we perhaps just use the native Node.js `fs` functionality instead? Based on https://nodejs.org/api/fs.html#fspromisesrmpath-options, would something like the following work (completely untested though)?
```diff
diff --git a/gulpfile.js b/gulpfile.js
index 5dbc2f1..4afd2b9 100644
--- a/gulpfile.js
+++ b/gulpfile.js
@@ -19,6 +19,7 @@
 const autoprefixer = require("autoprefixer");
 const postcssDirPseudoClass = require("postcss-dir-pseudo-class");
 const fs = require("fs");
+const fsPromises = require("fs/promises");
 const gulp = require("gulp");
 const postcss = require("gulp-postcss");
 const rename = require("gulp-rename");
@@ -2239,7 +2240,7 @@ gulp.task(
     "minified",
     "minified-legacy",
     "types",
-    function createDist() {
+    async function createDist() {
       console.log();
       console.log("### Cloning baseline distribution");
 
@@ -2249,7 +2250,10 @@ gulp.task(
 
       console.log();
       console.log("### Overwriting all files");
-      rimraf.sync(DIST_DIR);
+      await fsPromises.rm(
+        path.join(DIST_DIR, "*"),
+        { recursive: true, force: true }
+      );
 
       return merge([
         packageJson().pipe(gulp.dest(DIST_DIR)),
@@ -2432,7 +2436,7 @@ gulp.task(
   gulp.series(
     "mozcentral",
     "mozcentralbaseline",
-    function createMozcentralDiff(done) {
+    async function createMozcentralDiff(done) {
       console.log();
       console.log("### Creating mozcentral diff");
 
@@ -2441,7 +2445,10 @@ gulp.task(
       // The mozcentral baseline directory is a Git repository, so we
       // remove all files and copy the current mozcentral build files
       // into it to create the diff.
-      rimraf.sync(MOZCENTRAL_BASELINE_DIR);
+      await fsPromises.rm(
+        path.join(MOZCENTRAL_BASELINE_DIR + "*"),
+        { recursive: true, force: true }
+      );
 
       gulp
         .src([BUILD_DIR + "mozcentral/**/*"])
```

**Comment by calixteman** [comment]
Unfortunately it doesn't work either.
I just tried ` fsPromises.rm("./*", { recursive: true, force: true });` in a node shell and it doesn't work.

**Comment by Snuffleupagus** [comment]
> Unfortunately it doesn't work either.
> I just tried ` fsPromises.rm("./*", { recursive: true, force: true });` in a node shell and it doesn't work.

What if we create a helper function, for those two call-sites, that use `fs.readdirSync()` and then loop through the results doing the `rm`-call for each entry. Would something like that perhaps work?

```javascript
async function clearDirectory(dir) {
  for (const entry of fs.readdirSync(dir) {
    const dirPath = path.join(root, entry);
    await fsPromises.rm(dirPath, { recursive: true, force: true });`
  }
}
```

**Comment by calixteman** [comment]
I think we shouldn't remove `.git` directory else we'll lose the fact that it's a git repo.
