### ISSUE TITLE
(Mobile) Part of document text not displaying

### ISSUE THREAD

**Issue by jmkang-ucert** [mozilla/pdf.js#15988]
Attach (recommended) or Link to PDF file here:
This is the same document as it appears by default on the official demo site.
[compressed.tracemonkey-pldi-09.pdf](https://github.com/mozilla/pdf.js/files/10553450/compressed.tracemonkey-pldi-09.pdf)

Configuration:
- Web browser and its version: Chrome 109
- Operating system and its version: Android 12 (Galaxy S21+)
- PDF.js version: Official demo site pdfjs version (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Access PDF JS demo site on mobile
2. Check the default document being loaded

What is the expected behavior? (add screenshot)
a desktop screen.
![image](https://user-images.githubusercontent.com/92900283/215955572-af05b1a4-2836-4214-a286-a6a64731687f.png)

What went wrong? (add screenshot)
a mobile screen.
![pdfjs_diplay_error_mobile](https://user-images.githubusercontent.com/92900283/215955851-042953b2-66ad-49ea-bbba-1b1ecc5614a1.jpg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Chrome 109
> Operating system and its version: Android 12 (Galaxy S21+)

This unfortunately looks like a browser/platform-specific bug, rather than general PDF.js library one, since otherwise you'd really expect it to be consistently broken everywhere.
Most likely this needs to be filed, as e.g. a `canvas`-related bug, against the browser instead (and please keep in mind that Firefox is the *primary* development target here).
