### ISSUE TITLE
How to render to the browser instead of logging in getinfo.js

### ISSUE THREAD

**Issue by natnaeltibebu** [mozilla/pdf.js#15994]
I am using node `getinfo.js` it works fine but i dont get any info how to render it to the browser please help

**Comment by Snuffleupagus** [comment]
Please start at https://mozilla.github.io/pdf.js/examples/ and https://github.com/mozilla/pdf.js/tree/master/examples/learning
Furthermore, see https://github.com/mozilla/pdf.js/tree/master/examples but ignore the `node/`-folder since that's not for browsers.

Given the lack of details, that's probably the only help we can provide here.

**Comment by natnaeltibebu** [comment]
thanks, i am working on node server & i just want to render the output to browser
![Screenshot (154)](https://user-images.githubusercontent.com/120314540/216315116-c322f8f2-bcc5-4cd2-b3d8-6c828446ad17.png)
