### ISSUE TITLE
button or scrollbar for scrolling

### ISSUE THREAD

**Issue by Boy19991** [mozilla/pdf.js#16014]
I've been going at it for a day now, so I decided to risk making some people angry and asking for some help in what may not be the correct place.

https://jsfiddle.net/pdfjs/wagvs9Lf/

In the above example, adding the following code **changes the scale**
```
pdfDoc.getPage(pageNum).then(function(page){
  var viewport = page.getViewport({scale: 2});
  page.render({ canvasContext:ctx, 
                viewport: viewport })
})
```

After increasing the scale, part of the pdf extends outside the canvas, which the user cannot see. **How could I make some buttons or a scrollbar to allow the user to scroll to different parts of the page**, after they have increased the scale?

Any help is much appreciated, also, please swiftly delete this post if this is not the right place to ask, yours sincerely, Jolly Boy.

**Comment by Snuffleupagus** [comment]
> In the above example, adding the following code **changes the scale**
> ```
> pdfDoc.getPage(pageNum).then(function(page){
>   var viewport = page.getViewport({scale: 2});
>   page.render({ canvasContext:ctx, 
>                 viewport: viewport })
> })
> ```

It's not clear *exactly* what lines you changed, however your code-snippet is missing the following code between the `getViewport` and the `render` calls (which might explain the problem):
```javascript
canvas.width = viewport.width;
canvas.height = viewport.height;
```

If that's not it, then you'll need to provide a *runnable example that includes your code changes* since it's not really possible to tell what you changed and how otherwise.
Please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
