### ISSUE TITLE
Possibility to hide form fields / input elements

### ISSUE THREAD

**Issue by angelaki** [mozilla/pdf.js#16059]
As far as I know there currently is no option to hide form fields. I guess that could be implemented pretty easy? Where to start?

**Comment by Snuffleupagus** [comment]
Given the lack of details it's very difficult to know the exact context of the question, but assuming that you're using the default viewer then setting the `annotationMode` option/preference to `1` will disable all interactive form elements (and simply render their default values onto the `canvas` instead).

**Comment by angelaki** [comment]
Thank you very much! Where to get the docs of props available / how to use them?

Setting `PDFViewerApplicationOptions.set('annotationMode', 1);` after `documentLoad` doesn't seam to change anything (eventough it value obviously gets set, checking it via `PDFViewerApplicationOptions.getAll()`).

**Comment by Snuffleupagus** [comment]
> Where to get the docs of props available / how to use them?

No proper documentation exists, since the default viewer is primarily intended for the *built-in* Firefox PDF Viewer.
However, the `PDFViewer` options-documentation might help somewhat; see https://github.com/mozilla/pdf.js/blob/546902df63b4fcfad419bc8109d128040d7b27ab/web/pdf_viewer.js#L82-L125

> Setting `PDFViewerApplicationOptions.set('annotationMode', 1);` after `documentLoad` doesn't seam to change anything

That's way too late unfortunately, since it needs to be set *before* the viewer is initialized. You can set it within a "webviewerloaded` event listener, which is fired early enough; see also https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage
