### ISSUE TITLE
Legacy build is.... not legacy at all

### ISSUE THREAD

**Issue by veodko** [mozilla/pdf.js#16058]
I tried to use the legacy build from the official download ( https://github.com/mozilla/pdf.js/releases/download/v3.3.122/pdfjs-3.3.122-legacy-dist.zip ) targetted at older browsers but it is simply not working in anything below chrome 80.
I have checked the source code and it has es2020 stuff like null coalescing operators:
```js
this.opacity ?? (this.opacity = InkEditor._defaultOpacity);
```
What happened to the es5 version of the build?

**Comment by Snuffleupagus** [comment]
Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for information about the currently supported browsers.

> What happened to the es5 version of the build?

It was replaced by the `legacy` build, since it unfortunately isn't really feasible for the (few) regular PDF.js contributors to keep supporting browsers that are many years out-of-date.
