### ISSUE TITLE
Use of eval in "node_modules/pdfjs-dist/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification

### ISSUE THREAD

**Issue by gkiely** [mozilla/pdf.js#16061]
Configuration:
- [Vite](https://vitejs.dev/) project

Repo:
- https://github.com/gkiely/pdfjs-issue

Steps to reproduce the problem (with repo):
- `git clone git@github.com:gkiely/pdfjs-issue.git`
- `cd pdfjs-issue`
- `npm i`
- `npm run build`

Steps to reproduce the problem (without repo):
1. `npm create vite@latest`
2. Project name: `pdfjs-issue`
3. `Vanilla`
4. `JavaScript`
5. `cd pdfjs-issue`
6. `npm i pdfjs-dist`
7. Add the following to main.js
`import pdfjs from 'pdfjs-dist';`
8. `npm run build`

What is the expected behavior? (add screenshot)
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/1948935/219124650-af8f9dff-8e10-4cf0-9f67-c76d9c2c83f6.png">

**Comment by Snuffleupagus** [comment]
Please note that "Vite" isn't something we use here, and thus we unfortunately can't really provide help/support for it.

Furthermore, note that the code in question is intended specifically for Node.js environments; please see the following comment for additional context here: https://github.com/mozilla/pdf.js/blob/546902df63b4fcfad419bc8109d128040d7b27ab/src/display/api.js#L2296-L2317

**Comment by gkiely** [comment]
That's ok thanks for providing me a link to the source. I'll check with the vite team to see if there's a way to remove this error.

**Comment by FredrikWallstrom** [comment]
Hey. We have the same issue with the Rollup bundler. Rollup complains about the use of eval when bundling: https://rollupjs.org/troubleshooting/#avoiding-eval

Is there something that can be done to remove eval in pdfjs?
Or Is there a way to for me to get around this? We are using stenciljs in our project which in turn uses Rollup as bundler under the hood.

**Comment by Snuffleupagus** [comment]
> Is there something that can be done to remove eval in pdfjs?

Maybe, but that could very easily end up breaking more things than it fixes unfortunately.

If you look at the code/comment linked in https://github.com/mozilla/pdf.js/issues/16061#issuecomment-1431872557 you'll see that this was done for improved Webpack compatibility (for a while there were loads of issues filed about that). Hence trying to fix *this issue* could thus risk:
 - Re-introducing the Webpack warning yet again (and having to deal with a bunch of issues/complaints).
 - Potentially breaking general Node.js support, since this code is specifically intended for that environment (however bundlers won't leave it alone despite the run-time checks).
 - Removing the `eval` unfortunately doesn't guarantee that Rollup starts working correctly, since it's certainly possible that it uncovers other problems (given that we don't Rollup use it's not feasible for us to "officially" support it).
 - Any patch(es) might need be reverted, if there are problems with the first two points above.

---

Given that this doesn't affect the *built-in* Firefox PDF Viewer, I cannot really justify spending my spare time trying to fix this (since I'm not getting paid to hack on the PDF.js library).
However, if you'd be willing to compensate me for my time, I could certainly attempt a patch that removes the `eval` (with all the caveats above).

**Comment by FredrikWallstrom** [comment]
Ok, I understand. Thank you for taking your time and for the work you are putting into this, it's appreciated.
