### ISSUE TITLE
Android 12 - 13 and Chrome v109 - v110 rendering issues and glitches pdfjs

### ISSUE THREAD

**Issue by DanielBalsalobre** [mozilla/pdf.js#16070]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/viewer.html 

Configuration:
- Web browser and its version: Chrome 110.0.5481.65
- Operating system and its version: Android 13; Build/TQ1A.230205.002
- PDF.js version: At least 3.4.103 (demo URL) or 3.1.81
- Is a browser extension: No

Steps to reproduce the problem:
1. Visit the URL in android device
2. Do some scroll and/or zoom

What is the expected behavior? (add screenshot)
(Firefox screenshot)
![WhatsApp Image 2023-02-18 at 20 27 03 (1)](https://user-images.githubusercontent.com/26458005/219884504-ec07450d-ed67-4ed4-8c2c-ca17d5bad68c.jpeg)

What went wrong? (add screenshot)
(Chrome)
![WhatsApp Image 2023-02-18 at 20 27 03](https://user-images.githubusercontent.com/26458005/219884508-d615fa1a-33e9-43a5-8574-4e94c6762216.jpeg)

![WhatsApp Image 2023-02-18 at 20 31 35](https://user-images.githubusercontent.com/26458005/219884651-3fb7ba78-0a24-4aeb-9bda-3c973e6a76b7.jpeg)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This unfortunately looks like a browser, or possible graphics-driver, related bug rather than a general PDF.js library one. (Since you'd expect it to be consistently broken *everywhere* otherwise.)

One thing that'd be interesting is to check if disabling of hardware acceleration, in the browser, would help here?
To do so in Google Chrome, open the `about:flags` page and search for (and disable) hardware acceleration.

Does that fix things, because if so this definitely is a bug in the *browser itself* and needs to be reported to the Chromium bug tracker instead. (And in any case, this bug most unfortunately doesn't look actionable here.)

**Comment by timvandermeij** [comment]
I agree; this looks very much like a Chrome-specific graphics bug, either in the browser engine or in the graphics driver. I would recommend to file this bug in the Chrome bug tracker instead.
