### ISSUE TITLE
Display PDF format

### ISSUE THREAD

**Issue by Sterzz** [mozilla/pdf.js#16085]
In some situations it is helpful to know the PDF format. PDF.js already shows the PDF version in the documentpropeties. If a PDF file is in a format like PDF/A or PDF/X, it could be displayed there too. I have attached a sample pdf files.

[pdfx3.pdf](https://github.com/mozilla/pdf.js/files/10823080/pdfx3.pdf)

**Comment by Snuffleupagus** [comment]
> If a PDF file is in a format like PDF/A or PDF/X, it could be displayed there too.

Unfortunately it's not quite that easy, since the relevant /Info and /Metadata entries[1] will only tell you if a PDF document "pretends" to be e.g. a PDF/A or PDF/X document.
To tell if it's an *actually valid* PDF/A or PDF/X document there's also a lot of additional parsing/validation that needs to happen, which we don't do since it's not necessary for the PDF.js use-case (which is simply to render PDF documents).

Given that the mere existence of these "special" /Info and /Metadata entries thus cannot guarantee the validity of PDF/A or PDF/X documents, it thus seems (at least to me) questionable if surfacing this data more prominently makes sense since it could very easily mislead the user into thinking that a document is valid even if it's in fact *not*.

---
[1] Which the PDF.js library already lets you access, via the `PDFDocumentProxy.getMetadata` method.

**Comment by bmaupin** [comment]
This will log the `pdfaid` properties, which are required for PDF/A compliance as far as I understand:

```javascript
const loadingTask = pdfjsLib.getDocument({
  url: 'https://tcpdf.org/files/examples/example_065.pdf',
});
const doc = await loadingTask.promise;
const metadata = await doc.getMetadata();

console.log('pdfaid:part=', metadata.metadata.get('pdfaid:part'));
console.log(
  'pdfaid:conformance=',
  metadata.metadata.get('pdfaid:conformance')
);
```

Example output:

```
pdfaid:part= 1
pdfaid:conformance= B
```

But as Snuffleupagus said, this doesn't actually indicate that the file is PDF/A compliant, only that it claims to be.
