### ISSUE TITLE
PDFJS-dist in Electron application (workerSrc not working).

### ISSUE THREAD

**Issue by verlotl2000** [mozilla/pdf.js#16111]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Using Electron 23.
- Operating system and its version: Windows 10
- PDF.js version: PDFJS-dist @3.4.120
- Is a browser extension: No

Steps to reproduce the problem:
1. 
`const PDFJS = require('pdfjs-dist');
const url = "../node_modules/pdfjs-dist/build/pdf.worker.js";
PDFJS.GlobalWorkerOptions.workerSrc = url;`
2. 
`let pdfDoc = window.api.PDFJS.getDocument('../test.pdf')`

What is the expected behavior? (add screenshot)
Loading the worker succesfully and reading the template PDF.

What went wrong? (add screenshot)
![Capture](https://user-images.githubusercontent.com/116467108/222963331-931a6d23-6982-4d79-875a-4cd61cc9dc9a.PNG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
There is no viewer as this is an Electron app.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Using Electron 23.

Sorry, but that's unfortunately not a configuration that we can provide support for; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Given the paths in your screen-shot, you might run into problems because of the `file://`-protocol. As mentioned e.g. in https://github.com/mozilla/pdf.js#getting-the-code, try using a web server instead.

*For future reference:* Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by sunknudsen** [comment]
Hey @verlotl2000, did you find a solution?
