### ISSUE TITLE
Not able to view Signatures in PDF with latest PDF.js - where to set enableSignature in recent pdf.js

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#16136]
Attach (recommended) or Link to PDF file here:
[10016583 Lake Elsie RFDS v11(Crump).pdf](https://github.com/mozilla/pdf.js/files/10931757/10016583.Lake.Elsie.RFDS.v11.Crump.pdf)

Configuration:
- Web browser and its version: chrome 110.0.540
- Operating system and its version: Windows 
- PDF.js version: latest
- Is a browser extension:

Steps to reproduce the problem:
1.  Opening this file , in PDF.js viewer. it does not show the signature. 
2. We used to add enableSignature = true, in default_preferences.json to get this working. 

With recent pdf.js, we want to know how to add default preferences to enableSignature. Most of the preferences such as disableFontFace , disableRange are all now added to the getDocument task itself. 

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version: latest

Please provide an actual version *number*, since latest unfortunately isn't helpful.

> Opening this file , in PDF.js viewer. it does not show the signature.

Since some time back we render signatures, however we don't validate them. As the following screen-shot shows, when opening your PDF document with e.g. https://mozilla.github.io/pdf.js/web/viewer.html there's a signature rendered on the first page:

![signature](https://user-images.githubusercontent.com/2692120/224038346-343a5626-8984-4ec3-9b1a-83b0c1793047.png)

> We used to add enableSignature = true, in default_preferences.json to get this working.

Sorry, but no such option/preference has ever existed and you must have been using e.g. a custom version of the viewer.

---

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
