### ISSUE TITLE
Rendering problem when zooming on Safari on iPhone 11

### ISSUE THREAD

**Issue by HalvorHaugan** [mozilla/pdf.js#16155]
Attach (recommended) or Link to PDF file here: https://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf (seems to happen to any PDF)

Configuration:
- Web browser and its version: Safari
- Operating system and its version: iOS 16.2
- PDF.js version: 3.5.61 (also reproduced on 3.4.120)
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the PDF viewer in Safari on iOS
2. Zoom in. The more you zoom, the worse it gets.

What is the expected behavior? (add screenshot)
PDF is rendered correctly when zooming.
![expected](https://user-images.githubusercontent.com/83693529/225058190-20dd005b-27df-4de8-a5da-19edf5d44a56.png)

What went wrong? (add screenshot)
The PDF is rendered incorrectly when zooming.
![wrong](https://user-images.githubusercontent.com/83693529/225058543-6bc7671d-ac8f-4a4a-90c8-ad856b45de0e.png)

**Comment by Snuffleupagus** [comment]
This unfortunately sounds like a browser- and/or platform-specific bug, since otherwise you'd expect it to be consistently broken everywhere; most likely this needs to be reported to Apple instead.

Please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target here. (Historically it feels like Safari has often been the "worst" browser to attempt to support, and anecdotally it seems that later Safari versions have a fair share of trouble with the PDF.js library when Firefox/Chrome works fine.)
