### ISSUE TITLE
How to get all field details from XFA form and update fields value through code

### ISSUE THREAD

**Issue by SubratTest** [mozilla/pdf.js#16156]
Hi Team,
I am using the PDF.js viewer to render XFA form.
I want to know once the document is loaded how can i get all the fields inside the XFA form and as per the type how can i set value for the field.
Could you help me to resolve the issue.

**Comment by Snuffleupagus** [comment]
No such functionality exists unfortunately, since it's not really needed in the Firefox PDF Viewer.
Hence you'll need manually find the relevant elements in the DOM, and update their values.

---

*For future reference:* When opening an issue, please remember to actually provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by SubratTest** [comment]
so through code it is not possible?
