### ISSUE TITLE
Combining pdf.js with a search engine

### ISSUE THREAD

**Issue by blenzi** [mozilla/pdf.js#16150]
Hello,

I would like to build an application that combines a viewer for large pdf files, 100-500 MB, and an advanced search engine that runs on extracted and indexed text, based on ElasticSearch. What would be the best / easiest way to achieve this, please? I browsed past issues and saw one or two mentions (ex. #7932) but no solution.
A few thoughts and questions:

-  a first proof-of-concept was to build a new viewer from the pdf.js components and couple it to an API that provided the search results (page, words) but it lacked many nice features like highlighting, scrolling, multi-page view, etc. Re-implementing turns out to be complicated so we probably need to start from the full viewer
- it is not enough to simply go to the desired page: we would like to highlight and navigate through the search results, that can be different from the ones of a normal search. Ultimately we would also like to filter the table of contents and page thumbnails according to the search results
- the text extraction is done with another tool (PyMuPDF) but we have access to the bounding boxes of each span / word. Could this be an issue? 

Thanks a lot for your help

**Comment by Snuffleupagus** [comment]
Sorry, but we cannot provide detailed help/support with something like this since the find-implementation was never written with such a use-case in mind (and it's not really relevant for the *built-in* Firefox PDF Viewer either).

Furthermore, as-is this issue is a little bit too "broad" to make it easily actionable. Please keep in mind that this is first-and-foremost a *bug tracker*, and that help requests for help need to be more "focused" (since many of us here are unpaid volunteers); please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
