### ISSUE TITLE
Duplicate Key Id in PDF. Unable to set value in (input textBox).

### ISSUE THREAD

**Issue by Lakhtar-kays** [mozilla/pdf.js#16179]
"https://www.canada.ca/content/dam/ircc/migration/ircc/english/pdf/kits/forms/imm5257b_1.pdf" 

Web browser and its version: "Firefox 111.0 (64 bit)" 
Operating system and its version: "Windows 10 Home Single Language" 
PDF.js version: "^1.17.1" 
Is a browser extension: "No" - "ReactJs Libaray "

We intend to fill this XFA formatted PDF, using pdf.js library  

Steps to reproduce the problem:  

1. Provide the URL to library and get PDF instance. 
2. From Pdf instance variable, call the function `allXfaHtml`, which will return the data  
3. Now from that JSON data we will find out the field id, which will help us to insert the data into that field. 
4. Insert data to the corresponding field using the code. E.g. `pdf.annotationStorage.setValue('field284342', { value: 'John' });` 
5. You can find this field id from parsed xfahtml,  

` { 
"name": "textarea", 
"attributes": { 
    "dataId": "field24562", 
    "fieldId": "field24562", 
    "class": [ 
        "xfaTextfield" 
    ] 
...` 

6. Note: It’s not necessary that the dataid and fieldId, I have mentioned above, will also come in your code, it varies as it is dynamic form.  

7. Now the problem is dataId and fieldId are the same for multiple input types. for example, given name, family name etc. 

8. In other words, if you try to set the value of given name or family name input textbox in this pdf, you will be unable to set the value (due to duplicity).  

What is the expected behavior? (add screenshot) 

The problem is not exactly in the pdf JS library code, but we want to know if there is a way to handle the scenario of duplicate keyid in pdf, maybe using the type.  

How can set the value in that input type boxes. 
I added the code sample in JS bin, but ran into another issue  

"https://jsbin.com/recayiv/edit?html,console,output" 

 We can't see the `allXfaHtml` function response when I use CDN link of script, whereas I am getting the response when I am working on react js local server. 

React Js function return reference 

![image](https://user-images.githubusercontent.com/85861166/226314070-4eb3a1bf-cb7a-49b8-89eb-9bc9bd5b657b.png)

**Comment by calixteman** [comment]
Sorry but I don't really understand your problem...
What's the problem of having the same value for `dataId` and `fieldId` ? 
IIRC, `fieldId` is mainly there for debug purposes and `dataId` is used when some user data are saved in the pdf: we've a node in the template which maps onto a node in the data tree, hence when we want to save a value for the field we save it in the corresponding node in the data tree.
Anyway, as @Snuffleupagus mentioned it in an other issue, the main purpose of pdf.js is to be the Firefox pdf viewer, so either you've a bug in Firefox or in using https://mozilla.github.io/pdf.js/web/viewer.html where the root cause could be an `ids` issue and then we'll fix it, for the rest we won't spend some time to fix your issues.

Please read the code here:
https://github.com/mozilla/pdf.js/blob/3903391f3cbed25806adc4a9874979f7725ec883/src/display/xfa_layer.js#L151
https://github.com/mozilla/pdf.js/blob/3903391f3cbed25806adc4a9874979f7725ec883/src/display/xfa_layer.js#L32
https://github.com/mozilla/pdf.js/blob/3903391f3cbed25806adc4a9874979f7725ec883/src/core/xfa/data.js#L31
