### ISSUE TITLE
Fix PDF.js 3.5.141 post-release steps

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#16245]
It looks like sadly the Windows bot is still not happy after our previous efforts to fix failing steps in the release process. This time it again didn't perform the push to the `pdfjs-dist` repository (see https://github.com/mozilla/pdfjs-dist which also doesn't have the previous two versions), but it also didn't push the release to NPM (see https://www.npmjs.com/package/pdfjs-dist/v/latest which is still on the previous version). Especially the NPM push failing is new; this used to work just fine until last month.

@calixteman Could you check the bots again to see what is going on? For now we should at least perform the steps that the bot performs manually on there (see https://github.com/mozilla/botio-files-pdfjs/blob/master/on_release.js for the steps) so that at least the NPM update is pushed and `pdfjs-dist` is in sync again, but we should also find out why this keeps on failing for the last three releases so that next month it will hopefully go smoother.

**Comment by Snuffleupagus** [comment]
Given the age/quirks of the bots, and the limited access to them (for e.g. debugging purposes), it really feels like implementing issue #11851 would be the best way forward to reduce the sort of problems that we've experienced recently.

**Comment by Snuffleupagus** [comment]
@timvandermeij Unless the `on_release` work-flow can be converted "soon", could we perhaps try to create one more release using the old work-flow now?

There's a couple reasons why making a release sooner rather than later would be a good idea:
 - The current release has a couple of breaking regressions, see e.g. PRs #16291 and #16279.
 - There's larger changes coming, e.g. related to standard-font handling (see PR #16363), that we probably shouldn't land just prior to a release.

**Comment by calixteman** [comment]
How did I miss this bug.... ??? Sorry about that.
@timvandermeij as far as I can tell the failure was not due to the release script itself but something went wrong after integration tests (`Error: EPERM: operation not permitted, unlink...`) and the bot exited. I restarted it the 4th of April (when it exited the 2nd of April at 13.:28 (GMT)).
Could we trigger a new release this week to see if everything is correct or not ?

**Comment by calixteman** [comment]
And please don't hesitate to nag me if you see that I'm not responsive.

**Comment by timvandermeij** [comment]
Yes, I'll make a new release this weekend using the current release process and work on the new release process after that. Thank you both for looking into the recent bot issues and getting them to work again!

**Comment by timvandermeij** [comment]
Closing since NPM got updated and we're going to do a new release today that should hopefully update `pdfjs-dist` again.
