### ISSUE TITLE
I need to download a 14M PDF file before I can open it，but Open an 84M PDF file and just download 4 to view it，How to set up a 14M file that can be viewed by downloading only 4M？

### ISSUE THREAD

**Issue by kingmim** [mozilla/pdf.js#16267]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since nothing but a (long) title unfortunately isn't sufficient to make an issue actionable/valid.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Whether a PDF document can be lazily loaded ultimately depends on the internal structure of the document itself, and also on the server supporting range-requests, however the following options may be relevant to your question:
https://github.com/mozilla/pdf.js/blob/195db2cff52d9db7176861b642c1569661f0f946/src/display/api.js#L230-L239
