### ISSUE TITLE
Why is the browser version required by pdf.js so high? How or whether it can be polyfill?

### ISSUE THREAD

**Issue by axetroy** [mozilla/pdf.js#16321]
I found out that the build target is asking for Chrome 88, which was released at 2021/01/19

and Safari 14.1 was released at 2021/04/29

```js
const ENV_TARGETS = [
  "last 2 versions",
  "Chrome >= 88",
  "Firefox ESR",
  "Safari >= 14.1",
  "Node >= 16",
  "> 1%",
  "not IE > 0",
  "not dead",
];
```

**This means that even legacy builds are not compatible with browsers released two years ago**

There are many third-party browsers, based on Chromium and maintain at a lower version (Chrome 60-100), that mean `pdf.js` will not at these browser.

And there are many Linux distributions, and the version of the firefox browser that comes with it is also very low（firefox 40-60）

Is there a list of new features used, compatibility, and whether it can be polyfilled? This make developers also understand how to be compatible with their

eg. 

- [CSS Variable](https://caniuse.com/?search=CSS%20Variable)
- [fetch](https://caniuse.com/?search=fetch)
- [CSS Masks](https://caniuse.com/?search=CSS%20Masks)
- [Stream API](https://developer.mozilla.org/zh-CN/docs/Web/API/Streams_API)
- ...

### temporary solution

In order to use the new features of the new version.

I had to try my best to polyfill these features, and build an old version that supports IE, and use different versions according to the environment

**Comment by Snuffleupagus** [comment]
In general, please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support for an up-to-date list of the supported browsers/environments. Hence anything not listed there is explicitly unsupported.

> This means that even legacy builds are not compatible with browsers released two years ago

Note that for *obvious* security reasons using such old browsers is generally not a good idea.

Please keep in mind that the *primary* development target in this library is the built-in Firefox PDF Viewer.
Trying to support older browsers/environments quickly becomes complicated, since not all features can be easily polyfilled, and we want to (as much as possible) avoid a situation where we're forced to hold back improvements to the Firefox PDF Viewer just so that we can support some very old browsers.
Furthermore, trying to support older browsers would put a lot of strain on the few regular PDF.js contributors and that's time/effort that's better spent on improving the library itself.

**Comment by kkofler** [comment]
> Note that for _obvious_ security reasons using such old browsers is generally not a good idea.

There are stable branches that get security branches backported, such as QtWebEngine LTS branches. PDF.js since 3.6 (even in legacy mode) no longer works with QtWebEngine 5.15 LTS, the last Qt5WebEngine branch, which is just a pain and forces me to stick to an old PDF.js on the servers I administer.
