### ISSUE TITLE
Download location defaults to Download folder on Chromium

### ISSUE THREAD

**Issue by maneandrea** [mozilla/pdf.js#16348]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chromium 112.0.5615.165
- Operating system and its version: Arch Linux (latest rolling, kernel 6.2.12)
- PDF.js version: 2.3.164
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Go on Chrome settings and set "Ask where to save each file before downloading"
2. Open a PDF
3. Download it with the icon on the top right (sheet of paper with down-pointing arrow)
4. Download starts and the PDF appears in the Download folder

What is the expected behavior?
1. Chrome should ask where to save the file
2. Once the user chooses, download should start

What went wrong?
1. The extension failed to honor the global option of "Ask where to save each file before downloading"

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm

**Comment by Rob--W** [comment]
I don't think that the issue is specific to the Chrome extension, and if it were, then it would be a Chrome bug. The downloading logic in the PDF.js Chrome extension is identical to the logic for the web.

From the description it is not clear whether the file is opened after the download. If it is, then you have probably selected "Always open files of this type" by accident at some point. To resolve that, visit chrome://settings/downloads and click on the "Clear" button next to "Open certain file types automatically after downloading".

Note that there is a specific `downloads.download` extension API that could give the extension more control over the download directory, but without a way to look up the original directory. Furthermore, the usefulness of this method is reduced because there is a bug in Chrome that prevents the extension from controlling the file name if any other (unrelated) extension has registered a `downloads.onDeterminingFilename` listener: https://crbug.com/1106297 (note: despite being marked as Fixed, the issue is not fixed. The regression was merely documented).

**Comment by maneandrea** [comment]
The "Always open files of this type" option fixed the problem. Apologies that it was this trivial and thanks for the help!
