### ISSUE TITLE
How to use pdf.js with Apache Cordova

### ISSUE THREAD

**Issue by zjacky0409** [mozilla/pdf.js#16378]
Configuration:

- Web browser and its version: Cordova 9.x
- PDF.js version: happens on 3.5.141

For my application, I use the nextjs with Cordova for building an application. Then I want to use pdfjs to display pdf file to the users. However, there are two errors occur. 

![pdfjs](https://user-images.githubusercontent.com/62543035/235636508-fee1d877-c81c-47b1-a811-f403f7b5a6d8.png)

btw, my app works for chrome(mobile version), firefox(mobile version).

How can i fix it? Thank you for your help.

**Comment by Snuffleupagus** [comment]
> Web browser and its version: Cordova 9.x

As far as I can tell that's actually a JavaScript framework and *not* a browser. Please keep in mind that we unfortunately cannot provide help/support for the myriad of JS frameworks that exist.

> However, there are two errors occur.

Have you tried using a `legacy`-build of the PDF.js library, since that's often required in older browsers?
