### ISSUE TITLE
Show meta info in pdf

### ISSUE THREAD

**Issue by hitman4an** [mozilla/pdf.js#16384]
In pdf.js lib doesn't view QR-code from metadata.

At Acrobat Reader we can see it.

[
![Screenshot_37](https://user-images.githubusercontent.com/23082585/236181087-202de1b8-6138-4893-849c-ce5af9664f07.png)
](url)
[ДС №2 (2) (2) (2).pdf](https://github.com/mozilla/pdf.js/files/11396519/2.2.2.2.pdf)

**Comment by calixteman** [comment]
The two annotations have their `F` entry equals to 68 (== `Print | ReadOnly`).
Since it's readonly and the pdf doesn't have any embedded scripts, I suppose it's almost equivalent to `Locked | LockedContents` and then we could use their appearance instead of having an HTML element:
https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L474-L478
That said we could have a similar case but with some JS inside and then we'll have the same bug.
An idea could be to have an HTML element + the canvas with its appearance and we use the canvas if it's readonly and remove it if it becomes writable.

@Snuffleupagus, any thoughts ?
