### ISSUE TITLE
Slow loading of PDF

### ISSUE THREAD

**Issue by pshp** [mozilla/pdf.js#16406]
This PDF loads more slowly than average. It also loads instantly in native pdf viewer. Is there any particular reason this file takes longer than other files?

Attach (recommended) or Link to PDF file here: 
[data-service-bundle (4).pdf](https://github.com/mozilla/pdf.js/files/11431142/data-service-bundle.4.pdf)

Configuration:
- Web browser and its version: Chrome 113
- Operating system and its version: Mac OS 12.5.1
PDF.js version: newest (mozilla.github.io/pdf.js demo)

- Is a browser extension: no

Steps to reproduce the problem:
1. Open pdf with mozilla.github.io/pdf.js demo

What is the expected behavior? (add screenshot)
load quickly

What went wrong? (add screenshot)
slow load time https://www.loom.com/share/25a72a82fcb541fd90ed99e859c0e340

**Comment by Snuffleupagus** [comment]
Seems to work fine in Firefox Nightly 115.0a1, on Windows 11, with the pages rendering in under a second in the demo-viewer:

![image](https://github.com/mozilla/pdf.js/assets/2692120/de7d1957-8543-4981-a921-33781af5c65b)

**Comment by ipaqmaster** [comment]
Been having this option for probably over a year now. Opening a basic PDF with just a few paragraphs worth of rich text on a single page opens immediately in any other PDF viewing or editing tool but always has a minimum delay of 5 seconds to open the local file in Firefox  (Current version: 112.0.2).

**Comment by alvaroperez23** [comment]
espabila notas que

**Comment by calixteman** [comment]
No problem for me in Chrome or Firefox on Mac OS 13.3.1 (M1): the loading is under the second.
In looking at a profile in Firefox, some time is spent in `CanvasRenderingContext2D.getImageData`, maybe in Chrome, because of hardware acceleration, there is a huge cost to get the pixels array from the gpu to the main thread.

**Comment by Snuffleupagus** [comment]
Let's close this issue, since:
 - Both https://github.com/mozilla/pdf.js/issues/16406#issuecomment-1540299824 and https://github.com/mozilla/pdf.js/issues/16406#issuecomment-1552140790 indicate that this works fine in Firefox, which is the primary development target for this library.
 - According to https://github.com/mozilla/pdf.js/issues/16406#issuecomment-1552140790 it's not even consistently broken in all Chrome-configurations, hence this unfortunately looks like a bug that needs to be reported to the Chromium-developers instead.
