### ISSUE TITLE
how can I extract contents from a pdf 

### ISSUE THREAD

**Issue by yaotengyuan** [mozilla/pdf.js#16405]
When I use pdf.getOutline() to get the outline, what it returns like this:

> action:null
attachment:undefined
bold:false
color:Uint8ClampedArray(3) [0, 0, 0, buffer: ArrayBuffer(3), byteLength: 3, byteOffset: 0, length: 3, Symbol(Symbol.toStringTag): 'Uint8ClampedArray']
count:5
dest:"pdfname.indd:.103644:12898"
italic:false
items:(5) [{…}, {…}, {…}, {…}, {…}]
newWindow:undefined
setOCGState:undefined
title:"contentName"
unsafeUrl:undefined
url:null

I think I shoud get the number of page from the dest "pdfname.indd:.103644:12898", because I need the page number to display on the website.
what should I do the next?

**Comment by Snuffleupagus** [comment]
> I think I shoud get the number of page from the dest "pdfname.indd:.103644:12898",

Use the `dest`-data as input to the following method, in order to get information about a destination:
https://github.com/mozilla/pdf.js/blob/8f2d8f62f34e3a788673d9a622ba8dafaff05eef/src/display/api.js#L864-L872

The returned data will contain either a page-reference or a page-index, in the former case you'll need to use:
https://github.com/mozilla/pdf.js/blob/8f2d8f62f34e3a788673d9a622ba8dafaff05eef/src/display/api.js#L845-L852

See also the relevant part of the PDF specification for more information about explicit/named destinations:
https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G11.2063217

---

> what should I do the next?

If you completely ignore the ISSUE_TEMPLATE, we unfortunately cannot help you any further.
