### ISSUE TITLE
[Feature] Add `workerOption` in `GlobalWorkerOptions`

### ISSUE THREAD

**Issue by ylc395** [mozilla/pdf.js#16429]
`PDFWorkder` can not create a worker with user custom [workerOptions](https://developer.mozilla.org/en-US/docs/Web/API/Worker/Worker#parameters) for `Worker` constructor.

https://github.com/mozilla/pdf.js/blob/2c0478ecb2aa144230f8afbda5f411f82cb2b4fa/src/display/api.js#L2135-L2137

Can we add a new filed in `GlobalWorkerOptions` to set the wokerOptions?

**Comment by Snuffleupagus** [comment]
There's no need for any new option(s) here, since this is already supported via `GlobalWorkerOptions.workerPort`; note https://github.com/mozilla/pdf.js/blob/2c0478ecb2aa144230f8afbda5f411f82cb2b4fa/src/display/worker_options.js#L18-L19

Hence you simply create a new worker *manually*, and do something like:
```javascript
const worker = new Worker(url, { /* your options here... */ });, and then assign that to pass

**Comment by Snuffleupagus** [comment]
There's no need for any new option(s) here, since this is already supported via `GlobalWorkerOptions.workerPort`; note https://github.com/mozilla/pdf.js/blob/2c0478ecb2aa144230f8afbda5f411f82cb2b4fa/src/display/worker_options.js#L18-L19

Hence you simply create a new worker *manually*, e.g. along these lines:
```javascript
const worker = new Worker(path, { /* your options here... */ });
GlobalWorkerOptions.workerPort = worker;
```
