### ISSUE TITLE
Not showing flattened text with a warning: Error during font loading: Font "F0" is not available.

### ISSUE THREAD

**Issue by PailaGH** [mozilla/pdf.js#16432]
Attach (recommended) or Link to PDF file here:
[inputFields-Flattened-Output.pdf](https://github.com/mozilla/pdf.js/files/11493613/inputFields-Flattened-Output.pdf)

Configuration:
- Web browser and its version:
   Chrome or Edge latest version
- Operating system and its version:
   Windows 11
- PDF.js version:
   Latest version (V3.6.172)
- Is a browser extension:
  No
Steps to reproduce the problem:
1.  open file in https://mozilla.github.io/pdf.js/web/viewer.html
2.  warning that error during font loading

What is the expected behavior? (add screenshot)
Why is not falling back to default font if the font needed (Helvetica) is not available
What went wrong? (add screenshot)
I would expect the missing text to visible, I could see if I add Helvetica font as embeded font
![ExpectedOutput](https://github.com/mozilla/pdf.js/assets/25868810/435b9b38-e573-4ddd-87a1-96610af05507)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I would expect the missing text to visible, I could see if I add Helvetica font as embeded font

Unfortunately your PDF document is simply *corrupt*, since it tries to access a font (here named `F0`) that it doesn't actually contain; hence it's not entirely reasonable to assume that this should work unfortunately.

Given how uncommon this situation is, and that the fault is clearly with the PDF document itself (or possibly with the software creating that file), it's not immediately clear to me that trying to hack-around this in the PDF.js library makes sense.

**Comment by calixteman** [comment]
That said we don't have the widths, but we could use something like:
https://github.com/mozilla/pdf.js/blob/5ae353cf4da5e7fb6e01c166aa5f4f02f12e083a/src/display/canvas.js#L2171-L2184
and then compute the width in using `measureText`.
I'm very likely overlooking some details...
