### ISSUE TITLE
Annotation editor show wrong position when I try new editor from json that is exported from editor serialize.

### ISSUE THREAD

**Issue by muiten188** [mozilla/pdf.js#16442]
Hi
I did it step by step like below:
step 1: draw editor on pdf, 

step 2: using editor.serialize() to export edit to object and store to database.

![image](https://github.com/mozilla/pdf.js/assets/8792451/33a6d7ca-d6b7-40fc-8be6-5b414bd892d2)

step 3: when reopen pdf I load editor data from database and redraw it to pdf by annotationEditorLayer.deserialize() and annotationEditorLayer.addANewEditor(editor)
![image](https://github.com/mozilla/pdf.js/assets/8792451/3a9204ec-b2c0-4194-866d-15649f68a0a2)

It's working but it's showing wrong poisition comparing when I draw editor first time. 
Here I editor I drawed.
![image](https://github.com/mozilla/pdf.js/assets/8792451/36a67336-028b-4aec-872c-9fcf8cf6cb98)

but when redisplay from Json objec, It's wrong position like image below:

![image](https://github.com/mozilla/pdf.js/assets/8792451/3b21e0cb-df28-4824-b7a0-8825a7e4b66d)

Could tell me what's wrong with my solution I did, or how to fix it for display position correctly editor.
thanks

**Comment by Snuffleupagus** [comment]
Please keep in mind that what you're attempting to do here isn't something that we officially support, since the sort of importing/exporting described above isn't needed in the Firefox PDF Viewer.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since most details are unfortunately missing here.
Furthermore, please note that screen-shots of code is really not helpful; please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by pledi** [comment]
@muiten188 @thisisjulien  I had a similar problem and found out that changing `tx` and `ty` to `0` in the following file fixes the issue. 
https://github.com/mozilla/pdf.js/blob/598421b11f067dacfb2cf81897c19b10db3c9988/src/display/editor/editor.js#L310-L311

Note, that for my basic import & export annotation scenario it worked, but I'm not sure if it will break something else.

**Comment by dakshlohar1** [comment]
I am having the same issue, does anybody find any perfect solution?
