### ISSUE TITLE
Unable to preview pdf

### ISSUE THREAD

**Issue by wangzhiming1999** [mozilla/pdf.js#16452]
Attach (recommended) or Link to PDF file here:

![image](https://github.com/mozilla/pdf.js/assets/48944224/717100e9-9047-4023-ba89-84475b4affb9)

Configuration:
- Web browser and its version:113 chrome
- Operating system and its version:
- PDF.js version:1.6.172
- Is a browser extension:

Steps to reproduce the problem:
1. Unable to preview pdf
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required*.

> PDF.js version:1.6.172

That's not an official release, and in any case it's well over six years old and thus (obviously) no longer supported.
Furthermore, that version number doesn't actually agree with your screen-shot; please make sure that you provide *consistent* information to avoid unnecessary confusion.

Generally you should also provide any error messages *as text*, since that's much more usable than having to squint at an image. However, you seem to be running into a CORS issue; hence please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr which is realistically the only assistance that we can provide here.

---

*For future reference:* Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by wangzhiming1999** [comment]
sorry，PDF.js version is 3.6.172

**Comment by wangzhiming1999** [comment]
pdf link is https://d1wqtxts1xzle7.cloudfront.net/48864145/s0194-5998_2898_2970021-x20160915-18772-qx23j9-libre.pdf?1473965701=&response-content-disposition=inline%3B+filename%3DPlasmacytomas_of_the_head_and_neck.pdf&Expires=1684741110&Signature=Fs-EvMflNrcn4hxOC6~fp9cgzXb~1wwMEjj34mxr4k19MX0vsM4MBiNcMyalSbyUSgHPE2gv6gX5zH3NbXFfK~WAXxR~nIotnW7DTuul4BBabZi0dZqhqS44OTc3XXdoy9Z6Jk21~-3hyRjqQ7OZRE-ts791YvnMKVoCpdCd55IMyszwtQYALeEBNInWPoS9WKeVvjh7clpDCdWeEuGuCsscgwnWvpQ7dWuqcpFccE8Ju-0f-MdoMjv3H6ICLYA~Zkp1o1THAZNKOLh-ay-PvxSFDq840zo4F8J-YLaqpPAt0JVE6J~rpr2hg5KhbxKwLCBmxL3-zAS6nkiCj9fRHQ__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA
