### ISSUE TITLE
Issue #14800 is not resolved even in recent build pdfjs-3.6.172

### ISSUE THREAD

**Issue by dhanbhan** [mozilla/pdf.js#16475]
I see Issue #14800 Closed sometime back in last year but it is still not working with recent release. 

I have verified pdfjs-3.6.172 : Page display takes atleast 15 seconds. Until then viewer is blank. But this issue is not reproducible with demo pdfjs url. 

I have asked this question in #14800 but that is marked as out of topic [Not sure for what reason :( ]

Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1.  Refer #14800 
What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I see Issue #14800 Closed sometime back in last year but it is still not working with recent release.

It's not really clear what "still not working" actually means here, given your next sentence.

> I have verified pdfjs-3.6.172 : Page display takes atleast 15 seconds. Until then viewer is blank.

So you're saying that it *does work* eventually, but just a little slowly!? If so, that's expected on e.g. lower-powered hardware when dealing with huge images.

> But this issue is not reproducible with demo pdfjs url.

In that case there must be a bug in your application, which given the lack of details we cannot help you with.

> Configuration:
>     * Web browser and its version:
>     * Operating system and its version:
>     * PDF.js version:
>     * Is a browser extension:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

---

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by dhanbhan** [comment]
@Snuffleupagus I have not used any application other than pdfjs viewer. Please reconsider what I explained in description.

**Comment by dhanbhan** [comment]
Ok. I will recreate issue with all template you are looking.

**Comment by Snuffleupagus** [comment]
The problem is that https://github.com/mozilla/pdf.js/issues/16475#issue-1727212113 unfortunately doesn't *clearly and concisely* explain what you perceive to be the problem, since as mentioned above it contains some *conflicting* details.

Furthermore, you've not really addressed any of the points/questions raised in https://github.com/mozilla/pdf.js/issues/16475#issuecomment-1564119332, so opening yet another issue really doesn't serve any purpose.

*Please note:* This is an open-source project that you're able to use *for free*, where support is handled by *unpaid volunteers* (such as myself), hence please respect peoples time providing all necessary information in a clear manner when opening an issue.
