### ISSUE TITLE
how can i detect the border of pdf's table

### ISSUE THREAD

**Issue by Einskai** [mozilla/pdf.js#16510]
i need to detect the cell area (position and size) of a pdf table, and auto fill some text into the table cell. 
pdf.js can draw the table to canvas, if have some way to detect table's cell area (position and size) by pdf.js's api?
thank.

**Comment by Snuffleupagus** [comment]
Given how rendering works in PDFs, using primitive commands, there's not really any concept of e.g. "tables" unfortunately.
Hence there's no way to access such information, and furthermore this issue is also missing lots of details; please actually fill-out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md *properly* when opening an issue.
