### ISSUE TITLE
Fix new CodeQL scanning warning

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#16518]
There is currently one unresolved warning in https://github.com/mozilla/pdf.js/security/code-scanning/257. It's interesting because the line has been there for almost a year now as it was introduced in https://github.com/mozilla/pdf.js/commit/0c420f5135dc39e37244e74c2dc4584da5eb0f83, but merging https://github.com/mozilla/pdf.js/commit/74c62eaf14126515b96c18cd59a414c5cc850dba 4 days ago seems to have triggered the alert, possibly because of new CodeQL rules having been deployed in the meantime and because the code touched in that commit is very close to this line.

As far as I can tell this looks like a false positive given that the variable swap seems to work if I try this in isolation. If it's indeed a false positive we can simply dismiss the alert in the UI (and we should report it to CodeQL given that previous time we did that it actually got fixed upstream), but if there is actually a bug here we should fix it.

/cc @calixteman as the original author of this code

**Comment by Snuffleupagus** [comment]
It appears that all of the following is now dead code, since after PR #16494 there's no longer anything accessing either `w` or `h` in the code:
https://github.com/mozilla/pdf.js/blob/605d9f492f8fa09f0ab1fb180e95896143fff8e6/src/core/annotation.js#L4100-L4106

On the question on why ESLint doesn't pick this up, I'm guessing that the answer is that it's a *static* code-analyzer which means that it cannot (generally) detect that the `w` and `h` assignments doesn't have side-effects (e.g. they could be getters).
