### ISSUE TITLE
The background color of a specific PDF parsed is incorrect.

### ISSUE THREAD

**Issue by xu-sheng-ssoft** [mozilla/pdf.js#16527]
Attach (recommended) or Link to PDF file here:
[年末年始ラベル特集.pdf](https://github.com/mozilla/pdf.js/files/11659551/default.pdf)

Configuration:
- Web browser and its version: Chrome( 113.0.5672.129（Official Build）(64bit))
- Operating system and its version: Win10 pro
- PDF.js version: 3.7.107
- Is a browser extension: no

Steps to reproduce the problem:
1.  Open this pdf with the demo of pdf.js: https://mozilla.github.io/pdf.js/web/viewer.html
2. Turn to page 12, you can see the background color of this pdf turned to yellow, it's totally diffrent from how it looks in the other pdf viewer such as adobe reader.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/69140145/95c5879e-e67c-4a37-808a-89158c1a95c7)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/69140145/f5d9cd06-b8e3-4fcc-bbe7-2320ae18cc52)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html
※open this pdf with the demo above

**Comment by Snuffleupagus** [comment]
WFM, using the built-in PDF.js version `3.7.95` [cbc4b20b1] in Firefox Nightly 116.0a1 on Windows 11:

![firefox](https://github.com/mozilla/pdf.js/assets/2692120/07e2e412-799f-42e5-8949-f1ac3db04744)

---

Also WFM, using https://mozilla.github.io/pdf.js/web/viewer.html in Google Chrome Beta 115.0.5790.13 on Windows 11:

![chrome](https://github.com/mozilla/pdf.js/assets/2692120/b4fa17bd-bca5-4b85-8a75-b287df68c3cb)

---

Unfortunately this looks like an issue specific to the browser, platform, and/or graphics driver rather than a PDF.js bug, since otherwise you'd really expect it to be consistently broken everywhere. Please report this to the Chromium developers instead, since this doesn't look fixable here unfortunately.
