### ISSUE TITLE
Cannot load PDF due to unsupported encryption algorithm - Again

### ISSUE THREAD

**Issue by esteban-serfe** [mozilla/pdf.js#16537]
Attach (recommended) or Link to PDF file here: https://www.mynavyhr.navy.mil/Portals/55/Reference/Instructions/BUPERS/BUPERSINST 1001.39.pdf

Related to #2647 i assume.

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 3.8.6 [a2118f52b] in Firefox Nightly 116.0a1 on Windows 11.

> Related to #2647 i assume.

That issue was fixed *nine years ago*, so that would suggest that you're using an extremely outdated PDF.js version.

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this unfortunately doesn't contain enough information to be actionable.
