### ISSUE TITLE
How to extend `DOMCanvasFactory` (or detect `canvas.getContext("2d")` returned `null`)

### ISSUE THREAD

**Issue by luncheon** [mozilla/pdf.js#16568]
Like https://github.com/mozilla/pdf.js/issues/16530, I was able to create a `class extends DOMCanvasFactory`, but now `pdfjs-dist/lib` is not found.

This is implemented to detect that `canvas.getContext("2d")` returned `null` (for Safari). 

```ts
import { DOMCanvasFactory } from 'pdfjs-dist/lib/display/display_utils';

class InsufficientCanvasMemoryError extends Error {
  constructor() {
    super('insufficient canvas memory.')
  }
}

class CanvasFactory extends DOMCanvasFactory {
  override create(width: number, height: number) {
    const created = super.create(width, height);
    if (!created.context) {
      throw new InsufficientCanvasMemoryError();
    }
    return created;
  }
}

const doc = await pdfjsLib.getDocument({ data, canvasFactory: new CanvasFactory() }).promise;
```

How can I achieve this in v3.6.172 or later?

Thanks.

**Comment by Snuffleupagus** [comment]
> but now `pdfjs-dist/lib` is not found.

That's because the `lib/`-folder was never intended to be directly used, and in many cases people ran into subtle bugs when using it together with the actual builds; hence why it was removed.

> How can I achieve this in v3.6.172 or later?

Given the size and relative simplicity of the [`DOMCanvasFactory`](https://github.com/mozilla/pdf.js/blob/7588418b0912109348674c9c1993f564da340549/src/display/display_utils.js#L293-L308) and [`BaseCanvasFactory`](https://github.com/mozilla/pdf.js/blob/7588418b0912109348674c9c1993f564da340549/src/display/base_factory.js#L36-L75) classes, you could perhaps just implement a *custom* CanvasFactory from scratch?
Doing so would allow you to make whatever changes deemed necessary for your particular situation.

Considering that we've never exposed any of the BaseFactory-classes as part of the *official* API, since that isn't necessary for the Firefox PDF Viewer (which is the primary development target here), it's not entirely clear to me that we just want to add those to the API unfortunately (since all code needs to be maintained).

**Comment by luncheon** [comment]
It is easy to copy and paste the _current_ `DOMCanvasFactory` and `BaseCanvasFactory`, but when they are modified in future versions, I may not notice and be in trouble...

However, few people will have trouble with these classes not being exposed (just me?). If exporting them increases maintenance costs, then it may be reasonable not to export them.

Thank you for your reply, @Snuffleupagus.

**Comment by Snuffleupagus** [comment]
Having looked *very briefly* at this, I suppose that we might be able to expose at least the BaseFactory-classes in https://github.com/mozilla/pdf.js/blob/master/src/display/base_factory.js as part of the official API.[1]

Given that I'm an *unpaid* contributor to this freely available open-source project, would you be willing to compensate me for implementing that?
(Further conversation on that topic might be best done private, my email address can be found in my GitHub profile.)

---
[1] Since that would be doable with only a minor file-size impact for the Firefox PDF Viewer.
