### ISSUE TITLE
How do I enable form-filling for the PDF document?

### ISSUE THREAD

**Issue by marke-apexit** [mozilla/pdf.js#16582]
I need help on how to enable form-filling for the PDF document.  What I found in the APIs is separate support for Acroforms vs. XFA.  Is there a single function or property to enable form-filling for any PDF with form capability?

**Comment by Snuffleupagus** [comment]
> Is there a single function or property to enable form-filling for any PDF with form capability?

Unfortunately not, since XFA-documents are sufficiently different from AcroForms (i.e. the "normal" type of forms) in PDF documents.

To enable parsing of XFA-documents you need to include `enableXfa: true` in the `getDocument` call; please see https://github.com/mozilla/pdf.js/blob/7742d6e4a6e02d63b6831e097f6274a4206fbc72/src/display/api.js#L220-L221
To enable AcroForm-rendering you need to include `annotationMode: 2` in the `PDFPageProxy.render` call; please see https://github.com/mozilla/pdf.js/blob/7742d6e4a6e02d63b6831e097f6274a4206fbc72/src/display/api.js#L1196-L1207

**Comment by marke-apexit** [comment]
Can I determine from the PDF file if the PDF uses XFA or AcroForm to know how to enable the form filling correctly?

**Comment by Snuffleupagus** [comment]
> Can I determine from the PDF file if the PDF uses XFA or AcroForm to know how to enable the form filling correctly?

That'd require actually parsing the PDF document, since the PDF format itself is complex enough that you cannot necessarily answer such a question easily just be "looking" at the PDF file.
However you can just use both of the mentioned options at the same time, since that's what the [default viewer](https://github.com/mozilla/pdf.js#online-demo) is doing and things should just work.

**Comment by marke-apexit** [comment]
Where in the repository is the source for the "default viewer?"
