### ISSUE TITLE
PDF viewer is crashing in ios iphone only

### ISSUE THREAD

**Issue by twravindra** [mozilla/pdf.js#16591]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: iOS Chrome browser (Version 114.0.5735.133 (Official Build) (arm64))
- Operating system and its version: iOS
- PDF.js version: 3.7.107
- Is a browser extension: no

Steps to reproduce the problem:
1. Open a pdf in any iOS iphone
2. try to zoom in as much as possible.
3. Sometime this works perfectly fine but crashses as well many times.

What is the expected behavior? (add screenshot)

Should be able to zoom without crash.

What went wrong? (add screenshot)
App crashes when zoomed as much as possible in ios.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
not hosted

**Comment by Snuffleupagus** [comment]
> * Open a pdf in any iOS iphone
> * try to zoom in as much as possible.
> * Sometime this works perfectly fine but crashses as well many times.

We've seen other issues that suggest that iOS limits canvas-sizes much more than other environments, so that could perhaps be related here.
Given that this issue suggest an *intermittent* and browser-specific problem, this unfortunately doesn't really look fixable in the PDF.js library (please also keep in mind that Firefox is the primary development target).

**Comment by Mowmowj** [comment]
@twravindra  do you have same issue in chrome browser with iOS system?
