### ISSUE TITLE
Issue in pdf rendering, while using gradient fill in pdf.

### ISSUE THREAD

**Issue by sathishsakthi-ss** [mozilla/pdf.js#16611]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: chrome,firebox..etc
- Operating system and its version: mac,linux,window...etc
- PDF.js version: all version
- Is a browser extension: no

Steps to reproduce the problem:
1. upload the given pdf.
2.Render in pdfjs

What is the expected behavior?
<img width="1015" alt="image" src="https://github.com/mozilla/pdf.js/assets/137885954/5b522b69-bc17-43ae-a226-79a01ae77ea5">

What went wrong? image border colour changed
<img width="979" alt="image" src="https://github.com/mozilla/pdf.js/assets/137885954/bd545553-e69e-4382-8802-2419cb7c94b4">

original pdf:
[pdf with gradient fill.pdf](https://github.com/mozilla/pdf.js/files/11880979/pdf.with.gradient.

original pptx:
[Presentation with Gradient Fill.pptx](https://github.com/mozilla/pdf.js/files/11881043/Presentation.with.Gradient.Fill.pptx)
fill.pdf)

**Comment by Snuffleupagus** [comment]
> Web browser and its version: chrome,firebox..etc
> Operating system and its version: mac,linux,window...etc
> PDF.js version: all version

Please remember to provide actual version *numbers*, since "all version" unfortunately isn't really helpful.

---

WFM, using PDF.js version `3.8.107` [03059e1f8] in Firefox Nightly 116.0a1 on Windows 11.

This was most likely fixed by PR #16106, which is present in the current versions; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
