### ISSUE TITLE
Conflicting PDF text positions reported by pdf.js vs pdfminer

### ISSUE THREAD

**Issue by jamescrowley** [mozilla/pdf.js#16634]
I'm trying to round-trip from pdfminer server side text positions into pdf.js. Is this something you'd expect to be possible? Using the `compressed.tracemonkey-pldi-09.pdf` file the block of text "Trace-based Just-in-Time Type Specialization for Dynamic" has the correct x1, x2, width and height but y1 and y2 are offset slightly. 

I am not sure which library is 'correct' (or indeed if both can be correct, and this is subject to interpretation?). 

If this isn't reliable across text blocks, are there other ways to safely roundtrip references to text segments in the PDF? If we were to use PDF.JS on the back-end too, are these safe to round-trip over an extended time period (ie are these positions stable across releases if we were storing them in a database?). Thanks

**pdfjs**:

```
{
    "location": {
        "x0": 80.5159,
        "x1": 529.607,
        "y0": 700.6706,
        "y1": 718.6034,
        "width": 449.0911,
        "height": 17.9328
    },
    "text": "Trace-based Just-in-Time Type Specialization for Dynamic\n"
}
```

**pdfminer**:

```
{
  "location": {
    "x0": 80.5159,
    "x1": 529.607,
    "y0": 696.9226,
    "y1": 714.8554,
    "width": 449.0911,
    "height": 17.9328
  },
  "text": "Trace-based Just-in-Time Type Specialization for Dynamic\n"
}
```

# Attach (recommended) or Link to PDF file here

https://github.com/mozilla/pdf.js/blob/master/web/compressed.tracemonkey-pldi-09.pdf

# Configuration:
- PDF.js version: 3.8.162
- PDFMiner version: 20221105

# Steps to reproduce the problem:

1. pdfjs: (full code here: https://jsfiddle.net/jamescrowley/tzg8sb9w/32/)

```
  // 'item' is an item in the array from getTextContent
  return { 
    "location": { 
        "x0": Number(item.transform[4].toFixed(4)),
        "x1": Number((item.transform[4] + item.width).toFixed(4)),
        "y0": Number(item.transform[5].toFixed(4)),
        "y1": Number((item.transform[5] + item.height).toFixed(4)),
        "width": Number(item.width.toFixed(4)),
        "height": Number(item.height.toFixed(4)),
    },
    "text": item.str + (item.hasEOL ? "\n" : "")
  }
```
2. pdfminer (full code here: https://colab.research.google.com/drive/1nocq-on3mnOcsYTEvNu8ii8voF7VAP8x#scrollTo=2CqZLqUWXe_N)

```
# text_line is an item in the LTTextContainer arrays from extract_pages
return ({ 
    "location": { 
        "x0": round(text_line.x0, 4),
        "x1": round(text_line.x1, 4),
        "y0": round(text_line.y0, 4),
        "y1": round(text_line.y1, 4),
        "width": round(text_line.x1 - text_line.x0, 4),
        "height": round(text_line.y1 - text_line.y0, 4),
    },
    "text": text_line.get_text()
})
```

# What is the expected behavior? (add screenshot)

x0,y0,x1,y1 match across libraries on same text block.

# What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

1. pdf.js: https://jsfiddle.net/jamescrowley/tzg8sb9w/32/
2. pdfminer: https://colab.research.google.com/drive/1nocq-on3mnOcsYTEvNu8ii8voF7VAP8x#scrollTo=2CqZLqUWXe_N

**Comment by Snuffleupagus** [comment]
> I'm trying to round-trip from pdfminer server side text positions into pdf.js. Is this something you'd expect to be possible?

Unfortunately not, since "pdfminer" is a different project that we don't really know anything about here. (The comparison also becomes more difficult because of the differing programming languages used in the two projects.)

> I am not sure which library is 'correct' (or indeed if both can be correct, and this is subject to interpretation?).

Indeed, it's not immediately clear who is at "fault" here unfortunately.

> If we were to use PDF.JS on the back-end too, are these safe to round-trip over an extended time period (ie are these positions stable across releases if we were storing them in a database?).

While I don't believe that this has particular data has changed too much over the years, we however *cannot* guarantee stability in future releases.
Please keep in mind that the *primary* development target for the PDF.js library is the built-in Firefox PDF Viewer, hence if changes are deemed necessary for the Firefox use-case they will generally be made (even if that breaks backwards compatibility).

**Comment by calixteman** [comment]
I'd say that's because the coordinates you extracted from the matrix corresponds to the position of the base line and not to the position of one of the corner of the bbox.
Hence I'd say that this diff of ~4 corresponds the depth.

**Comment by calixteman** [comment]
The baseline is the virtual line where the text is drawn.
A glyph has a part above the baseline and its measure is its ascent, when the measure of the part below is the descent (or depth).
The bounding box is computed in using the position of the baseline, the max of the ascents and the max of the descents.
In horizontal mode, the only accurate values are the baseline position (x0 and y0) and the width of the box.
The height of the box is computed as the norm of the second column of the text matrix which almost corresponds to the font size.
So here height is equal to 17.9328 because the first instructions in the pdf are:
```
BT
/F41 17.9328 Tf 80.5159 700.6706 Td[(T)74(race-based)-250(J)
```
The `Tf` instruction is here to select the font /F41 at size 17.9328.
The font itself can specify a depth and you can find it in the `styles` object (see `g_d0_f1: Object { fontFamily: "sans-serif", ascent: 0.69, descent: -0.209, … }`) and  -0.209x17.9328 gives -3.7479552 which is the difference you're looking for.

**Comment by jamescrowley** [comment]
@calixteman thanks so much for the detailed explanation, it's really much appreciated

**Comment by jamescrowley** [comment]
For future reference if anyone comes across the same issue, I was able to get the pdf.js co-ordinates and pdf miner co-ordinates to match doing the following:
```

const loadPages = async function(file: string) {
  const doc = await pdfjs.getDocument(file).promise;
  const numPages = doc.numPages;
  const data:any[] = [];
  for (let pageNum = 1; pageNum <= numPages; pageNum++) {
    const page = await doc.getPage(pageNum);
    const viewport = page.getViewport({ scale: 1.0 });
    const opList = await page.getOperatorList(); // <- required to ensure font data available
    const content = await page.getTextContent();
    
    const blocks = await Promise.all(content.items
            .map(async (item: TextItem | TextMarkedContent) => {
              if (!item.hasOwnProperty("str")) {
                return "";
              }
              const textItem = item as TextItem;
              const font = await page.commonObjs.get(textItem.fontName); // <-- get font data
              const belowBaseline = font.descent * textItem.height; // <-- calculate as @calixteman described
              return { 
                "location": { 
                    "x0": Number(textItem.transform[4].toFixed(4)),
                    "x1": Number((textItem.transform[4] + textItem.width).toFixed(4)),
                    "y0": Number((textItem.transform[5] + belowBaseline).toFixed(4)),
                    "y1": Number((textItem.transform[5] + belowBaseline + textItem.height).toFixed(4)),
                    "width": Number(textItem.width.toFixed(4)),
                    "height": Number(textItem.height.toFixed(4)),
                },
                "text": textItem.str + (textItem.hasEOL ? "\n" : "")
              }
            }))
```

**Comment by Snuffleupagus** [comment]
*Given https://github.com/mozilla/pdf.js/issues/16634#issuecomment-1623058988 I'm assuming that we can close this as fixed now.*
