### ISSUE TITLE
PDFjs Viewer accumulates memory usage when paging/scrolling some PDF files.

### ISSUE THREAD

**Issue by TrilokJaladi** [mozilla/pdf.js#16647]
Attach (recommended) or Link to PDF file here:
[DI-c036090-09-00-44.364.pdf](https://github.com/mozilla/pdf.js/files/11967434/DI-c036090-09-00-44.364.pdf)

Configuration:
- Web browser and its version: Chrome, firefox (all browsers)
- Operating system and its version:
- PDF.js version: Observed from PDFjs versions v2.14.305.b9
- Is a browser extension:

Steps to reproduce the problem:
1. Open the pdf in pdfjs viewer. Click on pagedown arrow button continuously.
2. Check the memory usage in the task manager.
3. Cache clearing is not consistent. Sometimes it clears pretty quick and sometimes it take time to clear.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
I am attaching 2 screenshot, one with version 2.5 and another with version 3.18. I navigated upto 40 pages in both the cases and as you see the memory with version 3.8.162 increased.
<img width="1533" alt="pdfjs-2 5 207" src="https://github.com/mozilla/pdf.js/assets/131751104/dbcdba3e-efbe-4b06-a376-2cb69fb4322b">
<img width="1590" alt="pdfjs-3 3 122" src="https://github.com/mozilla/pdf.js/assets/131751104/3ba0ecdd-fa21-4684-a51d-ebce74fcf449">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> 3\. Cache clearing is not consistent. Sometimes it clears pretty quick and sometimes it take time to clear.

So you're saying that it does work, but just a little slower than you'd like? If so, that's not really a bug that we can do much (or anything) about unfortunately.

(Note that that we're caching *more* data in recent PDF.js versions, and images are handled slightly differently, since that generally improves performance.)

With PDF.js being a JavaScript application we can only remove references to no longer needed data-structures, however the decision on how/when said data is actually being evicted from memory is ultimately up to the browser *and* operating system.

---

Unless you can demonstrate a situation where cached data is *never* evicted from memory, I'm sorry to say that this unfortunately doesn't really look actionable here.
