### ISSUE TITLE
 PDF viewer defaults to 2nd page w/ cropped 1st page

### ISSUE THREAD

**Issue by helicos6** [mozilla/pdf.js#16644]
Attach (recommended) or Link to PDF file here: [Example PDF](https://d.pr/f/zDwvS0)

Configuration:
- Web browser and its version: Obsidian version: v1.3.5
- Operating system and its version: Darwin Kernel Version 22.5.0: Thu Jun 8 22:22:20 PDT 2023; root:xnu-8796.121.3~7/RELEASE_ARM64_T6000 22.5.0 (macOS 13.4.1)
- PDF.js version: not sure what's included with Obsidian version: v1.3.5
- Is a browser extension: Obsidian.md extension

Steps to reproduce the problem:

1. Embed a PDF file ( that contains a cropped 1st page ) in an Obsidian note.

Please note that PDF files that do not have a cropped 1st page do not have this issue.

What is the expected behavior? (add screenshot)

When I open the note, the PDF viewer would show me the 1st page of the PDF file.

![image](https://github.com/mozilla/pdf.js/assets/34452093/80871010-6377-4062-9f6c-d35d6bfb4ea5)

What went wrong? (add screenshot)

When I open the note, the PDF viewer shows me the 2nd (or a later) page of the PDF file.

![image](https://github.com/mozilla/pdf.js/assets/34452093/f7c3aa56-baa2-4b22-8615-e9b552a89fd3)

Comments:

This issue was raised in Obsidian forum: [PDF viewer defaults to 2nd page w/ cropped 1st page - Bug reports - Obsidian Forum](https://forum.obsidian.md/t/pdf-viewer-defaults-to-2nd-page-w-cropped-1st-page/62604/3). I was informed this is a problem with PDF.js and should be reported here.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here: [Example PDF](https://d.pr/f/zDwvS0)

*For future reference:* Please just *attach* the document, as recommended, rather than linking it since that's much easier.

> Web browser and its version: Obsidian version: v1.3.5

Sorry, but we have no idea what that is and consequently we cannot provide help/support for it here (quick googling also suggests that it's not a *browser*); please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> Steps to reproduce the problem:
>     1. Embed a PDF file ( that contains a cropped 1st page ) in an Obsidian note.

Given that we don't use "Obsidian note" here, whatever that it is, this information unfortunately isn't really possible to follow. (Your screen-shots also don't show a viewer that we've developed here.)

For this to become actionable you'd need to provide a clear and concise bug report without any references to "Obsidian", based e.g. on https://github.com/mozilla/pdf.js#online-demo such that it's possible to rule out that something in "Obsidian" isn't causing the problems.

**Comment by helicos6** [comment]
@Snuffleupagus Apologies, I will open a new issue that conforms to your requirements.
