### ISSUE TITLE
Signature is missing in mobile browser

### ISSUE THREAD

**Issue by lizaiqian** [mozilla/pdf.js#16679]
Attach (recommended) or Link to PDF file here:
[compact.pdf](https://github.com/mozilla/pdf.js/files/12026528/compact.pdf)

Configuration:
- Web browser and its version: **mobile mode** of Edge(114.0.1823.79) & Chrome(114.0.5735.199); Safari in IOS mobile
- Operating system and its version: Windows, 
- pdfjs-dist version: 3.8.162
- Is a browser extension: 

Steps to reproduce the problem:
1. open edge/chrome to visit https://url and view the pdf, signature is shown normally.
2. change the mode to mobile mode and then the signature is missing
<img width="1072" alt="image" src="https://github.com/mozilla/pdf.js/assets/38561884/e301a347-a14f-4e34-a827-24da45139f11">

What is the expected behavior? (add screenshot)
The signature is normal in browser of mobile phone.
What went wrong? (add screenshot)
The signature is missing in browser of mobile phone as well as mobile mode of chrome and edge.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version 3.9.24 [c33e6ceb0] in Firefox Nightly 117.0a1 on Windows 11.

![firefox](https://github.com/mozilla/pdf.js/assets/2692120/c5f2b266-3f0d-46c2-be70-eabf32509ac5)

---

> Web browser and its version: **mobile mode** of Edge(114.0.1823.79) & Chrome(114.0.5735.199); Safari in IOS mobile

Unfortunately this suggest bugs in the *browsers themselves*, rather than in the PDF.js library, since otherwise you'd really expect this to be consistently broken everywhere. (Note that Firefox is the primary development target here.)
