### ISSUE TITLE
Large image in pdf not displayed in IOS

### ISSUE THREAD

**Issue by gabifuse** [mozilla/pdf.js#16680]
Hello! I have a pdf file that consist only of a large image (4000px4000px).
When loading the page:

```
const pdf = await pdfjs.getDocument(data }.promise;
const canvas = document.createElement('canvas');
const page = await pdf.getPage(0);
 viewport = page.getViewport({ scale: 1 });
const context = canvas.getContext('2d');
canvas.height = viewport.height;
canvas.width = viewport.width;
await page.render({ canvasContext: context, viewport }).promise;
const pageAsImage = canvas.toDataURL()
```

I get the following error in IOS 

Canvas area exceeds the maximum limit (width * height > 16777216)

I understand the error but how i can display the page any way?

What im trying to achieve at the end of day is displaying the pdf page to the client.
Btw the same error happens i use react-pdf.
How i can handle this?

Thanks in advance,
Gabi.

**Comment by Snuffleupagus** [comment]
> I get the following error in IOS
> Canvas area exceeds the maximum limit (width * height > 16777216)

Please note that this is a limitation of the *browser itself*.

Furthermore, beginning with PDF.js version `3.5.141` we're *attempting* to downsize large images. However this depends on `OffscreenCanvas` being available in the browser, and Safari was (comparatively) slow at implementing this; see https://developer.mozilla.org/en-US/docs/Web/API/OffscreenCanvas#browser_compatibility

---

*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this isn't really actionable/valid.
