### ISSUE TITLE
Text layer editing

### ISSUE THREAD

**Issue by MallRoy** [mozilla/pdf.js#16688]
Attach (recommended) or Link to the PDF file here: 

Configuration:
- Web browser and its version: 
- Operating system and its version: Windows
- PDF.js version:  3.6.126
- Is a browser extension: no

Steps to reproduce the problem:
1. I am trying to identify the text layer and edit it. I was able to achieve that. But am not able to save the edited text. Please suggest to me how to achieve that.

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/54269166/484690aa-6a78-4bcf-b321-f6c7c1bbfc44)

What went wrong? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/54269166/15fdaef1-0117-4772-bdca-48c6a0abdf3c)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> PDF.js version:  3.6.126

That's not an official release; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> But am not able to save the edited text. Please suggest to me how to achieve that.

We support adding and/or editing some type of *annotations*, however completely "arbitrary" editing (which is effectively what you're asking for) isn't something that we do/will support.
Please keep in mind that the PDF.js library is primarily a PDF *viewer* rather than a complete PDF editing-library.
