### ISSUE TITLE
EnhanceTextSelection Removed in v3.6.172

### ISSUE THREAD

**Issue by JChan106** [mozilla/pdf.js#16684]
- PDF.js version: v3.6.172

We are looking to upgrade our PDFjs version from v2.14.305 to v3.6.172, and noticed that the ENABLE_ENHANCE / EnhanceTextSelection, text layer mode has been removed in v3.6. We currently use ENABLE_ENHANCE mode for our webapp, so the deprecation and removal of this mode would be a significant downgrade. What was the reason for the removal? Does that mode not work with the PDF versions v3.0 > anymore? Does the team have plans to bring the Enhance Text Selection mode back? We would also like to know if it's possible to retrofit PDFjs v3.6.172 to have ENABLE_ENHANCE. Thanks!

**Comment by Snuffleupagus** [comment]
> What was the reason for the removal?

Some reasons for removing the "enhanced" textLayer mode include:
 - It's generally slower than the regular text-selection mode, given e.g. the extra upfront parsing.
 - It often led to noticeably slugging behaviour when selecting text, given the amount of DOM invalidation that happens when starting/ending text-selection.
 - As far as I recall, it only worked acceptably for LTR documents.
 - It was never used in the *built-in* Firefox PDF Viewer (i.e. the primary development target for this library). However it contributed >10 kB of (essentially) unused code in the builds.
 - It was "getting in the way" of previous/future improvements to the textLayer, and it'd already started to regress in some cases. This would only get worse over time, since it was mostly unused and never *properly* tested.
 - It had known bugs; such as e.g. issues 14463 and 15138.
 - It was never being actively developed/maintained, and had since very little work done after it was added in 2016.

> Does that mode not work with the PDF versions v3.0 > anymore?

Probably not, note also all the caveats above, however we cannot really provide any help/support for that (since we *purposely* removed the code).

> Does the team have plans to bring the Enhance Text Selection mode back?

No.
