### ISSUE TITLE
Update the `vinyl-fs` package to the latest version

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#16694]
This package had its *major* version increased, please see https://github.com/gulpjs/vinyl-fs/releases/tag/v4.0.0, but simply updating the package without any changes on the PDF.js-side unfortunately causes the `gulp web` build-target to "break" files when copying them into the `gh-pages`-directory.

Some examples (there may be more) of the kind of breakage that occurred:
 - The `web/viewer.html` file had its BOM removed.
 - The `web/compressed.tracemonkey-pldi-09.pdf` file was "inflated", with its stream-data being modified, completely breaking it.

**Comment by timvandermeij** [comment]
I have bisected the BOM problem to https://github.com/gulpjs/vinyl-fs/commit/bfb56cdfeda7af45804095716034f0f8473bd5f0 which renamed `stripBOM` that we use to `removeBOM`, so that should fortunately be a trivial fix. What I don't really understand is that that was already changed in version 3.0.0, see that commit and also the changelog at https://github.com/gulpjs/vinyl-fs/releases/tag/v3.0.0, and we use 3.0.3, so either this hasn't worked since already or there was some conversion of `stripBOM` to `removeBOM` going on that I can't find...

**Comment by timvandermeij** [comment]
The pull request above gets rid of our direct dependency on `vinyl-fs` because we don't need it anymore, which overall seems like the simplest way to resolve this issue, and it fixes the BOM stripping issue. Note that `vinyl-fs` is still an _indirect_ dependency (of Gulp), but it's pinned to version 3 there which works well. This is also better because our `vinyl-fs` version can no longer get out of sync with what Gulp expects, which I think contributes to the problems listed in this issue. If `vinyl-fs` is updated to version 4 in Gulp that'll most likely be in Gulp 5 which we'll have to test carefully anyway, but the issues found here may already be solved then.

I have confirmed that the BOM stripping is indeed not a regression from the new `vinyl-fs` version and that's already not working correctly with the current version. To find this, I ran `file web/viewer.html` on the current master branch file and got `web/viewer.html: HTML document, Unicode text, UTF-8 (with BOM) text`. However, if I run this on the output of `gulp web`, which uses the `vinyl-fs` path with BOM stripping disabled, I get `viewer.html: HTML document, Unicode text, UTF-8 text` which confirms that the BOM is indeed removed.

According to threads like https://github.com/gulpjs/vinyl-fs/issues/72#issuecomment-117289656 the BOM doesn't have much meaning anymore for UTF-8 documents like this. https://stackoverflow.com/a/2223926 seems to confirm that BOM is unnecessary, but people also claim it can't hurt to have it. In any case, we'll recover the original behavior by using the options provided through `gulp.src` now, which is possible since Gulp 4 according to https://github.com/gulpjs/gulp/issues/1557#issuecomment-194536219, after which we get `build/gh-pages/web/viewer.html: HTML document, Unicode text, UTF-8 (with BOM) text` again.

**Comment by Snuffleupagus** [comment]
> According to threads like [gulpjs/vinyl-fs#72 (comment)](https://github.com/gulpjs/vinyl-fs/issues/72#issuecomment-117289656) the BOM doesn't have much meaning anymore for UTF-8 documents like this. https://stackoverflow.com/a/2223926 seems to confirm that BOM is unnecessary, but people also claim it can't hurt to have it.

The BOM was added in PR #3957, specifically to disable the "Character Encoding menu" when using the *built-in* Firefox PDF Viewer. Given that that menu was replaced in [bug 1687635](https://bugzilla.mozilla.org/show_bug.cgi?id=1687635) it's not really clear to me if we still need the BOM nowadays!?

**Comment by timvandermeij** [comment]
With that in mind, and the fact that the BOM hasn't actually been there for five years and nobody noticed, I'm also not opposed to removing it; for the initial patch above I just played it safe so we could get rid of the dependency.
