### ISSUE TITLE
无法生成文本

### ISSUE THREAD

**Issue by zank888** [mozilla/pdf.js#16708]
const textLayer = new TextLayerBuilder({
        textLayerDiv: textLayerDiv,
        pageIndex: page._pageIndex,
        viewport: viewport,
      });
      console.log(4, textLayer, page._pageIndex);
      textLayer.setTextContentSource(textContent);

      textLayer.render(viewport).then(console.log(10));
无法将文本dom查到页面中
![image](https://github.com/mozilla/pdf.js/assets/128762824/1ee40d8d-49ce-4dc1-8c3c-883569f38d26)
haishik还是空的,是写法出错了吗

**Comment by Snuffleupagus** [comment]
First of all, you need to communicate *only in English* when using this bug tracker.

Secondly, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue since this contains no actionable information.

Finally, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
