### ISSUE TITLE
Using canvas is very terrible in pdf viewer

### ISSUE THREAD

**Issue by zxlgh** [mozilla/pdf.js#16739]
Attach (recommended) or Link to PDF file here:
[2201.03281.pdf](https://github.com/mozilla/pdf.js/files/12163188/2201.03281.pdf)
Configuration:
- Web browser and its version: Chrome, 115.0.5790.102
- Operating system and its version: windows 10
- PDF.js version: 3.9.49
- Is a browser extension: yes

Steps to reproduce the problem:
1. open any pdf file.

What is the expected behavior? (add screenshot)
more clear text
What went wrong? (add screenshot)
the text is blurry
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Seems fine to me, when using PDF.js 3.9.130 [71f113bf8] in Firefox Nightly 117.0a1 on Windows 11.

---

Note that the ISSUE_TEMPLATE specifically ask for screenshots, so please provide that!

**Comment by zxlgh** [comment]
Thanks for you reply!

This is suspected to be due to the html canvas rendering used, not the rendering method like pdf software, eg, Adobe Acrobat.

Following is display effect in PDF.js:
 
![pdf](https://github.com/mozilla/pdf.js/assets/118647377/16134696-dfba-4fdf-a168-f8cb6b2c5afc)

This is the display effect in Adobe Acrobat extension in chrome:
![adobe](https://github.com/mozilla/pdf.js/assets/118647377/6521f5e5-a27a-4218-a957-c85670b564ee)

Looking forward to your reply!

**Comment by Snuffleupagus** [comment]
I'm not really seeing any "blurriness" in Firefox, which is the *primary* development target for the PDF.js library; see

![rendering](https://github.com/mozilla/pdf.js/assets/2692120/b0e83d80-444e-4c83-84de-976ef95977b1)

---

However please keep in mind that the rendering quality of a `canvas` is ultimately controlled by the browser, operating system, and graphics drivers used, hence it's not clear what (if anything) we can do about this here unfortunately since we can't remove `canvas`-usage for rendering.
