### ISSUE TITLE
First few pages not rendering when scroll up fast. Upgrading from pdfjs-1.6.210 to pdfjs-3.8.162

### ISSUE THREAD

**Issue by anudhuri23** [mozilla/pdf.js#16743]
Attach (recommended) or Link to PDF file here:
**_We are currently using pdfjs version pdfjs-1.6.210, which has xss issues. To esolve that I am trying to upgrade to pdfjs-3.8.162.
As per doc https://github.com/mozilla/pdf.js, I took the pdfjs-3.8.162-dist.zip from https://github.com/mozilla/pdf.js/releases/tag/v3.8.162 and updated pdf.js as mention in the doumentation_**
Configuration:

**I am attaching viewer.js for reference**

Configuration:

- Web browser and its version: 115.0.2 (64-bit)
- Operating system and its version: windows 10
- PDF.js version: pdfjs-3.8.162
- Is a browser extension: no

Steps to reproduce the problem:
- update the new pdf.js
- try to view in viewer

What is the expected behavior? (add screenshot)

PDF should be rendered properly

What went wrong? (add screenshot)
PDF not rendering on scroll up

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by anudhuri23** [comment]
@Snuffleupagus erlier PDFJS object had few properties like 
    "maxImageSize": -1,
    "disableFontFace": false,
    "imageResourcesPath": "",
    "disableWorker": false,
    "disableRange": false,
    "disableStream": false,
    "disableAutoFetch": false,
    "postMessageTransfers": true,
    "disableCreateObjectURL": false,
    "disableWebGL": true,
    "externalLinkTarget": 0,
    "externalLinkRel": "noreferrer",
    "isEvalSupported": true,
    "openExternalLinksInNewWindow": false,
    "LinkTarget": {
        "NONE": 0,
        "SELF": 1,
        "BLANK": 2,
        "PARENT": 3,
        "TOP": 4
    },

In new pdfjs object those are missing. How to get those?

**Comment by Snuffleupagus** [comment]
> earlier PDFJS object had few properties like

Most of those are `getDocument`-options, please see https://github.com/mozilla/pdf.js/blob/8f83a1359eb759507c66205ed40ab35bf83ccf13/src/display/api.js#L118-L236

Some of them are options for the relevant viewer-components. In the default viewer options are handled via https://github.com/mozilla/pdf.js/blob/master/web/app_options.js

Considering that you didn't specified *exactly* which option(s) your question is about, it's impossible to provide more detailed information unfortunately.

---

Given that https://github.com/mozilla/pdf.js/issues/16743#issuecomment-1652167336 doesn't seem to have much to do with this issue as originally reported in https://github.com/mozilla/pdf.js/issues/16743#issue-1821777277, and that this issue is still lacking *crucial* details/information necessary to make it actionable, let's just close this now.

*For future reference:* Please keep in mind that this is first and foremost an open-source *bug tracker* (rather than a support forum), frequented by unpaid volunteers (such as myself), hence all issues need to contain every piece of information necessary to clearly and concisely illustrate the problem.

**Comment by anudhuri23** [comment]
@Snuffleupagus  How can I get the any property value from pdfjs object as I wanted to build the viewer based on the above properties. Erlier we used to do like **PDFJS.disableRange, PDFJS.maxCanvasPixels, PDFJS.useOnlyCssZoom,PDFJS.disableTextLayer, PDFJS.pdfBug**. Now all these propertied are not present in PDFJS object.

**Comment by Snuffleupagus** [comment]
> PDFJS.disableRange

That's a `getDocument`-parameter, which you'd have seen if you looked at the JSDocs linked in https://github.com/mozilla/pdf.js/issues/16743#issuecomment-1652999846; did you actually bother reading that comment?

> PDFJS.pdfBug

That's for only intended for development purposes, so you should most likely not use that one.

> PDFJS.maxCanvasPixels, PDFJS.useOnlyCssZoom,PDFJS.disableTextLayer

The rest of them are `PDFViewer`-options, please see https://github.com/mozilla/pdf.js/blob/8f83a1359eb759507c66205ed40ab35bf83ccf13/web/pdf_viewer.js#L81-L124

**Comment by anudhuri23** [comment]
@Snuffleupagus  How can I get the any property value from pdfjs object as I wanted to build the viewer based on the above properties. Erlier we used to do like **PDFJS.disableRange, PDFJS.maxCanvasPixels, PDFJS.useOnlyCssZoom,PDFJS.disableTextLayer, PDFJS.pdfBug**. Now all these propertied are not present in PDFJS object.
