### ISSUE TITLE
Rendering Issues

### ISSUE THREAD

**Issue by blackmambahk** [mozilla/pdf.js#16814]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome 115.0.5790.114 (arm64)
- Operating system and its version: Mac OS Ventura
- PDF.js version: 3.10.54
- Is a browser extension:
[NACS_BellyBand_Trims.pdf](https://github.com/mozilla/pdf.js/files/12303524/NACS_BellyBand_Trims.pdf)

Steps to reproduce the problem:
1. open pdf in chrome on mac latest os and latest mac m1/m2 chips
2. 

What went wrong? (add screenshot)
![WMJ Portal Screenshot](https://github.com/mozilla/pdf.js/assets/947206/48416d90-c26a-475f-9276-b4620c530c86)
What is the expected behavior? (add screenshot)
![Screenshot of the downloaded file](https://github.com/mozilla/pdf.js/assets/947206/a0b2b1ae-e4ac-4c22-9987-f0771c0be762)

A layer with some extra peppers shows up on the wrong screenshot

Only a problem in Chrome, not a problem in Safari. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
WFM, using https://mozilla.github.io/pdf.js/web/viewer.html in both Firefox Nightly 118.0a1 and Chrome Beta 116.0.5845.82 on Windows 11.

> Web browser and its version: Chrome 115.0.5790.114 (arm64)
>
> open pdf in chrome on mac latest os and latest mac m1/m2 chips
>
> Only a problem in Chrome, not a problem in Safari.

Unfortunately all of this points to a browser/platform-related bug, rather than a PDF.js library one, since otherwise you'd expect it to be consistently broken everywhere. (Also, please keep in mind that Firefox is the primary development target for this library.)

This seem like a `canvas`-bug that probably needs to be reported to the Chromium developers instead.
