### ISSUE TITLE
incorrect rendering of latex pdf

### ISSUE THREAD

**Issue by ilyapashuk** [mozilla/pdf.js#16836]
pdf is generated from the following latex code:

[simplemath.tex.txt](https://github.com/mozilla/pdf.js/files/12344963/simplemath.tex.txt)

with pdflatex command, from texlive 2023 with default settings

pdf is the following:

[simplemath.pdf](https://github.com/mozilla/pdf.js/files/12344969/simplemath.pdf)

expected behavior:
pdfjs should use font from the pdf

actual behavior:
pdfjs uses system font, which is not needed in this case. as a result, math content displayed incorrectly on some platforms.

configuration:
windows 10 1809, firefox 116, pdfjs shipped with firefox

question:
how to force pdfjs to use embedded font whenever possible, even if it thinks that something is wrong with it?

**Comment by Snuffleupagus** [comment]
WFM, with the caveat that I don't speak Russian, using PDF.js 3.10.80 [690b87389] in Firefox Nightly 118.0a1 on Windows 11.

![fonts](https://github.com/mozilla/pdf.js/assets/2692120/e9d0ebf2-8eb3-49d2-9dde-7fc77612856d)

---

> pdfjs should use font from the pdf

The embedded fonts *are used* in my testing, and there's also no error/warning messages printed in the console.

> how to force pdfjs to use embedded font whenever possible, even if it thinks that something is wrong with it?

If a font is rejected by OTS (i.e. the OpenType Sanitizer) for some reason, which doesn't actually seem to happen here, it's simply *impossible* to force the browser to use said font.

---

It's not really clear what the "brokenness" looks like in your case, since you didn't include any screen-shots!
(This is something that the ISSUE_TEMPLATE specifically asks for, and please remember to fill out the ISSUE_TEMPLATE as it's presented to you rather than deleting it.)

**Comment by ilyapashuk** [comment]
screenshot:

![Screenshot 2023-08-15 at 18-02-07 simplemath pdf](https://github.com/mozilla/pdf.js/assets/40538919/e138f58c-d1da-47ab-b4ff-9a8065280f54)

that's how it looks in my Windows.

there is simple quadratic equation in this document.

the Equals sign looks like minus sign, which is incorrect, but copies as a equal sign.

in linux with firefox 116, all works perfectly.

therefore, this looks like as a problem with my windows system font.

logs:
[jslog.txt](https://github.com/mozilla/pdf.js/files/12345538/jslog.txt)

**Comment by ilyapashuk** [comment]
screenshot from the fresh latest nightly:
![Screenshot 2023-08-15 at 18-22-41 simplemath pdf](https://github.com/mozilla/pdf.js/assets/40538919/c0016a45-0032-4f0a-91d1-ac06d22021fd)

screenshot from the clear fresh profile of ff 116:

![Screenshot 2023-08-15 at 18-28-10 simplemath pdf](https://github.com/mozilla/pdf.js/assets/40538919/2ba3a9f9-2906-4ab2-94fd-72e1c3009e51)

**Comment by Snuffleupagus** [comment]
Given that this appears to work with a fresh profile, based on https://github.com/mozilla/pdf.js/issues/16836#issuecomment-1679180582, that unfortunately suggests that you've changed some setting(s) in your regular profile which break font handling in the browser.

**Comment by timvandermeij** [comment]
Closing given the above; I don't see anything actionable for us here at the moment.
