### ISSUE TITLE
Question: release >= 3.5.141 pageColors invalid on safari, edge is valid

### ISSUE THREAD

**Issue by maxiloEmmmm** [mozilla/pdf.js#16838]
Attach (recommended) or Link to PDF file here: https://www.rfc-editor.org/rfc/pdfrfc/rfc2328.txt.pdf
Configuration:
- Web browser and its version: safari 16.3 (18614.4.6.1.6)
- Operating system and its version: 13.2.1 (22D68)
- PDF.js version: >= 3.5.141(test) < 3.9.179(no test),
- Is a browser extension: no

Steps to reproduce the problem:
1. let pv = new PDFPageView({pageColors: {foreground: "#000", background: "rgb(204, 232, 207)"}, ...other_opts})
2. pv.draw()

What is the expected behavior? (add screenshot)
change color

<img width="194" alt="image" src="https://github.com/mozilla/pdf.js/assets/16779121/e6756b5f-2a86-4536-b6b0-58213235807d">

What went wrong? (add screenshot)
no change

<img width="175" alt="image" src="https://github.com/mozilla/pdf.js/assets/16779121/19efde19-c40d-4012-8fac-8316050e8588">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

but windows edge is ok!

version 3.4.120,3.3.122 ok on edge and safari!

brief code:

<img width="679" alt="image" src="https://github.com/mozilla/pdf.js/assets/16779121/94a2c1fd-aff0-4e6d-ae7e-25fef70829ce">

**Comment by Snuffleupagus** [comment]
> PDF.js version: >= 3.5.141(test) < 3.9.179(no test)

Assuming that I'm reading this correctly, it appears that you've not actually tested version `3.9.179`?
If so, please make sure that you do since as of this writing that's the *only* version that we support.

> Steps to reproduce the problem:
>     1. let pv = new PDFPageView({pageColors: {foreground: "#000", background: "rgb(204, 232, 207)"}, ...other_opts})
>     2. pv.draw()

If I change [the relevant options](https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/web/app_options.js#L147-L161) in the default viewer it seems to work just fine when testing against the PDF.js `master`-branch in Firefox Nightly 118.0a1 on Windows 11.

Hence, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

> but windows edge is ok!
> version 3.4.120,3.3.122 ok on edge and safari!

That'd unfortunately suggest a problem in the Safari browser *itself*, since otherwise you'd really expect it to be consistently broken everywhere. Please note that Safari is only listed as "mostly" supported in the FAQ: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

**Comment by maxiloEmmmm** [comment]
hello @Snuffleupagus

> 如果我更改默认查看器中的[相关选项，](https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/web/app_options.js#L147-L161)`master`那么在 Windows 11 上的 Firefox Nightly 118.0a1 中针对 PDF.js 分支进行测试时，它似乎工作得很好。

windows edge no problem on all versions. only safari

> 假设我正确阅读了这篇文章，看来您还没有实际测试过版本`3.9.179`？ 如果是这样，请确保您这样做，因为完成撰写论文时，这是我们支持的_唯一版本

v3.9.179 There is a problem under **Vite** and cannot be tested
I saw the relevant pr, it is estimated that it has been fixed, but there is no new release yet


> _不幸的是，这表明 Safari 浏览器本身_存在问题，否则你真的会认为它到处都会出现问题。请注意，FAQ 中仅将 Safari 中的“大部分”支持：[https://github.com/mozilla /pdf.js/wiki/ 常见问题#faq-support](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support)

Ok, I saw it, but this (pageColors) was supported in the previous version (<3.5.141), but suddenly it is not supported on Safari. It feels like a code problem. I will debug it later to see what the problem is.

thks

**Comment by maxiloEmmmm** [comment]
maybe this https://stackoverflow.com/questions/51549143/context-filter-not-working-on-safari

**Comment by Snuffleupagus** [comment]
> https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/canvas.js#L1168

If you actually follow the "blame" on that line you'll find PR #16075, where you'll see that this was changed *purposely* to improve handling of images. Note also that the `pageColors`-functionality is *primarily* intended for HCM, as clearly mentioned in the documentation: https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/api.js#L1232-L1234

Furthermore, the changes in that PR *significantly* simplified the overall implementation and quite frankly we'll not consider reverting that patch (or any patch really) just for improved Safari-compatibility.
The fact that this doesn't work in Safari is a bug in the *browser itself*, since all other modern browsers have supported the necessary functionality for many years; see https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/filter#browser_compatibility

Finally, please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target for this library and that as already mentioned Safari has only ever been listed as "mostly" supported.

**Comment by maxiloEmmmm** [comment]
thk reply
