### ISSUE TITLE
iOS print capture the wrong content

### ISSUE THREAD

**Issue by Aresenka** [mozilla/pdf.js#16833]
Attach (recommended) or Link to PDF file here: any page that contains a PDF file rendered by pdf.js ([example](https://pdfobject.com/examples/pdfjs-forced.html))

Configuration:
- Web browser and its version: Safari for iOS 16.4 (simulated by xCode, reproduced on a physical device as well)
- Operating system and its version: iOS 16.4 (simulated, reproduced on a physical device as well)
- PDF.js version: 3.9.148 [a2eca47ed]
- Is a browser extension: NO

Steps to reproduce the problem:
1. Open ([this link](https://pdfobject.com/examples/pdfjs-forced.html)) with an iOS browser (I can use only Safari);
2. Click on the "Print" button in the viewer menu:
<img width="294" alt="Screenshot 2023-08-14 at 23 27 12" src="https://github.com/mozilla/pdf.js/assets/38325864/2a3c6bb4-f45e-4369-9d7b-50f1ce86cc0f">

2.a.1. !Optional! Click on the Share button:
<img width="290" alt="Screenshot 2023-08-14 at 23 28 12" src="https://github.com/mozilla/pdf.js/assets/38325864/9073f99c-7888-4a8d-9b61-28650d4da515">
2.a.2. !Optional! Select Print down the list.

What is the expected behavior?

Print preview contains all the PDF pages rendered correctly:
<img width="299" alt="Screenshot 2023-08-14 at 23 30 37" src="https://github.com/mozilla/pdf.js/assets/38325864/bbfa8aff-fc7c-48b0-95cc-fc9a583375f8">

What went wrong? 

Print preview contains only the first page (or even nothing) with an artefacts of the viewer's header (second screenshot):
<img width="295" alt="Screenshot 2023-08-14 at 23 16 06" src="https://github.com/mozilla/pdf.js/assets/38325864/fbde83ee-5ff4-4d25-8aa1-983a23c22b3e">
<img width="301" alt="Screenshot 2023-08-14 at 23 09 52" src="https://github.com/mozilla/pdf.js/assets/38325864/a5f27867-bb49-48b6-bb11-760999581955">

2.a. Print preview contain two pages: first is a complete HTML page without the PDF; second is a blank page (I suppose there should be a PDF file)

I tried to find anything related to the issue for the whole day and found nothing. It seems like this issue appeared after iOS version 15 release, but I can't prove this theory (I don't have an iOS device neither can download a Simulator for earlier version of iOS).

**Comment by Snuffleupagus** [comment]
> PDF.js version: 3.9.148 [[a2eca47](https://github.com/mozilla/pdf.js/commit/a2eca47ed1882c0c5c59b1943ca1e9333397a49e)]

Note that that's not an *official release*, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Open ([this link](https://pdfobject.com/examples/pdfjs-forced.html)) with an iOS browser (I can use only Safari);

That page contains an "ancient" version of the PDF.js default viewer, apparently version `1.3.91` which is from 2016 and has been unsupported for years.

---

Unfortunately this issue really sounds like an problem with the browser and/or platform itself, rather than a bug in the PDF.js library/viewer as such. Please keep in mind that browsers (still) provide fairly limited abilities to control printing via JavaScript, and we're thus forced to jump through some hoops in order to (at all) support printing in the viewer.
Furthermore, please note that Safari is probably the browser that we've seen the most printing-related issues with and that it's also generally the most difficult browser to support; note how Safari is still only listed as "mostly" supported in the FAQ: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Finally, given that the built-in Firefox PDF Viewer is the *primary* development target for this library this issue is unfortunately very unlikely to be fixed here.
