### ISSUE TITLE
After I save a file, the webpage will restart, and the modifications that I have made after opening the file will be lost. Can you please let me know how to solve this issue?

### ISSUE THREAD

**Issue by rusty-peilin** [mozilla/pdf.js#16848]
Everything is described in the title.

**Comment by Snuffleupagus** [comment]
Given the complete lack of details, the following is probably the only help that we can provide here: https://github.com/mozilla/pdf.js/blob/c72cb5436def2d6f2e703447c8b901e92b4dd403/src/display/api.js#L1038-L1044

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md
(Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum.)

Furthermore, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
