### ISSUE TITLE
how to bind events in a new button?

### ISSUE THREAD

**Issue by Benjaminbai** [mozilla/pdf.js#16846]
I want to add a button in web/viewer.html and js files, I study the source code but doesn't success, how did pdfjs bind events worked ?
<img width="257" alt="image" src="https://github.com/mozilla/pdf.js/assets/23426556/9849ae65-5a14-4659-8d85-691ab8eddd9a">
I tried follow download button's logic, but failed.

**Comment by Snuffleupagus** [comment]
Unfortunately you've not shown what you actually tried, and thus more specifically what didn't work.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum. Hence all issues are required to contain enough details to be easily actionable in order to be valid.

**Comment by Benjaminbai** [comment]
thanks for your advice, its every funny, the button has disabled attributes that I don't realized. hahaha, my mistake.
