### ISSUE TITLE
Searching bar feature should be  introduced

### ISSUE THREAD

**Issue by ankush1233** [mozilla/pdf.js#16857]
A Searching bar feature should be introduced to make it easier to go to the page directly

**Comment by Snuffleupagus** [comment]
This has been implemented for *many years* in the default viewer:

![find](https://github.com/mozilla/pdf.js/assets/2692120/30eaa05c-273d-49b1-a50e-fac424aa7fb3)

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this contains nowhere near enough context be be actionable/valid
