### ISSUE TITLE
DFKai-sb font support

### ISSUE THREAD

**Issue by kelibox** [mozilla/pdf.js#16855]
Configuration:
- Web browser : Firefox 58
- Operating system and its version: win10
- PDF.js version: v2.0.588 maybe
- Is a browser extension: no

Steps to reproduce the problem:
1. a  doc uses dfkai-sb font. print as pdf.
2. font display is not correct.

What is the expected : 
acrobat reader open and display it correct, but pdfjs not.

**Comment by Snuffleupagus** [comment]
This is missing the `Attach (recommended) or Link to PDF file here:`-section of the ISSUE_TEMPLATE, which means that it's unfortunately not actionable/valid as-is.

> Web browser: Firefox 58

That browser is *many years* out-of-date, please update to one that still receive support and updates; please also see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version: v2.0.588 maybe

That version is no longer supported, since it's *many years* out-of-date (and it's also not an official release); please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by kelibox** [comment]
https://github.com/mozilla/pdf.js/issues/16870
