### ISSUE TITLE
Cant load pdf from URL

### ISSUE THREAD

**Issue by hermesgido** [mozilla/pdf.js#16851]
why i can load pdf from URL example aws s3??
 
 defaultOptions.defaultUrl = {
    value: "asw pdf url",  ##wont work, works if the pdf is in localhsot
    kind: OptionKind.VIEWER
  };

**Comment by Snuffleupagus** [comment]
It could be e.g. a CORS issue, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since there's unfortunately no actionable information provided here.

Please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
