### ISSUE TITLE
Is there any way to enable progressive loading/rendering using local pdfjs embedded as an iframe? 

### ISSUE THREAD

**Issue by connwork** [mozilla/pdf.js#16866]
Configuration:
- Web browser and its version: Firefox latest
- Operating system and its version: Windows 11
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Use pdfjs locally, disable CORS in firefox so that pdfs can be opened locally, open pdf manually through viewer.html

What is the expected behavior? (add screenshot)
Progressive loading/rendering is still possible even with a local implementation

What went wrong? (add screenshot)
Progressive loading is not possible

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): N/A

I would assume that this is because progressive loading/rendering uses range requests. 

Is there any way to enable progressive rendering locally?

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

*For future reference:* Please remember to provide the viewer *number*, since "latest" is ambiguous. 

> What is the expected behavior? (add screenshot)
> Progressive loading/rendering is still possible even with a local implementation
> 
> What went wrong? (add screenshot)
> Progressive loading is not possible

If by "local implementation" you mean that the viewer (and PDF document) is accessed via a `file://` URL, then that's probably expected be

> 1. Use pdfjs locally, disable CORS in firefox so that pdfs can be opened locally, open pdf manually through viewer.html

Does this actually mean that the viewer (and PDF document) is accessed via a `file://` URL, since that's not really clear from the description!?

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

*For future reference:* Please remember to provide the version *number*, since "latest" is ambiguous and naturally changes over time.

> Use pdfjs locally, disable CORS in firefox so that pdfs can be opened locally, open pdf manually through viewer.html

Assuming that you actually mean that the PDF document is loaded via a file:// URL, then it's unfortunately not expected that streaming and/or range-request work since those are features that require the data to be provided by a *web server*.
