### ISSUE TITLE
How to override default options from app_options.js?

### ISSUE THREAD

**Issue by c-x-g** [mozilla/pdf.js#16867]
Hello, first time using this tool and it's been working great so far. 

I just think the resolution is a bit too grainy and would like to improve it and I found that there were some default values set in the [app_options.js file](https://github.com/mozilla/pdf.js/blob/08f26be7b41a0d98e7e841fcc2750920d3e7680a/web/app_options.js#L4)

Sorry if this has been asked already, is there a way to configure the imported PDFJS object to override default values? In my case I would like to increase the printResolution value on line 67

**Comment by Snuffleupagus** [comment]
*For future reference:* When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since it's slightly difficult to know the exact context of your questions otherwise.

> is there a way to configure the imported PDFJS object to override default values?

You can listen for the "webviewerloaded" event and change options before the viewer has initialized, e.g. something along the following lines (see also https://github.com/mozilla/pdf.js/wiki/Third-party-viewer-usage#initialization-promise):
```javascript
document.addEventListener("webviewerloaded", function() {
  PDFViewerApplicationOptions.set(/* option name here */, /* option value here */);
});
```

> In my case I would like to increase the printResolution value on line 67

Note that this option, as its name suggests, only affects *printing* and furthermore increasing it too much will lead to very undesirable memory usage during printing.
