### ISSUE TITLE
Pdf pages not visible because of the Cache

### ISSUE THREAD

**Issue by anudhuri23** [mozilla/pdf.js#16879]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Chrome(Same issue on FF)
- Operating system and its version: Windows 11
- PDF.js version: Latest (pdfjs-3.10.111)
- Is a browser extension: No

Steps to reproduce the problem:
1. Upgrade to latest version
2. Try to load the pdf

What is the expected behavior? (add screenshot)
PDF should be visible without any issue.

What went wrong? (add screenshot)
**I upgraded the pdf.js to the latest version(pdfjs-3.10.111). I am trying to view the pdf which has 14 pages, when I am scrolling down and again up, initial 4 pages are not visible. I updated the the DEFAULT_CACHE_SIZE to 15 and tried the same. And the PDF rendered properly. Again I tried with another pdf which has 90 pages and the issue was same. I updated the DEFAULT_CACHE_SIZE to 90 and issue resolved.

I tried the same files with the old version of pdf.js 1.6.210, there is no issue. Pdf file with 90 pages is loading properly with the same DEFAULT_CACHE_SIZE which is 10.

We calculate the cache _Math.max(DEFAULT_CACHE_SIZE,2 * visiblePages.length + 1);_ with this, I feel cache is defined for every page which is visible. But in our case it required like noOfPages = Cache. Is page cleanup is having any issue?

Is there any change with cache in later versions?**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> I upgraded the pdf.js to the latest version(pdfjs-3.10.111).
> [...]
> I tried the same files with the old version of pdf.js 1.6.210, there is no issue.

I'm guessing that you cannot reproduce the problem with the demo viewer, see https://github.com/mozilla/pdf.js#online-demo, but rather only with a *custom viewer*?
In that case, you most likely didn't update your code/viewer to account for e.g. the API-changes that happened between the two versions mentioned above.

The best way to handle this would probably be to start with the *latest version* of the default viewer, and modify it to suite your needs, rather than trying to just insert a new PDF.js version into an "ancient" custom viewer.

Furthermore, as has been mentioned on multiple previous occasions; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Please keep in mind that this is first and foremost an open-source *bug tracker* (frequented by unpaid contributors), rather than a support forum, and all issues are thus *required* to contain every piece of necessary information in order to be easily actionable.

**Comment by anudhuri23** [comment]
@Snuffleupagus Yeh I understand that I need to start with latest version of default viewer but the thing is we have legacy code of viewer. So it is very difficult to manage the legacy code. Currently only thing I can do is debugging and that's what I am doing right now.
