### ISSUE TITLE
"cannot read properties of undefined (reading 'AnnotationEditorType')"Error while intialising PDFViewer.

### ISSUE THREAD

**Issue by RZ-Jyothsna** [mozilla/pdf.js#16903]
![Screenshot from 2023-09-05 13-40-31](https://github.com/mozilla/pdf.js/assets/117725492/ff352665-fc46-4fe1-82ac-7e80018b35fb)

 This is the code i added to intialise pdf viewer. I got this error
 
 
![Screenshot from 2023-09-05 13-42-04](https://github.com/mozilla/pdf.js/assets/117725492/39a1353b-492a-49c8-9f52-0cfab9bcdc84)

How to handle this.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since this issue unfortunately isn't actionable/valid as-is.

Furthermore, screen-shots of code and error messages are really not helpful; please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
