### ISSUE TITLE
Private methods and attributes makes it almost impossible to extend functionality without forking

### ISSUE THREAD

**Issue by heliomx** [mozilla/pdf.js#16946]
Could you help me understand the rationale behind using numerous private methods and attributes within the class definitions? I've noticed that it presents challenges when trying to extend the classes into modified subclasses. Would there be room to discuss possible alternatives or adjustments?

**Comment by Snuffleupagus** [comment]
> Could you help me understand the rationale behind using numerous private methods and attributes within the class definitions?

Because that makes it much easier to make changes to functionality that's intended to be *internal*, without that breaking e.g. API-compatibility even more than necessary.
Note that over time, as we add and modify code, we'll be likely be adding even more private fields/methods since that's now supported by JavaScript.

> I've noticed that it presents challenges when trying to extend the classes into modified subclasses.

If you have "custom" requirements, forking the library is probably easiest. (Please keep in mind that the primary development target in the *built-in* Firefox PDF Viewer.)

> Would there be room to discuss possible alternatives or adjustments?

It might be more meaningful to focus on the *specific examples* that you have in mind, since in the *general* case I don't think that we want to (nor should) stop using private fields/methods.

**Comment by heliomx** [comment]
@Snuffleupagus

I appreciate the design decisions you've made to distinguish between the public and internal APIs, and I certainly see the value in encapsulating certain functionalities. However, I wanted to discuss a potential trade-off: if the internal API was accessible to descendants (akin to the concept of protected), it might facilitate greater flexibility for developers who wish to extend specific components.

For instance, I've been looking to customize the way `PDFPageView[]` is instantiated within the `PDFViewer.setDocument` method. Normally, my approach would be to override the setDocument method, retaining the majority of the original code while tweaking the necessary sections. But given the numerous calls to private properties, such as the one [here](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L761):
```javascript
if (this.#annotationEditorUIManager) {
        this.#annotationEditorUIManager.destroy();
        this.#annotationEditorUIManager = null;
}
```
it's become challenging to proceed without extensive modifications.

This has led me to consider forking the entire codebase for a minor alteration, which brings about complexities in build and deployment processes. Naturally, this approach might not be the most efficient in terms of maintainability and resource usage.

I came across an article that touches upon this very subject: [The case against private methods](https://osoco.es/thoughts/2018/10/the-case-against-private-methods/). It raises some intriguing points on the potential limitations of strictly private methods.

I understand there's no one-size-fits-all solution, but I was hoping we could open a dialogue about this. Could there be a middle ground that allows the library to be more extensible while retaining its core principles?

Thank you for considering my perspective.

**Comment by Snuffleupagus** [comment]
> [...] it might facilitate greater flexibility for developers who wish to extend specific components.

Maybe, but it also makes it much easier for users to shoot themselves in the foot by calling methods or accessing properties that are only intended to be "internal" which could lead to all kinds of breakage. And no, just because the name of something begins with an underscore or it's documented as `@private` unfortunately doesn't really "stop" users from making such mistakes.

(Unfortunately many users tend to try "anything" that *appears* to do what they want, whether or not it's actually a good idea.)

> [...] It raises some intriguing points on the potential limitations of strictly private methods.

To me this is basically a limitation of JavaScript *itself* since it only has two modes of operation here. Either everything being "public" with all of the problems that follow with it, or using private methods/fields and sacrifice some ease of extensibility.

> Could there be a middle ground that allows the library to be more extensible while retaining its core principles?

As far as I'm concerned any attempt at reducing/removing usage of private methods/fields is the wrong way to go since it would *even further* increase the maintenance burden of the PDF.js library/viewer.
Please note that keeping the general PDF.js library/viewer "working" outside of the Firefox PDF Viewer is taking a *very significant* amount of time and effort on the part of *unpaid contributors* (such as myself).

**Comment by heliomx** [comment]
@Snuffleupagus I agree that adding an underscore doesn't necessarily deter developers who are determined to modify internals, and similarly, forking an open-source project offers its own form of freedom. I believe the distinction between public and protected types often serves as guidance for developers, highlighting the recommended interaction boundaries with the library.

My main point is to emphasize the ergonomics of code and the potential benefits of a more extensible approach.
