### ISSUE TITLE
Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.

### ISSUE THREAD

**Issue by Marcelin97** [mozilla/pdf.js#16949]
Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.

i have install pdfjs-dist for preview pdf on my app.
i use the commande line yarn : yarn add pdfjs-dist@3.4.120
i use node 14.18

**Comment by Snuffleupagus** [comment]
> Deprecated API usage: No "GlobalWorkerOptions.workerSrc" specified.

That means that you should set `GlobalWorkerOptions.workerSrc` to point to the location of the `pdf.worker.js` file in order to guarantee that the library works correctly.

> pdfjs-dist@3.4.120

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> i use node 14.18

The version is no longer supported, note https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

---

*For future reference:* When opening an issue, please remember to fill out the ISSUE_TEMPLATE properly rather than removing it.

**Comment by Marcelin97** [comment]
ok thank you but the project of my company work with node v 14.18 and i have a message in my console : for exemple : error pdfjs-dist@3.5.141: The engine "node" is incompatible with this module. Expected version ">=16". Got "14.18.0"
error Found incompatible module.
do you have a solution ?
