### ISSUE TITLE
English and Arabic text are overlapping in PDF 

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#16953]
Attach (recommended) or Link to PDF file here:
[test arabic1.pdf](https://github.com/mozilla/pdf.js/files/12619780/test.arabic1.pdf)

Configuration:
- Web browser and its version: Chrome, firefox
- Operating system and its version: Windows 11
- PDF.js version: 3.10.111
- Is a browser extension:

Steps to reproduce the problem:
1.  Open the above PDF in PDF.js viewer
2.

What is the expected behavior? (add screenshot)
Arabic text to be displayed properly without overlap. 
What went wrong? (add screenshot)
<img width="242" alt="image" src="https://github.com/mozilla/pdf.js/assets/79515387/fcaf07da-7163-4725-b5ed-2270390c0e09">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by mirnalinikarthik** [comment]
The above text displays in ADOBE perfectly.

**Comment by Snuffleupagus** [comment]
Given that we seem to match PDFium (i.e. the Google Chrome PDF Viewer) exactly, I'd say that it's your PDF document that's broken. You need to embed *all fonts* in order to guarantee that PDF Viewers will render your document correctly.

![image](https://github.com/mozilla/pdf.js/assets/2692120/c09b129e-b936-468e-9a63-f9301c19307f)

**Comment by ahmedelsied** [comment]
I think the direction of the canvas element will fix that

**Comment by Snuffleupagus** [comment]
As already mentioned in https://github.com/mozilla/pdf.js/issues/16953#issuecomment-1721317421, your PDF document is wrong which is why multiple viewers cannot handle this "correctly". More specifically:
 - The relevant fonts are *not* embedded in the PDF document, which is the first problem with your document.
 - The relevant fonts contain *no information* about how the glyph-mapping should be done. With those non-embedded fonts being CIDFontType2 they should've included CIDToGIDMap-data which would've prevented this issue.
 - The only possible indication of the "intended" glyph-mapping in this case is the ToUnicode-data of the fonts, which is what we're "forced" to fallback on[1], but unfortunately that data contains "bad" entries which explain the problem reported here.

Given the complete lack of *proper* data to use for the glyph-mapping, and that the only available information is "wrong", there unfortunately doesn't seem to be much that we can do here without breaking other PDF documents with non-embedded fonts.

---
[1] If we didn't use the ToUnicode-data in cases such as these we'd have *a lot* more problems with non-embedded fonts.
