### ISSUE TITLE
page.getAnnotations doesn't have opacity?

### ISSUE THREAD

**Issue by DavoodFaezian** [mozilla/pdf.js#16976]
`
page.getAnnotations().then(function (pageAnnotations) {
    console.log(pageAnnotations)
    pageAnnotations.forEach((annotation) => {
                 let color = annotation.color
                lineWidth =annotation.borderStyle.width,//works fine
                opacity= annotation.opacity//doesn't exists
          })

})
})

`

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since it's unfortunately not really possible to understand *exactly* what you're asking for here since in the general case there may not actually be just one "opacity" value for an Annotation.

Also, given that the Firefox PDF Viewer is the primary use-case, please note that we're somewhat unlikely to expose "unused" properties on the Annotation-data that's returned by the API.
