### ISSUE TITLE
Text looks different from its original format in Brave Browser latest versions

### ISSUE THREAD

**Issue by SSivakrishnan** [mozilla/pdf.js#17042]
Attachment or Link to the PDF file here:
[PDF testing file (1).pdf](https://github.com/mozilla/pdf.js/files/12746672/PDF.testing.file.1.pdf)

Configuration:
- Web browser and its version:  Brave Browser v 1.47+
- Operating system and its version: Windows and Mac 

Steps to reproduce the problem:
1. Go to Brave browser (version above 1.47)
2. render/parse the attached PDF in that browser ([PDF testing file (1).pdf](https://github.com/mozilla/pdf.js/files/12746672/PDF.testing.file.1.pdf)
)
3. You can see the text is not aligned properly (not its original format) (if you render/parse the PDF in Chrome/Firefox/Safari works perfectly)

What is the expected behaviour? Text should aligned properly like in Chrome/Firefox/Safari

What went wrong? The text looks different from its original format in Brave latest versions

Screenshot:
<img width="1621" alt="image" src="https://github.com/mozilla/pdf.js/assets/42609285/f58ca617-3d26-432c-a0b0-e6f017d2ff34">

**Comment by Snuffleupagus** [comment]
> Web browser and its version:  Brave Browser v 1.47+

Sorry, but that's not a browser that we support in the PDF.js project; please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

Also, you've not said anything about which PDF.js version you're using.

> You can see the text is not aligned properly (if you render/parse the PDF in Chrome/Firefox/Safari works perfectly)

If it works in all other browsers that most unfortunately points to a bug in the "Brave browser" itself, rather than in the PDF.js library and you'll probably need to report this to the browser developers instead.
