### ISSUE TITLE
disable --scale-factor and use fixed scale (or use scale from viewport)

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#17084]
https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.min.js

When using the text layer

console error
```
The `--scale-factor` CSS-variable must be set, to the same value as `viewport.scale`, either on the `container`-element itself or higher up in the DOM.
```

How to disable `--scale-factor` and use a fixed scale instead??

code
```
page.getTextContent().then(content=>{
	pdfjsLib.renderTextLayer({
		textContentSource: content,
		container: text[0],
		viewport,
		scale // <--- SET THE SCALE TO A FIXED SCALE
	});
});
```

Or even better. How to use the scale from the viewport directly without setting it multiple places?

```
page.getViewport({
	scale
});
```

**Comment by Snuffleupagus** [comment]
> How to disable `--scale-factor` and use a fixed scale instead??

That's unfortunately not supported, since the `--scale-factor` CSS variable is always expected to be available and correctly set. (Please keep in mind that the *primary* development target for this library is the built-in Firefox PDF Viewer.)

> Or even better. How to use the scale from the viewport directly without setting it multiple places?

That'd not be better for the viewer, since it'd affect zooming performance negatively, hence why it's implemented the way it is.

Unfortunately we cannot add options for everything that a particular user may want, since that'd add too much maintenance/testing/support overhead to the code-base.

**Comment by clarkk** [comment]
@timvandermeij  @Snuffleupagus 

But the console errors says:
```
The `--scale-factor` CSS-variable must be set, to the same value as `viewport.scale` ...
```

If `--scale-factor` has to be the same value as `viewport.scale` why doesn't you take and use that value? You compare the values anyway? If `--scale-factor` is not present it would be logic to just use it instead of throwing an error..

This working fine in previous versions where you could just set the value manually on the text layer but now `--scale-factor` is incorporated in each child elements in the text layer!?

**Comment by calixteman** [comment]
Instead of saying that it doesn't make sense, please try to understand why we did that and if you can proposed a better patch please just do it.
For reference it has been done here:
https://github.com/mozilla/pdf.js/pull/15722

And really, if you've a better solution please tell us, thank you.

**Comment by clarkk** [comment]
@calixteman 

If you want it to stay flexible to other people to use this change will not favor it. 

I just gave you a simple example on how to do it. When you calculate the position of each child element of the text layer you could calculate it relative to the height and width but doing something like this on each text node child on the text layer

```
style="left:10.34%; top:1.32%"
```

**Comment by clarkk** [comment]
I have been using this library for years but this resent change break the common use with this `--scale-factor` property

Now you have to add a css selector for each zoom stage.. What if the zoom is custom and the user can type whatever zoom value they want? Then you need `n` of css selectors

**Comment by calixteman** [comment]
We use percent most of the spans in the text layer except when we've a tagged pdf (the elements with the tag info contain the spans of the text layer, hence we can't use percent because their parent isn't the text layer itself).
And we use the css var to compute the font size.
Before the mentioned patch, at every zoom step, the text layer was rebuilt, so it helped avoid to do it.
So in general we don't break anything just to annoy people but because we've good reasons to do it and here I'm sorry to think that performances matter more than few coding annoyances.
Jonas said it before, but our only goal is to develop and improve the Firefox pdf viewer.
That said, I'm still happy to learn something, so if you've some ideas to improve the current situation please tell us.

**Comment by clarkk** [comment]
If you spend resources to traversing through the DOM to check for `--scale-factor` you might as well set it dynamically instead of throwing an error. Everybody is happy

```
text_layer.style.setProperty('--scale-factor', scale);
```
