### ISSUE TITLE
Not using cached files

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#17085]
PDF.js keep fetching/requesting the file even if it is cached in the browser?

PDF file response headers
```
Access-Control-Allow-Origin: *
Cache-Control: public, max-age=31536000
Content-Encoding: gzip
Content-Length: 45378
Content-Type: application/pdf
Date: Fri, 06 Oct 2023 19:04:08 GMT
Expires: Sat, 05 Oct 2024 19:04:08 GMT
Last-Modified: Fri, 06 Oct 2023 18:54:40 GMT
Server: nginx
```

https://i.stack.imgur.com/dPx40.png

**Comment by Snuffleupagus** [comment]
> PDF.js keep fetching/requesting the file even if it is cached in the browser?

The PDF.js library simply requests the URL using either the Fetch API or XMLHttpRequest, and it's then up to *the browser* to serve a cached resource if such exists. It's unfortunately not clear what, if anything, the PDF.js library could do differently here!

---

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md rather than removing the template.
Also, in cases such as these, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

**Comment by clarkk** [comment]
When reading this you can actually force the browser to used any cached resource instead of fetching the same resource over and over again 

https://rapidapi.com/guides/cache-data-fetch
