### ISSUE TITLE
Legacy build seems not work, still have optional chain

### ISSUE THREAD

**Issue by Spike-Leung** [mozilla/pdf.js#17082]
From https://github.com/mozilla/pdfjs-dist : 

> For usage with older browsers or environments, without support for modern features such as optional chaining, nullish coalescing, and private class fields/methods; please see the legacy/ folder.

After `npm install pdfjs-dist` and import `pdfjs-dist/legacy/build/pdf.js`, it still has modern features.

![image](https://github.com/mozilla/pdf.js/assets/30440218/792c1d6a-5361-4319-967d-bce807455bc8)

![image](https://github.com/mozilla/pdf.js/assets/30440218/c6fc9cbc-cde7-4ddb-a2db-0b50495b035e)

I also searched on the GitHub repo, it seems there are no modern features in the legacy build: 

![image](https://github.com/mozilla/pdf.js/assets/30440218/dcd716c2-f754-4588-af78-4f0bcd29b101)

According to the README, these features should not be included in the legacy build. 

Is there something wrong with my operation?

Configuration:
- PDF.js version:  3.6.172
- Is a browser extension: no

Steps to reproduce the problem:
1. npm install pdfjs-dist
2. open `node_module/pdfjs-dist/legacy/build/pdf.js` and check the code

**Comment by Snuffleupagus** [comment]
> From https://github.com/mozilla/pdfjs-dist :

Unfortunately, because of various issues, that GitHub repository no longer updates correctly and it's consequently outdated.

If you instead look at https://www.npmjs.com/package/pdfjs-dist you'll notice slightly updated compatibility text, with a link to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support that always contains the current support data.

If you compare our list of supported browsers/environments you'll notice that all of those have native support for optional chaining, please see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#browser_compatibility

> PDF.js version:  3.6.172

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by Spike-Leung** [comment]
Thanks :)
