### ISSUE TITLE
White circle bullet points converted to 'o' characters

### ISSUE THREAD

**Issue by Fdawgs** [mozilla/pdf.js#17100]
Attach (recommended) or Link to PDF file here:

[example.pdf](https://github.com/mozilla/pdf.js/files/12845250/example.pdf)

Configuration:
- Web browser and its version: N/A
- Operating system and its version: Windows 11
- PDF.js version: v3.11.174
- Is a browser extension: N/A

Steps to reproduce the problem:
1. Run the reproduction found at https://github.com/Fdawgs/pdfjs-white-circle-bullet-points

What is the expected behavior?

White circle bullet points should be rendered using the correct U+25CB unicode character, and not converted to a different character.

What went wrong?
![image](https://github.com/mozilla/pdf.js/assets/43814140/0509bd46-8978-4737-a098-11cb7cce2060)

White circle bullet points are converted to 'o' characters. Other bullet point types are fine.

**Comment by Snuffleupagus** [comment]
I get the same copy-paste behaviour in both Adobe Reader (i.e. the PDF reference implementation) and PDFium (in Google Chrome), since this is unfortunately a bug in the PDF document *itself*.
Note that the relevant font contains neither /ToUnicode or /Differences data, which means that a PDF Viewer cannot know how copying/text-extraction should be done.
