### ISSUE TITLE
resolution problem

### ISSUE THREAD

**Issue by parksuhyun9321** [mozilla/pdf.js#17127]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Google Chrome (ver 118.0.5993.70)
- Operating system and its version: PC
- PDF.js version: 3.11.0
- Is a browser extension:

Steps to reproduce the problem:
1. The resolution drops when load pdf from the window screen
2. Need a way to adjust the font on the pdf page

What is the expected behavior? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/6433d72a-a347-4b22-830c-36df3726be6e

What went wrong? (add screenshot)
https://github.com/mozilla/pdf.js/assets/59465364/b7dccca2-74d0-411d-a779-3cc6e88569b9

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> Web browser and its version: Google Chrome (ver 118.0.5993.70)

Does it work better in Mozilla Firefox, since that's the primary development target for this library?

> Operating system and its version: PC

Sorry, but that's not an OS name/version.

> PDF.js version: 3.11.0

Unfortunately that version number doesn't actually exist; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
