### ISSUE TITLE
resolution, font issues

### ISSUE THREAD

**Issue by parksuhyun9321** [mozilla/pdf.js#17168]
Attach (recommended) or Link to PDF file here: Any PDF will work

Configuration:
- Web browser and its version: Chrome
- Operating system and its version: Windows 10, 11
- PDF.js version: v3.11.174
- Is a browser extension: No

Steps to reproduce the problem:
1. Open attached pdf file in Chrome
2. Open same pdf file in https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior? (add screenshot) Can the font come out as clear as when window.devicepixcelratio is 2 or can you apply custom font?
https://github.com/mozilla/pdf.js/assets/59465364/e570c7fe-7724-4580-8b50-0339a015333a

What went wrong? (add screenshot) Font is broken when window.devicepixelratio is 1
https://github.com/mozilla/pdf.js/assets/59465364/4c42a99b-b420-4d8d-9895-36f66c8dd047

**Comment by Snuffleupagus** [comment]
> Can the font come out as clear as when window.devicepixcelratio is 2 or can you apply custom font?
> [...]
> Font is broken when window.devicepixelratio is 1

The `devicePixelRatio`-value depends on the actual screen, or its settings, hence if you forcibly *lower* that value on a HiDPI screen it's probably not all that surprising if rendering looks "worse".

And no, you cannot change the font since the entire point of a PDF document is that it should be rendered with the embedded fonts and in general trying to substitute a font would work at all.
