### ISSUE TITLE
Uncaught Error: Module parse failed: Unexpected token (393:14) You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

### ISSUE THREAD

**Issue by rajansinghkiwi** [mozilla/pdf.js#17180]
AboutUs.916475cf2e05b3ca1f1b.js?1ae8cc00f259270aab2e:8790 Uncaught Error: Module parse failed: Unexpected token (393:14)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| function _isValidProtocol(url) {
>   switch (url?.protocol) {
|     case "http:":
|     case "https:":
    at ./node_modules/pdfjs-dist/build/pdf.js (AboutUs.916475cf2e05b3ca1f1b.js?1ae8cc00f259270aab2e:8790:7)
    at __webpack_require__ (bootstrap:19:1)
    at ./view/common/PDFViewer.js (PDFViewer.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./view/component/PdfViewer/PdfViewer.js (PdfViewer.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at ./cache/jsimport/_AboutUs.js (_AboutUs.js:1:1)
    at __webpack_require__ (bootstrap:19:1)
    at bootstrap:83:1
    at bootstrap:83:1

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since there's unfortunately no actionable information provided here.

Also, please see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

Finally, this is likely an issue with your particular build-environment which is generally difficult for us to assist with; I'd suggest that you follow the link that you've included above and see if that helps.
