### ISSUE TITLE
Usage of :root makes CSS scopes difficult to handle

### ISSUE THREAD

**Issue by cgi-0** [mozilla/pdf.js#17194]
Hi,

I'm using the generic viewer (3.11.174) to build a custom PDF viewer in a web application. 
https://www.npmjs.com/package/pdfjs-dist

I noticed that some CSS values in pdfjs are defined in the :root scope. This creates the risk of unwanted collisions, because it's not possible to wrap a CSS scope around it  - i.e. by just wrapping a class around the whole pdf_viewer.css content - without modifying the distributed source files. How could one handle it?

at usage:
1. Customize the distributed pdf-dist/web/pdf_viewer.css via build script (not great, risk of losing compatibility long term)
2. Use an iframe to separate documents (safest solution and real separation, but dependent on the custom viewer an iframe might create other difficulties).

in pdfjs:

3. Use a prefix: _--highlight-bg-color_  would be changed to _--pdfjs-highlight-bg-color_ (similar to [bootstrap ](https://getbootstrap.com/docs/5.0/customize/css-variables/) & not sure about breaking compatibility with older versions?)
4. Use a custom class on the < html > instead of :root  (see below). This way you can easily move the scope to a certain container. At the same time you can keep it as the default on the html root like now  (I don't see a problem right now, there are only a few occurrences of :root in the whole source code, but it's always possible to overlook a downside or a complex case with CSS specificity of course).

Example for 4:
 
now
```
:root {
  --highlight-bg-color: rgba(180, 0, 170, 1);
  --highlight-selected-bg-color: rgba(0, 100, 0, 1);
}
```
idea
```
.pdfjs-root {
  --highlight-bg-color: rgba(180, 0, 170, 1);
  --highlight-selected-bg-color: rgba(0, 100, 0, 1);
}
 
plus adding the class to the root html tag

<html class="pdfjs-root">...
```

I fully understand that the focus is to build a pdf viewer for Firefox. Anyhow, I was wondering about your thoughts on this subject.

**Comment by Snuffleupagus** [comment]
> Use an iframe to separate documents (safest solution and real separation, but dependent on the custom viewer an iframe might create other difficulties).

While it might not fit perfectly in every situation, please note that this is the solution that we've generally always recommend to prevent issues (not just with CSS).

> Use a prefix: _--highlight-bg-color_  would be changed to _--pdfjs-highlight-bg-color_ (similar to [bootstrap ](https://getbootstrap.com/docs/5.0/customize/css-variables/) & not sure about breaking compatibility with older versions?)

Given the primary use-case for the PDF.js library (as the Firefox PDF Viewer), I'm not a big fan of this idea since it'll increase the size of the CSS (and JavaScript) code and also add additional overhead e.g. during review to enforce such naming-conventions.

> Use a custom class on the < html > instead of :root (see below).

This has similar problems as above, and would also likely introduce additional issues for certain use-cases by forcing users to manually add CSS rules to the HTML (which *will* lead to additional support requests).

---

Possibly more use of CSS nesting could help somewhat here, however I'm sorry to say that I general there might not be a great solution for all of these cases.

**Comment by Snuffleupagus** [comment]
> You said you recommend to use an iframe also for other reasons. Is it possible to briefly name the other reasons you have in mind?

If the viewer-components are used standalone there may be issues depending on how the container-element is positioned, which could manifest itself as problems with scrolling elements into view or determining what pages are visible; refer to issue #11626.

---

Note that we've just changed both the `textLayer` and `annotationLayer` to use CSS nesting, since those cases were fairly straightforward, which *should* avoid scope-problems for those particular CSS-files.
However, in the general case such conversions aren't always all that straightforward since it's quite easy to accidentally break something in the process; hence this isn't really a high priority as far as I'm concerned.
