### ISSUE TITLE
Text loaded inside textLayer is not readable. But the one loaded inside the canva is.

### ISSUE THREAD

**Issue by hard-quale** [mozilla/pdf.js#17206]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Edge 2023 or Chrome v118
- Operating system and its version: Windows 11
- PDF.js version: 2022
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the PDF with Viewer.js/PDF.js using Edge (or Chrome).
2. Most part of the text loaded to spans inside the textLayer is rendered incorrectly. There are strange characters unreadable. But, nonetheless, the text is well draw inside the canvas.

What is the expected behavior? (add screenshot) / What went wrong? (add screenshot)
The text inside textLayer should be readable.
[enem_example.pdf](https://github.com/mozilla/pdf.js/files/13209136/enem_example.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, since the relevant fonts don't contain the necessary data[1] in order for text-selection/copying to work correctly; similar broken behaviour can be observed in other PDF Viewer as well (e.g. Adobe Reader have incomplete /ToUnicode data

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, since the relevant fonts don't contain the necessary data[1] in order for text-selection/copying to work correctly; similar broken behaviour can be observed in other PDF Viewer as well (e.g. Adobe Reader and PDFium).

---
[1] The fonts have incomplete /ToUnicode data, and the /Differences arrays (in the /Encoding dictionaries) unfortunately contain non-standard and thus unusable entries as well.
