### ISSUE TITLE
Release version `4` now?

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17225]
Given that all pending https://github.com/mozilla/pdf.js/labels/release-blocker PRs have landed, should we perhaps attempt to release version `4` now?

The new version, being a major version bump, already contains a bunch of breaking changes as-is; some notable examples include outputting of JavaScript modules and removal of the SVG back-end.

(In this case, given the amount and kind of changes since the last release we might need to be prepared to do a follow-up release if any "serious" problem is found.)

/cc @timvandermeij

**Comment by timvandermeij** [comment]
I agree; I was thinking the same yesterday. We have enough pending changes to do it now, and those changes had some time to settle now, so I think we can do it now and if need be take care of follow-ups (which will be easier now than if we stack more on top of the existing changes). I'll take care of the release later this afternoon because I'll need some time to compose the release highlights given that it's a major version release.

**Comment by timvandermeij** [comment]
Closing since the release is done now.
