### ISSUE TITLE
Print function not working properly when using large files

### ISSUE THREAD

**Issue by oscarsecopazos** [mozilla/pdf.js#17235]
Hi,

I’m facing an issue regarding PDF.js Express version 8.7 (Windows 10/Google Chrome v.119.0.6045.106)

When trying to export a document more than 30MB long, specifically those which contain a large amount of images, the **print** function located in the settings menu doesn’t work properly. Besides taking too long to process the document, it also leaves many blank pages, neither printing any annotations made in that page, nor the content of the page itself.

I was wondering whether this issue is performance-related, or if it’s due to using the free trial version of the product. I would also want to know if there is any other way to export a PDF file with all its annotations on it, because I don’t really want to print the file but just download it.

Thank you very much. Looking forward to your response.

**Comment by Snuffleupagus** [comment]
> I’m facing an issue regarding PDF.js Express version 8.7

Unfortunately that's a *different* project, which is not developed here, hence we cannot provide help/support for that here; please address further questions to that project instead.

---

*For future reference:* When opening an issue here, please remember to fill out the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) since this issue unfortunately don't contain the necessary details required to be actionable.
