### ISSUE TITLE
Newest version isn't working with @create-react-app or with @craco

### ISSUE THREAD

**Issue by triguns98** [mozilla/pdf.js#17231]
Attach (recommended) or Link to PDF file here:

After upgrading to the newest version I get this error:
![image](https://github.com/mozilla/pdf.js/assets/41086574/d24851ad-f69a-4d42-aae3-01054201af20)

Configuration:
- Web browser and its version: Chrome Latest
- Operating system and its version: Windows
- PDF.js version: 4.0.189
- Is a browser extension: No

Steps to reproduce the problem:
1. Upgrade to the latest version
2. Try to run the app using `yarn start`

What is the expected behavior? (add screenshot)
Load all the js properly and work

What went wrong? (add screenshot)
Didn't work with the default @create-react-app configuration. I've enabled top-level-await using @craco but still not working :
![image](https://github.com/mozilla/pdf.js/assets/41086574/ca53b1e6-2588-4580-bad1-2603db19097e)

**Comment by triguns98** [comment]
@craco configuration: 
![image](https://github.com/mozilla/pdf.js/assets/41086574/5c61cfd0-a6b9-4498-8011-1e75f56bfa40)

**Comment by Snuffleupagus** [comment]
> Didn't work with the default @create-react-app configuration. I've enabled top-level-await using @craco but still not working :

Unfortunately we don't use, and thus cannot provide help/support for, either of those frameworks.

Based on your error messages it seems that enabling the necessary functionality didn't actually work, however asking those projects for help will probably provide better answers than we can provide here. *For future reference:* Please always provide error message and code as *text*, since images are much more difficult to work with (e.g. you cannot copy-and-paste from them).

Please also note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.
