### ISSUE TITLE
JavaScript modules in the legacy build

### ISSUE THREAD

**Issue by benbro** [mozilla/pdf.js#17258]
Is it possible to disable JavaScript modules in the legacy build?
According to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) modules in workers are only supported in Firefox 114+ and Safari 15+ which means that we will have to stay on pdf.js v3.11.174 for the next few years.

**Comment by Snuffleupagus** [comment]
> Is it possible to disable JavaScript modules in the legacy build?

No, since that'd add way too much maintenance/support burden; something that was mentioned in https://github.com/mozilla/pdf.js/pull/17055#issue-1921049867.
(Please note that it's already *a whole lot* of work to keep the PDF.js library even running *outside* of the Firefox PDF Viewer, work that's nowadays only done by unpaid contributors such as myself and without anyone currently sponsoring that.)

> According to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Modules) modules in workers are only supported in Firefox 114+ and Safari 15+

Please refer to the FAQ for the list of supported browsers: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support
Of particular note here is that we didn't make any changes to this list in PDF.js version `4.0`, hence the browsers you mention were already required in PDF.js version `3.11.174`.

**Comment by benbro** [comment]
There is [Module Workers Polyfill](https://www.npmjs.com/package/module-workers-polyfill) ([source](https://gist.github.com/developit/220246bc99044af74a6680ce13284f59)). Is it reasonable to include it with the pdf.js legacy build? This might extend the legacy build support to Firefox 100 and Safari 13.

**Comment by benbro** [comment]
I'm also getting "top-level await" warning when trying to compile pdf.js in an angular project.
