### ISSUE TITLE
how to customize the pdj.js viewer to undo an annotations 

### ISSUE THREAD

**Issue by rajkumar-react1720** [mozilla/pdf.js#17307]
I am trying to undo an annotations
I have tried deleting the DOM on the button click but on save I can still see those ink annotations after save.

I have also tried importing the pdf-lib library and adding the path in the viewer.html import script, but I am seeing the below error on run time

Uncaught TypeError: Failed to resolve module specifier "pdf-lib". Relative references must start with either "/", "./", or "../".

Can you please help us with any solution?

**Comment by Snuffleupagus** [comment]
Unfortunately this issue contains nowhere near enough information to be actionable, and there also seem to be a couple of *different* problems mentioned above.
Please keep in mind that this is first and foremost an open-source *bug tracker*, rather than a support forum, hence all issues need to be easily actionable/reproducible.
