### ISSUE TITLE
Issue with pdfjs-dist on Mac M2 Pro chip

### ISSUE THREAD

**Issue by abdo-repos** [mozilla/pdf.js#17323]
## Description 
I'm encountering an issue while attempting to start a React project that uses react-pdf-viewer to display PDFs. This library utilizes pdfjs-dist under the hood. When running npm start, the project fails to compile and throws the following error 

## Error
```bash
ode_modules/pdfjs-dist/build/pdf.js: Missing class properties transform.
  2929 |   #isEditing = false;
  2930 |   #isInEditMode = false;
> 2931 |   _initialOptions = Object.create(null);
       |   ^
  2932 |   _uiManager = null;
  2933 |   _focusEventsAllowed = true;
  2934 |   _l10nPromise = null;
```
## Environment:

- React project using react-pdf-viewer
- Node.js version: 14.20.1
- Mac with M2 Pro chip
- Using pdfjs-dist version 4.0.189 (multiple versions attempted, same issue persists)
- Node 14 is required by the project

**Comment by Snuffleupagus** [comment]
> React project using react-pdf-viewer

Sorry, but that's a *different* project (in a framework we don't use) that we unfortunately cannot provide help/support for here.

> Node.js version: 14.20.1

Unfortunately that version is no longer supported by the PDF.js project, note that https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support mentions that at least Node.js 18 is required.
Also, you shouldn't use Node.js 14 since it no longer receives any updates (and could thus suffer from security vulnerabilities).
