### ISSUE TITLE
Signature missing using pdfjs-dist

### ISSUE THREAD

**Issue by zhangxl1025** [mozilla/pdf.js#17350]
Configuration:
- Web browser and its version: chrome 119
- Operating system and its version: macOS
- PDF.js version: 4.0.269
- Is a browser extension: no

Steps to reproduce the problem:
1. use pdfjs-dist to load base64 string 
2. console.log error,"FormatError: Bad block header in flate stream"

What went wrong? (add screenshot)
The signature is not rendering.

I'm encountering the same issue about signature missing problem, I'm glad to see that you have fixed by #17340 , may I ask when the latest version can be released for urgent use?

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since without the `Attach (recommended) or Link to PDF file here:`-part this issue unfortunately isn't actionable/valid.

> I'm encountering the same issue about signature missing problem, I'm glad to see that you have fixed by #17340 ,

Without the PDF document in question, it's impossible to tell if your issue is actually the same one.

> may I ask when the latest version can be released for urgent use?

Sorry, but that issue unfortunately isn't (anywhere near) critical enough to warrant an "emergency" release. Hence that PR will simply be included in the next release, currently planned for the end of December.
