### ISSUE TITLE
(Proposal) Move the "Text Selection Tool" & "Hand Tool" items next to "Save" item

### ISSUE THREAD

**Issue by Aleksandra0056** [mozilla/pdf.js#17366]
### Configuration:
- **Web browser and its version:** Firefox v120.0.1 (64-bit)
- **Operating system and its version:** Windows 11 Pro 22631.2715 (64-bit)
- **Is a browser extension:** No, this issue is unrelated to any extension.

### Steps to reproduce the problem:
1. Open Firefox,
2. Open PDF Reader,
3. Look at the toolbar.

### What is the expected behaviour?
- Text Selection Tool & Hand Tool items should be located in the toolbar because they are important items.
- E.g. in Paint.net or Photoshop, similar items are located in the toolbar and not somewhere in the menu, making them easily accessible. Also, this change would be useful for touch devices.

### What went wrong?
- The "Text Selection Tool" & "Hand Tool" items are not in the toolbar but in the menu instead.
- I'm attaching a screenshot. To avoid misunderstanding, the red arrows point to the mentioned items, and the small blue line is where these items should be located.

![287455065-f3c8e330-9f12-4beb-bc84-aeb77366c94b](https://github.com/mozilla/pdf.js/assets/69351811/c6d4077a-b128-49dc-8da9-d796bd336f5e)

### Other details:
- Bugzilla bug: https://bugzilla.mozilla.org/show_bug.cgi?id=1867960
- Related discussion: https://github.com/black7375/Firefox-UI-Fix/discussions/834

**Comment by Aleksandra0056** [comment]
> > Bugzilla bug: [bugzilla.mozilla.org/show_bug.cgi?id=1867960](https://bugzilla.mozilla.org/show_bug.cgi?id=1867960)
> 
> Let's duplicate this to that one then, since there's no need to file "duplicate" reports in both GitHub and Bugzilla.

Wait! I closed that as won't fix on BugZilla!

**Comment by Snuffleupagus** [comment]
Please keep in mind that these buttons have *always* been placed in the secondaryToolbar, since this isn't often used functionality; hence it's not entirely clear (at least to me) that this is a necessary change.

---

To re-evaluate the placement of these toolbar buttons, we'd need input from Firefox UX/UI developers. (I believe there's already work *planned* to maybe re-design the viewer toolbar.)

Hence, please note that Bugzilla really is the more appropriate place for this report (and the bug was still open when I made my comment).

**Comment by Aleksandra0056** [comment]
But how do I re-open it on Bugzilla?

**Comment by Aleksandra0056** [comment]
> I reopened the bug on Bugzilla.

Thank you.
