### ISSUE TITLE
Can pdf-dist do syntax downgrade processing?

### ISSUE THREAD

**Issue by Ricuzy** [mozilla/pdf.js#17384]
I use react-pdf in the project to display pdf, react-pdf uses pdfjs-dist as its dependency.
![image](https://github.com/mozilla/pdf.js/assets/36161391/c78226b3-5ace-4264-82b0-039587b8b379)

I use webpack 5.x to package my project code.

![image](https://github.com/mozilla/pdf.js/assets/36161391/4943dcb6-5266-40d5-a598-331f286825bc)

I use a browser with version 80 chromium core to access my page，It gives the error in the picture above

I checked and found that webpack did not package the node_modules code, so I needed to manually configure webpack's config to repackage react-pdf.

Can pdfjs-dist solve the problem of syntax degradation when packaging products?

**Comment by Ricuzy** [comment]
![image](https://github.com/mozilla/pdf.js/assets/36161391/abb04e3e-d319-48a3-9144-50b3590be217)

js error as shown above

**Comment by Snuffleupagus** [comment]
> I use a browser with version 80 chromium core to access my page

Such an old browser is not supported in the PDF.js project, as clearly [mentioned in the FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support), and all modern browsers implement logical OR assignment according to the [MDN compatibility data](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment#browser_compatibility).

Furthermore, you should really updated to a modern browser since your version may contain known security vulnerabilities.

---

*For future reference:* Please don't ignore the [ISSUE_TEMPLATE](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) when opening an issue.

**Comment by Ricuzy** [comment]
thanks, It really helps me a lot.
