### ISSUE TITLE
Global 'keydown' event listener for the AnnotationEditorUIManager hijacks keystrokes for <div> and <textarea>

### ISSUE THREAD

**Issue by atrinker** [mozilla/pdf.js#17389]
This is largely a duplicate/extension of issue #17167.  Although the recent pdf.js updates have corrected this issue with respect to "input" elements, the issue still exists with respect to other editable elements, such as textareas or div elements with contenteditable="true".

**Comment by calixteman** [comment]
It should work as you expect.
In the mention PR, I removed the `capture` parameter, so if you've a div, you just have to add a `keydown` listener and use `event.stopImmediatePropagation` in order to stop the bubbling of the event (see https://developer.mozilla.org/en-US/docs/Web/API/Element/keydown_event) and then the window listener will never get it.

**Comment by atrinker** [comment]
Thanks, that worked!
