### ISSUE TITLE
`CompressionStream` now behaves differently in Node.js, compared to browsers

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#17399]
Previously `CompressionStream` behaved identically in Node.js *and* browsers, but with recent Node.js updates that's changed which caused a unit-test to start failing and it's now been disabled as a result; please see https://github.com/mozilla/pdf.js/blob/988d3a188f8f536b5ad13e262d9e50bd00e942a4/test/unit/annotation_spec.js#L2210-L2215

We should try and understand *why* this happens, and how to fix it, since this could otherwise become problematical if we start using `CompressionStream` more throughout the code-base.

**Comment by timvandermeij** [comment]
This unit test now fails in Chrome too, but not in Firefox. The last working Chrome version is 119.0.6045.105 (in Puppeteer 21.7.0), but as soon as Chrome 120.0.6099.109 (in Puppeteer 21.8.0) is used the unit test assertion fails. I _think_ it fails with the same traceback as we had in Node.js, but sadly the old build logs have expired so I can't be fully certain. I can't find anything in the Chrome 120 changelog that refers to `CompressionStream` having had any changed, and to add to the confusion the unit test passes locally in Node.js for me (although I should say that I never checked if it already worked _before_ it was disabled).

For debugging, the Chrome traceback I have on Linux now is:

```
TEST-UNEXPECTED-FAIL | should compress and save text | in chrome | Expected '2 0 obj
<< /Subtype /Form /Resources << /Font << /Helv 314 0 R>>>> /BBox [0 0 32 10] /Filter /FlateDecode /Length 69>> stream
xÓ©PpòuV(Tp
QÐ÷HÍ)S0IS0T0P0!¹
F
Æzæ
!)
▒#h*d)¸(*¸ú:Þëo
endstream
endobj
' to equal '2 0 obj
<< /Subtype /Form /Resources << /Font << /Helv 314 0 R>>>> /BBox [0 0 32 10] /Filter /FlateDecode /Length 68>> stream
xÓ©PpòuV(Tp
QÐ÷HÍ)S0IS0T0«`¤`¬g`®¢ 8Â¦BHkB «¯3Þëo
endstream
endobj
'.
```

**Comment by timvandermeij** [comment]
I looked into this further and can confirm that the input bytes are 100% equal in Firefox and Chrome and the difference is indeed in the output bytes of `CompressionStream`. I have checked the source code of Firefox and Node.js and they both have a similar deflate implementation using `zlib`, and the parameters (such as the window bits) seem to be equal. This might explain why Firefox and Node.js work for me locally. Sadly I couldn't really find out how Chrome does this exactly, but it might just be that different compression parameters are used, and as far as I could find the `CompressionStream` API does not make guaranteed about if the compressed bytes remain equal or not (i.e., the compression parameters might change and that shouldn't impact the decompressed bytes, only the compressed representation).

I'm starting to think the test should be written differently. Instead of checking a hardcoded array of compressed bytes, we should perhaps just try to do a roundtrip and check if we can correctly decompress the blob again. The API guarantees equal compression and decompression, but says nothing about if the compressed bytes are/remain equal between implementations, so we should probably be testing if decompression works since that's more relevant than the exact bytes sequence.

**Comment by Snuffleupagus** [comment]
> I'm starting to think the test should be written differently. Instead of checking the compressed bytes, which could differ between implementations depending on the implementation-dependent compression parameters, we might need to do a roundtrip and check if we can correctly decompress the blob again. The important bit for us seems to be that we can correctly compress _and_ decompress the blob, and the exact bytes sequence shouldn't really be that relevant.

That makes a lot of sense, and I've now updated the PR to do exactly that (using our `FlateStream`-implementation to do the validation).
