### ISSUE TITLE
Text rendering problem

### ISSUE THREAD

**Issue by liorphp** [mozilla/pdf.js#17413]
![screenshot](https://github.com/mozilla/pdf.js/assets/39471599/0b63a164-b708-4c08-8a7f-a8b7b6fcdac1)

- Web browser and its version: any
- Operating system and its version: windows
- pdfjsLib.version:  3.3.122

In the PDF file it is displayed well, but in the JS renderer the text overlaps.

**Comment by Snuffleupagus** [comment]
When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since the `Attach (recommended) or Link to PDF file here:`-part is *always required* for issues to be valid.

> pdfjsLib.version:  3.3.122

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by liorphp** [comment]
Thanks.

V4 is mjs files, i need js files.
