### ISSUE TITLE
PDF rendered is super blurry

### ISSUE THREAD

**Issue by kvkaranverma** [mozilla/pdf.js#17417]
Attach (recommended) or Link to PDF file here: 
[super blurry PDF.pdf](https://github.com/mozilla/pdf.js/files/13644476/super.blurry.PDF.pdf)

Configuration:
- Web browser and its version: Chrome - Version 120.0.6099.71 (Official Build) (64-bit)
- Operating system and its version: Windows 11 Business 23H2
- PDF.js version: Latest
- Is a browser extension: No

Steps to reproduce the problem:
1. Rendering the attached PDF in browser using PDF.js
2. In any browser or OS.

What is the expected behavior? (add screenshot)
It should render perfectly

What went wrong? (add screenshot)
PDF is blurry and many texts are breaking when opened using PDF.js library. However, if this PDF rendered locally then it works fine.
<img width="914" alt="image" src="https://github.com/mozilla/pdf.js/assets/42038789/238847bf-e496-4288-a323-32df294f1ce4">

**Comment by Snuffleupagus** [comment]
> PDF.js version: Latest

Please note that "latest" isn't a valid version number.

> PDF is blurry and many texts are breaking when opened using PDF.js library.

Please note that your PDF document contains almost no actual text, but instead lots of *images* of text hence this won't look perfect e.g. at higher zoom levels.
It's also possible that this looks worse than in Chrome because of hardware accelerated rendering of canvases, something that we've previously seen in a number of cases (which points to bugs in the Chrome browser *itself*).

---

WFM, as good as it realistically can given that the PDF document itself is badly created, when using PDF.js version 4.0.321 [f54cfe065] in Firefox Nightly 122.0a1 on Windows 11.
(Please keep in mind that the built-in Firefox PDF Viewer is the *primary* development target for this library.)

![firefox](https://github.com/mozilla/pdf.js/assets/2692120/989008d5-b04a-4385-888f-9d2b01acfeb8)
