### ISSUE TITLE
gulp has been officially discontinued upstream

### ISSUE THREAD

**Issue by moderation** [mozilla/pdf.js#17467]
According to `brew` 

> gulp has been officially discontinued upstream [0]

The last release was May 2019 [1].  The last `gulp-cli` release was June 2020 [2].

`brew` complains when you try to remove the deprecated `openssl@1.1` package due to `gulp-cli`

```
brew remove openssl@1.1
Error: Refusing to uninstall /usr/local/Cellar/openssl@1.1/1.1.1w
because it is required by gulp-cli, which is currently installed.
You can override this and force removal with:
  brew uninstall --ignore-dependencies openssl@1.1
```

It would appear the project is unmaintained and requires insecure dependencies. It would be great to replace with some modern / maintained.

0. https://stackoverflow.com/questions/76754244/gulp-needs-to-be-updated-on-macos-ventura-how-to-run-gulp-on-macos
1. https://github.com/gulpjs/gulp/releases/tag/v4.0.2
2. https://github.com/gulpjs/gulp-cli/releases/tag/v2.3.0

**Comment by Snuffleupagus** [comment]
> gulp has been officially discontinued upstream

I cannot find any statement to that effect on either https://gulpjs.com/, https://github.com/gulpjs/gulp, or https://github.com/gulpjs/gulp-cli

(However, you're obviously correct that there's not been any new releases for quite some time now.)

---

While using old(er) dependencies could obviously become a problem at some point, as far as I know our `gulp`-scripts still work just fine. Please note that in the PDF.js project we're only using `gulp` to trigger building and testing, however it's *not at all* used in e.g. the actual releases we ship.

I don't know if there's any good, and not to mention simple, replacements for `gulp` that has similar (if not the same) features and work-flows. Besides, if/once a replacement is found, replacing all the functionality in https://github.com/mozilla/pdf.js/blob/master/gulpfile.mjs would likely be a fair amount of work. (Which might affect other, "more important", work like fixing bugs and implementing PDF features, since the number of PDF.js contributors familiar with our `gulp`-usage aren't that many.)

All-in-all, unless there's any *actual* problems with `gulp` that can only be addressed by replacing it wholesale *my opinion* is that it's probably more effort/trouble than it's worth at this point in time.

**Comment by Snuffleupagus** [comment]
> > gulp has been officially discontinued upstream
> 
> I cannot find any statement to that effect on either https://gulpjs.com/, https://github.com/gulpjs/gulp, or https://github.com/gulpjs/gulp-cli

There's also the following statement: https://github.com/orgs/gulpjs/discussions/2725#discussioncomment-5748417
