### ISSUE TITLE
Scheduling with requestAnimationFrame appears to be inefficient

### ISSUE THREAD

**Issue by AkiSakurai** [mozilla/pdf.js#17485]
<img width="354" alt="Screenshot 2024-01-07 at 9 55 31 PM" src="https://github.com/mozilla/pdf.js/assets/75532970/1b79cdb5-e1b8-48fd-904a-a0cbef300607">

<img width="1172" alt="Screenshot 2024-01-07 at 9 53 17 PM" src="https://github.com/mozilla/pdf.js/assets/75532970/490b748b-f797-42e3-8315-b723a5a28ab9">

Below is the profiling graph of PDF from #14737. The first graph shows the execution with the setting EXECUTION_TIME = 15000, while the second one represents the normal execution. It is evident that there is a threefold increase in overhead due to splitting the rendering with a 16ms budget.

I wonder is the overhead of splitting rendering with a 16ms budget worth the slight improvement in scroll responsiveness?

**Comment by Snuffleupagus** [comment]
> The first graph shows the execution with the setting EXECUTION_TIME = 15000,

Using such a large value would be really bad for number of reasons (the following list is probably incomplete):
 - It would mean that rendering no longer pauses at all, in many cases, which could easily lead to the "slow-script dialog" being displayed by the browser for more complex PDF documents since rendering is no longer done in chunks.
 - Note that *cancelling* of rendering can only happen when rendering pauses, as [mentioned in the docs](https://github.com/mozilla/pdf.js/blob/29faa38dd78d319ac99ab35aed7e659f3b070f4f/src/display/api.js#L3210-L3219), which means that it'd become impossible to cancel rendering which would affect overall performance quite badly in many cases.

(Perhaps it's possible to slightly increase the value, but anything even close to e.g. a second is probably way too long.)

> It is evident that there is a threefold increase in overhead due to splitting the rendering with a 16ms budget.

Did you actually mean 15ms here, given the values used?
https://github.com/mozilla/pdf.js/blob/29faa38dd78d319ac99ab35aed7e659f3b070f4f/src/display/canvas.js#L50-L54

**Comment by marco-c** [comment]
Should we try with higher values to see what the effects are?
