### ISSUE TITLE
Extra line breaks are missing when PDF is loaded

### ISSUE THREAD

**Issue by artstalker** [mozilla/pdf.js#17492]
Link to PDF file here:
[document (19).pdf](https://github.com/mozilla/pdf.js/files/13894933/document.19.pdf)

It is reproducible in https://mozilla.github.io/pdf.js/web/viewer.html
Configuration:
- Web browser and its version: Firefox 121.0.1 (64-bit)
- Operating system and its version: Windows 11 Pro 10.0.22631
- PDF.js version: Latest (https://mozilla.github.io/pdf.js/web/viewer.html)
- Is a browser extension: No

Steps to reproduce the problem:
1. Load PDF file
Actual result:
There is no missing blank line in the field between Several and Other
![image](https://github.com/mozilla/pdf.js/assets/2846956/3c028b2b-c8b4-4131-86c8-48b31a9c8f2b)

Expected result:
If you open PDF in any other PDF viewer (Foxit desktop for example), you will see that empty line is there
![image](https://github.com/mozilla/pdf.js/assets/2846956/ce4a0c3c-131b-4319-8ff5-f0ffaa6d3a7a)

It is always reproducible with any file and any field.
You can add extra line breaks right in pdf.js, save the file, and it will be gone on the file load.

**Comment by Snuffleupagus** [comment]
The problem is with the Appearance-data of the Annotation, since the *empty* showText-command (i.e. the `0 -17.11 Td () Tj` line below) is being ignored when extracting textContent.
While that behaviour seems reasonable by default, perhaps the `keepWhiteSpace`-mode can/should behave differently and thus invoke `appendEOL` if the text-movement was large enough to "look like" a new-line in e.g. [this branch](https://github.com/mozilla/pdf.js/blob/56ca2fd65858bf0045734fae11c295e290728463/src/core/evaluator.js#L2805-L2820)?
```
21 (dict) [id: 144, gen: 0]
    Type = /Annot
    Rect (array)
    Ff = 4198400
    V = "Several\n\nOther\nJobs"
    T = "otherJobExperience"
    BS (dict)
    P (dict) [id: 1, gen: 0]
    DA = "/Helvetica 12 Tf 0 g"
    F = 4
    MK (dict)
    Subtype = /Widget
    FT = /Tx
    AP (dict)
        N (stream) [id: 154, gen: 0]
            Subtype = /Form
            Resources (dict)
            BBox (array)
            Length = 180
            <view contents> 
            /Tx BMC q 1 w 0 G 0 0 151.015 87.53 re S BT /Helvetica 12 Tf 0 g 1 0 0 1 0 87.53 Tm 2 -13.67 Td (Several) Tj
            0 -17.11 Td () Tj
            0 -17.11 Td (Other) Tj
            0 -17.11 Td (Jobs) Tj ET Q EMC

    M = "D:20240110195645"
```

**Comment by artstalker** [comment]
Hi,

Do you have plans for when this fix will be delivered in the release?
