### ISSUE TITLE
Update pdfjs-dist with newer version

### ISSUE THREAD

**Issue by PabbleDabble** [mozilla/pdf.js#17524]
Apologies if this is not the correct way to ask about this.

This repo - https://github.com/mozilla/pdfjs-dist/tags - appears to be the linked distributable for PDFjs.  It's currently on v3.4.120 which is ~10 releases behind PDFjs from what I can see.  Is there a way to trigger a build of the dist repo?  Is it still being maintained.  We've got a couple items that look like they're solved in some recent releases, but we're using the distributable.  

Thanks in advance.

**Comment by Snuffleupagus** [comment]
This is unfortunately a known issue, which is effectively blocked on #11851 being fixed (since we don't really know how/why it broke in the first place).

If possible, use the NPM package instead since that one is still being updated; see https://www.npmjs.com/package/pdfjs-dist

> Is there a way to trigger a build of the dist repo?

Locally you can run `gulp dist` against a clone of the PDF.js repository to generate the `pdfjs-dist` files.

> Apologies if this is not the correct way to ask about this.

Perhaps using the "Discussion" feature, rather than an issue, might have been slightly more appropriate in this case.

**Comment by PabbleDabble** [comment]
For anyone else seeing this in the future....
This...
https://www.npmjs.com/package/pdfjs-dist
...and this...
https://github.com/mozilla/pdfjs-dist
...do appear to be out of sync based on the message above...

> This is unfortunately a known issue, which is effectively blocked on https://github.com/mozilla/pdf.js/issues/11851 being fixed (since we don't really know how/why it broke in the first place).

https://www.npmjs.com/package/pdfjs-dist does show the most current packages, as well as running this command in your console.  This command is just a nice confirmation that your npm is pointing to the most current version from the registry. 
```
$ npm info pdfjs-dist
```
