### ISSUE TITLE
TypeError: Right-hand side of 'instanceof' is not an object suddenly appears

### ISSUE THREAD

**Issue by justflores** [mozilla/pdf.js#17545]
Attach (recommended)
[Chart test pdf.pdf](https://github.com/mozilla/pdf.js/files/13997499/Chart.test.pdf.pdf)

Configuration:
- Web browser and its version: Chrome Version 120.0.6099.225 (Official Build) (64-bit)
- Operating system and its version: Win10 Pro
- PDF.js version: 4.0.379
- Is a browser extension: No

Steps to reproduce the problem:
1. Drag attached file into app's document editor with drop event

What is the expected behavior? (add screenshot)
![image](https://github.com/mozilla/pdf.js/assets/51919327/e328d34f-0704-4c8a-95ca-2334753c4936)

What went wrong? (add screenshot)
All of the sudden an exception keeps on happening. It works fine before. I'm passing a valid typed Array
![image](https://github.com/mozilla/pdf.js/assets/51919327/3ae4cadf-6e68-4af4-acd6-947f468a15ec)
![image](https://github.com/mozilla/pdf.js/assets/51919327/bd7e6800-0c5f-412a-b29e-a23ace0bedf9)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Steps to reproduce the problem:
>     1. Drag attached file into app's document editor with drop event

Based on the screen-shot this is clearly some kind of *custom implementation*, that we know nothing about and consequently cannot provide any help/support for.
Please note https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md (emphasis mine):
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, **please prepare a short well-documented example that demonstrates the problem and make it accessible online** on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us in the Matrix room -- **keep in mind that just code snippets won't help us troubleshoot the problem**.

---

> All of the sudden an exception keeps on happening. It works fine before. I'm passing a valid typed Array

Based on the screen-shot, your environment apparently doesn't support `URL` correctly which points to a bug in *your* application. Please note that all modern browsers/environments support this, according to https://developer.mozilla.org/en-US/docs/Web/API/URL#browser_compatibility

*For future reference:* Please include code and error messages as *text*, rather than images.
