### ISSUE TITLE
Missing electronic signature by v3.10.111

### ISSUE THREAD

**Issue by ljn-gh** [mozilla/pdf.js#17583]
The console error is as follows:

> Warning: Unimplemented widget field type "Sig", falling back to base field type.
> Warning: getOperatorList - ignoring errors during  "GetOperatorList: page 3" task: "FormatError: Bad block header in flate stream".

Not all pdf has this problem,i think this electronic signature is special.

**Comment by Snuffleupagus** [comment]
That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

When opening an issue, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md since as-is this unfortunately contains no actionable details.

**Comment by ljn-gh** [comment]
My file is private,may I have other way to provide the pdf
