### ISSUE TITLE
Download does not work on current mobile Safari or Firefox

### ISSUE THREAD

**Issue by thosch6** [mozilla/pdf.js#17626]
Using the demo viewer at
https://github.com/mozilla/pdf.js#online-demo
of pdf.js 4.0.379 (both modern and older browsers tested)
downloading the demo PDF does not work on current iOS 17.3 or iPadOS 17.3 with Safari or Firefox.
Current versions of Safari or Firefox will not download the demo PDF, but switch the URL to 
blob:https://mozilla.github.io/7f25c26d-125d-42c9-bb7d-25b35726f23b 
and the pdf.js interface is not shown anymore.

Only when using Chrome, downloading the PDF works fine.

**Comment by Snuffleupagus** [comment]
> Using the demo viewer at
> https://github.com/mozilla/pdf.js#online-demo
> of pdf.js 4.0.379 (both modern and older browsers tested)

This is slightly confusing, since as of this writing the demo viewer uses PDF.js version 4.1.131 [7d9cc4901].

Also, note that as outlined in the FAQ the `modern` build doesn't even support Safari: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> downloading the demo PDF does not work on current iOS 17.3 or iPadOS 17.3 with Safari or Firefox.

That unfortunately sounds like *platform bug*, rather than a PDF.js one, and note that there's been no (relevant) recent changes to the `DownloadManager` code.
Furthermore, it works for me when using e.g. Firefox Nightly 124.0a1 and Chrome Beta 122.0.6261.18 on Windows 11.

Please keep in mind that the *built-in* Firefox PDF Viewer is the primary development target for this library.

**Comment by thosch6** [comment]
I was taking the version number from this page:
https://mozilla.github.io/pdf.js/getting_started/#download
where the last current pdf.js version is marked as 4.0.379.
But I did use the viewer on https://github.com/mozilla/pdf.js#online-demo and neither Safari or Firefox worked on iOS.
Where can I downlaod version 4.1.131 ?

**Comment by Snuffleupagus** [comment]
> But I did use the viewer on https://github.com/mozilla/pdf.js#online-demo and neither Safari or Firefox worked on iOS.

As already mentioned, this most unfortunately suggests a bug *in iOS* rather than here since otherwise you'd expect it to be broken in all operating systems.

> Where can I downlaod version 4.1.131 ?

That's the current *development version*, hence it's not yet available for download.

**Comment by thosch6** [comment]
I don't think you can blame it on the operating system as mobile Chrome does downloading perfectly.
