### ISSUE TITLE
Printing does not work on current iOS 17.3 or iPadOS 17.3

### ISSUE THREAD

**Issue by thosch6** [mozilla/pdf.js#17625]
Using the demo viewer at
https://github.com/mozilla/pdf.js#online-demo 
of pdf.js 4.0.379 (both modern and older browsers tested) 
printing does not work on current iOS 17.3 or iPadOS 17.3.
Current versions of Chrome, Safari or Firefox will only print the first page, but not the remaining 13 pages of the demo PDF.

**Comment by Snuffleupagus** [comment]
> printing does not work on current iOS 17.3 or iPadOS 17.3.

This unfortunately sounds like a *platform bug*, since there's been no recent changes to the printing code. Also, printing is notoriously difficult to implement well across browsers since the web-platform does not provide fine-grained control over it.

Furthermore, please note that Safari *in general* is much more difficult to support compared to other browsers which is why it's *not* listed as fully supported: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> Current versions of Chrome, Safari or Firefox will only print the first page, but not the remaining 13 pages of the demo PDF.

It works for me in both Firefox Nightly 124.0a1 and Chrome Beta 122.0.6261.18 when testing on Windows 11, which unfortunately points to a platform bug.
Note that historically there's also been a number of printing issues reported for Safari and/or iOS, however given that development is focused on the *built-in* Firefox PDF Viewer that's generally difficult for us to address here unfortunately.
