### ISSUE TITLE
How can we fix the problem where, on mobile devices like iPhones and Android phones, clicking 'Print' for PDF files doesn't show the correct document? In Safari, it only shows the first page, and in Chrome on Android, it shows nothing at all.

### ISSUE THREAD

**Issue by abdulkadarsabir** [mozilla/pdf.js#17644]
Configuration:
- android and iOS phones browser.

Steps to reproduce the problem:
1. Open any PDF file in android and iOS browser, and click print option.
2. After click you can see on print dialog box PDF file loads blank pages or just first page of PDF

What is the expected behavior? 
Load all pages of pdf in print dialog box as it works on laptop browser's.

What went wrong? 
![blankpdfimage](https://github.com/mozilla/pdf.js/assets/64594491/1f5ead08-fe45-4be5-94fb-2f565e2245f3)

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that the title should contain *a good summary* of the problem rather than multiple sentences.
Secondly, please remember to fill out the ISSUE_TEMPLATE *completely* since most of the request information is unfortunately missing (making this issue non-actionable).

---

If this is only broken in *some* browsers/platforms, that unfortunately suggests a bug in those environments rather than here.
