### ISSUE TITLE
Pdf rendering is incomplete in mobile phone systems below ios14.

### ISSUE THREAD

**Issue by jscovers** [mozilla/pdf.js#17716]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:Mobile terminal
- Operating system and its version:IOS13.6 
- PDF.js version:2.3.200
- Is a browser extension:No

Steps to reproduce the problem:
1. The IOS13.6,pdf preview is abnormal in the mobile operating system.
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is *always required* in order for any issue to be actionable/valid.

> Web browser and its version:Mobile terminal
> Operating system and its version:IOS13.6

Please see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> PDF.js version:2.3.200

That version is no longer supported, since it's *over three four old*, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
