### ISSUE TITLE
Where is the latest version used in the example page?

### ISSUE THREAD

**Issue by rgelb** [mozilla/pdf.js#17758]
The example page ([https://mozilla.github.io/pdf.js/web/viewer.html](https://mozilla.github.io/pdf.js/web/viewer.html)) appears to be using version 4.1.243, while the releases page shows version 4.0.379. 

It appears that 4.1.243 resolves a Chrome Print Preview crasher bug for some printer drivers, but I don't know where I can download it.  
Can you point me in the right direction please?

**Comment by Snuffleupagus** [comment]
> The example page (https://mozilla.github.io/pdf.js/web/viewer.html)

Please note that that's a *development version*, and consequently it's not a good idea (nor officially supported) to use that one in production environments since doing so may cause problems (either now or later).
Hence we don't distribute that, and you'd need to build it yourself; see https://github.com/mozilla/pdf.js?tab=readme-ov-file#getting-the-code and https://github.com/mozilla/pdf.js?tab=readme-ov-file#building-pdfjs
