### ISSUE TITLE
Can we only request data for a certain page

### ISSUE THREAD

**Issue by projectcss** [mozilla/pdf.js#17762]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version: 2.3.200
- Is a browser extension:

Steps to reproduce the problem:
Why is it that when using range request, if a PDF file has 100 pages, if I directly use pdfDocument. getPage (50), it will request all the data from the first 49 pages

<img width="531" alt="image" src="https://github.com/mozilla/pdf.js/assets/64296418/3f80c378-2196-409f-86dc-d2ea0b7d1a93">

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:

This part of the ISSUE_TEMPLATE is always required, since the issue isn't really actionable/valid without it.

> PDF.js version: 2.3.200

That version is no longer supported, since it's *over four years old*; please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> Steps to reproduce the problem: Why is it that when using range request, if a PDF file has 100 pages, if I directly use pdfDocument. getPage (50), it will request all the data from the first 49 pages

That'd only happen if the PDF document is "badly" generated, with all pages placed at a single level of the /Pages tree.
