### ISSUE TITLE
Not all file attachments are shown on initial opening, but appear later

### ISSUE THREAD

**Issue by petervwyatt** [mozilla/pdf.js#17821]
The PDF test file: https://safedocs.pdfa.org/FragmentTest.pdf has 2 embedded files:
1. "cat.pdf" is listed in the **EmbeddedFiles** name tree, and 
2. "TestDoc.docx" which is referenced by the File Attachment annotation (paperclip icon) on page 3 (and is not in the **EmbeddedFiles** name tree as it doesn't need to be).

Issue is that the file attachment navpane only shows "cat.pdf" when the PDF is first opened and displayed - the 2nd file is not listed at all. Screenshots below are from FireFox 124.0 (64 bit).

When this PDF is first opened, only "cat.pdf" is visible in the file attachment navpane:
![image](https://github.com/mozilla/pdf.js/assets/26521615/fc7cad29-3652-473c-bb11-d87c33b219f9)

Once you scroll a bit further, "TestDoc.docx" then appears all of a sudden:
![image](https://github.com/mozilla/pdf.js/assets/26521615/1048966e-943a-4c84-8ab2-de7d3d24c30d)

**Comment by Snuffleupagus** [comment]
This is (unfortunately) by design, since the entire implementation of the library/viewer is such that we don't have to load/parse all pages in order to e.g. start rendering in the viewer.
Hence any FileAttachment-annotations will be appended to the `attachmentsView` as those pages are rendered in the viewer, since anything else would force us to parse all annotations (for every page) upfront during document loading.
