### ISSUE TITLE
(Chrome)PDF can not be displayed correctly with chrome browser

### ISSUE THREAD

**Issue by UnicornLee** [mozilla/pdf.js#17841]
Attach (recommended) or Link to PDF file here:
[original.pdf](https://github.com/mozilla/pdf.js/files/14751745/original.pdf)

Configuration:
- Web browser and its version: Google Chrome / 123.0.6312.59 (Official Build) (64-bit)
- Operating system and its version: Windows 11 / 23H2
- PDF.js version: latest
- Is a browser extension: yes and I try it using dist code and original code(master branch)

Steps to reproduce the problem:
1. use the attachment oringal.pdf
2. open it with google chrome with pdfjs extension, or put it in pdfjs-dist folder and open viewer.html with chrome browser, or clone pdf.js oringal code, put it in` test/pdfs`, start sever, visit `http://localhost:8888/test/pdfs/?frame` and click the pdf.

What is the expected behavior? (add screenshot)
<img width="1131" alt="display_on_firefox_browser" src="https://github.com/mozilla/pdf.js/assets/25165425/ca93693c-80cc-462a-842a-17e83a9e0ab3">

What went wrong? (add screenshot)
<img width="1025" alt="display_on_chrome_broswer" src="https://github.com/mozilla/pdf.js/assets/25165425/40205508-708c-47ba-8c8a-b5d89f7fc63f">

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
None

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js version `4.1.315` [067c49dc4] in Firefox Nightly 126.0a1 on Windows 11.

This looks like a `canvas`-related bug in the Google Chrome browser *itself*, rather than a PDF.js related bug, since otherwise you'd expect it to be consistently broken everywhere.
Please report this to the Google Chrome developers instead, since it unfortunately doesn't seem actionable here.

**Comment by UnicornLee** [comment]
I see. Thanks @Snuffleupagus
