### ISSUE TITLE
Italic font not applied

### ISSUE THREAD

**Issue by siddhesh8k** [mozilla/pdf.js#17926]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. For this file italic font is not detected. 
[142_edited.pdf](https://github.com/mozilla/pdf.js/files/14946962/142_edited.pdf)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
I cannot reproduce the issue with the most recent version of PDF.js by opening the file with https://mozilla.github.io/pdf.js/web/viewer.html: the text is in italic, equal to other PDF viewers. Moreover, note that the information as requested in the issue template is required for the issue to be valid, so as it stands the issue is incomplete and we can't do more unless _all_ requested information is provided and the bug can be reproduced in the most recent, vanilla version of PDF.js.
