### ISSUE TITLE
Document Generated with Aspose.PDF for Java 24.2 is not viewable in PDF.js: 2.5.192, where as document generated in Aspose.PDF for Java 20.1 is working fine

### ISSUE THREAD

**Issue by akarshashok-agi** [mozilla/pdf.js#18155]
PDF 32322d44432d34462d46302d38412d43 [1.6 Aspose.PDF for Java 20.1 / Aspose Ltd.] (PDF.js: 2.5.192) - this is working 

PDF 46302d30372d43312d43462d39372d41 [1.6 Aspose.PDF for Java 24.2 / Aspose Pty Ltd.] (PDF.js: 2.5.192)

**Comment by timvandermeij** [comment]
PDF.js 2.5.192 is not an official release, see https://www.npmjs.com/package/pdfjs-dist?activeTab=versions, and is almost four years old and therefore _long_ out of support. Please upgrade to the most recent version. Moreover, it is required to provide _all_ details as requested in the issue template, in particular the PDF file itself, otherwise we cannot help and the issue has to be closed as invalid.
