### ISSUE TITLE
vue2 project install pdfjs after appear some errors

### ISSUE THREAD

**Issue by coderStars** [mozilla/pdf.js#18186]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: 50+
- Operating system and its version: macos(13.6.6)
- PDF.js version: 4.2.67
- Is a browser extension:

in my terminal appear probloms(webpack4 build):
<img width="555" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/ce7d9fc0-ba42-4077-a57d-cd3a5e08283f">

<img width="642" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/4a5eb56f-c5a3-44bf-9067-6ee5dd713079">

Steps to reproduce the problem:
1. npm i pdfjs-dist@4.2.67 --save
2. in PdfRender components write some codes: 
 
<img width="556" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/d7af9b85-b768-4548-9b86-fc21316e8b6c">
<img width="503" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/98f111d3-03f3-4540-9705-06363d3f8848">

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
 **You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file**

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by nicolo-ribaudo** [comment]
This is not a pdfjs problem.

You are using an old webpack version that does not support private fields. Webpack 5 has been released 4 years ago, you should upgrade to it. If not possible, you can configure Babel in webpack through babel-loader to transpile your code to ES6 so that webpack 4 can understand it (try googling how to do it in Vue, I have no idea).

**Comment by coderStars** [comment]
> This is not a pdfjs problem.
> 
> You are using an old webpack version that does not support private fields. Webpack 5 has been released 4 years ago, you should upgrade to it. If not possible, you can configure Babel in webpack through babel-loader to transpile your code to ES6 so that webpack 4 can understand it (try googling how to do it in Vue, I have no idea).

ok, thank you, i will try a try

**Comment by coderStars** [comment]
> This is not a pdfjs problem.
> 
> You are using an old webpack version that does not support private fields. Webpack 5 has been released 4 years ago, you should upgrade to it. If not possible, you can configure Babel in webpack through babel-loader to transpile your code to ES6 so that webpack 4 can understand it (try googling how to do it in Vue, I have no idea).

I set es6 to low version settings, but terminal report other errors。
<img width="719" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/466a8496-e471-48ee-b191-77db7dac8733">

<img width="890" alt="image" src="https://github.com/mozilla/pdf.js/assets/39763302/5a64b3ea-1f86-45e7-b6ed-69c25ace0b34">

await can use in there？

**Comment by timvandermeij** [comment]
PDF.js requires async/await support to be present. In version 4.3.136 top-level await usage got removed, so I would recommend to update to that version since it might solve this issue. Other than that, this issue is missing important information, primarily a short runnable example that reproduces the issue, so we can't help further unless _all_ details from the issue template are provided. We also can't provide support for third-party frameworks like Vue, so for that please consult Vue references/support forums.

**Comment by coderStars** [comment]
> PDF.js requires async/await support to be present. In version 4.3.136 top-level await usage got removed, so I would recommend to update to that version since it might solve this issue. Other than that, this issue is missing important information, primarily a short runnable example that reproduces the issue, so we can't help further unless _all_ details from the issue template are provided. We also can't provide support for third-party frameworks like Vue, so for that please consult Vue references/support forums.

thank you, i try to update 4.3.136
