### ISSUE TITLE
Unsupported gulp version

### ISSUE THREAD

**Issue by DerIngo** [mozilla/pdf.js#18232]
I followed the "Getting the Code" on https://github.com/mozilla/pdf.js
When I tried to start the server with ``gulp server``, I got an error message: ``Unsupported gulp version``.
I could fix it when I changed in ``package.json`` from ``"gulp": "^5.0.0"`` to ``"gulp": "4.0.0"``

PS: In the Learning-Section you have an introduction video, which might be a little outdated (12 years old).

**Comment by DerIngo** [comment]
Maybe the issue is a few lines earlier, when the guide tells me ``npm install -g gulp-cli@^2.3.0``. Maybe this should be ``npm install -g gulp-cli@^3.0.0``?

**Comment by timvandermeij** [comment]
`gulp server` only works if Gulp 5 is installed globally, which should no longer be done because global dependencies are harder to manage. It's better to use `npx gulp server` instead which ensures that the local dependency version is used. If you have Gulp installed globally, you should uninstall it first.

Note the following sentence in the "Getting the Code" section:

> If you prefer to not install gulp-cli globally, you have to prefix all the gulp commands with npx (for example, npx gulp server instead of gulp server).

**Comment by timvandermeij** [comment]
Looking at this again, we should indeed amend the README after https://github.com/mozilla/pdf.js/commit/98ef8a1be3592042798ae55afffe4c0c39bd8247. Thank you for reporting this.

**Comment by timvandermeij** [comment]
Fixed by #18247.
