### ISSUE TITLE
Implement publishing a release to the `pdfjs-dist` GitHub repository

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#18357]
In #18350 the release publishing logic got ported from the bots to GitHub Actions, but the long-broken GitHub repository push logic to the [pdfjs-dist repository](https://github.com/mozilla/pdfjs-dist) was left out. This issue tracks reimplementing pushing to the `pdfjs-dist` Git repository as part of the new [publish_release.yml](https://github.com/mozilla/pdf.js/blob/master/.github/workflows/publish_release.yml) workflow.

**Comment by timvandermeij** [comment]
Before doing this I would like to gauge if there is actually a use case left for this. The last push to https://github.com/mozilla/pdfjs-dist was from January 1st, 2023 and while we had some questions about this I'm not sure if just pushing to NPM alone isn't enough? After all, most packages just push artifacts to NPM without also having a separate Git repository, so I'd like to collect the use cases for such a repository first.

**Comment by Snuffleupagus** [comment]
> Before doing this I would like to gauge if there is actually interest for this.

I'd support deprecating the `pdfjs-dist` repository, simply because it'd reduce the number of things that we have to support.[1]

---
[1] If we go down this route then I'd probably suggest that we update, according to my comments, and land https://github.com/mozilla/pdfjs-dist/pull/22 and afterwards we can mark the repository as "archived".

**Comment by Snuffleupagus** [comment]
I've just updated and squash-merged https://github.com/mozilla/pdfjs-dist/pull/22, since that seems like the right thing to do in the short term.

---

> Most other NPM packages also just push artifacts to NPM without also having a separate Git repository, so I'd like to collect the use cases for such a repository first.

From my perspective, I do think that we should add a few "restrictions" here:
 - It should be *technically impossible* to achieve the desired outcome without the Git repository, rather than only "I prefer to not use NPM".
 - There should be a number of different users and use-cases affected, since maintaining this for e.g. a single user doesn't seem feasible.

**Comment by Snuffleupagus** [comment]
I think that we should just move forward with "archiving" the `pdfjs-dist` repository (and perhaps also clean-up the gulpfile).

**Comment by Snuffleupagus** [comment]
Additionally, I *believe* from looking at old issues that one reason for creating the `pdfjs-dist` repository was to support Bower.
However, note that we stopped supporting Bower almost two years ago, see PR #15390, since already by that point it'd been deprecated for a number of years.

**Comment by timvandermeij** [comment]
@calixteman Could you archive the https://github.com/mozilla/pdfjs-dist repository? There should be a red "Archive this repository" button at the bottom of https://github.com/mozilla/pdfjs-dist/settings.

**Comment by calixteman** [comment]
> @calixteman Could you archive the https://github.com/mozilla/pdfjs-dist repository? There should be a red "Archive this repository" button at the bottom of https://github.com/mozilla/pdfjs-dist/settings.

Done
