### ISSUE TITLE
[Bug]: i use "pdfjs-dist": "^4.4.168", "@types/pdfjs-dist": "^2.10.378", and run in docker and get error 26.99 node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.js (1982:23) Use of eval in "node_modules/react-pdf/node_modules/pdfjs-dist/build/pdf.js" is strongly discouraged as it poses security risks and may cause issues with minification.

### ISSUE THREAD

**Issue by Miri121** [mozilla/pdf.js#18373]
### Attach (recommended) or Link to PDF file

aa

### Web browser and its version

0

### Operating system and its version

0

### PDF.js version

0

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

aa

### What is the expected behavior?

aa

### What went wrong?

aa

### Link to a viewer

0

### Additional context

aa

**Comment by timvandermeij** [comment]
Closing since none of the required information in the issue template is provided, which is required for an issue to be valid. Moreover, the error mentions `react-pdf` and `@types/pdfjs-dist` which are both not projects we maintain, and the latter is even deprecated according to https://www.npmjs.com/package/@types/pdfjs-dist.
