### ISSUE TITLE
`viewer.html` at v4.4.168 is UTF-8 BOM

### ISSUE THREAD

**Issue by tamuratak** [mozilla/pdf.js#18370]
1. unzip pdfjs-4.4.168-dist.zip 
2. hexdump -C web/viewer.html | head

```
$  hexdump -C web/viewer.html | head
00000000  ef bb bf 3c 21 44 4f 43  54 59 50 45 20 68 74 6d  |...<!DOCTYPE htm|
00000010  6c 3e 0a 3c 21 2d 2d 0a  43 6f 70 79 72 69 67 68  |l>.<!--.Copyrigh|
00000020  74 20 32 30 31 32 20 4d  6f 7a 69 6c 6c 61 20 46  |t 2012 Mozilla F|
00000030  6f 75 6e 64 61 74 69 6f  6e 0a 0a 4c 69 63 65 6e  |oundation..Licen|
00000040  73 65 64 20 75 6e 64 65  72 20 74 68 65 20 41 70  |sed under the Ap|
00000050  61 63 68 65 20 4c 69 63  65 6e 73 65 2c 20 56 65  |ache License, Ve|
00000060  72 73 69 6f 6e 20 32 2e  30 20 28 74 68 65 20 22  |rsion 2.0 (the "|
00000070  4c 69 63 65 6e 73 65 22  29 3b 0a 79 6f 75 20 6d  |License");.you m|
00000080  61 79 20 6e 6f 74 20 75  73 65 20 74 68 69 73 20  |ay not use this |
00000090  66 69 6c 65 20 65 78 63  65 70 74 20 69 6e 20 63  |file except in c|
```

You can see BOM at the first three bytes.  I think it is not intended.

- https://en.wikipedia.org/wiki/Byte_order_mark

**Comment by timvandermeij** [comment]
The UTF-8 BOM has been included in the viewer in 2013 already, please see https://github.com/mozilla/pdf.js/commit/dca5edea21ff6a70ef6eaa7275227035567cfbda. It's most likely due to the new version of Gulp that it now gets copied verbatim to the distribution bundle and not stripped anymore; I do recall it's quite a pain to have all various tools play nicely together with the UTF-8 BOM present because there are different defaults w.r.t. stripping it or not...

However, we discussed this in #16694 and found that originally the UTF-8 BOM was included deliberately, and even though we believe it shouldn't be necessary anymore nowadays it also shouldn't be an issue since all browsers and tools should be able to deal with it? I think we remove it, and don't have a strong opinion either way, but I'd first like to understand if there is an actual issue with it now.

**Comment by Snuffleupagus** [comment]
The BOM was originally added from https://bugzilla.mozilla.org/show_bug.cgi?id=852909#c19, via https://github.com/mozilla/pdf.js/pull/3957#issuecomment-29103832, so Henri Sivonen might be the best one to ask if the BOM is still needed today.

**Comment by Snuffleupagus** [comment]
Or we just leave it as-is since that shouldn't break anything, but removing it potentially could, given that the BOM was added on purpose and this seems a very minor issue to spend time on?
