### ISSUE TITLE
[Bug]: Invalid rendering because of no colorspace

### ISSUE THREAD

**Issue by calixteman** [mozilla/pdf.js#18466]
### Attach (recommended) or Link to PDF file

[image2.pdf](https://github.com/user-attachments/files/16319966/image2.pdf)

### Web browser and its version

Firefox nightly

### Operating system and its version

Windows 11

### PDF.js version

last one

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

Open the pdf

### What is the expected behavior?

![image](https://github.com/user-attachments/assets/3d390c60-05e2-415a-b949-a7293a2a0a9f)

### What went wrong?

![image](https://github.com/user-attachments/assets/18abad5c-adfb-44c2-a881-07a6fa6ff9de)

### Additional context

The bug has been reported:
https://issues.apache.org/jira/browse/PDFBOX-5851

As mentioned in the bug report, `scn` and `SCN` are used without a previous call to `cs` so we fallback on `DeviceGray`:
https://github.com/mozilla/pdf.js/blob/ed83d7c5e16798a56c493d56aaa8200dd280bb17/src/core/evaluator.js#L4876-L4877

We should probably have a `null` rgb color or something like that to indicate to use a fully transparent one.

The rendering is correct in either Acrobat or Chrome.

**Comment by Snuffleupagus** [comment]
> As mentioned in the bug report, `scn` and `SCN` are used without a previous call to `cs` so we fallback on `DeviceGray`:

Yes, because as far as I understand that's what the PDF specification says should be the default value in https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G7.3881830

| Parameter | Type | Value |
| ----------- | ----- | ------ |
| color space | name or array | The current colour space in which colour values shall be <br> interpreted (see 8.6, "Colour Spaces"). There are two <br> separate colour space parameters: one for stroking and one <br> for all other painting operations. Initial value: **DeviceGray**. | 

> We should probably have a `null` rgb color or something like that to indicate to use a fully transparent one.

We might need to *somehow* limit that to the /Pattern handling, since given the above I'd worry about regressions elsewhere if we do that unconditionally (especially since the PDF document in question is corrupt).
