### ISSUE TITLE
[Bug]: Space inserted between each letter in textLayer 

### ISSUE THREAD

**Issue by rodolfoorl** [mozilla/pdf.js#18494]
### Attach (recommended) or Link to PDF file

[04b10dd4-1e2e-4b7a-8b40-f9ab73e3a723.pdf](https://github.com/user-attachments/files/16367950/04b10dd4-1e2e-4b7a-8b40-f9ab73e3a723.pdf)

### Web browser and its version

Chromium: 126.0.6478.186

### Operating system and its version

Windows 11 Home Versão 23H2

### PDF.js version

4.4.168

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the PDF `04b10dd4-1e2e-4b7a-8b40-f9ab73e3a723.pdf` in the viewer
2. Try searching for the term `sementes` or any other term present in the document
3. It says the phrase is not found, but it's there in PDF/OCR

![image](https://github.com/user-attachments/assets/e852fd19-668f-496c-988e-2cfc54d5b6ce)

### What is the expected behavior?

Match the searched phrase and the text contained in PDF/OCR

### What went wrong?

Apparently a value of NULL (\x00) is being placed between each character, consequently hindering the text search
![image](https://github.com/user-attachments/assets/7add4a2f-1627-467d-8526-8be4caf3ad25)

### Link to a viewer

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
> Try searching for the term `sementes` or any other term present in the document

This is unfortunately a bug in the PDF document *itself*, since it actually specifies the text like that.
Furthermore, both Adobe Reader (i.e. the PDF reference implementation) and PDFium (the Google Chrome PDF Viewer) are similarly "broken" and also cannot find that string.

Closing as WONTFIX, since it's clearly the document that's broken and several implementations agree here.
