### ISSUE TITLE
[Bug]: Fast Web View says No even if PDF is linearized

### ISSUE THREAD

**Issue by catmanjan** [mozilla/pdf.js#18520]
### Attach (recommended) or Link to PDF file

https://d2tkmshiozsr4v.cloudfront.net/documents/files/000/041/350/original/ad41798557504b40d26e11b4f059c0945bb5ca14/750614main_NASA_FY_2014_Budget_Estimates-508.pdf

### Web browser and its version

Google Chrome

### Operating system and its version

Windows 11

### PDF.js version

master

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load supplied PDF with PDF.js
2. Click Document Properties...
3. Notice Fast Web View says No
![image](https://github.com/user-attachments/assets/9fd21fcd-b0e0-46ee-bba7-2b72d3df4852)

### What is the expected behavior?

Should say Yes

### What went wrong?

![image](https://github.com/user-attachments/assets/e188cb5d-3137-4f27-9fa3-975ad4af1dca)

**Comment by Snuffleupagus** [comment]
> Notice Fast Web View says No

And so does Adobe Reader as well, i.e. the PDF reference implementation, since the /Linearized dictionary in the PDF document is unfortunately corrupt. More precisely, its /L-entry doesn't equal the length of the file; note https://opensource.adobe.com/dc-acrobat-sdk-docs/pdfstandards/PDF32000_2008.pdf#G19.1043548

![adobe](https://github.com/user-attachments/assets/3a6ff443-6366-4d91-b399-b35b8af7085a)

**Comment by catmanjan** [comment]
@Snuffleupagus do you have an example of a working linearized PDF? I tried several

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/blob/master/test/pdfs/pdf.pdf.link is a correctly linearized PDF document.
