### ISSUE TITLE
[Bug]: PDF not loading using Chrome on iOS

### ISSUE THREAD

**Issue by roldeguz** [mozilla/pdf.js#18602]
### Attach (recommended) or Link to PDF file

When using an iOS device with version 17.3 (and under) and Chrome, the PDF viewer is blank and the file is not being displayed.
![image](https://github.com/user-attachments/assets/d6403226-b58e-43e1-b1b8-e39b57f727b8)

### Web browser and its version

Goggle chrome 92.0.45

### Operating system and its version

iOS v17.3

### PDF.js version

4.2.67 (Modern browsers, Stable)

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. In iOS devices with v17.4 and below, open Chrome
2. Go to the pdfjs online demo
3. Click the link for modern browsers: https://mozilla.github.io/pdf.js/web/viewer.html
![image](https://github.com/user-attachments/assets/042bfc47-e7be-4dd9-b2d3-b1b3556ecad2)
4. But if you click the link for older browsers, its working
![image](https://github.com/user-attachments/assets/0dd4664a-b95b-4f41-8b06-0887ea7956b5)

### What is the expected behavior?

The pdf file should be loaded in the viewer. This is using iOS 17.5 + Chrome.
![image](https://github.com/user-attachments/assets/cea0e157-b867-4e1d-a595-d4070fb4a6c2)

### What went wrong?

The pdf viewer is empty and the file is not being loaded.
![image](https://github.com/user-attachments/assets/10abf6e6-f178-4f53-98b3-203b2005c343)

**Comment by Snuffleupagus** [comment]
> ### Web browser and its version
> 
> Goggle chrome 92.0.45

That's not a supported browser, as outlined in the FAQ (which the issue template asks you to please check  reporting a bug):
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support

> ### PDF.js version
> 
> 4.2.67 (Modern browsers, Stable)

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

> 4\. But if you click the link for older browsers, its working

Well, then you'll need to use the `legacy` version since it's intended for older browser (as outlined in the FAQ).

**Comment by roldeguz** [comment]
@Snuffleupagus thank you for your reply.
