### ISSUE TITLE
Use Workers as When rendering a large pdf file it is taking a quite a lot of time

### ISSUE THREAD

**Issue by kotasudhakar** [mozilla/pdf.js#18647]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

I think using multiple workers(worker threads in node or webworkers in browser) to render canvases using offscreen canvas (https://web.dev/articles/offscreen-canvas#use_with_popular_libraries) (https://web.dev/articles/offscreen-canvas) actually increases the speed exponentially as rendering/drawing these canvas actually taking a lot time

**Comment by Snuffleupagus** [comment]
Using multiple web-workers isn't free, since there's overhead when starting them and also overhead when sending data to/from workers; hence there might not be much of a performance improvement overall. Furthermore, using multiple web-workers would significantly increase the complexity of the code and might also introduce various edge-case problems.

Given the overall lack of context, or any actual data that suggests a clear improvement, let's close this as WONTFIX; please also see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#idea

**Comment by kotasudhakar** [comment]
Can I actually make a demo and demonstrate the performance improvements, if that's okay?

**Comment by Snuffleupagus** [comment]
> Can I actually make a demo and demonstrate the performance improvements,

Please note that https://github.com/mozilla/pdf.js/issues/18647#issuecomment-2308434696 mentions a number of potential issues, hence a standalone demo probably isn't very helpful. (*And once again:* please refrain from needlessly tagging users, since that creates notification spam.)

Also, since this is just a word for word copy of https://github.com/k-yle/pdf-to-img/issues/238 it seems that maybe your issue is actually with Node.js since it doesn't support web-workers. (We won't add support for the Node.js "Worker threads" concept in the PDF.js library.)
