### ISSUE TITLE
[Bug]: Can not search what I copy text from original pdf file

### ISSUE THREAD

**Issue by fengjac** [mozilla/pdf.js#18693]
### Attach (recommended) or Link to PDF file

[HP Photosmart 420 Series Printer User Manual.pdf](https://github.com/user-attachments/files/16883325/HP.Photosmart.420.Series.Printer.User.Manual.pdf)

### Web browser and its version

Chrome is up to date Version 116.0.5845.97 (Official Build) (64-bit)

### Operating system and its version

Windows 11 professional

### PDF.js version

v4.6.82-legacy

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. go to page 60；
2. select line 6&7 and then「Ctrl+c」to copy；
3. 「Ctrl+f」and then「Ctrl+v」to paste and then「Enter」to search;

It cannot high light what you have copied to search.

### What is the expected behavior?

It can search and high light successfully.

### What went wrong?

![image](https://github.com/user-attachments/assets/74c61d1d-f7e0-4a9f-8c07-e999df794030)

**Comment by n00nietzsche** [comment]
You can search using the text below

"Pursuant to Part 15.21 of the FCC Rules, any changes or modifications to this equipment not expressly approved by HewlettPackard Company may cause harmful interference, and void your authority to operate this equipment. Use of a shielded data"

It seems the problem might be the dashes (-) attached when line breaks occur. I hope this helps in solving the problem.

**Comment by fengjac** [comment]
> You can search using the text below
> 
> "Pursuant to Part 15.21 of the FCC Rules, any changes or modifications to this equipment not expressly approved by HewlettPackard Company may cause harmful interference, and void your authority to operate this equipment. Use of a shielded data"
> 
> It seems the problem might be the dashes (-) attached when line breaks occur. I hope this helps in solving the problem.

Thanks for your suggestion. I use your text and it can search. It is very interesting.

But is it possible to fix it so that it can search in this case?

**Comment by nicolo-ribaudo** [comment]
Chrome's PDF viewer behaves similarly to PDF.js when searching: they both cannot find that `Hewlett-\nPackard` when searching for `Hewlett-Packard`, and the both find it when searching for `HewlettPackard`.

On selection PDF.js has a better behavior (since it copies it with the dash), but this means that the selected text does not match the search rules.

**Comment by calixteman** [comment]
It's because we're considering that it's a word break which isn't the case here because the char on the next line is upper case.
I suppose that in English (or in French) it's obvious that it's a compound word. Are there some languages where some words have a capital letter inside ? If yes are they using the hyphen to break words ?
That said we can fix that and see if people complain...
