### ISSUE TITLE
[Feature]: Pixel snapping / `devicePixelContentBox`

### ISSUE THREAD

**Issue by page200** [mozilla/pdf.js#18700]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

To avoid pixel aliasing/blur due to _pixel snapping_ as described at https://web.dev/articles/device-pixel-content-box#pixel_snapping, you might want to use `devicePixelContentBox` as described at https://web.dev/articles/device-pixel-content-box#devicepixelcontentbox

I haven't checked which projects that use PDF.js have fractional pixel values, but that might happen.

(Also please check whether [`devicePixelRatio` is being used](https://github.com/search?q=repo%3Amozilla%2Fpdf.js%20devicePixel&type=code) correctly as described at https://web.dev/articles/device-pixel-content-box#pixel_perfection so that `devicePixelRatio` and `devicePixelContentBox` work together correctly.)

**Comment by Snuffleupagus** [comment]
We're already, since many years, using `devicePixelRatio` as can be seen here:
 - https://github.com/mozilla/pdf.js/blob/77c7ec6927c0263a0ed2be2b0aae46b655855239/web/ui_utils.js#L79-L103
 - https://github.com/mozilla/pdf.js/blob/77c7ec6927c0263a0ed2be2b0aae46b655855239/web/pdf_page_view.js#L1012-L1046

However, using `devicePixelContentBox` would apparently require introducing `ResizeObserver` as part of rendering and that's *not* really planned as far as I'm aware (since that might introduce various other issues/complications).

**Comment by page200** [comment]
[This demo](https://device-pixel-content-box.glitch.me/) linked from the aforementioned article implements a check for whether `ResizeObserver` is supported. Old browsers that don't support it can skip that adjustment.

Or do you mean other potential issues/complications?
