### ISSUE TITLE
[Feature]: Read pages non-sequentially when using HTTP Range Requests (and release from memory)

### ISSUE THREAD

**Issue by solis-eduardo** [mozilla/pdf.js#18720]
### Is the feature relevant to the Firefox PDF Viewer?

No

### Feature description

Currently, using HTTP Range Requests helps to quickly load and visualize the first pages of large PDF files, but it still requires loading all pages sequentially to render the last page, wouldn't it be possible to load pages non-sequentially (i.e. load from the last page backwards when loading page from history) and release page data from memory when loading new pages through Range Requests?
This would reduce loading times when the user wants to read the last page and avoid crashing low-memory machines.

![image](https://github.com/user-attachments/assets/62f90ae9-3097-4a42-aa69-b15af1aac1a4)
This is the view from my system monitor after opening a 1.5 GB PDF on the last page (loaded from viewer history).
Even tho the pages are rendered only when visible, the page data seems to be held indefinitely.

### Other PDF viewers

Evince seems to non-sequentially load only visible pages, appearing faster and using less memory.

**Comment by Snuffleupagus** [comment]
> Currently, using HTTP Range Requests helps to quickly load and visualize the first pages of large PDF files, but it still requires loading all pages sequentially to render the last page,

That would be caused by the structure of your PDF document then, since in many cases we unfortunately have to load many (or even all) pages in order for necessary data validation to be possible.

> Even tho the pages are rendered only when visible, the page data seems to be held indefinitely.

In the default viewer, pages that are scrolled (sufficiently) out of view will have their resources released. Additionally, global resources will also be released (on both the main- and worker-threads) after a period of inactivity in the viewer.
(However, if/when the memory is being released is up to the browser and operating system and thus isn't something a JavaScript application can control.)

---

Given that this issue is unfortunately quite "light" on the details, we probably cannot really help much here.

**Comment by solis-eduardo** [comment]
> That would be caused by the structure of your PDF document then, since in many cases we unfortunately have to load many (or even all) pages in order for necessary data validation to be possible.
I tried linearizing the document with [QPDF](https://qpdf.readthedocs.io/en/stable/cli.html#option-linearize) but saw no change in behavior or improvement in performance, maybe something else is broken whithin the document, but thanks for the input.
> In the default viewer, pages that are scrolled (sufficiently) out of view will have their resources released. Additionally, global resources will also be released (on both the main- and worker-threads) after a period of inactivity in the viewer.
Maybe I'm using an older or misconfigured version, got the demo to work locally and it worked as desired.
