### ISSUE TITLE
[Bug]: Will not display pdf until all chunks are loaded when using range requests

### ISSUE THREAD

**Issue by SamWiIIiams** [mozilla/pdf.js#18745]
### Attach (recommended) or Link to PDF file

Any large, linearized pdf

### Web browser and its version

Chrome 128.0.6613.138

### Operating system and its version

Windows 10

### PDF.js version

4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the live demo (https://mozilla.github.io/pdf.js/web/viewer.html)
2. Use the console to load a (large ~1000+ page) pdf from a location that serves range requests 
```
PDFViewerApplication.open({
  url: "http://localhost:3000/getPdf" , 
  disableAutoFetch: true,
  disableStream: true,
})
```

### What is the expected behavior?

Able to view the first few pages before the rest of the document has finished loading from the server. 

(additionally, should only see a few chunks loaded as `disableStream` and `disableAutoFetch` are set to `true`)

### What went wrong?

Nothing is shown in the viewer until the entire pdf has streamed in. If you watch the network tab, you can see that it waits until every single chunk is finished downloading until it displays anything. Additionally I wouldn't expect it to even load all chunks since the aforementioned options were set to true.

### Additional context

This works in version 2.5.207. If I change my local implementation to the current version, I see the same behavior as I see in the live demo. Simply downgrading to 2.5.207 will get this to work.

**Comment by SamWiIIiams** [comment]
I am serving my document from a nodejs server. Here is the endpoint for reference:
```
app.get("/getPdf", (req, res) => {
  const filePath = path.join(__dirname, "./static/P180010.pdf");
  const stat = fs.statSync(filePath);
  const fileSize = stat.size;

  const range = req.headers.range;
  if (range) {
    const [start, end] = range
      .replace(/bytes=/, "")
      .split("-")
      .map(Number);

    const endRange = Math.min(end || fileSize - 1, fileSize - 1);
    const chunkSize = endRange - start + 1;

    res.writeHead(206, {
      "Content-Type": "application/pdf",
      "Accept-Ranges": "bytes",
      "Content-Range": `bytes ${start}-${endRange}/${fileSize}`,
      "Content-Length": chunkSize,
    });
    try {
      const fileStream = fs.createReadStream(filePath, {
        start,
        end: endRange,
      });
      fileStream.pipe(res);
    } catch (err) {
      console.error(err);
    }
  } else {
    res.writeHead(200, {
      "Content-Type": "application/pdf",
      "Accept-Ranges": "bytes",
      "Content-Length": fileSize,
    });
    try {
      fs.createReadStream(filePath).pipe(res);
    } catch (err) {
      console.error(err);
    }
  }
});
```

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> Any large, linearized pdf

Sorry, but as mentioned in the issue template the actual PDF document is *required* in order for any issue to be actionable/valid.

Note that nowadays we have more validation, in order to deal with various corrupt PDFs, and it's thus possible that we might need to load the entire document in some cases.

I've just tested the following locally, in both Firefox Nightly 132.0a1 respectively Google Chrome 129.0.6668.42 running on Windows 11, and it works just fine with only *a limited* number of range request needed to render the first page:
http://localhost:8888/web/viewer.html?file=/test/pdfs/pdf.pdf#disableStream=true&disableAutoFetch=true

**Comment by SamWiIIiams** [comment]
Thank you for the timely response. My apologies - I'm unfortunately unable to share the pdfs that I'm working with but thank you for the additional context. I'll take a closer look at the pdf structure.

One other thing I noticed in implementations that did load the first page with a limited number of requests, if I jumped to a far off page, it will load everything between the two in order. With a perfectly working implementation, should I expect it to only send a few range requests to load the requested page or is what I described the intended behavior?

**Comment by Snuffleupagus** [comment]
> Thank you for the timely response. My apologies - I'm unfortunately unable to share the pdfs that I'm working with but thank you for the additional context. I'll take a closer look at the pdf structure.

In that case, let's close this for now since it's unfortunately not actionable currently. As mentioned in https://github.com/mozilla/pdf.js/issues/18745#issuecomment-2350196507 there are working examples, so this cannot be completely broken in general (and we'd need a test-case to actually look into this further).

> [...] if I jumped to a far off page, it will load everything between the two in order. With a perfectly working implementation, should I expect it to only send a few range requests to load the requested page or is what I described the intended behavior?

Again, it really depends on the internal structure of the PDF document. In general we cannot jump straight to another page, but will need to walk *part of* the /Pages-tree to reach it, which may require *some* intermediate data-fetching.

**Comment by Snuffleupagus** [comment]
One thing that you might want to confirm is that your server is actually *sending* appropriate data, e.g. by placing break-points in the PDF.js code, since we validate the response to ensure that range requests can be used; please see
 - https://github.com/mozilla/pdf.js/blob/c72fb9b7332d5db523736b76d0297cfb97c14385/src/display/fetch_stream.js#L132-L138
 - https://github.com/mozilla/pdf.js/blob/c72fb9b7332d5db523736b76d0297cfb97c14385/src/display/network_utils.js#L39-L83
