### ISSUE TITLE
[Bug]: Burp's security failed in pdfjs v2.6.423 and v3.5.553 in angular14

### ISSUE THREAD

**Issue by ritz535** [mozilla/pdf.js#18744]
### Attach (recommended) or Link to PDF file

Not able to resolve the Burp's security issue with pdfjs v2.6.423 and v4.6.82 in angular 14.
![image (12)](https://github.com/user-attachments/assets/1249c64f-a1fb-40c2-843c-5fb89fd2fd48)

### Web browser and its version

chrome

### Operating system and its version

Linux and window

### PDF.js version

2.6.423 and 3.5.553

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

no

### What is the expected behavior?

WE need to pass security with mentioned versions v2.6.423 and v3.5.553 in angular14.
![image (12)](https://github.com/user-attachments/assets/298e3191-80b2-4809-9fdd-a7b8edadb57d)

### What went wrong?

![image (12)](https://github.com/user-attachments/assets/b1738ee2-a76f-4ba3-ba26-72c983f39dbc)

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file
> 
> Not able to resolve the Burp's security issue with pdfjs v2.6.423 and v4.6.82 in angular 14.

First of all, that information isn't relevant under a heading called `Attach (recommended) or Link to PDF file`.
Secondly, please note that logs and error messages should always be provided *as text* rather than images.

Furthermore, we have no idea what "Burp" is here and we simply cannot provide support for the myriad of frameworks that exist (i.e. Angular in this case).

> ### PDF.js version
> 
> 2.6.423 and 3.5.553

Neither of those versions are supported now, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
