### ISSUE TITLE
[Bug]: Print and UI glitched on iOS 17.7

### ISSUE THREAD

**Issue by LittleLightLittleFire** [mozilla/pdf.js#18807]
### Attach (recommended) or Link to PDF file

Use the demo page: https://mozilla.github.io/pdf.js/web/viewer.html

### Web browser and its version

iOS Safari 17.7

### Operating system and its version

iOS 17.7

### PDF.js version

v4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Load any pdf
2. Print

### What is the expected behavior?

1. Document to print to the correct size

### What went wrong?

![IMG_3C137E021D69-1](https://github.com/user-attachments/assets/661dd8fe-4193-4270-805e-ce82a9b84f6d)
![IMG_09324562F67E-1](https://github.com/user-attachments/assets/9047f4e8-bd0f-4d4d-80ee-cf63fd7db818)
![IMG_F4563001BBAF-1](https://github.com/user-attachments/assets/5d6d4ad1-259b-480e-bf83-ce9214d7ef93)

### Link to a viewer

https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
This unfortunately sounds like a *browser/platform* bug, since otherwise you'd expect it to be similarly broken everywhere, hence you'll probably need to report this to the browser developers instead.

Please keep in mind that Safari is only listed as *mostly* supported in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support and that historically we've seen a lot of printing-bugs that only affects iOS.
