### ISSUE TITLE
[Bug]: Print button not working when PDF is rendered using <embed>, <object> or <iframe>

### ISSUE THREAD

**Issue by trott13** [mozilla/pdf.js#18810]
### Attach (recommended) or Link to PDF file

Any PDF

### Web browser and its version

Firefox 130

### Operating system and its version

MacOS 14.6.1

### PDF.js version

PDF.js: 4.5.255 [0e063ffdd]

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

use <embed src="path to some PDF" >

### What is the expected behavior?

The print panel opens when clicked

### What went wrong?

It does'nt open. Instead the console shows:
Uncaught NS_ERROR_FAILURE: 
    triggerPrinting resource://pdf.js/web/viewer.mjs:12540
    dispatch resource://pdf.js/web/viewer.mjs:1339
    dispatch resource://pdf.js/web/viewer.mjs:1396
    bindListeners resource://pdf.js/web/viewer.mjs:11192
    #bindListeners resource://pdf.js/web/viewer.mjs:11190
    Toolbar resource://pdf.js/web/viewer.mjs:11131
    _initializeViewerComponents resource://pdf.js/web/viewer.mjs:11732
    initialize resource://pdf.js/web/viewer.mjs:11521
    run resource://pdf.js/web/viewer.mjs:11793
    webViewerLoad resource://pdf.js/web/viewer.mjs:13638
    <anonymous> resource://pdf.js/web/viewer.mjs:13642

**Comment by calixteman** [comment]
Are you able to reproduce the issue in using the the viewer from: https://mozilla.github.io/pdf.js/web/viewer.html ?
If not, it's a Firefox issue. I don't manage to reproduce it neither with nightly nor with release (130) in using https://jkorpela.fi/HTML/iframe-pdf.html.
That said, if it's a Firefox issue, you should try to run Firefox with a new profile (see about:profiles). It'd be nice to file a bug in [Bugzilla](https://bugzilla.mozilla.org/enter_bug.cgi?product=Firefox&component=PDF%20Viewer) with a test case (especially because it wfm with the iframe link).
