### ISSUE TITLE
[Bug]: Pictures are not rendered correctly

### ISSUE THREAD

**Issue by eceeeren** [mozilla/pdf.js#18875]
### Attach (recommended) or Link to PDF file

Original page: 
![image](https://github.com/user-attachments/assets/c8accaf6-a1ab-4390-9939-e5a44f906310)

Rendered version:
![image](https://github.com/user-attachments/assets/93316828-3a6e-4b3d-a7bd-8f22704a8c32)

PDF file:
[12 - Error Handling.pdf](https://github.com/user-attachments/files/17309097/12.-.Error.Handling.pdf)

### Web browser and its version

Chrome Version 129.0.6668.90 

### Operating system and its version

macOS 14.6.1 (23G93)

### PDF.js version

4.6.82

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Render the PDF file using PDF.js
2. Optionally render It page by page

### What is the expected behavior?

The same page as the original picture should be shown

### What went wrong?

The picture under Debugging Title is not shown

**Comment by Snuffleupagus** [comment]
WFM, using PDF.js 4.7.78 [81cf42df4] in Firefox Nightly 133.0a1 on Windows 11.

![firefox](https://github.com/user-attachments/assets/324d8e0a-61b5-497f-8641-3f71940e0557)

> ### Attach (recommended) or Link to PDF file

*For future reference:* Please don't place screen-shots under this heading, since they belong under the `What is the expected behavior?` respectively `What went wrong?` headings further down in the template.

> ### PDF.js version
> 
> 4.6.82

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by calixteman** [comment]
I just tried with Chrome 129.0.6668.101 on Mac (Sequoia 15.0) with:
https://mozilla.github.io/pdf.js/web/viewer.html
and it wfm.
I tried in Chrome and Firefox on Windows 11 and Mac and it wfm.
And in looking at the image dictionary, there is nothing special.
