### ISSUE TITLE
[Bug]: PDF not loading on Safari 15.4 - Blank screen

### ISSUE THREAD

**Issue by barath46** [mozilla/pdf.js#18877]
### Attach (recommended) or Link to PDF file

<img width="1440" alt="Screenshot 2024-10-10 at 12 42 04 PM" src="https://github.com/user-attachments/assets/bd7099d0-d454-4595-afb7-1a737f5f4877">

I am experiencing an issue where the PDF viewer does not load on Safari version 15.4. The screen remains blank when attempting to open the PDF.js viewer on the following links:

[Standard Viewer](https://mozilla.github.io/pdf.js/web/viewer.html)
[Legacy Viewer](https://mozilla.github.io/pdf.js/legacy/web/viewer.html)
This issue occurs consistently in Safari 15.4, but the viewer works fine on other browsers like Chrome and Firefox.

### Web browser and its version

Safari 15.4

### Operating system and its version

macOS Monterey version 12.3.1

### PDF.js version

v4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open Safari (version 15.4).
2. Navigate to one of the following links:
3. https://mozilla.github.io/pdf.js/web/viewer.html or https://mozilla.github.io/pdf.js/legacy/web/viewer.html
4. Observe that the screen is blank, and the PDF does not load.

### What is the expected behavior?

The PDF should render and display as it does on other browsers.

### What went wrong?

The screen is blank, and the PDF is not visible.

**Comment by Snuffleupagus** [comment]
> ### Attach (recommended) or Link to PDF file

*For future reference:* Please don't place unrelated information under this heading, since you're *only* supposed to place the PDF document there and any other context belongs under appropriate headings below in the issue template.

> ### Web browser and its version
> 
> Safari 15.4

That's not a supported browser, as mentioned in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support which the issue template links to and explicitly asks you to check *before* filing an issue.

**Comment by barath46** [comment]
@Snuffleupagus Thanks
