### ISSUE TITLE
[Bug]: Page snapping/scrolling issue when activating annotation editor in a pdf with annotations on multiple pages.

### ISSUE THREAD

**Issue by atrinker** [mozilla/pdf.js#18911]
### Attach (recommended) or Link to PDF file

[b79facae-9204-424f-879a-dda7724d6c20.pdf](https://github.com/user-attachments/files/17401384/b79facae-9204-424f-879a-dda7724d6c20.pdf)

### Web browser and its version

Mozilla Firefox

### Operating system and its version

Windows 10

### PDF.js version

4.7.76

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached pdf in the demo browser.
2. Activate the annotation editor through the pdf.js toolbar.
3. Begin to scroll to page 2.

### What is the expected behavior?

Scrolling should continue naturally.

### What went wrong?

Instead, as soon as page 2 becomes visible, a cascading effect begins where the viewer rapidly snaps through all of your pages that contain annotations.  In the attached pdf, a minor scroll will take you from page 2 to page 5.

### Additional context

This issue only occurs when you have not previously scrolled to the other pages.

**Comment by simon-ging** [comment]
Same here. To reproduce: 1) Open a PDF with highlight and text annotations. 2) Press the text annotation tool. 3) Scroll down. Result: The pages jump like crazy. This also happens while editing occassionally but it is hard to pin down when it happens. Otherwise the PDF annotation directly in the browser is really nice, but this disturbs the workflow quite a lot.
