### ISSUE TITLE
[Bug]: page.getTextContent() return the wrong character

### ISSUE THREAD

**Issue by luckymore** [mozilla/pdf.js#19036]
### Attach (recommended) or Link to PDF file

https://arxiv.org/pdf/2006.07733

### Web browser and its version

chrome 130.0.6723.70

### Operating system and its version

macOS 14.1 (23B2073)

### PDF.js version

4.0.379

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. open P34
2. search `[projection]`, then copy it, you will get this: `[projection]`
![image](https://github.com/user-attachments/assets/e6f8c33d-e139-45cd-a445-48787f7f96b0)

### What is the expected behavior?

It should include single quotes `['projection']`

### What went wrong?

![image](https://github.com/user-attachments/assets/1c22a98e-506a-44ae-9446-4cc087c052ea)

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF document *itself*, since it doesn't contain a "correct" /ToUnicode entry for that glyph and consequently this simply cannot work.
Note that this is similarly broken in other PDF viewers as well, with both Adobe Reader (i.e. the PDF reference implementation) and PDFium (the Google Chrome PDF viewer) being unable to copy that glyph.

> ### PDF.js version
> 
> 4.0.379

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download

**Comment by luckymore** [comment]
@Snuffleupagus Do you mean that even within pdf.js there is no way to know the true unicode of the rendered content?
