### ISSUE TITLE
[Bug]: On screens with a higher DPR (E.g. 2.0), PDF is abnormally large (zoomed in)

### ISSUE THREAD

**Issue by kyletimmermans** [mozilla/pdf.js#19053]
### Attach (recommended) or Link to PDF file

Any PDF but I tested mainly with [compressed.tracemonkey-pldi-09.pdf](https://github.com/user-attachments/files/17786754/compressed.tracemonkey-pldi-09.pdf)

### Web browser and its version

Chrome 130.0.6723.117 (Official Build) (x86_64) | Firefox 132.0.2 (64-bit)

### Operating system and its version

macOS Version 11.6.1

### PDF.js version

v4.8.69

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Setup [singlepageviewer.html](https://github.com/mozilla/pdf.js/blob/v4.8.69/examples/components/singlepageviewer.html) and[singlepageviewer.mjs](https://github.com/mozilla/pdf.js/blob/v4.8.69/examples/components/singlepageviewer.mjs) using PDF.js v4.8.69
2. Use any PDF (I've tested with [compressed.tracemonkey-pldi-09.pdf](https://raw.githubusercontent.com/mozilla/pdf.js/v4.8.69/web/compressed.tracemonkey-pldi-09.pdf))
3. Visit the page from a screen with a DPR of 2.0

### What is the expected behavior?

Here is a screenshot of v4.6.82 singlepageviewer.html / singlepageviewer.mjs which does not have an issue with handling a DPR of 2.0

<img width="1439" alt="PDF js v4 6 82 - Single Page Viewer Example" src="https://github.com/user-attachments/assets/7c685582-cbf1-468c-aee6-8f0da7359bdc">

### What went wrong?

In version v4.8.69, when the PDF is loaded, the PDF is zoomed into its top right-hand corner and is abnormally large

<img width="1440" alt="PDF js v4 8 69 - Single Page Viewer Example" src="https://github.com/user-attachments/assets/9e2ff343-7b22-4e47-8d7a-6d3ce425c67c">

### Link to a viewer

https://www.kyles.world/resume

### Additional context

After testing, I noticed that this behavior was introduced in [v4.7.76](https://github.com/mozilla/pdf.js/releases/tag/v4.7.76). In versions prior to v4.7.76, I was unable to recreate this issue.

I also noticed that the a portion of styling (width & height) is not being applied to the canvas element after v4.7.76.  This is just a hunch, I don't know if this is the actual cause of the issue. See below:

v4.6.82 - We can see that there is an inline style here for the proper width and height for the canvas element
<img width="891" alt="PDF js v4 6 82 - Inspect Element" src="https://github.com/user-attachments/assets/0ff00eba-2773-4f09-b8be-edeb49667bad">

v4.8.69 - The extra styling is no longer there inline, or at all
<img width="751" alt="PDF js v4 8 69 - Inspect Element" src="https://github.com/user-attachments/assets/1e8936b6-f75c-4c08-97e8-7cfa6769636f">

When I manually apply the styling to the v4.8.69 canvas (width: 1400px, height: 1811px), the PDF looks normal again.

The following is my viewport information that I did my testing on:
<img width="673" alt="Viewport" src="https://github.com/user-attachments/assets/584e9526-3e13-4375-a242-72c178f2d7b8">

**Comment by Snuffleupagus** [comment]
It works when testing http://localhost:8888/examples/components/singlepageviewer.html locally against the PDF.js repository (after having run `npm gulp dist-install`).

The problem seems to be CSS related, since your implementation points to https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf_viewer.min.css
 - Please note that we do *not* distribute a minified version of the file, compare with https://www.npmjs.com/package/pdfjs-dist?activeTab=code, hence that file is created by *someone* else.
 - Looking at the contents of that CSS file there seems to be lots of missing spaces, which appear to break things pretty badly in many of the rules.
 - If I manually edit your example, using the browser devtools, to instead point to https://cdnjs.cloudflare.com/ajax/libs/pdf.js/4.8.69/pdf_viewer.css everything works as it should.

**Comment by kyletimmermans** [comment]
Understood, thank you for your help!
