### ISSUE TITLE
[Bug]: use pdf.js after pdf document show some black chunk

### ISSUE THREAD

**Issue by coderStars** [mozilla/pdf.js#19140]
### Attach (recommended) or Link to PDF file

![image](https://github.com/user-attachments/assets/3a82eb79-7303-487f-a342-f6b83b832aca)

### Web browser and its version

131.0.6778.70

### Operating system and its version

macos 14.1.2

### PDF.js version

3.9.179

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. install pdfjs(3.9.179)
2. use pdfjs
3. open browser
4. find pdf have some black chunk in colourful space

### What is the expected behavior?

have not black chunk

### What went wrong?

find pdf have some black chunk in colourful space

**Comment by Snuffleupagus** [comment]
Closing as INCOMPLETE, since there's unfortunately no actionable information provided.
Please take more care when filling out the issue template (see below).

---

> ### Attach (recommended) or Link to PDF file

The PDF file *must* be placed under this heading, as the issue template clearly mentions; as-is this is simply not actionable.
Also, a screen-shot is *not* appropriate there and should be placed further down in the template.

> ### Web browser and its version
> 
> 131.0.6778.70

That's only a version number, but says nothing about what browser you actually used.

> ### PDF.js version
> 
> 3.9.179

That version is no longer supported, please find the latest releases at https://mozilla.github.io/pdf.js/getting_started/#download
