### ISSUE TITLE
[Feature]: The click pop ups on both sides of the viewer cannot be closed outside the pop-up window on mobile devices

### ISSUE THREAD

**Issue by zbr826858040** [mozilla/pdf.js#19153]
### Is the feature relevant to the Firefox PDF Viewer?

Yes

### Feature description

I am currently working on a mobile website project that uses a PDF viewer. However, during actual development and testing, I found that users cannot click on positions outside the pop-up window to close the function windows on the left and right sides. For example, when clicking on the 'sidebarToggleButton' button, the 'sidebarContainer' window pops up. After sliding and clicking on the page they want to view, they habitually want to click on the screen outside the pop-up window to close it, but there is no response after clicking. You need to click the sidebar toggle button again to close it.
So, I hope the PDF viewer can support the operation of closing the pop-up window by clicking on the area outside the pop-up window.

**Comment by Snuffleupagus** [comment]
First of all, please note that the default viewer is developed for desktop applications (more specifically Firefox) and note also that Firefox for Android uses its own (simpler) UI.
Secondly, the *sidebar* is as its name suggests not a "popup" since it actually moves the document vertically when opened. Hence it seems completely wrong to treat it like a "popup", and the *sidebar* also supports being resized which would be much more difficult to do without accidentally closing it if what you're suggesting is implemented.

Since the current implementation is on purpose, and also inline with how sidebars usually work, closing as WONTFIX.
