### ISSUE TITLE
[Bug]: Pming liu Extension B characters in form fields does not render in pdf.js viewer

### ISSUE THREAD

**Issue by mirnalinikarthik** [mozilla/pdf.js#19182]
### Attach (recommended) or Link to PDF file

[ExtnB character not working.pdf](https://github.com/user-attachments/files/18037940/ExtnB.character.not.working.pdf)

### Web browser and its version

Firefox 133.0, chrome 131.0.6778.109 

### Operating system and its version

Windows 11

### PDF.js version

pdf.js 4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached document in pdf.js viewer. 
2. Extension B character present in the Form field is displayed as ? . 

### What is the expected behavior?

<img width="570" alt="edgeworking" src="https://github.com/user-attachments/assets/b3784437-38f4-4d28-b4d2-ff32cce47acd">

### What went wrong?

<img width="742" alt="firefox not working" src="https://github.com/user-attachments/assets/0e77c570-1ae3-425d-8fab-0a6a9e1fb8e1">

**Comment by Snuffleupagus** [comment]
(Note that there's no actual form fields involved here.)

This is a bug in the PDF document *itself*, since it uses a non-standard font without embedding it.

**Comment by calixteman** [comment]
I think the bug is valid.
It was a bit surprising to have this `d855` which corresponds to a high surrogate code and when the font is not embedded we just try to use the unicode we've to let the fallback font doing the magic.
So here it looks like we're just getting the first part of a utf32 char but with an utf16 encoding.
And I found that:
https://github.com/mozilla/pdf.js/blob/60eba287d46158ad1a6f274754cb8883cbcbdb44/src/core/to_unicode_map.js#L31

and replacing the `charCodeAt` by a `codePointAt` is fixing the issue, but I'm really not sure that's the correct way to do.

@Snuffleupagus wdyt ?

**Comment by Snuffleupagus** [comment]
> And I found that:
> 
> https://github.com/mozilla/pdf.js/blob/60eba287d46158ad1a6f274754cb8883cbcbdb44/src/core/to_unicode_map.js#L31
>
> and replacing the `charCodeAt` by a `codePointAt` is fixing the issue, but I'm really not sure that's the correct way to do.

First of all, does that change pass *all* tests locally?

Secondly, that code is just over ten years old (see PR #5150) and even before that it seems that `charCodeAt` was being used so it's quite difficult for me to say if changing this breaks any assumptions elsewhere in the code-base.
