### ISSUE TITLE
 [Bug]: Not able to view Signatures in PDF in the image layer

### ISSUE THREAD

**Issue by Veenam546** [mozilla/pdf.js#19229]
### Attach (recommended) or Link to PDF file

[10016583 Lake Elsie RFDS v11(Crump).pdf](https://github.com/user-attachments/files/18146116/10016583.Lake.Elsie.RFDS.v11.Crump.pdf)

### Web browser and its version

Firefox 133.0.3, chrome Version 131.0.6778.140

### Operating system and its version

Windows 10

### PDF.js version

4.9.155

### Is the bug present in the latest PDF.js version?

Yes

### Is a browser extension

No

### Steps to reproduce the problem

1. Open the attached file in viewer. In the 1st page of the attached document, we are not able to view the digital signature when the annotationMode is not set.

### What is the expected behavior?

Even in the image layer we expect the signature to be displayed. 

<img width="1453" alt="Expected" src="https://github.com/user-attachments/assets/a88b5471-50ab-4ea8-999c-15c557bb79a1" />

### What went wrong?

<img width="1604" alt="Current_behavior" src="https://github.com/user-attachments/assets/7237abf7-ab4c-4daf-a21c-22c44f8b272d" />

### Additional context

We are able to view the signature in annotation layer when annotationMode is set to 2, but for our use-case we only use image layer. This was working in previous pdfjs 3.8 version. We have embedded pdfjs code in our application.

**Comment by Snuffleupagus** [comment]
> 1. Open the attached file in viewer. In the 1st page of the attached document, we are not able to view the digital signature when the annotationMode is not set.

It works with `annotationMode = 1`, which is the default value; note https://github.com/mozilla/pdf.js/blob/8985d80aef7678cbf0c5fe119578560f14f4b6ce/src/display/api.js#L1237-L1248
Furthermore, as mentioned in the docs, setting `annotationMode = 0` will *disable all* annotations hence that's the expected behaviour here.

> Even in the image layer we expect the signature to be displayed.

Do you actually mean the *canvas*, since there's nothing called the "image layer"!?

> This was working in previous pdfjs 3.8 version.

Older versions of the PDF.js library had no way to disable annotations, but modern ones have and you'll thus need to use the correct parameters (as mentioned above).

**Comment by Veenam546** [comment]
We have tried below code but still not able to view the digital signature.

```
var renderContext = {
  canvasContext: context,
  transform: transform,
  viewport: viewport
};
page.render(renderContext);
```

We also tried setting with annotationMode=1 still digital signature is not visible.

```
var renderContext = {
  canvasContext: context,
  transform: transform,
  viewport: viewport,
 annotationMode : 1
};
page.render(renderContext);
```
