### ISSUE TITLE
Outline (bookmark) pane should be resizable.

### ISSUE THREAD

**Issue by zhyi** [mozilla/pdf.js#2072]
The outline pane always has a fixed width. Though a horizontal scroll bar is provided, it is still somehow inconvenient.

Furthermore, there is currently no way to fully display a long bookmark name. I think it can be solved by showing a tip (something like title="") when the mouse is hovered above such a bookmark.

**Comment by MetaMemoryT** [comment]
:+1: this is a very important issue

**Comment by ppradeepk** [comment]
:+1: 

I am not sure why this doesn't have the attention it  deserves.

**Comment by Daraius** [comment]
Yes, this would be my #1 Feature Request.  Resizable Bookmarks pane.
Wrapping the text allows reading it but makes the list super long to scroll around in.  So perhaps an option to wrap or not.  But resizable is highly desirable.
Thanks - Daraius

**Comment by nortexoid** [comment]
Still no word on this? Would be a very nice improvement to the current viewer, especially for folk using Chrome OS where there aren't really any other options available.

**Comment by le-jzr** [comment]
Any word on this? Seriously, I've taken to just editing the CSS properties by hand on most documents I open. Nobody gives a rat's ass about prettiness of animations when the current state is just flat out unusable.

**Comment by timvandermeij** [comment]
The viewer is now more responsive (and the code more modular) than it was at the time this issue was filed, so this should be a bit easier to fix now. If someone wants to work on this, please feel free to do so. I'm marking this as a good beginner bug because it does not require in-depth PDF.js knowledge to fix and so it gets more attention from developers that want to start working on PDF.js.

@le-jzr I really want to emphasize that most contributors are working on PDF.js in their spare time and therefore issues have to be prioritized. Please either help out by a) contributing a patch, b) providing constructive feedback or c) upvoting the initial comment of the issue to help raise its priority. Bumping the issue with such a comment is not going to fix the issue any sooner. All contributors do whatever they can to improve PDF.js, so please keep that in mind when writing comments. Thank you.

**Comment by le-jzr** [comment]
Sorry for my lack of manners. While I don't have any experience whatsoever in matters of browser layouts and JavaScript, I would like to suggest that it's not necessary to start with completely interactive solution.

Say, a query string like `?sidebar=500px` might be a good start.

**Comment by timvandermeij** [comment]
Closing since this is implemented by the pull request above.
