### ISSUE TITLE
Font has bold lowercase 'f'

### ISSUE THREAD

**Issue by lehasb** [mozilla/pdf.js#2422]
I ran into a PDF today that was mostly fine but all the lowercase 'f's were bold in the sans-serif font used for quotes (first case is on page 3). Here's the PDF I had the issue with: http://www.mereorthodoxy.com/wp-content/uploads/2011/06/Earthen-Vessels-Excerpt.pdf

I'm running PDF Viewer 0.6.39 on FF 17.0 on Windows7.

**Comment by Snuffleupagus** [comment]
Given the age of this issue, is this problem still present?

(Note that we, since some years, move all glyphs to a Private Use Area to avoid the browser/OS "interfering" with font rendering, which may have indirectly fixed this sort of bug and otherwise it's unfortunately difficult to see what else we could do here.)

**Comment by lehasb** [comment]
I can't seem to recreate this any longer. I haven't done a thorough check, but since the original issue was on Windows 7, I think it's probably been fixed inadvertently at some point.
