### ISSUE TITLE
Figure displayed incorrectly

### ISSUE THREAD

**Issue by wf-r** [mozilla/pdf.js#2546]
On Win8 32bit, PDF.js 0.7.55 and FF 18.0 Figure 3.3 on page 28 is displayed incorrectly (dotted lines are doubled and shifted) : http://www2.math.uni-paderborn.de/fileadmin/Mathematik/AG-Eisenbrand/publications/diss.pdf

**Comment by cetinsert** [comment]
Resolved as of `2.8.335`. @Snuffleupagus @timvandermeij 

https://citeseerx.ist.psu.edu/viewdoc/download?doi=10.1.1.337.2805&rep=rep1&type=pdf

[2546.pdf](https://github.com/mozilla/pdf.js/files/6643989/2546.pdf)

| `.js` | `ium` |
|-|-|
| ![image](https://user-images.githubusercontent.com/27027/121810013-19835780-cc9a-11eb-93bd-2099b3995852.png) | ![image](https://user-images.githubusercontent.com/27027/121810023-21db9280-cc9a-11eb-9daf-8a3d85d06c3a.png) |

**Comment by Snuffleupagus** [comment]
> Resolved as of `2.8.335`.

First of all, please make sure to always test with the `master` branch since no development happens against the released versions.

Secondly, it's not entirely clear if you actually tested on Windows with HWA *off* since that's the particular configuration that this issue concerned here!?

> `.js` 	`ium`

Again, I'm not entirely sure how to interpret this: please make sure to always provide *complete* names of the software you test with.

**Comment by Snuffleupagus** [comment]
WFM, when testing[1] in Firefox Nightly 91.0a1 (2021-06-27) (64-bit) running on Windows 7.

---
[1] By toggling the "Use hardware acceleration when available" checkbox to *off* and restarting the browser first.
