### ISSUE TITLE
Extrememly slow rendering on this pdf

### ISSUE THREAD

**Issue by qlum** [mozilla/pdf.js#2813]
This particular pdf takes more then 10 minutes to load on pdf.js on firefox 20 while If I where to compare it to the internal pdf reader on chrome that one only takes 5 seconds to load the same file. While firefox is loading the file its also slow and not very responsive, if you where to zoom in after it loads it will be a big pain as well. 
https://www.prorail.nl/sites/default/files/spoorkaart_prorail_april_2013.pdf

**Comment by timvandermeij** [comment]
Closing since this PDF file now renders in around six seconds after all performance optimizations since this issue was opened, which brings performance up to par with e.g., Okular and PDFium according to the original report. If there is anything more we can do, a separate issue should be opened with the exact details of what can be improved.

**Comment by Piruzzolo** [comment]
@timvandermeij it loads very slowly on 77.0.1
