### ISSUE TITLE
Rendering slow, fuzzy and incomplete

### ISSUE THREAD

**Issue by lukas-bernard** [mozilla/pdf.js#2825]
In FF 19, this pdf works not.
http://beta.arcig.cz/~bernard/vyuka-m/6krychli.pdf

**Comment by Rob--W** [comment]
I'm looking in a class of bugs involving the tiling pattern. Assigning this one to myself so that it stays on my to-do list.

Here is the uncompressed PDF from https://github.com/mozilla/pdf.js/issues/2825#issuecomment-24234561 to make debugging easier.
[6krychli-uncompressed.pdf](https://github.com/mozilla/pdf.js/files/7237/6krychli-uncompressed.pdf)
