### ISSUE TITLE
[range requests] PDF continues downloading after fatal error occurs

### ISSUE THREAD

**Issue by waddlesplash** [mozilla/pdf.js#3163]
Example: http://files2.appliancesconnection.com/attachments/D1335304737.pdf starts loading but then a fatal error appears in the console (PDF is same as #1828). The range request is not canceled after the error occurs but the progress bar keeps filling.

**Comment by Snuffleupagus** [comment]
While the PDF file is no longer available, I seem to recall that the breaking errors (related to unsupported encryption modes) were fixed by PR #4938.

> The range request is not canceled after the error occurs but the progress bar keeps filling.

At this point in time, there should be API support for aborting loading[1]. Hence it would probably be possible to implement this now, however the question is if you'd want to?
In Firefox (in particular) it's probably not unreasonable to expect that the user will click on the "Open With Different Viewer" button on the fallback bar, when a PDF file fails to open. In that case the PDF file will need to be downloaded anyway, and thus is might not make sense to abort the already running download!?

---
[1] I'm not entirely sure which PRs are relevant, and cannot be bothered to look now... :-)

**Comment by timvandermeij** [comment]
I tend to agree with the above, so I'm closing this as won't-fix unless a use case comes up that is applicable to the current rendering of a PDF file by PDF.js.
