### ISSUE TITLE
Swipe functionality

### ISSUE THREAD

**Issue by VmokshaMobility** [mozilla/pdf.js#3571]
Kindly, let me know if there a possibility in the plugin to swipe PDF pages. 

My requirement demands to identify the swipe gesture or swipe event direction and accordingly navigate to previous or next page.

**Comment by Snuffleupagus** [comment]
Swiping to change page is only implemented for PresentationMode, since "normal" scrolling is disabled there, and it might not work all that well in all situations in the regular viewer (e.g. for documents with varying page sizes).

Given the age of this issue, and the fact that the default viewer was written primarily for desktop usage, closing this as WONTFIX.
