### ISSUE TITLE
imageLayer does not call appendImage on all images

### ISSUE THREAD

**Issue by mitar** [mozilla/pdf.js#3688]
For [this PDF](http://arxiv.org/abs/0704.0010) I would suspect that `imageLayer`'s `appendImage` would be called on all diagrams in the PDF, but from what I can tell this is not so. It is just called for some micro images displayed for QED symbols.

**Comment by Snuffleupagus** [comment]
`appendImage` only works for images included either as standard `XObjects`, or as inline images (i.e. using `BI`-`ID`-`EI` operators).
Most of the "figures" in that PDF file are actually just comprised of standard PDF drawing operators, occurring at various positions within the `Contents` streams, meaning that it isn't possible to know that those should be regarded as "images".

Closing as answered, since this isn't something that we can realistically fix.

(And a work-around would most likely require *a lot* of potentially slow heuristics, with many false positives, for a use-case that isn't really relevant to the core library.)
