### ISSUE TITLE
Support Type1 Hint replacement

### ISSUE THREAD

**Issue by vingtetun** [mozilla/pdf.js#421]
Actually we do not support Hint Replacement in type1 and just assume the font does not use it (this is not the cause of the strange hinting problems we see in the Tracemonkey paper).
This make the font in page 25 of http://faq.ktug.or.kr/wiki/uploads/MathFonts.pdf to fail to load (The sanitizer detects that an hstem is missing some parameters).

For more information see section 8.1, “Changing Hints Within a Character,” in Chapter 8, “Using Subroutines.” of the Type1 specification.

**Comment by SamyCookie** [comment]
I do not see any differences between Acrobat Reader and PDF.js on the last page.
Is the font load issue still exist ?

**Comment by timvandermeij** [comment]
The sanitizer warnings are gone, there is a commit above that appears to have implemented this and the linked PDF renders without problems, so I'm going to close this as fixed. If we're missing support for something here, please open a new issue with more details and example files because currently this issue is not really actionable anymore.
