### ISSUE TITLE
After opening a lot (≥20) PDF files, the latter ones do not load

### ISSUE THREAD

**Issue by Lekensteyn** [mozilla/pdf.js#4228]
I had a lot of PDF files open (about 10). Since I wanted to view PDFs full screen in one screen and scroll through them on another monitor, I bookmarked all tabs and then opened it on another window.

The first 19 PDFs (in total) loaded fine. The n-th PDF did not load at all (n ≥ 20). I was told by @Rob--W that this limitation was caused by a limit on Web workers in Firefox.

What have I tried:

- I went to `dom.workers.maxPerDomain` and changed the default from `20` to `40`. Refreshing the page did not help though. I have not tried restarting the browser.

What would I expect:
- A warning that too many PDF files are open; and/ or
- A button which can be used to display the PDF file anyway.

Platform details:
- Firefox 26 on Arch Linux x86_64

**Comment by yump** [comment]
Looks like the problem occurs with >20 now, not ≥20.  See [Reddit thread](https://www.reddit.com/r/firefox/comments/3lxjdn/unable_to_open_more_than_20_pdf_files/).  Has there been any further work on this?

**Comment by timvandermeij** [comment]
Not as far as I'm aware of. However, is this really a PDF.js issue? It seems like a browser limitation more than anything to me, but I could be wrong.

**Comment by Rob--W** [comment]
@timvandermeij This is a browser limitation, but we can cope with it.

We could try to detect when we've reached the global worker limit, and then re-use worker threads elsewhere. An example of such an implementation is to create two workers; `SharedWorker` and `Worker`. The `Worker` instance is usually used for rendering. The `SharedWorker` is used as a fallback: When the Worker limit has been reached, then creating another `Worker` will fail, but the `SharedWorker` can then be used to handle the other PDFs.
Another way is to notify other subscribers of the SharedWorker events of the worker creation failure, so that another tab can terminate their (idle) worker to regain the ability to launch new workers.

The first requires that we support multiple documents per worker, i.e. that #5992 gets fixed. The second (terminating (idle) workers) requires that we can deal with loosing the worker, e.g. the ability to interrupt rendering, moving ownership of the PDF data buffer to the main thread prior worker termination, and (re)activating workers to process the PDF data at some arbitrary PDF object).

**Comment by timvandermeij** [comment]
Fixed by #6571.

**Comment by Rob--W** [comment]
@timvandermeij How does #6571 fix this bug? It allows PDF.js to use a single worker in a tab controlled by a single page, but this bug is about multiple tabs. Unless SharedWorkers are used, the workers are not shared across tabs, and after 20 tabs, this bug shows up.

Re-opening. If you think that the bug has really been fixed, please point out the mistake in my reasoning.

**Comment by timvandermeij** [comment]
It was mentioned in https://github.com/mozilla/pdf.js/pull/6571#issuecomment-151617456, but I'm also starting to doubt this now, so let's indeed reopen this.

**Comment by Snuffleupagus** [comment]
The worker limit (and the pref `dom.workers.maxPerDomain`) was removed in https://bugzilla.mozilla.org/show_bug.cgi?id=1280241. Closing as fixed.
