### ISSUE TITLE
problems with ligatures

### ISSUE THREAD

**Issue by jlegewie** [mozilla/pdf.js#4297]
Hi,
pdf.js doesn't handle the ligatures in [this example](http://www.columbia.edu/~jpl2136/ligatures.pdf) very well (file contains three examples). Selecting text and copy/pasting or using `page.getTextContent` both show fi as é etc. 

PDF.js v0.8.759 for Firefox and current github version, OS C 10.9.1

**Comment by Snuffleupagus** [comment]
The reason that copying doesn't work is that the `toUnicode` entry in one of the fonts, for some strange reason, maps the ligatures to the wrong characters. This thus explain why copying isn't working in *either* PDF.js or Adobe Reader.
Since this is a bug in the font data of a particular PDF file, and not actually a bug in PDF.js, there isn't really anything we can do about it (we don't have much choice other than trusting `toUnicode`).

Closing as invalid.
