### ISSUE TITLE
PDFjs not working to load pdf that converted from ppt or ppts file  normal in wechat's browser

### ISSUE THREAD

**Issue by weiransoft** [mozilla/pdf.js#4536]
PDFjs not working to load pdf that converted from ppt or ppts file  normal in wechat's browser. if you save as ppt or ppts file to pdf,and open it in embed browser of wechat.

**Comment by Snuffleupagus** [comment]
All modern browsers should support the `Blob` constructor, please refer to http://caniuse.com/#search=blob.

For older browsers lacking such support, setting `PDFJS.disableCreateObjectURL = true;` should probably help avoid these issues, see https://github.com/mozilla/pdf.js/blob/336b26a39dc304fc589d0cfb85c52e7d4ee85112/src/display/global.js#L203-L208.

Closing as answered, since it seems that this is an issue with an older browser that lacks modern features.
