### ISSUE TITLE
Is pdf.js supposed to capture all key events?

### ISSUE THREAD

**Issue by mijoharas** [mozilla/pdf.js#4555]
use of pdf.js with an extension (in chrome) seems to capture all key events.
This shadows functions of the extension, such as back, forward (in history) and switch tab left and right. Apparently this used to work.
https://github.com/philc/vimium/issues/723#issuecomment-39363488

**Comment by mackdata** [comment]
I hope that the J/K keybindings can be harmonized on PDF.js. The vimium implementation is really better than the way pdf.js does it right now.

In practice that would mean that you'd:
- Map **J key** to scroll down x lines.
- Map **K key** to scroll up x lines.

Where x could be set to be something like 4 or 5 lines.

**Comment by dragon788** [comment]
I'd like to see this improved as well, I see that j/k are scrolling, but it's currently a page at a time, while the arrow keys correctly scroll just a small portion of the document at a time. I do love the improvement over the Chrome reader and Adobe since my hands rarely leave the keyboard, but I would like to avoid leaving the home row as much as possible as well and the arrow keys (even on my custom keyboard layout) are just "a bridge too far".

**Comment by MrwanBaghdad** [comment]
Is there any updates?
