### ISSUE TITLE
pdf misses images

### ISSUE THREAD

**Issue by mehlis** [mozilla/pdf.js#4677]
this pdf has several images, but they are not displayed with pdf.js:

http://www.produktinfo.conrad.com/datenblaetter/375000-399999/395775-da-01-de-DIGITUS_BLUETOOTH_ADAPTER.pdf

nothing in the console so far....

**Comment by brainwarped** [comment]
I'm experiencing this issue when viewing PDF version 1.7 using the standard config viewer within an iframe on iOS devices. I have tried debugging, but cannot find an error message. (Chrome emulator displays the PDFs correctly.)

**Comment by timvandermeij** [comment]
Confirmed broken on Arch Linux with Firefox 37.0.1.

**Comment by mehlis** [comment]
@timvandermeij works for me now, please recheck!

**Comment by timvandermeij** [comment]
It's still broken for me on Arch Linux with Firefox 40.0.3 and the most recent PDF.js version.

**Comment by SamyCookie** [comment]
I have tested with a Debian Wheezy 64bits and Firefox 38, the bug was still here. I have updated to new 41 version, and the bug is gone (both with PDF.js embedded version). @timvandermeij, could you test with an up to date Firefox version (e.g. 41) ?

PS : in both case I have tested the upstream bug linked by yury, I saw no change. The printed minimal test was always two rectangle, a yellow and a green one.

**Comment by timvandermeij** [comment]
This is also fixed for me now on Arch Linux with Firefox 42. Closing.
