### ISSUE TITLE
Add support for disentangled search highlighting

### ISSUE THREAD

**Issue by ctensmeyer** [mozilla/pdf.js#4880]
Nutshell: Be able to programatically highlight a word or phrase independent of search.
Explanation: In the default viewer, input to the find widget causes the input to be highlighted as well as causing the viewer to scroll to the next instance.  The scrolling is not always desirable.  For instance, a user selects text to have other instances of that text to become highlighted (like an eclipse text editor).

**Comment by Snuffleupagus** [comment]
Given that this isn't something that [the demo viewer](https://github.com/mozilla/pdf.js#online-demo) would really need, I'd suggest WONTFIX here since this feature probably belongs in a *custom* viewer instead.

Please note http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***
