### ISSUE TITLE
Accessing worker objects

### ISSUE THREAD

**Issue by joepie91** [mozilla/pdf.js#4992]
I'm currently trying to build a PDF debugging/inspection tool based on the default viewer (that goes further than the existing browser.js utility), and to accomplish that I've been trying to figure out how to directly access the xref table from the viewer, but to no avail.

It's my understanding that this table can be accessed through the `PDFDocument` object, however since the viewer appears to be using a background worker, I can only access a `PDFDocumentProxy` object, which does not have an `xref` attribute and does not provide a direct means of access to the underlying `PDFDocument`. I've also been unable to find any methods that might be able to fetch this information through the worker transport.

How can I access the xref table (and possibly other internal data) in the default viewer, preferably without modifying the pdf.js core files?

**Comment by timvandermeij** [comment]
This is not something we support right now, nor will we in the future because it's a way too low-level API for most PDF.js users. If you need such functionality, you'll have to build it yourself in a custom version of PDF.js. Note that a tool that is similar to what you're asking is developed by one of the PDF.js developers at https://github.com/brendandahl/pdf.js.utils/blob/master/browser/browser.js to view the structure of PDF files, see https://github.com/brendandahl/pdf.js.utils/blob/master/browser/browser.js#L78-L129 in particular.
