### ISSUE TITLE
Please also allow creating a minified compatibility.js

### ISSUE THREAD

**Issue by josch** [mozilla/pdf.js#5041]
Hi,

using the `minified` target it is already possible to generate a minified version of pdf.js. Would you mind adding a line which also creates a standalone minified version of compatibility.js?

compatibility.js is used by pdf2htmlEX which we are packaging for Debian. Since pdf2htmlEX embeds compatibility.js into every generated HTML file, it does make sense to embed the minified version. The best binary package to supply a minified version of compatibility.js is the libjs-pdf package itself. We could carry a patch for make.js which minifies compatibility.js but would prefer to keep the amount of patches we carry low. Thus we wanted to ask you whether you could consider generating a minified version of compatibility.js in your version of make.js in addition to the minification that is already done?

Thank you for your consideration!

**Comment by Snuffleupagus** [comment]
After PR #8102, `compatibility.js` is now bundled *directly* into the `pdf.js` and `pdf.worker.js` files to remove the need to include it manually via HTML code.
Furthermore, after PR #9093 (in preparation for the upcoming release of PDF.js version `2.0`) we're no longer publishing `compatibility.js` as a standalone file.

Closing, since this issue is no longer relevant.
