### ISSUE TITLE
Pinch to Zoom stops rendering

### ISSUE THREAD

**Issue by webdevjg** [mozilla/pdf.js#5176]
I'm using the Hammer.js library to provide touch events to the PDF.js viewer.  However when the zoom on mobile devices reaches greater than 110% percent any text in PDF is removed.  All that remains are white pages and certain elements (i.e a link that was highlighted still has the blue border around it)

**Comment by timvandermeij** [comment]
I have worked with Hammer.js too to try to implement pinch to zoom, but it would transition waty too fast, causing a lot of re-rendering and performance issues. The pages can become white if re-rendering fails, which is a problem I also encountered. It seems like Hammer.js is just not the right tool for the job. Closing as answered, otherwise try the mailing list.
