### ISSUE TITLE
Shortcut Request

### ISSUE THREAD

**Issue by leoheck** [mozilla/pdf.js#5206]
Hi, I just found the shortcut's documentation here, https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts

There is no shortcut for the "Page Fit" command.
It would be nice to have this shortcut because it is very convenient for pdf presentations.

And thanks guys for the nice tool.

**Comment by Snuffleupagus** [comment]
I'd suggest closing this as WONTFIX, for the following reason:
 - You'd have to come up with a shortcut that doesn't clash with any existing ones in the browser, see https://support.mozilla.org/kb/keyboard-shortcuts-perform-firefox-tasks-quickly
 - Furthermore, the shortcut cannot clash with existing PDF.js ones, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-shortcuts
 - The shortcut should, at least somewhat, make sense since an arbitrary choice doesn't seems that useful.
 - If you add a shortcut for "Page Fit", then for consistency you probably should add shortcuts for "Actual Size" and "Page Width" as well (which further compounds the issues listed above).

**Comment by reasonablecow** [comment]
Is the shortcut `[Ctrl] + [\]` already taken (I looked up both documents and found zero usage of backslash), or otherwise inappropriate? I am not sure it makes a lot of sense, but it's the shortcut in chrome, so many people are already familiar with it. The first usage fits the width, and every following press switches between "Page Fit" and "Page Width".

**Comment by TheRickyZhang** [comment]
This has been closed for a while, but personally having any configurable shortcut would be nice for this purpose even if the specific keys don't mean anything.
