### ISSUE TITLE
Support more cmap platform/encoding pairs

### ISSUE THREAD

**Issue by behdad** [mozilla/pdf.js#5231]
Currently only (3,1) is supported:

  https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L3102

Here's what should be supported, and the order they should be preferred:

  https://github.com/behdad/harfbuzz/blob/master/src/hb-ot-font.cc#L83

**Comment by Snuffleupagus** [comment]
In practice, it seems that the cmap formats used in PDF files are only a subset of the possible ones (from a font specification point of view). I'm not sure if it makes much sense for us to attempt to implement support for more cmap formats, without examples of actual *PDF files* that are currently broken because of our (incomplete) cmap support.

Hence I'm closing this issue; but please open separate issues for individual PDF files where we're not rendering the fonts correctly.
