### ISSUE TITLE
PDF is throwing: Message: invalid top-level pages dictionary error

### ISSUE THREAD

**Issue by miltonpereira** [mozilla/pdf.js#5241]
Visit:  http://mozilla.github.io/pdf.js/web/viewer.html
Upload file attached in comment
Observe that following error appears
http://mozilla.github.io/pdf.js/web/viewer.html

**Comment by Snuffleupagus** [comment]
It seems that https://bugzilla.mozilla.org/show_bug.cgi?id=1037816 is another example of the same issue; given that the errors are identical, the PDF files look similar (when browsing through them with a text editor), and that both are created with `Nuance PDF Create 8`.

**Comment by Snuffleupagus** [comment]
This seems to work, and passes all tests: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:Parser_getObj-skip-over-endobj, but I'm not yet entirely sure why it's actually necessary :-)

**Comment by EltonR** [comment]
I'm still getting this error with the file bellow:
[Documento_T.pdf](https://github.com/mozilla/pdf.js/files/7131696/Documento_T.pdf)

**Comment by Snuffleupagus** [comment]
@EltonR As explained in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, you should open a new issue rather than commenting on (multiple) old ones; since it's more or less guaranteed to not be *exactly* the same problem.

When you do however, please make sure that you provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md

Finally, note that your PDF document doesn't even open in Adobe Reader (which is the PDF reference implementation), hence it's actually a bug in the document and not in the PDF.js library.
