### ISSUE TITLE
Highlight showing over text in IE, but works in Chrome/Firefox

### ISSUE THREAD

**Issue by msladev** [mozilla/pdf.js#5264]
There is a text that was highlighted but in IE the highlight is showing over the text and hiding the original text. However, in Chrome and Firefox the highlight works as expected. Screenshots are shown below.

In IE:
![hightlight](https://cloud.githubusercontent.com/assets/8659209/4154582/b9649a0c-3462-11e4-9e41-979c03b142fa.PNG)

In Chrome:
![highlight chrome](https://cloud.githubusercontent.com/assets/8659209/4154652/88afe910-3463-11e4-97fc-a940e14a480d.PNG)

Thanks,
MSLA-IT

**Comment by tbasse** [comment]
@msladev, your solution worked perfectly for us until we stumbled upon some PDFs which rendered other image and shape elements with a 50% transparency due to this change.

Example PDF: https://dl.dropboxusercontent.com/u/1652601/ht-1-handbook.pdf

We then moved the workaround to `CanvasGraphics_beginAnnotation()` and only apply it for IE so it only affects the text highlight and only when it needs to.

![screen shot 2015-04-25 at 10 42 43 am](https://cloud.githubusercontent.com/assets/291433/7330805/07fb91d8-eb39-11e4-84c2-bfef0a815d2d.png)

**Comment by lochstar** [comment]
Thanks @tbasse, works great.

**Comment by ArnoldFabasoft** [comment]
We had the same issue in our integration of pdf.js. We implemented the workaround of tbasse for internet explorer. Thanks @tbasse 
Will this fix or an other implementation find a way into pdf.js? I want to modify the original code as less as possible.
Thx Stefan

**Comment by jeremypress** [comment]
@yurydelendik, would you be open to a contribution that implements this workaround? I highly doubt that Microsoft will be addressing this on their end.

**Comment by timvandermeij** [comment]
This workaround is not acceptable for in the core, but it is may be accepted if it can be feature-detected and placed in https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
