### ISSUE TITLE
Implement Highlight File support with #xml=

### ISSUE THREAD

**Issue by tssk** [mozilla/pdf.js#547]
Nice to have feature to support externaly generated highlight information.

Adobe supported specification - http://partners.adobe.com/public/developer/en/pdf/HighlightFileFormat.pdf

**Comment by SamyCookie** [comment]
The specification link is broken, I upload the specification [here](https://github.com/mozilla/pdf.js/files/2376671/HighlightFileFormat.pdf).

**Comment by markmatney** [comment]
Related to https://github.com/mozilla/pdf.js/issues/4862.

I'm wondering if both of these issues could be addressed by implementing a generic notion of user-supplied highlight annotations. This new class of annotations would essentially be a "blank" `HighlightAnnotation` (i.e., no title or body).

In the case of those annotations relevant to this issue (https://github.com/mozilla/pdf.js/issues/547), each annotation would be rendered as one or more rectangular highlights on a sequence of words or characters (according to the [spec linked in the above comment](https://github.com/mozilla/pdf.js/issues/547#issuecomment-420776660)):

> highlights are given as character offsets on the page (characters) or as word offsets on the page (words).

What makes this potentially complicated is that the value of the `xml` URL fragment parameter is _itself_ a URL that points to a "highlight file", which must obviously be fetched when it is first referenced and should be re-fetched as often as possible in order to check for changes. In order to ensure that changes to the highlight file are reflected by PDF JS as soon as possible, the file should be fetched when a user either:
1. reloads PDF JS without changing the URL of the PDF they are viewing, or
2. changes the URL fragment of the URL of the PDF they are viewing, but keeps the value of the `xml` parameter (the highlight file URL) the same, for example:
    - `http://example.com/test.pdf#page=69&xml=http://example.com/hl.txt` ->
    - `http://example.com/test.pdf#page=420&xml=http://example.com/hl.txt`.

**Comment by jorbig** [comment]
Is this feature to be expected anytime soon?

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX for now, given that it's a very old issue (and the feature itself isn't commonly requested, and loading an external highlight-file could be tricky to implement in general with given e.g. CORS restrictions).
