### ISSUE TITLE
A small pdf cause pdf.js loading very slow and costs much more memory

### ISSUE THREAD

**Issue by xunxun1982** [mozilla/pdf.js#5503]
The small pdf is : http://www.wp11261757.server-he.de/Account-Closure-Form-lo-res.pdf

its size is only 1.1MB

but pdf.js loads it very slow and costs more than 2.5GB memory in my browser.

**Comment by apoku** [comment]
Any insight on what is problematic with this type of PDF file? (i.e. if a file has these characteristics, one can expect the reported behavior).

**Comment by timvandermeij** [comment]
There is a huge image in this PDF. Even though the file name contains "lo-res", it really is not. One should avoid using huge images in PDFs for on the web and downscale them a bit. These huge images are only relevant for printing really.

**Comment by sentientmachine** [comment]
Small PDF's loading slowly and taking huge disk and memory can be a troll.  You can make SVG graphics that renders each letter to terabyte-levels of detail that make it so your PDF reader freezes for seconds or minutes, just to scroll up or down.

John Cleese explained why these things exist his sketch on the cheese shop and how to irritate people.

**Comment by timvandermeij** [comment]
Closing since the URL is no longer reachable, the Web Archive doesn't contain a copy either and we just merged a new JPX decoder that should be more performant. If the problem still exists in the _most recent_ version of PDF.js at https://mozilla.github.io/pdf.js/web/viewer.html, please open a new issue with all required details and attach the PDF file to prevent it from getting lost over time.
