### ISSUE TITLE
textLayer slightly off

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5558]
The text layer for marking, as demonstrated in the [simpleviewer](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.html) is slightly off (towards the bottom). The example from there shows

![off](https://cloud.githubusercontent.com/assets/181628/5492529/7ba875c6-86e2-11e4-88c3-70a4841fa95c.png)

**Comment by Hengjie** [comment]
I've studied this problem and the way to fix it is to use `font_metrics.js` found in #4629. I've been improving on that code recently, to resolve problems with large or small zoom.

The reason why it happens is because the calculated fontAscent in text_layer_builder.js is slightly off, and always appears to be so. If anyone has better ideas of resolving this without using `font_metrics.js` I'd like to know, since the aforementioned solution can be (slightly) less performant.

**Comment by Hengjie** [comment]
Thinking about this more. What `font_metrics.js` is really doing is just letting the browser render the fonts correctly and then we measure it from the canvas. It basically means that the font rendering pipeline on the PDF.js end isn't as good as the browser, therefore we fallback to the browser for that information. So probably the best solution would be to improve the font pipeline in pdf.js

**Comment by nschloe** [comment]
Pull request #5545 largly fixes this problem.

**Comment by timvandermeij** [comment]
Closing since this got fixed by #12896 and other work.
