### ISSUE TITLE
simpleviewer: Show PDF in full width (without SCROLLBAR_PADDING)

### ISSUE THREAD

**Issue by nschloe** [mozilla/pdf.js#5559]
In https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L356, we find that the width scaling involves `SCROLLBAR_PADDING` (unless in presentation mode). For my use case, I would like the PDF to occupy the full width of the encapsulating `div`. (There's no scroll bar anyways.)
One obvious solution would be to add another switch value, `'full-width'`, which unconditionally sets the `hPadding` to `0`.

**Comment by nschloe** [comment]
@Snuffleupagus @yurydelendik Looking at the code where `{h,v}Padding` are set, it'd suffice for me if I could set
```
pdfViewer.presentationModeState = PDFJS.PresentationModeState.FULLSCREEN;
```
I'm not sure of the other implications of setting this to full screen when it really isn't, but anyhow it removes the unnecessary padding.

Unfortunately, I don't see `PresentationModeState` exposed anywhere. Can you help me out?

**Comment by Snuffleupagus** [comment]
@nschloe I would *very strongly* advice against doing that, since that will have a number of (most likely) unwanted side-effects.
Please look through the code in [pdf_viewer.js](https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js), try searching for e.g. `.presentationModeState`, and you will see that there's quite a bit of special handling of the `FULLSCREEN` case.

I don't think that we should expose two *slightly* different "width" zoom options in the standard viewer, which is why I personally don't think the proposed PR is a good idea in its current form. (Also, in the standard viewer, using `full-width` as implemented in that PR would cause a horizontal scrollbar to be displayed.)
Unfortunately the review times have been a bit long recently, so I don't think the developers have had time to look at it (and provide feedback) yet.

To add a `full-width` option, a very simple solution would be to modify `pdf_viewer.js` e.g. like this:
```diff
diff --git a/web/pdf_viewer.js b/web/pdf_viewer.js
index ea70979..ec0d5cd 100644
--- a/web/pdf_viewer.js
+++ b/web/pdf_viewer.js
@@ -424,6 +424,11 @@ var PDFViewer = (function pdfViewer() {
               Math.min(pageHeightScale, pageWidthScale) : pageWidthScale;
             scale = Math.min(MAX_AUTO_SCALE, horizontalScale);
             break;
+          case 'full-width':
+            // Width zoom option without padding, for e.g. viewer components.
+            scale = this.container.clientWidth /
+                    currentPage.width * currentPage.scale;
+            break;
           default:
             console.error('pdfViewSetScale: \'' + value +
               '\' is an unknown zoom value.');
```

**Comment by nschloe** [comment]
I've found an even simpler fix, see pull request #5787.

**Comment by nschloe** [comment]
@Snuffleupagus Thanks for reviewing the pull request and highlighting why it isn't appropriate.

Anyhow, the problem of a too narrow width remains:
![padding](https://cloud.githubusercontent.com/assets/181628/6505450/adfcc0bc-c342-11e4-90dc-5c5b423cd727.png)

If I understand correctly, one problem is that `pdf_viewer` is hardcoded to appear with a border-shadow, requiring the extra padding. Would it be possible to remove this requirement? I could live with _anything_  that makes better use the precious screen real estate.

**Comment by nschloe** [comment]
@Snuffleupagus Do you think the addition of `'full-width'` to `pdf_viewer.js` as mentioned above would be an appropriate fix for this?

**Comment by Snuffleupagus** [comment]
Since the `full-width` option wouldn't really deal with the underlying issue, which is the assumption that the pages have a border, I think that it would probably be better to try and make that configurable.

The following is a *very* quick, and poorly tested, patch that enables the user of `PDFViewer` to remove the page borders through an option: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:noPageBorder.
Please test it and see if does approximately what you want, in which case I would be happy to submit a PR for the devs to consider.

**Comment by nschloe** [comment]
@Snuffleupagus This change does exactly what I need.

Before:
![before](https://cloud.githubusercontent.com/assets/181628/6620083/f7777368-c8ce-11e4-8436-b3405865b9ef.png)

After:
![after](https://cloud.githubusercontent.com/assets/181628/6620087/fe765dbe-c8ce-11e4-9f51-6d0ef1c812b2.png)
(Note: The shadow borders in the screenshot are introduced by myself a posteriori.)

This is with
```
var pdfViewer = new PDFJS.PDFViewer({
    container: element[0],
    viewer: element[0],
    noPageBorder: false
});
```
If promoted to a pull request, I'd recommend to name the variable `setPageBorder` have it default to `true` (instead of `noPageBorder` defaulting to `false`). This makes it a tad bit easier to read and understand.

**Comment by timvandermeij** [comment]
I agree that the name `setPageBorder` would be a better name. I also think @Snuffleupagus' fix is pretty clean.

**Comment by Snuffleupagus** [comment]
This issue concerns an edge case that *does not apply* to the standard viewer, which is why I believe that a name such as `setPageBorder` would be bad for a number of reasons:
 1. The default value currently is, and should continue to be, that the pages have borders *unless* specified otherwise, hence such a name would be quite misleading. It suggests that you *must* set the variable for the borders to be used, when the reverse is actually correct.

 2. Having a parameter that defaults to `true` would mean that if it's not provided when calling `new PDFViewer(...)`, we have the somewhat illogical situation where an `undefined` value implies `true` (instead of the more expected `false`).

 3. It would make the code slightly less clean, and given that this is an edge case, we should strive to make the implementation as simple as possible.

**Comment by nschloe** [comment]
@Snuffleupagus Agreed. Not specifying the option should fall back to default (namely to set a page shadow), and since JS uses `undefined` as default and `undefined` is clearly `false`, we have to name the option `omit...`. Too bad, but I guess this is what JS is.
