### ISSUE TITLE
Saving the edited version of the PDF

### ISSUE THREAD

**Issue by JosephShering** [mozilla/pdf.js#5615]
I'm using pdf.js to display and edit a pdf in the browser, is there a way for me to get that edited PDF so I can resave it to my server?

**Comment by yurydelendik** [comment]
How do you edit it? PDF.js viewer does not allow or provides any editing functionality. If it would, it would allow you to download binary PDF data.

**Comment by timvandermeij** [comment]
Closing as incomplete. PDF.js does not have the ability to edit PDFs.

**Comment by ensemblebd** [comment]
Actually it has a form example which permits the usage of PDF's that contain form elements. 
pdf.getData() obtains the original canvas data, so in my opinion the solution is to submit the absolutely positioned form elements to a system that can compile the elements by name into the pdf, save it, and then you have a saved copy of edited pdf. 
I'm using coldfusion, and doing exactly that. 
Submitting this comment on an old closed thread because I feel the information is pertinent and contextually valid.

I found a way to add pages to the "edit mode" view of the pdf, but it certainly complicates things. For me , page #2 is a supplementary page, and so I allow my clients to add more of them to the working pdf, and handle it all manually. I definitely think it's a topic worthy of a fork and pull request. But not heading down that path myself quite yet.

**Comment by xlc** [comment]
https://github.com/mozilla/pdf.js/pull/6190 offers a way to edit PDF but you have to understand PDF spec before you can do anything useful with it.

**Comment by sandeep2244** [comment]
Hey @JosephShering , did you get , how to save updated pdf form data in bytes ?

**Comment by hemant3434** [comment]
Same comment as above, was anyone able to figure out how to get the form data inputted by the user along with the pdf as bytes?

**Comment by ditinex** [comment]
no luck saving the edited pdf

**Comment by sandeep2244** [comment]
Seems like this is premium feature of many library. Saving pdf files required to do engineering at browser level, as Firefox, chrome and safari may different Dom structure, need to create one viewer top of DOM and save it will work, don't aware about implementation.

**Comment by antonnifo** [comment]
It's 2024 anyone who has figured out how to save a file after annotations has being added to it using pdf.js?

**Comment by JakobJFL** [comment]
Looks like things have changed in newer versions of PDF.js.

If you have input fields in your PDF and want to download the PDF with the annotations, you can use the `saveDocument()` method instead of `getData()`.
```
const data = await pdfViewer.pdfDocument().saveDocument();
const blob = new Blob([data], { type: "application/pdf" });
```
Now just create a download for your Blob and when you should get a PDF with the annotations.
The code could look like this:

```
const blobURL = URL.createObjectURL(blob);
const a = document.createElement("a");
a.href = blobURL;
a.download = "This pdf has annotations🎉";
a.style.display = "none";
document.body.append(a);
a.click();
URL.revokeObjectURL(blobURL);
a.remove();
```

**Comment by bonnebulle** [comment]
Yes, save data as blob (or other way), should help to reload pdf in is last working state (annotating)... 
maybe as localstorage? Perhaps in a future version...
