### ISSUE TITLE
Image is fuzzy and has artifacts when viewed in PDF.js

### ISSUE THREAD

**Issue by alexhenrie** [mozilla/pdf.js#5616]
The image at http://www.slcdocs.com/Planning/MasterPlansMaps/North_Temple_Master.pdf#page=5 is fuzzy and has artifacts when viewed in Firefox (both on Windows and on Linux), but it is perfectly clear when viewed in Evince.

The following message appears in the browser console: "Warning: Trying to recover from JPX Error: Out of packets"

**Comment by fkaelberer** [comment]
Have you tried the latest version of pdf.js? It may be fixed by now. (Links: [online viewer](http://mozilla.github.io/pdf.js/web/viewer.html), [Firefox extension](http://mozilla.github.io/pdf.js/extensions/firefox/pdf.js.xpi))

**Comment by Snuffleupagus** [comment]
Works for me, using: Windows 7 (64-bit), Firefox Nightly 37 (buildID: 20150105030202) with HWA on, and PDF.js 1.0.1051.
@alexhenrie You can confirm that this is fixed by opening the file (by using the "Open file" button on the right-hand side of the toolbar) with the demo viewer: http://mozilla.github.io/pdf.js/web/viewer.html.

There has been a number JPX patches recently, e.g. #5426, hence I'm closing this issue as WORKSFORME.

**Comment by alexhenrie** [comment]
Ok, thanks!
