### ISSUE TITLE
Error when the same canvas is used for two render operations

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#5636]
To illuminate the common mistake: throw an exception if the canvas/context is used to start the rendering when other one with the same context is in progress

... and probably modify hello work example to e.g. print console message to indicate when rendering is finished.

**Comment by csicky** [comment]
Actually this is an API design issue. Instead of failing or throwing error it should simply abort previous render task silently and start the new task when it's safe to do. This issue was created in 2015. More than two years have passed and people make the same "mistake". I would say it's a hint for a better API.

**Comment by yurydelendik** [comment]
> This issue was created in 2015.

Which issue?

**Comment by yurydelendik** [comment]
> More than two years have passed and people make the same "mistake"

While we are deciding on better API, old will stay. Starting multiple render() shall be addressed regardless of what new API will look like.
