### ISSUE TITLE
'Show previous position upon load' preference not set correctly

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#5648]
Initially found when testing #5619. Disabling 'Show previous position upon load' does not seem to work for the Chrome extension as the viewer will still go back to the original position. @Rob--W debugged the issue and found that it is not specific to the Chrome extension. It is caused by the fact that the history's state is preserved when the page is reloaded. The page size, etc. are persisted in history.state across reloads.

We need to find a way to make this work, or remove the preference (or at least not present it to the user).

**Comment by Snuffleupagus** [comment]
I've actually wanted to remove that pref for a while (I even made a PR, see #4670), since it's useless for our main use case (Firefox) ever since we started using `SessionStorage` instead of `LocalStorage` in the addon/moz-central version.

This pref *should* still work when the PDF file is opened in e.g. a new tab, but since reloading is functionally equivalent to navigating away from the page I believe that this should explain the observed behaviour.
Note that the history stores the current position when navigating away from the page, to be able display the document at the last viewed position when going back in the history.
Since the history implementation has shown to be a bit fragile (given the lack of test coverage for the viewer), I'd suggest that we don't try to hack around the reload issue.
The easy "solution" to the reload issue is to either: ignore it, since it's an edge case anyway; or just remove the pref, thus eliminating the issue.

**Comment by Rob--W** [comment]
The bug can relatively easily be fixed: Just check whether this pref is set before using the value in `history.state`

The settings are still saved in `localStorage` for non-Firefox environments, and I can imagine use cases (e.g. PDF.js on the web, PDF Chrome extension in kiosks) where the user does not want to save state across restarts.

**Comment by Snuffleupagus** [comment]
> The bug can relatively easily be fixed: Just check whether this pref is set before using the value in history.state

That would break the main use case, which is displaying the correct position when navigating back to the document. (One very simple option would be just disable the history all together in this case.)
I'll think about this some more, to see if there are any better options available (I really want to avoid regressing anything here).

**Comment by Rob--W** [comment]
@Snuffleupagus 
The option is disabled by default.

I was thinking of logic like "Upon load, if the preference is set, reset `history.state`". This pref will not affect in-page navigation (i.e. navigation without unloading the viewer). If the user navigates away from the viewer, then goes back, the viewer will show the top of the document.

**Comment by Snuffleupagus** [comment]
@Rob--W Is this more along the lines of what you suggested https://github.com/Snuffleupagus/pdf.js/compare/issue-5648?

**Comment by Rob--W** [comment]
@Snuffleupagus 
That patch looks quite relatively complicated, and violates the defined interface.

I'm thinking of something like this, which explicitly communicates that the if the preference is set, then the document is initialized with an empty state:

```diff
diff --git a/web/viewer.js b/web/viewer.js
index 806c9f0..ce0aef2 100644
--- a/web/viewer.js
+++ b/web/viewer.js
@@ -897,6 +897,9 @@ var PDFViewerApplication = {
     var showPreviousViewOnLoadPromise =
       Preferences.get('showPreviousViewOnLoad').then(function (prefValue) {
         showPreviousViewOnLoad = prefValue;
+        if (!showPreviousViewOnLoad && window.history.state) {
+          history.replaceState(null, '');
+        }
       });
     var defaultZoomValue;
     var defaultZoomValuePromise =
```

**Comment by BeverlyLA** [comment]
I tried showPreviousViewOnLoad=false. But- does not solve my specific case of:
1) Render PDF document with highlighted text (abc) on page 3. It opens page 3 and shows highligthed text. Beautiful!
2) Now, render **same** PDF document with **different** highlighted text (xyz), PDFJS opens on previous page 3 instead new page (which is page 11). The highlight on "xyz" works. But does not take me direct to the page 11 where xyz is highlighted.

Any help would be appreciated. Thanks in advance.

**Comment by BeverlyLA** [comment]
Also- if you scroll to a different page, it opens the last page viewed over-riding the "highlight text selection" page..
