### ISSUE TITLE
viewer.html - minimum width iOS

### ISSUE THREAD

**Issue by Trevelyan87** [mozilla/pdf.js#5658]
Im inserting viewer.html into an iframe on my web application to view pdf's. Due to the restraints of my application I have limited width to work with. The viewer works great on desktop browsers and adds overflow scrolling if the width goes too small. 

On iOS, the viewer is being resized larger than its iframe container. 

The following jsfiddle illustrates my point: http://jsfiddle.net/b9q1k8g7/1/

As you can see if viewed on a desktop browser the width is set correctly. On mobile safari (iPad/iPhones) the iframe displays wider than the 250px width set. 

Any assistance would be greatly appreciated.

**Comment by timvandermeij** [comment]
250px is really too small to be able to properly work with the viewer. For this use case you probably need to strip down the viewer such that only the pages appear and the width is fixed to 250px, otherwise it will be impossible to work with nicely. Closing as answered, otherwise try asking at the mailing list.
