### ISSUE TITLE
PDF displays text layer before rendering correctly

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#5666]
https://pdf.yt/d/24F9YmgH0xUy-VOV

This PDF seems to display the text layer before rendering correctly.

Chrome 39,  Windows x64,  PDF.js 1.0.1086

First rendering
![image](https://cloud.githubusercontent.com/assets/10129039/5858814/fc14bffe-a24d-11e4-89ac-7ebac27c6106.png)

Correct rendering
![image](https://cloud.githubusercontent.com/assets/10129039/5858909/8d4d0c1a-a24e-11e4-9980-a022d85afc45.png)

**Comment by sethnk** [comment]
Windows 8.1 x64

**Comment by Snuffleupagus** [comment]
That is not actually the `textLayer`, i.e. what we're using to enable text selection and searching, you're seeing. The PDF file itself contains a lot of standard `showText` commands, which the images in the file are subsequently rendered "over" thus obscuring the text.
The same effect can actually be observed in Adobe Reader as well, if you change the zoom level quickly. Since the performance of PDF.js isn't quite as good as a native application, this effect is unfortunately more pronounced in PDF.js.

The reason that this is an issue at all, however, is that the PDF file is using incorrect text rendering modes. For PDF files like these, which contains a scanned image, it's possible to specify that (OCR) text used for selection and searching should be invisible (i.e. text rendering mode `3`).
Unfortunately this PDF file doesn't used the "invisible" text rendering mode, which thus explains the rendering issue observed here.

Since this really is a bug in the PDF generator, and Adobe Reader suffers from it as well, I would say that isn't actually an issue we can do anything about in PDF.js.
Hence I'd recommend that we close this issue as invalid, since the PDF file itself is broken.

**Comment by yurydelendik** [comment]
@sethnk can you provide more details how this document is created, so we will have a sense how many those PDF documents might exist?

**Comment by sethnk** [comment]
I didn't create it - I downloaded it.  I have only seen this issue on two pdfs out of 100's, so it is rare.  And also, as Jonas said, it is only visible temporarily while the pdf renders - as far as I am concerned it is a minor cosmetic issue and not important and by the sounds of it, pdf.js is behaving correctly - the pdf is likely to be at fault.

**Comment by timvandermeij** [comment]
Closing as won't-fix for the reasons mentioned above.
