### ISSUE TITLE
Not sending referrals in Chrome

### ISSUE THREAD

**Issue by Hengjie** [mozilla/pdf.js#5676]
Can't load files which require referrer on the server side

**Comment by Rob--W** [comment]
At present, adding the referer header in the Chrome extension is far from trivial. Do you have a (public) example where the absence of the referer header causes issues?

**Comment by CodingFabian** [comment]
@Rob--W thats a poor mands bandwith stealing protection. if you have that link on a website, clicking it would send the referrer, so the serverside pdf generation can check if that link was on a different page (who stole your content or traffic)
Its actually not that uncommon of a pattern. especially used for images.

**Comment by Hengjie** [comment]
I forgot exactly where but it's behind the https://select-a-spot.com/bart/ login wall. When I try to export the parking ticket or parking invoice, it'll require the PDF to be loaded from the referral.

**Comment by Hengjie** [comment]
Any update on this issue?

**Comment by Rob--W** [comment]
I have done three attempts at implementing this feature.

1. Grabbing `document.referrer` from the viewer and passing it with every request. This does not work, because `document.referrer` is only set for http(s) pages in Chrome, not on extension pages.
https://github.com/Rob--W/pdf.js/tree/preserve-http-referer-by-document.referrer (9b08e9f571f7e73e0542bb1fd6434b68d5a281fc)

2. Saving the Referer http header, and adding the header back to requests originating from that frame. An issue with this is that the referer is lost upon unload of the viewer.
https://github.com/Rob--W/pdf.js/tree/preserve-http-referer-by-header (d7924bac214197d25a58b24cef38d50c43621d19)

3. Combining both approaches. I extract the Referer header from the initial request, but persist it at the page. This seems to work well in all cases. I'll submit the patch as PR #5823.

**Comment by Rob--W** [comment]
@Hengjie Could you verify that the patch in #5823 resolves the problem?
If you don't have access to your original website, follow the steps from https://github.com/mozilla/pdf.js/pull/5823#issuecomment-82639912

**Comment by mplungjan** [comment]
Still an issue in PDF viewer Version 2.3.164 extension in May 2020 Chrome 81
