### ISSUE TITLE
Your Example Doesn't work...

### ISSUE THREAD

**Issue by courtaks** [mozilla/pdf.js#5707]
it outs red alert with this message:
Message: Unexpected server response (0) while retrieving PDF "http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf".

**Comment by timvandermeij** [comment]
Both https://mozilla.github.io/pdf.js/web/viewer.html and http://mozilla.github.io/pdf.js/web/compressed.tracemonkey-pldi-09.pdf work perfectly fine for me, as is the Demo button on http://mozilla.github.io/pdf.js. Maybe it was a temporary flaw from GitHub? Closing as resolved for now; otherwise please post more information about your browser and OS.

**Comment by roygwsidev** [comment]
getting same issue
PDF.js v? (build: ?)
Message: Unexpected server response (0) while retrieving PDF "http://static.googleusercontent.com/media/source.android.com/en//compatibility/android-cdd.pdf".
