### ISSUE TITLE
Internal links can change the zoom setting

### ISSUE THREAD

**Issue by aleth** [mozilla/pdf.js#5736]
I'm not sure if this is a bug or a PDF 'feature', but it's certainly surprising:
In this PDF
http://iopscience.iop.org/0264-9381/32/6/065001/pdf/0264-9381_32_6_065001.pdf
clicking on a reference (e.g. [1]) changes the zoom setting (zooms in).
Furthermore, if one then presses the back button to return, this zoom setting is retained and does not go back to the original one.

pdf-js 1.0.1143 on Firefox Aurora/OSX 10.10

**Comment by Snuffleupagus** [comment]
As far as "links" (or destinations, as they are called) in PDF files goes, the fact that they may also change the zoom level is feature of the specification. If you're interested, you can read more e.g. [here](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1947713) and [here](http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G11.1696125).

The fact that the zoom level isn't reset properly when going back, does however qualify as a bug.
With the way that the history in PDF.js is currently implemented, this might unfortunately be slightly difficult to fix without breaking something else. (I've actually tried once, in PR #3856, but that wasn't very good.)

**Comment by SamB** [comment]
I've always rather hated this feature and wished that Acrobat Reader had a way to turn it off. (I found it *especially* frustrating when I couldn't tell [`hyperref`](https://www.ctan.org/pkg/hyperref) not to include such zoom settings in the links and/or "bookmarks" in PDFs *I* was making. Thankfully, they fixed that at some point.)

So I'd be *quite* happy with a way to turn that off in **about:config**.

**Comment by tallus** [comment]
I want to point out the accessibility consequences of the first part of this issue. 

Though I accept that setting zoom levels is mandated by the PDF spec, this is somewhat contradicted by PDF/UA (which is now mandated by the US Access Board). I don't have the PDF/UA spec (or the money to buy a copy from ISO) but this presentation http://www.appligent.com/files/section508-pdf-center-documentation/ET04_PDFUA_The_Standard_for_Accessible_PDF.pdf addresses this issue  and would seem reasonably authoritative given its authors. It says:

> "Shall have the ability to navigate via outlines (bookmarks) 
> 
> Shall permit navigation zoom values to be overridden by the user"

Which is entirely consistent with what I read elsewhere, the former is necessary for users with cognitive impairments, the latter is necessary to maintain legibility.

As it happens I have both a cognitive and a visual impairment. This is not surprising, a combination of the two is almost inevitable, if you have the first, given normal age-based visual degeneration.

So the issue arises when I use bookmarks as an aid for my cognitive impairment, since the zoom level can be reset, meaning the text is no longer legible (especially since page fit is a common choice, and that's never legible for me, typically, even with the window full size on a decent size monitor (and having windows full-size interacts badly with my cognitive impairment)). Having the ability to reset the zoom level afterwards, is not a good solution. Aside from being annoying, and the extra burden imposed,  the interruption interacts badly with my cognitive impairment and  negates the benefits of being able to navigate this way as a consequence.

There's a clear solution to this: allowing users to set a preference that prevents their chosen zoom level from being overridden. This is consistent with how browsers handle this, and seemingly, thePDF/UA spec. I imagine its benefits will also be appreciated by users without disabilities. 

It looks like the link service treats [zoom level for links](https://github.com/mozilla/pdf.js/blob/7812b3cfb21690858c8260ac96ad0f702d5607fd/web/pdf_link_service.js#L210) as distinct from its other actions, so it  seems possible a check could be added there to override the behaviour.

Adding a check box next to the zoom level saying something like "prevent documents from overriding this" would seem like a reasonable way forward for UI. Ideally this would persist, but even having to set per document, would be an improvement over the current situation.

**Comment by Snuffleupagus** [comment]
> Furthermore, if one then presses the back button to return, this zoom setting is retained and does not go back to the original one.

This was fixed by PR #8775, hence I'm closing this issue.

> In this PDF
> http://iopscience.iop.org/0264-9381/32/6/065001/pdf/0264-9381_32_6_065001.pdf
> clicking on a reference (e.g. [1]) changes the zoom setting (zooms in).

As explained in https://github.com/mozilla/pdf.js/issues/5736#issuecomment-74398401, this is in accordance with the PDF specification.

---

With regards to the other comments, similar discussions have already happened elsewhere (e.g. issue #5064); please keep this excerpt from [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) in mind:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by TheEarlOfEmsworth** [comment]
For users who stumble across this, to disable the overriding of current zoom settings in firefox:
Go to about:config
search for "pdfjs.ignoreDestinationZoom"
set value to true

You can also set the default pdf zoom here:
search "pdfjs.defaultZoomValue"
set value to a number without a percentage sign. This is the new default percernt zoom

You need to restart firefox for these settings to take effect

Apologies if this isn't usually the place for these comments but to support visually impaired users, I think it is beneficial to list this info here.
