### ISSUE TITLE
I love to contribute in this project :)

### ISSUE THREAD

**Issue by flik** [mozilla/pdf.js#5745]
I am exploring the project, I will update you with my effort. It is really good.

**Comment by Snuffleupagus** [comment]
It's great to hear that you wish to contribute!
However, as explained [in CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md), GitHub issues are first and foremost a bug tracker and *not* a general discussion forum.

If you need help getting started, I would advice you to contact us either through IRC or the mailing list. For details, please see https://github.com/mozilla/pdf.js#questions.

Closing, since this isn't an actual issue.
