### ISSUE TITLE
PDFJS rendering PDF as an image

### ISSUE THREAD

**Issue by nhurwitz** [mozilla/pdf.js#5761]
I'm using PDFJS with meteor.js, and when I render a small, single page document its showing up as an image. I do not get the toolbar/pdf interactivity that is show in the demos

**Comment by timvandermeij** [comment]
Could you set up a link to a web page that has the problem?

**Comment by nhurwitz** [comment]
Yeah you can find it on nhurwitz.meteor.com/resume

On Thursday, February 26, 2015, Tim van der Meij <notifications@github.com>
wrote:

> Could you set up a link to a web page that has the problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/mozilla/pdf.js/issues/5761#issuecomment-76246840>.
>


-- 
------
Noam Hurwitz
(650) 521-2562
www.nhurwitz.com

**Comment by timvandermeij** [comment]
It's because your code is actually only rendering the canvas and not showing any other HTML elements like the toolbar (check the generated page source code to verify). You've probably just used the hello world example. If you want all the other functionality (toolbar, bookmarks, scrolling, etc.) you will need the entire viewer in the `/web` folder (see https://github.com/mozilla/pdf.js/tree/master/web).

Closing as answered for now.
