### ISSUE TITLE
Annotation Support Seems Very Brittle

### ISSUE THREAD

**Issue by tcorbet** [mozilla/pdf.js#5772]
I have been following the code, as best I can, concerning the current, minimal support for annotations.  Trying to work from the simplest test case, using the annotation-tx.pdf file in /test/pdfs, that particular test works reasonably well, but I am not sure how you produced a pdf file with no real content, only an annotation.  I first tried to do something as simple as change the Helvetica text size from 12 to 14 using Adobe Acrobat X.  When I saved the file and re-ran the tests, my debugging code was no longer invoked.

So, I tried an even simpler test, merely open the pdf in Acrobat and save it back with no changes.  That, as it turns out, is enough "damage" to cause your handling of the annotation object to change.  I believe the reason is that, upon saving from a current version of Acrobat, additional attributes have been added -- attributes which cause your code to behave differently.  Or, to state it another way, I think if your original test case had been based upon a pdf with a legitimate annotation, produced by some other authoring tool than was used for annotation-tx, you would have been able to run a more meaningful test of the handling of a very basic annotation.

Elsewhere in the project I see notes indicating that your testing finds that pdf content created by using LibreOffice's export to pdf capability, results in files with content that is worrisome [complex, slow to process, presumably].  So, I am eager to help make annotation handling more robust if you can tell me what the parameters are that you have established for your test bed.

**Comment by tcorbet** [comment]
A little more work, a little more sleuthing and I see that near viewer.js [generic build] line 6216, if you conclude that the document has AcroForm/XFA content, it is unsupported.  So I suppose that since Adobe believes that Annotations are a part of the larger eco-system of Forms, as soon as a document authored by their own tools has an annotation, the metadata will cause you to stop processing.  That seems to get back to my question as to what documents, produced by what means, do you consider as being 'in scope' to the functionality you intend to support with your viewer?

**Comment by timvandermeij** [comment]
According to the PDF standard, annotations are completely separated from AcroForm/XFA content. In fact, PDF.js supports rendering some types of annotation and we have plenty of examples for that.

I agree that annotation support could be much better and more compliant with the specification (only a few types are supported now) and we are working on that: see #5585 for example.

Could you post some sample PDFs that are troublesome for you for debugging?

**Comment by tcorbet** [comment]
Thanks for getting back to me.

As I tried to explain in opening the issue, the basic test case exists in /test/pdfs/annotation-tx.pdf.

A.  Open the the viewer to that document and it will be displayed as expected.

B.  Open the annotation-tx.pdf file with Adobe Acrobat.  Since Adobe Acrobat sees it as having forms content, when you exit, you will be asked if you want to save it, even if you did not make any change, only viewed it.  Accept the Adobe Acrobat offer to save the file.

C.  Refresh your browser to redisplay the now-modified file.  In the JS console window you will find:  "Warning:  AcroForm XFA is not supported."

As I read the code -- while in no way asserting that I understand it -- that warning message from the pdfDocument.getMetadata method will have resulted in something called a fallback to UNSUPPORTED_FEATURES.  Whatever else that means, it means that a document, having the same content, will or will not pass your sanitization test as a function of what other pdf document objects may have been inserted by the particular authoring tool.

So, let me be clear.  I am not complaining about the fact that, at this time, you do not support all the features required for proper display of all types of annotations.  I am only trying to test with what, to my mind, is the simplest case of text without much ornamentation.

I am asking what authoring tool, with what self-imposed restrictions, I need to use in order to be able to create meaningful test documents that you can use to make whatever range of features you are willing to support more robust.

Terry Corbet
  ----- Original Message -----

**Comment by tcorbet** [comment]
Many hours later, I have some other ideas as to what the differences are as between the original annotation-tx file and what you get after saving it out of Acrobat. For what it is worth, I spent most of that time using as a tool the rups viewer that is part of the iText project. Later I added the use of the PDFjs.utils browser that comes from your site.

I wish I knew how it would be possible to produce annotation-tx. I was able to find no combination of comments from Adobe Acrobat that would reproduce the file that you are using as your primary test vehicle. That said, the most visible difference between the original and the version that is created by doing a save out of Acrobat is the disappearance of the NeedsAppearances property. Since I could find nowhere in your code that seems to interrogate the value of NeedsAppearance, I gave up.

The second difference, not so apparent is the addition of an AP Dictionary. Following that down through what appears to be several level of inheritance, the existence of the AP Dictionary seems to imply that the Subtype of the Annotation is /Form.  In the absence of the AP Dictionary, the inherited Subtype seems to be /Widget and I can find code that is sensitive to that piece of information.

From there, those of you who know what all of this is about can probably deduce that the act of saving the original file somehow lead to a state in which the document is supposedly being passed around with some sort of signature verification, but I certainly do not see any check boxes or drop downs in Acrobat telling me that simply viewing a pdf and saving it, without touching its contents in any way, will result in such a state of affairs.

So, again, if I can get someone to write some definitive document explaining exactly what sorts of annotations produced by which authoring tools is required to produce a document whose annotations can be handled by the presently-defined functional specification for PDFjs, it will allow me to spend some time and energy in trying to produce test cases for you.

**Comment by timvandermeij** [comment]
@tcorbet You're right. The `annotation-tx.pdf` file is actually quite weird now that I'm looking at it. Clearly it's not constructed very well, because the resave prompt from Adobe Reader/Acrobat almost always indicate that the file is corrupt in some way, shape or form.

I'll try to be a bit more precise for you. The current annotation layer code can (mostly) be found in https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js. As of now, only the types `Link`, `Text` and `Widget` are somewhat supported, but even they are not complete. On top of that, the code needs to be refactored, for which I have done an attempt in #5218, which will be split into several smaller parts including #5585 for example. I have started working on the annotation layer code some time ago because I also found that the general annotation support was very limited. I'm hoping, by making smaller-sized pull requests, to get the refactored (and more complete) code in sooner than later.

The PDF specification can be found here: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf. More precisely, in paragraph 8.4 the entire annotation layer is described: see https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=604&zoom=auto,-246,598. I have been using the specification to strive for a full implementation in #5218, but quickly realized that the patch would become too large, and therefore I'm now splitting up the work into several patches. The specification itself is not very hard to understand, but the lack of test PDFs makes it hard for us to test any implementation.

You can find all the possible annotation types here: https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=615&zoom=auto,-246,286. There are 25, so it's quite a lot to implement, but at least having test PDFs for most of them would help a lot!

My rewriting work on the annotation layer quickly made me collect a bunch of PDF files for almost every feature of the `Link` annotation type. I have uploaded them here: http://wikisend.com/download/544390/PDF.js%20annotation%20layer.zip. The goal is to make a collection of PDF files for most/each of the annotation types, so if you can help with that by creating more test cases that would be great.

Feel free to let me know if you need more information :-)
