### ISSUE TITLE
Scrolling is slow for openMagazin PDF

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#5808]
http://www.openmagazin.cz/pdf/2011/openMagazin-2011-04.pdf

**Comment by timvandermeij** [comment]
The reason for this is that we render one `<div>` per letter.

**Comment by Snuffleupagus** [comment]
> The reason for this is that we render one `<div>` per letter, even with the latest text layer patches.

I've looked into this, and it's caused by the PDF file placing a `setFont` command before *every* single `showText` command. (The generator is Scribus PDF, which seem to be able to create very inefficient PDF files, see e.g. #6961)
The good news is that it seem to be possible to, at least partially, improve the situation here. I've got a patch locally, but it's currently blocked on PR #7374.

**Comment by timvandermeij** [comment]
Closing since the file (which is no longer available on this URL, but is available in the Web Archive) now renders fine. All pages now render within a second whereas it was much more before.
