### ISSUE TITLE
Feature request: ToolTip preview of PDF links

### ISSUE THREAD

**Issue by alexshtf** [mozilla/pdf.js#5835]
I have been reading a lot of scientific papers lately, and I would like to be able to see a small popup with the linked content when I hover over a PDF link. Usually, when there is a link to an equation of a theorem I don't want to go there, I just want a short reminder and continue reading. I believe that many people who read scientific papers would benefit.

It is something similar to Visual Studio's Peek Definition feature (http://channel9.msdn.com/Series/Visual-Studio-2012-Premium-and-Ultimate-Overview/Peek-Definition)

**Comment by mbbaig** [comment]
Hi. I'd like to work on this feature for pdf.js. 

However, I'm not overly familiar with the code base or API.

Does the API have the functionality to have an iframe load a URL?
I  guess I'm wondering what is a good starting place for this?

**Comment by timvandermeij** [comment]
There is nothing in PDF.js so far to help with this feature. I think this would have to be implemented from scratch. Each link is an annotation of type `Link`, so perhaps you could add an iframe on hover, much like how the `Text` annotations work. However, I think an iframe is not the best solution, both for security and usability. An image render would be much better, but I'm not sure how easy or difficult that is to implement.

**Comment by mbbaig** [comment]
Could the following js library be used to accomplish this?
[rasterizeHTML.js](https://github.com/cburgmer/rasterizeHTML.js/wiki/API)

**Comment by timvandermeij** [comment]
That looks like a better solution to me, yes.

**Comment by yurydelendik** [comment]
There are internal links, that point to some destination inside the same PDF, and external. I think the latter shall not have a preview (and act like a hyperlink on a regular web page). Internal link point to some place on a PDF page -- the PDF.js render capabilities can be used to generate the required preview.

**Comment by mbbaig** [comment]
How does PDF.js differenctiate between internal and external links?
Would I modify the link annotations to achieve this from within PDF.js itself?
If not than which file would I look at?

**Comment by mbbaig** [comment]
Okay so inpecting a page loaded with a PDF that has both link types, I saw that it uses the 
```
annotLink
```
class to specify a link and the 
```
internalLink
```
class to differentiate between the links types.

So I'm thinking that I should have a toggle avalaibel to enable preview on hover and then create a PDFPreviewer like the ```var PDFViewerApplication``` in the viewer.js.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Snuffleupagus** [comment]
I'd suggest closing this as WONTFIX, for a number of reasons:
 - Creating a preview would be just as expensive as rendering a page/thumbnail, since there's no concept of "previews" in PDF files, and it would thus be generally impossible to immediately display the preview (it could simply take arbitrarily long).
 - Having rendering starting/stopping when the user moves the mouse over/from links would waste resources better spent on pre-rendering actual pages.
 - Unless the destination is of the `FitR` type, which aren't very common in practice, rendering only the relevant section is basically impossible and the only thing that could be done is to display a preview of the *entire* page (which I assume would be quite pointless here).
 - It would require quite a bit of implementation effort, and as mentioned above wouldn't even work very well in general, for something that is arguable a *very* specialized use-case.
 - Given the browsing history implementation in the default viewer, it should be easy to go back to the previous position after a link has been clicked (used e.g. the native "back"-button of the browser).

**Comment by haichaoyu** [comment]
Hi @Snuffleupagus , thanks for your explanation. I am also very interested in this feature but I am only interested in previewing hyperlinks for bibliography. Could you please give some hints if I would like to implement this via Chrome Extension?

**Comment by maxsu** [comment]
This would be a valuable feature for an implementation of PDF.js that is specialized for science papers.
@mbbaig, @haichaoyu  - wanna brainstorm about this?

I think a simple tooltip, like [Tooltip.js](https://popper.js.org/tooltip-examples.html) would not be horrible for performance sake. However, I think that already the features discussed are out of scope of a general pdf reader, and we may want to take the discussion to a more specialized context.

Allow me to propose some cope creep: only a small minority of science papers have internal links for their in-body citations (let alone cross-references). A more broadly applicable solution would parse in text citations and let us "peek" at their associated bibliography items. I'd like to propose that as a parallel goal. Luckily there are tools and services that do this (see Resources, below). For inspiration, I think we can look at [Readcube](https://www.readcube.com/home), a proprietary science paper reader that decorates papers with mouse over bibliographic tooltips.

### Components it'd need (scope creep labeled with*):
Note: 'links' refer to hyperlinks (with either internal or external target) present in the pdf, while 'references' are in-text citations of bibliography items, or cross-references to footnotes, tables, figures, and so on.

1. Citation context detector: Detect links and references* in the document
2. Target data extractor: Pull relevant materials from link targets; text from footnotes, bibliography reference strings, and external pages; do the same for references*
     - Bibliography string parsing: title, year, author, journal, etc
     - Citation matching: Match reference strings to external paper links, get abstracts, etc
     - External link preview: Extract title & snippet from external pages
4. Preview formatter: Format and style extracted data 
3. Tooltip: Display preview text as a popup
4. PDF Enhancer: Add tooltips to detected links and references*

### Resources 

Extraction tools like Crossref's [pdfextract](https://www.crossref.org/labs/pdfextract/)(retired, [Cermine](http://cermine.ceon.pl/cermine/about.html), [Grobid](https://github.com/kermitt2/grobid) or Zotero's [Recognizer Server](https://github.com/zotero/recognizer-server) - would help identify and extract relevant text from bibliographic entities and in text references. 
- Cermine extracts bibliography data and annotates in text references with with the [<xref> tags](https://gist.github.com/maxsu/12526698325b22beaa035db93f3be8ab#file-nlm-xml-L98) - not. 
- Papers like [this one](http://faculty.pucit.edu.pk/swjaffry/rpr/Scientometrics18InformationMining.pdf) point to a ton of work in this area, including newer deep learning methods (now part of Grobid!).

Citation matching tools like [EXmatcher](https://github.com/exciteproject/EXmatcher) would let tooltips present external paper links, citation metrics, and abstracts.

[pdf.js-hypothes.is](https://github.com/hypothesis/pdf.js-hypothes.is) - pdf.js distribution that supports collaborative research annotation. Perhaps a good jumping off point. They [need help](https://github.com/hypothesis/pdf.js-hypothes.is/issues/15)!

Other suggestions and input welcome! This issue is almost certainly the wrong place to discuss this - feel free to reach out to me or suggest a new forum :)

**Comment by echebbi** [comment]
@maxsu @haichaoyu I would also be very interested in such a feature; did you discuss it further?

**Comment by YijunYuan** [comment]
I think [this](https://github.com/belinghy/PDFRefPreview) is a temporary solution.
