### ISSUE TITLE
IE11 is very slow for displaying this PDF

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#5841]
IE11(Windows 8.1) is very slow for displaying the following PDF:
https://www.nttdocomo.co.jp/binary/pdf/support/trouble/manual/download/f883ies/F883iES_J_01.pdf

In my PC the first page appears only after about two minutes. No errors in the console. 
Both Firefox and Google Chrome show no problem, and load it immediately.

PDF.js: 1.0.1207

**Comment by Snuffleupagus** [comment]
Please note that IE11 is really old, and haven't received meaningful updates/improvements in a couple of years. Besides, it's general JavaScript performance was never great to begin with, a problem that's further compounded by its lack of support for *many* modern JavaScript features which thus requires polyfills (which are slower than native code).

One possible explanation, besides general slowness of the browser itself, is that the amount of asynchronous code in PDF.js is difficult for IE11 to handle. However, the PDF.js code has/will only become *more* async over time (also the case with many other JavaScript applications), so there's nothing that can be done here.

This issue is essentially asking for PDF.js developers/contributors to *somehow* improve the general JavaScript performance of the IE11 browser *itself*, which is obviously not possible unfortunately; hence closing this as INVALID seems like the appropriate resolution here.
