### ISSUE TITLE
Can i update the html before it goes for print?

### ISSUE THREAD

**Issue by saurabhgarg2405** [mozilla/pdf.js#5860]
i want to update the generated html from pdf before it goes for print. 
My issue is: i have to update a comment section in pdf before it goes for print. in beforeprint event i am able to access the div containing the comment section and updated the html there but it is not reflected on print preview.

Or suggest me some other library for same.

Please help me

**Comment by timvandermeij** [comment]
The page itself is rendered on a canvas, so I can only assume that you update the text layer. However, since that is not printed, you will not see any effect. PDF.js is only a PDF renderer, not an editor, so a solution for your problem would have to be implemented in a custom fork and it out of scope for this project.
