### ISSUE TITLE
PDF Viewer - A confusing name

### ISSUE THREAD

**Issue by davidhedlund** [mozilla/pdf.js#5865]
"PDF Viewer" is the main title in https://addons.mozilla.org/en-US/firefox/addon/pdfjs/ but its better known as PDF.js.

**Comment by Snuffleupagus** [comment]
`PDF Viewer` is the name used for the Firefox version of PDF.js. Furthermore we're in the process of deprecating the [AMO addon](https://addons.mozilla.org/en-US/firefox/addon/pdfjs/), since PDF.js is already included by default in Firefox, and because the AMO addon adds unnecessary support burden.

Hence I don't think it really makes sense to update the description, especially since the AMO addon is not compatible with the current version of Firefox (and it's also changed to preliminary review status, to reduce its visibility in e.g. search results).

Closing as invalid.
