### ISSUE TITLE
Odd pdf rendering issue

### ISSUE THREAD

**Issue by efitz** [mozilla/pdf.js#5985]
This pdf has odd rendering artifacts:
![image](https://cloud.githubusercontent.com/assets/831801/7482498/e171ed9a-f345-11e4-8163-28905f07dd1a.png)

However, when viewing the pdf in a native reader like Apple preview of adobe, the issues are not present: https://www.dropbox.com/s/ga4dxeidr3xb48l/15-140%20%281%29.pdf?dl=0

**Comment by timvandermeij** [comment]
Works perfectly fine for me. Could you open the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) and see if it is also reproduced there?

**Comment by efitz** [comment]
Interesting....you are right...works fine using the hosted viewer you shared: 
![image](https://cloud.githubusercontent.com/assets/831801/7497983/a7ccdbda-f3eb-11e4-91d9-4ee1f93dcdcb.png)

We must be using an older version? Any other ideas as to why we might be seeing something different in our implementation?

**Comment by timvandermeij** [comment]
Most likely this has been fixed in a recent patch (not sure which one exactly; you would have to bisect the commits to find out). Indeed the one I linked to is the most recent viewer, so yes, your implementation probably uses an older version of PDF.js and you should update that to address the issue.

Closing as resolved.
