### ISSUE TITLE
"Load test font never loaded" in Internet Explorer can be fixed by enabling 'Font Download'.

### ISSUE THREAD

**Issue by holloway** [mozilla/pdf.js#6018]
Internet Explorer's Security Zones can prevent pdf.js from rendering custom fonts. Certain letters (especially ligatures, perhaps because there's no fallback) will be hidden completely, and kerning is really narrow making documents almost unreadable.

The only warning comes from `src/display/font_loader.js:217` which does a `warn('Load test font never loaded.');`

For an Internet Explorer user to fix this they have to enable fonts in their Security Zone; they must have 'Downloads / Font Download' enabled.

I suggest amending this warning to give a potential solution to the problem. E.g. `warn('Load test font never loaded. In Internet Explorer ensure Security Zone\'s Font Download feature is enabled.');`

Unfortunately the only documents that exhibit this behaviour are confidential so I can't share them. I'll try to make a test case and I'll update this ticket if this is needed.

**Comment by timvandermeij** [comment]
A test case is always good to have; thank you.

**Comment by Lord-of-Darkness** [comment]
Desarrolladores y líderes de Mozilla, que son travestis culo!

Alguien debe colgar ustedes para arriba en sus propias bolas y dejar que su perro muerda su caricatura de una polla!

Posteriormente deben ponerlo tiempo que sea necesario por la garganta hasta que traga a sí mismos en el suicidio!

Ustedes Mozilla está ... Estúpido de mierda coños!
--------------------------------------------------------
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Developers and leaders of Mozilla, which are shemales ass!

Someone should hang you up in your own balls and let your dog bite his caricature of a cock!

They should then put it long as needed by the throat until he swallows themselves in suicide!

You Mozilla is... Stupid fucking pussies!
.....................................................
You can lick my penis and my golden eggs and kiss my ass son of a bitch with a personality disorder from the depths of the abyss of hell from the abysses of Mozilla!

Fuck you and your mother you autistic son of a bitch, you will lick Putin eggs, fascist fucking faggot!

The shit out of your dog, your cat and your dirty faggot asshole mountain goat!

Suck cocks Mozilla and together go and suck Google ass full of shit!

Shit in your knee you cock suckers! And that damn Australis Chrome clone of shit! Mozilla gay homosexual lesbian fucking bastards from hell!
....................................
Do you love the pain that you do? And to do a favour... I'm going to do that!

I kicked her so hard failure golden eggs until they are ringing and sing you all the melodies of forward and back pain in an instant! I am the boy Nutcracker who cracks your are crazy nutheads!

And now go to the stupid shit shit cones!
....................................................................
Was it expected?

Oh, Yes, that was!

A movement such as the Mozilla!

So happy that I never upgraded to Firefox 29 and beyond!

Let me tell you something Mozilla developers! If I would be still using your latest crap-ware that really my mission would at this time to find out where you live and then drill him often in Golden's failure until you analyzes and understands how to threaten power users in the correct way!

Without a doubt, has been said before - but may not be repeated enough... You are...

Stupid cones!

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by Lord-of-Darkness** [comment]
Mozilla team! You betray the spirit of code open and another time! Fortunately, more and more people are realizing that kind of hypocrites you are!

You are never going to be the number one in the browser market! Stop thinking you could be a leader, never exceed Chrome! So stop running behind Google and again focus on geeks and power users, bring personalization back, stop adding more "Chrome parity"! Add place better "Vivaldi parity"-not from the development team, you can learn how users should be treated! With respect and with the aim of satisfying your needs instead of fleeing as it operates and betray its user base kernel and other time and again and again...

You is the Mozilla developers have a brain at all, or are you just treacherous opportunists in Google Paylist? Australis is an imitation without value of Google user interface - you betray your Open Source origins with the addition of DRM and ads... well, another step to sell, the same as add mess owner as of Pocket!

You're traitors to all related open source! Shame on you and your developers for Mozilla "out of this world" "leaders" with less than half of a brain!

I only say vivaldi.com - palemoon.org - otter-browser.org or seamonkey-project.org

**Comment by holloway** [comment]
Here are some screenshots showing the problem. As said, it doesn't seem like PDF.js could fix this because it's about browser settings, but it could give a better error message to help users fix the problem themselves. Thanks

![security-zone-fonts-disabled](https://cloud.githubusercontent.com/assets/620580/7672348/9cbddf80-fd43-11e4-8a90-a5e2e11d88c2.png)
![security-zone-fonts-disabled-settings](https://cloud.githubusercontent.com/assets/620580/7672349/9d01f6de-fd43-11e4-9d46-f9c2ad3e8668.png)
![security-zone-fonts-enabled](https://cloud.githubusercontent.com/assets/620580/7672350/9d047918-fd43-11e4-81cf-8d0d6b2ffb67.png)

**Comment by timvandermeij** [comment]
I think that would be fine. Could you submit a pull request for that?

**Comment by Snuffleupagus** [comment]
Given that this would introduce a browser specific "compatibility hack" in code residing in the `/src` folder, which is something we always try to avoid, I'm not sure if such a modification is a great idea.
If instead an additional `warn` is added, enclosed in `GENERIC` preprocessor tags, that *might* be slightly more acceptable.

As outlined in the [Required Browser Features](https://github.com/mozilla/pdf.js/wiki/Required-Browser-Features) (linked from the [FAQ](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support)), which can be tested using http://mozilla.github.io/pdf.js/features/, `@font-face` support is required for PDF.js to work properly. Against that background, I'm not convinced that an IE specific warning is necessary.

**Comment by yurydelendik** [comment]
> I suggest amending this warning to give a potential solution to the problem. E.g. warn('Load test font never loaded. In Internet Explorer ensure Security Zone\'s Font Download feature is enabled.');

Other browsers has similar options to disable document fonts, e.g. Firefox. So by adding Internet Explorer, we shall add Firefox and probably other browsers hints as well.

**Comment by yurydelendik** [comment]
Please notice there are other workaround for that: PDFJS.disableFontFace. Custom solutions may use that setting. The generic viewer will not test for that to avoid initial delay during rendering.

**Comment by holloway** [comment]
These are all good points.

My concern is only that people can know how to fix the problem. "Load test font never loaded" is the only feedback if fonts are disabled, and that's not particularly clear. It doesn't even clearly say that the browser has custom fonts disabled.

Could we perhaps add a section to the FAQ with that error message, and some browser-specific suggestions there, so that web searches for "Load test font never loaded" would turn up something useful. Currently all that turns up (in my google search) is the unrelated #3502.

**Comment by timvandermeij** [comment]
Closing IE11/Edge (non-Chromium-based) issues in response to #11211. Please note that, as outlined in https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, only bugs which completely prevent the library and/or the default viewer from running will be accepted.
