### ISSUE TITLE
PDF won't load in 1.1.114

### ISSUE THREAD

**Issue by rcocks** [mozilla/pdf.js#6029]
I have a PDF file which opens fine in PDFJS version 1.0.1040 (Firefox default) but when opening the same file in PDFJS version 1.1.114 (FIrefox Developer edition default) hits an error:
    
    pdf.js:1206
    DataCloneError: The object could not be cloned.

I'll try to see if I can get permission (it may be company confidential) to post the actual file, but if I can't then is there any other way I can debug this error?

**Comment by Snuffleupagus** [comment]
First of all, please check that this issue is present in the *latest* version of PDF.js (as of this writing, that version is `1.1.147`).
To do so, please open your file with the demo viewer (by clicking on the "Open File" button on the right-hand side of the toolbar): http://mozilla.github.io/pdf.js/web/viewer.html.

If the issue is still present there, the easiest way is obviously to make the PDF file available to us. (If you created the PDF file yourself, try to create a reduced test-case exhibiting the issue, but without any sensitive content.)
Another option that will help, is if you can try to bisect where it broke, see https://github.com/mozilla/pdf.js/wiki/Bisecting-a-Regression. But please note that we'll still need a test-case in order to fix the issue.

**Comment by rcocks** [comment]
Hi,

The file opened successfully with the demo-viewer online in 1.1.147.

Thanks,
Rich
