### ISSUE TITLE
Render "jumped" when scroll up and down in viewer.html at android phone

### ISSUE THREAD

**Issue by futurist** [mozilla/pdf.js#6075]
After testing in android+SafariMobile,  when scroll up or down, viewer.html rendered jumping, or to say, the frame rendering behind my touch up event. So the display jumped.

It's not good experience in mobile. 

Plus, need punch in and out gesture to get the PDF zoom in and out, and minimum the UI will be better.

**Comment by timvandermeij** [comment]
Pinch to zoom is tracked in #2582. I do not experience that jumping effect on my Nexus 6 (Android) too much. It's probably related to performance issues during rendering. We have been talking about creating a separate Android/mobile viewer that would make the experience on mobile devices a lot better, but work has not started on that yet as far as I know. Since there are no concrete points to fix here, other than improving the general performance of PDF.js and creating a separate Android viewer, and the pinch to zoom issue is already tracked elsewhere I'm closing this issue.
