### ISSUE TITLE
spacebar does not scroll down

### ISSUE THREAD

**Issue by kodabb** [mozilla/pdf.js#6098]
You can move in a pdf using up and down keys, but pressing space will result in nothing happening.
Ideally a spacebar keypress results in a step to the next space while a shift+spacebar in a step back.

**Comment by Snuffleupagus** [comment]
As outlined in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, especially the *first* paragraph, please provide information about your configuration! Quoting from that link:
> [...] and provide more details about the issue: [...] browser version, operating system, PDF.js version and JavaScript console warning/error messages. Issues that do not have enough details provided will be closed as invalid/incomplete.

**Comment by kodabb** [comment]
Sorry about that, here it is

 * Build identifier: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.9; rv:38.0) Gecko/20100101 Firefox/38.0
 * OS: MacBookPro11,3 Mac OS X 10.9.5
 * Version: PDF Viewer 1.1.191

**Comment by Snuffleupagus** [comment]
Based on the information provided, this is the following upstream bug: https://bugzilla.mozilla.org/show_bug.cgi?id=915962. Please note that it's already fixed, and that the patch will be in Firefox 40.

Since the issue is not a PDF.js bug, but rather an (already fixed) upstream bug, this unfortunately means that there's not much we can do here; hence why I'm closing this issue.

**Comment by kodabb** [comment]
thanks for the triaging
