### ISSUE TITLE
some words overlap in maxthon browser but display correctly in chrome.

### ISSUE THREAD

**Issue by MCaveMan** [mozilla/pdf.js#6102]
the link of the file:
http://7sbrob.com1.z0.glb.clouddn.com/error_pdf_20150609

the version of pdf.js v1.1.1

version:
chrome: 41.0.2272.89 (64-bit)
maxthon: 36.0.1
maxthon link address: http://www.maxthon.cn/

OS:
Ubuntu 1404

some words overlap in maxthon browser
![aoyou_error](https://cloud.githubusercontent.com/assets/1560027/8079968/f50a7e96-0f9a-11e5-8a55-ca77de9eec48.png)

screenshot: chrome compare with maxthon browser.
![chrome_normal](https://cloud.githubusercontent.com/assets/1560027/8079973/047c9ce2-0f9b-11e5-8fbe-a6072aca1f8d.png)

**Comment by timvandermeij** [comment]
Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if using the latest version of PDF.js resolves the issue?

**Comment by yurydelendik** [comment]
Maxthon is not supported browser, however based on http://en.wikipedia.org/wiki/Maxthon: "Since the release of version 3, Maxthon supports both the Trident and the WebKit rendering engines". Hard to tell which version of WebKit or Trident it's using. Probably outdated -- we had a similar issue with chrome long ago, e.g. #4017.

**Comment by timvandermeij** [comment]
From the screenshots it looks like a custom, likely outdated version. Closing as invalid until more information is provided (such as using the viewer URL posted above).
