### ISSUE TITLE
Letter too bold

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#6117]
This is a regression from PR #4615. The letter "F" on page 6 is unreadable.

URL: http://chrishecker.com/images/3/33/Gdmogl.pdf
1.1.209: https://i.imgur.com/IobYdDE.png
0.8.990: https://i.imgur.com/s188qBb.png

fc1e2483b433134a538cce0acd0ccc76e335cf5f is the first bad commit
commit fc1e2483b433134a538cce0acd0ccc76e335cf5f
Author: Jonas Jenwald
Date:   Fri Apr 11 20:19:39 2014 +0200

    Enforce minimum line widths

**Comment by Snuffleupagus** [comment]
In order to try avoiding drawing too thin, and thus nearly invisible, lines we use the [`getSinglePixelWidth`](https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L2126) method. Since this is a heavy operation, we attempt to cache the result (in `cachedGetSinglePixelWidth`) in order to speed this up the rendering of PDF files with *lots* of drawing operations (e.g. maps).

We are currently invalidating that cache in some circumstances (currently on `restore` and `transform`), to avoid incorrect rendering. However, judging by this issue, it seems that we might simply not be invalidating the cache in *every* case that we actually should.

**Comment by timvandermeij** [comment]
@automatedbugreportingfacility Thanks again for the high quality bug reports! Usually we are able to fix mentioned regressions quickly because of that.

**Comment by automatedbugreportingfacility** [comment]
No problem, thank you for taking your time to fix these issues and keep pdf.js moving forward despite Mozilla pulling resources towards other projects.
