### ISSUE TITLE
Search is not working when I load a single page

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#6119]
Hi This problem is critical.
I am rendering only one page on browser for next/previous clicks, initially i have loaded all the pages and made the viewer null and loaded required page.Please, suggest anything to do.I have modified viewer.js.

**Comment by timvandermeij** [comment]
We really need a working demo to be able to look into the issue. Please put one up online, for example on JSBin on a domain of your own.

**Comment by gsampath127** [comment]
Hi TIm , Thank you!!
I cant share the url for you  as i am working for client.Please follow through following code changes for loading a single page . I have made changes for viewer.js (stable version 1.1.1).
Here ATTPAGENO is global variable declared as   var ATTPAGENO = 1;
1.Changes in setDocument function for loading document.
![load](https://cloud.githubusercontent.com/assets/12858790/8203235/f8199b7c-14fd-11e5-849c-40b445d7ece1.PNG)
2.Changes for navigating between pages.
![click](https://cloud.githubusercontent.com/assets/12858790/8203248/11b59dec-14fe-11e5-8e39-29721b72a43c.PNG)

**Comment by gsampath127** [comment]
sorry!! the first image is not proper sending again.
Hope u will help me.
![load1](https://cloud.githubusercontent.com/assets/12858790/8203387/09de1634-14ff-11e5-9a65-d9a55c64395d.PNG)

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. In this case the *fourth* paragraph is most relevant, and I'm quoting it here:
> If you are developing a custom solution, first check the examples at https://github.com/mozilla/pdf.js#learning and search existing issues. If this does not help, please prepare a short well-documented example that demonstrates the problem and make it accessible online on your website, JS Bin, GitHub, etc. before opening a new issue or contacting us on the IRC channel -- **keep in mind that just code snippets won't help us troubleshoot the problem.**

Since it seems like you're modifying the default viewer, you're most likely going to have to modify/rewrite part of the find functionality as well, since it currently depends on being able to access the entire document. That kind of modification would most likely be out of scope for the default PDF.js viewer.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
