### ISSUE TITLE
Figure number text not rendering properly with latest stable release v1.1.3.

### ISSUE THREAD

**Issue by ztraboo** [mozilla/pdf.js#6130]
I uploaded the _Module_5.pdf_ to http://mozilla.github.io/pdf.js/web/viewer.html to test to see if the figure text would render properly.  It does not.  Please look into this issue and let me know what can be done.

Download the following files here:
https://cwd-cloud.ces.clemson.edu:5001/fbsharing/ZpHfHVfr
- Error with Figures 2015-06-18_9-20-13.png - shows error with Figure numbers not rendering properly.
- Module_5.pdf - sample pdf to test with.

**Comment by Snuffleupagus** [comment]
*A few quick observations:*
This isn't actually font related, but rather an issue with the ColorSpace/Pattern handling. The text *is* rendered, but using the wrong color, thus making it virtually invisible.

**Comment by ztraboo** [comment]
I noticed that when I changed the text to different color.  How can we recognize what colors won't be invisible?

**Comment by ztraboo** [comment]
@Snuffleupagus,
I noticed that you referenced #3988?  Do I need to wait until that issue is resolved to fix my issue?  Also can you answer my questions that I posted https://github.com/mozilla/pdf.js/issues/6130#issuecomment-113173901?

**Comment by Snuffleupagus** [comment]
> Do I need to wait until that issue is resolved to fix my issue?

Since all three issues appears to be similar, there's a *chance* the fixing one will fix all of them at the same time. (The comment was merely intended to help us keep track of potential duplicates.)

> Also can you answer my questions that I posted #6130 (comment)?

Unfortunately I don't really have any good answers, and I don't know that much about PDF generation in general, hence why I didn't comment. But I'll do my best anyway, please see below.

> How can we recognize what colors won't be invisible? What is the best RGB ColorSpace to use?

Generally speaking, I don't know. But in this particular case it appears that PDF.js currently has some, fairly severe, issues when it comes to rendering text that should be drawn use `Pattern` Colour Spaces.

> Any suggestions on how to make it look like *Figure 6.* since that's a good example.

That particular piece of text is *not* using a `Pattern` Colour Space, so using the *same* Colour Space for all `Figure nn.` text might work.

> Figure 3. Germanium is a good example of a pixelated text issue.

That is *not* a PDF.js issue, since it looks fine in Firefox. However it's broken in Chrome, meaning that it's a canvas related rendering bug in the browser, which we unfortunately cannot fix.

> Does PDF JS have a guide(s), that the designer can follow, when exporting PDFs from packages like InDesign?

Apart from a couple of general pointers, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize, I'm not aware of any guides specifically targeting certain programs/tool-chains.

**Comment by ztraboo** [comment]
Thanks for the help.  I passed the info off to the designer.
