### ISSUE TITLE
pdf.js modifies XMLHttpRequest.response, breaking other JS that wants blobs

### ISSUE THREAD

**Issue by samterrell** [mozilla/pdf.js#6167]
If you load pdf.js on the same page as code like this:
```javascript
var xhr = new XMLHttpRequest();
xhr.open('GET', 'binary.jpg', true);
xhr.responseType = 'blob';
xhr.onload = function(e) {
  console.log(xhr.response);
};
xhr.send();
```
You won't get a Blob as you would expect. This is the offending line:
https://github.com/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/web/compatibility.js#L199

**Comment by yurydelendik** [comment]
> You won't get a Blob as you would expect. 

Will you get 'blob' on the affected browser is you will not use pdf.js?

**Comment by samterrell** [comment]
Yes. I don't think there is anyway you get a blob with that code in there, though. It always pulls from responseText. The issue it was causing for me was that it was converting bytes > 0x7F into UTF-8 sequences, because it was doing text processing on it.

Browser was Chrome on a Mac (but will probably do the same thing everywhere). I was able to restore functionality by inserting `delete xhr.response` to remove the property from my xhr object.

**Comment by yurydelendik** [comment]
I don't understand how it's related Chrome code shall not reach this line due to https://github.com/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/web/compatibility.js#L163 (at least for me)... unless you have really old version of Chrome.

Please provide more information about your environment including link to the sample code that demonstrates the issue. See also https://github.com/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/CONTRIBUTING.md

**Comment by samterrell** [comment]
Closing this, because I updated pdf.js and the problem went away. I think we got a bum version of pdf.js from somewhere. I'm trying to track it down. It wasn't the tagged version on here, even, so I'm thinking someone grabbed it from a something else that redistributes pdf.js and it was broken there.

Thanks for taking your time and the awesome work you guys have done!
