### ISSUE TITLE
scrambled garbage

### ISSUE THREAD

**Issue by jazcam** [mozilla/pdf.js#6174]
What's this about?
pdf created in fpdf.
Chrome native viewer:
![chrome](https://cloud.githubusercontent.com/assets/13166997/8500572/14b150ec-2163-11e5-8864-24b4dc25cf41.jpg)

same file with pdf viewer enabled:
![pdf](https://cloud.githubusercontent.com/assets/13166997/8500583/2e5426d2-2163-11e5-8b95-d54d2aeb6c92.jpg)

The file is created in FPDF from content stored in a MySQL database.  The OS is Linux Mint 17.  The file opens correctly in Adobe, or the Chrome native viewer, and in Firefox with its default viewer.

**Comment by Snuffleupagus** [comment]
@jazcam As outlined in https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, please provide a link to the PDF file.

If the file isn't available online, please upload it to a file sharing service (e.g. Dropbox, Google Drive, Microsoft OneDrive, or similar), and paste a link to it here.

**Comment by jazcam** [comment]
The file is created dynamically, however, I did save the file, which worked fine.
asbs.ddns.net/insite/pdf/report.pdf

**Comment by timvandermeij** [comment]
Works fine for me on Windows 7 x64. Renders just like the Chrome viewer. Could you try opening the file with https://mozilla.github.io/pdf.js/web/viewer.html (Open File button in the toolbar) to see if the problem remains?

**Comment by jazcam** [comment]
It seems that saving or opening a file is not a problem.  Try this:
1.navigate to http://asbs.ddns.net/insite/Login.html
2.login as joe/joe.
3.from the content page click on "Reports"
4.from Reports.php simply click on the Submit button

The data in the program is simply test data anyway, so there is no sensitive data there to expose.  I'll leave these login credentials as is until you've had a chance to either give it a test, confirm, or otherwise what I'm seeing.  Works OK in Firefox, and I think in IE 11 with Adobe.  It could be that it's only the dynamically generated pdf that is problematic (for me anyway).  I have other FPDF files that are also dynamically created, but are first saved to disk then opened.  They work just fine in pdf.js.  It is this one file that is not saved to disk that is the problem child.

BTW, I'm using Chrome version 43.0.2357.130 (64-bit).

**Comment by timvandermeij** [comment]
The URL you linked to is not reachable anymore for me. The Chrome debugger warning has been resolved a few days ago by #5531.

**Comment by jazcam** [comment]
You might know, I had the server down at that time of day.  Ok, I'll check out 5531.  It's back online now if you're shooting firecrackers somewhere.

**Comment by timvandermeij** [comment]
I have checked your steps and even with those steps this renders fine for me using the development version of PDF.js. Maybe @Rob--W is able to reproduce this in Chrome?

**Comment by Snuffleupagus** [comment]
Following the steps described in https://github.com/mozilla/pdf.js/issues/6174#issuecomment-118436226, I get the following results when testing on *Windows 7*:
 - Works fine, using Firefox Nightly 42 (buildID: 20150703030216), with PDF.js 1.1.248.

 - Broken, in the same way as the screen-shot in https://github.com/mozilla/pdf.js/issues/6174#issue-92885106, using Google Chrome `44.0.2403.61 beta-m`, with PDF.js 1.1.132.

**Comment by Rob--W** [comment]
Reproduced, this is specific to the Chrome extension.

What happens is:

1. After submitting the POST form, the server replied with the PDF data
2. The PDF.js Chrome extension ignores the PDF file, because it cannot access the response data yet for the lack of support from Chrome extension APIs (#4483).
3. Chrome recognizes the response as PDF, and replaces the document with an `<embed>` element, with the src set to the URL of the POST target.
4. PDF.js recognizes the `<embed type="application/pdf">` element, and decides to load the PDF using PDF.js. This is a GET request, not a POST request, which causes your server to reply with unexpected data.

There are a few ways to address this problem:

1. From PDF.js side: Detect this scenario, and don't try to intercept the PDF. Then if the browser (e.g. Google Chrome) can display PDFs by other means, then the PDF from the POST request will be displayed.
2. From your side (as the dev behind the website): Do not reply with PDF data after a POST request. Instead, perform a 302 redirect to a (temporary) URL containing the PDF data. Or use the GET method for your form instead of POST.

**Comment by jazcam** [comment]
My workaround was to change the output of the pdf to a file, by changing
$pdf->output()  to  $pdf->output($outputName"), effectively saving the file to disk, where $outputName = directory + file name.  On the same form is now a button that says "test Report" that calls the js function to drive the fpdf script.  It's slower, but not garbage.

**Comment by jazcam** [comment]
If any of the collaborators need access again to the site, just drop me a note or comment and I'll re-establish the connection and update the url.  Thanks to all.

**Comment by Rob--W** [comment]
@jazcam Thanks for your willingness to help! The site is no longer needed, because I had already created and hosted a minimal test case at https://robwu.nl/pdfjs/issue6174.
