### ISSUE TITLE
Strange annotation borders after PR 5585

### ISSUE THREAD

**Issue by Snuffleupagus** [mozilla/pdf.js#6179]
In http://tug.ctan.org/tex-archive/macros/latex/contrib/pdfcomment/doc/pdfcomment.pdf#page=6 (note that the issue is present in the entire file), most of the annotations now have a coloured border, which they didn't have prior to PR #5585. *Please refer to the screen-shot below.*

Interestingly enough, when comparing the border colours to the rendering in Adobe Reader, it appears that the borders are rendered with the colours that the actual annotations *should* have.

I'm tentatively marking this as a regression from #5585, since there shouldn't be any borders visible.
/cc @timvandermeij 

---
![borders](https://cloud.githubusercontent.com/assets/2692120/8520761/b0aa87ee-23dd-11e5-94f0-fbd583112a3d.png)

---

![borders_reader](https://cloud.githubusercontent.com/assets/2692120/8520933/5a963626-23df-11e5-926d-adb4f7b1272a.png)

**Comment by timvandermeij** [comment]
From the specification:

"If neither the Border nor the BS entry is present, the border is drawn as a solid line with a width of 1 point."

In this case, all annotations lack a Border and a BS entry, so I think the functionality in my PR is actually the right one according to the spec. Since it is not the first time that Adobe Reader violates its own spec, I will create a patch that does not draw the border when no Border or BS dictionaries are available.

**Comment by CodingFabian** [comment]
@timvandermeij maybe in that case they did implement the border but had set the color to transparent? I think we came to the conclusion that transparent would be the logical case but adobe in the other case decided to make them black....

**Comment by timvandermeij** [comment]
That is also a possibility, but the specification unfortunately says nothing about this, so there is no way to tell for sure. With the merged patch above we now have the same display as Adobe Reader, so we should be good now, even though the specification should have been more clear about this.
