### ISSUE TITLE
Implement `advanceWidth` on fonts

### ISSUE THREAD

**Issue by jviereck** [mozilla/pdf.js#624]
Some times back I had a discussion with @vingtetun how we can get arround painting each character on its own which is slow. The reason we introduced this was, that on FF some characters had too much width compared to the actually width it should have (that was also defined in the font).

The idea was to implement the `advanceWidth` section on the fonts, which hopefully fixes this on FF.

@vingtetun, @notmasteryet, can someone of you maybe take a look at this or give me a pointer how to implement it myself? I have very little knowledge about the font code and how font processing works in general :/

**Comment by brendandahl** [comment]
I'd forgotten about this old issue, but quite awhile ago I looked into this. My initial experiment was just trying to draw all the text on one line at once and not care if we didn't get the advance correct. The initial rendering times showed no difference. Re-rendering of the same page was slightly faster since firefox was caching text runs, but still it wasn't much of an improvement.
