### ISSUE TITLE
Text selection is fragmented and sometimes in wrong place

### ISSUE THREAD

**Issue by sethnk** [mozilla/pdf.js#6244]
Using latest version  1.1.326

PDF is here: http://seth.redirectme.net/med/pdf/55ae6862e6b60.pdf

Scroll to the second page and select the text as shown in the screenshot.  The text is scattered in places.  The problem occurs throughout the PDF.  It works correctly in Acrobat

![image](https://cloud.githubusercontent.com/assets/10129039/8815111/8fa3f950-300c-11e5-82f2-22269354a803.png)

**Comment by sethnk** [comment]
using Chrome 43.0.2357.134 m

**Comment by Thunderforge** [comment]
I found that if you select the text as shown in the screenshot, you see the following:

    OLs were derived [
    13
    ].
    We further observed that CD8
    +
    T cells lines, speci
    fi
    -
    cally reactive with MBP peptide 110
    –
    118 which sits in
    the HLA-A2 groove [
    14
    ], were cytotoxic to HLA-A2
    but not to non-HLA-A2 cultured human OLs, even in
    the absence of exogenous peptide [
    15
    ]. Such cytotoxic
    effect was inhibited by anti-MHC class I Abs.

Note that the words highlighted in the right column (`target injury in`) do not appear and the unhighlighted words in the right column (`–118 which sits in`) do appear.

This issue is similar to #6237 where highlight text also doesn't match the underlying text.

**Comment by timvandermeij** [comment]
Using https://mozilla.github.io/pdf.js/web/viewer.html I can no longer reproduce the issue. Closing as fixed.
