### ISSUE TITLE
How to load GeoPDF headers (projection informations in page)?

### ISSUE THREAD

**Issue by fnicollet** [mozilla/pdf.js#6277]
Hello,

This is more of a question, I don't know if anybody has tried working with GeoPDF with PDF.js.
GeoPDF are a special kind of PDF which have additionnal information stored in them to describe maps that are contained in the document, such as projection informations, coordinates, etc.
Here are a few examples of GeoPDF:
http://www.agc.army.mil/Missions/Terrain/GeoPDFMaps/GeoPDFGallery.aspx

I found the specifications online : 
https://portal.opengeospatial.org/modules/admin/license_agreement.php?suppressHeaders=0&access_license_id=3&target=http://portal.opengeospatial.org/files/%3fartifact_id=33332

here is an extract:
```
Conceptually, GeoPDF® specifies map frames associated with a PDF page. A minimal map
frame describes a coordinate reference system that is associated with the entire document
page. This association provides a collection of tuples that map the page (PDF) coordinate
system to the known coordinate reference system. Optionally a neatline specifies the
geometric region of the page that is associated with the foreign coordinate system. There
may be multiple map frames on a given page. Map frames may overlap or be inset. The
coordinate reference system of a map frame is independent of any other map frame.
Map frames are associated with their parent PDF page object. 
```

I need these map frames informations but I don't really know how to get to them or if it is even possible. I tried looking into the PDF metadatas but there is nothing in there. I tried to get the first page with getPage(1).then(...) but there is no information that look like what I need in the JavaScript object.

So my question is, is this an impossible thing to do? Possible with some changes to pdf.js? I would love to be able to find this

Thanks a lot for your help,
Fabien

**Comment by timvandermeij** [comment]
Check out the PDF object browser at https://brendandahl.github.io/pdf.js.utils/browser (you can open a GeoPDF file with that and inspect its contents) and its source code at https://github.com/brendandahl/pdf.js.utils/tree/master/browser. Open for example http://www.agc.army.mil/Portals/75/docs/GeoPDF/1501ANF4815_geo.pdf and browse to `Root -> Pages -> Kids -> 0 -> LGIDict`. That `LGIDict` seems to contain all information you need (it appears to be the main container for GeoPDF data). Since the object browser uses PDF.js itself, it is definitely possible to get that information as PDF.js parses it, but it is not exposed via the API, hence you will not get it with `getPage`.

As you can see, PDF.js does parse the information, but it is not widely accessible because the display layer does not need it. However, you can work with it with some modifications. Perhaps #6266 will be helpful for you, but you might also be able to do something like https://github.com/mozilla/pdf.js/blob/d3e90cf825ae7af85f250db7d4b168d9cdce3214/src/core/core.js#L87-L94 (replace `MediaBox` with `LGIDict`) to fetch the information.

Since this is rather out of scope for the PDF.js library itself, I'm closing this as answered. Feel free to request more information on the mailing list or IRC though.

**Comment by fnicollet** [comment]
WOW! I can't believe such a quick and detailed answer, thank you so much, this is exactly what I needed :+1: 

Fabien
