### ISSUE TITLE
CSS error seems to prevent styling

### ISSUE THREAD

**Issue by raijinsetsu** [mozilla/pdf.js#6278]
We recently updated one of our projects to use an updated PDF.js. We found that, after the update, all the styling was missing:
![image](https://cloud.githubusercontent.com/assets/6809014/8966385/2057b03e-35ff-11e5-9eda-4f888a00ed41.png)

After several hours, we narrowed it down to this:
https://github.com/mozilla/pdf.js/blob/master/web/annotations_layer_builder.css#L62
````
.annotationLayer .annotLink > a /* -ms-a */  {
  background: url("data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///yH5BAEAAAAA\
                   LAAAAAABAAEAAAIBRAA7") 0 0 repeat;
}
````

The continuation of the data URL seems to be rejected by both Chrome and Firefox (IE was untested). This causes the compiled CSS to stop loading. The browsers do not display any errors in the console or otherwise.

We joined the two lines and removed the back-slash and it began working again.

The commit that introduced this is 70a093573750945c78995e923ee4220ea850d079. Note: our previous version was from before that commit.

**Comment by timvandermeij** [comment]
This is working fine in Firefox in the web viewer at https://mozilla.github.io/pdf.js/web/viewer.html as well as in the extension, for over a year. It is also working fine in the Chrome extension. I really doubt that this is the cause, because otherwise we would already have gotten other complaints about this since the commit is over a year old (and missing styles cannot really go unnoticed). Could you try creating a clean clone of the PDF.js repository and see if that also has the issue? I strongly think it is something related to your custom code.

**Comment by raijinsetsu** [comment]
If I take 1.1.215 and I do not integrate with our project, there is no issue.

Our custom code is limited to altering paths to fit our project layout and embeds all the images as data URLs. We verified that the browser was downloading all the assets, including all CSS. But the browser was not applying any of the styles to the elements - viewing the elements shows absolutely no styles applied. Using Chrome's debugging tools, we verified that the entirety of the files were downloaded. There were no errors displayed in the console.

Maybe this line continuation is somehow fixed-up when there are no other data URLs or the combination of this malformed data URL with the other changes caused the browser to give up parsing the CSS.

According to the W3 (http://www.w3.org/TR/CSS21/syndata.html), the backslash within a string will correctly ignore the backslash and the preceding newline but it does not say anything about stripping the preceding white-space, as is present here. I have no explanation why this works under most circumstances but it does not appear to be valid.

**Comment by timvandermeij** [comment]
Of course you can adjust this in your custom fork, but I don't really see why we should fix this on our end if it works in all browsers and configurations when no custom code is around.

@Rob--W @Snuffleupagus What is your opinion on this?

**Comment by Rob--W** [comment]
@timvandermeij The backslash plus white space looks weird. At least remove the leading whitespace.

If tools work against us, we should fix the tools, not break the code.

**Comment by timvandermeij** [comment]
If someone is willing to submit a PR for this that the lint tool accepts, then I guess I'm fine with it.

**Comment by Rob--W** [comment]
For the record: I think that the error is most likely caused by your use of Windows-style line endings (CR LF) instead of UNIX-style line endings (LF). Because of this, the backslash escapes the carriage return but not the linefeed.

- Works (body is red):  
  `data:text/html,<style>a{background:url("data:,\%0A...")}body{background:red}</style>`
- Does not work (body stays white):  
   `data:text/html,<style>a{background:url("data:,\%0A%0D...")}body{background:red}</style>`

**Comment by Snuffleupagus** [comment]
> It was probably done this way to respect the 80 character limit for a line (otherwise the linting tool will complain)

Given that linting only covers JavaScript code, I don't think that applies here (since it's a `.css` file).
