### ISSUE TITLE
Presentation mode on Mobile

### ISSUE THREAD

**Issue by closdesignUIUX** [mozilla/pdf.js#6323]
Presentation mode on mobile seems a bit counter intuitive.  
I tested on my Moto X 2nd gen using Android 5.0.  I see that when you touch/tap the screen in presentation mode, it advances to the next page.  But I would have expected tap on the right half of the screen == advance, tap on the left half of the screen == previous page.  

Also, i just posted another question about the pinch to zoom, in presentation mode and viewer mode, pinch to zoom is not implemented or just does not work.  This is something that would be great to have in both modes, as well as a left and right advancing on touch devices. 
(Got message back, no pinch to zoom yet)

**Comment by Snuffleupagus** [comment]
Please note that zooming is purposely disabled in Presentation Mode, see the discussion in issue #5336.

**Comment by closdesignUIUX** [comment]
Yeh, I was going to dive into this sometime soon.  We would like to implement PDF JS and zooming on mobile.  Hopefully can come up with a solution.  Much needed.

**Comment by Snuffleupagus** [comment]
Please note that the default PDF.js viewer, i.e. https://mozilla.github.io/pdf.js/web/viewer.html, was never really intended to be a good fit for mobile devices. Issue #6136 exists to track the creation of a more mobile friendly viewer, e.g. based on the https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer example.

PR #7653 added support for swiping between pages in Presentation Mode (both forwards and backwards), which should help with changing pages on touch devices.
Closing, since having different page switching behaviour depending of which half of screen is clicked in Presentation Mode could easily be confusing for many users.
