### ISSUE TITLE
Scroll bar not enabled when pdf is zoomed in Canvas

### ISSUE THREAD

**Issue by mechintosoftware** [mozilla/pdf.js#6328]
I am trying to use a Canvas as a container, in which user would control the zoom from outside the canvas (similar to navigation between the pages), but when the page is zoomed scrollbars are not enabled for the container, due tho this content is zoomed but only part of pdf is seen(looks like an image) looses the other part of PDF.
Please help to get the scroll bars in the canvas
Searched a lot for solution but no luck

**Comment by timvandermeij** [comment]
You should look into how the default viewer does it: https://github.com/mozilla/pdf.js/tree/master/web. That also uses canvases where the zoom is controlled from the outside. Since this appears to be an implementation issue, please use the mailing list or IRC as this issue tracker is mainly used for tracking bugs in PDF.js itself. Thanks.
