### ISSUE TITLE
characters chosen for text layer disagree with characters chosen for rendering

### ISSUE THREAD

**Issue by cdmalon** [mozilla/pdf.js#6330]
Search behaves erratically for the PDF

http://www.aclweb.org/anthology/C96-2212

Looking at the author's affiliation on page 1, a search for "ATR" succeeds, but a search for "Interpreting" does not.  This line is written in the font TimesNewRoman, which is not embedded in the PDF.

The text layer shows "ATR" in the div where the search succeeds, but text beginning with "h:lt" in the div where "Interpreting" should be.  Sure enough, a search for "h:lt" would highlight the first part of "Interpreting."

Because "Interpreting" is rendered correctly in the PDF, and the text comes from a system font, surely the right text could be written into the div if the text layer construction followed the same logic as the rendering code in selecting a character from the system font.

**Comment by cdmalon** [comment]
pdffonts (from xpdf) reports that the encoding for each font is WinAnsi, not Builtin.

**Comment by Rob--W** [comment]
This seems like an issue with the PDF. It also displays incorrectly in Chrome's PDF viewer and pdftotext (Poppler). Here is an extract of the pdftotext command:

```
Hierarchical

Clustering

of Words

A k i r a Ushioda*
ATR

h:lt(;rth'e.1;h:lg

T(;l('(:omnnlni(;&l;ions Res('ax(:.h I,M)ort~tories
2-2 ltika,ridM, S(;ika-(:ho, SorMcu-gun, Kyoto, ,]a,l:)~m 6] 9-02
ema,i]: u s h i o d a ( a ) i t l ,
```

**Comment by Snuffleupagus** [comment]
This PDF file looks like a scanned document, where OCR was used to (try to) enable text-selection and copying. Unfortunately the PDF file *itself* actually specifies the text in the broken way seen in e.g. https://github.com/mozilla/pdf.js/issues/6330#issuecomment-128927439 above.
Since this unfortunately is an issue with some OCR software incorrectly recognizing the text, there's really not much we can do about it (and please note that other PDF viewers has the exact same problem).

Closing as invalid, since the PDF itself is causing the issue.
