### ISSUE TITLE
Change the way the viewer open a doc.

### ISSUE THREAD

**Issue by qingzhengzhuma** [mozilla/pdf.js#6331]
I'm very sorry to ask a primary question here.I'm going to change the way the viewer to open a doc, but I can't get the entry to do that, I only can trace here :
![default](https://cloud.githubusercontent.com/assets/10589386/9149752/c3ce7066-3dea-11e5-8ca2-662fd053f1ad.PNG)
then I get confused where the code goes,  I also don't know when the fileInput post doc to the handler， can any body lend me a hand?

**Comment by timvandermeij** [comment]
All that https://github.com/mozilla/pdf.js/blob/d10573468634e5b1f431821ec2f8cf80d5a64ef6/web/secondary_toolbar.js#L77-L80 does is click the file input field to trigger the Open File dialog. It is dynamically added at https://github.com/mozilla/pdf.js/blob/26b9205c7e7d8d7507b26f56221bab13c0ef4001/web/viewer.js#L1240-L1245 because not all builds have the Open File functionality. The actual opening of the file appears to be done here: https://github.com/mozilla/pdf.js/blob/26b9205c7e7d8d7507b26f56221bab13c0ef4001/web/viewer.js#L1693-L1722

I agree that this is a bit hard to find out and probably that code needs some refactoring. If someone is willing to do that, feel free to create a PR.

Closing as answered.

**Comment by qingzhengzhuma** [comment]
thank you so much, that helps me a lot~
