### ISSUE TITLE
Font issues after upgrading to the latest version

### ISSUE THREAD

**Issue by aldokocha** [mozilla/pdf.js#6353]
I have a problem with radio buttons and check marks displaying correctly in the latest version (1.1.215). When using the version 0.8.505 (both pdf.js and compatibility.js) everything looks fine.
Once upgraded, all radio buttons and check marks are replaced with weird symbols.
When opening my pdf files on http://mozilla.github.io/pdf.js/web/viewer.html I see these weird symbols as well. 

The link to pdf file:
https://www.dropbox.com/s/swbd7be6sjq15pf/2319.pdf?dl=0

![pdf-font-ok](https://cloud.githubusercontent.com/assets/1692546/9252513/b4f43962-41a6-11e5-9d0b-c7a6579729b4.png)
![pdf-font-issue](https://cloud.githubusercontent.com/assets/1692546/9252370/f07274aa-41a5-11e5-9daa-6132e98b93f2.png)

**Comment by Snuffleupagus** [comment]
As outlined in the *first* paragraph of https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md, please provide a link to the PDF file.

**Comment by aldokocha** [comment]
Sorry, I couldn't attach the file and haven't thought about the link. Here's the link: https://www.dropbox.com/s/swbd7be6sjq15pf/2319.pdf?dl=0

**Comment by Snuffleupagus** [comment]
From the console:
```
PDF a75a1137f00857247965f974753f9384 [1.5 - / -] (PDF.js: 1.1.377) viewer.js:6645:1
Warning: Wingdings font without embedded font file, falling back to the ZapfDingbats encoding. pdf.worker.js:224:5
```

**Comment by aldokocha** [comment]
Thanks for the prompt response. So this Wingdings font was in the old versions and was later removed?

**Comment by Snuffleupagus** [comment]
> So this Wingdings font was in the old versions and was later removed?

No, we've never had support for non-embedded Wingdings fonts.
It's *possible* that some browsers (e.g. IE) where able to fallback to the correct font; but in general, I don't think that this has ever worked correctly across browsers (e.g. it did *not* work in Firefox using older versions of PDF.js).

**Comment by THausherr** [comment]
Wingdings is available on windows, but the name is "Wingdings-Regular" so it doesn't match.

**Comment by Snuffleupagus** [comment]
Closing as WONTFIX, since there's generally speaking not much we can actually do here unfortunately!

Wingdings is a *non*-standard font, only natively available on Windows, and as such PDF documents *themselves* should be embedding the necessary font data to ensure that rendering will be correct on all platforms (otherwise the "Portable" part of the PDF acronym isn't actually true).

Given that there doesn't appear to be a *free*/*libre* "Wingdings"-version available, we thus cannot ship any Wingdings font data with the PDF.js library either (as opposed to e.g. the "normal" Symbol fonts).
