### ISSUE TITLE
Hyper links are not supported in PDF JS version 1.1.1

### ISSUE THREAD

**Issue by gsampath127** [mozilla/pdf.js#6408]
Hi , I am using pdf js stable version 1.1.1 .
 Hyperlinks are not supported in pdf js 1.1.1 and we are able to open the hyper links from  version (1.1.114) . Can you please suggest any changes to be made in 1.1.1 version to enable hyper links , as of now we can not change the files of other version.

**Comment by timvandermeij** [comment]
No changes have been made to the `Link` annotation code recently as far as I know (except for #6281, which appears to be unrelated). Version 1.1.1 is pretty old; the latest stable version is 1.1.215. You should really consider updating, and otherwise you would have to go through the last commits manually to find out which commit fixed the situation for you. Closing as answered.
