### ISSUE TITLE
Print functionality in IE giving error and stops the browser

### ISSUE THREAD

**Issue by kvk123456** [mozilla/pdf.js#6415]
Printing some big PDF documents, first shows a dialog box "Preparing Document For Printing" takes long time and then Crashes the browser.

Please fix this issue
![screen1](https://cloud.githubusercontent.com/assets/13853369/9670589/d9a6ef72-5252-11e5-99d3-6c98d05e754b.jpg)
![screen2](https://cloud.githubusercontent.com/assets/13853369/9670594/dd5242f2-5252-11e5-8bec-a4ee144e9cdd.jpg)

**Comment by timvandermeij** [comment]
Please share a link to a PDF file that is causing this behavior, otherwise we probably cannot fix it.

**Comment by Rob--W** [comment]
@timvandermeij  Any big document works.

This is an out-of-memory issue. Perhaps we could use `<img>` instead of `<canvas>` to save some memory while printing?

**Comment by kvk123456** [comment]
Can i expect a fix for this from next stable version V1.1.366?

**Comment by Rob--W** [comment]
@kvk123456 Probably not. This is a limitation of the web browser / physical memory.

The only way to solve this problem is to get an API similar to mozPrintCallback in other browsers (this API allows us to stream print jobs (i.e. render one page at a time) instead of having to draw all pages at once and then request the browser to print it.

**Comment by gwellner** [comment]
Rob--W said:
>This is an out-of-memory issue. Perhaps we could use <img> instead of <canvas> to save some >memory while printing with the polyfill?

Is that really a possible workaround ? Guess Images aren't stored in Memory, but how does converting the HTML 5 canvases into images that are stored on client side work ? (from javascript)

**Comment by Rob--W** [comment]
@gwellner Note: My statement was a conjecture, whether it works is not certain.

If you want to experiment with it, you could try to convert a canvas to a data:-URL or a blob:-URL, and then assign it to an `<img>` object (that replaces the original `<canvas>`). This incurs an extra cost in the form of overhead: the canvas needs to be serialized, and the image data needs to be decoded again by the browser. I think that the ultimate result does not use as much memory, because the browser is in a better position to optimize the memory usage because it does not need to offer image manipulation methods to the JavaScript client.

As said, this is a guess. To know whether it really improves the situation, you need to implement it and profile the result.

**Comment by gwellner** [comment]
I tested the IE10 and IE11 with `<canvas>` and they both crashed uppon printing or print preview.

The Solution with converting the `<canvas>` Elements into base64 ebcided `<img>` worked, but to achieve the same quality i needed to create the canvas 3 times bigger and then scale the converted `<img>` back to original size. Sadly that produces a 6-9 times bigger file uppon printing.

Any Idea how i can get the file smaller without loosing quality ?

```javascript
pdfPage.render(renderContext).promise.then(function() {
          // Tell the printEngine that rendering this canvas/page has finished.

          var image = new Image();
          image.src = canvas.toDataURL("image/png");
          image.width = image.width / PRINT_OUTPUT_SCALE * PPI_TO_DPI;
          image.height = image.height / PRINT_OUTPUT_SCALE * PPI_TO_DPI;
          canvasWrapper.appendChild(image);
          canvasWrapper.removeChild(canvas);

          obj.done();
        }
```

**Comment by timvandermeij** [comment]
Closing as fixed by recent printing PRs. Further issues with large PDF files are tracked in #7536.
