### ISSUE TITLE
TextLayer contains scrambled data

### ISSUE THREAD

**Issue by danez** [mozilla/pdf.js#6428]
We have a pdf that renders fine, but the text-layer is completely broken and renders text like "ŚĞŝĚĞĂŽĨ͞ŚĂĐŬĞƌƐƉĂĐĞƐ͟ ŽƌŝŐŝŶĂƚĞĚŝŶ'ĞƌŵĂŶLJĂƐĂŶŝĚĞĂŽĨƚŚĞŚĂŽƐŽŵƉƵƚĞƌůƵď ŝŶϮϬϬε"

Probably it is a problem in the pdf, as also other pdf-viewers (chrome, mac preview app) can't render the text. But maybe anyone of the pdf-experts here can tell me what exactly is wrong. And if it is not fixable on viewer side, maybe detect that it is wrong and disable the textlayer?

https://github.com/danez/pdffail/raw/master/Learning%20in%20cyber-physical%20worlds_Issue39.pdf

**Comment by Snuffleupagus** [comment]
Text selection is broken in Adobe Reader too, which is usually a quite good indication that something is wrong with the PDF file (since Adobe Reader is quite good at recovering from corrupt/missing data).

As suspected, the PDF file itself is broken. Some parts of the text, e.g. the headlines, works as expected.
However, the main body of text is using `CIDFontType2` fonts, with font data which explicitly tell PDF viewers to use an Identity `ToUnicode` map.
In order to fix this, the fonts in the PDF file should be changed to provide accurate `ToUnicode` data. 
(See the screen-shot below; taken from http://brendandahl.github.io/pdf.js.utils/browser/, which lets you browse through the structure of a PDF file.)

Since the font data *explicitly* tells us what kind of `ToUnicode` map we should use, we really don't have much choice except to use it. If we ignored `ToUnicode`, then text selection would be broken in most PDF files (even correct ones).
Thus we simply need to trust that fonts embedded in PDF files actually contain appropriate `ToUnicode` data, since there is generally no way of knowing if a `ToUnicode` entry is "correct", without a human doing the actual comparison.

In closing, this is unfortunately not an issue that we'll be able to fix in PDF.js. It needs to be fixed in the software/tools used to create the PDF file.

---
![tounicode](https://cloud.githubusercontent.com/assets/2692120/9736603/78bc0820-5642-11e5-8420-c42293d6fa8a.png)

**Comment by danez** [comment]
I understand thanks.
