### ISSUE TITLE
Thumbnail rendering glitch

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6442]
After PR #6299 there is a (somewhat minor) visual glitch in the thumbnail viewer when a thumbnail is being rendered. See #6441 for a screenshot. I'm tentatively assigning this to @Snuffleupagus as he appears to have an idea on how to solve this.

I'm also adding https://stackoverflow.com/questions/14396356/force-firefox-to-render-empty-image-within-dimensions-specified-by-css for more documentation on how to possibly solve this. From that page it appears that this issue is Firefox-only.

**Comment by Snuffleupagus** [comment]
Conceptually, I'd actually prefer to re-factor this a bit.
My preferred solution would be to (again) render thumbnails on a visible `canvas`, and once the rendering is done convert to an `image` and then swap the elements; [please see a WIP patch here](https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:PDFThumnailView-refactor-canvas-to-image).
That seem to me to be a slightly more robust solution over all, but unfortunately it doesn't seem to be working perfectly. When testing this there was intermittent flickering (at least in Firefox) when doing `replaceChild`, which didn't look particularly good.

Since we're kind of short on time here, [before the next Firefox release](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates), I choose to submit a much simpler fix which should be an improvement for now. We can then revisit this later on, if we want to.

**Comment by timvandermeij** [comment]
I actually think this current patch does the work very well. We can indeed always refactor this later on if we wish, but swapping elements does seem a bit tricky to me too to get right.
