### ISSUE TITLE
Viewer unable to display PDF files retrieved through SSL

### ISSUE THREAD

**Issue by hammady** [mozilla/pdf.js#6446]
I am unable to display a PDF retrieved via SSL. Look at the demo with an SSL link:

http://mozilla.github.io/pdf.js/web/viewer.html?file=https://d2fqdaa97sxcjl.cloudfront.net/fulltext/c6f10e90-5646-4161-a72b-fa78bf76c5a0/I901_payment_confirmation_07262015.PDF

Is this a limitation of PDF.js? The certificates are OK and I believe this is something not related to PDF.js, if the browser can get it, then PDF.js should.

**Comment by Rob--W** [comment]
This is not an issue with PDF.js, it's an intentional security feature of browsers that websites cannot directly read files from other websites.

Although it's possible to circumvent the issue using a proxy (e.g. as explained at https://github.com/mozilla/pdf.js/issues/1000#issuecomment-133756244), a better solution is to host PDF.js on the same website (e.g. cloudflare in your case). Then the URL would be something like: `https://d2fqdaa97sxcjl.cloudfront.net/web/viewer.html?file=/fulltext/c6f10e90-5646-4161-a72b-fa78bf76c5a0/I901_payment_confirmation_07262015.PDF`

See https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-xhr and https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website.

**Comment by hammady** [comment]
Thanks for pointing out the CORS issue. The cloud front endpoint was not configured for CORS, but the S3 origin behind it was. However, if you inspect the network requests while loading the above link, it shows 200 OK for the PDF resource which means the file was pulled correctly. I have tried HTTP and HTTPS with no luck (200 OK though in both cases). Any clue how this can be debugged?

**Comment by Rob--W** [comment]
@hammady HTTP 200 OK means that the server found the resource. After that, what matters is that the `Access-Control-Allow-Origin` header is set.

If it still does not work, please include a log / screenshot of the network traffic.

**Comment by hammady** [comment]
@Rob--W it is working now, I guess there was a big latency in applying CORS rules in AWS. Thanks!
