### ISSUE TITLE
Odd alternating blank pages within electron when printing

### ISSUE THREAD

**Issue by neves** [mozilla/pdf.js#6516]
Running the sample viewer inside electron, add odd alternating blank pages when printing:

![captura de tela 2015-10-10 as 14 38 47](https://cloud.githubusercontent.com/assets/881/10412459/f0b7e65e-6f5c-11e5-9078-a393a049c941.png)

Sample files: https://gist.github.com/neves/1d74370051972aeb716d
```
git clone https://gist.github.com/1d74370051972aeb716d.git electron-pdf
cd electron-pdf
electron .
# try to print preview to pdf
```
Tested in osx El Capitan and Windows Seven 32bits

**Comment by timvandermeij** [comment]
Electron appears to be a PDF generator, so if that tool generates this kind of output there is not much we can do about that. Since there are also other issues about blank pages during printing (see https://github.com/mozilla/pdf.js/issues?utf8=%E2%9C%93&q=is%3Aopen+label%3A4-printing+blank) I'm closing this one as a (possible) duplicate for now.
