### ISSUE TITLE
Text selection

### ISSUE THREAD

**Issue by clarkk** [mozilla/pdf.js#6519]
How to make text selection work? There are no examples

```
https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.css
https://github.com/mozilla/pdf.js/blob/master/web/text_layer_builder.js

'use strict';

PDFJS.getDocument('file.pdf').then(function(pdf){
    pdf.getPage(1).then(function(page){
        var scale = 1.5;
        var viewport = page.getViewport(scale);
        var canvas = document.getElementById('the-canvas');
        var context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;

        var canvasOffset = $(canvas).offset();
        var $textLayerDiv = $('#text-layer').css({
            height : viewport.height+'px',
            width : viewport.width+'px',
            top : canvasOffset.top,
            left : canvasOffset.left
        });

        page.getTextContent().then(function(textContent){
            var textLayer = new TextLayerBuilder({
                textLayerDiv : $textLayerDiv.get(0),
                pageIndex : 0,
                viewport : viewport
            });

            textLayer.setTextContent(textContent);

            page.render({
                canvasContext : context,
                viewport : viewport,
                textLayer : textLayer
            });
        });  
    });
});

<body>
  <div>
    <canvas id="the-canvas" style="border:1px solid black;"></canvas>
    <div id="text-layer" class="textLayer"></div>
  </div>
</body>
```

**Comment by Snuffleupagus** [comment]
Please refer to the `pageviewer` and `simpleviewer` components examples: https://github.com/mozilla/pdf.js/tree/master/examples/components. Closing as answered.

**Comment by clarkk** [comment]
Where do I find the `../../build` dir!?

**Comment by Snuffleupagus** [comment]
> Where do I find the ../../build dir!?

It will be generated when you run `node make generic components`, as outlined in https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js#L18-L21.

**Edit:** See also https://github.com/mozilla/pdf.js#getting-the-code.

**Comment by clarkk** [comment]
But I don't want to use the viewer..

How to make it work from the src?

**Comment by Snuffleupagus** [comment]
You initially wrote:

> How to make text selection work? There are no examples

As a direct response to this, I point to the `pageviewer` example since it should do what you asked.

---

> But I don't want to use the viewer.

It's not entirely clear what "viewer" means here, but the examples that I referred to are distinctly *not* the same as the default viewer (http://mozilla.github.io/pdf.js/web/viewer.html).
The [components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components) are created specifically to simplify things as e.g. text selection, since it lets you avoid the hassles of having to work directly with the API.

> How to make it work from the src?

If you want to use the API directly, for inspiration I'd suggest to check how [`pdf_page_view.js`](https://github.com/mozilla/pdf.js/blob/master/web/pdf_page_view.js) enables text selection.

---

**Edit:** Looking at your example code, it seems that you're missing `textlayer.render();` after the `setTextContent` line. (Also, there's no point in including the `textLayer` in the renderContext for `page.render` since it's not used like that.)
I'm not sure if this is enough to get text selection working, since it can be quite difficult to tell where things fail by just looking at a few lines of code.

**Comment by clarkk** [comment]
Have made the modified the code like you said, but still no text selection :(

The PDF is rendered fine - but no text on top of the canvas..

Have added `.textLayer {background: red;}` to the css and I can see the red transparent color over the PDF.. But the text is not rendered in the div

```
PDFJS.getDocument('file.pdf').then(function(pdf){
	var page_num = 1;
	pdf.getPage(page_num).then(function(page){
		var scale = 1.5;
		var viewport = page.getViewport(scale);
		var canvas = document.getElementById('the-canvas');
		var context = canvas.getContext('2d');
		canvas.height = viewport.height;
		canvas.width = viewport.width;
		
		var canvasOffset = $(canvas).offset();
		var $textLayerDiv = $('#text-layer').css({
			height : viewport.height+'px',
			width : viewport.width+'px',
			top : canvasOffset.top,
			left : canvasOffset.left
		});
		
		page.render({
			canvasContext : context,
			viewport : viewport
		});
		
		page.getTextContent().then(function(textContent){
			var textLayer = new TextLayerBuilder({
				textLayerDiv : $textLayerDiv.get(0),
				pageIndex : page_num - 1,
				viewport : viewport
			});
			
			textLayer.setTextContent(textContent);
			textLayer.render();
		});
	});
});
```

**Comment by ashish0019oyo** [comment]
look here: https://github.com/vivin/pdfjs-text-selection-demo
