### ISSUE TITLE
t's replaced with arabic character

### ISSUE THREAD

**Issue by gidsg** [mozilla/pdf.js#6530]
Steps to reproduce
=============
Open: http://ukjewishfilm.org/wp-content/uploads/2015/09/Jewish-Film-Festival-Programme-ONLINE.pdf in Firefox 41 on OSX 10.11
Scroll to page 6

Actual Results
===========
t's in body text are replaced with an arabic character
![screen shot 2015-10-15 at 22 06 50](https://cloud.githubusercontent.com/assets/1764158/10527683/b85ff28e-7389-11e5-9bd3-57e4e5a39bf9.png)

Expected Results
==============
t's render correctly (as in OSX Preview):
![screen shot 2015-10-15 at 22 13 18](https://cloud.githubusercontent.com/assets/1764158/10527728/0e47701e-738a-11e5-9212-3f505b371385.png)

**Comment by timvandermeij** [comment]
I get a 400 Bad Request when visiting the link. Do you perhaps have a new one? Just recently you can also attach PDF files on GitHub by dragging and dropping them in the comment box.

**Comment by gidsg** [comment]
@timvandermeij I do not have rights to attach a PDF but I have updated the link in the bug report to one which should be accessible.

**Comment by Snuffleupagus** [comment]
If this issue is Mac OS specific, then there's a good chance that it was fixed by PR #6171 (based on a cursory look at the PDF file contents).
That patch will be included in Firefox 42, according to the "Target Milestone" field in [bug 1182228](https://bugzilla.mozilla.org/show_bug.cgi?id=1182228), which will be released [early in November](https://wiki.mozilla.org/RapidRelease/Calendar#Future_branch_dates).

**Comment by gidsg** [comment]
@timvandermeij yes, it is fixed in the latest viewer. Thanks for the follow-ups.
