### ISSUE TITLE
Ability to select region and copy to clipboard as graphic

### ISSUE THREAD

**Issue by huyvandoan** [mozilla/pdf.js#6704]
Currently, I'm working on PDF viewer feature and found out that PDFJS does not support to select region and copy to clipboard as graphic. Can PDFJS add this feature for next version? Thanks

**Comment by timvandermeij** [comment]
In my opinion we should not support this in PDF.js natively for the simple reason that the majority of people probably will not make use of this. I don't see any use case for this. Sure it's fine for a custom viewer where such functionality is desired, but for the general viewer this does not seem useful to me.

**Comment by timvandermeij** [comment]
Closing for now because of the above. We can reopen this if there are solid reasons why it would be good to have this in the generic PDF.js viewer instead of just in custom viewers.

**Comment by Godrules500** [comment]
I work for a company that deals with real estate, and this would be extremely useful fo rus. The reason is, is these people have huge printouts of something like a subdivision. However, they may only want a particular lot to be printed. So what they do in our old, extremely outdated desktop application, is select a plot of land on this very large pdf, and then just print that selection. Is there anyway to get this added or a work around?

**Comment by Snuffleupagus** [comment]
> Is there anyway to get this added or a work around?

It'd probably be much easier to just open the PDF file in a desktop PDF viewer, such as e.g. Adobe Reader, for this kind of use-case. As @timvandermeij said, given the very special nature of this feature, I don't think it really makes sense for us to try and implement this in PDF.js.

**Comment by Godrules500** [comment]
Yeah, the hard part is we almost have to use pdf.js so that we have more control over what we allow. embedded Foxit doesn't take parameters (if it does i don't know how), Adobe has some things that pop up that you can't defaultly hide which the users would hate.


Maybe I can somehow use another plugin for taking a picture of what's on the screen and using that.

**Comment by Godrules500** [comment]
Or what about the ability to print what is seen in the window? So if they heavily zoom in, just print what's in the area of the pdf that's viewed?

**Comment by Snuffleupagus** [comment]
> Or what about the ability to print what is seen in the window?

The thing is that PDF.js runs in a browser, which means that we don't have great control over the printing behaviour (as is unfortunately evident from the many open issues related to printing).
