### ISSUE TITLE
Namespace classes and ids

### ISSUE THREAD

**Issue by jacksonrayhamilton** [mozilla/pdf.js#6706]
This application uses very general class and id names. e.g., [#loadingBar, .progess](https://github.com/mozilla/pdf.js/blob/master/web/viewer.css#L326). If one were to drop PDF.js into his own website, there's a high likelihood these class names will clash with those of existing stylesheets.

This problem could mitigated by prefixing all the reader's classes and ids with a common string; e.g., #pdfjsLoadingBar, .pdfjsProgress.

Unfortunately, that's a breaking change for anyone who's styled PDF.js or written extensions with query selectors, so maybe it should be opt-in. There could be a configuration property, `PDFJS.usePrefixedSelectors`, that toggles whether prefixed classes and ids should be used, and all classes/ids could be prefixed (or not) by running them through a utility function `PDFJS.prepareClassOrId()`. A warning could be printed to the user's console instructing him to enable this option, as unprefixed selectors ought to be deprecated and eventually removed.

For the stylesheets themselves, there could be two copies (generated via a build script), one prefixed, one not.

**Comment by dryairship** [comment]
@jacksonrayhamilton @timvandermeij Is anyone working on this issue? If not, may I?

**Comment by timvandermeij** [comment]
Feel free to work on this. My feeling is that this will be easier to fix once the styles are more generic, such as via SASS. That way we can simply group our styles in a general `pdfjsViewer` namespace or something similar. Maybe it's best to start by making a simple prototype of how this could look for the current viewer so we can evaluate some ideas?

**Comment by corpsusvitale** [comment]
Any update on this issue? Not only are common ids and classes used, the application also messes with top level elements like 'html', 'input', 'select', etc.

**Comment by dryairship** [comment]
@corpsusvitale I realized that this is not a beginner's issue, and must be handled by someone with extensive knowledge of the code. Therefore, I did not make any progress on this.

**Comment by JerLai** [comment]
Hello, a small team of 5 of us is attempting a fix. We have some questions regarding the config for the viewer, and configurations for the software in general.

1. Is there an existing configuration modification file/script already in use in pdf.js?
2. If not, is there a mode variable/identifier located somewhere? More specifically is there a global variable somewhere that sets particular options to load/configure features of pdf.js?

From what we understand, viewer.html on load runs a getViewerConfiguration that then returns a configuration object which indicates all the DOM objects that need to be initialized and listened to.

Our proposed solution would to be abstract this to a controller script, namely viewer_config.js which would handle configuration requests on load, based on optional parameters that users can set, probably in some viewer_config.json file. viewer_config.js will be a new module in the web layer, and handle all types of configuration requests.

That being said this is what we think would be a solution. Are there any suggestions or specifics in mind about what to include to address this issue or on our solution?

**Comment by Snuffleupagus** [comment]
Unfortunately fixing this (e.g. for the GENERIC viewer) would *not* be limited to CSS-only changes, but would require pretty invasive changes to the JavaScript code as well.

Please note that while it *should* be pretty easy to use e.g. a PostCSS plugin to automatically prefix all CSS rules during building of e.g. the GENERIC viewer, that'd unfortunately not really help all that much as far as I can tell.
The reason for this is that there's a (fairly) large number of *dynamically* created elements in various parts of the JavaScript code, and you'd obviously also need to update those to (conditionally) use the prefixed CSS rules. This would very quickly become messy and somewhat difficult to maintain, since you'd need to pass *every* single CSS name access through some utility function which adds the CSS prefix for e.g. the GENERIC build.

The other option would be to *manually* change all existing CSS rules, in both the `.css` and `.js` files, to unconditionally use a prefix. That could be a breaking change (as mentioned above), it would result in *a lot* of code-churn for a (somewhat) minor feature, it would put more of a burden on reviewers to ensure that it's done for all changed/new code, and would also end up increasing the size of the built `viewer.css` file for a use-case that's not relevant for e.g. the built-in Firefox PDF Viewer (which is the main use-case for this library).

---

> If one were to drop PDF.js into his own website, there's a high likelihood these class names will clash with those of existing stylesheets.

The simplest solution, and the one we often suggest, is to embed the PDF.js library within an `<iframe>` to e.g. prevent these kind of issues with CSS rules matching other parts of a web-page.

All-in-all, closing this as WONTFIX for the reasons outlined above.
