### ISSUE TITLE
à character rendered where it should not be rendered

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6721]
The PDF file at https://www.dropbox.com/s/ygmic028oykprkw/respond_document_print.pdf?dl=1 has random `à` characters rendered where they should not be.

**Comment by Snuffleupagus** [comment]
Interestingly enough, even though Adobe Reader doesn't render the `à` character, it's still present on copy-and-paste.

**Comment by mjstyle** [comment]
Thanks guys!

**Comment by mjstyle** [comment]
Hi guys, just wanted to check in to see if you guys were able to find a fix to this issue.

Thank you so much!

Regards,

**Comment by timvandermeij** [comment]
Not yet, for these kinds of issues finding the cause of the problem is unfortunately not trivial, so this might take some time.

**Comment by mjstyle** [comment]
@timvandermeij Happy New Years everyone! Just checking in to see if anyone added a fix for this yet :)

Thanks!

Regards,

**Comment by mjstyle** [comment]
@timvandermeij Just following up to see if there will be a planned fix soon?

Thanks!

**Comment by timvandermeij** [comment]
When a fix becomes available, it will be reported here.

**Comment by mjstyle** [comment]
Hi there,

Just checking in to see if this fix is out on production?

Thanks!

Regards,
Jack

**Comment by timvandermeij** [comment]
The fix has been merged here, so it's most likely out for production in the current or the next Firefox release.

**Comment by mjstyle** [comment]
Hi Tim,

I'm just following up to see if this is out on production yet?

Thanks!

Regards,
Jack

**Comment by Snuffleupagus** [comment]
> [...] if this is out on production yet?

What does "production" actually mean in this case?
This issue was fixed in PR #7023, which is included in the `1.5.188` release of PDF.js; see https://github.com/mozilla/pdf.js/releases/tag/v1.5.188.
The PR was merged to mozilla-central in https://bugzilla.mozilla.org/show_bug.cgi?id=1253498, and the `Target Milestone` field says Firefox 47 (i.e. it's included in that version). As can be seen in https://wiki.mozilla.org/RapidRelease/Calendar#Past_branch_dates, the current Firefox release is version 48.

**Comment by mjstyle** [comment]
Understood thank you!
