### ISSUE TITLE
PDFJS.disableFontFace value is overwritten by font loader without any mercy

### ISSUE THREAD

**Issue by tryggve** [mozilla/pdf.js#6742]
In the [font_loader.js](https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js#L20) the PDFJS.disableFontFace is set to false. This overrides the work done in [api.js](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js#L53) and makes it problematic for a user of PDF.js to decide this value for himself.

**Comment by yurydelendik** [comment]
We will remove any PDFJS.xxxx properties in the future. This one is probably belong to render() parameters.

**Comment by Snuffleupagus** [comment]
> We will remove any PDFJS.xxxx properties in the future.

In the meantime, I do think it makes sense to remove that particular line from `font_loader.js`, since it doesn't seem neither necessary nor correct to have it there.
From a brief look through the file history, it seems that it was moved as part of PR #3530, and that it became unnecessary with PR #3595.
