### ISSUE TITLE
Add UMD headers to the web/ files.

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#6776]
We need to add UMD headers for the files we already packaging into pdf_viewer.js. For now we want to refer AMD "pdfjs/" modules directly in their headers, but eventually (after #6775) we need to refer pdf.js.

Let's choose "pdfjsViewer/" or "pdfjsviewer/" as prefix for AMD module names (for files located at web/)

Blocked #6771

/cc @Snuffleupagus

**Comment by timvandermeij** [comment]
Just adding that after this has been done we can also upgrade to the most recent Jasmine version (as use its NPM package instead of having the files in our repository). That relies on the `require` syntax to import the modules for the unit tests and since the unit tests uses a file from `/web`, we need to be able to import that using `require` too.

**Comment by timvandermeij** [comment]
#6771 has been merged, so nothing should be blocking this anymore.
