### ISSUE TITLE
Print highlighted text

### ISSUE THREAD

**Issue by blackzlq** [mozilla/pdf.js#6795]
Hi everyone,
When I print the pdf. the markups will disappear. I try to read the code in viewer but can not find how to print with markups. 
For example. I search Just, and choose highlight all, when I print the pdf file. I want to show the highlight 
Is it possible?

**Comment by timvandermeij** [comment]
The "highlight all" feature is only for searching purposes and does not create persistent highlights. You would have to implement that yourself, but since that is out of scope for the PDF.js library I'm closing this. https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_controller.js takes care of the searching process.
