### ISSUE TITLE
Annotations misplaced after reload

### ISSUE THREAD

**Issue by automatedbugreportingfacility** [mozilla/pdf.js#6804]
This regressed somewhere between 1.3.76 (f7ec866) and 1.3.124 (cba8a87) (sorry, can't bisect it further at the moment as it'd require building the extension for each step due to the reload requirement). Steps to reproduce:

1. Open http://www.nyc.gov/html/dcp/pdf/zone/map8c.pdf
2. Click the "Effective Date(s) of Rezoning:" link.
3. Press F5 to reload the document.
4. Set scale to automatic zoom.

1.3.124: https://i.imgur.com/3ofDOke.jpg
1.3.76: https://i.imgur.com/AZqKaaN.jpg

Please note the difference in scaling behavior:

1.3.76:
- After clicking the link, the document is scaled to 775.53%
- After reload, the document is still scaled to 775.53%

1.3.124:
- After clicking the link, the document is scaled to 761.97%
- After reload, the document is scaled to 775.53%

These values may vary depending on the effective size of the content window.

**Comment by Snuffleupagus** [comment]
A quick bisect seems to point to PR #6714, and more specifically commit https://github.com/mozilla/pdf.js/commit/2dc3ee38c0cc7c4a31aa6ac586f0bcbcb153f0c7.

**Comment by Snuffleupagus** [comment]
> Please note the difference in scaling behavior:

I cannot reproduce this part of the issue, but I've just submitted a patch that should address the main problem with the incorrect annotation positions on reload.

**Comment by DmitryGonchar** [comment]
@Snuffleupagus Thanks for the fix! One comment - it would be nice to be able to apply such fixes by downloading a tagged newer version of pdf.js, instead of applying them manually.

E.g. last 1.3.x version in this repo is 1.3.91 (both in Releases and Tags), while npm latest pdf-dist version is 1.3.233. However, I was not able to find a commit which corresponds to this latest (and I assume more stable than 1.3.91) version. 

Is there a way to track this commit? I cannot find the date when this version was released. It would be beneficial, if for example pdfjsbot would update version in package.json, bower.json and other files and commit on each deploy. This is quite simple to do

**Comment by Snuffleupagus** [comment]
> E.g. last 1.3.x version in this repo is 1.3.91 (both in Releases and Tags), while npm latest pdf-dist version is 1.3.233.

I'm not sure where you're looking, but the version numbers you mention above are *very* out of date.
All official releases, even previous ones, are available from https://github.com/mozilla/pdf.js/releases, and the latest ones are also always available from http://mozilla.github.io/pdf.js/getting_started/#download.

The official `mozilla/pdfjs-dist` library is https://github.com/mozilla/pdfjs-dist. Are you sure that you're using the correct one, since https://github.com/mozilla/pdfjs-dist/releases lists *many* versions newer than `1.3.xyz`?

> Is there a way to find this commit? I cannot find the date when this version was released.

The simple solution should be to look at the PR, in this case https://github.com/mozilla/pdf.js/pull/6805, and check the bottom for the "merged commit" string. In this case, that's https://github.com/mozilla/pdf.js/pull/6805#event-500914593, and clicking on the commit hash takes you to https://github.com/mozilla/pdf.js/commit/ad4354c0bd60c5f2d43c3657c51e812028e3ae54. There (close to the top) you will find a list of the release versions a particular PR is included in. (Note here that PR #6805 has been in every PDF.js release since version `1.4.11`.)

Note also that in `mozilla/pdfjs-dist`, the commit messages contain a link to the commit in this repo (i.e. `mozilla/pdf.js`) where a particular PR was merged; see https://github.com/mozilla/pdfjs-dist/commits/master.

> It would be useful, if for example pdfjsbot would update version number in package.json and bower.json, and commit on each deploy.

If you check an arbitrary commit in `mozilla/pdfjs-dist`, e.g. https://github.com/mozilla/pdfjs-dist/commit/b8f6fc2dbe277c9031d3c60cb2ac288187d0034b, you'll see that the version numbers *are* updated.

**Comment by DmitryGonchar** [comment]
@Snuffleupagus thanks for the help! My mistake, I checked in this repo instead of `pdf-dist`
