### ISSUE TITLE
How to set viewer.html initial parameters without modifying viewer.js

### ISSUE THREAD

**Issue by fryaniv** [mozilla/pdf.js#6812]
Hey guys,

Going over the code, and Google, I am trying to understand how to set the viewer.html initial parameters without modifying viewer.js.

The parameters I would like to set are the loaded PDF file, zoom, and page number.

I've managed to set the first parameter by including a new JS file to viewer.html containing only:
DEFAULT_URL = ''; 
PDFViewerApplication.open(...);

but I cannot find how to set zoom, and page number.

Moreover, I would assume there is a safer way to set these parameters, for example setting them in a callback function after pdf.js was initialized, or attaching them to an initialized event, rather than just having them as-is in the JS file.

Thanks,
Yaniv

**Comment by melashkov** [comment]
I am also interested hot to change DEFAULT_PREFERENCES without modifying viewer.js
```javascript
var DEFAULT_PREFERENCES = {
...
};
```

**Comment by yurydelendik** [comment]
Per [recommendation](http://mozilla.github.io/pdf.js/getting_started/), you will need to modify the demo viewer per your needs and be different from the standard one. Simple way will be to modify viewer.js and viewer.html, and track changes somewhere else (e.g. patch file or your own source control). If you don't want to modify viewer.js, you will need to modify viewer.html to add a script after viewer.js that will override `DEFAULT_URL`, `DEFAULT_PREFERENCES` and PDFViewerApplication.initialBookmark values. Also you are also free to hook into any predefined function/event.

There is no expected behavior specified in this issue (or criteria when the issue counts as resolve). Closing as answered atm.
