### ISSUE TITLE
Uncaught TypeError: Cannot read property 'firstElementChild' of null

### ISSUE THREAD

**Issue by ehsaan-israr** [mozilla/pdf.js#6826]
Uncaught TypeError: Cannot read property 'firstElementChild' of null

problem in viewer.js file at line # 4822

**Comment by ehsaan-israr** [comment]
![image](https://cloud.githubusercontent.com/assets/11690482/12070948/bc51c75c-b0b3-11e5-8c37-b0923e26d232.png)

**Comment by timvandermeij** [comment]
We need more information than this to look into the issue. Please make sure to read https://github.com/mozilla/pdf.js/blob/master/CONTRIBUTING.md. Provide more information about your configuration, a link to your viewer if it's custom and a link to a PDF file if the problem is caused by a specific file.

**Comment by ehsaan-israr** [comment]
![image](https://cloud.githubusercontent.com/assets/11690482/12070950/3ba4ac5e-b0b4-11e5-818a-48f6482493a7.png)

**Comment by dmeh89** [comment]
What did you do to make it work?

**Comment by Ksantacr** [comment]
it was solved?
