### ISSUE TITLE
Embedded font displayed as random characters

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6889]
I made a document using Scribus 1.5.0svn with only the text "This should be readable" in it using the embedded Arial Regular font. While it displays fine in Adobe Acrobat Reader DC, PDF.js displays random characters when using Windows 10 x64 and Firefox 43.0.4.

Initially I thought my issues with the Scribus PDF exports were fixed by #6068. That issue is still fixed, so this is not a regression, but something must have changed in the meantime (either in Scribus or in my system fonts) because, as far as I can remember, this new PDF is generated in the *exact* same way as the one in that issue, yet this one is broken and the other one is not.

Here is a reduced test case for inclusion in the PR that fixes this issue:
[example.pdf](https://github.com/mozilla/pdf.js/files/93576/example.pdf)

Using Brendan's PDF browser I see that this font also has names of the form `uniXXX` in the `differences` array, which might indicate a similarity with #6090. @Snuffleupagus Do you perhaps have an idea if the fix for this issue is similar to the one in #6090, but for a different code path?

**Comment by Snuffleupagus** [comment]
> [...] but something must have changed in the meantime (either in Scribus or in my system fonts)

The embedded TrueType fonts are not entirely identical, since the 'post' table<sup>1</sup> format differs:
in #6068 it's `2`, and here it's `3`. Note how `properties.glyphNames` is undefined in the latter case<sup>2</sup>.

Also, it seems that Scribus PDF includes *a lot* of unnecessary junk in the files it generates, so I figured it couldn't hurt to "reduce" the PDF file even more :)

---
[1] https://developer.apple.com/fonts/TrueType-Reference-Manual/RM06/Chap6post.html
[2] https://github.com/mozilla/pdf.js/blob/master/src/core/fonts.js#L3748-L3815
