### ISSUE TITLE
Font styles are not applied

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6894]
*I have tested this with the preview from PR #6891 as that makes the PDF render properly.*

Opening the file below with the preview at http://107.21.233.14:8877/20a6d5dd16fdaa6/web/viewer.html makes all characters display properly, but the font styles (bold and italic) are not applied. Adobe Acrobat Reader DC has no problem with this. The PDF is generated by Scribus 1.5.0svn.

Below is a reduced test case for inclusion in a PR that fixes this issue. It might be possible to reduce it even further.
[reduced-font-styles.pdf](https://github.com/mozilla/pdf.js/files/94490/reduced-font-styles.pdf)

**Comment by Snuffleupagus** [comment]
This could possibly be related to the remaining issue (i.e. the slightly incorrect glyph rendering) observed in [bug 1132849](https://bugzilla.mozilla.org/show_bug.cgi?id=1132849), since the bold/italic styles in this issue were correct *prior* to commit https://github.com/mozilla/pdf.js/commit/b5b94a4af389ef387570cf22662d9fc6bd41417a (i.e. PR #4259). See also https://github.com/mozilla/pdf.js/pull/6090#issuecomment-111081768.

@brendandahl Any ideas here?
