### ISSUE TITLE
Use `beforeEach` and `afterEach` instead of initialization code in `describe` blocks

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6905]
This might make the unit tests a bit slower (as we might, for example, read one file for each test instead of just once), but it is the recommended way to setup and tear down unit tests properly.

Blocked by #6877.

**Comment by Rob--W** [comment]
We're currently using Jasmine 1.1.0 (https://github.com/mozilla/pdf.js/tree/58329f7f92f9c9f5dd8a7e42caf6ba3afdd6911d/external/jasmine), which is over 4 years old. Meanwhile Jasmine has improved a lot (in particular in the syntax for asynchronous tests, using explicit callbacks instead of error-prone `waitsFor` calls), so upgrading to the latest version of Jasmine (and putting the dependency in package.json instead of external/jasmine) might make it easier to enhance the tests.

**Comment by yurydelendik** [comment]
Jasmine was updated to 2.4.1 by #7129

**Comment by yurydelendik** [comment]
There is also `beforeAll` and `afterAll`, see http://jasmine.github.io/2.4/introduction.html#section-Setup_and_Teardown

**Comment by yurydelendik** [comment]
TODO:
* [ ] crypto_spec: inside "CipherTransformFactory"
* [ ] dom_utils_spec: inside "isExternalLinkTargetSet"
* [ ] font_spec: inside 'font' (maybe), 'CFFParser',
