### ISSUE TITLE
DOM getting reloaded on enter keypress

### ISSUE THREAD

**Issue by sohitri** [mozilla/pdf.js#6907]
I have created a modal for printing function. The modal contains three radio buttons and a text field. Whenever i am entering some value in the text field and hit enter(or hit enter in the blank text field), whole DOM gets reloaded. This occurs when the focus is on the text field not on radio button. I am attaching screenshot of my modal. 
1. How can i stop this page reloading?
2. From where this reload function is triggered?

![modal](https://cloud.githubusercontent.com/assets/13832184/12472872/973b9e1e-c032-11e5-9476-9de6d4c3e61f.png)

**Comment by Rob--W** [comment]
What do you mean by "DOM is getting reloaded"? Please provide a link to a page with your custom viewer, or provide the source code so that we can test it.

I think that it is most likely that the issue is not really caused by PDF.js and that you wrapped the input fields in a `<form>` element without an `onsubmit` event handler (or one that does not call `event.preventDefault()`), which causes the form to be "submitted" (=reload page) when the user presses <kbd>Enter</kbd>.

**Comment by sohitri** [comment]
Thanks Rob. Missed the event.preventDefault(). Now it is working fine. Thank you very much for your time.
