### ISSUE TITLE
In IE styling is different how can we fix in pdf.js

### ISSUE THREAD

**Issue by KRaghupathy** [mozilla/pdf.js#6966]

**Comment by yurydelendik** [comment]
No screenshot or IE version information provided -- assuming IE9. CSS styling on different browser can be different since some legacy browsers might not support some feature. UI parity for legacy browsers is not a priority of the core PDF.js team. The generic viewer shall be used only for modern browsers and its support for old browsers falls on shoulder of the web developers that changing it. Closing as answered.
