### ISSUE TITLE
Add-on is not signed anymore

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#6970]
I noticed this too and now it's also reported in #6137. Did the API change? Perhaps this is also a good chance to implement that we should only publish the extension when it is signed.

/cc @yurydelendik

**Comment by mcl21014** [comment]
Yes the addon should be signed, and automatically for the sake of my sanity as a user. Firefox for Android does not include a PDF Viewer, and I use this addon with it so I can view PDFs in the browser. I also use it on the desktop with stable Firefox to get a better experience viewing PDFs. You may say I should run a nightly build for this purpose, but the nightly builds do not integrate so well on Linux, and I'd have to compile them myself, or use some install script, or use a version for Ubuntu from an outdated PPA.

And with extension signing being mandatory in v46 of Firefox with the override being removed, this needs some attention ever more promptly.

**Comment by yurydelendik** [comment]
Fixed by providing path to "unzip" (https://github.com/mozilla/botio-files-pdfjs/blob/master/signxpi.js#L28). On botio-windows, the botio can be started with "cmd" or via "bash". bash environmeth had all the settings and "cmd" did not. botio was restarted in "bash" and, also, the correct path was set for "cmd" environment as well. Closing as resolved.
