### ISSUE TITLE
Text selection not possible for annotations with a trigger div

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#7013]
Some annotation types, like Squiggly and Highlight, make use of trigger divs to show the popup on hover. These divs overlay the text div, causing text selection to be impossible when starting on the div. Starting selection from outside the div does work, so this is not a large usability issue, but if someone knows an issue for this that would be great.

(Try for instance https://drive.google.com/uc?export=download&id=0B6YhVF9p-y2AMmlnaURWSjZKNlk)

**Comment by Snuffleupagus** [comment]
Text-selection actually seem to work (or rather not work) almost identical for the annotations in that file, when comparing Adobe Reader and PDF.js.

**Comment by sharanmunyal** [comment]
Yes. agreed that is hard. However I found a fix so that text selection of anchor tags can be possible. Solution: On mousedown in the every page (selector = '.page') hide the annotationLayer until a mouseup is triggered for that page. This way anchor tags don't hinder the text selection. I implemented this for my application and it looks fine so far.

**Comment by Snuffleupagus** [comment]
Given https://github.com/mozilla/pdf.js/issues/7013#issuecomment-188726595, let's close this old issue as WONTFIX for now.
