### ISSUE TITLE
Poorly rendered image quality

### ISSUE THREAD

**Issue by nicholassinggih** [mozilla/pdf.js#7041]
Hi all,

I have tried using the latest 1.3.91 version for this. All I did was modify the viewer.js to point to my own PDF. This is the result using the fresh out of the box viewer.html :
![image](https://cloud.githubusercontent.com/assets/13591425/13384259/fd9dd7a2-dee7-11e5-9598-05e8baae48af.png)

The left one is the actual PDF, and the right one is rendered by viewer.html. Same thing in IE and Chrome. I did not try it in FF because my users use either IE or Chrome. 

I've tried searching everywhere I could and have been unsuccessful in finding a solution to this. Here's the PDF file from the picture. 
[.0002.pdf](https://github.com/mozilla/pdf.js/files/150290/default.0002.pdf)

**Comment by Rob--W** [comment]
What exactly is wrong with the PDF from viewer.html?
(the zoom levels are different by the way, the one at the left uses 100% zoom, the one on the right 80%).

**Comment by nicholassinggih** [comment]
Hi Rob,

Thanks for your reply. 

The problem is the text quality (I'm not sure if it's strictly font rendering or not) makes it a bit harder to read the words on it. Check out the word Billing at number 12, for example. The one on the right looks like it says "Bllllng". My users need to be able to see at least 8 pages at the same time, as they go through thousands every day. This means they're going to view the pdfs with an even smaller zoom level. 

The one on the left is not at 100%. It's actually at a smaller percentage than 80%. Just look at the sizes. The one on the left showed number 1-28 on the same screen, while the right one only showed 25.

**Comment by Rob--W** [comment]
Could you paste a screenshot with exactly the same zoom sizes?

The "text rendering" is not a text rendering issue. What you see is an image. The question is whether the quality deteriotated after scaling (and of course, whether it can be improved).

**Comment by nicholassinggih** [comment]
Let me clarify that I've tried playing with the scaling for both. I've tried looking at the PDF at 50% in Adobe Reader and Foxit. The quality doesn't get affected much by scaling. 

Here's from the viewer at 100%. Notice that the first 'i' in the word Billing still looks like an 'l'.
![image](https://cloud.githubusercontent.com/assets/13591425/13407566/16a688d0-df7d-11e5-968d-6af49437f70f.png)

And this next one is at 100% in Adobe Reader.
![image](https://cloud.githubusercontent.com/assets/13591425/13407640/9591e00e-df7d-11e5-9e82-3526f0f59083.png)

**Comment by Rob--W** [comment]
Thanks for your extra info. I don't know what goes wrong, but maybe some of the other PDF.js devs know.

**Comment by fkaelberer** [comment]
I think the loss of image quality happens in [canvas.js#L1895](https://github.com/mozilla/pdf.js/blob/ff87f3fb86e3b50d3d952842cb0d57d991fe994e/src/display/canvas.js#L1895), where the Jpeg image of dimensions 2508 x 3525 is drawn onto a canvas that is much smaller than the image. Images look poor when they are scaled down by a large factor at once, which is fixed in [canvas.js#L2081](https://github.com/mozilla/pdf.js/blob/ff87f3fb86e3b50d3d952842cb0d57d991fe994e/src/display/canvas.js#L2081) (from #3312). The same fix was applied to thumbnails in #4924. So I guess it should be fixed here for Jpeg images as well.

**Comment by nicholassinggih** [comment]
The PDFs I'm rendering mostly contain text as majority of the content. 

The same PDFs are displayed perfectly in an iframe on IE + Adobe plugin, or IE + Foxit plugin. This is despite the iframe's dimensions were set to 360 x 400 (much smaller than the actual size). While on Chrome, using both the default viewer and PdfViewer extension, they look really distorted.

Adobe and Foxit use their own engine to render the PDF, while most Chrome extensions translate the PDF contents into html elements. Problem is, Adobe & Foxit draw their whole interface on a different layer on top of the html, disabling my application from displaying context menu and other things over the PDFs. 

I'm still hoping I can use pdf.js for my app. But right now, I'm forced to try a different solution.

**Comment by fkaelberer** [comment]
> The PDFs I'm rendering mostly contain text as majority of the content.

@nicholassinggih The pdf you provided contains a (scanned?) jpeg image in the background. The text that you can select in the document is an invisible text overlay.
The images are downscaled by the browser (not by pdf.js's javascript code), so image quality may vary with the browser or OS. Firefox and Chrome (maybe others too) do a terrible job of downscaling the big images to small canvases, thus causing the bad image quality.

I pushed a commit to https://github.com/fkaelberer/pdf.js/commit/913d3bcadba828c1f3a73f17b0c029016c244259, which downscales the jpegs in multiple steps, in each step with a factor of <= 2x. As a result, the readability is increased a lot, see images below.

I did not open a pull request, though, because the code is unfinished and not tested much. Anyone, please feel free take and improve the code.

- [x] better readabilty / image quality
- [ ] figure out if / how it works if image does not fill the whole canvas
- [ ] Fix blurry issue1350
- [ ] Bonus: deduplicate the downscaling code
- [ ] Check out if blurryness of some images can be reduced (red font in issue2642 looks better without this patch)

At 50%:
![before-after50](https://cloud.githubusercontent.com/assets/4624768/13541447/8f5c528c-e25c-11e5-90ca-13ae4951cd44.png)

At 70%:
![before-after70](https://cloud.githubusercontent.com/assets/4624768/13541520/07582f90-e25d-11e5-8b03-182b3e052d40.png)

**Comment by nicholassinggih** [comment]
Hi Felix, 

Thank you very much for this. I've tested your new code and it does give a much better result, just as shown in your screenshots. Bravo to you!! 

Forgive me if my next questions sound silly, but I just want to clarify if I understand this correctly. About the text vs jpeg image thing, are you saying that the PDF that I provided actually only contain jpeg of a scanned paper with text on it? Therefore, it doesn't actually contain text data and it was rendered as an image which in turn was scaled down by the browser? 

Should I close this thread, or let either Yuri or Tim to close this?

**Comment by Rob--W** [comment]
> About the text vs jpeg image thing, are you saying that the PDF that I provided actually only contain jpeg of a scanned paper with text on it?

Yes. That's why I slapped the jpeg label on this ticket.

> Therefore, it doesn't actually contain text data and it was rendered as an image which in turn was scaled down by the browser?

It does contain text data (with a transparent color, probably for text selection), but what you see (and what is printed) is the (scaled) image.

> Should I close this thread, or let either Yuri or Tim to close this?

The (legitimate) issue hasn't been resolved yet, so I'd keep the issue open.

**Comment by nicholassinggih** [comment]
> It does contain text data (with a transparent color, probably for text selection), but what you see (and what is printed) is the (scaled) image.
I see. They ran OCR on the PDF, thus the transparent/invisible text data. But, if they hadn't ran OCR on it, I'm guessing it would just contain a jpeg image with no text. 

Thank you both for your help. Really appreciate it.

**Comment by yurydelendik** [comment]
That's a first time I see scanned data was packaged as JPEG (vs JBIG2 or CCITT). We probably didn't see this issue early since it's probably a rare case. As mentioned in https://github.com/mozilla/pdf.js/issues/7041#issuecomment-192496865 above, we already do it for most of the images except JPEG (e.g. https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L2081) Trade-off is more memory and CPU is used. If we will decide to move decoding of the JPEG to the worker side then we don't have to worry about code duplication.

**Comment by fkaelberer** [comment]
> That's a first time I see scanned data was packaged as JPEG (vs JBIG2 or CCITT). We probably didn't see this issue early since it's probably a rare case.

It does not only affect text, but also images
From #2739:
![nvidia_resized](https://cloud.githubusercontent.com/assets/4624768/13614762/5635a7d8-e572-11e5-99a9-e4f568e14dc5.png) ![nvidia_resampled](https://cloud.githubusercontent.com/assets/4624768/13614764/5a79c252-e572-11e5-823b-a302e14734b6.png)

http://www.ikea.com/at/de/assembly_instructions/rakke-kleiderschrank__AA-808506-1.pdf (notice the thumbnails)
![ikea_resize](https://cloud.githubusercontent.com/assets/4624768/13614811/88774d14-e572-11e5-9e18-601f0d2a72df.png) ![ikea_resample](https://cloud.githubusercontent.com/assets/4624768/13614816/8b809a60-e572-11e5-9695-4bb54da6c9fa.png)

**Comment by nicholassinggih** [comment]
Hi Felix or anyone, 

Is there a chance that you could implement a better downsampling algorithm in the paintJpegXObject methods? Some of my users are still complaining about the quality of the images. Even with the gradual scaling that Felix added, scanned images (JPEG) of handwritten documents are sometimes too faded or blurry too read. 

[Volume 1 of 4 43_Redacted.pdf](https://github.com/mozilla/pdf.js/files/647407/Volume.1.of.4.43_Redacted.pdf)
[Volume 1 of 4 6_Redacted.pdf](https://github.com/mozilla/pdf.js/files/647408/Volume.1.of.4.6_Redacted.pdf)


This is all I know about the user's machine:
Windows 7 SP1 
Browser: Google Chrome  54.0.2840.71 m
I used Felix's version https://github.com/fkaelberer/pdf.js/commit/913d3bcadba828c1f3a73f17b0c029016c244259
Graphics card: GeForce GT610
Monitor's resolution 1680 x 1050


I am currently trying to implement Lanczos or sinc downscaling algorithm in the paintJpegXObject. But I don't know how bad it will affect the performance, and not sure if it is going to fix the problem.

Really appreciate your help.

**Comment by yurydelendik** [comment]
> But I don't know how bad it will affect the performance, and not sure if it is going to fix the problem.

@nicholassinggih if you will find out algorithm that we can use for downsampling and it works, we will provide pointers on how to improve its performance (e.g via asm.js).

**Comment by nicholassinggih** [comment]
@yurydelendik I've tried implementing bicubic interpolation instead to scale down the jpegs. The result is not as good as @fkaelberer 's solution, not to mention that the performance is also slower. 

This problem proves to be the most difficult challenge in the process of developing the current application. I'm currently looking into the possibility of just creating a modified copy of the PDF file with all the pages and images resized to the desired dimensions. As my users don't actually dynamically zoom in and out when viewing the pages, this could work.

**Comment by natarajnattu** [comment]
var options = options || {
        scale: 1
 };

increase the scale you can see improved clarity

**Comment by may583** [comment]
😀

เมื่อ 21 ธ.ค. 2017 14:11 "Nataraj" <notifications@github.com> เขียนว่า

**Comment by may583** [comment]
https://accounts.firefox.com/signin
may33153

**Comment by Wotzhs** [comment]
hey guys, not sure if this is applicable in this case, i have been getting blurry text as well from the rendered canvas, and i have been wondering if this is rather **html5 canvas issue** rather than pdf.js, till i stumbled on:
https://www.html5rocks.com/en/tutorials/canvas/hidpi/

before accounting for `window.devicePixelRatio`. the pdf looks like this:
<img width="496" alt="23" src="https://user-images.githubusercontent.com/18510209/36137225-2eeab58a-10cf-11e8-95f9-685bc8bdbed1.PNG">
after accounting for `window.devicePixelRation`, the pdf looks like this:
<img width="470" alt="24" src="https://user-images.githubusercontent.com/18510209/36137238-4115b3fe-10cf-11e8-96e6-7aa227d9a159.PNG">

**Comment by yurydelendik** [comment]
@Wotzhs yes, pdf.js demo viewer relies on devicePixelRatio to increase pixel density per pixel via CSS.

**Comment by c-e-p-x-u-o** [comment]
Is it a dup for #2750?

**Comment by nowherenearithaca** [comment]
@yurydelendik I am confused.  Are you saying that the existing pdfjs should handle the devicePixelRatio as that article suggested?  If so, you don't happen to know when it started doing that, do you?  I am seeing blurriness with wix where they seem to be using pdfjs-dist version 2.305 from Feb 1, 2018, and wondering if they need to either upgrade or make use of the devicePixelRatio stuff in their use of the library.
