### ISSUE TITLE
Zoom Dropdown "customScaleOption" option element value is blank until a custom value is selected

### ISSUE THREAD

**Issue by matsteen** [mozilla/pdf.js#7065]
Browser: Safari 9.0.3 on OSX Yosemite

On initial load, with a fresh cache, the zoom dropdown has a blank value right under the "Page Width" option:

![screen shot 2016-03-04 at 3 50 52 pm](https://cloud.githubusercontent.com/assets/17658819/13543569/4b7b8870-e221-11e5-89a9-fd86a35e240c.png)

Upon closer inspection is appears that PDFjs is trying to use the CSS style "display: none" on this element: `<option id="customScaleOption" title value="custom"></option>,` which isn't supported in Safari. In other browsers, this option element disappears from the view when "display: none" is used.

**Comment by Snuffleupagus** [comment]
Note that we since quite some time attempt to hide the `customScaleOption` option *twice*, using both HTML and CSS; please see https://github.com/mozilla/pdf.js/blob/e3e7ccc3e266c6c59355ccdfba15bae46bfc9fd7/web/viewer.html#L270 and https://github.com/mozilla/pdf.js/blob/e3e7ccc3e266c6c59355ccdfba15bae46bfc9fd7/web/viewer.css#L733-L735

There isn't much else that can be done, in PDF.js, so if this isn't enough to hide the `customScaleOption` option that should be considered a bug in the Safari browser itself and reported to its developers instead.

**Comment by timvandermeij** [comment]
Closing since this should be reported to Safari instead.
