### ISSUE TITLE
Text not displaying at all, images are fine

### ISSUE THREAD

**Issue by danlester** [mozilla/pdf.js#7074]
I've tried multiple browsers and the latest version of pdf.js. The text in the PDF does not show at all, but images and shapes appear fine.

Here is the PDF:

[EE-Summer-2015-for-web Original.pdf](https://github.com/mozilla/pdf.js/files/164771/EE-Summer-2015-for-web.Original.pdf)

And a screenshot from the pdf.js example viewer:

![screen shot 2016-03-09 at 08 56 27](https://cloud.githubusercontent.com/assets/786238/13630093/316c11ae-e5d5-11e5-82ec-64b06769166d.png)

The PDF as shown in Preview on a Mac:

![screen shot 2016-03-09 at 08 56 41](https://cloud.githubusercontent.com/assets/786238/13630099/3b3b0b04-e5d5-11e5-8e86-0ba6fd6003b5.png)

Sorry that I don't have any insight at all at the moment! Please let me know if you need anything else.

Thanks,

Dan

**Comment by timvandermeij** [comment]
I can reproduce this using Arch Linux x64, Firefox 44.0.2 and the latest PDF.js development version. The following console message indicates the error:

`Warning: Error during font loading: invalid array length`

**Comment by Snuffleupagus** [comment]
The errors originate in [`sanitizeGlyph`](https://github.com/mozilla/pdf.js/blob/4784863ef7ef3198631cb3299fff16a0843f7a88/src/core/fonts.js#L1529), and are caused by trying to write *outside* of the `dest` Uint8Array.
This suggests that the `loca`/`glyf` tables most likely contain bad font data, which we're not able to correctly detect and recover from. (Note that just catching the errors does *not* help here.)

It's interesting to note that every font in the PDF file look weird. E.g. the TrueType font tables all have completely bogus checksums, which doesn't inspire a lot of confidence in the validity of the font data.

**Comment by Maxiride** [comment]
Having the same issue here, some pages are without text but it is still selectable.

**Comment by Snuffleupagus** [comment]
@brendandahl Do you perhaps have time to look into this, since there's now multiple issues (see #9263 as well) affected by this? Unfortunately https://github.com/mozilla/pdf.js/issues/7074#issuecomment-198950374 is about as far as I got here.

**Comment by zhaowanhua** [comment]
I got same issue and have you fixed the issue?

**Comment by brendandahl** [comment]
> I got same issue and have you fixed the issue?

@zhaowanhua Please file a new issue, yours is probably not the same.

**Comment by zhaowanhua** [comment]
So sorry, I had choosed another way out.
