### ISSUE TITLE
Investigate issue6961 test due to its frequent test failures 

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#7112]
The recently affected runs:
- https://github.com/mozilla/pdf.js/pull/7053#issuecomment-201367496
- https://github.com/mozilla/pdf.js/pull/7111#issuecomment-201379121
- https://github.com/mozilla/pdf.js/pull/7098#issuecomment-199837181
- https://github.com/mozilla/pdf.js/pull/7069#issuecomment-194974581

**Comment by yurydelendik** [comment]
Test is disabled to save efforts/resources on other pull requests.

**Comment by timvandermeij** [comment]
Yes, it seems to fail quite often, so it's good to disable it for now. This file came from https://github.com/mozilla/pdf.js/commit/07e1ad40a2c8cb4d6e46053fe2714d57f2fbca01. If we can find out what's wrong with it, I might be able to provide a new file generated by the same tool, as I provided the current file too.

**Comment by Snuffleupagus** [comment]
Should we attempt to re-enable this test-case now, or should we simply close this as WONTFIX?

**Comment by timvandermeij** [comment]
I'd say we can try enabling it since many fixes were made since this issue was originally opened. If we run the test suite with it a couple of times and it passes, we're safe to re-enable it. If not, I'm not sure what is wrong with it and we can close this issue. It might be that all the test framework fixes and performance fixes have actually fixed the problems we encountered before in the meantime.
