### ISSUE TITLE
Function to get PDF file details

### ISSUE THREAD

**Issue by JohnEwen** [mozilla/pdf.js#7120]
I would like a simple function that can extract the number of pages, width and height of a PDF document using pdf.js but avoiding the use of promises.

The following works:

	PDFJS.getDocument(PDFDoc).then(function(pdf){
		pdf.getPage(1).then(function(page) {
			var v=page.getViewport(1);
			PAGES=pdf.numPages;
			WIDTH=v.width;
			HEIGHT=v.height;
		});
	});

but I would like the values to be immediately available without having to bury all the rest of my code in a function called after HEIGHT has been calculated.

**Comment by Snuffleupagus** [comment]
The PDF.js API is written in order to allow ranged/chunked loading of PDF files, which is necessary to be able start rendering without having to wait for the entire PDF file to be downloaded first.
In order to achieve that, all of the API methods must be *asynchronous*, which is why Promises are used heavily in PDF.js.
It's neither possible, nor wanted, to convert parts of the API to be synchronous. Also, if anything the API/Core parts of PDF.js have only been getting more asynchronous over time.

Closing as answered, and out of scope for the library.
