### ISSUE TITLE
Simple resizing PDF without toolbars

### ISSUE THREAD

**Issue by JohnEwen** [mozilla/pdf.js#7121]
I want to display PDF documents on my Web site that  automatically resize to fill the available width of the iframe but show no toolbars and do not respond to keyboard shortcuts that allow the document to be printed etc. I have achieved much of what I need by modifying viewer.js as can be seen here:

http://www.u3a.nz/wp.htm

But my version of viewer.js is full of unwanted code. I know I can go through it and take out the redundant code but this can be a lengthy exercise so I am hoping that someone may have done it already or possibly built a simple viewer that supports resizing.

It may be worth while explaining that the Web content is to be created by many different elderly (over 65) users who have no skills with HTML editors but can easily use a word processor to create PDF files. This allows me to create responsive pages (at least horizontally if not vertically) very easily. I have, of course, built a fully responsive site

http://www.u3a.nz

but this one requires users to edit their files with an HTML editor and this is proving too difficult.

**Comment by Snuffleupagus** [comment]
Given your use case, I'd suggest that you look into using the viewer components instead, since they are intended to simplify building a custom viewer based on the PDF.js API. In this case, the `simpleviewer` is probably most relevant, please see the examples in https://github.com/mozilla/pdf.js/tree/master/examples/components.

Closing as answered.
