### ISSUE TITLE
Suggestion - Render two or more PDF files in one viewer

### ISSUE THREAD

**Issue by lucasscarduelli** [mozilla/pdf.js#7139]
Hello,

My suggestion is that the API have possibility set multiple PDF files to render a one viewer by the input sequence.

**Comment by timvandermeij** [comment]
You can have multiple PDF instances (see e.g. https://github.com/mozilla/pdf.js/blob/master/test/unit/api_spec.js#L793) or open another document in an existing instance. You name a custom use case that is not applicable for the majority of the PDF.js users nor the PDF.js library, so that should be implemented in a custom solution. It does not have much to do with the API, but more with the viewer you're using. Closing as answered.
