### ISSUE TITLE
PDF from cnki.net not opening

### ISSUE THREAD

**Issue by berricks** [mozilla/pdf.js#7145]
Link to PDF file (or attach file here):
[111.pdf](https://github.com/mozilla/pdf.js/files/199967/111.pdf)

Configuration:
- Web browser and its version:  chrome latest, firefox 45
- Operating system and its version:  Mac OSX 10.11.3
- PDF.js version:  demo version
- Is an extension: 

Steps to reproduce the problem:
1. Try to open the file in the demo pdf.js found here https://mozilla.github.io/pdf.js/web/viewer.html 
2. Notice only white pages are rendered

What is the expected behavior? (add screenshot)
The file should be rendered by pdf.js

What went wrong? (add screenshot)
The file does not render text, only white pages.   This file opens in mac preview and Adobe Acrobat on a mac

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This is an issue with the JBIG2 image parser, and the (first) failure occurs because `referenceBitmap === undefined` at [jbig2.js#L364](https://github.com/mozilla/pdf.js/blob/65de3d62680c419618589daa337c39320ae4ff3c/src/core/jbig2.js#L364).

Either the JBIG2 image itself is corrupt, or our code is lacking support for certain JBIG2 features, or a combination of both.
