### ISSUE TITLE
Presentation mode of PDF viewer in iFrame

### ISSUE THREAD

**Issue by sanjivani2208** [mozilla/pdf.js#7163]
We have embedded pdf viewer in our application with the help of iFrame tag. But presentation mode is shown as disabled. We require presentation mode to be enabled for the application. Any help for same is appreciated.

**Comment by timvandermeij** [comment]
If presentation mode is disabled, it is because it is not supported for the browser you are working in, for example some older IE versions. See e.g. https://github.com/mozilla/pdf.js/pull/5525/files for how this was introduced. There is nothing we can do about that as the experience for those browsers would just be too bad. Upgrade to a recent browser version to resolve that.

Closing as incomplete because not all information from https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is provided, most notably a link to the custom solution and the browser information.

**Comment by Snuffleupagus** [comment]
Besides what @timvandermeij said, please remember that you also need to set the `allowfullscreen` attribute on the `<iframe>`.

**Comment by sanjivani2208** [comment]
Browser: Chrome Version 49.0.2623.110 m
OS: Win 7
PDF.js version: 1.0.1194
