### ISSUE TITLE
Highlight not working properly in pdf.js

### ISSUE THREAD

**Issue by SaranrajR** [mozilla/pdf.js#7227]
Here, i have attached the PDF, that PDF document contains "Nudi" as an embedded font. Its appear to render in correct manner, but if i select / highlight the text, the problem will occur. 

Link to PDF file (or attach file here):
[sample_pdf.zip](https://github.com/mozilla/pdf.js/files/227873/sample_pdf.zip)

Configuration:
- Web browser and its version: Mozilla / Chrome
- Operating system and its version: Windows 7
- PDF.js version: PDF.js-1.2.109-dist

What is the expected behavior? (add screenshot)
![correct_img](https://cloud.githubusercontent.com/assets/17423938/14673906/4a1d3dbc-071e-11e6-9c54-ca38b9afe3ac.png)

What went wrong? (add screenshot)
![error_img](https://cloud.githubusercontent.com/assets/17423938/14673852/088d3460-071e-11e6-80d4-c8567b49cf0a.png)

Note : For english font PDF, i am getting proper selection / Highlighted text.

**Comment by Snuffleupagus** [comment]
WFM, when I open the PDF file with the latest version (`1.4.258`) of PDF.js: http://mozilla.github.io/pdf.js/web/viewer.html.

As outlined in (the fourth paragraph) of https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, since this appears to be an issue with a custom PDF.js implementation, please provide access to a working example online.

**Comment by SaranrajR** [comment]
Thanks for your help. i found a solution for my issue .
ie ***.css was missing while i replacing file.
