### ISSUE TITLE
Option to disable showing of PDF annotations

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#7282]
is there an option for PDF.js not to show annotations embedded in the pdf?

**Comment by yurydelendik** [comment]
There is no such option. However depending on type of annotation some of them placed into operator list, some of them in the separate request.

If you need a workaround, disable getting of annotations at https://github.com/mozilla/pdf.js/blob/master/src/core/document.js#L320

**Comment by chitgoks** [comment]
thanks yury. hope there'll be an option in the next update. this would come in handy.

**Comment by yurydelendik** [comment]
> this would come in handy.

please explain why -- this will help to prioritize the issue.

**Comment by chitgoks** [comment]
ive created an annotation layer on top of every pdf.js page amd i figure that while ive extracted the annotations in the pdf, saves to darabase and shown them in my annotation layer, by not showing them in the pdf.js layer, the resource consumption may lessen

at least that is what i think

**Comment by messman** [comment]
> please explain why -- this will help to prioritize the issue.

The project I'm working on retrieves annotations separately so that they can be edited on top of the page and saved through a web service. For this reason, we don't want PDF.js to render the annotations because we will be showing them on our own.

**Comment by chitgoks** [comment]
just wish to follow up, will this be considered?

please advise.

**Comment by timvandermeij** [comment]
I think I'm fine with this if it can be made a preference like https://github.com/mozilla/pdf.js/blob/master/web/default_preferences.json#L12.

**Comment by singhkaushlendra** [comment]
Is there any update regarding the above issue ?? I also want to disable rendering of annotations by default.

**Comment by lpillonel** [comment]
Also interested in disabling the annotation. Could be in preferences or maybe as a page render param

**Comment by bdely** [comment]
I would also be interested in an option to disable the annotation layer. the one specifically that i would like to not render would be hyperlinks. because for security reasons we do not what the user to be able to click on the links.
currently i am just setting the annotationLayer class to display: none.

**Comment by jscher2000** [comment]
Possibly a special case, but we had a complaint on SuMo that it is distracting to have an annotation appear on **hover** for a highlight annotation when highlighting has been used liberally in a document. https://support.mozilla.org/questions/1246527

**Comment by vlastimilmaca** [comment]
Maybe show popup only if there is any "Contents" or "RichText" ? That's what Acrobat does.

**Comment by harryMamani** [comment]
> > please explain why -- this will help to prioritize the issue.
> 
> The project I'm working on retrieves annotations separately so that they can be edited on top of the page and saved through a web service. For this reason, we don't want PDF.js to render the annotations because we will be showing them on our own.


Hello,
could you please tell me how this is done by putting the annotations on another layer, did you use any other tools? or some additional library option.

Thank you

**Comment by chitgoks** [comment]
@harryMamani  you mean like this?

https://youtu.be/g2YAn-Yvlss

**Comment by kevinbeal** [comment]
I'm assuming the `disableAnnotationLayer` option is not available yet or this issue would be closed.

I'm looking to implement my own annotation layer, but some annotations are rendered directly in the canvas (e.g. highlighting). Is there any place on the API surface of the display layer of PDF.js that I can use to prevent this behavior? Are there any workarounds at all?

**Comment by kevinbeal** [comment]
@chitgoks 

> [youtu.be/g2YAn-Yvlss](https://youtu.be/g2YAn-Yvlss)

How'd you get annotations not to show?

**Comment by chitgoks** [comment]
> @chitgoks
> 
> > [youtu.be/g2YAn-Yvlss](https://youtu.be/g2YAn-Yvlss)
> 
> How'd you get annotations not to show?

you can listen to the event when the page was created and remove or hide the annotation layer.

**Comment by kevinbeal** [comment]
> you can listen to the event when the page was created and remove or hide the annotation layer.

I can simply not call `AnnotationLayer.render(options)` which means a small subset of annotations are not separately rendered inside a `div`, but the other annotations (e.g. ink, polyline, square, etc) are painted directly onto the canvas element. Your video makes it looks like these other annotations are also not rendered by PDF.js, but separately rendered by you. I also want to separately render them.

Am I misunderstanding you that you successfully got all annotations to stop being rendered by PDF.js?

**Comment by chitgoks** [comment]
ahh.ok i forgot about that behavior and solution. that video happened when there was no annotationLayer yet.

yep, its a separate canvas.

**Comment by Snuffleupagus** [comment]
Note that, as already explained in https://github.com/mozilla/pdf.js/issues/7282#issuecomment-216417923, some Annotations can *only* be rendered onto the page itself rather than being placed in the AnnotationLayer (in the viewer).
Hence it's *somewhat* questionable, at least to me, that we really want to add an option to disable Annotation-rendering since that could lead to *more* user confusion/bugs reports; not to mention the added complexity that this would add for a minor feature.

All-in-all, I'd probably suggest WONTFIX for this (old) issue.

**Comment by patkujawa-wf** [comment]
If it's a preference that defaults to enabled, I imagine most bug reports will be from consumers who choose to disable annotations. Since those consumers (myself included) are already forced to do ugly workarounds, I imagine we'd be able to fallback to those workarounds if some annotations did show up unintentionally.

In other words, it may be a minor feature to some, but it's essential to other consumers and the current workarounds are not great. Please reconsider.

**Comment by kevinbeal** [comment]
In order to do this today, you need to strip out the annotations prior to handing it over to PDF.js. You can do this with a variety of server-side libraries, or with PDF-lib.js (a separate dependency). The PDF-lib.js API is simple.

Here's an issue showing how to strip annotations out:
https://github.com/Hopding/pdf-lib/issues/191

Here's an issue showing how to add annotations:
https://github.com/Hopding/pdf-lib/issues/529
