### ISSUE TITLE
TypeError: database.files.shift is not a function

### ISSUE THREAD

**Issue by Azgaroux** [mozilla/pdf.js#7290]
Link to PDF file (or attach file here): NA

Configuration: 
- Web browser and its version:Mozilla 46.0
- Operating system and its version: Win7 64bit
- PDF.js version: 1.4.20 b15f335
- Is an extension: no

Steps to reproduce the problem: NA
1. 
2.

What is the expected behavior? (add screenshot) 
PDF file is not rendered in the viewer at all. However, page number is displayed and can toggle the previous/next page, document properties is properly displayed, find feature works too.

What went wrong? (add screenshot)
I don't know, really.. I'm getting this error on firebug: 'TypeError: database.files.shift is not a function'. I configure it on my webapp and place it on an iframe; Calling the viewer via cntrler and passing the url and doctype along with it and using another cntrler to pass the url and doctype to generate the pdf.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): NA

**Comment by Snuffleupagus** [comment]
WFM, in the latest version of PDF.js (which as of this writing is `1.5.230`), when using the demo viewer: http://mozilla.github.io/pdf.js/web/viewer.html.

Since this appears to be an issue with a custom deployment of PDF.js, as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, you need to provide a link to a *working* example. Otherwise it's virtually impossible for anyone to provide help here.

**Comment by timvandermeij** [comment]
Closing as incomplete until the information requested above is provided.
