### ISSUE TITLE
page.getTextContent() loses fontName transitions but viewer renders correctly

### ISSUE THREAD

**Issue by gerrysc** [mozilla/pdf.js#7297]
Link to PDF file (or attach file here):
[KGR2304form.pdf](https://github.com/mozilla/pdf.js/files/252741/KGR2304form.pdf)

Configuration:
- Web browser and its version: Iceweasel 38.6.0
- Operating system and its version:Debian GNU/Linux 8.3 (jessie)
- PDF.js version:1.4.44
- Is an extension:

Steps to reproduce the problem:
1. The problem screenshots below show the result of copying KGR2304form.pdf, testfont.css, testfont.html, testfont.js to viewer Web folder and initiating testfont.html.
[testfont.css.txt](https://github.com/mozilla/pdf.js/files/252765/testfont.css.txt)
[testfont.html.txt](https://github.com/mozilla/pdf.js/files/252766/testfont.html.txt)
[testfont.js.txt](https://github.com/mozilla/pdf.js/files/252767/testfont.js.txt)

What is the expected behavior? (add screenshot)
The viewer correctly renders the bold text.
![screenshot-from-viewer](https://cloud.githubusercontent.com/assets/7339358/15081227/43a6a1e6-1405-11e6-9f74-0488f1e2b6a0.png)

What went wrong? (add screenshot)
pdf.js page.getTextContent() does not show transition in fontName between normal and bold items.
![screenshot-from-testfont html-1-unsorted](https://cloud.githubusercontent.com/assets/7339358/15081662/3bfb7df2-1407-11e6-80d7-97a06c951187.png)
![screenshot-from-testfont html-2-sorted](https://cloud.githubusercontent.com/assets/7339358/15081663/3c01a10a-1407-11e6-903b-6d1d3d81d44f.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  Used viewer from https://mozilla.github.io/pdf.js/getting_started/
and copied v1.4.44 from existing node.ja installation.

**Comment by Snuffleupagus** [comment]
Using http://brendandahl.github.io/pdf.js.utils/browser/ to browser the contents of this PDF file, you'll find that (most of) the regular *and* bold text actually uses the exact *same* font.

The explanation for why some parts of the text are bold, and others are not, is that the PDF file utilizes `Text rendering modes` to simulate bold text.
For the normal text `0 Tr` (== Fill) is used, and for the bold text `2 Tr` (== Fill, then stroke) is used; please refer to section 9.3.6 of the PDF specification[1].
By using the same colour for both the fill and stroke operations, this thus create the appearance of a bold font. This seems like a very uncommon way the create a bold font, and I cannot remember seeing it before, since virtually all other PDF files uses separate fonts for regular and bold text.

This unfortunately means that the issue as stated, i.e. `page.getTextContent() loses fontName transitions but viewer renders correctly`, isn't valid since there PDF file *does not* actually change the font name.

One way to solve this issue could be to also add the current `Text rendering mode` to the data returned by `getTextContent`, e.g. something along these lines: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-7297
@yurydelendik Does the above seem reasonable? If so, I'll submit a PR with tests.

---
[1] http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#G8.1772271.

**Comment by yurydelendik** [comment]
Thank you for analysis. I don't think it's worth addressing this. We return this information via getOperatorList. This is not a text selection or text extraction use case. Closing as won't fix.

**Comment by gerrysc** [comment]
Thank you Snuffleupagus for your expert analysis.  This has helped address some of my imperfect understanding of PDF operations.  Thank you yurydelenik for your suggestion.  Looking at page.getOperatorList(), I see that I can get the data I need to simplify my parsing requirement.
My problem is solved.

**Comment by gerrysc** [comment]
One further point for anyone coming in later.  Because the font has not changed, pdf.js, optimizes the stream by consolidating contiguous text elements.  There is some work to do to isolate the bold items in a run of free form text returned from getTextContent().
