### ISSUE TITLE
missing all spaces on page 1 (text selection)

### ISSUE THREAD

**Issue by ldenoue** [mozilla/pdf.js#7310]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome 51.0.2704.36 beta (64-bit)
- Operating system and its version: Mac OS X El Capitan 10.11.3 (15D21)
- PDF.js version: online viewer (May 10, 2016)
- Is an extension:

Steps to reproduce the problem:
1. copy text from page 1
2. paste somewhere else: all words touch, without any space

What is the expected behavior? (add screenshot)
need to add spaces between words.
[jansen_public_queries.pdf](https://github.com/mozilla/pdf.js/files/257334/jansen_public_queries.pdf)

What went wrong? (add screenshot)
no spaces were found between words.
Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by ldenoue** [comment]
I think there's a fix for this problem.
On the attached image rendering the first page of this PDF, you can notice that the bounding boxes of the text items seem wider than the last printed character, e.g. "g " of searching has an extra empty space after. It means that the widths are computed correctly (textMatrix is properly updated in the code), but it doesn't add a space when it should. And it should depending on the current value of charSpacing.
So in https://github.com/mozilla/pdf.js/blob/070f2d32ada10bd877bdfd6cae2a2179a20a9930/src/core/evaluator.js#L1334  after the line textChunk.str.push(glyphUnicode); we should see if the current charSpacing is greater than textChunk.spaceWidth * SPACE_FACTOR.

If so, we should add a space to the str array of characters, as follows:
if (charSpacing >= textChunk.spaceWidth * SPACE_FACTOR) {
            textChunk.str.push(' ');
}

Laurent.
![screen shot 2016-05-10 at 8 50 06 pm](https://cloud.githubusercontent.com/assets/149561/15158619/0df90720-16f1-11e6-862f-c972e2ace352.png)

**Comment by timvandermeij** [comment]
We have quite a lot of text layer spacing issues open now. Perhaps it's indeed time to revisit the `SPACE_FACTOR` constant handling.

**Comment by luxferoo** [comment]
PDF is shown as html page.Each sentence is a div , so when we copy a text  actually we copy divs and between each div and other  there is no space and that's why the past contain missing spaces.

**Comment by brookhong** [comment]
@luxferoo It depends.

[p16.pdf](https://github.com/mozilla/pdf.js/files/1663608/p16.pdf)

I attached this sample to show that some documents are rendered word by word, but not exactly, sometimes word is getting split.
This issue is really annoying, which makes text layer completely useless.

![image](https://user-images.githubusercontent.com/288207/35384364-07669886-0200-11e8-9b33-411e43a0d827.png)

**Comment by DJArty** [comment]
Confirm the problem with spaces.
This is my sample pdf.
And no spaces in pdfjs viewer / renderer 
Copy/paste like one big word.
[Testpdfsandwich.pdf](https://github.com/mozilla/pdf.js/files/1736145/Testpdfsandwich.pdf)

**Comment by Maheshme** [comment]
Hey @timvandermeij any update on this, I am facing this issue too.

**Comment by Andrew3005** [comment]
also search works incorrect with this issue

**Comment by Andrew3005** [comment]
any improvements [about it](https://github.com/mozilla/pdf.js/issues/7310#issuecomment-218258040) @timvandermeij 
I have issues with hebrew

**Comment by wesinator** [comment]
Encountering this with https://www.ncsc.gov.uk/files/NCSC%20advisory%20-%20CNI%20Supply%20Chain.pdf page 13

Firefox 71
![ff71_pdf_selectedtext_no_spaces](https://user-images.githubusercontent.com/5124946/71784085-43bcea00-2fbd-11ea-830f-d04c0c9a3eac.png)

the spaces appear to be there but aren't even selectable in the span section, hence it only selects the text

**Comment by valentas-kurauskas** [comment]
I have the same problem, spaces are missing in copied text pdf.js Firefox 75.0, Ubuntu 18.04. Copying works correctly with Evince on Ubuntu and Edge 44 on Windows 10. The document is produced by ABBYY Fine Reader.

 http://klevas.mif.vu.lt/~valentas/pdf_js_spaces.pdf.

**Comment by Manisha333** [comment]
> https://github.com/mozilla/pdf.js/blob/070f2d32ada10bd877bdfd6cae2a2179a20a9930/src/core/evaluator.js#L1247-L1248
> 
> By fixing someone replace all space character in chunk, so repair to
> `str: (normalizeWhitespace ? replaceWhitespace(bidiResult.str) + ' ' : bidiResult.str),`
> Actually, it work for me

But the chunk division is not proper. The complete word is placed into multiple span tags

**Comment by Manisha333** [comment]
> Encountering this with https://www.ncsc.gov.uk/files/NCSC%20advisory%20-%20CNI%20Supply%20Chain.pdf page 13
> 
> Firefox 71
> ![ff71_pdf_selectedtext_no_spaces](https://user-images.githubusercontent.com/5124946/71784085-43bcea00-2fbd-11ea-830f-d04c0c9a3eac.png)
> 
> the spaces appear to be there but aren't even selectable in the span section, hence it only selects the text
> 
> Chrome's viewer has spaces, as expected

No even the chrome viewer is facing the issue

**Comment by judell** [comment]
We are running into this problem using ABBYY, as reported elsewhere in this issue. 

I have noticed the following difference when using PDF.js on a PDF that was OCRd by both ABBYY and Acrobat Pro:

![image](https://user-images.githubusercontent.com/46509/91077109-5ab85700-e5f5-11ea-9831-d09841bc0066.png)

I'm not sure what "composite" means but it seems related to font encoding, PDF.js ends up on different code paths when composite is true vs false. Does this suggest a possible workaround for using PDF.js on ABBYY OCR output? (I'm also asking ABBYY the same question.)

**Comment by Joozty** [comment]
any update on this issue? Thanks :)

**Comment by lbittner-pdftron** [comment]
+1 would like to see a solution to this issue

**Comment by calixteman** [comment]
I think I understand the problem. The first line of text in the pdf is:
`(Searchin)Tj 0.3328 Tc 4.204 0 Td (g)Tj 0 Tc 0.9438 0 Td (th)`
The width of "Searchin" is exactly 4.204 so moving here (with `Td`) will put the "g" at the right place but because of the Tc a "space" is added after the "g".
The width of g+space is exactly 0.9438.
So I think we shouldn't add a `charSpacing` for the last char here to have the exact string size:
https://github.com/mozilla/pdf.js/blob/f45ba02fd3b8b4cf54cec21579873d12926b640f/src/core/evaluator.js#L2190.
And here I think the way to compute advance is not correct:
https://github.com/mozilla/pdf.js/blob/f45ba02fd3b8b4cf54cec21579873d12926b640f/src/core/evaluator.js#L2320
For example, because of `Tc 4.204` we don't enter in the next `if` and we got a flush which is wrong.
So I think the advance should be computed: `advance = args[0] - args[1] - textContentItem.lastAdvanceWidth` to take into account the string we've before.
I tried this and ctrl+a+ctrl+c on the first page looks pretty good (except maybe an issue eol).
I need to test that everything is fine but it could be a fix.

**Comment by timvandermeij** [comment]
Fixed by #13257.

**Comment by valentas-kurauskas** [comment]
Thanks @calixteman!

**Comment by Reda-ELOUAHABI** [comment]
1- you need to normalize your css ,in my case I was using materialUI (mui) and this code worked as a charm :
` <ScopedCssBaseline>
      {/* The div the print*/}
      <div> ***** </div>
    </ScopedCssBaseline>`
2- make sure jspdf support the font family you are using, otherwise try to add the font to the jspdf call.
