### ISSUE TITLE
Use chrome.storage.sync instead of chrome.storage.local

### ISSUE THREAD

**Issue by csbenjamin** [mozilla/pdf.js#7325]
Is there any chance to use chrome.storage.sync to store the history? Thus the database will be stored on the cloud and it will be synced over all computer that the user is logged in into chrome with a google account. Doing that, if I have some online pdf document, something like www.example.com/myOnlinePdf.pdf, I can open in my office computer, start reading it and later, when I get home, I can open that pdf url and I can continue reading where I had stopped when I was in the office.

**Comment by timvandermeij** [comment]
Fixed in #7346.

**Comment by csbenjamin** [comment]
@Rob--W When will the PDF Viewer be updated? I mean, when will the chrome extension in chrome web store be updated?

**Comment by timvandermeij** [comment]
@csbenjamin Probably this week, according to https://github.com/mozilla/pdf.js/pull/7353#issuecomment-221425363.

**Comment by Rob--W** [comment]
@csbenjamin I published an update two days ago (1.4.55).

But after reading your ticket again, I see that the initial triage is incorrect. `chrome.storage` is only used for preferences, not for the database (so supporting `chrome.storage.sync` along with `chrome.storage.local` does not change the status of this bug): https://github.com/mozilla/pdf.js/blob/bd47440e799a4e769b38566ffd54cf390c22a17e/web/view_history.js#L71-L98

@yurydelendik @Snuffleupagus  In Firefox, the database is stored in transient `sessionStorage` instead of some persistent storage. This was introduced in #4559 (previously the settings were in prefs.js). Why did you switch to `sessionStorage` instead of `localStorage`?

it is not that difficult to offer a preference to save the database in synchronized storage instead of localStorage (we just need to be careful and not store data when Private/incognito mode is enabled). If there are no objections I don't mind sending a PR.

**Comment by Snuffleupagus** [comment]
> In Firefox, the database is stored in transient sessionStorage instead of some persistent storage. This was introduced in #4559 (previously the settings were in prefs.js). Why did you switch to sessionStorage instead of localStorage?

Please see the bugs referenced in the PR, i.e. https://bugzilla.mozilla.org/show_bug.cgi?id=986966 and https://bugzilla.mozilla.org/show_bug.cgi?id=865893, for the rationale.

**Comment by Rob--W** [comment]
> > In Firefox, the database is stored in transient sessionStorage instead of some persistent storage. This was introduced in #4559 (previously the settings were in prefs.js). Why did you switch to sessionStorage instead of localStorage?
>
> Please see the bugs referenced in the PR, i.e. https://bugzilla.mozilla.org/show_bug.cgi?id=986966 and https://bugzilla.mozilla.org/show_bug.cgi?id=865893, for the rationale.

Those bugs are about switching away from prefs.js, and do not provide any reason to specifically prefer sessionStorage over localStorage.

**Comment by Rob--W** [comment]
The `storage.sync` area quota is very limited, and I don't see a benefit in syncing per-document preferences. Therefore I'll close this.
