### ISSUE TITLE
How to save html file in demo?

### ISSUE THREAD

**Issue by ak9250** [mozilla/pdf.js#7349]
I tried saving the compressed.tracemonkey-pldi-09.html file in demo but it only downloads the compressed.tracemonkey-pldi-09.pdf by default. I can see there is html in the output when I go to the inspect element. How can I save that output as a html file? I tried doing right click save as on the output but that does not work.

**Comment by Snuffleupagus** [comment]
The default viewer doesn't have support for converting PDF files to HTML. (And note that PDF.js renders to `canvas` elements, which are "images" rather than HTML markup).
However, there is a SVG viewer example, please see https://github.com/mozilla/pdf.js/tree/master/examples/svgviewer, that can be used for this purpose.

Closing as answered.

**Comment by ak9250** [comment]
How can I use svgviewer for this purpose? 
Can it be run it locally? I was able to download html file through download button using default viewer but it shows loading icon divs instead of the text layer divs so it mostly empty file
