### ISSUE TITLE
Would be very useful if download button returns html file instead of pdf file

### ISSUE THREAD

**Issue by ak9250** [mozilla/pdf.js#7358]
The download button seems not very useful as it is right now because downloading the same pdf you upload seems counter intuitive after browser renders HTML, you would expect html output to download as a file. I have already been able to download html file but it has loading divs since data is not loaded for pages not rendered. If there is a way to render all pages when uploading file without scrolling, that would be great. even if zoom is set to 1% and data-loaded="true" text layer does not contain any content. I am mostly interested in text layer to get html file. 

here I explain functionalitly using another library which depends on pdf.js
http://stackoverflow.com/questions/37427502/how-to-get-loaded-html-download-file-with-javascript-jquery

**Comment by timvandermeij** [comment]
PDF.js is a renderer and viewer and not a tool to convert PDF to HTML. While that does partially happen in the background (I say partially because most of it is actually rendered onto a canvas, and only the text and annotation layers are actually HTML), the main intent it to show the contents of the PDF file. Therefore the download button does what one would expect: when reading a PDF file on the web, the download button gives you the file you're reading in PDF format for local storage.

Don't forget that the viewer that we provide is specifically designed for usage in Firefox or other web browsers. Custom implementations will most likely want to adjust this viewer to their needs.

Of course you can get the rendered HTML contents by just grabbing the page `div`s, but that is out of scope for the PDF.js project. You might get inspiration for doing this (and rendering all pages at once) from the examples: https://github.com/mozilla/pdf.js/tree/master/examples

Closing as answered.
