### ISSUE TITLE
Update Node to latest version on the bots

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#7369]
One bot is running 4.4.3, the other one is too old.

Then we can make use of modern JS features and improved standard libraries.

**Comment by timvandermeij** [comment]
Recent builds are now failing, most likely because of this. See https://travis-ci.org/mozilla/pdf.js/builds/170795365#L309 and https://github.com/npm/npm/issues/14232#issuecomment-252813224. We can safely update to the lastest `node` and `npm` packages available for the bots as I've been using the latest versions locally for a long time now and no incompatibilities have been found.

@yurydelendik Could you take care of this?

**Comment by yurydelendik** [comment]
Both bots are now at node v4.6.1 and npm v3.10.9

**Comment by timvandermeij** [comment]
Closing as fixed.
