### ISSUE TITLE
Text Layers ReferenceError

### ISSUE THREAD

**Issue by darkicex3** [mozilla/pdf.js#7371]
Objective:
Have text layers feature working.

I took the code from this tutorial : 
http://www.ryzhak.com/converting-pdf-file-to-html-canvas-with-text-selection-using-pdf-js/

Configuration:
- Google Chrome 50.0.2661.102 (64-bit)
- OS X El Captain 10.11.5
- PDF.JS 1.4.20

The complete code : 

```
<!DOCTYPE html><meta charset="utf-8">
<link rel="stylesheet" href="pdf.js/web/text_layer_builder.css" />
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="pdf.js/web/ui_utils.js"></script>
<script src="pdf.js/web/text_layer_builder.js"></script>
<script src="https://mozilla.github.io/pdf.js/build/pdf.js"></script>
<body>
  <div>
    <canvas id="the-canvas" style="border:1px solid black;"></canvas>
    <div id="text-layer" class="textLayer"></div>
  </div>
<script>
 
PDFJS.getDocument("test.pdf").then(function(pdf){
    var page_num = 4;
    pdf.getPage(page_num).then(function(page){
        var scale = 1.5;
        var viewport = page.getViewport(scale);
        var canvas = $('#the-canvas')[0];
        var context = canvas.getContext('2d');
        canvas.height = viewport.height;
        canvas.width = viewport.width;
 
        var canvasOffset = $(canvas).offset();
        var $textLayerDiv = $('#text-layer').css({
            height : viewport.height+'px',
            width : viewport.width+'px',
            top : canvasOffset.top,
            left : canvasOffset.left
        });
 
        page.render({
            canvasContext : context,
            viewport : viewport
        });
 
        page.getTextContent().then(function(textContent){
           console.log( textContent );
            var textLayer = new TextLayerBuilder({
                textLayerDiv : $textLayerDiv.get(0),
                pageIndex : page_num - 1,
                viewport : viewport
            });
 
            textLayer.setTextContent(textContent);
            textLayer.render();
        });
    });
});
</script>
</body>
</html>
```

Errors : 
<img width="1440" alt="screen shot 2016-05-30 at 11 16 33" src="https://cloud.githubusercontent.com/assets/9675021/15638929/2f582d6c-2658-11e6-9410-e6062e57e000.png">

**Comment by Snuffleupagus** [comment]
Instead of using a non-official example (one which we know nothing about), I'd suggest that you look into the [viewer components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components) instead. They support text-selection by default, and should be a much better starting point.

If you still want to use the example you referred to above, as outline in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), you must provide a link to our code. Since only code snippets aren't particularly helpful, without being able to run the code in the exact same context as you are.

**Comment by timvandermeij** [comment]
Closing as answered or until the information requested above is provided.
