### ISSUE TITLE
PDF.js viewer rendering and re-rendering of pages

### ISSUE THREAD

**Issue by fryaniv** [mozilla/pdf.js#7391]
Hey guys,

Using the PDF.js viewer (https://mozilla.github.io/pdf.js/web/viewer.html), is there a way to render an entire PDF document at once, rather than having each page being rendered and re-rendered once you arrive to it?

For example, if I went from page 1 to page 11, which didn't get rendered until I arrived to page 11, and then went back to page 2, and then went again to page 11 - page 11 will be re-rendered, i.e. show again the spinner and then load the page.

Thanks,
Yaniv

**Comment by Snuffleupagus** [comment]
In a custom implementation of PDF.js, you can increase the `DEFAULT_CACHE_SIZE`, see https://github.com/mozilla/pdf.js/blob/c4db4dd4ac366236cbf2864e94cb0e561e096de8/web/pdf_viewer.js#L65 to avoid clearing rendered pages once they are out of view.
Also, if you want no limit at all, you can modify `PDFPageViewBuffer` to ignore the cache size, see https://github.com/mozilla/pdf.js/blob/c4db4dd4ac366236cbf2864e94cb0e561e096de8/web/pdf_viewer.js#L87.

As far as rendering of all pages on load goes, to achieve that you'd probably have to modify e.g. https://github.com/mozilla/pdf.js/blob/c4db4dd4ac366236cbf2864e94cb0e561e096de8/web/pdf_viewer.js#L708 to essentially lie, by always treating all pages as visible.

Since all of the above would *greatly* increase memory consumption, and resource utilization, this is not really recommended. (Which is why the default viewer isn't doing this.)
Closing as answered.

**Comment by vinaynb** [comment]
@Snuffleupagus i am trying to render all pages and as pointed out by you, i was looking at _getVisiblePages function but with absence of comments it's hard to get around what the code does and needs to be changed to render all pages without scrolling to them.

Can you provide any tips as to what do you mean when you said "to essentially lie, by always treating all pages as visible." ?

**Comment by Snuffleupagus** [comment]
> Can you provide any tips as to what do you mean when you said "to essentially lie, by always treating all pages as visible." ?

As explained in the Wiki, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#allthepages, rendering all pages of a document is *very* bad from a memory (and CPU) perspective.

Considering that we do *not* ever recommend doing this, I don't think it would be a good idea for us to make it any easier to implement by providing exact instructions. (Giving such pointers could easily give the impression that it's "OK" to do, or lead to people using it without understanding the implications.)

**Comment by vinaynb** [comment]
@Snuffleupagus fair enough.
