### ISSUE TITLE
pdf.js crashes when pdf contains pages that are both horizontal and vertical

### ISSUE THREAD

**Issue by theDude30** [mozilla/pdf.js#7393]
Link to PDF file (or attach file here):
cannot be shared...

Configuration:
- Web browser and its version: chrome Version 51.0.2704.79 (64-bit)
- Operating system and its version: Mac OSX 10.11.5
- PDF.js version: Tested on the online version - https://mozilla.github.io/pdf.js/web/viewer.html
- Is an extension: No

Steps to reproduce the problem:
1.  open pdf that some pages are vertical and some pages and horizontal.

What is the expected behavior? (add screenshot)
pdf.js should display the file.

What went wrong? (add screenshot)
browser crashed.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
https://mozilla.github.io/pdf.js/web/viewer.html

**Comment by timvandermeij** [comment]
We have had several PDF files with pages of different orientation and all of them work fine. I can only assume that the PDF file is either very large or there are other troublesome elements in your particular PDF file, but since it is not shared there is nothing we can do to debug the issue. Please make sure you provide all requested information in the issue template before opening an issue here.
