### ISSUE TITLE
pdf.js crash

### ISSUE THREAD

**Issue by qwer1304** [mozilla/pdf.js#7395]
Link to PDF file (or attach file here): http://etheses.whiterose.ac.uk/9968/1/Damianou_Thesis.pdf

Configuration:
- Web browser and its version: Chrome Version 53.0.2763.0 canary (64-bit)
- Operating system and its version: Win 10, 1511
- PDF.js version: 1.5.285
- Is an extension: Yes

Steps to reproduce the problem:
1. Load the file
1a. Set the zoom to 150%
2. Scroll to about p.177 (overall pagination), or go to p.177
3. Crash occurs at transition to p.178

What is the expected behavior? (add screenshot) Normal display

What went wrong? (add screenshot) Crash

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yurydelendik** [comment]
Works for me on Mac OSX.

**Comment by qwer1304** [comment]
It seems that the problem occurs when the whole pdf page does NOT fit the screen.
I set the zoom to 50% and the crash does NOT occur; with zoom at 150% the crash occurs.

**Comment by THausherr** [comment]
It happened to me on W7, at default resolution, which is a bit higher than 100% (probably 120%).

**Comment by yurydelendik** [comment]
Does it happen on older versions of chrome, if not, probably it's a good time to bisect the regression?

**Comment by fako** [comment]
I also experience a crash with an Electron app (so that's a few weeks outdated Chromium build). Not sure if crashes are related, but posting it here as other crash tickets get closed. There are quite a view tickets in the Chromium tracker related to pdf.js crashes. Seems that they are not really being worked on. So I hope there is a work around in pdf.js, possibly by doing it myself.

One thing that strikes me is that I see this warning being triggered by the workers file: **The provided value 'moz-chunked-arraybuffer' is not a valid enum value of type XMLHttpRequestResponseType.**
It's only triggered with the crashing PDF, not other PDF's. Furthermore it only crashes on 32-bit, not 64-bit.

**Comment by Rob--W** [comment]
This bug was also reported at Chrome's issue tracker: https://crbug.com/623375

See also my comment at https://crbug.com/623375/#c11

This bug seems to be triggered by tiling patterns (see my comment in the Chromium report on how to interpret this graph):

![devtools screenshot: tiling patterns all the time](https://cloud.githubusercontent.com/assets/1365071/17396114/9c2590b2-59e6-11e6-87b3-74edb3f4402c.png)

**Comment by Rob--W** [comment]
I just tried Firefox with 200% zoom, going from page 175 to page 178 lead to a very noticeable freeze and a memory spike of +6 GB.

**Comment by whoizz** [comment]
not sure if this helps.. I've been working with PDF.js running inside Electron (from v0.32 ~ 1.3.3) which goes across a number of Chromium releases and I can confirm the crash on Chrome 32 bits whenever a canvas of 11000+ x 9000+ is loaded.. not too sure if this is possible but detecting the size of each 'to be rendered' canvas and when some conditions apply don't even try to render.

**Comment by qwer1304** [comment]
Chrome improved / fixed issues related to this bug in https://bugs.chromium.org/p/chromium/issues/detail?id=626082 and the non-pdf.js test case now passes. pdf.js still crashes with OOM on 8GB 64b machine or there're black pages blinking. I was wondering whether we're now hitting pdf.js specific issues.

**Comment by qwer1304** [comment]
The current status after GC improvement is that:

32b version (e.g., Installed Version 61.0.3141.8 (Official Build) dev (32-bit) works CORRECTLY
64b version (e.g., Version 61.0.3141.7 (Official Build) dev (64-bit)) works INCORRECTLY 

on pdf test file on a 8GB machine w/ Win 10 64b.

It seems that the issue now is w/ 64 bit version ONLY.
I wonder if it makes sense to re-dissect the issues since it seems specific to pdf.js.

**Comment by yurydelendik** [comment]
> I wonder if it makes sense to re-dissect the issues since it seems specific to pdf.js.

Not sure what do you mean. You demonstrated that the same browser (but different version) behave differently, so I'm also not sure why it will be specific to PDF.js.

**Comment by qwer1304** [comment]
This bug has a LONG history. After it has been posted, through several reductions it was found that the issue was related to Chrome's GC behavior and a generic test NOT involving pdf.js was developed. Then, Chrome guys developed a series of improvements to GC s.t. the generic test now PASSES. However, pdf.js still FAILS.
I noticed that this has to do with whether Chrome runs in its 32-bit OR 64-bit version.
I therefore suggested, since the generic test does NOT fail anymore, to look at why / where pdf.js fails in 64 bit version, but passes in 32 bit one. I hope that this would help in resolving the issue (whether in pdf.js or, more likely, in Chrome).

**Comment by qwer1304** [comment]
This seems to be fixed now in Chrome 64b too.
e.g., in Version 63.0.3232.0 (Official Build) canary (64-bit)
