### ISSUE TITLE
TypeError when rendering a PDF with an annotation with missing Subtype

### ISSUE THREAD

**Issue by manuelstofer** [mozilla/pdf.js#7446]
When the annotation subtype is undefined it defaults to an empty string:
https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L76-L77

Falls back to the default annotation:
https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L121

And gets a TypeError when accessing .name of undefined:
https://github.com/mozilla/pdf.js/blob/master/src/core/annotation.js#L184

The problem appears in files that have an annotation without subtype. I received such a file from a customer but can't provide it. I think this is actually invalid according to the PDF specs but other viewers render the file.

I am willing to create a pull request to fix it but wanted to ask first how this should be handled

**Comment by timvandermeij** [comment]
I'm not sure how this should be handled because I cannot inspect the PDF file properly. For a fix it is also required that we at least have some test document for verification. Would you be able to create a PDF document with the same issue, or strip the document from the customer to only keep the annotations and not all other content?

**Comment by manuelstofer** [comment]
I created a test document:
https://github.com/manuelstofer/pdf-js-test-file/blob/master/missing-annotation-subtype.pdf

**Comment by Snuffleupagus** [comment]
@timvandermeij What do you think about doing something like https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:annotation-missing-subtype to prevent errors in this case?

**Comment by timvandermeij** [comment]
Looks good! I'm only wondering if we can perhaps use the `default` case in the `switch` instead of handling this seperately in an `if` statement above the `switch` (as that is kind of what the `default` case was intended for originally. The warning will then show `''` for the subtype, but I think that's okay since it indicates that it's empty.

Feel free to make a PR and I'll review it.
