### ISSUE TITLE
Getting random Blob 404 error 

### ISSUE THREAD

**Issue by nicholassinggih** [mozilla/pdf.js#7469]
Hi all,

This application I'm currently developing loads multiple PDF files (each has a size of 20Mb), and part of the requirement is to be able to display more than 4000 pages in one page. However, only up to 120 pages are loaded at any given time. Now, the problem is, after a while (after successfully showing 3000 pages) I start getting these blob 404 errors, where the object url seems to point to nothing. These blob 404 errors occur while trying to load jpeg stream, as all the PDFs contain jpeg as a huge part of them. 

Prior to this, I did not recycle the reference to the PDFDocumentProxy nor the PDFPageProxy objects. It worked fine, except the memory consumption is really high and causes the browser to crash. So, I decided to recycle those objects. Now, the memory consumption stays at an acceptable level, but now each time I've loaded around 3000+ pages (mind you, only 120 pages are kept while the rest are always recycled), this error starts to occur. 

I'm currently doing these tests with Chrome 51.0.2704.103 m and IE 10 on Windows 7 & 8 machines. PDF.js version 1.3.91. 

Do any of you guys have any idea of why this happen and how to fix it?

**Comment by Snuffleupagus** [comment]
Please provide all the information requested in the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, especially a PDF file that can be used to reproduce this and detailed steps to reproduce the problem.
As it is, this issue is unfortunately incomplete, see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md.

**Comment by Snuffleupagus** [comment]
Please provide all the information requested in the https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, especially a PDF file that can be used to reproduce this and detailed steps to reproduce the problem.
If this is a custom PDF.js implementation, then you also need to provide access to a working example, please also see https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md.
As it currently stands, this issue is unfortunately incomplete.

**Comment by nicholassinggih** [comment]
I can't provide you the PDF file as their content is protected by a confidentiality agreement and it would be illegal for me to show it here. All I can tell you is that the original PDF is 800Mb and was broken down to smaller 20Mb pieces. All of the pages are scanned from a hard copy document, which means their content is just one big jpeg image. 

Is it possible that because I let the garbage collector collect the previous instances of the PDFDocument, that all the blob's object url become invalid? Does PDF.js reuse the same object url for each blob or does it create a new one even though the same PDF has been rendered before?

**Comment by yurydelendik** [comment]
Requesting complete test cases/example to reproduce the issue. There is nothing we can do without this. It can be defect or limitation in a browser, or incorrect release of the resources in the custom solution.

**Comment by nicholassinggih** [comment]
I've already worked around this problem by setting PDFJS.disableCreateObjectURL to true. 

Not sure if this is true, but from what I read, it seems there's an issue with blobs in Google Chrome. So, it's probably not a PDF.js issue anyway. 

However, I will provide a mock up implementation and PDF that can reproduce this error once I have the time.

**Comment by timvandermeij** [comment]
Closing as resolved for now. When the required information is provided, we can reopen this.
