### ISSUE TITLE
Issue with printing password protected pdf file

### ISSUE THREAD

**Issue by HenryHeeralal** [mozilla/pdf.js#7504]
Configuration:
- Web browser and its version: Desktop application using firefox pdf viewer to view pdf files.
- Operating system and its version: Windows 10, x64
- PDF.js version: 1.1.366
- Is an extension: 

Able to open password protected pdf file but when i press print button it prompts for password. Is it possible to provide password in code so that it doesn't prompt for it.

What is the expected behavior? print pdf file with password prompt.

What went wrong? (add screenshot) Always prompts for password.

[1469088443_AAAAAAAAAAAAAAAAAAA.pdf](https://github.com/mozilla/pdf.js/files/381230/1469088443_AAAAAAAAAAAAAAAAAAA.pdf)

Thanks in advance.

Heeralal
Ziorinfotech Pvt. Ltd.

**Comment by Snuffleupagus** [comment]
First of all, please check that this issue exists in the latest PDF.js development version (which as of this writing is `1.5.351`), since the version you're using is fairly old.
Second of all, does this issue affect the default PDF.js viewer, found here: http://mozilla.github.io/pdf.js/web/viewer.html?
Also, if this issue is limited to a custom implementation of PDF.js, it's not possible for us provide any assistance without a working example (as explained in the *forth* paragraph of https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).

> Able to open password protected pdf file but when i press print button it prompts for password.

Please provide the password for the PDF file, since it's impossible for anyone to look into this without that information!

**Comment by HenryHeeralal** [comment]
Thanks for prompt reply. 
Actually we embedded pdf.js in web viewer control in a desktop javafx application. 
With the help of pdf.js we are able to open a password protected file by providing the password in open pdf command.

PDFViewerApplication.setTitleUsingUrl(file);
    var xhr = new XMLHttpRequest();
    xhr.onload = function() {
     // PDFViewerApplication.open(new Uint8Array(xhr.response), 0);
      PDFViewerApplication.open(new Uint8Array(xhr.response), null,'123456');
    };

But when we click on print icon a dialog is shown with buffer status and then disappears. No print dialog opened and no output. (screen shot attached)

Can you please any code or sample application to print the pdf if any.

Heeralal Tiwari
Ziorinfotech Pvt. Ltd.
![buffer](https://cloud.githubusercontent.com/assets/9475259/17134653/118a308c-5349-11e6-9b2b-9f605f404da1.png)

**Comment by Snuffleupagus** [comment]
> Actually we embedded pdf.js in web viewer control in a desktop javafx application.
> [...] 
> But when we click on print icon a dialog is shown with buffer status and then disappears. No print dialog opened and no output. (screen shot attached)

This makes is sound like the issue actually concerns printing support in your desktop application, rather than PDF.js *itself*. If so, this isn't really a PDF.js issue, and consequently we'll not be able to offer much help here.

Given that you've not really provided answers to *any* of the questions in https://github.com/mozilla/pdf.js/issues/7504#issuecomment-234916711, we unfortunately cannot provide more assistance here!
Closing as incomplete for now, until *all* the information requested above has been provided.
