### ISSUE TITLE
how to customize the outlineItemToggler

### ISSUE THREAD

**Issue by kevin3566** [mozilla/pdf.js#7522]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chromium 51.0.2704.79 , Firefox 47.0,
- Operating system and its version:Windows7
- PDF.js version:latest
- Is an extension:no

What is the expected behavior? (add screenshot)

all outline Item hidden except the first one by default, as the screenshot shows
thx

![unnamed qq screenshot20160804165809](https://cloud.githubusercontent.com/assets/20036033/17396292/5200c7ac-5a65-11e6-84ff-9c6e99da4288.png)

**Comment by timvandermeij** [comment]
You can double-click on the outline icon to collapse all items so that only the toplevel items are shown. This is done in https://github.com/mozilla/pdf.js/blob/61a4c740d2df6fa2fe1497f5436d4acc1dcbb0c8/web/pdf_sidebar.js#L334. For a custom viewer you could make this the default. Closing as answered.
