### ISSUE TITLE
Mobile browser does NOT suppurt range request and need download whole source PDF before render

### ISSUE THREAD

**Issue by godwin668** [mozilla/pdf.js#7528]
I tested on iPhone Chrome browser and found that I need wait for the whole source PDF downloaded before render. Is there any way make mobile support range request like PC?

**Comment by Snuffleupagus** [comment]
The Google Chrome browser for iOS is actually based on the Safari browser, please refer to https://developer.chrome.com/multidevice/ios/overview.
Unfortunately Safari has issues with range requests, which is why they are disabled in the default viewer; see [compatibility.js#L455-L478](https://github.com/mozilla/pdf.js/blob/ca81f4df1897322416ede1462abdc3e0a523bdea/web/compatibility.js#L455-L478) and issue #3260.
Closing as answered.
