### ISSUE TITLE
pdf js making 20 kb document to load in 15 seconds

### ISSUE THREAD

**Issue by shefali217** [mozilla/pdf.js#7559]
I am using PDF.js to open a document in my web site but it is increasing time to view a document in my application.

**Comment by Snuffleupagus** [comment]
When reporting an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, and that you provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

Closing as incomplete for now, since there's nothing we can do given the lack of information/test-case.
