### ISSUE TITLE
Localization for exception messages

### ISSUE THREAD

**Issue by Kateryna-Baranovska** [mozilla/pdf.js#7560]
Could you please help me a little with localization stuff.

Configuration:
- Web browser and its version: Firefox 48.0.1
- Operating system and its version: Windows 7
- PDF.js version: 1.4.20

Steps to reproduce the problem:
I am trying to reproduce issue with "Missing PDF file" exception (add some wrong letters in src for the pdf document file). If I am on en-US locale I see correct error translation when expand "More Information" button. But if I am change locale to different one - I see just one translated word (is "Message(Mensaje):") and the rest of the error still appear on en-US.
Could you please tell me are there some ability to reproduce this scenario on the "pdfjs DEMO" (using this link: https://mozilla.github.io/pdf.js/web/viewer.html) or could maybe you can describe me how exactly should the errors shown on the UI with different locales? Or maybe are there some another scenario and steps to reproduce any exception (unexpected Server error  etc.)?

Screenshot with English localization:
![error_en](https://cloud.githubusercontent.com/assets/10024414/17895395/a8bc4040-6955-11e6-9197-16325598b2bc.png)

Screenshot with Spanish localization:
![error_es](https://cloud.githubusercontent.com/assets/10024414/17895407/af8fc2fc-6955-11e6-86f2-c38c47802e4a.png)

Thank you.

**Comment by Snuffleupagus** [comment]
The "Missing PDF ..." message that is provided when clicking on the "More Information" button is the *exact* error as it comes from the API (in this case the worker side of PDF.js, see [src/core/network.js#L484-L501](https://github.com/mozilla/pdf.js/blob/e5baf7ec368620c5884e258462e1fd6a7fb13576/src/core/network.js#L484-L501)).

Please note that the additional information provided by the "More Information" button is provided for debugging purposes and thus aimed at developers, rather than regular users, hence those messages are not intended to be translated. (Note that the "Missing PDF file" in the top left is translated, since this part is intended for regular users.)

Closing as answered.

**Comment by Kateryna-Baranovska** [comment]
Thank you very much!
