### ISSUE TITLE
pdf not working for arXiv.org

### ISSUE THREAD

**Issue by githubuser2012** [mozilla/pdf.js#7572]
Link to PDF file (or attach file here):  http://arxiv.org/list/astro-ph/new or more specifically http://arxiv.org/pdf/1608.06938.pdf

Configuration:
- Web browser and its version:  Mozilla Firefox 48.0.1
- Operating system and its version:  Mac OSX 10.9.5
- PDF.js version:  1.0.277.1-signed.1-signed
- Is an extension:  Yes

Steps to reproduce the problem:
1. Click on the pdf link.  It does not work.
2.

What is the expected behavior? (add screenshot)  The pdf should be displayed.  It is not displayed at all

What went wrong? (add screenshot)  The pdf is not displayed.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> Link to PDF file (or attach file here): http://arxiv.org/list/astro-ph/new or more specifically

@githubuser2012 It looks like you forgot to provide the link to the *actual* PDF file!
(The link that was provided contains far too many files in order to be actionable.)

> Configuration:
> 
>     Web browser and its version:
>     Operating system and its version:
>     PDF.js version:
>     Is an extension:

Please make sure that provide as much of this information as possible when reporting an issue!

**Comment by githubuser2012** [comment]
You can try with any of the pdf links.  More specifically try this link http://arxiv.org/pdf/1608.06938.pdf

**Comment by Snuffleupagus** [comment]
Works for me, using the latest PDF.js version (`1.5.391`) on Windows.

> 1.0.277.1-signed.1-signed

This suggests that you're using the addon from https://addons.mozilla.org/en-US/firefox/addon/pdfjs/, which as the description says has been discontinued, and is thus no longer updated.
Please uninstall the PDF Viewer addon, and use the version of PDF.js that is *included* in Firefox instead.

Closing as answered, since this works in the latest PDF.js version.
