### ISSUE TITLE
Get error at load PDF from byte array with PDF.js

### ISSUE THREAD

**Issue by dudu3321** [mozilla/pdf.js#7594]
Hello,
I got some problem when I open my PDF file 

my error code:
PDF.js v1.4.20 (build: b15f335)
Message: Worker was destroyed

and this  my code 
C#:
Byte[] result = ExistPDFFile;
var response = Convert.ToBase64String(result);    

JS:
function (response) {
   response = atob(response);
   var uint8Array = new Uint8Array(response.length);
   for (var i = 0; i < response.length; i++) {
   uint8Array[i] = response.charCodeAt(i);
   }
   PDFViewerApplication.open(uint8Array);
}

PDF was open correct, but still hava error like the above
Please help me!!

**Comment by Snuffleupagus** [comment]
When filing an issue, please ensure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, and that you provide *all* the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

Closing as incomplete for now, since just code snippets are not particularly helpful when trying to debug an issue. Please provide a link to an example, in order to re-open the issue.
