### ISSUE TITLE
Open button is not visible?

### ISSUE THREAD

**Issue by roondal** [mozilla/pdf.js#7608]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: JavaFX8 desktop app
- Operating system and its version: win 10
- PDF.js version: pdfjs-1.4.20-dist
- Is an extension:

Steps to reproduce the problem:
1. I use PDF.js to show pdf files in JavaFX desktop app in WebView but open button is not visible
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![image](https://cloud.githubusercontent.com/assets/15047075/18312331/9f4ffb36-7509-11e6-9760-2642d0be3d94.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You are probably hitting https://github.com/mozilla/pdf.js/blob/master/web/app.js#L1380, i.e., some required features are missing. I'm not sure what JavaFX is using to render web element, but you might want to look into why this support is missing. Closing as answered since it's now out-of-scope for the PDF.js project.
