### ISSUE TITLE
Page not displaied

### ISSUE THREAD

**Issue by dmitrirussu** [mozilla/pdf.js#7611]
InvalidStateError: An attempt was made to use an object that is not, or is no longer, usable
https://localhost/popcompta_apps/public/global/js/pdfjs/pdf.js
Line 5072

this.ctx.drawImage(groupCtx.canvas, 0, 0);

Configuration:
Firefox 46.0.1
Ubuntu version 15.10
PDF JS - 1.1.469

Steps to reproduce the problem:
1. Open a pdf file go to second page.
2. Reload page (he should be on the second page is ok)
3. Move Scroll up you have to see the Blank page wich is always in loading

What is the expected behavior? 
The PDF document has 2 pages, if point is saved to second page, and you go back to the last opened document, he show you directly second page and it looks ok. 

The problem is on the first page which is not displaied, always stay loader to load page

**Comment by Snuffleupagus** [comment]
This should already have been fixed by PR #6551.
Please update PDF.js to the latest version, since the version you are using is quite out of date.

Closing as fixed for now. (We can re-open this issue if the problem persists in the *latest* version of PDF.js, and if the problematic PDF file is supplied.)
