### ISSUE TITLE
Speed Issues with Custom PDF.js based PDF Viewer

### ISSUE THREAD

**Issue by IAPark** [mozilla/pdf.js#7654]
This might not be the right place for this but I didn't get anywhere on StackOverflow. If you will think of this as a request for better documentation surrounding the whole /web side of the project.

I've been trying to create a minimilastic PDF viewer that allows for a bit of customization. Going directly from the existing PDF.js viewer would have taken a huge amount of work because it has a lot of code I don't need. The goal here is just to have a scrolling view of the pdf with an index off to one side. After a bit of looking mostly regarding the lack of proper documentation for anything in the PDFViewer side of PDF.js I got something working, but now in testing I've discovered scrolling is laggy on lower powered devices. Some searching has confirmed that the scroll listener in PDFViewer is taking long to update. The default viewer though works fine. Does anyone have any advice for how to speed things up a bit.  I suspect it's maybe because I'm not explicitly passing something to PDFViewer

        this.linkService = new pdf.PDFLinkService();
        this.viewer =  new pdf.PDFViewer({container: element,
                                      linkService: this.linkService});
        this.linkService.setViewer(this.viewer);
        this.viewer.setDocument(document);
       this.linkService.setDocument(document);

Is there anything I'm obviously missing? I'm trying to embed it it inside react which is a whole other story, but this should be the important code.

Is there a better way to do what I want: an embedded PDF with custom positioning controls?

**Comment by timvandermeij** [comment]
You should use the web components to make your own minimalistic viewer. Examples are located at https://github.com/mozilla/pdf.js/tree/master/examples/components. The default viewer is made especially for usage in Firefox and indeed has a lot of functionality that you may not need. To make the development of minimalistic viewers easy we developed the web components so you can use components from the default viewer without all other functionality.

Scrolling may indeed be laggy on lower powered devices because rendering pages takes longer. Make sure to use the worker (i.e., no `singlefile` build). If you have control over the PDF files, optimize them for web usage: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#optimize.

**Comment by timvandermeij** [comment]
I would also recommend to take a look at the mobile viewer example at https://github.com/mozilla/pdf.js/tree/master/examples/mobile-viewer, which probably (largely) does what you want.

**Comment by IAPark** [comment]
Thanks, I appreciate it. Something in the editing I did today seems to have fixed the issue I was having with lagging scrolling. I actually had the same issue with at least the mobile viewer. What seems to have fixed it somehow was adding a listener for mouse wheel events so I could implement zoom. I wasn't sure that was it and to be honest I'm still not sure, but removing it reintroduces lag and putting it back in gets rid of the lag. Probably if it is a real affect it's some problem with Chrome given it only showed up when my Linux partition got corrupted and I at least temporarily had to switch over to Windows.
