### ISSUE TITLE
PDFJS viewer doesn't open files from NOT Assets folder

### ISSUE THREAD

**Issue by coolhunter33** [mozilla/pdf.js#7672]
Link to PDF file (or attach file here):
[testPdf.pdf](https://github.com/mozilla/pdf.js/files/492718/testPdf.pdf)

Configuration:
- Web browser and its version:
- Operating system and its version: Windows 10
- PDF.js version: 1.1.366
- Is an extension:

Steps to reproduce the problem:
1.  PDF.js fails to open Pdf file from NOT Assets folder of the project
2.  How to make viewer to open files from another location?

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)
![2016-09-26_12-36-10](https://cloud.githubusercontent.com/assets/10404295/18829633/da2de16a-83e5-11e6-9ca0-20c70cb021d5.png)
Here must be opened pdf document, but the viewer doesn't load it

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
You should be able to open the file from any location, such as https://github.com/mozilla/pdf.js/blob/master/examples/mobile-viewer/viewer.js#L32 and other examples. Make sure you use a web server as using local files may not work due to browser security policies. The web console may provide more reasons as to why your file is not loaded, but without a running example of your code there is not much we can do here.
