### ISSUE TITLE
Access Find reset via the eventBus

### ISSUE THREAD

**Issue by LegalRadius** [mozilla/pdf.js#7680]
I'm looking for an API to clear the current search results for a `Find` operation through the `eventBus`.

I've been looking at the `PDFFindController`. I see the `reset()` function. It would be ideal if there was an event to reset the search. Would anyone know if there is one already? Perhaps a full event-driven API should be supported?

**Comment by Snuffleupagus** [comment]
> I've been looking at the `PDFFindController`. I see the `reset()` function.

That function, which is now marked as "private" (since its name is `_reset`), is/was only ever intended to be called when a *new* document is opened in the default viewer and not in other situations.

> It would be ideal if there was an event to reset the search. Would anyone know if there is one already?

If I were to guess, I'd say that what's *actually* being asked here is for a way to cancel a running search operation and remove any active highlights. In that case, in the default viewer, it should be as simple as dispatching a `find` event with suitable parameters provided (i.e. `query` set to an empty string); please see e.g. the `PDFFindBar` implementation in https://github.com/mozilla/pdf.js/blob/ece6a31a442d8d2489817579dfc57ed371135d3a/web/pdf_find_bar.js#L94-L103

@timvandermeij Should the issue simply be closed as answered, since it's already possible to achieve this using existing events?

**Comment by timvandermeij** [comment]
Yes, I don't see a need at this point to implement this.
