### ISSUE TITLE
How to add distribution version of the pdf viewer to website?

### ISSUE THREAD

**Issue by anik786** [mozilla/pdf.js#7685]
I have a very simple question. How do I add http://mozilla.github.io/pdf.js/web/viewer.html to my site. Note I do not intend to add any other css, scripts or any other bespoke features. 

I thought this would be a simple copy and paste job with few modifications, but when going through https://github.com/mozilla/pdf.js/blob/master/web/viewer.html , I found it was just so confusing to understand.

First it links to sooo many files. These files then may require more files, so I had to hunt them down and change those paths to my website's paths. It also seems to use a template engine which I don't recognise. 

Then I decided to follow the same page for the production version. This page then seemed to link to `viewer-snippet-minified.html`, which in turn seems to use `../build/pdf.js` which dosen't seem to exist!

I'm also aware there is a pre-built version of the library here: https://github.com/mozilla/pdfjs-dist but no example in how to use it!

Therefore can someone kindly provide the minimal code (or a link to a file on the GitHub repository), which I can simply copy and paste and state whatever I need to change to match my own paths.

Many Many Thanks and you are a life saver!

**Comment by Rob--W** [comment]
https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website lists several methods. The easiest way is shown at ["From examples"](https://github.com/mozilla/pdf.js/wiki/Setup-PDF.js-in-a-website#from-examples).

**Comment by timvandermeij** [comment]
The default viewer is complex because it has many features that are required for the add-on versions in Firefox/Chrome. You might be better off with using the viewer components (https://github.com/mozilla/pdf.js/tree/master/examples/components) to create your own viewer. You can look at e.g., https://github.com/mozilla/pdf.js/blob/master/examples/webpack/main.js for how to use `pdfjs-dist`. Closing as answered.
