### ISSUE TITLE
The request for locale.properties of pdf.js returns 404

### ISSUE THREAD

**Issue by cooperLgm** [mozilla/pdf.js#7716]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:Firefox 49.0.1
- Operating system and its version:win7
- PDF.js version:1.5.188
- Is an extension:

Steps to reproduce the problem:

I'm trying to set up PDF.JS in an SpringMVC application for displaying PDF-files. Therefore I want also to use the pdf-viewer that is shipped with PDF.JS.

But I'm having problems with the "locale.properties" file. The error returns an 404 for that file.
My web server is tomcat7.0.
I'm trying to add mime-type（application/octet-stream） to web.xml and still return 404.
![default](https://cloud.githubusercontent.com/assets/22806524/19336050/c0a35592-913a-11e6-9770-9f4589358df4.PNG)

**Comment by Snuffleupagus** [comment]
As mentioned in both the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), please provide access to a working example since it's impossible to tell what might be wrong from the information given.
Closing as incomplete for now; please provide a link to a complete example in order to re-open.
