### ISSUE TITLE
can PDF.js support base64 coding pdf showing?

### ISSUE THREAD

**Issue by lixiuna0908** [mozilla/pdf.js#7729]
This situation which puting the base64 coding pdf as input instead of url = '../../web/compressed.tracemonkey-pldi-09.pdf', the can pdf.js support this situation?

**Comment by Snuffleupagus** [comment]
The base64 encoding is an inefficient way to represent data, and some browsers (e.g. Internet Explorer) will even truncate long base64 strings.
The solution is to convert base64 encoded data to a binary format, as is shown in https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html#L19, and feed that to PDF.js since this is supported. Another solution would be to convert the base64 encoded data to a TypedArray, which PDF.js also supports.

Closing as answered.

**Comment by lixiuna0908** [comment]
ths a lot!
