### ISSUE TITLE
Delaying in PDF rendering

### ISSUE THREAD

**Issue by TheNasirKhan** [mozilla/pdf.js#7740]
Link to PDF file (or attach file here): http://cssexplore.com/web/index.php?file=BOOK%20WITH%20INDEX.pdf&bookid=19

Configuration:
- Web browser and its version: Chrome and Version 53.0.2785.143 (64-bit)
- Operating system and its version: MacOS Sierra and Version 10.12 / Windows 8
- PDF.js version: Current version
- Is an extension: .JS

Steps to reproduce the problem:
1. Click on a link above
2. Pdf will take so much time to open

What is the expected behavior? (add screenshot)
Fast Pdf rendering even if size of the pdf is high

What went wrong? (add screenshot)
Pdf is taking so much time in rendering when file is high

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
<img width="1280" alt="screen shot 2016-10-20 at 11 01 07 am" src="https://cloud.githubusercontent.com/assets/9740293/19548076/9f1417a6-96b5-11e6-8492-771d8c130c48.png">
![img_20102016_111011](https://cloud.githubusercontent.com/assets/9740293/19548107/d275ef66-96b5-11e6-8820-90eee431c1dd.png)

**Comment by Snuffleupagus** [comment]
Using PDF.js version `1.6.263`, the file *renders* instantly for me when e.g. opening it locally.

The link that you provided does *not* point directly to a PDF file, but rather to a customized version of the PDF.js viewer (using PDF.js version `1.4.20`, which is now outdated).
Given that the size of the PDF file is 13.2 MB, and that the server seem to be using a slow internet connection, it simply takes a while to load the entire PDF file. However, once it has loaded, it *renders* more of less instantly in PDF.js `1.6.263`.
It appears (e.g. from your screenshots) that you confuse the time it takes to load the PDF file from the server, with the time it takes to actually *render* it in PDF.js.

Closing as invalid, since we we cannot do anything about the slowness of a random server

---

> PDF.js version: Current version

*For future reference, when filing issue:* Please provide a valid version number, since "Current version" is not useful information.
