### ISSUE TITLE
localstorage key naming

### ISSUE THREAD

**Issue by TZanke** [mozilla/pdf.js#7760]
At the moment PDF.js saves data from "showPreviousViewOnLoad" to local storage with the key **database**.

I would like to change the key for standalone installations of PDF.js because **database** could easily used from someone else. Also **database** isnt very intuitive for a developer, finding the source of this key.

Wish: Change it to somethine like **pdf.js-database**

**Comment by timvandermeij** [comment]
It's possibly defined here: https://github.com/mozilla/pdf.js/blob/c1a34ffbcdec0eb31a2bdccc3b49c41f1e5e4601/web/view_history.js#L80

We have `pdfjsHistory` just above it, so I'm not sure why the name `database` is chosen. Feels like a bad name to me too. I'm not sure if we can just change that as it might mean that older preferences get lost. Let's see if others have ideas for this.

**Comment by Snuffleupagus** [comment]
> We have pdfjsHistory just above it, so I'm not sure why the name database is chosen.

`pdfjsHistory` is specific to the Firefox addon/built-in version, hence it may not be entirely relevant to the current discussion.
The name `database`, for e.g. the `GENERIC` viewer, has been used basically since "forever", hence I don't think we can just rename it without trying to migrate existing data first (which shouldn't be too hard).
A better name might be `pdfjs.history` for the `ViewHistory` entries (since it follows the same naming convention as in [preferences.js#L204](https://github.com/mozilla/pdf.js/blob/master/web/preferences.js#L204)).
