### ISSUE TITLE
How can i open links to new tab / window

### ISSUE THREAD

**Issue by azetutu** [mozilla/pdf.js#7779]
Everything works fine but i cannot change behavior for links. I found LinkTarget in pdf.js file but how i supposed to change this string to get it really works?

**Comment by Snuffleupagus** [comment]
Since there's no information provided about how you're using PDF.js, e.g. just the API or the entire default viewer, the general approach to specify the `target` attribute is to place e.g.
```javascript
PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK;
```
somewhere before the `PDFJS.getDocument(...)` call in your code.
Please refer to [global.js](https://github.com/mozilla/pdf.js/blob/9f8d67475ea668e3e8eaeb241733b998d64e90ca/src/display/global.js#L217-L228) for a list of the possible values that `PDFJS.externalLinkTarget` accepts.

Closing as answered.

**Comment by markusd1984** [comment]
@Snuffleupagus I tried 

> PDFJS.externalLinkTarget = PDFJS.LinkTarget.BLANK; 

instead of:

`PDFJS.openExternalLinksInNewWindow = (
  PDFJS.openExternalLinksInNewWindow === undefined ?
    false : PDFJS.openExternalLinksInNewWindow);`

but unfortunately to no effect :( What else can I do to check or try?

Running Opigno LMS = Drupal 7 which uses /sites/all/libraries/pdf.js/build/pdf.js

**Comment by whxleemdddd** [comment]
app.js：
 let pdfLinkService = new PDFLinkService({
      eventBus,
      //externalLinkTarget: AppOptions.get('externalLinkTarget'),
      externalLinkTarget: 2,
      externalLinkRel: AppOptions.get('externalLinkRel'),
    });
