### ISSUE TITLE
pdf.js-dist is not included with i10 and images for web viewer as bower component . 

### ISSUE THREAD

**Issue by VijayAllagi** [mozilla/pdf.js#7780]
I am trying to use pdf-dist as bower component. I am very curious to know are there any plans to add the files related translations and images for the viewer in web. Currently those parts are missing in the pdf-dist in bower. 
Missing files in packages for web viewer.

1. i10.js
2. images for web viewer
3. locale properties

Please provide with the details of the inclusions or plans for the them in bower.

**Comment by Snuffleupagus** [comment]
As mentioned in e.g. issues https://github.com/mozilla/pdf.js/issues/5609#issuecomment-68530552 and https://github.com/mozilla/pdf.js/issues/7203#issuecomment-210510569, we purposely don't include the default viewer in `pdfjs-dist`. Since the files you reference are only meaningful in connection with the default viewer, but not with the core PDF.js library, they are thus not included in `pdfjs-dist` repository.

Closing as answered.
