### ISSUE TITLE
taking more than 2minutes to load file of size 9mb, how can i handle this?

### ISSUE THREAD

**Issue by nikhilreddy93** [mozilla/pdf.js#7790]
Here is my code
var data = base64ToUint8Array(base64String);
		function base64ToUint8Array(base64) {
		    var raw = atob(base64);
		    var uint8Array = new Uint8Array(raw.length);
		    for (var i = 0; i < raw.length; i++) {
		      	uint8Array[i] = raw.charCodeAt(i);
		    }
		    return uint8Array;
		  }

PDFJS.getDocument(data)
	    .then(function(pdf) {
});

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since there's no actionable information provided here.

**Comment by nikhilreddy93** [comment]
@Snuffleupagus 
Here is the pdf link. https://drive.google.com/file/d/0B7zGd0ub1kvNU0xsVmpwVzF6REk/view?usp=sharing
Well i'm loading the pdf from my local storage, not from the url.

**Comment by Snuffleupagus** [comment]
Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md to re-open the issue (don't forget a link a working example, since code snippets are not helpful.that we can run).
When reporting an issue, please make sure that you also read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md.

**Comment by nikhilreddy93** [comment]
[doc 2.pdf](https://github.com/mozilla/pdf.js/files/578094/doc.2.pdf)

Configuration:
* chrome
* windows 8.1
* pdf.js version-1.6.256
* not an extension, this is a webapp

expected behaviour:
                              Load pdf file faster and without any crash. 
went wrong:
                     taking more than two minutes to load the above file, after file load browser got struck.
