### ISSUE TITLE
Handle loading abort/failure in password callback

### ISSUE THREAD

**Issue by sudheer-ranga** [mozilla/pdf.js#7806]
I am using pdf.js for my project and I am facing issue with encrypted pdf's. I am using PDF.js passwordCallback function to provide the password.

```
PDFJS.getDocument(file, null, passwordCB, null).then(function (res) {
    console.log("Document Decrypted);
});
```

Here is the passwordCallback Function

```
var passwordCB = function (passwordFunc, reason) {
      if (reason === 1) {
        passwordFunc(pdfpassword);
      } else {
        console.log("Wrong Password");
      }
    };
```

When a wrong password is provided, the control do not get out of passwordCB function (promise is not returned). It get's stuck until a valid password is provided.

So when user enters a wrong password I have to tell them that the password is wrong and need to get a new password. I am using a custom popup to get the password from user.

Is there a way to break the passwordCallback function and return to the getDocument() promise when a wrong password is entered, so that I can call the getDocument again with the new password that the user enters?

Also, from the source code it is mentioned that the passwordCallback is deprecated.

```
    * @param {function} passwordCallback (deprecated) It is used to request a
    * password if wrong or no password was provided. The callback receives two
    * parameters: function that needs to be called with new password and reason
    * (see {PasswordResponses}).
```

Is there any other way for dealing with password callbacks? Any article or example on this scenario?

**Comment by Snuffleupagus** [comment]
*Since there's only code snippets provided, and not actual working examples (as asked for in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md)), the following becomes more general advice.*

There are *two* different [`PasswordResponses`](https://github.com/mozilla/pdf.js/blob/7ec8adc712bd5d03768991d59da7950e3fda75df/src/shared/util.js#L391-L394), and you need to handle *both* of them in the callback function.
Note how your code snippet above only seem to deal with the `NEED_PASSWORD` case.

> Also, from the source code it is mentioned that the passwordCallback is deprecated.

It's replace by the `onPassword` callback, please see [src/display/api.js#L342-L347](https://github.com/mozilla/pdf.js/blob/7ec8adc712bd5d03768991d59da7950e3fda75df/src/display/api.js#L342-L347).

> Any article or example on this scenario?

You can look at e.g. the unit-tests for two different examples of how password can be used, please see [test/unit/api_spec.js#L140-L227](https://github.com/mozilla/pdf.js/blob/7ec8adc712bd5d03768991d59da7950e3fda75df/test/unit/api_spec.js#L140-L227).
There's also the default viewer, see [web/app.js#L649-L652](https://github.com/mozilla/pdf.js/blob/7ec8adc712bd5d03768991d59da7950e3fda75df/web/app.js#L649-L652) and [web/password_prompt.js](https://github.com/mozilla/pdf.js/blob/7ec8adc712bd5d03768991d59da7950e3fda75df/web/password_prompt.js), but that implementation might not be as simple to understand as the unit-tests.

Closing as answered, since it's difficult to provide more detailed help without working examples.

**Comment by sudheer-ranga** [comment]
Here is a small code snippet

```
var loadTask = PDFJS.getDocument(file);

loadTask.onPassword = function passwordNeeded(updateCallback, reason) {
	if (reason === 1) {
	  updateCallback('wrong_password');
	} else {
	  updateCallback(null);
	}
};

loadTask.then(function (res) {
  console.log(res);
}).then(null, function (err) {
  console.log("some error ", err);
}).catch(null, function (err) {
  console.log("some error ", err);
});
```

So when the document is encrypted, the `loadTask.onPassword` is triggered. From the above code If the password is correct, the `loadTask.then()` success is executed and I can return that promise to further use it.

If the password is wrong then the reason is 2 (Wrong Password) and the `loadTask.onPassword` else block is executed. Here I pass `null to updateCallback function` to stop the execution. In this case the `loadTask.then()` should atleast throw error.

Is there a way where the `loadTask.then` throw error when I enter a wrong password so I can handle and send a custom promise?

**Comment by yurydelendik** [comment]
Passing `null` to `updateCallback` will not cancel document loading. It's hard to grasp what is expected from PDF.js. Do you just want to cancel loadingTask and does loadingTask.destroy() accomplish what you are expecting?

**Comment by sudheer-ranga** [comment]
It's not about cancelling. If a password is wrong I want to make PDFJS return to the Promise success or error block so that I can make some changes that I want.

For example:

```
var loadTask = PDFJS.getDocument(file);

loadTask.onPassword = function passwordNeeded(updateCallback, reason) {
    if (reason === 1) {
      updateCallback('wrong_password');
    } else {
      // Password is wrong, so make the PDFJS enter the error block of promise
      updateCallback(null);
    }
};

loadTask.then(function (res) {
  console.log("Successfully Descrypted the PDF");
}).then(null, function (err) {
  // How to enter this error block if a wrong password is entered
  console.log("PDF is password Protected");
}).catch(null, function (err) {
  // How to enter this error block if a wrong password is entered
  console.log("PDF is password Protected");
});
```

**Comment by yurydelendik** [comment]
>  If a password is wrong I want to make PDFJS return to the Promise success or error block so that I can make some changes that I want.

load canceling will reject a Promise, no?

**Comment by sudheer-ranga** [comment]
No. It doesn't as far as I have tried. Any idea?

**Comment by yurydelendik** [comment]
Sending `updatePassword(null);` will not be a good choice for API. I recommend to fix existing behavior to properly react on the following code:

```
var loadingTask = PDFJS.getDocument(data);
loadingTask.promise.then(function (d) {
  console.log('Loaded pages: ' + d.numPages);
}, function (e) {
  console.error('Error: ' + e);
});
loadingTask.onPassword = function(updatePassword, reason) {
  loadingTask.destroy();
  // or throw new Error("");
};
```

For now workaround is to invoke getDocument twice one time without password, and if loading promise fails due to password, then with password, e.g. `getDocument({url: url, password: '111'})`

Reopening with different title

**Comment by mukulmishra18** [comment]
I think in src/display/api.js, when wrong password is provided 
```
messageHandler.on('IncorrectPassword',
                        function transportIncorrectPassword(exception) {
        var loadingTask = this.loadingTask;
        if (loadingTask.onPassword) {
          return loadingTask.onPassword(updatePassword,
                                        PasswordResponses.INCORRECT_PASSWORD);
        }
        loadingTask._capability.reject(
          new PasswordException(exception.message, exception.code));
      }, this)
```
the above code calls itself repeatedly and hence loadingTask._capability.reject() is not invoked,  that's why no error is thrown. 
I think removing the if condition will throw an error and reject the loading task.

Please find the PR that fixes the issue.

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:api-onPassword-abort/throw contains a tentative patch that I believe should address both cases, i.e. `loadingTask.destroy()` and generic `throw`ing, as described in https://github.com/mozilla/pdf.js/issues/7806#issuecomment-261273634.

Handling the `throw` case is straightforward; however ensuring that we reject with the *proper* exception in the `destroy` case seem to require a (somewhat) more hacky solution. I'm not sure if there's any easier/better solution available here!?

**Comment by rebeccamantel** [comment]
I read the above and I am quite new at it  so I don't really know how to use it.
I am using the viewer of pdf.js and i need to pass to it programmatically the password to open the protected pdf files.
I downloaded the libraries of pdf.js which contain build and web How should i do it?
Thank you
