### ISSUE TITLE
AEM dropdown is not working with PDF.js

### ISSUE THREAD

**Issue by pradeeppagra** [mozilla/pdf.js#7808]
Hi,

I am using pdf.js for ODF wrapper. It is causing problem in dropdown in AEM dialog. Error message i am getting is

Uncaught ReferenceError: text is not defined(…)

Attached dropdown and error message in file.
Please help.

Thanks,
Pradeep
 
[Doc1.docx](https://github.com/mozilla/pdf.js/files/588434/Doc1.docx)

**Comment by timvandermeij** [comment]
Closing as incomplete. Please read https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md before opening an issue to make sure that you provide all necessary details for us to work with. This issue is missing a PDF file to reproduce the issue, the PDF.js version and details on your custom solution/what an ODF wrapper and AEM dialog is.
