### ISSUE TITLE
What files are necessary for integration?

### ISSUE THREAD

**Issue by TomVanHaver** [mozilla/pdf.js#7811]
Hi,

We are trying to integrate the pdf.js library in our angular app.
The pdfjs-dist npm package is integrated in our webpack build.

Now we are not sure what files to take from the package (and which not) to ensure maximum flexibility and compatibility (for the future) ?

For now:
- pdf.js, pdf.worker.js and compatibility.js are taken from the pdfjs-dist npm package and integrated in our webpack build.
- viewer.js, viewer.html, viewer.css, l10n.js /cmaps /locale and /images are taken from the gh-pages repo and copied in our solution.

Problems: 
- we could also take the pdf-viewer.js and pdf-viewer.css from the pdfjs-dist npm package, but is is very unclear to us on what source location to prefer? What files should be taken from where?
- what is the pdf.combined.js file for anyway?

kind regards, 
Tom.

**Comment by yurydelendik** [comment]
> Now we are not sure what files to take from the package (and which not) to ensure maximum flexibility and compatibility (for the future) ?

You can take and rely on APIs and files provided in pdfjs-dist. Viewer is not fully modular and subject to further modifications, that's why it's not included into pdfjs-dist. Also we don't want to people to use viewer without UI modification to avoid confusions with demo and embedded browser viewers. So third-party viewer package maintainer is responsible for maintaining anything that is not included into pdfjs-dist.

>    we could also take the pdf-viewer.js and pdf-viewer.css from the pdfjs-dist npm package, but is is very unclear to us on what source location to prefer? What files should be taken from where?

Not sure I understand the question. Is it webpack specific?

>    what is the pdf.combined.js file for anyway?

pdf.combined.js is for "Web Worker"-less support of third-party solutions, but we don't recommend to use it and possibly will remove from pdfjs-dist in the future once we will figure out proper webpack/browserify/etc. packages integration. 

Closing as now as answered.

**Comment by TomVanHaver** [comment]
Thank you for replying so fast.

We are certainly  intend to adapt the viewer UI (viewer.html)
Our core question was: for now we rely on viewer.css and viewer.js (= viewer layer) taken from the gh-package, but there is also a pdf-viewer.css and pdf-viewer.js in the pdfjs-dist package that are very similar. 

We do not know what files we need to take.

Our concern is that if we take the viewer.js from the gh-package and not the pdf-viewer.js from the npm package, we are "separating" the pdf.js, pdf-worker.js and viewer.js that we think are very tight coupled with each other ?

kind regards, Tom.

**Comment by yurydelendik** [comment]
> Our concern is that if we take the viewer.js from the gh-package and not the pdf-viewer.js from the npm package, we are "separating" the pdf.js, pdf-worker.js and viewer.js that we think are very tight coupled with each other ?

pdf-viewer.js in subset of viewer.js is somewhat established API (we trying to properly version API in pdf-viewer.js but not in viewer.js), so you need to take one of these two. If you stop at viewer.js, you have to assume all burden of merging from upstream on yourself. However pdf-viewer.js does not contain enhanced functionality (such as e.g. toolbars, sidebars or presentation mode)  that you may want.
