### ISSUE TITLE
Highlight Selected Text using PDFjs

### ISSUE THREAD

**Issue by ParthBDesai** [mozilla/pdf.js#7818]
I want to Highlight Selected text which is selected by mouse using PDFjs. please help me in solving this

**Comment by timvandermeij** [comment]
The text layer consists of `div` elements, each containing a word, sentence or character. Getting the selected text is not a trivial task because of this. If you know which `div` is selected, you can probably do something like http://stackoverflow.com/a/5379408 to get the selected text content. Closing as this is out of scope for the PDF.js project itself.

**Comment by hyiltiz** [comment]
Considering most PDF readers provide this feature, it would be quite a deal-breaker feature (for me) as a user. Is it impossible to implement within PDF.js?

**Comment by idibidiart** [comment]
Who determined that it's out of scope. Seems entirely arbitrary.

**Comment by mingwugmail** [comment]
@ParthBDesai  Can you reopen this issue?

**Comment by hyiltiz** [comment]
`pdf-tools` in emacs can deal with this https://github.com/politza/pdf-tools/issues/399. I would think `pdf.js` could also do this too.

**Comment by cuiyc2000** [comment]
so about 4 years later, problem soleved?

**Comment by hyiltiz** [comment]
Not sure how it got closed; as the referenced issue doesn't seem to only involve a workaround.
