### ISSUE TITLE
nameddest does not work

### ISSUE THREAD

**Issue by rmondesilva** [mozilla/pdf.js#7836]
[427_resume_56fba97.pdf](https://github.com/mozilla/pdf.js/files/605319/427_resume_56fba97.pdf)

I am using the latest version of Chrome in Windows 10 Desktop
-Latest PDF.js

I tried accessing the bookmark in file using:
http://localhost/assets/js/pdf.js/web/viewer.html#nameddest=section5
or
http://localhost/assets/js/pdf.js/web/viewer.html#section5

But it does not bring me to the page. It always show on first page.

I tried it in Mozilla and it does not work as well.

**Comment by Snuffleupagus** [comment]
That PDF document does *not* contain any named destinations, i.e. there's neither a `Names` nor a `Dests` entry in the `Root` dictionary of the file, which you can check yourself with http://brendandahl.github.io/pdf.js.utils/browser/.

Closing as invalid, since this cannot work without the PDF file actually specifying named destinations (note that it doesn't work in Adobe Reader either).
