### ISSUE TITLE
  Does pdf.js accept inputstream as param?

### ISSUE THREAD

**Issue by cooperLgm** [mozilla/pdf.js#7874]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
What is an "inputstream"?
The only references that I can find, when searching the web, seems to suggest that this a Java class/method.
PDF.js is written in Java*Script*, which isn't the same thing, so the answer would thus most likely be that this neither is (nor can) be supported.

Closing as answered; since the lack of details makes it difficult to understand what's really being asked here.

**Comment by 4urelienjo** [comment]
Hello ! I don't know if I can dig here, but : 
I have an issue for embedding a pdf in my html page in IE 11
With Chrome I write something along these lines 
`<embed src=<%:url%> type="application/pdf" style="width:100%; height:600px;" />`

The url is an action that return a **C# FileStream**.

Problem is that some historical users of our app are using IE 11 with Foxit as their PDF reader, and somehow Foxit is messing up with something and I have a white panel (I contacted them as well). 

In order to end all pain and unifiy the UX among browsers, I would like to implement a solution with PDF.js. Doest it worth the pain I'm gonna inflict myself ?
