### ISSUE TITLE
Add Toolbar in acroforms index 

### ISSUE THREAD

**Issue by greg59650** [mozilla/pdf.js#7880]
Hello,

I would like to know if in the example "acroforms" in the file index.html it would be possible to integrate the same toolbar as in the viewer.html.

/examples/acroforms/index.html

If yes, how to do this ?

I would like to modify the form of my pdf while keeping the possibility to use the actions of the toolbar (print, zoom, ...).

Thank you in advance for your future answers.

Greg

Configuration:

•Web browser and its version: Chrome Version 55.0.2883.75 
•Operating system and its version: Win 10
•PDF.js version: 1.5.188
•Is an extension: No

**Comment by Snuffleupagus** [comment]
> I would like to know if in the example "acroforms" in the file index.html it would be possible to integrate the same toolbar as in the viewer.html.

I suppose that it would be possible, however that is not something that we'll support.
More useful here is probably issue #7613, which tracks improved/added AcroForm support for the [default PDF.js viewer](https://mozilla.github.io/pdf.js/web/viewer.html). Please note that that work is still far from being complete, since it's a fairly large/difficult project, but it's probably a better starting point.

Closing as answered.
