### ISSUE TITLE
Error messages are not fully translated

### ISSUE THREAD

**Issue by slimjim181** [mozilla/pdf.js#7885]
As an non-english speaking user
I want to read the translated error message of my pdf document from PDF.js
So I can understand the error

The PDF file just needs to be a PDF with an invalid structure (or other error*):
![1e4ce406-bdff-11e6-815a-f8c6d717cd9a](https://cloud.githubusercontent.com/assets/4167522/21029539/1e4ce406-bdff-11e6-815a-f8c6d717cd9a.png)

**Configuration**:
- Web browser and its version: Chrome (latest), FF (latest), Safari 9/10
- Operating system and its version: Win7, Win10, OSX (latest), Linux (various)
- PDF.js version: v1.5.188

**Steps to reproduce**
- Change the browser language to something other than english (the example used Japanese)
- Open a 'invalid structure' pdf document into pdf.js
- On the red error banner, Click the 'More Information' button

**Expected Behaviour**
Error message is translated fully into browser language

**Actual Behaviour**
The most important part of the error message 'invalid PDF structure' is not translated and remains in english.

*This could be the case for other error messages not just 'invalid PDF structure'

**Comment by Snuffleupagus** [comment]
The "Invalid PDF structure" message, and others like it, that is provided when clicking on the "More Information" button is the *exact* error message as it comes from the API. In this case it originates at the worker side of PDF.js, more specifically [src/core/obj.js#L1156-L1158](https://github.com/mozilla/pdf.js/blob/e6720ad558e7fb99594eed1b9d5de6c5bc79ae8e/src/core/obj.js#L1156-L1158).

Please note that the additional information provided by the "More Information" button is intended for debugging purposes and thus aimed at developers, rather than regular users, hence those messages are not intended to be translated.
However, note that the string in the top left (which is visible *without* clicking on the "More Information" button) should contain a string saying approximately "Invalid or corrupted PDF file.", since this part is intended for regular users.

Closing as answered.
