### ISSUE TITLE
Feature request: Add type definitions for Typescript and make it available on NPM.

### ISSUE THREAD

**Issue by DannyBoyNg** [mozilla/pdf.js#7909]
I would like to request "type definitions" for Typescript for this library. It would be great to use this library in my Typescript projects.

Thanks.

**Comment by timvandermeij** [comment]
Could you elaborate a bit about what this is exactly? Why can't you use it in TypeScript project right now and how large is this change?

**Comment by yurydelendik** [comment]
It's possible to re-create definition files from display/api.js, and it will be easier for person who already done that. We shall adapt style from https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html . Problem will be to keep api.js and definition files in sync but will be easier after the latter is created.

**Comment by yurydelendik** [comment]
Notice that pdf.d.ts shall be created for the pdfjs-dist/build/pdf.js file and not files in the src/ folder.

**Comment by dannyboyng** [comment]
I'm not sure how much work it is to make "type declaration files" because I have no experience myself creating "type declaration files". 

I think you can use third party Javascript libraries in Typescript without "type declaration files", but when "type declaration files" are available, you can get rich intellisense while using third party libraries.

https://www.typescriptlang.org/docs/handbook/declaration-files/introduction.html is a good resource to start learning about "type declaration files".

**Comment by dannyboyng** [comment]
I would prefer if you could also make the "type declaration files" available on NPM. It makes it easy to include them in a project. 

For example by using to following command: npm install @types/pdfjs-dist --save-dev

**Comment by yurydelendik** [comment]
Publishing them via "@types/" is one way to do it and usually made by third-party contributors. If we are committed to include support for .d.ts files, then they can be included in pdfjs-dist's package.json manifest (there not reason to place them into separate npm package afaik)

**Comment by dannyboyng** [comment]
Apparently, you can bundle "type declaration files" together with your already existing NPM package. I forgot about that. No need to publish them to @types/

**Comment by dmiller9911** [comment]
There a d.ts file in the DefinitelyTyped repo for this:  [DefinitelyTyped pdf.js](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/4869992bc079b88280b9ff91213528904109e8ae/pdf/index.d.ts)  

I have not checked how complete or accurate it is, but it might be a good starting point.

**Comment by StevenLiekens** [comment]
I tried using the typings from DefinitelyTyped but they are so bad it's laughable. (laugh so you don't cry)

These are the latest typings (they were moved): https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pdfjs-dist/index.d.ts

Here's how you would use the them:
```ts
import { PDFJSStatic, PDFDocumentProxy, PDFPromise } from 'pdfjs-dist';

var pdfjs: PDFJSStatic;

pdfjs.getDocument('helloworld.pdf').then(function (pdf) {
	var pdfDoc: PDFDocumentProxy = pdf;
	var pageNum: number = 1;
	renderPage(pageNum);
});
```

Do you see how you have to import an imaginary `PDFJSStatic` type and then create a variable without initializing it? That's complete nonsense. (No offense to the original author)

Please reopen this issue because there is a need for better quality typings for pdfjs. Just take a look at a few of these SO questions:

- https://stackoverflow.com/questions/41503320/how-am-i-supposed-to-use-the-pdf-package-from-typescript
- https://stackoverflow.com/questions/46738700/how-can-i-get-typescript-to-load-the-pdf-js-npm-module-and-types-bindings-in-a
- https://stackoverflow.com/questions/47755268/importing-namespace-and-interface-with-methods-in-typescript-tsx-in-pdfjs-dist
- https://stackoverflow.com/questions/45467843/importing-pdfjs-breaks-ts-application
- https://stackoverflow.com/questions/47812903/how-to-import-pdf-js-into-typescript-using-npm

I think that most people who try to use pdf.js in a TypeScript app end up writing crap code or just give up and try something else.

So really, it would be MUCH better for TypeScript devs everywhere if the `pdfjs-dist` package had self-contained, high quality typings.

**Comment by therealparmesh** [comment]
Bumping this. `@types/pdfjs-dist` isn't even close.

**Comment by SandyGifford** [comment]
Struggling through `@types/pdfjs-dist` as well.  None of the text layer rendering is in it.  I've resorted to augmenting the module through declaration merging:

```typescript
declare module "pdfjs-dist" {
	export interface TextLayerRenderTask extends PDFLoadingTask<void> { }
	export interface RenderTextLayerOptions {
		textContent: TextContent;
		viewport: PDFPageViewport;
		container: HTMLElement;
	}
	export function renderTextLayer(options: RenderTextLayerOptions): TextLayerRenderTask;
}
```

**Comment by burtonator** [comment]
@SandyGifford yes... the pdf.js typescript types are very very stale it seems.

**Comment by burtonator** [comment]
If I send in a PR can we get this officially supported? The API isn't that difficult.

**Comment by burtonator** [comment]
This is really really really really needed.  pdf.js is great/functional but the API is essentially undocumented.  This REALLY needs to be rectified.

**Comment by soadzoor** [comment]
+1, we need proper type definitions!

**Comment by timvandermeij** [comment]
Please +1 the top comment instead of replying so it's easier for us to gauge interest from the community. Moreover, work for this is in progress; see #11235 which landed two days ago and #11209 which landed six days ago, both to improve the JSDoc comments for better documentation and TypeScript definition generation.

**Comment by geopic** [comment]
Is somebody working on writing up a types declaration file right now?

**Comment by timvandermeij** [comment]
#10575 has been worked on again, and we've decided that that's the way we would like to provide the TypeScript definitions.

**Comment by timvandermeij** [comment]
Fixed by pull request #12102. It took quite some time to converge to a solution that was both maintainable and tested, but thanks to hard work from community members it's done now. Future `pdfjs-dist` releases will start shipping the TypeScript definitions as generated from our JSDoc comments.

We are open for contributions from the community to improve our API documentation even further, not only for better API documentation but also for better types since they are both generated from the JSDoc comments in the files.

**Comment by LuisAlejandro** [comment]
Where are the instructions to use the typings provided by pdfjs-dist? I cant seem to find them anywhere

**Comment by hey24sheep** [comment]
@LuisAlejandro I am struggling with the same here. I can't declare the type for `const pdfjs: ???? = require('path/pdf.js')`

**Comment by koogle** [comment]
My suggestion is
```
import * as pdfjsLib from "pdfjs-dist";
import * as pdfjsViewer from "pdfjs-dist/web/pdf_viewer";
```
