### ISSUE TITLE
Question: How PDF.js fetches PDF contents

### ISSUE THREAD

**Issue by tweezy-au** [mozilla/pdf.js#7930]
I have a question about how PDF.js fetches the contents of a PDF file.

I'm using a 3rd party JS "flipbook" web app that is based around PDF.js. From my testing it seems that the initial request to the PDF is a normal HTTP "GET" request (although somehow the entire file is not received at that time). Subsequent requests are for a specific byte-range.

To me it would make more sense to send a HEAD request first to find out the file size.

With another viewer I was using, the first request is for the last 22 bytes, which is another quick way to get the total size.

I'm interested in knowing (if my assumption is correct), why a full GET request is initially sent. It seems to be an unnecessary overhead, especially for large PDFs.

**Comment by Rob--W** [comment]
Not all servers support HEAD; GET is the safest method to ensure a response.

The request is *aborted* if the server claims to support byte-range requests. Otherwise the request continues and its response is used.

The logic is here: https://github.com/mozilla/pdf.js/blob/c0a47fddcca573e49db3d1ba0a6a1777e9889224/src/core/network.js#L369-L434

If you are curious about range request implementations: I have also implemented a JS library that lists zip files. Its requirements are similar to the PDF fetching logic, since in both file formats (zip and pdf), the last chunk of the file is significant. You can learn more about it at:

- Documentation of HTTP logic: https://github.com/Rob--W/zipinfo.js#optimization-minimize-fetch
- Implementation: https://github.com/Rob--W/zipinfo.js/blob/56fadfed121263b38ee85746ede6a2b23ed9f41a/zipinfo.js#L111-L176

**Comment by timvandermeij** [comment]
Closing as answered.

**Comment by tweezy-au** [comment]
Thanks @Rob--W - makes perfect sense now
