### ISSUE TITLE
Load a PDF using javaFX

### ISSUE THREAD

**Issue by Gibran-16** [mozilla/pdf.js#7975]
Hello, I'm building a Desktop app using javaFX, I using pdf.js as a PDF viewer in my app, the problem is that I need to load a PDF with javaFX (url from any folder in my computer), then load that PDF in a webview with pdf.js, Is possible to do that?

I tried something like that but with a local url from my computer and it didn't work.
http://mozilla.github.io/pdf.js/web/viewer.html?file=compressed.tracemonkey-pldi-09.pdf

**Comment by timvandermeij** [comment]
It should be possible, judging by previously opened issues (https://github.com/mozilla/pdf.js/issues?q=is%3Aissue+javafx+is%3Aclosed). If the local URL is not working, you could also pass the `base64` encoded contents to PDF.js, as is done in https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html for example. However, since JavaFX is out of scope for the PDF.js project, I'm closing this issue.
