### ISSUE TITLE
Bug 1334831 - Use .remove() instead of .parentNode.removeChild

### ISSUE THREAD

**Issue by fqueze** [mozilla/pdf.js#8008]
Landed on mozilla-central today:
https://hg.mozilla.org/integration/mozilla-inbound/diff/a9d172aa4414/browser/extensions/pdfjs/content/build/pdf.js
https://hg.mozilla.org/integration/mozilla-inbound/diff/a9d172aa4414/browser/extensions/pdfjs/content/web/viewer.js

**Comment by Snuffleupagus** [comment]
Looking at https://developer.mozilla.org/en-US/docs/Web/API/ChildNode/remove#Browser_compatibility and http://caniuse.com/#feat=childnode-remove, it seems that not all browsers support this (notably Internet Explorer is missing support).

Please note that the general PDF.js library is supposed to usable cross-browser, and not just in Firefox, hence we cannot make this change here (until such a time that we'd explicitly remove support for IE from PDF.js).

Ninja edit: These changes were reverted in `mozilla-central` as part of https://bugzilla.mozilla.org/show_bug.cgi?id=1335048.

**Comment by timvandermeij** [comment]
I agree that using the preprocessor just for this small case does not make sense and only complicates the code. At least for now we need to have cross-browser support, so let's close this as won't-fix for now. If it turns out that upstream has problems if we don't make this change (for example, if it constantly gets reverted after an update), we could use the preprocessor, but let's only do that if absolutely required.

**Comment by timvandermeij** [comment]
By the way, we appreciate that you keep us updated about the upstream changes. Most of the upstream changes have been merged here as well, and we have also been able to adjust the add-on code on our side so that upstream needs less ESLint exceptions, so the collaboration on this is really nice.
