### ISSUE TITLE
My pdf displays only the lines not fonts

### ISSUE THREAD

**Issue by MaitriSejpal** [mozilla/pdf.js#8013]
Link to PDF file (or attach file here):
![pdfproblem](https://cloud.githubusercontent.com/assets/25455958/22464384/91885c0a-e7dc-11e6-8f51-98562f9a351f.png)

this is my pdf file and it is not loading the fonts in the frame.

Please help me out from this issue

Thanks in advance

**Comment by Snuffleupagus** [comment]
Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when reporting an issue.
Without e.g. the PDF file in question, the issue will be closed as incomplete.

**Comment by MaitriSejpal** [comment]
Link to PDF file (or attach file here):
![pdfproblem](https://cloud.githubusercontent.com/assets/25455958/22464384/91885c0a-e7dc-11e6-8f51-98562f9a351f.png)
Confi
this is my pdf file and it is not loading the fonts in the Iframe.

Configuration:
Web browser and its version:Chrome 55.0.2883.87
Operating system and its version: Windows 10


Please help me out from this issue

Thanks in advance

**Comment by Snuffleupagus** [comment]
You have still not provided the *PDF file* itself (i.e. a file with the `.pdf` extension), but only a screen-shot of the problem.

**Comment by MaitriSejpal** [comment]
Sorry but i can not provide you that Pdf file as it contains Personal data of our Customers.

Is there any other ways so that you can help me out from this problem.

**Comment by Snuffleupagus** [comment]
Without a PDF file, it's *very* difficult to provide any help. Especially since other vital information is missing, such as e.g. the PDF.js version and whether or not it's a custom PDF.js implementation (which is information that is requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).

However, just looking at the screen-shot it seems that you're using an older version of PDF.js and that it thus most likely is a custom deployment.
I would first of all recommend updating to the latest release, and furthermore check that you've properly included the CMaps. Failing to provide the CMaps *can* sometimes result in failures similar to those above, and would be indicated by errors in the browser console.
For documentation about the CMaps, please refer to https://github.com/mozilla/pdf.js/blob/master/src/display/global.js#L113-L124.

Closing as incomplete, since it's unfortunately not possible to provide more assistance with the limited information provided thus far.
