### ISSUE TITLE
My pdf link is not working

### ISSUE THREAD

**Issue by robinblogspot** [mozilla/pdf.js#8073]
Configuration:
- Web browser and its version: chrome 56 and firefox 51.0.1
- Operating system and its version: windows
- PDF.js version: 1.6.210

working in pc browser ie 10
working in mobile browsers.

not showing in pc browser : chrome 56 and firefox 51.0.1

this is the pdf link: http://scripturefeast.net/web/viewer.html?file=/web/books/pdf/book6/6%20th%20Book%204-5-6.pdf

**Comment by THausherr** [comment]
I get a 403 error when trying to open the file from java. On my mobile and on the desktop, I get a red bar and "Fehlende PDF-Datei" which means "missing PDF file".

**Comment by Snuffleupagus** [comment]
> [...] this is the pdf link: http://scripturefeast.net/web/viewer.html?file=/web/books/pdf/book6/6%20th%20Book%204-5-6.pdf

That links to a custom deployment of the PDF.js default viewer, where at least the `viewer.html` file has been modified, and looking in the browser console I see the following error in Firefox 54:
```
Content Security Policy: The page’s settings blocked the loading of a resource at self (“script-src http://scripturefeast.net https://www.google.com”). Source: 
//<![CDATA[
try{if (!window.CloudFlare)....
```
and the following error in Chrome 57:
```
Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://www.google.com". Either the 'unsafe-inline' keyword, a hash ('sha256-zeaoG+1OE4xkEqky1oU58S7/Lx2mHLrJIkcDJzDDAyM='), or a nonce ('nonce-...') is required to enable inline execution.
```

This thus points to an issue with the custom deployment *itself*, and how the Content Security Policies has been set up on the server, rather than with the PDF.js library or its default viewer.
Closing as invalid, since this ought to be a configuration issue on your server which we cannot address.
