### ISSUE TITLE
Feature Request - Support custom keybindings

### ISSUE THREAD

**Issue by kabeersvohra** [mozilla/pdf.js#8077]
Hi

I am an avid user of vimium and it has increased my productivity massively. However vimium does not work with pdf tabs and it is a hindrance to my workflow, is there any way you can add an option to add custom keybindings to pdf.js so that I can add certain keybindings I use regularly to my pdf tabs as well?

I understand that chrome extensions cannot communicate but would basic keybinding customisation be a difficult task?

Many thanks

Kabeer

**Comment by timvandermeij** [comment]
Closing since this is tracked in #7019.

**Comment by KVohra95** [comment]
Can you reopen this? I am actually fine with the scrolling in pdf.js being one page, what I really want is custom keybindings because then i can use all of the other keybindings present in vimium like gt to change tabs etc. It becomes a hindrance to consistency when keybindings I use a lot are not available in pdf tabs

**Comment by Snuffleupagus** [comment]
This feature seems like something that would have a disproportionate implementation/testing/maintenance overhead for the default viewer, since making all keyboard shortcuts customizable would require, relatively speaking, a lot of code for a minor feature. It's also not really clear how the actual customization would even work, but I'd assume that some sort of UI would be needed (thus exacerbating the points above).

Given that the default viewer is used in Firefox, there's would also be the question of how to prevent the user modifying keyboard shortcuts in such a way that they interfere with the browser ones.
Generally, this feature seems special enough that referencing https://mozilla.github.io/pdf.js/getting_started/ probably is relevant here:
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. *However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.*

Closing this issue as WONTFIX?
