### ISSUE TITLE
Printing PDF from Firefox replaces all images with last image

### ISSUE THREAD

**Issue by airblade** [mozilla/pdf.js#8086]
I'm hoping this is the place to post issues with Firefox's PDF printing.  Apologies if it isn't!

Link to PDF file (or attach file here): [Labels.pdf](https://github.com/mozilla/pdf.js/files/787392/Labels.pdf)

Configuration:
- Web browser and its version: Firefox 51.0.1 (64-bit)
- Operating system and its version: OS X El Capitan 10.11.6
- PDF.js version: whatever is in my Firefox
- Is an extension: no

Steps to reproduce the problem:
1. View PDF in Firefox.
2. Print PDF directly from Firefox.

The PDF shows four "cells" for printing on a sheet of labels.  Each label is for a different item, and each item has its own unique barcode.  The barcodes are Code128C barcodes, as PNG images, encoding the numbers 474100, 474110, 474114, 474116 respectively.

What is the expected behavior? (add screenshot)
- The printed images are the same as they are on-screen.

What went wrong? (add screenshot)
- When printed, all images have been replaced by the final image.  In other words every barcode image is the same as the last one (encoding 474116).
- Here is a photo of the print-out: ![img_9552](https://cloud.githubusercontent.com/assets/7265/23125302/0289729a-f769-11e6-8a4b-19e2a4d7b668.JPG)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
N/A.

The PDF was generated by a webapp I wrote.  One of the users raised this problem, saying it started around a couple of weeks ago.

This is when the problem occurs:

- Printing the PDF from the webapp.
- Saving the PDF from the webapp, viewing the saved PDF in Firefox, and printing (as described above).

The problem doesn't occur in these situations:

- Saving the PDF from the webapp, opening it in Preview.app, and printing from there.
- Printing the PDF from the webapp using Safari.

**Comment by airblade** [comment]
Also: the right-most line of each barcode image is truncated at the bottom.  You can see this in the PDF and in the photo of the printed PDF.  The images also appear this way on screen in the webapp.

The images aren't modified like this in Safari or Chrome.

I don't know whether this is related but it's odd.

**Comment by mbraunerDE** [comment]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: 51.0.1
- Operating system and its version: macOS Sierra 10.12.3
- PDF.js version: unkown
- Is an extension: no

Steps to reproduce the problem:
1. Start Firefox on macOS
2. open our client website (sry, no link for you)
3. click on button to generate pdf 

What is the expected behavior? (add screenshot)
The print should always be like [no_barcode_correct.pdf](https://github.com/mozilla/pdf.js/files/811125/no_barcode_correct.pdf)

What went wrong? (add screenshot)
The preview render it nice, but the print out of the preview will be [no_barcode_failure.pdf](https://github.com/mozilla/pdf.js/files/811126/no_barcode_failure.pdf)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
unkown

This problem only occured with firefox for mac, no other browser or operating system is affected.

**Comment by airblade** [comment]
This appears to be fixed in Firefox 52.0.1.

**Comment by timvandermeij** [comment]
Closing in that case. Indeed, this does sound like an upstream issue.
