### ISSUE TITLE
Question:where can i find java-script built-in functions

### ISSUE THREAD

**Issue by jodevsa** [mozilla/pdf.js#8108]
Hello, 
i'm looking for the definitions of built-in functions like util.printf

**Comment by timvandermeij** [comment]
There is no `printf` in PDF.js. I think you are confusing PDF.js with another library. Our utils are mostly in https://github.com/mozilla/pdf.js/blob/master/src/shared/util.js.

**Comment by jodevsa** [comment]
what i meant is, javascript libraries used by the pdf reader mentioned here:https://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/js_api_reference.pdf

**Comment by timvandermeij** [comment]
PDF.js disables all JavaScript embedded in a PDF file for security reasons. The only exception is the `print` command to initiate a printing command, which is handled separately to simulate clicking the print button. Other JS is disabled and so far we do not intend to enable any other JS because of security concerns.

**Comment by jodevsa** [comment]
thanks alot for clarification .
