### ISSUE TITLE
 ES5 strict mode and CSP support

### ISSUE THREAD

**Issue by hemantdamahe** [mozilla/pdf.js#8141]
Hi,

Our client is very particular about security. They allow only those external JavaScripts which support ES5 strict mode and CSP. So can you please add this feature to your JS libraries.

**Comment by Snuffleupagus** [comment]
The PDF.js code is already executed in (ES5) strict mode. (However, note that we're currently in the process of migrating to ES6 modules, but we'll continue to support ES5 through Babel for the time being.)

As for CSP support, I think that you'll need to provide a lot more context here since it's difficult to know what you're actually asking for! Generally, the more details the better; see also [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).

**Comment by timvandermeij** [comment]
Indeed, ES5 strict mode is already the default. You should also be able to use a CSP, as multiple issues regarding that have been fixed. Some open ones remain (such as #5573), but if there are specific issues with CSPs separate issues should be opened for them.

Closing as answered.

**Comment by hemantdamahe** [comment]
In our case Content Security Policy (CSP). unsafe-eval and unsafe-inline are disallowed. Libraries using eval() or inline JavaScript code execution will not work with LockerService.

Please refer this link for more info : https://developer.salesforce.com/blogs/developer-relations/2017/02/lockerservice-lightning-container-third-party-libraries-lightning-components.html?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+SforceBlog+%28Salesforce+Developers+Blog%29
