### ISSUE TITLE
Embedded JavaScript in the original pdf

### ISSUE THREAD

**Issue by SuperNoob13** [mozilla/pdf.js#8143]
[PDF.pdf](https://github.com/mozilla/pdf.js/files/830944/PDF.pdf)
Hi Guys,

Is it possible to run the embedded pdf javaScript coding if I converted the pdf to the page view ?

  var pdfPageView = new PDFJS.PDFPageView({
          container: container,
          id: pageNum,
          scale: DEFAULT_SCALE,
          defaultViewport: pdfPage.getViewport(DEFAULT_SCALE),
          annotationLayerFactory: new PDFJS.DefaultAnnotationLayerFactory(),
          renderInteractiveForms: true,
        });

I also tried to get the JavaScript with the getJavaScript() function on the pdf document.
But I don't get anything back. 

Attached is the pdf file 

Thanks for your help!

Christopher

**Comment by timvandermeij** [comment]
Getting the JavaScript for this PDF file works with the most recent version of PDF.js. Visit https://mozilla.github.io/pdf.js/web/viewer.html and run the following in the browser console: `PDFViewerApplication.pdfDocument.getJavaScript().then(function (js) { console.log(js); });`. You'll then see the embedded JavaScript. The regular `getJavaScript` call thus works.

There is, however, another problem with this PDF file. Some widget annotations have a parent that is not a dictionary and therefore the field name construction crashes. The second page doesn't render because of this. The pull request below fixes that as well.

**Comment by SuperNoob13** [comment]
Thanks for your help,
Can I run the embedded JavaScript automatically in the backround ?, I looked into the pdf,js core and there I found just the print command.

**Comment by Snuffleupagus** [comment]
> Can I run the embedded JavaScript automatically in the backround ?, I looked into the pdf,js core and there I found just the print command.

Please refer to e.g. https://github.com/mozilla/pdf.js/issues/8140#issuecomment-285284960.

**Comment by SuperNoob13** [comment]
Thanks :)
