### ISSUE TITLE
ES5 strict mode and CSP support

### ISSUE THREAD

**Issue by hemantdamahe** [mozilla/pdf.js#8161]
Hi,
In our case Content Security Policy (CSP). unsafe-eval and unsafe-inline are disallowed. Libraries using eval() or inline JavaScript code execution will not work with LockerService.

Please refer this link for more info : https://developer.salesforce.com/blogs/developer-relations/2017/02/lockerservice-lightning-container-third-party-libraries-lightning-components.html?utm_source=feedburner&utm_medium=email&utm_campaign=Feed%3A+SforceBlog+%28Salesforce+Developers+Blog%29

**Comment by Snuffleupagus** [comment]
*This appears to be a duplicate of issue #8141.*

As mentioned in https://github.com/mozilla/pdf.js/issues/8141#issuecomment-285485338, there's already an open issue that tracks this for the case in [src/core/function.js](https://github.com/mozilla/pdf.js/blob/master/src/core/function.js); please refer to issue #5573.
For the case in [src/core/font_loader.js](https://github.com/mozilla/pdf.js/blob/master/src/display/font_loader.js), there's the `PDFJS.isEvalSupported` parameter that can be used to disable `eval` there (at the cost of worse performance); please refer to [src/display/global.js#L246-L252](https://github.com/mozilla/pdf.js/blob/2b17188998036df02f6413795714f89a552d31f5/src/display/global.js#L246-L252).

Closing, since this should already either be tracked elsewhere, or a work-around is available.

If the above isn't sufficient information, then as outlined in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) and mentioned in https://github.com/mozilla/pdf.js/issues/8141#issuecomment-285485338, please try provide more *specific* information about what *exactly* in PDF.js isn't working with these Content Security Policies.
