### ISSUE TITLE
Newer versions are unstable with security software

### ISSUE THREAD

**Issue by JasonNVSD** [mozilla/pdf.js#8162]
Link to PDF file (or attach file here): http://www.cic.gc.ca/english/passport/forms/pdf/pptc153.pdf

Configuration:
- Web browser and its version: Firefox ESR 52.0
- Operating system and its version: Windows 7 SP1 Enterprise
- PDF.js version: 1.6.315 (and others)
- Is an extension: no?

Steps to reproduce the problem:
1. Install Sophos Endpoint Security and Control
2. Open any AcroForm PDF (may have to reload a couple times to reproduce issue)

What is the expected behavior? The PDF should open.

What went wrong? The browser stops responding and doesn't recover.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Hello.  Our organization has 2,000 PCs with Firefox ESR and Sophos Endpoint Security and Control (SESC).  With ESR 45.7 (PDF.js 1.3.76) we had no problems.  Now that we've deployed ESR 52.0 (PDF.js 1.6.315), the browser often stops responding when viewing any AcroForm PDF.  I also tried PDF.js 1.6.210 and 1.7.225 and they have the same problem.  SESC is not blocking or logging anything when this happens.  I realize you may want to dismiss this as Sophos' problem, but this is common software and I suspect that this issue exists with other security software as well.

**Comment by timvandermeij** [comment]
Yes, this really is a Sophos-specific issue. I have not heard of issues with other security software before. On top of that, PDF.js does nothing for AcroForm rendering that a regular web page cannot do, i.e., it just renders normal form elements such as input fields and check boxes. By default, AcroForm rendering isn't even enabled, so I highly doubt AcroForm rendering is the issue here. Scripts in the PDF are not executed by PDF.js, so that can also be ruled out. There may be something else in the PDF file that triggers Sophos, but it's impossible for us to tell, especially if Sophos does not log anything. I would recommend to contact Sophos support for this and ask them how to debug what's triggering their software.
