### ISSUE TITLE
[Feature Request] Standalone Print Page

### ISSUE THREAD

**Issue by jtnw** [mozilla/pdf.js#8173]
Is it possible we could make a standalone printing script that call on scripts such as:

firefox_print_service.js
pdf_print_service.js
chromecom.js

A lot of work is being done on printing and it would be nice to have all of that on a stripped down page for standalone projects. I am happy to help with this. I already did make one a year or so ago which we can use as a starting point if needed. It's pretty simple, it just renders each page as a canvas and does a few things like checking for ios/android and using 150 dpi for those mobile browsers instead of 300dpi. It has a progress bar and a few stylesheets, etc. However it doesn't implement Firefox's faster printing as I didn't know about that a year ago.

In any case, I need to re-write the code I did a year ago and if no one else can join in this task I can eventually release the code I end up making here.

**Comment by timvandermeij** [comment]
This would be interesting to add to https://github.com/mozilla/pdf.js/wiki/Gallery-of-user-projects-and-modifications. Feel free to let us know once it's done and we'll add it there so other people can use it as well. Since it's not something that is directly needed for the PDF.js library itself, I'm closing this issue.

**Comment by yurydelendik** [comment]
@jtnw do you mean to refactor classes to be used as components without a viewer? if yes, you can propose an API as a PR and we will try to prove a feedback.
