### ISSUE TITLE
Now it's can't work

### ISSUE THREAD

**Issue by Smoranlr** [mozilla/pdf.js#8213]
pdf.js-master/web/viewer.html can't open ;
1. at system.js  error: Failed to load resource: net::ERR_FILE_NOT_FOUND
2.Uncaught ReferenceError: SystemJS is not defined
    at systemjs.config.js:36
    at systemjs.config.js:60
3.Uncaught ReferenceError: SystemJS is not defined
    at HTMLDocument.webViewerLoad (viewer.js:174)

**Comment by Snuffleupagus** [comment]
Did you follow *all* of the steps described in https://github.com/mozilla/pdf.js#getting-the-code?
If not, please make sure to do so, since the `npm install` command should install both SystemJS (and other necessary dependencies).

Closing as incomplete for now, if you need further assistance please make sure that you provide a *detailed* description of *exactly* what you tried and what didn't work.
