### ISSUE TITLE
PDF with images with different formats (eg jpg and png) doesnt gets downloaded on Chrome in IPAD

### ISSUE THREAD

**Issue by shivam-bhatt** [mozilla/pdf.js#8238]
PDF with images with different formats (eg, I am using a jpg and a png image) does'nt gets downloaded on **Chrome**  in **IPAD**. 
On safari browser on IPAD it works fine.
On desktop all browsers it works fine
DPI of both images = 72 dpi

But if I use images with same format, like both images are jpg or png it works fine.
Can anyone explain me why this type of behavior is there for only Chrome browser on IPAD

**Comment by timvandermeij** [comment]
It could be a browser bug or an image decoding issue specific to Chrome, but it is impossible to tell without the actual PDF file. Please provide that and the other information requested in the issue template  (https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) to reopen this issue, since I'm closing it as incomplete for now.
