### ISSUE TITLE
Don't guess file name from non-http/file URLs

### ISSUE THREAD

**Issue by yurydelendik** [mozilla/pdf.js#8263]
From e-mail:

> pdf.js tries to find a nice filename for the document. this takes an incredible amount of time when a data-uri document is displayed

data: or blob: schemas doesn't any useful info to guess title, so viewer.js:1709-1710 / getPDFFileNameFromURL may skip regex if non-http/file URL is used.

**Comment by Snuffleupagus** [comment]
> data: or blob: schemas doesn't any useful info to guess title, so viewer.js:1709-1710 / getPDFFileNameFromURL may skip regex if non-http/file URL is used.

Wouldn't that basically break the use-case that PR #8024 added, since it depends on the filename being appended to a `blob:` URL for e.g. the download prompt to be able to display the correct filename, i.e. does this mean that we need to back out that PR?

**Comment by yurydelendik** [comment]
> Wouldn't that basically break the use-case that PR #8024 added

I'm sorry, but I'm not quite following this. I'm talking about use in https://github.com/mozilla/pdf.js/blob/31f88756148475440c94c3cc2ad5da25139b101b/web/app.js#L578 and https://github.com/mozilla/pdf.js/blob/31f88756148475440c94c3cc2ad5da25139b101b/web/app.js#L578. If there is a problem with logic in #8024, can we improve the attachment opening in some way or reduce the proposed above logic to not exclude such attachment URLs?

**Comment by Snuffleupagus** [comment]
Looking at https://github.com/mozilla/pdf.js/blob/d6dfc26d4e578ce11ecb28132f166022edb3439f/web/pdf_attachment_viewer.js#L112, which for PDF attachments (in FIREFOX/MOZCENTRAL builds) is then used by `PDFViewerApplication.download` to determine the file name at https://github.com/mozilla/pdf.js/blob/d6dfc26d4e578ce11ecb28132f166022edb3439f/web/app.js#L751.

It might not be an issue, but I simply wanted to mention that particular use-case, such that we don't inadvertently break the file name detection there.

**Comment by Snuffleupagus** [comment]
Unless I'm mistaken, this problem described in the first post *mainly* concerns `data:` URLs, since they can be arbitrarily long. For a `blob:` URL on the other hand, since the identifier part has a fixed length, it shouldn't be any worse than the length of e.g. a `http:` or `file:` URL.

If the above is a reasonable analysis, then I'm wondering if something along the lines of https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-8263 would work[1]?
Since I'm not totally sure if I've completely grasped all of the problems with the current code, I figured I'd ask for feedback first before submitting a PR.

---
[1] Note that since there's a couple of protocols that we probably want to allow (e.g. http/https/ftp/file/...), and that `getPDFFileNameFromURL` needs to support relative URLs as well, it seemed to me that it may be easier/more efficient to just disallow `data:` URLs explicitly rather than attempting to white-list a bunch of cases.
