### ISSUE TITLE
移动端可以读取网络的pdf文件显示吗

### ISSUE THREAD

**Issue by wasonxie** [mozilla/pdf.js#8278]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is an extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by wasonxie** [comment]
移动端可以读取网络的pdf文件显示吗

**Comment by Snuffleupagus** [comment]
Closing as invalid; please use English when reporting bugs (or asking questions), since we'll not be able to help otherwise.
Also, when opening an issue, please make sure that you provide as much of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) as possible.
