### ISSUE TITLE
Part of pdf is not rendering [Invalid canvas size error in console]

### ISSUE THREAD

**Issue by anirudh-modi** [mozilla/pdf.js#8330]
Link to PDF file (or attach file here
[FailingPDF.pdf](https://github.com/mozilla/pdf.js/files/954710/FailingPDF.pdf)

Configuration:
- Chrome (57.0.2987.133)
- MAC OS (10.10.5)
- PDF.js version:1.8.252
- Is an extension: No

Steps to reproduce the problem:
1. Kindly upload the file attached above in the https://mozilla.github.io/pdf.js/web/viewer.html
2. When the first page is rendered it throw an error on the console telling invalid canvas size

A part of the pdf present in the first page was not loaded, and the loading is stuck.
Below is the error, and the loading sign on the pdf first page
![error](https://cloud.githubusercontent.com/assets/16587779/25381270/b27d1f00-29d0-11e7-888b-50ef7f321463.png)
![loadingsign](https://cloud.githubusercontent.com/assets/16587779/25381271/b27f1ec2-29d0-11e7-9844-50d436a5835c.png)

Ideally it should have loaded the part of the pdf.

**Comment by Snuffleupagus** [comment]
The PDF file is corrupt, and even Adobe Reader fails to render it (there's even a warning shown).
The problem is that the PDF file includes a `/Pattern` entry that is completely bogus. Note in particular how the `/BBox` is empty, which explains the failures, and also that there's no actual content in the pattern:

![corrupt](https://cloud.githubusercontent.com/assets/2692120/25382942/191037e6-29ba-11e7-89fb-122d1f3ff632.png)

**Comment by anirudh-modi** [comment]
Ok.. so if there a way to figure out if the file is corrupt or not??

So that I can handle corrupt files..
