### ISSUE TITLE
Bug 1355056 - Replace (function(args) { /* do stuff using this */ }).bind(this) with arrow functions

### ISSUE THREAD

**Issue by fqueze** [mozilla/pdf.js#8343]
See https://hg.mozilla.org/mozilla-central/rev/0f97f76c0b34#l26.1

**Comment by timvandermeij** [comment]
Thank you for filing this issue! Fortunately we're already working on it for our ES6 conversion project.

**Comment by yurydelendik** [comment]
we cannot do it for pdf.worker.js just yet, we will need to replace that with, e.g. `var _self=this; ... function () { _self... }`

**Comment by Snuffleupagus** [comment]
Please do not edit PDF.js specific files directly on mozilla-central without the changes being made *here* first, since *this* GitHub repository is the canonical upstream repository, and mozilla-central is simply a downstream consumer of it.

In cases like these, changes made directly in mozilla-central will most likely just cause merge conflicts (and be reverted) during the regular PDF.js updates.
At the very least, for these kind of mass changes, personally I think that it would be *most* helpful if these two directories were excluded: http://searchfox.org/mozilla-central/source/browser/extensions/pdfjs/content/build, http://searchfox.org/mozilla-central/source/browser/extensions/pdfjs/content/web.

**Comment by Snuffleupagus** [comment]
Closing as fixed by PRs #8354, #8355, #8370, and #8377.
