### ISSUE TITLE
Text areas overrun each other

### ISSUE THREAD

**Issue by yurivict** [mozilla/pdf.js#8405]
Link to PDF file (or attach file here):
http://journals.aps.org.secure.sci-hub.io/prl/abstract/10.1103/PhysRevLett.83.1558

Configuration:
- Web browser and its version: Chrome 57.0.2987.133
- Operating system and its version: FreeBSD 11
- PDF.js version: n/a, embedded in the site, no version is displayed
- Is an extension: no

Steps to reproduce the problem:
1.  go to URL
2. observe the problem

What is the expected behavior? normal document display

What went wrong? 
![pdfj-text-overrun](https://cloud.githubusercontent.com/assets/271906/26030127/5053face-37fe-11e7-88ad-81d33ddde7e5.png)

**Comment by Snuffleupagus** [comment]
> PDF.js version: n/a, embedded in the site, no version is displayed

The screen-shot that you provided is *not* of PDF.js, but actually shows part of the UI in PDFium (i.e. the PDF reader built-in to the Chrome browser). Looking at the HTML of the page, the PDF file is displayed within an `iframe`, which thus invokes the default PDF viewer of the browser.

Closing as invalid, since we cannot provided support for *another* PDF viewer.
