### ISSUE TITLE
Missing Plugin on Chrome/Safari but working in FF

### ISSUE THREAD

**Issue by LubenZA** [mozilla/pdf.js#8449]
Hi

I have been searching through the issues but can't find this one.

I am embedding an object in my HTML but is doesn't work in any browser except FF.
See link below:
http://www.nbits.co.za/Impression2/

This is strange because if you navigate directly to the viewer it works:
http://www.nbits.co.za/Impression2/web/viewer.html

I cannot expect my site visitors to have to download a plugin; some people are not tech savvy.
Is there a way to resolve this? Can someone point me to the correct documentation?

Best Regards

**Comment by Snuffleupagus** [comment]
Looking at how you attempt to embed the viewer, it seems that you have made a typo in the `type` attribute of the `<object>` tag:
```html
<object type="type/html" style="width:100%;height:720px;" data="web/viewer.html?file=GettingStarted.pdf" title="undefined"></object>
```
I'm assuming that it should be `type="text/html"` instead, which probable explains the issue; based on the first couple of results [from a simple search](https://www.google.se/#q=chrome+%3Cobject%3E+type+type/html).

Closing as answered (and invalid), since this really doesn't appear to be related to PDF.js at all, but rather a seems to be a general HTML issue.

**Comment by LubenZA** [comment]
Thank you sorted!
