### ISSUE TITLE
Why PDFJS redirects to Download Manager?

### ISSUE THREAD

**Issue by priyabratta1991** [mozilla/pdf.js#8454]
Why my pdf are always redirected to download in download manager while opening in pdfjs viewer?

**Comment by Snuffleupagus** [comment]
It's extremely difficult to understand what the problem might be, since *all* of the required details are missing; please see https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

However, guessing as to what the problem might be, I'd recommend that you follow https://support.mozilla.org/en-US/kb/disable-built-pdf-viewer-and-use-another-viewer and ensure that the `Portable Document Format (PDF)` entry is set to `Preview in Firefox`.

Closing as incomplete for now; please provide all the required details to re-open the issue.
