### ISSUE TITLE
Crash after try "javascript: window.print()"

### ISSUE THREAD

**Issue by wellington1993** [mozilla/pdf.js#8479]
Link to PDF file (or attach file here): `http://www.pdf995.com/samples/pdf.pdf`

Configuration:
- Web browser and its version: `Firefox Nightly 55.0a1`
- Operating system and its version:  `Ubuntu 17.04`
- PDF.js version:
```
  Criador do PDF: GNU Ghostscript 7.05
  Versão do PDF: 1.3
  Número de páginas: 5 
```

- Is an extension:

Steps to reproduce the problem:
1. Open PDF
2. Try to do javascript: window.print() on URL bar or console.
3. Page Crash

I need to open and automatically print  the PDF file.

What is the expected behavior? (add screenshot)
Print Message Dialog.

What went wrong? (add screenshot)
Tab Crash
https://webcompat.com/issues/7189

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Native Nightly

**Comment by timvandermeij** [comment]
This does work with Firefox 53.0.3 on Arch Linux. According to the page you link to, it works for other people as well. This is most likely an issue in Nightly (which can definitely happen due to its nature), so I suggest filing this upstream at Bugzilla with a link to the crash report (check `about:crashes` for that). Closing since there is nothing we can do about this on the PDF.js side.
