### ISSUE TITLE
Linux. Letters have different sizes

### ISSUE THREAD

**Issue by Teir** [mozilla/pdf.js#8484]
Link to PDF file (or attach file here):
[no_spaces.pdf](https://github.com/mozilla/pdf.js/files/1051520/no_spaces.pdf)

Configuration:
- Web browser and its version: Google Chrome 58.0.3029.110 (64-bit) 
- Operating system and its version: Linux version 4.4.60-1.el7.elrepo.x86_64 (mockbuild@Build64R7) (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) ) #1 SMP Sat Apr 8 12:50:45 EDT 2017
- PDF.js version: demo (1.8.423)
- Is an extension:

Steps to reproduce the problem:
1. Open no_spaces.pdf in pdf.js.

What is the expected behavior? (add screenshot)
Letters have the same sizes. Just like in Windows 7.
![no_spaces_windows7](https://cloud.githubusercontent.com/assets/19780067/26777503/22f8a2ba-49e6-11e7-9c58-72f0451d5f19.png)

What went wrong? (add screenshot)
Letters have different sizes.
![no_spaces](https://cloud.githubusercontent.com/assets/19780067/26777376/9ebc5cf8-49e5-11e7-87a2-8b5c6995bcae.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by timvandermeij** [comment]
I think the font weight is meant here instead of the size.

**Comment by nish17** [comment]
I want to contribute to this project(PDF.js).
I have gone through almost all resources available for contribution.
Still, as it's my first time for a contribution I may make some mistake.
I dont understand in which file one has to make changes.
and how to understand that which function is causing bugs.
please help.
I'll definitely like to work on this issue.

**Comment by Snuffleupagus** [comment]
> I think the font weight is meant here instead of the size.

I'm not sure that's the issue, since if you zoom in on the screen-shots the height of the letters on Linux does seem to vary (as indicated in the OP).[1]

It seems to me that this isn't so much a font-conversion issue, but rather an issue with `<canvas>` text rendering on different platforms (and possibly dependent on hardware acceleration being available as well).
Thus, I think this is more of a browser/platform issue, rather than a PDF.js one; I'm updating the labels to reflect that.

---
Also, how "bold" the font weight looks depends on the zoom level, as is often the case. However, comparing PDF.js and Adobe Reader (with matching page sizes), it looks fine to me on Windows.

**Comment by timvandermeij** [comment]
Fixed in the most recent version. The characters all have the same height now.
