### ISSUE TITLE
Motivation for asking to use a modified version of the viewer

### ISSUE THREAD

**Issue by stijnherreman** [mozilla/pdf.js#8513]
https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website says:

> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. _However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it._

What is the motivation for this? Is it a technical reason? Or are you hoping to encourage people to build more viewers? Please clarify.

**Comment by yurydelendik** [comment]
> What is the motivation for this? Is it a technical reason?

It's multiple reasons. In numerous occasions, people mistakenly called defects in custom deployments as Firefox bugs (since PDF.js demo viewer looks nearly identical to PDF Viewer). Security, see #6916. Also, people are asking for configuration that is not easy to invest in (e.g. skins, adding/removing toolbar buttons, etc.) -- while it is fixable it requires lots of investment in the support.

> Or are you hoping to encourage people to build more viewers?

Yes, this too.

Closing as answered.
