### ISSUE TITLE
How can i set the fontsize of content in some pdf?

### ISSUE THREAD

**Issue by huangche007** [mozilla/pdf.js#8529]
I want to set the fontsize of content in some pdf,Because I use this plug in my mobile web app,I found all contents are so small by default

**Comment by Snuffleupagus** [comment]
PDF.js is a PDF *reader*, and does not offer any editing capabilities for PDF files. The whole point of PDF.js is to render PDF files as they are, hence changing e.g. the font size of text isn't something that we support (or intend to support either).
Closing as answered, since this is out of scope.

**Comment by huangche007** [comment]
Ok,Thanks a lot
