### ISSUE TITLE
Add Option to set serach panel by default

### ISSUE THREAD

**Issue by basti12203** [mozilla/pdf.js#8549]
Hello,

is there a way to set the search panel shows by default?
Similar to pdfjs.sidebarViewOnLoad?

Best Regards

**Comment by Snuffleupagus** [comment]
> is there a way to set the search panel shows by default?

No, there's no way of doing what you ask by default (you'd have to implement opening of the PDF.js findbar when the viewer loads yourself).

Since the Firefox versions of PDF.js uses the native browser findbar, which we don't want to trigger programmatically, I don't think that implementing such a preference would be a good idea since it would *not* behave consistently in the various PDF.js build targets.

Closing as answered.
