### ISSUE TITLE
how to use password in the iframe?

### ISSUE THREAD

**Issue by minipoint** [mozilla/pdf.js#8631]
<iframe src="viewer.html?file=../../files/456.pdf" password='123456'  style =\"width:100%;height:100%;"> </iframe>

i want to set password in the iframe, but it is not work. how can i do it?

**Comment by yurydelendik** [comment]
There is no way to provide password via iframe attribute. But you may modify viewer to sniff [frameElement](https://developer.mozilla.org/en-US/docs/Web/API/Window/frameElement). There is nothing we can do on our side, since it inherently unsafe to provide password in clear text (why not just remove that from PDF?). Closing as answered.
