### ISSUE TITLE
Text layers using different fonts than text rendered on canvas

### ISSUE THREAD

**Issue by wojtekmaj** [mozilla/pdf.js#8659]
Link to PDF file (or attach file here): default

Configuration:
- Web browser and its version: any
- Operating system and its version: any
- PDF.js version: any
- Is an extension: no

Steps to reproduce the problem:
1. Adjust textLayers CSS so that you could see rendered text in red.
2. Observe.

What is the expected behavior? (add screenshot)

This is how it looks when I change textLayers styles so that they use the same font as the text rendered on cancas. I'd make a pull request, but apparently, PDF.js removed the fonts after a while after using them and while it's all beautiful for a minute or so, that results in a much bigger mess later.

![image](https://user-images.githubusercontent.com/5426427/28254646-d01953e8-6aae-11e7-8c46-847b93690588.png)

What went wrong? (add screenshot)

![image](https://user-images.githubusercontent.com/5426427/28254638-b9a654a8-6aae-11e7-9084-f32878115ff6.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): default

**Comment by yurydelendik** [comment]
It is not original idea and not easily implementable in the PDF context for multiple reasons:

- Glyph can represent ligature e.g. 'ﬁ' glyph represent 'f' and 'i' and the latter might be absent in the font -- PDF scope has to distinct algorithms to display and extract text
- Type 3 or invisible font for scanned images does/may not have the same font
- PDF glyph positioning so granular so exact positioning will need inefficient DOM layer creation

I'll close it as won't fix because it looks like not well thought out idea (see also https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md)
