### ISSUE TITLE
Non-embedded "Cursivestandard" font not rendered correctly

### ISSUE THREAD

**Issue by OlivierAltinae** [mozilla/pdf.js#8667]
Link to PDF file (or attach file here):

[Cursive.pdf](https://github.com/mozilla/pdf.js/files/1158463/Cursive.pdf)

Configuration:
- Web browser and its version: FireFox 54.0.1 (32 bits)
- Operating system and its version: Windows 10
- PDF.js version: 1.8.557

Steps to reproduce the problem:
    Download this document: [Cursive.pdf](https://github.com/mozilla/pdf.js/files/1158464/Cursive.pdf)
    Load up in the viewer here: https://mozilla.github.io/pdf.js/web/viewer.html

What is the expected behavior?
The text should appear with the embeded cursive font.

![image](https://user-images.githubusercontent.com/26435963/28357174-d801bc9a-6c6a-11e7-90cc-bc658723dc98.png)

What went wrong?
Standard non-serif font is used instead.

![image](https://user-images.githubusercontent.com/26435963/28357138-b9fa7354-6c6a-11e7-9f81-7591105897a3.png)

This issue is not present in Chrome or IE.

**Comment by Snuffleupagus** [comment]
> The text should appear with the embedded cursive font.

Unfortunately the claim that the attached PDF file contains embedded fonts is *incorrect*, since there are no font files anywhere to be found in the PDF file.
In this case, the PDF file uses a non-embedded (and non-standard) font called "Cursivestandard", which even Adobe Reader cannot render correctly on my system (since I haven't got that font installed):

![non-embedded-font](https://user-images.githubusercontent.com/2692120/28362370-7c4c2a4a-6c7c-11e7-86f8-8835ed157eea.png)

**Comment by Thj007** [comment]
Are you solve your issue?

**Comment by OlivierAltinae** [comment]
Yes. The issue was on my side. The fonts were not included properly.

Thanks.

2018-01-30 2:13 GMT+01:00 Thj007 <notifications@github.com>:

**Comment by timvandermeij** [comment]
Closing since there is nothing more we can do on the PDF.js side.
