### ISSUE TITLE
Cannot read property 'firstElementChild' of null

### ISSUE THREAD

**Issue by vikramTungsten** [mozilla/pdf.js#8703]
am trying to embedded pdf on my html page using pdf.js, with the help of pdf viewer blog,I have included pdf.js and pdf.worker.js in my html file, but when I open the page, nothing is embedded and I am getting below error.
Cannot read property firstElementChild of null

Please help me in this.
Thanks!

HTML Code:

<body>  
<div class="pdfjs">
</div> 
<script src="{% static 'pdf.js-viewer/pdf.js'%}"></script>
<script src="{% static 'pdf.js-viewer/pdf.worker.js'%}"></script> 

<script type="text/javascript">
      PDFJS.webViewerLoad('http://url/mypdf.pdf');
</script>
</body>

Checkout below error:

Uncaught (in promise) TypeError: Cannot read property 'firstElementChild' of null at Object.PDFViewer (http://url/pdf.js:17939:52) at http://url/pdf.js:12985:21 at Object._initializeViewerComponents (http://url/pdf.js:12973:10) at http://url/pdf.js:12884:16PDFViewer

**Comment by Snuffleupagus** [comment]
> PDFJS.webViewerLoad('http://url/mypdf.pdf');

The PDF.js library does *not* expose `webViewerLoad` on the `PDFJS` object, that's apparently a feature of https://github.com/legalthings/pdf.js-viewer which is a *different* repo.
Closing as invalid, since this isn't directly a PDF.js issue; and based on https://github.com/legalthings/pdf.js-viewer/issues/23 you've already opened with the correct repo.
