### ISSUE TITLE
Recent changes?

### ISSUE THREAD

**Issue by gnosisgithub** [mozilla/pdf.js#8708]
FF 52.2.1
Windows 10
Using this http://omeka.org/add-ons/plugins/pdf-embed/ 
https://github.com/zerocrates/PdfEmbed#readme
which uses your library

Suddenly I hate to turn off, because PDFs were not rendering on the site. We have a complicated setup, where PDFs are behind a firewall and proxy tunnels in via htaccess. 

Where there any changes that would suddenly not allow for this type of setup?

**Comment by yurydelendik** [comment]
The referred library(es) use really old version of PDF.js. We have no control over third-party solutions and libraries. I recommend contact them directly with the problem.

@gnosisgithub you can update your site with [demo viewer](http://mozilla.github.io/pdf.js/getting_started/) -- we are trying to keep it up-todate.

> Where there any changes that would suddenly not allow for this type of setup?

Hard to tell since you did not provided link and details to your deployment. Closing as incomplete.

**Comment by gnosisgithub** [comment]
Thank you.

**Comment by gnosisgithub** [comment]
What are the server dependencies, if any, that allow PDF.js to run?
--

**Comment by yurydelendik** [comment]
> What are the server dependencies, if any, that allow PDF.js to run?

There are none (except regular HTTP server, e.g. Apache)
