### ISSUE TITLE
Is it possible to export rendered HTML code with CSS from viewer?

### ISSUE THREAD

**Issue by s-a** [mozilla/pdf.js#8732]

**Comment by yurydelendik** [comment]
No, it isn't. Closing as answered.

**Comment by s-a** [comment]
Thank you for your quick response. Can we transform this into a feature request? 😃

**Comment by yurydelendik** [comment]
> Can we transform this into a feature request?

@s-a please read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md -- transforming into feature request will not get it to be assigned or fix the issue. If you have a pretty good idea how to do it yourself, are you welcome to submit a pull request.

**Comment by Snuffleupagus** [comment]
Also, please keep in mind that by default PDF.js does *not* generate any HTML/CSS to be exported in the first place, since the PDF file is rendered on `<canvas>` elements.

There's an *experimental* SVG backend that could be used to generate HTML output, but note it's currently missing a number of features available in the default canvas back-end.
Please see https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js, and in particular the examples in https://github.com/mozilla/pdf.js/tree/master/examples/node for more information.
