### ISSUE TITLE
Download pdf file with rotation page 

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8765]
I rotated some pages and downloaded that file but pages didnot rotate in downloaded file .
Is it possible in pdf.js viewer ?

**Comment by Snuffleupagus** [comment]
As mentioned in both the README and the FAQ, PDF.js is only a *viewer* and does not contain any functionality for creating/editing PDF files.
Hence the save functionality present in the default viewer will allow you to save a PDF file *exactly* as-is, since doing what you ask would require editing the PDF file itself.

Closing as invalid.

**Comment by SOftEngrAtta** [comment]
Please guide me what can i do in this situation ? i want to do this in my project
