### ISSUE TITLE
Chrome: Only secure origins are allowed

### ISSUE THREAD

**Issue by everCyan** [mozilla/pdf.js#8767]
Hello, I put the pdfjs project on my server, not localhost. Then I open the address by chrome, the console.log show this error:
```
Uncaught (in promise) Error: Only secure origins are allowed (see: https://goo.gl/Y0ZkNV).
  Instantiating http://(***my server***)/pdfjs/web/genericcom.js
  Loading pdfjs-web/genericcom
```
Then I use safari, everything works well.
I know it's the chrome secure origins, like this:
```
“Secure origins” are origins that match at least one of the following (scheme, host, port) patterns: 
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
(chrome-extension, *, —) 
```

But how can I resolve this? My server doesn't support https.
Thank You.

**Comment by timvandermeij** [comment]
This is a limitation that Chrome puts on service workers. There is not much you can do about it other than supporting HTTPS it seems (see https://github.com/phonegap/phonegap-plugin-push/issues/1235 or https://stackoverflow.com/questions/41373166/why-am-i-seeing-error-only-secure-origins-are-allowed-for-my-service-worker). PDF.js itself should work just fine on HTTP sites if the browser let's us.

Note that more and more limitations are put on non-encrypted sites nowadays. It's really recommended to support HTTPS. With services like Let's Encrypt, the certificate is free.

Closing since there is nothing we can really do about this in PDF.js itself.
