### ISSUE TITLE
Cordova Windows App

### ISSUE THREAD

**Issue by jabelcs** [mozilla/pdf.js#8770]
Hello all.

First of all congratulations for this great work.

I have to say that what I'm describing IS NOT A PDF.JS PROBLEM but I need to now if someone can help me because I'm really stuck here.

I developed a cordova based app for iOS, Android and Windows that uses pdf.js as a pdf viewer.
The app worked well, and still works in iOS and Android, but in Windows it stopped working correctly since windows updated to version 1703.

When a user installs the app it downloads pdf files from my server to the windows app folder.

Now when I open a pdf document on windows app I get this error "Unexpected server response (0) while retrieving PDF "ms-appdata:///local/pdf/cates_43.pdf"."

I think this may be a cross origin problem because if I use a file inside the compilation (ex. /images/example.pdf) it works correctly.

Does anyone nows if this is realy a CORS problem and how to solve it?

Thanks in advance.

**Comment by timvandermeij** [comment]
It most definitely looks like a CORS problem, especially since you described that it does work when you put it inside the build. Make sure you have proper CORS headers set. We're not experts on Windows, but perhaps https://stackoverflow.com/questions/37134754/not-able-to-make-ajax-call-from-a-web-view-in-windows-10-cordova-app helps? We have a FAQ about CORS as well because the question comes up regularly, so this may help too: https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request.

If there are still issues after checking these resources, feel free to join us on #pdf.js on irc.mozilla.org since it may be easier to help out there and because we like to keep the issue tracker only for PDF.js bugs/features. Thank you!

**Comment by yurydelendik** [comment]
> I get this error "Unexpected server response (0) while retrieving PDF "ms-appdata:///local/pdf/cates_43.pdf"."

@jabelcs there is a chance that cordova app cannot load from "ms-appdata:" using XHR. You need to provide real URL (e.g. http) or load PDF using cordova API and give the Uint8Array to the getDocument.

**Comment by jabelcs** [comment]
@yurydelendik Thanks for taking the time to review this issue.

Could you please pointe me in the right direction to acomplish "load PDF using cordova API and give the Uint8Array to the getDocument"?

Thank you.

**Comment by AlfonsoBM** [comment]
Same problem here. Updating Windows solved the issue (Windows 10 ver. 1709 & 1803 tested and app working)
