### ISSUE TITLE
Relative links to pdfs not working with hosted pdf.js and demo viewer

### ISSUE THREAD

**Issue by jmiklaucich** [mozilla/pdf.js#8771]
Links to PDF files:
Annotation Links:
- [From #6616](https://github.com/mozilla/pdf.js/files/36341/Untitled.pdf)

Document Outline Item Links:
- [Relative pdf link bookmark.pdf](https://github.com/mozilla/pdf.js/files/1217812/Relative.pdf.link.bookmark.pdf)

Configuration:
- Web browser and its version: Chrome 60.0.3112.90 / Firefox 54.0.1 / Edge 40.15063.0.0
- Operating system and its version: Windows 10 version 1703 (10.0.15063)
- PDF.js version: v1.8.188 (Issue also occurs with earlier versions)

Relative links to other pdfs (both document outline items and link annotations in the document) do not work when the pdf.js project (with the demo viewer) is hosted on a local or non-local server. The href attribute of the anchor tags for the relative links are empty when inspect element is used on them.

Using console.log, the value of docBaseUrl just before an absolute URL is created for links (obj.js line 760) can be found to be null and params.docBaseUrl which it is assigned from is undefined. I believe this is the issue as the value for url here also contains the relative part of the link and createValidAbsoluteUrl requires docBaseUrl for relative links.

I set up a local server both per https://github.com/mozilla/pdf.js#getting-the-code and using the online demo files with a different command line http server but both had the same issue.

https://github.com/mozilla/pdf.js/blob/21cc2c020026341586024fb6a9d41602bddc3ed5/src/core/obj.js#L760

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that using relative links in PDF files are a *really* bad idea, since that means that the files are not as portable as they ought to be.

In an attempt to try and work-around the problems with relative links, PR #7689 gave API consumers the ability to provide a base URL against which relative links are resolved.
In order for this to work in custom deployments[1], the `PDFJS.getDocument` call *must* include the `docBaseUrl` parameter specifying a valid *absolute* URL; please refer to the documentation in: https://github.com/mozilla/pdf.js/blob/21cc2c020026341586024fb6a9d41602bddc3ed5/src/display/api.js#L119-L121

Closing as answered.

---
[1] Since no *absolute* URL is available when using the default viewer locally (with `gulp server`), that explains why it's not available there either.

**Comment by jmiklaucich** [comment]
Thank you for the caution but that be a problem for my use.

Ah thank you very much for explaining that, sounds perfect.
