### ISSUE TITLE
The PDF view does not show the contents of the file remaining normal

### ISSUE THREAD

**Issue by jimmyYSY** [mozilla/pdf.js#8806]
I have been supervised by nginx server, and use angularjs, and to modify the file address, but all went well, only when you enter a page cannot use, source throw an error, but don't know where is the problem, hope to help solve, thank you

![qq 20170822160432](https://user-images.githubusercontent.com/22142720/29554944-977d4f5a-8753-11e7-8d35-765f4bbdefb4.png)
![qq 20170822160442](https://user-images.githubusercontent.com/22142720/29554962-a3de54a6-8753-11e7-9901-1805462cafee.png)

**Comment by yurydelendik** [comment]
Demo viewer depends on how `window.location.hash` is used. You have to review viewer.js code and remove all uses of it (e.g. from https://github.com/mozilla/pdf.js/blob/master/web/pdf_history.js). If you don't want to modify the code, use viewer in a iframe as is. Closing as answered.

**Comment by Snuffleupagus** [comment]
> Demo viewer depends on how window.location.hash is used. You have to review viewer.js code and remove all uses of it (e.g. from https://github.com/mozilla/pdf.js/blob/master/web/pdf_history.js).

Besides the above, the errors shown in the screen-shots are *not* actually breaking ones, but are rather printed only for informational purposes.
This can be easily tested by opening e.g. http://www.nada.kth.se/kurser/kth/2D1339/linser2005.pdf#qwerty in Firefox, and noticing that the PDF document renders just fine even with such a console error.

Hence I'd guess that the actual problem lies elsewhere, but since this appears to be a custom deployment of PDF.js it's impossible to say what that problem could be given the limited information provided in the OP.
