### ISSUE TITLE
Replace occurrences of `throw new Error(...)` with `unreachable(...)` where applicable

### ISSUE THREAD

**Issue by timvandermeij** [mozilla/pdf.js#8846]
Especially in abstract methods, we would like to use `unreachable(...)` because it's a more explicit way to indicate that a fail state of the application is reached. Let's ensure that all abstract methods use `unreachable(...)` instead of throwing an error.

Note: we use `unreachable(...)` only for code paths that cannot happen by design (such as directly calling an abstract method). Errors in parsing can happen if the PDF is corrupted for example, so since that is dependent on the input, we throw a regular error there.

**Comment by DomHoney** [comment]
I'll work on this over the next couple weeks

**Comment by Fatehsandhu** [comment]
I'm a student at Seneca college learning open source, and I was hoping to work on this bug for my course.  If no one else is currently working on it, I'd like to give it a try.

**Comment by timvandermeij** [comment]
@DomHoney Are you still working on this? If not, cn @Fatehsandhu take over the work?

**Comment by Fatehsandhu** [comment]
@timvandermeij once again thanks a lot for this! I would love to try and contribute to this.

**Comment by DomHoney** [comment]
I was, but didn't make any real progress - I'm happy to let @Fatehsandhu take over.

**Comment by AK-007** [comment]
Is anyone working on it?

**Comment by Snuffleupagus** [comment]
Since a number of people have expressed interest of working on this, but no patch has yet been provided, let's try the following approach to 
If someone states that they intend to work on this issue, but doesn't provide a patch (or any sort of update) within *one* week, it's safe to assume that it's safe to

**Comment by Snuffleupagus** [comment]
Since a number of people have expressed interest in working on this, but no patch has yet been provided, let's try the following approach to make some headway here:
If someone leaves a comment stating that they intend to work on this issue, but doesn't provide a patch (nor any kind of update) within *one* week, then this issue will be considered available for another contributor.

**Comment by nveenjain** [comment]
Can i work on this if this issue is still available?
