### ISSUE TITLE
Unable to print document after scrolling through more than 10 pages.

### ISSUE THREAD

**Issue by mullery** [mozilla/pdf.js#8858]
Link to PDF file (or attach file here):

Configuration:
- Web browser and its version: Chrome Version 60.0.3112.113 (Official Build) (64-bit)
- Operating system and its version: Windows 10
- PDF.js version: 1.9.506
- Is an extension: No

Steps to reproduce the problem:
1. Open the demo viewer at https://mozilla.github.io/pdf.js/web/viewer.html.
2. Make sure you are viewing the first page in the document.
3. Scroll to the bottom of the document (page 14), one page at a time.
4. Click the print toolbar button to print the document.

What is the expected behavior? (add screenshot)

The document should print properly.

What went wrong? (add screenshot)

The document doesn't print and an exception is thrown:

![image](https://user-images.githubusercontent.com/11668760/29941939-2ce1f0c2-8e62-11e7-9ec8-df7ddb0236ea.png)

Running through the javascript debugger, I can see the viewer is destroying PDFPageView objects as they fall outside the 10-page window of pages loaded into page view buffer. When a PDFPageView object is destroyed, the PDFPage object attached to it is cleaned-up and nullified. The printing exception is the result of attempting to access the viewport from one of these destroyed PDFPageView objects.

**Comment by Snuffleupagus** [comment]
Removing the following line fixes this, so it's unfortunately a fairly serious (printing) regression from PR #8746.
https://github.com/mozilla/pdf.js/blob/51be27853f1d9d65333edce32f971cba56d64442/web/pdf_page_view.js#L114
Rather that just removing that, which I assume may be bad considering what the PR intended to fix, I quickly looked if it'd be possible to make https://github.com/mozilla/pdf.js/blob/51be27853f1d9d65333edce32f971cba56d64442/web/pdf_viewer.js#L931-L935
asynchronous since then we could use https://github.com/mozilla/pdf.js/blob/51be27853f1d9d65333edce32f971cba56d64442/web/pdf_viewer.js#L823-L828 to re-fetch the deleted `pdfPage`s.

Currently however, the printService is initialized synchronously, so I'm not sure if we can easily transition it to be asynchronous.
@yurydelendik Since you wrote the patch in PR #8746, can you please help here?

**Comment by yurydelendik** [comment]
I miss read function code and it's looks like `destroy` is a bad name for it. For now, we can safely, I think, remove this line.

> Currently however, the printService is initialized synchronously, so I'm not sure if we can easily transition it to be asynchronous instead.

We cannot it is not possible due to beforeprint event nature.
