### ISSUE TITLE
Getting file not found error

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#8882]
**Configuration:**
Google Chrome and 59.0.3071.115
Windows 10

I have tried to open pdf in pdfjs but It doesn’t display correctly. I am getting “../web/cmaps/Adobe-Japan1-UCS2.bcmap” not found error. All other pdf loaded perfectly but only this one [736317.pdf](https://github.com/mozilla/pdf.js/files/1284623/736317.pdf) getting error.

**What is the expected behavior? (add screenshot)**
![image](https://user-images.githubusercontent.com/11785531/30163222-cbfed344-93f5-11e7-8a49-864096717203.png)

**What went wrong? (add screenshot)**
![image](https://user-images.githubusercontent.com/11785531/30163243-e29fbe24-93f5-11e7-8217-6d2e9e5d9220.png)

**Error In Console:**
![image](https://user-images.githubusercontent.com/11785531/30163368-533816b8-93f6-11e7-90fd-85c6064f9ecb.png)

**Comment by Snuffleupagus** [comment]
> I am getting “../web/cmaps/Adobe-Japan1-UCS2.bcmap” not found error.

That indicates that you have either not included the the CMap files in your project, or not set the path (i.e. `PDFJS.cMapUrl`) to them correctly; please refer to https://github.com/mozilla/pdf.js/blob/9b14f8ea2a512ddf13ca6797048eeda08df380a7/src/display/global.js#L104-L109

Closing as answered, since this is a configuration issue with a custom deployment of PDF.js rather than a bug.

**Comment by jigskpatel** [comment]
I have checked in Pdf.js file. The path is set correctly
PDFJS.cMapUrl = PDFJS.cMapUrl === undefined ? null : PDFJS.cMapUrl;

![image](https://user-images.githubusercontent.com/11785531/30436612-354bade2-998a-11e7-9e4f-644073fe354d.png)

The error is getting only for this pdf ([736317.pdf](https://github.com/mozilla/pdf.js/files/1303423/736317.pdf)).  Others pdf loaded correctly. So I don’t why this pdf is not load and other are loaded?

**Comment by igorlino** [comment]
I had the same problem, and the path is definitively correct, but its not the solution.
The reason it fails, in my case at least, is because the encoding requires additional cmap file, which its not located.
Why is it not located? its because the IIS does not understand the mimetype. Therefore you need to add the required mimetype, in this case, looking at the official demo  of the viewer, the type would be 
Content-Type: application/octet-stream

In my case, as im using IIS to serve the web application, then I need to add a web.config file to the root of the webapplication. The content of it was:

> <?xml version="1.0" encoding="UTF-8"?>
> <configuration>
>     <system.webServer>
>         <staticContent>
> 		  <clear/>
> 		  <clientCache cacheControlCustom="no-store" cacheControlMode="DisableCache" />
> 
> 		  <mimeMap fileExtension=".json" mimeType="application/json" />
> 		  <mimeMap fileExtension=".css" mimeType="text/css" />
> 		  <mimeMap fileExtension=".js" mimeType="application/x-javascript" />
> 		  <mimeMap fileExtension=".map" mimeType="text/plain" />
> 		  <mimeMap fileExtension=".html" mimeType="text/html" />
> 
> 		  <mimeMap fileExtension=".jpg" mimeType="image/jpeg" />
> 		  <mimeMap fileExtension=".png" mimeType="image/png" />
> 		  <mimeMap fileExtension=".gif" mimeType="image/gif" />
> 
> 		  <mimeMap fileExtension=".bcmap" mimeType="application/octet-stream" />
> 
>         </staticContent>
>     </system.webServer>
> </configuration>
>

**Comment by zleight1** [comment]
> I had the same problem, and the path is definitively correct, but its not the solution.
> The reason it fails, in my case at least, is because the encoding requires additional cmap file, which its not located.
> Why is it not located? its because the IIS does not understand the mimetype. Therefore you need to add the required mimetype, in this case, looking at the official demo of the viewer, the type would be
> Content-Type: application/octet-stream
> 
> In my case, as im using IIS to serve the web application, then I need to add a web.config file to the root of the webapplication. The content of it was:
> 
> > ```
> >     <mimeMap fileExtension=".json" mimeType="application/json" />
> >     <mimeMap fileExtension=".css" mimeType="text/css" />
> >     <mimeMap fileExtension=".js" mimeType="application/x-javascript" />
> >     <mimeMap fileExtension=".map" mimeType="text/plain" />
> >     <mimeMap fileExtension=".html" mimeType="text/html" />
> > 
> >     <mimeMap fileExtension=".jpg" mimeType="image/jpeg" />
> >     <mimeMap fileExtension=".png" mimeType="image/png" />
> >     <mimeMap fileExtension=".gif" mimeType="image/gif" />
> > 
> >     <mimeMap fileExtension=".bcmap" mimeType="application/octet-stream" />
> > 
> >     </staticContent>
> > </system.webServer>
> > ```

I had the same issue, apparently IIS doesn't serve files unless it knows the MIME type by default. Thanks for the fix!
