### ISSUE TITLE
Some PDFs cannot render correctly when using gulp-protect

### ISSUE THREAD

**Issue by dangquang1020** [mozilla/pdf.js#8886]
Link to PDF file (or attach file here): 
[Stony Lonesome Group. Quarterly Newsletter. Q2 2017.pdf](https://github.com/mozilla/pdf.js/files/1287261/Stony.Lonesome.Group.Quarterly.Newsletter.Q2.2017.pdf)

Configuration:
- Web browser and its version:
  Chrome Version 61.0.3163.79 (Official Build) (64-bit)
  Firefox 55.0.2 (64-bit)
- Operating system and its version:
  Ubuntu 14.04 LTS

- PDF.js version: v1.9.426
- Is an extension:
  gulp-protect: [https://github.com/sjeedandi/gulp-protect](url)

What is the expected behavior? (add screenshot)
![expected](https://user-images.githubusercontent.com/12976768/30203914-f0849e7a-94ad-11e7-90e4-993f7d138fc8.png)

What went wrong? (add screenshot)
![unexpected](https://user-images.githubusercontent.com/12976768/30203970-1436316c-94ae-11e7-8002-807d2a51b033.png)

At localhost I build the project and the pdf file render correctly.
But when I build production mode (gulp-protect is enable) it print error to conlose logs:
`Chrome Version 61.0.3163.79 (Official Build) (64-bit)`
`Warning: Failed to load font "g_d2_f16": SyntaxError: Invalid font data in ArrayBuffer.`

`Firefox 55.0.2 (64-bit)`
`downloadable font: cmap: Range glyph reference too high (57344 > 39) (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...`
`downloadable font: rejected by sanitizer (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...`
`downloadable font: font load failed (font-family: "g_d0_f1" style:normal weight:normal stretch:normal src index:0) source: data:font/opentype;base64 ...`

It seems some fonts has corrupted.

**Comment by Snuffleupagus** [comment]
> At localhost I build the project and the pdf file render correctly.
> But when I build production mode (gulp-protect is enable) it print error to conlose logs:

Given that it, by your own account, works when using PDF.js as is it thus seem to be an issue with `gulp-protect` rather than with PDF.js itself.
Hence I'd suggest reporting the issue directly to the `gulp-protect` project, since this appears to be out of scope as far as PDF.js is concerned. And we cannot really provide support for *other* projects.
(Also, for future reference, for issues regarding custom implementation of PDF.js you'll need to provide a complete example when opening an issue; please see [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).)

Closing as out-of-scope.
