### ISSUE TITLE
Images not rendered / Unsupported predictors 132 & 255

### ISSUE THREAD

**Issue by omicron81** [mozilla/pdf.js#8895]
Link to PDF file (or attach file here):
http://www-eu.apache.org/dist/lucene/solr/ref-guide/apache-solr-ref-guide-6.6.pdf

Configuration:
- Web browser and its version: Firefox 55.0.3
- Operating system and its version: Windows 7
- PDF.js version: 1.8.439
- Is an extension: No

Steps to reproduce the problem:
1. Open linked PDF file
2. Scroll down to page 11 (16)

What is the expected behavior? (add screenshot)
Images are rendered:
![grafik](https://user-images.githubusercontent.com/8233992/30279242-f94b4a3e-970c-11e7-91c2-c4c5792b31b2.png)
![grafik](https://user-images.githubusercontent.com/8233992/30279048-647b6b78-970c-11e7-816c-0b61fad6e7b9.png)

What went wrong? (add screenshot)
Images are not rendered:
![grafik](https://user-images.githubusercontent.com/8233992/30279258-07ae3b9a-970d-11e7-9444-9153c075340f.png)
![grafik](https://user-images.githubusercontent.com/8233992/30279111-8ff8c570-970c-11e7-8415-9273881592ed.png)

Error console:
```
PDF ad557cf1f10fc51f55a5f8fdb17f6669 [1.4 Written by the Apache Lucene/Solr Project / Asciidoctor PDF 1.5.0.alpha.15, based on Prawn 2.2.2] (PDF.js: 1.8.439)  viewer.js:1503:7
Error: Unsupported predictor: 255  pdf.worker.js:352:5
predictorStreamReadBlockPng@resource://pdf.js/build/pdf.worker.js:2322:10
DecodeStream_getBytes@resource://pdf.js/build/pdf.worker.js:1830:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:33012:14
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:32948:18
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:16907:23
  pdf.worker.js:353:5
Warning: Unable to decode image: Error: Unsupported predictor: 255  pdf.worker.js:344:5
Warning: Dependent image isn't ready yet  pdf.js:344:5
Error: Unsupported predictor: 255  pdf.worker.js:352:5
predictorStreamReadBlockPng@resource://pdf.js/build/pdf.worker.js:2322:10
DecodeStream_getBytes@resource://pdf.js/build/pdf.worker.js:1830:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:33012:14
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:32948:18
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:16907:23
  pdf.worker.js:353:5
Warning: Unable to decode image: Error: Unsupported predictor: 255  pdf.worker.js:344:5
Warning: Dependent image isn't ready yet  pdf.js:344:5
Error: Unsupported predictor: 132  pdf.worker.js:352:5
predictorStreamReadBlockPng@resource://pdf.js/build/pdf.worker.js:2322:10
DecodeStream_getBytes@resource://pdf.js/build/pdf.worker.js:1830:11
PDFImage_getImageBytes@resource://pdf.js/build/pdf.worker.js:33012:14
PDFImage_createImageData@resource://pdf.js/build/pdf.worker.js:32948:18
PartialEvaluator_buildPaintImageXObject/<@resource://pdf.js/build/pdf.worker.js:16907:23
  pdf.worker.js:353:5
Warning: Unable to decode image: Error: Unsupported predictor: 132  pdf.worker.js:344:5
Warning: Dependent image isn't ready yet  pdf.js:344:5
```

**Comment by THausherr** [comment]
Apache PDFBox has the same problem and here's my 2ct on this:

When I removed the predictor (overwrite "/Predictor 15" with blanks) from the PDF then it was rendered properly.

The PDF specification has this about /DecodeParms :

> A parameter dictionary or an array of such dictionaries, used by the filters specified by Filter. If there is only one filter and that filter has parameters, DecodeParms shall be set to the filter’s parameter dictionary unless all the filter’s parameters have their default values, in which case the DecodeParms entry may be omitted. If there are multiple filters and any of the filters has parameters set to nondefault values, DecodeParms shall be an array with one entry for each filter: either the parameter dictionary for that filter, or the null object if that filter has no parameters (or if all of its parameters have their default values). If none of the filters have parameters, or if all their parameters have default values, the DecodeParms entry may be omitted.

Currently PDFBox takes "whatever is there" from the DecodeParms array / dictionary.

So now I tried to implement the specification literally in PDFBox ("If there is only one filter and that filter has parameters, DecodeParms shall be set to the filter’s parameter dictionary") and that failed, there are files that have a filter array with 1 element and have a /DecodeParms array with 1 element and these render properly with Adobe Reader, but no longer in PDFBox. So that "incorrect" DecodeParms array element must be used or it will look bad. The PDF specification should read "If there is only one filter as a name object and..."

Then I tried to implement that a dictionary would be expected when the filter was only a name, and that worked, i.e. no regressions, and the SOLR file renders too.

in parser.js you have this today:
```
      if (isName(filter)) {
        if (Array.isArray(params)) {
          params = this.xref.fetchIfRef(params[0]);
        }
        return this.makeFilter(stream, filter.name, length, params); 
      }
```
In an older version that I saved years ago the code was like this:
```
      if (isName(filter)) {
        return this.makeFilter(stream, filter.name, length, params);
      }
```
This logic was changed in commit c8f83d6 but I could not find a PR nor did I understand whether it solved a problem with a specific file.

Btw the very first page of the PDF has the same issue.

**Comment by timvandermeij** [comment]
Fixed by the pull request above.

@THausherr Thank you for providing your analysis!
