### ISSUE TITLE
"PDFLinkService_navigateTo: "null" is not a valid destination array."

### ISSUE THREAD

**Issue by hukuiabc** [mozilla/pdf.js#8911]
- PDF.js version:  node  "pdfjs-dist": "^1.9.432",
`import PDFViewer from 'pdfjs-dist/web/pdf_viewer.js';`

Steps to reproduce the problem:
1. I change the hash route by  click back button of browser or custom button in vuejs 
    eg.
    From  http://localhost:8080/#/pdf back  to  http://localhost:8080/#/home
   ps: Sorry the demo is in my local.
2. Show the error : "PDFLinkService_navigateTo: "null" is not a valid destination array."

What went wrong? (add screenshot)
![image](https://user-images.githubusercontent.com/20129167/30464194-aed0c22e-9a02-11e7-837a-0f321cefe090.png)

I used viewer from the  mobile-viewer example's code 
[https://github.com/mozilla/pdf.js/blob/master/examples/mobile-viewer/viewer.js](url)

**Comment by Snuffleupagus** [comment]
> I change the hash route by click back button of browser or custom button in vuejs
> From http://localhost:8080/#/pdf back to http://localhost:8080/#/home

The viewer components, which are the building blocks of the default viewer, were created to be generally usable in browsers rather than specific JS frameworks. Thus it's certainly possible that way that a particular JS framework modifies the hash isn't entirely compatible with PDF.js (but see below as well).

> ps: Sorry the demo is in my local.

Please keep in mind that issues regarding custom implementation of PDF.js must, as requested in both https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md, be accompanied with a working example.

> Show the error : "PDFLinkService_navigateTo: "null" is not a valid destination array."

That is actually not a breaking error, but rather just a warning, hence it can be safely ignored.

> I used viewer from the mobile-viewer example's code
> https://github.com/mozilla/pdf.js/blob/master/examples/mobile-viewer/viewer.js

Note that that code contains no event handler which listens for `hashchange` events, so I'm not entirely sure how an `hashchange` event even reaches `PDFLinkService.navigateTo` in the first place (and given the lack of an example, it's difficult to tell).

Closing, since the above shouldn't prevent PDF.js from working, and we simply cannot support specific functionality of various JS frameworks.
