### ISSUE TITLE
Pdf.JS should not load any blob URLs detected if type is not PDF

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8914]
Would be nice to have this behavior

i read in a StackOverflow post that you can disable PDFJS worker. i tried that but it did not work. PDFJS will still load the document blob even if it is not PDF.

**Comment by Snuffleupagus** [comment]
> Would be nice to have this behavior

*Slightly off-topic, but:* Generally speaking a sentence such as the one above doesn't provide any motivation for, nor any real explanation as to *why*, you think something should be implemented/changed.

In this case though, ignoring `Blob`s with a non-PDF `type` would mean that if the `Blob` was incorrectly created it would (completely unnecessarily) fail to open.
Not to mention that it would require adding a bunch of specialized validation code for what seems very much like an edge-case, considering that `InvalidPDFException` will already be thrown if you attempt to open a non-PDF file with PDF.js.

> i read in a StackOverflow post that you can disable PDFJS worker. i tried that but it did not work.

I'm not entirely sure how this comment is relevant for the current discussion, but please keep in mind that disabling the worker will cause worse performance and is thus very much advised against.

Closing as invalid, since I don't see why we need to change this behaviour in the PDF.js repo.
