### ISSUE TITLE
Is it possible to have another input file chooser that will not trigger PDF.JS loading it as PDF?

### ISSUE THREAD

**Issue by chitgoks** [mozilla/pdf.js#8915]
PDF.JS has a file chooser icon to load another PDF without refreshing the site

i have a different file chooser that does something else, but whenever the file gets selected, PDF.JS will load that file

is there a way to override this?

**Comment by Snuffleupagus** [comment]
The solution would be quite simple: Have the PDF.js default viewer ignoring 'change' events that originated "outside" of the viewer; e.g. something like this: https://github.com/mozilla/pdf.js/compare/master...Snuffleupagus:issue-8915.

However, this use-case seems very much limited to a custom implementation of the default viewer, and as such I'm not sure if we actually want to fix the issue in the PDF.js repo (which is why I'm not submitting a PR).
/cc @timvandermeij, @yurydelendik Do you think it makes sense to change this in the default viewer?

**Comment by timvandermeij** [comment]
It's a small change and if that makes viewer integration easier (more self-container viewer), I'm personally not opposed to it.

**Comment by chitgoks** [comment]
thats great

because there is no way to add it in the first of event listeners listening to the change event

so the only workaround would be to edit every new version of viewer.js to ignore change events not coming from the viewer

thanks

**Comment by timvandermeij** [comment]
Fixed by the pull request above.

**Comment by chitgoks** [comment]
hi tim. im not familiar much yet with these pull stuff. do i wait for the next version of pdf.js after v1,8,188?

**Comment by timvandermeij** [comment]
You can either do that, or use https://github.com/mozilla/pdfjs-dist which is updated after each push.
