### ISSUE TITLE
PDF Load Properly 

### ISSUE THREAD

**Issue by SOftEngrAtta** [mozilla/pdf.js#8918]
i am getting issue , when i open pdf file on pdfviewer.js and scroll pages move from frist page to last page so on that time pdfviewer was loading pages . why pdfviewer doing this ugly behavior ?

**Comment by timvandermeij** [comment]
It's really not clear what behavior you mean exactly. First of all, always fill in the entire issue template that is provided so we know what your configuration is (PDF.js version, browser, et cetera). If it is a problem with a particular PDF file, please provide it. Does it happen with a custom deployment or the default viewer at https://mozilla.github.io/pdf.js/web/viewer.html?

In short, there is not much we can do right now. What could help is providing a screen capture of the behavior to visualize it for us. Closing as incomplete for now.

**Comment by SOftEngrAtta** [comment]
you open this url https://mozilla.github.io/pdf.js/web/viewer.html , and
move your browser sidebar from bottom to top rapidly then you will notice
loading bar will appear and page will display after some seconds , so i
want to show page rapidly and loading bar will not appear when you
scrolling or moving your pages

**Comment by timvandermeij** [comment]
I think this is because the viewer has a page cache (see https://github.com/mozilla/pdf.js/blob/master/web/pdf_viewer.js#L36). If you scroll quickly, some already rendered pages may be removed from the cache because they are out of view. You can try adjusting this constant or searching for "cache" in that file to disable it for your custom solution. Note that caching pages makes rendering faster, but the downside is more memory usage, so a trade-off for the default viewer was made.

**Comment by SOftEngrAtta** [comment]
Ok ,  thanks for quick response
