### ISSUE TITLE
does not work with ftp files (1.8.557 latest version for Chrome)

### ISSUE THREAD

**Issue by yashamon** [mozilla/pdf.js#8926]
Link to PDF file (or attach file here): ftp://ftp.fernuni-hagen.de/pub/pdf/urz-broschueren/broschueren/a0279510.pdf
Configuration:
- Web browser and its version: Chrome 61.0.3163.91
- Operating system and its version: OSX 10.12.6
- PDF.js version: 1.8.557
- Is an extension: yes

Steps to reproduce the problem:
1. Go to ftp pdf like ftp://ftp.fernuni-hagen.de/pub/pdf/urz-broschueren/broschueren/a0279510.pdf2.
Get unexpected server error. 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by yashamon** [comment]
So I am guessing chrome users are kind of second class citizens in this case :(

**Comment by Snuffleupagus** [comment]
According to https://bugs.chromium.org/p/chromium/issues/detail?id=435547#c46, this appears to be an upstream issue in Google Chrome *itself* rather than in the PDF.js extension.

**Comment by Rob--W** [comment]
I'm going to disable ftp support for Chrome 59+ because of the upstream Chrome issue.

I can think of a work-around to enable FTP display anyway, but I am not sure if that is worth the effort. @yashamon Would it be an acceptable solution for you to be able to open ftp PDFs in Chrome (either with the built-in viewer, if any, or as a download + drag file to Chrome)?

The work-around that I am thinking of relies on the fact that Chrome only allows `ftp:`-requests from `ftp:`-URLs:
1. Find any tab with the `ftp:` scheme.
2. If not found, open a temporary (inactive) tab with a `ftp:` URL.
3. Let the extension run a content script in the tab (from 1 or 2), and let that script fetch the `ftp:`-resource.
4. Send back the response to the original tab and show the PDF.

Now, if there is an existing tab with a `ftp:`-URL, then this work-around would barely have any noticeable difference when compared with the pre-Chrome 59 method. But if there is not such a tab (which I fully expect), then opening a tab can be confusing. But that confusion might be worth it, if the alternative is to not have an easy way to display PDF files.

**Comment by timvandermeij** [comment]
Closing since #9595 is merged.

**Comment by Rob--W** [comment]
FYI: Upstream bug report to request access to ftp URLs: https://bugs.chromium.org/p/chromium/issues/detail?id=904455
