### ISSUE TITLE
Test files request

### ISSUE THREAD

**Issue by tiriana** [mozilla/pdf.js#8997]
No issue here, just a kind request - I'm trying to write unit tests for my piece of code using pdf.js, and I need pdf in which single page is corrupted - so that `getPage` throw error only for this particular page. I have pdf in which all pages are corrupted, but just cannot figure it out how to corrupt a single page. I tried editing some pdf and removing characters, but pdf.js handles this pretty well :)

I know this is more of a StackOverflow question, but I just wanted to ask at the very source.

Can you please provide me with such file?

**Comment by timvandermeij** [comment]
PDF.js indeed tries hard to recover corrupted content in files. The files in https://github.com/mozilla/pdf.js/tree/master/test/pdfs form our test suite that we use for regression testing. Everytime a corrupted PDF is encountered and its problem is fixed, we put a file/link there, so that won't help you since they're fixed. I think the best you can do is try to take a file from https://github.com/mozilla/pdf.js/issues?q=is%3Aopen+is%3Aissue+label%3A4-corrupted-pdf since they're unfixed (yet). Otherwise you'd have to edit the PDF stream yourself, but given that corruption is hard to trigger since we recover a lot, it's not sure how to do this exactly.
