### ISSUE TITLE
Any reason for not committing the lock file?

### ISSUE THREAD

**Issue by fgilio** [mozilla/pdf.js#9000]
Hi!
This is not a bug issue, just a question. Is there any special reason not to be using a lock file? I guess it'd be `package-lock.json`, since the instructions mention using `npm`.

**Comment by yurydelendik** [comment]
When we started the project there was no package-lock.json . Not sure if there is a value for this file since pdf.js, as is, will not be used as dependency.

Added by https://github.com/mozilla/pdf.js/pull/8977

/cc @timvandermeij

**Comment by Snuffleupagus** [comment]
> Not sure if there is a value for this file since pdf.js, as is, will not be used as dependency.

Completely agree (especially considering the size of the `package-lock.json` file).

**Comment by yurydelendik** [comment]
I have no preference at the moment. I interested in "install exactly the same dependencies", if this works as advertised, that may fix users' concern about different pdf.js/pdf.worker.js when generated on different computers.

**Comment by fgilio** [comment]
Well, as far as I understand, that was one of the main reasons why Facebook created [yarn](https://yarnpkg.com). Then `npm` also adopted the `lock` file.

**Comment by timvandermeij** [comment]
It's mainly due to the size and the fact that we didn't really need it before that I excluded it. We keep our `package.json` up-to-date pretty well in general and exact version pinning was not really necessary. What I also wanted to avoid is that people constantly commit this file since it appears it can change quite rapidly (i.e., if you try out a new dependency and remove it again), but maybe I'm wrong there. If you think it may prevent issues in the future, we can reconsider it, but I would like to know if there is actually added value.

**Comment by fgilio** [comment]
I'm seeing it's around 340kb, is that a problem?
I consider version pinning to be very important and would assume "install exactly the same dependencies" to be a very very attractive thing, even more considering it has no side effects.

> i.e., if you try out a new dependency and remove it again

In my experience it only actually changes when someone upgrades, adds or removes a dependency. But not in cases where you try something and later remove it. *I may be wrong.*

\* I also speeds up the initial `npm install`, but I guess that's just a nice to have.

---
I'm not really trying to convince you guys, I just found it really interesting that you didn't commit the file.

**Comment by timvandermeij** [comment]
Fixed by the pull request above.

**Comment by fgilio** [comment]
Nice!
