### ISSUE TITLE
PDF Renders Badly

### ISSUE THREAD

**Issue by psidhu** [mozilla/pdf.js#9017]
Attach (recommended) or Link to PDF file here: https://www.recom-power.com/pdf/Powerline-AC-DC/RAC05-K.pdf

Configuration:
- Web browser and its version: Firefox 56.0 (64-bit)
- Operating system and its version: Windows 10 with OS Build 15063.632
- PDF.js version: ?
- Is an extension: Built-in

Steps to reproduce the problem:
1. Open Page

What is the expected behavior? To properly render the first page. 
![image](https://user-images.githubusercontent.com/1151969/31415345-b1504022-add7-11e7-855b-8030a308f7a2.png)

What went wrong? Renders poorly.
![image](https://user-images.githubusercontent.com/1151969/31415363-d8842096-add7-11e7-818d-728c1102891b.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): ?

**Comment by janpe2** [comment]
[issue9017_reduced.pdf](https://github.com/mozilla/pdf.js/files/1412216/issue9017_reduced.pdf)

```
0 0 0 1 k
/GS2 gs
529.353 650.92 43.37 43.213 re
f
q
  529.353 650.92 43.37 43.37 re
  W n
  q
    568.938 673.022 m
    W n
    q
      0 g
      /GS0 gs
      0 37.3465474 37.3465474 -0 531.5914887 654.3490896 cm
      BX
      /Sh2 sh
      EX
    Q
  Q
Q
```

Shading `Sh2` should be invisible because it is clipped by a one-point clip path `568.938 673.022 m W n`. But instead the whole page is filled with the shading. I suspect there is a problem in the SMask implementation that causes the clip path to be lost. Line `/GS0 gs` calls [suspendSMaskGroup()](https://github.com/mozilla/pdf.js/blob/ad74f6e7410420dc6ae27edc863a2ef906d77b57/src/display/canvas.js#L984). It changes the current `ctx` object but doesn't copy the clip path from the old `ctx` to the new one. Other context properties are copied by `copyCtxState()` but not the clip path.

**Comment by amit777** [comment]
This PDF looks like it renders correctly in the below version:

```
const pdfjsVersion = '2.7.90';
const pdfjsBuild = '6728c8fa6';
```

**Comment by timvandermeij** [comment]
Closing since the original PDF is indeed fixed now.
