### ISSUE TITLE
Chrome and range requests

### ISSUE THREAD

**Issue by sporkman** [mozilla/pdf.js#9022]
Attach (reccomened) or Link to PDF file here:

http://resourcefurniture.com/wp-content/uploads/2016/06/CL-Oslo-301.pdf

Configuration:
- Web browser and its version: Chrome 61.0.3163.100
- Operating system and its version: OS-X 10.12.6
- PDF.js version: 1.8.888
- Is an extension:

Steps to reproduce the problem:
1. Load above file and watch for range requests
2. Repeat, clear cache, etc. and sometimes it stalls out with the spinning progress wheel.  Other times it does not.  When it errors out, Chrome logs an error.  Does not seem to happen w/Firefox or Safari.

What is the expected behavior? PDF loads

What went wrong? PDF sometimes does not load

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):  http://resourcefurniture.com/themencode-pdf-viewer/?file=http://resourcefurniture.com/wp-content/uploads/2016/06/CL-Oslo-301.pdf

Attached are a few screenshots of what happens when it goes wrong in Chrome. You can see a bunch of range requests.  If one fails, then everything seems to fall apart and no further requests are made.  The site is hosted on Flywheel.  My understanding is that they use Varnish and Nginx. The PDF.js viewer included by this WP plugin developer appears to be stock - really the only non-stock seems to be the WP admin portion of their plugin.

![rf-req1](https://user-images.githubusercontent.com/510750/31517436-e813da54-af69-11e7-99da-fc33acd94ec5.png)
![rf-req2-failed](https://user-images.githubusercontent.com/510750/31517438-e82507e8-af69-11e7-83fa-fcc53c0547ef.png)
![rf-req3](https://user-images.githubusercontent.com/510750/31517439-e83d4574-af69-11e7-9fe1-19eb2b28f21b.png)

**Comment by sporkman** [comment]
Also got someone to grab the more specific Chrome error.  Also confirmed that this is only happening when Varnish is enabled and also only with Chrome.  So Chrome bug, Varnish bug or PDF.js bug?  No idea, but is there something I can do as a workaround?
![rf-req-cache-err](https://user-images.githubusercontent.com/510750/31525532-e37b3e40-af8e-11e7-9108-0ae568f6ecef.png)

Error of note is net::ERR_CACHE_OPERATION_NOT_SUPPORTED

**Comment by yurydelendik** [comment]
Can you reproduce that on regular http server using same version of chrome using the same version of pdf.js demo viewer? What's varnish?

**Comment by yurydelendik** [comment]
If you setup (web server) can not handle http range requests properly, the workaround will be to disable that (in wp or elsewhere). You can also disable range requests in pdf.js

**Comment by carlowahlstedt** [comment]
I'm seeing the same on all front (minus whatever varnish is). Seemed to work better before I upgraded yesterday to v1.9.426. When it works I'm seeing 36 requests for the PDF file. When it failed, it was more like the above, 6ish requests and then a failed request and the file never completes download. I also seem to notice it when the MVC site is cold and IIS needs to warm up. Also looks like this [angular-pdfjs-viewer](https://github.com/sharelatex/angular-pdfjs-viewer) library is seeing a similar issue.

**Comment by sporkman** [comment]
Varnish is pretty much the most widely-used web cache in the world, FWIW. If you're on a site that runs some heavy PHP/Ruby/Python/whatever web app, this is probably sitting between you and the web server.   http://varnish-cache.org/intro/index.html#intro  And real "touchy" web client app like pdf.js should probably be testing against a host with Varnish in the chain.

**Comment by carlowahlstedt** [comment]
Agreed @sporkman. It seems to work very well in Firefox.

**Comment by amakhrov** [comment]
I have a similar issue when hosting pdf files directly from Amazon S3, without Varnish or any other proxy server in between.
So: Chrome, large pdf file (~500MB) hosted on S3.

When I first open the file it loads well as I would expect it to (the stream download in progress - http response 200; and a couple of range requests - http response 206).

Then I reload the page, while the stream request is still in progress.
Now I see a new stream request starting, which is ok, and 2 range requests in the pending state!

See screenshots below:
![screenshot 2017-10-27 17 20 11](https://user-images.githubusercontent.com/1004015/32129376-6000937c-bb3b-11e7-874e-36ff9ff24230.png)
![screenshot 2017-10-27 17 20 30](https://user-images.githubusercontent.com/1004015/32129377-62695a68-bb3b-11e7-96ca-8a73c5da179f.png)

**Comment by steve-ntl** [comment]
I also am having the same issues as @amakhrov. Hosting my PDFs in S3. Range requests work perfectly in Firefox, but Chrome will fail ~25% of the time after returning 206 on the first few range requests. These PDFs are 100+ pages.

Is there any way to catch these errors and retry the request? A try/catch around PDFJS.getDocument() always successfully returns on the first 200 even if the range request eventually fails.

**Comment by stevelikesmusic** [comment]
I also am having the same issues as @amakhrov. Hosting my PDFs in S3. Range requests work perfectly in Firefox, but Chrome will fail ~25% of the time after returning 206 on the first few range requests. These PDFs are 100+ pages.

Is there any way to catch these errors and retry the request? A try/catch around PDFJS.getDocument() always successfully returns on the first 200 even if the range request eventually fails.

**Comment by suconghou** [comment]
same problem here on Chrome , anybody who know how to solve  it ?

**Comment by stevelikesmusic** [comment]
For me, I needed to ensure Chrome didn't cache range requests. This meant setting my PDFs in S3 to have  a cache-control property of `Cache Control: max-age=0, no-cache, no-store, must-revalidate`.

Not the most ideal solution, but using range requests are essential for 200+ page PDFs. So disabling range requests wasn't an option.

As @yurydelendik mentioned in other issues, disabling streams and autoFetch helped a little. 
```
PDFJS.disableStream = true;
PDFJS.disableAutoFetch = true;
```
It was also a bit better only downloading chunks on demand rather than the whole 200+ page chunked out PDF (smaller PDFs worked fine with the default settings). Chrome failures went from ~25% of the time to ~10%. Since changing the cache-control settings, I've been getting 0 Chrome errors.

**Comment by Rob--W** [comment]
`net::ERR_CACHE_OPERATION_NOT_SUPPORTED` maybe related to https://crbug.com/770694 ? ("Multiple simultaneous requests to same URL with Range header cause failure ( block backend returns ERR_CACHE_OPERATION_NOT_SUPPORTED)" )

**Comment by loretoparisi** [comment]
Even if on  a different context (audio files streaming with Partial HTTP Content) I guess that this is the same error that I'm having [here](https://stackoverflow.com/questions/53226595/streaming-audio-in-node-js-with-content-range).

In my case a `Content-Range` header plug no caching headers it seems it is not enough to work in Crome.

While when streaming full file my headers were

```javascript
{ 'Content-Length': 4724126,
  'Content-Type': 'audio/mpeg',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
  'Access-Control-Allow-Headers': 'POST, GET, OPTIONS',
  Expires: 0,
  Pragma: 'no-cache',
  'Cache-Control': 'no-cache, no-store, must-revalidate' }
```

and it works, when streaming partial contents with HTTP 206 I had

```javascript
{ 'Content-Length': 4724126,
  'Content-Type': 'audio/mpeg',
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'POST, GET, OPTIONS',
  'Access-Control-Allow-Headers': 'POST, GET, OPTIONS',
  Expires: 0,
  Pragma: 'no-cache',
  'Cache-Control': 'no-cache, no-store, must-revalidate',
  'Accept-Ranges': 'bytes',
  'Content-Range': 'bytes 120515-240260/4724126' }
```

This led to an error of the Chrome page where the `<audio>` or `<video>` tag was.

<img width="356" alt="schermata 2018-11-12 alle 10 49 20" src="https://user-images.githubusercontent.com/163333/48339477-9ffdd580-e668-11e8-8688-50ad9fdea3d9.png">

**Comment by smellslikedonkey** [comment]
We're struggling with something similar and came across this bug... If you run these chrome requests through mitmproxy you'll probably find that there's a "range-if" header appended to the request (that doesn't show up in dev tools) which is causing the servers to return 200's instead of 206's. Hope this helps.

**Comment by rehmanmuradali** [comment]
Hey. This is how I am returning an mp4 video. When requesting this in firefox it works pretty well and seeking is working fine. But Google Chrome is not loading this video. Any updates ?

```  
return ResponseEntity.status(HttpStatus.PARTIAL_CONTENT)
                .contentType(MediaTypeFactory.getMediaType(video)
                        .orElse(MediaType.APPLICATION_OCTET_STREAM))
                .body(video);
```

**Comment by Snuffleupagus** [comment]
Given first of all the age of this issue, secondly the fact that it seems specific to a *particular* browser (i.e. Google Chrome), and finally that the latest comments seem completely unrelated to the PDFs; is it really meaningful to keep this issue open?

**Comment by Rob--W** [comment]
This issue may be still relevant, but it's a bug in Chrome if anything, with little reason for us to keep tracking it in PDF.js. So I'm fine with closing this.

**Comment by conorom** [comment]
Maintainers you can ignore this massive comment, it's for posterity for others struggling with Chromium browsers doing really excessive downloading of a single PDF file, when working through proxy servers. Not as uncommon a problem as you might think in the university library world.

Thanks to @smellslikedonkey for adding a comment above about `Range-If` headers that got me here (once I realized the problem was Chromium-only), and to @stevelikesmusic for adding the `Cache-Control` solution/workaround comment.

-----------------------------------------------------------------------------------------

Apologies if this annoys but I really want to comment on this issue for search engine purposes, though it be closed long ago. Adding some keywords etc. Cause landing here really helped me out! Hopefully this isn't too rude to do.

There are other range request caching tickets for pdf.js too, like #11622, and I agree that these all totally seem like browser/server/proxy issues and nothing to do with pdf.js bugs or development.

Chrome/Chromium is very aggressive in caching content, and that causes issues, for the developers on that engine too, [it seems](https://bugs.chromium.org/p/chromium/issues/detail?id=820599#c3). But I suspect the prevalence of pdf.js and it's very necessary range request functionality causes many head-scratchers like myself to end up in its issue queue.

I work on fulcrum.org, and we use pdf.js as our PDF reader (many thanks for all your hard work!). The comments above allowed me to hack around Chrome/Chromium's range request caching eating up bandwidth for Library content subscribers accessing protected PDFs through EZproxy. 

When certain headers are tweaked through EZproxy, Chrome's pending and caching behavior for pdf.js range requests causes a certain percentage of said requests to be turned from 206 into full-file 200 downloads. Depending (I suspect) on the PDF [file structure](https://github.com/mozilla/pdf.js/pull/14311#issue-1063833849), and maybe other things too, up to every other pending range request through the proxy will end up performing a **full-file** download. So like a full file download for every other page in the PDF can happen. I've seen numbers like 12GB of bandwidth used on a 75MB PDF. And what makes that extra bad is that one of the main features of EZproxy is throttling users and preventing excessive use (in case bad actors are stealing entire document collections, I suppose, see [here](https://help.oclc.org/Library_Management/EZproxy/Configure_resources/UsageLimit) and [here](https://help.oclc.org/Library_Management/EZproxy/Secure_your_EZproxy_server/Security_rules_configuration)).

I have opened an issue with EZproxy to hopefully alter their handling of headers which (i assume) are affecting range requests when Chromium caching is involved. It's not that long since they added this feature for PDFs (release notes [here](https://help.oclc.org/Library_Management/EZproxy/EZproxy_release_notes_and_known_issues/2019_release_notes/050EZproxy_v6_6_2_release_notes), more about ByteServe [here](https://help.oclc.org/Library_Management/EZproxy/Configure_resources/ByteServe)). I will edit this comment if there is anything new on that front. I know it's important to get this fixed because our library also runs an EZproxy server, and the admin has told me he can see this "many simultaneous full PDF file downloads" issue happening in the logs there, when our users access subscription-only PDF content in other institutions through the proxy.

In the meantime, in our Rails app I've added the following to the controller that is serving the PDF file to `pdf.js`:
`response.headers['Cache-Control'] = 'no-cache, no-store' if request.headers['Range'].present?`

This allows us to keep the awesome pdf.js range requests working, so that people who complain about "time to first page" problems can be kept happy, while people who authenticate and use our app thorough EZproxy can actually read things without getting inexplicably limited/throttled/blocked.
