### ISSUE TITLE
pdf.js在ie下无法显示问题！（文件流）

### ISSUE THREAD

**Issue by giserman001** [mozilla/pdf.js#9035]
我是后台获取的文件流通过转码（var array = new Uint8Array(new ArrayBuffer(rawLength));），在谷歌，火狐，opera下可以预览，但是在ie下无法预览，报错：“Unhandled rejection: TypeError: 对象不支持“replace”属性或方法”，有遇到过的吗？

**Comment by Snuffleupagus** [comment]
Closing as invalid; please use English when reporting bugs (or asking questions), since we'll not be able to help otherwise.
Also, when opening an issue, please make sure that you provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).
