### ISSUE TITLE
pdf.js  demo ，It can't be displayed under all versions of IE

### ISSUE THREAD

**Issue by giserman001** [mozilla/pdf.js#9036]
Official website's demo ，It can't be displayed under all versions of IE.  because,  demo Using the local path,
And I'm using a backstage file stream,  and transcoding(var array = new Uint8Array(new ArrayBuffer(rawLength));)   but  under IE  browser, An error:'Unhandled rejection: TypeError:The object does not support the "replace" property or method'

thanks

**Comment by Snuffleupagus** [comment]
https://mozilla.github.io/pdf.js/web/viewer.html works for me, when using IE 11.

As it stands, this issue doesn't contain nearly enough information in order to be actionable.
Again, as explained in https://github.com/mozilla/pdf.js/issues/9035#issuecomment-336792533, you *need* to fill out https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md with *all* of the information requested in order for us to have sufficient information to go on.

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since not enough information was provided.
