### ISSUE TITLE
under 360 browser perview  font  question!

### ISSUE THREAD

**Issue by giserman001** [mozilla/pdf.js#9038]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:360browser   9.1.0.356 version
- Operating system and its version: win10
- PDF.js version:new version
- Is an extension: no

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
under 360 browser  preview  .
What went wrong? (add screenshot)

> under 360 browser ,All Chinese fonts only show half!!!!!!!!!!

- 

- 

- 

- 

> 

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
As it stands, this issue is missing too much of the required information in order to be valid.

> Attach (recommended) or Link to PDF file here:

Without including an example file, this issue isn't actionable.

> Web browser and its version:360browser 9.1.0.356 version

Please refer to https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support to information about supported browsers.

> PDF.js version:new version

Please specify the *actual* version number, since it's not clear what this means.

> What went wrong? (add screenshot)

Please add a screen-shot.

**Comment by timvandermeij** [comment]
Closing until the information requested above is provided.
