### ISSUE TITLE
Unexpected server response (0) while retrieving pdf

### ISSUE THREAD

**Issue by 15004511** [mozilla/pdf.js#9067]
Attach (recommended) or Link to PDF file here:
[http://www.pdf995.com/samples/pdf.pdf](http://www.pdf995.com/samples/pdf.pdf)

Configuration:
- Web browser and its version: Google Chrome - Version 62.0.3202.62 (Official Build) (64-bit)
- Operating system and its version: - 
- PDF.js version: v0.8.377 (build: c682c25)
- Is a browser extension: - 
- Using Outsystems : Web application

Steps to reproduce the problem:
1.  run the web application.
2. failed to open pdf.

I put the pdf viewer at the main page for testing and it could not open any pdf.

What is the expected behavior?
![image](https://user-images.githubusercontent.com/30136646/31986225-35d39254-b99a-11e7-9044-bf8d2a57613e.png)

What went wrong?
![image](https://user-images.githubusercontent.com/30136646/31986193-180de6de-b99a-11e7-82ba-43a94bf4b6ff.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
[https://www.outsystems.com/forge/Component_Details.aspx?ProjectId=444](https://www.outsystems.com/forge/Component_Details.aspx?ProjectId=444)

**Comment by Snuffleupagus** [comment]
> PDF.js version: v0.8.377 (build: c682c25)

That version is more than *four* years out of date, and not supported any longer. You really should update to a recent release, see https://github.com/mozilla/pdf.js/releases.

> What went wrong?
> Unexpected server response (0) while retrieving PDF

Since it appears that you may be trying to load a PDF file from a different domain, please make sure that you read https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-load-a-pdf-from-another-server-cross-domain-request.

> https://www.outsystems.com/forge/Component_Details.aspx?ProjectId=2661

Please understand that we cannot provide support for third-party implementations of PDF.js, hence you'll need to ask support from the maintainer of that package.
(Also, note the very prominent "NOT READY FOR PRODUCTION" text on that page.)

> I put the pdf viewer at the main page for testing and it could not open any pdf.

Finally, when reporting an issue with a custom implementation of PDF.js you need to, as outlined in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), provide access to the complete example you use (and not just linking to a third-party library using PDF.js)

Closing as answered, since based on the information provided this seems to be a CORS issue.
