### ISSUE TITLE
PDF viewer showing/copying double spaces instead of single

### ISSUE THREAD

**Issue by rohanxtreme** [mozilla/pdf.js#9083]
Attach (recommended) or Link to PDF file [here:]
[Sample PDF document.pdf](https://github.com/mozilla/pdf.js/files/1426655/Sample.PDF.document.pdf)

Configuration:
- Web browser and its version: IE 11, Chrome 61
- Operating system and its version: Windows 7
- PDF.js version: 1.5.188
- Is a browser extension: No

Steps to reproduce the problem:
1. Open the attached PDF in PDF.js Viewer
2. Search for "acting as a single judge" as a phrase
3. PDF.js viewer does not return any result
4. Search the same phrase with double spaces "acting  as  a  single  judge". This time the phrase is highlighted
5. Open the PDF in any other PDF viewer (Chrome, Acrobat) search for  term with single spaces and the search yields results

What is the expected behavior? (add screenshot)
It is expected that PDF.js viewer does not show double spacing  

What went wrong? (add screenshot)
PDF.js replaces single spacing with double spacing.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

Comments:
- This behavior is not appearing on all PDF. The issue is this spacing does not appear in other viewers. My application depends on PDF.js viewer highlighting phrases, but due to this issue PDF.js viewer is not able to search and highlight the phrase even if it is present in the system.

On a side note, is there a way to negate spacing while searching using phrases ?

**Comment by rjpedrosa** [comment]
Hi! I am having the smae issue.
Did you find any solution for this?
Thanks!

**Comment by braham-snyder** [comment]
Similar issue, but more unfortunate: it's inconsistent within one file, even for the the same phrase, in the same font.

With the same file, macOS Preview does not exhibit this issue (Preview ignores whitespace in searches, but you can check the parsing by just copy/paste of the text instances in question), nor did Ubuntu's pdf viewer last I checked.


Attach (recommended) or Link to PDF file here: https://arxiv.org/pdf/1803.05407.pdf?download

Configuration:
- Web browser and its version: Firefox v80.0
- Operating system and its version: macOS Mojave (v 10.14.6)
- PDF.js version: Couldn't find this easily
- Is a browser extension: No? I'm using Firefox v80.0's built-in pdf viewer, if that answers this

Steps to reproduce the problem:
1. Open in firefox's pdf viewer: https://arxiv.org/pdf/1803.05407.pdf?download
2. Search "learning rate"
3. Note firefox says 66 matches
4. Add a second space in between to search for "learning  rate"
5. Note firefox says 17 matches

What is the expected behavior? "learning rate" is parsed with one space in all instances

What went wrong? (add screenshot) "learning rate" is often parsed with two spaces in between

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension): I don't follow

&nbsp;

I haven't double-checked, but I'd guess the issue at least partly stems from the variable-length spacing present in documents such as the linked one

Thanks a bunch.

**Comment by braham-snyder** [comment]
One potential easy way to work around the find aspect of this bug (which in my humble opinion is the worst part): one space in the find input could match any contiguous stretch of spaces in the pdf.

For example, searching for "foo bar" (one space) would also match "foo&nbsp;&nbsp;bar" (two spaces). I believe macOS Preview does this.

<br>

I'm not missing a workaround for this that everyone else is using, am I? (Other than using a different pdf viewer.)
