### ISSUE TITLE
Invalid root reference when parsing pdf

### ISSUE THREAD

**Issue by radu-cigmaian** [mozilla/pdf.js#9105]
Trying to read a pdf file using PDFJS.getDocument function. The pdf worker is throwing

UnknownErrorException {
 name: "UnknownErrorException", 
 message: "Invalid root reference", 
 details: "FormatError: Invalid root reference"
}

The error can be easily reproduced calling PDFJS.getDocument(pdfUrl) using the attached pdf
[110229_10312017_6810306.pdf](https://github.com/mozilla/pdf.js/files/1444166/110229_10312017_6810306.pdf)

**Comment by Snuffleupagus** [comment]
The PDF file is sufficiently broken that the XRef table cannot be successfully parsed, hence we fallback to parsing the entire file in order to try and find the objects.

Unfortunately even [`XRef.indexObjects`](https://github.com/mozilla/pdf.js/blob/2b70e68ebaee923683cd739020ebb45f8a921d3c/src/core/obj.js#L1069) cannot handle the brokenness of this particular file, since it relies on `endobj` to know where objects end. In the excerpt below, note how there's no `endobj` where the `5 0 R` object *should* end, meaning that parsing continues until an `endobj` is found and object `1 0 R` is thus skipped.

```
%PDF-1.3
% Factura 6810306 - Report
% Generated by Admin on 02.11.2017 at 21:14:49
5 0 obj <<
  /Creator (Axapta)
  /Producer (Admin)
  /Title (Factura 6810306 - Report)
  /Author (Axapta  \(build1600.3673\))
  /Subject (Factura 6810306 - Report)
  /CreationDate (D:20171102211449)
>>

<-- Missing 'endobj' right here. -->

1 0 obj << /Type/Catalog  /Outlines 2 0 R /Pages 3 0 R>> endobj
2 0 obj << /Type /Outlines /Count 0>>endobj
6 0 obj <<
  /Type/XObject /Subtype/Image /ColorSpace /DeviceRGB
  /Name /I6 /BitsPerComponent 8
  /Filter [/ASCII85Decode/DCTDecode] /DecodeParms[null<<>>]
  /Length 54657
  /Width 2357 /Height 180
>>
stream
```

**Comment by radu-cigmaian** [comment]
The thing is that adobe DC reader can open this file and correct this problem

**Comment by Snuffleupagus** [comment]
> The thing is that adobe DC reader can open this file and correct this problem

I fail to so how that is relevant here, since it does *not* change the fact that the PDF file is in fact *corrupt*. Hence we most likely need to re-write our XRef recovery code, in order to be able to open that file.

(It's really unfortunate that Adobe Reader opens corrupt/damaged files, since it forces every other PDF viewer to do the same, thus wasting a lot of time and effort in the process.)

**Comment by THausherr** [comment]
Indeed - today I learned that Adobe Reader displays this:

```
%PDF-1.
1 0 obj
<</Kids[<</Parent 1 0 R/Contents[2 0 R]>>]/Resources<<>>>>
2 0 obj
<<>>
stream
BT
/F1 105 Tf
0 400 Td
(Adobe tweet) Tj
ET
endstream
endobj
trailer<</Root<</Pages 1 0 R>>>>
```
Source:
https://twitter.com/angealbertini/status/928047292254425090
