### ISSUE TITLE
PR request (Korean version of contributing guide)

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9120]
Hi! My name is Sehyun Park, currently an undergraduate student who's interested in computer software programming.

As a Korean user, Korean fellows are having a problem when it comes to installing mozilla's pdf.js due to English version of contribution guide.

I do hope a lot of Korean users who want to use mozila's pdf.js, could easily understand how to install it and to contribute while looking my translation Korean version of pdf.js

I'm certain that I could give the accurate Korean translating version to people.
(I graduated from Goyang Foreign Langauage High school, and I was in English Department)

What is the expected behavior? (add screenshot)
: For those of Koreans who have somewhat problems in understanding the document fully which is written English, could definitely get a lot of help.

As an avid user who have posted several issues, I'd kindly request PR.
I'm waiting for your reply.

Have a nice day, and wish you(the members in mozilla) all the best :)

Sehyun Park

**Comment by Snuffleupagus** [comment]
I'm not sure this is a good idea, for a couple of different reasons:
 - Since none of the current contributors speak Korean, we'd have no way of actually reviewing such a change. (Short of using e.g. Google Translate, which isn't going to provide a perfect result.)
 - We'd have no way of updating such a document (as indicated see above), meaning that it could *very* soon be out of date.
 - If we start accepting localized content for e.g. the Wiki pages, where does that end?
We could quickly end up with a number of different languages that we'd need to somehow maintain (again, the points above apply). Please note, as mentioned in [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), that we don't even maintain the translations for PDF.js any more.
 - Any communication with other contributors, not to mention a PR reviewer, will still need to happen in English. Hence it seems, at least to me personally, that some basic understanding of the English language could probably be assumed.

Closing as answered.

**Comment by SehyunPark** [comment]
I totally understand what you're saying, but my little hope was that someday, some Korean users who have difficulty understanding it in English def could get a lot of help from Korean translated version.

I just wanted to help them since I could understand how to use pdf.js viewer. 

but I understand what you're saying. 
But if there's a lot of translated version file are attached in README file or in the other folders, this open source would be more popular and could target a lot of users around the world for the people who can't understand English though have the excellent computing skills. 

That's my opinion
