### ISSUE TITLE
Add an embeddable version of the default viewer

### ISSUE THREAD

**Issue by konstin** [mozilla/pdf.js#9127]
Please add an embeddable version of the default viewer or a viewer with comparable functionality and deploy it with npm. With embeddable I mean that the viewer is some `<div>` that you can include using your favorite template engine.

I am well aware of the reasoning in #5609. I don't think that this applies to an embedded viewer as it is still clearly part of a website and not of firefox or chrome. Various websites are using the default viewer anyway as there's no real alternative. Even projects as big as nextcloud [include the default viewer](https://github.com/nextcloud/files_pdfviewer/blob/master/templates/viewer.php) instead of creating their own viewer.

Due to the lack of an official embedable viewer most sites vendor the package from the website. This means every update is manual extra work and a lot of outdated viewers, which is clearly undesirable. There is even a [project](https://github.com/legalthings/pdf.js-viewer) which attempts to deploy an embeddable version themselves, but it seems to be abandoned.

For those reasons I think it is desirable for pdf.js to deploy an easily embeddable default viewer or a comparable viewer.

**Comment by Snuffleupagus** [comment]
> I don't think that this applies to an embedded viewer as it is still clearly part of a website and not of firefox or chrome.

It very much applies here, since it's essentially impossible for a "regular" user to tell if what they're seeing in an `<iframe>` is the Firefox built-in PDF Viewer or rather a version of the default viewer hosted by the web-site itself; please see http://mozilla.github.io/pdf.js/getting_started/#introduction (emphasis mine):
> The viewer is built on the display layer and is the UI for PDF viewer in Firefox and the other browser extensions within the project. It can be a good starting point for building your own viewer. ***However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.***

---

Given that there's the [viewer components examples](https://github.com/mozilla/pdf.js/tree/master/examples/components), and that the default viewer isn't really intended to be used as-is any way (as mentioned above), should this issue simply be closed as WONTFIX?

**Comment by timvandermeij** [comment]
Yes, I would agree with the reasoning above. If there is any way to improve the existing examples to make usage easier, feel free to open an issue with a suggestion or create a pull request; we'll be happy to review those.
