### ISSUE TITLE
Gimage OCR reader exports PDF in Hindi language in problematic ways. How to resolve it?

### ISSUE THREAD

**Issue by abhinavmosesben** [mozilla/pdf.js#9132]
I use Gimage reader to OCR Hindi books. It works perfectly fine when it recognises the text but when the recognised text is exported to PDF, it shows broken letters in Devanagari. I have installed the Unicode Hindi fonts also but the letters in pdf doesn't show correctly in Hindi. Just broken letters.

For example in preview it shows "प्रथम' but when exported to pdf it shows "परथम". What to do?

**Comment by timvandermeij** [comment]
I don't think anyone here speaks Hindi and the texts you show look equal to me. Without an example PDF file there is nothing we can do here, so please provide that.

**Comment by Snuffleupagus** [comment]
In addition to https://github.com/mozilla/pdf.js/issues/9132#issuecomment-344393982, it's not even clear to me if this is actually an issue with PDF.js!?

> I use Gimage reader to OCR Hindi books. It works perfectly fine when it recognises the text but when the recognised text is exported to PDF, it shows broken letters in Devanagari.

From this description, it really sounds like your issue is with the "Gimage" OCR software, and/or the specific PDF generator used. In that case, you'll need to contact the vendors of that software directly for support.

Finally, please make sure to amend this issue with *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; otherwise this issue will be closed as incomplete.

**Comment by timvandermeij** [comment]
Closing since I'm also not convinced that there is a PDF.js issue here, and it's not possible to verify without more information.

**Comment by tika949898** [comment]
Hi Sir,
I want to install hindi language, how could I do that? Gimagereader is not accessible with screen reader for blind!
