### ISSUE TITLE
the font is changed after converting the document in pdf.js viewer

### ISSUE THREAD

**Issue by SehyunPark** [mozilla/pdf.js#9139]
Steps to reproduce the problem:
1. converting a particular document into the pdf.js viewer
2. after opening the file in pdf.js viewer, some korean language fonts were changed
(which is different from the original one)

What is the expected behavior? (add screenshot)
--> appearing the same Korean fonts as specified

What went wrong? (add screenshot)
(the original document)
![image](https://user-images.githubusercontent.com/28240330/32844109-e275a5bc-ca64-11e7-933d-c7941fcfa36a.png)

(the document in pdf.js viewer)
![image](https://user-images.githubusercontent.com/28240330/32844121-ebe49f72-ca64-11e7-9251-ead3bc9a95e9.png)

(the Korean characters which come after the square appear differently)

**Comment by Snuffleupagus** [comment]
This issue is currently missing too much of the necessary information in order to be valid, please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.
Of particular importance is that you actually provide the PDF file in question!

> converting a particular document into the pdf.js viewer

What does the word "converting" actually mean here?

> (the original document)

In what other software was this screen-shot captured?
To me (not speaking Korean), the only difference between the two screen-shots I can spot appears to perhaps be slightly different zoom-levels used.

**Comment by timvandermeij** [comment]
Closing since not enough information is present to be actionable.

**Comment by SehyunPark** [comment]
the Korean font itself was represented slightly different not withstanding the face that zoom size was also different. but the problem was not that a big deal to me and it's readable so I think it's ok to be closed. Sorry for the unspecified information and I'll keep posting the issues! Thank you :)
