### ISSUE TITLE
Return fieldOptions for (buttons, radio, checkboxes)

### ISSUE THREAD

**Issue by senica** [mozilla/pdf.js#9146]
Could the `ButtonWidgetAnnotation` return the fieldOptions (the available values)?

In using a pdftk or poppler to fill our the form, it requires the actual value of the field which is not always `On` or `Off`.  As in the picture below from a fdf dump, sometimes these field values are not apparent.

I tried adding `let options = Util.getInheritableProperty(params.dict, 'Opt');` to `ButtonWidgetAnnotation` but that did not return anything. I'm assuming it needs to be in the xref parser, but in looking through it, I figured someone might be able to point me in the right direction and I'll create a pull request.

Thanks.

[g-28.pdf](https://github.com/mozilla/pdf.js/files/1480707/g-28.pdf)

![screen shot 2017-11-16 at 4 33 33 pm](https://user-images.githubusercontent.com/954952/32923411-51f60602-caec-11e7-8bff-c8c750c3cb4a.jpg)

**Comment by Snuffleupagus** [comment]
Let's close this as WONTFIX for now, given that:
 - This has not been a commonly requested feature (in the five years since the issue was opened).
 - This data is not currently needed in the *built-in* Firefox PDF Viewer (which is the primary development target for this library).
 - This behaviour *may* not be properly specified, according to https://github.com/mozilla/pdf.js/issues/11078#issuecomment-522758197.
