### ISSUE TITLE
edit wiki page's content to look good

### ISSUE THREAD

**Issue by Einere** [mozilla/pdf.js#9150]
https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#i-know-javascript-and-want-to-contribute-to-the-project-how-do-i-start

in upper link, i think editing configuration is looks better.

in front of Second, Third, and Last, insert "\n". so it looks better.
or replace them to number(1. 2. 3. ...)

**Comment by Snuffleupagus** [comment]
The https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-contrib section in the FAQ is simply intended as a very brief introduction. For more detailed information, that section already contains a reference to https://github.com/mozilla/pdf.js/wiki/Contributing, which provides *a lot* more details in a structured way.

Closing, since I don't think we need to change anything here.

**Comment by Einere** [comment]
Thank you for reading!
