### ISSUE TITLE
handle toggle doesn't work

### ISSUE THREAD

**Issue by Einere** [mozilla/pdf.js#9151]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: fire fox
- Operating system and its version: ubuntu
- PDF.js version: 
- Is a browser extension: 

Steps to reproduce the problem:
1. type "h"key to toggle text mode to handle mode
2. type "h"key to toggle handle mode to text mode

What is the expected behavior? (add screenshot)
at second type, handle mode switches to text mode

What went wrong? (add screenshot)
at second type, handle mode doesn't switch to text mode

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
With the changes made in PR #7635, toggling the HandTool on/off with just one key wouldn't work any more. The reason is that the code is now written to handle more (future) cursor tools, in which case toggling a cursor tool on/off with *one* key would no longer result in unambiguous behaviour.

Hence you'll now need to use <kbd>H</kbd> to enable the HandTool, and <kbd>S</kbd> to then enable the SelectTool.
Closing as answered.

**Comment by Einere** [comment]
thank you for explanation!!
