### ISSUE TITLE
Some pages are not displaying in IE 11

### ISSUE THREAD

**Issue by HariKrishnaT** [mozilla/pdf.js#9164]
Attach (recommended) or Link to PDF file here:
We have prepared a custom code which opens multiple PDF files in a single window. When user clicks on the hyper link the application executes below function to open the PDF file in the window.
function displayDocument(documentId)
{
	$.ajax({
            type: "POST",
            url: "DocumentDownload.jsp?documentId="+documentId,
            dataType: "xml",
            success: function(xml){
				console.log('ajax call success...' + xml);
                $(xml).find('DocumentView').each(function(){
                var responseCode = $(this).find('ResponseCode').text();
				var fileType = $(this).find('FileType').text();
				documentName = $(this).find('DocumentName').text();
				var strToken = $(this).find('Token').text();
				filePath = $(this).find('FilePath').text();
				console.log('ajax call success... file path ' + filePath);
				if(fileType.toUpperCase() == 'PDF')
				{
					$('#outerContainer').show();
					$('#outerImageContainer').hide();
					console.log('opening...PDFViewerApplication');
					PDFViewerApplication.open(filePath);
					console.log('opened...PDFViewerApplication');
				}
				else
				{
					displayTiff();
				}
				window.document.title = documentName;
				if(responseCode == 'FAIL')
				{
					alert("File you are looking to view has been crashed. Can not open " +documentName+ " file");
				}
            });
            },
            error: function() {
				console.log('error occurred in ajax call');
            	alert("An error occurred while processing XML file.");
            },
			beforeSend :function(){
				$("#fade").css('display','block');
			},
			complete : function() {
                $("#fade").css('display','none');                      
            }
});
}

Configuration:
- Web browser and its version: Internet Exproler 11
- Operating system and its version: Windows 7 - 64 bit
- PDF.js version: 1.6.210
- Is a browser extension: No

Steps to reproduce the problem:
1. Open PDF file using PDFViewerApplication.open(filePath);

What is the expected behavior? (add screenshot)
The PDF should be rendered with all the content without script errors.

What went wrong? (add screenshot)
The PDF js is throwing errors and not rendering the PDF with all the content available on the page.
![untitled111](https://user-images.githubusercontent.com/3839930/33022326-d61f8c6e-ce2a-11e7-9a96-6388c7eb3950.png)

**Comment by Snuffleupagus** [comment]
Please provide *all* of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening an issue.

In this case, you need to first of all attach the PDF file in question. Secondly, since this appears to be a custom implementation, as requested in both [ISSUE_TEMPLATE.md ](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md])https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) you need to provide access to a working example (since code snippets are of limited use).

> PDF.js version: 1.6.210

That version is no longer supported, please test with the *latest* release: https://github.com/mozilla/pdf.js/releases.

Finally, if you open your PDF file (by clicking on the "Open file" button on the right-hand side of the toolbar) with the default viewer available at https://mozilla.github.io/pdf.js/web/viewer.html; does the file render correctly there?
If it does then it's an issue with your custom implementation, and without *all* of the requested information available we cannot provide further assistance.

**Comment by timvandermeij** [comment]
Closing since this is not actionable at the moment.
