### ISSUE TITLE
Korean language error occurs.(ko)

### ISSUE THREAD

**Issue by jungyoungwoong** [mozilla/pdf.js#9172]
Ubuntu working environment.

Steps to reproduce the problem:
1. After typing 'gulp server' in terminal.
2. Server running at 'http://localhost:8888/' click
3. Enter the PDFs of/l10n/ko/...
4. Runs the files in that directory from the web page.

Problem:
What appears to be white is what we performed on the firefox web page.
The figure on the right is a state executed on Ubuntu's terminal.(Using the vi editor)
The figure created using the vi editor has no problem.
but, Running through firefox, Korean is displayed in broken state.

![1](https://user-images.githubusercontent.com/28239993/33083909-f10bf568-cf23-11e7-9733-1e0133bd0b1b.JPG)

**Comment by Snuffleupagus** [comment]
Unfortunately it's very difficult to understand what you're trying to report/ask here.

> Problem:
> An error which Korean can not see occurs.

Can you please try and clarify what you mean, since e.g. the sentence above isn't very clear?

**Comment by jungyoungwoong** [comment]
I'm sorry. I will make it in detail again.

**Comment by Snuffleupagus** [comment]
*I don't know Korean, but the following is my best guess based on squinting at the screen-shot above once more**

The `viewer.properties` files are intended to be used for localizing the default viewer interface, i.e. they're loaded by the `l10n.js` file in the *viewer* itself. However, they are *not* intended to be viewed as-is in a browser.
Hence it's likely that the browser isn't able to handle the encoding of a specific `viewer.properties` file when opened stand-alone. This isn't a problem, since the only thing that matters is that the translations appear correctly in the default viewer *itself*.

Closing as invalid.

**Comment by jungyoungwoong** [comment]
Thanks you.
