### ISSUE TITLE
License translation(en->ko)

### ISSUE THREAD

**Issue by jungyoungwoong** [mozilla/pdf.js#9174]
It is open source, but the license is important.
How about translating licenses into Korean language?
In order to ensure that Korean developers can read the license.
Do you not want translation?
I can do it.

![2](https://user-images.githubusercontent.com/28239993/33084884-6779075c-cf26-11e7-90fd-799ebffa8f08.JPG)

**Comment by Snuffleupagus** [comment]
I don't think we'd want to do this, for a couple of different reasons:
 - Since none of the contributors speak Korean, we'd have no way of actually reviewing such a change. (Short of using e.g. Google Translate, which isn't going to provide a perfect result.)
 - We'd have no way of updating such a document (as indicated see above), meaning that it could very soon be out of date.
 - If we start accepting localized content for these kind of resources, where does that end?
We could quickly end up with a number of different languages that we'd need to somehow maintain (again, the points above apply).
 - Finally, as noted in http://www.apache.org/foundation/license-faq.html#Translation a translated licence in *not* legally binding.
