### ISSUE TITLE
How do I set the workerSrc with chunkhash?

### ISSUE THREAD

**Issue by JannyHo** [mozilla/pdf.js#9203]
HI,

 I got the webpack example like this:

webpack.config.js:
```
entry: {
    'pdf.worker': 'pdfjs-dist/build/pdf.worker.entry'
  },
  output: {
    filename: '[name].bundle.js'
  },
```
and main.js like this:
```
var pdfjsLib = require('pdfjs-dist');
pdfjsLib.PDFJS.workerSrc = '../../build/webpack/pdf.worker.bundle.js';
```

It's works!

 But in my project, the webpack.config.js looks like this:
```
entry: {
    'pdf.worker': 'pdfjs-dist/build/pdf.worker.entry'
  },
  output: {
    filename: 'static/scripts/[name].bundle.[chunkhash].js'
  }
```
how do I set the pdfjsLib.PDFJS.workerSrc with **chunkhash** ? 

I coded like this but I think it won't  work cause the value is a String:

```
var pdfjsLib = require('pdfjs-dist');
pdfjsLib.PDFJS.workerSrc = '../static/scripts/pdf.worker.bundle.[chunkhash].js';
```

Could you tell me How should I do? ^_^

**Comment by JRigotti** [comment]
I couldn't make it work this way, then I tried the 

`var pdfjsLib = require('pdfjs-dist/webpack');`

It didn't work as well, but it was some worker-loader issue in my webpack configuration. I managed to use it after all just pointing to an external worker script.

**Comment by Snuffleupagus** [comment]
This sounds more like a Webpack issue rather than a PDF.js one. However, a quick search brought up https://webpack.github.io/docs/long-term-caching.html, which seems relevant here.
Based on the information provided there you should be able to output the actual filename with Webpack, and then just assign that to `workerSrc`.

If you're not able to make that work, then as asked for in both https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md and https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, you'll need to provide a complete (runnable) example (since just code snippets aren't very helpful).
