### ISSUE TITLE
How can I access PDFViewerApplication?

### ISSUE THREAD

**Issue by JRigotti** [mozilla/pdf.js#9210]
- I installed pdf.js in my web application using webpack and npm to get `pdfjs-dist` package.
- I can't find a way to access this `PDFViewerApplication` in the fashion that it says in this [FAQ answer](https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#can-i-specify-a-different-pdf-in-the-default-viewer)

Checking out the files I could see that [`App.js`](https://github.com/mozilla/pdf.js/blob/master/web/app.js) exports this function, but I get an error when I try to import it directly. But so none of the exported object from 'pdfjs-dist' provide that.

How can I access this function?

**Comment by Snuffleupagus** [comment]
The default viewer, i.e. the one found at https://mozilla.github.io/pdf.js/web/viewer.html, is purposely *not* included in https://github.com/mozilla/pdfjs-dist; please refer to https://github.com/mozilla/pdf.js/issues/5609#issuecomment-68530552 and https://github.com/mozilla/pdf.js/issues/7203#issuecomment-210510569.

Please keep the following, as mentioned in e.g. https://mozilla.github.io/pdf.js/getting_started/ and https://github.com/mozilla/pdf.js/wiki/Setup-pdf.js-in-a-website, in mind:
> However, we do ask if you plan to embed the viewer in your own site, that it not just be an unmodified version. Please re-skin it or build upon it.

Hence we don't want to make it too simple to use it directly. Instead there's a number of viewer components (which are also used by the default viewer) available, that can be used to create a custom viewer.
Please find examples of using the viewer components at https://github.com/mozilla/pdf.js/tree/master/examples/components, and that the necessary files for a custom viewer is already being distributed in https://github.com/mozilla/pdfjs-dist/tree/master/web (i.e. available through e.g. NPM).

Closing as answered.

**Comment by JRigotti** [comment]
Thanks for the reply, I checked out the components folder, but if I follow it I got an error since I don't have access to `PDFPageView` ([source](https://github.com/mozilla/pdf.js/blob/012d075604103805b5404dcc94ef0d14cd8d97e2/examples/components/pageviewer.js#L43)), which should be packaged in `pdfjs-dist`, right?.

I tried to require the file you told me 
```
import { PDFViewer } from 'pdfjs-dist/web/pdf_viewer';
```
But that generates an error 
```
ReferenceError: document is not defined at Object.defineProperty.value (/mypackage/node_modules/pdfjs-dist/web/webpack:/external/webL10n/l10n.js:34:1)
```

**Comment by Snuffleupagus** [comment]
Since the various viewer components are (currently) added to the global `PDFJS` object, I'm assuming that simply doing `import 'pdfjs-dist/web/pdf_viewer';` should work directly with the e.g. the [pageviewer example](https://github.com/mozilla/pdf.js/blob/master/examples/components/pageviewer.js). Is that not the case?
Or, you could probably do something like `import { PDFJSViewer } from pdfjs-dist/web/pdf_viewer;` and use `PDFJSViewer.PDFPageView` (in place of `PDFJS.PDFPageView` in the example).

However, without a complete (runnable) example, as mentioned in e.g. https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, it's very difficult (or even impossible) to tell what might be wrong.

**Comment by RaviGprec** [comment]
Hi @JRigotti ,

Have you got any solution for your problem?

I'm also facing the same issue.

thanks in advance!!

**Comment by JRigotti** [comment]
@RaviGprec no, I gave up and started importing the pdf.js script through a `<script>` tag

**Comment by RaviGprec** [comment]
Hi @JRigotti ,

Actually, I'm trying to develop PDFviewer using PDF.js in Angular 5. 

1. Right now, I'm able to implement only PreviuosPage, NextPage, zoom functionality. 
2. Is there any way that we can feed the PDF content to the viewer and the rest of functionality will take care of any js file.?
3. I tries using viewer.js but the limitation for this viewer.js is that it can take only file path. But I've pdf 
4. content in uint8array format.  @timvandermeij  is saying 

> Passing UInt8Array data is not what viewer.js supports since it's the default viewer in Firefox and it doesn't need that capability. You'll have to make a custom viewer, for example based on https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js. In any case, you need to pass it to the getDocument API function as the data parameter.

Have a look here:-[https://github.com/mozilla/pdf.js/issues/9615](url)

**My question is** : 
**Do I need to develop my own custom viewer instead of using default viewer.html,viewer.js provided by mozilla?
Or is there any way to use viewer.js, viewer.html in our project just by feeding PDF content (uint8array format) to viewer.js?** 

Thanks in advance!!

Regards,
Ravi Kumar

**Comment by JRigotti** [comment]
Hi @RaviGprec, I don't work for a while with pdf.js, but I'll try to help you out.

> Do I need to develop my own custom viewer instead of using default viewer.html,viewer.js provided by mozilla?

You don't, check [simpleviewer example](https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js) to see how it is implemented.

> Or is there any way to use viewer.js, viewer.html in our project just by feeding PDF content (uint8array format) to viewer.js?

I don't think so, as far as I know pdf.js only supports `.pdf` files and [base64](https://github.com/mozilla/pdf.js/blob/63c7aee11211f071af382892f1664fe90f56b9e4/examples/learning/helloworld64.html) encoded strings.

**Comment by RaviGprec** [comment]
Hi @JRigotti ,

Have you tried anything?

> I don't think so, as far as I know pdf.js only supports .pdf files and base64 encoded strings

feeding PDF content means, I'll give pdf to viewer.js in uint8array format. This uint8array data is coming from server.  So will that work fine?

viewer.js is taking DEFUALT_URL (file path). I want to give uint8array instead of default_url (as my files are coming from server as arraybuffer format and are  being converted uint8array format.)

Thanks in advance!!

Regards,
Ravi Kumar

**Comment by KenSpur** [comment]
@JRigotti, I Solved the .pdf isseu on my webserver by rerouting "*.pdf" extensions to a Mvc controller in an ASP.NET web app to return FileResult(byte[], contentType) which works well to load pdfs out of Azure blob storage

**Comment by LibertyNLP** [comment]
I have wrote a post introduced works codes about "How to get and learn PDFViewerApplication from PDF.js“, you can view that post, this is my post URL [https://www.libertynlp.com/index.php/2022/06/02/how-to-get-and-learn-pdfviewerapplication-from-pdfjs/](https://www.libertynlp.com/index.php/2022/06/02/how-to-get-and-learn-pdfviewerapplication-from-pdfjs/)
