### ISSUE TITLE
What is the status of svg renderer?

### ISSUE THREAD

**Issue by MickL** [mozilla/pdf.js#9211]
It seems like there is(or was?) a svg renderer in work that could replace canvas rendering. I don't find any documentation and hardly any informations about it so i'd like to ask some questions:

- What is the status so far? Is it production ready?
- Can it just replace the canvas renderer, e.g. by use of `PREFERENCES`?
- Or do we need a completely new viewer.js? (The [example of viewer.js](https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer/viewer.js) contains only 59 lines of code while the original from the [demo](https://mozilla.github.io/pdf.js/web/viewer.html) contains more than 9000.)
- Why not make svg the default? It seems like it is way more efficient than canvas rendering. (What about benchmarks for comparison?)

**Comment by Snuffleupagus** [comment]
> What is the status so far? Is it production ready?

No, and I'd say quite far from it. There's currently a fair number of operations that are unsupported in the SVG backend (as can be seen from the large amount of warnings when using it), when compared with the Canvas backend.
Currently, save for the occasional patches, there's not really much work being done on the SVG backend; see also https://github.com/mozilla/pdf.js/projects/2.

> Can it just replace the canvas renderer, e.g. by use of PREFERENCES?
> Or do we need a completely new viewer.js?

The default viewer has supported the SVG backend since PR #7738, and it can be toggled using the `renderer` preference.

> Why not make svg the default? It seems like it is way more efficient than canvas rendering.

It's currently missing *a lot* of features and futhermore there aren't currently any (reference) tests for the SVG backend.
Furthermore, in practice, there's no guarantee that it's faster (or more memory efficient) than the Canvas backend. For example, the sheer amount of DOM elements in many documents causes the viewer to become really sluggish when scrolling. There can also be issues with text-selection, since the PDF format uses different algorithms for rendering/text-extraction (one potentially problematic example is ligatures).

> (What about benchmarks for comparison?)

You're certainly free to attempt to provide comparisons!

Closing as answered.
