### ISSUE TITLE
Is it possible to get an annotation link text?

### ISSUE THREAD

**Issue by datermine** [mozilla/pdf.js#9236]
If you look at this jsfiddle (http://jsfiddle.net/k3m8pnk5/) you can see that this PDF has an annotation on the text "PDF.js" (which goes to https://github.com/mozilla/pdf.js/). 

See L39 for the gist of my problem. I'd like to be extract the link text that the annotation is associated with. Is there no way to do so? What about extracting the text in a rectangle?

**Comment by varunnair18** [comment]
@timvandermeij @Snuffleupagus 

Hello! Has there been any update on this question since it was asked here and in #11345 ? 

I've also been looking to extract the text of a LinkAnnotation or extract the text present in rectangle using the coordinates in the annotation "rect" property, but am unable to find the answer anywhere in documentation or elsewhere online. 

Would greatly appreciate some help!

**Comment by timvandermeij** [comment]
In general this is not really possible because the annotation layer and the text layer are disjoint. In the PDF file format, annotations only have a rectangle (position) that is absolute in relation to the canvas. It only defines which link should be followed when the rectangle is clicked, but it has no knowledge about the underlying canvas/text element.

The only thing I can imagine is trying to map the rectangle coordinates onto the text layer coordinates, but this may become very complicated and therefore not something we can support from the library perspective.
