### ISSUE TITLE
#findInput::placeholder style is now low-contrast in Chrome - consider setting color

### ISSUE THREAD

**Issue by alice** [mozilla/pdf.js#9237]
Per the image below, the placeholder text in `#findInput` is now low contrast because the Chrome UA style changed to improve the placeholder contrast against a white background.
![image](https://user-images.githubusercontent.com/95208/33579847-386b848e-d99f-11e7-92c1-d13f9cec0de9.png)

`#cecece` or lighter would meet AA contrast ratio requirements.

`::placeholder` style is defined here:
https://github.com/mozilla/pdf.js/blob/04b93cf57e36f46a2cbb13c839a9b32fa76ff4e5/web/viewer.css#L444

**Comment by amit7010** [comment]
Hi,
Can i do it?

**Comment by timvandermeij** [comment]
Sure, just keep in mind that a solution for this must work in all browsers, i.e., not be Chrome-specific. Thanks!

**Comment by amit7010** [comment]
Hi,
i used `color:#e0e0e0;` , a lighter shade then `#cecece` because it was little darker for Mozilla Firefox.
Below is the Preview of Mozilla Firefox Browser.
Firefox Quantum
Version: | 57.0.2 (64-bit) 

![pdf_mozilla](https://user-images.githubusercontent.com/22027941/33899441-812e231e-df91-11e7-8de4-15fd8b99ba9a.PNG)

Other Browsers:
Opera
Version: | 49.0.2725.47

![opera_pdf](https://user-images.githubusercontent.com/22027941/33899761-825c2fc8-df92-11e7-8d46-98b4a89eeec4.PNG)

Chrome
Version: | 63.0.3239.84 (Official Build) (64-bit)

![chrome_pdf](https://user-images.githubusercontent.com/22027941/33900757-9ea9a978-df95-11e7-95bd-71c41dea8e1e.PNG)

Microsoft Edge 
Version: | 38.14393.1066.0

I don't know why pdf s are not opening in my edge browser but saw that Input placeholder and not happy about it.

![edge_pdf](https://user-images.githubusercontent.com/22027941/33900635-283a20f6-df95-11e7-98b2-92f67ae0a73a.PNG)

Open for suggestions .. 
Guide me what to do next 
Thank You
