### ISSUE TITLE
PDF not rendering at all: getOperatorList - ignoring errors during task: RenderPageRequest

### ISSUE THREAD

**Issue by ndnenkov** [mozilla/pdf.js#9252]
This can be reproduced either with a simple app using PDFJS or a newer version of Firefox. I'll give details for the latter.

**Attach (recommended) or Link to PDF file here:**
[not-shown-pdfjs.pdf](https://github.com/mozilla/pdf.js/files/1542926/not-shown-pdfjs.pdf)

Configuration:
---
**- Web browser and its version:**
Firefox 57.0.1 (64-bit)
**- Operating system and its version:**
OS X EI Capitan 10.11.6
**- PDF.js version:**
1.9.583 (shipped with Firefox)
**- Is a browser extension:**
No (built into Firefox out of the box)

Steps to reproduce the problem:
---
1. Open the related PDF

**What is the expected behavior? (add screenshot)**
One page with the text 'Test' is rendered. Works with any other viewer I tried.
<img width="903" alt="screen shot 2017-12-08 at 4 43 22 pm" src="https://user-images.githubusercontent.com/1595577/33770606-04755ff2-dc37-11e7-9c93-c5491366dc57.png">

**What went wrong? (add screenshot)**
Nothing renders.

<img width="1069" alt="screen shot 2017-12-08 at 4 43 40 pm" src="https://user-images.githubusercontent.com/1595577/33770624-0ed54ca0-dc37-11e7-8282-c86925cb6a76.png">

Related warning in the console:
```javascript
Warning: getOperatorList - ignoring errors during task: RenderPageRequest: page 0
```

**Comment by Snuffleupagus** [comment]
This is what the content stream in that PDF file looks like, once decoded:
```
q
BT
/F1 15 Tf
. .59 .84 rg
50 750 Td
(Test) Tj
ET
Q
```
The `rg`, i.e. the "setStrokeRGBColor", operator requires *three numerical* arguments. However as can be seen above, the first value is just a decimal comma, which isn't a valid number (in `. .59 .84 rg`).

**Comment by ndnenkov** [comment]
@Snuffleupagus I see. So is it a matter of adding a sensible default when the value isn't numeric (`0` perhaps)? Is this going to get fixed in PDFJS?

**Comment by Snuffleupagus** [comment]
> So is it a matter of adding a sensible default when the value isn't numeric (0 perhaps)?

I don't completely understand this question, since if you're not providing three *numeric* arguments then the `rg` operator, and by extension the PDF file itself, is *not* valid. So obviously, if you want one of the values to be zero, then it should be set to that (and not to something else).

> Is this going to get fixed in PDFJS?

It may eventually get fixed, but please keep in mind that this is a bug in a specific PDF file, rather than in the PDF.js library itself. And in this case, I'm not sure if there's an easy solution that won't slow down parsing of *valid* PDF files.
Hence a workaround may not be implemented any time soon, so if you're in control of the PDF generation, please make sure that the file created is valid.

**Comment by ndnenkov** [comment]
I understand that it's not valid. My point was that other viewers seem to use `0` when a value is not valid (numeric) as a workaround.

I get that this is not part of the pdf standard and it's unfortunate that other viewers have implemented hacks to support malformed pdfs, which in turn leads such pdfs becoming popular in the wild.

---

Still, I'm not in control of the pdf generation and I can't tell clients that their pdf is invalid and they have to submit a new one given that they can see the contents of said pdf with other viewers.
