### ISSUE TITLE
The right half of each character is cut off in Microsoft Edge in some PDFs

### ISSUE THREAD

**Issue by takahiroyoshi** [mozilla/pdf.js#9259]
In some PDFs and in older PDF.js, the right half of each character is cut off in Microsoft Edge in one of my Widnows 10 computers.

How to reproduce:
1. Download http://www.jpma.or.jp/opir/news/news-44.pdf
2. Load it pdf.js viewer whose version is lower than 1.8.582.
(Make sure the zoom level is auto.)

The screenshot in one of my Windows 10 computer (bad)
![moji_bad20171210](https://user-images.githubusercontent.com/3334552/33803288-b7f043a0-ddcf-11e7-9201-6d20f880fbc0.png)

The screenshot in one of my another Widnows 10 computer (good)
![good_pdfjs201712](https://user-images.githubusercontent.com/3334552/33803322-73f1856e-ddd0-11e7-80c0-da753e2c0bfe.png)

Even on my problematic Windows 10 computer as well, the latest pdf.js seems to have no problem because streams-lib is now useed as polyfill after commit 01b47d9012b15c857f423dcbf2f7238f341c1985.

But for some reasons, I can not upgrade to the latest pdf.js.

Strangely, even on my problematic Windows 10 computer as well, if I zoom out the PDF from automatic level, it begins to show the whole character. Mostly when I zoom down to 70% or so, almost all parts of each character are visible except the title text whose font size is bigger.

I turned off and on HWA but no change. What seems to be wrong?

Issue #9225 may be a little bit similar.

I appreciate any suggestions. Thank you in advance.

**Comment by Snuffleupagus** [comment]
> the right half of each character is cut off in Microsoft Edge in one of my Windows 10 computers.

This really sounds like an issue with a particular version of Windows 10 and/or an issue with e.g. the graphics drivers, both issues that we really cannot fix.

> Load it pdf.js viewer whose version is lower than 1.8.582.

As can be seen at https://github.com/mozilla/pdf.js/releases, the latest stable release is `v1.9.426` as of this writing. The version you're referring to was never an official release, and please keep in mind that support for previous versions end when a new release is created.

> But for some reasons, I can not upgrade to the latest pdf.js.

I'm sorry, but as a general rule we won't attempt to patch old and now unsupported versions of PDF.js.
Especially in a case like this, when the evidence points to this being an issue with a *particular* configuration rather than the PDF.js library itself.
Hence the only advise that we can provide is to attempt the update anyway, which I'd assume you'll need to do eventually anyway in order to benefit from future bug fixes (and miscellaneous improvments) anyway! 

> Issue #9225 may be a little bit similar.

I'm not sure it's relevant here, since that one is a more general issue about font rendering quality on canvas.

Closing as invalid, since there doesn't appear to be anything we can fix on the PDF.js side.
