### ISSUE TITLE
Fill-in AcroForm still does not works? What about JavaScript?

### ISSUE THREAD

**Issue by Alex-DE-74** [mozilla/pdf.js#9261]
Hello and thanks for this work!

I'm new here, so please excuse me if I wrote something bogus ;)

Accordingly many discussions here, AcroForms should be supported now. As example this document is referred:
https://www.irs.gov/pub/irs-pdf/f1040.pdf

I tried this, and also my own documents, but no one field can be filled/checked/selected. Is it a new bug in latest (stable and development) release? I've tried this on online demo-page as on my local-page with Edge & Chrome, but no luck.

Or ist it only currently possible to render AcroForms, but no interaction?

-------------------------

Other question - is it planned to add some JavaScript functionality like set field value, clear field(s), send data to server. Because this library itself is hugely based on JavaScript, parsing/executing some simple PDF-JavaScript is maybe not a big deal. Or am I completelly wrong?

Thank you for considering my questions!
Alex

**Comment by Snuffleupagus** [comment]
> Accordingly many discussions here, AcroForms should be supported now.

No such claim has been made, since this is still an open issue; this work is being tracked in https://github.com/mozilla/pdf.js/projects/1 and e.g. issue #7613. Please keep in mind that this is a big and complicated project.

> Other question - is it planned to add some JavaScript functionality like set field value, clear field(s), send data to server.

Some of this may eventually be implemented as part of adding form support.

> Because this library itself is hugely based on JavaScript, parsing/executing some simple PDF-JavaScript is maybe not a big deal. Or am I completelly wrong?

Executing *general* JavaScript is probably never going to happen, since doing so could pose quite serious security risks.

Closing as answered, since this is already tracked elsewhere.

**Comment by kingihai** [comment]
Come and See to the smartTest which everyone can make acroform easily immediately. www.smarttest.kr
