### ISSUE TITLE
Broken PDF does not throw any error

### ISSUE THREAD

**Issue by Capocalypse** [mozilla/pdf.js#9273]
Configuration:
- Chrome 63.0.3239.84
- Windows 7
- PDF.js version: 2.0.205

While trying to show a corrupted PDF, a blank page is rendered. The console log reports a lot of warnings (screen attached). I just need to throw an error when the pdfjs fails to correctly read a pdf. Is that possible? thank you in advance 
![image](https://user-images.githubusercontent.com/34517753/33951910-8de51352-e030-11e7-8bc3-82f2c733d382.png)

**Comment by Snuffleupagus** [comment]
Since PDF readers will in general attempt to recover from all sorts of corrupted files, PDF.js needs to attempt to do the same. Hence `getDocument` will only throw an error (or more correctly return a rejected Promise on the `PDFDocumentLoadingTask`), for *really* broken PDF files.

Depending on the kind of corruption present in the PDF file, the following `getDocument` parameter may be helpful to disable *part* of our recovery code: https://github.com/mozilla/pdf.js/blob/b327633ad606ba54bded787c4e004d0aa1484b7c/src/display/api.js#L135-L138

Another option may be to register a callback function, to be notified if a PDF file triggers any unsupported features; refer to https://github.com/mozilla/pdf.js/blob/b327633ad606ba54bded787c4e004d0aa1484b7c/src/display/api.js#L361-L365

However, without access to the PDF file in question, it's really difficult to provide a more detailed answer. So please, as requested in the [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md), attach the PDF file to this issue.

**Comment by timvandermeij** [comment]
Closing; we cannot provide more information if the PDF file is missing.
