### ISSUE TITLE
etting pdf path

### ISSUE THREAD

**Issue by hemant6263** [mozilla/pdf.js#9277]
I am new to pdfJS my issue is i am trying to show PDFs from my database 
I don't know how to exactly send the stored PDFs to pdfJS viewer for viewing  purpose I followed ?file= but didn't get any success

**Comment by Snuffleupagus** [comment]
When opening an issue, please make sure that you first of all read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) and that you provide all of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md).
In particular, note also that if the question pertains to a custom implementation of PDF.js, you'll need to provide access to a complete and runnable example.

Closing as incomplete, since there's unfortunately no actionable information provided.
