### ISSUE TITLE
Is there any way i can skip or restrict PDFJS from rendering specific pages in a whole PDF? 

### ISSUE THREAD

**Issue by AnanthaRamaKrishnan47** [mozilla/pdf.js#9284]
If i load a PDF, for example say 10 pages. Can i restrict or stop PDFJS from rendering the specific pages i choose? Is there any way i can implement it?

**Comment by Snuffleupagus** [comment]
You can use the `disableAutoFetch` option to only load and render the pages that are visible in the default viewer, please refer to https://github.com/mozilla/pdf.js/blob/546cd2b67cade0ca5b083aff8346f4d50a40cd73/src/display/global.js#L173-L183

Aside from that, PDF.js contains no specific functionality to "ignore" random pages in the default viewer.
If you implement your own viewer, then it should be possible to no fetch certain pages from the API, however that isn't functionality that's relevant for the default viewer in PDF.js.

Closing as answered (and out-of-scope), since the limited information provided makes it difficult to provide a more detailed answer.
