### ISSUE TITLE
open blob url in viewer application

### ISSUE THREAD

**Issue by jafar-rezaei** [mozilla/pdf.js#9289]
I am looking a way to read `pdf` file from `blob` link and display it in my `pdf.js` viewer application .

my blob Url seems some thing like :
`blob:null/564c950d-1010-4cf4-994c-6e8e63e16a21`

when I open it with mozilla opened in pdf.js extention but if I try get this with my `pdf.js` application with some url like this :

`PATH/index.html?file=blob:null/564c950d-1010-4cf4-994c-6e8e63e16a21`

viewer application gives me this error :

`PDF.js v2.0.0 (build: ?)
Message: Unexpected server response (0) while retrieving PDF "blob:null/564c950d-1010-4cf4-994c-6e8e63e16a21".`

**Comment by Snuffleupagus** [comment]
> PDF.js v2.0.0 (build: ?) Message: Unexpected server response (0) while retrieving PDF "blob:null/564c950d-1010-4cf4-994c-6e8e63e16a21".

That version number doesn't make sense, since there's never been any point where that *exact* version has been used. Furthermore, the fact that `build` isn't defined also seem weird.

Since this appears to be an issue with a custom implementation of PDF.js, please provide a complete (and runnable) example, as asked from in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md).

**Comment by jafar-rezaei** [comment]
@Snuffleupagus  actually it is working in Mozilla and Chrome but in chrome I can not open blob link from `pdfMake` library.

is it good way to show blob with URL ?
we have some methods in pdfmake like this : 
```
# option 1
var data;
pdfMake.createPdf(docDefinition).getDataUrl(function(dataURL) {
    data = dataURL;
});

# option 2 
var data;
pdfMake.createPdf(docDefinition).getBase64(function(encodedString) {
    data = encodedString;
});

# option 3
var data;
pdfMake.createPdf(docDefinition).getBuffer(function(buffer) {
    // turn buffer into blob
    data = buffer;
});
```
can we use this data instead of adding URL ? which one will be faster ?
(@note I am using viewer application)

For testing , you can get a blob url with `pdfmake` library here(opens a new tab) : 
http://www.jurchin.com/test/build/

and show it here : 
http://www.jurchin.com/test/generic/web/viewer.html?file=BLOB_URL

**Comment by Snuffleupagus** [comment]
> actually it is working in Mozilla and Chrome but in IE can not open blob link from pdfMake library.

That's information you really ought to have provided up front, by filling out all of the details requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md when opening the issue.

> For testing , you can get a blob url with pdfmake library here(opens a new tab) :
> http://www.jurchin.com/test/build/
> 
> and show it here :
> http://www.jurchin.com/test/generic/web/viewer.html?file=BLOB_URL

Those steps aren't entirely straight-forward to follow, since all modern browsers block popup windows by default. However, when trying to load the http://www.jurchin.com/test/build/ page in IE 11, there's errors throw from the `pdfmake.min.js` file (and all browsers seem to throw jQuery errors as well).

Since `pdfmake` has nothing to do with PDF.js, I'm closing this issue as invalid.
