### ISSUE TITLE
want disable text selection. but after change "disableTextLayer": to true, still can select text

### ISSUE THREAD

**Issue by yoer** [mozilla/pdf.js#9292]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Qt webkit
- Operating system and its version: win10
- PDF.js version: 1.10.88
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)
i want disable text selection, so i disable text layer rendering by edit view.js, change "disableTextLayer": to true, but not working, i still can select text...

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
> i want disable text selection, so i disable text layer rendering by edit view.js, change "disableTextLayer": to true, but not working, i still can select text...

Without *any* information regarding how exactly you're attempting to set `disableTextLayer` to `true`, there's unfortunately nothing we can do to help here!

As requested in both [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md), for issues with custom implementationd of PDF.js, please provide a complete (and runnable) example in order for the issue to be valid.

**Comment by timvandermeij** [comment]
Closing since not enough information is provided. Try looking into how the mobile example works, because that uses the `disableTextLayer` flag: https://github.com/mozilla/pdf.js/blob/c26e49724400fb2c463f3348c8322daefc9539ed/examples/mobile-viewer/viewer.js#L25. If you're using the default viewer, try setting https://github.com/mozilla/pdf.js/blob/af71ea7a7dcb8cbb3d710a73584a0de8d65e5a96/web/default_preferences.json#L13.
