### ISSUE TITLE
pdf.js applied to the app, the process will automatically shut down the problem

### ISSUE THREAD

**Issue by wangyunshuo** [mozilla/pdf.js#9298]
pdf.js code applied to the app project, when opening the pdf document will take up a lot of process space led to the app automatically shut down, may I ask this question is the pdf source code cache or system cache you?

**Comment by Snuffleupagus** [comment]
Unfortunately there's nowhere near enough information provided to understand what's being asked here!

When opening an issue, please read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) and make sure that you provide the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md). Since this appears to be an issue with a custom implementation of PDF.js, please provide access to a complete (and runnable) example as explained in the links above.

**Comment by timvandermeij** [comment]
Closing due to the above.
