### ISSUE TITLE
PDF.JS Performance Issue 

### ISSUE THREAD

**Issue by ffourofhom** [mozilla/pdf.js#9302]
Hello , every advanced .
I write pdf.js in jQuery mobile，
On Android phone, the problem is that I first in  the PDF page is normal  ,when i back to the Previous page and  into the pdf page again, phone's performance is down . Is anyone has the same situation? 
How do I resolved the problem?

**Comment by Stefanieissun** [comment]
Silent, I can't wait silent

**Comment by Snuffleupagus** [comment]
Closing as incomplete, since there's unfortunately no actionable information provided.

When opening an issue, please make sure that you read https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md and also that you provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.
