### ISSUE TITLE
Splitting PDF.js into multiple libraries

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#9312]
I think that PDF.js contains many great features, that could be used separately for other purposes than just rasterizing PDF documents. I.e. making it more robust.

Right now, I am looking for a PDF interpreter with a following interface:

    PDFI.interpret( pdfFile, drawer );

The interpreter would process the content of pdfFile and ocasionally call drawer.Fill(gst);  drawer.Stroke(gst),  drawer.Text(gst),  drawer.ShowPage(gst) .. . "gst" would be current graphic state (including current path, fill and stroke parameters etc.)

The drawer could be anything. It could draw stuff into a Context2D Canvas, or triangulate shapes and draw into WebGL canvas, or "analyze" paths and (partially) reconstruct the original LaTeX / DOCX file. Or just extract all bitmaps or all text from a PDF file.

Personally, I want to make a PDF to SVG converter (so my drawer would build a string containing the SVG representation of the PDF). 

Would anybody here be interested in making PDF.js more robust, so it could be used for other purposes?

**Comment by timvandermeij** [comment]
I think it's an interesting idea, but it will require quite a bit of work to get there. There is some WebGL code particularly for masks: https://github.com/mozilla/pdf.js/blob/master/src/display/webgl.js. More interestingly, we also have an experimental SVG back-end (see https://github.com/mozilla/pdf.js/blob/master/src/display/svg.js), so I think that can be seen as what you describe as a drawer. While the operators are the same, there is no formal interface and usage defined right now. It might be good to move towards such a structure where the interface and usage for a back-end (2D canvas, SVG, WebGL, ...) is well-defined. I think that would also make it easier to integrate the SVG back-end in the current core and testing code, because, while it's not terribly hard at the moment, the code for that could be easier.

**Comment by photopea** [comment]
Thanks for your answer. My idea was, that the interface would be always the same for each drawer (no matter if it is context2D or SVG, or WebGL). You would provide the interpreter and users of your library (e.g. me) would make their own drawers. Of course, you can provide your own drawers inside PDF.js and even keep the current interface (drawer would be behind it).

I am going to make a PDF import for my image editor www.Photopea.com (to convert PDF to PSD, and later PSD to SVG / PNG / PDF) and I will write my own PDF parser / interpreter. I would love to use any existing tool, but PDF.js seems too "monolythic" and complex for me. I prefer to use a "black box" with a clear interface, rather than trying to tweak megabytes of unknown code.

**Comment by Snuffleupagus** [comment]
> Splitting PDF.js into multiple libraries

I'm not convinced that *separate* libraries would do much more than increase the maintenance burden placed on the main contributors, so it'd probably be best to focus efforts on improvements in this repository.

> Would anybody here be interested in making PDF.js more robust, so it could be used for other purposes?

While there is probably room for improvements in the core PDF.js, w.r.t. re-use in other more general situations, it does seem that the issue as filed is perhaps slightly too broad to be actionable in its current form. Refer to https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, in particular:
> The issue tracking system is designed to record a single technical problem. A bug report is something where a developer/contributor can work on. The GitHub issue tracker is not a good place for general, not well thought out or unworkable ideas. Most likely a discussion-type issue will not be addressed for a long time or closed as invalid. The best place for general discussions is our #pdfjs IRC channel on irc.mozilla.org.

**Comment by photopea** [comment]
I guess I will write my own PDF interpreter. I also want to make a PDF export, so it will be handy to know the PDF specification.
