### ISSUE TITLE
Is there anyway that i can duplicate an existing page twice or more?

### ISSUE THREAD

**Issue by AnanthaRamaKrishnan47** [mozilla/pdf.js#9324]
is there any way i can modify the page list and show an existing page twice?

**Comment by Snuffleupagus** [comment]
No, there's functionality like that in the default viewer (which I'd assume is what you're asking about).
Furthermore, there appears to be no need for doing in the default viewer, so this would also be out-of-scope for the PDF.js project itself.

Closing as answered. 

---
*For future reference: When opening an issue, please provide more information/context than this, since it's quite difficult to understand what's being asked otherwise.
