### ISSUE TITLE
Extract tables from PDF and store it in JSON

### ISSUE THREAD

**Issue by shandy101** [mozilla/pdf.js#9338]
My use case is , I have to extract text from PDF.The problem is I have  to do it from the buffer. My file location is S3 so I will get the file as a buffer. I have tried various plugins built on this  those are not giving up satisfactory result. All my PDF files will have table. These tabular coloums will have to extracted  But, [I am following this](https://github.com/mozilla/pdf.js/blob/master/examples/node/getinfo.js) for now, Could some one put me in the right path.

Thanks in advance.

**Comment by Snuffleupagus** [comment]
> All my PDF files will have table. These tabular coloums will have to extracted

The PDF specification has no concept of tables (or similar structures), and the contents of a page simply consists of a series of operators. Hence there's not going to be any easy to achieve what you want here.

Closing as invalid.

**Comment by taoqf** [comment]
I believe this is a very common need, because many PDF files are in fact exported from spreadsheets. When we no longer have the original tabular data, we do need to convert the PDF back into table form. A Python library called pdfplumber already provides this capability through its extract_tables method. Although the conversion isn’t perfect, it’s largely accurate and has proven sufficient to solve many real-world production problems.
@Snuffleupagus
