### ISSUE TITLE
Hide Download Button when loading PDF from 'file://'

### ISSUE THREAD

**Issue by Hirse** [mozilla/pdf.js#9342]
Configuration:
- Web browser and its version: Firefox 57
- Operating system and its version: Win 10
- PDF.js version: 1.9.583
- Is a browser extension: Yes

Steps to reproduce the problem:
1. Open a local PDF file with Firefox

What is the expected behavior?
Hidden Download Button as the file I am looking at is already on my computer.
![2018-01-05_15-39-54](https://user-images.githubusercontent.com/2564094/34633118-c4e0fa3c-f22e-11e7-8c9a-15c52a9e9345.png)

What went wrong?
Download Button is visible.
![2018-01-05_15-38-02](https://user-images.githubusercontent.com/2564094/34633088-95b8481e-f22e-11e7-811b-1ecb1bff6f84.png)

**Comment by himanish-star** [comment]
@timvandermeij , Could I work on this issue ?

**Comment by timvandermeij** [comment]
Yes, it's yours.

**Comment by himanish-star** [comment]
Ok, cool. I'll start working on this.

**Comment by himanish-star** [comment]
@timvandermeij , I have a few doubts. Well I know that we can build pdfJS using ```gulp generic``` and now that when I was going through the `gulpfile.js` I found out that the gulp generic command only compiles from the web/ folder . So does that mean the src/ folder has no role to play here. I am bascially having difficulty in understanding the difference between the two folders src/ and web/. Could you explain just the brief roles of both. That'll help me go deep into my work

**Comment by timvandermeij** [comment]
The `gulp generic` command creates a generic build of PDF.js, both core and viewer. At https://github.com/mozilla/pdf.js/blob/a3b2456c7a33811010961ee111c58554dbc74ffc/gulpfile.js#L593 we make the core bundle and at https://github.com/mozilla/pdf.js/blob/a3b2456c7a33811010961ee111c58554dbc74ffc/gulpfile.js#L594 we make the web bundle.

The difference between `src/` and `web/` is that `src/` contains all files required for the PDF.js library and `web/` only contains all files required for the viewer. Since PDF.js can also run without a viewer, for example in Node.js, in that case one doesn't need the `web/` folder, but only the files in the `src/` folder. So, with just the files in `src/` you have the PDF.js library that can be used in any context and with `web/` you have the viewer that makes use of the library to display the PDF files in the browser.

**Comment by himanish-star** [comment]
@timvandermeij , Thanks for the explanation
