### ISSUE TITLE
how to disable right click on PDF viewer

### ISSUE THREAD

**Issue by VepariSafin** [mozilla/pdf.js#9366]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
- Operating system and its version:
- PDF.js version:
- Is a browser extension:

Steps to reproduce the problem:
1. 
2.

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Snuffleupagus** [comment]
This doesn't appear to be a PDF.js issue, but rather a general JavaScript question; although considering the lack of *any* details it's somewhat difficult to understand what the purpose is here.

That said, using a search engine of your choice (with a simple "disable right click" query) brings up a wealth of useful information, for example: https://stackoverflow.com/questions/737022/how-do-i-disable-right-click-on-my-web-page

Closing, since this doesn't seem relevant to PDF.js and considering the lack of any details.
