### ISSUE TITLE
ppt file can't fully loaded in pdfjs

### ISSUE THREAD

**Issue by jigskpatel** [mozilla/pdf.js#9389]
Configuration:
- Google Chrome : Version 63.0.3239.132 (Official Build) (64-bit)
- Windows 10 x64
- PDF.js version: 1.9.426
- Is a browser extension: No

**Ppt file not able to fully load in pdfjs**

- Display in pdfjs
![pdfjs](https://user-images.githubusercontent.com/11785531/35209442-037d4cbc-ff74-11e7-8428-b039fd298d16.png)

- Display in powerpoint:
![ppt](https://user-images.githubusercontent.com/11785531/35209464-1b87f17c-ff74-11e7-8ec4-a776462df897.png)

- Original ppt:
[14774.pptx](https://github.com/mozilla/pdf.js/files/1651066/14774.pptx)

**Comment by Snuffleupagus** [comment]
Quoting from https://github.com/mozilla/pdf.js#pdfjs:
> PDF.js is a Portable Document Format (PDF) viewer that is built with HTML5.
>
> PDF.js is community-driven and supported by Mozilla Labs. Our goal is to create a general-purpose, web standards-based platform for parsing and rendering PDFs.

Please note that PDF.js only supports `*.pdf` files, and no other formats (e.g. not PowerPoint files).
Furthermore, the screen-shot included above isn't from the default PDF.js viewer, but appears to be a custom viewer that we know nothing about.

Closing as invalid, since there's no information provided to indicate that this is a PDF.js issue.
