### ISSUE TITLE
PDF Edit support【 A urgent question】

### ISSUE THREAD

**Issue by AngryCatherine** [mozilla/pdf.js#9390]
I attempt to apply a pdf handwriting application based on pdf.js. 
By now it could be written on every page, which is actually written on a canvas by adding a canvas in each page rendered by HTML
`<div class="page" id="pdfPage1" data-page-number="1" data-loaded="true" style="width: 733px; height: 1037px;"><canvas id="pdfCanvasPage1" width="733" height="1037" style="position: absolute; top: 0px; cursor: default;"></canvas></div>`

But when I try to print or download the edited pdf, the content in canvas could not display with it. What I got on paper is the old pdf. 
I would take it kindly if you would give me some help to overcome it which is quite significant to me.
Thank you so much!

**Comment by Snuffleupagus** [comment]
As mentioned in https://github.com/mozilla/pdf.js#pdfjs (emphasis mine):
> PDF.js is a Portable Document Format (PDF) ***viewer*** that is built with HTML5.

Please refer to the FAQ as well, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-annotations.

---

> But when I try to print or download the edited pdf, the content in canvas could not display with it. What I got on paper is the old pdf.

As explained above, PDF.js contains no functionality for editing/creating PDF files.
Regarding printing custom content, that is out of scope for PDF.js and you'd have to extend the printing functionality yourself to support this. (The main printing code is here: https://github.com/mozilla/pdf.js/blob/master/web/pdf_print_service.js.)

For future reference, this issue is also missing enough details to be non-actionable; please make sure to provide the details requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) and that you read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) before opening an issue.

Closing as invalid, since this is out-of-scope for the PDF.js library.
