### ISSUE TITLE
Stream Objects inside other objects

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#9400]
In PDF, a stream object is a dictionary followed by a stream:
```
    <<  ...  >>
    stream
    ... binary data ...
    endstream
```
Adobe Acrobat Reader can not read PDF, where a Stream Object is inside another object (i.e. all Stream Objects must be at "level zero", directly referenced by XREF).

Meanwhile, pdf.js can read such PDFs just fine. I.e. PDFs readable by pdf.js is a superset of what Adobe Reader can read. This may encourage PDF creators create corrupted PDF files. Could anybody figure out, what does a spec say, and fix pdf.js or report a bug to Adobe?

I attach two similar PDFs, both can be opened in pdf.js, but just the first one in Adobe Reader.
[stream_xref.pdf](https://github.com/mozilla/pdf.js/files/1659710/stream_xref.pdf)
[stream_inline.pdf](https://github.com/mozilla/pdf.js/files/1659711/stream_inline.pdf)

**Comment by yurydelendik** [comment]
>  Could anybody figure out, what does a spec say, and fix pdf.js or report a bug to Adobe?

The spec can be found at http://www.adobe.com/content/dam/Adobe/en/devnet/acrobat/pdfs/PDF32000_2008.pdf . This issue is missing the analysis of the spec.

**Comment by Snuffleupagus** [comment]
> Meanwhile, pdf.js can read such PDFs just fine.

As can other PDF viewers, such as e.g. PDFium in Google Chrome.

> This may encourage PDF creators create corrupted PDF files.

The reason that PDF.js, and other PDF viewer, were ever forced to recover data from various kinds of corrupt/incomplete PDF files is that this is a practice that was started by Adobe Reader (and other Adobe software).

Over time we've thus been forced to add various fallbacks for corrupt PDF files, and I don't think that we should start removing any such code without *very* good reasons (which I don't think's been provided here), since we could easily end up breaking whole classes of already existing real-world (broken) PDF files.

> or report a bug to Adobe?

If you, after analysing the PDF specification, believe that this is a bug in Adobe software please report that yourself (rather than asking someone to do it for you).

**Comment by photopea** [comment]
ok I am closing it.

**Comment by Snuffleupagus** [comment]
> Could anybody figure out, what does a spec say

Based on e.g. http://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/PDF32000_2008.pdf#page=86, the `Contents` entry of a `Page` dictionary should be either a stream or an array.
In most PDF files, the `Contents` entry simply contains a reference to the "Content Stream". However there doesn't appear, from a cursory reading of the specification, to be explicitly forbidden for an inline stream to be used here.
