### ISSUE TITLE
Trying to get embedded jpg base 64 code (from the images in the pdf itself)

### ISSUE THREAD

**Issue by Ayrtonalec** [mozilla/pdf.js#9403]
I've been busy with this for weeks and I can't get it done, I've been searching everywhere and I'm honestly lost. I could find the new image name the pdf.js give them and their sizes (width and height) but I need to reproduce the picture outside of just the pdf viewer. 

I'm making a application which loads in a pdf design (from a design company) and dynamically adds that specific design into a list with more design from people to choose from. But I can't even start that part since I'm lost on finding jpg data.

If anyone has any idea on how to gather this data I'd really appreciate it!

Kind regards,
Rick

**Comment by Ayrtonalec** [comment]
Still in need of help, haven't managed so far.

Kind regards,
Rick

**Comment by timvandermeij** [comment]
Is https://github.com/mozilla/pdf.js/blob/master/src/display/canvas.js#L2098 perhaps what you're looking for? I think this is called when an image must be drawn on the canvas.

**Comment by timvandermeij** [comment]
Closing since this answered and out-of-scope for PDF.js itself. If the suggestion above does not work, you could try using the `imageLayer` canvas parameter (https://github.com/mozilla/pdf.js/blob/9a115b41dede03b76cc4cd73319d77857a466a43/src/display/canvas.js#L421) or getting the image data from e.g., https://github.com/mozilla/pdf.js/blob/9a115b41dede03b76cc4cd73319d77857a466a43/src/display/canvas.js#L443.

**Comment by infosecliqin** [comment]
> 我已经忙了好几个星期了，但是我做不完，我一直到处搜索，老实说我迷路了。我可以找到pdf.js赋予它们的新图像名称及其大小（宽度和高度），但是我需要在pdf查看器之外复制图片。
> 
> 我正在制作一个应用程序，该应用程序加载了pdf设计（来自设计公司），并动态地将特定设计添加到列表中，供更多人选择。但由于找不到jpg数据，我什至无法开始这一部分。
> 
> 如果有人对如何收集这些数据有任何想法，我将不胜感激！
> 
> 亲切的问候，
> 瑞克

你好，您说的“我可以找到pdf.js赋予它们的新图像名称及其大小（宽度和高度）”，这一步如何实现的呢
