### ISSUE TITLE
Issue opening PDF from Nextcloud (Hidden letters)

### ISSUE THREAD

**Issue by BetaLeaf** [mozilla/pdf.js#9428]
Initially from https://github.com/ONLYOFFICE/onlyoffice-owncloud/issues/151

I have an interesting issue. When I try to open a PDF created with OnlyOffice, there are issues rendering some letters. 

Testing Notes:
  - The first letter of the spreadsheet is always invisible (It's still there as I can search for it)
  - This doesn't happen on merged cells (If first letter of spreadsheet is within a merged cell, it is the next cell over that is affected)
  - The letter that is affected is  affects all cells that contain the same case-sensitive letter. (Doesn't have to be the first letter of the cell)
  - This issue occurs when creating a document from scratch within OnlyOffice and when importing existing documents created from other sources. 
  - This issue is not present when saved as PDF in another document reader and then viewed in Open Office
  - This issue is not present when viewed in another document reader (such as Excel)

## Screenshot
(The letter "S" is invisible)
![image](https://user-images.githubusercontent.com/7028351/35474087-2c601312-0357-11e8-8888-43288aade716.png)

## Links & Downloads
[Nintendo Switch.xlsx](https://github.com/ONLYOFFICE/onlyoffice-owncloud/files/1670256/Nintendo.Switch.xlsx)

The following links will take you to my Nextcloud Server.
Spreadsheet (Edit Mode) https://cloud.betaleaf.net/apps/onlyoffice/6370
Spreadsheet https://cloud.betaleaf.net/s/hC1LsnTTVJBW89W
PDF (OnlyOffice)https://cloud.betaleaf.net/s/bnqExmsytuQQdg0
PDF (Excel)https://cloud.betaleaf.net/s/6hOTNetNJRVHB7I

If prompted to log in, use guest:guest
Don't worry about messing up the spreadsheet, its a copy.

**Comment by THausherr** [comment]
The "S" is cid 0 in the font... that is unusual.

**Comment by Snuffleupagus** [comment]
First of all, please keep in mind that we're not able to provide support for "Nextcloud" since we know nothing about it. Secondly, it's not really clear to me if this is actually a PDF.js issue, or rather an issue with the Nextcloud implementation of the PDF.js library.

> PDF (OnlyOffice)https://cloud.betaleaf.net/s/bnqExmsytuQQdg0
> PDF (Excel)https://cloud.betaleaf.net/s/6hOTNetNJRVHB7I

Both those PDF files open just fine for me in the latest version of PDF.js, which as of this writing is `2.0.310`.
Please test this yourself, using the default viewer available at https://mozilla.github.io/pdf.js/web/viewer.html (using the "Open file" button on the right-hand side of the toolbar to open new files).
Does that work for you?

If not, please ensure that you provide all of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md such that this becomes an actionable PDF.js issue.

*Edit:* I just noticed that you're apparently using PDF.js version `1.4.20` in Nextcloud, which is a now couple of years out date. Please make sure that you're using the *latest* version of PDF.js, see https://github.com/mozilla/pdf.js/releases, since it's possible that this was already fixed.

**Comment by BetaLeaf** [comment]
I made a request to have it updated. Thanks.
