### ISSUE TITLE
Document that pdfjs-dist is a "nightly" build

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#9440]
https://github.com/mozilla/pdfjs-dist and https://www.npmjs.com/package/pdfjs-dist does not clearly show that the release is a continuous build. The documentation, sourced from https://github.com/mozilla/pdf.js/blob/a7c35025fed8beb8f9b93688fff40497c7ad2de0/external/dist/README.md should probably be changed to make this more clear. And https://mozilla.github.io/pdf.js/getting_started/ does not clearly state that pdfjs-dist is not the stable release build.

Here is an example of confusion that was caused by this: https://github.com/mozilla/pdf.js/pull/9385#issuecomment-363030784

**Comment by brendandahl** [comment]
Or we could send npm releases instead.

**Comment by wojtekmaj** [comment]
npm releases, please! I'd use `next` tag for all the beta ones and no tag for stable releases. Pretty much industry standard at the moment.

**Comment by brendandahl** [comment]
I did some work on this over in https://github.com/mozilla/botio-files-pdfjs/pull/22.

One thing I'm not sure how to handle is fixing our current npm setup. I'm thinking I'll retag the 2.0 branch as `next` and publish an older 1.0 version as stable until we release. This may lead to some weirdness for anyone who's already pulled a 2.0 release from npm though. Open to suggestions!

**Comment by wojtekmaj** [comment]
Can't answer for the whole community but in my opinion, the change is very much worth this one-time commotion.

**Comment by wojtekmaj** [comment]
Oh yeah. We can just tag non-final releases with `next` instead of `latest` starting with official 2.0. So:

1. `^1.x.xxx` users will still to be on newest 1.x pre-release released - no change
2. `^2.x.xxx` users will receive final stable 2.0 and will stop receiving pre-releases
3. `latest` users will receive final stable 2.0 and will stop receiving pre-releases

So that's pretty sweet IMO.

We could also give people from point 1 stuck on 1.x pre-release a hint using [npm deprecate](https://docs.npmjs.com/cli/deprecate) by deprecating all 1.x pre-releases with a message like "You're likely unknowingly using unstable PDF.js release. Please downgrade to the newest stable version, 1.9.xxx or upgrade to all-new 2.x version. Upgrade guide here: http://example.com/pdfjsupgradeguide".

**Comment by timvandermeij** [comment]
The bot change is now merged.

@brendandahl Is there anything else that needs to be done for this issue, other than perhaps a bot restart/webhook?

**Comment by prohtex** [comment]
It seems like this is done

**Comment by timvandermeij** [comment]
Yes, the `pdfjs-dist` repository is not changed after every commit anymore. I'm just not sure if the release process was working correctly. @brendandahl Didn't you have some issues with that while creating the pre-release?

**Comment by banyan** [comment]
@timvandermeij 

do you have any plan when will you release for 2.0? is there any remaining issues regarding 2.0?  https://github.com/mozilla/pdf.js/projects/5

**Comment by prohtex** [comment]
@banyan You can use it now:
https://github.com/mozilla/pdf.js/releases/tag/2.0.550

**Comment by wojtekmaj** [comment]
@prohtex, it's clearly marked as a pre-release.

**Comment by prohtex** [comment]
@wojtekmaj Didn't say it wasn't a pre-release. I was told it would be more or less functionally the same as release. Given that is very difficult to find this link, I thought I'd share it.

**Comment by timvandermeij** [comment]
Closing since this is done.
