### ISSUE TITLE
Upstream the changes from bug 1431533

### ISSUE THREAD

**Issue by rvandermeulen** [mozilla/pdf.js#9441]
Bug 1431533 part 5a (https://hg.mozilla.org/mozilla-central/rev/e6a7b5e11ba8) included a mass rewrite changing all instances of Components.utils.import to ChromeUtils.import. We should upstream those too.

**Comment by Snuffleupagus** [comment]
Thanks for the pointer; however this was taken care of in commit https://github.com/mozilla/pdf.js/commit/4db49b6613401a336f68098656e56e1fca442895, which was included in PR #9433.

**Comment by rvandermeulen** [comment]
Looks like there's a bit of a whitespace issue in PdfJs.jsm, though.
https://github.com/mozilla/pdf.js/commit/4db49b6613401a336f68098656e56e1fca442895#diff-fac62551eadfe79f141900988b8e8a8dL52

**Comment by Snuffleupagus** [comment]
> Looks like there's a bit of an indentation issue in PdfJs.jsm, though.

Whoops, I was mostly using ESLint to automatically apply the changes and forgot to manually re-indent that; sorry if this caused you unnecessary merge conflicts!
Unless you need this fixed right away, I'll just address it when upstreaming the changes from https://bugzilla.mozilla.org/show_bug.cgi?id=1432992 since that one looks pretty close to landing.

**Comment by rvandermeulen** [comment]
I think it's fine to wait. I just dropped that hunk from the update I did
today.
