### ISSUE TITLE
Issues with patch that removed `disableWorker`

### ISSUE THREAD

**Issue by tonyjin** [mozilla/pdf.js#9443]
Thanks for all the great work!

I'm running into a slight issue with my particular setup. The recent patch to remove `PDFJS.disableWorker` (https://github.com/mozilla/pdf.js/commit/56a8c934dde6cce806b1d74fa80c181eb30bbb96) updated one of the checks for a fake worker to use

```
 if (typeof Worker !== 'undefined' && !isWorkerDisabled &&
          !getMainThreadWorkerMessageHandler()) {
```

I prefetch the worker file while users are not on a page that requires PDF preview, and when they do come to a document preview, I point the workerSrc to that same file that I prefetched earlier. Because of browser caching, the worker can be loaded from the cache. With this patch, `getMainThreadWorkerMessageHandler()` will return a handler because I prefetched the worker file at an earlier time and then this block returns false and goes into `_setupFakeWorker()`. Can this last handler check be entirely removed?

On a related, but slightly different note, would you folks be open to a PR that swaps these two in https://github.com/mozilla/pdf.js/blob/7fbeeebbffe68787117aade4b3c00c4728aac81c/src/display/api.js#L1204?

```
if (typeof workerSrc !== 'undefined') {
      return workerSrc;
}
if (getDefaultSetting('workerSrc')) {
     return getDefaultSetting('workerSrc');
}
```

The library I build can sometimes be run in an application that uses RequireJS (in which `workerSrc` will be set to requirejs.url(...something)). I'd explicitly like to keep using the workerSrc I define using PDFJS.workerSrc = 'someUrl'.

**Comment by Snuffleupagus** [comment]
> Can this last handler check be entirely removed?

If what you're suggesting is to completely remove line https://github.com/mozilla/pdf.js/blob/6b7e2cbcd1fbfd68c17f92178ce47df7f6665c31/src/display/api.js#L1336
then that would make it totally impossible, rather than the intended *difficult*, for users to disable workers.
This would also imply that it's no longer possible to simulate the functionality of the (now removed) `pdf.combined.js` file, by manually loading `pdf.worker.js` into the main-thread.

Please note that, as part of the [upcoming version `2.0`](https://github.com/mozilla/pdf.js/projects/5) of PDF.js, we wanted to make it more difficult (but not impossible) to disable workers. Keep in mind that using PDF.js without workers will result in worse performance.
Unfortunately, since the `pdf.combined.js` file appeared to be somewhat popular in practice we still wanted a way to support use-case; hence why this code was re-factored in PR #9385.

> I prefetch the worker file while users are not on a page that requires PDF preview, and when they do come to a document preview, I point the workerSrc to that same file that I prefetched earlier.

In that case, why don't you simply use `workerPort` instead to load the worker file?
https://github.com/mozilla/pdf.js/blob/6b7e2cbcd1fbfd68c17f92178ce47df7f6665c31/src/display/global.js#L141-L144

**Comment by tonyjin** [comment]
Ah perfect, let me try `workerSrc`, looks like what I need :)

**Comment by Snuffleupagus** [comment]
> Do you foresee any issue with swapping the order of:

That seems somewhat orthogonal to the rest of the issue, but I suppose that would be OK.
