### ISSUE TITLE
Unable to get PDFJS global object

### ISSUE THREAD

**Issue by sushovan07** [mozilla/pdf.js#9471]
Hello All,
I guess I am facing issue while accessing PDFJS global object. From alert I have added I can see upto altert 3 I am getting , following alert is not showing up. Please help to resolve this issue. Code is attached for your reference.

I was trying to test this by simply converting that .txt extension to .html and was opening that .html in web browser. Is there any setup required at my browser level or if I run this from server is there any installation required. Please help to provide the guidelines or steps to follow.

Regards
SB

[helloworld64.txt](https://github.com/mozilla/pdf.js/files/1714700/helloworld64.txt)

**Comment by sushovan07** [comment]
Hi All,
Further info, I was trying to test this by simply converting that .txt extension to .html and was opening that .html in web browser

**Comment by Snuffleupagus** [comment]
With PDF.js version `2.0`, the global `PDFJS` object has been removed. Hence this issue, as filed, is no longer valid.

Also, when reporting an issue with a custom deployment of PDF.js, as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, you need to provide access to a complete (and runnable) example since just code snippets aren't helpful.
