### ISSUE TITLE
Windows path changes drive letter...

### ISSUE THREAD

**Issue by tracker1** [mozilla/pdf.js#9482]
## Configuration:
- Web browser and its version: Node 8.9.x
- Operating system and its version: Windows Server 2012
- PDF.js version: pdfjs-dist@^2.0.269
- Is a browser extension: No

## Steps to reproduce the problem:

1. Working directory on `E:\`
2. `await PDF.getDocument("C:\\Windows\\TEMP\\b6f1c1cd-f811-4b84-8116-5adfe4bd973b")`

## What is the expected behavior? (add screenshot)

Loads the PDF document.

## What went wrong?

Note: drive letter is now E:\
```
ENOENT: no such file or directory, lstat 'E:\\Windows\\TEMP\\b6f1c1cd-f811-4b84-8116-5adfe4bd973b'
```

## Notes

I don''t know if this is corrected with `pdfjs-dist@2.0.374` which seems to have been published today.

I was able to work around the issue by encoding to a `file://` url.  But wanted to submit the problem upstream.

```
// work around drive change issue with windows on the server... C:\ became E:/
if (process.platform === 'win32' && /^[a-z]\:/i.test(filePath)) {
  filePath = `file:///${filePath
    .split(/[\\\/]+/g)
    .map(encodeURIComponent)
    .join('/')}`;
}
```

**Comment by Rob--W** [comment]
This is because #9020 was fixed by #9323 in an incorrect way.
That patch fixed the issue by trimming the leading `/` from the path. The proper fix is to detect whether the input looks like a Windows path (i.e. by checking whether the URL matches `/^[a-z]:[/\\]/i` ) and if so, prepend `file:///`. Note that I'm specifically testing with a slash after the name in case someone wants to use a file name with a colon inside.

**Comment by pardeepshokeen** [comment]
hi @Rob--W .  I want to work on this issue. Can i take this?

**Comment by Rob--W** [comment]
@pardeepshokeen Sure.
