### ISSUE TITLE
built in pdf viewer not working in chrome

### ISSUE THREAD

**Issue by pranjal0891** [mozilla/pdf.js#9512]
Please help , As I want to open pdf in chrome. 
I tried to download in built pdf from chrome web store. But I am getting error like Connection error with the json parser process.

Please consider on priority, I have attached screenshot

Configuration:
- Web browser and its version: chrome vs 63
- Operating system and its version:  windows 8
- PDF.js version:   
- Is a browser extension: https://chrome.google.com/webstore/detail/pdf-viewer/oemmndcbldboiebfnladdacbdfmadadm?hl=en

![screenshot 18](https://user-images.githubusercontent.com/36857522/36683460-a0fcf89e-1b43-11e8-8555-32beda495308.png)
![screenshot 19](https://user-images.githubusercontent.com/36857522/36683476-adb077e6-1b43-11e8-8000-b38c33744fe5.png)

What is the expected behavior? (add screenshot)

What went wrong? (add screenshot)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):

**Comment by Rob--W** [comment]
This is not a problem of our PDF.js extension, but a bug in Chrome. You are probably unable to install any Chrome extension at the moment.

Try restarting the browser and retry the installation.

And note that the latest version of Chrome is 64, not 63. Perhaps Chrome updated itself in the background, and somehow you ended up with a partially working browser.

I'm closing this bug since there is not anything that PDF.js can do.
