### ISSUE TITLE
Backward compatibility broken from 2.0.402 -> 2.0.419

### ISSUE THREAD

**Issue by chirag64** [mozilla/pdf.js#9525]
~~Attach (recommended) or Link to PDF file here:~~

__Configuration:__
- ~~Web browser and its version: N/A~~
- ~~Operating system and its version: N/A~~
- PDF.js version: 2.0.419
- ~~Is a browser extension: No~~

__Steps to reproduce the problem:__
1. Try running the code mentioned in an older version of the example docs:
`// The workerSrc property shall be specified.`
`PDFJS.workerSrc = '//mozilla.github.io/pdf.js/build/pdf.worker.js';`

__What is the expected behavior? (add screenshot)__
PDF should load with the new version of the library.

__What went wrong? (add screenshot)__
PDF does not load. Instead, we get a console error that says `PDFJS is not defined`. Backward compatibility is broken on a minor version upgrade.

~~Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):~~

**Comment by timothyjensen** [comment]
Thanks for reporting this. I am experiencing the same console error as explained above. When I load version 2.0.402 instead the console error disappears.

**Comment by amrbedair** [comment]
same here!

**Comment by Snuffleupagus** [comment]
> [...] Backward compatibility is broken on a minor version upgrade.

That's not really accurate here, since there was a *major* version increase previously (from `1.x.y` to `2.x.y`), which should suggest that backwards incompatible changes were made.
Please refer to e.g. https://github.com/mozilla/pdf.js/pull/9385#issuecomment-363102565 and https://github.com/mozilla/pdf.js/pull/9385#issuecomment-363064779 for additional details.

The first official release from the `2.0` branch will happen any day now, and is tracked in issue #9521 and https://github.com/mozilla/pdf.js/projects/5, which contains a fair number of backwards incompatible changes.

Closing as answered/invalid.
