### ISSUE TITLE
Can not fit page width after full screen display

### ISSUE THREAD

**Issue by tenglongwentian** [mozilla/pdf.js#9538]
Can not fit page width after full screen display？

**Comment by Paarmita** [comment]
@tenglongwentian Can I work on this issue?

**Comment by Snuffleupagus** [comment]
> Can not fit page width after full screen display？

There isn't (currently) anywhere near enough information provided in this issue to understand what's actually being asked/reported here!
Please make sure that you read [CONTRIBUTING.md](https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md) when opening a new issue, and that you provide *all* of the information requested in [ISSUE_TEMPLATE.md](https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md)

However please note that zooming is purposely disabled in Presentation Mode, see e.g. issue #5336 and PR #5413, so if that's what this issue is asking for it'll be closed as WONTFIX.
