### ISSUE TITLE
Have an alias (e.g. PDFJS or PDFJS2) instead of window['pdfjs-dist/build/pdf'] or window.pdfjsDistBuildPdf

### ISSUE THREAD

**Issue by Rob--W** [mozilla/pdf.js#9545]
#9493 removed the `PDFJS` global, so now the only way to access the PDF.js library from a browser in a non-module context (i.e. not AMD or CommonJS) is through `window['pdfjs-dist/build/pdf']` or `window.pdfjsDistBuildPdf`.

This is an unfriendly name, and seemingly just an artefact of the implementation. Can we use a global such as `PDFJS`, or if you wish, `PDFJS2`?

The name originates from here:
https://github.com/mozilla/pdf.js/blob/6662985a20b769d7e78e7cf4486eb6b7130f0cf0/gulpfile.js#L228-L235
https://github.com/mozilla/pdf.js/blob/6662985a20b769d7e78e7cf4486eb6b7130f0cf0/gulpfile.js#L241-L253

The `window['pdfjs-dist/build/pdf']` export is done by Webpack, and can probably be configured by replacing the `library` string with an object, and set `root` to the desired name.

The `window.pdfjsDistBuildPdf` export is generated by our custom `replaceJSRootName` function. An alternative to reconfiguring Webpack is to add an extra parameter to the `replaceJSRootName` function, so that the caller defines `jsName` instead of auto-generating it.

I would personally be in favor of configuring Webpack to use the custom name, because I cannot imagine anyone wanting to use `window['pdfjs-dist/build/pdf']` to import the JS variable.

Relevant Webpack documentation for configuring the `library`:
- https://webpack.js.org/configuration/output/#output-library
  (The documentation does not have any explicit information for configuring the UMD target, so I digged in the source and found the following)
- https://github.com/webpack/webpack/blob/41bb63ad69d0f32c042e74e732cb045b5966c452/schemas/WebpackOptions.json#L484-L516 - the schema that the configuration needs to adhere to.
- https://github.com/webpack/webpack/blob/41bb63ad69d0f32c042e74e732cb045b5966c452/test/configCases/library/umd/webpack.config.js (example)

**Comment by Rob--W** [comment]
@Snuffleupagus @yurydelendik @timvandermeij Opinions?

**Comment by timvandermeij** [comment]
I agree that the current way of accessing PDF.js is not that user-friendly. I think something like `pdfjsLib` might work. Using `PDFJS` may cause confusion with the previous global `PDFJS` variable.

**Comment by Snuffleupagus** [comment]
Since https://github.com/mozilla/pdf.js/issues/9545#issue-304065602 only mentions `window.pdfjsDistBuildPdf`, please keep in mind that there's actually *three* different files to consider here!

To avoid an inconsistent state (which IMHO would be worse than the current state), the following would *all* need to be addressed if any changes are deemed necessary here:
 - The built `pdf.js` file, where we're currently using `window.pdfjsDistBuildPdf`.
 As suggested in https://github.com/mozilla/pdf.js/issues/9545#issuecomment-372035169, `pdfjsLib` could probably be a reasonable name instead.[1]

 - The built `pdf.worker.js` file, where we're currently using `window.pdfjsDistBuildPdfWorker` (assuming of course that the worker was loaded in the main thread; despite that being a bad idea).
 In line with the suggestion above, we could perhaps use the name `pdfjsWorker` instead.

 - The built `pdf_viewer.js` file, i.e. the viewer components obtained with `gulp components`, where we're currently using `window.pdfjsDistWebPdfViewer`.
 In line with the other suggestions, we could perhaps use the name `pdfjsViewer` instead.
  
> When this is implemented, the examples need to be updated accordingly.

In addition to the examples, note that there's code in https://github.com/mozilla/pdf.js/tree/master/test that would need to be updated as well.

---
[1] Especially since that name is already being used in the default viewer, see https://github.com/mozilla/pdf.js/blob/master/web/pdfjs.js

**Comment by Rob--W** [comment]
> Since https://github.com/mozilla/pdf.js/issues/9545#issue-304065602 only mentions `window.pdfjsDistBuildPdf`, please keep in mind that there's actually *three* different files to consider here!

Those can be found by searching for the callers of `replaceJSRootName` in gulpfile.js. The `createBundle` function is responsible for the main and worker script. The main script is the one that I care most about, since it is the primary entry point. The worker script is merely an implementation detail of PDF.js, so the exact name is not that important. The `createComponentsBundle` target creates the viewer components that you were referring to.

> By using a new name instead (e.g. pdfjsLib and others), it ought to be (relatively) simple for custom implementers to detect if a pre/post-2.0 version of the PDF.js library is being used.

There is a `PDFJS.version` (replace `PDFJS` with the actual exported object name) for this purpose.

The main argument against using `PDFJS` as the export name is backwards-compatibility. While settings like `PDFJS.workerSrc` have been moved, the core API, `PDFJS.getDocument` is still working (just like the example at the examples page). Therefore I think that we should restore the `PDFJS` global.

If someone upgrades from a PDF.js 1.x project to PDF.js 2.x, and their customization breaks, then they should be able to figure out that their API usage is incorrect, regardless of the exported object name.
To make that easier, we could add a migration guide from PDF.js 1.x to 2.x to the documentation.

Given these arguments, are you still in favor of `pdfjsLib` over `PDFJS`?

**Comment by Snuffleupagus** [comment]
> The worker script is merely an implementation detail of PDF.js, so the exact name is not that important.

As stated in https://github.com/mozilla/pdf.js/issues/9545#issuecomment-372042523, I think that there's something to be said for using *consistent* names throughout. However, I'll concede that the *worker* part isn't nearly as important as the global names used in the built `pdf.js` and `pdf_viewer.js` files.

> While settings like PDFJS.workerSrc have been moved, the core API, PDFJS.getDocument is still working

Given all the changes that were made, `PDFJS.getDocument` is among the few things that would actually work as before. As you've already mentioned above, none of the options (previously on `PDFJS`) will work now and they would thus be silently ignored. (To me it seems better to fail early, rather than having users wonder why all their settings are now being ignored.)

> Therefore I think that we should restore the PDFJS global.

Besides the re-factored options, there's also been a number of changes (mostly deletions) to the functions/properties that are being exported. Hence the shape of the `pdfjsDistBuildPdf` (or whatever we end up calling it) object differs quite a bit from the old `PDFJS` object.

> Given these arguments, are you still in favor of pdfjsLib over PDFJS?

Yes; since you asked for opinions in https://github.com/mozilla/pdf.js/issues/9545#issuecomment-372024830, I've simply stated *my* position here :-)

**Comment by brendandahl** [comment]
I'm leaning towards keeping PDFJS and letting the version number be the indication of change. If we change the name this time it seems like we should change it every major release, which I'd rather not do.

**Comment by yurydelendik** [comment]
`pdfjsDistBuildPdf` name was a workaround (that's why I started using something like pdfjs-dist/dist/pdf), we can start using PDFJS instead of pdfjsDistBuildPdf

**Comment by brendandahl** [comment]
I missed that we have three export like things now. In light of that, I'm in favor of Jonas' suggestions of pdfjsLib, pdfjsViewer, pdfjsWorker.

**Comment by timvandermeij** [comment]
Closing since this is fixed by #9565.
