### ISSUE TITLE
Connect programmatically Anotations with their position in the document text

### ISSUE THREAD

**Issue by MarioBatusic** [mozilla/pdf.js#9559]
Configuration:
- Web browser and its version: ALL
- Operating system and its version: ALL

Steps to reproduce the problem:
1. For screen reader bookmark links are empty and their texts (unlinked) is to find at an undefined and incorellated location in the document stream.

What is the expected behavior?

Bookmarks and all other annotations are currently implemented as pure overlays according to absolute page positions. This way the screen reader users get only empty links and the corelated link / annotation texts are positioned at a deliberate spot in the document stream thus loosin any meaning.

The solution shoul be similar to the "Comments" and "Footnotes" in MS Word, which are accessible to the screen reader users.

**Comment by timvandermeij** [comment]
I'm not really sure if this is possible. The annotations are being positioned like this because they are truly separate entities in the PDF file format, so they are not inline with the test in any way and can be placed anywhere on a page. Could you clarify how this can be improved given these constraints? I'm not familiar with how Word works (as I'm not using it and I'm also not a screen reader user).

**Comment by MarioBatusic** [comment]
Hi Tim,

I am really no expert for the complicated PDF Format. Maybe can somebody help, that knows it in detail. It is of course possible, that this accessibility requirement is technically not solvable at the current moment, but I hope this is not so.
Thanks anyway for your basic interrest for accessibility agenda.

**Comment by Snuffleupagus** [comment]
https://github.com/mozilla/pdf.js/issues/9559#issuecomment-373184494 describes the situation quite well; closing since there's generally no way in which this can be solved?
