### ISSUE TITLE
Strange colors in PDF

### ISSUE THREAD

**Issue by photopea** [mozilla/pdf.js#9599]
I have this PDF (below), which contains the "triangle" at the bottom part, filled with a Gradient between light blue and dark blue (it is the only gradient in the whole PDF).

The gradient function is FunctionType 3  between
/C0: [1, 0.02745099924504757]
/C1: [0.49411800503730774, 0.03137259930372238]

Color Space info says, that this is ["/Cyan", "/Yellow"], and the color-space function (of FunctionType 4) converts them to  CMYK  [0.49411797523498535, 0, 0.03137260675430298, 0]  and CMYK  [1, 0, 0.027450978755950928, 0]

But these CMYK values correspond to more "Cyan" colors, like this: https://imgur.com/zCtVtth . So why pdf.js renders it as much "bluer" blue?  https://imgur.com/5duPx6j  Should there be any other color processing, that I am missing?

[WEBSITE-ZLONIN-uprava.pdf](https://github.com/mozilla/pdf.js/files/1840752/WEBSITE-ZLONIN-uprava.pdf)

**Comment by Snuffleupagus** [comment]
The is how Adobe Reader renders the file:
![adobe](https://user-images.githubusercontent.com/2692120/37843994-be36741c-2ec6-11e8-9508-3c48ef1c892e.png)

This is how PDF.js, version `2.0.451` (the latest as of this writing), renders the file:
![pdfjs](https://user-images.githubusercontent.com/2692120/37844034-d3896586-2ec6-11e8-807a-6c259101135f.png)

---

At least to my eye, there's nothing really separating Adobe Reader and PDF.js here; hence it's not really clear what (if anything) is the problem here!?

Furthermore, most of the information requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md is missing. Also, if this is a problem with a custom implementation of PDF.js you'll need to provide access to a working example the demonstrates the problem; as described in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md.

**Comment by photopea** [comment]
I didn't expect you to use the output of Adobe Reader as a proof of correctness.

I think the information from Issue Template is not relevant in this case. I am trying to learn the PDF format and I am curious why it works as it worsk. I would like to find somebody, who could tell me, how the colors (in pdf.js or in Adobe Reader) were achieved. According to my understanding of the specifications, the colors should be different.

**Comment by brendandahl** [comment]
The web doesn't really support CMYK so it is converted to RGB using https://github.com/mozilla/pdf.js/blob/24f766b14d84b6776c1b3b6952b097bd8f865a5d/src/core/colorspace.js#L668

**Comment by photopea** [comment]
Oh, ok, that was it. My error was just in the CMYK to RGB conversion.

I expected the simple conversion R=1-C;  G=1-M;  B=1-Y;   But your transformation matrix gives the corresponding result. Thanks!
