### ISSUE TITLE
Chrome extension fails to render properly attachment file name in encoded utf-8

### ISSUE THREAD

**Issue by eugene-rozov** [mozilla/pdf.js#9616]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version:
Chrome 65.0.3325.181
- Operating system and its version:
OSX 10.13.3
- PDF.js version:
2.0.466
- Is a browser extension:
Chrome extension

Steps to reproduce the problem:
1. Make server return properly encoded file name in a header. For example, use this value for header `Content-Disposition=attachment; filename="test-a-test.pdf"; filename*=UTF-8''test-%C3%A4-%D1%82%D0%B5%D1%81%D1%82.pdf`
2. Open the file in a browser tab.

What is the expected behavior?
File name should be properly decoded and showed correctly in browser tab header or after file has been download using 'Download' button. For example from above, file name in the browser tab should be "test-ä-тест.pdf".

What went wrong?
File name is wrongly decoded:
![image](https://user-images.githubusercontent.com/4630127/38156072-0ec2b108-3484-11e8-9195-b80201fb4c2d.png)
![image](https://user-images.githubusercontent.com/4630127/38156140-804e02e6-3484-11e8-86bd-f182520ef346.png)

But if file is saved from the chrome incognito tab (no plugin used), name will be decoded properly
![image](https://user-images.githubusercontent.com/4630127/38156187-db06b872-3484-11e8-9a00-1fed35ac0650.png)

**Comment by Snuffleupagus** [comment]
> `Content-Disposition=attachment; filename="test-a-test.pdf"; filename*=UTF-8''test-%C3%A4-%D1%82%D0%B5%D1%81%D1%82.pdf`

@Rob--W Since you implemented the Content-Disposition parser used in PDF.js, is this issue something that can be easily fixed? And if so, should that perhaps happen upstream in https://github.com/Rob--W/open-in-browser/blob/master/extension/content-disposition.js first?

**Comment by Rob--W** [comment]
The upstream library works fine. I made some mistakes at converting the library, but fixed them in #9773 . Please check and merge it @Snuffleupagus

**Comment by Snuffleupagus** [comment]
> The upstream library works fine. I made some mistakes at converting the library, but fixed them in #9773

Thank you; great that this was so easy to fix!

Slightly off-topic here, but would it make sense to try and reduce the differences between https://github.com/mozilla/pdf.js/blob/master/src/display/content_disposition.js and upstream, to make updates easier?
For example, it seems that https://github.com/mozilla/pdf.js/blob/5053d02ba446e3c491bfd0e62633f7db46fb385c/src/display/content_disposition.js#L21-L22 aren't strictly necessary, since it should be possible to just add the necessary [core-js](https://github.com/zloirock/core-js) polyfills in [src/shared/compatibility.js](https://github.com/mozilla/pdf.js/blob/master/src/shared/compatibility.js) instead.

> Please check and merge it @Snuffleupagus

Well I'm no longer actively involved in the PDF.js project, hence I don't have commit access anymore.[1]
Anyway that PR is already merged, so we should be good here :-)

---
[1] Please note that no one revoked, or even asked me to give up, my commit access. However, personnally, it didn't seem necessary/correct to still have commit access when I'm no longer actively involved in the project.
