### ISSUE TITLE
contents display incorrectly.

### ISSUE THREAD

**Issue by ntanh005** [mozilla/pdf.js#9627]
https://github.com/ntanh005/ntanhGit1990/blob/master/untitled.pdf
Configuration:
- Web browser and its version: IE 11
- Window 10
- PDF.js version: newest
- Is a browser extension: No

Steps to reproduce the problem:
1.  open the pdf file attached above

What is the expected behavior? (add screenshot)
- The text **"helvetica 14 Point"** is positioned correctly.

What went wrong? (add screenshot)
- The text **"helvetica 14 Point"** is positioned incorrectly.

**Comment by timvandermeij** [comment]
The text in green is mirrored and in the wrong position. Moreover, it misses the black pattern in PDF.js.

**Comment by Snuffleupagus** [comment]
Fixed by PR #13361

**Comment by THausherr** [comment]
The original file is fixed, but not the cinnebar file (hard to see), gs-bugzilla690297.pdf and pattyp2.pdf from my own comment. I can of course open a separate issue but I believe it's all related.

**Comment by Snuffleupagus** [comment]
> The original file is fixed, but not the cinnebar file (hard to see), gs-bugzilla690297.pdf and pattyp2.pdf from my own comment. I can of course open a separate issue but I believe it's all related.

Please note that as mentioned in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md, there should only be *one* issue reported by bug since otherwise tracking can become a bit of a nightmare :-)

It's always possible to close issues as duplicates of each other, if that turns out to actually be the case, but have (subtly) different bugs reported in the same issue means that it could in the general case become impossible to ever close some issues (e.g. if users kept adding new files to an old issue).

**Comment by timvandermeij** [comment]
Closing this one; please open a new issue if there is still a problem with a file so we can track that separately. Thanks!
