### ISSUE TITLE
web/secondary_toolbar.js loops over every event property value, triggering sync reflow

### ISSUE THREAD

**Issue by gijsk** [mozilla/pdf.js#9654]
https://github.com/mozilla/pdf.js/blob/593dec1bb7aec1802abf8268137b0f7adab2ae32/web/secondary_toolbar.js#L146-L149

This evaluates every property of the event. As noted in https://gist.github.com/paulirish/5d52fb081b3570c81e3a , some of these (notably the ones associated with the position of mouse events, but in Gecko also e.g. `rangeOffset`) will cause synchronous flushes. This causes jank. Off-hand, I doubt that the stuff on the other side of the `eventBus` really needs every single property of the event. It would be better to pass either the original event, or a proxy, or just pass a specific subset of the event properties that the consumer actually needs.

**Comment by Snuffleupagus** [comment]
> This evaluates every property of the event.

*I know that you're a very experienced Firefox developer, but I nonetheless have to ask:*

Was this issue filed based on actual profiling results, or just code inspection?
The reason that I'm asking, is that the code in question shouldn't be accessing the event properties; see https://github.com/mozilla/pdf.js/blob/593dec1bb7aec1802abf8268137b0f7adab2ae32/web/secondary_toolbar.js#L144-L155

Unless I'm completely misunderstanding how arrow functions work, given that the event handling function is an arrow function `this` ought to refer to surrounding scope here rather than the event itself; i.e. `this instanceof SecondaryToolbar` here (and placing a breakpoint in this code confirms that).

Furthermore, `eventDetails` isn't related to the event either but rather defined just above; see https://github.com/mozilla/pdf.js/blob/593dec1bb7aec1802abf8268137b0f7adab2ae32/web/secondary_toolbar.js#L142
Note that `eventDetails` will either be `undefined`, or a simple object; see e.g. https://github.com/mozilla/pdf.js/blob/593dec1bb7aec1802abf8268137b0f7adab2ae32/web/secondary_toolbar.js#L75-L80

> Off-hand, I doubt that the stuff on the other side of the eventBus really needs every single property of the event.

Both looking at this code, and then testing it with the Firefox Devtools, it doesn't actually seem to access any of the event properties!?

> [...] or just pass a specific subset of the event properties that the consumer actually needs.

That should already be happening here, based on the above.

---

However, assuming that there's a real problem here, I suppose that there's maybe one possible explanation for why it's happening. The `SecondaryToolbar` instance does, by necessity, hold references to a couple of DOM elements. Could accessing the `SecondaryToolbar` instance during the `eventBus.dispatch` call be what's actually triggering these synchronous reflows here?

If that's the case, then that will require changes to a fair amount of other code in the `web/` folder, since this pattern is used elsewhere as well.
In theory, the `source` property used on the `eventBus` could probably be changed to e.g. a `sourceName` parameter (containing just the class name instead).
However that would end up breaking, since it relies on access to properties on the `source` object, this code https://github.com/mozilla/pdf.js/blob/c5c06bf5c42707355de325ae5a9e24757e8f86dc/web/dom_events.js#L18-L20
That code exists, in no small part, to support the `mozilla-central` specific PDF.js tests https://searchfox.org/mozilla-central/source/browser/extensions/pdfjs/test, are relying on those events.
Fixing all of this doesn't strike me as *too* difficult[1], assuming previous experience with this code, but will probably need to happen in stages. (I.e. fixing the `mozilla-central` tests first, and then changing the `source` usage and remove `attachDOMEventsToEventBus`). 

PS. In any case, I don't think the "5-good-beginner-bug" tag is appropriate here.

---
[1] Based on previous experience with the PDF.js codebase, since I'm no longer contributing myself.

**Comment by gijsk** [comment]
> Was this issue filed based on actual profiling results, or just code inspection?
> The reason that I'm asking, is that the code in question shouldn't be accessing the event properties; see 

You're absolutely right - the issue was filed based on code inspection, and I just misread the code (having audited literally all the non-test JS in mozilla-central that mentioned 'ev' or 'event' in a for loop, I must have been tired and misread this bit). Sorry for the wasted work!

For background, I ran into this type of loop in https://bugzilla.mozilla.org/show_bug.cgi?id=1371523 because the sync reflows were accidentally keeping tests green, so when I got rid of them the test went orange ( https://treeherder.mozilla.org/#/jobs?repo=try&revision=43d9b194b4148693ac40856d43566fe29f032567 ), so I tried to audit for other places where we did this... anyway. Clearly I misread this particular snippet of code. Thanks for flagging it up!
