### ISSUE TITLE
Scroll to the exact text location in PDF viewer through the API

### ISSUE THREAD

**Issue by maxime-c2c** [mozilla/pdf.js#9657]
Hello,

First of all, thanks for your precious time while reading this help inquiry ;-)
And thanks a lot for your great work around PDF.js.

Basically, I want to pass through the API the text to search via an other application (no manual text typing) and the expected behavior would be the same as manual searching, that is, highlight the text and make the viewer automatically scroll to the exact position of the text.

When exploring the API, I don't find a way to make indeed the viewer scroll to the exact location.
Any clue? I am a bit lost...

Your advises would be really much appreciated.

Again, thank you!
Best regards, Maxime

**Comment by timvandermeij** [comment]
I don't think the API provides a way to do exactly that, but you could replicate what the find bar does to achieve that, which works by putting events (such as "find" or "highlight all") on the event bus so that the find controller can perform that task. For example, check https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_bar.js#L93 and https://github.com/mozilla/pdf.js/blob/master/web/pdf_find_bar.js#L74.

**Comment by AkshatTR** [comment]
is there any update on this in 2025?

**Comment by digiajay** [comment]
Is there update on this, we are providing a signing service and we can't search for text but need to go to position which user selects in the given page.

**Comment by nicolo-ribaudo** [comment]
You can copy this function, which accepts as parameters:
- an element
- an offset (top/left) within that element

and scrolls to it

https://github.com/mozilla/pdf.js/blob/729f2bb1489b629a54c3d65a7d988a5d7f2f2e4d/web/ui_utils.js#L92
