### ISSUE TITLE
Background images not displayed in page margin boxes

### ISSUE THREAD

**Issue by LukasKlement** [mozilla/pdf.js#9665]
Attach (recommended) or Link to PDF file here: https://assets.menutech.com/food_menu.pdf

**Configuration:**
- Web browser and its version: Firefox Quantum 59.0.2 (64-Bit)
- Operating system and its version: Mac OS X 10.13.3
- PDF.js version: browser in-built
- Is a browser extension: no

**Steps to reproduce the problem:**
1. Load example PDF: https://assets.menutech.com/food_menu.pdf
2. Page margin background image is not displayed

**What is the expected behavior?**
Downloading the PDF and opening it with Adobe Reader correctly shows the background image in the @top-center page margin box. -> PDF.js should also display background images in the page margin boxes.

**Other information:**
Weasyprint was used to generate the PDF (github.com/Kozea/WeasyPrint). The CSS code to add the background image is as follows:

```
@page {
    @top-center {
        content: '';
        display: block;
        width: 100%;
        height: 30mm;
        background-image: <LOGO URL>;
        background-repeat: no-repeat;
        background-size: contain;
        background-position: 50% 50%;
        border-bottom: #fff solid 10mm;
    }
}
```

**Comment by timvandermeij** [comment]
This may be somewhat related to #5539.

**Comment by aahancoc** [comment]
I'm having a similar issue, using Weasyprint 0.42 and Firefox 61 (the latest versions of each program) using very similar CSS. This also seems to appear on the Chrome WebExtension. 
[Here's my PDF.](https://github.com/mozilla/pdf.js/files/2303265/alcohol.pdf)


I've found that the background images don't disappear, but instead they shift up by about half an inch or so. This happens if the source image is an SVG or a PNG. This renders fine on Chrome, Acrobat, and SumatraPDF.
