### ISSUE TITLE
ghost text isn't filtered out by getTextContent()

### ISSUE THREAD

**Issue by gravsten** [mozilla/pdf.js#9666]
Some PDFs have ghost (transparent, or white on white ?) text that needs to be filtered out, for example on page 5 of the following:
http://www.sta.be.ch/sta/fr/index/staatskanzlei/staatskanzlei/downloads_publikationen/amtsblatt.assetref/dam/documents/STA/Amtsblatt/fr/2018/FOJB_15-2018.pdf

If you search in this PDF for `saf@hep-` you will find this invisible text located behind other (normal) text.
Hence the result of getTextContent() has become unreliable with **visible and invisible texts mangled together**.

There is currently no parameter for getTextContent() that would let it filter out this invisible text.
But I would be happy to contribute if I can **understand what in the text's state makes it invisible ?**

I have already hacked pdf.worker.js to track fillColor changes, but even this invisible text exhibits a black color ([0, 0, 0]) so this ain't the reason.

**Comment by Snuffleupagus** [comment]
This is a bug in the PDF file *itself*, rather than in the PDF.js library and as such it cannot be fixed.[1] Please note that the same behaviour can be observed in other PDF viewers as well, see e.g. Adobe Reader and PDFium (in Google Chrome).

---
[1] Furthermore, even attempting to fix this could very easily risk breaking text-selection/searching in PDF files that contain images and purposely "invisible" OCR text.
