### ISSUE TITLE
PDF does render with wrong encoding with hosted pdf.js

### ISSUE THREAD

**Issue by jzillmann** [mozilla/pdf.js#9692]
Attach (recommended) or Link to PDF file here:
https://github.com/jzillmann/pdf-to-markdown/files/1940855/sample_success.pdf
https://github.com/jzillmann/pdf-to-markdown/files/1940859/sample_fail.pdf

Configuration:
- Web browser and its version: Chrome-65.0.3325.181/Safari-11.1
- Operating system and its version: OSX
- PDF.js version: 1.7.246 & 1.10.97 & 2.0.489
- Is a browser extension: No, but custom usage of pdfjs-dist

I'm using pdfjs-dist in my custom webpage to render both of the linked pdfs.
While sample_success.pdf is rendering nicely, sample_fail.pdf is not.

What is the expected behavior? (add screenshot)
![success](https://user-images.githubusercontent.com/7592695/39166159-d13dbe5a-47ba-11e8-9f95-b6c4aab298e8.png)

What went wrong? (add screenshot)
![fail](https://user-images.githubusercontent.com/7592695/39166197-0e2583de-47bb-11e8-8157-b390df22f424.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
http://pdf2md.morethan.io/

The sample_fail.pdf does render successful in Mozillas demo viewer.

I tried 3 different version of pdfjs-dist version (from 1.7.246 to 2.0.489).
I enabled cmaps (version is not online) but the pdfs isn't making a request for cmaps (pdfs from your tests folder did make successful cmap requests.

I pretty closely followed the examples like https://github.com/mozilla/pdf.js/blob/master/examples/components/simpleviewer.js except i don't use the viewer.

Important code pieces look like:
```
import pdfjs from 'pdfjs-dist'; 
pdfjs.GlobalWorkerOptions.workerSrc = 'bundle.worker.js';
...
reader.onload = (evt) => {
    const fileBuffer = evt.target.result;
        uploadFunction(new Uint8Array(fileBuffer));
    };
reader.readAsArrayBuffer(files[0]);
...
pdfjs.getDocument({
            data: fileBuffer,
            cMapUrl: 'cmaps/',
            cMapPacked: true
        }).then(
```
So i would be grateful for any hints into what i can look else!

**Comment by Snuffleupagus** [comment]
Please keep in mind that in the PDF specification, there's two different algorithms used for rendering respectively text-selection/copying/searching.
For the latter to work as expected, the PDF file itself need to include correct (and complete) `ToUnicode` data for each font being used. 

> https://github.com/jzillmann/pdf-to-markdown/files/1940859/sample_fail.pdf

In this PDF file, one of the fonts doesn't provide correct `ToUnicode` data, and it's thus impossible for text-extraction to work correctly[1]. Try opening that file with a few different PDF viewers, e.g. Adobe Reader, PDFium (in Google Chrome), and PDF.js (using https://mozilla.github.io/pdf.js/web/viewer.html), and you'll notice that in every single one text-selection/copying returns gibberish.

Based on https://github.com/jzillmann/pdf-to-markdown/blob/2869b5e5de89abd68f83f744c78fe959f2ac6e56/src/javascript/components/LoadingView.jsx#L123 you're not actually "rendering" the PDF file, but rather output the result of `getTextContent`.
Since its output. as explained above, is susceptible to errors in the `ToUnicode` data of the fonts used in individual PDF files, that should thus explain why things aren't working as you'd expect.

Unfortunately, this isn't something that can be fixed (short of re-creating the PDF file with the necessary font data included).

---
[1] Short of rendering the file, and attempting to use OCR software on it; this is *obviously* out of scope for the PDF.js project.

**Comment by jzillmann** [comment]
Hey @Snuffleupagus , thanks for elaborate answer!

**Comment by RaphiStein** [comment]
Make sure that pdf-worker is getting loaded properly.
If you are minifying, run a test using `pdf-worker.js` and not `pf-worker.min.js` to ensure there is no error in the minification.
