### ISSUE TITLE
Image interpolation incorrect

### ISSUE THREAD

**Issue by THausherr** [mozilla/pdf.js#9713]
[image_via_1.3_001.pdf](https://github.com/mozilla/pdf.js/files/1991319/image_via_1.3_001.pdf)
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: Microsoft Edge 42.17134.1.0 and FF 60.0
- Operating system and its version: W10, 10.0.17134.1 and also on W7 6.1.7601
- PDF.js version: https://mozilla.github.io/pdf.js/web/viewer.html

Steps to reproduce the problem:
1. start https://mozilla.github.io/pdf.js/web/viewer.html
2. open file

What is the expected behavior? (add screenshot)

![clipboard01](https://user-images.githubusercontent.com/6665575/39866295-68460d4c-5450-11e8-98d5-d172d072b1f3.png)

What went wrong? (add screenshot)

![clipboard02](https://user-images.githubusercontent.com/6665575/39866309-6dd8edf6-5450-11e8-8257-9a8c0f16bce2.png)

/Im0 is the lower Image and has /Interpolate true but this isn't done.

File is from
https://storage.googleapis.com/google-code-archive-source/v2/code.google.com/lumi-read/source-archive.zip
and can be found in lumi-read/trunk/PDF_smoketest/pdf/image_via/image_via_1.3_001.pdf

There are more incorrect renderings but I suspect these are related.

**Comment by dholbert** [comment]
Two notes:
(1) this bug does still seem to exist; I can still reproduce this in current Firefox Nightly (version 94.0a1 (2021-09-07)) with the built-in PDF viewer.
(2) there's a suspicion that this is the root cause of https://bugzilla.mozilla.org/show_bug.cgi?id=1722191 , which is about a French-government COVID-status QR Code (in a PDF) incorrectly displaying and printing in a blurry fashion (presumably making the QR code a lot less useful/scannable).

Given that association, it would be great to see this fixed if it's not too much trouble.

**Comment by Snuffleupagus** [comment]
> Given that association, it would be great to see this fixed if it's not too much trouble.

Unfortunately it's probably not that simple, since an attempt was previously made (see PR #8338) which couldn't land since it regressed *way more* things than it actually fixed.
