### ISSUE TITLE
Extremely slow rendering in Edge

### ISSUE THREAD

**Issue by iberezansky** [mozilla/pdf.js#9718]
Attach (recommended) or Link to PDF file here:
http://wp.iberezansky.net/wp-content/uploads/custom/SMC-2017-catalogue.pdf

Configuration:
- Web browser and its version:  Edge x64 20.10240.17146.0
- Operating system and its version: Windows 10 Pro x64 
- PDF.js version: 2.0.493
- Is a browser extension: no

Steps to reproduce the problem:
1. Clear the browser cache.
2. Open http://wp.iberezansky.net/?page_id=60

What is the expected behavior? (add screenshot)
After disappearing the progress it takes ~5 sec for IE11, Firefox and Chrome to finish rendering.

What went wrong? (add screenshot)
After disappearing the progress it takes >30 sec for Edge to finish rendering.

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
Open http://wp.iberezansky.net/?page_id=60

See PDFJS object in the debug console for information.

**Comment by Snuffleupagus** [comment]
> Attach (recommended) or Link to PDF file here:
> http://wp.iberezansky.net/wp-content/uploads/custom/SMC-2017-catalogue.pdf

The file is no longer available (hence why it's recommended to attach it rather than linking).
However given that this is apparently limited to just *one* browser, in this case Edge, that points to the specific browser being the culprit rather than the PDF.js library. In such cases, there's usually nothing that can be done *here*, so I'd suggest simply closing the issue.
