### ISSUE TITLE
Information related to encryption used in PDF JS

### ISSUE THREAD

**Issue by manojpersonal** [mozilla/pdf.js#9727]
Hi,

We are planning to use PDF.JS in our product and currently evaluating it for our requirements.

In the same process we are currently evaluating the Encryption algorithms used in PDF.JS. Specifically the code in this file: https://github.com/mozilla/pdf.js/blob/master/src/core/crypto.js
It appears that the AES cipher and other algorithms are indeed being implement by the software. 

We would like to understand why these are used in the software PDF.JS

**Comment by timvandermeij** [comment]
Those algorithms are implemented because they are used in the PDF specification for protecting PDF documents from unauthorized viewing. Refer to https://www.adobe.com/content/dam/acom/en/devnet/acrobat/pdfs/pdf_reference_1-7.pdf#page=115&zoom=auto,-247,483 for more information. In order to open encrypted PDF files, the user is prompted to enter the password for decryption.
