### ISSUE TITLE
attachments are not opening on single click in pdfviewer, I am supposed to double click

### ISSUE THREAD

**Issue by bljd369** [mozilla/pdf.js#9755]
Hi,

We use pdfjs viewer to display the pdfs and in those pdfs we have some more pdfs in the form of attachments, somehow when we click on them, nothing is happening, they are getting downloaded only on double click, however our intention is like to make them open on single click rather than double clicking on it. Is there any way to do that please.

Thanks,
Balaji.

**Comment by timvandermeij** [comment]
The code indicates that downloading attachments works with single click. It also works for me for example at https://tcpdf.org/examples/example_041. Hence it must be some custom configuration that is causing issues. Since no more details/example PDF files are provided, I'm closing this as it seems to work just fine.
