### ISSUE TITLE
WebExtension cannot access document rendered by pdf.js (since Firefox 60)

### ISSUE THREAD

**Issue by mdnsk** [mozilla/pdf.js#9765]
Hello!

I have a firefox add-on for text translation ( https://addons.mozilla.org/en-US/firefox/addon/leo-translate/ ) and it perfectly worked with pdf.js until Firefox 60.
Since Firefox 60 the add-on cannot access pdf documents rendered by pdf.js
Is there any solutions of this problem? Should I add any permission in manifest.json to allow the extension to be injected into page rendered by pdf.js?

Thank you!

**Comment by Snuffleupagus** [comment]
The ability for extension scripts to be injected into the built-in Firefox PDF viewer may have been purposely broken, most likely for security reasons, in https://bugzilla.mozilla.org/show_bug.cgi?id=1436482 (which unfortunately isn't publicly accessible).

Since this is a browser limitation, the issue is unfortunately invalid from the point of view of the PDF.js project. For future reference these kind of bug reports, regarding Firefox addons, should probably be filed here instead: https://bugzilla.mozilla.org/enter_bug.cgi?product=Toolkit&component=WebExtensions:%20Untriaged.
