### ISSUE TITLE
Loading speed issues in large page rendering.....

### ISSUE THREAD

**Issue by youlook** [mozilla/pdf.js#9766]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: IE 11
- Operating system and its version: windows 7
- PDF.js version: 1.9.426
- Is a browser extension:

Steps to reproduce the problem:
One.
  > When the pdf file has more than 700 pages, I want to render the initial 2 pages first.
2.

What is the expected behavior? (add screenshot)

What went wrong? 

 > Currently, only the first page is rendered first. If you go to page 2, you have to wait until all the pages are rendered. We currently have 10 minutes to wait.

**i want...

 > I want to render from page 1 to page 2 first. Is there a way?**

**Comment by timvandermeij** [comment]
You most likely did not enable range request (properly) on the server, because if that's configured properly then it's not necessary to wait for all pages to render. Check https://mozilla.github.io/pdf.js/web/viewer.html for example where only the first few pages are loaded until you scroll further. Since no PDF file is provided, I'm closing this as answered.
