### ISSUE TITLE
pdfjs-dist is outdated

### ISSUE THREAD

**Issue by SavePointSam** [mozilla/pdf.js#9780]
There was recently an update to this repo that added support for webpack 4. However, that update has yet to land in pdfjs-dist. I believe that pushing an update would resolve https://github.com/wojtekmaj/react-pdf/issues/179.

The last update pushed was on April 11, 2018.

**Comment by timvandermeij** [comment]
I think that `pdfjs-dist` is not updated anymore because of https://github.com/mozilla/pdf.js/issues/9440#issuecomment-363625331. People complained about the fact that we updated it on every merge (so it was basically a nightly release) and we should be updating it on every release only according to NPM standards.

**Comment by timvandermeij** [comment]
Closing since we're tracking this in that issue instead.
