### ISSUE TITLE
Can we have a simple example without system.js?

### ISSUE THREAD

**Issue by aidanlister** [mozilla/pdf.js#9784]
Is there not enough PDF.JS to learn without trying to work out the System.JS stuff?

```
// In production, the bundled pdf.js shall be used instead of SystemJS.
Promise.all([System.import('pdfjs/display/api'),
             System.import('pdfjs/display/worker_options'),
             System.import('pdfjs/display/network'),
             System.resolve('pdfjs/worker_loader')])
       .then(function (modules) {
  var api = modules[0];
  var GlobalWorkerOptions = modules[1].GlobalWorkerOptions;
  var network = modules[2];
```

**Comment by Snuffleupagus** [comment]
Maybe it'd make sense to simply remove https://github.com/mozilla/pdf.js/tree/master/examples/helloworld, and update all the relevant links to point to https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld.html instead?
Especially since the example is using PDF.js without building it first, which (as far as I know) isn't officially supported and thus probably shouldn't be advertised in this kind of highly visible way.

Similarly, https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer probably ought to be updated as well. Or it might be better to just replace it with a (much simpler) [components based](https://github.com/mozilla/pdf.js/tree/master/examples/components) `svgviewer` example?

@timvandermeij What do you think?

**Comment by timvandermeij** [comment]
Yes, I think reconsidering the examples is a good idea here.

**Comment by Bluejanis** [comment]
I wish there were some examples on how to use pdfjs with systemjs.
