### ISSUE TITLE
Detect when web fonts are blocked via browser extention

### ISSUE THREAD

**Issue by websirnik** [mozilla/pdf.js#9798]
Steps to reproduce the problem:
1. Download browser extension that allows web font blocking, e.g. Ublock Origin. [Chrome](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm?hl=en)  [Firefox](https://addons.mozilla.org/en-US/firefox/addon/ublock-origin/)
2. Enable setting to block web fonts
3. Open demo page https://mozilla.github.io/pdf.js/web/viewer.html (v.2.0.571) and see that fonts are rendered poorly:
<img width="1552" alt="screen shot 2018-06-11 at 17 57 18" src="https://user-images.githubusercontent.com/282871/41245837-145c1ea0-6da1-11e8-97b2-6b4d2eda91e4.png">

For the demo, `window.PDFViewerApplication.supportsDocumentFonts` returns `true`, I would expect it to be `false` in this case.

**Comment by Snuffleupagus** [comment]
> For the demo, window.PDFViewerApplication.supportsDocumentFonts returns true, I would expect it to be false in this case.

That property exists (solely) for supporting the PDF.js version that's shipping in Firefox (it's always `true` in other builds), please see https://searchfox.org/mozilla-central/rev/e6a0a192ea8691f7eb466506301da73fabe8fd23/browser/extensions/pdfjs/content/PdfStreamConverter.jsm#323-327

> Open demo page https://mozilla.github.io/pdf.js/web/viewer.html (v.2.0.571) and see that fonts are rendered poorly:

Since this is essentially just a (regular) web-page, how would it detect that fonts aren't being loaded (and without using really ugly/non-performant hacks)?

**Comment by Snuffleupagus** [comment]
As already mentioned in https://github.com/mozilla/pdf.js/issues/9798#issuecomment-396352900, attempting to in *general* detect that fonts are blocked might not always be feasible and even trying to would slow down loading of *every* document opened with the default viewer, which really does *not* seem acceptable in general.

Furthermore PR #10539 might be somewhat relevant here as well, since it implemented a fallback for fonts that fail to load when the Font Loading API is being used.
All in all, it seems like closing this issue as WONTFIX would be appropriate here.
