### ISSUE TITLE
Question regarding reading PDF from local filesystem

### ISSUE THREAD

**Issue by brunodelgado1988** [mozilla/pdf.js#9806]
Hey guys, how are you?

I'm generating an offline version of a webpage that includes some PDF's rendered by PDF.js. But when I load a PDF offline, I get a Network Error. At my research, I read that it's not possible to read the bytes from a PDF that is in the filesystem of the users for security reasons.

Are there any possible way of rendering a local pdf file, without the need of the user select it from an input? When I try to read local I receive the following error in the image.

Configuration:
- PDF.js version: 2.0.489
- Is a browser extension: No

Steps to reproduce the problem:
1. Create a local html file with the pdfjs scripts;
2. Create a local pdf file in the same folder than the HTML;
3. PDFjs.getDocument('file:///local/path/to/file.pdf');

What went wrong? (add screenshot)
![screenshot from 2018-06-12 15-16-23](https://user-images.githubusercontent.com/2372140/41295955-b2c36c30-6e53-11e8-96c7-80d4b1560a45.png)

**Comment by timvandermeij** [comment]
The browser limits requests for the `file://` protocol, so I don't think you can use that without the user inputting the file. What you could try is read the PDF file using another non-JavaScript language and feeding the fetched data into the `getDocument` API (since it supports direct data input too, aside from a URL). For example, you could fetch the PDF data with PHP and load the data with PDF.js in JavaScript. Since this is out of scope for PDF.js, I'm closing this.

**Comment by brunodelgado1988** [comment]
Thanks for your explanation. 

In fact I'm trying to do exactly this, but I wanted a confirmation that I can't load a pdf directly from user's filesystem in an offline context.
