### ISSUE TITLE
#9208 better GUI naming for scrolling and spread

### ISSUE THREAD

**Issue by Djfe** [mozilla/pdf.js#9813]
Hi,
I'm currently translating strings from #9208 to German and I have a suggestion to rearrange those gui items to make them intuitive.

**Let's look at how Libre Office handle's it:**
- Single-page view (=vertical scrolling)
![soffice bin_2018-06-14_01-39-16](https://user-images.githubusercontent.com/5685512/41384011-d8f50f00-6f73-11e8-8c24-d42342200cbc.png)

- Multiple-page view (=wrapped scrolling)
![soffice bin_2018-06-14_01-40-48](https://user-images.githubusercontent.com/5685512/41384049-fba3ad18-6f73-11e8-8571-bca606dda4b0.png)

- Book view (=vertical scrolling + even spread) -> you could in addition remove the margin between those pages, that would look a bit better IMO for stuff like this: https://i.pinimg.com/736x/bc/24/cd/bc24cd3842dc94e3d632a4d9213692ab--farming-spreads.jpg
![soffice bin_2018-06-14_01-42-55](https://user-images.githubusercontent.com/5685512/41384109-472e91ee-6f74-11e8-9941-41239c466288.png)

- Edge and Adobe have an Option for even spread:
![Edge](https://i.imgur.com/nkQihTY.png)
![Adobe](https://i.stack.imgur.com/SK0TC.png)

We could make ***book view*** default to odd spread (unlike Libre Office) and add a second option ***Show cover page separately*** for even spread.

**Map (old scheme -> new scheme):**
Vertical scrolling + no spread -> Single-page view
Vertical scrolling + odd spread -> Book view
Vertical scrolling + even spread -> Book view + "Show cover page separately"
Horizontal scrolling + any spread -> (currently makes no difference)
Wrapped scrolling + no spread -> Multiple-page view
Wrapped scrolling + odd spread -> (dunno, it would only make a difference, if we remove the margin between two adjacent pages)
Wrapped scrolling + odd spread -> Multiple-page view + "Show cover page separately" (in-case this is useful)

___

- I also have another idea for horizontal scrolling that would need actual changes in the code (not just a map):
**Fill up the vertical height**
![firefox_2018-06-14_02-09-53](https://user-images.githubusercontent.com/5685512/41384775-0c8beace-6f78-11e8-8dc2-2e30f063c6a4.png)

**new scheme for the context menu:**
Single-page view
Multiple-page view
Book view
(separator)
"Show cover page separately"
Vertical scrolling
Horizontal scrolling

**Map:**
Horizontal scrolling + Single-page view -> align pages vertically (center); one row
Horizontal scrolling + Multiple-page view -> fill up vertical space: multiple rows (count order: first rows, second columns; as shown in the image)

EDIT: This way (if look at the pages like a matrix) the horizontal scrolling matrix would be a transpose of the vertical scrolling matrix.

EDIT2:

I forgot about *Horizontal Scrolling + Book view*
Either you display them below each other (weird)
or you display them next to each other and remove the margin between them and then display the next couple to the right of it

*Show cover page separately* could be hidden, if *Single-page view* is selected.

EDIT3:
*Two-page view* would be another possible name for *Book view*

EDIT4:
*Multiple-page view* could zoom outwards to display 3 or 4 elements next to each other. (in-case the user hasn't zoomed out further already)
This would better indicate to the user, what multiple actually does.

**Comment by rhendric** [comment]
I welcome this conversation! Although we did go back and forth on a few different options for the menu items, I'm not quite as confident as I think @prohtex is that we've arrived at the optimal design. Of course, there may not be one optimal design for everyone, in which case we should go with a good enough design and stop debating. Perhaps we're already there, but I don't think we know enough to say that for sure yet.

Let me start by saying that I think there are two related but separable questions to be discussed: the first is how many menu buttons (or other widgets) should there be and what should they do, and the second is how should they be labeled and iconed. While I think the second can provide good feedback to the first (in that if we propose a button that can't be labeled in a graceful way, it may not be a good button), I do think we should separate them and discuss them in that order, since if the functionality is good, people can get used to new names for things.

### How many menu buttons (or other widgets) should there be and what should they do?

For clarity of conversation, I'm going to use the terms that were accepted in #9208 when discussing this question to describe the functionality of buttons. For example, maybe we will decide ‘book view’ is a better term than ‘spreads’ for people who aren't in publishing, but for now, I'm going to continue to refer to a button that joins two pages together as a ‘spreads’ button. To keep the conversation clear, I hope that others will do the same. However, if someone proposes a button with slightly different functionality and wants to call that functionality ‘book view’, that would be fine.

To recap where we are, there are currently two three-state toggles:
* **scrolling mode**: how ‘units’ (pages or spreads) are laid out in the viewer
* **spread mode**: which pairs of pages, if any, should be joined as a single unit

All nine combinations of these two variables potentially have value, even though the three of them corresponding to horizontal scrolling currently look identical. (There is a proposal to follow up #9208 with refinements to reduce or remove the intraspread margin, which would make the spread mode in horizontal scrolling relevant.) In particular, I think you may have missed that with wrapped scrolling, spread mode can be very important. See my (long, sorry) visual tour at the top of #9208, or the images in [#9208 (comment)](/mozilla/pdf.js/pull/9208#issuecomment-359894630)—choosing the correct spread mode is what prevents spreads from being split across rows. I don't think your proposal takes that into account.

If I may modify your proposal to include the wrapped+spreads cases, I would describe it as four two-state toggles, one of which is disabled in some states. The four toggles are (in the existing terminology):
* **scrolling mode**: vertical or horizontal
* **wrapping**: no or yes
* **spreads**: no or yes
* **start spreads on even pages**: no or yes, disabled if spreads = no

This yields 12 cases: the original nine plus three more corresponding to your new idea for horizontal scrolling and vertical wrapping.

I'm skeptical about that new idea. Would that mode—reading pages top to bottom, then left to right—ever be useful to you personally? If not, do you have any reason to think that it would be useful to someone else? You called this out in ‘EDIT2’, but I'll re-ask and elaborate: how should it interact with spreads? If spreads continue to be joined horizontally, the order of pages would now be:
```
1 2 5 6
3 4 7 8
```
or
```
 1  4 5
2 3 6 7
```
Is that good?

If spreads in horizontal scrolling + wrapping mode transpose to be joined vertically, that would be a special case, since spreads in horizontal scrolling mode without wrapping would presumably be joined horizontally as they are now. It would also not correspond to the way pages are physically bound in what I assume are the overwhelming majority of cases.

Or perhaps you would propose that spreads be disabled when horizontal mode and wrapping are enabled, in which case the toggles now become:
* **scrolling mode**: vertical or horizontal
* **wrapping**: no or yes
* **spreads**: no or yes, disabled if horizontal and wrapping = yes
* **start spreads on even pages**: no or yes, disabled if spreads = no

and there are ten cases: the original nine plus one new case for horizontal scrolling and vertical wrapping. It's also a little awkward to have a button disabled only when multiple conditions are met—it becomes a puzzle to understand how the buttons interact with each other.

If you come around to thinking that the new case isn't all that useful to anybody, then representing the original nine cases with these four toggles becomes:
* **scrolling mode**: vertical or horizontal
* **wrapping**: no or yes, disabled if horizontal
* **spreads**: no or yes
* **start spreads on even pages**: no or yes, disabled if spreads = no

It's easy to see that this is just a cosmetic redesign of the original two three-state toggles.

### How should they be labeled and iconed?

Many words on this have already been said in #9208, so I'll just share my thoughts on some of the comments made here and there:

> Multiple-page view (=wrapped scrolling)

This is basically short for ‘multiple pages on a row’, right? Spreads are a different way to achieve that, which is why I think ‘wrapped’ is a more specific (and therefore better) term than ‘multiple-page’.

If there's a word I'd change here, it would be ‘scrolling’. Maybe something like ‘Vertical Layout’, ‘Horizontal Layout’, and ‘Horizontal Layout With Breaks’ would translate better?

> Book view (=vertical scrolling + even spread)

I wouldn't mind replacing ‘Odd Spreads’ with ‘Book View’ and ‘Even Spreads’ with ‘Book View With Cover’. I'm not sure what ‘No Spreads’ would be called in that case, if there is such a button. (‘No Book View’? ‘Book View Off’? Ick.) If we replace the three spread buttons with two buttons that can be active or inactive, one called ‘Book View’ and the other called something like ‘Show Cover Page Separately’, that could work for me. The downside to that would be that everything else in that menu is a button to activate what the button describes—there aren't yet any items that can be toggled off by clicking on them, so that UX would have to be designed and distinguished from the other menu items. (I tried a variation on this by not having a ‘No Spreads’ button, only ‘Odd Spreads’ and ‘Even Spreads’ and clicking on the currently active button turned it off, and maintainers decided that having an off button was better.)

> "Show cover page separately"

Note that this doesn't quite describe what ‘Even Spreads’ does, although perhaps it does describe what some users might want it to do. To me, ‘Show Cover Page Separately’ would imply that the cover page gets its own row, as in some of @prohtex's mockups. Currently, if wrapped scrolling is on and the zoom is small enough/viewport is wide enough, if even spreads are enabled, the first spread (pages 2 and 3) can end up on the same row as page 1. (This logically follows from the definitions of scrolling and spread modes, if wrapped scrolling means layout units horizontally until they don't fit, and even spreads means that the first page is its own unit and the next two pages are a unit! Changing this behavior would mean using different, and probably a little more complicated, definitions.) It's a separate debate whether this is a bug or a feature (I happen to think it's a feature, since to me, the point of wrapping is to maximize the value of screen space, and covers are usually visually distinctive enough that they don't need further emphasis by putting them on their own row), but keep in mind that this label would nudge that debate in a particular direction.

Also, in some documents I've seen (comic book scans is the example that comes to mind), some full spreads are actually merged in the PDF as a single, double-wide page. Because of that, while reading through the book, you may want to toggle between even spreads and odd spreads a few times. In that case, I think telling the viewer to start page spreads on even-numbered or odd-numbered pages is a more direct expression of what you want then telling the viewer to show the cover page separately or not—you may have long passed the cover page, but no matter where you are in the document you can see what page number you're currently on and whether or not you would like that page to be the first page in a spread.

> *Show cover page separately* could be hidden, if *Single-page view* is selected.

Disabled, maybe. I would strongly oppose hiding a button when it isn't obvious how to show it again.

> *Multiple-page view* could zoom outwards to display 3 or 4 elements next to each other. (in-case the user hasn't zoomed out further already)

I would also be opposed to messing with the user's zoom setting when changing other view modes. Also, in documents with varying page sizes, figuring out how far out you'd need to zoom to ‘show off’ the new mode is non-trivial.

From https://github.com/mozilla/pdf.js/pull/9208#issuecomment-397152628:
> In german when you talk about even or odd, people tend to think:
Ah, ok the number of pages is even or odd

This is a problem in English as well. I consider ‘Odd Spreads’ and ‘Even Spreads’ an uneasy compromise between succinctness and clarity, which perhaps leans a little too far towards succinctness. The hover text and icons both mitigate the concern for me enough to be okay with it, so I think if the same is true in German, that's not much of a problem. But better labels may exist in either language that have not yet been proposed and shot down. (Better icons may exist as well—I used Arabic numerals in the current icons, which are probably recognizable in most locales but definitely won't feel native in some.)

**Comment by prohtex** [comment]
For me, this discussion raises an important point: there's no way to use "book view" or "spread lock" or whatever you prefer to call it, without continuous scrolling. There's no way to look at a spread and advance to the next spread without scrolling. Fullscreen mode does not support spreads, and the thumbnail pane still shows one page at a time, meaning the user must click "next" twice to advance to the next spread.
Hope to see some of these issues addressed going forward. Thanks again to everyone who made developing and implementing these features possible!!

**Comment by Snuffleupagus** [comment]
Let's close this as WONTFIX for now, since I don't believe that there's any plans to make changes to this part of the UI at this time. (Also, please note that any changes here would require input from the Firefox UX team first.)
