### ISSUE TITLE
[Question] 'pdfjs-dist' repo not updated anymore?

### ISSUE THREAD

**Issue by MichaelDeBoey** [mozilla/pdf.js#9814]
I've noticed that the `pdfjs-dist` repo is currently on [`v2.0.489`](https://github.com/mozilla/pdfjs-dist/blob/master/package.json#L3), while there's already `v2.0.550`

**Comment by timvandermeij** [comment]
For version 2.0 we're no longer updating `pdfjs-dist` after every commit (refer to #9440). The reason is that in that case it's in a sense a "nightly build" and can be unstable, but anything on NPM without flags like `@next` should be considered stable. Instead, we're now only going to update `pdfjs-dist` for every formal release, and that is tracked in #9440 too.
