### ISSUE TITLE
Along with disableAutoFetch option as true, is it possible to increase the number of pages loaded in the DOM?

### ISSUE THREAD

**Issue by Srinithi-23** [mozilla/pdf.js#9825]
I use pdfjs-dist as an npm package version 1.7.331 in an ember app.

I wanted to send byte range requests on demand. So I made _disableAutofetch_ and _disableStream_ to true. Now on load, only first two pages are in the DOM. But while scrolling the pdf, there seems to some delay in rendering the pages and the scrolling is not smooth.

So is there anyway to increase the default no. of pages pre-loaded in DOM with _disableAutofetch_ and _disableStream_ as true so that delay in rendering will become lower and scrolling will be smooth?

**Comment by Snuffleupagus** [comment]
> I use pdfjs-dist as an npm package version 1.7.331 in an ember app.

That version first of all doesn't correspond to any [official release](https://github.com/mozilla/pdf.js/releases), and second of all it's also quite out-of-date.

> But while scrolling the pdf, there seems to some delay in rendering the pages

That's hardly surprising, given that the point of `disableAutoFetch = true` is to attempt to delay loading of as much of the PDF file as possible until the data in question is actually needed. Hence rendering becomes network bound, rather than just affected by the speed of the computer.

> So is there anyway to increase the default no. of pages pre-loaded in DOM with disableAutofetch and disableStream as true so that delay in rendering will become lower and scrolling will be smooth?

You could try modifying https://github.com/mozilla/pdf.js/blob/3b07147d98e376a774316288647d421b80b589c1/web/pdf_rendering_queue.js#L96 to pre-render more than just one page (as it's currently doing).
However, please keep in mind that doing so will increase both CPU and memory usage. Furthermore by requesting more data than strictly necessary upfront, such a change *could* also end up making `disableAutoFetch = true` more or less redundant. (Keep in mind that, with the exception on "linearized" files, it's generally not possible to load *only* the data for a specific page.)
