### ISSUE TITLE
Does it make sense to "web-optimize" the pdf file?

### ISSUE THREAD

**Issue by dimitrove** [mozilla/pdf.js#9833]
This is about version 1.9.426. I have a server supporting "range requests".
I see
- one request loading the whole file (response code 200)
- one request for a range in the beginning (response code 206)
- one request for a range in the end (response code 206)

The rendering on the screen starts after the whole file is loaded.
I am wondering - does it make any difference for PDF.js is the file "web-optimized" or not? Especially when the server supports "range requests"?

**Comment by brendandahl** [comment]
You'd probably want to run some tests to verify performance (if you do, let us know I'd be curious to see results). It's still generally good to web optimize, since it will reduce image DPI's and put all the pages and their needed data close together within the file which is good for range requests too.

**Comment by timvandermeij** [comment]
Indeed, web optimization should help range requests too. Closing since this is now answered.
