### ISSUE TITLE
Use svg.js will pdf to svg, but out of the Chinese garbled

### ISSUE THREAD

**Issue by xxh950501** [mozilla/pdf.js#9856]
I'm sorry for my bad english, it's not my native language.

![image](https://user-images.githubusercontent.com/24908666/42119925-ec186446-7c44-11e8-8b13-b79e8b578849.png)

This is the code, I hope to help me see why it turns out to be garbled

**Comment by timvandermeij** [comment]
You'll need to provide all information asked for in the issue template (https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md) because we cannot do anything with just code snippets. By reading your description I can only guess you did not include the cMaps that may be needed for rendering Chinese text. Refer to https://github.com/mozilla/pdf.js/blob/master/examples/svgviewer/viewer.js#L56-L64.

**Comment by xxh950501** [comment]
I use the official website example and then convert our own generated pdf, there is also a garbled phenomenon

**Comment by xxh950501** [comment]
@timvandermeij
