### ISSUE TITLE
Is it possible to disable PDFFetchStream?

### ISSUE THREAD

**Issue by robotlovesyou** [mozilla/pdf.js#9863]
As detailed in #9862 we're having issues with range requests when using PDFFetchStream.

I'm wondering if there is a simple way for us to disable it so that all browsers will use PDFNetworkStream instead?

The only ways I can think of to do it are either to recreate our own version of `/lib/pdf.js` with modified `setPDFNetworkStreamFactory` code, or perhaps to create a private fork of pdfjs-dist and simply modify `/lib/pdf.js` in there, both of which seem a bit extreme.

**Comment by Snuffleupagus** [comment]
> I'm wondering if there is a simple way for us to disable it so that all browsers will use PDFNetworkStream instead?

If what you're asking for is a *runtime* flag to disable the use of the Fetch API, then that does *not* seem like a good idea to me.
The reason is that the Fetch API, assuming obviously that it works correctly in the browser, would now be preferred over using `XMLHttpRequest` in general. However, adding a runtime flag to disable the use of the Fetch API could very easily lead to people setting it all the time[1] just because there *may* be issues in some specific configurations, leading to worse overall performance when using the PDF.js library.

Since the problem seem to be limited to a certain browser, the best way forward would probably be if someone was able to come up with a reduced test-case such that a bug report could be filed with the browser vendor.

---
[1] This is probably not just a theoretical concern either, since the situation reminds me of the runtime option to disable workers which was present in PDF.js versions `1.x.y`.
Disabling workers results in worse performance, and is neither properly tested or supported, but nonetheless most third-party PDF.js examples (that I've seen) were recommending to disable workers rather than showing how correctly set-up the library.

**Comment by robotlovesyou** [comment]
Well, it's not for me to tell you what the best way forwards is with the pdf.js API and I can fully appreciate your desire to prevent people naively reducing the performance of the library, but my (perhaps ignorant) understanding is that the main advantage of  fetch vs XHR is that it returns a promise. I'm not aware that it offers any performance benefit. On the other hand, having range requests broken in the most popular browser desktop browser, with no simple way to fix them is quite a concern. For us it means that people on even slightly constrained networks have a really extended wait to view a pdf when using chrome. 

That being said, this issue is 5 months old. I should (and will) re-test chrome as soon I can (some time in the next two weeks) and update. 

Thanks for your response.

**Comment by robotlovesyou** [comment]
Sorry, clicked the wrong button!

**Comment by Snuffleupagus** [comment]
> [...] but my (perhaps ignorant) understanding is that the main advantage of fetch vs XHR is that it returns a promise. I'm not aware that it offers any performance benefit.

For example: Using the Fetch API allows the initial request to continue, whereas ranged loading with `XMLHttpRequest` requires aborting the initial request and then start issuing range requests instead.
Hence using the Fetch API will, generally, result in quicker overall document loading.

---

@timvandermeij As outlined in https://github.com/mozilla/pdf.js/issues/9863#issuecomment-430577828, making this configurable  this doesn't seem like a good idea in general; closing as WONTFIX?
