### ISSUE TITLE
PDF JS does not show files using & in file path

### ISSUE THREAD

**Issue by ctygoer** [mozilla/pdf.js#9867]
Attach (recommended) or Link to PDF file here:

Configuration:
- Web browser and its version: PYQT5 QWebEngineView
- Operating system and its version: Windows 7
- PDF.js version: 
- Is a browser extension: PYQT5 QWebEngineView

Steps to reproduce the problem:
1. "&" character in file path

What is the expected behavior? (add screenshot)
There are two version of the PDF file in different folders. Displaying the PDF works in the one without the "&" character.
![image](https://user-images.githubusercontent.com/40792718/42214473-88788a26-7eb3-11e8-9879-93d9c359c245.png)

What went wrong? (add screenshot)
The message below is shown if the file is located in a folder using the "&" character.
![image](https://user-images.githubusercontent.com/40792718/42214480-901833c6-7eb3-11e8-88c4-87f9df82cbb4.png)

Link to a viewer (if hosted on a site other than mozilla.github.io/pdf.js or as Firefox/Chrome extension):
The code of my viewer is based on the pyqt5 example of the following link.
https://stackoverflow.com/questions/23389001/how-to-render-pdf-using-pdf-js-viewer-in-pyqt

Thanks,

C

**Comment by Snuffleupagus** [comment]
> "&" character in file path

As explained in e.g. https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#file, you'll need to encode the URL (using `encodeURIComponent`) in order for this to work correctly.

If that doesn't fix the problem, then as outlined in https://github.com/mozilla/pdf.js/blob/master/.github/CONTRIBUTING.md you'll need to provide a complete and *runnable* example since only screen-shots and/or code snippets are of limited usefulness.

**Comment by timvandermeij** [comment]
Yes, it's most likely URL encoding that's causing issues here. If not, as outlined above, please provide the requested information to make this issue actionable. Closing for now.

**Comment by ctygoer** [comment]
Thank you very much for the quick response. Your answers have solved the issue.
