### ISSUE TITLE
"Unexpected Server Response" when file doesn't loads up

### ISSUE THREAD

**Issue by PranjalAgni** [mozilla/pdf.js#9908]
We can show up a better error message when the file doesn't loads up, right now the below message pops up.
PDF.js v? (build: ?)
Message: Unexpected server response (204) while retrieving PDF "http://localhost:8888/test/pdfs/annotation-button-widget.pdf".

**Comment by Snuffleupagus** [comment]
> We can show up a better error message when the file doesn't loads up, right now the below message pops up.
> PDF.js v? (build: ?)
> Message: Unexpected server response (204) while retrieving PDF "http://localhost:8888/test/pdfs/annotation-button-widget.pdf".

There doesn't appear to be anything wrong with the existing error message, since it even contains the actual status code of the error. There's a special error thrown for files that are missing, i.e. status code 404, but that doesn't seem relevant in this particular case.

Generally though, since that particular file is available in the PDF.js repository, there shouldn't be any problems accessing it. Similar to issue #9909 the problem is most likely that PDF.js wasn't [setup properly](https://github.com/mozilla/pdf.js#getting-the-code) locally, but given the lack of details this issue is unfortunately not actionable.
