### ISSUE TITLE
Unable to Polyfill Uint8ClampedArray for PDFJS

### ISSUE THREAD

**Issue by owlkaboom** [mozilla/pdf.js#9970]
Browser: IE11 with IE10 compatibility Mode
PDFJS-DIST: 2.0.489

I am just trying to better understand the errors I am receiving from PDF.JS which are printed out below. The PDF "renders" but obviously fails to load any image data. I would upload the PDF but unfortunately I cannot.

The code that is having the issues is SimpleSegmentVisitor_onPageInformation and to me it looks like it can't instantiate a "Uint8ClampedArray" which my first instinct would of been to try and polyfill this using core-js which works well for the rest of my application but for some reason in the pdfjs worker it does not pick up on the polyfill? Is there some kind of special polyfilling that needs to be done for pdfjs?

Errors being logged in the console:
"Warning: Unable to decode image: ReferenceError: 'Uint8ClampedArray' is undefined"
followed by a handful of the error below.
"Warning: getOperatorList - ignoring XObject: "ReferenceError: 'Uint8ClampedArray' is undefined"."

Stacktrace from a breakpoint
"ReferenceError: 'Uint8ClampedArray' is undefined\n   at SimpleSegmentVisitor_onPageInformation (http://localhost:3000/452640e97fef798fa6dd.worker.js:32983:7)\n   at processSegment (http://localhost:3000/452640e97fef798fa6dd.worker.js:32961:7)\n   at processSegments (http://localhost:3000/452640e97fef798fa6dd.worker.js:32966:7)\n   at parseJbig2Chunks (http://localhost:3000/452640e97fef798fa6dd.worker.js:32974:7)\n   at Jbig2Image_parseChunks (http://localhost:3000/452640e97fef798fa6dd.worker.js:33583:7)\n   at Jbig2Stream.prototype.readBlock (http://localhost:3000/452640e97fef798fa6dd.worker.js:31791:5)\n   at DecodeStream_getBytes (http://localhost:3000/452640e97fef798fa6dd.worker.js:4677:11)\n   at buildPaintImageXObject (http://localhost:3000/452640e97fef798fa6dd.worker.js:35934:9)\n   at Anonymous function (http://localhost:3000/452640e97fef798fa6dd.worker.js:36429:19)\n   at Promise (http://localhost:3000/452640e97fef798fa6dd.worker.js:27055:7)"

**Comment by timvandermeij** [comment]
For PDF.js 2.0 we rely on `Uint8ClampedArray` being provided by the browser. According to https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray it should be supported since IE10, so I'm not sure why you're getting this. We had a polyfill, but since PDF.js 2.0 requires `Uint8ClampedArray` to be present natively, it was removed in https://github.com/mozilla/pdf.js/commit/2dbd3f260373bac29b44aecff12ed4dd0d6ba90b#diff-4d39e8c9bedccb5801357f6c1cb2cbf5. You could try to add that back, but I would suggest to see if some other library is perhaps also polyfilling/messing with `Uint8ClampedArray`.

**Comment by Snuffleupagus** [comment]
> Browser: IE11 with IE10 compatibility Mode

In addition to https://github.com/mozilla/pdf.js/issues/9970#issuecomment-411569193: As clearly stated in the FAQ, see https://github.com/mozilla/pdf.js/wiki/Frequently-Asked-Questions#faq-support, IE10 is now *explicitly* unsupported.
