### ISSUE TITLE
Implementation with example in Angular 4

### ISSUE THREAD

**Issue by sai2812** [mozilla/pdf.js#9981]
Here I get base64 data and i am converting it into blob and passing it to viewer.html .....
can anyone help me how to implment in angular2/4 and pass data to viewer.js or html

import { Component, Input, Output } from '@angular/core';
import { Router, ActivatedRoute, Params } from '@angular/router';

import * as pdfjsLib from 'assets/js/build/pdf.js'
import * as pdfjsLibWorkers from 'assets/js/build/pdf.worker.js'
import * as viewer from 'assets/js/web/viewer.js'

@Component({
    template: `<script src="assets/js/build/pdf.js"></script>
    <script src="assets/js/web/viewer.js"></script>
    `
   
})
export class PrintPolicyComponent  {

     this.printPolicyService.printSearchResult(JSON.stringify(json)).subscribe(printpolicyResults => {
                if (printpolicyResults) {
              var pdfData = atob(printpolicyResults.toString());
                        var url = URL.createObjectURL(blob);
                        
                        var viewerUrl = 'assets/js/web/viewer.html?file=' +url;  
                }
     })

     
}

**Comment by timvandermeij** [comment]
The issue tracker is only for filing bugs in PDF.js. We cannot provide support for custom Angular (or other library) implementations; please use e.g., StackOverflow or related websites for such questions. We can only recommend to use the viewer components (https://github.com/mozilla/pdf.js/tree/master/examples/components) to build a custom viewer. Otherwise, we have more examples (https://github.com/mozilla/pdf.js/blob/master/examples/learning/helloworld64.html) that show how to load a PDF file from e.g., a base64 encoded blob.
