### ISSUE TITLE
PDF form fields out of place

### ISSUE THREAD

**Issue by kyangy** [mozilla/pdf.js#9993]
Attach (recommended) or Link to PDF file here:
[sagaftra.pdf](https://github.com/mozilla/pdf.js/files/2304128/sagaftra.pdf)

Configuration:
- Web browser and its version: Chrome/Firefox
- Operating system and its version: OSX
- PDF.js version: 
- Is a browser extension: No

Steps to reproduce the problem:
1. Load the pdf to generate annotations and render interactive forms
2. Notice that the pdf does get generated but the input fields are out of place below the pdf

What is the expected behavior? (add screenshot)
<img width="1439" alt="screen shot 2018-08-20 at 3 30 35 pm" src="https://user-images.githubusercontent.com/9537888/44370208-0a4e1200-a48e-11e8-9cb0-cdc9a1b7e1c1.png">

What went wrong? (add screenshot)
<img width="1440" alt="screen shot 2018-08-20 at 3 30 44 pm" src="https://user-images.githubusercontent.com/9537888/44370207-091ce500-a48e-11e8-9f9e-ca4faa216234.png">

**Comment by Snuffleupagus** [comment]
The issue is (currently) missing key pieces of information as requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; e.g.

> PDF.js version:

That shouldn't be left blank, since the version number is necessary information.

> Steps to reproduce the problem:
> 
>     Load the pdf to generate annotations and render interactive forms
>     Notice that the pdf does get generated but the input fields are out of place below the pdf

The above isn't nearly enough information to go on, especially since the screen-shots indicate that you're using a custom implementation of the PDF.js library. *Please note:* It works fine in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) with the `renderInteractiveForms` preference set.

Most likely, the explanation for the issue is that you didn't include the necessary CSS file (`pdf_viewer.css`) in order for this to work. However, without access to a working example (as asked for in the ISSUE_TEMPLATE) it's more-or-less impossible to help.

**Comment by Snuffleupagus** [comment]
The issue is (currently) missing key pieces of information as requested in https://github.com/mozilla/pdf.js/blob/master/.github/ISSUE_TEMPLATE.md; e.g.

> PDF.js version:

That shouldn't be left blank, since the version number is necessary information.

> Steps to reproduce the problem:
> 
>     Load the pdf to generate annotations and render interactive forms
>     Notice that the pdf does get generated but the input fields are out of place below the pdf

The above isn't nearly enough information to go on, especially since the screen-shots indicate that you're using a custom implementation of the PDF.js library. *Please note:* It works fine in the [default viewer](https://mozilla.github.io/pdf.js/web/viewer.html) with the `renderInteractiveForms` preference set.

Most likely, the explanation for the issue is that you didn't include the necessary CSS file (`pdf_viewer.css`) for this to work correctly. However, without access to a working example (as asked for in the ISSUE_TEMPLATE) it's more-or-less impossible to help.

**Comment by kyangy** [comment]
@Snuffleupagus Thanks, I'm currently using the `pdfjs-dist` generic library and the css is not being loaded

**Comment by kyangy** [comment]
@Snuffleupagus After the interactive form is generated, what other purposes are there after the user finishes inputting all the fields? Looking around the issues, it seems like there is no implementation on grabbing the values from the inputs or even saving to pdf.

**Comment by timvandermeij** [comment]
It's not implemented yet; we have another tracking issue open for that, that's why it's disabled by default.
