### ISSUE TITLE
 Base64 online preview pdf content does not display

### ISSUE THREAD

**Issue by 4o4-Not-Found** [mozilla/pdf.js#9994]
Attach (recommended) or Link to PDF file here:
[20180820150932180_189.pdf](https://github.com/mozilla/pdf.js/files/2304492/20180820150932180_189.pdf)

Configuration:
- Web browser and its version:
  Google Chrome(68.0.3440.106)
- Operating system and its version:
  Windows 10 Pro
- PDF.js version:
  v1.10.88 (build: c62a1938)

Steps to reproduce the problem:
When I submit the form on the page, the background data is mapped to the PDF template in the background. The PDF template is created by Acrobat DC Por table. After the completion, the PDF is converted to the Base64 encoding format, and there is no problem here. Passed to the front desk for online preview via pdf.js, but the form content is not displayed at this time.
![image](https://user-images.githubusercontent.com/28617648/44376460-48e5da00-a52b-11e8-884c-54e521eb027a.png)
![image](https://user-images.githubusercontent.com/28617648/44376471-58fdb980-a52b-11e8-838f-4bbfdc1766de.png)

this is the PDF template
[道路挖掘夜间施工备案样表PDF模板.pdf](https://github.com/mozilla/pdf.js/files/2304512/PDF.pdf)

**Comment by timvandermeij** [comment]
Fixed in the most recent version of PDF.js since it renders just fine on https://mozilla.github.io/pdf.js/web/viewer.html. Note that not all fonts in this PDF file are embedded, so the text will be rendered differently depending on OS and reader. For example, Evince and PDF.js already render the text with a different font. Embedding fonts is highly recommended and I would suggest that you check if you can enable font embedding in your PDF generator to avoid any future issues.
